truenas/middleware

src/gui/grunt_tasks/config/concurrent.js
src/gui/grunt_tasks/develop.js

Remove references to local development option as it was not functional.

---

build/nanobsd-cfg/Files/etc/crontab

https://bugs.freenas.org/issues/9099

Fix daily db backups.

---

gui/templates/vcp/index.html
gui/vcp/forms.py
gui/vcp/models.py
gui/vcp/plugin.py
gui/vcp/urls.py
gui/vcp/utils.py
gui/vcp/views.py

Hi Jordan/Williams,
Please find changes for password and ui refresh for vCenter plugin.

Password widget and ui refresh implementation for vCenter plugin.

---

gui/vcp/Extensionconfig.ini.dist
gui/vcp/forms.py
gui/vcp/plugin.py
gui/vcp/urls.py
gui/vcp/vcp_locales/task_locale_en.properties
gui/vcp/views.py

Hi Jordan/William
Please find vCenter plugin changes for
- Custom Vsphere web client Task for Datastore operation.
- Event creation for Vsphere web client Alarm
- Repair feature.

vCenter plugin changes for Task, Event and Repair feature

---

gui/templates/vcp/index.html
gui/vcp/forms.py
gui/vcp/models.py
gui/vcp/utils.py

Hi William,
Pull request contains changes for Https support from vCenter plugin.

Added HTTPS support for vCenter plugin.

---

gui/vcp/forms.py

Hi William,
Please find validations for vCenter HTTPS support.

Added validation messages for vCenter HTTPS support.

---

gui/common/warden.py
gui/jails/forms.py
gui/jails/queryset.py
gui/jails/utils.py
gui/middleware/notifier.py
gui/plugins/views.py

This should fix https://bugs.freenas.org/issues/11969

Ephemeral cache for Warden.list() to avoid calling warden many times during normal browsing

---

gui/api/resources.py
gui/storage/admin.py

column added in storage section and showing the value of 'readonly' property of
ZFS.

I have added the column 'Readonly' in the volume datagrid

---

gui/services/migrations/0194_auto__add_field_ups_ups_optionsupsd.py
gui/services/models.py
src/freenas/etc/ix.rc.d/ix-ups

Added new entry in 'UPS Settings form' to add 'Auxiliary Parameters' to 'upsd.conf' and added the column in database.

Added new entry in 'UPS Settings form' to add 'Auxiliary Parameters' to 'upsd.conf'

---

gui/services/forms.py
gui/system/forms.py
gui/system/models.py

In this commit, when generating local certificate and SSH Key,
I have logged their fingerprints to the console and /var/log/messages.

Logging local certificate and SSH key fingerprint

---

gui/services/forms.py
gui/services/models.py

Changed the Services/AFP/Bind IP formfield as CIFS formfield,
now user will be able to bind the lagg Interface IP with AFP.

bug #13343 : AFP Binding Error

---

gui/services/migrations/0195_auto__add_field_nfs_nfs_srv_mountd_log__add_field_nfs_nfs_srv_statd_lo.py
gui/services/models.py
src/freenas/etc/rc.conf.local

One checkbox added for the logging of mountd and another added for statd and lockd.

Enable the logging of mountd, statd and lockd with checkbox

---

gui/jails/forms.py

In this commit, I have made code changes to raise a Validation error if a Jail dataset is created on an existing share.

BUG #15705: Seat-belt to prevent creating jail datasets on a share

---

gui/services/models.py
gui/system/models.py

In this commit, I have added a filter to allow only Certificates(.crt) and not Certificate Signing Requests(.csr) in the drop-down menus of FTP, WebDAV and System->General

BUG #16029 TLS FTP problem

---

gui/choices.py
nas_ports/dns/inadyn-mt/Makefile
nas_ports/dns/inadyn-mt/distinfo
nas_ports/dns/inadyn-mt/files/inadyn-mt.in
nas_ports/dns/inadyn-mt/files/patch-dyndns.h
nas_ports/dns/inadyn-mt/files/patch-readme.html
nas_ports/dns/inadyn-mt/pkg-descr

Adding this since we need latest version of inadyn-mt, feel free to remove when we upgrade our ports tree to a one which has this version in it.

FIX-13135:Added inadyn-mt custom port upgrading it to present latest version and Replaced older url for he.net with the latest one in choices.py

---

gui/system/forms.py

In this commit, I have added a help text for the user to understand the order in which he needs to paste the certificate chain alongwith incorporating Jatindar's changes on the same ticket.

Bug #9879: Importing a Certificate that includes the full chain causes the wrong certificate to be saved

---

gui/freeadmin/static/lib/js/freeadmin.js
gui/system/forms.py

In this commit, I have added a warning when user selects a new .system dataset.

Bug #16564: Red warning when moving .system dataset

---

gui/api/resources.py
gui/middleware/notifier.py
gui/storage/admin.py
gui/storage/forms.py
gui/storage/views.py

In this commit, I have added a field to the Dataset and Zvol forms for adding comments.

Bug #14355: Add Comment column in Storage section (for zvol and datasets)

---

src/freenas/etc/ix.rc.d/ix-proftpd

In this commit, I have raised the TLS version from default "SSLv23" to "SSLv3 TLSv1.2".

Bug #15236: Raising TLS version on FTP

---

gui/reporting/rrd.py
gui/reporting/urls.py

The geom_stat datas were already collected, this commit only show these datas on Reporting / Disk. The graph naming convention taken from the colletctd disk plugin.

Add more disk statistic graphs.

---

gui/directoryservice/forms.py
gui/directoryservice/migrations/0063_auto__add_field_activedirectory_ad_monitor_frequency__add_field_active.py
gui/directoryservice/models.py
gui/middleware/notifier.py
gui/system/alertmods/service_monitor.py
nas_ports/sysutils/tw_cli/Makefile
nas_ports/sysutils/tw_cli/files/407.status-3ware-raid.in
src/freenas/etc/ix.rc.d/ix-service_monitoring
src/freenas/usr/local/libexec/nas/service_monitor.py
src/middlewared/middlewared/client/__init__.py
src/middlewared/middlewared/logger.py
src/middlewared/middlewared/plugins/service_monitor.py

Hi,
Here is the port of service monitoring from master to stable branch.
Best,

Fix ad on branch stable

---

webui/src/app/pages/volumes/manager/disk/disk.component.ts

Fixed:  Disks icons do not show properly(CSS)

---

webui/src/app/pages/login/login.html

fix(gui): enable press "Enter" to login

---

test/README

The former location is no longer available.

Corrected location of splinter

---

gui/freeadmin/static/lib/js/freeadmin.js
gui/vm/forms.py
src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/plugins/vm.py

feat(vm): Instead of bind VNC in all IFACES, allow users to choose between bind all, or bind to an specific IPv4.
Ticket: #24884

Give options for users instead of only let VNC bind to 0.0.0.0

---

gui/network/forms.py
src/middlewared/middlewared/plugins/network.py

fix(middlewared): configure http proxy on start and on events

---

gui/freeadmin/static/lib/js/freeadmin/SupportTicket.js
gui/support/utils.py
gui/support/views.py
gui/system/alert.py
src/middlewared/middlewared/job.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/datastore.py
src/middlewared/middlewared/plugins/mail.py
src/middlewared/middlewared/plugins/notifier.py
src/middlewared/middlewared/plugins/service_monitor.py
src/middlewared/middlewared/plugins/support.py
src/middlewared/middlewared/pytest/functional/test_0075_support.py
src/middlewared/middlewared/schema.py

Middleware API to submit support tickets

---

src/middlewared/middlewared/plugins/backup.py

Ticket:	#24534
(cherry picked from commit 2b392de939085f18247f96fab129b274fbdfdd24)

fix(middlewared): backup.sync with py3k

---

gui/services/forms.py
gui/support/forms.py

run ix-loader when ALUA checkbox state changed or when FC+HA license installed

---

gui/network/forms.py

Ticket:	#25061
(cherry picked from commit 421f94fbd4578e4bc5bca4c9a0fd1e376be81ba2)

fix(gui): make sure gateway is not empty, avoiding traceback

---

gui/network/forms.py
gui/network/models.py

Fix hostname save logic

---

gui/directoryservice/models.py

Drop the 'experimental' label from AD Restart UI

---

gui/system/views.py
gui/templates/system/debug.html

https://bugs.freenas.org/issues/24449

Cannot create a debug when 1 node is down.

---

gui/api/resources.py
gui/middleware/notifier.py
gui/middleware/zfs.py
gui/storage/forms.py
gui/storage/views.py

Unify dataset creation/update in GUI/API

---

gui/system/views.py
gui/templates/system/debug.html

https://bugs.freenas.org/issues/24449

Cannot create a debug when 1 node is down. - PR to the stable U@

---

src/freenas-installer/etc/install.sh

Don't need to create swap space (again)
Ticket: #25211

Fix an issue installing TrueNAS specifically into an existing BE.

---

src/freenas-installer/etc/install.sh

Updated to catch a bug where fstab wasn't getting created on BE upgrades
Ticket: #25211

When doing TN swap / upgrades, we still need to create the fstab entry

---

gui/system/models.py

Include CSRs in cert dropdowns post they have been converted into certificates

---

gui/system/alert.py

Ticket:	#25253
(cherry picked from commit e57fc6dbccec6e4e0ec9f30e7d0d0b979a3a8388)

fix(alert): encoding issue when creating proactive support ticket

---

src/freenas/etc/rc.conf.local

Only start nfsuserd if GIDS > 16

---

gui/freeadmin/static/lib/js/freeadmin.js
gui/vm/forms.py
src/middlewared/middlewared/plugins/vm.py

Some applications such like Microsoft SQL Server, Oracle and perhaps other need it.

feature(vm/disksector): Add the capability for users to select sector size for block devices.

---

src/freenas/usr/local/libexec/nas/generate_sssd_conf.py

Ticket: #25326
(cherry picked from commit 48e2a45330f1c6b2983a9d47693ac8c7098fb4f4)

encode utf-8 auxiliary parameters

---

gui/freeadmin/static/lib/js/freeadmin.js
gui/vm/forms.py
src/middlewared/middlewared/plugins/vm.py

Add support for VNC authentication via bhyve RFB implementation.
Ticket: #23979

feat(vm): Add VNC authentication support.

---

gui/support/views.py

fix(gui): make sure customer name is a string

---

src/middlewared/middlewared/plugins/service_monitor.py

Ticket: #25337
(cherry picked from commit 83d36066929e0541b1487640c6ad8e36732c6703)

Only alert if unsuccessful

---

src/freenas/etc/ix.rc.d/ix-snmpd
src/freenas/usr/local/bin/freenas-snmp/zfs-snmp
src/freenas/usr/local/share/snmp/mibs/FREENAS-MIB.txt

registration.
https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers
Ticket: #50536

Update the SNMP enterprise numbers we use to our new IANA

---

gui/choices.py
gui/freeadmin/static/lib/js/freeadmin.js
gui/services/forms.py
gui/templates/services/webdav_edit.html
src/freenas/usr/local/libexec/nas/generate_webdav_conf.py

feat(gui): Allow "No Authorization" option for WebDAV

---

src/freenas/usr/local/sbin/migrate_warden.py

I'm adding this as a PR so it can get some review before we put it in `master`.  Adding Kris as the initial reviewer as he knows Warden. He can suggest additional reviewers.

Add migration tool for warden jails to iocage ones.

---

src/freenas/etc/ix.rc.d/ix-activedirectory

Ticket: #25337
(cherry picked from commit 4b104de28faaccca7d8f789cc0c906642af58ebb)

Clear alerts if we are already joined

---

src/freenas/etc/ix.rc.d/ix-pre-samba

Ticket: #25470
(cherry picked from commit 2814ff7e8521f7a64ace0243bcc4a4bed78409f4)

Don't run any net commands before smb4.conf exists

---

src/freenas/usr/local/libexec/nas/generate_smb4_conf.py

Ticket: #24608
(cherry picked from commit 38399d3404dd037ab2fc938c34951539976d2c1d)

Setup autorid idmap correctly

---

gui/middleware/notifier.py

That may happen if a dataset mount fails (readonly parent dataset).
Ticket:	#24936
(cherry picked from commit 3086abda5e41ccbf859406d3da759947e99d1736)

fix(notifier): check if pool imported after failed "zpool import"

---

gui/common/warden.py

Ticket: #25325
(cherry picked from commit 3e42018d9122db60590c2a6479eda1e97733474e)

Stringify warden exceptions

---

src/freenas/etc/ix.rc.d/ix-activedirectory

Ticket: #25106
(cherry picked from commit 220de96193ab58c48e1b5eb8c83189c1a4f36141)

Don't disable machine account - no longer necessary

---

gui/tools/autorepl.py

Ticket:	#24405
(cherry picked from commit cd3190192bd3af6c73b9e346be59a3400889595f)

fix(repl): remove double dd (it make things slower now with pipewatcher)

---

gui/common/ssl.py
gui/system/forms.py

fix(gui): Importing an encrypted CA key fails with "incorrect passphrase"

---

gui/api/resources.py
gui/freeadmin/static/lib/js/freeadmin.js
gui/templates/vm/vncweb.html
gui/vm/admin.py
gui/vm/forms.py
gui/vm/urls.py
gui/vm/views.py
src/middlewared/middlewared/plugins/vm.py

Allow users to access guests VNC via web if enabled.

---

src/middlewared/middlewared/plugins/jail.py

Iocage integration

---

gui/system/forms.py

fix(api/middleware): Unable to change Certificate

---

gui/network/forms.py

Ticket:	#25351
(cherry picked from commit 7f7ad104e80cc36f5a2f8f245f2efaaf2b07aeac)

feat(gui): disable failover LAGG in HA

---

gui/reporting/rrd.py
gui/reporting/urls.py
gui/reporting/views.py

Closed #316 because of Jenkins checkout error
Re-Opened with shorter branch name
I'm adding a plugin to the gui reporting page which displays a graph for cpu core temperatures. The cpu temperature data is already provided as a set of rrd files by the freenas os - so why not visualize these, right?

feat(gui): add reporting plugin for cpu temperature(s)

---

gui/system/alert.py

Ticket:	#25395
(cherry picked from commit 9ae06d6944001beab93b5c3235711b156f5bdcc4)

fix(alert): allow alerts to run on licensed HA but unconfigured

---

src/middlewared/middlewared/etc_files/local/openldap/ldap.conf

ad is a dict, specify certfile as key

---

src/middlewared/middlewared/plugins/pool.py

Fix mount_msdosfs: /dev/da1s7: Disk too big, try '-o large' mount option

---

src/freenas/usr/local/libexec/nas/generate_smb4_conf.py

And still maintaining the right modules order where appropriate. That should address #25982

Allow catia to be added independently from fruit

---

gui/choices.py
gui/freeadmin/static/lib/js/freeadmin.js
gui/freeadmin/static/lib/js/freeadmin/CloudSync.js
gui/freeadmin/static/lib/js/freeadmin/templates/cloudsync.html
gui/system/forms.py
gui/system/hook.py
gui/system/nav.py
gui/tasks/hook.py
gui/tasks/nav.py
gui/templates/freeadmin/generic_model_add.html
gui/templates/system/cloudcredentials_edit.html
nas_ports/freenas/py-middlewared/Makefile
src/middlewared/middlewared/plugins/backup.py

Add Cloud Sync to FreeNAS and support for Backblaze + Google Cloud Storage

---

gui/api/resources.py
gui/system/admin.py
gui/system/forms.py
gui/system/urls.py
gui/system/views.py

feat(api/middleware): Add ability to sign CSR's with Internal FreeNAS CA to GUI

---

gui/middleware/notifier.py
src/freenas/usr/local/libexec/nas/generate_smb4_conf.py

Mount system dataset on passive node

---

gui/account/forms.py

fix(api/middleware): Infinite Folder Replication

---

gui/common/ssl.py
gui/system/forms.py

fix(middleware): Traceback on certificate import

---

src/freenas/etc/ix.rc.d/ix-nginx

Ticket: #26043
I think this proposed fix works but I would like it reviewed

Add try_files to make angular cli route resolving work properly from url

---

gui/common/forms.py
gui/freeadmin/options.py
gui/middleware/client.py
gui/middleware/form.py
gui/system/forms.py
gui/system/views.py
src/middlewared/middlewared/plugins/bootenv.py
src/middlewared/middlewared/pytest/functional/test_0004_bootenv.py

Implement CRUD for Boot Env and move validation to middlewared

---

src/freenas/etc/rc.conf.local
src/freenas/usr/local/etc/rc.d/smartd-daemon
src/middlewared/middlewared/plugins/service.py

fix(smartd): Replace smartd rc script with smartd-daemon that forks immediately

---

src/freenas/etc/ix.rc.d/ix-collectd

Store RRD data in "localhost" and symlink it from "hostname" instead of doing
it the other way.
Ticket: #26030

Fix RRD graphs being wiped after hostname change

---

gui/common/ssl.py

fix(middleware): Creating internal certificate fails

---

src/middlewared/middlewared/job.py
src/middlewared/middlewared/plugins/jail.py

This is waiting on one other small fix from William to add a wait_sync call

(jail) Fix create call

---

gui/services/forms.py
src/middlewared/middlewared/plugins/ftp.py
src/middlewared/middlewared/plugins/tftp.py

Services:TFTP - GUI to Middlewared

---

src/middlewared/middlewared/async_validators.py
src/middlewared/middlewared/plugins/afp.py
src/middlewared/middlewared/plugins/ftp.py
src/middlewared/middlewared/plugins/tftp.py

fix(middleware): Add check_path_resides_within_volume validator

---

gui/api/resources.py
gui/middleware/notifier.py
gui/middleware/zfs.py
gui/templates/storage/snapshots.html

rm(gui): remove `replication` column in Snapshots UI

---

src/middlewared/middlewared/plugins/unauthorized_reboot_alert.py

Ticket: #23361
Please note that clean middlewared shutdown was already implemented in 5b2574dccb13dd364a3f960ceb2d5926237030a5

feat(middleware): Unauthorized reboot e-mail alert

---

gui/system/forms.py

fix(django/legacy): Traceback when signing a CSR

---

gui/freeadmin/static/lib/js/freeadmin/CloudSync.js
gui/freeadmin/static/lib/js/freeadmin/templates/cloudsync.html
src/middlewared/middlewared/plugins/backup.py

Server Side Encryption to Amazon S3

---

src/middlewared/middlewared/plugins/jail.py

This will return a list of what RELEASEs are available locally or remotely, which plugins are available locally and remotely and which templates are available locally.

Add listing resources to API

---

gui/system/forms.py

fix(api/middleware): Cron is not restarted after timezone change

---

docs/api/resources/system.rst

fix(api/middleware): Added "stg_guicertificate" to system docs

---

gui/system/forms.py
src/middlewared/middlewared/plugins/boot.py

Option to expand disk on boot atach

---

src/middlewared/middlewared/plugins/jail.py

This was missing some needed logic.

(jail): Fix updating to the latest patch level

---

docs/api/resources/directoryservice.rst
gui/system/forms.py
src/middlewared/middlewared/plugins/boot.py

@b-a-t asked my help with this and it turned out to be deeply buried malfunction with a simple, but hackish solution... What to you think?
API response diffs:
https://gist.github.com/themylogin/b9fc2a0980152b5e3e48a9626843ed85/revisions#diff-39859e34161f0cb6f5f50974282a2593
https://gist.github.com/themylogin/13a028999d9ddd0767dc622dffe0db76/revisions#diff-39859e34161f0cb6f5f50974282a2593

Dojo model form resource mixin + resolve ticket: #24127

---

src/middlewared/middlewared/client/client.py
src/middlewared/middlewared/event.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/filesystem.py
src/middlewared/middlewared/utils.py

Implement event source feature with file get and watch source

---

gui/freeadmin/static/lib/js/freeadmin/Update.js

fix(gui): dont show update from 11-STABLE to 11.1-PRERELEASE as downgrade

---

gui/system/forms.py

fix(gui): do not strip motd field

---

src/middlewared/middlewared/plugins/vmware.py

feat(middlewared/vmware): catch generic exceptions

---

src/middlewared/middlewared/plugins/pool.py

feat(middlewared/pool): send email when scrub finishes

---

src/middlewared/middlewared/plugins/jail.py

This fixes the issues iX's network is facing with ftp.

(jail): Now lists over HTTP and uses iocage's API

---

src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/plugins/zfs.py

Middlewared events for scrub/resilver

---

src/freenas-installer/etc/install.sh

Really make 8GB the minimum RAM

---

src/freenas/usr/local/libexec/freenas-debug/include.sh

fix(src): syntax error in freenas-debug

---

src/middlewared/middlewared/plugins/device.py

fix(middleware): Fix middleware hang on devd stop

---

src/middlewared/middlewared/plugins/boot.py
src/middlewared/middlewared/plugins/disk.py
src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/plugins/zfs.py

Middleware methods required by the Boot UI

---

gui/api/resources.py

fix(api): do not traceback if volume is locked

---

src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/device.py

fix(middlewared/device): a devd message may contain multiple entries

---

src/middlewared/middlewared/plugins/update.py

fix(middleware): Proper update.update progress reporting

---

src/middlewared/middlewared/plugins/ipmi.py

fix(middlewared/ipmi): no need to quote, no longer using shell

---

src/middlewared/middlewared/plugins/zfs.py

Ticket:	#26165
(cherry picked from commit 08947f60d72dd433a621203a73f29977ebf4ad79)

fix(middlewared/zfs): sending email when scrub finishes

---

gui/choices.py

This will pervent on having multiple VLANs of same interface.
Ticket:	#25839
(cherry picked from commit 09a8d52a16db591aca15caf6c3fb983fc9def2d0)

fix(gui): count every interface on database as configured

---

gui/freeadmin/static/lib/js/freeadmin.js
gui/jails/utils.py

Proper warden error message handling

---

gui/sharing/forms.py

fix(gui): check for overlapping network on same share

---

src/middlewared/middlewared/plugins/account.py

Allow querying/setting group users members

---

src/middlewared/middlewared/plugins/pool.py

pool.download_encryption_key 

---

gui/system/forms.py
src/middlewared/middlewared/plugins/boot.py

Fix attaching boot disk matching current size

---

gui/choices.py
src/freenas/etc/netcli

Remove broken "remove" method from NICChoices and IPChoices

---

gui/middleware/form.py

fix(gui): Fix saving foreign keys in MiddlewareModelForm

---

gui/tasks/forms.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/backup.py

Pull issue with cloud sync to BackBlaze

---

gui/system/forms.py

fix(gui): Proper common clean_certificate with validation for all certificate-related forms

---

gui/storage/forms.py

fix(gui): add field prefix to show error in the right place

---

src/freenas/etc/ix.rc.d/ix-proftpd

fix(proftpd): Add TLSCertificateChainFile to proftpd config if certificate contains multiple parts

---

gui/network/forms.py

fix(gui): only create virtual interface if it doesnt exist yet

---

gui/freeadmin/forms.py
gui/sharing/forms.py

fix(gui): Allow IEC-suffixed input for afp_timemachine_quota

---

src/freenas/etc/ix.rc.d/ix-proftpd

 fix(proftpd): Add TLSCertificateChainFile to proftpd config if certificate contains multiple parts

---

gui/api/resources.py
gui/directoryservice/admin.py

Ticket: #26330
(cherry picked from commit abb0ea7be8e09d4a66aac5413902a8a3064e96e0)

Add REST API endpoint for KerberosPrincipal

---

gui/choices.py
gui/freeadmin/static/lib/js/freeadmin.js
gui/freeadmin/static/lib/js/freeadmin/CloudSync.js
gui/freeadmin/static/lib/js/freeadmin/templates/cloudsync.html
gui/system/forms.py
nas_ports/freenas/py-middlewared/Makefile
src/middlewared/middlewared/plugins/backup.py

Ticket: #26471
DEPENDS: https://github.com/freenas/ports/tree/FIX-26471

Add support for CloudSync Azure backups

---

gui/network/forms.py

fix(gui): additional domains parsing

---

docs/api/resources/storage.rst

fix(api): document a few options in API

---

src/freenas/usr/local/bin/freenas-snmp/snmpresponse.py

(cherry picked from commit cd8e872d17f7f507c500512eba0a636eed587e5b)

2to3 fix for snmpresponse

---

gui/network/forms.py

fix(gui): Document how to set MTU option for LAGG interfaces

---

src/freenas/etc/ix.rc.d/ix-inetd

fix(tftp): Make tftp onestart work

---

src/middlewared/middlewared/plugins/jail.py

This is required for bru-server curerntly

(jail): Allow accepting license for plugins

---

src/middlewared/middlewared/plugins/boot.py

fix(middlewared/boot): properly install grub

---

src/freenas/etc/rc.conf.local
src/middlewared/middlewared/plugins/service.py

fix(nfs): be more consistent about NFSv3 ownership model

---

gui/reporting/rrd.py

Yes, there will be repeated colors. There is a more elegant solution but
I don't plan on wasting more time than we need here since this is just a
stop gap solution until new UI is ready.
Ticket:	#26661

fix(gui/reporting): make sure there are colors for all cores

---

gui/api/resources.py
gui/choices.py
gui/middleware/zfs.py
gui/storage/forms.py

feat(gui): add `exec` option to dataset

---

src/middlewared/middlewared/plugins/vm.py

fix(middlewared/vm): Make random_mac method public. It will be used in the new interface to generate a random mac for a given nic.
Note: It won't be fixed in the OLD UI as it will be replaced soon.
Ticket: #26559

Make random_mac method public.

---

gui/storage/nav.py
gui/system/hook.py
gui/system/nav.py

fix(gui): Move View Enclosure to System

---

src/middlewared/middlewared/job.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/backup.py
src/middlewared/middlewared/plugins/boot.py
src/middlewared/middlewared/plugins/config.py
src/middlewared/middlewared/plugins/datastore.py
src/middlewared/middlewared/plugins/device.py
src/middlewared/middlewared/plugins/disk.py
src/middlewared/middlewared/plugins/etc.py
src/middlewared/middlewared/plugins/mdns.py
src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/plugins/service.py
src/middlewared/middlewared/plugins/service_monitor.py
src/middlewared/middlewared/plugins/support.py
src/middlewared/middlewared/plugins/update.py
src/middlewared/middlewared/plugins/vm.py
src/middlewared/middlewared/plugins/zfs.py
src/middlewared/middlewared/service.py

Run all libzfs things in a single thread

---

src/middlewared/middlewared/plugins/jail.py

This will correctly identify them as null.

Replace the "-" in plugin response

---

gui/storage/forms.py

fix(gui): run `done` hook on zfs volume manager

---

src/middlewared/middlewared/plugins/vm.py

fix(middlewared/vm): Make guest vm name be unique, now we combine the guest name with its id number.
Ticket: #26365

[Master] Make guest vm name be unique: ticket: #26365

---

src/middlewared/middlewared/plugins/vm.py

fix(middlewared/vm): Make guest vm name be unique, now we combine the guest name with its id number.
Ticket: #26365

[stable] Make guest vm name be unique: ticket: #26365

---

gui/freeadmin/templatetags/freeadmin.py

feat(gui): fieldsets form attribute for admin_form renderer

---

src/freenas/etc/find_alias_for_smtplib.py

feat(mail): do no try to send email if no alias has been found

---

gui/system/views.py
gui/templates/system/system_info.html
src/middlewared/middlewared/client/ejson.py
src/middlewared/middlewared/plugins/system.py

 fix(gui): Add Status View for Contracts

---

gui/system/views.py
gui/templates/system/system_info.html
src/middlewared/middlewared/client/ejson.py
src/middlewared/middlewared/plugins/system.py

fix(gui): Add Status View for Contracts

---

src/middlewared/middlewared/service.py

(cherry picked from commit 117ef498b4ed87bfaa6cb9fc3f52ed27c96a0be0)

fix(middlewared): do not serialize `thread_pool` config option

---

gui/storage/views.py
gui/templates/freeadmin/generic_model_confirm.html

Ticket:	#25748
(cherry picked from commit 12d2c713d7e7c8d40bf149ed007d429ffbbb8941)

feat(gui): confirm once again of destroy/detach for HA

---

src/freenas/etc/netcli

There are a number of ways we could do this better but it is not worth
the effort. We really need a netcli rewrite using middlewared.
Ticket:	#25526
(cherry picked from commit c17ecd95c47fffc89c02c89ed467bee7834ee4fd)

fix(netcli): basic validation of VIP

---

gui/system/forms.py

Validate that first certificate in chain matches private key.
Ticket: #26281

fix(gui): Validate certificate chain

---

gui/middleware/notifier.py

fix(gui): do not destroy geli metadata on failed encrypted import

---

gui/vm/forms.py

[MASTER] fix(OLD_UI/vm): Remove 0.0.0.0 from VNC option.

---

gui/vm/forms.py

[STABLE] fix(OLD_UI/vm): Remove 0.0.0.0 from VNC option.

---

gui/storage/models.py
src/middlewared/middlewared/plugins/vm.py

[MASTER] Prior to destroy a volume we need to stop all guest vms attached to it or otherwise the volume is busy and we can't perform the action.

---

gui/middleware/notifier.py

Ticket:	#26797
(cherry picked from commit ba13c6af01b7ad1e3de5b9c73f9765730ecbebcb)

fix(notifier): revert piece of code removed by mistake in c5cc98f3

---

gui/freeadmin/static/lib/js/freeadmin.js

fix(gui): Fix regression in 6c5f27232ed68c4aac16dd3a6a8fbf8a524fb7ea

---

gui/freeadmin/static/lib/js/alert.js
gui/freeadmin/static/lib/js/freeadmin/FCPorts.js
gui/freeadmin/static/lib/js/freeadmin/WizardShares.js
gui/freeadmin/static/lib/js/freeadmin/form/PathSelector.js
gui/freeadmin/static/lib/js/top.js

fix(gui): a few missing path changes for the legacy UI

---

gui/freeadmin/static/lib/js/freeadmin.js

Broken in https://github.com/freenas/freenas/pull/485
@william-gr maybe some other code parts matching this pattern were missed too?

fix(gui): Fix "Would you like to enable this service?" dialog

---

src/freenas-installer/etc/install.sh

get passwords with whitespace properly set at install time.
Ticket: #24740

Go through and do some proper quoting for passwords so we can

---

src/middlewared/middlewared/plugins/zfs.py

Ticket:	#26432
(cherry picked from commit c14a1e4bbc417b26f1d72f148fe652c8550c4dc3)

feat(middlewared/zfs): add `zfs.pool.query` method

---

src/middlewared/middlewared/plugins/system.py

Ticket:	#24452
(cherry picked from commit 6a1cfa5e4e9e90341e117156c902d19f4ed0e060)

feat(middlewared/system): add system_serial(_ha)? to `license`

---

src/middlewared/middlewared/plugins/zfs.py

Ticket:	#26432
(cherry picked from commit 29bbf9b03971b87daa79824e535a2f6de145a0bc)

fix(middlewared/zfs): getting pool using `id`

---

src/middlewared/middlewared/plugins/mdns.py

Ticket:	#26936
(cherry picked from commit 37fb51397e7e85621b26e33fca790790f24615ec)

fix(middlewared/mdns): do not mix native threads locks and coroutines

---

gui/middleware/notifier.py

fix(notifier): make sure disk obj exists

---

src/middlewared/middlewared/plugins/unauthorized_reboot_alert.py

fix(middlewared/reboot): make sure dirname exists

---

gui/contrib/IPAddressField.py
gui/network/models.py
src/middlewared/middlewared/plugins/network.py

fix(network): Allow IPv6 addresses with zone indexes for IPv6 Default Gateway

---

src/freenas/root/.login
src/freenas/root/.warning
src/freenas/root/.zlogin
src/freenas/root/.zshrc

These will be useful since zsh is now the default.

feat(zsh): add default startup files

---

src/freenas/etc/rc.conf

fix(jails): Allow boot="on" in the GUI to mean something

---

src/middlewared/middlewared/plugins/vm.py

[MASTER] fix(middlewared/vm): Add quotes around rancher password to avoid issues when users use special characters such like '&'.

---

src/middlewared/middlewared/plugins/vm.py

[STABLE] fix(middlewared/vm): Add quotes around rancher password to avoid issues when users use special characters such like '&'.

---

gui/system/forms.py

Merge requested here: https://redmine.ixsystems.com/issues/23197#change-152635
Ticket: #23197

Proper common clean_certificate with validation for all certificate-related forms

---

src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/schema.py

Add user facing dataset/zvol middleware methods

---

gui/templates/system/reboot.html
gui/templates/system/shutdown.html

fix(gui): reboot and shutdown after /legacy/ url change

---

src/middlewared/middlewared/plugins/service_monitor.py

Just that all of them failed. Must be an ERROR really.

Don't keep stack of failed attempts to restore the service.

---

src/middlewared/middlewared/plugins/mdns.py

Ticket: #26531
(cherry picked from commit 7209838040c3b520116063b4a199e71ca352274c)

wait for mdnsd to start

---

src/freenas/usr/local/etc/consul.d/freenas.json

Fix freenas.json for newer versions of consul

---

src/middlewared/middlewared/plugins/disk.py

fix(middlewared/disk): avoid traceback if limit of mirror is reached

---

src/middlewared/middlewared/plugins/sysdataset.py

fix(middlewared/sysds): fix destroying source datasets

---

gui/system/forms.py

Ticket:	#27099
(cherry picked from commit ad5063f63dedc1fa156e9a8b14b800865b64ac7f)

fix(gui): make sure keyfile exists

---

gui/storage/forms.py
gui/system/forms.py

Ticket:	#27128
(cherry picked from commit 73d6b8293a2784ea294c5151d9738ec61fbda96f)

fix(gui): do not destroy volume on failed wizard form

---

src/middlewared/middlewared/plugins/jail.py

This allows the list action to actually list.

(jail): Return a dict with fstab list, and add REPLACE.

---

src/freenas/etc/rc.conf.local

(cherry picked from commit 092300a1a266aee8db7a4528b6dbd49384603072)

Replace abandoned AIC platform support with new ECHOWARP.

---

src/freenas/etc/rc.conf.local

fix(ha): skip interfaces configuration if mode is MANUAL

---

src/freenas/usr/local/etc/consul.d/freenas.json

Fix freenas.json for newer versions of consul (#566)

---

src/middlewared/middlewared/etc_files/dhclient.conf
src/middlewared/middlewared/etc_files/local/nss_ldap.conf
src/middlewared/middlewared/etc_files/local/openldap/ldap.conf
src/middlewared/middlewared/etc_files/master.passwd
src/middlewared/middlewared/etc_files/nsswitch.conf
src/middlewared/middlewared/etc_files/pam.d/ftp
src/middlewared/middlewared/etc_files/pam.d/ftpd
src/middlewared/middlewared/etc_files/pam.d/login
src/middlewared/middlewared/etc_files/pam.d/netatalk
src/middlewared/middlewared/etc_files/pam.d/samba
src/middlewared/middlewared/etc_files/pam.d/sshd
src/middlewared/middlewared/etc_files/pam.d/su
src/middlewared/middlewared/etc_files/pam.d/sudo
src/middlewared/middlewared/plugins/etc.py

While I'm here replace middleware client with local middleware
`call_sync` calls.
Ticket:	#27271

fix(middlewared/etc): run all mako code within a thread

---

gui/templates/services/netdata.html

Ticket:	#27299
(cherry picked from commit af6acb718221296badc81442551c0b1d7ca59744)

fix(gui): link to netdata

---

docs/api/resources/system.rst

feat(api): add example for /system/update/check/

---

gui/freeadmin/static/lib/js/freeadmin.js
gui/freeadmin/static/lib/js/freeadmin/Middleware.js

fix(gui): make it work on IE11 again

---

src/middlewared/middlewared/plugins/jail.py

We already have jobs here, the logging in the API is superflous.
Ticket: 23706

(jail) Silence fetching to logs

---

src/middlewared/middlewared/gdb.py
src/middlewared/setup.py

Script to try to download debug symbols and run gdb on running
middlewared process to help debug issues.
Ticket:	#27325

feat(middlewared): add `midgdb` script

---

docs/api/resources/system.rst
gui/api/resources.py
gui/templates/system/settings_edit.html
src/freenas/etc/netcli

Rename "Factory Restore" to "Reset Configuration to Defaults"

---

src/freenas/etc/netcli

fix(netcli): filter interface from IPv6

---

src/middlewared/middlewared/plugins/disk.py

fix(middlewared/disk): stop when max swap number is reached

---

src/middlewared/middlewared/plugins/zfs.py

fix(middlewared/zfs): finding vdev by guid as str

---

gui/api/resources.py
gui/storage/admin.py

fix(gui): do not show Wipe button for used disks

---

docs/api/resources/account.rst

fix(api): note it only retrieves/sets auxiliary groups

---

docs/api/resources/account.rst

fix(api): note bsdusr_attributes cannot be set

---

gui/reporting/rrd.py

There is separate commit to collectd port to make it account one.
Ticket:	#27356

Replace "Cache" memory reporting with new "Laundry" in legacy UI.

---

docs/api/resources/network.rst
gui/api/resources.py

feat(api): add doc for lagg interface members

---

gui/freeadmin/static/lib/js/freeadmin/VolumeManager.js

Unless changing number of disks.
Ticket:	#26586

fix(gui): do not switch away from select vdev type

---

src/middlewared/middlewared/plugins/disk.py
src/middlewared/middlewared/plugins/pool.py

feat(middleware): pool.get_disks_for_import

---

src/middlewared/middlewared/plugins/pool.py

fix(middleawared/pool): mount created dataset and fix call to query

---

gui/system/forms.py

Also fix certificate serial number being always the same
Ticket: #27407

fix(cert): set proper certificate expire time when signing CSR

---

gui/freeadmin/static/lib/js/freeadmin/CloudSync.js
src/middlewared/middlewared/plugins/backup.py

fix(gui): Properly report cloud sync credentials being invalid

---

gui/services/forms.py
src/middlewared/middlewared/plugins/s3.py
src/middlewared/middlewared/plugins/service.py

feat(middlewared/s3): move s3 from django to middlewared

---

src/freenas/usr/local/etc/consul.d/freenas.json

[STABLE] Disable consul update check.

---

src/freenas/usr/local/etc/consul.d/freenas.json

[MASTER] Disable consul update check.

---

src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh

squelch replication/snaphot noise; absolve me of pwd sins

---

src/middlewared/middlewared/plugins/vm.py

[MASTER] -  Update RancherOS to 1.1.2.

---

src/middlewared/middlewared/plugins/vm.py

[STABLE] Update RancherOS to 1.1.2.

---

gui/network/forms.py
gui/network/models.py

fix(gui): sync nameservers if additional domains has changed

---

src/middlewared/middlewared/client/client.py

feat(middlewared/client): retry in case of EADDRINUSE

---

gui/middleware/notifier.py
gui/storage/forms.py

fix(gui): there is no reason to inherit mountpoint on every unlock

---

src/middlewared/middlewared/client/client.py

fix(middlewared): make sure to raise last failed attempt

---

src/middlewared/middlewared/plugins/account.py

fix(middlewared/account): .ssh permission on user create

---

src/middlewared/middlewared/plugins/account.py

This way a client can set general purpose attribute keys without having
to worry about preserving other keys with `user.update`.
Ticket:	#27608

feat(middlewared/account): add `user.set_attribute`

---

gui/account/views.py

fix(gui): do not auto-fill root account at login ui prompt

---

gui/network/migrations/0007_globalconfiguration_gc_hostname_virtual.py

11.0-U6 had a migration out of order which means we need to restore
virtual hostname.
Ticket:	#27607

fix(gui): modify existing migartion to get the value from sentinel file

---

src/middlewared/middlewared/plugins/zfs.py

Just an API enhancement - maybe someone also needs a defer snapshot removal.

Added: Snapshot removal option to defer snapshot removal + simplified logic

---

gui/system/forms.py

fix(ha): fallback to hasycnd on manual update

---

src/freenas/etc/netcli

fix(netcli): validate vlanX in netcli

---

src/middlewared/middlewared/plugins/account.py

feat(middlewared/account): add `user.pop_attribute`

---

gui/system/forms.py

Clarify "use all disk space" wording

---

src/middlewared/middlewared/plugins/network.py

Add `network.general.summary` call

---

gui/templates/freeadmin/generic_form.html
gui/templates/storage/volume_detach.html

fix(ha): detach volume on active HA

---

gui/middleware/client.py

(cherry picked from commit f2376226da7997043b6c6b41d26108907b55a6c1)

fix(gui): race condition on django using middleware client

---

src/middlewared/middlewared/plugins/account.py

fix(middlewared/account): chown new dir

---

docs/api/resources/storage.rst
gui/api/resources.py

feat(api): document volume rekey

---

src/freenas/etc/netcli

PendingUpdates to PendingUpdatesChanges(), but also add in some
status callbacks so it doesn't look like it's hung.

Fix the netcli update method.  Primarily by fixing the use of

---

docs/api/resources/storage.rst
gui/api/resources.py

I'm not strong with naming things so any sugesstions are welcome :)

Encrypted Volumes API (Create Passphrase) #27649

---

src/middlewared/middlewared/plugins/service.py

fix(dyndns): Fix ix-inadyn not being called on service update

---

gui/account/views.py
gui/common/system.py
gui/freeadmin/site.py
gui/templates/footer.html

fix(gui): Bump the year! "FreeNAS® © 2017 - iXsystems, Inc. - 11.1-U1"

---

gui/plugins/forms.py

fix(gui): Remove dead link to pcbsd.org

---

src/freenas/etc/ix.rc.d/ix-bsdloader

since this is replaced by /conf/base/etc/fstab (which still has grub)

Fix a bug after upgrade, we don't want to directly edit /etc/fstab

---

src/freenas/usr/local/etc/consul-checks/freenas_health.sh

fix consul message flood if notifier.get_alerts outputs an empty line

---

src/freenas/etc/ix.rc.d/ix-snmpd

fix(snmp): Fix passing multiline SNMP options

---

gui/freeadmin/middleware.py
gui/settings.py

feat(gui): Authenticate API calls using Authorization: Token header

---

src/middlewared/middlewared/main.py

Should bind to localhost
Ticket: #28031

fix(API / Middleware):Fix middlewared bind to 0.0.0.0

---

src/middlewared/middlewared/main.py

Should bind to localhost 
Ticket: #28031

fix(API / Middleware):Fix middlewared binding to 0.0.0.0 

---

src/freenas/etc/ix.rc.d/ix-update

Introduced in e62a54720508add55ecd533f73c5f6a86b0a10ee
Ticket: #28074

fix(update): Fix out of order migrations

---

src/freenas/etc/ix.rc.d/ix-update

fix(update): Fix sqlite3: not found

---

gui/templates/500_freenas.html

[STABLE] Fix: hide values of POST variables that have 'password' in their name

---

gui/network/forms.py

Kick NFS services when virtual hostname changes

---

gui/system/utils.py

Ticket:	#28174
(cherry picked from commit 7bf0d2076fddbf14cd54425b3fcd48ce3b5aa684)

fix(debug): getting standby debug file

---

src/middlewared/middlewared/plugins/update.py

Ticket:	#28187
(cherry picked from commit f84b8ad8dc9e218fd4a5e6f3f0fec92f0d57bdab)

fix(update): new update email notification

---

gui/freeadmin/static/lib/js/freeadmin.js

fix(gui): logout url

---

gui/templates/registration/login.html

fix(gui): focus on username in login page

---

gui/storage/admin.py

fix(gui): do not show Enclosure Slot in Disk View

---

gui/storage/views.py

Ticket:	#27697
(cherry picked from commit 16df2a510d7d8ad12d1110a0c1b98dd1d5c7a96b)

fix(ha): clear key on standby node when pool is locked

---

gui/system/forms.py
gui/system/urls.py
gui/system/views.py
gui/templates/system/bootenv_pool_attach.html
src/middlewared/middlewared/plugins/boot.py

fix(boot): Turn boot.attach into a job

---

gui/services/forms.py

fix(gui): Hide UPS monitor password

---

gui/network/admin.py

feat(gui): warn before removing last HA critical interface

---

src/freenas/etc/rc.conf.local
src/middlewared/middlewared/plugins/service.py

Cherry pick back into 11.1-stable
Ticket: #28105

Conform to RFC-7530 when using NFSv3 UID-GIDs with NFSv4 stable 28105

---

gui/templates/system/email_edit.html

fix(gui): Change Email button no longer exists

---

src/autotune/files/autotune.py

(cherry picked from commit 80aaf04a1b7d3a6b5befc7d01f74148e39c3ea2d)

Fix rounding error

---

src/middlewared/middlewared/plugins/disk.py

fix(middlewared/disk): only run savecore in unused partitions

---

src/freenas/usr/local/libexec/nas/generate_afpd_conf.py

(cherry picked from commit 83ae3f7ee446aefa26789470a825f12dada7469d)
Signed-off-by: Timur I. Bakeyev <timur@iXsystems.com>

Enable providing afpstats via DBus interface.

---

src/middlewared/middlewared/job_process.py

Ticket:	#27739
(cherry picked from commit a35e4dc03b44bbe8c78dcd1f5ad47d282377a0bd)

fix(middlewared): calling job with process=True

---

src/middlewared/middlewared/plugins/sysdataset.py

Ticket:	#28125
(cherry picked from commit d1fcdf6a150525135ea241141b448158d2627dd6)

fix(ha): make sure uuid always exists

---

src/freenas/etc/netcli

Remove System Update from netcli

---

src/freenas/etc/ix.rc.d/ix-smartd

https://redmine.ixsystems.com/issues/15534
This patch is a temporary fix to the nvme issue in the bug

Patch to fix smartd nvme issue with 11.1U1 issues/15534

---

gui/templates/system/system_info.html
src/middlewared/middlewared/plugins/system.py

Display System Serial and System Product in FreeNAS when using hardware from iX.

---

src/freenas/etc/netcli

Fix spelling errors

---

gui/templates/menubar.html

Location change of the PDF version of the user guide - fix naming convention.

---

nas_ports/freenas/freenas-docs/Makefile

Fix the TrueNAS PDF generation since it needs a few other

---

gui/api/resources.py
gui/services/forms.py
gui/services/models.py

fix(gui): show node IPs in select box and datagrid for ALUA

---

Jenkinsfile

This is for testing purposes now. Please do not commit until I can refine.

Add new Jenkinsfile for testing of settting github context messages

---

src/middlewared/middlewared/plugins/network.py

fix(middlewared/network): do the right thing when MTU is changed for LAGG

---

nas_ports/freenas/freenas-pkgtools/Makefile
nas_ports/freenas/freenas-pkgtools/pkg-plist

Ticket:	#28133
(cherry picked from commit d4cfed01ceac9e89bba0f0ffbf876f791392f172)

fix(pkg): generate python cache files and add to pkg-plist automatically

---

src/middlewared/middlewared/plugins/zfs.py

Ticket:	#28381
(cherry picked from commit 5d28d734c83c191c7d68ab6589c308006b0f4497)

fix(middlewared/zfs): not use libzfs out of the SINGLE_THREAD_POOL

---

gui/storage/views.py
gui/templates/storage/volume_detach.html

fix(ha): do not allow pool detach if standby is down

---

src/freenas/usr/local/libexec/freenas-debug/include.sh
src/freenas/usr/local/libexec/freenas-debug/system/system.sh
src/freenas/usr/local/libexec/samba/samba-backtrace

Fix 28021 master

---

gui/freeadmin/static/lib/js/freeadmin/SupportTicket.js
src/middlewared/middlewared/plugins/support.py

fix(gui): Fix submitting tickets through "Support" tab

---

gui/system/models.py

FIx "Proactive Support" being greyed out

---

src/freenas/usr/local/libexec/freenas-debug/include.sh
src/freenas/usr/local/libexec/freenas-debug/system/system.sh
src/freenas/usr/local/libexec/samba/samba-backtrace

Fix 28021 11.1 stable

---

gui/templates/network/ipmi.html

fix(ipmi): Identify Button on HA

---

src/middlewared/middlewared/plugins/mdns.py

This means they will only show when middlewared is started in
foreground.
Ticket:	#28533

feat(middlewared/mdns): use TRACE level for mdns messages

---

src/freenas/etc/ix.rc.d/ix-snmpd

fixed issue with SNMP over IPv6 (#28572)

---

gui/reporting/rrd.py
src/freenas/etc/rc.conf.local

fix(gui): showing graphs with colon in the interface name

---

gui/reporting/rrd.py
gui/reporting/urls.py
src/freenas/etc/ix.rc.d/ix-collectd
src/freenas/usr/local/lib/collectd_pyplugins/disktemp.py

Disk temperature graphs

---

src/freenas/usr/local/etc/syslog-ng.conf.freenas
src/middlewared/middlewared/plugins/notifier.py

fix(consul): do not log to /var/log/messages

---

nas_ports/freenas/py-middlewared/files/middlewared.in
src/middlewared/middlewared/main.py

This now runs it in foreground mode in a tmux session that gets killed upon stopping.
Ticket: #28593

fix(rc): middlewared debug not starting

---

src/middlewared/middlewared/client/client.py

fix(middlewared): make sure to close fd when using reserved_ports client

---

src/freenas/usr/local/etc/syslog-ng.conf.freenas

fix(consul): do not show consul in /var/log/messages

---

src/freenas/usr/local/libexec/freenas-debug/network/network.sh

Use -vvv for ifconfig

---

src/freenas/usr/local/libexec/freenas-debug/network/network.sh

Caleb asked Kris to get this in STABLE, and he was OK with it.
Ticket: #26931

[STABLE] Use -vvv for ifconfig

---

src/middlewared/middlewared/main.py

fix(middlewared): restart when middlewared is started on foregound

---

src/middlewared/middlewared/plugins/jail.py

feat(jails): Add method to get current activated pool

---

gui/network/forms.py
gui/network/models.py

fix(gui): Do not allow underscores in hostname

---

src/middlewared/middlewared/plugins/auth.py

This allows removing a token's access to the system
Ticket: #27990

feat(middlewared): Add logout method to auth plugin

---

gui/system/alert.py
src/middlewared/middlewared/plugins/support.py

fix(alert): creating SS tickets and alertd crash

---

src/middlewared/middlewared/plugins/datastore.py

[STABLE] Fix 28812 stable

---

src/middlewared/middlewared/plugins/datastore.py

fix(plugins/datastore): Raise CallError instead of OperationalError

---

src/middlewared/middlewared/plugins/vm.py

[MASTER] - Provide an API call for the next available VNC port.

---

tests/api2/disk.py
tests/api2/interfaces.py
tests/api2/network.py
tests/api2/runtest.py
tests/runtest.py

Adding interfaces.py for api 2.0 test
Adding interfaces.py to runtests.py
Adding network.py for getting network general info
Adding test to get netmask from interfaces
Fix merge conflict
Adding code to find if disk were properly setup after installation
Adding code to run only network test

Adding latest change for api tests 2.0 and 1.0

---

src/middlewared/middlewared/plugins/filesystem.py

Return acl in filesystem.stat

---

docs/api/resources/tasks.rst

fix(api): smart tests take disk_identifier not id

---

src/freenas/etc/ix.rc.d/ix-collectd

Also stop collecting geom_stat for every partition.
Ticket:	#28792

fix(collectd): increase collectd tmpfs based of disks and CPUs

---

gui/system/forms.py

fix(ha): use middleware client within context

---

src/middlewared/middlewared/main.py

fix(middlewared): Allow token in header

---

src/freenas/etc/ix.rc.d/ix-collectd

Increase it from 600m to 1g.
Ticket:	#28792

fix(collectd): revert dynamic tmpfs size after discussion

---

src/freenas/etc/ix.rc.d/ix-collectd

Increase it from 600m to 1g.
Ticket:	#28792
(cherry picked from commit 072dfb2df090020e909c3730547799e198db8d62)

[stable] fix(collectd): revert dynamic tmpfs size after discussion

---

src/middlewared/middlewared/plugins/sysdataset.py

fix(middlewared/sysdataset): setup datasets of the target pool

---

src/middlewared/middlewared/plugins/sysdataset.py

Ticket:	#28786
(cherry picked from commit 18099f63538f941621fd8d38954568bb35fb11fd)

[stable] fix(middlewared/sysdataset): setup datasets of the target pool

---

src/freenas/etc/netcli

If the user wants to configure failover settings, we also ask if they want to set it critical for failover
Ticket: #26279

feat(netcli): Add critical for failover dialog

---

gui/storage/views.py

Ticket:	#25748
(cherry picked from commit 0094a35ae125ce3c7cb3e95726ee95b60574b274)

fix(ha): only warn on last pool

---

src/middlewared/middlewared/plugins/pool.py

fix(gui): Fix failed import text formatting

---

src/freenas/usr/local/libexec/nas/scrub

fix(scrub): Don't run if the pool is not online or unlocked

---

gui/middleware/notifier.py

fix(notifier): detach geli provider when removing a zfs disk

---

gui/storage/forms.py

fix(gui): do not detach pool if extending a volume fails

---

gui/middleware/form.py
gui/system/forms.py
src/middlewared/middlewared/logger.py
src/middlewared/middlewared/plugins/sysdataset.py
src/middlewared/middlewared/service.py

systemdataset.update is a long running call, turn it into a job

---

src/freenas/etc/netcli

fix(ha): do not ask for passphrase if other node is still MASTER

---

src/middlewared/middlewared/client/client.py

If client fails at the connecting stage reserved_fd would never be
closed.
Ticket:	#29062

fix(ha): make sure to close reserved_fd by all means necessary

---

src/middlewared/middlewared/job.py

fix(middleware): Ugly hack to close file descriptors opened by mail.send

---

gui/storage/views.py

fix(ha): warn when locking the last pool

---

gui/system/alert.py
src/middlewared/middlewared/plugins/mail.py

Per-alert e-mails

---

src/middlewared/middlewared/plugins/disk.py

fix(disk): use only one partition if no more swaps are found

---

gui/freeadmin/static/lib/js/freeadmin.js
gui/system/forms.py
gui/system/urls.py
gui/system/views.py
gui/templates/system/manualupdate_wizard_1.html

Apparently some recent combination of browsers+OS can make long running
HTTP POST responses be entirely missed by the browser.
Ticket:	#29040

feat(gui): rework manual upgrade to use polling requests

---

src/freenas/etc/ix.rc.d/ix-nginx
src/freenas/etc/newsyslog.conf
src/freenas/usr/local/etc/syslog-ng.conf.freenas

fix(nginx): access log to tmpfs

---

src/middlewared/middlewared/plugins/device.py

fix(devd): Read complete lines from devd socket

---

src/middlewared/middlewared/plugins/system.py
src/middlewared/middlewared/plugins/unauthorized_reboot_alert.py

Ticket:	#29133
(cherry picked from commit c3a022b8720d0db0698ae450755cb562b3f84dc2)

fix(middlewared/alert): only issue an email if uptime is lower than 3m

---

src/middlewared/middlewared/plugins/service.py

Screen saver bug fixed

---

src/freenas/usr/local/libexec/nas/generate_smb4_conf.py

Set the private dir per node

---

gui/system/forms.py
src/middlewared/middlewared/plugins/tunables.py

System:Tunables - GUI to Middlewared

---

gui/storage/forms.py

fix(ha): only force master if not MASTER yet

---

gui/tasks/forms.py
nas_ports/freenas/py-middlewared/Makefile
src/middlewared/middlewared/plugins/notifier.py
src/middlewared/middlewared/plugins/rsync.py

I'll add missing dependency for asyncssh tomorrow.
I think I'm going to simplify the validation logic even more.

Tasks:Rsync - GUI to Middlewared

---

src/middlewared/middlewared/plugins/pool.py

More robust parser for rsync progress in pool.import_disk

---

gui/templates/storage/import_stats.html
src/middlewared/middlewared/job.py
src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/service.py

Better rsync logs for pool.import_disk

---

gui/templates/system/system_info.html

fix(gui): check ixsystems lowercase

---

gui/system/views.py
gui/templates/system/debug.html

fix(gui): use polling requests to get the debug

---

src/freenas/usr/local/libexec/nas/generate_smb4_conf.py

(cherry picked from commit 83ca0620b94fe9d1ed934c346175ba5a9c1f891a)

Don't change private dir on FreeNAS

---

src/middlewared/middlewared/alert/base.py
src/middlewared/middlewared/alert/schedule.py
src/middlewared/middlewared/alert/source/httpd_ssl.py
src/middlewared/middlewared/alert/source/scrub_paused.py
src/middlewared/middlewared/alert/source/selftest.py
src/middlewared/middlewared/alert/source/smart.py
src/middlewared/middlewared/alert/source/update.py
src/middlewared/middlewared/alert/source/volume_version.py
src/middlewared/middlewared/alert/source/zpool_capacity.py
src/middlewared/middlewared/plugins/alert.py

Please not that alert logic itself is not implemented yet

Generate warning when a scrub is paused

---

src/freenas/etc/ix.rc.d/ix-snmpd

Return FreeNAS version in SNMP sysDescr string

---

gui/services/forms.py
src/middlewared/middlewared/plugins/lldp.py

isort is also run ;)
Ticket: #25942

Services:LLDP - GUI to Middlewared

---

src/middlewared/middlewared/plugins/pool.py

Also add `origin` to pool.dataset.query
Ticket:	#28876

feat(middlewared/pool): add pool.dataset.promote

---

src/freenas/usr/local/libexec/nas/generate_smb4_conf.py

(cherry picked from commit 9bec8a01f3735df875bf812643e8ec4237fa9b4f)

Migrate files to private dir

---

gui/support/views.py
gui/templates/documentation/index.html
nas_ports/freenas/freenas-docs-legacy/Makefile
nas_ports/freenas/freenas-docs-legacy/pkg-descr
src/freenas/etc/ix.rc.d/ix-nginx

DEPENDS: https://github.com/freenas/build/tree/issues/30100
Move old to docs_legacy.
Ticket:	#30100

feat(docs): add another documentation for the new ui

---

src/freenas/usr/local/libexec/nas/generate_smb4_conf.py

(cherry picked from commit c7a4932ab88abb7df1872dfef9e4cc6f0156c3d8)

Sigh. Write the sentinel file.

---

src/middlewared/middlewared/service.py

fix(middleware): Insert rows in ConfigService if none was found

---

src/freenas/usr/local/libexec/nas/generate_smb4_conf.py

Select proper location of `privatedir` depending on the `is_truenas_ha` value.

Fix privatedir stable

---

src/freenas/usr/local/libexec/nas/generate_smb4_conf.py

Use `is_truenas` to determine the location of the `privatedir`.

Create global variable `is_truenas` to reduce number of client calls.

---

src/middlewared/middlewared/worker.py

fix(middlewared/worker): implement run_in_thread in FakeMiddleware

---

gui/services/forms.py
src/middlewared/middlewared/plugins/webdav.py

Services:WebDAV - GUI to Middlewared

---

gui/network/forms.py
src/middlewared/middlewared/plugins/network.py

Network Global Configuration moved to middlewared

---

gui/middleware/form.py
gui/storage/forms.py
src/middlewared/middlewared/plugins/pool.py

Storage scrub moved to middlewared

#Ticket: 30690

---

gui/common/samba.py

if this is an HA system or not.
(cherry picked from commit 553ca25b03d2ec41deb46d38d6a59f179f8b44ab)
Signed-off-by: Timur I. Bakeyev <timur@iXsystems.com>

Choose location of the `.usersimported` sentinel file depending on

---

src/middlewared/middlewared/alert/schedule.py

fix(alert): Fix first run of anything under CrontabSchedule

---

gui/choices.py
gui/system/forms.py
src/middlewared/middlewared/plugins/system.py

System Advanced moved to Middlewared

---

src/middlewared/middlewared/plugins/service.py

Don't reload sysctl, this shouldn't ever be necessary

---

src/middlewared/middlewared/plugins/vm.py

Ticket: #29189
Forum: https://forums.freenas.org/index.php?threads/network-gone-from-vm-after-reboot-upgrade.61717/

Bring up the host nic attached to a VM to a UP state in case the nic is down.

---

gui/storage/forms.py

fix(gui): import non-encrypted volume/pool

---

gui/storage/forms.py
src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/validators.py

Storage: Resilver Priority moved to middlewared

---

src/freenas/usr/local/bin/freenas-debug
src/freenas/usr/local/libexec/freenas-debug/active_directory/active_directory.sh
src/freenas/usr/local/libexec/freenas-debug/afp/afp.sh
src/freenas/usr/local/libexec/freenas-debug/cache/cache.sh
src/freenas/usr/local/libexec/freenas-debug/domain_controller/domain_controller.sh
src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh
src/freenas/usr/local/libexec/freenas-debug/include.sh
src/freenas/usr/local/libexec/freenas-debug/ipmi/ipmi.sh
src/freenas/usr/local/libexec/freenas-debug/iscsi/iscsi.sh
src/freenas/usr/local/libexec/freenas-debug/ldap/ldap.sh
src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh
src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh

Redmine: https://redmine.ixsystems.com/issues/30729
The vast majority of changes in this commit is to add some logic for certain services that are disabled, don't run the scripts. Exit that particular module and move on.
There are also lots of clean ups/verbiage corrections and duplicate command removals.

fix(master) freenas-debug speed up and clean up

---

src/middlewared/middlewared/plugins/account.py

fix(middlewared/account): user.delete when DC is enabled

---

src/middlewared/middlewared/plugins/network.py

fix(middlewared/network): Do not use shell=True

---

gui/middleware/notifier.py
gui/storage/views.py
src/middlewared/middlewared/plugins/disk.py

Also do not blow up an exception to user face if a disk format fails.
Ticket:	#25246

fix(gui): use middleware to wipe disks on volume creation

---

gui/storage/forms.py
src/middlewared/middlewared/plugins/jail.py

fix(jail/rc): Run after volume unlock

---

src/freenas/usr/local/libexec/freenas-debug/system/system.sh
src/freenas/usr/local/libexec/freenas-debug/verify/verify.sh
src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh

Redmine: https://redmine.ixsystems.com/issues/24965
add zfs list -ro space,refer,mountpoint in zfs section
add sqlite3 pragma integrit_check output to verify section
add 'hactl' output if HA TrueNAS is detected

fix(stable) add more command output to freenas-debug 

---

src/freenas/usr/local/libexec/freenas-debug/system/system.sh
src/freenas/usr/local/libexec/freenas-debug/verify/verify.sh
src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh

Redmine: https://redmine.ixsystems.com/issues/24965
add zfs list -ro space,refer,mountpoint in zfs section
add sqlite3 pragma integrit_check output to verify section
add 'hactl' output if HA TrueNAS is detected

fix(master) add more command output to freenas-debug

---

gui/choices.py
gui/services/forms.py
src/middlewared/middlewared/plugins/ups.py

Services: UPS moved to middlewared

---

gui/storage/forms.py

Bug Fix for ZVOL deduplication

---

src/freenas/etc/ix.rc.d/ix-syncdisks
src/freenas/etc/ix.rc.d/ix-system
src/freenas/etc/rc.conf
src/freenas/etc/rc.conf.local
src/middlewared/middlewared/plugins/disk.py

Fix Unexpected failures, timeout, null during boot

---

src/middlewared/middlewared/main.py

fix(middlewared): do not spawn another thread on `call_sync`

---

src/freenas/usr/local/etc/syslog-ng.conf.freenas

fix(syslog): do not log nginx errors to console

---

src/middlewared/middlewared/main.py

fix(middlwared): do not spawn thread only if thread id is different

---

src/freenas/etc/rc.conf.local

Redmine: https://redmine.ixsystems.com/issues/31350

let middleware attach geli providers

---

src/freenas/etc/rc.conf.local

Redmine: https://redmine.ixsystems.com/issues/31350

fix(stable) let middleware mount geli providers

---

src/middlewared/middlewared/plugins/service.py

Log the reason why we think that AD is not started.

Add more logging for AD monitoring

---

src/middlewared/middlewared/plugins/account.py

* Don't create parent directories if are missing in the `__update_sshpubkey` -
there should be good reason why it's not there yet(like `/nonexistent`)
* Optimized `__update_sshpubkey` to exit earlier if not all conditions are met.
* Fixed coping of the home dir on the user update. Due to the async nature
of copy we need to set home dir permissions in the corutine itself and
set the ssh public keyfile before the operation in the old home dir.
Ticket: #31137
(cherry picked from commit e98bf9cfb294389259d656c85c3525b568f1bb6e)
Signed-off-by: Timur I. Bakeyev <timur@iXsystems.com>

Try harder not to create `/nonexistent` directory. (#1081)

---

gui/sharing/forms.py
src/middlewared/middlewared/plugins/afp.py
src/middlewared/middlewared/schema.py

Sharing:AFP to Middlewared

---

gui/templates/system/job_logs.html

Follow-up for c5fb2fc1cc40e45091bebef901932f3fb585a339
Add forgotten file
Ticket: #27756

Follow-up for c5fb2fc1cc40e45091bebef901932f3fb585a339

---

src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh

Add `camcontrol devlist -v` to debug output

---

gui/storage/forms.py
gui/tasks/forms.py
nas_ports/freenas/py-middlewared/Makefile
src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/plugins/rsync.py
src/middlewared/middlewared/schema.py
src/middlewared/middlewared/validators.py

2 CRUD Services refactored for maximum consistency among the attributes they accept

2 Middlewared Services refactored

---

gui/tasks/forms.py
src/middlewared/middlewared/plugins/cron.py

Tasks: Cron moved to middlewared

---

src/winacl/winacl.c

(cherry picked from commit fefffe6b602e5f97dacee6ccd67b2ed13964ff2d)

null terminate

---

gui/services/forms.py
src/middlewared/middlewared/plugins/nfs.py

NFS to Middlewared

---

gui/services/forms.py
gui/services/models.py
src/middlewared/middlewared/plugins/domain_controller.py

DC to Middlewared

---

gui/support/views.py
gui/templates/support/license_update.html

Use HTML TrueNAS EULA

---

src/middlewared/middlewared/worker.py

fix(middlewared): make process worker function again for CRUD services

---

gui/templates/freeadmin/index.html

middlewareTokenUrl being undefined
Ticket: #31014

fix(oldgui): Fix middleware client not working in Microsoft Edge due to

---

gui/network/migrations/0003_lagg_no_mtu.py

Ticket:	#31773
(cherry picked from commit 4fad3af78875645c16687cb93dcae017c258efa2)

fix(migration): move MTU from lagg to members

---

src/middlewared/middlewared/plugins/jail.py

Return an ip4 address instead of none for dhcp jails

---

src/freenas/etc/rc.conf.local

feat(rc.conf.local): cache failover_status and failover_licensed

---

src/middlewared/middlewared/gdb.py

fix(midgdb): getting middlewared proc and remote output

---

src/freenas/etc/ix.rc.d/ix-fstab

fix(rc.d): /conf/base/etc/fstab no longer exists

---

src/middlewared/middlewared/plugins/account.py

(fix/account): Add non-builtin user/groups to the user list for query

---

src/freenas/usr/local/etc/syslog-ng.conf.freenas

fix(syslog-ng): update config file format version

---

src/middlewared/middlewared/plugins/pool.py

feat(middlewared/pool): add `share_type` to pool.dataset

---

gui/freeadmin/static/lib/js/freeadmin.js
gui/system/forms.py
src/middlewared/middlewared/plugins/backup.py

feat(backup): Allow specifying custom S3 endpoint

---

gui/common/system.py
gui/system/forms.py
src/middlewared/middlewared/plugins/ntp.py

System:General:NTP to Middlewared

---

src/middlewared/middlewared/client/client.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/auth.py

feat(middlewared): bind to unix socket and use it by default in client

---

gui/choices.py
gui/sharing/forms.py
src/middlewared/middlewared/plugins/smb.py

Sharing:CIFS to middlewared

---

src/middlewared/middlewared/plugins/afp.py

(fix/sharing.afp) Verify path is in volume

---

src/middlewared/middlewared/plugins/smb.py

Change Dir back to Str

---

src/middlewared/middlewared/etc_files/smartd.py

fix(smart): Fix smartd config not being generated

---

gui/choices.py
gui/services/forms.py
src/middlewared/middlewared/plugins/ups.py

UPS Port choices added to Middlewared

---

src/middlewared/middlewared/plugins/pool.py

fix(middlewared/pool): mount zfs dataset before set share type

---

src/middlewared/middlewared/main.py

Reggression when updating to aiohttp 3.1.

fix(middlewared): sending event from thread

---

gui/services/models.py

Bug Fix for WebDAV SSL choices

---

gui/sharing/forms.py
src/middlewared/middlewared/plugins/webdav.py

Convert Sharing:WebDAV to Middlewared

---

src/middlewared/middlewared/main.py

fix(middlewared): shell with aiohttp 3.1

---

src/middlewared/middlewared/plugins/smb.py

fix(sharing/smb): Continue if it's not a filesystem.

---

src/middlewared/middlewared/plugins/support.py

feat(support): Check debug file size before attaching to ticket

---

gui/system/alert.py

We need a try/except here for the end of the file

---

gui/services/forms.py
gui/services/models.py
src/middlewared/middlewared/plugins/iscsi.py

Sharing:iSCSI  - Authorized Access to middlewared

---

src/freenas/usr/local/bin/ixdiagnose

Redmine: https://redmine.ixsystems.com/issues/33012

feat(master)if /root/syslog exists, add it to freenas-debug

---

src/freenas/usr/local/bin/ixdiagnose

Redmine: https://redmine.ixsystems.com/issues/33012

feat(stable)if /root/syslog exists, add it to freenas-debug

---

gui/choices.py
gui/common/ssl.py
gui/system/forms.py
gui/system/views.py
src/freenas/usr/local/libexec/nas/generate_ssl_certificates.py
src/middlewared/middlewared/async_validators.py
src/middlewared/middlewared/plugins/crypto.py
src/middlewared/middlewared/plugins/datastore.py
src/middlewared/middlewared/plugins/system.py
src/middlewared/middlewared/schema.py
src/middlewared/middlewared/service_exception.py

Moving CA's/Certificate's to Middlewared

Ticket 31953

---

gui/api/resources.py

Sorting bug fixed in ISCSITargetToExtent api 1.0

---

gui/storage/forms.py
src/middlewared/middlewared/plugins/snapshot.py
src/middlewared/middlewared/schema.py

Periodic Snapshots moved to Middlewared

---

src/freenas-installer/etc/install.sh

that retire GRUB.
Ticket: #33183

Fix issue with UEFI installs on the new hybrid BSD loader images

---

src/middlewared/middlewared/plugins/crypto.py

Schema name param removed from Sign CSR public method

---

tests/api2/disk.py
tests/api2/ftp.py
tests/api2/interfaces.py
tests/api2/ssh.py
tests/runtest.py

* removing domaincontroler from runtest until it fix
* adding user api 2 test in runtest
* change the code in ssh.py ftp.py interface.py to search instead of harcoding id and list

chaging code to have api test ready to run on jenkins

---

gui/tools/autosnap.py

fix(autosnap): try to show the reason a vmware snapshot failed

---

src/freenas/usr/local/etc/sudoers

Ticket: #29805
(cherry picked from commit b962a59e75acce42373d7c7cdb90e3ac9b14c0d4)

Allow /etc/find_alias_for_smtplib.sh to be used by sudoers

---

docs/api/resources/sharing.rst
gui/api/resources.py
gui/sharing/admin.py

fix(api): document and output `cifs_storage_task`

---

src/middlewared/middlewared/restful.py

fix(middlewared/rest): allow REST to run Jobs returning its `id`

---

src/middlewared/middlewared/plugins/disk.py

feat(middlwared): reconfigure swaps when disk vanishes

---

gui/services/forms.py
src/middlewared/middlewared/plugins/iscsi.py

Services:iSCSI Initiators to Middlewared

---

gui/services/forms.py
src/middlewared/middlewared/plugins/iscsi.py
src/middlewared/middlewared/plugins/notifier.py

Sharing:iSCSI - Extents to middlewared

---

gui/freeadmin/options.py
src/middlewared/middlewared/plugins/nfs.py

fix(nfs): Fix NFS share creation

---

src/middlewared/middlewared/plugins/domain_controller.py

fix(directoryservice): Fix domaincontroller partial update

---

src/middlewared/middlewared/plugins/snmp.py

fix(snmp): Allow empty SNMP contact

---

gui/services/forms.py
src/middlewared/middlewared/plugins/datastore.py
src/middlewared/middlewared/plugins/iscsi.py
src/middlewared/middlewared/plugins/system.py

feat(middlewared/iscsi): move iSCSI target from GUI

---

gui/storage/forms.py
src/middlewared/middlewared/alert/source/replication.py
src/middlewared/middlewared/plugins/replication.py
src/middlewared/middlewared/validators.py

Storage: Replication moved to Middlewared

---

src/middlewared/middlewared/plugins/network.py

Remove all addresses if dhcp is set

---

gui/templates/registration/login.html

Remove "Try the Beta UI!" link

---

src/middlewared/middlewared/plugins/disk.py
src/middlewared/middlewared/plugins/pool.py

feat(middlewared/pool): add `device` to pool `topology`

---

src/middlewared/middlewared/plugins/account.py

feat(middlewared/account): handle permission error more gracefully

---

src/middlewared/middlewared/client/client.py

STABLE -- (middlewared/client): retry in case of EADDRINUSE

---

tests/api2/lldp.py
tests/runtest.py

feat(api2): add LLDP tests

---

docs/api/resources/storage.rst
gui/api/resources.py

feat(api): add disk online API and document disk offline API

---

src/middlewared/middlewared/plugins/tunables.py
tests/api2/tunable.py
tests/runtest.py

API v2 tests added for Tunables
Minor fixes in tunable plugin ( Middlewared )

Ticket: #33666

---

tests/api2/system_general.py
tests/runtest.py

Add system general API tests

---

tests/api2/cronjob.py
tests/runtest.py

Add APIv2 cronjob test

---

src/middlewared/middlewared/restful.py

feat(middlewared/restful): handle some exceptions gracefully

---

gui/sharing/forms.py

Redmine: https://redmine.ixsystems.com/issues/33786

fix(stable)be less restrictive on same share NFS exports

---

src/middlewared/middlewared/plugins/init_shutdown_script.py
tests/api2/initshutdownscript.py
tests/runtest.py

Also in this commit:
- Modernize init_shutdown_script plugin
- Rewrite testfile routine
- Correct error message in runtest.py
TIcket: #33687

Write API functional tests for Init/Shutdown Scripts

---

tests/api2/system_advanced.py

Add System Advanced tests

---

src/middlewared/middlewared/plugins/zfs.py

fix(middlewared/zfs): setting value on inherited attributes

---

gui/system/views.py

Ticket:	#33846
(cherry picked from commit 515595ac7e3a37106f948a7a4e4f4d71158782c4)

feat(gui): initialize variables properly for HA update check

---

gui/storage/forms.py
gui/storage/models.py
src/middlewared/middlewared/plugins/disk.py

Update method added to Disk plugin

---

src/middlewared/middlewared/plugins/snmp.py
tests/api2/snmp.py

- Add defaults to keys that need them
Ticket: #33837

Write API functional tests for snmp

---

src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh

Redmine: https://redmine.ixsystems.com/issues/33927

fix(master) fix typo in table name

---

src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh

Redmine: https://redmine.ixsystems.com/issues/33927

fix(stable) fix typo in table name

---

src/freenas/usr/local/libexec/freenas-debug/system/system.sh

Redmine: https://redmine.ixsystems.com/issues/33930

fix(master) replace jq with json.tool in freenas-debug

---

src/freenas/usr/local/libexec/freenas-debug/system/system.sh

Redmine: https://redmine.ixsystems.com/issues/33930

fix(stable) replace jq with json.tool in freenas-debug

---

tests/api2/dyndns.py

Write API functional tests for dyndns

---

tests/api2/disk.py
tests/runtest.py

Tests added for Disk plugin

---

gui/common/freenasldap.py
src/freenas/usr/local/libexec/nas/generate_sssd_conf.py

Allow self signed certificates

---

src/middlewared/middlewared/etc_files/pam.d/ftp
src/middlewared/middlewared/etc_files/pam.d/ftpd
src/middlewared/middlewared/etc_files/pam.d/login
src/middlewared/middlewared/etc_files/pam.d/netatalk
src/middlewared/middlewared/etc_files/pam.d/samba
src/middlewared/middlewared/etc_files/pam.d/sshd
src/middlewared/middlewared/etc_files/pam.d/su
src/middlewared/middlewared/etc_files/pam.d/sudo

Shut pam_sss up when authenticating local users

---

jenkins/Jenkinsfile-PR

- Nuke rm -rf commands and replace it with zfs mount points, this improves the build time about 5/10 mins in total.

Jenkins Performance Update

---

src/freenas/etc/ix.rc.d/ix-nis

Redmine: https://redmine.ixsystems.com/issues/33924
cherry-picking this back into stable

fix(stable) Add check to see if nis is enabled

---

src/middlewared/middlewared/plugins/system.py

Backport system.advanced.config

---

src/middlewared/middlewared/plugins/system.py
src/middlewared/middlewared/utils/__init__.py

DEPENDS: https://github.com/freenas/ports/tree/FIX-33957
Ticket:	#33936

feat(middlewared/system): add `buildtime` to system.info

---

src/freenas/usr/local/bin/freenas-debug

Redmine: https://redmine.ixsystems.com/issues/33993

fix(master) remove parallel routines for freenas-debug

---

src/freenas/usr/local/bin/freenas-debug

Redmine: https://redmine.ixsystems.com/issues/33993

fix(stable) remove parallel routines for freenas-debug

---

gui/api/utils.py

fix(api): handle ValidationErrors from middleware

---

gui/templates/support/license_update.html

Update License button needs to say "I agree" instead of "OK".

---

tests/api2/ups.py

Write API functional tests for ups

---

docs/api/resources/storage.rst
gui/api/resources.py

fix(api/resources): Pass through force attribute to ZFS replace

---

gui/services/forms.py

fix(api): iscsi target group broke in middlewared conversion

---

src/middlewared/middlewared/plugins/service.py

We dont have service monitoring yet. We cant tell if service crashed or
was deliberately stopped.
Ticket:	#34050

fix(middlewared/service): remove CRASHED state

---

src/middlewared/middlewared/plugins/zfs.py

fix(zfs/dataset): Umount before deletion

---

src/middlewared/middlewared/restful.py

feat(restful): allow GET in a subresource (/{service}/id/{id}/)

---

src/freenas/etc/ix.rc.d/ix-nginx

fix(ngix-middlewared): remove path from proxy_pass to disable decoding

---

docs/api/resources/storage.rst
gui/api/resources.py

feat(api): add endpoint to zfs remove a disk

---

src/middlewared/middlewared/plugins/pool.py

feat(middlewared/pool): add `compressratio` to `pool.dataset.query`

---

src/middlewared/middlewared/plugins/iscsi.py

Minor fixes for ISCSI plugin

---

src/middlewared/middlewared/main.py

Somehow I've lost this commit while merging main PR

Make run_in_io_thread accept kwargs

---

src/freenas/etc/ix.rc.d/ix-smartd

Revert "fix(smart): Temporarily enable monitoring for all NVMe devices if at …"

---

src/freenas/etc/ix.rc.d/ix-ldap
src/freenas/etc/rc.conf.local

Start nslcd on boot

---

src/middlewared/middlewared/plugins/pool.py

Convert Storage:Permissions to Middlewared

---

tests/api2/webdav_osx.py

This depends on PR #1321 first, as it has changes required for this.
Ticket: #33975

Write API functional tests for webdav_osx

---

src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/plugins/webdav.py
tests/api2/webdav_bsd.py

In addition:
- Return an instance when creating a dataset
- Add an id key to keep consistency in API
- Fix bad tests in WebDAV plugin

Write API functional tests for webdav_bsd

---

src/middlewared/middlewared/plugins/afp.py

fix(afp): Path key may not exist

---

tests/api2/iscsi.py

API v2 Tests for iSCSI

---

src/middlewared/middlewared/plugins/tftp.py
src/middlewared/middlewared/validators.py

Minor changes for TFTP plugin

---

src/middlewared/middlewared/plugins/update.py

fix(update): Provide progress report for update.download job

---

tests/api2/tftp.py

TFTP tests API v2

---

src/middlewared/middlewared/plugins/crypto.py

Following changes have been made:
1) Datastore service is queried for retrieving contents of CA service instead of CA default query method to stop the recursive loop which starts from certificate's extend method
2) Methods in crypto services have been made private
3) Serials weren't unique among a cert chain. This commit fixes that

Ticket: #34477

---

src/middlewared/middlewared/plugins/nfs.py

fix(nfs): Support IPv6 networks for NFS shares

---

src/middlewared/middlewared/plugins/ipmi.py

fix(ipmi): setting VLAN

---

src/middlewared/middlewared/plugins/ipmi.py

Ticket:	#34603
(cherry picked from commit 4fde75877119bee92b5fe273407e7bab1aa6b09d)

[stable] fix(ipmi): setting VLAN

---

src/middlewared/middlewared/plugins/jail.py

fix(plugins/jail): Catch any exceptions during updating a property

---

gui/system/forms.py

Root email field populated in Wizard form

---

src/middlewared/middlewared/plugins/ipmi.py

Minor edits in IPMI plugin

---

tests/api2/ipmi.py

Api v2 tests for IPMI plugin

---

gui/storage/forms.py
gui/system/forms.py
src/middlewared/middlewared/plugins/disk.py
src/middlewared/middlewared/plugins/system.py

Functionality to reset SED password in GUI added

---

src/middlewared/middlewared/plugins/system.py

fix(middlewared): `ui_protocol` should be uppercase

---

src/middlewared/middlewared/plugins/smb.py

fix(plugin/smb): Path key may not exist

---

src/middlewared/middlewared/plugins/jail.py

fix(plugins/jail): Fix default jail filtering

---

src/middlewared/middlewared/plugins/jail.py

Minor changes in Jail plugin

---

src/middlewared/middlewared/plugins/cloud_sync.py

fix(cloudsync): Make encryption_salt non-required field

---

src/middlewared/middlewared/main.py
src/middlewared/middlewared/worker.py

fix(middlewared): deadlock when using call_sync

---

src/freenas/etc/devd/ifnet_attach.conf
src/middlewared/middlewared/plugins/network.py

fix(middlewared): handle interface attach in middlewared

---

src/freenas/etc/find_alias_for_smtplib.py
src/freenas/etc/ix.rc.d/ix-aliases

/etc/alias bug fixed - some users were not getting an entry in alias file
Ticket: #32685

Ticket: #32685

---

src/middlewared/middlewared/service.py

SSH not reloading when start on boot is disabled for SSH

---

gui/account/models.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/auth.py

Adds middleware endpoints and model fields for prototypical support of WebAuthn. Requires supporting changes in freenas/webui.

WebAuthn support

---

gui/account/models.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/auth.py

Revert "WebAuthn support"

---

gui/sharing/forms.py
src/middlewared/middlewared/plugins/service.py
src/middlewared/middlewared/plugins/smb.py
tests/api2/smb_and_cifs.py

fix(smb): renaming and tests

---

src/middlewared/middlewared/restful.py

feat(middlewared/restful): do not allow extra attributes

---

src/middlewared/middlewared/plugins/system.py

Improve validation for serial ports

---

gui/services/forms.py

fix(api): secret confirmation not required

---

gui/sharing/forms.py
src/middlewared/middlewared/plugins/smb.py

feat(mw/smb): document args and simplify sharing.smb.get_storage_tasks

---

src/middlewared/middlewared/plugins/cloud_sync.py

fix(cloud_sync): Properly report invalid credentials

---

src/middlewared/middlewared/restful.py

feat(api): register URLs with and without slash, avoiding a redirect

---

src/middlewared/middlewared/etc_files/nfsd.py

It was lost when porting sh -> python
Ticket: #34744

fix(nfs): add -sec=sys if we have kerberos keytabs

---

gui/storage/forms.py
src/middlewared/middlewared/plugins/pool.py

feat(mw|gui): reload iscsi when zvol size changes

---

src/middlewared/middlewared/plugins/jail.py

Fix a potential oddity if the user supplies a nested list.
Ticket: #35128

fix(jail/exec): Attribute name changed upstream, additional improvements

---

src/middlewared/middlewared/restful.py
src/middlewared/middlewared/schema.py

fix(apidocs): show lists in swagger ui (openapi)

---

gui/choices.py

fix(gui): catch up sharing.cifs -> sharing.smb renaming

---

src/freenas/usr/local/libexec/freenas-debug/smart/smart.sh

fix(stable) echo the device so smart.nawk finds da#

---

src/freenas/usr/local/libexec/freenas-debug/smart/smart.sh

fix(master) echo the device so smart.nawk finds da#

---

src/middlewared/middlewared/etc_files/nfsd.py

fix(nfs): Fix invalid syntax for multiple networks

---

src/middlewared/middlewared/plugins/backup.py

fix(backup): fix deleting cloud credentials through compability layer

---

docs/api/resources/tasks.rst

Documentation for smarttest api1.0 updated

---

src/middlewared/middlewared/plugins/pool.py

Force size option added for zvol creation in Middlewared

---

src/freenas/etc/rc.conf.local
src/middlewared/middlewared/plugins/service.py

Remove vaaiserver from FreeNAS repo as well for 11.2:

---

gui/tasks/forms.py

Rsync bug fixed

---

src/middlewared/middlewared/plugins/snapshot.py

Snapshot extend method bug fix

---

src/middlewared/middlewared/worker.py

fix(middlewared): watch parent process on workers

---

tests/api2/s3.py

API v2 tests for S3

---

src/middlewared/middlewared/plugins/pool.py

Bug fix for traceback when updating zvol size

---

tests/api2/jails.py

Jails API v2 tests

---

src/middlewared/middlewared/plugins/replication.py

pool.snapshot usages renamed to pool.snapshottask

---

gui/middleware/notifier.py
gui/middleware/zfs.py
gui/storage/views.py
gui/templates/storage/scrub_confirm.html
gui/templates/storage/volumestatus_datagrid.html
gui/templates/system/alertservice_edit.html
gui/templates/system/bootenv_datagrid.html

fix(oldgui): Display paused scrub state as Paused

---

gui/api/resources.py
src/middlewared/middlewared/plugins/cloud_sync.py

Revert "Join latest job to cloud sync tasks"

---

gui/middleware/notifier.py
gui/middleware/zfs.py
gui/storage/views.py
gui/templates/storage/scrub_confirm.html
gui/templates/storage/volumestatus_datagrid.html
gui/templates/system/alertservice_edit.html
gui/templates/system/bootenv_datagrid.html

Revert "fix(oldgui): Display paused scrub state as Paused"

---

gui/storage/forms.py
gui/system/forms.py

Functionality to reset SED Password added

---

src/middlewared/middlewared/plugins/vm.py

we need to let the upper layer knows about it.
Ticket: #34825

- If we can't reserve memory from ZFS ARC for a guest VM,

---

src/middlewared/middlewared/plugins/vm.py

Revert "- If we can't reserve memory from ZFS ARC for a guest VM,"

---

src/middlewared/middlewared/plugins/cloud_sync.py

fix(cloud_sync): Default value for args

---

src/middlewared/middlewared/plugins/cloud_sync.py

Fix updating cloud credentials in new UI

---

src/middlewared/middlewared/plugins/datastore.py
src/middlewared/middlewared/utils/__init__.py

fix(middleware): Be more strict with CRUDPlugin query filters

---

gui/system/forms.py

CSR identifier made editable in GUI

---

src/freenas/etc/ix.rc.d/ix-nginx

This commits adds the ability for the nginx to accept ec keys as well for SSL
Ticket: #27665

Accept ECC keys for Nginx

---

nas_ports/freenas/freenas-files/Makefile
src/fix_afp_ea/Makefile
src/fix_afp_ea/fix_afp_ea.c

Standalone tool to fix AFP files with EA corruption

---

gui/api/resources.py
gui/freeadmin/static/lib/js/freeadmin.js
gui/storage/forms.py
gui/storage/views.py

Storage:Volumes:Change Permission to Middlewared

---

gui/tasks/admin.py
gui/tasks/forms.py

fix(oldgui): Hide Auxiliary Arguments from Cloud Sync task

---

gui/system/migrations/0024_rename_bes.py

tkt-36118: fix(migration): skip migration on fresh install

---

gui/freeadmin/static/lib/js/freeadmin/CloudSync.js
gui/freeadmin/static/lib/js/freeadmin/templates/cloudsync.html

tkt-29825: fix(oldgui): Allow saving cloud sync even if bucket listing failed

---

src/freenas-installer/etc/install.sh

Don't give `set +e` chance to fire without real reason.

---

src/middlewared/middlewared/plugins/cache.py
src/middlewared/middlewared/plugins/system.py

feat(middlewared/system): add system.health event source

---

src/freenas/etc/ix.rc.d/ix-etc

fix(smart): Fix smartd.conf being empty on first boot due to race condition

---

gui/api/resources.py

fix(api): avoid traceback if disk in iscsi extent does not exist

---

gui/api/resources.py
src/middlewared/middlewared/plugins/cloud_sync.py

Join latest job to cloud sync tasks

---

docs/api/resources/storage.rst
gui/api/resources.py
gui/storage/forms.py

This commit adds support for vmware sync when taking snapshots via api v1
Ticket: #36238

Vmware sync support added for snapshots in API v1

---

docs/api/resources/storage.rst
gui/storage/forms.py

Ability to unlock volumes via a recovery key in api v1 has been added in this commit
Ticket: #36083

Unlock volume with Recovery key in API v1

---

gui/services/forms.py
src/middlewared/middlewared/plugins/iscsi.py
src/middlewared/middlewared/plugins/network.py

iSCSI Portal IP bug fix

---

gui/services/views.py

Traceback fixed for validation errors in S3

---

src/middlewared/middlewared/plugins/pool.py

Unique constraint failed for volume scrubs, this commit fixes that

---

gui/services/forms.py
src/freenas-sysctl/services.c

Turn off SMB1

---

src/freenas/etc/newsyslog.conf
src/freenas/usr/local/libexec/nas/generate_afpd_conf.py

Log netatalk to its own file

---

gui/freeadmin/static/lib/js/freeadmin/CloudSync.js
gui/tasks/widgets.py
src/middlewared/middlewared/plugins/cloud_sync.py
src/middlewared/middlewared/rclone/base.py
src/middlewared/middlewared/rclone/remote/amazon_cloud_drive.py
src/middlewared/middlewared/rclone/remote/azureblob.py
src/middlewared/middlewared/rclone/remote/b2.py
src/middlewared/middlewared/rclone/remote/box.py
src/middlewared/middlewared/rclone/remote/dropbox.py
src/middlewared/middlewared/rclone/remote/ftp.py
src/middlewared/middlewared/rclone/remote/google_cloud_storage.py
src/middlewared/middlewared/rclone/remote/google_drive.py
src/middlewared/middlewared/rclone/remote/http.py
src/middlewared/middlewared/rclone/remote/hubic.py
src/middlewared/middlewared/rclone/remote/mega.py
src/middlewared/middlewared/rclone/remote/onedrive.py
src/middlewared/middlewared/rclone/remote/pcloud.py
src/middlewared/middlewared/rclone/remote/s3.py
src/middlewared/middlewared/rclone/remote/sftp.py
src/middlewared/middlewared/rclone/remote/webdav.py
src/middlewared/middlewared/rclone/remote/yandex.py
src/middlewared/middlewared/schema.py

https://redmine.ixsystems.com/issues/27364

--fast list option for cloud sync

---

gui/storage/views.py

This will make sure things can be restarted in a graceful state on unlock
Ticket: #35062

fix(storage/locking_volumes): Stop iocage jails before doing so

---

src/middlewared/middlewared/plugins/jail.py

- Rewrite plugin_get_versions to operate on a single plugin at a time
- Make it a private method
- Add caching to list_resource for remote resources
- Append a pkg version and plugin revision to remote plugin list_resources call
Ticket: #35431

feat(plugin/jail): Rewrite jail.plugin_get_versions

---

gui/freeadmin/static/lib/js/msg.js
gui/system/forms.py
gui/templates/freeadmin/index.html

fix(advanced/consolemsg): Show consolemsg correctly on update and load

---

src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/plugins/vm.py

Beginning of transition from a bunch of private API calls to fewer public ones handling those private parts.
TIcket: #35737

feat(vm/create): Create zvol's instead of the UI

---

src/middlewared/middlewared/plugins/vm.py

tkt-36808: fix(vm/vnc): Fix VNC for touch events and mobile

---

src/freenas/etc/directoryservice/DomainController/ctl

regenerate /etc/resolv.conf when disabling DC

---

src/middlewared/middlewared/plugins/network.py

Returns the interface the websocket is connected to.
Ticket:	#37168

feat(middlewared/network): implement interfaces.websocket_interface

---

src/middlewared/middlewared/plugins/etc.py

Write out files if they don't exist

---

src/freenas/usr/local/libexec/freenas-debug/afp/afp.sh
src/freenas/usr/local/libexec/freenas-debug/iscsi/iscsi.sh
src/freenas/usr/local/libexec/freenas-debug/ldap/ldap.sh
src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh
src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh

Ticket #35973
This was approved and merged into the master branch at PR #1449

fix(stable) remove enabled/disabled logic in freenas-debug

---

src/freenas/etc/ix.rc.d/ix-syslogd

fix(stable) remote syslog for truenas HA

---

src/freenas/etc/ix.rc.d/ix-syslogd

fix(master) remote syslog for truenas HA

---

src/freenas/usr/local/libexec/freenas-debug/doms/doms.sh

fix(stable) add M series hardware to doms.sh

---

gui/common/freenasdc.py
gui/common/freenasldap.py
gui/common/system.py
src/freenas/etc/directoryservice/rc.LDAP

Master kerberos auth
