truenas/middleware

src/middlewared/middlewared/restful.py
This PR adds ability to document return type of a method in HTTP API swagger docs.
Example screenshot:
=> NAS-120277 / 23.10 / Document return type in swagger API endpoints

src/middlewared/middlewared/restful.py
This PR adds ability to document return type of a method in HTTP API swagger docs.
Example screenshot:
Original PR: https://github.com/truenas/middleware/pull/10720
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120277
=> NAS-120277 / 22.12.2 / Document return type in swagger API endpoints (by sonicaj)

src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/failover_/disabled_reasons.py, src/middlewared/middlewared/plugins/failover_/utils.py
This is believed to be causing `failover.status` to sometimes take many minutes (30+) before it returns. This effects the login page since webUI calls this to determine if HA node or not. We also cache the response and listen for specific events to update the HA status so this is no longer needed. We also have a semaphore on the websocket server side to prevent a large amount of concurrent calls rendering this functionality even more useless.
Original PR: https://github.com/truenas/middleware/pull/10724
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120241
=> NAS-120241 / 22.12.2 / rm @throttle decorator from failover plugin (by yocalebo)

src/middlewared/middlewared/plugins/smb_/registry.py
This reverts a change to default parameters that was made between 13.0-U3.1 and 13.0-U4. Initial plan was to normalize how DOS attributes are stored between SCALE and Core (specifically as regards how file ids are generated and used), but upstream has since reverted changes to store a synthesized fileid based on inode birth time. Our temporary plan for now is to switch back to using inode number for this purpose (while evaluating other means of handling these).
=> NAS-120428 / 13.0 / Ensure that DOSATTRIB xattr is disabled

src/middlewared/middlewared/plugins/account.py, tests/api2/test_011_user.py
This switches implicit creation of non-existing path to having API user explicitly determine whether to create a homedir with the username.
=> NAS-120417 / 23.10 / Add ability to specify whether to create homedir

src/middlewared/middlewared/plugins/account.py, tests/api2/test_011_user.py
This switches implicit creation of non-existing path to having API user explicitly determine whether to create a homedir with the username.
Original PR: https://github.com/truenas/middleware/pull/10723
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120417
=> NAS-120417 / 22.12.2 / Add ability to specify whether to create homedir (by anodos325)

src/middlewared/middlewared/plugins/dns_client.py
CNAME records may be returned by python DNS when querying A or AAAA records. Since the middleware API supports explictly requesting certain types of records, add filtering that we only return the type requested. This PR also adds support for requesting CNAME records.
=> NAS-120427 / 23.10 / Expand handling for CNAME records in dnsclient

src/middlewared/middlewared/plugins/dns_client.py
CNAME records may be returned by python DNS when querying A or AAAA records. Since the middleware API supports explictly requesting certain types of records, add filtering that we only return the type requested. This PR also adds support for requesting CNAME records.
Original PR: https://github.com/truenas/middleware/pull/10730
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120427
=> NAS-120427 / 22.12.2 / Expand handling for CNAME records in dnsclient (by anodos325)

src/middlewared/middlewared/plugins/vpn.py
This PR handles a case where if you try to make a call like `midclt call openvpn.server.update '{"remove_certificates": true}'` and you don't have openvpn server configured already, it will error out with a ValueError because by default no `server` attribute is configured.
=> NAS-120416 / 23.10 / Handle case when no server is specified for openvpn server service

src/middlewared/middlewared/plugins/datastore/read.py, src/middlewared/middlewared/schema.py, src/middlewared/middlewared/validators.py
`query-filters` are always a list of lists (or in some cases tuples) of the form `[<key>, <op>, <val>]` or `['OR', <list of filters>]`. We should perform some basic schema validation to give users more helpful messages.
Example of unhelpful message:
```
root@truenas[/mnt/dozer/middleware/src/middlewared]# midclt call user.query '["bob"]'
Invalid operation: o
```
Example of more helpful message:
```
root@truenas[~]# midclt call user.query '["bob"]'
[EINVAL] query-filters: Item#0 is not valid per list types: [query-filter] Not a list
```
=> NAS-120280 / 23.10 / Add some validation for query-filters

src/middlewared/middlewared/plugins/datastore/read.py, src/middlewared/middlewared/schema.py, src/middlewared/middlewared/validators.py
`query-filters` are always a list of lists (or in some cases tuples) of the form `[<key>, <op>, <val>]` or `['OR', <list of filters>]`. We should perform some basic schema validation to give users more helpful messages.
Example of unhelpful message:
```
root@truenas[/mnt/dozer/middleware/src/middlewared]# midclt call user.query '["bob"]'
Invalid operation: o
```
Example of more helpful message:
```
root@truenas[~]# midclt call user.query '["bob"]'
[EINVAL] query-filters: Item#0 is not valid per list types: [query-filter] Not a list
```
Original PR: https://github.com/truenas/middleware/pull/10679
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120280
=> NAS-120280 / 22.12.2 / Add some validation for query-filters (by anodos325)

src/middlewared/middlewared/plugins/catalogs_linux/item_version.py, src/middlewared/middlewared/plugins/catalogs_linux/items.py
Last update field has been added to item/item versions in https://github.com/truenas/catalog_validation/pull/35 and this is a followup PR to add the attribute to items schema so it correctly reflects what we return.
=> NAS-120482 / 23.10 / Add last update field to schema

src/middlewared/middlewared/plugins/truecommand/update.py
This PR adds changes to make sure that standby node marks itself as DISABLED as currently it was following the same logic as master node but it got out of sync quickly because of how status is handled. It is dependant on API actions and TC events but both of them are not valid on the standby node as the db is updated directly.
Original PR: https://github.com/truenas/middleware/pull/10743
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120484
=> NAS-120484 / 22.12.2 / Mark truecommand service as disabled on standby node (by sonicaj)

src/middlewared/middlewared/plugins/vpn.py, src/middlewared/middlewared/plugins/vpn_/attachments.py
This PR adds changes to not raise a port conflict with openvpn server or any other service if `nobind` is set as that means the `port` field just points to the remove openvpn server's port and not it's own which would be selected dynamically by openvpn ( whichever is not in use ).
=> NAS-120295 / 23.10 / Do not raise port conflict error when nobind for openvpn client is set

src/middlewared/middlewared/plugins/vpn.py, src/middlewared/middlewared/plugins/vpn_/attachments.py
This PR adds changes to not raise a port conflict with openvpn server or any other service if `nobind` is set as that means the `port` field just points to the remove openvpn server's port and not it's own which would be selected dynamically by openvpn ( whichever is not in use ).
Original PR: https://github.com/truenas/middleware/pull/10751
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120295
=> NAS-120295 / 22.12.2 / Do not raise port conflict error when nobind for openvpn client is set (by sonicaj)

src/middlewared/middlewared/test/integration/assets/account.py
https://github.com/truenas/middleware/pull/10723 caused API tests regressions. This fixes it.
=> NAS-120488 / 23.10 / fix API tests

src/middlewared/middlewared/test/integration/assets/account.py
https://github.com/truenas/middleware/pull/10723 caused API tests regressions. This fixes it.
Original PR: https://github.com/truenas/middleware/pull/10742
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120488
=> NAS-120488 / 22.12.2 / fix API tests (by yocalebo)

src/middlewared/middlewared/plugins/catalogs_linux/sync_catalogs.py, src/middlewared/middlewared/plugins/kubernetes_linux/app_migrations.py, src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
This PR adds changes to allow apps to be migrated from one train to another. The changes are limited to `OFFICIAL` catalog for now.
Original PR: https://github.com/truenas/middleware/pull/10750
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120522
=> NAS-120522 / 22.12.2 / Allow apps to be migrated from one train to another (by sonicaj)

src/middlewared/middlewared/plugins/cluster_linux/utils.py
Typo in how we generated our list of paths to remove caused stale nodes file to exist which triggered issues for QE workflows to involve building / tearing down clusters.
=> NAS-120534 / 23.10 / Fix removal of ctdb_shared_volume files during teardown

src/middlewared/middlewared/plugins/cluster_linux/utils.py
Typo in how we generated our list of paths to remove caused stale nodes file to exist which triggered issues for QE workflows to involve building / tearing down clusters.
Original PR: https://github.com/truenas/middleware/pull/10762
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120534
=> NAS-120534 / 22.12.2 / Fix removal of ctdb_shared_volume files during teardown (by anodos325)

src/middlewared/middlewared/plugins/smb.py
When determining whether a mountpoint is a child of the current path, we should append path separator so that we don't generate false-positives in the following case
```
/mnt/dozer/SHARE
/mnt/dozer/SHARE2
```
=> NAS-120563 / 23.10 / Ensure we append path separator in SMB validation

src/middlewared/middlewared/plugins/smb.py
When determining whether a mountpoint is a child of the current path, we should append path separator so that we don't generate false-positives in the following case
```
/mnt/dozer/SHARE
/mnt/dozer/SHARE2
```
Original PR: https://github.com/truenas/middleware/pull/10770
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120563
=> NAS-120563 / 22.12.2 / Ensure we append path separator in SMB validation (by anodos325)

src/middlewared/middlewared/plugins/cluster_linux/ctdb_ips.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
Serialize write access to clustered IP address files via fcntl locks. This helps to avoid time-of-check / time-of-use issues when user is inadvertantly making changes via multiple nodes at once.
=> NAS-120569 / 23.10 / Cluster - change IPs under fcntl lock

src/middlewared/middlewared/plugins/cluster_linux/ctdb_ips.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
Serialize write access to clustered IP address files via fcntl locks. This helps to avoid time-of-check / time-of-use issues when user is inadvertantly making changes via multiple nodes at once.
Original PR: https://github.com/truenas/middleware/pull/10774
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120569
=> NAS-120569 / 22.12.2 / Cluster - change IPs under fcntl lock (by anodos325)

src/middlewared/middlewared/plugins/failover_/event.py
`udevadm settle` seems to be the most fault tolerant mechanism for properly waiting on disk events (in this scenario) to complete.
=> NAS-120590 / 23.10 / call device.settle_udev_events in failover plugin

src/middlewared/middlewared/plugins/enclosure.py, src/middlewared/middlewared/plugins/enclosure_/nvme.py
2 things done here:
1. `enclosure.set_slot_status` needs to be a NO-OP on R30 until the drive identification implementation can be done. It requires a separate module completely since identifying the nvme drives is done via ipmi raw commands which is something we don't have
2. `disk.query` returns slot information for each disk but `disk.sync_all` stores the namespace device of nvme drives (i.e. nvme1n1). `def map_r30` was returning the root character device (/dev/nvme1) instead of the 1st namespace device (/dev/nvme1n1) which is the only we use. This prevented `disk.query` from showing the enclosure slot mapping information which is required by the front-end team to map the drives to enclosure slots in the enclosure management section of the webUI.
=> NAS-120593 / 23.10 / add support for enclosure.sync_disk on R30

src/middlewared/middlewared/plugins/enclosure.py, src/middlewared/middlewared/plugins/enclosure_/nvme.py
2 things done here:
1. `enclosure.set_slot_status` needs to be a NO-OP on R30 until the drive identification implementation can be done. It requires a separate module completely since identifying the nvme drives is done via ipmi raw commands which is something we don't have
2. `disk.query` returns slot information for each disk but `disk.sync_all` stores the namespace device of nvme drives (i.e. nvme1n1). `def map_r30` was returning the root character device (/dev/nvme1) instead of the 1st namespace device (/dev/nvme1n1) which is the only we use. This prevented `disk.query` from showing the enclosure slot mapping information which is required by the front-end team to map the drives to enclosure slots in the enclosure management section of the webUI.
Original PR: …
=> NAS-120593 / 22.12.2 / add support for enclosure.sync_disk on R30 (by yocalebo)

src/middlewared/middlewared/plugins/system_advanced/config.py
A new endpoint was made available for the UI to consume which was separate from `system.advanced.update` and dedicated solely to allow changing GPU isolation settings. In the endpoint the changes were made in the database to reflect new user configuration but the system settings were not changed to reflect that change.
Similar to how we enforce how user supplied GPU isolation settings are applied in `system.advanced.update`, the same should be done for the newer dedicated endpoint.
=> NAS-120589 / 23.10 / Reflect GPU isolation changes on the system

cluster-tests/tests/directoryservices/test_001_activedirectory.py, src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/ldap.py, src/middlewared/middlewared/plugins/service_/services/ctdb.py, src/middlewared/middlewared/plugins/tdb/base.py, src/middlewared/middlewared/plugins/tdb/wrapper.py, src/middlewared/middlewared/service.py
If cluster is overall unhealthy (nodes missing), some of the nodes may still have a healthy copy of our DBs. Since TC wants to present users with at least some config info in this unhealthy state, we can check on per-db basis whether the data is healthy and return what we have.
Updates will still fail as expected.
=> NAS-120040 / 23.10 / Allow RO access to clustered config if DB healthy

cluster-tests/tests/directoryservices/test_001_activedirectory.py, src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/ldap.py, src/middlewared/middlewared/plugins/service_/services/ctdb.py, src/middlewared/middlewared/plugins/tdb/base.py, src/middlewared/middlewared/plugins/tdb/wrapper.py, src/middlewared/middlewared/service.py
If cluster is overall unhealthy (nodes missing), some of the nodes may still have a healthy copy of our DBs. Since TC wants to present users with at least some config info in this unhealthy state, we can check on per-db basis whether the data is healthy and return what we have.
Updates will still fail as expected.
Original PR: https://github.com/truenas/middleware/pull/10564
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120040
=> NAS-120040 / 22.12.2 / Allow RO access to clustered config if DB healthy (by anodos325)

src/middlewared/middlewared/plugins/system_advanced/config.py
A new endpoint was made available for the UI to consume which was separate from `system.advanced.update` and dedicated solely to allow changing GPU isolation settings. In the endpoint the changes were made in the database to reflect new user configuration but the system settings were not changed to reflect that change.
Similar to how we enforce how user supplied GPU isolation settings are applied in `system.advanced.update`, the same should be done for the newer dedicated endpoint.
Original PR: https://github.com/truenas/middleware/pull/10787
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120589
=> NAS-120589 / 22.12.2 / Reflect GPU isolation changes on the system (by Qubad786)

src/middlewared/middlewared/restful.py, src/middlewared/middlewared/schema.py
Currently the `OpenAPIResource.add_path` method was excluding routes with `{id}` from having their schema generated.
This seems to have been a bug accidentally included in [833fbfb](https://github.com/truenas/middleware/commit/833fbfb520168891f332de8a809ecbc18cff48b0) here:
Previously, a PUT route with `'{id}'` in the path (and 1 `accepts` arg etc) would:
- Pass the `elif` on line 230
- Fail the `if` on line 231
- End up within the `else` on 244
and as such, would have `opobject['requestBody']` set.
Now such a route fails the `elif` on (new) line 233, and thus doesn't have `opobject['requestBody']` set.
Additionally, the `Patch` class wasn't correctly updating the `title` field, but only the `name` field. This led to it having the same name, and as such, not actually being considered …
=> Bugfix: Allowed schema in openapi docs for {id} routes

src/middlewared/middlewared/plugins/acme_protocol_/authenticators/factory.py, src/middlewared/middlewared/plugins/acme_protocol_/authenticators/ovh.py
I know this is a bit unprompted, but I couldn't get the shell script route to work to add my domain registered at OVH to work with SSL certificates.
The code is more or less identical to the Cloudflare Authenticator, so it should work out of the box. One caveat is that OVH can only guarantee propagation to all DNS within 24 hours, in practice though I haven't had any case happen where propagation wasn't done within the hour.
Any comment / review is greatly appreciated for my first contribution to TrueNAS
=> Added OVH authenticator to list of ACME DNS providers

tests/api2/test_420_smb.py
These are relatively quick tests that ascertain whether internal libraries that samba uses work properly.
=> NAS-120643 / 23.10 / Add local smbtorture tests

tests/api2/test_420_smb.py
These are relatively quick tests that ascertain whether internal libraries that samba uses work properly.
Original PR: https://github.com/truenas/middleware/pull/10805
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120643
=> NAS-120643 / 22.12.2 / Add local smbtorture tests (by anodos325)

src/middlewared/middlewared/plugins/activedirectory_/dns.py
Resolver result may have different case than what we expected (for example manually added DNS entries rather than our dynamic updates).
=> NAS-120644 / 23.10 / Compare casefolded strings for hostnames

src/middlewared/middlewared/plugins/activedirectory_/dns.py
Resolver result may have different case than what we expected (for example manually added DNS entries rather than our dynamic updates).
Original PR: https://github.com/truenas/middleware/pull/10807
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120644
=> NAS-120644 / 22.12.2 / Compare casefolded strings for hostnames (by anodos325)

src/middlewared/middlewared/plugins/docker_linux/images.py
git cherry-pick -x cdbb28f47894a189dc40446c5af65570ac3e2ea7
git cherry-pick -x cadd7d8b757f6c0923a12ff5ae178cb594154ac2
Original PR: https://github.com/truenas/middleware/pull/10801
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120304
=> NAS-120304 / 22.12.2 / Increase private docker images password length to 4096 (by sonicaj)

src/middlewared/middlewared/plugins/cluster_linux/ctdb_job.py
This avoids more expensive check for glusterd status when we're checking for cluster jobs.
=> NAS-120650 / 23.10 / Use standardized check for whether we're clustered

src/middlewared/middlewared/plugins/cluster_linux/ctdb_job.py
This avoids more expensive check for glusterd status when we're checking for cluster jobs.
Original PR: https://github.com/truenas/middleware/pull/10811
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120650
=> NAS-120650 / 22.12.2 / Use standardized check for whether we're clustered (by anodos325)

src/middlewared/middlewared/apidocs/templates/websocket/query.md, src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/activedirectory_/dns.py, src/middlewared/middlewared/plugins/activedirectory_/health.py, src/middlewared/middlewared/plugins/kerberos.py, src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py, src/middlewared/middlewared/utils/__init__.py
Add special behavior where capital C prefix in filterop performs a casefolded version of
the filter. This is useful in cases where we're dealing with external protocols that are
case-insensitive, and will hopefully lead to fewer bugs related to case-insensitive checks.
=> NAS-120647 / 23.10 / Add some casefolded filters

src/middlewared/middlewared/etc_files/scst.conf.mako, tests/api2/test_261_iscsi_cmd.py
Use the recently added SCST setting `lb_per_pb_exp` to turn off reporting of LOGICAL BLOCKS PER PHYSICAL BLOCK EXPONENT by READ CAPACITY 16 when `pblocksize` is set.
=> NAS-120303 / 23.10 / fix pblocksize toggling

src/middlewared/middlewared/etc_files/scst.conf.mako, tests/api2/test_261_iscsi_cmd.py
Use the recently added SCST setting `lb_per_pb_exp` to turn off reporting of LOGICAL BLOCKS PER PHYSICAL BLOCK EXPONENT by READ CAPACITY 16 when `pblocksize` is set.
Original PR: https://github.com/truenas/middleware/pull/10818
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120303
=> NAS-120303 / 22.12.2 / fix pblocksize toggling (by bmeagherix)

src/middlewared/middlewared/plugins/network.py
Run the various hostnames in Core through the
Hostname validator to prevent invalid hostnames
from being used.
=> NAS-120677 / 13.0 / Properly validate hostnames

src/middlewared/middlewared/plugins/account.py, tests/api2/test_011_user.py
Typo in parameters being passed to create user homedir during new user creation caused spurious failure in case when user specified an exising path as a home directory. This fixes the bug and adds some more test coverage for path handling on new user creation.
=> NAS-120665 / 23.10 / Fix user creation permissions on homedir

src/middlewared/middlewared/plugins/account.py, tests/api2/test_011_user.py
Typo in parameters being passed to create user homedir during new user creation caused spurious failure in case when user specified an exising path as a home directory. This fixes the bug and adds some more test coverage for path handling on new user creation.
Original PR: https://github.com/truenas/middleware/pull/10819
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120665
=> NAS-120665 / 22.12.2 / Fix user creation permissions on homedir (by anodos325)

src/freenas/usr/local/sbin/disk_resize
There are NVMe SSDs that know about multipath, but do not support it. Passing that option makes namespace creation fail with INVALID FIELD status.  nvmecontrol sets the default based on NVMe capabilities.
=> NAS-120672 / 13.0 / Do not explicitly request multipath support for NVMe.

src/middlewared/middlewared/alert/source/enclosure_status.py
I traced the logic that was put into this alert back to a commit done in 2019. The changes done back then essentially ignored all alerts for an enclosure. I honestly couldn't deduce what the intended reasoning was for choosing to do it the way it was done. Maybe, it was a simple mistake, who knows? Either way, I've fixed the alerts for enclosures on SCALE with these changes. I referenced the logic that I put into CORE (when I rewrote all of this over there) so this should be mostly feature (and logic) parity.
Tested this by pulling a PSU from an enclosure and ensuring the proper alert was generated.
Original PR: https://github.com/truenas/middleware/pull/10826
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120666
=> NAS-120666 / 22.12.2 / fix enclosure alerts on SCALE (by yocalebo)

src/freenas/usr/local/sbin/disk_resize
There are NVMe SSDs that know about multipath, but do not support it. Passing that option makes namespace creation fail with INVALID FIELD status.  Unlike FreeBSD's nvmecontrol nvme is not clever enough to set the default based on NVMe capabilities, so do it manually.
=> NAS-120672 / 23.10 / Do not explicitly request multipath support for NVMe.

src/freenas/usr/local/sbin/disk_resize
There are NVMe SSDs that know about multipath, but do not support it. Passing that option makes namespace creation fail with INVALID FIELD status.  Unlike FreeBSD's nvmecontrol nvme is not clever enough to set the default based on NVMe capabilities, so do it manually.
Original PR: https://github.com/truenas/middleware/pull/10832
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120672
=> NAS-120672 / 22.12.2 / Do not explicitly request multipath support for NVMe. (by amotin)

src/middlewared/middlewared/etc_files/pam.d/pam.inc.mako, src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/registry_share.py, tests/api2/test_030_activedirectory.py
There are several moving parts when configuring the
`homes` share for AD users. This feature relies on
pam_mkhomedir to generate home directories for users
on an as-needed basis. This means that several procedures
need to happen:
1) pam_mkhomedir must be in pam-session block
2) intermediate directories for domain component must exist
for domains that will authenticate to our server.
3) winbindd configuration must be changed in order for the
template homedir utilize the homes share.
4) samba must be configured to obey pam restrictions
(so that pam_mkhomedir will be called when SMB session
started).
5) winbindd caches must be flushed out so that correct homedir
is returned in NSS queries.
This feature can be fragile, but has been around since the
days of FreeNAS 9 and so it cannot be …
=> NAS-120610 / 23.10 / Fix AD home shares in SCALE

src/middlewared/middlewared/etc_files/pam.d/pam.inc.mako, src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/registry_share.py, tests/api2/test_030_activedirectory.py
There are several moving parts when configuring the
`homes` share for AD users. This feature relies on
pam_mkhomedir to generate home directories for users
on an as-needed basis. This means that several procedures
need to happen:
1) pam_mkhomedir must be in pam-session block
2) intermediate directories for domain component must exist
for domains that will authenticate to our server.
3) winbindd configuration must be changed in order for the
template homedir utilize the homes share.
4) samba must be configured to obey pam restrictions
(so that pam_mkhomedir will be called when SMB session
started).
5) winbindd caches must be flushed out so that correct homedir
is returned in NSS queries.
This feature can be fragile, but has been around since the
days of FreeNAS 9 and so it cannot be …
=> NAS-120610 / 22.12.2 / Fix AD home shares in SCALE (by anodos325)

src/middlewared/middlewared/plugins/pool_/replace_disk.py
This was added over 4 years ago for freeBSD based product. It is now, currently, interfering with the proper operation of zed and zfsd on CORE and SCALE respectively.
=> NAS-119515 / 23.10 / fix hot-spare not auto-detaching after replace

src/middlewared/middlewared/plugins/pool_/replace_disk.py
This was added over 4 years ago for freeBSD based product. It is now, currently, interfering with the proper operation of zed and zfsd on CORE and SCALE respectively.
Original PR: https://github.com/truenas/middleware/pull/10839
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119515
=> NAS-119515 / 22.12.2 / fix hot-spare not auto-detaching after replace (by yocalebo)

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py, src/middlewared/middlewared/plugins/service_/services/kubernetes.py
This PR adds changes to ensure that required cgroup controllers are always present before attempting to start apps. We have been seeing this issue for various users where apps refused to work and kubernetes was not really giving us any good information wrt why it fails to start. It has been isolated that it is a kernel/systemd issue and not related to apps and OS team is working on isolating/diagnosing that appropriately. For now these changes will ensure we refuse to start apps and also raise an alert for apps when an attempt is made to start them outlining why it did not start.
=> NAS-120955 / 23.10 / Ensure required cgroup controllers are always present before starting apps

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
This PR adds changes to ensure that required cgroup controllers are always present before attempting to start apps. We have been seeing this issue for various users where apps refused to work and kubernetes was not really giving us any good information wrt why it fails to start. It has been isolated that it is a kernel/systemd issue and not related to apps and OS team is working on isolating/diagnosing that appropriately. For now these changes will ensure we refuse to start apps and also raise an alert for apps when an attempt is made to start them outlining why it did not start.
Original PR: https://github.com/truenas/middleware/pull/10838
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120955
=> NAS-120955 / 22.12.2 / Ensure required cgroup controllers are always present before starting apps (by sonicaj)

src/middlewared/middlewared/alert/source/failover_sync.py, src/middlewared/middlewared/plugins/failover_/datastore.py
The following scenario caused the alert to be generated during QE test cycle.
1. controller A is master controller
2. user initiates a failover via the webUI
3. controller B takes over as master and generates this alert
This alert shouldn't be generated since, almost always, a failover means a controller has been rebooted. This changes the logic just a bit to only generate this alert if we fail to sync the database after 20mins since some of the hardware platforms we sell can take roughly that amount of time to boot up.
=> NAS-120608 / 23.10 / fix alert being generated on user caused failover

src/middlewared/middlewared/alert/source/failover_sync.py, src/middlewared/middlewared/plugins/failover_/datastore.py
The following scenario caused the alert to be generated during QE test cycle.
1. controller A is master controller
2. user initiates a failover via the webUI
3. controller B takes over as master and generates this alert
This alert shouldn't be generated since, almost always, a failover means a controller has been rebooted. This changes the logic just a bit to only generate this alert if we fail to sync the database after 20mins since some of the hardware platforms we sell can take roughly that amount of time to boot up.
Original PR: https://github.com/truenas/middleware/pull/10840
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120608
=> NAS-120608 / 22.12.2 / fix alert being generated on user caused failover (by yocalebo)

src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh
This does 2 things:
1. adds `storcli show`
2. and adds `storcli /c<x> show all` based on number of detected HBAs
This might not have everything compared to CORE's `mprutils` commands, but it's way better than what we're currently doing (nothing).
=> NAS-119244 / 23.10 / add storcli /c<x> show all in debug

src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh
This does 2 things:
1. adds `storcli show`
2. and adds `storcli /c<x> show all` based on number of detected HBAs
This might not have everything compared to CORE's `mprutils` commands, but it's way better than what we're currently doing (nothing).
Original PR: https://github.com/truenas/middleware/pull/10848
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119244
=> NAS-119244 / 22.12.2 / add storcli /c<x> show all in debug (by yocalebo)

src/middlewared/middlewared/etc_files/scst.conf.mako, src/middlewared/middlewared/plugins/iscsi_/iscsi_global.py, tests/api2/test_261_iscsi_cmd.py, tests/protocols/__init__.py, tests/protocols/iSNSP/client.py, tests/protocols/iSNSP/exceptions.py, tests/protocols/iSNSP/packet.py, tests/runtest.py
Add iSNS support.
Some additional context ...
- The existing Linux(/FreeBSD) iSNS client software (included in [open-isns](https://github.com/open-iscsi/open-isns)) and MS iSNS server do not play very well together, so implemented a _minimal_ subset of iSNS (client) in python to side-step the issue when running tests.  (Only used in tests.)
- Added parameter `--isns_ip` to _runtest.py_ (with a default value pointing to our MS iSNS server)
- While in there, likewise added `--pool` (defaults to "tank" as was previously hard-coded).  Also allow `-s` to be passed thru to `pytest`.
- Previously we were validating the format of the input, but not checking connectivity.  Add this.
- At the moment SCST only supports a single iSNS server, whereas the UI allows multiple.  Have implemented the …
=> NAS-106086 / 23.10 / Add support for iSNS servers in scst

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py, src/middlewared/middlewared/plugins/kubernetes_linux/utils.py
This PR addresses a regression caused by recent changes where we validate that all supported controllers are actually available for consumption but it did not take into account that on some systems after a reboot not all supported controllers are automatically added to available controllers for consumption. So now we try to do that first and don't error out if that is not happening ( as we have seen for users where `cpuset` refused to become part of available controllers ) as that is handled already and we refuse to start k8s in that case.
=> NAS-120978 / 23.10 / Fix all supported controllers not being added to available controllers

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py, src/middlewared/middlewared/plugins/kubernetes_linux/utils.py
This PR addresses a regression caused by recent changes where we validate that all supported controllers are actually available for consumption but it did not take into account that on some systems after a reboot not all supported controllers are automatically added to available controllers for consumption. So now we try to do that first and don't error out if that is not happening ( as we have seen for users where `cpuset` refused to become part of available controllers ) as that is handled already and we refuse to start k8s in that case.
Original PR: https://github.com/truenas/middleware/pull/10851
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120978
=> NAS-120978 / 22.12.3 / Fix all supported controllers not being added to available controllers (by sonicaj)

cluster-tests/tests/directoryservices/test_002_ldap.py, src/middlewared/middlewared/plugins/ldap.py
This feature is a significant deviation from best-practice in general (in that the filer has access to NT hashes for all LDAP + SMB users) and removing from clustered product reduces overall maintenance overhead.
=> NAS-120999 / 23.10 / Remove legacy LDAP SMB support from clustered TrueNAS

cluster-tests/tests/directoryservices/test_002_ldap.py, src/middlewared/middlewared/plugins/ldap.py
This feature is a significant deviation from best-practice in general (in that the filer has access to NT hashes for all LDAP + SMB users) and removing from clustered product reduces overall maintenance overhead.
Original PR: https://github.com/truenas/middleware/pull/10854
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120999
=> NAS-120999 / 22.12.3 / Remove legacy LDAP SMB support from clustered TrueNAS (by anodos325)

src/middlewared/middlewared/plugins/failover.py
This is a particularly "hot" code-path and it's producing quite a bit of log spam on an HA system when other side is rebooted. This prevents, ideally, logs from being generated when that occurs.
=> NAS-121009 / 23.10 / prevent log spam in failover.mismatch_disks

src/middlewared/middlewared/plugins/failover.py
This is a particularly "hot" code-path and it's producing quite a bit of log spam on an HA system when other side is rebooted. This prevents, ideally, logs from being generated when that occurs.
Original PR: https://github.com/truenas/middleware/pull/10856
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121009
=> NAS-121009 / 22.12.2 / prevent log spam in failover.mismatch_disks (by yocalebo)

src/middlewared/middlewared/plugins/failover.py
This is a particularly "hot" code-path and it's producing quite a bit of log spam on an HA system when other side is rebooted. This prevents, ideally, logs from being generated when that occurs.
Original PR: https://github.com/truenas/middleware/pull/10856
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121009
=> NAS-121009 / 22.12.3 / prevent log spam in failover.mismatch_disks (by yocalebo)

tests/runtest.py
Accidently left this out of recent commit (d96486e) that included an enhancement to runtest.py
=> NAS-121016 / 23.10 / Add pool to option_list

src/middlewared/middlewared/plugins/ldap.py, tests/api2/test_275_ldap.py
This particular configuration is somewhat unsafe (in that the filer has access to NT hashes on LDAP server) and relies on a feature that upstream samba has also marked as deprecated. In Cobia we will mark as deprecated (generating alert when LDAP is running with samba schema) and then remove option entirely in version after Cobia. Note that the problem is how the LDAP server is configured and not internal to TrueNAS itself. We have been warning about this being removed in a future version since TrueNAS 12/13.
=> NAS-121000 / 23.10 / Deprecate LDAP with Samba schema

src/middlewared/middlewared/async_validators.py, src/middlewared/middlewared/plugins/account.py, tests/api2/test_011_user.py
Give explicit guidance in validation error messages about non-existent homedirs and also run homedir path through our standard method of path validation (to catch any more subtle errors in the path).
This also fixes an error where non-existent home directories were bypassing validation and error was being caught by filesystem plugin.
The PR also addresses issues where validation for user creation and update could potentially block main loop by running the homedir validation in a separate thread.
New tests were added to validate the following behavior:
1) Update of user to change home directory to an existing path.
We check that path owner changed to user in question.
2) Creation of user with non-existing home directory base dir fails
with a Validation Error.
3) Update of user to change …
=> NAS-121023 / 23.10 / Improve user homedir validation errors

src/middlewared/middlewared/async_validators.py, src/middlewared/middlewared/plugins/account.py, tests/api2/test_011_user.py
Give explicit guidance in validation error messages about non-existent homedirs and also run homedir path through our standard method of path validation (to catch any more subtle errors in the path).
This also fixes an error where non-existent home directories were bypassing validation and error was being caught by filesystem plugin.
The PR also addresses issues where validation for user creation and update could potentially block main loop by running the homedir validation in a separate thread.
New tests were added to validate the following behavior:
1) Update of user to change home directory to an existing path.
We check that path owner changed to user in question.
2) Creation of user with non-existing home directory base dir fails
with a Validation Error.
3) Update of user to change …
=> NAS-121023 / 22.12.3 / Improve user homedir validation errors (by anodos325)

src/middlewared/middlewared/async_validators.py, src/middlewared/middlewared/plugins/account.py, tests/api2/test_011_user.py
Give explicit guidance in validation error messages about non-existent homedirs and also run homedir path through our standard method of path validation (to catch any more subtle errors in the path).
This also fixes an error where non-existent home directories were bypassing validation and error was being caught by filesystem plugin.
The PR also addresses issues where validation for user creation and update could potentially block main loop by running the homedir validation in a separate thread.
New tests were added to validate the following behavior:
1) Update of user to change home directory to an existing path.
We check that path owner changed to user in question.
2) Creation of user with non-existing home directory base dir fails
with a Validation Error.
3) Update of user to change …
=> NAS-121023 / 22.12.2 / Improve user homedir validation errors (by anodos325)

src/middlewared/middlewared/main.py
Noticed when I was troubleshooting an unrelated issue. I often do `systemctl restart middlewared`. This can finish before a `ws.prepare(request)` returns. When this happens, a `ConnectionRefusedError` is raised and looks pretty nasty in the logs. This PR accounts for this scenario.
Original PR: https://github.com/truenas/middleware/pull/10863
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121028
=> NAS-121028 / 22.12.3 / add create_and_prepare_ws() (by yocalebo)

src/middlewared/middlewared/plugins/disk_/wipe.py, tests/api2/test_disk_wipe.py
When we wipe partition information from a disk using this method, we must open the device again to trigger udev events so the udev cache for the partition information for the disk that we just wiped is updated to reflect reality. Without these changes, middleware will still show a device as having partition labels on it when it doesn't.
=> NAS-121034 / 23.10 / generate a udev event after disk has been wiped

src/middlewared/middlewared/plugins/disk_/wipe.py, tests/api2/test_disk_wipe.py
When we wipe partition information from a disk using this method, we must open the device again to trigger udev events so the udev cache for the partition information for the disk that we just wiped is updated to reflect reality. Without these changes, middleware will still show a device as having partition labels on it when it doesn't.
Original PR: https://github.com/truenas/middleware/pull/10865
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121034
=> NAS-121034 / 22.12.2 / generate a udev event after disk has been wiped (by yocalebo)

src/middlewared/middlewared/plugins/disk_/wipe.py, tests/api2/test_disk_wipe.py
When we wipe partition information from a disk using this method, we must open the device again to trigger udev events so the udev cache for the partition information for the disk that we just wiped is updated to reflect reality. Without these changes, middleware will still show a device as having partition labels on it when it doesn't.
Original PR: https://github.com/truenas/middleware/pull/10865
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121034
=> NAS-121034 / 22.12.3 / generate a udev event after disk has been wiped (by yocalebo)

tests/api2/test_420_smb.py
These are relatively quick tests that ascertain whether internal libraries that samba uses work properly.
Original PR: https://github.com/truenas/middleware/pull/10805
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120643
=> NAS-120643 / 13.0 / Add local smbtorture tests (by anodos325)

src/middlewared/middlewared/plugins/failover_/detect_enclosure.py
This fixes 2 primary problems.
1. correctly identify whether the controller is in the `A` or `B` position of the head-unit
2. We were caching the return of this method twice. Once on class and one via the functools.cache decorator.
While I'm here, i've cleaned this method up a bit to make it more concise.
=> NAS-121064 / 23.10 / fix x controller position detection logic

src/middlewared/middlewared/plugins/failover_/detect_enclosure.py
This fixes 2 primary problems.
1. correctly identify whether the controller is in the `A` or `B` position of the head-unit
2. We were caching the return of this method twice. Once on class and one via the functools.cache decorator.
While I'm here, i've cleaned this method up a bit to make it more concise.
Original PR: https://github.com/truenas/middleware/pull/10880
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121064
=> NAS-121064 / 22.12.3 / fix x controller position detection logic (by yocalebo)

src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
When a failover occurs on an HA system and the login page is shown, the login page will give human readable reasons for why HA is unhealthy. During testing of this functionality, I've noticed that the login page will show `No zpools configured` immediately during a failover event. This is because the webUI is calling `failover.disabled.reasons` and we're returning that. However, we're not considering the fact that the controller that the user is logging into is actually processing a failover event. In that scenario, we'll show that the local system is processing a failover event and return early. This will ease the confusion that QE/customers experience when they perform a manual failover.
=> NAS-121059 / 23.10 / add LOC_FAILOVER_ONGOING to HA disabled reasons

src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
When a failover occurs on an HA system and the login page is shown, the login page will give human readable reasons for why HA is unhealthy. During testing of this functionality, I've noticed that the login page will show `No zpools configured` immediately during a failover event. This is because the webUI is calling `failover.disabled.reasons` and we're returning that. However, we're not considering the fact that the controller that the user is logging into is actually processing a failover event. In that scenario, we'll show that the local system is processing a failover event and return early. This will ease the confusion that QE/customers experience when they perform a manual failover.
Original PR: https://github.com/truenas/middleware/pull/10877
Jira URL: …
=> NAS-121059 / 22.12.3 / add LOC_FAILOVER_ONGOING to HA disabled reasons (by yocalebo)

tests/api2/test_420_smb.py
This particular local smbtorture test was removed
in Samba 4.18
=> NAS-121080 / 23.10 / Remove local.compression test

src/middlewared/middlewared/plugins/vm/vms.py
We are seeing another edge case with VMs where if libvirt socket is closed and we try to query VMs it fails as the socket is not re-initialized and we try to update the domain.
The failure happens when middleware tries to retrieve status of the VM and covering the usage there making sure that libvirt socket is initialised before we try to retrieve the status of the VM. For performance it is only done once in VM extend context to avoid making the same call - the drawback is that if during the query call libvirt socket fails it will result in a crash but a subsequent VM query call will work.
=> NAS-121086 / 23.10 / Fix libvirt socket closed edge case when querying VMs

src/middlewared/middlewared/plugins/vm/vms.py
We are seeing another edge case with VMs where if libvirt socket is closed and we try to query VMs it fails as the socket is not re-initialized and we try to update the domain.
The failure happens when middleware tries to retrieve status of the VM and covering the usage there making sure that libvirt socket is initialised before we try to retrieve the status of the VM. For performance it is only done once in VM extend context to avoid making the same call - the drawback is that if during the query call libvirt socket fails it will result in a crash but a subsequent VM query call will work.
Original PR: https://github.com/truenas/middleware/pull/10895
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121086
=> NAS-121086 / 22.12.2 / Fix libvirt socket closed edge case when querying VMs (by Qubad786)

src/middlewared/middlewared/plugins/vm/vms.py
We are seeing another edge case with VMs where if libvirt socket is closed and we try to query VMs it fails as the socket is not re-initialized and we try to update the domain.
The failure happens when middleware tries to retrieve status of the VM and covering the usage there making sure that libvirt socket is initialised before we try to retrieve the status of the VM. For performance it is only done once in VM extend context to avoid making the same call - the drawback is that if during the query call libvirt socket fails it will result in a crash but a subsequent VM query call will work.
Original PR: https://github.com/truenas/middleware/pull/10895
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121086
=> NAS-121086 / 22.12.3 / Fix libvirt socket closed edge case when querying VMs (by Qubad786)

src/middlewared/middlewared/plugins/failover_/virtual_ips.py
Primary problem being fixed here is to make sure that the interface being checked actually has carrier. In this particular instance `eno2` was showing as being in `BACKUP` state on the master controller. Checking the other controller, it wasn't showing the VIP either. Investigating a little further, the interface was down. I also cleaned up this plugin while I was here.
=> NAS-121074 / 23.10 / fix failover.vip.get_states

src/middlewared/middlewared/plugins/failover_/virtual_ips.py
Primary problem being fixed here is to make sure that the interface being checked actually has carrier. In this particular instance `eno2` was showing as being in `BACKUP` state on the master controller. Checking the other controller, it wasn't showing the VIP either. Investigating a little further, the interface was down. I also cleaned up this plugin while I was here.
Original PR: https://github.com/truenas/middleware/pull/10899
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121074
=> NAS-121074 / 22.12.2 / fix failover.vip.get_states (by yocalebo)

src/middlewared/middlewared/plugins/failover_/virtual_ips.py
Primary problem being fixed here is to make sure that the interface being checked actually has carrier. In this particular instance `eno2` was showing as being in `BACKUP` state on the master controller. Checking the other controller, it wasn't showing the VIP either. Investigating a little further, the interface was down. I also cleaned up this plugin while I was here.
Original PR: https://github.com/truenas/middleware/pull/10899
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121074
=> NAS-121074 / 22.12.3 / fix failover.vip.get_states (by yocalebo)

src/middlewared/middlewared/plugins/ipmi.py, src/middlewared/middlewared/plugins/ipmi_/chassis.py
After discussion with webUI team, the current ipmi.identify implementation is clunky and not very user friendly. This adds a new plugin that uses a different tool which is much easier to use (and quicker to respond).
I've also added a `ipmi.chassis.query` method to get the status on whether or not the chassis identify light has been toggled.
Currently, we do not allow user to specify a timeout for when the light turns off. It's either on indefinitely, or off.
=> NAS-121055 / 23.10 / add ipmi.chassis plugin

src/middlewared/middlewared/plugins/activedirectory_/dns.py, src/middlewared/middlewared/plugins/smb.py
We must restrict SMB bind ips and dynamically registered IP addresses to TrueNAS HA Virtual IPs. Otherwise clients may attempt to connect to the wrong storage node.
=> NAS-121058 / 23.10 / Only register HA VIPs during AD dynamic DNS updates

src/middlewared/middlewared/plugins/ipmi.py, src/middlewared/middlewared/plugins/ipmi_/chassis.py
After discussion with webUI team, the current ipmi.identify implementation is clunky and not very user friendly. This adds a new plugin that uses a different tool which is much easier to use (and quicker to respond).
I've also added a `ipmi.chassis.query` method to get the status on whether or not the chassis identify light has been toggled.
Currently, we do not allow user to specify a timeout for when the light turns off. It's either on indefinitely, or off.
Original PR: https://github.com/truenas/middleware/pull/10908
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121055
=> NAS-121055 / 22.12.2 / add ipmi.chassis plugin (by yocalebo)

src/middlewared/middlewared/plugins/activedirectory_/dns.py, src/middlewared/middlewared/plugins/smb.py
We must restrict SMB bind ips and dynamically registered IP addresses to TrueNAS HA Virtual IPs. Otherwise clients may attempt to connect to the wrong storage node.
Original PR: https://github.com/truenas/middleware/pull/10878
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121058
=> NAS-121058 / 22.12.3 / Only register HA VIPs during AD dynamic DNS updates (by anodos325)

src/middlewared/middlewared/plugins/ipmi.py, src/middlewared/middlewared/plugins/ipmi_/chassis.py
After discussion with webUI team, the current ipmi.identify implementation is clunky and not very user friendly. This adds a new plugin that uses a different tool which is much easier to use (and quicker to respond).
I've also added a `ipmi.chassis.query` method to get the status on whether or not the chassis identify light has been toggled.
Currently, we do not allow user to specify a timeout for when the light turns off. It's either on indefinitely, or off.
Original PR: https://github.com/truenas/middleware/pull/10908
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121055
=> NAS-121055 / 22.12.3 / add ipmi.chassis plugin (by yocalebo)

src/middlewared/middlewared/plugins/activedirectory_/dns.py, src/middlewared/middlewared/plugins/smb.py
We must restrict SMB bind ips and dynamically registered IP addresses to TrueNAS HA Virtual IPs. Otherwise clients may attempt to connect to the wrong storage node.
Original PR: https://github.com/truenas/middleware/pull/10878
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121058
=> NAS-121058 / 22.12.2 / Only register HA VIPs during AD dynamic DNS updates (by anodos325)

src/middlewared/middlewared/etc_files/exports.mako, src/middlewared/middlewared/plugins/nfs.py, src/middlewared/middlewared/plugins/nfs_/utils.py, tests/api2/test_300_nfs.py
See `man 5 exports` for list of valid wildcards.
Rules:
* Wildcards are allowed only in the left most level
* If the name is multiple levels, the levels below must be resolvable
Updated _exports.mako_ to allow wildcards.
Extended test 32 in _test_300_nfs.py_ to include wildcard hostnames.
Fixed a few `flake8` complaints.
=> NAS-120616 / 23.10 / Added support for wildcarded NFS hostnames

src/middlewared/middlewared/etc_files/exports.mako, src/middlewared/middlewared/plugins/nfs.py, src/middlewared/middlewared/plugins/nfs_/utils.py, tests/api2/test_300_nfs.py
See `man 5 exports` for list of valid wildcards.
Rules:
* Wildcards are allowed only in the left most level
* If the name is multiple levels, the levels below must be resolvable
Updated _exports.mako_ to allow wildcards.
Extended test 32 in _test_300_nfs.py_ to include wildcard hostnames.
Fixed a few `flake8` complaints.
Original PR: https://github.com/truenas/middleware/pull/10879
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120616
=> NAS-120616 / 22.12.3 / Added support for wildcarded NFS hostnames (by mgrimesix)

src/middlewared/middlewared/plugins/activedirectory.py
Beginning in 22.12.0 we began to use nsupdate to perform dynamic DNS updates for active directory. libads with MIT kerberos wouldn't successfully perform these while we were working on the transition to building with MIT kerberos, but it appears that issue is now fixed. This PR prevents libads from performing DNS updates during domain join so that we have finer-grained control over this in middleware.
Original PR: https://github.com/truenas/middleware/pull/10921
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121130
=> NAS-121130 / 22.12.3 / prevent libads from performing DNS updates (by anodos325)

src/middlewared/middlewared/plugins/activedirectory.py
Beginning in 22.12.0 we began to use nsupdate to perform dynamic DNS updates for active directory. libads with MIT kerberos wouldn't successfully perform these while we were working on the transition to building with MIT kerberos, but it appears that issue is now fixed. This PR prevents libads from performing DNS updates during domain join so that we have finer-grained control over this in middleware.
Original PR: https://github.com/truenas/middleware/pull/10921
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121130
=> NAS-121130 / 22.12.2 / prevent libads from performing DNS updates (by anodos325)

src/middlewared/middlewared/plugins/disk_/retaste.py, src/middlewared/middlewared/plugins/failover_/event.py, src/middlewared/middlewared/plugins/pool_/export.py, src/middlewared/middlewared/plugins/pool_/pool.py
1. in `disk.retaste` method, I now call `BLKRRPART` which tells kernel to force reread partition tables on the disk. (I also log any type of errors that might occur while I'm there)
2. Remove the `disk.retaste` call on failover event since that seems to have caused all of the problems that we've been experiencing.
=> NAS-121017 / 23.10 / fix disk.retaste and, hopefully, SCALE HA failover events

src/middlewared/middlewared/plugins/disk_/retaste.py, src/middlewared/middlewared/plugins/failover_/event.py, src/middlewared/middlewared/plugins/pool.py
1. in `disk.retaste` method, I now call `BLKRRPART` which tells kernel to force reread partition tables on the disk. (I also log any type of errors that might occur while I'm there)
2. Remove the `disk.retaste` call on failover event since that seems to have caused all of the problems that we've been experiencing.
Original PR: https://github.com/truenas/middleware/pull/10918
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121017
=> NAS-121017 / 22.12.3 / fix disk.retaste and, hopefully, SCALE HA failover events (by yocalebo)

src/middlewared/middlewared/plugins/disk_/retaste.py, src/middlewared/middlewared/plugins/failover_/event.py, src/middlewared/middlewared/plugins/pool.py
1. in `disk.retaste` method, I now call `BLKRRPART` which tells kernel to force reread partition tables on the disk. (I also log any type of errors that might occur while I'm there)
2. Remove the `disk.retaste` call on failover event since that seems to have caused all of the problems that we've been experiencing.
Original PR: https://github.com/truenas/middleware/pull/10918
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121017
=> NAS-121017 / 22.12.2 / fix disk.retaste and, hopefully, SCALE HA failover events (by yocalebo)

src/middlewared/middlewared/plugins/activedirectory_/dns.py, src/middlewared/middlewared/plugins/smb.py
The common_validation method for activedirectory plugin gets called during AD status checks. This is a safeguard against radically misconfigured active directory settings as failure will result in the AD service being disabled.
Starting in 22.12 the validation was expanded to also include making sure that forward lookup of our hostname returns ips that are ours. In the HA case though it is expected that failover be enabled and FAULTED when on the standby controller. The status is changed to healthy during a failover event when the data pool along with system dataset and secrets file stored there is imported (and directoryservices.setup is called).
This commit slightly alters the set of IP addresses used for validation when checking whether the name is ours by using smb.bindip_choices …
=> NAS-121141 / 23.10 / Don't disable AD on passive controller

src/middlewared/middlewared/plugins/activedirectory_/dns.py, src/middlewared/middlewared/plugins/smb.py
The common_validation method for activedirectory plugin gets called during AD status checks. This is a safeguard against radically misconfigured active directory settings as failure will result in the AD service being disabled.
Starting in 22.12 the validation was expanded to also include making sure that forward lookup of our hostname returns ips that are ours. In the HA case though it is expected that failover be enabled and FAULTED when on the standby controller. The status is changed to healthy during a failover event when the data pool along with system dataset and secrets file stored there is imported (and directoryservices.setup is called).
This commit slightly alters the set of IP addresses used for validation when checking whether the name is ours by using smb.bindip_choices …
=> NAS-121141 / 22.12.2 / Don't disable AD on passive controller (by anodos325)

src/middlewared/middlewared/plugins/activedirectory_/dns.py, src/middlewared/middlewared/plugins/smb.py
The common_validation method for activedirectory plugin gets called during AD status checks. This is a safeguard against radically misconfigured active directory settings as failure will result in the AD service being disabled.
Starting in 22.12 the validation was expanded to also include making sure that forward lookup of our hostname returns ips that are ours. In the HA case though it is expected that failover be enabled and FAULTED when on the standby controller. The status is changed to healthy during a failover event when the data pool along with system dataset and secrets file stored there is imported (and directoryservices.setup is called).
This commit slightly alters the set of IP addresses used for validation when checking whether the name is ours by using smb.bindip_choices …
=> NAS-121141 / 22.12.3 / Don't disable AD on passive controller (by anodos325)

src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/failover_/event.py
When systemd is handling reboot of an HA server, a race condition may be exposed whereby fenced is stopped before pool is exported. This can result in the now-passive controller halting IO to the zpool and hanging in a state that requires server reset in order to recover. This PR makes a couple of minor changes:
1) On active (rebooting) controller, we no longer stop the fenced
process when processing a shutdown event in middleware.
2) On standby (becoming active) controller, we poll the fenced for
remote node for up to 10 seconds (repeating if other side has
fenced running) to give time for fenced to stop / controller
reboot.
Original PR: https://github.com/truenas/middleware/pull/10937
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121133
=> NAS-121133 / 22.12.3 / Fix failover via rebooting active controller (by anodos325)

src/middlewared/middlewared/plugins/failover_/event.py
As of NAS-121133 storage controllers now poll for getting persistent reservations while becoming VRRP master. This now opens up a window in which to hang onto them on the standby controller a little longer to ensure that pools are fully exported before granting the master access to the disks.
=> NAS-121153 / 23.10 / Shift timing of fenced stop

src/middlewared/middlewared/plugins/failover_/event.py
As of NAS-121133 storage controllers now poll for getting persistent reservations while becoming VRRP master. This now opens up a window in which to hang onto them on the standby controller a little longer to ensure that pools are fully exported before granting the master access to the disks.
Original PR: https://github.com/truenas/middleware/pull/10941
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121153
=> NAS-121153 / 22.12.3 / Shift timing of fenced stop (by anodos325)

src/middlewared/middlewared/plugins/failover_/event.py
When we become vrrp_backup we restart the keepalived process through middlewared. For historic reasons, service operations through middleware are propagated to the other storage controller. In this case under the right circumstances, the HA propagation could lead to queued failover events and ping-pong between nodes.
=> NAS-121157 / 23.10 / avoid propagating keepalived restart

src/middlewared/middlewared/plugins/failover_/event.py
When we become vrrp_backup we restart the keepalived process through middlewared. For historic reasons, service operations through middleware are propagated to the other storage controller. In this case under the right circumstances, the HA propagation could lead to queued failover events and ping-pong between nodes.
Original PR: https://github.com/truenas/middleware/pull/10944
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121157
=> NAS-121157 / 22.12.3 / avoid propagating keepalived restart (by anodos325)

src/middlewared/middlewared/plugins/failover_/event.py
When we become vrrp_backup we restart the keepalived process through middlewared. For historic reasons, service operations through middleware are propagated to the other storage controller. In this case under the right circumstances, the HA propagation could lead to queued failover events and ping-pong between nodes.
Original PR: https://github.com/truenas/middleware/pull/10944
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121157
=> NAS-121157 / 22.12.2 / avoid propagating keepalived restart (by anodos325)

src/middlewared/middlewared/common/attachment/certificate.py, src/middlewared/middlewared/plugins/chart_releases_linux/cert_attachments.py, src/middlewared/middlewared/plugins/crypto_/attachments.py, src/middlewared/middlewared/plugins/crypto_/certificate_authorities.py, src/middlewared/middlewared/plugins/crypto_/certificates.py, src/middlewared/middlewared/plugins/crypto_/dependencies.py, src/middlewared/middlewared/plugins/ftp_/cert_attachment.py, src/middlewared/middlewared/plugins/idmap_/cert_attachments.py, src/middlewared/middlewared/plugins/kmip/attachment.py, src/middlewared/middlewared/plugins/ldap_/cert_attachments.py, src/middlewared/middlewared/plugins/s3_/attachments.py, src/middlewared/middlewared/plugins/system/cert_attachments.py, src/middlewared/middlewared/plugins/vpn_/cert_attachments.py, src/middlewared/middlewared/plugins/webdav_/cert_attachments.py
This PR adds changes to be more descriptive about which service is consuming a certificate when deleting a certificate. New changes have the following format:
```
❯ midclt call certificate.check_cert_deps 7
[EFAULT] Certificate is being used by following service(s):
1) 'collabora' Applications
2) OpenVPN Client Service
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 200, in call_method
result = await self.middleware._call(message['method'], serviceobj, methodobj, params, app=self)
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1336, in _call
return await methodobj(*prepared_call.args)
File "/usr/lib/python3/dist-packages/middlewared/plugins/crypto_/dependencies.py", line 12, in check_cert_deps
raise …
```
=> NAS-120144 / 23.10 / Improve error reporting when deleting a certificate

src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
Spoke with hardware platform team about this because, apparently, we were missing nvdimm types as well as incorrectly identifying others.
Original PR: https://github.com/truenas/middleware/pull/10956
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121148
=> NAS-121148 / 22.12.2 / fix mseries.nvdimm.info (by yocalebo)

src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
Spoke with hardware platform team about this because, apparently, we were missing nvdimm types as well as incorrectly identifying others.
Original PR: https://github.com/truenas/middleware/pull/10956
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121148
=> NAS-121148 / 22.12.3 / fix mseries.nvdimm.info (by yocalebo)

src/middlewared/middlewared/plugins/filesystem_/acl_base.py, src/middlewared/middlewared/plugins/filesystem_/acl_linux.py, tests/api2/test_340_pool_dataset.py
There are a large category of apps that are extremely poorly designed and will fail to deploy if they are unable to recursively chown paths presented to them.
Although it is debatable about whether one should try to support something so haphazardly developed, we can present a knob for at least NFSv4 acltype to allow administrator to grant chown / chmod rights to these IDs on a per-host-path basis.
=> NAS-121144 / 23.10 / Allow adding FULL_CONTROL to ACL for apps

src/middlewared/middlewared/plugins/filesystem_/acl_base.py, src/middlewared/middlewared/plugins/filesystem_/acl_linux.py, tests/api2/test_340_pool_dataset.py
There are a large category of apps that are extremely poorly designed and will fail to deploy if they are unable to recursively chown paths presented to them.
Although it is debatable about whether one should try to support something so haphazardly developed, we can present a knob for at least NFSv4 acltype to allow administrator to grant chown / chmod rights to these IDs on a per-host-path basis.
Original PR: https://github.com/truenas/middleware/pull/10928
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121144
=> NAS-121144 / 22.12.3 / Allow adding FULL_CONTROL to ACL for apps (by anodos325)

src/middlewared/middlewared/plugins/pool_/dataset_details.py
This was supposed to be fixed in 22.12.1 and I added the `readonly` attribute to the data we gather, however, I never added the key in the response. This means webUI is still trying to probe datasets that are encrypted which raises a CallError. This simply adds it so that the webUI will behave as intended.
=> NAS-121088 / 23.10 / fix missing readonly property

src/middlewared/middlewared/plugins/pool_/dataset_details.py
This was supposed to be fixed in 22.12.1 and I added the `readonly` attribute to the data we gather, however, I never added the key in the response. This means webUI is still trying to probe datasets that are encrypted which raises a CallError. This simply adds it so that the webUI will behave as intended.
Original PR: https://github.com/truenas/middleware/pull/10991
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121088
=> NAS-121088 / 22.12.2 / fix missing readonly property (by yocalebo)

src/middlewared/middlewared/plugins/pool_/dataset_details.py
This was supposed to be fixed in 22.12.1 and I added the `readonly` attribute to the data we gather, however, I never added the key in the response. This means webUI is still trying to probe datasets that are encrypted which raises a CallError. This simply adds it so that the webUI will behave as intended.
Original PR: https://github.com/truenas/middleware/pull/10991
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121088
=> NAS-121088 / 22.12.3 / fix missing readonly property (by yocalebo)

src/middlewared/middlewared/client/client.py
```[2023/03/28 09:43:05] (DEBUG) FailoverService.sync_to_peer():354 - Syncing database to standby controller.
[2023/03/28 09:43:05] (DEBUG) FailoverService.sync_to_peer():357 - Syncing cached encryption keys to standby controller.
[2023/03/28 09:43:06] (DEBUG) FailoverService.sync_to_peer():360 - Syncing zpool cachefile, license, pwenc and authorized_keys files to standby controller.
[2023/03/28 09:43:14] (WARNING) middlewared.client.client._on_error():145 - Websocket client error: WebSocketConnectionClosedException('Connection to remote host was lost.')
[2023/03/28 09:43:14] (ERROR) FailoverService.mismatch_disks():436 - Unhandled exception in get_disks_local on remote controller
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover.py", …
```
=> NAS-121008 / 23.10 / catch AttributeError in websocket client

src/middlewared/middlewared/client/client.py
```[2023/03/28 09:43:05] (DEBUG) FailoverService.sync_to_peer():354 - Syncing database to standby controller.
[2023/03/28 09:43:05] (DEBUG) FailoverService.sync_to_peer():357 - Syncing cached encryption keys to standby controller.
[2023/03/28 09:43:06] (DEBUG) FailoverService.sync_to_peer():360 - Syncing zpool cachefile, license, pwenc and authorized_keys files to standby controller.
[2023/03/28 09:43:14] (WARNING) middlewared.client.client._on_error():145 - Websocket client error: WebSocketConnectionClosedException('Connection to remote host was lost.')
[2023/03/28 09:43:14] (ERROR) FailoverService.mismatch_disks():436 - Unhandled exception in get_disks_local on remote controller
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover.py", …
```
=> NAS-121008 / 22.12.2 / catch AttributeError in websocket client (by yocalebo)

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/account_/privilege.py, src/middlewared/middlewared/plugins/auth_/authenticate.py, tests/api2/test_account_shell_choices.py
git cherry-pick -x 98cabb24b230bfdf8e61f3a22cd44cffca0651e1
git cherry-pick -x 3e8e94c011197b3af0e6460747fc372f8a4a09f2
… CLI for non-privileged users
Original PR: https://github.com/truenas/middleware/pull/10955
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121087
=> NAS-121087 / 22.12.3 / Make `user.shell_choices` accept group IDs to prevent showing TrueNAS… (by themylogin)

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py, src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
Platform team has qualified a new nvdimm firmware version for a specific model of nvdimm. I've added a `recommended_firmware` key so that users who upgrade to the next version of scale with these changes, don't get an alarming false message.
=> NAS-121223 / 23.10 / add new 2.6 qualified firmware to nvdimm alert

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py, src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
Platform team has qualified a new nvdimm firmware version for a specific model of nvdimm. I've added a `recommended_firmware` key so that users who upgrade to the next version of scale with these changes, don't get an alarming false message.
Original PR: https://github.com/truenas/middleware/pull/11004
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121223
=> NAS-121223 / 22.12.2 / add new 2.6 qualified firmware to nvdimm alert (by yocalebo)

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py, src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
Platform team has qualified a new nvdimm firmware version for a specific model of nvdimm. I've added a `recommended_firmware` key so that users who upgrade to the next version of scale with these changes, don't get an alarming false message.
Original PR: https://github.com/truenas/middleware/pull/11004
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121223
=> NAS-121223 / 22.12.3 / add new 2.6 qualified firmware to nvdimm alert (by yocalebo)

src/middlewared/middlewared/plugins/catalogs_linux/apps.py, src/middlewared/middlewared/plugins/catalogs_linux/sync_catalogs.py
This PR adds changes to account for the fact that if catalogs have not been synced, we sync them when `app.available` is called. Why this is required is that we don't sync catalogs at all unless user configures apps or navigates to available apps. Earlier `catalog.items` used to account for this and it made sure catalog was synced before we retrieved it's contents but that is not the case anymore as `catalog.items` is not a job anymore.
Earlier, we used to ensure that official catalog is synced in such cases and similar changes have been introduced now so we keep backwards compatibility.
=> NAS-121195 / 23.10 / Sync catalogs if they have not been synced

debian/debian/postinst
Platform team asking for vim to be installed but we already ship with vim.tiny. This adds a "vim" command that just points to vim.tiny so we don't have to install, essentially, an identical text editor that we already ship.
=> NAS-120155 / 23.10 / point vim.tiny to vim

debian/debian/postinst
Platform team asking for vim to be installed but we already ship with vim.tiny. This adds a "vim" command that just points to vim.tiny so we don't have to install, essentially, an identical text editor that we already ship.
Original PR: https://github.com/truenas/middleware/pull/11010
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120155
=> NAS-120155 / 22.12.3 / point vim.tiny to vim (by yocalebo)

src/middlewared/middlewared/plugins/activedirectory.py
Make it clearer to end-user when they've typoed the username they're using to bind to active directory.
=> NAS-121245 / 23.10 / Add more verbose error message for wrong name

src/middlewared/middlewared/test/integration/assets/smb.py, tests/api2/test_428_smb_rpc.py, tests/protocols/__init__.py, tests/protocols/ms_rpc.py
This series of tests is just a thin wrapper around rpclient, and is a preliminary step to having formal tests for FSS support.
Right now we only check that shares are properly enumerated via srvsvc endpoint and that users and RIDs are presented as expeceted.
=> NAS-121091 / 23.10 / Add tests for MS-RPC server

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/cache.py, src/middlewared/middlewared/plugins/idmap.py, tests/api2/test_011_user.py, tests/api2/test_030_activedirectory.py
This commit adds support for a non-default option to retrieve SID information from winbindd. This may be used to definitively identify whether the user is from AD, a local SMB user, or a local non-SMB user.
=> NAS-121269 / 23.10 / Add non-default parameter to retrieve SID info

src/middlewared/middlewared/plugins/chart_releases_linux/schema.py
If app developer uses `valid_chars` attribute to validate a value specified by user, the error is vague i.e does not match pattern.
It does not help tell the user that he needs to follow this specific order to be able to correctly specify the value in question so now the dev can specify a custom error message which will better guide the user on what to input for a field which is being validated by `valid_chars`.
=> NAS-120646 / 23.10 / Allow app dev to specify custom error message for valid_chars

src/middlewared/middlewared/migration/0007_catalog_enterprise_train.py, src/middlewared/middlewared/plugins/catalogs_linux/update.py
1. Any machine which is marked as `SCALE_ENTERPRISE` will at least have enterprise train set in it's preferred trains.
2. HA capable machines and R series machines will only have enterprise train set whenever the license is applied and they can then later add on more trains if required.
3. HA capable machines and R series machines cannot add any other catalogs other then OFFICIAL catalog.
4. Machines which are `SCALE_ENTERPRISE` and not ha capable and not R series will have enterprise train in it's preferred trains and will also be able to add other catalogs if required.
=> NAS-121275 / 23.10 / Properly have HA licensed systems to consume enterprise apps train

src/middlewared/middlewared/migration/0007_catalog_enterprise_train.py, src/middlewared/middlewared/plugins/catalogs_linux/update.py
1. Any machine which is marked as `SCALE_ENTERPRISE` will at least have enterprise train set in it's preferred trains.
2. HA capable machines and R series machines will only have enterprise train set whenever the license is applied and they can then later add on more trains if required.
3. HA capable machines and R series machines cannot add any other catalogs other then OFFICIAL catalog.
4. Machines which are `SCALE_ENTERPRISE` and not ha capable and not R series will have enterprise train in it's preferred trains and will also be able to add other catalogs if required.
Original PR: https://github.com/truenas/middleware/pull/11038
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121275
=> NAS-121275 / 22.12.3 / Properly have HA licensed systems to consume enterprise apps train (by sonicaj)

src/middlewared/middlewared/migration/0007_catalog_enterprise_train.py, src/middlewared/middlewared/plugins/catalogs_linux/update.py
1. Any machine which is marked as `SCALE_ENTERPRISE` will at least have enterprise train set in it's preferred trains.
2. HA capable machines and R series machines will only have enterprise train set whenever the license is applied and they can then later add on more trains if required.
3. HA capable machines and R series machines cannot add any other catalogs other then OFFICIAL catalog.
4. Machines which are `SCALE_ENTERPRISE` and not ha capable and not R series will have enterprise train in it's preferred trains and will also be able to add other catalogs if required.
Original PR: https://github.com/truenas/middleware/pull/11038
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121275
=> NAS-121275 / 22.12.2 / Properly have HA licensed systems to consume enterprise apps train (by sonicaj)

src/middlewared/middlewared/plugins/nfs.py, src/middlewared/middlewared/pytest/unit/plugins/test_nfs.py, tests/api2/test_300_nfs.py
Updated validation checks:
* Allow sharing unrelated directories
* Prevent sharing related directories to 'same' hosts
Original PR: https://github.com/truenas/middleware/pull/11002
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120957
=> NAS-120957 / 22.12.3 / Update NFS /etc/exports validations (by mgrimesix)

src/middlewared/middlewared/plugins/failover.py
We don't want to log a stack trace when the other controller is down in an HA system. It's expected that remote calls will fail.
=> NAS-121328 / 23.10 / prevent service_remote from spamming logs

src/middlewared/middlewared/plugins/failover.py
We don't want to log a stack trace when the other controller is down in an HA system. It's expected that remote calls will fail.
Original PR: https://github.com/truenas/middleware/pull/11043
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121328
=> NAS-121328 / 22.12.3 / prevent service_remote from spamming logs (by yocalebo)

src/middlewared/middlewared/test/integration/assets/smb.py, tests/api2/test_428_smb_rpc.py, tests/protocols/__init__.py, tests/protocols/ms_rpc.py
This series of tests is just a thin wrapper around rpclient, and is a preliminary step to having formal tests for FSS support.
Right now we only check that shares are properly enumerated via srvsvc endpoint and that users and RIDs are presented as expected.
Original PR: https://github.com/truenas/middleware/pull/10898
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121091
=> NAS-121091 / 22.12.3 / Add tests for MS-RPC server (by anodos325)

src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/auth.py
Seen on HA system running latest nightly
```
[2023/04/04 05:47:01] (ERROR) middlewared.call_hook():1227 - Failed to run hook core.on_connect:<function check_permission at 0x7f689f221ca0>(*(), **{'app': <middlewared.main.Application object at 0x7f68792c77c0>})
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1220, in call_hook
await fut
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1253, in run_in_thread
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1250, in run_in_executor
return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, …
```
=> NAS-121330 / 23.10 / fix AttributeError crash in auth plugin

src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/auth.py
Seen on HA system running latest nightly
```
[2023/04/04 05:47:01] (ERROR) middlewared.call_hook():1227 - Failed to run hook core.on_connect:<function check_permission at 0x7f689f221ca0>(*(), **{'app': <middlewared.main.Application object at 0x7f68792c77c0>})
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1220, in call_hook
await fut
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1253, in run_in_thread
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1250, in run_in_executor
return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, …
```
=> NAS-121330 / 22.12.3 / fix AttributeError crash in auth plugin (by yocalebo)

src/middlewared/middlewared/etc_files/local/nut/upsd.users.mako
UPS extra users are expected to be specified at root level of the configuration file for the user and should not have an indent before. Right now it was following the below format:
```
[upsmon]
password = abcd
upsmon master
[admin]
password = abcd
instcmds = all
```
Whereas the correct specification is:
```
[upsmon]
password = abcd
upsmon master
[admin]
password = abcd
instcmds = all
```
Correctly render the extra users so they are specified keeping in line with upstream guidelines for NUT.
References:
https://wiki.ipfire.org/addons/nut/detailed
https://wiki.archlinux.org/title/Network_UPS_Tools
=> NAS-121082 / 23.10 / Fix ups service's extra users

src/middlewared/middlewared/etc_files/local/nut/upsd.users.mako
UPS extra users are expected to be specified at root level of the configuration file for the user and should not have an indent before. Right now it was following the below format:
```
[upsmon]
password = abcd
upsmon master
[admin]
password = abcd
instcmds = all
```
Whereas the correct specification is:
```
[upsmon]
password = abcd
upsmon master
[admin]
password = abcd
instcmds = all
```
Correctly render the extra users so they are specified keeping in line with upstream guidelines for NUT.
References:
https://wiki.ipfire.org/addons/nut/detailed
https://wiki.archlinux.org/title/Network_UPS_Tools
Original PR: https://github.com/truenas/middleware/pull/11042
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121082
=> NAS-121082 / 22.12.3 / Fix ups service's extra users (by Qubad786)

src/middlewared/middlewared/plugins/auth.py
This PR adds changes so UI can consume the following workflow for logging in users:
1. Users present a login screen where username/password is only asked
2. UI calls `auth.two_factor_auth` where UI passes credentials and endpoint will return if the user has 2FA configured. It will only say 2FA is configured when the credentials are good and 2FA is actually configured.
3. Based on step 2 output, UI will show a new screen where it will ask for OTP
4. With/without OTP, after step 3 - UI will finally call `auth.login` to login the said user
=> NAS-121304 / 23.10 / Improve logging in workflow for UI

src/middlewared/middlewared/plugins/catalogs_linux/apps.py, src/middlewared/middlewared/schema.py, src/middlewared/middlewared/service.py
It was requested by the UI team that `app.latest` should have the same options as `filterable` so they can retrieve all apps at once and filter/limit as required.
While updating `app.latest` endpoint, `filterable_returns` was broken when `Ref` was used. The problem it turned out to be were 2:
1. `_filterable_schema` attribute which points to schema never got resolved which failed obviously
2. When the same `Ref` object was specified in `OROperator`, ref in the list item did not resolve because the same object was being manipulated when the ref was specified as second entry in the OR operator.
Convert `app.latest` to be filterable and fixes for the 2 problems were:
1. Specify the OROperator in `_filterable_schema` so that the schema does get resolved as the same object would be referenced …
=> NAS-121363 / 23.10 / Fix filterable return schema and update app.latest endpoint

src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/kerberos.py
This backports a fundamental design change to no longer use python bindings into libnet / libads in the activedirectory plugin. This is generally more reliable. Information we were gleaning from the python bindings can be gotten through subprocessing out to net commands. This commit also fixes an edge case where kerberos errors would not be properly turned into ValidationError while checking user-provided passwords.
=> NAS-121238 / 13.0 / Backport SCALE activedirectory-related fixes to Core

src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/failover_/configure.py, src/middlewared/middlewared/plugins/system/product.py, src/middlewared/middlewared/test/integration/utils/client.py, tests/api2/test_002_system_license.py
The `failover.licensed` endpoint reads the license file from disk, deserializes it and then checks to see if this is an HA license. Since this endpoint is called _EVERYWHERE_ we moved to caching the return of this endpoint years ago. This has exposed a bug in the `hook_license_update` method that gets called when an HA license is updated via our API.
We send the license file to the other controller, but that is not enough to cache the license into memory. We must call the appropriate hook on the remote controller as well. However, after investigation, I realized that this hook would cause a recursion loop. Now I remove that hook and explicitly setup the license on the other controller. Also, while I'm here, fix a false log message to reflect reality.
=> NAS-121387 / 23.10 / fix hook_license_update

src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/failover_/configure.py, src/middlewared/middlewared/plugins/system/product.py, src/middlewared/middlewared/test/integration/utils/client.py, tests/api2/test_002_system_license.py
The `failover.licensed` endpoint reads the license file from disk, deserializes it and then checks to see if this is an HA license. Since this endpoint is called _EVERYWHERE_ we moved to caching the return of this endpoint years ago. This has exposed a bug in the `hook_license_update` method that gets called when an HA license is updated via our API.
We send the license file to the other controller, but that is not enough to cache the license into memory. We must call the appropriate hook on the remote controller as well. However, after investigation, I realized that this hook would cause a recursion loop. Now I remove that hook and explicitly setup the license on the other controller. Also, while I'm here, fix a false log message to reflect reality.
Original PR: …
=> NAS-121387 / 22.12.3 / fix hook_license_update (by yocalebo)

src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/kerberos.py
* Prevent users from manually deleting the AD machine account keytab if the AD service is currently enabled. This keytab is vital to keeping kerberized services working properly.
* Whitelist which AD fields may be changed while service is enabled. This will hopefully encourage users to take maintenance windows before making changes on production servers that may affect clients that are currently connected to the server.
* In some abusive testing support was able to get into a state where libads had cached stale information which led to failures spurious failures when looking up DC and domain information. This commit changes the behavior of related methods so that if the first attempt doesn't succeed, we flush out caches then try again.
Original PR: …
=> NAS-121392 / 22.12.3 / Add some more validation for AD-related changes (by anodos325)

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py, src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
SCALE has ability to report armed information for legacy NVDIMMs while CORE did not. This is to add that functionality to SCALE (requested by platform team).
I've fixed ambiguous, very confusing alerts while I'm here.
=> NAS-121397 / 23.10 / Add nvdimm arm info for legacy NVDIMMs

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py, src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
SCALE has ability to report armed information for legacy NVDIMMs while CORE did not. This is to add that functionality to SCALE (requested by platform team).
I've fixed ambiguous, very confusing alerts while I'm here.
Original PR: https://github.com/truenas/middleware/pull/11083
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121397
=> NAS-121397 / 22.12.3 / Add nvdimm arm info for legacy NVDIMMs (by yocalebo)

src/middlewared/middlewared/plugins/system_advanced/config.py, src/middlewared/middlewared/plugins/system_advanced/gpu.py, src/middlewared/middlewared/plugins/vm/pci.py, src/middlewared/middlewared/plugins/vm/utils.py, src/middlewared/middlewared/pytest/unit/plugins/test_gpu_isolation.py, src/middlewared/middlewared/utils/gpu.py
Logic where we determine if a gpu is critical for the host to function had been outdated with what we have for PCI devices. The same logic is now used in both places to determine critical devices to make sure that a GPU is properly marked as critical.
=> NAS-120230 / 23.10 / Properly mark a gpu as critical if it is critical to the system

tests/api2/test_110_certificate.py
With changes to how we properly give out humanised errors when deleting certs which are being consumed by services, those changes broke our certificate deletion test which has been fixed.
=> NAS-121418 / 23.10 / Fix certificate delete test

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py, src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
After clarification from platform team, we do not need a recommended nvdimm firmware alert for version 2.6. Instead, we need to alert as if it's an invalid firmware. I've left the recommended firmware logic in place in-case we ever have more than 1 qualified firmware for an nvdimm.
=> NAS-121443 / 23.10 / fix legacy nvdimm alert

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py, src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
After clarification from platform team, we do not need a recommended nvdimm firmware alert for version 2.6. Instead, we need to alert as if it's an invalid firmware. I've left the recommended firmware logic in place in-case we ever have more than 1 qualified firmware for an nvdimm.
Original PR: https://github.com/truenas/middleware/pull/11094
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121443
=> NAS-121443 / 22.12.3 / fix legacy nvdimm alert (by yocalebo)

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py, src/middlewared/middlewared/plugins/hardware_/m_series_nvdimm.py
After clarification from platform team, we do not need a recommended nvdimm firmware alert for version 2.6. Instead, we need to alert as if it's an invalid firmware. I've left the recommended firmware logic in place in-case we ever have more than 1 qualified firmware for an nvdimm.
Original PR: https://github.com/truenas/middleware/pull/11094
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121443
=> NAS-121443 / 13.0 / fix legacy nvdimm alert (by yocalebo)

src/middlewared/middlewared/plugins/activedirectory_/dns.py, src/middlewared/middlewared/plugins/cluster_linux/utils.py, src/middlewared/middlewared/plugins/dns_client.py
Input parameters:
* record_type changed to a list of record_types. Default is ['A', 'AAAA']. 'SRV' and 'CNAME' remain singular and cannot be requested in combination with the others. NOTE: With the default record_types selection, hosts that support both IPv4 and IPv6 will return entries for both 'A' and 'AAAA' records.
* Added 'throw_exception_on'. Default to 'host_failure'.  Options are 'never', 'any_failure', 'host_failure', all_failure'. Output parameters and exception reporting behavior (with default selection) remain unchanged.
=> NAS-121309 / 23.10 / Update forward_lookup to support A/AAAA records by default

tests/api2/test_vmware.py
…6-01a205f5 already exists.`
Original PR: https://github.com/truenas/middleware/pull/11098
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121426
=> NAS-121426 / 22.12.3 / Prevent `The specified key, name, or identifier /vmfs/volumes/f7f8aa8… (by themylogin)

debian/debian/postinst
In Cobia (based on bookworm), we're bringing in proper ndctl package since it has Mav's fixes. The package adds this service which needs to be masked since it will error If a system doesn't have an NVDIMM.
=> NAS-121450 / 23.10 / mask ndctl-monitor.service

src/middlewared/middlewared/plugins/chart_releases_linux/acl.py, src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py, src/middlewared/middlewared/plugins/chart_releases_linux/normalize_schema.py, src/middlewared/middlewared/plugins/filesystem_/acl_linux.py, tests/api2/test_chart_release_acl_apply.py
`filesystem.add_to_acl` has been added to allow app devs to correctly specify ACLs for host paths. A feature `normalize/acl` has been added which app devs can specify to consume the new feature.
=> NAS-120252 / 23.10 / Allow specifying acls for apps

src/middlewared/middlewared/plugins/network.py
…the MAC address for bond
Original PR: https://github.com/truenas/middleware/pull/10973
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121032
=> NAS-121032 / 22.12.3 / Use `lagg_ordernum` to determine the correct child interface to grab … (by themylogin)

src/middlewared/middlewared/alert/source/failover_disks.py
Regression introduced on Feb 15th, 2022. This fixes it so the alert properly works.
=> NAS-121457 / 23.10 / fix regression (from Feb, 2022) for missing disks alert

src/middlewared/middlewared/alert/source/failover_disks.py
Regression introduced on Feb 15th, 2022. This fixes it so the alert properly works.
Original PR: https://github.com/truenas/middleware/pull/11103
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121457
=> NAS-121457 / 22.12.3 / fix regression (from Feb, 2022) for missing disks alert (by yocalebo)

src/middlewared/middlewared/plugins/iscsi_/extents.py, src/middlewared/middlewared/plugins/iscsi_/utils.py, tests/api2/test_261_iscsi_cmd.py
Currently the underlying iSCSI target code has a limitation wrt the maximum length of the extent name (64).  Enforce a check in middleware to prevent an invalid SCST configuration.
=> NAS-120980 / 23.10 / Add MAX_EXTENT_NAME_LEN for iSCSI

src/middlewared/middlewared/plugins/iscsi_/extents.py, src/middlewared/middlewared/plugins/iscsi_/utils.py, tests/api2/test_261_iscsi_cmd.py
git cherry-pick -x fbf9a05c8696a87d4991576ab36e369b56ac734a
git cherry-pick -x 6254f72dd006f7fed44e616d82397ff938762002
Currently the underlying iSCSI target code has a limitation wrt the maximum length of the extent name (64).  Enforce a check in middleware to prevent an invalid SCST configuration.
Original PR: https://github.com/truenas/middleware/pull/11105
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120980
=> NAS-120980 / 22.12.3 / Add MAX_EXTENT_NAME_LEN for iSCSI (by bmeagherix)

cluster-tests/tests/directoryservices/test_001_activedirectory.py, cluster-tests/tests/filesystem/test_001_base_filesystem_tests.py, src/middlewared/middlewared/etc_files/ctdb.conf.mako, src/middlewared/middlewared/plugins/cluster_linux/ctdb_ips.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_private.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_public.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_services.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_setup.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py, src/middlewared/middlewared/plugins/cluster_linux/utils.py, src/middlewared/middlewared/plugins/gluster_linux/filesystem.py, src/middlewared/middlewared/plugins/gluster_linux/pyglfs_utils.py, src/middlewared/middlewared/plugins/pwenc.py, src/middlewared/middlewared/scripts/ctdb_events.py
* use python libgfapi bindings to read / write configuration
files that reside on glusterfs volumes
* shift the cached glusterfs volume handles to a common utils
class shared between multiple middleware plugins
* remove usage of hard-coded paths under /cluster for clustered
config and state files
These steps are significant progress toward deprecating the
dedicated ctdb_shared_volume
=> NAS-121277 / 23.10 /  Reduce dependencies on glusterfs fuse mount 

cluster-tests/tests/directoryservices/test_001_activedirectory.py, cluster-tests/tests/filesystem/test_001_base_filesystem_tests.py, src/middlewared/middlewared/etc_files/ctdb.conf.mako, src/middlewared/middlewared/plugins/cluster_linux/ctdb_ips.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_private.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_public.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_services.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_setup.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py, src/middlewared/middlewared/plugins/cluster_linux/utils.py, src/middlewared/middlewared/plugins/gluster_linux/filesystem.py, src/middlewared/middlewared/plugins/gluster_linux/pyglfs_utils.py, src/middlewared/middlewared/plugins/pwenc.py, src/middlewared/middlewared/scripts/ctdb_events.py
* use python libgfapi bindings to read / write configuration
files that reside on glusterfs volumes
* shift the cached glusterfs volume handles to a common utils
class shared between multiple middleware plugins
* remove usage of hard-coded paths under /cluster for clustered
config and state files
These steps are significant progress toward deprecating the
dedicated ctdb_shared_volume
Original PR: https://github.com/truenas/middleware/pull/11030
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121277
=> NAS-121277 / 22.12.3 /  Reduce dependencies on glusterfs fuse mount  (by anodos325)

src/middlewared/middlewared/plugins/gluster_linux/filesystem.py
The docstring was copy-pasted from unlink function.
=> NAS-121516 / 23.10 / Fix copy-paste error in glusterfs filesystem doc

src/middlewared/middlewared/plugins/gluster_linux/filesystem.py
The docstring was copy-pasted from unlink function.
Original PR: https://github.com/truenas/middleware/pull/11113
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121516
=> NAS-121516 / 22.12.3 / Fix copy-paste error in glusterfs filesystem doc (by anodos325)

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py, src/middlewared/middlewared/plugins/hardware_/m_series_nvdimm.py
A sysctl was added to 13 to allow us to parse the "legacy" nvdimms for arm status information (like we do in SCALE). This keeps core in feature parity with SCALE. While I'm here, this fixes the fact that these alerts would not run on 13 because of a copy and paste error when doing a cherry-pick from SCALE in a previous commit.
=> NAS-121397 / 13.0 / add legacy ARM status information for NVDIMM

src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py, src/middlewared/middlewared/plugins/cluster_linux/utils.py, src/middlewared/middlewared/plugins/config.py
We need to ensure that we wipe all cluster related configuration files if an end-user chooses to wipe the system to factory defaults.
=> NAS-121524 / 23.10 / Be sure and wipe cluster config on factory reset

src/middlewared/middlewared/plugins/datastore/connection.py, src/middlewared/middlewared/plugins/datastore/schema.py, src/middlewared/middlewared/pytest/unit/plugins/test_datastore.py, src/middlewared/middlewared/sqlalchemy.py
These changes are incompatible with SQLAlchemy 1.3. TrueNAS SCALE uses SQLAlchemy 1.3, TrueNAS CORE 13 uses SQLAlchemy 1.4. This ticket should be merged once we update TrueNAS SCALE to the distribution that ships SQLAlchemy 1.4.
=> NAS-113861 / 23.10 / SQLAlchemy 1.4 compatibility

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/pytest/unit/test_schema.py, src/middlewared/middlewared/schema.py
WebUI is exclusively doing validation on the username field (with exception of the length). The validation there is out of date and incorrect on SCALE (still makes references to NIS, for example). This adds a new schema class specifically for validating local usernames based on Debian recommendations.
Original PR: https://github.com/truenas/middleware/pull/11119
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121541
=> NAS-121541 / 22.12.3 / properly validate username field when creating a local user (by yocalebo)

src/middlewared/middlewared/plugins/device_/device_info.py
I fixed an off-by-one error (and a few other issues) in `libsgio` module. Part of fixing this was raising a proper custom exception. Because of this (we have users that have esoteric hardware (I'm looking at you qnap branded hard drives)), some of our users are missing hard-drives on upgrade from 22.12.1 to 22.12.2. Just catch all exceptions when trying to get rotation rate of a drive. It's not even remotely "critical" information that is necessary for the system to function.
=> NAS-121508 / 23.10 / catch Exception class getting libsgio.rotation_rate()

src/middlewared/middlewared/plugins/device_/device_info.py
I fixed an off-by-one error (and a few other issues) in `libsgio` module. Part of fixing this was raising a proper custom exception. Because of this (we have users that have esoteric hardware (I'm looking at you qnap branded hard drives)), some of our users are missing hard-drives on upgrade from 22.12.1 to 22.12.2. Just catch all exceptions when trying to get rotation rate of a drive. It's not even remotely "critical" information that is necessary for the system to function.
Original PR: https://github.com/truenas/middleware/pull/11125
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121508
=> NAS-121508 / 22.12.3 / catch Exception class getting libsgio.rotation_rate() (by yocalebo)

tests/api2/test_420_smb.py
This fails 100% of the time but not because the actual test is failing, seems the test isn't formatted properly or some such. Skip it for now.
=> NAS-121560 / 23.10 / skip local.replace smb torture test for now

src/middlewared/middlewared/plugins/s3.py
When using double quotes in s3 service in secret/access key `rc.conf` being generated is invalid..fixing rc.conf escaping those quotes does not solve the problem as minio rc files gets broken as well because it runs a command which does not account for double quotes properly.
The proper fix would be patching up the rc file and fixing rc conf generation but considering that double quotes in secret/access key has never been working in CORE it should be fine to just not allow those characters in these fields..in SCALE however this is not a problem and works as intended.
=> NAS-121261 / 13.0 / Do not allow double quotes in access/secret key

src/middlewared/middlewared/plugins/disk_/sync.py
Seen in the wild, a certain manufacturer is returning double-quotes in the information returned from the disk. This breaks the xml iteration. Use shlex.quote to resolve this.
=> NAS-121598 / 13.0 / fix edge-case crash

src/middlewared/middlewared/plugins/failover_/event.py
Again, investigating an unrelated issue and noticed this in the logs on the system I'm investigating. Don't crash right here at the end. This failure scenario is present when an HA system is installed and 1 controller is powered off/removed from the head-unit while the end-user is configuring the A controller for the first time. Initial failover event that is received is BACKUP event, subsequently followed by a MASTER event.
=> NAS-121594 / 23.10 / fix unhandled exception in vrrp_backup

src/middlewared/middlewared/plugins/failover_/event.py
Again, investigating an unrelated issue and noticed this in the logs on the system I'm investigating. Don't crash right here at the end. This failure scenario is present when an HA system is installed and 1 controller is powered off/removed from the head-unit while the end-user is configuring the A controller for the first time. Initial failover event that is received is BACKUP event, subsequently followed by a MASTER event.
Original PR: https://github.com/truenas/middleware/pull/11138
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121594
=> NAS-121594 / 22.12.3 / fix unhandled exception in vrrp_backup (by yocalebo)

src/middlewared/middlewared/etc_files/ctdb.conf.mako
ctdb api endpoints makes the assumption that the glusterd service is started. ctdb.conf needs to be gated on whether or not glusterd is enabled.
=> NAS-121633 / 23.10 / don't generate ctdb unless glusterd is enabled

src/middlewared/middlewared/etc_files/ctdb.conf.mako
ctdb api endpoints makes the assumption that the glusterd service is started. ctdb.conf needs to be gated on whether or not glusterd is enabled.
Original PR: https://github.com/truenas/middleware/pull/11144
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121633
=> NAS-121633 / 22.12.3 / don't generate ctdb unless glusterd is enabled (by yocalebo)

src/middlewared/middlewared/plugins/failover_/detect_enclosure.py
This cannot be an `elif` branch because we depend on the HBA for determining the slot position on the x-series platform. Without this change, the first `if` branch is true on BOTH controllers but the controller in the physical A slot will only ever properly detect its own position in the head-unit.
=> NAS-121659 / 23.10 / fix xseries B slot identification on SCALE HA

src/middlewared/middlewared/plugins/failover_/detect_enclosure.py
This cannot be an `elif` branch because we depend on the HBA for determining the slot position on the x-series platform. Without this change, the first `if` branch is true on BOTH controllers but the controller in the physical A slot will only ever properly detect its own position in the head-unit.
Original PR: https://github.com/truenas/middleware/pull/11149
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121659
=> NAS-121659 / 22.12.3 / fix xseries B slot identification on SCALE HA (by yocalebo)

src/middlewared/middlewared/plugins/interface/configure.py, src/middlewared/middlewared/plugins/interface/netif_linux/address/types.py, src/middlewared/middlewared/plugins/interface/netif_linux/interface.py, src/middlewared/middlewared/plugins/interface/netif_linux/routing.py, src/middlewared/middlewared/plugins/network.py, src/middlewared/middlewared/plugins/network_/route.py, src/middlewared/middlewared/plugins/network_/static_routes.py, src/middlewared/middlewared/plugins/reporting/rrd_utils.py, src/middlewared/middlewared/plugins/reporting/update.py
Unfortunately, in python3.11-BETA.1 (https://docs.python.org/3.11/whatsnew/changelog.html search for bpo-26579), they introduced a dunder method called getstate for certain built-in objects. This means all the classes that we implemented with a getstate dunder method now collide with the changes introduced in 3.11.
To resolve this, I have renamed those methods to `asdict`. This is a common pattern followed by popular 3rd party python modules and is even implemented by the `dataclasses.dataclass` built-in.
=> NAS-121667 / 23.10 / remove __getstate__ for py3.11 compat

src/middlewared/middlewared/plugins/service_/services/nfs.py
rpc-statd is now marked as a "static" service type. This means it cannot be enabled or disabled manually (since a static service doesn't have an Install section so systemd doesn't know where to put the symlink). For now, remove it from `systemd_extra_units` so we can at least generated rc for systemd on Cobia.
=> NAS-121622 / 23.10 / remove rpc-statd as a systemd extra unit for nfs

src/middlewared/middlewared/etc_files/pam.d/middleware.mako
pam.authenticate will still be gated based on details of common-auth.
=> NAS-121671 / 23.10 / Use common-account for middleware pam file

src/middlewared/middlewared/async_validators.py
Python 3.10 removed the loop kwarg to asyncio.wait_for so by upgrading to python3.11, this raises an error. To my pleasant surprise, this is the only place that I could find where we passed a loop kwarg to asyncio.wait_for.
=> NAS-121677 / 23.10 / fix async_validators.py:resolve_hostnames()

tests/api2/test_027_kubernetes_logs.py
`qbittorrent` application has been changed as to how it functions and it now has init container which exits and we don't have logs to follow/assert.
Use a different application which solves this problem and has logs streaming which we can test/assert.
=> NAS-121558 / 23.10 / Fix kubernetes logs assertion error

src/middlewared/middlewared/plugins/pool_/unlock.py
On dataset unlock we were considering/treating zvol associated with a VM as a directory whereas that's not true and the condition will fail resulting in the associated VM to not start.
The path can be directly asserted by converting zvol to it's path and getting the path saved in VM device and if it matches we would want to restart the VM in that case.
=> NAS-121446 / 23.10 / Fix vm restart on dataset unlock

src/middlewared/middlewared/plugins/pool_/unlock.py
On dataset unlock we were considering/treating zvol associated with a VM as a directory whereas that's not true and the condition will fail resulting in the associated VM to not start.
The path can be directly asserted by converting zvol to it's path and getting the path saved in VM device and if it matches we would want to restart the VM in that case.
Original PR: https://github.com/truenas/middleware/pull/11158
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121446
=> NAS-121446 / 22.12.3 / Fix vm restart on dataset unlock (by Qubad786)

src/freenas/usr/bin/install-dev-tools
With python3.11 pip does not allow installing packages and errors out saying the packages are managed externally by the debian environment i.e
```
error: externally-managed-environment
× This environment is externally managed
```
List of pip packages has been refined to bring in packages with apt which are available in debian repositories and pip is provided with a force flag which will still force install those packages which we are not able to find with apt.
=> NAS-121702 / 23.10 / Fix install-dev-tools

tests/api2/test_261_iscsi_cmd.py, tests/protocols/__init__.py, tests/protocols/iscsi_proto.py
Currently `python-scsi` presents an **illegal** initiator name when CHAP is in use.  In bookworm `SCST` responds very badly to these illegal values, so skip these tests for now.
FWIW, plan to address two related aspects separately (and in this order):
1. Modify test-runner environment to use a more modern `python-scsi` that does not present an illegal initiator name
2. Robustize `SCST` to reject illegal initiator names.
=> NAS-121727 / 23.10 / Skip iSCSI CHAP tests for invalid initiatorname values

.github/workflows/unittests.yml, src/middlewared/Makefile
Previously bookworm based CI builds were failing in the `Deploy` phase.
With the updated python paths in this PR, it now fails in the `Test` phase ... so _slight_ progress.
FWIW, the failure is now, e.g.
```
_______________ ERROR collecting unit/plugins/test_datastore.py ________________
/usr/local/lib/python3.11/dist-packages/middlewared/pytest/unit/plugins/test_datastore.py:[19](https://github.com/truenas/middleware/actions/runs/4825763722/jobs/8596936868?pr=11171#step:5:20): in <module>
from middlewared.pytest.unit.middleware import Middleware
/usr/local/lib/python3.11/dist-packages/middlewared/pytest/unit/middleware.py:4: in <module>
from asynctest import CoroutineMock, Mock
/usr/local/lib/python3.11/dist-packages/asynctest/__init__.py:[22](https://github.com/truenas/middleware/actions …
```
=> NAS-121728 / 23.10 / Switch from python 3.9 to 3.11

tests/api2/test_027_kubernetes_logs.py
`qbittorrent` application has been changed as to how it functions and it now has init container which exits and we don't have logs to follow/assert.
Use a different application which solves this problem and has logs streaming which we can test/assert.
Original PR: https://github.com/truenas/middleware/pull/11156
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121558
=> NAS-121558 / 22.12.3 / Fix kubernetes logs assertion error (by Qubad786)

src/middlewared/middlewared/plugins/catalogs_linux/apps.py, src/middlewared/middlewared/plugins/catalogs_linux/item_version.py, src/middlewared/middlewared/plugins/catalogs_linux/items.py
It was requested by UI team that middleware should provide `maintainers` attribute which UI can present in the new Apps UI design. Changes have been added in `truenas/catalog_validation` and here we update schema to reflect the new attribute.
=> NAS-121561 / 23.10 / Reflect maintainers attribute in schema

src/middlewared/middlewared/plugins/chart_releases_linux/normalize_schema.py, src/middlewared/middlewared/plugins/chart_releases_linux/utils.py
There were 2 problems with 1 problem being a side-effect of another one..root problem was:
We have an attribute which reflects if nvidia runtime class should be added or not but it was always set which indicated that app developer should always add nvidia runtime even when nvidia gpu was not available.
This problem was being reflected in one of the integration tests we have where the helm chart was updated to reflect the value middleware provides to the app dev if he should add the runtime class or not:
```
Error creating: pods "prune-test1-ix-chart-6c6f674cbb-" is forbidden: pod rejected: RuntimeClass "nvidia" not found
```
Fixing the root problem will solve the integration test problem automatically. Now we correctly determine if nvidia runtime class should be added by the app developer …
=> NAS-121689 / 23.10 / Properly reflect add nvidia runtime class variable

tests/requirements.txt
This is required to pickup a version of `python-scsi` that provides a valid initiator name.
=> NAS-121746 / 23.10 / Switch tests to use truenas repo for python-scsi and cython-iscsi

tests/requirements.txt
This is required to pickup a version of `python-scsi` that provides a valid initiator name.
Original PR: https://github.com/truenas/middleware/pull/11184
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121746
=> NAS-121746 / 22.12.3 / Switch tests to use truenas repo for python-scsi and cython-iscsi (by bmeagherix)

src/middlewared/middlewared/plugins/system_general/timezone.py
Integration test for timezones was failing https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/API%20Tests%20-%20TrueNAS%20SCALE%20(Incremental)/lastCompletedBuild/testReport/api2/test_490_system_general/test_09_timezone_choices/ in bookworm..in bullseye we don't have `ETC/GMT+X` as valid timezone options.
Make sure we recognise `ETC/GMT+X` as valid timezones as they are reported as valid by `timedatectl` and applying them reflects reality as well.
=> NAS-121745 / 23.10 / Fix timezone integration test

src/middlewared/middlewared/plugins/ipmi.py
`get_cmd()` is an inner function that is called to prevent duplicate code since ipmitool commands essentially are prefixed with the same few commands. This isn't true when changing the password but that inner method was mistakenly called when changing the password leading to an invalid command. Remove the call to the inner method.
=> NAS-121657 / 23.10 / fix typo in ipmi plugin (preventing passwd change)

src/middlewared/middlewared/plugins/ipmi.py
`get_cmd()` is an inner function that is called to prevent duplicate code since ipmitool commands essentially are prefixed with the same few commands. This isn't true when changing the password but that inner method was mistakenly called when changing the password leading to an invalid command. Remove the call to the inner method.
Original PR: https://github.com/truenas/middleware/pull/11186
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121657
=> NAS-121657 / 22.12.3 / fix typo in ipmi plugin (preventing passwd change) (by yocalebo)

src/middlewared/middlewared/plugins/ipmi.py, src/middlewared/middlewared/plugins/ipmi_/sel.py
This adds an `ipmi.sel` specific plugin for directly managing the ipmi SEL portion of systems. The justification for doing this is to not crowd the main `ipmi` plugin with other ipmi sub-tasks that don't really make sense. Keeping each ipmi related "sub-task" in their own plugin makes it easier to maintain and extend.
=> NAS-121764 / 22.12.3 / add ipmi.sel plugin

src/middlewared/middlewared/plugins/ipmi.py, src/middlewared/middlewared/plugins/ipmi_/sel.py
This adds an `ipmi.sel` specific plugin for directly managing the ipmi SEL portion of systems. The justification for doing this is to not crowd the main `ipmi` plugin with other ipmi sub-tasks that don't really make sense. Keeping each ipmi related "sub-task" in their own plugin makes it easier to maintain and extend.
Original PR: https://github.com/truenas/middleware/pull/11190
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121764
=> NAS-121764 / 23.10 / add ipmi.sel plugin (by yocalebo)

src/middlewared/middlewared/plugins/ipmi_/sel.py
This adds the `-v` command flag so we can get the event direction for each sel elist entry as well as added the `--no-header-output` flag so the column title line would not be returned in the results.
=> NAS-121781 / 23.10 / add -v and --no-header-output to ipmi.sel.elist

src/freenas/usr/bin/install-dev-tools
pip install won't work with an empty array. Check whether we actually need to install anything before invoking it.
=> NAS-121787 / 23.10 / Fix middleware reinstalls

src/middlewared/middlewared/etc_files/hosts.mako
Seen on an internal cluster, we had a set of nodes that were not able to be added to a cluster because it kept failing with some obscure message about localhost (this came from gluster).
Long-story short, it was because the localhost entry was the first entry in the /etc/hosts file. Even though forward and reverse look ups were working on this network, the cluster was still failing in an extravagant ways. The moment I moved the localhost entry to the last entry in that file, everything magically started working.
=> NAS-121789 / 23.10 / fix hosts file when clustered

src/middlewared/middlewared/etc_files/hosts.mako
Seen on an internal cluster, we had a set of nodes that were not able to be added to a cluster because it kept failing with some obscure message about localhost (this came from gluster).
Long-story short, it was because the localhost entry was the first entry in the /etc/hosts file. Even though forward and reverse look ups were working on this network, the cluster was still failing in an extravagant ways. The moment I moved the localhost entry to the last entry in that file, everything magically started working.
Original PR: https://github.com/truenas/middleware/pull/11211
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121789
=> NAS-121789 / 22.12.3 / fix hosts file when clustered (by yocalebo)

src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/activedirectory_/dns.py, src/middlewared/middlewared/plugins/activedirectory_/health.py
Pass through the legacy dns_timeout key to our DNS client plugin when doing various AD checks. This potentially allows users to account for really terrible DNS. Since the DNS client ops are not called within a job, timeout should have some validation to prevent setting something too low or too high.
=> NAS-121788 / 23.10 / Make DNS timeouts for AD checks configurable

src/middlewared/middlewared/plugins/nfs_/debug.py
Changing `enum.Flags` to `enum.Enum` restores expected behavior.
```
>>> import enum
>>> class NFSDBG(enum.Flag):
...     # include/uapi/linux/nfs_fs.h
...     NONE = 0x0000
...     VFS = 0x0001
...     DIRCACHE = 0x0002
...     LOOKUPCACHE = 0x0004
...     PAGECACHE = 0x0008
...     PROC = 0x0010
...     XDR = 0x0020
...     FILE = 0x0040
...     ROOT = 0x0080
...     CALLBACK = 0x0100
...     CLIENT = 0x0200
...     MOUNT = 0x0400
...     FSCACHE = 0x0800
...     PNFS = 0x1000
...     PNFS_LD = 0x2000
...     STATE = 0x4000
...     XATTR_CACHE = 0x8000
...     ALL = 0xFFFF
...
>>> [x.name for x in NFSDBG]
['NONE', 'VFS', 'DIRCACHE', 'LOOKUPCACHE', 'PAGECACHE', 'PROC', 'XDR', 'FILE', 'ROOT', 'CALLBACK', 'CLIENT', 'MOUNT', 'FSCACHE', 'PNFS', 'PNFS_LD', 'STATE', 'XATTR_CACHE', 'ALL']
``` …
=> NAS-121794 / 23.10 / Behavior of python enum.Flags has changed between 3.9 and 3.11.

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
There was a problem with how we removed the pool name from k3s datasets. Essentially we were relying on some custom logic which broke when pool was named `applications` and hence the resulting dataset was malformed i.e `ix-/kubectl` 
To address this issue, we remove the complicated logic we had in place and just strip away the pool name cleanly.
=> NAS-121509 / 23.10 / Fix application pool name bug in kubernetes setup

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
There was a problem with how we removed the pool name from k3s datasets. Essentially we were relying on some custom logic which broke when pool was named `applications` and hence the resulting dataset was malformed i.e `ix-/kubectl` 
To address this issue, we remove the complicated logic we had in place and just strip away the pool name cleanly.
Original PR: https://github.com/truenas/middleware/pull/11206
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121509
=> NAS-121509 / 22.12.3 / Fix application pool name bug in kubernetes setup (by Qubad786)

src/middlewared/middlewared/plugins/chart_releases_linux/events.py
It has been requested by UI team to stream app's events so that they can be dynamically updated on the UI instead of UI polling for them.
Now whenever an app's status changes we will be sending an event with with app's k8s events - unfortunately kubernetes does not provide for streaming these objects directly so polling is not a good solution but this one should work reasonably well.
=> NAS-121779 / 23.10 / Stream app's events on app status changes

src/middlewared/middlewared/plugins/kubernetes_linux/app_migrations.py
This PR adds changes to allow changing catalog name for existing apps. So for example if we want to rename the official catalog, we need to make that happen in 2 places i.e available apps and installed apps, for available ones we would be updating the database and for installed we would be writing a migration which would make this work.
=> NAS-121740 / 23.10 / Add changes to allow renaming catalogs for installed apps

.github/workflows/unittests.yml
We should be installing any relevant dependencies required for the testing environment to work before executing unit tests in the CI.
=> NAS-121806 / 23.10 / Install relevant dependencies before running unit tests in CI

src/middlewared/middlewared/plugins/catalogs_linux/apps.py, src/middlewared/middlewared/plugins/catalogs_linux/item_version.py, src/middlewared/middlewared/plugins/catalogs_linux/items.py
It was requested by the UI team to have the `home` attribute be made available in the `app.available` response.
=> NAS-121808 / 23.10 / Add home attribute to app details

src/middlewared/middlewared/plugins/usage.py
Remove osc module from this plugin since it's not needed.
Original PR: https://github.com/truenas/middleware/pull/11227
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121812
=> NAS-121812 / 22.12.3 / remove osc module from usage.py plugin (by yocalebo)

src/middlewared/middlewared/plugins/usage.py
This was requested by the PM team to have the raw zpool capacity (i.e. zpool list -p -o size) output in the usage stats.
=> NAS-121718 / 23.10 / add zpool list -o size output to usage.py plugin

src/middlewared/middlewared/plugins/usage.py
This was requested by the PM team to have the raw zpool capacity (i.e. zpool list -p -o size) output in the usage stats.
Original PR: https://github.com/truenas/middleware/pull/11232
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121718
=> NAS-121718 / 22.12.3 / add zpool list -o size output to usage.py plugin (by yocalebo)

src/freenas/etc/default/kexec
We've noticed that "reboot" command is bypassing the grub boot menu. Because of this fact, on upgrade, the upgrade isn't booted into. Even though there is a new boot environment with the new upgrade and that new boot environment is even "activated" (according to zectl list output). This has something to do with kexec. Fortunately, there seems to be a relatively safe and easy work-around to fix this by using USE_GRUB_CONFIG=true.
=> NAS-121795 / 23.10 / fix cobia upgrades

src/middlewared/middlewared/plugins/usage.py
We're also iterating over the root_datasets.values() to calculate the total_capacity unnecessarily. We can calculate this value when we're iterating over the datasets when we gather the context which gets passed to all the functions.
=> NAS-121826 / 23.10 / add total_capacity to context in usage.py

tests/protocols/nfs_proto.py
Very small fix in an NFS CI routine that's most likely not yet used.
=> NAS-121824 / 23.10 / Fix cut-n-paste issue.

src/middlewared/middlewared/plugins/usage.py
- we already capture service information in context so there is no reason to service.query again in the gather_rsyncmod_stats() method so use the context['services'] key instead
- "type" is a builtin for python and it's not best practice to overwrite those so change it to _type
- simplify, remove unnecessary newlines, and remove an unnecessary variable in gather_pools()
=> NAS-121828 / 23.10 / Improve usage.py some more

src/middlewared/middlewared/plugins/usage.py
- we already capture service information in context so there is no reason to service.query again in the gather_rsyncmod_stats() method so use the context['services'] key instead
- "type" is a builtin for python and it's not best practice to overwrite those so change it to _type
- simplify, remove unnecessary newlines, and remove an unnecessary variable in gather_pools()
Original PR: https://github.com/truenas/middleware/pull/11244
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121828
=> NAS-121828 / 22.12.3 / Improve usage.py some more (by yocalebo)

src/middlewared/middlewared/plugins/usage.py, src/middlewared/middlewared/plugins/zfs.py
There is no reason to use deepcopy in gather_backup_stats. Keeping a set with dataset names allows us to remove the necessity of deepcopy'ing 3 times in this method alone. That's painful.
- allow getmntinfo() to be passed as kwarg to zfs.dataset.path_to_dataset
- capture getmntinfo() in the context variable in usage.py
- remove deepcopy in gather_backup_stats
- remove another unnecessary iteration over all datasets
- remove unnecessary variables and newlines
Original PR: https://github.com/truenas/middleware/pull/11246
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121833
=> NAS-121833 / 22.12.3 / Remove 3 deepcopy(s) from usage.py improving perf and memory consumption (by yocalebo)

src/freenas/etc/default/kexec.d/truenas
/etc/default/kexec is being overwritten it seems since kexec.service is a sysv generated file. Create a new file "truenas" in /etc/default/kexec.d/ with just the option that we want to enable.
=> NAS-121851 / 23.10 / fix cobia upgrades (again)

src/middlewared/middlewared/plugins/pool.py
This for loop is filtering to ensure the object (dictionary) has an "encrypted_provider" key and value, however, there is a typo that is passing the dict object to the next method instead of the "encrypted_provider" key's value (a string). This causes an AttributeError crash further down the rabbit hole. Excerpt of the traceback
```
File "/usr/local/lib/python3.9/site-packages/middlewared/plugins/pool.py", line 1047, in get_disks
if disk_name := await self.middleware.call('disk.label_to_disk', prov, False, cache):
File "/usr/local/lib/python3.9/site-packages/middlewared/main.py", line 1279, in call
File "/usr/local/lib/python3.9/site-packages/middlewared/main.py", line 1247, in _call
return await self.run_in_executor(prepared_call.executor, methodobj, …
```
=> NAS-121860 / 13.0 / Fix AttributeError crash

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
Because of a typo in the logic in https://github.com/truenas/middleware/pull/11206/commits/fe45c4ffeb64527461fb7f3f027372e4c71b483e we were not properly re-setting custom props of k8s datasets which resulted in various mounting errors.
Fix the typo and make sure accurate mapping takes place for the kubernetes datasets we have defined so proper properties can be applied.
=> NAS-121849 / 23.10 / Fix ix-appilcation dataset split bug

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
Because of a typo in the logic in https://github.com/truenas/middleware/pull/11206/commits/fe45c4ffeb64527461fb7f3f027372e4c71b483e we were not properly re-setting custom props of k8s datasets which resulted in various mounting errors.
Fix the typo and make sure accurate mapping takes place for the kubernetes datasets we have defined so proper properties can be applied.
Original PR: https://github.com/truenas/middleware/pull/11254
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121849
=> NAS-121849 / 22.12.3 / Fix ix-appilcation dataset split bug (by Qubad786)

tests/api2/test_130_cloudsync.py
It is not defined and not use in the step definition.
=> TE-405 / 13.0 / Remove env in test 96 of test_130_cloudsync.py

src/middlewared/middlewared/plugins/disk_/swap_configure.py, src/middlewared/middlewared/pytest/unit/plugins/disk/test_swap_configuration.py
Changes have been made to not use data pool disks for swap configuration if swap partitions exist in the boot-pool.
While at it have also done some optimizations to not list all disks partitions while configuring swap to handle cases where systems have thousands of disks which are not involved in pools or the system is HA capable and data pool based disks should not be touched at all. In cases like these we only take those disks into account for listing partitions which can actually be used in swap.
=> NAS-121632 / 23.10 / Don't create swap from data pool if swap partitions in boot pool exist

src/middlewared/middlewared/plugins/boot.py, src/middlewared/middlewared/plugins/pool_/pool.py
This PR adds changes to change `ashift` to `12` if it is at `DEFAULT` value whenever a zfs pool is updated or extended.
=> NAS-112093 / 23.10 / Set ashift to 12 for pools which do not have it

src/middlewared/middlewared/plugins/boot.py, src/middlewared/middlewared/plugins/pool.py
This PR adds changes to change `ashift` to `12` if it is at `DEFAULT` value whenever a zfs pool is updated or extended.
Original PR: https://github.com/truenas/middleware/pull/11257
Jira URL: https://ixsystems.atlassian.net/browse/NAS-112093
=> NAS-112093 / 13.0 / Set ashift to 12 for pools which do not have it (by sonicaj)

src/middlewared/middlewared/plugins/boot.py, src/middlewared/middlewared/plugins/pool.py
This PR adds changes to change `ashift` to `12` if it is at `DEFAULT` value whenever a zfs pool is updated or extended.
Original PR: https://github.com/truenas/middleware/pull/11257
Jira URL: https://ixsystems.atlassian.net/browse/NAS-112093
=> NAS-112093 / 22.12.3 / Set ashift to 12 for pools which do not have it (by sonicaj)

src/middlewared/middlewared/plugins/pool_/unlock.py
We have encountered a use case where the parent dataset is locked, but its child dataset is being used as a disk by a virtual machine (VM). This scenario has not been addressed before. The dataset logic checks for a mount path like `/mnt/tank/enc` in the pool, but the path on the VM is in the form of a zvol, such as `/zvol/tank/enc/vm-vol`.
To resolve this issue, we need to verify whether the zvol disk is a child of the unlocked dataset or not. If it is a child, then we should restart the VM.
=> NAS-121696 / 23.10 / Properly cover the case where parent of VM disk device is encrypted

src/middlewared/middlewared/plugins/pool_/unlock.py
We have encountered a use case where the parent dataset is locked, but its child dataset is being used as a disk by a virtual machine (VM). This scenario has not been addressed before. The dataset logic checks for a mount path like `/mnt/tank/enc` in the pool, but the path on the VM is in the form of a zvol, such as `/zvol/tank/enc/vm-vol`.
To resolve this issue, we need to verify whether the zvol disk is a child of the unlocked dataset or not. If it is a child, then we should restart the VM.
Original PR: https://github.com/truenas/middleware/pull/11220
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121696
=> NAS-121696 / 22.12.3 / Properly cover the case where parent of VM disk device is encrypted (by Qubad786)

tests/api2/test_341_pool_dataset_encryption.py
This commit fixes encryption tests as with last changes where numbering prefixes were removed for the tests, a lot of the tests ended up with similar names as the number was the only difference between them which resulted in subsequent similar named tests to not execute.
```
api2/test_341_pool_dataset_encryption.py::test_verify_the_the_child_got_props_by_the_parent_root PASSED                                                [ 98%]
api2/test_341_pool_dataset_encryption.py::test_delete_the_key_encrypted_pool_with_all_the_dataset 2023 May 10 07:54:11 truenas md/raid1:md127: Disk failure on sdb1, disabling device.
md/raid1:md127: Operation continuing on 1 devices.
PASSED                                               [100%]
---------------------------------------------- generated xml file: …
```
=> NAS-121897 / 23.10 / Fix encryption tests again

src/middlewared/middlewared/plugins/disk_/sync.py
This does 2 things primarily.
1. revert https://github.com/truenas/middleware/pull/11139 since it caused a regression preventing disk.sync_all to function which means disks to not get properly written to db
2. fix the original problem that the offending commit tried to do by replacing double-quotes with utf8 url encoded value
We do this already in this function up a few lines with single-quotes. The predicate that gets passed to the xml function must be surrounded by double-quotes but escaping that double-quote the traditional way does not work. Replacing double-quotes with the utf8 encoded value is sufficient. Furthermore, this is an edge-case bug so don't expect it to be hit that often in the wild.
=> NAS-121910 / 13.0 / fix regression and edge-case crash in disk.sync_all

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/map.py
This is the correct mapping for the Mini 3.0 X version 1.0 according to internal documentation.
=> NAS-121909 / 13.0 / fix MINI 3.0 X version 1.0 enclosure mapping

tests/boot.exp
This will fix the boot issue for 13.1. It should now affect the 13.0 boot since it is how it is set up for the 13.0 and 13.1 HA boot.
There is a https:// in the boot of 13.1.
```
---<<BOOT>>---
Copyright (c) 1992-2021 The FreeBSD Project.
Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
The Regents of the University of California. All rights reserved.
FreeBSD is a registered trademark of The FreeBSD Foundation.
FreeBSD 13.2-RELEASE truenas/13.1-stable-d0c24e376 TRUENAS amd64
FreeBSD clang version 14.0.5 (https://greset/: standard error: Inappropriate ioctl for device
```
=> NAS-121912 / 13.0 / Expect Enter an option instead of https:// in boot.exp

src/middlewared/setup.py
Support for app migrations was added but the directory which will hold these migrations was not being added to the final middlewared installed files which resulted in kubernetes setup failing as on setup app migrations are executed. This is also resulting in various integration tests to fail.
`app_migrations` directory has been added to the list of middlewared installed files.
Original PR: https://github.com/truenas/middleware/pull/11286
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121913
=> NAS-121913 / 22.12.3 / Add app migrations to installed middlewared files (by Qubad786)

src/middlewared/middlewared/plugins/disk_/swap_configure.py, src/middlewared/middlewared/plugins/pool_/format_disks.py
We don't configure swap on data drives when swap partitions exist on boot drive with recent changes. However we were still creating partitions nevertheless which should not be done as it is no longer required.
Check if system is either HA capable or has swap partition on boot pool disks and if either is true we don't create swap partition on data pool disks.
**Note**: This does mean that as the disks will be formatted and swap partition will not be created on them, if for some reason the boot disks are phased out which had swap partitions or if the data pool was exported and imported in another TrueNAS - swap cannot be configured on that data pool disks because the partitions don't exist.
=> NAS-121917 / 23.10 / Do not create swap partition when swap detected on boot drive

src/middlewared/middlewared/main.py
This was introduced in python 3.11 and has been on my radar for awhile. This allows for cleaning up resources that our child processes accumulate during normal operation. I don't expect it to solve the worlds problems, but it's an easy way to "clean up" memory usage on large systems or systems that have a large uptime.
To quote the docs
```
max_tasks_per_child is an optional argument that specifies the maximum number of tasks a single process can execute
before it will exit and be replaced with a fresh worker process. By default max_tasks_per_child is None which means
worker processes will live as long as the pool.
=> NAS-121918 / 23.10 / max_tasks_per_child for process pool workers

src/middlewared/middlewared/plugins/account.py
Missing "await" for this coroutine so it's never being scheduled to be executed as a task.
Original PR: https://github.com/truenas/middleware/pull/11293
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121924
=> NAS-121924 / 22.12.3 / fix un-awaited coroutine in account.py (by yocalebo)

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
1. failover.update has been broken for a long time. The truth logic is inversed (`if master is not NOT_PROVIDED` should be `if master is NOT_PROVIDED`). This took me entirely too long to notice but once I did, I realized this can be simplified and prevents the next developer from trying to understand obtuse logic.
2. Once I got the logic working in failover.update, I noticed another issue in failover.force_master and traced it to a cherry-pick from SCALE to CORE for `failover.events.event` but that does not exist on CORE, it is still just `failover.event`
This fixes the ability in the webUI to go to `System->Failover` and disable HA and mark the other truenas controller as the default controller (trigger a failover event in a round-about way).
=> NAS-121932 / 13.0 / fix 2 regressions in 13 HA code

src/middlewared/middlewared/plugins/ldap.py
pdbldap requires encrypted LDAP transport since it is accessing sensitive user information via the LDAP schema. This also fixes a typo in SSL configuration validition.
=> NAS-121945 / 23.10 / Add validation to force encryption with LDAP SMB

src/middlewared/middlewared/plugins/docker_linux/images.py, src/middlewared/middlewared/plugins/docker_linux/utils.py
This PR adds changes to use subprocess for pulling large docker images in bluefin as the python client which we were using breaks the connection when pulling large images and so does k3s.
This is not an issue in cobia, so for bluefin let's use subprocess instead.
=> NAS-121506 / 22.12.3 / Use subprocess for pulling large docker images

src/middlewared/setup.py
Currently there are no app migrations written and the app migrations folder contains `.gitkeep` file which is not being retrieved by `get_assets` function. This results in the folder being missing which causes other regressions including failure of various integration tests.
If we have a file named `.gitkeep`, let's gather it when we gather our assets which should be installed in the system.
Original PR: https://github.com/truenas/middleware/pull/11304
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121959
=> NAS-121959 / 22.12.3 / Properly make sure app migrations dir is copied over (by Qubad786)

src/middlewared/middlewared/plugins/pool_/dataset_details.py
This PR addresses an issue where a user reported encrypted properties were not being correctly reported in the UI which on investigation i found that we were first building a mapping of all datasets and then performing an additional loop to normalize the dataset which was redundant and we were making some mistake with the references of the objects being maintained which resulted in the dataset not properly reflecting it's normalized properties.
I have not investigated the actual reference issue but just not maintaining that mapping and normalizing in one iteration fixes the issue reasonably.
Left one outlines the one without fix and the right one with the fix.
=> NAS-120096 / 23.10 / Fix normalization of datasets 

tests/api2/test_261_iscsi_cmd.py, tests/protocols/iscsi_proto.py
git cherry-pick -x ae57d7688873c052e9867a80ace1c039a6850c01
git cherry-pick -x 61463a6b0736bd1df0a1cc15353f0c6912318903
git cherry-pick -x 16a85ecde8e2e4a8fcf3841aae65178896b532e4
git cherry-pick -x 4bad047b6d5e0de080403428c4c8172131c1d030
Now that SCST has been updated to check initiator name upon LOGIN, add a unit test.
Original PR: https://github.com/truenas/middleware/pull/11314
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121743
=> NAS-121743 / 22.12.3 / NAS-121743 (by bmeagherix)

src/middlewared/middlewared/plugins/disk_/swap_mirror.py
We have come across a case where when same disk was used in a pool in the system and then taken out and then put back again in which resulted in not all md devices not showing up in `/dev/md` directory but still showing up as a device under `/dev`.
`/proc/mdstat` contains all references of used/unused md devices which we are now using. However that does not get us the custom array name which we specify so we still retrieve that information from `/dev/md` and come up with a complete mapping of supported/un-supported md devices.
This in turn makes sure the logic we already have in place to remove disks from mirrors even if they are un-supported ones work automatically leaving nothing else to be changed.
=> NAS-121786 / 23.10 / Get all unsupported md mirrors

src/middlewared/middlewared/plugins/disk_/swap_mirror.py
We have come across a case where when same disk was used in a pool in the system and then taken out and then put back again in which resulted in not all md devices not showing up in `/dev/md` directory but still showing up as a device under `/dev`.
`/proc/mdstat` contains all references of used/unused md devices which we are now using. However that does not get us the custom array name which we specify so we still retrieve that information from `/dev/md` and come up with a complete mapping of supported/un-supported md devices.
This in turn makes sure the logic we already have in place to remove disks from mirrors even if they are un-supported ones work automatically leaving nothing else to be changed. 
Original PR: https://github.com/truenas/middleware/pull/11289
Jira URL: …
=> NAS-121786 / 22.12.3 / Get all unsupported md mirrors (by Qubad786)

src/middlewared/middlewared/plugins/enclosure_/nvme.py, src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/failover_/detect_enclosure.py, src/middlewared/middlewared/plugins/failover_/internal_interface.py, src/middlewared/middlewared/plugins/truenas.py
This adds logic to properly detect the F1 HA product type. NOTE: this does not add the drive bay identification logic (that will come in another PR)
Original PR: https://github.com/truenas/middleware/pull/11313
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121259
=> NAS-121259 / 22.12.3 / add F1 product detection (by yocalebo)

src/middlewared/middlewared/etc_files/local/openvpn/server/perms.py, src/middlewared/middlewared/plugins/etc.py
This PR fixes the ownership of openvpn server based log files which happened to be `root/root`. A user reported issues with his OpenVPN server not accepting clients because of these permission issues which when he manually fixed resulted in successful connection.
The user in question had some extra parameters specified as well but i think it is generally speaking good practice to do this.
Original PR: https://github.com/truenas/middleware/pull/11321
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121359
=> NAS-121359 / 22.12.3 / Fix openvpn server logs ownership (by sonicaj)

src/middlewared/middlewared/plugins/ipmi.py, src/middlewared/middlewared/schema.py, src/middlewared/middlewared/validators.py
This addresses a couple of issues with IPMI password validation
1) The webui lists password complexity requirements that are
not validated within middleware before sending payload
through ipmitool.
2) Password length of 20 characters is enforced in middleware,
but this value exceeds that supported by ipmi 1.5 (16 characters).
The first item is problematic because the error messages from ipmitool for passwords that lack sufficient complexity are less than helpful ("Request data field length limit exceeded").
The second item is also incredibly problematic because on some devices a password of more than 16 characters will be silently truncated to 16 characters.
This PR shifts validation to the middleware schema by introducing two changes:
a) Password() schema type. This currently only …
=> NAS-121993 / 13.0 / Improve IPMI password validation (#9251)

src/middlewared/middlewared/alert/source/enclosure_status.py
git cherry-pick -x 38d01a1bf8dca9e2a94177d76490070dec54b736
git cherry-pick -x 4c0bc47e12995e8967b525cc1d99bc323d3c0f3c
Enclosure elements can "flap" (i.e. report a bad status but then be cleared almost immediately). The alert that is flapping is a particular problem in and of itself. However, this fixes the scenario so that we wait a bit before we raise an alert to the end-user.
Original PR: https://github.com/truenas/middleware/pull/11260
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121881
=> NAS-121881 / 22.12.3 / Fix flapping enclosure alerts (by themylogin)

src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/activedirectory_/dns.py, src/middlewared/middlewared/plugins/activedirectory_/health.py
Pass through the legacy dns_timeout key to our DNS client plugin when doing various AD checks. This potentially allows users to account for really terrible DNS. Since the DNS client ops are not called within a job, timeout should have some validation to prevent setting something too low or too high.
Original PR: https://github.com/truenas/middleware/pull/11208
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121788
=> NAS-121788 / 22.12.3 / Make DNS timeouts for AD checks configurable (by anodos325)

src/middlewared/middlewared/plugins/account.py, tests/api2/test_011_user.py
We should catch following cases and turn them into informative validation errors:
* New home directory doesn't exist and parent directory is on RO dataset
* New home directory doesn't exist and parent directory is immutable
* New home directory exists and is on RO dataset or immutable
Since we're already having to get mount information, this commit adds an additional check for filesystem type in the returned mount info. If any validation errors have been added, then skip more expensive checks using libzfs.
=> NAS-121206 / 23.10 / Expand validation of user home directories

src/middlewared/middlewared/plugins/account.py, tests/api2/test_011_user.py
We should catch following cases and turn them into informative validation errors:
* New home directory doesn't exist and parent directory is on RO dataset
* New home directory doesn't exist and parent directory is immutable
* New home directory exists and is on RO dataset or immutable
Since we're already having to get mount information, this commit adds an additional check for filesystem type in the returned mount info. If any validation errors have been added, then skip more expensive checks using libzfs.
Original PR: https://github.com/truenas/middleware/pull/10994
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121206
=> NAS-121206 / 22.12.3 / Expand validation of user home directories (by anodos325)

src/middlewared/middlewared/alembic/versions/22.12/2023-04-27_08-00_official_catalog_rename.py, src/middlewared/middlewared/alembic/versions/22.12/2023-05-18_08-00_official_catalog_rename.py, src/middlewared/middlewared/plugins/catalogs_linux/update.py
This PR adds changes to rename the official catalog to be named as `Truenas` instead. This change affects apps which we are going to install or update and not the already existing ones. There is a separate PR for that change.
=> NAS-121517 / 22.12.3 / Rename official catalog to "Truenas"

src/middlewared/middlewared/plugins/ipmi.py, src/middlewared/middlewared/plugins/ipmi_/lan.py
This does a few things:
- add an ipmi.lan plugin since the generic "ipmi" plugin isn't the proper namespace
- mask lan channel 8 on the F1 HA platform
- move the crud portion of the generic ipmi plugin to the ipmi.lan plugin
- use `ipmi-config` binary which prevents (potentially) 16x subprocesses when the channels function is first called
NOTE: I've kept the same logic for the ipmi.lan.update that was in ipmi.update. However, this could be simplified (I predict) by using `ipmi-config` as well. That will come in another PR.
=> NAS-122006 / 23.10 / add ipmi.lan plugin and hide ipmi lan channel 8 on F1 HA

src/middlewared/middlewared/alembic/versions/22.12/2023-04-27_08-00_official_catalog_rename.py, src/middlewared/middlewared/alembic/versions/22.12/2023-05-18_08-00_official_catalog_rename.py, src/middlewared/middlewared/alembic/versions/23.10/2023-05-19_18-00_merge.py, src/middlewared/middlewared/plugins/catalogs_linux/update.py
This PR adds changes to rename the official catalog to be named as `Truenas` instead. This change affects apps which we are going to install or update and not the already existing ones. There is a separate PR for that change.
Original PR: https://github.com/truenas/middleware/pull/11348
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121517
=> NAS-121517 / 23.10 / Rename official catalog to "Truenas" (by sonicaj)

src/middlewared/middlewared/plugins/kubernetes_linux/app_migrations/01_middleware_migrate_official_catalog.json
This PR adds changes to account for the rename we are doing of `OFFICIAL` catalog to be named as `TRUENAS`.
=> NAS-122038 / 23.10 / Migrate existing installed apps to TrueNAS catalog

debian/debian/postinst
Despite a 'preset' value of 'disabled, the NFS package install
results in running the NFS server at boot.   We add an explicit
disable for the service as a work around.
=> Fix NFS 'at boot' state

src/middlewared/middlewared/plugins/kubernetes_linux/app_migrations/01_middleware_migrate_official_catalog.json
This PR adds changes to account for the rename we are doing of `OFFICIAL` catalog to be named as `TRUENAS`.
Original PR: https://github.com/truenas/middleware/pull/11347
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122038
=> NAS-122038 / 22.12.3 / Migrate existing installed apps to TrueNAS catalog (by sonicaj)

src/middlewared/middlewared/plugins/catalogs_linux/apps.py
We were retrieving similar apps based on common tags/categories, however this did not prioritise apps which were more "similar".
An improvement to the existing logic has been added where a similarity score has been added and we sort the similar apps based on the similarity score generated so apps which are more similar are prioritised first when retrieving similar apps.
=> NAS-121981 / 23.10 / Add similarity score for retrieving similar apps

src/middlewared/middlewared/plugins/smb.py, tests/api2/test_425_smb_protocol.py
Forcibly shut down SMB sessions if share is being locked or disabled.
=> NAS-122042 / 23.10 / Close SMB share in a few more cases

src/middlewared/middlewared/plugins/smb.py, tests/api2/test_425_smb_protocol.py
Forcibly shut down SMB sessions if share is being locked or disabled.
Original PR: https://github.com/truenas/middleware/pull/11350
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122042
=> NAS-122042 / 22.12.3 / Close SMB share in a few more cases (by anodos325)

src/middlewared/middlewared/plugins/pool.py
git cherry-pick -x b2faaf0fa1b32e0425dc035da8badca86437b050
git cherry-pick -x bd3e8959529925dfc35128773806fa7b0bacb0b1
(might be erroneously set previously)
Original PR: https://github.com/truenas/middleware/pull/11360
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121907
=> NAS-121907 / 22.12.3 / Remove immutable flag after mounting unlocked dataset too (by themylogin)

src/middlewared/middlewared/plugins/network.py
Details on the justification for doing this can be obtained from the platform team.
=> NAS-122007 / 23.10 / hide eno1 interface on F1 HA systems

src/middlewared/middlewared/plugins/activedirectory_/cache.py, src/middlewared/middlewared/plugins/cache.py
Store SID information when generating our AD user and group cache. In cases where user, uid, group, or gid are explicitly specified in query request, we directly query NSS on cache miss. In this case we need to also retrieve SID information and insert into new cache entry that is generated.
=> NAS-122089 / 23.10 / Optimize and fix retrieval of SID info for AD user

src/middlewared/middlewared/plugins/smb_/sharesec.py, src/middlewared/middlewared/schema.py
There are a few API endpoints where we may ingest SIDs (even if internally), and so it's helpful to have schema validation option for them. This uses a freshly-minted py_wbclient method to perform validation (will not block).
=> NAS-122093 / 23.10 / Add schema validation for Windows SIDs

src/middlewared/middlewared/plugins/smb_/sharesec.py, src/middlewared/middlewared/schema.py
There are a few API endpoints where we may ingest SIDs (even if internally), and so it's helpful to have schema validation option for them. This uses a freshly-minted py_wbclient method to perform validation (will not block).
Original PR: https://github.com/truenas/middleware/pull/11373
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122093
=> NAS-122093 / 22.12.3 / Add schema validation for Windows SIDs (by anodos325)

src/middlewared/middlewared/plugins/service_/services/openvpn_client.py, src/middlewared/middlewared/plugins/service_/services/openvpn_server.py, src/middlewared/middlewared/plugins/service_/services/rsync.py
This marks the openvpn server, openvpn client and rsync host services as deprecated.
=> NAS-122096 / 22.12.3 / mark opnvpn{client/server} and rsync as deprecated

src/middlewared/middlewared/plugins/account_/privilege.py, src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/idmap.py
SIDS are more stable (can't change value based on user configuration)
and so should be preferred for mapping privileges for directory
services groups.
This PR adds a bulk conversion API for mapping unix ids to SIDs, which
is used for privilege evaluation.
=> NAS-122102 / 23.10 / Prefer sids privileges

src/middlewared/middlewared/plugins/usage.py
If usage reporting is restricted, we still want to gather the platform key. Move this logic to `gather_system_version` since that method is called regardless of whether or not usage restriction is toggled.
=> NAS-122135 / 23.10 / fix usage reporting when it's restricted

src/middlewared/middlewared/plugins/usage.py
If usage reporting is restricted, we still want to gather the platform key. Move this logic to `gather_system_version` since that method is called regardless of whether or not usage restriction is toggled.
Original PR: https://github.com/truenas/middleware/pull/11387
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122135
=> NAS-122135 / 22.12.3 / fix usage reporting when it's restricted (by yocalebo)

src/middlewared/middlewared/alert/source/enclosure_status.py
"Not Installed" or any variation thereof for an element in an enclosure doesn't warrant us alerting the end-user. This change was made in CORE but not backported here.
=> NAS-122136 / 23.10 / remove "not installed" as a bad element status

src/middlewared/middlewared/alert/source/enclosure_status.py
"Not Installed" or any variation thereof for an element in an enclosure doesn't warrant us alerting the end-user. This change was made in CORE but not backported here.
Original PR: https://github.com/truenas/middleware/pull/11389
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122136
=> NAS-122136 / 22.12.3 / remove "not installed" as a bad element status (by yocalebo)

src/middlewared/middlewared/plugins/chart_releases_linux/schema.py
Chart devs specifying `empty` was having no effect as when the schema was converted to middleware schema objects the attribute was not being passed on.
Make sure the attribute if specified by chart dev is respected on the conversion to middleware schema so proper validation can take place.
=> NAS-122139 / 23.10 / Respect empty attribute specified on schema

src/middlewared/middlewared/alert/source/deprecated_service.py
This improves the verbiage for the deprecated service alert in Bluefin. With guidance from technical documentation team.
Original PR: https://github.com/truenas/middleware/pull/11393
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122140
=> NAS-122140 / 23.10 / improve verbiage for deprecated service alert (by yocalebo)

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/activedirectory_/dns.py, src/middlewared/middlewared/plugins/auth_/authenticate.py, src/middlewared/middlewared/plugins/cache.py, tests/api2/test_030_activedirectory.py
Grant members of domain admins group full API control after successful domain join. This is more-or-less expected by AD admins, and is still gated on enabling the global configuration option to allow directory services API access.
=> NAS-122103 / 23.10 / Make domain admins middleware admins

src/middlewared/middlewared/alert/source/deprecated_config.py, src/middlewared/middlewared/plugins/ldap.py
This isn't used in Bluefin (yet) but is needed in Cobia since we have parameters for certain services that are being deprecated. This separates deprecated services vs deprecated service configuration.
Original PR: https://github.com/truenas/middleware/pull/11395
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122143
=> NAS-122143 / 23.10 / add DeprecatedServiceConfigurationAlert (by yocalebo)

src/middlewared/middlewared/pytest/unit/test_schema.py, src/middlewared/middlewared/schema.py
There are a couple of places in middleware where we call `IPAddr().validate(ip)`.  This _used_ to raise an error if an invalid value was provided, but has not done so since Dec 2021.
Therefore, added some additional tests, along with a **tentative** fix for `IPAddr.validate` (mostly to solicit input).
=> NAS-122157 / 23.10 / Fix ipaddr

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
On a failover event we are importing pools using `zpool import` command bypassing middleware which suits us in a variety of ways.
However after importing pool we run `pool.dataset.unlock` essentially to unlock any datasets whose keys we might have in the database..during unlock we have a flag to toggle attachments which is enabled by default. What this did in the current case is that after each pool import it toggled all related services which caused variety of different issues.
We should not be toggling attachments after each pool import while unlocking that pool's datasets as we have relevant logic in place which dictates the service restarts after pools have imported..this change already exists in `stable/bluefin` but has not been backported to CORE …
=> NAS-122178 / 13.0 / Don't toggle attachments after importing pool during failover

src/middlewared/middlewared/plugins/etc.py
We need to generate the smb.conf during ctdb startup, but setting up PAM at this point creates potential for CTDB_START cluster event to hang for an unreasonable time. There's not really a downside to configuring pam_winbind settings with other pam settings.
=> NAS-122177 / 23.10 / Avoid tdb lookup during cluster start

src/middlewared/middlewared/common/attachment/__init__.py, tests/api2/test_encrypted_dataset_services_restart.py
Services are not restarted when datasets are unlocked if they were already stopped at the time of unlocking. In a change introduced in https://github.com/truenas/middleware/pull/7388, motivation was that we should always be restarting/reloading necessary services and that does not take into account the case where service was stopped at the time dataset was unlocked.
After discussing with Caleb, we decided that the service if stopped should be started on dataset unlock if the service is meant to be started on boot. Changes have been made to Lockable FS attachment delegate so any attachments defined using this will be making use of this change.
For testing this change, i configured different shares and tried following cases to see that we are not regressing:
1. Exporting pool
2. Deleting …
=> NAS-121697 / 23.10 / Start service if it stopped for lockable fs attachment delegates

src/middlewared/middlewared/job.py, src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/update.py, src/middlewared/middlewared/plugins/update_/install.py, src/middlewared/middlewared/plugins/update_/install_linux.py, src/middlewared/middlewared/plugins/update_/upload_location_linux.py
Warning will be returned as `EAGAIN` `CallError`. The UI will check for this specific `errno`, present a yes/no dialog, and, if "yes" is selected, will call the same method but with `{"resume": true}` option (no file re-upload will be necessary, no repeated network requests will be performed).
=> NAS-121891 / 23.10 / Consume update warnings and allow resuming the update after warning

src/middlewared/middlewared/job.py, src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/update.py, src/middlewared/middlewared/plugins/update_/install.py, src/middlewared/middlewared/plugins/update_/install_linux.py, src/middlewared/middlewared/plugins/update_/upload_location_linux.py
Warning will be returned as `EAGAIN` `CallError`. The UI will check for this specific `errno`, present a yes/no dialog, and, if "yes" is selected, will call the same method but with `{"resume": true}` option (no file re-upload will be necessary, no repeated network requests will be performed).
Original PR: https://github.com/truenas/middleware/pull/11391
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121891
=> NAS-121891 / 22.12.4 / Consume update warnings and allow resuming the update after warning (by themylogin)

src/middlewared/middlewared/job.py, src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/update.py, src/middlewared/middlewared/plugins/update_/install.py, src/middlewared/middlewared/plugins/update_/install_linux.py, src/middlewared/middlewared/plugins/update_/upload_location_linux.py
Warning will be returned as `EAGAIN` `CallError`. The UI will check for this specific `errno`, present a yes/no dialog, and, if "yes" is selected, will call the same method but with `{"resume": true}` option (no file re-upload will be necessary, no repeated network requests will be performed).
Original PR: https://github.com/truenas/middleware/pull/11391
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121891
Original PR: https://github.com/truenas/middleware/pull/11409
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121891
=> NAS-121891 / 22.12.3 / Consume update warnings and allow resuming the update after warning (by themylogin) (by bugclerk)

src/middlewared/middlewared/plugins/usage.py
Rsyncd service has been removed from middleware and gathering stats about rsynd is bound to fail.
Remove the endpoint we had in place to gather stats about rsyncd service.
=> NAS-122221 / 23.10 / Remove rsyncd stats from usage service

src/middlewared/middlewared/plugins/crypto_/certificates.py
This PR adds changes to allow updating renew days attribute for ACME certs so users can define when they expect the cert to be renewed i.e 5 days before expiry or 1 day before expiry etc.
=> NAS-121479 / 23.10 / Allow updating renew_days attribute for ACME certs

src/middlewared/middlewared/plugins/hardware_/m_series_nvdimm.py
2 problems (typos) being fixed.
- first typo is 0xc180 which should be 0xce01. this was a typo in the internal documentation
- second typo is 0x4e88 which should be 0x4e38. this was a typo introduced during development process
With both typos fixed, no more false nvdimm alerts are raised on m-series platforms with relevant nvdimm modules installed.
=> NAS-122242 / 13.0 / fix typos in nvdimm firmware alert

src/middlewared/middlewared/plugins/vm/supervisor/domain_xml.py, src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_devices_xml.py
The current issue is that Qemu can deflate (decrease) the memory allocation for a guest machine, but it does not have the capability to automatically inflate (increase) the memory allocation when the guest machine requires more memory. This problem leads to out-of-memory (OOM) errors when the guest machine needs more memory, even though the host machine has available memory. Ideally, the system should allocate free memory from the host to the guest machine and inflate the guest machine's memory allocation.
To address this problem, it is necessary to enable automatic deflation of the guest machine's memory allocation. By default, this feature is not enabled. Some changes need to be made in the system configuration to enable automatic deflation.
Once the automatic deflation feature is …
=> NAS-122035 / 23.10 / Make virtio-ballooning auto deflation on

src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
2 problems (typos) being fixed.
- first typo is 0xc180 which should be 0xce01. this was a typo in the internal documentation
- second typo is 0x4e88 which should be 0x4e38. this was a typo introduced during development process
With both typos fixed, no more false nvdimm alerts are raised on m-series platforms with relevant nvdimm modules installed.
Original PR: https://github.com/truenas/middleware/pull/11424
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122242
=> NAS-122242 / 22.12.3 / fix typos in nvdimm firmware alert (by yocalebo)

src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
2 problems (typos) being fixed.
- first typo is 0xc180 which should be 0xce01. this was a typo in the internal documentation
- second typo is 0x4e88 which should be 0x4e38. this was a typo introduced during development process
With both typos fixed, no more false nvdimm alerts are raised on m-series platforms with relevant nvdimm modules installed.
Original PR: https://github.com/truenas/middleware/pull/11424
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122242
=> NAS-122242 / 22.12.4 / fix typos in nvdimm firmware alert (by yocalebo)

src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
2 problems (typos) being fixed.
- first typo is 0xc180 which should be 0xce01. this was a typo in the internal documentation
- second typo is 0x4e88 which should be 0x4e38. this was a typo introduced during development process
With both typos fixed, no more false nvdimm alerts are raised on m-series platforms with relevant nvdimm modules installed.
Original PR: https://github.com/truenas/middleware/pull/11424
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122242
=> NAS-122242 / 23.10 / fix typos in nvdimm firmware alert (by yocalebo)

src/freenas/usr/local/bin/truenas-set-authentication-method.py, src/middlewared/middlewared/alembic/versions/23.10/2023-05-31_19-37_normalize_2fa_records.py, src/middlewared/middlewared/plugins/account.py
This PR adds changes to make sure whenever an admin user is created, we also add a record of that user to our 2fa table as all local users have a 1-1 relation with the 2fa table and this was a case which we had missed where a user was being added but the relevant 2fa record was not being added.
=> NAS-122231 / 23.10 / Revert "Fix KeyError in API tests (#11404)

src/middlewared/middlewared/alert/source/memory_errors.py, src/middlewared/middlewared/plugins/hardware/mem_info.py
We currently have a mechanism to report on APEI or MCA events on CORE for our enterprise users. This brings us to mostly feature parity with CORE by getting the relevant information from sysfs.
=> NAS-120951 / 23.10 / add hardware.memory.error_info endpoint

src/middlewared/middlewared/plugins/ipmi_/chassis.py
I've refactored and improved the ipmi plugin over many commits here recently. Unfortunately, it seems I backported a commit from the master branch that has caused the webUI to reference an endpoint that was removed/refactored in master. This takes the least path of resistance to prevent massive change in middleware and change in webUI.
=> NAS-122271 / 22.12.4 / prevent AttributeError crash (caused by webUI)

src/middlewared/middlewared/plugins/ipmi_/chassis.py
I've refactored and improved the ipmi plugin over many commits here recently. Unfortunately, it seems I backported a commit from the master branch that has caused the webUI to reference an endpoint that was removed/refactored in master. This takes the least path of resistance to prevent massive change in middleware and change in webUI.
Original PR: https://github.com/truenas/middleware/pull/11433
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122271
=> NAS-122271 / 22.12.3 / prevent AttributeError crash (caused by webUI) (by yocalebo)

src/middlewared/middlewared/plugins/webdav.py
After internal discussion with QE and Exec team, it has been decided to prevent the creation of new webdav shares (using the webdav native host service) in 22.12.3. This is to further encourage the migration to the webDAV app since this service has been removed in Cobia (in favor of the webdav app).
This does not prevent the editing or deletion of existing webdav shares, simply prevents new ones from being created.
=> NAS-122280 / 22.12.4 / prevent new webdav share creation

src/middlewared/middlewared/plugins/webdav.py
After internal discussion with QE and Exec team, it has been decided to prevent the creation of new webdav shares (using the webdav native host service) in 22.12.3. This is to further encourage the migration to the webDAV app since this service has been removed in Cobia (in favor of the webdav app).
This does not prevent the editing or deletion of existing webdav shares, simply prevents new ones from being created.
Original PR: https://github.com/truenas/middleware/pull/11435
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122280
=> NAS-122280 / 22.12.3 / prevent new webdav share creation (by yocalebo)

src/middlewared/middlewared/test/integration/assets/two_factor_auth.py
This commit increases 2fa window for API tests as we see some random 2fa failures which are likely related to window specified expiring and 2fa auth failing.
=> NAS-122306 / 23.10 / Increase 2fa window for API tests

src/middlewared/middlewared/plugins/network.py, src/middlewared/middlewared/plugins/vm/devices/display.py, src/middlewared/middlewared/plugins/vm/vm_devices.py
`DISPLAY` devices defaults have been to not ask user to specify `password` as a hard requirement.
However that is not appropriate because if VNC server socket is not protected by password it just means that any malicious actor can just scan ports and then gain access to a VMs console which in most cases is also connected to the user's local network.
Now specifying `password` is a hard requirement for any one looking to create more `DISPLAY` devices or edit the ones they have already. Also by default we are going to bind the VNC/spice server to `localhost` instead of wildcard ip i.e `0.0.0.0` improving the defaults further so only if anyone really wants to expose their VNC server socket they can do so explicitly.
=> NAS-122211 / 23.10 / Improve display devices defaults

src/middlewared/middlewared/plugins/network.py, src/middlewared/middlewared/plugins/vm/devices/display.py, src/middlewared/middlewared/plugins/vm/vm_devices.py
`DISPLAY` devices defaults have been to not ask user to specify `password` as a hard requirement.
However that is not appropriate because if VNC server socket is not protected by password it just means that any malicious actor can just scan ports and then gain access to a VMs console which in most cases is also connected to the user's local network.
Now specifying `password` is a hard requirement for any one looking to create more `DISPLAY` devices or edit the ones they have already. Also by default we are going to bind the VNC/spice server to `localhost` instead of wildcard ip i.e `0.0.0.0` improving the defaults further so only if anyone really wants to expose their VNC server socket they can do so explicitly.
Original PR: https://github.com/truenas/middleware/pull/11429
Jira URL: …
=> NAS-122211 / 22.12.4 / Improve display devices defaults (by Qubad786)

debian/debian/ix-update.service, src/freenas/usr/bin/ix-boot-core.py
/boot/grub was not mounted at the time this script was started which prevented
the GRUB config from being updated and resulted in booting back to CORE not
possible.
Additionally, let's stop running update script when we just need to boot back
to FreeBSD as this consumes too much time.
=> NAS-122319 / 23.10 / Fix booting back to FreeBSD

debian/debian/ix-update.service, src/freenas/usr/bin/ix-boot-core.py
/boot/grub was not mounted at the time this script was started which prevented
the GRUB config from being updated and resulted in booting back to CORE not
possible.
Additionally, let's stop running update script when we just need to boot back
to FreeBSD as this consumes too much time.
Original PR: https://github.com/truenas/middleware/pull/11447
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122319
=> NAS-122319 / 22.12.4 / Fix booting back to FreeBSD (by themylogin)

src/middlewared/middlewared/etc_files/syslogd.py
Generally speaking, /var/log shouldn't have symlinks in it and so we can safely skip any that appear (for example symlink to systemd README file).
=> NAS-122292 / 22.12.4 / Don't try to copy symlinks in /var/log

src/middlewared/middlewared/pytest/unit/test_schema.py, src/middlewared/middlewared/schema.py
@topazbarziv raised a PR https://github.com/truenas/middleware/pull/11443 proposing a fix for properly handling negative integer values as they are not being handled by `Int` schema currently and instead it fails if such a value is supplied.
Co-authored-by: Topaz Barziv <mail@topazbarziv.com>
=> NAS-122318 / 23.10 / Properly handle negative integers in int schema

src/middlewared/middlewared/pytest/unit/test_schema.py, src/middlewared/middlewared/schema.py
@topazbarziv raised a PR https://github.com/truenas/middleware/pull/11443 proposing a fix for properly handling negative integer values as they are not being handled by `Int` schema currently and instead it fails if such a value is supplied.
Co-authored-by: Topaz Barziv <mail@topazbarziv.com>
Original PR: https://github.com/truenas/middleware/pull/11445
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122318
=> NAS-122318 / 22.12.4 / Properly handle negative integers in int schema (by Qubad786)

src/middlewared/middlewared/rclone/remote/storjix.py
In order to determine whether a Storj bucket was associated with iX Systems, the text contents of the bucket's `Attribution` tag in Storj's S3 XML response was checked to see whether it contained the iX-Storj user agent. However, a `TypeError` exception was raised if the bucket was unattributed because the content of the empty `Attribution` element was `None`. This issue has been fixed by gracefully handling the empty element.
=> NAS-122320 / 23.10 / Properly handle unattributed Storj buckets

src/middlewared/middlewared/plugins/smb_/sharesec.py
Shift lookup of share name in smb.sharesec endpoint to earlier in setacl function so that we fail with MatchNotFound if the share doesn't exist. This PR also fixes handling for HOMES shares.
=> NAS-122322 / 23.10 / Improve sharesec validation

src/middlewared/middlewared/plugins/idmap.py, src/middlewared/middlewared/plugins/idmap_/utils.py
We should be parsing the returned winbindd ID type and not SID type. Generally SID type string will match up until handling more obscure edge cases like dynamically allocated IDs via passdb.
=> NAS-122333 / 23.10 / Fix ID parsing in idmap bulk sid conversion

src/middlewared/middlewared/plugins/idmap.py, src/middlewared/middlewared/plugins/idmap_/utils.py
We should be parsing the returned winbindd ID type and not SID type. Generally SID type string will match up until handling more obscure edge cases like dynamically allocated IDs via passdb.
Original PR: https://github.com/truenas/middleware/pull/11460
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122333
=> NAS-122333 / 22.12.4 / Fix ID parsing in idmap bulk sid conversion (by anodos325)

src/middlewared/middlewared/alembic/versions/23.10/2023-04-27_06-20_remove_geli_keys.py, src/middlewared/middlewared/alembic/versions/23.10/2023-06-04_00-20_remove_geli_keys.py, src/middlewared/middlewared/alert/source/volume_status.py, src/middlewared/middlewared/plugins/boot.py, src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/pool_/attach_disk.py, src/middlewared/middlewared/plugins/pool_/dataset.py, src/middlewared/middlewared/plugins/pool_/export.py, src/middlewared/middlewared/plugins/pool_/import_pool.py, src/middlewared/middlewared/plugins/pool_/info.py, src/middlewared/middlewared/plugins/pool_/pool.py, src/middlewared/middlewared/plugins/usage.py, src/middlewared/middlewared/plugins/zettarepl.py
This PR introduces changes to cover usages of encryption fields which we had in pool table.
We still have some leftover references of geli in failover plugin which will be handled in a separate ticket.
=> NAS-120267 / 23.10 / Remove geli related attributes from database

src/middlewared/middlewared/plugins/activedirectory.py
For quite some time already we don't need the AD bindpw stored in our sqlite database. Pop it out of config dict before insertion in activedirectory.update (after we've performed kinit to get kerberos ticket as admin).
Original PR: https://github.com/truenas/middleware/pull/11464
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122344
=> NAS-122344 / 22.12.4 / Rely exclusively on kerberos tickets for AD ops (by anodos325)

src/middlewared/middlewared/plugins/system_general/timezone.py, tests/api2/test_490_system_general.py
The test was failing which caused me to investigate and find a bunch of problems.
- performing blocking IO in the main event loop
- we are reading from a directory and that was producing a bunch of unexpected entries that differed from the command timedatectl list-timezones
- don't read from a directory, just run timedatectl list-timezones since it does exactly what we need
- cache the response of this method using @cache decorator instead of using a class attribute
- fix the test by removing it. We already call timezone_choices endpoint in this test so there is nothing else to do
=> NAS-122330 / 23.10 / fix system.general.timezone_choices and test

src/middlewared/middlewared/plugins/system_general/timezone.py, tests/api2/test_490_system_general.py
The test was failing which caused me to investigate and find a bunch of problems.
- performing blocking IO in the main event loop
- we are reading from a directory and that was producing a bunch of unexpected entries that differed from the command timedatectl list-timezones
- don't read from a directory, just run timedatectl list-timezones since it does exactly what we need
- cache the response of this method using @cache decorator instead of using a class attribute
- fix the test by removing it. We already call timezone_choices endpoint in this test so there is nothing else to do
Original PR: https://github.com/truenas/middleware/pull/11471
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122330
=> NAS-122330 / 22.12.4 / fix system.general.timezone_choices and test (by yocalebo)

src/middlewared/middlewared/plugins/system_general/timezone.py, tests/api2/test_490_system_general.py
The test was failing which caused me to investigate and find a bunch of problems.
- performing blocking IO in the main event loop
- we are reading from a directory and that was producing a bunch of unexpected entries that differed from the command timedatectl list-timezones
- don't read from a directory, just run timedatectl list-timezones since it does exactly what we need
- cache the response of this method using @cache decorator instead of using a class attribute
- fix the test by removing it. We already call timezone_choices endpoint in this test so there is nothing else to do
Original PR: https://github.com/truenas/middleware/pull/11471
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122330
Original PR: https://github.com/truenas/middleware/pull/11472
Jira URL: …
=> NAS-122330 / 22.12.3 / fix system.general.timezone_choices and test (by yocalebo) (by bugclerk)

src/middlewared/middlewared/plugins/system/__init__.py
Crash reporting framework was removed and so we shouldn't set it on start.
=> NAS-122367 / 23.10 / Fix middleware start failure

src/middlewared/middlewared/plugins/vm/devices/display.py, src/middlewared/middlewared/plugins/vm/supervisor/domain_xml.py, src/middlewared/middlewared/plugins/vm/vm_display_info.py
When no explicit port was specified for DISPLAY device we try to auto assign ports which are not being used by the system currently.
That logic was flawed and this resulted in subsequent DISPLAY device getting ports of the first DISPLAY device which is bound to fail.
Logic which provided ports which were unused was fixed to make sure it properly took into account currently used ports in the system and for devices which might already have this issue some changes were made to not allow a VM to start if it's DISPLAY device port is being used by any other VM or a service.
**Note:** Should we add a migration which automatically updates existing DISPLAY devices which have port clashes? Problem with that might be that we might update some ports magically which user was not expecting and it …
=> NAS-122374 / 23.10 / Fix vm display ports logic

src/middlewared/middlewared/plugins/vm/devices/display.py, src/middlewared/middlewared/plugins/vm/supervisor/domain_xml.py, src/middlewared/middlewared/plugins/vm/vm_display_info.py
When no explicit port was specified for DISPLAY device we try to auto assign ports which are not being used by the system currently.
That logic was flawed and this resulted in subsequent DISPLAY device getting ports of the first DISPLAY device which is bound to fail.
Logic which provided ports which were unused was fixed to make sure it properly took into account currently used ports in the system and for devices which might already have this issue some changes were made to not allow a VM to start if it's DISPLAY device port is being used by any other VM or a service.
**Note:** Should we add a migration which automatically updates existing DISPLAY devices which have port clashes? Problem with that might be that we might update some ports magically which user was not expecting and it …
=> NAS-122374 / 22.12.4 / Fix vm display ports logic (by Qubad786)

src/middlewared/middlewared/plugins/vm/devices/display.py, src/middlewared/middlewared/plugins/vm/supervisor/domain_xml.py, src/middlewared/middlewared/plugins/vm/vm_display_info.py
When no explicit port was specified for DISPLAY device we try to auto assign ports which are not being used by the system currently.
That logic was flawed and this resulted in subsequent DISPLAY device getting ports of the first DISPLAY device which is bound to fail.
Logic which provided ports which were unused was fixed to make sure it properly took into account currently used ports in the system and for devices which might already have this issue some changes were made to not allow a VM to start if it's DISPLAY device port is being used by any other VM or a service.
**Note:** Should we add a migration which automatically updates existing DISPLAY devices which have port clashes? Problem with that might be that we might update some ports magically which user was not expecting and it …
=> NAS-122374 / 22.12.3 / Fix vm display ports logic (by Qubad786) (by bugclerk)

src/middlewared/middlewared/plugins/ftp.py
anonpath was allowed to be set unvalidated if onlyanonymous was not enabled.
Also included:
* Clearing anonpath if onlyanonymous is not enabled
* Change the default value of defaultroot from False to True.  This matches our actual default setting
=> NAS-122396 / 23.10 / Fix anonpath validation hole

src/middlewared/middlewared/plugins/test/log.py, tests/conftest.py
We want to log test starts/ends to the middleware log so, when a message is logged, we have a better idea on which test caused it
=> NAS-122390 / 23.10 / Log integration tests start/end

src/middlewared/middlewared/plugins/test/log.py, tests/conftest.py
We want to log test starts/ends to the middleware log so, when a message is logged, we have a better idea on which test caused it
Original PR: https://github.com/truenas/middleware/pull/11479
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122390
=> NAS-122390 / 22.12.3 / Log integration tests start/end (by themylogin)

src/middlewared/middlewared/plugins/ldap.py, tests/api2/test_278_freeipa.py
This first group of tests just validates that we can bind to a FreeIPA LDAP server and configure NSS properly.
=> NAS-122326 / 23.10 / Implement basic FreeIPA tests

src/middlewared/middlewared/plugins/activedirectory.py
There are certain operations (such as configuring DNS correctly) that are critical for a properly functioning domain join. If we fail at this point in the join process then we should remove the computer account that was created earlier in the join.
=> NAS-122431 / 23.10 / Remove computer account on AD join failure

src/middlewared/middlewared/plugins/activedirectory.py
Since we no longer store AD bind passwords persistently we should raise a validation error if user tries to set one without enabling the AD plugin.
=> NAS-122437 / 23.10 / Fix AD form validation edge cases

src/middlewared/middlewared/plugins/smb_/sharesec.py
Shift lookup of share name in smb.sharesec endpoint to earlier in setacl function so that we fail with MatchNotFound if the share doesn't exist. This PR also fixes handling for HOMES shares.
Original PR: https://github.com/truenas/middleware/pull/11454
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122322
=> NAS-122322 / 22.12.4 / Improve sharesec validation (by anodos325)

src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/ldap.py
Ensure that winbind request timeout and passdb path are set back to defaults for standalone server when LDAP and AD are stopped.
=> NAS-122460 / 23.10 / Re-init global SMB parameters when DS stopped

src/middlewared/middlewared/plugins/vm/pci.py
If a PCI device has any controller type which we deem as sensitive to system's functionality, we mark the PCI device as critical but  we are not properly marking it as critical right now.
Properly mark a PCI device as critical as we were missing `any` keyword to do that.
=> NAS-122456 / 23.10 / Properly mark a PCI device as critical

src/middlewared/middlewared/plugins/vm/pci.py
If a PCI device has any controller type which we deem as sensitive to system's functionality, we mark the PCI device as critical but  we are not properly marking it as critical right now.
Properly mark a PCI device as critical as we were missing `any` keyword to do that.
Original PR: https://github.com/truenas/middleware/pull/11501
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122456
=> NAS-122456 / 22.12.4 / Properly mark a PCI device as critical (by Qubad786)

debian/debian/ix-cgroups.service, debian/debian/rules, src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py, src/middlewared/middlewared/plugins/kubernetes_linux/utils.py, src/middlewared/middlewared/scripts/setup_cgroups.py, src/middlewared/setup.py
This PR adds changes to enable cgroup controllers at boot. Motivation behind the change is that OS team found if some process has `PF_NO_SETAFFINITY ` flag set, we are not able to add cpuset controller. This happens when SMB service is started and it has shares mounted which starts a process which has the flag which means that after that we can't enable the `cpuset` controller.
There are 2 approaches to solve the problem:
1. Enable cgroup controllers before everything else
2. Have a firewall in place which does not allow users to connect before the system is ready
After discussion with Andrew, we have done point 1 and Andrew will be syncing with services team to see if we should factor in other services as well for the firewall and those changes can still be added separately as they still …
=> NAS-121919 / 22.12.4 / Enable cgroup controllers at boot (by sonicaj)

src/middlewared/middlewared/client/client.py, src/middlewared/middlewared/plugins/disk_/sync.py, src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/failover_/datastore.py, src/middlewared/middlewared/plugins/failover_/event.py, src/middlewared/middlewared/plugins/failover_/remote.py, src/middlewared/middlewared/plugins/iscsi_/iscsi_global.py, src/middlewared/middlewared/plugins/pool_/export.py, src/middlewared/middlewared/plugins/pool_/pool.py
We had a ton of code duplication and specific error handling for when the remote request fails in known ways. This moves the logic to `failover.call_remote` (the lowest caller in the stack) and handles it there. I've added a logger.trace message there just in case we ever need to start middleware with TRACE debug level set to get the messages. I've also fixed a flake8 issue while I'm here.
=> NAS-122384 / 23.10 / handle known errors in failover.call_remote

tests/api2/test_200_ftp.py
Update the test to make it less fragile.
* Increase the file size and the bandwidth limits.  This moves the test away from the 1KiB chunk sizes and should provide better test fidelity.
* Increase the allowed variance from +/- 1KiB to +/- 2KiB.  We've not looking for perfection, just solid evidence that we're limiting to the requested rate.
=> NAS-122430 / 23.10 / NAS-122476 / 23.10 / Update the FTP bandwidth limit test

src/middlewared/middlewared/plugins/vm/pci.py
If a PCI device has any controller type which we deem as sensitive to system's functionality, we mark the PCI device as critical but  we are not properly marking it as critical right now.
Properly mark a PCI device as critical as we were missing `any` keyword to do that.
Original PR: https://github.com/truenas/middleware/pull/11501
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122456
Original PR: https://github.com/truenas/middleware/pull/11514
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122456
=> NAS-122456 / 22.12.3.1 / Properly mark a PCI device as critical (by Qubad786) (by bugclerk)

src/middlewared/middlewared/plugins/failover.py
On an HA system, download the update file once (on the active controller) and then send that file to the other controller via the heartbeat interface. This prevents the standby from downloading the same files off the network.
=> NAS-122495 / 23.10 / download update file once on HA systems

src/middlewared/middlewared/plugins/failover.py
On an HA system, download the update file once (on the active controller) and then send that file to the other controller via the heartbeat interface. This prevents the standby from downloading the same files off the network.
Original PR: https://github.com/truenas/middleware/pull/11533
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122495
=> NAS-122495 / 22.12.4 / download update file once on HA systems (by themylogin)

src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/ldap.py
Ensure that winbind request timeout and passdb path are set back to defaults for standalone server when LDAP and AD are stopped.
Original PR: https://github.com/truenas/middleware/pull/11504
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122460
=> NAS-122460 / 22.12.4 / Re-init global SMB parameters when DS stopped (by anodos325)

src/middlewared/middlewared/plugins/iscsi_/target_to_extent.py, tests/api2/test_261_iscsi_cmd.py
Enhance `validate` routine for _iscsi.targetextent_:
- Now throw an error on LUN clash whether the LUNID or target has changed.
- Also throw an error if the extent is currently used in any target.
Add `test_14_target_lun_extent_modify` for _iscsi.targetextent_ operations
- Refactor `initiator_portal` out of `configured_target_to_file_extent` and `configured_target_to_zvol_extent` to facilitate their reuse (and the reuse of `configured_target`).  This is useful here, but will also be useful in future tests.
Renumber tests
=> NAS-122264 / 23.10 / Duplicate LUN ID for an iSCSI Target

src/middlewared/middlewared/client/client.py, src/middlewared/middlewared/plugins/disk_/sync.py, src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/failover_/event.py, src/middlewared/middlewared/plugins/failover_/remote.py, src/middlewared/middlewared/plugins/pool_/export.py, src/middlewared/middlewared/plugins/pool_/pool.py
Add `raise_connect_error` boolean option to `failover.call_remote`. If this is set to false, then it will not raise an exception of the remote call fails in a known way (i.e. standby node is rebooting/upgrading/heartbeat issue/etc). Defaults to true otherwise.
=> NAS-122504 / 23.10 / Add raise_connect_error option to failover.call_remote

src/middlewared/middlewared/plugins/iscsi_/target_to_extent.py
Enhance `validate` routine for _iscsi.targetextent_:
- Now throw an error on LUN clash whether the LUNID or target has changed.
- Also throw an error if the extent is currently used in any target.
Original PR: https://github.com/truenas/middleware/pull/11521
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122264
=> NAS-122264 / 22.12.4 / Duplicate LUN ID for an iSCSI Target (by bmeagherix)

src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/update_/download.py, src/middlewared/middlewared/plugins/update_/pending_linux.py, src/middlewared/middlewared/plugins/update_/utils.py
Before these changes, this failed with the following error:
```
....
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1425, in call_sync
return methodobj(*prepared_call.args)
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/remote.py", line 269, in send_file
self.CLIENT.send_file(token, src, dst)
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/remote.py", line 180, in send_file
raise CallError(
middlewared.service_exception.CallError: [EFAULT] Failed to send /var/db/system/update/updatefile.sqsh to Standby Controller: [Errno 28] No space left on device.
```
This is because we were sending the downloaded update file and the manual update file to the remote path which is tmpfs. The remote path is on tmpfs on HA systems and so it ran out of …
=> NAS-122512 / 23.10 / Only send the necessary update file to the standby controller

src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/update_/download.py, src/middlewared/middlewared/plugins/update_/pending_linux.py, src/middlewared/middlewared/plugins/update_/utils.py
Before these changes, this failed with the following error:
```
....
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1425, in call_sync
return methodobj(*prepared_call.args)
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/remote.py", line 269, in send_file
self.CLIENT.send_file(token, src, dst)
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/remote.py", line 180, in send_file
raise CallError(
middlewared.service_exception.CallError: [EFAULT] Failed to send /var/db/system/update/updatefile.sqsh to Standby Controller: [Errno 28] No space left on device.
```
This is because we were sending the downloaded update file and the manual update file to the remote path which is tmpfs. The remote path is on tmpfs on HA systems and so it ran out of …
=> NAS-122512 / 22.12.3.1 / Only send the necessary update file to the standby controller (by themylogin)

src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/update_/download.py, src/middlewared/middlewared/plugins/update_/pending_linux.py, src/middlewared/middlewared/plugins/update_/utils.py
Before these changes, this failed with the following error:
```
....
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1425, in call_sync
return methodobj(*prepared_call.args)
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/remote.py", line 269, in send_file
self.CLIENT.send_file(token, src, dst)
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/remote.py", line 180, in send_file
raise CallError(
middlewared.service_exception.CallError: [EFAULT] Failed to send /var/db/system/update/updatefile.sqsh to Standby Controller: [Errno 28] No space left on device.
```
This is because we were sending the downloaded update file and the manual update file to the remote path which is tmpfs. The remote path is on tmpfs on HA systems and so it ran out of …
=> NAS-122512 / 22.12.4 / Only send the necessary update file to the standby controller (by themylogin)

src/middlewared/middlewared/plugins/failover.py
This improves the progress reporting when upgrading an HA system. Instead of showing 0% for the entire process, it'll update accordingly.
=> NAS-122511 / 23.10 / Better progress report for failover upgrade

src/middlewared/middlewared/plugins/failover.py
This improves the progress reporting when upgrading an HA system. Instead of showing 0% for the entire process, it'll update accordingly.
Original PR: https://github.com/truenas/middleware/pull/11541
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122511
=> NAS-122511 / 22.12.3.1 / Better progress report for failover upgrade (by themylogin)

src/middlewared/middlewared/plugins/failover.py
This improves the progress reporting when upgrading an HA system. Instead of showing 0% for the entire process, it'll update accordingly.
Original PR: https://github.com/truenas/middleware/pull/11541
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122511
=> NAS-122511 / 22.12.4 / Better progress report for failover upgrade (by themylogin)

src/middlewared/middlewared/plugins/filesystem_/acl_template.py
In some circumstances webui sends an invalid ACE that is missing the `id` key entirely. We need to properly handle this variety of malformed payload.
=> NAS-122548 / 23.10 / Fix KeyError in ACL validation

src/middlewared/middlewared/plugins/failover_/remote.py
```
File "/usr/local/lib/python3.11/dist-packages/middlewared/plugins/failover_/remote.py", line 270, in call_remote
return self.CLIENT.call(method, *args, **options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/middlewared/plugins/failover_/remote.py", line 128, in call
return self.client.call(*args, **kwargs)
TypeError: Client.call() got an unexpected keyword argument 'raise_connect_error'
=> NAS-122551 / 23.10 / Fix failover.call_remote TypeError crash

src/middlewared/middlewared/etc_files/hosts.mako, src/middlewared/middlewared/plugins/network_/global_config.py, tests/api2/test_003_network_global.py
Many problems found while investigating this issue. For one, we added a file named `global.py`.... `global` is a keyword in python so when I added the `HOSTS_FILE_EARMARKER` global variable, I was unable to import it into the mako file because of a syntax error. For two, adding static host table entries to /etc/hosts and having them take effect immediately has been broken on SCALE for a year or more minimally. It has required a restart before those entries have been added to /etc/hosts. Lastly, we made the hosts key in the schema a string which is incredibly hard to validate in any meaningful way. I've changed this to a list object (just like we do for the search domains). This allows us to more easily (and in a more standard programmatic way) validate the entries given to us by the …
=> NAS-122357 / 23.10 / Fix adding static entries to /etc/hosts

src/middlewared/middlewared/plugins/filesystem_/acl_template.py
In some circumstances webui sends an invalid ACE that is missing the `id` key entirely. We need to properly handle this variety of malformed payload.
Original PR: https://github.com/truenas/middleware/pull/11554
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122548
=> NAS-122548 / 22.12.4 / Fix KeyError in ACL validation (by anodos325)

src/middlewared/middlewared/plugins/ipmi_/sel.py
This fixes a typo in ipmi.sel.clear. Without the fix, it's impossible to clear the ipmi system event log.
=> NAS-122549 / 23.10 / fix typo in ipmi.sel.clear

src/middlewared/middlewared/plugins/ipmi_/sel.py
This fixes a typo in ipmi.sel.clear. Without the fix, it's impossible to clear the ipmi system event log.
Original PR: https://github.com/truenas/middleware/pull/11560
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122549
=> NAS-122549 / 22.12.4 / fix typo in ipmi.sel.clear (by yocalebo)

src/middlewared/middlewared/plugins/hardware/cpu.py
This provides some api endpoints to query (and set) cpu governor. This is not exposed by webUI team at the moment and is being added mostly for performance team to easily be able to change this setting so that they can measure impact on performance numbers.
=> NAS-118034 / 23.10 / add ability to change cpu governor

src/middlewared/middlewared/utils/functools.py
If the function that is being cached returns a mutable python object, then the caller of said function can alter the object. This will cause all other subsequent callers to receive the altered response.
=> NAS-122594 / 23.10 / deepcopy `@cache`d function return value in case caller modifies it

src/middlewared/middlewared/utils/functools.py
If the function that is being cached returns a mutable python object, then the caller of said function can alter the object. This will cause all other subsequent callers to receive the altered response.
Original PR: https://github.com/truenas/middleware/pull/11567
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122594
=> NAS-122594 / 22.12.4 / deepcopy `@cache`d function return value in case caller modifies it (by themylogin)

src/middlewared/middlewared/service/crud_service.py, src/middlewared/middlewared/test/integration/utils/client.py, tests/api2/test_crud_events.py
This PR fixes create/update/delete post execution events/hooks when any of those methods are jobs as we were not waiting for the job to actually finish before trying to fire events and it has never worked for job based methods. Now with the current changes we properly wait for the actual method to complete execution and then we fire events/hooks regardless of the actual method being a job or not.
=> NAS-121867 / 23.10 / Fix CRUD service events/hooks not working with job based methods

tests/api2/test_440_snmp.py, tests/functions.py, tests/requirements.txt
Add SNMP tests that verify the response uses the same IP as request.
Use the new utility functions `async_SSH_start` and `async_SSH_done` to run a `tcpdump` on the TrueNAS system to capture a SNMP Get/Response (issued using `pysnmplib`).  Verify that the destination of the GET is the same as the source of the RESPONSE.
=> NAS-122482 / 23.10 / Add SNMP tests that verify the response uses the same IP as request

tests/api2/test_440_snmp.py, tests/functions.py, tests/requirements.txt
Add SNMP tests that verify the response uses the same IP as request.
Use the new utility functions `async_SSH_start` and `async_SSH_done` to run a `tcpdump` on the TrueNAS system to capture a SNMP Get/Response (issued using `pysnmplib`).  Verify that the destination of the GET is the same as the source of the RESPONSE.
Original PR: https://github.com/truenas/middleware/pull/11572
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122482
=> NAS-122482 / 22.12.4 / Add SNMP tests that verify the response uses the same IP as request (by bmeagherix)

src/middlewared/middlewared/alert/service/slack.py
This fixes this formatting bug in alerts sent to Slack:
The issue is that Slack only wants `&`, `<`, and `>` escaped, we shouldn't escape `"` nor `'`: https://api.slack.com/reference/surfaces/formatting#escaping
=> Fix Slack HTML escaping for alerts

tests/api2/test_440_snmp.py
Restore the import of depends, removed during backport for NAS-122482.
=> Restore depends

src/middlewared/middlewared/alert/service/slack.py
This fixes this formatting bug in alerts sent to Slack:
The issue is that Slack only wants `&`, `<`, and `>` escaped, we shouldn't escape `"` nor `'`: https://api.slack.com/reference/surfaces/formatting#escaping
Original PR: https://github.com/truenas/middleware/pull/11580
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122658
=> NAS-122658 / 22.12.4 / Fix Slack HTML escaping for alerts (by jburianek)

tests/api2/test_440_snmp.py, tests/functions.py, tests/requirements.txt
Add SNMP tests that verify the response uses the same IP as request.
Use the new utility functions `async_SSH_start` and `async_SSH_done` to run a `tcpdump` on the TrueNAS system to capture a SNMP Get/Response (issued using `pysnmplib`).  Verify that the destination of the GET is the same as the source of the RESPONSE.
Original PR: https://github.com/truenas/middleware/pull/11572
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122482
=> NAS-122482 / 13.0 / Add SNMP tests that verify the response uses the same IP as request (by bmeagherix)

src/middlewared/middlewared/plugins/sysdataset.py
This has knock-on effects regarding failover when AD is broken. We should ensure that it's always possible to get system dataset set up, and in principle if AD join is already broken things can't really get worse by moving around the system dataset.
Original PR: https://github.com/truenas/middleware/pull/11598
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122689
=> NAS-122689 / 13.0 / Allow sysdataset move if AD faulted (by anodos325)

src/middlewared/middlewared/plugins/sysdataset.py
This has knock-on effects regarding failover when AD is broken. We should ensure that it's always possible to get system dataset set up, and in principle if AD join is already broken things can't really get worse by moving around the system dataset.
Original PR: https://github.com/truenas/middleware/pull/11598
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122689
=> NAS-122689 / 13.1 / Allow sysdataset move if AD faulted (by anodos325)

src/middlewared/middlewared/plugins/sysdataset.py
This has knock-on effects regarding failover when AD is broken. We should ensure that it's always possible to get system dataset set up, and in principle if AD join is already broken things can't really get worse by moving around the system dataset.
=> NAS-122689 / 13.0 / Allow sysdataset move if AD faulted (#11598)

src/middlewared/middlewared/plugins/failover_/datastore.py
#
#
#
We had a safeguard in place that prevented this scenario but it was lost in commit: e2afcdec6ee89e7849168db89ee3ff9f5ac6bcaf (which also fixed an insidious HA db replication issue). Also note that I had to do this in `failover.datastore.receive` since the current versions of bluefin have this method and would prevent this situation without having to deal with the ENOMETHOD dance.
Original PR: https://github.com/truenas/middleware/pull/11602
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122693
=> NAS-122693 / 22.12.3.2 / fix replication database when alembic revisions dont match (by yocalebo)

src/middlewared/middlewared/plugins/failover_/datastore.py
#
#
#
We had a safeguard in place that prevented this scenario but it was lost in commit: e2afcdec6ee89e7849168db89ee3ff9f5ac6bcaf (which also fixed an insidious HA db replication issue). Also note that I had to do this in `failover.datastore.receive` since the current versions of bluefin have this method and would prevent this situation without having to deal with the ENOMETHOD dance.
Original PR: https://github.com/truenas/middleware/pull/11602
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122693
=> NAS-122693 / 22.12.4 / fix replication database when alembic revisions dont match (by yocalebo)

src/middlewared/middlewared/plugins/filesystem_/acl_linux.py, src/middlewared/middlewared/plugins/gluster_linux/filesystem.py
This changes how permissions-related operations are handled on glusterfs volumes so that we use libgfapi directly rather than shelling out to iterate in glusterfs fuse mount.
=> NAS-122696 / 23.10 / Use pyglfs bindings for permissions ops

src/middlewared/middlewared/plugins/ipmi_/lan.py
The inner function `get_cmd` takes a list of commands. When DHCP is passed in, it's passing more than 1 command which causes an error. Fix it by removing the `id` argument.
=> NAS-122754 / 23.10 / fix crash in ipmi.lan.update

src/middlewared/middlewared/plugins/auth_/2fa.py
This PR adds changes to reset 2fa configured for users when 2fa global configuration changes because the secret generated for those users needs to be generated again.
=> NAS-122657 / 23.10 / Reset 2FA configuration for users when 2FA global configuration is changed

tests/api2/test_pool_dataset_unlock_restart_vms.py
VM unlock test had not been updated to reflect a bug fix test done which assessed children of a dataset correctly. In case of a zvol there is no child involved and the test will fail so the parameters have been updated accordingly to reflect the correct logic.
=> NAS-122331 / 22.12.4 / Fix VM dataset unlock test in bluefin

src/middlewared/middlewared/plugins/pool_/pool.py, src/middlewared/middlewared/plugins/zfs_/pool.py, src/middlewared/middlewared/plugins/zfs_/pool_utils.py, tests/api2/test_draid.py
ZFS allows creating a vdev of `DRAID` type. Basically each draid type vdev has certain attributes associated with it namely:
1. parity
2. spares
3. explicitly specifying data disks
After discussion with Alexander Motin we decided to at least expose specifying parity when creating a draid type vdev similar to how raidz vdev works. With the current changes as required we can further allow specifying the other configuration options for draid type vdev if requested.
=> NAS-121926 / 23.10 / Add DRAID support

src/middlewared/middlewared/etc_files/scst.conf.mako, tests/api2/test_261_iscsi_cmd.py
Add unit tests to exercise EXTENDED COPY (XCOPY) between pairs of iSCSI targets.
Because of the dynamic nature of the tests, it was discovered that the `scstadmin` component of `scst` was eliminating some extent LUNs that were auto-added to the copy manager.  This would **not** manifest if the targets were defined, and then `scst` was restarted, but it was a problem during the unit tests as two targets were added in order to exercise the XCOPY.
The simplest solution was to avoid the issue by explicitly writing an existing copy manager LUNs when rewriting the _scst.conf_
=> NAS-122707 / 23.10 / Add iSCSI XCOPY unit tests

src/middlewared/middlewared/plugins/gluster_linux/local_events.py
Impact of exposure of this is minimal in clustered situation, but this should be made readable only by root.
=> NAS-122808 / 23.10 / Restrict permissions on gluster jwt seed

src/middlewared/middlewared/plugins/gluster_linux/local_events.py
Impact of exposure of this is minimal in clustered situation, but this should be made readable only by root.
Original PR: https://github.com/truenas/middleware/pull/11620
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122808
=> NAS-122808 / 22.12.4 / Restrict permissions on gluster jwt seed (by anodos325)

src/middlewared/middlewared/plugins/gluster_linux/local_events.py, src/middlewared/middlewared/webhooks/cluster_events.py
Initial implementation of JWT usage was to encode static dummy payload with pre-shared key. Presence of decodable header was used to authenticate the command / payload sent to the webhook. Since the encoded payload and secret were both static, the JWTOKEN used for all commands was identical.
This PR replaces the static dummy payload with a dict containing timestamp and uuid for message id. If clock slew from message we receive is more than 10 seconds or if the message id is reused, then we reject the event request.
=> NAS-122813 / 23.10 / Add more protection for JWT usage in cluster event

src/middlewared/middlewared/plugins/gluster_linux/volume.py
Glustercli expects the dict to be presented as arg rather than breaking into kwargs.
=> NAS-122818 / 23.10 / Fix gluster.volume.optset endpoint

src/middlewared/middlewared/plugins/vm/pci.py
This is way too complicated for what it does. We can gather this information using pyudev (python bindings to udev database) instead of subprocessing in the main event loop. Furthermore, caching this information doesn't really make sense because, in theory, certain pci devices are hot-pluggable. This is fast enough by itself that we don't need to cache the information.
The returned data is the exact same so there is no change in functionality or behavior.
=> NAS-122817 / 23.10 / simplify and improve vm.device.get_pci_devices

src/middlewared/middlewared/plugins/gluster_linux/volume.py
Glustercli expects the dict to be presented as arg rather than breaking into kwargs.
Original PR: https://github.com/truenas/middleware/pull/11625
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122818
=> NAS-122818 / 22.12.4 / Fix gluster.volume.optset endpoint (by anodos325)

src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
There isn't a legitimate reason to allow remote clients to mount this.
=> NAS-122819 / 22.12.4 / Do not allow remote fuse mounts of ctdb_shared_vol

src/middlewared/middlewared/main.py
When `str(exc)` is empty (for example, if `MatchNotFound` was raised), send `repr(exc)` as `ClientException` reason.
=> Send `repr(exc)` as error text if `str(exc)` is empty

tests/api2/test_twofactor_auth.py
This commit fixes an issue where in integration test we configured 2fa for user before enabling 2fa globally which resulted in configuration for user 2fa getting wiped as expected because we remove 2fa configuration for user when parameters like interval are changed for 2fa as secret needs to be regenerated at that point.
=> NAS-122829 / 23.10 / Configure 2fa for user after enabling it globally in tests

cluster-tests/config.py, cluster-tests/init_gluster.py, cluster-tests/tests/cleanup/test_cluster_cleanup.py, cluster-tests/utils.py, src/middlewared/middlewared/alert/source/ctdb.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_general.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_job.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_setup.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py, src/middlewared/middlewared/plugins/cluster_linux/utils.py, src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/plugins/gluster_linux/filesystem.py, src/middlewared/middlewared/plugins/gluster_linux/local_events.py, src/middlewared/middlewared/plugins/gluster_linux/peer.py, src/middlewared/middlewared/plugins/gluster_linux/utils.py, src/middlewared/middlewared/plugins/gluster_linux/volume.py, src/middlewared/middlewared/plugins/service_/services/glusterd.py, src/middlewared/middlewared/plugins/sysdataset.py, src/middlewared/middlewared/plugins/tdb/base.py, src/middlewared/middlewared/webhooks/cluster_events.py
Ctdb and clustered middleware configuration relies on a small numbers of configuration files that are stored within a gluster volume. Originally, we used a hard-coded dedicated volume. This PR makes the location for these files configuable and provides a framework to shift volume location. This is a significantly disruptive operation cluster-wide and should only be performed in a maintenance window.
=> NAS-122782 / 23.10 / Remove hard-coded ctdb_shared_vol for glusterfs

src/middlewared/middlewared/plugins/vm/pci.py
The presence of the directory "iommu_groups" in /sys/kernel is enough to determine if IOMMU is enabled. Check that instead of sub processing in the main event loop and then parsing stdout.
=> NAS-122844 / 23.10 / better iommu enabled detection

src/middlewared/middlewared/plugins/vm/pci.py
The presence of the directory "iommu_groups" in /sys/kernel is enough to determine if IOMMU is enabled. Check that instead of sub processing in the main event loop and then parsing stdout.
Original PR: https://github.com/truenas/middleware/pull/11640
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122844
=> NAS-122844 / 22.12.4 / better iommu enabled detection (by yocalebo)

src/middlewared/middlewared/plugins/pool_/dataset.py, tests/api2/test_543_vm_device.py, tests/api2/test_iscsi.py, tests/api2/test_pool_dataset_unlock_restart_vms.py
This PR adds changes to use 16K as default for volume block size based on changes introduced in https://github.com/openzfs/zfs/pull/12406.
=> NAS-122841 / 23.10 / Use 16K as default for volume block size

src/middlewared/middlewared/pytest/unit/test_schema.py, src/middlewared/middlewared/schema.py
OROperator lacked has_private() method which broke dumping values in some edge cases.
Allow dumping of Lists where single item schema is set for the list and the schema contains private entries. If we don't do this then our job log is relatively useless.
=> NAS-122859 / 23.10 / Improve schema handling for private items

tests/api2/test_iscsi.py
We changed the volume size to 1 Mebibyte in bytes but forgot to update the parenthesized value that gets displayed by iscsi (1000 KiB instead of 1 MiB)
=> NAS-122871 / 23.10 / fix failing iscsi test

src/middlewared/middlewared/utils/gpu.py
(apologies if this isn't the right way to propose changes; I'm not familiar with the JIRA workflow and am external to iX systems)
I recently upgraded to TrueNAS 22.12.3.1 from 22.12.2.x and suddenly I was no longer able to pass an NVMe drive into one of my VMs as it's now considered "critical".
This is PCI device 0000:04:00.0.
```
$ lspci -nnD
...
0000:00:14.2 RAM memory [0500]: Intel Corporation Device [8086:7aa7] (rev 11)
...
0000:04:00.0 Non-Volatile memory controller [0108]: Phison Electronics Corporation PS5013 E13 NVMe Controller
...
```
I believe the catch-all for "memory" controller types was probably intended specifically for "RAM memory" PCI devices/controllers.
Fortunately, the existing code easily supports that with minimal changes (the regular expression already captures the …
=> NAS-122875 / 23.10 / [vm] Be more specific about which PCI device/controllers are "sensitive"

src/middlewared/middlewared/plugins/vm/utils.py
(apologies if this isn't the right way to propose changes; I'm not familiar with the JIRA workflow and am external to iX systems)
I recently upgraded to TrueNAS 22.12.3.1 from 22.12.2.x and suddenly I was no longer able to pass an NVMe drive into one of my VMs as it's now considered "critical".
This is PCI device 0000:04:00.0.
```
$ lspci -nnD
...
0000:00:14.2 RAM memory [0500]: Intel Corporation Device [8086:7aa7] (rev 11)
...
0000:04:00.0 Non-Volatile memory controller [0108]: Phison Electronics Corporation PS5013 E13 NVMe Controller
...
```
I believe the catch-all for "memory" controller types was probably intended specifically for "RAM memory" PCI devices/controllers.
Fortunately, the existing code easily supports that with minimal changes (the regular expression already captures the …
=> NAS-122875 / 22.12.4 / [vm] Be more specific about which PCI device/controllers are "sensitive" (by ownaginatious)

src/middlewared/middlewared/restful.py
If a consumer of our REST API sends us json formatted data that is incorrect we crash here:
```
File "/usr/lib/python3/dist-packages/middlewared/restful.py", line 524, in on_method
return await do(method, req, resp, authenticated_credentials, *args, **kwargs)
File "/usr/lib/python3/dist-packages/middlewared/restful.py", line 669, in do
request_body = await req.json()
File "/usr/lib/python3/dist-packages/aiohttp/web_request.py", line 614, in json
return loads(body)
File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, …
```
=> NAS-122869 / 22.12.4 / Better REST error message (by yocalebo)

src/middlewared/middlewared/plugins/vm/pci.py, src/middlewared/middlewared/pytest/unit/plugins/vm/test_passthrough_choices.py
This fixes many numerous problems. First and foremost, this method was subprocessing N * 2 times. "N" being the total number of pci devices on the system. This, obviously, becomes painful on certain systems rather quickly. Furthermore, this was doing xml parsing and calling blocking I/O in the main event loop. On a system with 331 pci devices, this takes ~0.22 seconds and without my changes it was taking ~32.22 seconds. This is roughly ~197% faster to run. The returned data is the exact same with the exception that my changes are actually pulling a bit more verbose information for the vendor/product etc. (This doesn't matter since it's shown to end-user and not actually depended upon).
Fixes employed:
- stop sub processing for pci devices and use direct db bindings to udev database
- stop …
=> NAS-122865 / 23.10 / fix vm.device.passthrough_device_choices

src/middlewared/middlewared/plugins/vm/pci.py, src/middlewared/middlewared/pytest/unit/plugins/vm/test_passthrough_choices.py
This fixes many numerous problems. First and foremost, this method was subprocessing N * 2 times. "N" being the total number of pci devices on the system. This, obviously, becomes painful on certain systems rather quickly. Furthermore, this was doing xml parsing and calling blocking I/O in the main event loop. On a system with 331 pci devices, this takes ~0.22 seconds and without my changes it was taking ~32.22 seconds. This is roughly ~197% faster to run. The returned data is the exact same with the exception that my changes are actually pulling a bit more verbose information for the vendor/product etc. (This doesn't matter since it's shown to end-user and not actually depended upon).
Fixes employed:
- stop sub processing for pci devices and use direct db bindings to udev database
- stop …
=> NAS-122865 / 22.12.4 / fix vm.device.passthrough_device_choices (by yocalebo)

src/middlewared/middlewared/plugins/kubernetes_linux/attachments.py, src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py, src/middlewared/middlewared/plugins/kubernetes_linux/update.py, src/middlewared/middlewared/plugins/kubernetes_linux/utils.py, src/middlewared/middlewared/plugins/service_/services/kubernetes.py
This PR adds state management for kubernetes so we stay up to date on what the current state of kubernetes cluster is. Motivation behind this change is users accessing apps page when the cluster is initializing which can potentially result in giving invalid results as the cluster might be starting or is yet to be started if system is not ready yet.
=> NAS-122365 / 23.10 / Add state management for kubernetes

src/middlewared/middlewared/plugins/account.py, tests/api2/test_011_user.py
This fixes KeyError when user submits payload that includes home_mode for immutable user.
Original PR: https://github.com/truenas/middleware/pull/11652
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122958
=> NAS-122958 / 22.12.4 / Separately check home_mode for immutable user (by anodos325)

tests/api2/test_012_directory_service_ssh.py, tests/api2/test_030_activedirectory.py, tests/api2/test_032_ad_kerberos.py, tests/api2/test_035_ad_idmap.py, tests/api2/test_036_ad_ldap.py, tests/api2/test_040_ad_user_group_cache.py
Only install new computer objects in a dedicated OU in our AD domain during CI runs. This helps us to keep track of what was added via CI and what has been manually added (as well as simplifying permissions management).
=> NAS-122974 / 23.10 / Shift automation workloads to dedicated AD OU

src/middlewared/middlewared/plugins/interface/bridge.py
This bug was introduced by 97ff05a74845dacbd2974ef8c03a846e060986aa
=> NAS-119331 / 23.10 / On bridge update, do not put its member down if it already was a member of the bridge before update.

src/middlewared/middlewared/plugins/interface/bridge.py
This bug was introduced by 97ff05a74845dacbd2974ef8c03a846e060986aa
Original PR: https://github.com/truenas/middleware/pull/11657
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119331
=> NAS-119331 / 22.12.4 / On bridge update, do not put its member down if it already was a member of the bridge before update. (by themylogin)

src/middlewared/middlewared/plugins/zfs_/utils.py
User ssh'ed into a box and tried to "dd" a zvol to another zvol (to copy it) but made a typo in the command. This lead to dd creating a regular file in /dev/zvol directory. When we tried to "readlink" this file, it crashed with "Invalid Argument". This prevented the webUI from showing zvol choices in the VM creation window. To fix this, simply skip files that we crash on when trying to "readlink"
=> NAS-122697 / 23.10 / prevent crash when users doing things via the cli

src/middlewared/middlewared/plugins/zfs_/utils.py
User ssh'ed into a box and tried to "dd" a zvol to another zvol (to copy it) but made a typo in the command. This lead to dd creating a regular file in /dev/zvol directory. When we tried to "readlink" this file, it crashed with "Invalid Argument". This prevented the webUI from showing zvol choices in the VM creation window. To fix this, simply skip files that we crash on when trying to "readlink"
Original PR: https://github.com/truenas/middleware/pull/11661
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122697
=> NAS-122697 / 22.12.4 / prevent crash when users doing things via the cli (by yocalebo)

src/middlewared/middlewared/plugins/chart_releases_linux/secrets_management.py
We have seen cases earlier with users where helm had malformed secrets which resulted in us not being able to parse those secrets. Currently we have seen a user where another exception was being raised and this commit handles that exception so we properly handle this. This change makes sure that other apps which don't have a malformed secret are not affected by this inconsistency on helm side.
=> NAS-122659 / 23.10 / Properly catch exception with invalid helm secret

src/middlewared/middlewared/plugins/crypto_/utils.py
This commit adds changes to not allow using brainpool ec curve anymore as it is not supported by major browsers / openssl.
=> NAS-122099 / 23.10 / Do not allow using brainpool ec curves

src/middlewared/middlewared/plugins/vm/devices/display.py
The problem lies in the logic of the `validate_port_attrs` function. This function accepts a validation error as an optional parameter and should initializes a new validation error object if the parameter is not provided. The main problem arises there because validation error class has string method overridden which returns empty string if no validation error is added in verrors. So the `or` keyword used in this logic considers it `null` and initializes new object. As a result `validation_port_attr` function always initializes object if there are no validation errors already defined and in the main function `verrors` object being referenced does not contain the validation errors required.
Use the `verrors` object returned by the port validation error function.
=> NAS-122363 / 23.10 / Fix vm display validation errors

src/middlewared/middlewared/plugins/vm/devices/display.py
The problem lies in the logic of the `validate_port_attrs` function. This function accepts a validation error as an optional parameter and should initializes a new validation error object if the parameter is not provided. The main problem arises there because validation error class has string method overridden which returns empty string if no validation error is added in verrors. So the `or` keyword used in this logic considers it `null` and initializes new object. As a result `validation_port_attr` function always initializes object if there are no validation errors already defined and in the main function `verrors` object being referenced does not contain the validation errors required.
Use the `verrors` object returned by the port validation error function.
Original PR: …
=> NAS-122363 / 22.12.4 / Fix vm display validation errors (by Qubad786)

src/middlewared/middlewared/plugins/chart_releases_linux/secrets_management.py
We have seen cases earlier with users where helm had malformed secrets which resulted in us not being able to parse those secrets. Currently we have seen a user where another exception was being raised and this commit handles that exception so we properly handle this. This change makes sure that other apps which don't have a malformed secret are not affected by this inconsistency on helm side.
Original PR: https://github.com/truenas/middleware/pull/11660
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122659
=> NAS-122659 / 22.12.4 / Properly catch exception with invalid helm secret (by sonicaj)

src/middlewared/middlewared/plugins/gluster_linux/local_events.py, src/middlewared/middlewared/webhooks/cluster_events.py
Initial implementation of JWT usage was to encode static dummy payload with pre-shared key. Presence of decodable header was used to authenticate the command / payload sent to the webhook. Since the encoded payload and secret were both static, the JWTOKEN used for all commands was identical.
This PR replaces the static dummy payload with a dict containing timestamp and uuid for message id. If clock slew from message we receive is more than 10 seconds or if the message id is reused, then we reject the event request.
Original PR: https://github.com/truenas/middleware/pull/11622
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122813
=> NAS-122813 / 22.12.4 / Add more protection for JWT usage in cluster event (by anodos325)

src/middlewared/middlewared/plugins/chart_releases_linux/schema.py
The problem identified is that the `clean_value_of_attr_for_upgrade` function does not support nested sub-questions in variables which results in nested subquestions values getting cleaned/added to the values for the app in question.
A recursive approach has been added to the function where this implementation enables support for nested sub-questions 
being cleaned and added to cleaned values for the app in question.
=> NAS-123029 / 23.10 / Fix nested subquestions on app upgrade

src/middlewared/middlewared/alembic/versions/23.10/2023-07-13_20-35_k8s_host_path_validation.py, src/middlewared/middlewared/etc_files/rancher/k3s/flags.py, src/middlewared/middlewared/plugins/chart_releases_linux/host_path_attachments.py, src/middlewared/middlewared/plugins/chart_releases_linux/utils.py, src/middlewared/middlewared/plugins/chart_releases_linux/validation.py, src/middlewared/middlewared/plugins/kubernetes_linux/update.py, src/middlewared/middlewared/pytest/unit/plugins/chart_releases/test_chart_release_validation_schema.py, src/middlewared/middlewared/pytest/unit/plugins/test_kubernetes.py
Kris has requested that we remove host path validation logic from kubernetes. All of the logic in place wrt that has been removed and we just now always validate that the path in question does not belong to a locked dataset.
In a future ticket we would be however adding tracing in containerd so we keep track of which paths were mounted by apps and we can based on that make a decision if we want to debug a ticket further or not.
=> NAS-119483 / 23.10 / Remove host path validation logic from kubernetes

src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py, src/middlewared/middlewared/plugins/cluster_linux/management.py, src/middlewared/middlewared/plugins/pwenc.py
Since ctdb_shared_vol is not longer being used for ctdb configuration, shift our clwpenc plugin to use localevents token for our secret seed.
This reduces risk of exposure via glusterfs clients and also makes removes dependency on health of gluster volume.
=> NAS-123054 / 23.10 / Use preshared secret for localevents for clpwenc

src/freenas/usr/local/sbin/ctdb_glfs_lock, src/middlewared/middlewared/plugins/cluster_linux/ctdb_event.py
The CTDB cluster leader is the node that currently holds the ctdb recovery lock. The node holding leader role becomes source of truth about status of other cluster nodes. This commit changes our recovery lock script so that a node will send an event to TrueCommand upon successfully taking the CTDB recovery lock. The payload to TC includes the pnn, gluster peer uuid, and private ip of the new leader.
=> NAS-123053 / 23.10 / Send event to TrueCommand when node becomes leader

cluster-tests/tests/smb/test_001_sharing_smb.py
This test intentionally breaks permissions on smbd to prevent it
from starting and verifies that the cluster-wide service monitor
reports the issue back to us. We may get stale results on the
first go causing a spurious test failure. Mark some of the checks
as flakey and have pytest retry them.
=> NAS-123056 / 23.10 / Mark clustered service flakey

src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/failover_/remote.py
A few problems:
- we're restarting Kubernetes and kuberouter services on the standby which shouldn't ever be done
- we're looking for 'webshell' service which no longer exists
- we're overwriting errno value in failover.call_remote if it's an error we expect and `raise_connect_error` is true (the default)
=> NAS-123068 / 23.10 / improve and fix service_remote and call_remote

src/middlewared/middlewared/plugins/etc.py
This commit adds changes to specify pool import checkpoint for generating 2fa ssh configuration because after AD support being added, system dataset must be there for us to find out users which are configured for 2fa as we query AD bits as well which lie in the system dataset.
=> NAS-122862 / 23.10 / Specify checkpoint for generating 2fa ssh configuration

cluster-tests/tests/gluster/test_volume.py, src/middlewared/middlewared/plugins/cluster_linux/management.py, src/middlewared/middlewared/plugins/gluster_linux/rebalance.py
This commit adds a method that creates a job API consumers can use to track the progress of a gluster rebalance task to completion. Wrap around it if user specifies to rebalance after adding cluster nodes.
=> NAS-123086 / 23.10 / Add option to rebalance volume when adding nodes

src/middlewared/middlewared/plugins/device_/device_info.py, src/middlewared/middlewared/plugins/disk_/retaste.py, tests/api2/test_261_iscsi_cmd.py
`get_disks` was returning logged in iSCSI targets.  The primary example was on the Standby controller of a HA system with ALUA enabled and at least one iSCSI target defined.  This was causing `hactl` on both nodes to emit "_The quantity of disks do not match between the nodes._" in error.
```
Node status: Standby
This node serial: A1-89655
Other node serial: A1-89654
Failover status: The quantity of disks do not match between the nodes.
```
Some further investigation:
```
>>> from middlewared.client import Client
>>> Client().call('failover.mismatch_disks')
{'missing_local': [], 'missing_remote': ['']}
>>> Client().call('failover.get_disks_local')
['V1K9RJ5G', 'V1K9RHVG', 'V1K9RHRG', 'V1K9WPUG', '']
>>> Client().call('device.get_disks', False, True)
{'nvme0n1': '21322M809021', 'sda': …
```
=> NAS-123069 / 23.10 / Prevent logged in iSCSI targets being included in get_disks

src/middlewared/middlewared/plugins/chart_releases_linux/schema.py
Expose `hostpathdirectory` and `hostpathfile` schemas to app developers so that they can consume it to validate if the host path being specified is a directory/file and have more validation in place to properly validate their app's values to conform to what's actually required by the app.
=> NAS-122715 / 23.10 / Allow validating path is dir/file on host in apps

src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
We are not validating maximum characters allowed in an app's name which results in errors being thrown from helm side.
Properly validate the length of chart release name.
=> NAS-122714 / 23.10 / Limit app names to 40 characters

src/middlewared/middlewared/scripts/ctdb_events.py
There are some situations in which the clustered services file may exist, but is empty. This should be treated in the same way in the ctdb event script as the case where the file simply doesn't exist (load our defaults).
=> NAS-123116 / 23.10 / Reduce log spam for clustered services file

src/middlewared/middlewared/plugins/ups.py
This commit adds changes to not spam middleware logs again and again if the error has already been logged once.
Original PR: https://github.com/truenas/middleware/pull/11701
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123089
=> NAS-123089 / 22.12.4 / Do not spam upsd errors (by sonicaj)

src/middlewared/middlewared/plugins/enclosure.py, src/middlewared/middlewared/plugins/enclosure_/map.py
The r10 and r40 platforms head-unit have their drive slots mapped to a human readable way (i.e. physically cabled slot 5 is actually physical slot 1, etc). This means we need to ensure that `enclosure.set_slot_status` (the method used to identify a drive in the webUI) takes into account when we're on a system whose head-unit has been "mapped".
To simplify this greatly, I added a top-level `bsg` key to enclosure.query output since that's what is needed to instantiate an `EnclosureDevice` object which allows us to toggle the drive light.
Improvements and fixes employed in this PR:
- add top-level "bsg" key to `enclosure.query` output
- fix the for loop that was doing `set_control`. It was actually failing regardless of these changes because of a logic bug
- add more validation before we …
=> NAS-123066 / 23.10 / fix drive identify on mapped enclosures

src/middlewared/middlewared/plugins/catalogs_linux/items.py, src/middlewared/middlewared/plugins/ports/ports.py, src/middlewared/middlewared/plugins/vm/vm_display_info.py
A `ref` is being added so questions in an app which consume ports and allow it to be user configurable have a way to show unused ports which can actually be used by the app.
=> NAS-122338 / 23.10 / Retrieve unused ports to be added to questions

debian/debian/postinst, tests/api2/test_200_ftp.py
FTP service was not starting after reboot despite the service being enabled.
The source of the problem was that `proftpd.socket` was also enabled.  This is not correct or supposed to happen.  The default state is for `proftpd.socket` to be disabled. 
The fix is to disable `proftpd.socket` in our `postinst` module.
Also added a CI test to detect regression.
=> NAS-123024 / 23.10 / FTP service does not automatically start upon system reboot

cluster-tests/init_gluster.py, cluster-tests/tests/gluster/test_volume.py, src/middlewared/middlewared/plugins/cluster_linux/management.py, src/middlewared/middlewared/plugins/gluster_linux/rebalance.py
Add some basic validation of payloads delivered related to brick and volume type, and expand cluster tests to validate that volumes are created properly.
Testing for validation and normalization of gluster config, and creating different volume configurations is achieved by using multiple bricks on the same server. This is a rough analogue to supported cluster configurations and something we can address later as the testing infrastructure for automation improves.
=> NAS-123132 / 23.10 / Add validation for gluster volume creation

src/middlewared/middlewared/plugins/gluster_linux/volume.py
As we deprecated the ctdb shared volume, the migrate method was moved from ctdb.shared.volume namespace to ctdb.root_dir namespace.
=> NAS-123146 / 23.10 / Fix CTDB root dir migration

cluster-tests/tests/gluster/test_volume.py
This test intermittently fails with an error that another transaction is in progress. Since it can cause a cascade of other test failures, we should just retry a few times before failing. The error is probably spurious due to VMs that we are running the cluster on.
=> NAS-123147 / 23.10 / Mark gluster volume stop as flaky

src/middlewared/middlewared/plugins/interface/netif_linux/utils.py
This commit adds changes to ignore any interfaces created by tailscale app when running in host network mode as they are not managed by middleware and will result in all sorts of different issues.
=> NAS-123033 / 23.10 / Ignore interfaces created by tailscale

src/middlewared/middlewared/plugins/interface/netif_linux/utils.py
git cherry-pick -x 682765cc1189a33774dea333711c38538f8b8098
git cherry-pick -x 6e4b2f30ec59c1143915a20ddc5ded59a68e026f
This commit adds changes to ignore any interfaces created by tailscale app when running in host network mode as they are not managed by middleware and will result in all sorts of different issues.
Original PR: https://github.com/truenas/middleware/pull/11719
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123033
=> NAS-123033 / 22.12.4 / Ignore interfaces created by tailscale (by sonicaj)

src/middlewared/middlewared/plugins/pool_/pool.py
This commit adds a separate endpoint to validate pool name so UI can consume it at the start of pool creation wizard and error out before user proceeds to next step in the wizard.
=> NAS-123170 / 23.10 / Add endpoint to validate pool name

src/middlewared/middlewared/plugins/system/product.py
The documentation team has requested this since they are making some infrastructural changes to how documentation is handled starting in Cobia. This endpoint grabs the "major" version of the software version on the system so that the webUI can call this and show proper URL on the front-end.
=> NAS-123187 / 23.10 / add version_major endpoint

src/middlewared/middlewared/plugins/system/product.py
This adds `system.release_notes_url` endpoint that returns the public documentation link based on the major version of the SCALE version that is running. This will be used by webUI to display the URL to end-user.
=> NAS-123187 / 23.10 / add system.release_notes_url

src/freenas/usr/lib/netdata/python.d/cputemp.chart.py, src/middlewared/middlewared/plugins/reporting/cpu_temperatures.py, src/middlewared/middlewared/pytest/unit/utils/test_cpu_util_amd.py, src/middlewared/middlewared/pytest/unit/utils/test_cpu_util_generic.py, src/middlewared/middlewared/utils/cpu.py
Netdata cpu temperature plugin has been updated to consume the library/logic netdata uses to retrieve cpu temperatures.
Reasoning for using our own implementation of cpu temperatures is for 2 reasons:
1. Only retrieve metrics we are interested in as otherwise sensors retrieve lots of other metrics which will consume space unnecessarily
2. `sensors` netdata plugin retrieves temperatures under different charts which makes it harder to normalize/properly retrieve when trying to get historical cpu temperature statistics.
=> NAS-122774 / 23.10 / Use netdata for retrieving cpu temperatures

src/middlewared/middlewared/plugins/ipmi_/sel.py
These 2 endpoints are called every 5 minutes in an alert so these are filling up the task manager screen in UI. Mark them as transient so they don't show up there.
=> NAS-123222 / 23.10 / mark ipmi.sel.elist/info as transient=true

src/middlewared/middlewared/plugins/ipmi_/sel.py
These 2 endpoints are called every 5 minutes in an alert so these are filling up the task manager screen in UI. Mark them as transient so they don't show up there.
Original PR: https://github.com/truenas/middleware/pull/11728
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123222
=> NAS-123222 / 22.12.4 / mark ipmi.sel.elist/info as transient=true (by yocalebo)

src/middlewared/middlewared/plugins/cluster_linux/ctdb_job.py
This adds some protection for job contents being passed over the wire via ctdb.
There is already strict requirement that inter-node communication be on dedicated
network, but encrypting job payloads and results is trivial to implement.
=> NAS-123223 / 23.10 / Make Cluster Jobs payload private

src/middlewared/middlewared/plugins/reporting/cpu_temperatures.py
A VM will not have cpu temperature stats being retrieved so currently retrieving cpu temperature stats will fail and will result in a traceback.
Safely retrieve cpu temperature statistics.
=> NAS-123229 / 23.10 / Safely retrieve cpu temp stats

src/middlewared/middlewared/service_exception.py
There is minor descripancy between ValidationError and ValidationErrors regarding default errno that is set. It makes sense to use EINVAL in both cases since they're related to validation failures.
=> NAS-123227 / 23.10 / use EINVAL for default errno for ValidationError

src/middlewared/middlewared/plugins/system/product.py, src/middlewared/middlewared/plugins/update_/trains.py
After a bit more discussion with documentation and webUI teams, I'm adding a new key `release_notes_url` to `update.check_available`. The webUI actually already uses `update.check_available` and provides a link in the section of that webUI. This allows them to use existing data object and just check new key.
Adding a dedicated link for the release notes of the currently running version (exclusive to the update page) can come later as an improvement.
I also remove `version_major` endpoint since I originally added it for this purpose but ended up not needing it so there are no downstream consumers of this endpoint.
=> NAS-123238 / 23.10 / add release_notes_url to update.check_available

src/middlewared/middlewared/alert/source/license_status.py
The new f-series platform has a new licensed variant that ends with `-NR`. We need to account for this in the license alert so we don't raise false positive alerts to the end-user.
=> NAS-123247 / 23.10 / account for new NR license model for f-series

src/middlewared/middlewared/plugins/failover.py
`raise_connect_error: false` hides known exceptions when trying to connect to the other node. This means `rd` is None so when we try to `set(rd)` it raises a `TypeError`. Ensure `rd` is not None before casting it to a `set`
=> NAS-123246 / 23.10 / fix TypeError crash in failover.mismatch_disks

src/freenas/usr/local/sbin/disk_resize
In recent versions, the `nvme list-ctrl` command outputs additional information in the form of "num of ctrls present: 1" which causes the disk_resize script to behave unexpectedly. This commit addresses the issue by also matching the output format of [1-9].
=> NAS-122934 / 23.10 / Fix NVMe drives resizing in Cobia

src/middlewared/middlewared/job.py
This reverts commit https://github.com/truenas/middleware/commit/66442f016bfb62c6e57db2d35566b1cb6e3620f4.
This allows a deadlock to occur when using our websocket client and calling a method with the job=True argument. Since no events are emitted for the job, the websocket client will wait indefinitely but since no events are emitted it will never complete.
A subsequent change was made in https://github.com/truenas/middleware/pull/10714 which exposes the transient flag in core.get_jobs which is what the webUI team should use to filter jobs from the task UI.
=> NAS-123255 / 23.10 / Revert "Do not send events for transient jobs"

cluster-tests/init_gluster.py, src/middlewared/middlewared/plugins/cluster_linux/management.py
Switch API to using auth tokens for management. This allows cluster creation and expansion via lower-value / time-limited credentials.
=> NAS-123264 / 23.10 / Allow auth tokens for cluster management

src/middlewared/middlewared/plugins/reporting/rest.py, src/middlewared/middlewared/plugins/reporting/utils.py
To properly calculate how much space netdata database is going to consume we now make note of all the stats which we are retrieving at per second interval for 7 days and based on that we calculate how much disk space will be required.
=> NAS-122665 / 23.10 / Properly calculate netdata disk usage

src/middlewared/middlewared/plugins/chart_releases_linux/utils.py
This PR adds changes to add some metadata to the app so it can make an informed decision on how to expose/consume SMB/NFS CSI for storage.
=> NAS-122679 / 23.10 / Add changes to integrate SMB/NFS CSI in kubernetes lifecycle

src/middlewared/middlewared/schema/string_schema.py
This works around issues loading libwbclient during fresh TrueNAS installs.
=> NAS-123276 / 23.10 / Ignore ImportError for wbclient in our schema

src/middlewared/middlewared/plugins/ipmi_/sensors.py
The caller of `query_impl` is expecting it to return a tuple of size 2 but if there is no IPMI device, it was returning a single object which was causing the caller to crash with `ValueError`
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/ipmi_/sensors.py", line 73, in query
sensors, reread = self.query_impl()
^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
=> NAS-123327 / 24.04 / fix ValueError crash in ipmi.sensors.query_impl

src/middlewared/middlewared/plugins/ipmi_/sensors.py
The caller of `query_impl` is expecting it to return a tuple of size 2 but if there is no IPMI device, it was returning a single object which was causing the caller to crash with `ValueError`
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/ipmi_/sensors.py", line 73, in query
sensors, reread = self.query_impl()
^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
Original PR: https://github.com/truenas/middleware/pull/11758
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123327
=> NAS-123327 / 23.10 / fix ValueError crash in ipmi.sensors.query_impl (by yocalebo)

src/middlewared/middlewared/plugins/reporting/events.py
Optimize our realtime event subscription by calling `device.get_disks, False, True` which will call the "quick" path. This will only retrieve drive names and their serials instead of all the verbose detail information. This can be 40-60% faster on systems with "large" (>= 100's) of disks.
=> NAS-123331 / 24.04 / optimize RealtimeEventSource

src/middlewared/middlewared/plugins/reporting/events.py
Optimize our realtime event subscription by calling `device.get_disks, False, True` which will call the "quick" path. This will only retrieve drive names and their serials instead of all the verbose detail information. This can be 40-60% faster on systems with "large" (>= 100's) of disks.
Original PR: https://github.com/truenas/middleware/pull/11761
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123331
=> NAS-123331 / 23.10 / optimize RealtimeEventSource (by yocalebo)

src/middlewared/middlewared/alert/source/license_status.py
Missing parenthesis which is causing this to crash with a TypeError because the builtin any() is receiving 2 arguments instead of 1.
=> NAS-123332 / 24.04 / fix crash in alert.license_status

src/middlewared/middlewared/alert/source/license_status.py
Missing parenthesis which is causing this to crash with a TypeError because the builtin any() is receiving 2 arguments instead of 1.
Original PR: https://github.com/truenas/middleware/pull/11764
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123332
=> NAS-123332 / 23.10 / fix crash in alert.license_status (by yocalebo)

src/middlewared/middlewared/plugins/pool_/pool.py, src/middlewared/middlewared/plugins/zfs_/pool.py, src/middlewared/middlewared/plugins/zfs_/pool_utils.py, tests/api2/test_draid.py
Support for specifying data disks and spare disks has been added for a DRAID based vdev along with necessary validation required for it to function properly. Integration tests have also been updated to account for the changes so we can properly verify that the changes work as desired.
=> NAS-123305 / 24.04 / Add spare support in draid

src/middlewared/middlewared/plugins/pool_/pool.py, src/middlewared/middlewared/plugins/zfs_/pool.py, src/middlewared/middlewared/plugins/zfs_/pool_utils.py, tests/api2/test_draid.py
Support for specifying data disks and spare disks has been added for a DRAID based vdev along with necessary validation required for it to function properly. Integration tests have also been updated to account for the changes so we can properly verify that the changes work as desired.
Original PR: https://github.com/truenas/middleware/pull/11757
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123305
=> NAS-123305 / 23.10 / Add spare support in draid (by Qubad786)

tests/api2/test_200_ftp.py
The current allowance of +/- 2KB is too tight resulting in test failures.
=> Increase allowed variance in FTP bandwidth test

src/middlewared/middlewared/plugins/zfs_/pool.py
To create groups in draid, the total number of disks available for data must be divisible by `draid_data_disks`. For example, if there are 12 disks available for data, then `draid_data_disks` must be a number that is divisible by 12, such as 2, 3, or 4. These numbers can be evenly divided into 6, 4, and 3 groups, respectively.
However, this validation is already handled in py_libzfs when creating groups. The provided code snippet demonstrates how the left-hand side of the code ensures this validation. It attempts to find a multiple of available disks that will be grouped together. For example, if there are 12 disks with 3 `draid_data_disks` and 3 parity disks, it will iterate as follows: 1 * 6 % 12 = 6, and then in the second iteration, 2 * 6 % 12 = 0. This process finds a multiple for …
=> NAS-123353 / 24.04 / Remove redundant draid validation

src/middlewared/middlewared/plugins/zfs_/pool.py
To create groups in draid, the total number of disks available for data must be divisible by `draid_data_disks`. For example, if there are 12 disks available for data, then `draid_data_disks` must be a number that is divisible by 12, such as 2, 3, or 4. These numbers can be evenly divided into 6, 4, and 3 groups, respectively.
However, this validation is already handled in py_libzfs when creating groups. The provided code snippet demonstrates how the left-hand side of the code ensures this validation. It attempts to find a multiple of available disks that will be grouped together. For example, if there are 12 disks with 3 `draid_data_disks` and 3 parity disks, it will iterate as follows: 1 * 6 % 12 = 6, and then in the second iteration, 2 * 6 % 12 = 0. This process finds a multiple for …
=> NAS-123353 / 23.10 / Remove redundant draid validation (by Qubad786)

src/freenas/usr/local/sbin/disk_resize
When a process opens a device for a write operation and then closes it, udevd synthesizes a change event, which results in several ATA commands. The ATA_CMD_SET_MAX_EXT command requires ATA_CMD_READ_NATIVE_MAX_EXT to be executed exactly as the previous command. sginfo operations open the device with O_RDWR. Setting sense data before setting max sectors causes udevd to inject an ATA command between ATA_CMD_READ_NATIVE_MAX_EXT and ATA_CMD_SET_MAX_EXT, leading to the eventual failure of ATA_CMD_SET_MAX_EXT. To fix this issue, we should wait for the udev event queue to drain before setting max sectors.
Validated on both Bluefin and Cobia by Jeff Ervine.
=> NAS-123000 / 24.04 / SATA: Wait for udev events to settle before setting max sector count

src/freenas/usr/local/sbin/disk_resize
When a process opens a device for a write operation and then closes it, udevd synthesizes a change event, which results in several ATA commands. The ATA_CMD_SET_MAX_EXT command requires ATA_CMD_READ_NATIVE_MAX_EXT to be executed exactly as the previous command. sginfo operations open the device with O_RDWR. Setting sense data before setting max sectors causes udevd to inject an ATA command between ATA_CMD_READ_NATIVE_MAX_EXT and ATA_CMD_SET_MAX_EXT, leading to the eventual failure of ATA_CMD_SET_MAX_EXT. To fix this issue, we should wait for the udev event queue to drain before setting max sectors.
Validated on both Bluefin and Cobia by Jeff Ervine.
Original PR: https://github.com/truenas/middleware/pull/11755
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123000
=> NAS-123000 / 22.12.4 / SATA: Wait for udev events to settle before setting max sector count (by ixhamza)

src/freenas/usr/local/sbin/disk_resize
When a process opens a device for a write operation and then closes it, udevd synthesizes a change event, which results in several ATA commands. The ATA_CMD_SET_MAX_EXT command requires ATA_CMD_READ_NATIVE_MAX_EXT to be executed exactly as the previous command. sginfo operations open the device with O_RDWR. Setting sense data before setting max sectors causes udevd to inject an ATA command between ATA_CMD_READ_NATIVE_MAX_EXT and ATA_CMD_SET_MAX_EXT, leading to the eventual failure of ATA_CMD_SET_MAX_EXT. To fix this issue, we should wait for the udev event queue to drain before setting max sectors.
Validated on both Bluefin and Cobia by Jeff Ervine.
Original PR: https://github.com/truenas/middleware/pull/11755
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123000
=> NAS-123000 / 23.10 / SATA: Wait for udev events to settle before setting max sector count (by ixhamza)

src/freenas/usr/local/sbin/disk_resize
When a process opens a device for a write operation and then closes it, udevd synthesizes a change event, which results in several ATA commands. The ATA_CMD_SET_MAX_EXT command requires ATA_CMD_READ_NATIVE_MAX_EXT to be executed exactly as the previous command. sginfo operations open the device with O_RDWR. Setting sense data before setting max sectors causes udevd to inject an ATA command between ATA_CMD_READ_NATIVE_MAX_EXT and ATA_CMD_SET_MAX_EXT, leading to the eventual failure of ATA_CMD_SET_MAX_EXT. To fix this issue, we should wait for the udev event queue to drain before setting max sectors.
Validated on both Bluefin and Cobia by Jeff Ervine.
Original PR: https://github.com/truenas/middleware/pull/11755
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123000
=> NAS-123000 / 23.10-BETA.1 / SATA: Wait for udev events to settle before setting max sector count (by ixhamza)

src/freenas/usr/local/sbin/disk_resize
In nvmeXnY, 'Y' does not represent the namespace ID, but rather the namespace instance. Reading the correct namespace ID allows us to resize nvmeXn2 disks, which happens in the case of HA where fenced does not release a disk, making it reappear as nvmeXn2.
Tested by Jeff Ervin on f60-141.dc1.ixsystems.net.
=> NAS-123267 / 24.04 / Use the correct namespace id for disk resize

src/freenas/usr/local/sbin/disk_resize
In nvmeXnY, 'Y' does not represent the namespace ID, but rather the namespace instance. Reading the correct namespace ID allows us to resize nvmeXn2 disks, which happens in the case of HA where fenced does not release a disk, making it reappear as nvmeXn2.
Tested by Jeff Ervin on f60-141.dc1.ixsystems.net.
Original PR: https://github.com/truenas/middleware/pull/11784
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123267
=> NAS-123267 / 22.12.4 / Use the correct namespace id for disk resize (by ixhamza)

src/freenas/usr/local/sbin/disk_resize
In nvmeXnY, 'Y' does not represent the namespace ID, but rather the namespace instance. Reading the correct namespace ID allows us to resize nvmeXn2 disks, which happens in the case of HA where fenced does not release a disk, making it reappear as nvmeXn2.
Tested by Jeff Ervin on f60-141.dc1.ixsystems.net.
Original PR: https://github.com/truenas/middleware/pull/11784
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123267
=> NAS-123267 / 23.10-BETA.1 / Use the correct namespace id for disk resize (by ixhamza)

src/freenas/usr/local/sbin/disk_resize
In nvmeXnY, 'Y' does not represent the namespace ID, but rather the namespace instance. Reading the correct namespace ID allows us to resize nvmeXn2 disks, which happens in the case of HA where fenced does not release a disk, making it reappear as nvmeXn2.
Tested by Jeff Ervin on f60-141.dc1.ixsystems.net.
Original PR: https://github.com/truenas/middleware/pull/11784
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123267
=> NAS-123267 / 23.10 / Use the correct namespace id for disk resize (by ixhamza)

src/middlewared/middlewared/plugins/reporting/netdata/__init__.py, src/middlewared/middlewared/plugins/reporting/netdata/client.py, src/middlewared/middlewared/plugins/reporting/netdata/exceptions.py, src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py, src/middlewared/middlewared/plugins/reporting/rest.py
When system dataset is being migrated and a query is made by consumer to retrieve reporting metrics, that fails as netdata is not running during the migration of system dataset resulting in a traceback.
We should not allow the calls to fail when system dataset is being migrated but still nevertheless log the error in case there is an actual bug which is worth investigating.
=> NAS-123309 / 24.04 / Safely retrieve data if netdata is not running

src/middlewared/middlewared/plugins/reporting/netdata/__init__.py, src/middlewared/middlewared/plugins/reporting/netdata/client.py, src/middlewared/middlewared/plugins/reporting/netdata/exceptions.py, src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py, src/middlewared/middlewared/plugins/reporting/rest.py
When system dataset is being migrated and a query is made by consumer to retrieve reporting metrics, that fails as netdata is not running during the migration of system dataset resulting in a traceback.
We should not allow the calls to fail when system dataset is being migrated but still nevertheless log the error in case there is an actual bug which is worth investigating.
Original PR: https://github.com/truenas/middleware/pull/11783
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123309
=> NAS-123309 / 23.10 / Safely retrieve data if netdata is not running (by Qubad786)

src/middlewared/middlewared/plugins/reporting/netdata/__init__.py, src/middlewared/middlewared/plugins/reporting/netdata/client.py, src/middlewared/middlewared/plugins/reporting/netdata/exceptions.py, src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py, src/middlewared/middlewared/plugins/reporting/rest.py
When system dataset is being migrated and a query is made by consumer to retrieve reporting metrics, that fails as netdata is not running during the migration of system dataset resulting in a traceback.
We should not allow the calls to fail when system dataset is being migrated but still nevertheless log the error in case there is an actual bug which is worth investigating.
Original PR: https://github.com/truenas/middleware/pull/11783
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123309
=> NAS-123309 / 23.10-BETA.1 / Safely retrieve data if netdata is not running (by Qubad786)

src/middlewared/middlewared/plugins/enclosure_/map.py
This is crashing with a KeyError because I'm not referencing the correct dictionary. This means any platform that has a mapped head-unit will crash here
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure_/map.py", line 384, in map_enclosures
return await self._map_enclosures(enclosures, version_mapping.slots)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure_/map.py", line 441, in _map_enclosures
"bsg": original_enclosure["bsg"],
~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'bsg'
=> NAS-123375 / 24.04 / fix KeyError crash in enclosure.query

src/middlewared/middlewared/plugins/enclosure_/map.py
This is crashing with a KeyError because I'm not referencing the correct dictionary. This means any platform that has a mapped head-unit will crash here
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure_/map.py", line 384, in map_enclosures
return await self._map_enclosures(enclosures, version_mapping.slots)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure_/map.py", line 441, in _map_enclosures
"bsg": original_enclosure["bsg"],
~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'bsg'
Original PR: https://github.com/truenas/middleware/pull/11792
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123375
=> NAS-123375 / 23.10 / fix KeyError crash in enclosure.query (by yocalebo)

src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/sharesec.py, src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py, src/middlewared/middlewared/plugins/tdb/base.py, src/middlewared/middlewared/plugins/tdb/wrapper.py, tests/api2/test_430_smb_sharesec.py
Store base64-encoded copy of share ACL blob per-share rather than converting to string via sharesec. This allows restoring ACL without having to use the sharesec utility. Also add plumbing for enabling / disabling SMB shares via the smb.conf parameter `available` this allows clustered shares to be enabled / disabled.
These are both preparation steps for finalizing share ACL support on clustered TrueNAS.
=> NAS-123392 / 24.04 / Simplify SMB share ACL handling

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
This commit adds changes to make sure if license has been revoked on a HA system, we do not allow starting k8s for the system in question.
=> NAS-123015 / 24.04 / Do not allow starting k8s if system is not licensed

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
This commit adds changes to make sure if license has been revoked on a HA system, we do not allow starting k8s for the system in question.
Original PR: https://github.com/truenas/middleware/pull/11786
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123015
=> NAS-123015 / 23.10 / Do not allow starting k8s if system is not licensed (by sonicaj)

src/middlewared/middlewared/etc_files/cron.d/middlewared.mako
(cherry picked from commit e4ce3c2901670ac950a214fa1f0cac6e01503ae0)
=> NAS-123292 / 13.1 / Fix cron task for scrubbing a pool containing whitespace in its name

src/middlewared/middlewared/plugins/cluster_linux/management.py, src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py, src/middlewared/middlewared/plugins/sysdataset.py
We shouldn't allow cluster to be set up if system dataset is on the boot device, and users should be prevented from moving the system dataset on a clustered server.
=> NAS-123451 / 24.04 / Add clustered sysdataset validation

src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/sharesec.py, src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py, src/middlewared/middlewared/plugins/tdb/base.py, src/middlewared/middlewared/plugins/tdb/wrapper.py, tests/api2/test_430_smb_sharesec.py
Store base64-encoded copy of share ACL blob per-share rather than converting to string via sharesec. This allows restoring ACL without having to use the sharesec utility. Also add plumbing for enabling / disabling SMB shares via the smb.conf parameter `available` this allows clustered shares to be enabled / disabled.
These are both preparation steps for finalizing share ACL support on clustered TrueNAS.
Original PR: https://github.com/truenas/middleware/pull/11785
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123392
=> NAS-123392 / 23.10 / Simplify SMB share ACL handling (by anodos325)

src/middlewared/middlewared/plugins/cluster_linux/management.py, src/middlewared/middlewared/plugins/sysdataset.py
We shouldn't allow cluster to be set up if system dataset is on the boot device, and users should be prevented from moving the system dataset on a clustered server.
Original PR: https://github.com/truenas/middleware/pull/11811
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123451
=> NAS-123451 / 23.10 / Add clustered sysdataset validation (by anodos325)

src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
In a system we noted that some disks had their serials in the format `WD-WXB2XXXXS97` whereas the csv file created by smartd had been named `WD_WXB2XXXXS97` which ended up in us not retrieving details for the disk.
Account for this change in the logic we have which determines which disks data has been collected by netdata.
=> NAS-123363 / 24.04 / Fix disk temperature identifier bug

src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
In a system we noted that some disks had their serials in the format `WD-WXB2XXXXS97` whereas the csv file created by smartd had been named `WD_WXB2XXXXS97` which ended up in us not retrieving details for the disk.
Account for this change in the logic we have which determines which disks data has been collected by netdata.
Original PR: https://github.com/truenas/middleware/pull/11814
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123363
=> NAS-123363 / 23.10 / Fix disk temperature identifier bug (by Qubad786)

src/middlewared/middlewared/etc_files/dhclient.conf.mako
Similar to what we do with the ipv4 gateway, we need to supersede the name servers provided by DHCP if we already have the name servers set in the database (user has manually configured them).
=> NAS-123017 / 24.04 / supersede nameservers in dhclient.conf

src/middlewared/middlewared/plugins/vm/devices/display.py
When assigning a port number to `web_port`, we are not taking into account the display port number that will be utilized by SPICE. Consequently, there are instances where the `web_port` and display ports end up being the same. This issue disrupts the entire virtual machine display configuration.
If user has already specified a port we should remove that from the new ports we are getting from our port wizard so that if one of the attrs has been specified already and it matches to what the port wizard provided us, we remove it from there and make sure we don't end up using it.
Original PR: https://github.com/truenas/middleware/pull/11825
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123446
=> NAS-123446 / 23.10 / Fix new port assignment bug (by Qubad786)

src/middlewared/middlewared/plugins/enclosure_/element_types.py, src/middlewared/middlewared/plugins/enclosure_/enclosure2.py, src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py, src/middlewared/middlewared/plugins/enclosure_/identification.py, src/middlewared/middlewared/plugins/enclosure_/map2.py, src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py, src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_element_types.py, src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_identification.py, src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_slot_mappings.py, src/middlewared/middlewared/utils/scsi_generic.py
Before the reviewer(s) go(es) into a panic because of the ~2k lines of changes, it's important to note a few things.
1. this is NOT being used by the front-end and isn't even being called by back-end. This is incomplete right now (still need to handle mapping nvme drives on our enclosures, and drive identification) but is fully functional otherwise
2. the `element_types.py`, `enclosure_class.py` and `identification.py` files are essentially copy and pasted directly from CORE with a few minor tweaks.
3. 869 lines of changes are from unit tests (yayyy, unit tests are better than no tests 😄 )
4. MOST of this logic is essentially what we do on CORE so I'm not diverging significantly
5. I've added a pure python (ctypes) script (`scsi_generic.py`) for sending inquiry commands to the enclosure …
=> NAS-123479 / 24.04 / port CORE enclosure plugin to SCALE (stage 1)

src/middlewared/middlewared/plugins/smb_/sharesec.py
Fix arguments, use filterable decorator, and return empty list if the share_info.tdb file is missing.
=> NAS-123516 / 24.04 / fix smb.sharesec.entries

src/middlewared/middlewared/plugins/smb_/sharesec.py
Fix arguments, use filterable decorator, and return empty list if the share_info.tdb file is missing.
Original PR: https://github.com/truenas/middleware/pull/11835
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123516
=> NAS-123516 / 23.10 / fix smb.sharesec.entries (by anodos325)

src/middlewared/middlewared/rclone/remote/s3.py
There will be no behavioral change https://github.com/rclone/rclone/blob/34195fd3e87c51bbd1ed6ced9e5cf19f57ce7030/backend/s3/s3.go#L3051
=> NAS-123452 / 24.04 / Get rid of `NOTICE: s3: s3 provider "" not known - please set correctly`

src/middlewared/middlewared/rclone/remote/s3.py
There will be no behavioral change https://github.com/rclone/rclone/blob/34195fd3e87c51bbd1ed6ced9e5cf19f57ce7030/backend/s3/s3.go#L3051
Original PR: https://github.com/truenas/middleware/pull/11839
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123452
=> NAS-123452 / 23.10 / Get rid of `NOTICE: s3: s3 provider "" not known - please set correctly` (by themylogin)

src/middlewared/middlewared/plugins/enclosure_/enclosure2.py, src/middlewared/middlewared/plugins/enclosure_/nvme2.py, src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py, src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_slot_mappings.py
This adds the missing functionality that is responsible for mapping nvme drives on certain platforms that we sell. More specifically, it maps the M50, M60, F60, F100, F130, R50, R50B, and R50BM platforms. Again, this code is essentially copied and pasted from how we're currently mapping nvme drives on SCALE (`enclosure_/nvme.py`) but has been changed to work with the new enclosure rewrite.
=> NAS-123529 / 24.04 / Add nvme2.py (map_nvme() functionality) to enclosure plugin

src/middlewared/middlewared/plugins/reporting/realtime_reporting/ifstat.py
The ifstat function is currently returning data on the first iteration, which prevents it from processing other interfaces.
Make sure all interfaces are processed when getting realtime interface stats.
=> NAS-123488 / 24.04 / Fix bug in interface stats

src/middlewared/middlewared/plugins/reporting/realtime_reporting/ifstat.py
The ifstat function is currently returning data on the first iteration, which prevents it from processing other interfaces.
Make sure all interfaces are processed when getting realtime interface stats.
Original PR: https://github.com/truenas/middleware/pull/11848
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123488
=> NAS-123488 / 23.10 / Fix bug in interface stats (by Qubad786)

src/middlewared/middlewared/plugins/iscsi_/global_linux.py, src/middlewared/middlewared/plugins/pool_/dataset.py, tests/api2/test_261_iscsi_cmd.py
Certain iSCSI configurations were permitted in CORE that are not valid in SCALE.  One of these was **already** being [handled](https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/etc_files/scst.conf.mako#L114) in _scst.conf.mako_
This PR makes a similar change is required in `resync_lun_size_for_zvol`.
Furthermore, a unit test is added: _test_25_resize_target_zvol_
=> NAS-123403 / 24.04 / Expanding iSCSI ZVol with a period in name doesn't notify connected client

src/middlewared/middlewared/plugins/iscsi_/global_linux.py, src/middlewared/middlewared/plugins/pool_/dataset.py, tests/api2/test_261_iscsi_cmd.py
Certain iSCSI configurations were permitted in CORE that are not valid in SCALE.  One of these was **already** being [handled](https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/etc_files/scst.conf.mako#L114) in _scst.conf.mako_
This PR makes a similar change is required in `resync_lun_size_for_zvol`.
Furthermore, a unit test is added: _test_25_resize_target_zvol_
Original PR: https://github.com/truenas/middleware/pull/11853
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123403
=> NAS-123403 / 23.10 / Expanding iSCSI ZVol with a period in name doesn't notify connected client (by bmeagherix)

src/middlewared/middlewared/plugins/container_runtime_interface/client.py, src/middlewared/middlewared/plugins/kubernetes_linux/nodes.py, src/middlewared/middlewared/utils/socket.py
This PR adds changes which makes sure that containerd socket is available and has initialized itself appropriately as we are seeing in some cases that we mark the node as ready but that is not the case with containerd socket still not available for consumption.
=> NAS-123466 / 24.04 / Make sure containerd has initialized itself before declaring apps are ready

src/middlewared/middlewared/plugins/container_runtime_interface/client.py, src/middlewared/middlewared/plugins/kubernetes_linux/nodes.py, src/middlewared/middlewared/utils/socket.py
This PR adds changes which makes sure that containerd socket is available and has initialized itself appropriately as we are seeing in some cases that we mark the node as ready but that is not the case with containerd socket still not available for consumption.
Original PR: https://github.com/truenas/middleware/pull/11850
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123466
=> NAS-123466 / 23.10 / Make sure containerd has initialized itself before declaring apps are ready (by sonicaj)

src/middlewared/middlewared/main.py, src/middlewared/middlewared/restful.py, tests/api2/test_auth_otp.py
…ed (#9742)
* HTTP Basic Auth is unavailable when OTP is enabled
* OTP integration tests
Original PR: https://github.com/truenas/middleware/pull/11818
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123289
=> NAS-123289 / 13.0 / HTTP Basic Auth is unavailable when OTP is enabl… (by sonicaj)

src/middlewared/middlewared/plugins/pool_/dataset_encryption_info.py, src/middlewared/middlewared/plugins/zettarepl.py, tests/api2/test_dataset_encryption_keys_in_replication.py
This PR adds changes to add a public end point to download encryption keys of datasets related to a replication task. This can then be used in the UI so that the downloaded file can be directly used by users in the target/destination system to unlock the encrypted datasets.
=> NAS-123372 / 24.04 / Add a public endpoint to download dataset keys related to a replication task

src/middlewared/middlewared/plugins/pool_/dataset_encryption_info.py, src/middlewared/middlewared/plugins/zettarepl.py, tests/api2/test_dataset_encryption_keys_in_replication.py
This PR adds changes to add a public end point to download encryption keys of datasets related to a replication task. This can then be used in the UI so that the downloaded file can be directly used by users in the target/destination system to unlock the encrypted datasets.
Original PR: https://github.com/truenas/middleware/pull/11847
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123372
=> NAS-123372 / 23.10 / Add a public endpoint to download dataset keys related to a replication task (by sonicaj)

tests/api2/test_auth_otp.py
This commit adds changes to try and disable 2fa instead of querying system info as a customer had faced this scenario in previous versions and we want to be sure we are not allowing that to happen.
=> NAS-123572 / 24.04 / Update OTP test to try and disable 2FA

tests/api2/test_auth_otp.py
This commit adds changes to try and disable 2fa instead of querying system info as a customer had faced this scenario in previous versions and we want to be sure we are not allowing that to happen.
Original PR: https://github.com/truenas/middleware/pull/11860
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123572
=> NAS-123572 / 13.0 / Update OTP test to try and disable 2FA (by sonicaj)

tests/api2/test_auth_otp.py
This commit adds changes to try and disable 2fa instead of querying system info as a customer had faced this scenario in previous versions and we want to be sure we are not allowing that to happen.
Original PR: https://github.com/truenas/middleware/pull/11860
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123572
=> NAS-123572 / 13.1 / Update OTP test to try and disable 2FA (by sonicaj)

tests/api2/test_auth_otp.py
This commit adds changes to try and disable 2fa instead of querying system info as a customer had faced this scenario in previous versions and we want to be sure we are not allowing that to happen.
Original PR: https://github.com/truenas/middleware/pull/11860
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123572
=> NAS-123572 / 23.10 / Update OTP test to try and disable 2FA (by sonicaj)

src/freenas/usr/lib/netdata/python.d/cputemp.chart.py
The existing cputemp plugin encounters issues when dealing with hardware that lacks physical sensors. This deficiency leads to None type errors within the netdata python.d plugin.
To address this problem, a solution has been devised wherein default sensor data is integrated. This data will be utilized as a substitute for None values, effectively resolving the problem.
=> NAS-123576 / 24.04 / Fix cpu temp plugin for those machine which don't have sensors

src/freenas/usr/lib/netdata/python.d/cputemp.chart.py
The existing cputemp plugin encounters issues when dealing with hardware that lacks physical sensors. This deficiency leads to None type errors within the netdata python.d plugin.
To address this problem, a solution has been devised wherein default sensor data is integrated. This data will be utilized as a substitute for None values, effectively resolving the problem.
Original PR: https://github.com/truenas/middleware/pull/11865
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123576
=> NAS-123576 / 23.10 / Fix cpu temp plugin for those machine which don't have sensors (by Qubad786)

src/middlewared/middlewared/plugins/iscsi_/extents.py, src/middlewared/middlewared/plugins/iscsi_/global_linux.py, tests/api2/test_261_iscsi_cmd.py
Allow the size of a file-based extent for an iSCSI target to be increased.
This includes adding `resync_lun_size_for_file` (similar to `resync_lun_size_for_zvol`) to notify SCST and any connected clients about the change.
---
Currently the API ignores attempts to reduce the size of the extent (although the size will be saved in the database).  I would like to tweak the API to also allow reducing the size of the file, however ...
For ZVOL based targets, the webui code currently traps attempting to reduce the size of a target.  It presents the error message:
> Shrinking a ZVOL is not allowed in the User Interface. This can lead to data loss.
@undsoft do you think the webui should add a similar block to prevent reducing the size of a file extent?  (If so, I can then tweak this PR to allow …
=> NAS-123570 / 24.04 / Extending a file-based iSCSI target has no effect

src/middlewared/middlewared/plugins/iscsi_/extents.py, src/middlewared/middlewared/plugins/iscsi_/global_linux.py, tests/api2/test_261_iscsi_cmd.py
Allow the size of a file-based extent for an iSCSI target to be increased.
This includes adding `resync_lun_size_for_file` (similar to `resync_lun_size_for_zvol`) to notify SCST and any connected clients about the change.
---
Currently the API ignores attempts to reduce the size of the extent (although the size will be saved in the database).  I would like to tweak the API to also allow reducing the size of the file, however ...
For ZVOL based targets, the webui code currently traps attempting to reduce the size of a target.  It presents the error message:
> Shrinking a ZVOL is not allowed in the User Interface. This can lead to data loss.
@undsoft do you think the webui should add a similar block to prevent reducing the size of a file extent?  (If so, I can then tweak this PR to allow …
=> NAS-123570 / 23.10 / Extending a file-based iSCSI target has no effect (by bmeagherix)

src/middlewared/middlewared/plugins/enclosure_/map2.py, src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py, src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_slot_mappings.py
The R40 doesn't have a predictable guaranteed unique enclosure identifier to map the drives. It is the only platform with this problem so the best we can do is use the enclosures logical id and map the 1st set of 24 slots to the enclosure with the smaller id while mapping the 2nd slot of 24 drives (total of 48) to the enclosure with the larger id.
I've also improved and simplified the code quite a bit.
- add R40 enclosure mapping support
- add dict comprehensions to remove unnecessary lines
- simplify the `map2.py:map_enclosures()` function
- remove a top-level key `mapping_info` since it was unnecessary and caused a level of indirection that wasn't needed
- update unit tests to reflect the changes
=> NAS-123537 / 24.04 / add R40 enclosure mapping to new enclosure code

src/middlewared/middlewared/plugins/reporting/graphs.py, src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py, src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
To put the problem in perspective - if a machine has no disks for which we can collect temperature, whenever `reporting.netdata_graph` will be called it will assume a `None` identifier as some plugins do not require an explicit identifier and keeping in line with old behavior we were doing the same.
However if a plugin which actually consumes identifiers and reports an empty list because there are no identifiers available in this case and the plugin will fail if that is done - we were doing exactly that which resulted in traceback.
Make sure we take into account if the plugin actually needs/consumes identifiers and based on that we retrieve graphs appropriately.
=> NAS-123592 / 24.04 / Fix case when reporting identifier can be none

src/middlewared/middlewared/plugins/reporting/graphs.py, src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py, src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
To put the problem in perspective - if a machine has no disks for which we can collect temperature, whenever `reporting.netdata_graph` will be called it will assume a `None` identifier as some plugins do not require an explicit identifier and keeping in line with old behavior we were doing the same.
However if a plugin which actually consumes identifiers and reports an empty list because there are no identifiers available in this case and the plugin will fail if that is done - we were doing exactly that which resulted in traceback.
Make sure we take into account if the plugin actually needs/consumes identifiers and based on that we retrieve graphs appropriately.
Original PR: https://github.com/truenas/middleware/pull/11873
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123592
=> NAS-123592 / 23.10 / Fix case when reporting identifier can be none (by Qubad786)

src/freenas/etc/systemd/system/nfs-server.service.d/override.conf, src/middlewared/middlewared/alert/source/nfs_exportsd.py, src/middlewared/middlewared/etc_files/exports.mako, src/middlewared/middlewared/plugins/service_/services/nfs.py, tests/api2/test_300_nfs.py
In releases prior to Cobia, the NFS server start was dependent on the existence of NFS shares and would potentially complain if the exports file was empty.  This is no longer the case in Cobia. 
What this changes:
- NFS server start is independent of NFS shares
Additions:
- Entries in /etc/exports.d are not tolerated and a systemd start condition was added to that effect
- At manual NFS start, we raise an error alert if entries are detected in /etc/exports.d
Added a CI test for NFS service start independent of shares
Added a CI test for NFS start with rogue entries in /etc/exports.d
=> NAS-123498 / 24.04 / Allow NFS server to start with empty or missing exports

src/freenas/etc/systemd/system/nfs-server.service.d/override.conf, src/middlewared/middlewared/alert/source/nfs_exportsd.py, src/middlewared/middlewared/etc_files/exports.mako, src/middlewared/middlewared/plugins/service_/services/nfs.py, tests/api2/test_300_nfs.py
In releases prior to Cobia, the NFS server start was dependent on the existence of NFS shares and would potentially complain if the exports file was empty.  This is no longer the case in Cobia. 
What this changes:
- NFS server start is independent of NFS shares
Additions:
- Entries in /etc/exports.d are not tolerated and a systemd start condition was added to that effect
- At manual NFS start, we raise an error alert if entries are detected in /etc/exports.d
Added a CI test for NFS service start independent of shares
Added a CI test for NFS start with rogue entries in /etc/exports.d
Original PR: https://github.com/truenas/middleware/pull/11871
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123498
=> NAS-123498 / 23.10 / Allow NFS server to start with empty or missing exports (by mgrimesix)

src/middlewared/middlewared/plugins/reporting/netdata/client.py
When netdata is not running - `ClientOSError` can be raised as well by the aiohttp client so we should be handling that gracefully.
Catch `ClientOSError` appropriately and raise it in a proper manner so it can be handled in middleware gracefully.
=> NAS-123535 / 24.04 / Gracefully handle client os error

src/middlewared/middlewared/plugins/acme_protocol_/authenticators/cloudflare.py
`_CloudflareClient`'s constructor changed with https://github.com/certbot/certbot/commit/a845ab844622a5419de166a3a35bb4dca33d8060, which has been incorporated in the most recent version of the `certbot-dns-cloudflare` package. Update middleware's use of this class to prevent the error `neither email/key or token defined.` during DNS challenge creation.
=> NAS-123623 / 24.04 / acme: Fix instantiation of _CloudflareClient

src/middlewared/middlewared/plugins/pool_/dataset_encryption_info.py, src/middlewared/middlewared/plugins/replication.py, tests/api2/test_dataset_encryption_keys_in_replication.py
This PR adds an additional attribute in replication tasks which can be used to determine if the task has associated datasets which have encryption keys which can be downloaded by the user. This attribute can be consumed by UI to display a button next to replication tasks so that it is only displayed when there are actually datasets available which match the criteria.
While at it, performance for gathering keys which will be exported for a replication task has been improved as well with previous timing for me being on average 4 seconds for a task i have and now i am seeing 1.5 seconds.
For `replication.query` i see that when the extra flag is not specified the time for me is `0.09` seconds and with the flag it is 0.2 seconds where i have 3 replication tasks.
=> NAS-123597 / 24.04 / Add an additional attribute in replication task

src/middlewared/middlewared/plugins/acme_protocol_/authenticators/cloudflare.py
`_CloudflareClient`'s constructor changed with https://github.com/certbot/certbot/commit/a845ab844622a5419de166a3a35bb4dca33d8060, which has been incorporated in the most recent version of the `certbot-dns-cloudflare` package. Update middleware's use of this class to prevent the error `neither email/key or token defined.` during DNS challenge creation.
Original PR: https://github.com/truenas/middleware/pull/11898
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123623
=> NAS-123623 / 23.10 / acme: Fix instantiation of _CloudflareClient (by evan-a-a)

src/middlewared/middlewared/plugins/pool_/unlock.py, src/middlewared/middlewared/plugins/zfs_/dataset_encryption.py
No 24.04 backport is needed, these fixes are included in https://github.com/truenas/middleware/pull/11895
=> NAS-123622 / 23.10 / Fix misused `id`

src/middlewared/middlewared/plugins/ipmi_/lan.py
```
File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 181, in nf
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/ipmi_/lan.py", line 64, in query
for i in filter(lambda x: x.startswith('\t') and not x.startswith('\t#'), stdout.split('\n')):
^^^^^^
UnboundLocalError: cannot access local variable 'stdout' where it is not associated with a value
```
Original PR: https://github.com/truenas/middleware/pull/11902
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123613
=> NAS-123613 / 23.10 / fix UnboundLocalError crash in ipmi_/lan.py (by yocalebo)

src/middlewared/middlewared/plugins/pool_/unlock.py, src/middlewared/middlewared/plugins/zfs.py
git cherry-pick -x 24cecae3a2e0e27a08f044747918ce4b2b582bdc
git cherry-pick -x bfecb8b730b2d9b86780cde41362326126ab2006
No 24.04 backport is needed, these fixes are included in https://github.com/truenas/middleware/pull/11895
Original PR: https://github.com/truenas/middleware/pull/11896
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123622
=> NAS-123622 / 22.12.4 / Fix misused `id` (by themylogin)

src/middlewared/middlewared/plugins/service_/services/ups.py
This PR adds changes to account for `nut-driver-enumerator` service which needs to be accounted for as well when UPS is running in bookworm because without that the ups driver is not recognized which results in UPS not working.
=> NAS-123625 / 24.04 / Add changes to ensure UPS service works nicely in bookworm

src/freenas/usr/lib/netdata/python.d/k3s_stats.chart.py, src/middlewared/middlewared/etc_files/netdata/python_conf.py, src/middlewared/middlewared/etc_files/rancher/k3s/flags.py, src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py, src/middlewared/middlewared/plugins/chart_releases_linux/events.py, src/middlewared/middlewared/plugins/chart_releases_linux/resources.py, src/middlewared/middlewared/plugins/chart_releases_linux/utils.py, src/middlewared/middlewared/plugins/kubernetes_linux/k8s/core_api.py, src/middlewared/middlewared/plugins/kubernetes_linux/stats.py, src/middlewared/middlewared/plugins/reporting/stats_utils.py, src/middlewared/middlewared/plugins/reporting/utils.py
At present, k3s statistics are obtained during runtime using the k3s node summary API. However, this approach introduces notable sluggishness into the process, particularly due to the extensive number of API calls needed to access and update data in real-time. To tackle this performance bottleneck, a novel solution has been implemented in the form of a netdata python.d plugin. This plugin systematically collects data at set intervals, enabling us to efficiently retrieve data through streamlined queries. Consequently, this transition in data collection effectively distributes the computational load, significantly alleviating the previous strain on the middleware. It's important to note that netdata does not offer alternative methods that can be seamlessly integrated into the middleware for …
=> NAS-121442 / 24.04 / Gather kubernetes statistics for UI

src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py
This commit adds changes to reflect default value for available gpus because in case if a user allocated a gpu to an app and then later removed the gpu, UI does not present him with a way of resetting that configuration because middleware reports empty dict for available gpus. The aim is to at least account for the keys with defaults so user can easily unset it - it is still currently possible to unset but via API.
=> NAS-122970 / 24.04 / Add default value for available gpus

src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py
This commit adds changes to reflect default value for available gpus because in case if a user allocated a gpu to an app and then later removed the gpu, UI does not present him with a way of resetting that configuration because middleware reports empty dict for available gpus. The aim is to at least account for the keys with defaults so user can easily unset it - it is still currently possible to unset but via API.
Original PR: https://github.com/truenas/middleware/pull/11924
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122970
=> NAS-122970 / 22.12.4 / Add default value for available gpus (by sonicaj)

src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py
This commit adds changes to reflect default value for available gpus because in case if a user allocated a gpu to an app and then later removed the gpu, UI does not present him with a way of resetting that configuration because middleware reports empty dict for available gpus. The aim is to at least account for the keys with defaults so user can easily unset it - it is still currently possible to unset but via API.
Original PR: https://github.com/truenas/middleware/pull/11924
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122970
=> NAS-122970 / 23.10 / Add default value for available gpus (by sonicaj)

src/middlewared/middlewared/plugins/filesystem_/acl_template.py
Seen in user debug who had configured the AD idmap backend but not set up unix IDs for domain users and domain admins.
=> NAS-123689 / 24.04 / Fix crash in querying ACL template

src/middlewared/middlewared/plugins/filesystem_/acl_template.py
Seen in user debug who had configured the AD idmap backend but not set up unix IDs for domain users and domain admins.
Original PR: https://github.com/truenas/middleware/pull/11925
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123689
=> NAS-123689 / 23.10 / Fix crash in querying ACL template (by anodos325)

src/middlewared/middlewared/plugins/filesystem_/acl_template.py
Seen in user debug who had configured the AD idmap backend but not set up unix IDs for domain users and domain admins.
Original PR: https://github.com/truenas/middleware/pull/11925
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123689
=> NAS-123689 / 22.12.4 / Fix crash in querying ACL template (by anodos325)

src/middlewared/middlewared/plugins/pool_/pool.py, src/middlewared/middlewared/plugins/pool_/topology.py, src/middlewared/middlewared/plugins/pool_/utils.py
It was requested by UI that middleware should report draid vdev statistics like parity/spares/data disks etc when querying for pool information.
=> NAS-123692 / 24.04 / Add additional draid vdev stats when querying pool data

src/middlewared/middlewared/plugins/pool_/pool.py, src/middlewared/middlewared/plugins/pool_/topology.py, src/middlewared/middlewared/plugins/pool_/utils.py
It was requested by UI that middleware should report draid vdev statistics like parity/spares/data disks etc when querying for pool information.
Original PR: https://github.com/truenas/middleware/pull/11934
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123692
=> NAS-123692 / 23.10 / Add additional draid vdev stats when querying pool data (by Qubad786)

src/middlewared/middlewared/etc_files/rancher/k3s/flags.py
Reason for switching to `KubeletConfiguration` is that kubelet flags are [deprecated](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) (See on every flag description).
Also added a gracefulShutdown period for pods. So k8s can try to stop pods when a shutdown is detected.
While the feature gate `GracefulNodeShutdown` is [enabled by default](https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown) on v1.21 and later it needs some configuration to actually be enabled. 
---
Tested that config file is being picked up, by doing the following
1. make the changes on my system (but setting maxPods to `1`)
2. restart middlewared
3. unset pool
4. set pool
5. observe that only 1 pod could start
6. reset maxPods back to 250
7. Repeat 2-4
8. observe all …
=> NAS-123632 / 24.04 / switch to `KubeletConfiguration` as flags are deprecated and add grace periods for node shutdown

src/middlewared/middlewared/etc_files/rancher/k3s/flags.py
Reason for switching to `KubeletConfiguration` is that kubelet flags are [deprecated](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) (See on every flag description).
Also added a gracefulShutdown period for pods. So k8s can try to stop pods when a shutdown is detected.
While the feature gate `GracefulNodeShutdown` is [enabled by default](https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown) on v1.21 and later it needs some configuration to actually be enabled. 
---
Tested that config file is being picked up, by doing the following
1. make the changes on my system (but setting maxPods to `1`)
2. restart middlewared
3. unset pool
4. set pool
5. observe that only 1 pod could start
6. reset maxPods back to 250
7. Repeat 2-4
8. observe all …
=> NAS-123632 / 23.10 / switch to `KubeletConfiguration` as flags are deprecated and add grace periods for node shutdown (by stavros-k)

src/middlewared/middlewared/alert/source/truecommand.py, src/middlewared/middlewared/plugins/truecommand/portal.py, src/middlewared/middlewared/plugins/truecommand/update.py, src/middlewared/middlewared/plugins/truecommand/wireguard.py
This PR adds changes to raise an alert for the user in the case when wireguard service on truenas is running as desired but the the TC container is actually down.
=> NAS-119369 / 24.04 / Properly account for the case when TC container might not be running

src/middlewared/middlewared/alert/source/truecommand.py, src/middlewared/middlewared/plugins/truecommand/portal.py, src/middlewared/middlewared/plugins/truecommand/update.py, src/middlewared/middlewared/plugins/truecommand/wireguard.py
This PR adds changes to raise an alert for the user in the case when wireguard service on truenas is running as desired but the the TC container is actually down.
Original PR: https://github.com/truenas/middleware/pull/11937
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119369
=> NAS-119369 / 13.1 / Properly account for the case when TC container might not be running (by sonicaj)

src/middlewared/middlewared/alert/source/truecommand.py, src/middlewared/middlewared/plugins/truecommand/portal.py, src/middlewared/middlewared/plugins/truecommand/update.py, src/middlewared/middlewared/plugins/truecommand/wireguard.py
This PR adds changes to raise an alert for the user in the case when wireguard service on truenas is running as desired but the the TC container is actually down.
Original PR: https://github.com/truenas/middleware/pull/11937
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119369
=> NAS-119369 / 23.10 / Properly account for the case when TC container might not be running (by sonicaj)

src/middlewared/middlewared/plugins/reporting/graphs.py, src/middlewared/middlewared/plugins/reporting/netdata/connector.py, src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py, src/middlewared/middlewared/plugins/reporting/utils.py
The process of fetching data for `reporting.netdata_graph` is taking a significant amount of time, approximately around 1 minute and 10 seconds, particularly on systems with a large number of resources like disks. This duration exceeds our API timeout, which is set at 60 seconds.
To address this performance issue, several optimizations have been implemented. Primarily, improvements were made to the aggregation function, which was consuming extra time. Additionally, the method of requesting data was changed from sequential to parallel retrieval. These enhancements collectively resulted in a performance boost of around 40-45%. As a result, the data retrieval process for `reporting.netdata_graph` now takes only 39 seconds, well within the API timeout on a system which has the most resources …
=> NAS-123326 / 24.04 / Improve retrieving historical stats performance

src/middlewared/middlewared/plugins/reporting/graphs.py, src/middlewared/middlewared/plugins/reporting/netdata/connector.py, src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py, src/middlewared/middlewared/plugins/reporting/utils.py
git cherry-pick -x eeaedd2cdcf9b83fdd694d6414d7fa1acec3ec10
git cherry-pick -x 58c406958c04ffd231367c14686fc06a911b0cbe
The process of fetching data for `reporting.netdata_graph` is taking a significant amount of time, approximately around 1 minute and 10 seconds, particularly on systems with a large number of resources like disks. This duration exceeds our API timeout, which is set at 60 seconds.
To address this performance issue, several optimizations have been implemented. Primarily, improvements were made to the aggregation function, which was consuming extra time. Additionally, the …
=> NAS-123326 / 23.10 / Improve retrieving historical stats performance (by Qubad786)

src/middlewared/middlewared/plugins/enclosure.py, src/middlewared/middlewared/utils/license.py
This adds ES60G2 enclosure detection while also adding it to utils/license.py. While I'm here, add ES102S to utils/license.py since it seems it was forgotten.
=> NAS-123286 / 23.10 / add ES60G2 enclosure detection

src/middlewared/middlewared/plugins/enclosure.py, src/middlewared/middlewared/utils/license.py
This adds ES60G2 enclosure detection while also adding it to utils/license.py. While I'm here, add ES102S to utils/license.py since it seems it was forgotten.
Original PR: https://github.com/truenas/middleware/pull/11954
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123286
=> NAS-123286 / 24.04 / add ES60G2 enclosure detection (by yocalebo)

src/middlewared/middlewared/plugins/enclosure.py, src/middlewared/middlewared/utils/license.py
This adds ES60G2 enclosure detection while also adding it to utils/license.py. While I'm here, add ES102S to utils/license.py since it seems it was forgotten.
Original PR: https://github.com/truenas/middleware/pull/11954
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123286
=> NAS-123286 / 22.12.4 / add ES60G2 enclosure detection (by yocalebo)

src/middlewared/middlewared/plugins/pool_/dataset_encryption_lock.py, src/middlewared/middlewared/plugins/pool_/unlock.py
This PR adds changes to remove `pool.dataset.restart_services_after_unlock` method and disk service usages as disk service no longer exists and was removed when collectd was removed from our product.
=> NAS-123741 / 24.04 / Fix disk service usage

src/middlewared/middlewared/plugins/system_advanced/gpu.py, src/middlewared/middlewared/plugins/vm/devices/pci.py, src/middlewared/middlewared/plugins/vm/devices/usb.py, src/middlewared/middlewared/plugins/vm/vm_lifecycle.py
It is not guarenteed that in HA machines on both nodes the PCI structure and the devices attached are same which means on failover we could end up with a disastrous scenario of bricking the system by trying to critical PCI slots/devices.
All forms of passthrough being disabled on HA machines addresses this problem.
=> NAS-123676 / 24.04 / Disable all forms of passthrough on ha machines

src/middlewared/middlewared/plugins/pool_/dataset_encryption_lock.py, src/middlewared/middlewared/plugins/pool_/unlock.py
git cherry-pick -x d424dd905aa29a4431ea940aa158a2d25127354b
git cherry-pick -x f5ad14e26f4790b0e27fd3a39399821780f83f1f
git cherry-pick -x 17d639b6442ad6b67f7d80eaf7590c30853ff3e0
This PR adds changes to remove `pool.dataset.restart_services_after_unlock` method and disk service usages as disk service no longer exists and was removed when collectd was removed from our product.
Original PR: https://github.com/truenas/middleware/pull/11957
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123741
=> NAS-123741 / 23.10 / Fix disk service usage (by sonicaj)

src/middlewared/middlewared/plugins/account.py, tests/api2/test_account_ssh_key.py
Strip trailing newlines/whitespace in `user.query` for the `sshpubkey` attribute.
=> NAS-123700 / 24.04 / strip trailing newline/whitespace on sshpubkey

src/middlewared/middlewared/plugins/account.py, tests/api2/test_account_ssh_key.py
Strip trailing newlines/whitespace in `user.query` for the `sshpubkey` attribute.
Original PR: https://github.com/truenas/middleware/pull/11963
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123700
=> NAS-123700 / 23.10 / strip trailing newline/whitespace on sshpubkey (by yocalebo)

src/middlewared/middlewared/plugins/system_advanced/gpu.py, src/middlewared/middlewared/plugins/vm/devices/pci.py, src/middlewared/middlewared/plugins/vm/devices/usb.py, src/middlewared/middlewared/plugins/vm/vm_lifecycle.py
It is not guarenteed that in HA machines on both nodes the PCI structure and the devices attached are same which means on failover we could end up with a disastrous scenario of bricking the system by trying to critical PCI slots/devices.
All forms of passthrough being disabled on HA machines addresses this problem.
Original PR: https://github.com/truenas/middleware/pull/11955
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123676
=> NAS-123676 / 23.10 / Disable all forms of passthrough on ha machines (by Qubad786)

src/middlewared/middlewared/plugins/account.py
The authorized keys file needs to be chowned to the newly-created user. Since this function is now synchronous and parent dir is guaranteed to be ACL-free, we can just use fchmod and fchown on it.
Original PR: https://github.com/truenas/middleware/pull/11973
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123764
=> NAS-123764 / 23.10 / Fix owner for authorized keys file (by anodos325)

src/middlewared/middlewared/plugins/nfs.py, src/middlewared/middlewared/pytest/unit/plugins/test_nfs.py, tests/api2/test_300_nfs.py
What is restricted on sharing to the same path:
1) Repeated 'host' or 'network' names
2) Potential collisions with the use of wildcards (everyone) and
overlaping of network subnets
=> NAS-123042 / 24.04 / Relax restrictions on NFS subdir sharing

src/middlewared/middlewared/plugins/account.py
There is no technical reason to prevent using question mark in an SMB password. This was requested by customer.
=> Allow question mark through backend validation

src/middlewared/middlewared/plugins/smb_/sharesec.py
This add checks that SID, domain, and name is known to us on an as-needed basis. Checking early in middleware gives better control of error messages before we pass along to the sharesec command. This endpoint has been substantially rewritten for Cobia and so the change only applies to BlueFin.
=> NAS-123585 / 22.12.4 / Add validation for share ACL payload

src/freenas/usr/lib/netdata/python.d/smart_log.chart.py, src/middlewared/middlewared/plugins/reporting/rest.py, src/middlewared/middlewared/plugins/reporting/utils.py, src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
Currently, smartd collects data at a 30-minute interval. However, our current data collection process from smartd involves allocating disk space for a 1-second interval. This mismatch between the collection intervals and disk space allocation intervals is causing excessive disk space allocation and unnecessarily cpu is being consumed as well.
To address this, we need to adjust our data collection process to match the 30-minute interval used by smartd for data collection.
=> NAS-123755 / 24.04 / Collect disk temperature stats at 30 min intervals

src/freenas/usr/lib/netdata/python.d/smart_log.chart.py, src/middlewared/middlewared/plugins/reporting/rest.py, src/middlewared/middlewared/plugins/reporting/utils.py, src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
git cherry-pick -x 4d0f2b0894cea383f7fdf06280e0739192596c2f
git cherry-pick -x 3d6089534ae02e747892fcfd8c774160c732f0d4
Currently, smartd collects data at a 30-minute interval. However, our current data collection process from smartd involves allocating disk space for a 1-second interval. This mismatch between the collection intervals and disk space allocation intervals is causing excessive disk space allocation and unnecessarily cpu is being consumed as well.
To address this, we need to adjust our data collection process to match the 30-minute interval used by smartd for data …
=> NAS-123755 / 23.10 / Collect disk temperature stats at 30 min intervals (by Qubad786)

tests/api2/test_25_kubernetes_passthrough_test.py
This PR adds changes to make sure we run the kubernetes passthrough test right after we have setup the cluster. Why this needs to be done is that after initial k8s tests are executed, we make network changes which are done in the testing framework which can result in temporary network failure in which if the cluster was downloading some images, that won't happen and cluster would not have initialized itself properly for the passthrough tests.
=> NAS-123607 / 24.04 / Fix kubernetes passthrough test

tests/api2/test_25_kubernetes_passthrough_test.py
This PR adds changes to make sure we run the kubernetes passthrough test right after we have setup the cluster. Why this needs to be done is that after initial k8s tests are executed, we make network changes which are done in the testing framework which can result in temporary network failure in which if the cluster was downloading some images, that won't happen and cluster would not have initialized itself properly for the passthrough tests.
Original PR: https://github.com/truenas/middleware/pull/11986
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123607
=> NAS-123607 / 23.10 / Fix kubernetes passthrough test (by sonicaj)

src/middlewared/middlewared/plugins/nfs.py, src/middlewared/middlewared/pytest/unit/plugins/test_nfs.py, tests/api2/test_300_nfs.py
What is restricted on sharing to the same path:
1) Repeated 'host' or 'network' names
2) Potential collisions with the use of wildcards (everyone) and
overlaping of network subnets
Original PR: https://github.com/truenas/middleware/pull/11953
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123042
=> NAS-123042 / 23.10 / Relax restrictions on NFS subdir sharing (by mgrimesix)

src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
This method is in a hot-path on our HA systems. It's vitally important to be as efficient and as quick as possible here. By calling `query_imported_fast_impl`, it removes a call to our process pool which is an efficiency and speed boost.
=> NAS-123825 / 24.04 / call query_imported_fast_impl in disabled_reasons

src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
This method is in a hot-path on our HA systems. It's vitally important to be as efficient and as quick as possible here. By calling `query_imported_fast_impl`, it removes a call to our process pool which is an efficiency and speed boost.
Original PR: https://github.com/truenas/middleware/pull/11998
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123825
=> NAS-123825 / 23.10 / call query_imported_fast_impl in disabled_reasons (by yocalebo)

src/middlewared/middlewared/plugins/nfs.py, src/middlewared/middlewared/validators.py
* NotMatch validator can avoid complicated regex when writing exclude patterns
* Added explanation of NFS share hostname validation to provide the user with a human readable message.
Original PR: https://github.com/truenas/middleware/pull/12001
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123830
=> NAS-123830 / 23.10 / Add NotMatch validator and NFS share validation explanation (by mgrimesix)

src/middlewared/middlewared/plugins/enclosure_/identification.py, src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_identification.py
This adds the ES60G2 enclosure mapping to the new enclosure code.
=> NAS-123748 / 24.04 / add ES60G2 to enclosure2 code

src/middlewared/middlewared/etc_files/syslogd.py
The default syslog-ng config file changed and our replacement logic stopped working for f_syslog3 and f_daemon.
Original PR: https://github.com/truenas/middleware/pull/11994
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123822
=> NAS-123822 / 23.10 / Fix syslog-ng config generation (by anodos325)

src/middlewared/middlewared/etc_files/syslogd.py
The default syslog-ng config file changed and our replacement logic stopped working for f_syslog3 and f_daemon.
Original PR: https://github.com/truenas/middleware/pull/11994
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123822
Original PR: https://github.com/truenas/middleware/pull/12007
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123822
=> NAS-123822 / 23.10-RC.1 / Fix syslog-ng config generation (by anodos325) (by bugclerk)

src/middlewared/middlewared/plugins/rsync.py, tests/api2/test_rsync_ssh_authentication.py
with SSH key in user home directory.
Add `ssh_keyscan` option to automatically run `ssh_keyscan` when setting up a rsync task with SSH key in user home directory.
=> NAS-123733 / 24.04 / Check for host keys in user home directory when setting up a rsync task

src/middlewared/middlewared/alert/source/smb.py
We perform path validation on creation and update of SMB shares, but there are a variety of ways users can put ZFS datasets within existing SMB shares that have unsupported or invalid configuraitons.
We should alert on this so that they have an opportunity to fix the configuration promptly before they file issue reports about invalid configurations.
=> NAS-123503 / 24.04 / Add alert misconfigured SMB paths

src/middlewared/middlewared/alert/source/smb.py
We perform path validation on creation and update of SMB shares, but there are a variety of ways users can put ZFS datasets within existing SMB shares that have unsupported or invalid configuraitons.
We should alert on this so that they have an opportunity to fix the configuration promptly before they file issue reports about invalid configurations.
Original PR: https://github.com/truenas/middleware/pull/12019
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123503
=> NAS-123503 / 23.10 / Add alert misconfigured SMB paths (by anodos325)

src/middlewared/middlewared/alert/source/smb.py
We perform path validation on creation and update of SMB shares, but there are a variety of ways users can put ZFS datasets within existing SMB shares that have unsupported or invalid configuraitons.
We should alert on this so that they have an opportunity to fix the configuration promptly before they file issue reports about invalid configurations.
Original PR: https://github.com/truenas/middleware/pull/12019
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123503
=> NAS-123503 / 22.12.4 / Add alert misconfigured SMB paths (by anodos325)

src/middlewared/middlewared/plugins/pool_/dataset.py, src/middlewared/middlewared/plugins/zfs_/zfs_events.py
This PR adds changes to only set create/update events of zfs datasets whenever changes are made via our API instead of relying on ZFS events because when for example replicating, numerous zfs create/set events are raised which result in us trying to engage the process pool to get all the data related to the dataset which can become expensive and results in blocking tasks in the process pool.
=> NAS-123609 / 24.04 / Send pool.dataset.query events whenever create/update methods on dataset service are called

src/middlewared/middlewared/plugins/pool_/dataset.py, src/middlewared/middlewared/plugins/zfs_/zfs_events.py
git cherry-pick -x 385a24c8ecfedc69d95bf3a33d5667830d21981d
git cherry-pick -x 4860d63da6f32595785d9637079ed40fbd59915f
This PR adds changes to only set create/update events of zfs datasets whenever changes are made via our API instead of relying on ZFS events because when for example replicating, numerous zfs create/set events are raised which result in us trying to engage the process pool to get all the data related to the dataset which can become expensive and results in blocking tasks in the process pool.
Original PR: https://github.com/truenas/middleware/pull/12027
Jira URL: …
=> NAS-123609 / 23.10 / Send pool.dataset.query events whenever create/update methods on dataset service are called (by sonicaj)

src/middlewared/middlewared/plugins/pool_/dataset.py, src/middlewared/middlewared/plugins/zfs_/zfs_events.py
git cherry-pick -x 385a24c8ecfedc69d95bf3a33d5667830d21981d
git cherry-pick -x 4860d63da6f32595785d9637079ed40fbd59915f
This PR adds changes to only set create/update events of zfs datasets whenever changes are made via our API instead of relying on ZFS events because when for example replicating, numerous zfs create/set events are raised which result in us trying to engage the process pool to get all the data related to the dataset which can become expensive and results in blocking tasks in the process pool.
Original PR: https://github.com/truenas/middleware/pull/12027
Jira URL: …
=> NAS-123609 / 23.10-RC.1 / Send pool.dataset.query events whenever create/update methods on dataset service are called (by sonicaj)

src/middlewared/middlewared/plugins/pool_/dataset.py
git cherry-pick -x 485036e26075af5796b75ee56914b7f53990a065
git cherry-pick -x 4717cbc4560a0a1e47acff5faf4bbff327f7a55a
Original PR: https://github.com/truenas/middleware/pull/12031
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123890
=> NAS-123890 / 23.10 / Fix event name when creating/updating dataset (by sonicaj)

src/middlewared/middlewared/plugins/pool_/dataset.py
git cherry-pick -x 485036e26075af5796b75ee56914b7f53990a065
git cherry-pick -x 4717cbc4560a0a1e47acff5faf4bbff327f7a55a
Original PR: https://github.com/truenas/middleware/pull/12031
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123890
=> NAS-123890 / 23.10-RC.1 / Fix event name when creating/updating dataset (by sonicaj)

src/middlewared/middlewared/plugins/enclosure_/enclosure2.py, src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py, src/middlewared/middlewared/plugins/enclosure_/identification.py, src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py, src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_identification.py
This adds `enclosure2.set_slot_status` to the new enclosure plugin. This code isn't called anywhere but has been tested on real hardware to ensure it doesn't crash. This also fixes a crash in `slot_mappings.py` that was occurring on m-series systems for the rear nvme enclosure mapping code.
=> NAS-123611 / 24.04 / add enclosure2.set_slot_status

src/middlewared/middlewared/plugins/pool_/dataset.py, src/middlewared/middlewared/plugins/pool_/dataset_recordsize.py, src/middlewared/middlewared/plugins/pool_/pool.py, src/middlewared/middlewared/plugins/pool_/utils.py, tests/api2/test_draid_record_and_block_size.py
A request was made to redefine default values and minimum values for recordsize/volblocksize attrs of a dataest/zvol for draid based pools.
=> NAS-123782 / 24.04 / Update default recordsize for draid pool based datasets/zvols

src/middlewared/middlewared/plugins/pool_/dataset.py, src/middlewared/middlewared/plugins/pool_/dataset_recordsize.py, src/middlewared/middlewared/plugins/pool_/pool.py, src/middlewared/middlewared/plugins/pool_/utils.py, tests/api2/test_draid_record_and_block_size.py
A request was made to redefine default values and minimum values for recordsize/volblocksize attrs of a dataest/zvol for draid based pools.
Original PR: https://github.com/truenas/middleware/pull/12026
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123782
=> NAS-123782 / 23.10 / Update default recordsize for draid pool based datasets/zvols (by Qubad786)

src/middlewared/middlewared/plugins/pool_/dataset.py, src/middlewared/middlewared/plugins/pool_/dataset_recordsize.py, src/middlewared/middlewared/plugins/pool_/pool.py, src/middlewared/middlewared/plugins/pool_/utils.py, tests/api2/test_draid_record_and_block_size.py
A request was made to redefine default values and minimum values for recordsize/volblocksize attrs of a dataest/zvol for draid based pools.
Original PR: https://github.com/truenas/middleware/pull/12026
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123782
=> NAS-123782 / 23.10-RC.1 / Update default recordsize for draid pool based datasets/zvols (by Qubad786)

src/middlewared/middlewared/plugins/usage.py
Quiet option for NFS exports was removed.
Original PR: https://github.com/truenas/middleware/pull/12051
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123968
=> NAS-123968 / 23.10 / Fix usage plugin (by anodos325)

src/middlewared/middlewared/plugins/usage.py
Quiet option for NFS exports was removed.
Original PR: https://github.com/truenas/middleware/pull/12051
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123968
=> NAS-123968 / 23.10-RC.1 / Fix usage plugin (by anodos325) (by bugclerk)

src/middlewared/middlewared/alert/source/license_status.py
On our M60 with 12x ES102 JBODs (with ~1.2k+ hard drives), I was noticing that `failover.get_ips` was taking > 46 seconds to return.
I gathered flame graphs of the running middleware process and noticed that `alert/license_status.py` line 81 (`enclosure.query`) was the spot where it was blocked. This doesn't surprise me because that's the old enclosure code that wasn't written in a way to be efficient. It's the exact opposite of efficient.
I changed to using `enclosure2.query` which is the new enclosure code that was written exclusively with speed/efficiency in mind and `failover.get_ips` now takes ~0.4 seconds to return.
The only logical conclusion that I can come up with is that our alert was calling such an inefficient method every 60 seconds that it was slowing down the entire main …
=> NAS-123981 / 24.04 / dramatically improve alert/license_status.py

src/middlewared/middlewared/alert/source/license_status.py, src/middlewared/middlewared/plugins/enclosure_/element_types.py, src/middlewared/middlewared/plugins/enclosure_/enclosure2.py, src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py, src/middlewared/middlewared/plugins/enclosure_/identification.py, src/middlewared/middlewared/plugins/enclosure_/map2.py, src/middlewared/middlewared/plugins/enclosure_/nvme2.py, src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py, src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_element_types.py, src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_identification.py, src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_slot_mappings.py, src/middlewared/middlewared/utils/scsi_generic.py
This backports the `enclosure2` logic to `stable/cobia` branch because the performance benefits are too great to not have. Furthermore, this code is isolated and written in a way where nothing actually depends on it. The risk for regression is basically 0.
Now that this has been backported, I can change `alert/license_status.py` to call `enclosure2.query` which gives us the performance benefits described in https://github.com/truenas/middleware/pull/12054.
The reason why this is being done is because we're seeing that it's taking 240seconds+ to "log in" on an HA system during certain scenarios. I saw this on an internal system and implemented the changes mentioned up above.
=> NAS-123938 / 23.10 / fix login on HA taking >4mins

src/middlewared/middlewared/pytest/unit/utils/test_mountinfo.py, src/middlewared/middlewared/utils/osc/linux/mount.py
This provides validated method of generating tree for checking whether unexpected filesystems or ZFS dataset parameters are mounted under a given path. Example of how one would do this would be:
getmnttree(os.lstat('/mnt/dozer/SHARE').st_dev)
=> NAS-123960 / 24.04 / Add ability to convert mountinfo to tree

src/middlewared/middlewared/plugins/smb.py
This uses a somewhat more efficient way of selecting only mounted filesystems that have the SMB share as a parent. More importantly, the method is standard and has CI coverage.
=> NAS-123997 / 24.04 / Refactor SMB mountinfo validation to use getmnttree

src/middlewared/middlewared/plugins/disk_/availability.py
On an internal system, we have a drive that has failed in a "fun" way. The drive was reporting as being spun down which resulted in the size of the disk to be reported as 0 by the OS. The problem is that the front-end code depends on size being a valid number and if it isn't, the entire zpool creation wizard breaks and the user is unable to create a zpool.
This makes it so that `disk.get_unused` doesn't return drives that don't report a size.
=> NAS-123948 / 24.04 / fix webUI zpool creation page

src/middlewared/middlewared/plugins/disk_/availability.py
On an internal system, we have a drive that has failed in a "fun" way. The drive was reporting as being spun down which resulted in the size of the disk to be reported as 0 by the OS. The problem is that the front-end code depends on size being a valid number and if it isn't, the entire zpool creation wizard breaks and the user is unable to create a zpool.
This makes it so that `disk.get_unused` doesn't return drives that don't report a size.
Original PR: https://github.com/truenas/middleware/pull/12063
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123948
=> NAS-123948 / 23.10 / fix webUI zpool creation page (by yocalebo)

src/middlewared/middlewared/plugins/system/coredump.py
This commit adds changes to safely retrieve coredump exe attr because we are seeing it not being present in our integration tests.
```
[2023/09/07 03:32:17] (WARNING) SystemService.coredumps():32 - Failed to obtain coredump information
File "/usr/lib/python3/dist-packages/middlewared/plugins/system/coredump.py", line 24, in coredumps
'exe': core['COREDUMP_EXE'],
~~~~^^^^^^^^^^^^^^^^
KeyError: 'COREDUMP_EXE'
[2023/09/07 03:32:17] (DEBUG) mid
```
=> NAS-124012 / 24.04 / Safely retrieve coredump exe attr

src/middlewared/middlewared/plugins/system/coredump.py
This commit adds changes to safely retrieve coredump exe attr because we are seeing it not being present in our integration tests.
```
[2023/09/07 03:32:17] (WARNING) SystemService.coredumps():32 - Failed to obtain coredump information
File "/usr/lib/python3/dist-packages/middlewared/plugins/system/coredump.py", line 24, in coredumps
'exe': core['COREDUMP_EXE'],
~~~~^^^^^^^^^^^^^^^^
KeyError: 'COREDUMP_EXE'
[2023/09/07 03:32:17] (DEBUG) mid
```
Original PR: https://github.com/truenas/middleware/pull/12067
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124012
=> NAS-124012 / 23.10-RC.1 / Safely retrieve coredump exe attr (by sonicaj)

src/middlewared/middlewared/plugins/tdb/base.py, src/middlewared/middlewared/plugins/tdb/wrapper.py, src/middlewared/middlewared/plugins/zfs_/utils.py
A user presented an unreproducible issue in which attempted batch operations on a TDB handle failed with TDB_ERR_LOCK when trying to obtain a transaction lock.
Since no additional collateral or steps to reproduce were provided it's unclear whether these changes would fix the underlying issue that was reported. This PR tries to minimize impact of libary errors by closing the handle (thereby releasing locks held by the current process) on RuntimeError. The library error will be passed on to the caller, but subsequent calls will have a new handle on the file and presumably not encounter the issue.
=> NAS-124009 / 24.04 / Add some handling for RuntimeError in tdb library

src/middlewared/middlewared/plugins/tdb/base.py, src/middlewared/middlewared/plugins/tdb/wrapper.py, src/middlewared/middlewared/plugins/zfs_/utils.py
A user presented an unreproducible issue in which attempted batch operations on a TDB handle failed with TDB_ERR_LOCK when trying to obtain a transaction lock.
Since no additional collateral or steps to reproduce were provided it's unclear whether these changes would fix the underlying issue that was reported. This PR tries to minimize impact of libary errors by closing the handle (thereby releasing locks held by the current process) on RuntimeError. The library error will be passed on to the caller, but subsequent calls will have a new handle on the file and presumably not encounter the issue.
Original PR: https://github.com/truenas/middleware/pull/12066
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124009
=> NAS-124009 / 23.10 / Add some handling for RuntimeError in tdb library (by anodos325)

src/middlewared/middlewared/plugins/tdb/base.py, src/middlewared/middlewared/plugins/tdb/wrapper.py, src/middlewared/middlewared/plugins/zfs_/utils.py
A user presented an unreproducible issue in which attempted batch operations on a TDB handle failed with TDB_ERR_LOCK when trying to obtain a transaction lock.
Since no additional collateral or steps to reproduce were provided it's unclear whether these changes would fix the underlying issue that was reported. This PR tries to minimize impact of libary errors by closing the handle (thereby releasing locks held by the current process) on RuntimeError. The library error will be passed on to the caller, but subsequent calls will have a new handle on the file and presumably not encounter the issue.
Original PR: https://github.com/truenas/middleware/pull/12066
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124009
=> NAS-124009 / 23.10-RC.1 / Add some handling for RuntimeError in tdb library (by anodos325)

src/freenas/etc/systemd/system/tmp.mount
This is generally good practice and required per STIG on some Linux distros.
=> NAS-124054 / 24.04 / Mount /tmp filesystem noexec

src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
This commit adds changes to mark chart.release create/update method values as private because they can contain potentially sensitive information like passwords etc for the app. We cannot be fine grained about it at this point because we don't have the app schema at this point when schema is called/validated, so we mark the values as private.
=> NAS-124029 / 24.04 / Mark chart.release create/update method values as private

src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
This commit adds changes to mark chart.release create/update method values as private because they can contain potentially sensitive information like passwords etc for the app. We cannot be fine grained about it at this point because we don't have the app schema at this point when schema is called/validated, so we mark the values as private.
Original PR: https://github.com/truenas/middleware/pull/12080
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124029
=> NAS-124029 / 23.10 / Mark chart.release create/update method values as private (by sonicaj)

src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
This commit adds changes to mark chart.release create/update method values as private because they can contain potentially sensitive information like passwords etc for the app. We cannot be fine grained about it at this point because we don't have the app schema at this point when schema is called/validated, so we mark the values as private.
Original PR: https://github.com/truenas/middleware/pull/12080
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124029
Original PR: https://github.com/truenas/middleware/pull/12081
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124029
=> NAS-124029 / 22.12.4 / Mark chart.release create/update method values as private (by sonicaj) (by bugclerk)

src/middlewared/middlewared/plugins/pool_/dataset_encryption_lock.py, tests/api2/test_dataset_unlock_validation.py
This commit adds changes to not raise a validation error if a dataset is specified explicitly in the list which is already unlocked. We are not erroring out here because it should be fine as rest of the implementation is not concerned about it being unlocked already and a consumer to be on the safe side can just specify whichever datasets he wants unlocked rather then checking first and only specifying locked ones.
=> NAS-124017 / 24.04 / Safely validate unlocked datasets

src/middlewared/middlewared/plugins/pool_/dataset_encryption_lock.py, tests/api2/test_dataset_unlock_validation.py
This commit adds changes to not raise a validation error if a dataset is specified explicitly in the list which is already unlocked. We are not erroring out here because it should be fine as rest of the implementation is not concerned about it being unlocked already and a consumer to be on the safe side can just specify whichever datasets he wants unlocked rather then checking first and only specifying locked ones.
Original PR: https://github.com/truenas/middleware/pull/12076
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124017
=> NAS-124017 / 23.10 / Safely validate unlocked datasets (by sonicaj)

src/middlewared/middlewared/plugins/pool_/dataset_encryption_lock.py, tests/api2/test_dataset_unlock_validation.py
This commit adds changes to not raise a validation error if a dataset is specified explicitly in the list which is already unlocked. We are not erroring out here because it should be fine as rest of the implementation is not concerned about it being unlocked already and a consumer to be on the safe side can just specify whichever datasets he wants unlocked rather then checking first and only specifying locked ones.
Original PR: https://github.com/truenas/middleware/pull/12076
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124017
=> NAS-124017 / 23.10-RC.1 / Safely validate unlocked datasets (by sonicaj)

src/middlewared/middlewared/plugins/failover_/internal_interface.py
The fseries platform uses the AMD ntb driver. This driver behaves differently than the intel NTB driver in that the B controller is active and the A controller reboots, the `ntb0` interface is removed from the B controller. When this happens, any traffic on the 169.254.10/24 subnet will be forwarded to the default gateway. We don't want to do this so we add a RTN_BLACKHOLE route for 169.254.10.0/23. This route is 1 bit larger than the subnet we put on the interface so it will only take effect when the B controller is active and the `ntb0` interface is removed from the OS.
=> NAS-123905 / 24.04 / add blackhole route for heartbeat iface on HA

src/freenas/usr/lib/netdata/python.d/k3s_stats.chart.py
In a fresh setup where Kubernetes has not been previously configured, an error occurs due to missing files. Specifically, the error is related to the absence of certain k3s configuration files in the Netdata k3s_stats plugin.
Safely handle/accommodate the case where the configuration file is not present when apps are not configured so as to avoid spamming netdata logs.
=> NAS-123969 / 24.04 / Handle file not found error in kubernetes stats

src/middlewared/middlewared/test/integration/utils/mock_binary.py
The middleware test utility to mock binaries requires read-write access to /usr. This adds simple utility function to toggle the property for duration of the mocked binary's context. This is so that we can ensure that the other tests occur within regular designed parameters.
=> NAS-124108 / 24.04 / Toggle zfs readonly on /usr during binary mock

src/middlewared/middlewared/plugins/device_/device_info.py, src/middlewared/middlewared/plugins/reporting/events.py, tests/api2/test_device_get_disk_names.py
I generated a flame graph of the main middleware process on an internal system with ~1.2k disks. The flame graph included 40,293 samples. Of those samples, 27,837 (69.09%) of them were spent on line 85 in the `reporting/events.py` script.
After looking at line 85, I realized that we're casting the dictionary to a list which just pulls out the keys of the dictionary. The keys of the dictionary from `device.get_disks` are simply block device names for the disks on the system. This is too expensive to call just to get the names of the disks so I added a new function `device.get_disk_names`.
The function that I've added is ~150% faster than the old method. The returned output is the exact same.
=> NAS-124118 / 24.04 / optimize reporting/events.py

src/middlewared/middlewared/plugins/device_/device_info.py, src/middlewared/middlewared/plugins/reporting/events.py, tests/api2/test_device_get_disk_names.py
I generated a flame graph of the main middleware process on an internal system with ~1.2k disks. The flame graph included 40,293 samples. Of those samples, 27,837 (69.09%) of them were spent on line 85 in the `reporting/events.py` script.
After looking at line 85, I realized that we're casting the dictionary to a list which just pulls out the keys of the dictionary. The keys of the dictionary from `device.get_disks` are simply block device names for the disks on the system. This is too expensive to call just to get the names of the disks so I added a new function `device.get_disk_names`.
The function that I've added is ~150% faster than the old method. The returned output is the exact same.
Original PR: https://github.com/truenas/middleware/pull/12103
Jira URL: …
=> NAS-124118 / 23.10 / optimize reporting/events.py (by yocalebo)

src/middlewared/middlewared/plugins/pool_/pool.py
Symlinks in `/dev/disk/by-partuuid` don't get populated on the standby controller on failover unless on fresh boot OR the active controller tells the standby to "retaste" the disks.
We were retesting the disks on pool create, but we were not doing it on pool update. This means, for example, if a new vdev was added on active controller and a failover occurred after. The standby would fail to import the pool because sysfs would not have the proper symlinks in place. This fixes it so that any pool.create/update operation triggers a retasting of the disks on the standby controller.
=> NAS-124087 / 24.04 / retaste disks on standby on any pool create/delete op

src/middlewared/middlewared/plugins/pool_/pool.py
Symlinks in `/dev/disk/by-partuuid` don't get populated on the standby controller on failover unless on fresh boot OR the active controller tells the standby to "retaste" the disks.
We were retesting the disks on pool create, but we were not doing it on pool update. This means, for example, if a new vdev was added on active controller and a failover occurred after. The standby would fail to import the pool because sysfs would not have the proper symlinks in place. This fixes it so that any pool.create/update operation triggers a retasting of the disks on the standby controller.
Original PR: https://github.com/truenas/middleware/pull/12105
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124087
=> NAS-124087 / 23.10 / retaste disks on standby on any pool create/delete op (by yocalebo)
