src/middlewared/middlewared/plugins/pool_/pool.py

Symlinks in `/dev/disk/by-partuuid` don't get populated on the standby controller on failover unless on fresh boot OR the active controller tells the standby to "retaste" the disks.
We were retesting the disks on pool create, but we were not doing it on pool update. This means, for example, if a new vdev was added on active controller and a failover occurred after. The standby would fail to import the pool because sysfs would not have the proper symlinks in place. This fixes it so that any pool.create/update operation triggers a retasting of the disks on the standby controller.
Original PR: https://github.com/truenas/middleware/pull/12105
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124087

NAS-124087 / 23.10-RC.1 / retaste disks on standby on any pool create/delete op (by yocalebo)

---

tests/api2/test_420_smb.py

This is an initial step to improving the SMB API tests. Many of the removed items have been superseded by more explicit / better testing.
Original PR: https://github.com/truenas/middleware/pull/12102
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124096

NAS-124096 / 22.12.4 / Remove legacy / problematic SMB tests (by anodos325)

---

src/middlewared/middlewared/plugins/account.py

When using the webUI to create a new user and choosing to create the home directory, if you choose `/mnt` an error message gets raised stating `Home Directory must begin with /mnt/ ...`. This really confused me because I clearly had chosen `/mnt`. The issue is that we're checking for a literal `/mnt/` so the validation error is misleading.
To remedy this and keep the same short-circuits in place, change the `startswith(` check to just `/mnt` to catch the obvious errors. Add another short-circuit branch to check to see if the home directory is a literal `/mnt` or `/mnt/` and raise a proper validation error message as well.

NAS-124126 / 24.04 / raise better validation error on improper home dir

---

src/middlewared/middlewared/plugins/account.py

When using the webUI to create a new user and choosing to create the home directory, if you choose `/mnt` an error message gets raised stating `Home Directory must begin with /mnt/ ...`. This really confused me because I clearly had chosen `/mnt`. The issue is that we're checking for a literal `/mnt/` so the validation error is misleading.
To remedy this and keep the same short-circuits in place, change the `startswith(` check to just `/mnt` to catch the obvious errors. Add another short-circuit branch to check to see if the home directory is a literal `/mnt` or `/mnt/` and raise a proper validation error message as well.
Original PR: https://github.com/truenas/middleware/pull/12115
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124126

NAS-124126 / 23.10 / raise better validation error on improper home dir (by yocalebo)

---

tests/api2/test_system_general_ui_allowlist.py

We used expect GET /vm/display to return 403 when Web UI access is restricted. It does not return it anymore because this URL is not served by nginx (we now have individual rules per-vm). That's why we are now probing /vm/display/1 (and we mock the VM to have this rule in nginx configuration)
Original PR: https://github.com/truenas/middleware/pull/12122
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124155

NAS-124155 / 23.10 / Adapt `test_system_general_ui_allowlist` to VM changes (by themylogin)

---

src/middlewared/middlewared/alembic/versions/24.04/2023-09-07_19-50_add_exporting_table_for_reporting.py
src/middlewared/middlewared/etc_files/netdata/exporting.conf.mako
src/middlewared/middlewared/plugins/etc.py
src/middlewared/middlewared/plugins/reporting/export.py
src/middlewared/middlewared/plugins/reporting/exporters/base.py
src/middlewared/middlewared/plugins/reporting/exporters/factory.py
src/middlewared/middlewared/plugins/reporting/exporters/graphite.py
src/middlewared/middlewared/plugins/reporting/update.py

It was requested that we add ability to export reporting data to graphite similar to what we used to do before and while we are doing this also make sure the approach is implementation agnostic so we can add more relevant export types as well.
Here changes have been made to the reporting system to ensure that the configuration aligns with the use of Netdata for reporting. Specifically, the reporting system is updated to support Netdata's metrics export to Graphite, as Collectd is no longer used. This involves creating a new endpoint within the reporting system, such as `reporting.exporters`, which exposes methods for creating, deleting, and updating Netdata export configurations.
The following parameters should be specified to enable Graphite as the reporting destination for Netdata:
1. …

NAS-123668 / 24.04 / Enable exporting reporting data to graphite

---

src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
src/middlewared/middlewared/plugins/network.py

The fseries platform will add a usb ethernet device when ikvm console is opened up. That's horrible design imo but the fact is that we have to deal with it. This 2 things.
1. on the fseries platform, if a nic has a bus attribute of `usb` then skip it so it doesn't show up in `interface.query` preventing the end-user from using our webUI/API to configure said device
2. stop logging the interface name in the devd hook when an interface is attached and that interface doesn't exist in the database. It's confusing an unnecessary to pollute our logs with messages like these.

NAS-124190 / 24.04 / mask ipmi usb ethernet on fseries platform

---

tests/api2/test_425_smb_protocol.py

Silence this warning:
```
api2/test_425_smb_protocol.py:712
/root/jenkins/workspace/TrueNAS_SCALE_-_Cobia/HA_API_Tests_-_TrueNAS_SCALE_Cobia_Nightly/middleware/tests/api2/test_425_smb_protocol.py:712: DeprecationWarning: invalid escape sequence \{
with smb_share(f'EXTERNAL:{ip}\{SMB_NAME}', {'name': 'EXTERNAL'}):
```
Also rectify a missing definition of `cmd` on an assertion failure, and fix misc flake8 items.

NAS-124194 / 24.04 / Silence a DeprecationWarning: invalid escape sequence warning, etc

---

src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
src/middlewared/middlewared/plugins/network.py

The fseries platform will add a usb ethernet device when ikvm console is opened up. That's horrible design imo but the fact is that we have to deal with it. This 2 things.
1. on the fseries platform, if a nic has a bus attribute of `usb` then skip it so it doesn't show up in `interface.query` preventing the end-user from using our webUI/API to configure said device
2. stop logging the interface name in the devd hook when an interface is attached and that interface doesn't exist in the database. It's confusing an unnecessary to pollute our logs with messages like these.
Original PR: https://github.com/truenas/middleware/pull/12133
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124190

NAS-124190 / 23.10 / mask ipmi usb ethernet on fseries platform (by yocalebo)

---

src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py

NAS-124244 / 24.04 / add new NVDIMM info to mseries.nvdimm plugin

---

src/middlewared/middlewared/plugins/hardware_/m_series_nvdimm.py

Original PR: https://github.com/truenas/middleware/pull/12143
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124244

NAS-124244 / 13.0 / add new NVDIMM info to mseries.nvdimm plugin (by yocalebo)

---

src/middlewared/middlewared/plugins/hardware_/m_series_nvdimm.py

Original PR: https://github.com/truenas/middleware/pull/12143
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124244

NAS-124244 / 13.1 / add new NVDIMM info to mseries.nvdimm plugin (by yocalebo)

---

src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py

Original PR: https://github.com/truenas/middleware/pull/12143
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124244

NAS-124244 / 23.10 / add new NVDIMM info to mseries.nvdimm plugin (by yocalebo)

---

src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py

Original PR: https://github.com/truenas/middleware/pull/12143
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124244
Original PR: https://github.com/truenas/middleware/pull/12146
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124244

NAS-124244 / 22.12.4 / add new NVDIMM info to mseries.nvdimm plugin (by yocalebo) (by bugclerk)

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/enclosure_class.py
src/middlewared/middlewared/utils/license.py

This was missed when originally adding the ES102S enclosure platform to SCALE.

NAS-122711 / 13.1 / add ES102S to CORE

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/enclosure_class.py
src/middlewared/middlewared/utils/license.py

This was missed when originally adding the ES102S enclosure platform to SCALE.
Original PR: https://github.com/truenas/middleware/pull/12149
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122711

NAS-122711 / 13.0 / add ES102S to CORE (by yocalebo)

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/enclosure_class.py
src/middlewared/middlewared/utils/license.py

This was missed when originally adding the ES60G2 enclosure platform to SCALE.

NAS-123286 / 13.1 / add ES60G2 to CORE

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/enclosure_class.py
src/middlewared/middlewared/utils/license.py

This was missed when originally adding the ES60G2 enclosure platform to SCALE.
Original PR: https://github.com/truenas/middleware/pull/12151
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123286

NAS-123286 / 13.0 / add ES60G2 to CORE (by yocalebo)

---

src/middlewared/middlewared/plugins/ldap.py
tests/api2/test_278_freeipa.py

* Updated plugins/ldap.py to include netgroups for FreeIPA
* Updated test_278_freeipa.py 
- Small amount of refactoring
- Added test for config settings
- Added forward and reverse DNS test
- Added test for retrieving netgroups

NAS-124184 / 24.04 / Add support for FreeIPA netgroups

---

src/middlewared/middlewared/plugins/pool_/dataset_encryption_info.py
tests/api2/test_dataset_encryption_keys_in_replication.py

This PR adds changes so that we account for source datasets which are not encrypted root themselves and we retrieve their encryption keys properly so that they can be downloaded from the UI and used on the target system after replication has completed to properly unlock target datasets.

NAS-124052 / 24.04 / Account for source datasets which are not encryption root themselves when retrieving encrypted keys

---

src/middlewared/middlewared/plugins/enclosure_/map.py
src/middlewared/middlewared/plugins/enclosure_/nvme.py

There are 2 problems being fixed.
1. this is crashing with `KeyError` on platforms that have rear nvme drive bays (R50 variants). It's crashing because the nvme mapping logic is missing a top-level `bsg` key. Add a top-level `bsg` key to the nvme mapping plugin.
2. On the R50 platforms, we were using `controller_enclosures[0]` always so that means all 48 drives got mapped to the first expander in the head-unit. The R50 variants have 2 expanders in the head-unit. 1-24 and 25-48.
Without these changes, it's impossible to use the webUI/API to create zpools since `enclosure.query` is called somewhere in the code-path.

NAS-124207 / 24.04 / fix enclosure mapping for platforms with nvme

---

src/middlewared/middlewared/plugins/enclosure_/map.py
src/middlewared/middlewared/plugins/enclosure_/nvme.py

There are 2 problems being fixed.
1. this is crashing with `KeyError` on platforms that have rear nvme drive bays (R50 variants). It's crashing because the nvme mapping logic is missing a top-level `bsg` key. Add a top-level `bsg` key to the nvme mapping plugin.
2. On the R50 platforms, we were using `controller_enclosures[0]` always so that means all 48 drives got mapped to the first expander in the head-unit. The R50 variants have 2 expanders in the head-unit. 1-24 and 25-48.
Without these changes, it's impossible to use the webUI/API to create zpools since `enclosure.query` is called somewhere in the code-path.
Original PR: https://github.com/truenas/middleware/pull/12160
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124207

NAS-124207 / 23.10 / fix enclosure mapping for platforms with nvme (by yocalebo)

---

src/middlewared/middlewared/plugins/reporting/graphs.py
src/middlewared/middlewared/plugins/reporting/update.py

**Observation:**
Reporting includes a number of query/get commands that are not formatted or functional to view in the CLI. 
**Applied Change:**
Made the graphs related system reporting commands private to CLI

NAS-124086 / 24.04 / Hide system reporting queries commands in SCALE CLI

---

src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/failover_/remote.py

Literally, every other plugin in `failover_` is marked as `private=True`. This is the CRUD endpoint for the failover related api endpoints but there is no reason to provide those to midcli so this marks it as cli_private = True to prevent the endpoints from showing up in midcli program.

NAS-124264 / 24.04 / hide failover CRUD from midcli

---

src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/failover_/remote.py

Literally, every other plugin in `failover_` is marked as `private=True`. This is the CRUD endpoint for the failover related api endpoints but there is no reason to provide those to midcli so this marks it as cli_private = True to prevent the endpoints from showing up in midcli program.
Original PR: https://github.com/truenas/middleware/pull/12161
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124264

NAS-124264 / 23.10 / hide failover CRUD from midcli (by yocalebo)

---

src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/failover_/remote.py

Literally, every other plugin in `failover_` is marked as `private=True`. This is the CRUD endpoint for the failover related api endpoints but there is no reason to provide those to midcli so this marks it as cli_private = True to prevent the endpoints from showing up in midcli program.
Original PR: https://github.com/truenas/middleware/pull/12161
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124264

NAS-124264 / 22.12.4 / hide failover CRUD from midcli (by yocalebo)

---

src/middlewared/middlewared/plugins/reporting/graphs.py
src/middlewared/middlewared/plugins/reporting/update.py

git cherry-pick -x c5820ea6578055a69e6b06b906128c1bd03d3515
git cherry-pick -x 72ba33d2d3dce18b8537e04c056198e261f71a94
**Observation:**
Reporting includes a number of query/get commands that are not formatted or functional to view in the CLI. 
**Applied Change:**
Made the graphs related system reporting commands private to CLI
Original PR: https://github.com/truenas/middleware/pull/12153
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124086

NAS-124086 / 23.10 / Hide system reporting queries commands in SCALE CLI (by Qubad786)

---

src/middlewared/middlewared/plugins/cluster_linux/management.py
src/middlewared/middlewared/pytest/unit/test_schema.py

This implements equivalent of cli_validate_volname from glusterfs so that we can give useful validation error before submitting the volume payload and having glustercli fail.
Original PR: https://github.com/truenas/middleware/pull/12155
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124289

NAS-124289 / 23.10 / Add validation for gluster volume name (by anodos325)

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

We force replica=3 to ensure that user always has replica count that avoids split-brain scenarios.

NAS-124310 / 24.04 / Clarify replica node count

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

We force replica=3 to ensure that user always has replica count that avoids split-brain scenarios.
Original PR: https://github.com/truenas/middleware/pull/12172
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124310

NAS-124310 / 23.10 / Clarify replica node count (by anodos325)

---

src/middlewared/middlewared/plugins/smb_/passdb.py
src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py

It's theoretically for users to end up with passdb.tdb containing invalid information due to past configuration mishaps. This adds handling for two cases:
1) totally broken passdb file
2) passdb file with users that have an incorrect `domain` populated.
In both cases remedy is same, nuke the file and redo.

NAS-124317 / 24.04 / Add more error handling for invalid passdb entries

---

src/middlewared/middlewared/plugins/gluster_linux/volume.py

kwargs were being passed incorrectly to the glustercli method resulting in volume-wide stats being omitted from volume entries.

NAS-124321 / 24.04 / Fix gluster.volume.query results

---

src/middlewared/middlewared/plugins/gluster_linux/volume.py

kwargs were being passed incorrectly to the glustercli method resulting in volume-wide stats being omitted from volume entries.
Original PR: https://github.com/truenas/middleware/pull/12182
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124321

NAS-124321 / 23.10 / Fix gluster.volume.query results (by anodos325)

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

A typo in credential setup broke authentication call for the remote node connection in add_node API.

NAS-124326 / 24.04 / Fix API key based authentication cluster management

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

A typo in credential setup broke authentication call for the remote node connection in add_node API.
Original PR: https://github.com/truenas/middleware/pull/12184
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124326

NAS-124326 / 23.10 / Fix API key based authentication cluster management (by anodos325)

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

The add_nodes API has a non-default option to skip creating a gluster brick on the node being added to the cluster. There are some cases where we may want to add a node to the cluster without actually expanding the gluster volume onto it.

NAS-124327 / 24.04 / Fix crash in cluster.management.add_nodes

---

src/middlewared/middlewared/plugins/reporting/cpu_temperatures.py
src/middlewared/middlewared/plugins/reporting/events.py

**Motivation:**
The UI necessitates a flag to indicate the availability of cpu temperature data.
**Change:**
This PR addresses the requirement by setting the `cpu_temperatures_retrieved` flag to True when temperature values are available for machine.

NAS-124312 / 24.04 / Add flag outlining if cpu temperatures are being retrieved

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

The add_nodes API has a non-default option to skip creating a gluster brick on the node being added to the cluster. There are some cases where we may want to add a node to the cluster without actually expanding the gluster volume onto it.
Original PR: https://github.com/truenas/middleware/pull/12185
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124327

NAS-124327 / 23.10 / Fix crash in cluster.management.add_nodes (by anodos325)

---

src/middlewared/middlewared/plugins/smb_/passdb.py
src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py

It's theoretically for users to end up with passdb.tdb containing invalid information due to past configuration mishaps. This adds handling for two cases:
1) totally broken passdb file
2) passdb file with users that have an incorrect `domain` populated.
In both cases remedy is same, nuke the file and redo.
Original PR: https://github.com/truenas/middleware/pull/12177
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124317

NAS-124317 / 23.10 / Add more error handling for invalid passdb entries (by anodos325)

---

src/middlewared/middlewared/etc_files/local/avahi/avahi_services.py
src/middlewared/middlewared/plugins/service_/services/cifs.py
src/middlewared/middlewared/plugins/smb.py
tests/api2/assets/websocket/server.py
tests/api2/assets/websocket/service.py
tests/api2/test_200_ftp.py
tests/api2/test_310_service_announcement.py
tests/requirements.txt

This PR is predominately to add some _basic_ unit tests wrt mDNS service announcement.  More may be added at a later date.
It includes one to check announcements following a reboot, but this is currently turned off (being perhaps too heavyweight for everyday use).
The python [`zeroconf`](https://pypi.org/project/zeroconf/) package is used to discover announcements from the TrueNAS under test.

NAS-118579 / 24.04 / avahi-daemon is not announcing services

---

src/middlewared/middlewared/etc_files/local/avahi/avahi_services.py
src/middlewared/middlewared/plugins/service_/services/cifs.py
src/middlewared/middlewared/plugins/smb.py
tests/api2/assets/websocket/server.py
tests/api2/assets/websocket/service.py
tests/api2/test_200_ftp.py
tests/api2/test_310_service_announcement.py
tests/requirements.txt

This PR is predominately to add some _basic_ unit tests wrt mDNS service announcement.  More may be added at a later date.
It includes one to check announcements following a reboot, but this is currently turned off (being perhaps too heavyweight for everyday use).
The python [`zeroconf`](https://pypi.org/project/zeroconf/) package is used to discover announcements from the TrueNAS under test.
Original PR: https://github.com/truenas/middleware/pull/12022
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118579

NAS-118579 / 23.10 / avahi-daemon is not announcing services (by bmeagherix)

---

tests/api2/test_replication_utils.py

This was removed from master as a small part of https://github.com/truenas/middleware/pull/12117 , which was **NOT** backported to Cobia.
The subsequent https://github.com/truenas/middleware/pull/12158 which **was** backported to Cobia (https://github.com/truenas/middleware/pull/12163), therefore was missing the changes to this file.
Obviously this PR represents _one_ means of resolving the discrepancy.  Backporting https://github.com/truenas/middleware/pull/12117 would be another.

Remove dev_test

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

This just provides basic API endpoint for cluster node replacement so that in the future we can decide whether to finalize the feature and also indicate to API consumers that this feature is not baked.

NAS-124346 / 24.04 / Add cluster.management.replace_node stub

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

This just provides basic API endpoint for cluster node replacement so that in the future we can decide whether to finalize the feature and also indicate to API consumers that this feature is not baked.
Original PR: https://github.com/truenas/middleware/pull/12198
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124346

NAS-124346 / 23.10 / Add cluster.management.replace_node stub (by anodos325)

---

src/middlewared/middlewared/plugins/account_/2fa.py

This commit adds changes to include username in provisioning uri so that it is better readable in the authenticator app as to which user the uri belongs to.

NAS-124295 / 24.04 / Use username in provisioning uri

---

src/middlewared/middlewared/plugins/account_/2fa.py

This commit adds changes to include username in provisioning uri so that it is better readable in the authenticator app as to which user the uri belongs to.
Original PR: https://github.com/truenas/middleware/pull/12164
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124295

NAS-124295 / 23.10 / Use username in provisioning uri (by sonicaj)

---

src/middlewared/middlewared/plugins/nfs.py
tests/api2/test_300_nfs.py

Some refactoring
- Eliminate redundant host test
- Added function dedicated to overlap network testing
- Made sure all 'network' entries were in 'ip_network' format (required by the overlap test)
- Enhanced support for IPv6
- Cleaned up error reporting
- Network tests: Expanded tests and included IPv6
- Host tests: Added IPv6 and moved some tests from subtree to here
- Subtree share tests:  IPv6 and tests specific to NAS-124269

NAS-124269 / 24.04 / Fix detection and reporting of network overlap

---

src/middlewared/middlewared/plugins/iscsi_/iscsi_global.py

This is not valid for SCALE as currently fibrechannel is not supported.

No longer shortcut alua_enabled when license contains FIBRECHANNEL

---

src/middlewared/middlewared/plugins/nfs.py
tests/api2/test_300_nfs.py

Some refactoring
- Eliminate redundant host test
- Added function dedicated to overlap network testing
- Made sure all 'network' entries were in 'ip_network' format (required by the overlap test)
- Enhanced support for IPv6
- Cleaned up error reporting
- Network tests: Expanded tests and included IPv6
- Host tests: Added IPv6 and moved some tests from subtree to here
- Subtree share tests:  IPv6 and tests specific to NAS-124269
Original PR: https://github.com/truenas/middleware/pull/12206
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124269

NAS-124269 / 23.10 / Fix detection and reporting of network overlap (by mgrimesix)

---

src/middlewared/middlewared/plugins/iscsi_/iscsi_global.py

git cherry-pick -x b894ccf21c81b65420dafef07c206c5a6e056ac9
git cherry-pick -x 433cd09fa4aba2ae0fb5a98483e01ec8a717ae74
This is not valid for SCALE as currently fibrechannel is not supported.
Original PR: https://github.com/truenas/middleware/pull/12209
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124377

NAS-124377 / 23.10 / No longer shortcut alua_enabled when license contains FIBRECHANNEL (by bmeagherix)

---

src/middlewared/middlewared/plugins/iscsi_/iscsi_global.py

git cherry-pick -x b894ccf21c81b65420dafef07c206c5a6e056ac9
git cherry-pick -x 433cd09fa4aba2ae0fb5a98483e01ec8a717ae74
This is not valid for SCALE as currently fibrechannel is not supported.
Original PR: https://github.com/truenas/middleware/pull/12209
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124377

NAS-124377 / 22.12.4 / No longer shortcut alua_enabled when license contains FIBRECHANNEL (by bmeagherix)

---

src/middlewared/middlewared/plugins/vm/vms.py

This commit adds changes for UI to be able to see if a display device is available for a VM. Consumer can use following call to retrieve this information:
```
midclt call vm.query | jq .
```

NAS-124348 / 24.04 / Add flag showing if a display device is available for a VM

---

src/middlewared/middlewared/plugins/vm/vms.py

This commit adds changes for UI to be able to see if a display device is available for a VM. Consumer can use following call to retrieve this information:
```
midclt call vm.query | jq .
```
Original PR: https://github.com/truenas/middleware/pull/12200
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124348

NAS-124348 / 23.10 / Add flag showing if a display device is available for a VM (by sonicaj)

---

tests/api2/test_certs.py

This commit adds a fix where pytest was dumping entire certificate during execution as it is a parameter but then all of this is an unnecessary noise and has subsequently been fixed.

NAS-124361 / 24.04 / Define ids when running cert tests

---

tests/api2/test_certs.py

This commit adds a fix where pytest was dumping entire certificate during execution as it is a parameter but then all of this is an unnecessary noise and has subsequently been fixed.
Original PR: https://github.com/truenas/middleware/pull/12216
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124361

NAS-124361 / 23.10 / Define ids when running cert tests (by sonicaj)

---

src/middlewared/middlewared/plugins/reporting/graphs.py
src/middlewared/middlewared/plugins/reporting/netdata/client.py
src/middlewared/middlewared/plugins/reporting/netdata/connector.py
src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
src/middlewared/middlewared/plugins/reporting/utils.py

The Netdata graph export function currently generates a substantial number of API calls, resulting in a high volume of open file descriptors and extended processing time.
To address this issue, modifications have been implemented in the Netdata API code to support multiple calls. This enhancement has led to a reduction improvement in processing time by approximately 10 seconds during graph exports involving 1200 disks.
This also resolves the file descriptors issue we were seeing where we ran out of them - solution to address this has been to use a connection pool instead of making separate requests.

NAS-124128 / 24.04 / Improve performance for netdata retrieving graphs data

---

src/middlewared/middlewared/plugins/reporting/graphs.py
src/middlewared/middlewared/plugins/reporting/netdata/client.py
src/middlewared/middlewared/plugins/reporting/netdata/connector.py
src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
src/middlewared/middlewared/plugins/reporting/utils.py

The Netdata graph export function currently generates a substantial number of API calls, resulting in a high volume of open file descriptors and extended processing time.
To address this issue, modifications have been implemented in the Netdata API code to support multiple calls. This enhancement has led to a reduction improvement in processing time by approximately 10 seconds during graph exports involving 1200 disks.
This also resolves the file descriptors issue we were seeing where we ran out of them - solution to address this has been to use a connection pool instead of making separate requests.
Original PR: https://github.com/truenas/middleware/pull/12214
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124128

NAS-124128 / 23.10 / Improve performance for netdata retrieving graphs data (by Qubad786)

---

src/middlewared/middlewared/plugins/datastore/read.py

It was introduced by e1054f7b2e04ce75225742a1b3c5f02644829c6a along with some tests that now pass even with this bit removed

NAS-124400 / 24.04 / Remove pre-SQLite 3.30 workaround

---

src/middlewared/middlewared/plugins/iscsi_/extents.py
tests/api2/test_261_iscsi_cmd.py

Starting in COBIA we require a valid serial number to be specified for each iSCSI target extent, in order to support ALUA.  This gets applied to the scst config as `t10_dev_id`.
Previously _some_ paths through our code auto-generated a serial number, but another path did not.  This PR rectifies this deficiency by enhancing `extent_serial` to also generate on the empty string.
Furthermore, we also now ensure that serial numbers are unique.
Finally, add some tests.

NAS-124425 / 24.04 / Fatal Error message appears post start of iSCSI service containing multiple targets and file extents

---

src/middlewared/middlewared/alembic/versions/23.10/2023-10-02_21-57_extent_serial.py

Starting in COBIA we require a valid serial number to be specified for each iSCSI target extent, in order to support ALUA.  This gets applied to the scst config as `t10_dev_id`.
NAS-124425 is the defect that tracks the code changes so that going forward a serial number will always be generated when an extent is created.
This related defect (NAS-124432) is to modify the contents of the database to repair any *previously created* iSCSI extents.  It does this by performing an alembic migration (without a schema change).
As recommended in the relevant [documentation](http://docs.middleware.ixsystems.net/database/migrations.html#backporting-migrations), the first PR for this issue is to handle the backport.

NAS-124432 / 23.10 / Ensure iSCSI extents have a non-empty serial number

---

src/middlewared/middlewared/alembic/versions/23.10/2023-10-02_21-57_extent_serial.py
src/middlewared/middlewared/alembic/versions/24.04/2023-10-03_17-08_merge.py

Starting in COBIA we require a valid serial number to be specified for each iSCSI target extent, in order to support ALUA.  This gets applied to the scst config as `t10_dev_id`.
NAS-124425 is the defect that tracks the code changes so that going forward a serial number will always be generated when an extent is created.
This related defect (NAS-124432) is to modify the contents of the database to repair any *previously created* iSCSI extents.  It does this by performing an alembic migration (without a schema change).
As recommended in the relevant [documentation](http://docs.middleware.ixsystems.net/database/migrations.html#backporting-migrations), the first PR for this issue was to handle the backport.  **This** PR is the forward-port and subsequent merge heads.
Original PR: …

NAS-124432 / 24.04 / Ensure iSCSI extents have a non-empty serial number (by bmeagherix)

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

The `-f` flag is needed because the hostid can change. It changes, for example, when upgrading from CORE to SCALE. It also changes if the zpool being imported is from another system.

NAS-124451 / 24.04 / add -f (force) flag to import_on_boot()

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

The `-f` flag is needed because the hostid can change. It changes, for example, when upgrading from CORE to SCALE. It also changes if the zpool being imported is from another system.
Original PR: https://github.com/truenas/middleware/pull/12241
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124451

NAS-124451 / 23.10 / add -f (force) flag to import_on_boot() (by yocalebo)

---

src/middlewared/middlewared/plugins/vm/clone.py

git cherry-pick -x 86ba40456defb451a0dd8816f9d6e1d0dd7ea80f
git cherry-pick -x 6479c651bf1771d997a1041552ec3462ef21014a
When cloning a VM which has a display device where no password is configured (which was allowed in earlier versions of SCALE) - cloning the VM fails with a traceback as we are not able to clone the display device in question.
Properly validate the VM before cloning ensuring that it's display devices have a password configured and raise a validation error before trying to clone the VM.
Original PR: https://github.com/truenas/middleware/pull/12243
Jira URL: …

NAS-124297 / 23.10.0 / Add empty password validation when cloning a VM (by Qubad786)

---

src/freenas/usr/lib/netdata/python.d/smart_log.chart.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
src/middlewared/middlewared/plugins/reporting/utils.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py

The primary issue stems from receiving zero values in `reporting.netdata_get_data` for `disktemp` metrics. This problem is exacerbated by the relatively large time interval, which can be as long as 30 minutes. With such a lengthy interval, Netdata only collects data once in that time frame. Consequently, when attempting to retrieve data for every second, Netdata often lacks current values, resulting in it repeating previous values to fill the gaps. Additionally, the Netdata `disktemp` plugin has a 30-minute sleep interval, causing it to lag by that duration. This delay means Netdata lacks data for the current 30 minutes, leading to zero values on service restart or when the system boots up. Furthermore, a minor issue in the middleware relates to an incorrect time interval for data …

NAS-124182 / 23.10.0 / Fix disk temperature graph (by Qubad786)

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

A fix to enhance validation to catch invalid cluster peer configuation early in setup caused regression due to checking for credential for the local node.

NAS-124473 / 24.04 / Fix regression in create_cluster

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

A fix to enhance validation to catch invalid cluster peer configuation early in setup caused regression due to checking for credential for the local node.
Original PR: https://github.com/truenas/middleware/pull/12249
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124473

NAS-124473 / 23.10.1 / Fix regression in create_cluster (by anodos325)

---

src/middlewared/middlewared/plugins/disk_/temperature.py

Certain drives (ATA) will report their "raw" values for the temperature attribute (190, 194). For reasons not fully understood, something changed between 22.12.3.3 and 22.12.4 which caused this to break.
It's not fully understood if this was something in kernel (we updated kernel in 22.12.4) or if this has always been the case and we're just now getting reports of it. The solution is relatively simple, just convert the raw value if necessary.
I was able to reproduce the change of behavior in-house on real hardware and then confirmed these changes fix the issue.

NAS-124452 / 22.12.5 / fix disk.read_temps()

---

src/middlewared/middlewared/plugins/disk_/temperature.py

Certain drives (ATA) will report their "raw" values for the temperature attribute (190, 194). For reasons not fully understood, something changed between 22.12.3.3 and 22.12.4 which caused this to break.
It's not fully understood if this was something in kernel (we updated kernel in 22.12.4) or if this has always been the case and we're just now getting reports of it. The solution is relatively simple, just convert the raw value if necessary.
I was able to reproduce the change of behavior in-house on real hardware and then confirmed these changes fix the issue.
Original PR: https://github.com/truenas/middleware/pull/12253
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124452

NAS-124452 / 22.12.4.1 / fix disk.read_temps() (by yocalebo)

---

src/middlewared/middlewared/apidocs/templates/websocket/query.md
src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
src/middlewared/middlewared/utils/__init__.py

This adds support for more flexible usage of OR condition in our query-filters. For example, users will be able to filter by (a || (b & c)). Validation is also added for depth of filters to prevent API consumers from making extremely ill-advised queries. We can expand validation as-needed.
This may slightly increase time-complexity of evaluation of `OR` conditions (isinstance() check added), but most common case of simple conditions has no impact.

NAS-124428 / 24.04 / Add support for more complex filters

---

src/middlewared/middlewared/plugins/smb_/sharesec.py

There are various ways that users can encrypt, decrypt, enable and disable SMB paths and shares. Some operations require removing the SMB share from our shares list, which automatically removes the share acl entry. To prevent this we store a copy of it prefixed by a `#` character when share path is encrypted and when share is decrypted we restore from the backup copy. This logic had some gaps in it whereby a reboot when the backup was out-of-sync from the current one, the current share ACL could be replaced. This commit plugs the gap by immediately duplicating the ACL on setacl calls.
This issue does not impact Cobia and later since SMB share ACL handling was substantially refactored.

NAS-124486 / 22.12.5 / Update "toggled" share acl on sharesec update

---

src/middlewared/middlewared/plugins/smb_/sharesec.py

There are various ways that users can encrypt, decrypt, enable and disable SMB paths and shares. Some operations require removing the SMB share from our shares list, which automatically removes the share acl entry. To prevent this we store a copy of it prefixed by a `#` character when share path is encrypted and when share is decrypted we restore from the backup copy. This logic had some gaps in it whereby a reboot when the backup was out-of-sync from the current one, the current share ACL could be replaced. This commit plugs the gap by immediately duplicating the ACL on setacl calls.
This issue does not impact Cobia and later since SMB share ACL handling was substantially refactored.
Original PR: https://github.com/truenas/middleware/pull/12252
Jira URL: …

NAS-124486 / 22.12.4.1 / Update "toggled" share acl on sharesec update (by anodos325)

---

src/middlewared/middlewared/plugins/disk_/disk_info.py

I am making another pull request with this after the previous one was cancelled.
Whatever you think about the issue, it is not acceptable to read file without checking if it is present and then crashing storage UI, k3s and docker in the process. How it happens is of no consequence.
This is not feature request, this pull request is fixing unsanitized code. You may 100% ignore how I discovered it, but the code is unsanitized in a major way.
I also do not think that importing zpool should crash storage UI, k3s and docker under any circumstances.
I am willing to improve it any way, so it passes and even track why disks are reported as unused, it will be similar issue.

fix: https://ixsystems.atlassian.net/browse/NAS-124487

---

src/middlewared/middlewared/plugins/service_/services/cifs.py
tests/api2/test_435_smb_registry.py

An abusive test was being skipped due to dependency no longer being set. When it was re-enabled, the test failed due to race in the SMB service reload method. This commit fixes the test dependency and waits for the registry sync to finish before reloading the SMB service.

NAS-124492 / 24.04 / Fix abusive test of SMB registry config

---

src/middlewared/middlewared/plugins/directoryservices.py

This shouldn't be fatal, we just treat ourselves as not having a backup of domain secrets and write it to config.

NAS-124498 / 24.04 / Don't crash if secrets backup lacks last change TS

---

src/middlewared/middlewared/plugins/service_/services/cifs.py
tests/api2/test_435_smb_registry.py

An abusive test was being skipped due to dependency no longer being set. When it was re-enabled, the test failed due to race in the SMB service reload method. This commit fixes the test dependency and waits for the registry sync to finish before reloading the SMB service.
Original PR: https://github.com/truenas/middleware/pull/12261
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124492

NAS-124492 / 23.10.1 / Fix abusive test of SMB registry config (by anodos325)

---

src/middlewared/middlewared/plugins/directoryservices.py

This shouldn't be fatal, we just treat ourselves as not having a backup of domain secrets and write it to config.
Original PR: https://github.com/truenas/middleware/pull/12264
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124498

NAS-124498 / 23.10.1 / Don't crash if secrets backup lacks last change TS (by anodos325)

---

src/middlewared/middlewared/plugins/directoryservices.py

This shouldn't be fatal, we just treat ourselves as not having a backup of domain secrets and write it to config.
Original PR: https://github.com/truenas/middleware/pull/12264
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124498

NAS-124498 / 23.10.0 / Don't crash if secrets backup lacks last change TS (by anodos325)

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/directoryservices.py
tests/api2/test_030_activedirectory.py

Expand the enum to default to TEMPLATE. This is not a functional change, but does fix validation errors and gives better idea of how this maps to winbind nss parameters in smb.conf documentation.

NAS-124504 / 24.04 / Fix winbind NSS info handling in middleware

---

src/middlewared/middlewared/plugins/smb_/passdb.py

If we hit some error while attempting to rename the passdb.tdb file, we should still go ahead with attempting to sync it up with our config database.

NAS-124503 / 24.04 / Add more error handling for reinit of SMB passdb

---

src/middlewared/middlewared/plugins/smb_/passdb.py

If we hit some error while attempting to rename the passdb.tdb file, we should still go ahead with attempting to sync it up with our config database.
Original PR: https://github.com/truenas/middleware/pull/12271
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124503

NAS-124503 / 23.10.1 / Add more error handling for reinit of SMB passdb (by anodos325)

---

src/middlewared/middlewared/plugins/smb_/passdb.py

If we hit some error while attempting to rename the passdb.tdb file, we should still go ahead with attempting to sync it up with our config database.
Original PR: https://github.com/truenas/middleware/pull/12271
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124503

NAS-124503 / 23.10.0 / Add more error handling for reinit of SMB passdb (by anodos325)

---

src/middlewared/middlewared/plugins/enclosure_/map2.py
src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py

Slowing working on this rewrite and noticed on an internal R50B, this wasn't mapping appropriately. This fixes both problems.
Original PR: https://github.com/truenas/middleware/pull/12270
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124499

NAS-124499 / 23.10.1 / fix enclosure2 mapping code (by yocalebo)

---

src/middlewared/middlewared/plugins/smb.py
tests/api2/test_420_smb.py

Failure to resolve guest name will prevent SMB service from starting.

NAS-124508 / 24.04 / Prevent setting empty string for SMB guest

---

src/middlewared/middlewared/plugins/vm/clone.py
src/middlewared/middlewared/plugins/vm/vms.py

git cherry-pick -x 0d39d89583c8e91406bc3352dbb539319a71f7d0
git cherry-pick -x 4f66e553079fd4855298ae50747a6d762b008122
git cherry-pick -x 49c8b880dd77b0cc8e41b048e0c6cd737a8f7fbf
Original PR: https://github.com/truenas/middleware/pull/12277
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124493

NAS-124493 / 23.10.0 / Fix display available usages in vm schema (by sonicaj)

---

src/middlewared/middlewared/plugins/vm/clone.py
src/middlewared/middlewared/plugins/vm/vms.py

git cherry-pick -x 0d39d89583c8e91406bc3352dbb539319a71f7d0
git cherry-pick -x 4f66e553079fd4855298ae50747a6d762b008122
git cherry-pick -x 49c8b880dd77b0cc8e41b048e0c6cd737a8f7fbf
Original PR: https://github.com/truenas/middleware/pull/12277
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124493

NAS-124493 / 23.10.1 / Fix display available usages in vm schema (by sonicaj)

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

Typo which leads to a TypeError crash during importing of pools at boot. A regression introduced in https://github.com/truenas/middleware/pull/12202

NAS-124562 / 24.04 / fix typo causing TypeError crash

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

Typo which leads to a TypeError crash during importing of pools at boot. A regression introduced in https://github.com/truenas/middleware/pull/12202
Original PR: https://github.com/truenas/middleware/pull/12283
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124562

NAS-124562 / 23.10.0 / fix typo causing TypeError crash (by yocalebo)

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

Typo which leads to a TypeError crash during importing of pools at boot. A regression introduced in https://github.com/truenas/middleware/pull/12202
Original PR: https://github.com/truenas/middleware/pull/12283
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124562

NAS-124562 / 23.10.1 / fix typo causing TypeError crash (by yocalebo)

---

src/middlewared/middlewared/plugins/pool_/utils.py

The `compression=on` property value is a valid choice but often isn't seen anymore since it's considered a legacy value. Upstream changed the default years ago but we have certain users that create a zpool on a <= freenas 11 (yes freenas) and then import said zpool on SCALE. When this happens, we raise a validation error stating "on" is an invalid choice which is incorrect.

NAS-124477 / 24.04 / add 'ON' as a compression choice

---

src/middlewared/middlewared/plugins/pool_/utils.py

The `compression=on` property value is a valid choice but often isn't seen anymore since it's considered a legacy value. Upstream changed the default years ago but we have certain users that create a zpool on a <= freenas 11 (yes freenas) and then import said zpool on SCALE. When this happens, we raise a validation error stating "on" is an invalid choice which is incorrect.
Original PR: https://github.com/truenas/middleware/pull/12280
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124477

NAS-124477 / 23.10.1 / add 'ON' as a compression choice (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/map.py

Fixing YET ANOTHER R50 series enclosure mapping issue. https://github.com/truenas/middleware/pull/12160 fixed a regression but introduced another. The last enclosure in the list that we create is the plx or nvme "fake" enclosure that we generate. If we set the model for the `mapped_enclosure_0` to the model of the fake nvme enclosure, the webUI explodes and becomes, literally, unavailable (by design). This tries to fix it as best as possible by just ignoring those enclosures and setting the model once.
NOTE: this is not an issue in the enclosure2 rewrite but the webUI isn't using that endpoint, yet so this will have to limp us along.

NAS-124566 / 24.04 / another regression with R50 enclosure mgmt

---

src/middlewared/middlewared/plugins/enclosure_/map.py

Fixing YET ANOTHER R50 series enclosure mapping issue. https://github.com/truenas/middleware/pull/12160 fixed a regression but introduced another. The last enclosure in the list that we create is the plx or nvme "fake" enclosure that we generate. If we set the model for the `mapped_enclosure_0` to the model of the fake nvme enclosure, the webUI explodes and becomes, literally, unavailable (by design). This tries to fix it as best as possible by just ignoring those enclosures and setting the model once.
NOTE: this is not an issue in the enclosure2 rewrite but the webUI isn't using that endpoint, yet so this will have to limp us along.
Original PR: https://github.com/truenas/middleware/pull/12288
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124566

NAS-124566 / 23.10.1 / another regression with R50 enclosure mgmt (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/map.py

Fixing YET ANOTHER R50 series enclosure mapping issue. https://github.com/truenas/middleware/pull/12160 fixed a regression but introduced another. The last enclosure in the list that we create is the plx or nvme "fake" enclosure that we generate. If we set the model for the `mapped_enclosure_0` to the model of the fake nvme enclosure, the webUI explodes and becomes, literally, unavailable (by design). This tries to fix it as best as possible by just ignoring those enclosures and setting the model once.
NOTE: this is not an issue in the enclosure2 rewrite but the webUI isn't using that endpoint, yet so this will have to limp us along.
Original PR: https://github.com/truenas/middleware/pull/12288
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124566

NAS-124566 / 23.10.0 / another regression with R50 enclosure mgmt (by yocalebo)

---

src/middlewared/middlewared/plugins/smb.py

Homes share may be removed by either updating the share so that home=False or deleting the share. After these changes have been committed, we need to rebuild our global SMB config to remove the "obey pam restrictions" parameter.

NAS-124575 / 24.04 / Cleanup global settings after removing homes share

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/enclosure_class.py
src/middlewared/middlewared/utils/license.py

git cherry-pick -x 4edfc39a6a5d6e02e86118c4da71c9eb50c4a0d4
git cherry-pick -x f38fe6266abe78a733638e526bead2d5e2a879bd
Original PR: https://github.com/truenas/middleware/pull/12289
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124567

NAS-124567 / 13.0 / rename ES102S to ES102G2 (by yocalebo)

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/enclosure_class.py
src/middlewared/middlewared/utils/license.py

git cherry-pick -x 4edfc39a6a5d6e02e86118c4da71c9eb50c4a0d4
git cherry-pick -x f38fe6266abe78a733638e526bead2d5e2a879bd
Original PR: https://github.com/truenas/middleware/pull/12289
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124567

NAS-124567 / 13.1 / rename ES102S to ES102G2 (by yocalebo)

---

tests/api2/test_420_smb.py
tests/api2/test_425_smb_protocol.py
tests/api2/test_426_smb_vss.py
tests/api2/test_427_smb_acl.py

This is a minor refactor of SMB protocol related tests to ensure that module-specific state is properly reset at conclusion of tests.

NAS-124576 / 24.04 / Improve cleanup in SMB tests

---

src/middlewared/middlewared/alert/source/pools.py

Placing this as a warning encourages users to upgrade pool when it's not really necessary and should be evaluated carefully by the administrator.

NAS-124584 / 24.04 / Decrease alert priority of zpool upgrade to NOTICE

---

src/middlewared/middlewared/alert/source/pools.py

Placing this as a warning encourages users to upgrade pool when it's not really necessary and should be evaluated carefully by the administrator.
Original PR: https://github.com/truenas/middleware/pull/12299
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124584

NAS-124584 / 23.10.1 / Decrease alert priority of zpool upgrade to NOTICE (by anodos325)

---

src/middlewared/middlewared/plugins/ldap.py

Remove code that was preventing the clearing of the LDAP 'bindpw' field.
If keytab is available, we prefer that 'bindpw' not be populated.
Changed the nag message to a user action request and reduced it's priority from warning to info.

NAS-124588 / 24.04 / Fix LDAP bindpw handling

---

src/middlewared/middlewared/plugins/account_/2fa.py

This PR fixes an issue where whenever a user's secret is renewed we make sure to reflect that in SSH settings as if it's not reloaded, it will continue using older secret.

NAS-124594 / 23.10.1 / Make sure SSH settings reflect newer user secret

---

src/middlewared/middlewared/plugins/reporting/rest.py

We were spamming middleware logs unnecessarily with complete stack trace whenever netdata call failed and it was requested that we stop doing that to make the logs easier to debug.

NAS-124431 / 24.04 / Remove unnecessary spam from middleware logs

---

src/middlewared/middlewared/plugins/reporting/rest.py

We were spamming middleware logs unnecessarily with complete stack trace whenever netdata call failed and it was requested that we stop doing that to make the logs easier to debug.
Original PR: https://github.com/truenas/middleware/pull/12309
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124431

NAS-124431 / 23.10.0 / Remove unnecessary spam from middleware logs (by Qubad786)

---

src/freenas/etc/systemd/system/netdata.service.d/override.conf
src/middlewared/middlewared/plugins/reporting/events.py

The current user interface lacks the ability to verify whether Netdata is operational and correctly receiving data from the `reporting.realtime` event source.
To address this limitation, a flag is added to the response from `reporting.realtime` event source. This flag will be set to true if Netdata is not running. Furthermore, changes are made to the Netdata unit file's restart policy, setting it to "always." This ensures that Netdata will automatically restart in case it fails to start for any reason. These improvements enhance the UI's capability to verify and maintain Netdata's functionality.

NAS-124429 / 24.04 / Add flag to reporting realtime event source determining netdata's health

---

src/freenas/etc/systemd/system/netdata.service.d/override.conf
src/middlewared/middlewared/plugins/reporting/events.py

git cherry-pick -x efa786583654e21813b2fb04d9870c3164d99f2e
git cherry-pick -x 5a9e300141eab950734cf50a73d96f133a7dbddf
The current user interface lacks the ability to verify whether Netdata is operational and correctly receiving data from the `reporting.realtime` event source.
To address this limitation, a flag is added to the response from `reporting.realtime` event source. This flag will be set to true if Netdata is not running. Furthermore, changes are made to the Netdata unit file's restart policy, setting it to "always." This ensures that Netdata will automatically restart in case …

NAS-124429 / 23.10.1 / Add flag to reporting realtime event source determining netdata's health (by Qubad786)

---

src/middlewared/middlewared/plugins/audit/audit.py
src/middlewared/middlewared/plugins/audit/backend.py
src/middlewared/middlewared/plugins/audit/utils.py
tests/api2/test_audit_basic.py

This provides an API for generating an audit report based on our query-filters and query-options for services (same API details as audit.query), but adds an additional parameter to specify format. When the endpoint is called a file in the specified format is written to a file in a directory (based on currently-authenticated user's username) within /audit/reports. The path for the newly-created file is return to caller, and may be used to fetch file either through scp or middleware filesystem.get API.

NAS-124605 / 24.04 / Add API for generating audit reports

---

src/freenas/etc/systemd/system/keepalived.service.d/override.conf

This adds 2 new startup flags while removing 1 from the original `ExecStart` operation that ships with debian's service file.
I add:
- `--log-detail` to get much more detailed log messages
- `--vrrp` which starts up keepalived while enabling on the vrrp subsystem since we're not using IPVS in our implementation
I remove the `$DAEMON_ARGS` argument that gets tacked on the end since we control these by hand and in a very explicit way. Making these changes on a real system proved invaluable for interpreting and understanding a particularly insidious network issue.

NAS-124617 / 24.04 / add keepalived override.conf

---

src/freenas/etc/systemd/system/keepalived.service.d/override.conf

This adds 2 new startup flags while removing 1 from the original `ExecStart` operation that ships with debian's service file.
I add:
- `--log-detail` to get much more detailed log messages
- `--vrrp` which starts up keepalived while enabling on the vrrp subsystem since we're not using IPVS in our implementation
I remove the `$DAEMON_ARGS` argument that gets tacked on the end since we control these by hand and in a very explicit way. Making these changes on a real system proved invaluable for interpreting and understanding a particularly insidious network issue.
Original PR: https://github.com/truenas/middleware/pull/12317
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124617

NAS-124617 / 23.10.0 / add keepalived override.conf (by yocalebo)

---

src/freenas/etc/systemd/system/keepalived.service.d/override.conf

This adds 2 new startup flags while removing 1 from the original `ExecStart` operation that ships with debian's service file.
I add:
- `--log-detail` to get much more detailed log messages
- `--vrrp` which starts up keepalived while enabling on the vrrp subsystem since we're not using IPVS in our implementation
I remove the `$DAEMON_ARGS` argument that gets tacked on the end since we control these by hand and in a very explicit way. Making these changes on a real system proved invaluable for interpreting and understanding a particularly insidious network issue.
Original PR: https://github.com/truenas/middleware/pull/12317
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124617

NAS-124617 / 23.10.1 / add keepalived override.conf (by yocalebo)

---

src/middlewared/middlewared/plugins/smb.py

Raise ValidationError if a different exists that has `home` set to True.
Original PR: https://github.com/truenas/middleware/pull/12320
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124364

NAS-124364 / 23.10.0 / Fix check for existing home directory (by anodos325)

---

src/middlewared/middlewared/plugins/smb.py

Raise ValidationError if a different exists that has `home` set to True.
Original PR: https://github.com/truenas/middleware/pull/12320
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124364

NAS-124364 / 23.10.1 / Fix check for existing home directory (by anodos325)

---

src/middlewared/middlewared/plugins/system/debug.py
src/middlewared/middlewared/plugins/system/utils.py

In certain scenarios (which i have not been able to reproduce), the `shutils.rmtree` operation fails to remove an existing debug directory. This failure results in a "Compressed path already exists" call error.
To mitigate this error and ensure that we always generate a debug no matter what, a new directory will be created if an unexpected issue occurs during the removal of the debug directory. This adjustment ensures the smooth execution of the operation and prevents the error from being triggered.

NAS-124585 / 24.04 / Ensure we always generate debug

---

src/middlewared/middlewared/plugins/system/debug.py
src/middlewared/middlewared/plugins/system/utils.py

In certain scenarios (which i have not been able to reproduce), the `shutils.rmtree` operation fails to remove an existing debug directory. This failure results in a "Compressed path already exists" call error.
To mitigate this error and ensure that we always generate a debug no matter what, a new directory will be created if an unexpected issue occurs during the removal of the debug directory. This adjustment ensures the smooth execution of the operation and prevents the error from being triggered.
Original PR: https://github.com/truenas/middleware/pull/12314
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124585

NAS-124585 / 23.10.0 / Ensure we always generate debug (by Qubad786)

---

src/middlewared/middlewared/plugins/system/debug.py
src/middlewared/middlewared/plugins/system/utils.py

In certain scenarios (which i have not been able to reproduce), the `shutils.rmtree` operation fails to remove an existing debug directory. This failure results in a "Compressed path already exists" call error.
To mitigate this error and ensure that we always generate a debug no matter what, a new directory will be created if an unexpected issue occurs during the removal of the debug directory. This adjustment ensures the smooth execution of the operation and prevents the error from being triggered.
Original PR: https://github.com/truenas/middleware/pull/12314
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124585

NAS-124585 / 23.10.1 / Ensure we always generate debug (by Qubad786)

---

src/middlewared/middlewared/plugins/vm/devices/display.py

The VM display device was allowed to be created with a port that was already in use by some other display device. 
Validations error was not raised for port already in use because verrors was being initialized again in the `validate_port_attrs` function hence loosing the captured errors.
Fixed the error raise issue for its validation.

NAS-124396 / 24.04 / Fix raising validation error for vm devices port utilization

---

src/middlewared/middlewared/plugins/vm/devices/display.py

The VM display device was allowed to be created with a port that was already in use by some other display device. 
Validations error was not raised for port already in use because verrors was being initialized again in the `validate_port_attrs` function hence loosing the captured errors.
Fixed the error raise issue for its validation.
Original PR: https://github.com/truenas/middleware/pull/12329
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124396

NAS-124396 / 23.10.0 / Fix raising validation error for vm devices port utilization (by Qubad786)

---

src/middlewared/middlewared/plugins/vm/devices/display.py

The VM display device was allowed to be created with a port that was already in use by some other display device. 
Validations error was not raised for port already in use because verrors was being initialized again in the `validate_port_attrs` function hence loosing the captured errors.
Fixed the error raise issue for its validation.
Original PR: https://github.com/truenas/middleware/pull/12329
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124396

NAS-124396 / 23.10.1 / Fix raising validation error for vm devices port utilization (by Qubad786)

---

src/middlewared/middlewared/alembic/versions/24.04/2023-10-08_16-22_2fa_per_user_settings.py
src/middlewared/middlewared/alembic/versions/24.04/2023-10-11_16-22_2fa_per_user_settings.py
src/middlewared/middlewared/etc_files/local/users.oath.mako
src/middlewared/middlewared/plugins/account_/2fa.py
src/middlewared/middlewared/plugins/auth_/2fa.py
src/middlewared/middlewared/test/integration/assets/two_factor_auth.py
tests/api2/test_twofactor_auth.py

This PR adds changes to have `interval` and `otp_digits` be specified at user level for both AD and local users. This helps making it more configurable and a user can change his own settings instead of this being applied at a global level which resulted in all the existing users secret to be renewed because secret depends on this.

NAS-122626 / 24.04 / Allow specifying interval/otp digits at per user level for 2FA

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/activedirectory_/dns.py
src/middlewared/middlewared/plugins/network_/dns.py

This commit includes two principle changes:
1) the nsupdate endpoint now allows GLOBAL addresses 
2) validation for IP addresses to register happens earlier in activedirectory.update so that we can raise proper validation error and redirect user to either disable the automatic DNS update or fix the server configuration prior to joining AD. As things stand, this can cause an exception mid-join and leave server in semi-deployed state.
Future enhancement will be to allow users to select which addresses to register in DNS. At that point, we can safely allow global addresses.

NAS-124557 / 24.04 / Allow nsupdate to set non-private IP addresses

---

src/middlewared/middlewared/plugins/pool_/dataset.py
tests/api2/test_340_pool_dataset.py

In principle in Linux this is less of a problem than in FreeBSD because of proper inotify support, and kernel oplocks. Add a share_type preset that provides user with dataset settings that are likely to make SMB and NFS clients happier.
Original PR: https://github.com/truenas/middleware/pull/12332
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124626

NAS-124626 / 23.10.0 / Add share_type preset for mixed SMB/NFS (by anodos325)

---

src/middlewared/middlewared/plugins/truecommand/wireguard.py

This commit adds changes to reduce the time to check if truecommand connection is active to 30 seconds instead of 30 minutes after setting up the interfaces and everything because the latter was way too long and system only updated the status before if truecommand.config was explicitly called. Setting it to 30 seconds works nicely and is enough to ensure the relevant wireguard interface is up and everything.

NAS-122931 / 24.04 / Reduce the time to check if truecommand connection is active

---

src/middlewared/middlewared/plugins/truecommand/wireguard.py

This commit adds changes to reduce the time to check if truecommand connection is active to 30 seconds instead of 30 minutes after setting up the interfaces and everything because the latter was way too long and system only updated the status before if truecommand.config was explicitly called. Setting it to 30 seconds works nicely and is enough to ensure the relevant wireguard interface is up and everything.
Original PR: https://github.com/truenas/middleware/pull/12338
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122931

NAS-122931 / 23.10.1 / Reduce the time to check if truecommand connection is active (by sonicaj)

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

Force RFC-1918 addresses for inter-node traffic on TrueNAS clusters.
Original PR: https://github.com/truenas/middleware/pull/12341
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124672

NAS-124672 / 23.10.1 / Add validator for CTDB private IP addresses (by anodos325)

---

src/middlewared/middlewared/etc_files/krb5.conf.mako
src/middlewared/middlewared/plugins/kerberos.py
tests/runtest.py

The default location of the 'system' Kerberos credential cache is /tmp.   This directory is managed by systemd and is cleaned asynchronously.  This results in anomalous authentication failures.
Store the credential cache in a different location.   The Kerberos subsystem provides a mechanism (krb5.conf) to use a different path for the cache.

NAS-124684 / 24.04 / Move krb5 ccache directory from /tmp

---

src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
src/middlewared/middlewared/utils/__init__.py

Select logic was broken for case where the parameter we were selecting had a null value. This fixes the behavior and adds test.

NAS-124688 / 24.04 / Fix selecting parameters with NULL value in filter_list

---

src/middlewared/middlewared/etc_files/krb5.conf.mako
src/middlewared/middlewared/plugins/kerberos.py
tests/runtest.py

The default location of the 'system' Kerberos credential cache is /tmp.   This directory is managed by systemd and is cleaned asynchronously.  This results in anomalous authentication failures.
Store the credential cache in a different location.   The Kerberos subsystem provides a mechanism (krb5.conf) to use a different path for the cache.  
Original PR: https://github.com/truenas/middleware/pull/12343
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124684

NAS-124684 / 23.10.1 / Move krb5 ccache directory from /tmp (by mgrimesix)

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/cache.py

This commit removes a legacy behavior for the private method dscache.query. In this case dscache.query calls would also retrieve the local users datastore and return unified results. This was due to some design constraints when replacing the user and group cache in our legacy django webui in TrueNAS 11.2. As of SCALE the webui no longer directly calls dscache.query to get user / group lists and so we can safely remove this oddity.
The primary motivation for removing this legacy behavior is to fix how query-options are applied to query results.
Original PR: https://github.com/truenas/middleware/pull/12333
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124628

NAS-124628 / 23.10.1 / Fix filtering behavior for user and group queries (by anodos325)

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/activedirectory_/dns.py
src/middlewared/middlewared/plugins/network_/dns.py

This commit includes two principle changes:
1) the nsupdate endpoint now allows GLOBAL addresses 
2) validation for IP addresses to register happens earlier in activedirectory.update so that we can raise proper validation error and redirect user to either disable the automatic DNS update or fix the server configuration prior to joining AD. As things stand, this can cause an exception mid-join and leave server in semi-deployed state.
Future enhancement will be to allow users to select which addresses to register in DNS. At that point, we can safely allow global addresses.
Original PR: https://github.com/truenas/middleware/pull/12281
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124557

NAS-124557 / 23.10.1 / Allow nsupdate to set non-private IP addresses (by anodos325)

---

tests/api2/test_036_ad_ldap.py

Removed failing test for existence of a krb5 credential cache in /tmp. 
It was using a hard-coded path that's no longer valid and there is other validation that covers this file existence check.

NAS-124705 / 24.04 / Remove existence test that uses hard-coded path

---

src/middlewared/middlewared/plugins/failover.py

This PR fixes an issue where when backup node middleware restarts, we do not sync keys from master node because when we tried to sync the keys on middleware boot - we were not able to talk to active node which is highly likely because middleware has not initialised itself properly at that point, so we add a delay to ensure we only do that once middleware has booted and initialised itself properly.

NAS-124662 / 24.04 / Fix encryption keys not syncing to backup node on middleware restart

---

src/middlewared/middlewared/plugins/failover.py

This PR fixes an issue where when backup node middleware restarts, we do not sync keys from master node because when we tried to sync the keys on middleware boot - we were not able to talk to active node which is highly likely because middleware has not initialised itself properly at that point, so we add a delay to ensure we only do that once middleware has booted and initialised itself properly.
Original PR: https://github.com/truenas/middleware/pull/12340
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124662

NAS-124662 / 23.10.0 / Fix encryption keys not syncing to backup node on middleware restart (by sonicaj)

---

src/middlewared/middlewared/plugins/failover.py

This PR fixes an issue where when backup node middleware restarts, we do not sync keys from master node because when we tried to sync the keys on middleware boot - we were not able to talk to active node which is highly likely because middleware has not initialised itself properly at that point, so we add a delay to ensure we only do that once middleware has booted and initialised itself properly.
Original PR: https://github.com/truenas/middleware/pull/12340
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124662

NAS-124662 / 23.10.1 / Fix encryption keys not syncing to backup node on middleware restart (by sonicaj)

---

src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_graphs.py

This commit fixes an issue where if the netdata call failed for whatever reason, we instead of handling that gracefully resulted in a traceback.
```
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1254, in run_in_thread
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1251, in run_in_executor
return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```

NAS-124715 / 24.04 / Fix netdata disk temperature graph plugin

---

src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_graphs.py

This commit fixes an issue where if the netdata call failed for whatever reason, we instead of handling that gracefully resulted in a traceback.
```
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1254, in run_in_thread
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1251, in run_in_executor
return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```

NAS-124715 / 23.10.1 / Fix netdata disk temperature graph plugin (by sonicaj)

---

src/middlewared/middlewared/etc_files/scst.conf.mako
tests/api2/test_261_iscsi_cmd.py

When examining a set of logs noticed that a target was enabled, even though no active targets were associated with it.  Correct the existing check.  Also include a unit test.

NAS-124739 / 24.04 / Only enable an iSCSI target if it has an active extent

---

src/middlewared/middlewared/etc_files/scst.conf.mako
tests/api2/test_261_iscsi_cmd.py

When examining a set of logs noticed that a target was enabled, even though no active targets were associated with it.  Correct the existing check.  Also include a unit test.
Original PR: https://github.com/truenas/middleware/pull/12371
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124739

NAS-124739 / 23.10.1 / Only enable an iSCSI target if it has an active extent (by bmeagherix)

---

src/middlewared/middlewared/plugins/vm/pci.py
src/middlewared/middlewared/pytest/unit/plugins/vm/test_pci_device_iommu_groups.py

This PR adds changes to correctly retrieve iommu groups as we were not validating the directory names properly and that resulted in normalization logic failing.

NAS-124627 / 24.04 / Correctly retrieve iommu groups information

---

src/middlewared/middlewared/plugins/vm/pci.py
src/middlewared/middlewared/pytest/unit/plugins/vm/test_pci_device_iommu_groups.py

This PR adds changes to correctly retrieve iommu groups as we were not validating the directory names properly and that resulted in normalization logic failing.
Original PR: https://github.com/truenas/middleware/pull/12370
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124627

NAS-124627 / 23.10.1 / Correctly retrieve iommu groups information (by sonicaj)

---

src/middlewared/middlewared/plugins/interface/internal_ifaces.py
src/middlewared/middlewared/plugins/network.py

When an f-series is installed cleanly and boots up the 1st time, by design , we start DHCP on all the physical interfaces on the system. With the f-series, we mask the `eno1` interface since it's shared with IPMI.
To ensure this interface is ignored, I added `eno1` check in the `interface.internal_interfaces` method which is what all consumers should be calling. Since I added this logic to that method, I was able to simplify `interface.query` but more importantly, the `interface.sync` method will now ignore `eno1` on the f-series platform when the system boots for the first time.

NAS-124730 / 24.04 / dont start dhcp on eno1 on fseries

---

src/middlewared/middlewared/plugins/interface/internal_ifaces.py
src/middlewared/middlewared/plugins/network.py

When an f-series is installed cleanly and boots up the 1st time, by design , we start DHCP on all the physical interfaces on the system. With the f-series, we mask the `eno1` interface since it's shared with IPMI.
To ensure this interface is ignored, I added `eno1` check in the `interface.internal_interfaces` method which is what all consumers should be calling. Since I added this logic to that method, I was able to simplify `interface.query` but more importantly, the `interface.sync` method will now ignore `eno1` on the f-series platform when the system boots for the first time.
Original PR: https://github.com/truenas/middleware/pull/12377
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124730

NAS-124730 / 23.10.1 / dont start dhcp on eno1 on fseries (by yocalebo)

---

src/middlewared/middlewared/plugins/container_runtime_interface/client.py
src/middlewared/middlewared/plugins/container_runtime_interface/dockerhub_rate_limit.py
src/middlewared/middlewared/plugins/container_runtime_interface/utils.py
src/middlewared/middlewared/pytest/unit/plugins/container_images/test_container_images_utils.py

This PR adds changes to introduce a new endpoint which returns available pull limits for dockerhub registry. Motivation behind the endpoint is that on app installation, UI can make a call to this endpoint and if `remaining_pull_limit` is less then 5, it would display a warning to the user that it is possible the installation process may get stuck as images wouldn't be pulled if they are coming from dockerhub because user limit to dockerhub has almost/or has been reached and until `remaining_time_limit_in_secs`, it won't be renewed.

NAS-124601 / 24.04 / Add an endpoint to retrieve remaining dockerhub registry pull limits

---

src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
src/middlewared/middlewared/plugins/filesystem_/perm_check.py
tests/api2/test_340_pool_dataset.py

This commit modifies our execute check so that we by default skip
non-existent path components. This is relevant when validating case
where ZFS create_ancestors is specified when creating a new dataset. We
don't want to fail validation on the non-existent path component, but
we do want to validate permissions on any parent datasets that do exist.

NAS-124799 / 24.04 / Fix zfs create ancestors

---

src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
src/middlewared/middlewared/plugins/filesystem_/perm_check.py
tests/api2/test_340_pool_dataset.py

This commit modifies our execute check so that we by default skip
non-existent path components. This is relevant when validating case
where ZFS create_ancestors is specified when creating a new dataset. We
don't want to fail validation on the non-existent path component, but
we do want to validate permissions on any parent datasets that do exist.
Original PR: https://github.com/truenas/middleware/pull/12393
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124799

NAS-124799 / 23.10.1 / Fix zfs create ancestors (by anodos325)

---

src/freenas/usr/bin/install-dev-tools

Also, only run `disable-rootfs-protection` when running on SCALE
These issues were encountered when running in a **fresh** environment.

NAS-124827 / 24.04 / Only run disable-rootfs-protection when running on SCALE

---

src/middlewared/middlewared/plugins/cache.py
src/middlewared/middlewared/plugins/idmap.py
tests/api2/test_040_ad_user_group_cache.py

When 2fa is enabled we look up user / group object info via user.translate_user to get consistent data structures containing SID information for DS and local users. Since the initial step of this goes through nss (which doesn't report back to us with nss module actually resolved the name), we pass along the resulting passwd or group dict to a winbind query which validates the uid/gid against our currently configured domains. This PR adds handling for when resolution fails so that we return None type which falls through to initial user.query allowing it to proceed with the local user / group database.

NAS-124777 / 24.04 / Add handling for local user / group 2fa

---

src/middlewared/middlewared/plugins/cache.py
src/middlewared/middlewared/plugins/idmap.py
tests/api2/test_040_ad_user_group_cache.py

When 2fa is enabled we look up user / group object info via user.translate_user to get consistent data structures containing SID information for DS and local users. Since the initial step of this goes through nss (which doesn't report back to us with nss module actually resolved the name), we pass along the resulting passwd or group dict to a winbind query which validates the uid/gid against our currently configured domains. This PR adds handling for when resolution fails so that we return None type which falls through to initial user.query allowing it to proceed with the local user / group database.
Original PR: https://github.com/truenas/middleware/pull/12388
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124777

NAS-124777 / 23.10.1 / Add handling for local user / group 2fa (by anodos325)

---

debian/debian/ix-netif.service
debian/debian/ix-preinit.service
src/freenas/etc/systemd/system/nfs-server.service.d/override.conf
src/middlewared/middlewared/plugins/smb.py

Under some configurations, NFS can be dependent on nslcd and directory service, AD or LDAP (IPA) are nearly always dependent on the network subsystem.
Under some conditions and configurations, NFS and directory service would start before their dependent services.
NFS and nslcd are mostly managed by systemd.
To address NFS dependency on nslcd:  Added `After=nslcd` criteria to nfs-server unit file.
Directory Service is managed by middleware and, if enabled, is started as part of smb.configure.
To address Directory Service dependency on the network subsystem:  Added a sentinel file generated in the ix-netif unit file.  SMB `configure` will wait for the sentinel file before starting Directory Service.
Also did some cosmetic clean up of smb.py for flake8.

NAS-124758 / 24.04 / NFS and directory service should wait for dependent services

---

src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/pool_/import_pool.py

This PR fixes a case where any unencrypted datasets under encrypted root dataset get mounted before we actually get the chance to unlock root dataset.

NAS-124776 / 24.04 / Make sure we don't mount any unencrypted datasets on pool import

---

src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/pool_/import_pool.py

This PR fixes a case where any unencrypted datasets under encrypted root dataset get mounted before we actually get the chance to unlock root dataset.
Original PR: https://github.com/truenas/middleware/pull/12398
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124776

NAS-124776 / 23.10.1 / Make sure we don't mount any unencrypted datasets on pool import (by sonicaj)

---

src/middlewared/middlewared/etc_files/syslogd.py

This removes an unnecessary closing brace in the syslog-ng directive for remote syslog target.

NAS-124845 / 23.10.1 / Fix regression in remote syslog

---

tests/api2/test_475_syslog.py

This commit adds a basic test that setting a remote syslog target doesn't break syslog-ng. Proper functional tests are still needed.

NAS-124876 / 24.04 / Add remote syslog test

---

src/middlewared/middlewared/plugins/smb.py

Our system SID changes on netbios name change and so we need to flush any cached sid-to-name / name-to-sid results. Failing to flush cached entries causes potential for failure to set SMB share ACLs (failure to convert names to SIDs) if server administrator immediately switches to that form before the cached entries time out.

NAS-124879 / 24.04 / Flush cached SID info on netbios name change

---

src/middlewared/middlewared/plugins/audit/audit.py
src/middlewared/middlewared/plugins/audit/schema/common.py
src/middlewared/middlewared/plugins/audit/schema/smb.py

This PR adds schema info for all SMB auditing events and validates API user `select` query-options against possible keys in SMB auditing events to give better feedback if user has typoed a column.

NAS-124686 / 24.04 / auditing - validate select against available columns

---

src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/failover_/detect_enclosure.py
src/middlewared/middlewared/plugins/failover_/internal_interface.py

Similar to what we do when we run our CI against HA VMs running on BHYVE hypervisors, we now have HA VMs working on KVM hypervisor. This adds the necessary changes to our code to detect such an environment and configure the system accordingly.

NAS-124896 / 24.04 / add HA KVM detection

---

src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/failover_/detect_enclosure.py
src/middlewared/middlewared/plugins/failover_/internal_interface.py

Similar to what we do when we run our CI against HA VMs running on BHYVE hypervisors, we now have HA VMs working on KVM hypervisor. This adds the necessary changes to our code to detect such an environment and configure the system accordingly.
Original PR: https://github.com/truenas/middleware/pull/12411
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124896

NAS-124896 / 23.10.1 / add HA KVM detection (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/pool_/import_pool.py

This PR fixes a case where any unencrypted datasets under encrypted root dataset get mounted before we actually get the chance to unlock root dataset.
Original PR: https://github.com/truenas/middleware/pull/12398
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124776
Original PR: https://github.com/truenas/middleware/pull/12402
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124776

NAS-124776 / 23.10.0.1 / Make sure we don't mount any unencrypted datasets on pool import (by sonicaj) (by bugclerk)

---

src/middlewared/middlewared/etc_files/syslogd.py

This removes an unnecessary closing brace in the syslog-ng directive for remote syslog target.
Original PR: https://github.com/truenas/middleware/pull/12403
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124845

NAS-124845 / 23.10.0.1 / Fix regression in remote syslog (by anodos325)

---

src/middlewared/middlewared/plugins/reporting/realtime_reporting/ifstat.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_stats_func.py

**Problem:**
Presently, Netdata is sending network statistics in kilobits, but in the middleware, these values are being interpreted as kilobytes. This results in inflated reported network statistics in the UI, both for sent and received data.
**Solution:**
The solution involves appropriately converting the Netdata values to bytes in order to accurately represent the network statistics. This adjustment will ensure the consistency and correctness of the reported data in the UI.

NAS-124779 / 24.04 / Send network stats in bytes

---

src/middlewared/middlewared/plugins/reporting/realtime_reporting/ifstat.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_stats_func.py

**Problem:**
Presently, Netdata is sending network statistics in kilobits, but in the middleware, these values are being interpreted as kilobytes. This results in inflated reported network statistics in the UI, both for sent and received data.
**Solution:**
The solution involves appropriately converting the Netdata values to bytes in order to accurately represent the network statistics. This adjustment will ensure the consistency and correctness of the reported data in the UI.
Original PR: https://github.com/truenas/middleware/pull/12429
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124779

NAS-124779 / 23.10.1 / Send network stats in bytes (by Qubad786)

---

src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py

**Problem:**
There are instances where the UI queries data from Netdata using a timestamp that doesn't exist in Netdata's records. In such cases, Netdata returns a value of 0. This results in the minimum value remaining at 0, which is incorrect. However, sometimes the UI reports the correct value.
**Solution:**
To address this issue, a new "natural-points" flag has been introduced. This flag ensures that Netdata will not return data for a timestamp that doesn't exist. Additionally, a check has been added to the normalization process. This check ensures that if the last value is zero, it will be removed. These changes allow for the correct reporting of minimum values.

NAS-124669 / 24.04 / Remove extra zeros for all graphs if coming from netdata

---

src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py

**Problem:**
There are instances where the UI queries data from Netdata using a timestamp that doesn't exist in Netdata's records. In such cases, Netdata returns a value of 0. This results in the minimum value remaining at 0, which is incorrect. However, sometimes the UI reports the correct value.
**Solution:**
To address this issue, a new "natural-points" flag has been introduced. This flag ensures that Netdata will not return data for a timestamp that doesn't exist. Additionally, a check has been added to the normalization process. This check ensures that if the last value is zero, it will be removed. These changes allow for the correct reporting of minimum values.
Original PR: https://github.com/truenas/middleware/pull/12430
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124669

NAS-124669 / 23.10.1 / Remove extra zeros for all graphs if coming from netdata (by Qubad786)

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/account_/privilege.py
src/middlewared/middlewared/plugins/account_/privilege_utils.py
src/middlewared/middlewared/plugins/cache.py
tests/api2/test_account_query_roles.py

This commit adds a new option for `additional_information` from user.query and group.query whereby API user can request roles of which the user or group is a member.

NAS-124981 / 24.04 / Allow query of roles via account plugin

---

tests/api2/test_190_filesystem.py
tests/api2/test_account_privilege_role.py
tests/api2/test_cloud_sync.py
tests/api2/test_cloud_sync_config.py
tests/api2/test_cloud_sync_custom_s3.py
tests/api2/test_cloudsync_storj.py
tests/api2/test_nfs_share_crud_roles.py
tests/api2/test_pool_dataset_create.py
tests/api2/test_pool_dataset_details.py
tests/api2/test_pool_dataset_encrypted.py
tests/api2/test_pool_dataset_set_quota.py
tests/api2/test_pool_dataset_snapshot_count.py
tests/api2/test_smb_share_crud_roles.py
tests/api2/test_zfs_snapshot_events.py
tests/api2/test_zfs_snapshot_hold.py

This helps identify places where perhaps teardown of dataset is failing.

NAS-125004 / 24.04 / Give temporary datasets unique names in tests

---

src/middlewared/middlewared/plugins/interface/internal_ifaces.py

This commit adds changes to create a copy of internal interfaces which we retrieve because in places we manipulate the list and remove interaces like loopback device which results in tracebacks in various places as `interface.ip_in_use` errors out.
```
❯ midclt call interface.ip_in_use '{"any": true, "static": false, "loopback": true}' | jq
list.remove(x): x not in list
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 201, in call_method
result = await self.middleware._call(message['method'], serviceobj, methodobj, params, app=self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1367, in _call
return await …
```

NAS-124987 / 24.04 / Correctly retrieve used ips

---

tests/api2/test_iscsi_extent_crud_roles.py
tests/api2/test_nfs_share_crud_roles.py
tests/api2/test_smb_share_crud_roles.py

We want shares and datasets torn down when the series of tests performed in the respective pytest files are complete, as opposed to having them persist for the remaining test run.

NAS-125009 / 24.04 / Fix scope of role CRUD tests

---

src/middlewared/middlewared/plugins/interface/internal_ifaces.py
src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
src/middlewared/middlewared/plugins/interface/netif_linux/utils.py
src/middlewared/middlewared/plugins/network.py

Revert b95d161c1c5b74f7391186cb80e6d369ee4965d6 since it's not a valid fix and only masks the real problem. The real problem is that a regression was introduced in f03e9fb8744684fa4f6aa0d978e2bb8dce26b458 whereby we keep `append`'ing and `extend`'ing the contents of the global mutable variable (INTERNAL_INTERFACES). This list grows every time the `interface.internal_interfaces` method is called.
This was fixed once before in the past but was introduced again. To try and prevent this from happening again, `INTERNAL_INTERFACES` has been converted to an immutable type. While I'm here, I've also converted `CLONED_PREFIXES` to an immutable type even though there were no instances where that was growing.

NAS-125012 / 24.04 / fix memory leak using mutable global variables

---

src/middlewared/middlewared/plugins/interface/internal_ifaces.py
src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
src/middlewared/middlewared/plugins/interface/netif_linux/utils.py
src/middlewared/middlewared/plugins/network.py

Revert b95d161c1c5b74f7391186cb80e6d369ee4965d6 since it's not a valid fix and only masks the real problem. The real problem is that a regression was introduced in f03e9fb8744684fa4f6aa0d978e2bb8dce26b458 whereby we keep `append`'ing and `extend`'ing the contents of the global mutable variable (INTERNAL_INTERFACES). This list grows every time the `interface.internal_interfaces` method is called.
This was fixed once before in the past but was introduced again. To try and prevent this from happening again, `INTERNAL_INTERFACES` has been converted to an immutable type. While I'm here, I've also converted `CLONED_PREFIXES` to an immutable type even though there were no instances where that was growing.
Original PR: https://github.com/truenas/middleware/pull/12441
Jira URL: …

NAS-125012 / 23.10.1 / fix memory leak using mutable global variables (by yocalebo)

---

src/middlewared/middlewared/alert/source/smb.py
src/middlewared/middlewared/plugins/audit/audit.py
src/middlewared/middlewared/plugins/audit/schema/smb.py
src/middlewared/middlewared/plugins/smb.py
src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py
src/middlewared/middlewared/plugins/smb_/status.py
tests/api2/test_420_smb.py

Now that we have centralized place for audit-style information, remove the handling whereby we wrote auth_audit events into a separate samba log file in favor of direct insertion into our auditing DB. If we need auth info from users, it is simple enough to just request a dump of it from them when troubleshooting.

NAS-124935 / 24.04 / Add SMB AUTHENTICATION audit events

---

src/middlewared/middlewared/plugins/smb.py

CLI help text gets mangled while formatting this.

NAS-125035 / 24.04 / Add an escape character to docstring for SMB

---

src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py

Why is this needed?
[Scenario](https://github.com/truenas/charts/issues/1687):
- User stops the application and there is an upgrade available.
- User clicks upgrade while the application is still stopped.
What is the issue?
Usually applications with databases may have a `pre-upgrade` hook to create a database dump before the application upgrade.
If the application is stopped and an upgrade is triggered, the hook will try to reach the database but the database is stopped. This will lead to a timeout from Helm (unless the script job exists with 0 and do not wait for ever for the database to respond), and the upgrade will be blocked.
This can be both a good and a bad thing.  The good thing is that the upgrade is blocked because a backup could not be created.
But what if the container is …

NAS-125042 / 24.04 / Add isStopped metadata to chart upgrade

---

src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py

Why is this needed?
[Scenario](https://github.com/truenas/charts/issues/1687):
- User stops the application and there is an upgrade available.
- User clicks upgrade while the application is still stopped.
What is the issue?
Usually applications with databases may have a `pre-upgrade` hook to create a database dump before the application upgrade.
If the application is stopped and an upgrade is triggered, the hook will try to reach the database but the database is stopped. This will lead to a timeout from Helm (unless the script job exists with 0 and do not wait for ever for the database to respond), and the upgrade will be blocked.
This can be both a good and a bad thing.  The good thing is that the upgrade is blocked because a backup could not be created.
But what if the container is …

NAS-125042 / 23.10.1 / Add isStopped metadata to chart upgrade (by stavros-k)

---

src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/service/__init__.py
src/middlewared/middlewared/service/core_service.py
src/middlewared/middlewared/service/decorators.py
tests/api2/test_account_privilege_role.py

There are situations where we want methods to be callable by all authenticated users whilst disallowing unauthenticated users. This commit adds a decorator `no_authz_required` to mirror existing `no_auth_required`.

NAS-125060 / 24.04 / Add no_authz_required fixture

---

src/middlewared/middlewared/plugins/filesystem.py
src/middlewared/middlewared/plugins/filesystem_/acl_base.py
src/middlewared/middlewared/plugins/filesystem_/acl_template.py
src/middlewared/middlewared/plugins/pool_/dataset_details.py
src/middlewared/middlewared/role.py
tests/api2/test_account_privilege_role.py

This commit adds filesystem specific roles, and grants FILESYSTEM_READ_ATTRS to the READONLY role since this is required to render many webui components. The SHARING_MANAGER role is granted FILESYSTEM_WRITE_ATTRS so that it is allowed to chown, setperm, setacl, etc.

NAS-125052 / 24.04 / Add roles to filesystem plugin

---

src/middlewared/middlewared/plugins/auth.py
tests/api2/test_account_privilege_role.py

The attributes dictionary contains webui preferences as determined
by the UI team. Users should be able to write to their own settings
regardless of privileges granted to them.

NAS-125067 / 24.04 / Always allow authenticated users to set webui prefs

---

src/middlewared/middlewared/plugins/cluster_linux/utils.py
src/middlewared/middlewared/plugins/directoryservices.py
src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/system/product.py

This allows all authenticated users to retrieve the following info:
* directory services state (HEALTHY, DISABLED, FAULTED)
* whether system is licensed for failover
* truenas version information
These are required for basic UI info on login

NAS-125070 / 24.04 / Allow all authenticated users to get basic state info

---

src/middlewared/middlewared/role.py

Constants were renamed during review process, and the item granting READONLY role ability to read file attributes was missed resulting in READONLY being unable to read filesystem-related attributes.

NAS-125084 / 24.04 / Fix typo in READONLY role

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
src/middlewared/middlewared/plugins/update_/utils.py

This simply catches up our CORE code-base with what we do in SCALE. We've fixed numerous bugs in update logic on SCALE but never back ported to CORE.
Original PR: https://github.com/truenas/middleware/pull/12457
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125088

NAS-125088 / 13.1 / fix failover.upgrade_pending and utils.can_update (by yocalebo)

---

src/middlewared/middlewared/plugins/vm/supervisor/supervisor.py

This commit adds changes to cover an exception traceback i noticed in one of the debugs. I was not able to reproduce the issue but changes have been made to safely retrieve this.
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/vm/memory.py", line 65, in get_memory_usage_internal
return self._memory_info(vm['name'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/vm/vm_supervisor.py", line 93, in _memory_info
return self.vms[vm_name].memory_usage()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/vm/supervisor/supervisor.py", line 92, in …
```

NAS-125126 / 24.04 / Safely get actual memory of a vm

---

src/middlewared/middlewared/plugins/vm/supervisor/supervisor.py

This commit adds changes to cover an exception traceback i noticed in one of the debugs. I was not able to reproduce the issue but changes have been made to safely retrieve this.
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/vm/memory.py", line 65, in get_memory_usage_internal
return self._memory_info(vm['name'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/vm/vm_supervisor.py", line 93, in _memory_info
return self.vms[vm_name].memory_usage()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/vm/supervisor/supervisor.py", line 92, in …
```

NAS-125126 / 23.10.1 / Safely get actual memory of a vm (by sonicaj)

---

src/middlewared/middlewared/auth.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/auth.py
tests/api2/test_account_privilege_role.py
tests/api2/test_api_key.py

When an administrator generates an API key they explicity whitelist one or more API methods that may be called via the key. This means that authorizations checks for API keys must always be strict to avoid unexpected access being granted.

NAS-125085 / 24.04 / Do not apply no_authz_required for API keys

---

src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/pytest/unit/plugins/test_interface.py

This commit adds changes to not allow changing an alias if it's being consumed by apps.

NAS-124761 / 24.04 / Do not allow changing an alias if it is being consumed by apps

---

src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/pytest/unit/plugins/test_interface.py

This commit adds changes to not allow changing an alias if it's being consumed by apps.
Original PR: https://github.com/truenas/middleware/pull/12471
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124761

NAS-124761 / 23.10.1 / Do not allow changing an alias if it is being consumed by apps (by sonicaj)

---

src/middlewared/middlewared/plugins/vm/pci.py

cli was causing an exception in middleware when it called call('core.get_methods', None, "CLI")

NAS-125184 / 24.04 / Fix cli breakage when it calls core.get_methods

---

src/middlewared/middlewared/plugins/idmap.py

Backend is required. This is set in SCALE, but change wasn't backported to Core / Enterprise.

NAS-124122 / 13.1 / Flag idmap domain backend as required for create

---

src/middlewared/middlewared/plugins/nfs.py
src/middlewared/middlewared/plugins/nfs_/krb5.py
src/middlewared/middlewared/plugins/nfs_/status.py
tests/api2/test_nfs_share_crud_roles.py

Added READ role to `nfs.client_count`
Added WRITE role to `nfs.add_principal`, `nfs.get_nfs3_clients` and `nfs.get_nfs4_clients`
Added can-READ CI tests for everything.
Added cannot-WRITE CI tests for everything
Added can-WRITE CI test for everything except `nfs.add_principal` as it requires more than trivial setup, it will be tested in other tests and the cannot-WRITE test is more important.

NAS-125057 / 24.04 / Add support for NFS roles

---

src/middlewared/middlewared/job.py
src/middlewared/middlewared/plugins/account_/privilege_utils.py
src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/service/core_service.py
src/middlewared/middlewared/utils/allowlist.py
tests/api2/test_account_privilege_role.py

This commit alters behavior of job-related core plugin methods in the following ways:
1. Authorization is no longer required for core.get_jobs, core.job_wait, and core.job_abort.
2. Non-admin users calling core.get_jobs will only receive info about their own jobs
3. Non-admin users will only be able to wait for, abort, or modify their own jobs
To achieve this a few minor changes were made:
1. Allowlist object now stores boolean indicating whether the allow list contained an unrestrained full access entry
2. TokenSessionManagerCredentials now contains a reference to the user info from the token's root (originating) credentials.
3. Job encoding now includes a `user` key that contains the username for user sessions. In case of API key or internal jobs, this will be None / null.

NAS-125187 / 24.04 / Allow limited users to interact with own jobs

---

src/middlewared/middlewared/plugins/smb.py
src/middlewared/middlewared/plugins/smb_/status.py
tests/api2/test_425_smb_protocol.py
tests/api2/test_smb_share_crud_roles.py

This allows properly authorized users to view / set SMB share ACL and view SMB status.

NAS-125055 / 24.04 / Add roles for SMB share ACL and status

---

src/middlewared/middlewared/plugins/pool_/utils.py

This PR adds the required change to include BLAKE3 as an option for checksum in dataset creation.
Original PR: https://github.com/truenas/middleware/pull/12493
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124749

NAS-124749 / 23.10.1 / Add BLAKE3 checksum option (by Qubad786)

---

src/middlewared/middlewared/plugins/account.py
tests/api2/test_011_user.py
tests/api2/test_428_smb_rpc.py

PAM session checks require that home directory actually exist, which is causing various CI tests to fail because the PAM check prevents su to the limited user account. /var/empty exists and is immutable, this has the side-benefit of preventing situations where pam_mkhomedir may try to create the directory /nonexistent leading to users sharing same writable home directory.

NAS-125216 / 24.04 / Switch default home path to /var/empty

---

debian/debian/ix-preinit.service
src/middlewared/middlewared/plugins/smb.py

At boot, smb.configure holds up waiting for the network subsystem to complete configuration.  To achieve this a sentinel file is generated at the completion of network configuration.  The sentinel file was removed after smb.configure detected it's presence.  However, without the sentinel subsequent calls to smb.update would stall (timeout waiting for the sentinel)
The sentinel file is created in /var/run/middleware. The /var/run/middleware directory is tmpfs and starts with zero files on every boot. We do not need to actively manage the removal of the ix-netif-sentinel. 
This change eliminates the stall on calling smb.update during runtime

NAS-125212 / 24.04 / fix smb.update stall waiting for sentinel file

---

src/middlewared/middlewared/plugins/boot.py
tests/api2/test_tunables.py

We sometimes need to toggle readonly when changing tunables.

NAS-125112 / 24.04 / Toggle readonly property on dataset underlying root 

---

tests/api2/test_smb_share_crud_roles.py

Some regressions were introduced due to missed cherry-pick back from testing branch that was being used in a jenkins run. This fixes some now-failing tests

NAS-125224 / 24.04 / Fix SMB roles CRUD tests

---

src/middlewared/middlewared/plugins/account.py

At present SMB authentication for local users requires some form of NT hash. User expectation of disabling password-based auth for local users on SMB access is ambiguous at best, and so we should just raise a ValidationError and have user make some other choices regarding parameter combination.
Original PR: https://github.com/truenas/middleware/pull/12488
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125109

NAS-125109 / 23.10.1 / Prevent password_disable for SMB users (by anodos325)

---

src/middlewared/middlewared/alert/source/volume_version.py

Placing this as a warning encourages users to upgrade pool when it's not really necessary and should be evaluated carefully by the administrator.
Original PR: https://github.com/truenas/middleware/pull/12299
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124584

NAS-124584 / 13.1 / Decrease alert priority of zpool upgrade to NOTICE (by anodos325)

---

tests/api2/test_475_syslog.py

This commit adds a basic test that setting a remote syslog target doesn't break syslog-ng. Proper functional tests are still needed.
Original PR: https://github.com/truenas/middleware/pull/12405
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124876

NAS-124876 / 23.10.1 / Add remote syslog test (by anodos325)

---

tests/api2/test_261_iscsi_cmd.py
tests/functions.py

The iSCSI test `test_19_alua_config` has passed reliably when run against real hardware, but equally failed on a regular basis when run (by [Jenkins](https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/HA%20API%20Tests%20-%20TrueNAS%20SCALE%20(Full%20-%20Nightly%20ISO)/)) against a bhyve-based HA VM pair.  Test timing issues either being exposed or not.
The typical failure was a socket timeout in `_get_node` called from `_ha_reboot_master`, shortly after the reboot call.  It is likely the controller is sent the request, but does not respond before rebooting.
This PR addresses this by adding a optional `timeout` our our test `GET` function, then supply a timeout when calling `_get_node` from `_ha_reboot_master`.
It also fixes a logic flaw (inverted check) wrt …

NAS-125226 / 24.04 / Robustize iSCSI HA ALUA test

---

tests/api2/test_011_user.py
tests/api2/test_020_account.py
tests/api2/test_ip_auth.py
tests/api2/test_keychain_ssh.py

* Disabling password auth on SMB users raises ValidationError
* PAM session management checks require that homedir exist

NAS-125231 / 24.04 / Fix broken API tests

---

src/middlewared/middlewared/plugins/sysctl/sysctl_info.py
src/middlewared/middlewared/plugins/vm/lifecycle.py
tests/api2/test_007_early_settings.py

Upstream ZFS removed the ARC MAX == 50% of available RAM recently. We need to update the VM plugin as well. Instead of halving memory in the VM plugin, we simply store the "default" ARC max value before we initialize any VMs. We use that as a high water mark since duplicating the openzfs logic inside middleware isn't the right approach (since upstream can change this calculation at any time)

NAS-124864 / 24.04 / properly toggle ARC sysctls

---

src/middlewared/middlewared/plugins/sysctl/sysctl_info.py
src/middlewared/middlewared/plugins/vm/lifecycle.py
tests/api2/test_007_early_settings.py

Upstream ZFS removed the ARC MAX == 50% of available RAM recently. We need to update the VM plugin as well. Instead of halving memory in the VM plugin, we simply store the "default" ARC max value before we initialize any VMs. We use that as a high water mark since duplicating the openzfs logic inside middleware isn't the right approach (since upstream can change this calculation at any time)
Original PR: https://github.com/truenas/middleware/pull/12504
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124864

NAS-124864 / 23.10.1 / properly toggle ARC sysctls (by yocalebo)

---

tests/api2/test_007_early_settings.py

(cherry picked from commit 6cc1fb1be706ccfc5a757fcca080eca6a0e206f5) I merged the master PR (https://github.com/truenas/middleware/pull/12504) but forgot to push my local commit which fixes the tests. No need for backport since I included this commit in the original backport.

NAS-125236 / 24.04 / remove import from middlewared.plugins in test_007

---

src/middlewared/middlewared/plugins/system/utils.py

Whenever a debug is generated, the archive file is named as `ixdiagnose-X` with X being iteration number of the attempt made to generate the debug however with the exception handling we have in place, it is almost always guarenteed to pass on the first attempt and having `-0` suffix is not helpful.
If on the first attempt debug generation succeeds, we don't add a suffix `-0` in that case to the debug archive name.

NAS-125040 / 24.04 / Fix debug archive name

---

src/middlewared/middlewared/plugins/system/utils.py

Whenever a debug is generated, the archive file is named as `ixdiagnose-X` with X being iteration number of the attempt made to generate the debug however with the exception handling we have in place, it is almost always guarenteed to pass on the first attempt and having `-0` suffix is not helpful.
If on the first attempt debug generation succeeds, we don't add a suffix `-0` in that case to the debug archive name.
Original PR: https://github.com/truenas/middleware/pull/12508
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125040

NAS-125040 / 23.10.1 / Fix debug archive name (by Qubad786)

---

docs/source/database/migrations.rst
src/middlewared/middlewared/alembic/versions/23.10/2023-11-10_23-19_add_exporting_table_for_reporting.py
src/middlewared/middlewared/alembic/versions/24.04/2023-09-06_14-45_cleanup_reporting_api.py
src/middlewared/middlewared/alembic/versions/24.04/2023-11-13_17-14_merge.py

With reporting exporter changes backported to cobia - a merge migration has been added to master and the migration also added to dragonfish.

NAS-125204 / 24.04 / Add cobia reporting exporter migration to dragonfish

---

src/middlewared/middlewared/alembic/versions/23.10/2023-11-10_23-19_add_exporting_table_for_reporting.py
src/middlewared/middlewared/etc_files/netdata/exporting.conf.mako
src/middlewared/middlewared/plugins/etc.py
src/middlewared/middlewared/plugins/reporting/export.py
src/middlewared/middlewared/plugins/reporting/exporters/base.py
src/middlewared/middlewared/plugins/reporting/exporters/factory.py
src/middlewared/middlewared/plugins/reporting/exporters/graphite.py
src/middlewared/middlewared/plugins/reporting/update.py

git cherry-pick -x 9da3c6a3b928c45d07a79e7f1e5053e5a7386085
git cherry-pick -x 4835d0121d465d704e676d252ba05264e3a3b991
It was requested that we add ability to export reporting data to graphite similar to what we used to do before and while we are doing this also make sure the approach is implementation agnostic so we can add more relevant export types as well.
Here changes have been made to the reporting system to ensure that the configuration aligns with the use of Netdata for reporting. Specifically, the reporting system is updated to support Netdata's metrics export to Graphite, as …

NAS-123668 / 23.10.1 / Enable exporting reporting data to graphite (by Qubad786)

---

src/middlewared/middlewared/alembic/versions/22.12/2023-01-17_15-29_fix-broken-idmap-table.py
src/middlewared/middlewared/plugins/idmap.py

Initial check in this migration was for primary key == 5. This has been hard-coded since FreeNAS 9.3, but in an early angelfish beta a code change was introduced that automatically deleted table entries to prevent update failures in some edge cases. This resulted in a required default idmap table entry being deleted for some users (the precise details are nuanced and covered in the related commits / jira tickets). The situation was rectified and a migration introduced to automatically re-add the missing table entry. It appears that in some cases, users manually added the entry back via shell, but didn't preserve the original primary key that was used to identify the special entry. This has resulted in a handful of users that are unable to upgrade.

NAS-119424 / 24.04 / Convert check for presence of DS_TYPE_DEFAULT_DOMAIN

---

src/middlewared/middlewared/etc_files/nfs.conf.d/local.conf.mako
tests/api2/test_300_nfs.py

Fixed a typo in the mako file that generated an incorrect setting for NFS bindip
Updated CI tests to confirm the resulting settings for bindip changes.
Also made a few opportunistic cleanup changes.

NAS-125251 / 24.04 / Fix scale NFS bindip setting

---

src/middlewared/middlewared/alembic/versions/22.12/2023-01-17_15-29_fix-broken-idmap-table.py
src/middlewared/middlewared/plugins/idmap.py

Initial check in this migration was for primary key == 5. This has been hard-coded since FreeNAS 9.3, but in an early angelfish beta a code change was introduced that automatically deleted table entries to prevent update failures in some edge cases. This resulted in a required default idmap table entry being deleted for some users (the precise details are nuanced and covered in the related commits / jira tickets). The situation was rectified and a migration introduced to automatically re-add the missing table entry. It appears that in some cases, users manually added the entry back via shell, but didn't preserve the original primary key that was used to identify the special entry. This has resulted in a handful of users that are unable to upgrade.
Original PR: …

NAS-119424 / 23.10.1 / Convert check for presence of DS_TYPE_DEFAULT_DOMAIN (by anodos325)

---

src/middlewared/middlewared/plugins/enclosure.py

QE found that the latest firmware provided by OEM changed a single character in the product name. (N -> V). By design, this prevents proper identification of the JBOD since, technically, the firmware changed. Platform team has given the "okay" to proceed by also adding this string as one to check for the ES102G2.

NAS-125258 / 24.04 / account for ES102G2 firmware change

---

src/middlewared/middlewared/plugins/enclosure.py

QE found that the latest firmware provided by OEM changed a single character in the product name. (N -> V). By design, this prevents proper identification of the JBOD since, technically, the firmware changed. Platform team has given the "okay" to proceed by also adding this string as one to check for the ES102G2.
Original PR: https://github.com/truenas/middleware/pull/12516
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125258

NAS-125258 / 23.10.1 / account for ES102G2 firmware change (by yocalebo)

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/enclosure_class.py

QE found that the latest firmware provided by OEM changed a single character in the product name. (N -> V). By design, this prevents proper identification of the JBOD since, technically, the firmware changed. Platform team has given the "okay" to proceed by also adding this string as one to check for the ES102G2.
Original PR: https://github.com/truenas/middleware/pull/12516
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125258

NAS-125258 / 13.0 / account for ES102G2 firmware change (by yocalebo)

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/enclosure_class.py

QE found that the latest firmware provided by OEM changed a single character in the product name. (N -> V). By design, this prevents proper identification of the JBOD since, technically, the firmware changed. Platform team has given the "okay" to proceed by also adding this string as one to check for the ES102G2.
Original PR: https://github.com/truenas/middleware/pull/12516
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125258

NAS-125258 / 13.1 / account for ES102G2 firmware change (by yocalebo)

---

src/middlewared/middlewared/alert/base.py
src/middlewared/middlewared/alert/service/slack.py
src/middlewared/middlewared/alert/source/ntp.py
src/middlewared/middlewared/alert/source/update.py
src/middlewared/middlewared/alert/source/vmware_login.py
src/middlewared/middlewared/plugins/system/debug_update_failed.py
src/middlewared/middlewared/plugins/update.py
src/middlewared/middlewared/plugins/update_/utils.py

This traceback occurred on a user running a nightly image when they tried to use the webUI to update.
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/update.py", line 310, in download_update
await self.middleware.call('alert.alert_source_clear_run', 'HasUpdate')
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1399, in call
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1353, in _call
return await self.run_in_executor(prepared_call.executor, methodobj, *prepared_call.args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1251, in run_in_executor
return await loop.run_in_executor(pool, …
```

NAS-125237 / 24.04 / fix regression in update.download_update

---

src/middlewared/middlewared/alert/base.py
src/middlewared/middlewared/alert/service/slack.py
src/middlewared/middlewared/alert/source/ntp.py
src/middlewared/middlewared/alert/source/update.py
src/middlewared/middlewared/alert/source/vmware_login.py
src/middlewared/middlewared/plugins/system/debug_update_failed.py
src/middlewared/middlewared/plugins/update.py
src/middlewared/middlewared/plugins/update_/utils.py

This traceback occurred on a user running a nightly image when they tried to use the webUI to update.
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/update.py", line 310, in download_update
await self.middleware.call('alert.alert_source_clear_run', 'HasUpdate')
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1399, in call
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1353, in _call
return await self.run_in_executor(prepared_call.executor, methodobj, *prepared_call.args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1251, in run_in_executor
return await loop.run_in_executor(pool, …
```

NAS-125237 / 23.10.1 / fix regression in update.download_update (by yocalebo)

---

src/middlewared/middlewared/plugins/kubernetes_linux/update.py

This PR adds changes to properly validate that the interface specified in apps settings for routing traffic, is actually "UP" at the time it is intended to be used as if the interface link state is down, that is bound to result in a failure when apps are going to try and configure themselves.

NAS-124930 / 24.04 / Properly validate interface selected with apps

---

src/middlewared/middlewared/plugins/kubernetes_linux/update.py

This PR adds changes to properly validate that the interface specified in apps settings for routing traffic, is actually "UP" at the time it is intended to be used as if the interface link state is down, that is bound to result in a failure when apps are going to try and configure themselves.
Original PR: https://github.com/truenas/middleware/pull/12515
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124930

NAS-124930 / 23.10.1 / Properly validate interface selected with apps (by sonicaj)

---

src/middlewared/middlewared/plugins/alert.py
src/middlewared/middlewared/utils/plugins.py

1. micro-optimize `load_modules()`
2. stop blocking main event loop in `alert.load`

NAS-125269 / 24.04 / micro-optimize load_modules and unblock alert.load

---

src/middlewared/middlewared/plugins/alert.py
src/middlewared/middlewared/utils/plugins.py

1. micro-optimize `load_modules()`
2. stop blocking main event loop in `alert.load`
Original PR: https://github.com/truenas/middleware/pull/12524
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125269

NAS-125269 / 23.10.1 / micro-optimize load_modules and unblock alert.load (by yocalebo)

---

src/middlewared/middlewared/plugins/keychain.py

Fix many issues:
1. stop blocking main event loop in `validate_and_pre_save` methods
2. stop blocking main event loop in `ssh_pair` method
3. fix TOCTOU issue in `ssh_pair`
4. use `MatchNotFound` exception instead of `IndexError`
Original PR: https://github.com/truenas/middleware/pull/12527
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125275

NAS-125275 / 23.10.1 / Stop blocking main event loop in keychain plugin (by yocalebo)

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/filesystem.py
tests/api2/test_190_filesystem.py

These specific calls to os.mkdir can be replaced by filesystem.mkdir API calls. This is to help standardize local filesystem access. Currently the filesystem.mkdir API lacks ability to specify mode when creating a file, but in this case it was deemed redundant since the mkdir operation is subsequently followed by a filesystem.setperm call.

NAS-123754 / 24.04 / Plumb mkdir operations through filesystem.mkdir

---

src/freenas/usr/lib/systemd/system-preset/10-truenas.preset
src/middlewared/middlewared/plugins/service_/services/ups.py

Upstream introduced `nut.target` unit, which was not present in codebase previously upstream.
Inclusion of `nut.target` and its default enabling on fresh install caused `nut-monitor` service to start automatically even if it was disabled. 
The issue is fixed by disabling the `nut.target` in preset and grouping it to start with the start of UPS service.

NAS-124824 / 24.04 / UPS service auto start fix

---

src/freenas/usr/lib/systemd/system-preset/10-truenas.preset
src/middlewared/middlewared/plugins/service_/services/ups.py

Upstream introduced `nut.target` unit, which was not present in codebase previously upstream.
Inclusion of `nut.target` and its default enabling on fresh install caused `nut-monitor` service to start automatically even if it was disabled. 
The issue is fixed by disabling the `nut.target` in preset and grouping it to start with the start of UPS service.
Original PR: https://github.com/truenas/middleware/pull/12521
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124824

NAS-124824 / 23.10.1 / UPS service auto start fix (by Qubad786)

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/filesystem.py
tests/api2/test_190_filesystem.py

These specific calls to os.mkdir can be replaced by filesystem.mkdir API calls. This is to help standardize local filesystem access. Currently the filesystem.mkdir API lacks ability to specify mode when creating a file, but in this case it was deemed redundant since the mkdir operation is subsequently followed by a filesystem.setperm call.
Original PR: https://github.com/truenas/middleware/pull/11969
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123754

NAS-123754 / 23.10.1 / Plumb mkdir operations through filesystem.mkdir (by anodos325)

---

src/freenas/usr/local/libexec/smart_alert.py
src/middlewared/middlewared/plugins/device_/device_info.py

The automatic alert that we generate in `smart_alert.py` (called by `smartd`) only gives the block device name (i.e. `/dev/sda`). Those names change frequently so we need to try and append the serial number of the drive. This does that by doing 2 things:
1. fix the `device.get_disk` api to match `device.get_disks`
2. call `device.get_disk` in `smart_alert.py` and add the serial number information to the alert

NAS-125274 / 24.04 / add serial number information to smart alert (if possible)

---

src/freenas/usr/local/libexec/smart_alert.py
src/middlewared/middlewared/plugins/device_/device_info.py

The automatic alert that we generate in `smart_alert.py` (called by `smartd`) only gives the block device name (i.e. `/dev/sda`). Those names change frequently so we need to try and append the serial number of the drive. This does that by doing 2 things:
1. fix the `device.get_disk` api to match `device.get_disks`
2. call `device.get_disk` in `smart_alert.py` and add the serial number information to the alert
Original PR: https://github.com/truenas/middleware/pull/12528
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125274

NAS-125274 / 23.10.1 / add serial number information to smart alert (if possible) (by yocalebo)

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/filesystem.py

NAS-123754 among other things slightly refactored how new user home directories were created so that internal middleware filesystem.mkdir was used instead of os.mkdir. This was missed in limited CI run prior to merge.

NAS-125285 / 24.04 / Fix regression caused by typo in NAS-123754

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/filesystem.py

This fixes string being used for path in mkdir request in accounts plugin and also makes error handling configurable of filesystem.mkdir requests. In case of chmod failure during filesystem.mkdir processing API user can either ignore errors (but will have to do own validation that the `mode` in response is acceptable), or allow backend to raise an exception on chmod failure (in which case newly-created directory will be removed to prevent its use).

NAS-125285 / 23.10.1 / Fix regression caused by typo in NAS-123754 (#12534)

---

src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py

When the system is down, Netdata normalizes that time interval with zero, ultimately affecting min-max values in aggregation.
To address this, a `skip_zero` flag has been added in aggregation. This flag ensures that zero values are not considered when determining min-max values. This is particularly effective for reporting charts where values cannot be zero, such as temperature.

NAS-124784 / 24.04 / Skip zero values when determining aggregated values in reporting

---

src/middlewared/middlewared/plugins/enclosure.py

The ES60G2's firmware was updated but our string matching is a bit too strict and matches the specific firmware revision. This removes the firmware revision portion of the string at bequest of platform team.

NAS-125287 / 24.04 / fix ES60G2 enclosure identification (FW change)

---

src/middlewared/middlewared/plugins/enclosure.py

The ES60G2's firmware was updated but our string matching is a bit too strict and matches the specific firmware revision. This removes the firmware revision portion of the string at bequest of platform team.
Original PR: https://github.com/truenas/middleware/pull/12538
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125287

NAS-125287 / 23.10.1 / fix ES60G2 enclosure identification (FW change) (by yocalebo)

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/enclosure_class.py

The ES60G2's firmware was updated but our string matching is a bit too strict and matches the specific firmware revision. This removes the firmware revision portion of the string at bequest of platform team.
Original PR: https://github.com/truenas/middleware/pull/12538
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125287

NAS-125287 / 13.1 / fix ES60G2 enclosure identification (FW change) (by yocalebo)

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/enclosure_class.py

The ES60G2's firmware was updated but our string matching is a bit too strict and matches the specific firmware revision. This removes the firmware revision portion of the string at bequest of platform team.
Original PR: https://github.com/truenas/middleware/pull/12538
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125287

NAS-125287 / 13.0 / fix ES60G2 enclosure identification (FW change) (by yocalebo)

---

src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py

git cherry-pick -x b101da1b1f939b60662cd1224c5e2587f1f621cf
git cherry-pick -x 24a08ecd8393f59aeecdcfcc4e68cfbe554f1d8e
When the system is down, Netdata normalizes that time interval with zero, ultimately affecting min-max values in aggregation.
To address this, a `skip_zero` flag has been added in aggregation. This flag ensures that zero values are not considered when determining min-max values. This is particularly effective for reporting charts where values cannot be zero, such as temperature.
Original PR: https://github.com/truenas/middleware/pull/12532
Jira URL: …

NAS-124784 / 23.10.1 / Skip zero values when determining aggregated values in reporting (by Qubad786)

---

src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/plugins/reporting/events.py
src/middlewared/middlewared/plugins/reporting/realtime_reporting/ifstat.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_stats_func.py

**Problem:**
When reporting network statistics in the `realtime.reporting` event, the rate of change is miscalculated. Currently, the calculation involves dividing the current value by the interval, but it should be the difference between the current and old values at the current time minus the interval. The interval should remain constant.
**Solution:**
To address this, the solution involves querying the current value from Netdata along with the old value, which is from seconds equal to the interval in the past. The difference between these values is then calculated to accurately report the change in network statistics.

NAS-125139 / 24.04 / Fix network send/receive rate

---

src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
tests/api2/test_340_pool_dataset.py

This allows our apps framework to specify FULL_CONTROL for POSIX ACL. We can't _actually_ give FULL_CONTROL to a user or group under POSIX1E ACLs (only owner will be able to chown / chmod), but this makes error handling easier in the apps framework.

NAS-124980 / 24.04 / Allow FULL_CONTROL for POSIX ACL in add_to_acl

---

src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
tests/api2/test_340_pool_dataset.py

This allows our apps framework to specify FULL_CONTROL for POSIX ACL. We can't _actually_ give FULL_CONTROL to a user or group under POSIX1E ACLs (only owner will be able to chown / chmod), but this makes error handling easier in the apps framework.
Original PR: https://github.com/truenas/middleware/pull/12545
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124980

NAS-124980 / 23.10.1 / Allow FULL_CONTROL for POSIX ACL in add_to_acl (by anodos325)

---

src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/plugins/reporting/events.py
src/middlewared/middlewared/plugins/reporting/realtime_reporting/ifstat.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_stats_func.py

**Problem:**
When reporting network statistics in the `realtime.reporting` event, the rate of change is miscalculated. Currently, the calculation involves dividing the current value by the interval, but it should be the difference between the current and old values at the current time minus the interval. The interval should remain constant.
**Solution:**
To address this, the solution involves querying the current value from Netdata along with the old value, which is from seconds equal to the interval in the past. The difference between these values is then calculated to accurately report the change in network statistics.
Original PR: https://github.com/truenas/middleware/pull/12502
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125139

NAS-125139 / 23.10.1 / Fix network send/receive rate (by Qubad786)

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/filesystem.py
src/middlewared/middlewared/test/integration/assets/filesystem.py
tests/api2/test_190_filesystem.py
tests/api2/test_300_nfs.py

This shifts some tests from REST to websocket calls (general incremental improvements to our testing), adds ability to use new options in our `directory` test asset, and allows creating .ssh directory for root and admin users (which are not under /mnt).

NAS-125291 / 24.04 / Fix failing CI tests that were due to filesystem.mkdir chanages

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

This adds the new firmware (identified during QE cycle) to the enclosure2 namespace. Was explicitly done in a separate PR so ticket tracking could be kept separate since the original PR was back ported all the way back to 13.0 but enclosure2 only exists in Cobia/DF.

add new firmware for ES60G2 to enclosure2

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/filesystem.py
src/middlewared/middlewared/test/integration/assets/filesystem.py
tests/api2/test_190_filesystem.py

This shifts some tests from REST to websocket calls (general incremental improvements to our testing), adds ability to use new options in our `directory` test asset, and allows creating .ssh directory for root and admin users (which are not under /mnt).
Original PR: https://github.com/truenas/middleware/pull/12546
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125291

NAS-125291 / 23.10.1 / Fix failing CI tests that were due to filesystem.mkdir chanages (by anodos325)

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

This adds the new firmware (identified during QE cycle) to the enclosure2 namespace. Was explicitly done in a separate PR so ticket tracking could be kept separate since the original PR was back ported all the way back to 13.0 but enclosure2 only exists in Cobia/DF.
Original PR: https://github.com/truenas/middleware/pull/12553
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125310

NAS-125310 / 23.10.1 / add new firmware for ES60G2 to enclosure2 (by yocalebo)

---

src/middlewared/middlewared/plugins/reporting/realtime_reporting/ifstat.py

For backwards compatibility due to UI changes involved we are adding `received_bytes/sent_bytes` keys back reflecting `bytes/sec` values.

NAS-125311 / 23.10.1 / Add back received/sent bytes keys

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

This fixes the R50 series platform in the new enclosure2 code. I'm working on adding tests in another PR and will push those soon which will, in theory, catch situations like this.
Original PR: https://github.com/truenas/middleware/pull/12556
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125324

NAS-125324 / 23.10.1 / fix R50 in enclosure2 (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/map2.py
src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py

The R40 has to be handled specially because of a mishap with HBA firmware flashing.
Original PR: https://github.com/truenas/middleware/pull/12559
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125262

NAS-125262 / 23.10.1 / add special handling for R40 in enclosure2 (by yocalebo)

---

cluster-tests/tests/cleanup/test_cluster_cleanup.py
src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py
src/middlewared/middlewared/plugins/gluster_linux/peer.py

This simplifies cluster cleanup for the TrueCommand team for the highly unusual case where a user has deployed a TrueNAS cluster and wants to rip out the clustering configuration without a full server OS reinstall or rolling back from snapshot. Such a situation may occur as part of CI pipelines where clustering is repeatedly configured and torn down without server reinstalls.

NAS-125252 / 24.04 / Remove node from TSP during ctdb teardown

---

src/freenas/etc/ix.rc.d/ix-nfsbind
src/middlewared/middlewared/plugins/nfs.py

The NFS bindip cannot be configured if the selected IP address is not functional.  This setting is in `/etc/rc.conf.freebsd`.  NFS is started and configured _before_ the network is started.  NFS has a post network start event handler that will restrart NFS if bindip is configured in the DB.
However, the NFS bindip _setting_ was blocked at boot during the initial configuration run because the network subsystem had not yet completed startup.  This resulted in no NFS bindip configuration.
In the post network start handler, regenerate `rc.conf.freebsd` before restarting NFS.

NAS-125048 / 13.1 / Fix NFS bindip configuration at boot

---

cluster-tests/tests/cleanup/test_cluster_cleanup.py
src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py
src/middlewared/middlewared/plugins/gluster_linux/peer.py

This simplifies cluster cleanup for the TrueCommand team for the highly unusual case where a user has deployed a TrueNAS cluster and wants to rip out the clustering configuration without a full server OS reinstall or rolling back from snapshot. Such a situation may occur as part of CI pipelines where clustering is repeatedly configured and torn down without server reinstalls.
Original PR: https://github.com/truenas/middleware/pull/12557
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125252

NAS-125252 / 23.10.1 / Remove node from TSP during ctdb teardown (by anodos325)

---

tests/api2/test_190_filesystem.py

This commit fixes some broken filesystem tests and also expands testing for filesystem.mkdir endpoint so that behavior of raise_chmod_error is validated.

NAS-125336 / 24.04 / Expand tests for filesystem.mkdir

---

tests/api2/test_190_filesystem.py

This commit fixes some broken filesystem tests and also expands testing for filesystem.mkdir endpoint so that behavior of raise_chmod_error is validated.
Original PR: https://github.com/truenas/middleware/pull/12565
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125336

NAS-125336 / 23.10.1 / Expand tests for filesystem.mkdir (by anodos325)

---

src/middlewared/middlewared/plugins/smb.py
tests/api2/test_428_smb_rpc.py

TrueNAS SMB share name validation allowed invalid characters, which
resulted in share that was created being rejected by libsmbconf.
This commit validates that share name minimally meets requirements
from MS-FSCC 2.1.6
```
* A share name MUST be no more than 80 characters in length.
* The following characters are illegal in a share name:
" \ / [ ] : | < > + = ; , * ?
* Control characters in range 0x00 through 0x1F, inclusive, are illegal in a share name.
* All other Unicode characters are legal.
```
Extended requirements for TrueNAS are as follows:
* the % (percent) character is also illegal
* all unicode control characters are prohibited

NAS-125335 / 24.04 / Add validation for SMB share name

---

src/middlewared/middlewared/plugins/vm/usb.py

Certain valid USB devices are being filtered out because their vendor/product ID contains only the ID without accompanying text. The vendor and product IDs are what make these devices valid.
Remove the condition that checks for the availability of text in the vendor/product ID filter to include these devices.
Sample xml
```
<device>
<name>usb_1_14</name>
<path>/sys/devices/pci0000:00/0000:00:14.0/usb1/1-14</path>
<devnode type='dev'>/dev/bus/usb/001/007</devnode>
<parent>usb_usb1</parent>
<driver>
<name>usb</name>
</driver>
<capability type='usb_device'>
<bus>1</bus>
<device>7</device>
<product id='0x0032' />
<vendor id='0x8087'>Intel Corp.</vendor>
</capability>
</device>
```
Original PR: https://github.com/truenas/middleware/pull/12571
Jira URL: …

NAS-125381 / 23.10.2 / Allow valid usb devices where their text is null (by Qubad786)

---

src/middlewared/middlewared/plugins/auth.py

Seen in CI run:
```
2023/11/27 12:45:07] (ERROR) middlewared.call_hook():1314 - Failed to run hook core.on_connect:<function check_permission at 0x7fa38de4fe20>(*(), **{'app': <middlewared.main.Application object at 0x7fa32ed976d0>})
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1307, in call_hook
await fut
File "/usr/lib/python3/dist-packages/middlewared/plugins/auth.py", line 652, in check_permission
'username': await middleware.call(
^^^^^^^^^^^^^^^^
TypeError: 'coroutine' object is not subscriptable
```

NAS-125391 / 24.04 / Fix crash in auth plugin

---

src/middlewared/middlewared/plugins/filesystem_/acl_base.py
src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
src/middlewared/middlewared/plugins/pool_/dataset.py
src/middlewared/middlewared/pytest/unit/plugins/test_acl_inherit.py
tests/api2/test_345_acl_nfs4.py

Webui team requested ability to also specify NFS share_type. At present it is identical to multiprotocol share.
This PR also fixes a longstanding issue with using share_type preset to create a child of an existing NFSv4 dataset that has an ACL already set. In this edge-case we will now generate an inherited ACL based on the parent dataset's ACL (with a few modifications) rather than applying a default to it.

NAS-125304 / 24.04 / Add NFS share_type and ability to get inherited ACL

---

tests/api2/test_300_nfs.py

We need to ensure that the `NFSblockedByExportsDir` alert does NOT exist. not merely that another event exists.

NAS-125397 / 24.04 / Fix check that alert should have been cleared

---

src/middlewared/middlewared/plugins/chart_releases_linux/validation.py
src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
tests/api2/test_chart_release_acl_apply.py

Applying ACL to a non-empty path with force flag disabled gives a traceback of error message.
This PR will add the change to handle validation more appropriately and raise a friendly error message for user.

NAS-125106 / 24.04 / Allow specifying force flag for ACL based questions

---

tests/api2/test_011_user.py
tests/api2/test_020_account.py
tests/api2/test_ip_auth.py
tests/api2/test_keychain_ssh.py

* Disabling password auth on SMB users raises ValidationError
* PAM session management checks require that homedir exist

NAS-125418 / 23.10.2 / Fix broken API tests (#12501)

---

tests/api2/test_030_activedirectory.py

The particular test causing regression in cobia pipeline was removed as part of refactor of AD test in dragonfish nightlies.
Backporting full change that removed the test would be more impactful than desired for existing stable branch.

Remove ad_bindpw key from ActiveDirectory API test

---

tests/api2/test_audit.py

This test validates that our filter for special audit messages is not letting things through to /var/log/messages and /var/log/syslog.

NAS-125422 / 24.04 / Add test syslog filter

---

src/middlewared/middlewared/plugins/smb_/status.py

Add configurable option (defaulting to True) to resolve uids to usernames in smbstatus output.

NAS-125442 / 24.04 / Default to showing usernames in smb.status output

---

src/middlewared/middlewared/plugins/dlm.py

`dlm` had some `failover.remote_on_disconnect` processing that (ended up) **only** being used to log.  (The main control was thru the processing of udev events)

NAS-125431 / 24.04 / Eliminate log spam as a result of failover.remote_on_disconnect events

---

src/middlewared/middlewared/plugins/dlm.py

`dlm` had some `failover.remote_on_disconnect` processing that (ended up) **only** being used to log.  (The main control was thru the processing of udev events)
Original PR: https://github.com/truenas/middleware/pull/12594
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125431

NAS-125431 / 23.10.2 / Eliminate log spam as a result of failover.remote_on_disconnect events (by bmeagherix)

---

src/middlewared/middlewared/plugins/failover.py

6a4cbadaff410c88838b4d3f1c1e42993dbe0c04 introduced a regression with breaks HA connections across the heartbeat interface.

NAS-125449 / 24.04 / fix HA authentication

---

src/middlewared/middlewared/plugins/idmap.py
tests/api2/test_035_ad_idmap.py

Typo during fix of several methods related to idmap bulk operations caused regression in middleware AD authentication. This commit fixes regression and adds coverage for private idmap endpoints that do bulk conversion of SIDS to Unix IDs.

NAS-125457 / 24.04 / Fix regression in AD privilege authentication

---

tests/api2/test_020_account.py
tests/api2/test_210_group.py

Add CI test for existence of and expected gid for groups `nogroup` and `nobody`

NAS-125466 / 24.04 / Add CI test for nobody group

---

src/middlewared/middlewared/etc_files/group.mako
tests/api2/test_210_group.py

Adding some FreeBSD compatibility with regard to group name nobody caused behavior change where 65534 resolved to the FreeBSD group nobody rather than the Linux group nogroup.

NAS-125469 / 24.04 / Ensure that gid 65534 resolves to nogroup

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/smb.py
src/middlewared/middlewared/plugins/smb_/groupmap.py
src/middlewared/middlewared/plugins/smb_/passdb.py
tests/api2/test_011_user.py

We should not proceed with passdb and groupmap synchronization if SMB has not been properly configured. Passdb interaction in a broken state can lead to SMB_ASSERT() in pdbedit and other tools due to global sam sid failing to initialize (possibly due to missing path components).
In case of creating user / group this should raise ValidationError.
NOTE: these exceptions will not be user-facing unless in very unusual circumstances (like broken system dataset configuration) and so their primary purpose is to focus developer attention on root cause.

NAS-125481 / 24.04 / Raise exceptions if SMB not configured

---

src/middlewared/middlewared/pytest/unit/test_schema.py
src/middlewared/middlewared/schema/string_schema.py

We should allow dashes in netbios names.

NAS-125485 / 24.04 / Fix overly-strict netbios name regex

---

src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnfilters.conf.mako
src/middlewared/middlewared/plugins/etc.py
src/middlewared/middlewared/plugins/nfs.py
tests/api2/test_300_nfs.py

Recent Linux kernels generate a log message for every client mount and umount and each running mountd repeats the message.
This can generate substantial amount of log traffic.  The PR provides the ability to disable the high-volume messages.
The `mountd_log` setting in nfs.config is used as the enable/disable flag, where `True` enables the mountd logging and `False` disables mountd logging.  In both states, error and higher priority messages from mountd will still be logged.
Logging is enabled in the current default state.  Logging can be disabled with: `midclt call nfs.config '{"mountd_log": true}'`

NAS-125388 / 24.04 / Disable rpc.mountd logging with mountd_log NFS config setting

---

src/middlewared/middlewared/plugins/account.py

This corrects an oversight when adding roles to user.query results in which only auxiliary group roles were added.

NAS-125496 / 24.04 / Add primary-group roles to user.query output

---

src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py

This change allows TrueCommand to bypass sanity check for wiping cluster config in case of failed cluster creation.

NAS-125491 / 24.04 / Allow `force` to bypass check for ctdb root dir

---

src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py

This change allows TrueCommand to bypass sanity check for wiping cluster config in case of failed cluster creation.
Original PR: https://github.com/truenas/middleware/pull/12617
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125491

NAS-125491 / 23.10.2 / Allow `force` to bypass check for ctdb root dir (by anodos325)

---

src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py

This change allows TrueCommand to bypass sanity check for wiping cluster config in case of failed cluster creation.
Original PR: https://github.com/truenas/middleware/pull/12617
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125491

NAS-125491 / 23.10.1 / Allow `force` to bypass check for ctdb root dir (by anodos325)

---

src/middlewared/middlewared/plugins/system/__init__.py

This BE is not used by support department or other parts of company and its overall utility is questionable. Most of value is already covered by us snapshotting the relevant BE datasets during the ISO / update install process.

NAS-125393 / 24.04 / Remove logic to create initial-install BE on first boot

---

src/middlewared/middlewared/plugins/etc.py
src/middlewared/middlewared/plugins/nfs.py

Fix two issues: 
-  change `nfs.query` to `nfs.config`
-  use middleware call to `service.reload`

NAS-125506 / 24.04 / Fix the NFS syslog filter config

---

src/middlewared/middlewared/plugins/account_/privilege.py

Currently the default administrator privilege in TrueNAS has wildcard allowlist without explicitly specifying roles configuraiton. This is sufficient for proper behavior from backend perspective, but is less than fully clear from API consumer perspective if they only look at the roles set. This commit maps the wildcard allowlist entry to FULL_ADMIN in roles set to make the actual permissions clearer.

NAS-125498 / 24.04 / Always map wildcard allowlist to FULL_ADMIN

---

cluster-tests/tests/cleanup/test_cluster_cleanup.py

This commit adds a test to run ctdb.root_dir.teardown job when cluster is already torn down to validate that forcing cleanup succeeds. This force behavior was added for TrueCommand team to allow them to reset from a failed cluster configuration.
Original PR: https://github.com/truenas/middleware/pull/12626
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125503

NAS-125503 / 23.10.2 / Add test for forcing ctdb teardown (by anodos325)

---

src/middlewared/middlewared/pytest/unit/test_validators.py
src/middlewared/middlewared/validators.py

Who would have thought how miserable email address validation could be....I sure didn't until I started doing research. Instead of trying to validate all conceivable incantations of the various RFC's wrt to email addresses, we take the other approach of being less strict so we don't have a false-negative (i.e. preventing a valid email address) which is what our current code does.
Original PR: https://github.com/truenas/middleware/pull/12618
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125483
Original PR: https://github.com/truenas/middleware/pull/12619
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125483

NAS-125483 / 13.1 / fix Email schema class (by yocalebo) (by bugclerk)

---

src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/plugins/system/info.py
src/middlewared/middlewared/plugins/system/product.py
tests/api2/test_auth_me.py

* Allow all authorized users to gather some basic hardware info.
* Allow all authenticated users to see their own 2fa config via auth.me.

NAS-125533 / 24.04 / Relax authorization requirements

---

src/middlewared/middlewared/plugins/account_/privilege_roles.py
src/middlewared/middlewared/role.py

Some roles exist for internal backend RBAC purposes and should be flagged as such so that webui can de-emphasize.

NAS-125540 / 24.04 / Add flag indicating whether role is builtin

---

tests/api2/test_200_ftp.py

Added 'flaky' decorator with retries.
Widened the acceptance range from +8KB to +20KB
Fix flake8 issues.

NAS-125546 / 24.04 / Make the bandwidth test more resilient.

---

src/middlewared/middlewared/plugins/filesystem_/acl_base.py
src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
tests/api2/test_300_nfs.py
tests/protocols/nfs_proto.py

Add initial testing for NFSv4.1 `acl_flag`
This is done by enhancing test_43_check_nfsv4_acl_support to handle multiple NFS versions (NFSv4.2, NFSv4.1 & NFSv4.0) and then test setting each available value (`auto-inherit`, `protected`, `defaulted`) for `acl_flag`.
Add missing `defaulted` support to our middleware filesystem plugin (for test purposes).
----
**NOTE:** This PR is **WIP** for the time being, until the underlying linux kernel [PR](https://github.com/truenas/linux/pull/142) lands.

NAS-123903 / 24.04 / Add initial test support for NFSv41 acl_flag

---

src/middlewared/middlewared/plugins/boot.py

This regressed in fa7d871b579. Changes introduced there don't take into account that we don't enforce any type of sanity on zpool names. So a zpool created with a space in the name produces the below error. Luckily, `zpool -H` flag always separates the values by tab so we can safely split on tab instead of space.
As a final precaution, however, I wrap it in an `try: except` block so we don't crash here since it's not fatal that we don't apply this setting on middleware start-up. Instead we'll log an error message so we can review them in debug archives and fix the various issues as we come across them.
```
[2023/12/04 11:31:02] (TRACE) middlewared.trace():46 - _console_write 'setting up plugins (boot) [5/109]'
File "/usr/bin/middlewared", line 12, in …
```

NAS-125550 / 23.10.2 / fix regression in boot.py:setup() (by yocalebo)

---

tests/api2/test_chart_release_acl_apply.py

Earlier we were creating a file but it was being done on the runner and not the actual NAS where it should have been created.
Make sure we create the file on the NAS itself and not the runner.

NAS-125557 / 24.04 / Fix ACL flag integration test in apps

---

src/middlewared/middlewared/plugins/usage_/firstboot.py

There is no reason to log the entire call stack here. It's actually quite large (since it eventually goes through aiohttp). I'm investigating an unrelated issue and the system I'm on obviously fails here because there are no DNS servers by the time this is called.

NAS-125558 / 24.04 / dont exc_info=True in usage_/firstboot.py

---

src/middlewared/middlewared/plugins/usage_/firstboot.py

There is no reason to log the entire call stack here. It's actually quite large (since it eventually goes through aiohttp). I'm investigating an unrelated issue and the system I'm on obviously fails here because there are no DNS servers by the time this is called.
Original PR: https://github.com/truenas/middleware/pull/12642
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125558

NAS-125558 / 23.10.1 / dont exc_info=True in usage_/firstboot.py (by yocalebo)

---

src/middlewared/middlewared/plugins/reporting/netdata/client.py
src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py

These endpoints are called incessantly (especially on our HA systems) so doing exc_info=True is entirely too verbose and just fills up `middlewared.log` I noticed this on an internal HA system for which I'm investigating an unrelated problem.

NAS-125559 / 24.04 / stop more netdata connection log spam

---

src/middlewared/middlewared/plugins/reporting/netdata/client.py
src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py

These endpoints are called incessantly (especially on our HA systems) so doing exc_info=True is entirely too verbose and just fills up `middlewared.log` I noticed this on an internal HA system for which I'm investigating an unrelated problem.
Original PR: https://github.com/truenas/middleware/pull/12643
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125559

NAS-125559 / 23.10.1 / stop more netdata connection log spam (by yocalebo)

---

src/middlewared/middlewared/plugins/idmap.py
tests/api2/test_275_ldap.py

This fixes a broken LDAP authentication test and adds error handling for edge case LDAP configurations where idmap.known_domains will not be possible.

NAS-125566 / 24.04 / Fix LDAP middleware authentication tests

---

src/middlewared/middlewared/plugins/idmap.py
tests/api2/test_275_ldap.py

This fixes a broken LDAP authentication test and adds error handling for edge case LDAP configurations where idmap.known_domains will not be possible.
Original PR: https://github.com/truenas/middleware/pull/12650
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125566

NAS-125566 / 23.10.2 / Fix LDAP middleware authentication tests (by anodos325)

---

src/middlewared/middlewared/plugins/chart_releases_linux/events.py

More log spam that just fills up middlewared.log.
Original PR: https://github.com/truenas/middleware/pull/12657
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125581

NAS-125581 / 23.10.1 / prevent more log spam (by yocalebo)

---

src/middlewared/middlewared/plugins/chart_releases_linux/events.py

More log spam that just fills up middlewared.log.
Original PR: https://github.com/truenas/middleware/pull/12657
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125581

NAS-125581 / 23.10.2 / prevent more log spam (by yocalebo)

---

src/middlewared/middlewared/plugins/kubernetes_linux/k8s/client.py

Our k8s client caches k3s certificates used to make requests to kube-api server, however we run into problems in the case when those certs are about to expire and k3s auto-rotates them on it's own. In that case we run into client connection errors because the cert we specify is not valid and this has been gracefully handled to remove the cache we have and get latest certs which are to be used for the request.

NAS-125579 / 24.04 / Make sure we gracefully handle certificate rotation for k3s

---

src/middlewared/middlewared/plugins/acme_protocol.py
src/middlewared/middlewared/plugins/mail.py
src/middlewared/middlewared/plugins/truecommand/connection.py
src/middlewared/middlewared/plugins/vmware_/snapshot_delete.py

This entire feature wasn't designed/thought about very well. It's flawed in many aspects but without the changes in this PR we're spamming our log files when someone does `Deny All` (even though that's not actually happening) in the webUI.
This squashes the most obvious log spam use-cases. (This was found on an internal HA system for which I'm troubleshooting an unrelated issue)

NAS-125562 / 24.04 / Fix more log spam (network activity feature)

---

src/middlewared/middlewared/plugins/acme_protocol.py
src/middlewared/middlewared/plugins/mail.py
src/middlewared/middlewared/plugins/truecommand/connection.py
src/middlewared/middlewared/plugins/vmware_/snapshot_delete.py

This entire feature wasn't designed/thought about very well. It's flawed in many aspects but without the changes in this PR we're spamming our log files when someone does `Deny All` (even though that's not actually happening) in the webUI.
This squashes the most obvious log spam use-cases. (This was found on an internal HA system for which I'm troubleshooting an unrelated issue)
Original PR: https://github.com/truenas/middleware/pull/12645
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125562

NAS-125562 / 23.10.1 / Fix more log spam (network activity feature) (by yocalebo)

---

src/middlewared/middlewared/plugins/acme_protocol.py
src/middlewared/middlewared/plugins/mail.py
src/middlewared/middlewared/plugins/truecommand/connection.py
src/middlewared/middlewared/plugins/vmware_/snapshot_delete.py

This entire feature wasn't designed/thought about very well. It's flawed in many aspects but without the changes in this PR we're spamming our log files when someone does `Deny All` (even though that's not actually happening) in the webUI.
This squashes the most obvious log spam use-cases. (This was found on an internal HA system for which I'm troubleshooting an unrelated issue)
Original PR: https://github.com/truenas/middleware/pull/12645
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125562

NAS-125562 / 23.10.2 / Fix more log spam (network activity feature) (by yocalebo)

---

src/middlewared/middlewared/plugins/nfs_/status.py

READONLY is being treated as conferring administrative-level privileges to the server (ability to see unredacted sensitive information). This commit adds ability for the role to see NFS session information.

NAS-125577 / 24.04 / allow READONLY role to get NFS client status

---

src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/role.py

This commit allows READONLY role to list currently authenticated middleware sessions. AUTH_SESSIONS_WRITE role is defined so that webui can have hint about whether to turn off the terminate sessions button.

NAS-125584 / 24.04 / Add roles for interacting with auth sessions

---

src/middlewared/middlewared/plugins/nfs.py

This commit adds a readonly key to nfs.config output to indicate whether the system keytab contains an SPN entry for the NFS service. This helps UI team to save an API call and simplifies roles management.

NAS-125620 / 24.04 / Expand nfs.config to show whether keytab has NFS spn

---

cluster-tests/tests/cleanup/test_cluster_cleanup.py
src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py
src/middlewared/middlewared/plugins/service_/services/glusterd.py

This commit adds more handling for clustering teardown for the true command team.
* regenerate smb.conf during cluster teardown job.
* always stop glusterfs service (along with ctdb and smb)

NAS-125614 / 24.04 / More clustering teardown improvements

---

cluster-tests/tests/cleanup/test_cluster_cleanup.py
src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py
src/middlewared/middlewared/plugins/service_/services/glusterd.py

This commit adds more handling for clustering teardown for the true command team.
* regenerate smb.conf during cluster teardown job.
* always stop glusterfs service (along with ctdb and smb)
Original PR: https://github.com/truenas/middleware/pull/12671
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125614

NAS-125614 / 23.10.2 / More clustering teardown improvements (by anodos325)

---

src/middlewared/middlewared/plugins/reporting/realtime_reporting/memory.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_stats_func.py

All the real-time reporting statistics are now standardized to bytes. These changes are aimed at reducing complexity in the user interface.

NAS-123965 / 24.04 / Convert all relevant realtime stats in bytes

---

src/middlewared/middlewared/plugins/idmap.py

There is potential to have a race between middleware idmap operations and system dataset move. If system dataset path is not set (which can happen when we have system dataset migration in progress) we should raise an exception.

NAS-125627 / 24.04 / Do not try to restart winbindd when sysdataset missing

---

src/middlewared/middlewared/role.py

This was omitted by oversight when feature was developed.

NAS-125638 / 24.04 / Add DATASET_READ to READONLY role

---

src/middlewared/middlewared/plugins/account_/privilege.py
src/middlewared/middlewared/pytest/unit/utils/test_privilege.py
src/middlewared/middlewared/utils/privilege.py

This adds flag to composed privilege (for example in auth.me output) that can be used by the webui team to determine whether and authenticated session should have webui access. Current algorithm is to check whether credential has one of non-builtin roles (READONLY, FULL_ADMIN, SHARING_MANAGER).

NAS-125573 / 24.04 / Add webui_access flag to composed privilege

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py
src/middlewared/middlewared/plugins/failover_/event.py

This fixes 2 primary issues with HA logic on SCALE.
1. receiving a rapid succession of failover events
2. BACKUP failover loop
This fixes both situations by adding a pub/sub model to vrrp_events.py and checking the timeframe for when we receive VRRP events. The reason why this needs to be fixed is that without these changes, when both controllers are boot up simultaneously (for example), we don't handle the events properly and leave the system with the zpool imported without fenced running. That's a worst case scenario since fenced guards us from having the zpool imported on both controllers simultaneously.
Have tested this myself on 2 different internal systems extensively.

NAS-124988 / 24.04 / fix faulty HA logic

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py
src/middlewared/middlewared/plugins/failover_/event.py

This fixes 2 primary issues with HA logic on SCALE.
1. receiving a rapid succession of failover events
2. BACKUP failover loop
This fixes both situations by adding a pub/sub model to vrrp_events.py and checking the timeframe for when we receive VRRP events. The reason why this needs to be fixed is that without these changes, when both controllers are boot up simultaneously (for example), we don't handle the events properly and leave the system with the zpool imported without fenced running. That's a worst case scenario since fenced guards us from having the zpool imported on both controllers simultaneously.
Have tested this myself on 2 different internal systems extensively.
Original PR: https://github.com/truenas/middleware/pull/12692
Jira URL: …

NAS-124988 / 23.10.1 / fix faulty HA logic (by yocalebo)

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/etc.py
src/middlewared/middlewared/utils/privilege.py
tests/api2/test_password_reset.py

This commit adds a new API endpoint user.set_password that may be used to change the password of a given user.
NOTE: when authenticated session has less than FULL_ADMIN role, password changes will be rejected if the payload does not match the currently-authenticated user.
API keys granting access to this endpoint will be able to reset password of any user.

NAS-125618 / 24.04 / Allow users to set own passwords

---

src/middlewared/middlewared/plugins/service.py
src/middlewared/middlewared/plugins/service_/utils.py
src/middlewared/middlewared/pytest/unit/utils/test_privilege.py
src/middlewared/middlewared/role.py
tests/api2/test_nfs_share_crud_roles.py
tests/api2/test_smb_share_crud_roles.py

This commit adds SERVICE_READ and SERVICE_WRITE roles that are allowed to read / write services table configuration and administer services. SERVICE_READ is able to determine service running state. If user has SHARING_NFS_WRITE, SHARING_SMB_WRITE, and SHARING_ISCSI write they will be able to start, stop, restart, etc the respective service. If user has SERVICE_WRITE, then they will be able to manipulate running state of all services.

NAS-125673 / 24.04 / Configure roles for service plugin

---

src/middlewared/middlewared/plugins/account_/privilege.py
src/middlewared/middlewared/utils/privilege.py

If builtin_administrators is removed from Local Administrators privilege then root and admin user will not be able to authenticate via middlware APIs.

NAS-125685 / 24.04 / Prevent locking out root / admin user

---

src/middlewared/middlewared/plugins/account_/privilege.py
src/middlewared/middlewared/utils/privilege.py

If builtin_administrators is removed from Local Administrators privilege then root and admin user will not be able to authenticate via middlware APIs.
Original PR: https://github.com/truenas/middleware/pull/12707
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125685

NAS-125685 / 23.10.2 / Prevent locking out root / admin user (by anodos325)

---

src/middlewared/middlewared/plugins/reporting/netdata/graphs.py

The vertical label on the system load graph for the "load" chart is incorrect; it displays "processes" instead of "load."
The vertical label on the system load graph is corrected to display "load." Additionally, a new graph is added to show the active number of processes.

NAS-125454 / 24.04 / Change load label and add processes chart

---

src/middlewared/middlewared/plugins/update.py

This information is used to indicate whether update is ready to install, which might be useful for someone with readonly role.

NAS-125688 / 24.04 / Allow READONLY role to read update info

---

src/middlewared/middlewared/plugins/audit/audit.py
src/middlewared/middlewared/role.py

This commit adds a role to explicitly allow access to read audit reports.

NAS-125633 / 24.04 / Add AUDIT_READ role

---

src/middlewared/middlewared/plugins/chart_releases_linux/scale_workload.py
src/middlewared/middlewared/plugins/chart_releases_linux/utils.py

This PR adds changes to not scale workloads which have host paths which don't exist as in this case k3s automatically creates those paths which can be problematic as if a user tries to create a dataset which has the same mountpoint as the path, dataset creation will fail as we make sure that the dataset's mountpoint does not exist when we attempt to create it.
Original PR: https://github.com/truenas/middleware/pull/12702
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125545

NAS-125545 / 23.10.2 / Do not scale workloads which are using hostpaths which don't exist (by sonicaj)

---

src/middlewared/middlewared/plugins/smb.py
tests/api2/test_simple_share.py

This expands validation performed in the SMB share precheck that is performed by webui in simplified share creation form.

NAS-125301 / 24.04 / Add check for share name collision

---

tests/api2/test_300_nfs.py
tests/protocols/nfs_proto.py

Part of NAS-125674
'allow_nonroot' translates to the `insecure` option on shares defined in /etc/exports.
This commit is to improve the CI testing for this setting.

NAS-125700 / 24.04 / Enhance testing of NFS 'allow_nonroot' setting

---

src/middlewared/middlewared/plugins/chart_releases_linux/validation.py
src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
tests/api2/test_chart_release_acl_apply.py

It was requested by Stavros that we backport ACL changes so users can make use of the new force flag properly.
Original PR: https://github.com/truenas/middleware/pull/12636
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125528

NAS-125528 / 23.10.1 / Backport ACL changes to cobia (by Qubad786)

---

src/middlewared/middlewared/alembic/versions/23.10/2023-10-24_14-28_network_interface_link_address.py
src/middlewared/middlewared/plugins/interface/link_address.py

VLANs have the same hardware address as their parent interface which will cause confusion in the network interface migration process:
```
[2023/12/14 05:24:45] (INFO) middlewared.setup():202 - Interface 'ens5f4' is now 'vlan370' (matched by link address '00:07:43:40:60:50')
[2023/12/14 05:24:45] (INFO) middlewared.rename():111 - Renaming interface 'ens5f4' to 'vlan370'
```

NAS-125713 / 23.10.2 / Do not store and use hardware addresses for non-physical interfaces

---

src/middlewared/middlewared/alembic/versions/23.10/2023-10-24_14-28_network_interface_link_address.py
src/middlewared/middlewared/plugins/interface/link_address.py

VLANs have the same hardware address as their parent interface which will cause confusion in the network interface migration process:
```
[2023/12/14 05:24:45] (INFO) middlewared.setup():202 - Interface 'ens5f4' is now 'vlan370' (matched by link address '00:07:43:40:60:50')
[2023/12/14 05:24:45] (INFO) middlewared.rename():111 - Renaming interface 'ens5f4' to 'vlan370'
```
Original PR: https://github.com/truenas/middleware/pull/12717
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125713

NAS-125713 / 23.10.1 / Do not store and use hardware addresses for non-physical interfaces (by themylogin)

---

src/middlewared/middlewared/alembic/versions/23.10/2023-10-24_14-28_network_interface_link_address.py
src/middlewared/middlewared/plugins/interface/link_address.py

VLANs have the same hardware address as their parent interface which will cause confusion in the network interface migration process:
```
[2023/12/14 05:24:45] (INFO) middlewared.setup():202 - Interface 'ens5f4' is now 'vlan370' (matched by link address '00:07:43:40:60:50')
[2023/12/14 05:24:45] (INFO) middlewared.rename():111 - Renaming interface 'ens5f4' to 'vlan370'
```
Original PR: https://github.com/truenas/middleware/pull/12717
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125713

NAS-125713 / 24.04 / Do not store and use hardware addresses for non-physical interfaces (by themylogin)

---

src/middlewared/middlewared/plugins/account_/privilege.py

READONLY builtin privilege should not allow having web_shell access enabled since this allows the users to be able to write to the filesystem.

NAS-125719 / 24.04 / prevent web_shell from being enabled for READONLY

---

src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/plugins/auth_/authenticate.py
tests/api2/test_030_activedirectory.py
tests/api2/test_auth_me.py

This adds specific account-related flags to user credentials that webui can evaluate whether user is local, our special system administrator account, etc. This is implemented as a list so that we have capability to expand what is presented without having to modify API.
This commit also removes two indirect calls to `user.query` during `auth.authenticate`.

NAS-125710 / 24.04 / Add account_attributes to auth.me output

---

src/middlewared/middlewared/plugins/account.py

This adds explicit error message for case when we need to refuse changing an SMB user due to broken system dataset configuration.

NAS-125715 / 24.04 / Clarify ValidationError for broken sysdataset

---

tests/api2/test_027_kubernetes_logs.py

This commit makes 2 changes, first it adds changes to use an image which is lightweight and can be pulled relatively quickly so that we don't timeout and secondly it marks the test as flaky as sometimes on the CI the test can take some time to complete because of the I/O invovled.

NAS-125600 / 24.04 / Mark chart release logs test as flaky

---

tests/api2/test_027_kubernetes_logs.py

This commit makes 2 changes, first it adds changes to use an image which is lightweight and can be pulled relatively quickly so that we don't timeout and secondly it marks the test as flaky as sometimes on the CI the test can take some time to complete because of the I/O invovled.
Original PR: https://github.com/truenas/middleware/pull/12703
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125600

NAS-125600 / 23.10.2 / Mark chart release logs test as flaky (by sonicaj)

---

src/middlewared/middlewared/plugins/auth.py

We now store 2FA flag in account_attributes to indicate whether two-factor authentication is required. This eliminates an extra user.query call.

NAS-125730 / 24.04 / Small optimization to check for 2fa required

---

src/middlewared/middlewared/plugins/config.py

Configuration reset is an incredibly destructive action that is inappropriate to expose to more than the root account.

NAS-125636 / 24.04 / Restrict config reset to root / admin account

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/cache.py

There are some edge cases with regard to SMB passdb and groupmap interactions where user.query and group.query will fail if the system dataset is broken. Rather than failing these calls we should simply omit the SMB-related information so that dependent calls do not fail.

NAS-125714 / 24.04 / Add more error handling for broken system dataset

---

src/middlewared/middlewared/role.py

Per request from webui team, grant the SHARING_MANAGER role all rights that READONLY has.

NAS-125593 / 24.04 / Make SHARING_MANAGER role a superset of READONLY

---

src/middlewared/middlewared/plugins/reporting/realtime_reporting/utils.py

In certain scenarios, the values of netdata dimensions are `None`, resulting in the return of a `None` value instead of the expected default value. This issue is addressed by modifying the logic to return the dimension's value if it is not `None`; otherwise, the default value is returned.
Changes have been implemented to ensure that if the dimension's value is not `None`, it is returned; otherwise, the default value is returned.

NAS-125731 / 24.04 / Fix edge case while retrieving netdata dimensions

---

src/middlewared/middlewared/plugins/reporting/realtime_reporting/utils.py

In certain scenarios, the values of netdata dimensions are `None`, resulting in the return of a `None` value instead of the expected default value. This issue is addressed by modifying the logic to return the dimension's value if it is not `None`; otherwise, the default value is returned.
Changes have been implemented to ensure that if the dimension's value is not `None`, it is returned; otherwise, the default value is returned.
Original PR: https://github.com/truenas/middleware/pull/12732
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125731

NAS-125731 / 23.10.2 / Fix edge case while retrieving netdata dimensions (by Qubad786)

---

src/middlewared/middlewared/plugins/smb.py

This was accidentally omitted when developing roles for SMB.

NAS-125770 / 24.04 / set SHARING_SMB role prefix for SMB service

---

src/middlewared/middlewared/plugins/vm/devices/storage_devices.py
src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_devices_xml.py

Adding discard setting to disk, allowing VM images to shrink on physical disk. Setting should be supported by all available disk types.
Partially solves https://ixsystems.atlassian.net/browse/NAS-113503 (without transition to virtio-scsi).

NAS-125642 / 24.04 / Enable discard for VM disks

---

src/middlewared/middlewared/plugins/vm/vms.py

Change ovmf_options to collect all available images from disk, instead of limiting to the base ones.

NAS-125641 / 24.04 / Lift limitations of OVMF option collection

---

src/middlewared/middlewared/utils/cpu.py

For some AMD CPUs that have a single core, the temperature sensor sends a float value instead of a list. However, We expect a list, leading to a type error.
This edge case is now handled in the AMD CPU temperature function.

NAS-125362 / 24.04 / Fix edge case for getting CPU temperature on AMD machines

---

src/middlewared/middlewared/utils/cpu.py

For some AMD CPUs that have a single core, the temperature sensor sends a float value instead of a list. However, We expect a list, leading to a type error.
This edge case is now handled in the AMD CPU temperature function.
Original PR: https://github.com/truenas/middleware/pull/12755
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125362

NAS-125362 / 23.10.2 / Fix edge case for getting CPU temperature on AMD machines (by Qubad786)

---

src/middlewared/middlewared/plugins/reporting/netdata/client.py

Log is unnecessarily spamming the debug and we are gracefully handling the issue elsewhere so better not log it here.

NAS-125782 / 24.04 / Reduce log spamming from reporting plugin

---

src/middlewared/middlewared/plugins/reporting/netdata/client.py

Log is unnecessarily spamming the debug and we are gracefully handling the issue elsewhere so better not log it here.
Original PR: https://github.com/truenas/middleware/pull/12759
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125782

NAS-125782 / 23.10.2 / Reduce log spamming from reporting plugin (by Qubad786)

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/role.py

ACCOUNT_READ - allows reading user / group information
ACCOUNT_WRITE - allows creating, updating, and deleting local users and groups

NAS-125788 / 24.04 / Add roles for manipulating local accounts

---

src/middlewared/middlewared/plugins/support.py
src/middlewared/middlewared/plugins/truenas.py
src/middlewared/middlewared/role.py

This commit adds SUPPORT_READ and SUPPORT_WRITE roles with ability to manage details of support plugin. READONLY is granted SUPPORT_READ as well as ability to generate tickets.

NAS-125787 / 24.04 / Add SUPPORT_READ and SUPPORT_WRITE roles

---

src/middlewared/middlewared/plugins/interface/capabilities.py
src/middlewared/middlewared/plugins/interface/lag_protocols.py

Webui calls interface.lag_supported_protocols, which is a private endpoint and therefore not suitable for roles configuration. The data returned is benign and so remove roles check for access to it.
Permit NETWORK_INTERFACE roles to get / set interface capabilities.

NAS-125792 / 24.04 / Expand roles configuration for interfaces

---

src/middlewared/middlewared/plugins/acme_protocol_/schema.py
src/middlewared/middlewared/plugins/device.py
src/middlewared/middlewared/plugins/idmap.py
src/middlewared/middlewared/plugins/smb.py
src/middlewared/middlewared/plugins/smb_/status.py
src/middlewared/middlewared/plugins/vmware.py

This commit allows READONLY admins to access various public API endpoints in smb, idmap, acme, and device plugins that provide basic information about the services.

NAS-125801 / 24.04 / Allow READONLY role to access various public endpoints

---

src/middlewared/middlewared/plugins/reporting/export.py
src/middlewared/middlewared/role.py

This commit adds roles for various reporting.exporters endpoints. REPORTING_READ and REPORTING_WRITE are reused since use-case for finer-grained permissions here is not clear.

NAS-125794 / 24.04 / Add roles for reporting exporters

---

src/middlewared/middlewared/apidocs/templates/websocket/query.md
src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
src/middlewared/middlewared/utils/__init__.py

Audit queries return as a field an ISO-8601 timestamp that's internally converted to a python datetime object and returned to external callers as a JSON object containing $date key. This commit adds special handling for filter-list to allow specifying ISO-8601 timestamp values for `timestamp.$date` key. In this case we will convert the specified string into datetime object during filters validation and use it for comparison with datetime object being handled in backend.

NAS-125783 / 24.04 / Add query-filters for timestamps

---

src/freenas/usr/lib/netdata/python.d/cputemp.chart.py

The netdata python.d plugin is presently not handling and logging exceptions that may occur during the normalization process of CPU temperature data. As a consequence, the CPU temperature fails to execute due to an unhandled exception.
To address this, exceptions that may arise during the normalization of CPU temperature data are now handled and logged appropriately. In case of an error, default data is returned, and the error is logged to facilitate debugging in the normalization process.

NAS-125732 / 24.04 / Handle and log exception while normalizing cpu temp

---

src/freenas/usr/lib/netdata/python.d/cputemp.chart.py

The netdata python.d plugin is presently not handling and logging exceptions that may occur during the normalization process of CPU temperature data. As a consequence, the CPU temperature fails to execute due to an unhandled exception.
To address this, exceptions that may arise during the normalization of CPU temperature data are now handled and logged appropriately. In case of an error, default data is returned, and the error is logged to facilitate debugging in the normalization process.
Original PR: https://github.com/truenas/middleware/pull/12733
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125732

NAS-125732 / 23.10.2 / Handle and log exception while normalizing cpu temp (by Qubad786)

---

src/middlewared/middlewared/plugins/zfs_/dataset_actions.py
tests/api2/test_dataset_mount.py

This commit adds changes to ensure that when we want to recursively mount datasets and if for some reason any dataset fails to mount - we do not stop in mounting the subsequent datasets as shown by the behavior of 'zfs mount -a' as well.

NAS-124823 / 24.04 / Make sure we mount all datasets we can when doing recursive mount

---

src/middlewared/middlewared/plugins/vm/devices/usb.py
src/middlewared/middlewared/plugins/vm/usb.py

Unavailability of USB device due to any reasons was causing issues in XML creation. For a user this was happening because his printer had power saving mode enabled and it went to sleep which resulted in TrueNAS not being able to retrieve the USB details which are required/relevant for defining domain of a VM using USB device or starting one.
Base of the problem was a missing check for presence of None values in the USB capability dict we made and available flag should be accounting for this and relevant usages have been covered so if any user runs into this scenario we have it properly handled.

NAS-125452 / 24.04 / Validation for USB device not being available

---

src/middlewared/middlewared/plugins/account_/privilege.py

This fixes an edge case where FULL_ADMIN granted via access to all methods (*) does not set the webui_access flag in the composed privilege.

NAS-125830 / 24.04 / Ensure that full allowlist grants webui access

---

src/middlewared/middlewared/plugins/account_/privilege.py
tests/api2/test_auth_me.py

This test validates that users with FULL_ADMIN privilege also have webui_access flag set. It also catches an edge case for sessions authenticated via unix domain socket not having key present.

NAS-125835 / 24.04 / Add tests for webui_access privilege flag

---

tests/api2/test_300_nfs.py

UDP has been removed,  the setting in the NFS CI test should also have been removed.
This change removes the erroneous UDP usage.

NAS-125836 / 24.04 / Remove udp from NFS CI test.

---

src/freenas/usr/lib/systemd/network/10-enp135_141_s0f0np0.link
src/freenas/usr/lib/systemd/network/10-enp135_141_s0f1np1.link

The f-series HA system has a quirk with a specific
hardware configuration that shows up when 2x pcie
slots are filled with add-on NICs. This has something
to do with the AMD NTB hardware mapping but the end
result is that the A controller's NIC name will be
enp135* and the B controller's NIC name will be enp141*.
This breaks effectively everything related to our HA
logic. To mitigate this issue, this link file will
match on pci path name and rename the interface name
accordingly.

NAS-125771 / 24.04 / add special handling for fseries

---

src/freenas/usr/lib/systemd/network/10-enp135_141_s0f0np0.link
src/freenas/usr/lib/systemd/network/10-enp135_141_s0f1np1.link

The f-series HA system has a quirk with a specific
hardware configuration that shows up when 2x pcie
slots are filled with add-on NICs. This has something
to do with the AMD NTB hardware mapping but the end
result is that the A controller's NIC name will be
enp135* and the B controller's NIC name will be enp141*.
This breaks effectively everything related to our HA
logic. To mitigate this issue, this link file will
match on pci path name and rename the interface name
accordingly.
Original PR: https://github.com/truenas/middleware/pull/12782
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125771

NAS-125771 / 23.10.2 / add special handling for fseries (by yocalebo)

---

src/middlewared/middlewared/etc_files/scst.conf.mako

When binding an iSCSI portal to an IPv6 address, `middlewared` is adding square brackets to the ipv6 addresses where scst is not expecting any in the initiator target group lines in `/etc/scst.conf` e.g. `INITIATOR *\#[2a10:4741:36:28:e61d:2dff:fe90:80fe]` instead of `INITIATOR *\#2a10:4741:36:28:e61d:2dff:fe90:80fe`.
This locks all initiators out of the target because `scst` is expecting these IPv6 addresses without the square brackets and thus the addresses don't match up.
A very bad poor man's "fix" is  making the iSCSI portal bind to all addresses.
When binding to all addresses, `/etc/scst.conf` is populated with `INITIATOR *\#*` which causes iscsiadm to crap out during target discovery. This is because link-local ipv6 addresses from the TrueNAS box are sent to the client which …

NAS-125569 Don't enclose ipv6 addresses in square brackets in scst.conf

---

src/middlewared/middlewared/etc_files/scst.conf.mako

When binding an iSCSI portal to an IPv6 address, `middlewared` is adding square brackets to the ipv6 addresses where scst is not expecting any in the initiator target group lines in `/etc/scst.conf` e.g. `INITIATOR *\#[2a10:4741:36:28:e61d:2dff:fe90:80fe]` instead of `INITIATOR *\#2a10:4741:36:28:e61d:2dff:fe90:80fe`.
This locks all initiators out of the target because `scst` is expecting these IPv6 addresses without the square brackets and thus the addresses don't match up.
A very bad poor man's "fix" is  making the iSCSI portal bind to all addresses.
When binding to all addresses, `/etc/scst.conf` is populated with `INITIATOR *\#*` which causes iscsiadm to crap out during target discovery. This is because link-local ipv6 addresses from the TrueNAS box are sent to the client which …

NAS-125569 / 23.10.2 / Don't enclose ipv6 addresses in square brackets in scst.conf (by starcraft66)

---

src/middlewared/middlewared/plugins/pool_/pool.py

Adds the `READONLY` role to `pool.validate_name` method required by the UI team. While this endpoint is only ever called during pool creation, to keep the logic as simple as possible we can allow this to be used by `READONLY`.

NAS-125866 / 24.04 / add READONLY to pool.validate_name

---

src/middlewared/middlewared/plugins/webui/main_dashboard.py

This is similar to what was done in `webui.enclosure.dashboard`. This is an endpoint exclusively designed for the webUI to consume. This one is particularly important because the UI team is calling `system.info` which includes an absurd amount of information about the system but they're only showing 6 top-level keys on the system information widget. That's kind of painful because `system.info` is not cheap. Furthermore, the webui team is also making a few `failover.call_remote` calls on their own which should never be happening since we consider `failover.call_remote` an internal endpoint that can change quite dramatically because we assume we don't have any external consumers.

NAS-125858 / 24.04 / add new webui namespace (webui.main.dashboard)

---

src/middlewared/middlewared/plugins/disk_/temperature.py

The `skip_zero_values_in_aggregation` flag is set to true in the disktemp graph. As a result, aggregation calculations are skipped if all the disk temperature values are zero. In some cases, temperature values might not exist, causing a key error when retrieving disk temperature from the `temperature_agg` API.
Now, the `temperature_agg` is retrieved safely, and default null values are returned to prevent the key error.

NAS-125841 / 24.04 / Gracefully handle case for aggregating disk temperatures when no temperatures have been retrieved

---

src/middlewared/middlewared/plugins/disk_/temperature.py

The `skip_zero_values_in_aggregation` flag is set to true in the disktemp graph. As a result, aggregation calculations are skipped if all the disk temperature values are zero. In some cases, temperature values might not exist, causing a key error when retrieving disk temperature from the `temperature_agg` API.
Now, the `temperature_agg` is retrieved safely, and default null values are returned to prevent the key error.
Original PR: https://github.com/truenas/middleware/pull/12806
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125841

NAS-125841 / 23.10.2 / Gracefully handle case for aggregating disk temperatures when no temperatures have been retrieved (by Qubad786)

---

src/middlewared/middlewared/plugins/truecommand/portal.py

This commit fixes an issue where if tc container is down, we immediately try to start wireguard service which will initiate a health check which is destined to fail and we will continue stop/start cycle. So adding a delay of 5 minutes before each time we initiate this.

NAS-125548 / 24.04 / Retry starting truecommand after a small delay if TC container is down

---

src/middlewared/middlewared/plugins/truecommand/portal.py

This commit fixes an issue where if tc container is down, we immediately try to start wireguard service which will initiate a health check which is destined to fail and we will continue stop/start cycle. So adding a delay of 5 minutes before each time we initiate this.
Original PR: https://github.com/truenas/middleware/pull/12775
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125548

NAS-125548 / 23.10.2 / Retry starting truecommand after a small delay if TC container is down (by sonicaj)

---

src/middlewared/middlewared/alert/source/applications.py
src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py

The alert framework received chart release data as is, exposing sensitive information present in `chart.release.query` via the alerts' endpoint.
This PR fixes the issue by sending only the chart ID instead of the complete query to the alert framework, ensuring data privacy and security.

NAS-125820 / 24.04 / Fix config data being exposed for chart releases

---

src/middlewared/middlewared/alert/source/applications.py
src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py

The alert framework received chart release data as is, exposing sensitive information present in `chart.release.query` via the alerts' endpoint.
This PR fixes the issue by sending only the chart ID instead of the complete query to the alert framework, ensuring data privacy and security.
Original PR: https://github.com/truenas/middleware/pull/12809
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125820

NAS-125820 / 23.10.2 / Fix config data being exposed for chart releases (by Qubad786)

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/account_/builtin_administrator.py
src/middlewared/middlewared/plugins/account_/privilege.py
src/middlewared/middlewared/plugins/auth_/authenticate.py
src/middlewared/middlewared/test/integration/assets/account.py
tests/api2/test_account_privilege.py
tests/api2/test_user_admin.py

…_has_root_password_enabled` is `True`
Original PR: https://github.com/truenas/middleware/pull/12798
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125839

NAS-125839 / 23.10.2 / Fix `privilege.local_administrators` being empty if `privilege.always… (by themylogin)

---

src/middlewared/middlewared/plugins/filesystem.py
src/middlewared/middlewared/service/core_service.py
tests/api2/test_job_logs.py
tests/api2/test_rest_api_download.py

UI can continue to use `core.download` as it was doing it before.
The only change wrt to `core.download` is that unprivileged user will not be able to call `filesystem.get`. I looked in the UI code and `filesystem.get` was used for the following cases:
* Download job logs (this will be replaced with `core.job_download_logs`, UI ticket https://ixsystems.atlassian.net/browse/NAS-125918)
* Download CA/CSR/certificates (these are not RBAC yet so no changes are needed)
* Download VM logs (same as above)

NAS-125689 / 24.04 / Make `core.download` no_authz_required, but validate access permissions to called method inside

---

src/middlewared/middlewared/plugins/activedirectory.py
tests/api2/test_030_activedirectory.py

Removing ad_bindpw column was from the TrueNAS config file broke validation for parameters while AD is enabled.

NAS-125930 / 24.04 / Fix validation for permitted keys in AD plugin

---

src/middlewared/middlewared/plugins/activedirectory.py
tests/api2/test_030_activedirectory.py

Removing ad_bindpw column from the TrueNAS config file broke validation for parameters while AD is enabled.
Original PR: https://github.com/truenas/middleware/pull/12816
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125930

NAS-125930 / 23.10.2 / Fix validation for permitted keys in AD plugin (by anodos325)

---

src/middlewared/middlewared/alert/source/nfs_exportsd.py
src/middlewared/middlewared/etc_files/exports.mako
src/middlewared/middlewared/plugins/account_/internal_cache.py
src/middlewared/middlewared/plugins/nfs.py
tests/api2/test_300_nfs.py

On upgrade, if `maproot` or `mapall` is configured on an NFS share and the user or group is deleted as part of the upgrade, then all NFS shares end up disabled.
- In nfs exports mako add check for required users or groups and disable NFS shares that use missing users or groups.
- Add oneshot alert when missing user or group is detected.   Remove oneshot alert when share configuration is repaired.
- Enhance reporting on attempt to configure NFS share with invalid user or group setting
- Add CI test for missing user and group with NFS `maproot` and `mapall` configuration options
- Some refactoring of the NFS CI test module

NAS-125621 / 24.04 / Handle missing users and groups in NFS share configuration

---

src/freenas/usr/bin/install-dev-tools
src/freenas/usr/local/libexec/disable-rootfs-protection

This commit adds a license check before proceeding with disabling rootfs protection on enterprise-licensed TrueNAS. Developers are able to circumvent it, but this should protect against casual foot-shooting.

NAS-125945 / 24.04 / Prevent disabling rootfs protection on SCALE_ENTERPRISE

---

src/middlewared/middlewared/utils/git.py

This commit improves improves logs readability by reducing verbosity of counterproductive logs. Instead of displaying the entire error message in case of failure which can be really enormous, it now shortens the message to a acceptable length.

NAS-125876 / 24.04 / Reduce git subprocess spam in error logging

---

src/middlewared/middlewared/utils/git.py

This commit improves improves logs readability by reducing verbosity of counterproductive logs. Instead of displaying the entire error message in case of failure which can be really enormous, it now shortens the message to a acceptable length.
Original PR: https://github.com/truenas/middleware/pull/12823
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125876

NAS-125876 / 23.10.2 / Reduce git subprocess spam in error logging (by sonicaj)

---

src/middlewared/middlewared/plugins/disk_/temperature.py

The `skip_zero_values_in_aggregation` flag is set to true in the disktemp graph. As a result, aggregation calculations are skipped if all the disk temperature values are zero. In some cases, temperature values might not exist, causing a key error when retrieving disk temperature from the `temperature_agg` API.
Now, the `temperature_agg` is retrieved safely, and default null values are returned to prevent the key error.
Original PR: https://github.com/truenas/middleware/pull/12806
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125841
Original PR: https://github.com/truenas/middleware/pull/12808
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125841

NAS-125841 / 23.10.1.1 / Gracefully handle case for aggregating disk temperatures when no temperatures have been retrieved (by Qubad786) (by bugclerk)

---

src/freenas/usr/lib/systemd/network/10-enp135_141_s0f0np0.link
src/freenas/usr/lib/systemd/network/10-enp135_141_s0f1np1.link

The f-series HA system has a quirk with a specific
hardware configuration that shows up when 2x pcie
slots are filled with add-on NICs. This has something
to do with the AMD NTB hardware mapping but the end
result is that the A controller's NIC name will be
enp135* and the B controller's NIC name will be enp141*.
This breaks effectively everything related to our HA
logic. To mitigate this issue, this link file will
match on pci path name and rename the interface name
accordingly.
Original PR: https://github.com/truenas/middleware/pull/12782
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125771
Original PR: https://github.com/truenas/middleware/pull/12784
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125771

NAS-125771 / 23.10.1.1 / add special handling for fseries (by yocalebo) (by bugclerk)

---

src/middlewared/middlewared/test/integration/assets/smb.py
tests/api2/test_smb_client.py

This commit adds basic tests for the SMB client mount option that maps NT security descriptor to a ZFS ACL xattr. Tests are via loopback mount to ensure that all SIDs in the security descriptor will be properly mapped to Unix IDs.

NAS-125985 / 24.04 / Add SMB client tests for ZFS ACL compatibiltiy

---

src/middlewared/middlewared/alert/source/applications.py
src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py

The alert framework received chart release data as is, exposing sensitive information present in `chart.release.query` via the alerts' endpoint.
This PR fixes the issue by sending only the chart ID instead of the complete query to the alert framework, ensuring data privacy and security.
Original PR: https://github.com/truenas/middleware/pull/12809
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125820
Original PR: https://github.com/truenas/middleware/pull/12811
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125820

NAS-125820 / 23.10.1.1 / Fix config data being exposed for chart releases (by Qubad786) (by bugclerk)

---

src/middlewared/middlewared/plugins/smb.py

Since clustering has been deprecated, we no longer need to blacklist this SMB auxiliary parameter.

NAS-114068 / 24.04 / Remove interfaces parameter from aux param blacklist

---

src/middlewared/middlewared/plugins/iscsi_/global_linux.py

The WebUI uses this API to warn the user wrt restarting iSCSI service.
If ALUA is enabled we will _always_ have sessions from the peer controller, so do not report these "internal" sessions here.

NAS-126011 / 24.04 / Do not include HA peer iSCSI ALUA sessions in global.iscsi.sessions

---

src/middlewared/middlewared/plugins/service_/services/base.py
src/middlewared/middlewared/plugins/service_/services/iscsitarget.py

Previously we had a hard-coded timeout of 5 seconds on `systemctl` operations on services.  This is inadequate for iSCSI (`scst`), especially when a large number of targets are present and `ALUA` is enabled.
Original PR: https://github.com/truenas/middleware/pull/12833
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126010

NAS-126010 / 23.10.2 / Add systemd_unit_timeout and make longer for ISCSITargetService (by bmeagherix)

---

src/middlewared/middlewared/plugins/iscsi_/global_linux.py

The WebUI uses this API to warn the user wrt restarting iSCSI service.
If ALUA is enabled we will _always_ have sessions from the peer controller, so do not report these "internal" sessions here.
Original PR: https://github.com/truenas/middleware/pull/12835
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126011

NAS-126011 / 23.10.2 / Do not include HA peer iSCSI ALUA sessions in global.iscsi.sessions (by bmeagherix)

---

src/middlewared/middlewared/auth.py
src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/utils/privilege.py

Observed in middleware log on HA CI runs. In various situations call_remote was failing in an authorization check to see whether the credential had full-admin privileges via allowlist (for example when determining whether credential is allowed to start/stop services). This PR checks whether the credential is de-facto root (via other node or root TCP session) and returns that it has full admin privileges.
To safeguard against AttributeError on allowlist checks, set allowlist=None on SessionManagerCredentials class.

NAS-126015 / 24.04 / Fix Authorization of remote middleware in HA

---

src/middlewared/middlewared/plugins/ipmi_/lan.py
src/middlewared/middlewared/role.py

This adds a boolean value to `ipmi.lan.update` endpoint so the webUI team can stop calling `failover.call_remote`. This is necessary because we're now applying RBAC policies to the various endpoints and we're leaving `failover.call_remote` as accessible to root only.
Changes implemented here:
1. move the subprocess related logic to its own function `apply_config`
2. add an `apply_remote` boolean to the schema which when set to True will apply the config to the remote controller
3. add role information

NAS-125867 / 24.04 / add `apply_remote` to ipmi.lan.update

---

src/middlewared/middlewared/main.py
src/middlewared/middlewared/role.py

This PR adds fixes to make sure middleware starts when we try to add roles to crud/config based methods. What happens is that these methods are already registered and if we try to add additional roles to them, middleware crashes as we always try to register a method but these ones are already registered automatically.
e.g
```
❯ middlewared restart --loop-debug -P --debug-level 'DEBUG'
[2024/01/04 14:07:12] (INFO) middlewared.__init__():897 - Starting TrueNAS-SCALE-24.04.0-MASTER-20240103-143513 middleware
[2024/01/04 14:07:14] (WARNING) asyncio._run_once():1917 - Executing <Task finished name='Task-1' coro=<Middleware.__initialize() done, defined at /usr/lib/python3/dist-packages/middlewared/main.py:1950> exception=ValueError("Method 'ipmi.lan.query' is already registered in this role …
```

NAS-126046 / 24.04 / Fix middleware not starting

---

src/middlewared/middlewared/plugins/catalogs_linux/sync_catalogs.py
src/middlewared/middlewared/plugins/catalogs_linux/update.py
tests/api2/test_catalog_sync.py

This PR adds changes to make sure we don't exhaust /var/run by cloning in catalogs. These are the changes we are introducing to prevent this scenario from happening:
1. Make sure we can't add more catalogs if apps pool is not configured
2. Do not sync non official catalogs if apps pool is not configured as it will result in tmpfs being exhausted
3. Make sure we don't sync non-official catalogs if apps pool's root dataset is locked

NAS-125877 / 24.04 / Make sure we don't exhaust /var/run with catalogs

---

src/middlewared/middlewared/plugins/catalogs_linux/sync_catalogs.py
src/middlewared/middlewared/plugins/catalogs_linux/update.py
tests/api2/test_catalog_sync.py

This PR adds changes to make sure we don't exhaust /var/run by cloning in catalogs. These are the changes we are introducing to prevent this scenario from happening:
1. Make sure we can't add more catalogs if apps pool is not configured
2. Do not sync non official catalogs if apps pool is not configured as it will result in tmpfs being exhausted
3. Make sure we don't sync non-official catalogs if apps pool's root dataset is locked
Original PR: https://github.com/truenas/middleware/pull/12839
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125877

NAS-125877 / 23.10.2 / Make sure we don't exhaust /var/run with catalogs (by sonicaj)

---

src/middlewared/middlewared/etc_files/local/smb4.conf

This parameter is deprecated and no longer exists in Samba 4.19.

NAS-126064 / 13.1 / Remove "directory name cache size" parameter from smb4.conf

---

src/middlewared/middlewared/etc_files/scst.conf.mako
src/middlewared/middlewared/plugins/iscsi_/targets.py
tests/api2/test_261_iscsi_cmd.py

Fix ALUA support for multi-lun iSCSI targets.
Change the return type of `logged_in_iqns` (and `login_ha_targets`) so that **ALL** devices corresponding to each target are returned.  (Now return dict values of a list that will contain e.g. `["13:0:0:0", "13:0:0:1"]` rather than a single string `"13:0:0:1"` (or `"13:0:0:1"`) as previously was the case.)
Update `scst.conf.mako` to take advantage of this new information.
Finally add a corresponding unit test `test_32_multi_lun_targets`.  This will check targets on regular SCALE, or HA SCALE both with and without ALUA enabled.

NAS-126045 / 24.04 / Fix ALUA support for multi-lun iSCSI targets

---

src/middlewared/middlewared/etc_files/scst.conf.mako
src/middlewared/middlewared/plugins/iscsi_/targets.py
tests/api2/test_261_iscsi_cmd.py

git cherry-pick -x 45ac3bee0d381f89705913ac16d7ba725685c7c5
git cherry-pick -x 11c0506d4f5848a34bdbc525922fa4cea43be6d8
Fix ALUA support for multi-lun iSCSI targets.
Change the return type of `logged_in_iqns` (and `login_ha_targets`) so that **ALL** devices corresponding to each target are returned.  (Now return dict values of a list that will contain e.g. `["13:0:0:0", "13:0:0:1"]` rather than a single string `"13:0:0:1"` (or `"13:0:0:1"`) as previously was the case.)
Update `scst.conf.mako` to take advantage of this new information.
Finally add a corresponding unit test `test_32_multi_lun_targets`.  This will …

NAS-126045 / 23.10.2 / Fix ALUA support for multi-lun iSCSI targets (by bmeagherix)

---

src/middlewared/middlewared/auth.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/plugins/service_/utils.py
src/middlewared/middlewared/test/integration/assets/account.py
tests/api2/test_account_privilege_role_private_fields.py
tests/api2/test_account_query_roles.py
tests/api2/test_job_credentials.py

* Credentials had all roles by default. This will be a huge security risk if we start using. roles to determine if users can execute certain things. We should default to `False`, credentials must have roles explicitly.
* As a consequence, token credentials (all WebUI sessions) had all roles, including `READONLY` role. This made the middleware redact all private variables for all return values for WebUI even if we were root.
* `has_role("READONLY")` is a weird way to determine whether we should redact private variables for return values. Should we just only show them to full admins?
* As for the original issue (SMART test schema being inconsistent with the actual return value and failing to redact private variables), let's fix this once we have SMART tests available to non-privileged …

NAS-126058 / 24.04 / Fix roles

---

src/middlewared/middlewared/etc_files/nfs.conf.d/local.conf.mako
tests/api2/test_300_nfs.py

`manage-gids` in the `mountd` section of `/etc/nfs.conf` was enabled In the Debian Bookworm release.
This effected our management of the setting.
The setting was also incorrectly being set with 'True' or 'False'.  The correct settings are 'y' or 'n', respectively.

NAS-126067 / 24.04 / Fix NFS manage-gids conf setting

---

src/middlewared/middlewared/plugins/failover_/event.py

A simple omission is wreaking havoc on ALUA enabled SCALE HA systems. Without `self.HA_PROPAGATE`, the service related requests get sent to the other controller, which in turn, sends them back to the originating controller which sends them to the other controller.....this ends in a service.reload/restart loop.
```
[2024/01/03 14:38:21] (WARNING) middlewared.service_remote():1272 - Failed to run reload(iscsitarget)
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/remote.py", line 130, in call
return self.client.call(*args, **kwargs)
File "/usr/lib/python3/dist-packages/middlewared/client/client.py", line 480, in call
return self.wait(c, callback=callback, job=job, timeout=timeout) …
```

NAS-126072 / 23.10.2 / fix ETOOMANYREFS on SCALE HA

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py

`VrrpObjs.event_queue` should never be `None`. If this was written in C, this would be a null pointer deference 😄 Instead, we're crashing with `AttributeError` as seen below:
```
[2024/01/08 07:40:30] (WARNING) failover.run():249 - vrrp fifo connection not established, retrying every 2 seconds
File "/usr/lib/python3/dist-packages/middlewared/plugins/device_/vrrp_events.py", line 246, in run
self.event_queue.append({'event': event, 'time': time()})
^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append'
```
This error condition should only ever be hit when an HA license is being applied (or removed) but the failure condition is that we miss a failover event which is a much larger issue. This just clears the `deque` object …

NAS-126697 / 23.10.2 / fix AttributeError crash in vrrp event thread

---

src/middlewared/middlewared/plugins/failover_/event.py

The `failover.events.fenced_start_loop` method assumes that `failover.fenced.start` takes 1 second to return. This is not the case since the `fenced` daemon has functionality built-in to wait around 10 or so seconds to see if the reservations on the disk change. If the reservation keys change, then fenced assumes that the other node's fenced daemon is running and so backs off. This is by design and has been this way since the beginning.
This fixes the `fenced_start_loop` to take into account for this wait time and logs accurate messages in logs files. Before these changes, we're populating the log files with messages like these (notice timestamp)
```
[2024/01/08 12:37:35] (WARNING) failover.vrrp_master():376 - Entering MASTER on "eno1".
[2024/01/08 12:37:35] (WARNING) …
```

NAS-126698 / 23.10.2 / fix logic in failover.events.fenced_start_loop

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py

`VrrpObjs.event_queue` should never be `None`. If this was written in C, this would be a null pointer deference 😄 Instead, we're crashing with `AttributeError` as seen below:
```
[2024/01/08 07:40:30] (WARNING) failover.run():249 - vrrp fifo connection not established, retrying every 2 seconds
File "/usr/lib/python3/dist-packages/middlewared/plugins/device_/vrrp_events.py", line 246, in run
self.event_queue.append({'event': event, 'time': time()})
^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append'
```
This error condition should only ever be hit when an HA license is being applied (or removed) but the failure condition is that we miss a failover event which is a much larger issue. This just clears the `deque` object …

NAS-126697 / 23.10.1.1 / fix AttributeError crash in vrrp event thread (by yocalebo)

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py

`VrrpObjs.event_queue` should never be `None`. If this was written in C, this would be a null pointer deference 😄 Instead, we're crashing with `AttributeError` as seen below:
```
[2024/01/08 07:40:30] (WARNING) failover.run():249 - vrrp fifo connection not established, retrying every 2 seconds
File "/usr/lib/python3/dist-packages/middlewared/plugins/device_/vrrp_events.py", line 246, in run
self.event_queue.append({'event': event, 'time': time()})
^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append'
```
This error condition should only ever be hit when an HA license is being applied (or removed) but the failure condition is that we miss a failover event which is a much larger issue. This just clears the `deque` object …

NAS-126697 / 24.04 / fix AttributeError crash in vrrp event thread (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/event.py

A simple omission is wreaking havoc on ALUA enabled SCALE HA systems. Without `self.HA_PROPAGATE`, the service related requests get sent to the other controller, which in turn, sends them back to the originating controller which sends them to the other controller.....this ends in a service.reload/restart loop.
```
[2024/01/03 14:38:21] (WARNING) middlewared.service_remote():1272 - Failed to run reload(iscsitarget)
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/remote.py", line 130, in call
return self.client.call(*args, **kwargs)
File "/usr/lib/python3/dist-packages/middlewared/client/client.py", line 480, in call
return self.wait(c, callback=callback, job=job, timeout=timeout) …
```

NAS-126072 / 24.04 / fix ETOOMANYREFS on SCALE HA (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/event.py

A simple omission is wreaking havoc on ALUA enabled SCALE HA systems. Without `self.HA_PROPAGATE`, the service related requests get sent to the other controller, which in turn, sends them back to the originating controller which sends them to the other controller.....this ends in a service.reload/restart loop.
```
[2024/01/03 14:38:21] (WARNING) middlewared.service_remote():1272 - Failed to run reload(iscsitarget)
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/remote.py", line 130, in call
return self.client.call(*args, **kwargs)
File "/usr/lib/python3/dist-packages/middlewared/client/client.py", line 480, in call
return self.wait(c, callback=callback, job=job, timeout=timeout) …
```

NAS-126072 / 23.10.1.1 / fix ETOOMANYREFS on SCALE HA (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/event.py

The `failover.events.fenced_start_loop` method assumes that `failover.fenced.start` takes 1 second to return. This is not the case since the `fenced` daemon has functionality built-in to wait around 10 or so seconds to see if the reservations on the disk change. If the reservation keys change, then fenced assumes that the other node's fenced daemon is running and so backs off. This is by design and has been this way since the beginning.
This fixes the `fenced_start_loop` to take into account for this wait time and logs accurate messages in logs files. Before these changes, we're populating the log files with messages like these (notice timestamp)
```
[2024/01/08 12:37:35] (WARNING) failover.vrrp_master():376 - Entering MASTER on "eno1".
[2024/01/08 12:37:35] (WARNING) …
```

NAS-126698 / 23.10.1.1 / fix logic in failover.events.fenced_start_loop (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/virtual_ips.py

Fix the following TypeError crash:
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/event.py", line 635, in vrrp_backup
status = self.run_call(
^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/event.py", line 145, in run_call
return self.middleware.call_sync(method, *args)
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1420, in call_sync
return self.run_coroutine(methodobj(*prepared_call.args))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1460, in run_coroutine
return fut.result()
^^^^^^^^^^^^
File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
return self.__get_result() …
```

NAS-126691 / 23.10.2 / fix TypeError crash in failover.vip.check_failover_group

---

src/middlewared/middlewared/plugins/failover_/virtual_ips.py

Fix the following TypeError crash:
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/event.py", line 635, in vrrp_backup
status = self.run_call(
^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/event.py", line 145, in run_call
return self.middleware.call_sync(method, *args)
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1420, in call_sync
return self.run_coroutine(methodobj(*prepared_call.args))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1460, in run_coroutine
return fut.result()
^^^^^^^^^^^^
File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
return self.__get_result() …
```

NAS-126691 / 23.10.1.1 / fix TypeError crash in failover.vip.check_failover_group (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/virtual_ips.py

Fix the following TypeError crash:
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/event.py", line 635, in vrrp_backup
status = self.run_call(
^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/event.py", line 145, in run_call
return self.middleware.call_sync(method, *args)
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1420, in call_sync
return self.run_coroutine(methodobj(*prepared_call.args))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1460, in run_coroutine
return fut.result()
^^^^^^^^^^^^
File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
return self.__get_result() …
```

NAS-126691 / 24.04 / fix TypeError crash in failover.vip.check_failover_group (by yocalebo)

---

src/freenas/usr/local/sbin/hactl
src/middlewared/middlewared/plugins/failover_/disabled_reasons.py

On Cobia, `hactl` is showing a `Failover status: UNKNOWN` when the current node is processing a failover event. This is because a reason `LOC_FAILOVER_ONGOING` is missing in the enum in `hactl`. To fix this issue, I've created a `DisabledReasonsEnum` in `failover_/disabled_reasons.py` module. In `failover.disabled.reasons`, I've used this new enum when adding to the list of reasons of why failover can be non-functional. Finally, I've imported this enum into `hactl` script and used it so that, in theory, problems like this don't happen in the future.

NAS-126705 / 24.04 / Fix hactl returning UNKNOWN status

---

src/freenas/usr/local/sbin/hactl
src/middlewared/middlewared/plugins/failover_/disabled_reasons.py

On Cobia, `hactl` is showing a `Failover status: UNKNOWN` when the current node is processing a failover event. This is because a reason `LOC_FAILOVER_ONGOING` is missing in the enum in `hactl`. To fix this issue, I've created a `DisabledReasonsEnum` in `failover_/disabled_reasons.py` module. In `failover.disabled.reasons`, I've used this new enum when adding to the list of reasons of why failover can be non-functional. Finally, I've imported this enum into `hactl` script and used it so that, in theory, problems like this don't happen in the future.
Original PR: https://github.com/truenas/middleware/pull/12874
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126705

NAS-126705 / 23.10.2 / Fix hactl returning UNKNOWN status (by yocalebo)

---

src/middlewared/middlewared/plugins/interface/netif_linux/netif.py

On HA systems, the UI is immediately showing the login page on a failover event. This means they're making a bunch of API calls related to networking. This is happening too soon (before failover is actually complete) and so various places in middleware are crashing because `netif.list_interfaces()` is crashing.
The exception being raised is actually expected in these circumstances and so we need retry to grab the information when this specific exception is raised.

NAS-125728 / 24.04 / handle NetlinkDumpInterrupted in list_interfaces()

---

src/middlewared/middlewared/etc_files/nfs.conf.d/local.conf.mako
tests/api2/test_300_nfs.py

`manage-gids` in the `mountd` section of `/etc/nfs.conf` was enabled In the Debian Bookworm release.
This effected our management of the setting.
The setting was also incorrectly being set with 'True' or 'False'.  The correct settings are 'y' or 'n', respectively.
Original PR: https://github.com/truenas/middleware/pull/12858
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126067

NAS-126067 / 23.10.2 / Fix NFS manage-gids conf setting (by mgrimesix)

---

tests/api2/test_300_nfs.py

Analysis of the logs from tests where `test_48_syslog_filters` failed found the time to complete the NFS restart was much longer than expected.  In some circumstances it was nearly twice as long and with more unrelated entries.
Fix:  Increase the number of samples taken to allow for slow restarts and widen the syslog search to account for the additional unrelated entries.   The test will exit on the first sample that passes the criteria.

NAS-126724 / 24.04 / NFS syslog filter test:  Add samples and widen search to eliminate false failures

---

tests/api2/test_300_nfs.py

This same fix was added to the Cobia branch.

NAS-126734 / 24.04 / Add delay to allow syslog flush

---

src/middlewared/middlewared/plugins/security/info.py
src/middlewared/middlewared/plugins/security/update.py
src/middlewared/middlewared/plugins/system_advanced/config.py
tests/api2/test_fips.py

This adds 2 new endpoints for the UI team to finalize the Roles work.
1. `system.advanced.sed_global_password_is_set`
2. `system.security.info.fips_available`
Finally, this moves the logic out of the `security/update.py` module to `security/info.py` where it makes sense. There should be no change in functionality.

NAS-126745 / 24.04 / add new endpoints for UI team

---

src/middlewared/middlewared/plugins/smb.py
src/middlewared/middlewared/plugins/smb_/sharesec.py

These APIs were switched to private in Cobia and replaced with sharing.smb.getacl / sharing.smb.setacl.

NAS-126739 / 24.04 / Remove deprecated smb.sharesec APIs

---

tests/api2/test_011_user.py

This test originally manipulated the glusterd user to validate behavior of immutable user. Switch to different user and make sure we're testing the right validation error.

NAS-126794 / 24.04 / Fix test_011 missing user

---

src/middlewared/middlewared/plugins/vm/devices/__init__.py
src/middlewared/middlewared/plugins/vm/devices/display.py
src/middlewared/middlewared/plugins/vm/info.py
src/middlewared/middlewared/plugins/vm/vm_devices.py
src/middlewared/middlewared/plugins/vm/vm_display_info.py
src/middlewared/middlewared/plugins/vm/vm_memory_info.py
src/middlewared/middlewared/plugins/vm/vms.py
tests/api2/test_account_privilege_role_private_fields.py

VM device attributes are generic so `private=True` was not working as desired for VM display devices' password making it visible in plain text for READONLY role.
PR fixes the problem by using OROperator for dynamic inclusion of VM device attributes.

NAS-126788 / 24.04 / Fix VM device attributes schema

---

tests/api2/test_catalog_sync.py

Tests in`test_catalog_sync.py` are failing because the k8s cluster starts unconfiguring before it is fully set up. Consequently, the cluster is unable to stop properly, leading to a timeout error.
In this PR we make changes to make sure the k8s cluster is fully set up before initiating the unconfiguration process. This ensures that the cluster stops properly when needed and subsequently the tests run in a neat/clean manner.

NAS-126741 / 24.04 / Fix catalog sync tests

---

src/middlewared/middlewared/plugins/catalogs_linux/apps.py

We have failing integration tests for app based roles because when using a non admin ROLE values are dumped through return schema and if it is invalid - an exception is raised.
Make sure schema is properly reflected so that `app.available` based integration tests work as desired and a user consuming it through appropriate ROLE has no issue either.

NAS-126802 / 24.04 / Fix app available schema

---

tests/api2/test_account_privilege.py
tests/api2/test_account_privilege_role.py

This commit fixes two account-related regressions in CI tests
* idmap.flush_gencache is now idmap.gencache.flush
* READONLY role was renamed

NAS-126813 / 24.04 / Fix regressions in CI tests

---

src/middlewared/middlewared/plugins/iscsi_/targets.py

Logic (data struct type error) introduced when some code was replicated here.  `extents` needs to be a dict keyed by extent id in order for the loop that generates `target_extents` to work properly.  Currently it was yielding the empty set which is **always** a subset of `cl_extents`.

NAS-126823 / 24.04 / Fix cluster_mode_targets

---

src/middlewared/middlewared/plugins/iscsi_/targets.py

Logic (data struct type error) introduced when some code was replicated here.  `extents` needs to be a dict keyed by extent id in order for the loop that generates `target_extents` to work properly.  Currently it was yielding the empty set which is **always** a subset of `cl_extents`.
Original PR: https://github.com/truenas/middleware/pull/12909
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126823

NAS-126823 / 23.10.2 / Fix cluster_mode_targets (by bmeagherix)

---

src/middlewared/middlewared/plugins/account_/privilege.py
src/middlewared/middlewared/plugins/idmap.py

When LDAP users are presented for directory services privileges the sysadmin may specify a GID rather than SID for identifying the group in question. Convert to string before having libwbclient check whether it's a SID to prevent TypeError.
Fix instance where middleware.call is used instead of middleware.call_sync.

NAS-126825 / 24.04 / Fix regressions caused by SID handling refactor

---

tests/api2/test_vm_roles.py

Tests for `vm.guest_architecture_and_machine_choices` and `vm.device.usb_passthrough_choices` are failing due to runner not supporting virtualization. PR fixes tests by moving these endpoints to the sets handling that appropriately.

NAS-126833 / 24.04 / Fix VM integration tests

---

src/middlewared/middlewared/plugins/audit/audit.py
tests/api2/test_audit_basic.py

Webui needs and endpoint through which to download generated audit reports that allows access for SYSTEM_AUDIT_READ role.
Users are only allowed to download files from their own audit reports directory.

NAS-126850 / 24.10 / Add dedicated endpoint to download audit reports

---

src/middlewared/middlewared/plugins/failover_/event.py

Noticed on a customer's system running Cobia.
```
[2024/01/17 13:18:48] (WARNING) failover.vrrp_master():372 - Received MASTER event for "enp193s0f0np0", but other interfaces "[]" are still working on the MASTER node. Ignoring event.
```

NAS-126859 / 24.10 / fix typo in log message

---

src/middlewared/middlewared/plugins/failover_/event.py

Noticed on a customer's system running Cobia.
```
[2024/01/17 13:18:48] (WARNING) failover.vrrp_master():372 - Received MASTER event for "enp193s0f0np0", but other interfaces "[]" are still working on the MASTER node. Ignoring event.
```
Original PR: https://github.com/truenas/middleware/pull/12919
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126859

NAS-126859 / 24.04-RC.1 / fix typo in log message (by yocalebo)

---

tests/api2/test_catalog_sync.py

The `catalog_sync` test is encountering a timeout error when attempting to unconfigure the kubernetes cluster.
As a permanent solution, we should mock the unconfiguring of k8s cluster because it is not really required for this test to have a functional workflow of setting/unsetting kubernetes cluster - this will reduce time and also help ensure we don't get random failures in the runner.

NAS-126862 / 24.10 / Mock catalog sync unconfigure pool

---

tests/api2/test_kubernetes_delegate_validation.py

In the attachment delegate test for k8s, the order of services can change which is fine so we should not be asserting the exact error statement and rather can just assert snippets in it.

NAS-126866 / 24.10 / Fix kubernetes integration test

---

tests/api2/test_catalog_sync.py

The `catalog_sync` test is encountering a timeout error when attempting to unconfigure the kubernetes cluster.
As a permanent solution, we should mock the unconfiguring of k8s cluster because it is not really required for this test to have a functional workflow of setting/unsetting kubernetes cluster - this will reduce time and also help ensure we don't get random failures in the runner.
Original PR: https://github.com/truenas/middleware/pull/12921
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126862

NAS-126862 / 24.04-RC.1 / Mock catalog sync unconfigure pool (by Qubad786)

---

tests/api2/test_kubernetes_delegate_validation.py

In the attachment delegate test for k8s, the order of services can change which is fine so we should not be asserting the exact error statement and rather can just assert snippets in it.
Original PR: https://github.com/truenas/middleware/pull/12923
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126866

NAS-126866 / 24.04-RC.1 / Fix kubernetes integration test (by sonicaj)

---

src/middlewared/middlewared/plugins/sysdataset.py

`mountpoint` variable was not declared and was being used, so changes have been made to correctly use the relevant variable pointing to the mountpoint.

NAS-126871 / 24.10 / Fix variable not declared usage

---

src/middlewared/middlewared/plugins/directoryservices.py

We don't want to run though this method if controller is not MASTER. Additionally, we should fail early if SMB has not been properly configured (otherwise we will failure with unrelated errors later in this method).
Original PR: https://github.com/truenas/middleware/pull/12930
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126875

NAS-126875 / 23.10.2 / Fail earlier in directoryservices.setup (by anodos325)

---

src/middlewared/middlewared/plugins/activedirectory.py

There are apparent cases of users manually calling the private `activedirectory.start` API via midclt whilst having an incomplete active directory configuration. This may allow winbindd to start and some AD integration to work, but at the cost of having service potentially get disabled during future health checks. This commit adds some rudimentary detection of this situation and will refuse to start the activedirectory service if we're misconfigured. This commit is for backport to Cobia. More recent versions will have more robust fixes.

NAS-126878 / 24.10 / Forcibly disable AD service if misconfigured

---

src/middlewared/middlewared/plugins/activedirectory.py

There are apparent cases of users manually calling the private `activedirectory.start` API via midclt whilst having an incomplete active directory configuration. This may allow winbindd to start and some AD integration to work, but at the cost of having service potentially get disabled during future health checks. This commit adds some rudimentary detection of this situation and will refuse to start the activedirectory service if we're misconfigured. This commit is for backport to Cobia. More recent versions will have more robust fixes.
Original PR: https://github.com/truenas/middleware/pull/12933
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126878

NAS-126878 / 24.04-RC.1 / Forcibly disable AD service if misconfigured (by anodos325)

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py

On SCALE HA systems, our support team often administratively down interfaces during a support session. When this happens, HA isn't completing and fails (by design). The reason why this fails is because of the following:
1. on A node, run `ip link set <iface> down`
2. on A node _NO_ event is generated via the vrrp daemon
3. `fenced` continues to run on A node
4. at same time, VIP floats to B node and receives a MASTER event
5. B node begins to takeover as MASTER and starts `fenced`
6. `fenced` fails on B node because the A node's `fenced` daemon is still running
The failover _failure_ condition is understood and by design (i.e. we fail "safely" because we detected the reservation keys on the disk weren't owned by us and they changed).
The failover _not completing_ is unexpected and is …

NAS-126722 / 24.10 / handle iface fault events on SCALE HA

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py

On SCALE HA systems, our support team often administratively down interfaces during a support session. When this happens, HA isn't completing and fails (by design). The reason why this fails is because of the following:
1. on A node, run `ip link set <iface> down`
2. on A node _NO_ event is generated via the vrrp daemon
3. `fenced` continues to run on A node
4. at same time, VIP floats to B node and receives a MASTER event
5. B node begins to takeover as MASTER and starts `fenced`
6. `fenced` fails on B node because the A node's `fenced` daemon is still running
The failover _failure_ condition is understood and by design (i.e. we fail "safely" because we detected the reservation keys on the disk weren't owned by us and they changed).
The failover _not completing_ is unexpected and is …

NAS-126722 / 23.10.1.2 / handle iface fault events on SCALE HA (by yocalebo)

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py

On SCALE HA systems, our support team often administratively down interfaces during a support session. When this happens, HA isn't completing and fails (by design). The reason why this fails is because of the following:
1. on A node, run `ip link set <iface> down`
2. on A node _NO_ event is generated via the vrrp daemon
3. `fenced` continues to run on A node
4. at same time, VIP floats to B node and receives a MASTER event
5. B node begins to takeover as MASTER and starts `fenced`
6. `fenced` fails on B node because the A node's `fenced` daemon is still running
The failover _failure_ condition is understood and by design (i.e. we fail "safely" because we detected the reservation keys on the disk weren't owned by us and they changed).
The failover _not completing_ is unexpected and is …

NAS-126722 / 23.10.2 / handle iface fault events on SCALE HA (by yocalebo)

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py

On SCALE HA systems, our support team often administratively down interfaces during a support session. When this happens, HA isn't completing and fails (by design). The reason why this fails is because of the following:
1. on A node, run `ip link set <iface> down`
2. on A node _NO_ event is generated via the vrrp daemon
3. `fenced` continues to run on A node
4. at same time, VIP floats to B node and receives a MASTER event
5. B node begins to takeover as MASTER and starts `fenced`
6. `fenced` fails on B node because the A node's `fenced` daemon is still running
The failover _failure_ condition is understood and by design (i.e. we fail "safely" because we detected the reservation keys on the disk weren't owned by us and they changed).
The failover _not completing_ is unexpected and is …

NAS-126722 / 24.04-RC.1 / handle iface fault events on SCALE HA (by yocalebo)

---

src/middlewared/middlewared/plugins/interface/lag.py
src/middlewared/middlewared/plugins/interface/link_address.py
src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
src/middlewared/middlewared/plugins/interface/netif_linux/vrrp.py
src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/pytest/unit/plugins/test_interface_link_address.py

Two issues are being fixed here:
* `ordernum` field missing from the DB update request when upgrading Link Aggregation interface members if any of them is renamed in the kernel. That leads to removing all the members of one Link Aggregation interface on first boot after the upgrade.
* Effective interface link address being used to match real and database network interfaces on boot (interface names can change, for example, on TrueNAS kernel upgrade). If Link Aggregation is configured on interfaces then their effective link addresses will be changed to the one of the Link Aggregation and we will have duplicate entries in the database, yielding incorrect interface matching results. Instead, persistent interface link address should be used for this purpose.
Original PR: …

NAS-126860 / 24.04-BETA.1 / Fix `NOT NULL constraint failed: network_lagginterfacemembers.lagg_or… (by themylogin) (by bugclerk)

---

src/middlewared/middlewared/plugins/interface/lag.py
src/middlewared/middlewared/plugins/interface/link_address.py
src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
src/middlewared/middlewared/plugins/interface/netif_linux/vrrp.py
src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/pytest/unit/plugins/test_interface_link_address.py

Two issues are being fixed here:
* `ordernum` field missing from the DB update request when upgrading Link Aggregation interface members if any of them is renamed in the kernel. That leads to removing all the members of one Link Aggregation interface on first boot after the upgrade.
* Effective interface link address being used to match real and database network interfaces on boot (interface names can change, for example, on TrueNAS kernel upgrade). If Link Aggregation is configured on interfaces then their effective link addresses will be changed to the one of the Link Aggregation and we will have duplicate entries in the database, yielding incorrect interface matching results. Instead, persistent interface link address should be used for this purpose.
Original PR: …

NAS-126860 / 24.04-RC.1 / Fix `NOT NULL constraint failed: network_lagginterfacemembers.lagg_or… (by themylogin)

---

src/middlewared/middlewared/plugins/interface/lag.py
src/middlewared/middlewared/plugins/interface/link_address.py
src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
src/middlewared/middlewared/plugins/interface/netif_linux/vrrp.py
src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/pytest/unit/plugins/test_interface_link_address.py

Two issues are being fixed here:
* `ordernum` field missing from the DB update request when upgrading Link Aggregation interface members if any of them is renamed in the kernel. That leads to removing all the members of one Link Aggregation interface on first boot after the upgrade.
* Effective interface link address being used to match real and database network interfaces on boot (interface names can change, for example, on TrueNAS kernel upgrade). If Link Aggregation is configured on interfaces then their effective link addresses will be changed to the one of the Link Aggregation and we will have duplicate entries in the database, yielding incorrect interface matching results. Instead, persistent interface link address should be used for this purpose.
Original PR: …

NAS-126860 / 23.10.2 / Fix `NOT NULL constraint failed: network_lagginterfacemembers.lagg_or… (by themylogin)

---

src/middlewared/middlewared/plugins/interface/lag.py
src/middlewared/middlewared/plugins/interface/link_address.py
src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
src/middlewared/middlewared/plugins/interface/netif_linux/vrrp.py
src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/pytest/unit/plugins/test_datastore.py
src/middlewared/middlewared/pytest/unit/plugins/test_interface_link_address.py

Two issues are being fixed here:
* `ordernum` field missing from the DB update request when upgrading Link Aggregation interface members if any of them is renamed in the kernel. That leads to removing all the members of one Link Aggregation interface on first boot after the upgrade.
* Effective interface link address being used to match real and database network interfaces on boot (interface names can change, for example, on TrueNAS kernel upgrade). If Link Aggregation is configured on interfaces then their effective link addresses will be changed to the one of the Link Aggregation and we will have duplicate entries in the database, yielding incorrect interface matching results. Instead, persistent interface link address should be used for this purpose.
Original PR: …

NAS-126860 / 23.10.1.3 / Fix `NOT NULL constraint failed: network_lagginterfacemembers.lagg_or… (by themylogin)

---

src/middlewared/middlewared/alert/source/active_directory.py
src/middlewared/middlewared/plugins/activedirectory_/health.py

Include text of ValidationErrors in alert so that it's easier for users and support team to diagnose problems.

NAS-126829 / 24.10 / Improve invalid AD config alert verbosity

---

src/middlewared/middlewared/test/integration/assets/iscsi.py

A recent PR (#12927) was over-zealous in removing some code, which meant that some iSCSI tests were broken.  Restore the code (with minor tweaks to account for the code elsewhere **not** being restored).

NAS-126940 / 24.10 / Undo some breakage wrt iscsi incremental tests

---

src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py

Currently, we only allow one Nvidia GPU to be shared for use by an app in the Nvidia GPU configuration. However, AMD and Intel configurations allow multiple GPUs to be allocated to a single app.
Modify the configuration to allow apps to use more than one Nvidia GPU shared in the Nvidia GPU configuration.

NAS-125859 / 24.10 / Allow multiple NVIDIA gpus to be shared to a single app

---

src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py

Currently, we only allow one Nvidia GPU to be shared for use by an app in the Nvidia GPU configuration. However, AMD and Intel configurations allow multiple GPUs to be allocated to a single app.
Modify the configuration to allow apps to use more than one Nvidia GPU shared in the Nvidia GPU configuration.
Original PR: https://github.com/truenas/middleware/pull/12969
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125859

NAS-125859 / 24.04-RC.1 / Allow multiple NVIDIA gpus to be shared to a single app (by Qubad786)

---

src/middlewared/middlewared/plugins/ipmi_/lan.py

Related to the RBAC changes, the UI was using `failover.call_remote` to query the IPMI LAN information. `failover.call_remote` is for internal use only and is only accessible to root so this fixes `ipmi.lan.query` to take a dictionary with a key `query_remote` which is a boolean. This boolean value, when set to True, will try to query ipmi lan information for the other controller.

NAS-126800 / 24.10 / fix ipmi.lan.query for UI

---

src/middlewared/middlewared/plugins/ipmi_/lan.py

Related to the RBAC changes, the UI was using `failover.call_remote` to query the IPMI LAN information. `failover.call_remote` is for internal use only and is only accessible to root so this fixes `ipmi.lan.query` to take a dictionary with a key `query_remote` which is a boolean. This boolean value, when set to True, will try to query ipmi lan information for the other controller.
Original PR: https://github.com/truenas/middleware/pull/12939
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126800

NAS-126800 / 24.04-RC.1 / fix ipmi.lan.query for UI (by yocalebo)

---

nas_ports/freenas/py-middlewared/Makefile

https://github.com/truenas/ports/pull/1319 has been accepted, howewer middlewared uses wrong dependency

NAS-126969 / 13.1 / middlewared: point dependency to correct path

---

src/middlewared/middlewared/alert/source/ipmi_sel.py
src/middlewared/middlewared/etc_files/smartd.py
src/middlewared/middlewared/plugins/disk.py
src/middlewared/middlewared/plugins/disk_/smartctl.py
src/middlewared/middlewared/plugins/enclosure.py
src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/plugins/system/product.py
src/middlewared/middlewared/plugins/truenas.py

UI was calling `system.is_ix_hardware` for various reasons which was marked as a `private` endpoint. Instead of making changes to that endpoint, I've added a new endpoint called `truenas.is_ix_hardware` which uses the proper logic.
I've also removed the `is_enterprise_ix_hardware` function as that was removed in 8528961fdc2 but the surrounding code was never cleaned up. This unifies all `system.is_ix_hardware` and/or `system.is_enterprise_ix_hardware` to use `truenas.is_ix_hardware`.
I also removed a bunch of references to `TRUENAS-UNKNOWN` strings since that is prone to breakage.

NAS-126959 / 24.10 / add truenas.is_ix_hardware for UI team (RBAC required changes)

---

src/middlewared/middlewared/alert/source/ipmi_sel.py
src/middlewared/middlewared/etc_files/smartd.py
src/middlewared/middlewared/plugins/disk.py
src/middlewared/middlewared/plugins/disk_/smartctl.py
src/middlewared/middlewared/plugins/enclosure.py
src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/plugins/system/product.py
src/middlewared/middlewared/plugins/truenas.py

UI was calling `system.is_ix_hardware` for various reasons which was marked as a `private` endpoint. Instead of making changes to that endpoint, I've added a new endpoint called `truenas.is_ix_hardware` which uses the proper logic.
I've also removed the `is_enterprise_ix_hardware` function as that was removed in 8528961fdc2 but the surrounding code was never cleaned up. This unifies all `system.is_ix_hardware` and/or `system.is_enterprise_ix_hardware` to use `truenas.is_ix_hardware`.
I also removed a bunch of references to `TRUENAS-UNKNOWN` strings since that is prone to breakage.
Original PR: https://github.com/truenas/middleware/pull/12968
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126959

NAS-126959 / 24.04-RC.1 / add truenas.is_ix_hardware for UI team (RBAC required changes) (by yocalebo)

---

src/freenas/usr/lib/netdata/charts.d/nut_ups.chart.sh
src/freenas/usr/lib/netdata/conf.d/charts.d.conf
src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py

If the UPS service is stopped, Netdata will not start the UPS plugin. Even if the UPS service is restarted, Netdata won't start the plugin until Netdata itself is restarted. Additionally, there are bugs related to UPS identifiers, which can change and affect chart names.
Modify the Netdata UPS plugin to send default data if the UPS service is not running. This ensures that Netdata continues to send default stats even when the UPS service is stopped - we handle this gracefully when user tries to retrieve UPS stats when no UPS is running by making sure we are not sharing the default stats. When the UPS service is started, Netdata will begin sending the actual UPS stats. Properly obtain UPS identifiers for use in graphs to ensure the correctness of UPS plugin chart names.

NAS-126842 / 24.10 / Fix UPS reporting plugin

---

src/middlewared/middlewared/plugins/service_/services/ups.py
tests/api2/test_015_services.py

After calling `service.stop ups` the NUT driver continues to record attempts to restart:
`Jan 23 17:49:35 tnee-A systemd[1]: nut-driver@ups.service: Scheduled restart job, restart counter is at 349.
Jan 23 17:49:35 tnee-A systemd[1]: Stopped nut-driver@ups.service - Network UPS Tools - device driver for ups.
Jan 23 17:49:35 tnee-A systemd[1]: Starting nut-driver@ups.service - Network UPS Tools - device driver for ups...
Jan 23 17:49:35 tnee-A nut-driver@ups[34624]: Can't start /lib/nut/(null): No such file or directory
Jan 23 17:49:35 tnee-A nut-driver@ups[34624]: Network UPS Tools - UPS driver controller 2.8.0
Jan 23 17:49:35 tnee-A systemd[1]: nut-driver@ups.service: Control process exited, code=exited, status=1/FAILURE
Jan 23 17:49:35 tnee-A systemd[1]: nut-driver@ups.service: Failed …

NAS-126975 / 24.10 / Update NUT driver systemctl stop function.

---

src/middlewared/middlewared/alert/source/active_directory.py
src/middlewared/middlewared/plugins/activedirectory_/health.py

Include text of ValidationErrors in alert so that it's easier for users and support team to diagnose problems.
Original PR: https://github.com/truenas/middleware/pull/12951
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126829

NAS-126829 / 24.04-RC.1 / Improve invalid AD config alert verbosity (by anodos325)

---

src/middlewared/middlewared/plugins/activedirectory_/dns.py

When adding the server to Active Directory, all registered nameservers must also be part of the Active Directory.  This change adds this hint to the error message.

NAS-126984 / 24.10 / Update the error message with a helpful hint.

---

src/middlewared/middlewared/plugins/failover_/remote.py

With this change the `failover.log` will also include an entry when the connection is reestablished.
```
[2024/01/25 07:59:27] (ERROR) failover.remote.run():52 - Persistent connection refused, retrying every 5 seconds
[2024/01/25 08:01:24] (INFO) failover.remote._on_connect():112 - Persistent connection reestablished
```
If `middlewared` is restarted on the other node, then we see a shorter outage:
```
[2024/01/25 08:23:13] (ERROR) failover.remote.run():52 - Persistent connection refused, retrying every 5 seconds
[2024/01/25 08:23:23] (INFO) failover.remote._on_connect():112 - Persistent connection reestablished
```
Original PR: https://github.com/truenas/middleware/pull/12979
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126986

NAS-126986 / 23.10.2 / Improve logging wrt reestablishment on failover RemoteClient connection (by bmeagherix)

---

src/middlewared/middlewared/plugins/network.py

Before these changes, the user is presented a list of interfaces that are available to be added to a `bond` type interface regardless of whether or not that interface has an associated config tied to it. This means, a user could have configured a physical interface and marked it critical for failover but then added it to the `bond`. This wiped the config on the physical interface silently without any warning to the end-user.
The changes implemented here skips interfaces in the `interface.lag_ports_choices` endpoint to exclude any interface that has an associated config to it. This also prevents the same configuration error from occurring in the `do_create` or `do_update` methods.

NAS-126960 / 24.10 / fix interface.lag_ports_choices and API

---

src/middlewared/middlewared/plugins/network.py

Before these changes, the user is presented a list of interfaces that are available to be added to a `bond` type interface regardless of whether or not that interface has an associated config tied to it. This means, a user could have configured a physical interface and marked it critical for failover but then added it to the `bond`. This wiped the config on the physical interface silently without any warning to the end-user.
The changes implemented here skips interfaces in the `interface.lag_ports_choices` endpoint to exclude any interface that has an associated config to it. This also prevents the same configuration error from occurring in the `do_create` or `do_update` methods.
Original PR: https://github.com/truenas/middleware/pull/12981
Jira URL: …

NAS-126960 / 24.04-RC.1 / fix interface.lag_ports_choices and API (by yocalebo)

---

src/middlewared/middlewared/plugins/network.py

Before these changes, the user is presented a list of interfaces that are available to be added to a `bond` type interface regardless of whether or not that interface has an associated config tied to it. This means, a user could have configured a physical interface and marked it critical for failover but then added it to the `bond`. This wiped the config on the physical interface silently without any warning to the end-user.
The changes implemented here skips interfaces in the `interface.lag_ports_choices` endpoint to exclude any interface that has an associated config to it. This also prevents the same configuration error from occurring in the `do_create` or `do_update` methods.
Original PR: https://github.com/truenas/middleware/pull/12981
Jira URL: …

NAS-126960 / 23.10.2 / fix interface.lag_ports_choices and API (by yocalebo)

---

src/middlewared/middlewared/plugins/filesystem_/acl_template.py

Fix a typo that generated an exception when on the share page in the UI and selecting the `Edit FilesystemACL` for an SMB share.

NAS-126990 / 24.10 / Fix typo

---

src/middlewared/middlewared/alert/source/ipmi_sel.py

Platform team has advised that these platforms have a FIFO for SEL (meaning it never "runs out of space").

NAS-126972 / 24.10 / fix low sel space alert

---

src/middlewared/middlewared/plugins/filesystem_/acl_template.py

Fix a typo that generated an exception when on the share page in the UI and selecting the `Edit FilesystemACL` for an SMB share.
Original PR: https://github.com/truenas/middleware/pull/12991
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126990

NAS-126990 / 24.04-RC.1 / Fix typo (by mgrimesix)

---

src/middlewared/middlewared/alert/source/ipmi_sel.py

Platform team has advised that these platforms have a FIFO for SEL (meaning it never "runs out of space").
Original PR: https://github.com/truenas/middleware/pull/12992
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126972

NAS-126972 / 24.04-RC.1 / fix low sel space alert (by yocalebo)

---

src/middlewared/middlewared/alert/source/ipmi_sel.py

Platform team has advised that these platforms have a FIFO for SEL (meaning it never "runs out of space").
Original PR: https://github.com/truenas/middleware/pull/12992
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126972

NAS-126972 / 23.10.2 / fix low sel space alert (by yocalebo)

---

tests/api2/test_023_kubernetes.py
tests/api2/test_024_container.py

In the test `test_pruning_for_deleted_chart_release_images`, an assertion error still occurs sometimes even after waiting for a container to stop using its ID. After investigation, it appears that if a container of a different ID from the same image is still running, it can also cause this test to fail. This can happen if the container is still running from a previous test.
Wait for the container to terminate in the previous test `test_pruning_for_deleted_chart_release_images`.

NAS-126988 / 24.10 / Fix edge case in container pruning test

---

tests/api2/test_344_acl_templates.py

This adds coverage for non-default options related to retrieving acl templates by path.

NAS-127018 / 24.10 / Add test coverage for resolving names in acl templates

---

tests/api2/test_344_acl_templates.py

This adds coverage for non-default options related to retrieving acl templates by path.
Original PR: https://github.com/truenas/middleware/pull/13005
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127018

NAS-127018 / 24.04-RC.1 / Add test coverage for resolving names in acl templates (by anodos325)

---

tests/api2/test_344_acl_templates.py

This adds coverage for non-default options related to retrieving acl templates by path.
Original PR: https://github.com/truenas/middleware/pull/13005
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127018

NAS-127018 / 23.10.2 / Add test coverage for resolving names in acl templates (by anodos325)

---

src/middlewared/middlewared/alert/source/active_directory.py
src/middlewared/middlewared/plugins/activedirectory_/health.py

Include text of ValidationErrors in alert so that it's easier for users and support team to diagnose problems.
Original PR: https://github.com/truenas/middleware/pull/12951
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126829

NAS-126829 / 23.10.2 / Improve invalid AD config alert verbosity (by anodos325)

---

src/middlewared/middlewared/plugins/chart_releases_linux/schema.py
tests/api2/test_charts_schema.py

PR adds support for charts to specify and use large text data (json, yaml, toml etc) inputs of upto 1 MiB using `text type` in questions.yaml, the idea to allow up to 1 MiB after discussion with Stavros is specifically to make sure this is not abused but still be large enough to accommodate configmap/secret(s) contents.

NAS-127006 / 24.10 / Add a text field schema in catalog format for UI

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py
src/middlewared/middlewared/plugins/network.py

Take the following example:
4x total interfaces
2x marked critical for failover in the same failover group
the other 2x interfaces NOT marked critical for failover
take 1x critical interface down, no failover event is generated (by design since another interface in that group is functional)
take the other critical interface down, failover event is generated (by design since all other interfaces in that group are non-functional)
That's 2 out of the 4 interfaces taken down and a failover event is generated, however, the other controller that is becoming master receives 2 more events for the interfaces that are not marked critical for failover. By design, since these interfaces are not marked critical we ignore the failover event. This leaves HA in a broken state.
The changes being done here …

NAS-126979 / 24.10 / fix SCALE HA failover logic

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py
src/middlewared/middlewared/plugins/network.py

Take the following example:
4x total interfaces
2x marked critical for failover in the same failover group
the other 2x interfaces NOT marked critical for failover
take 1x critical interface down, no failover event is generated (by design since another interface in that group is functional)
take the other critical interface down, failover event is generated (by design since all other interfaces in that group are non-functional)
That's 2 out of the 4 interfaces taken down and a failover event is generated, however, the other controller that is becoming master receives 2 more events for the interfaces that are not marked critical for failover. By design, since these interfaces are not marked critical we ignore the failover event. This leaves HA in a broken state.
The changes being done here …

NAS-126979 / 23.10.2 / fix SCALE HA failover logic (by yocalebo)

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py
src/middlewared/middlewared/plugins/network.py

Take the following example:
4x total interfaces
2x marked critical for failover in the same failover group
the other 2x interfaces NOT marked critical for failover
take 1x critical interface down, no failover event is generated (by design since another interface in that group is functional)
take the other critical interface down, failover event is generated (by design since all other interfaces in that group are non-functional)
That's 2 out of the 4 interfaces taken down and a failover event is generated, however, the other controller that is becoming master receives 2 more events for the interfaces that are not marked critical for failover. By design, since these interfaces are not marked critical we ignore the failover event. This leaves HA in a broken state.
The changes being done here …

NAS-126979 / 24.04-RC.1 / fix SCALE HA failover logic (by yocalebo)

---

src/middlewared/middlewared/plugins/system/debug.py

This is required by UI team to allow readonly user to generate a debug.

NAS-127058 / 24.10 / add READONLY_ADMIN to system.debug

---

src/middlewared/middlewared/plugins/system/debug.py

This is required by UI team to allow readonly user to generate a debug.
Original PR: https://github.com/truenas/middleware/pull/13025
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127058

NAS-127058 / 24.04-RC.1 / add READONLY_ADMIN to system.debug (by yocalebo)

---

src/middlewared/middlewared/plugins/disk_/resize.py
src/middlewared/middlewared/plugins/pool_/expand.py
tests/api2/test_pool_expand.py

@yocalebo this is the part that is absolute must even for 23.10.2. Always partitioning the disk to its fullest size even if we do it (I want to run additional tests to ensure that we can do it, that logic is there for a reason) probably should not be in 23.10.2.

NAS-126809 / 24.10 / Preserve partition start when expanding a pool

---

src/middlewared/middlewared/plugins/disk_/resize.py
src/middlewared/middlewared/plugins/pool_/expand.py
tests/api2/test_pool_expand.py

@yocalebo this is the part that is absolute must even for 23.10.2. Always partitioning the disk to its fullest size even if we do it (I want to run additional tests to ensure that we can do it, that logic is there for a reason) probably should not be in 23.10.2.
Original PR: https://github.com/truenas/middleware/pull/13029
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126809

NAS-126809 / 24.04-RC.1 / Preserve partition start when expanding a pool (by themylogin)

---

src/middlewared/middlewared/plugins/disk_/resize.py
src/middlewared/middlewared/plugins/pool_/expand.py
tests/api2/test_pool_expand.py

@yocalebo this is the part that is absolute must even for 23.10.2. Always partitioning the disk to its fullest size even if we do it (I want to run additional tests to ensure that we can do it, that logic is there for a reason) probably should not be in 23.10.2.
Original PR: https://github.com/truenas/middleware/pull/13029
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126809

NAS-126809 / 23.10.2 / Preserve partition start when expanding a pool (by themylogin)

---

src/middlewared/middlewared/plugins/pool_/dataset.py
tests/api2/test_011_user.py
tests/api2/test_345_acl_nfs4.py

Setting a DISCARD aclmode when NFSv4 acltype is in use. The DISCARD aclmode causes ZFS to strip ACL whenever chmod is called on a file. This may lead to security incidents if administrator sets the parameter without actually knowing what it does.

NAS-126857 / 24.10 / Prevent combination of DISCARD aclmode and NFSv4 acltype

---

src/middlewared/middlewared/plugins/pool_/dataset.py
tests/api2/test_011_user.py
tests/api2/test_345_acl_nfs4.py

Setting a DISCARD aclmode when NFSv4 acltype is in use. The DISCARD aclmode causes ZFS to strip ACL whenever chmod is called on a file. This may lead to security incidents if administrator sets the parameter without actually knowing what it does.
Original PR: https://github.com/truenas/middleware/pull/13014
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126857

NAS-126857 / 24.04-RC.1 / Prevent combination of DISCARD aclmode and NFSv4 acltype (by anodos325)

---

src/middlewared/middlewared/plugins/pool_/dataset.py
tests/api2/test_011_user.py
tests/api2/test_345_acl_nfs4.py

Setting a DISCARD aclmode when NFSv4 acltype is in use. The DISCARD aclmode causes ZFS to strip ACL whenever chmod is called on a file. This may lead to security incidents if administrator sets the parameter without actually knowing what it does.
Original PR: https://github.com/truenas/middleware/pull/13014
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126857

NAS-126857 / 23.10.2 / Prevent combination of DISCARD aclmode and NFSv4 acltype (by anodos325)

---

src/middlewared/middlewared/test/integration/assets/roles.py
tests/api2/test_apps_roles.py
tests/api2/test_certificate_roles.py
tests/api2/test_iscsi_auth_crud_roles.py
tests/api2/test_iscsi_extent_crud_roles.py
tests/api2/test_iscsi_global_crud_roles.py
tests/api2/test_iscsi_host_crud_roles.py
tests/api2/test_iscsi_initiator_crud_roles.py
tests/api2/test_iscsi_portal_crud_roles.py
tests/api2/test_iscsi_target_crud_roles.py
tests/api2/test_iscsi_targetextent_crud_roles.py
tests/api2/test_nfs_share_crud_roles.py
tests/api2/test_smb_share_crud_roles.py
tests/api2/test_vm_roles.py

This PR adds changes optimizing role based integration tests removing subsystem specific logic where we setup relevant resources needed for the subsystem calls to work. However earlier what we were missing was the fact that we don't really need to make sure those calls actually succeed, what we are testing is that does the consumer has relevant role to make that call in the first place - so just checking that the consumer can/cannot make the call is enough. This saves time/resources optimizing the integration tests for the specific case they are written for.

NAS-127079 / 24.10 / Optimize role based integration tests

---

src/middlewared/middlewared/plugins/ipmi_/lan.py

The `channel` argument is an integer but must be converted to a string since we're calling `subprocess.run`

NAS-127109 / 24.10 / fix TypeError crash in ipmi.lan.update

---

src/middlewared/middlewared/plugins/ipmi_/lan.py

The `channel` argument is an integer but must be converted to a string since we're calling `subprocess.run`
Original PR: https://github.com/truenas/middleware/pull/13045
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127109

NAS-127109 / 24.04-RC.1 / fix TypeError crash in ipmi.lan.update (by yocalebo)

---

src/middlewared/middlewared/service/crud_service.py
tests/api2/test_crud.py

`offset` and `limit` parameters were being applied twice, one at the sql level and the then again at middleware level.
PR fixes the problem by making sure this is not done at database level keeping in line with some other parameters we remove as well already.

NAS-126080 / 24.10 / Fix pagination parameters

---

src/middlewared/middlewared/service/crud_service.py
tests/api2/test_crud.py

git cherry-pick -x 760bda0a21146c28e019c807ae8fbe5de47d8193
git cherry-pick -x b8d927cf869db72199c314967072917ca934c955
git cherry-pick -x 89e2d4bca9646fc8b3366fd277f16746d982cdf1
`offset` and `limit` parameters were being applied twice, one at the sql level and the then again at middleware level.
PR fixes the problem by making sure this is not done at database level keeping in line with some other parameters we remove as well already.
Original PR: https://github.com/truenas/middleware/pull/12970
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126080

NAS-126080 / 23.10.2 / Fix pagination parameters (by Qubad786)

---

src/middlewared/middlewared/service.py

git cherry-pick -x 760bda0a21146c28e019c807ae8fbe5de47d8193
git cherry-pick -x b8d927cf869db72199c314967072917ca934c955
git cherry-pick -x 89e2d4bca9646fc8b3366fd277f16746d982cdf1
`offset` and `limit` parameters were being applied twice, one at the sql level and the then again at middleware level.
PR fixes the problem by making sure this is not done at database level keeping in line with some other parameters we remove as well already.
Original PR: https://github.com/truenas/middleware/pull/12970
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126080

NAS-126080 / 13.1 / Fix pagination parameters (by Qubad786)

---

src/middlewared/middlewared/plugins/pool_/dataset.py
tests/api2/test_340_pool_dataset.py
tests/api2/test_344_acl_templates.py

This commit fixes a KeyError that may be raised when dataset update payload does not contain the acltype or aclmode keys.
Original PR: https://github.com/truenas/middleware/pull/13053
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127127

NAS-127127 / 24.04-RC.1 / Fix regression in validation for dataset parameters (by anodos325)

---

src/middlewared/middlewared/plugins/pool_/dataset.py
tests/api2/test_340_pool_dataset.py
tests/api2/test_344_acl_templates.py

This commit fixes a KeyError that may be raised when dataset update payload does not contain the acltype or aclmode keys.
Original PR: https://github.com/truenas/middleware/pull/13053
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127127

NAS-127127 / 23.10.2 / Fix regression in validation for dataset parameters (by anodos325)

---

src/middlewared/middlewared/service/crud_service.py

If role prefix is defined, allow corresponding READ role to subscribe to events by default.

NAS-127132 / 24.10 / Add roles to subscriptions for CRUD services

---

src/middlewared/middlewared/service/crud_service.py

If role prefix is defined, allow corresponding READ role to subscribe to events by default.
Original PR: https://github.com/truenas/middleware/pull/13058
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127132

NAS-127132 / 24.04-RC.1 / Add roles to subscriptions for CRUD services (by anodos325)

---

src/middlewared/middlewared/plugins/activedirectory.py
tests/api2/test_006_pool_and_sysds.py

This mirrors validation that already takes place when attempting to move the system dataset while AD is enabled.

NAS-126939 / 24.10 / Add earlier validation to prevent enabling AD without pool

---

src/middlewared/middlewared/plugins/activedirectory.py
tests/api2/test_006_pool_and_sysds.py

This mirrors validation that already takes place when attempting to move the system dataset while AD is enabled.
Original PR: https://github.com/truenas/middleware/pull/13043
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126939

NAS-126939 / 24.04-RC.1 / Add earlier validation to prevent enabling AD without pool (by anodos325)

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/activedirectory_/health.py
src/middlewared/middlewared/plugins/directoryservices.py
src/middlewared/middlewared/plugins/idmap.py
src/middlewared/middlewared/plugins/kerberos.py
src/middlewared/middlewared/plugins/ldap.py
src/middlewared/middlewared/role.py

This commit adds read and write roles for endpoints related to directory services LDAP, Active Directory, and Kerberos. Since the functionality is all inter-connected, we use single set of roles for all of these plugins.

NAS-127134 / 24.10 / Add roles for directory services

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/activedirectory_/health.py
src/middlewared/middlewared/plugins/directoryservices.py
src/middlewared/middlewared/plugins/idmap.py
src/middlewared/middlewared/plugins/kerberos.py
src/middlewared/middlewared/plugins/ldap.py
src/middlewared/middlewared/role.py

This commit adds read and write roles for endpoints related to directory services LDAP, Active Directory, and Kerberos. Since the functionality is all inter-connected, we use single set of roles for all of these plugins.
Original PR: https://github.com/truenas/middleware/pull/13061
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127134

NAS-127134 / 24.04-RC.1 / Add roles for directory services (by anodos325)

---

src/middlewared/middlewared/plugins/pool.py

The original commit didn't remove all the references to the `devname` key (https://github.com/truenas/middleware/pull/11612)

NAS-127095 / 13.1 / fix KeyError crash in pool.py

---

src/freenas/usr/lib/netdata/charts.d/nut_ups.chart.sh
src/freenas/usr/lib/netdata/conf.d/charts.d.conf
src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py

If the UPS service is stopped, Netdata will not start the UPS plugin. Even if the UPS service is restarted, Netdata won't start the plugin until Netdata itself is restarted. Additionally, there are bugs related to UPS identifiers, which can change and affect chart names.
Modify the Netdata UPS plugin to send default data if the UPS service is not running. This ensures that Netdata continues to send default stats even when the UPS service is stopped - we handle this gracefully when user tries to retrieve UPS stats when no UPS is running by making sure we are not sharing the default stats. When the UPS service is started, Netdata will begin sending the actual UPS stats. Properly obtain UPS identifiers for use in graphs to ensure the correctness of UPS plugin chart names.
Original PR: …

NAS-126842 / 24.04-RC.1 / Fix UPS reporting plugin (by Qubad786)

---

src/middlewared/middlewared/plugins/chart_releases_linux/utils.py

The `scaleVersion` attribute holds the TN Scale version in ixChartContext in order to provide app developers exposure to current running scale version as requested by Stavros.

NAS-127099 / 24.10 / Add scale version to app's config

---

src/middlewared/middlewared/plugins/account_/privilege.py
tests/api2/test_account_privilege.py

This was an oversight when we added roles to privileges framework.
Allowlists are readonly for builtin privileges. In keeping with same
design, we should also prevent changing roles

NAS-127223 / 24.10 / Prevent users from editing roles for builtin privileges

---

src/middlewared/middlewared/plugins/account_/privilege.py
tests/api2/test_account_privilege.py

This was an oversight when we added roles to privileges framework.
Allowlists are readonly for builtin privileges. In keeping with same
design, we should also prevent changing roles
Original PR: https://github.com/truenas/middleware/pull/13088
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127223

NAS-127223 / 24.04-BETA.1 / Prevent users from editing roles for builtin privileges (by anodos325)

---

src/middlewared/middlewared/plugins/account_/privilege.py
tests/api2/test_account_privilege.py

This was an oversight when we added roles to privileges framework.
Allowlists are readonly for builtin privileges. In keeping with same
design, we should also prevent changing roles
Original PR: https://github.com/truenas/middleware/pull/13088
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127223

NAS-127223 / 24.04-RC.1 / Prevent users from editing roles for builtin privileges (by anodos325)

---

src/middlewared/middlewared/plugins/rsync.py

Changes the format of rsync push in module mode.
While the current format is valid based on the man pages (https://rsync.samba.org/ftp/rsync/rsync.html), it prompts for password, but the new proposed format does not.
Modified this on a test **Core** system and
And Rsync task worked, while previously it was failing with auth error (publickey,password).

NAS-127158 / 24.10 / change format of rsync push in module mode

---

src/middlewared/middlewared/plugins/rsync.py

git cherry-pick -x e1e982771889424b803b4ed7720e4af64d035d4a
git cherry-pick -x b7b7e0b9c3e5083b6ce6e67df91bb7e088a21100
Changes the format of rsync push in module mode.
While the current format is valid based on the man pages (https://rsync.samba.org/ftp/rsync/rsync.html), it prompts for password, but the new proposed format does not.
Modified this on a test **Core** system and
And Rsync task worked, while previously it was failing with auth error (publickey,password).
Original PR: https://github.com/truenas/middleware/pull/13094
Jira URL: …

NAS-127158 / 13.1 / change format of rsync push in module mode (by stavros-k)

---

src/middlewared/middlewared/plugins/nfs.py
tests/api2/test_300_nfs.py

The NFS share validator had logic that allowed a secondary check
NFS share has more than one layer of validation.  There was a logic flaw in a secondary validator that over rode an earlier check.
The error text associated with the earlier check is a better match for _that_ error.   The secondary check traps similar, but different enough to error condition to warrant a different error message.
The fix was to correct the logic to exclude the secondary check from trapping the error.
Enhance NFS CI testing around NFS share validation.

NAS-127220 / 24.10 / Fix logic error in NFS share validation.

---

src/middlewared/middlewared/plugins/nfs.py
tests/api2/test_300_nfs.py

The NFS share validator had logic that allowed a secondary check
NFS share has more than one layer of validation.  There was a logic flaw in a secondary validator that over rode an earlier check.
The error text associated with the earlier check is a better match for _that_ error.   The secondary check traps similar, but different enough to error condition to warrant a different error message.
The fix was to correct the logic to exclude the secondary check from trapping the error.
Enhance NFS CI testing around NFS share validation.
Original PR: https://github.com/truenas/middleware/pull/13092
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127220

NAS-127220 / 24.04-RC.1 / Fix logic error in NFS share validation. (by mgrimesix)

---

src/middlewared/middlewared/plugins/catalogs_linux/update.py

This PR fixes a problem where we were still using temp dir when a new catalog was being added so we could validate it before adding it to the system. With the changes, now we use the apps dataset to hold the catalog and validate it for any issues.
Original PR: https://github.com/truenas/middleware/pull/13100
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127213

NAS-127213 / 23.10.2 / Do not use ix temp dir when creating catalogs (by sonicaj)

---

src/middlewared/middlewared/plugins/container_runtime_interface/containerd_utils.py
src/middlewared/middlewared/plugins/container_runtime_interface/utils.py
src/middlewared/middlewared/plugins/kubernetes_linux/nodes.py

This PR adds changes to consume containerd socket instead of just connecting to the socket to see if it is available. Problem we see is that sometimes it is possible the socket can be connected to but containerd is still initiating itself which leads to calls failing which involve containerd.

NAS-125640 / 24.10 / Improve checking if containerd socket is available

---

src/freenas/etc/systemd/system/netdata.service.d/override.conf

On the first boot, when netdata is initializing for the first time, if smartd starts after netdata's smart_log plugin has started, it will cause the smart_log plugin's check to fail. This is because smartd is not started yet, and the smart_log plugin requires its CSV files to get disk temperature.
1. First, stop smartd.
2. Delete the smartd `smartmontools` folder.
3. Turn off and on netdata's smart_log plugin, followed by a system restart in each case to emulate the first boot scenario.
4. Reboot the system.
5. Start smartd by creating its folder and starting its service.
Observation: We will observe that netdata will not collect disk temperature until it is restarted.
I was not able to reproduce exactly the reporter's issue because of the system i am testing on is not entirely based off …

NAS-127100 / 24.10 / Fix netdata boot order

---

src/freenas/etc/systemd/system/netdata.service.d/override.conf

On the first boot, when netdata is initializing for the first time, if smartd starts after netdata's smart_log plugin has started, it will cause the smart_log plugin's check to fail. This is because smartd is not started yet, and the smart_log plugin requires its CSV files to get disk temperature.
1. First, stop smartd.
2. Delete the smartd `smartmontools` folder.
3. Turn off and on netdata's smart_log plugin, followed by a system restart in each case to emulate the first boot scenario.
4. Reboot the system.
5. Start smartd by creating its folder and starting its service.
Observation: We will observe that netdata will not collect disk temperature until it is restarted.
I was not able to reproduce exactly the reporter's issue because of the system i am testing on is not entirely based off …

NAS-127100 / 23.10.2 / Fix netdata boot order (by Qubad786)

---

src/freenas/etc/systemd/system/netdata.service.d/override.conf

On the first boot, when netdata is initializing for the first time, if smartd starts after netdata's smart_log plugin has started, it will cause the smart_log plugin's check to fail. This is because smartd is not started yet, and the smart_log plugin requires its CSV files to get disk temperature.
1. First, stop smartd.
2. Delete the smartd `smartmontools` folder.
3. Turn off and on netdata's smart_log plugin, followed by a system restart in each case to emulate the first boot scenario.
4. Reboot the system.
5. Start smartd by creating its folder and starting its service.
Observation: We will observe that netdata will not collect disk temperature until it is restarted.
I was not able to reproduce exactly the reporter's issue because of the system i am testing on is not entirely based off …

NAS-127100 / 23.10.3 / Fix netdata boot order (by Qubad786)

---

src/freenas/etc/systemd/system/netdata.service.d/override.conf

On the first boot, when netdata is initializing for the first time, if smartd starts after netdata's smart_log plugin has started, it will cause the smart_log plugin's check to fail. This is because smartd is not started yet, and the smart_log plugin requires its CSV files to get disk temperature.
1. First, stop smartd.
2. Delete the smartd `smartmontools` folder.
3. Turn off and on netdata's smart_log plugin, followed by a system restart in each case to emulate the first boot scenario.
4. Reboot the system.
5. Start smartd by creating its folder and starting its service.
Observation: We will observe that netdata will not collect disk temperature until it is restarted.
I was not able to reproduce exactly the reporter's issue because of the system i am testing on is not entirely based off …

NAS-127100 / 24.04-RC.1 / Fix netdata boot order (by Qubad786)

---

src/middlewared/middlewared/main.py

The test `test_chart_release_acl_apply.py` is failing because it uses acl normalization of paths, and acl normalization uses the core.bulk API to apply acl on multiple paths at once. The bug exists in the core.bulk API because it expects the `@pass_app` parameter, and we are not providing it in acl normalization. This is causing a `NoneType` error when it tries to authenticate credentials while calling the `call_with_audit` API.
Authenticate app's credentials only when the app object is present.
- [core_service.py](https://github.com/truenas/middleware/blob/8eb4000954f60818e64f625da2ab9137984e9722/src/middlewared/middlewared/service/core_service.py#L763)
- [acl.py](https://github.com/truenas/middleware/blob/8eb4000954f60818e64f625da2ab9137984e9722/src/middlewared/middlewared/plugins/chart_ …

NAS-127302 / 24.10 / Fix app authentication error

---

src/middlewared/middlewared/plugins/container_runtime_interface/containerd_utils.py
src/middlewared/middlewared/plugins/container_runtime_interface/utils.py
src/middlewared/middlewared/plugins/kubernetes_linux/nodes.py

This PR adds changes to consume containerd socket instead of just connecting to the socket to see if it is available. Problem we see is that sometimes it is possible the socket can be connected to but containerd is still initiating itself which leads to calls failing which involve containerd.
Original PR: https://github.com/truenas/middleware/pull/13093
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125640

NAS-125640 / 24.04-RC.1 / Improve checking if containerd socket is available (by sonicaj)

---

src/middlewared/middlewared/main.py

The test `test_chart_release_acl_apply.py` is failing because it uses acl normalization of paths, and acl normalization uses the core.bulk API to apply acl on multiple paths at once. The bug exists in the core.bulk API because it expects the `@pass_app` parameter, and we are not providing it in acl normalization. This is causing a `NoneType` error when it tries to authenticate credentials while calling the `call_with_audit` API.
Authenticate app's credentials only when the app object is present.
- [core_service.py](https://github.com/truenas/middleware/blob/8eb4000954f60818e64f625da2ab9137984e9722/src/middlewared/middlewared/service/core_service.py#L763)
- [acl.py](https://github.com/truenas/middleware/blob/8eb4000954f60818e64f625da2ab9137984e9722/src/middlewared/middlewared/plugins/chart_ …

NAS-127302 / 24.04-RC.1 / Fix app authentication error (by Qubad786)

---

src/middlewared/middlewared/plugins/zfs_/pool_status.py

When a device is removed from the system, zpool status output would show the guid partition label and show `REMOVED` in the state column. We weren't showing that properly in this endpoint. It was being resolved to `block` because sysfs `/sys/class/block/<gptid>` didn't exist. This changes the endpoint to catch this type of scenario.

NAS-127317 / 24.10 / fix output of zpool.status when dev is removed

---

src/middlewared/middlewared/plugins/zfs_/pool_status.py

When a device is removed from the system, zpool status output would show the guid partition label and show `REMOVED` in the state column. We weren't showing that properly in this endpoint. It was being resolved to `block` because sysfs `/sys/class/block/<gptid>` didn't exist. This changes the endpoint to catch this type of scenario.
Original PR: https://github.com/truenas/middleware/pull/13118
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127317

NAS-127317 / 24.04-RC.1 / fix output of zpool.status when dev is removed (by yocalebo)

---

src/middlewared/middlewared/utils/privilege.py
tests/api2/test_auth_me.py

We need to allow webui access if at least one of user roles grant webui access.

NAS-127267 / 24.10 / Fix webui access flag in auth.me for custom privileges

---

src/middlewared/middlewared/utils/privilege.py
tests/api2/test_auth_me.py

We need to allow webui access if at least one of user roles grant webui access.
Original PR: https://github.com/truenas/middleware/pull/13117
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127267

NAS-127267 / 24.04-RC.1 / Fix webui access flag in auth.me for custom privileges (by anodos325)

---

src/middlewared/middlewared/etc_files/scst.conf.mako
src/middlewared/middlewared/plugins/dlm.py
src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/iscsi_/alua.py
src/middlewared/middlewared/plugins/iscsi_/extents.py
src/middlewared/middlewared/plugins/iscsi_/scst.py
src/middlewared/middlewared/plugins/iscsi_/target_to_extent.py
src/middlewared/middlewared/plugins/iscsi_/targets.py
src/middlewared/middlewared/plugins/service.py
src/middlewared/middlewared/plugins/service_/services/base.py
src/middlewared/middlewared/plugins/service_/services/base_interface.py
src/middlewared/middlewared/plugins/service_/services/iscsitarget.py
tests/api2/test_261_iscsi_cmd.py

SCST uses a script `scstadmin` to load the config file into the kernel.  This done serially, so when large configurations are present it can be slow.
Further, iSCSI ALUA targets use the linux kernel `dlm` (distributed lock manager).  Configuration requires the interaction of the kernel and middleware on both nodes.  This can be slow, especially when many targets are present. 
A couple of changes to SCST have been made to improve configuration/lifecycle performance (PRs #[19](https://github.com/truenas/scst/pull/19) and #[23](https://github.com/truenas/scst/pull/23)).  Also allowed `vdisk_fileio` to use the same active parameter as `vdisk_blockio` (PR #[26](https://github.com/truenas/scst/pull/26)) - more below.
This PR contains substantial changes being made to middleware to further …

NAS-126731 / 24.10 / Improve failover handling of a large number of targets

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/account_/privilege.py

local and ds groups are written via group ID, but are returned as full group entries.
Original PR: https://github.com/truenas/middleware/pull/13123
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127268

NAS-127268 / 24.04-RC.1 / Fix schema for privilege plugin (by anodos325)

---

src/freenas/usr/bin/install-dev-tools

This commit fixes an issue where checking file's existence we were running it whereas it required middlewared to be actually running - now this becomes a problem in our unit tests pipeline as middleware is not running in the docker container we create and these changes are not really required either for us torun the unit tests etc.

NAS-127319 / 24.10 / Make sure middleware socket is present

---

src/middlewared/middlewared/etc_files/scst.conf.mako
src/middlewared/middlewared/plugins/dlm.py
src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/iscsi_/alua.py
src/middlewared/middlewared/plugins/iscsi_/extents.py
src/middlewared/middlewared/plugins/iscsi_/scst.py
src/middlewared/middlewared/plugins/iscsi_/target_to_extent.py
src/middlewared/middlewared/plugins/iscsi_/targets.py
src/middlewared/middlewared/plugins/service.py
src/middlewared/middlewared/plugins/service_/services/base.py
src/middlewared/middlewared/plugins/service_/services/base_interface.py
src/middlewared/middlewared/plugins/service_/services/iscsitarget.py
tests/api2/test_261_iscsi_cmd.py

SCST uses a script `scstadmin` to load the config file into the kernel.  This done serially, so when large configurations are present it can be slow.
Further, iSCSI ALUA targets use the linux kernel `dlm` (distributed lock manager).  Configuration requires the interaction of the kernel and middleware on both nodes.  This can be slow, especially when many targets are present. 
A couple of changes to SCST have been made to improve configuration/lifecycle performance (PRs #[19](https://github.com/truenas/scst/pull/19) and #[23](https://github.com/truenas/scst/pull/23)).  Also allowed `vdisk_fileio` to use the same active parameter as `vdisk_blockio` (PR #[26](https://github.com/truenas/scst/pull/26)) - more below.
This PR contains substantial changes being made to middleware to further …

NAS-126731 / 24.04-RC.1 / Improve failover handling of a large number of targets (by bmeagherix)

---

src/middlewared/middlewared/etc_files/scst.conf.mako
src/middlewared/middlewared/plugins/dlm.py
src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/iscsi_/alua.py
src/middlewared/middlewared/plugins/iscsi_/extents.py
src/middlewared/middlewared/plugins/iscsi_/scst.py
src/middlewared/middlewared/plugins/iscsi_/target_to_extent.py
src/middlewared/middlewared/plugins/iscsi_/targets.py
src/middlewared/middlewared/plugins/service.py
src/middlewared/middlewared/plugins/service_/services/base.py
src/middlewared/middlewared/plugins/service_/services/base_interface.py
src/middlewared/middlewared/plugins/service_/services/iscsitarget.py
tests/api2/test_261_iscsi_cmd.py

SCST uses a script `scstadmin` to load the config file into the kernel.  This done serially, so when large configurations are present it can be slow.
Further, iSCSI ALUA targets use the linux kernel `dlm` (distributed lock manager).  Configuration requires the interaction of the kernel and middleware on both nodes.  This can be slow, especially when many targets are present. 
A couple of changes to SCST have been made to improve configuration/lifecycle performance (PRs #[19](https://github.com/truenas/scst/pull/19) and #[23](https://github.com/truenas/scst/pull/23)).  Also allowed `vdisk_fileio` to use the same active parameter as `vdisk_blockio` (PR #[26](https://github.com/truenas/scst/pull/26)) - more below.
This PR contains substantial changes being made to middleware to further …

NAS-126731 / 23.10.2 / Improve failover handling of a large number of targets (by bmeagherix)

---

src/middlewared/middlewared/alembic/versions/24.10/2024-02-12_19-47_add_enable_learning_flag.py
src/middlewared/middlewared/plugins/interface/bridge.py
src/middlewared/middlewared/plugins/interface/netif_linux/bridge.py
src/middlewared/middlewared/plugins/network.py

This commit fixes an issue where on certain hardware, the bridge interface takes some time to set up, causing a delay in network setup and disrupting other services when they attempt to use the network. To address this issue after syncing with Caleb we decided that we will disable learning of all bridge members allowing the bridge to become active without unnecessary delay

NAS-125367 / 24.10 / Disable learning of bridge interface members

---

src/middlewared/middlewared/plugins/cache.py

entry may be None type if user has queried a non-existent user directly via filters (for example ['name', '=', 'bob']).

NAS-127336 / 24.10 /  Fix TypeError on lookup failure for DS users

---

src/middlewared/middlewared/plugins/cache.py

entry may be None type if user has queried a non-existent user directly via filters (for example ['name', '=', 'bob']).
Original PR: https://github.com/truenas/middleware/pull/13130
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127336

NAS-127336 / 24.04-RC.1 /  Fix TypeError on lookup failure for DS users (by anodos325)

---

src/middlewared/middlewared/plugins/idmap.py

We should raise a ValidationError on duplicate DNS names because there shouldn't be multiple idmap backends configured for a single domain.

NAS-127341 / 24.10 / idmap: add validation to prevent duplicate DNS names

---

src/freenas/usr/lib/netdata/python.d/k3s_stats.chart.py

Some k3s pods don't use the network at all, and as a result, their network stats don't appear in the k3s stats summary. This can cause a network key error in the netdata k3s_stats plugin, leading to an abnormal exit of the plugin. Consequently, netdata is unable to report stats for any pods.
Handle the 'networks' key appropriately to prevent key errors in such cases.

NAS-127269 / 24.10 / Handle missing k3s network stats in k3s netdata plugin

---

src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py

This commit adds changes marking app's config as private as it can contain potentially passwords/secrets of user's app configuration.

NAS-126925 / 24.10 / Mark app's config as private

---

src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py

This commit adds changes marking app's config as private as it can contain potentially passwords/secrets of user's app configuration.
Original PR: https://github.com/truenas/middleware/pull/13105
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126925

NAS-126925 / 24.04-RC.1 / Mark app's config as private (by sonicaj)

---

src/middlewared/middlewared/plugins/idmap.py

In a previous refactor ([PR #13001](https://github.com/truenas/middleware/pull/13001)) `directoryservices.set_ldap_secret` was changed to `directoryservices.secrets.set_ldap_idmap_secret`, but one call was incorrectly updated.

NAS-127367 / 24.10 / Changed set_ldap_secret call to set_ldap_idmap_secret

---

src/middlewared/middlewared/apidocs/templates/websocket/query.md
src/middlewared/middlewared/plugins/chart_releases_linux/portals.py
src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
src/middlewared/middlewared/utils/__init__.py

There are some cases where API user may wish to query an endpoint based on nested values within a list. For example
[["local_groups.*.name", "=", "bad"]] passed to privilege.query to return all privileges where the group "bad" is present in the list of local groups to which the privilege applies.

NAS-127350 / 24.10 / Add ability to filter by keys in list objects

---

src/middlewared/middlewared/plugins/network.py

This commit fixes keyerror in `interface.update` as for bridge interface, db column name is `members` and not `bridge_members`.

NAS-127362 / 24.10 / Properly reflect bridge members when updating bridge settings

---

src/middlewared/middlewared/plugins/system/debug.py

There is no way currently to determine that which compressed file belongs to active or which belongs to standby when a debug for a HA system is taken. The changes made label the compressed folder to represent that they belong to active/standby appropriately.

NAS-127157 / 24.10 / Mark HA nodes as active/standby in debug

---

src/middlewared/middlewared/plugins/system/debug.py

There is no way currently to determine that which compressed file belongs to active or which belongs to standby when a debug for a HA system is taken. The changes made label the compressed folder to represent that they belong to active/standby appropriately.
Original PR: https://github.com/truenas/middleware/pull/13114
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127157

NAS-127157 / 24.04-RC.1 / Mark HA nodes as active/standby in debug (by Qubad786)

---

src/middlewared/middlewared/etc_files/keepalived.conf.mako
src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/failover_/vrrp.py

if 2x interfaces are in the same failover group and 1 of them goes
down, the VIP will float to the other controller. However, a failover
won't happen because the other interface is still UP on the master.
If the down'ed interface comes back online, the VIP needs to float
back to the original master controller. Reloading keepalived service
re-generates the configuration file which ensures the config has the
right priority set.
To ensure the VIP floats back to the original master, this does 2 primary things:
1. set priority property on the master/backup controllers appropriately (higher priority wins)
2. enable preemption

NAS-127366 / 24.10 / fix failover group logic

---

src/middlewared/middlewared/etc_files/keepalived.conf.mako
src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/failover_/vrrp.py

if 2x interfaces are in the same failover group and 1 of them goes
down, the VIP will float to the other controller. However, a failover
won't happen because the other interface is still UP on the master.
If the down'ed interface comes back online, the VIP needs to float
back to the original master controller. Reloading keepalived service
re-generates the configuration file which ensures the config has the
right priority set.
To ensure the VIP floats back to the original master, this does 2 primary things:
1. set priority property on the master/backup controllers appropriately (higher priority wins)
2. enable preemption
Original PR: https://github.com/truenas/middleware/pull/13155
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127366

NAS-127366 / 23.10.2 / fix failover group logic (by yocalebo)

---

src/middlewared/middlewared/etc_files/keepalived.conf.mako
src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/failover_/vrrp.py

if 2x interfaces are in the same failover group and 1 of them goes
down, the VIP will float to the other controller. However, a failover
won't happen because the other interface is still UP on the master.
If the down'ed interface comes back online, the VIP needs to float
back to the original master controller. Reloading keepalived service
re-generates the configuration file which ensures the config has the
right priority set.
To ensure the VIP floats back to the original master, this does 2 primary things:
1. set priority property on the master/backup controllers appropriately (higher priority wins)
2. enable preemption
Original PR: https://github.com/truenas/middleware/pull/13155
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127366

NAS-127366 / 23.10.3 / fix failover group logic (by yocalebo)

---

src/middlewared/middlewared/etc_files/keepalived.conf.mako
src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/failover_/vrrp.py

if 2x interfaces are in the same failover group and 1 of them goes
down, the VIP will float to the other controller. However, a failover
won't happen because the other interface is still UP on the master.
If the down'ed interface comes back online, the VIP needs to float
back to the original master controller. Reloading keepalived service
re-generates the configuration file which ensures the config has the
right priority set.
To ensure the VIP floats back to the original master, this does 2 primary things:
1. set priority property on the master/backup controllers appropriately (higher priority wins)
2. enable preemption
Original PR: https://github.com/truenas/middleware/pull/13155
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127366

NAS-127366 / 24.04-RC.1 / fix failover group logic (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/event.py

Noticed on a customer's system running Cobia.
```
[2024/01/17 13:18:48] (WARNING) failover.vrrp_master():372 - Received MASTER event for "enp193s0f0np0", but other interfaces "[]" are still working on the MASTER node. Ignoring event.
```
Original PR: https://github.com/truenas/middleware/pull/12919
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126859

NAS-126859 / 23.10.2 / fix typo in log message (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/event.py

QE team is discovering edge cases with our HA failover logic and has pointed out the fact that we can do better with our logging. This fixes very minor logging typos so that the logs are accurate which will benefit more than just the development team but also the QE/Support teams.
Original PR: https://github.com/truenas/middleware/pull/13168
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127390

NAS-127390 / 24.04-RC.1 / better HA logging (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/event.py

A race condition exists where a `vrrp_master` job would start and then a `vrrp_backup` would subsequently start and depending on which method was the quickest, they would both interact with `fenced` which ultimately ended up with fenced exiting with EBADF. This is because the 2 methods run in their own native threads. There are 2 subtle issues and that is the controller would become `vrrp_master` and `vrrp_backup` almost simultaneously and then fenced would error with EBADF.
To fix both issues:
1. create a global lock that is shared between vrrp_master/backup methods
2. outright _stop_ the vrrp daemon when we become backup (instead of restarting it)

NAS-127385 / 24.10 / fix EBADF error in HA logic

---

src/middlewared/middlewared/plugins/failover_/event.py

A race condition exists where a `vrrp_master` job would start and then a `vrrp_backup` would subsequently start and depending on which method was the quickest, they would both interact with `fenced` which ultimately ended up with fenced exiting with EBADF. This is because the 2 methods run in their own native threads. There are 2 subtle issues and that is the controller would become `vrrp_master` and `vrrp_backup` almost simultaneously and then fenced would error with EBADF.
To fix both issues:
1. create a global lock that is shared between vrrp_master/backup methods
2. outright _stop_ the vrrp daemon when we become backup (instead of restarting it)
Original PR: https://github.com/truenas/middleware/pull/13173
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127385

NAS-127385 / 23.10.2 / fix EBADF error in HA logic (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/event.py

A race condition exists where a `vrrp_master` job would start and then a `vrrp_backup` would subsequently start and depending on which method was the quickest, they would both interact with `fenced` which ultimately ended up with fenced exiting with EBADF. This is because the 2 methods run in their own native threads. There are 2 subtle issues and that is the controller would become `vrrp_master` and `vrrp_backup` almost simultaneously and then fenced would error with EBADF.
To fix both issues:
1. create a global lock that is shared between vrrp_master/backup methods
2. outright _stop_ the vrrp daemon when we become backup (instead of restarting it)
Original PR: https://github.com/truenas/middleware/pull/13173
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127385

NAS-127385 / 23.10.3 / fix EBADF error in HA logic (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/event.py

A race condition exists where a `vrrp_master` job would start and then a `vrrp_backup` would subsequently start and depending on which method was the quickest, they would both interact with `fenced` which ultimately ended up with fenced exiting with EBADF. This is because the 2 methods run in their own native threads. There are 2 subtle issues and that is the controller would become `vrrp_master` and `vrrp_backup` almost simultaneously and then fenced would error with EBADF.
To fix both issues:
1. create a global lock that is shared between vrrp_master/backup methods
2. outright _stop_ the vrrp daemon when we become backup (instead of restarting it)
Original PR: https://github.com/truenas/middleware/pull/13173
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127385

NAS-127385 / 24.04-RC.1 / fix EBADF error in HA logic (by yocalebo)

---

tests/runtest.py

The legacy ixautomation script used to initiate runtest.py in jenkins may fail to retrieve our interface name from console logs (due to changed logging settings). This commit instead gathers the interface name from the server instead of relying on it being provided.

NAS-127393 / 24.10 / Get iface name from server

---

src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/jbof/crud.py
src/middlewared/middlewared/plugins/pool_/import_pool.py
src/middlewared/middlewared/plugins/rdma/interface/crud.py

Add code to bring up any previously-configure NVMe/RoCE JBOFs on boot.
A new job (`jbof.configure_job`) will bring all configured JBOFs in parallel using `jbof.configure_jbof`.  This configures the necessary RoCE HBA and does a `nvme connect-all`.
In the non-HA case we call `jbof.configure_job` from `pool.import_on_boot` and wait with a 10 second.  Note that if the job takes more than 10 seconds, it will continue to run rather than get aborted after the 10 second timeout.  That said, this should not occur.
For HA we do a similar operation in `failover.vrrp_master`, but also add a parameter to reload fenced if it is running.  We also call `jbof.configure_job` from failover.vrrp_backup, but do not need to wait there as we don't plan on using the drives until the next failover.

NAS-123833 / 24.10 / Rework boot to initiate/wait NVMe/TCP

---

src/middlewared/middlewared/etc_files/rancher/k3s/flags.py

In 1.29, `MixedProtocolLBService` feature is available and an additional flag is not required to enable this anymore. Changes have been made to make sure middleware is up to date with the update in k8s version.

NAS-127378 / 24.10 / Update k8s to 1.29

---

src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/jbof/crud.py
src/middlewared/middlewared/plugins/pool_/import_pool.py
src/middlewared/middlewared/plugins/rdma/interface/crud.py

Add code to bring up any previously-configure NVMe/RoCE JBOFs on boot.
A new job (`jbof.configure_job`) will bring all configured JBOFs in parallel using `jbof.configure_jbof`.  This configures the necessary RoCE HBA and does a `nvme connect-all`.
In the non-HA case we call `jbof.configure_job` from `pool.import_on_boot` and wait with a 10 second.  Note that if the job takes more than 10 seconds, it will continue to run rather than get aborted after the 10 second timeout.  That said, this should not occur.
For HA we do a similar operation in `failover.vrrp_master`, but also add a parameter to reload fenced if it is running.  We also call `jbof.configure_job` from failover.vrrp_backup, but do not need to wait there as we don't plan on using the drives until the next failover.
Original PR: …

NAS-123833 / 24.04-RC.1 / Rework boot to initiate/wait NVMe/TCP (by bmeagherix)

---

src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py

This commit updates AMD k8s device plugin image tag as we have a user whose gpu is not being recognized by the tag we had earlier. However there is still breakage expected for other users as we had bumped this earlier as well but we had quite a few users for whom AMD gpu was not being recognized anymore and hence we went back to the older version in https://github.com/truenas/middleware/pull/10312. Idea is to see that if things have improved as it's been a while since we reverted back and based on feedback we can re-evaluate.

NAS-126877 / 24.10 / Bump AMD k8s device plugin image tag

---

src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py

This commit updates AMD k8s device plugin image tag as we have a user whose gpu is not being recognized by the tag we had earlier. However there is still breakage expected for other users as we had bumped this earlier as well but we had quite a few users for whom AMD gpu was not being recognized anymore and hence we went back to the older version in https://github.com/truenas/middleware/pull/10312. Idea is to see that if things have improved as it's been a while since we reverted back and based on feedback we can re-evaluate.
Original PR: https://github.com/truenas/middleware/pull/13179
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126877

NAS-126877 / 24.04-RC.1 / Bump AMD k8s device plugin image tag (by sonicaj)

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/rseries_nvme.py

Pointed out by the platform team. The rear nvme drive bays on the R50B are off by 1.

NAS-127432 / 13.0 / fix off-by-1 on R50B nvme drives

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/rseries_nvme.py

Pointed out by the platform team. The rear nvme drive bays on the R50B are off by 1.
Original PR: https://github.com/truenas/middleware/pull/13190
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127432

NAS-127432 / 13.1 / fix off-by-1 on R50B nvme drives (by yocalebo)

---

src/middlewared/middlewared/plugins/zfs_/pool_status.py

I fixed an error in 88ebd737e30 but caused a regression whereby I omitted returning the resolved disk.

NAS-127453 / 24.10 / fix regression in pool_status.py

---

src/middlewared/middlewared/plugins/zfs_/pool_status.py

I fixed an error in 88ebd737e30 but caused a regression whereby I omitted returning the resolved disk.
Original PR: https://github.com/truenas/middleware/pull/13193
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127453

NAS-127453 / 24.04-RC.1 / fix regression in pool_status.py (by yocalebo)

---

src/middlewared/middlewared/plugins/jbof/crud.py

Improve the speed of these APIs, generally by performing certain operations in parallel rather than in series.
Also add some additional logging.
---
The need for this became apparent when  we moved the JBOF to new hardware, and also fully populated the JBOF with drives.

NAS-127457 / 24.10 / Improve speed of jbof.create and jbof.delete APIs

---

src/middlewared/middlewared/plugins/webui/enclosure.py

To allow UI team to start using this new endpoint, we needed to add some of the disk details from `disk.query` to the returned object. Most of the changes here are associated to the docstring being updated to reflect reality.

NAS-127467 / 24.10 / add disk details to webui.enclosure.dashboard

---

src/middlewared/middlewared/plugins/jbof/crud.py

Improve the speed of these APIs, generally by performing certain operations in parallel rather than in series.
Also add some additional logging.
---
The need for this became apparent when  we moved the JBOF to new hardware, and also fully populated the JBOF with drives.
Original PR: https://github.com/truenas/middleware/pull/13199
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127457

NAS-127457 / 24.04-RC.1 / Improve speed of jbof.create and jbof.delete APIs (by bmeagherix)

---

src/middlewared/middlewared/plugins/activedirectory.py

This validation is perhaps overly restrictive as it prevents us from automatically registering IPv6 and public IPv4 addresses in Active Directory.
Original PR: https://github.com/truenas/middleware/pull/13206
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127406

NAS-127406 / 24.04-RC.1 / Remove restriction on registering global addresses (by anodos325)

---

src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py

Earlier versions of filter_list would crash on handling None type with `in` filter when an invalid key was specified for the filter. Since fix in NAS-127480 we short-circuit when specified key doesn't exist. This commit adds an additional test for this specific situation.

Add test to ensure we don't regress on invalid key handling

---

src/middlewared/middlewared/plugins/disk_/format.py
src/middlewared/middlewared/plugins/disk_/wipe.py
src/middlewared/middlewared/plugins/pool_/format_disks.py
tests/api2/test_disk_format.py
tests/api2/test_disk_wipe.py

This PR does a few things to improve our disk format (partitioning) and clean handling.
This makes it easier to identify the partition function.   
Example output from `sgdisk -p /dev/sdb`, where `sdb` is a 4 GiB drive with 2 GiB swap partition:
```
Number  Start (sector)    End (sector)  Size       Code  Name
1            2048         4196352   2.0 GiB     8200  swap
2         4198400         8386560   2.0 GiB     BF01  data
```
Partitioning a disk without swap would result in a partition shortened by 1MiB
```
Number  Start (sector)    End (sector)  Size       Code  Name
1            4096         4192256   2.0 GiB     BF01
```
The starting sector for that partition should be 2048
We now _always_ partition disks to the largest possible data partition.  As such, removed the parameter that …

NAS-127460 / 24.10 / Improve disk partitioning

---

src/middlewared/middlewared/plugins/pool_/dataset.py

This particular check never quite worked correctly in that our filter for whether the dataset was in boot pool was a de-facto no op (since we were not populating the pool name before filtering).
This issue was not detected due to a compensating bug in filter_list where missing keys were not being handled correctly either.

NAS-127498 / 24.10 / Fix check for whether a dataset is internal

---

src/middlewared/middlewared/plugins/pool_/dataset.py

This particular check never quite worked correctly in that our filter for whether the dataset was in boot pool was a de-facto no op (since we were not populating the pool name before filtering).
This issue was not detected due to a compensating bug in filter_list where missing keys were not being handled correctly either.
Original PR: https://github.com/truenas/middleware/pull/13210
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127498

NAS-127498 / 24.04-RC.1 / Fix check for whether a dataset is internal (by anodos325)

---

src/middlewared/middlewared/plugins/service_/utils.py
tests/api2/test_api_key.py

Allow API keys to toggle services. We only need to check whether this is a user session since API keys don't support roles. This means that once an API key is within the permissions check function we already know that it has been explicitly granted access to this endpoint via its allowlist.

NAS-127074 / 24.10 / Fix permissions check for services plugin using api key

---

src/middlewared/middlewared/plugins/service_/utils.py
tests/api2/test_api_key.py

Allow API keys to toggle services. We only need to check whether this is a user session since API keys don't support roles. This means that once an API key is within the permissions check function we already know that it has been explicitly granted access to this endpoint via its allowlist.
Original PR: https://github.com/truenas/middleware/pull/13213
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127074

NAS-127074 / 24.04-RC.1 / Fix permissions check for services plugin using api key (by anodos325)

---

src/middlewared/middlewared/plugins/webui/main_dashboard.py
src/middlewared/middlewared/utils/__init__.py

This adds `codename` field to webui.dashboard.sys_info. Depends on https://github.com/truenas/scale-build/pull/595

NAS-127301 / 24.10 / add codename to webui.dashboard.sys_info

---

src/middlewared/middlewared/plugins/webui/main_dashboard.py
src/middlewared/middlewared/utils/__init__.py

This adds `codename` field to webui.dashboard.sys_info. Depends on https://github.com/truenas/scale-build/pull/595
Original PR: https://github.com/truenas/middleware/pull/13218
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127301

NAS-127301 / 24.04-RC.1 / add codename to webui.dashboard.sys_info (by yocalebo)

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/directoryservices.py
src/middlewared/middlewared/plugins/kerberos.py
src/middlewared/middlewared/plugins/smb.py

If networking is not fully configured, kinit attempt may fail with EAGAIN. Retry several times before giving up. Since the actual kinit has a timeout set for 30 seconds, this loop may end up being quite long-running and so convert directoryservices.initialize into a middleware job. The only direct caller for this private endpoint is smb.configure which is itself a job and so we don't have to worry about any potential timeouts here.

NAS-127452 / 24.10 / Retry starting kerberos during DS initialization

---

src/middlewared/middlewared/plugins/disk_/retaste.py
src/middlewared/middlewared/plugins/disk_/wipe.py
tests/api2/test_disk_wipe.py

Recent changes to `disk.wipe` added a call to `disk.list_partitions`.  It was later determined `disk.list_partitions` might cause excessive delay when used in wipe on large systems.  This PR adds a lightweight alternative and eliminates the call to `disk.list_partitions`.  The new routine is called `get_partitions_quick`.
Also, during testing it was discovered we are failing to update the kernel partition table after a `disk.wipe` call.  This behavior was introduced in Electric Eel.  The fix is to use the block ioctl `BLKRRPATH`.  This was already conveniently implemented in `retaste.py` and only required a simple wrapper and small bug fix.
Finally, added a CI test to `test_disk_wipe.py` to detect regression of the kernel partition table updates.

NAS-127488 / 24.10 / Add lightweight replacement for disk.list_partitions

---

tests/runtest.py

A recent change (dade5605b9) disallowed a hostname from being supplied as the `ip` parameter to `runtest.py`.  Work around this new restriction. (Only useful in limited circumstances e.g. running tests locally.  There _may_ be tests that _require_ an IP address, but I use `runtest.py` to run a subset that do not.)
----
`socket.gethostbyname` of an IP address, just returns the IP address - so this change should be non-destructive
```
>>> socket.gethostbyname('1.2.3.4')
'1.2.3.4'
>>> socket.gethostbyname('scale3')
'192.168.56.115'
>>>
```

Relax recent restriction on supplied ip parameter

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/directoryservices.py
src/middlewared/middlewared/plugins/kerberos.py
src/middlewared/middlewared/plugins/smb.py

If networking is not fully configured, kinit attempt may fail with EAGAIN. Retry several times before giving up. Since the actual kinit has a timeout set for 30 seconds, this loop may end up being quite long-running and so convert directoryservices.initialize into a middleware job. The only direct caller for this private endpoint is smb.configure which is itself a job and so we don't have to worry about any potential timeouts here.
Original PR: https://github.com/truenas/middleware/pull/13221
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127452

NAS-127452 / 24.04-RC.1 / Retry starting kerberos during DS initialization (by anodos325)

---

tests/api2/test_001_ssh.py

This API call needs to be made via the ws_client fixture rather than normal middleware call test asset.

NAS-127553 / 24.10 / Fix test for local accounts on HA platform

---

src/middlewared/middlewared/test/integration/utils/client.py

Having our middleware client hit a socket timeout usually means that the test VM is seriously broken. We should swiftly abort test run in this case.

Fail test runs if we start hitting socket timeouts

---

tests/api2/test_001_ssh.py

This API call needs to be made via the ws_client fixture rather than normal middleware call test asset.
Original PR: https://github.com/truenas/middleware/pull/13228
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127553

NAS-127553 / 24.04-RC.1 / Fix test for local accounts on HA platform (by anodos325)

---

src/middlewared/middlewared/test/integration/utils/client.py

Having our middleware client hit a socket timeout usually means that the test VM is seriously broken. We should swiftly abort test run in this case.
Original PR: https://github.com/truenas/middleware/pull/13232
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127559

NAS-127559 / 24.04-RC.1 / Fail test runs if we start hitting socket timeouts (by anodos325)

---

tests/runtest.py

Use IP address for controller1 to perform initial configuration. This fixes an issue where middleware client calls during initial setup were hitting socket timeouts due to VIP not being configured yet.

NAS-127561 / 24.10 / Fix runtest.py for HA VMs

---

tests/api2/test_030_activedirectory.py

Our HA vms are always enterprise-licensed and so we should bypass tests related to license in the AD plugin.

NAS-127576 / 24.10 / Fix failing AD test related to ds_auth for middleware

---

tests/api2/test_030_activedirectory.py

Our HA vms are always enterprise-licensed and so we should bypass tests related to license in the AD plugin.
Original PR: https://github.com/truenas/middleware/pull/13236
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127576

NAS-127576 / 24.04-RC.1 / Fix failing AD test related to ds_auth for middleware (by anodos325)

---

tests/api2/test_catalog_sync.py
tests/runtest.py

These tests fail because we are enterprise-licensed.

NAS-127579 / 24.10 / Skip catalog tests on HA platform

---

tests/api2/test_catalog_sync.py
tests/runtest.py

These tests fail because we are enterprise-licensed.
Original PR: https://github.com/truenas/middleware/pull/13238
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127579

NAS-127579 / 24.04-RC.1 / Skip catalog tests on HA platform (by anodos325)

---

src/freenas/usr/local/bin/truenas-initrd.py
src/middlewared/middlewared/plugins/boot.py
src/middlewared/middlewared/plugins/system_general/update.py

When the console keymap is updated in the UI, it updates successfully, but the change does not persist across reboots.
Update the initramfs to ensure the console keymap change persists across reboots.
https://superuser.com/questions/646425/permanently-change-default-language-and-keyboard-settings-what-am-i-missing

NAS-127032 / 24.10 / Make sure console keymap changes persist

---

src/middlewared/middlewared/plugins/disk_/wipe.py

Previously, the check was to skip the first partition, which would start at 1MiB and process all others.
This did not account for drives that that had partitions within 1MiB of the start of the drive.
Add check for partition start and exclude those that are less than 30MiB

NAS-127547 / 24.10 / Fix middle partition clean processing

---

src/middlewared/middlewared/plugins/disk_/temperature.py
src/middlewared/middlewared/utils/disks.py

Users are unable to retrieve the disk temperature of certain disks because their `hddstandby` value is set to something other then `ALWAYS ON`.
In TrueNAS CORE, we supported HDD standby functionality, which was due to the reason as in reporting it could lead to inconsistencies, as some disks might not report temperature when in standby mode. However, TrueNAS SCALE should effectively not be supporting HDD standby feature now. To address this, we are removing the usage of HDD standby attr in reporting because disks will always remain active in SCALE, ensuring data consistency and allowing users to retrieve disk temperatures reliably.
Original PR: https://github.com/truenas/middleware/pull/13240
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127524

NAS-127524 / 24.04-RC.1 / Remove old hddstandby usages (by Qubad786)

---

src/middlewared/middlewared/plugins/disk_/temperature.py
src/middlewared/middlewared/utils/disks.py

Users are unable to retrieve the disk temperature of certain disks because their `hddstandby` value is set to something other then `ALWAYS ON`.
In TrueNAS CORE, we supported HDD standby functionality, which was due to the reason as in reporting it could lead to inconsistencies, as some disks might not report temperature when in standby mode. However, TrueNAS SCALE should effectively not be supporting HDD standby feature now. To address this, we are removing the usage of HDD standby attr in reporting because disks will always remain active in SCALE, ensuring data consistency and allowing users to retrieve disk temperatures reliably.
Original PR: https://github.com/truenas/middleware/pull/13240
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127524

NAS-127524 / 23.10.3 / Remove old hddstandby usages (by Qubad786)

---

src/middlewared/middlewared/plugins/system_advanced/config.py

Previously values from old config were also sent for validation hence making update problematic for users in case there is some issue in old config wrt GPU configuration.
PR makes the change to safely validate only the changed fields for `system.advanced.update`. Essentially motivation is that in the UI where user changes system advanced settings, GPU settings are not listed and it is very awkward to see a GPU error when you are changing system advanced settings in the UI where there is no GPU attr (which has it's own dedicated tab/section in the UI).

NAS-127405 / 24.04-RC.1 / Safely validate GPU related config in system.advanced namespace

---

src/freenas/etc/systemd/system/netdata.service.d/override.conf
src/middlewared/middlewared/etc_files/netdata/netdata.conf.mako
src/middlewared/middlewared/plugins/reporting/netdata_configure.py
src/middlewared/middlewared/plugins/sysdataset.py
src/middlewared/middlewared/plugins/system_dataset/hierarchy.py
src/middlewared/middlewared/plugins/system_dataset/utils.py
src/middlewared/middlewared/pytest/unit/plugins/test_system_dataset.py

The default path for Netdata database storage exists at `/var/cache/netdata`, but its data is stored in the system dataset. Symlinks were used to bind that dataset with the Netdata storage directory. However, the `netdata_setup` function, responsible for this process, runs on every netdata restart, although it should only be required once or when the system dataset is migrated.
Simplify the Netdata setup logic by changing the Netdata database storage directory to `/var/db/system/netdata` and mounting the Netdata system dataset in that same directory. Other tasks performed by the `netdata_setup` function will also be handled in the system dataset in a clean/centric way.

NAS-127112 / 24.10 / Improve netdata setup

---

src/middlewared/middlewared/plugins/enclosure.py
src/middlewared/middlewared/plugins/enclosure_/nvme.py

This adds ES24N support to our legacy enclosure code. I use the logic from the previous PR: https://github.com/truenas/middleware/pull/13256 and just massage the data into the structured object that our legacy code expects.
NOTE: this is a DF only change which is why it's targeted to this branch only.

NAS-127600 / 24.04-RC.1 / add ES24N enclosure to legacy enclosure code

---

src/middlewared/middlewared/plugins/kerberos.py

Most of the routines in kerberos.py are declared `async`, however the routines themselves often contain blocking IO calls.
The purpose of this PR is to cleanup the async routines with regards to blocking IO calls.

NAS-127232 / 24.10 / Make kerberos.py functions async compatible

---

src/middlewared/middlewared/etc_files/scst.conf.mako
src/middlewared/middlewared/plugins/iscsi_/extents.py

Some performance analysis was done on our ZVOL based iSCSI targets and configuration changes were suggested.
This PR implements those changes:
- Specify `threads_num 32` in for the extents in _scst.conf_
- When creating a new extent turn **off** `volthreading` parameter on the underlying ZVOL.  Likewise revert when deleting an extent.
- When importing a pool, if necessary turn off `volthreading` parameter on any ZVOL underlying an extent (handles upgrade cases).

NAS-117880 / 24.10 / Change SCST extent threading for performance

---

src/middlewared/middlewared/etc_files/scst.conf.mako
src/middlewared/middlewared/plugins/iscsi_/extents.py

Some performance analysis was done on our ZVOL based iSCSI targets and configuration changes were suggested.
This PR implements those changes:
- Specify `threads_num 32` in for the extents in _scst.conf_
- When creating a new extent turn **off** `volthreading` parameter on the underlying ZVOL.  Likewise revert when deleting an extent.
- When importing a pool, if necessary turn off `volthreading` parameter on any ZVOL underlying an extent (handles upgrade cases).
Original PR: https://github.com/truenas/middleware/pull/13265
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117880

NAS-117880 / 24.04-RC.1 / Change SCST extent threading for performance (by bmeagherix)

---

src/middlewared/middlewared/etc_files/scst.conf.mako
src/middlewared/middlewared/plugins/iscsi_/extents.py

Some performance analysis was done on our ZVOL based iSCSI targets and configuration changes were suggested.
This PR implements those changes:
- Specify `threads_num 32` in for the extents in _scst.conf_
- When creating a new extent turn **off** `volthreading` parameter on the underlying ZVOL.  Likewise revert when deleting an extent.
- When importing a pool, if necessary turn off `volthreading` parameter on any ZVOL underlying an extent (handles upgrade cases).
Original PR: https://github.com/truenas/middleware/pull/13265
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117880

NAS-117880 / 24.04.0 / Change SCST extent threading for performance (by bmeagherix)

---

src/middlewared/middlewared/plugins/audit/audit.py
src/middlewared/middlewared/plugins/audit/backend.py
src/middlewared/middlewared/plugins/audit/utils.py
src/middlewared/middlewared/pytest/unit/plugins/audit/test_audit_utils.py
src/middlewared/middlewared/sqlalchemy.py

Most queries to this endpoint can be passed directly to sqlalchemy which provides a very large performance boost.
Additionally, users may specify filters that can be used to exclude some of our audit databases from the query results.
This commit makes us more intelligent about how we handle this situation (avoiding unnecessarily querying
databases).

NAS-127627 / 24.10 / Try to use sql filters in audit.query calls

---

src/middlewared/middlewared/plugins/audit/audit.py
src/middlewared/middlewared/plugins/audit/backend.py
src/middlewared/middlewared/plugins/audit/utils.py
src/middlewared/middlewared/pytest/unit/plugins/audit/test_audit_utils.py
src/middlewared/middlewared/sqlalchemy.py

This commit improves performance of the audit.query endpoint in the following ways:
1. Majority of combinations of query-filters and query-options are now passed directly
to auditbackend.query where they are converted into SQL. This avoids having
to manipulate potentially very large lists within filter_list.
2. Parse user-provided `query-filters` to look for opportunities to limit the
number of audit databases we query.
3. When multiple databases are the target of a particular audit.query call,
perform the queries concurrently via asyncio.gather.
Original PR: https://github.com/truenas/middleware/pull/13271
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127627

NAS-127627 / 24.04.0 / Improve audit.query performance (by anodos325)

---

src/middlewared/middlewared/plugins/device_/device_info.py
src/middlewared/middlewared/plugins/webui/enclosure.py

After discussion with the UI team, we concluded that we needed to remove some keys from this endpoint that don't provide any benefit. Especially since this feature is on our enterprise line.
This does, primarily, 4 things:
1. calls `device.get_disks` which gets disk details directly from kernel cache instead of looking at our cache in our own db (looking at a cache of a cache isn't good)
2. remove useless keys
3. add `type` key to show if the drive is a HDD or SSD
4. remove the str cast of rotationrate in `device.get_disks` and keep it as an integer (git blame shows that I kept rotation rate as a string for backwards compatibility. however, the db column for this value is an integer type so we've been storing it wrong for years)

NAS-127612 / 24.10 / Remove unnecessary keys in webui.enclosure.dashboard endpoint

---

src/freenas/usr/lib/netdata/conf.d/python.d/smart_log.conf
src/freenas/usr/lib/netdata/python.d/smart_log.chart.py
src/middlewared/middlewared/etc_files/netdata/python.d/smart_log.conf.mako
src/middlewared/middlewared/plugins/etc.py
src/middlewared/middlewared/plugins/service_/services/smartd.py

The smartd interval is hard-coded in the Netdata smart_log plugin. When users change the smartd time interval to a value greater than the hard-coded interval in the plugin, the Netdata plugin's check fails. This happens because smartd does not update its CSV file according to the hard-coded value in the Netdata plugin.
Create a configuration file for the Netdata smart_log plugin. Update this configuration file whenever the smartd interval changes. Additionally, synchronize the Netdata smart plugin cache update interval to comply with configured smartd interval.

NAS-127637 / 24.10 / Fix disk temperature logs not being retrieved when smartd interval is changed

---

src/freenas/usr/lib/netdata/conf.d/python.d/smart_log.conf
src/freenas/usr/lib/netdata/python.d/smart_log.chart.py
src/middlewared/middlewared/etc_files/netdata/python.d/smart_log.conf.mako
src/middlewared/middlewared/plugins/etc.py
src/middlewared/middlewared/plugins/service_/services/smartd.py

The smartd interval is hard-coded in the Netdata smart_log plugin. When users change the smartd time interval to a value greater than the hard-coded interval in the plugin, the Netdata plugin's check fails. This happens because smartd does not update its CSV file according to the hard-coded value in the Netdata plugin.
Create a configuration file for the Netdata smart_log plugin. Update this configuration file whenever the smartd interval changes. Additionally, synchronize the Netdata smart plugin cache update interval to comply with configured smartd interval.
Original PR: https://github.com/truenas/middleware/pull/13278
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127637

NAS-127637 / 23.10.3 / Fix disk temperature logs not being retrieved when smartd interval is changed (by Qubad786)

---

src/freenas/usr/lib/netdata/conf.d/python.d/smart_log.conf
src/freenas/usr/lib/netdata/python.d/smart_log.chart.py
src/middlewared/middlewared/etc_files/netdata/python.d/smart_log.conf.mako
src/middlewared/middlewared/plugins/etc.py
src/middlewared/middlewared/plugins/service_/services/smartd.py

The smartd interval is hard-coded in the Netdata smart_log plugin. When users change the smartd time interval to a value greater than the hard-coded interval in the plugin, the Netdata plugin's check fails. This happens because smartd does not update its CSV file according to the hard-coded value in the Netdata plugin.
Create a configuration file for the Netdata smart_log plugin. Update this configuration file whenever the smartd interval changes. Additionally, synchronize the Netdata smart plugin cache update interval to comply with configured smartd interval.
Original PR: https://github.com/truenas/middleware/pull/13278
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127637

NAS-127637 / 24.04.0 / Fix disk temperature logs not being retrieved when smartd interval is changed (by Qubad786)

---

src/middlewared/middlewared/plugins/pool_/dataset_processes.py
src/middlewared/middlewared/plugins/sysdataset.py
tests/api2/test_pool_dataset_track_processes.py

This commit does the following:
1. Fixes a bug whereby query for processes owned by paths would not list the paths within the `paths` variable in output
2. Adds ability to pass a parameter to include files opened by the middlewared process in the output to assist in troubleshooting issues where the middlewared process is what is preventing system dataset umount from occurring.
3. Passes new parameter when handling errors during systemdataset setup.
4. Parses the recursive umount error message for the dataset that failed and pass that to the call to look up processes.

NAS-127671 / 24.10 / Fix error message for errors umounting sysdataset

---

src/middlewared/middlewared/plugins/pool_/dataset_processes.py
src/middlewared/middlewared/plugins/sysdataset.py
tests/api2/test_pool_dataset_track_processes.py

This commit does the following:
1. Fixes a bug whereby query for processes owned by paths would not list the paths within the `paths` variable in output
2. Adds ability to pass a parameter to include files opened by the middlewared process in the output to assist in troubleshooting issues where the middlewared process is what is preventing system dataset umount from occurring.
3. Passes new parameter when handling errors during systemdataset setup.
4. Parses the recursive umount error message for the dataset that failed and pass that to the call to look up processes.
Original PR: https://github.com/truenas/middleware/pull/13283
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127671

NAS-127671 / 24.04.0 / Fix error message for errors umounting sysdataset (by anodos325)

---

src/middlewared/middlewared/plugins/smb.py

We weren't raising a validation error on empty string for SMB share name, this resulted in share info being passed to libsmbconf and failing during share creation.
Original PR: https://github.com/truenas/middleware/pull/13288
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127708

NAS-127708 / 24.04.0 / Fix validation for empty SMB share name (by anodos325)

---

src/middlewared/middlewared/plugins/sysdataset.py

If for some reason a process has an open handle on our old system dataset, log an error message and proceed with a lazy umount to avoid leaving system in broken state.
Original PR: https://github.com/truenas/middleware/pull/13292
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127724

NAS-127724 / 24.04.0 / Try much harder to not break the system dataset (by anodos325)

---

src/middlewared/middlewared/plugins/pool_/dataset.py
tests/api2/test_340_pool_dataset.py

In certain scenarios parameter combinations provided by API consumers could cause spurious validation errors on mismatch between acltype and aclmode.

NAS-127710 / 24.10 / Apply share_type preset prior to validation

---

src/middlewared/middlewared/plugins/pool_/dataset.py
tests/api2/test_340_pool_dataset.py

In certain scenarios parameter combinations provided by API consumers could cause spurious validation errors on mismatch between acltype and aclmode.
Original PR: https://github.com/truenas/middleware/pull/13293
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127710

NAS-127710 / 24.04.0 / Apply share_type preset prior to validation (by anodos325)

---

src/middlewared/middlewared/plugins/pool_/dataset.py
tests/api2/test_340_pool_dataset.py

In certain scenarios parameter combinations provided by API consumers could cause spurious validation errors on mismatch between acltype and aclmode.
Original PR: https://github.com/truenas/middleware/pull/13293
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127710

NAS-127710 / 24.04-RC.1 / Apply share_type preset prior to validation (by anodos325)

---

src/middlewared/middlewared/plugins/interface/configure.py
src/middlewared/middlewared/plugins/rdma/interface/crud.py
src/middlewared/middlewared/plugins/rdma/rdma.py

When JBOF support was added, we added *all* RDMA interfaces to `rdma.interface.internal_interfaces`.  Instead only add those currently in use for JBOF purposes.
Likewise, in `rdma.get_link_choices` omit any interfaces that have been configured for general networking.

NAS-127697 / 24.10 / Allow RDMA capable interfaces to be exposed for regular networking

---

src/middlewared/middlewared/plugins/interface/configure.py
src/middlewared/middlewared/plugins/rdma/interface/crud.py
src/middlewared/middlewared/plugins/rdma/rdma.py

When JBOF support was added, we added *all* RDMA interfaces to `rdma.interface.internal_interfaces`.  Instead only add those currently in use for JBOF purposes.
Likewise, in `rdma.get_link_choices` omit any interfaces that have been configured for general networking.
Original PR: https://github.com/truenas/middleware/pull/13289
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127697

NAS-127697 / 24.04-RC.1 / Allow RDMA capable interfaces to be exposed for regular networking (by bmeagherix)
