truenas/middleware

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
src/middlewared/middlewared/plugins/update_/utils.py

This simply catches up our CORE code-base with what we do in SCALE. We've fixed numerous bugs in update logic on SCALE but never back ported to CORE.

NAS-125088 / 13.0 / fix failover.upgrade_pending and utils.can_update

---

src/middlewared/middlewared/plugins/nfs_/status.py

Describe the fields in the midclt calls get_nfs[34]_clients

NAS-125099 / 24.04 / Document fields for get_nfsX_clients

---

src/middlewared/middlewared/plugins/catalogs_linux/item_version.py
src/middlewared/middlewared/plugins/catalogs_linux/items_util.py
src/middlewared/middlewared/plugins/chart_releases_linux/resources.py

This PR adds changes to optimize retrieving versions of apps. Earlier for a truechart app, it took around 5 seconds on my VM and now it takes 1 second to get the same result.

NAS-124614 / 24.04 / Optimize retrieving versions of apps

---

src/middlewared/middlewared/plugins/catalogs_linux/item_version.py
src/middlewared/middlewared/plugins/catalogs_linux/items_util.py
src/middlewared/middlewared/plugins/chart_releases_linux/resources.py

This PR adds changes to optimize retrieving versions of apps. Earlier for a truechart app, it took around 5 seconds on my VM and now it takes 1 second to get the same result.
Original PR: https://github.com/truenas/middleware/pull/12470
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124614

NAS-124614 / 23.10.1 / Optimize retrieving versions of apps (by sonicaj)

---

src/middlewared/middlewared/plugins/vm/pci.py
src/middlewared/middlewared/plugins/vm/utils.py

This PR adds a new endpoint which UI should use when trying to determine which PCI devices are to be created for isolation when user selects a GPU to be attached to a VM.

NAS-124416 / 24.04 / Add an endpoint to retrieve PCI devices which are to be isolated for VM GPU isolation

---

src/middlewared/middlewared/plugins/pool_/utils.py

This PR adds the required change to include BLAKE3 as an option for checksum in dataset creation.

NAS-124749 / 24.04 / Add BLAKE3 checksum option

---

src/middlewared/middlewared/plugins/account.py

At present SMB authentication for local users requires some form of NT hash. User expectation of disabling password-based auth for local users on SMB access is ambiguous at best, and so we should just raise a ValidationError and have user make some other choices regarding parameter combination.

NAS-125109 / 24.04 / Prevent password_disable for SMB users

---

src/middlewared/middlewared/plugins/enclosure.py

Add h-series enclosure management to legacy enclosure code. This is a bit hacky but this platform uses a Virtual SES driver, for which we have outright ignored for the entirety of our enclosure plugin. To try and keep the potential for regression to a minimum, I've hidden the new logic (most of it) behind a `if is_hseries` check.

NAS-123854 / 24.04 / add hseries enclosure mapping

---

src/middlewared/middlewared/plugins/disk_/format.py
tests/api2/test_disk_format.py

…ta partition size was specified explicitly
Original PR: https://github.com/truenas/middleware/pull/12489
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125078

NAS-125078 / 23.10.1 / Fix swap partition being created after the data partition when the da… (by themylogin)

---

tests/api2/test_345_acl_nfs4.py

This commit also converts many jobs called via REST with websocket-based calls to improve runtime for tests and reduce overall lines of code.

NAS-125239 / 24.04 / Add NFSv4 ACL restricted owner ACL test

---

tests/api2/test_345_acl_nfs4.py

This commit also converts many jobs called via REST with websocket-based calls to improve runtime for tests and reduce overall lines of code.
Original PR: https://github.com/truenas/middleware/pull/12507
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125239

NAS-125239 / 23.10.1 / Add NFSv4 ACL restricted owner ACL test (by anodos325)

---

src/middlewared/middlewared/plugins/keychain.py

Fix many issues:
1. stop blocking main event loop in `validate_and_pre_save` methods
2. stop blocking main event loop in `ssh_pair` method
3. fix TOCTOU issue in `ssh_pair`
4. use `MatchNotFound` exception instead of `IndexError`

NAS-125275 / 24.04 / Stop blocking main event loop in keychain plugin

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

This fixes the R50 series platform in the new enclosure2 code. I'm working on adding tests in another PR and will push those soon which will, in theory, catch situations like this.

NAS-125324 / 24.04 / fix R50 in enclosure2

---

src/middlewared/middlewared/plugins/enclosure_/map2.py
src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py

The R40 has to be handled specially because of a mishap with HBA firmware flashing.

NAS-125262 / 24.04 / add special handling for R40 in enclosure2

---

src/middlewared/middlewared/apidocs/templates/websocket/query.md

NAS-125353 / 24.04 / Fix API docs

---

src/middlewared/middlewared/plugins/failover_/configure.py
src/middlewared/middlewared/plugins/system/product.py

…license
Original PR: https://github.com/truenas/middleware/pull/12630
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125478

NAS-125478 / 23.10.2 / DO not wait 24 hours to run `LicenseStatus` alert after applying new … (by themylogin)

---

src/middlewared/middlewared/plugins/failover_/configure.py
src/middlewared/middlewared/plugins/system/product.py

…license
Original PR: https://github.com/truenas/middleware/pull/12630
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125478
Original PR: https://github.com/truenas/middleware/pull/12631
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125478

NAS-125478 / 23.10.1 / DO not wait 24 hours to run `LicenseStatus` alert after applying new … (by themylogin) (by bugclerk)

---

src/middlewared/middlewared/plugins/boot.py

This regressed in fa7d871b579. Changes introduced there don't take into account that we don't enforce any type of sanity on zpool names. So a zpool created with a space in the name produces the below error. Luckily, `zpool -H` flag always separates the values by tab so we can safely split on tab instead of space.
As a final precaution, however, I wrap it in an `try: except` block so we don't crash here since it's not fatal that we don't apply this setting on middleware start-up. Instead we'll log an error message so we can review them in debug archives and fix the various issues as we come across them.
```
[2023/12/04 11:31:02] (TRACE) middlewared.trace():46 - _console_write 'setting up plugins (boot) [5/109]'
File "/usr/bin/middlewared", line 12, in …
```

NAS-125550 / 24.04 / fix regression in boot.py:setup()

---

src/middlewared/middlewared/plugins/chart_releases_linux/validation.py
src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
tests/api2/test_chart_release_acl_apply.py

It was requested by Stavros that we backport ACL changes so users can make use of the new force flag properly.

NAS-125528 / 23.10.2 / Backport ACL changes to cobia

---

src/middlewared/middlewared/plugins/chart_releases_linux/events.py

More log spam that just fills up middlewared.log.

NAS-125581 / 24.04 / prevent more log spam

---

src/middlewared/middlewared/plugins/pool_/dataset_attachments.py
src/middlewared/middlewared/plugins/pool_/dataset_encryption_info.py
src/middlewared/middlewared/plugins/pool_/dataset_mountpoint.py
src/middlewared/middlewared/plugins/pool_/dataset_processes.py
src/middlewared/middlewared/plugins/pool_/dataset_quota_and_perms.py
src/middlewared/middlewared/plugins/pool_/dataset_recordsize.py
src/middlewared/middlewared/plugins/pool_/info.py
src/middlewared/middlewared/plugins/pool_/snapshot_count.py
src/middlewared/middlewared/plugins/pool_/unlock.py

This commit adds more roles configuration for pool and dataset related API endpoints.

NAS-125578 / 24.04 / Add more roles configuration for pool and dataset

---

src/middlewared/middlewared/plugins/disk_/availability.py
src/middlewared/middlewared/plugins/disk_/temperature.py
src/middlewared/middlewared/plugins/smart.py

This exposes smart and temperature info for disks to users with REPORTING_READ role.

NAS-125619 / 24.04 / Allow users with REPORTING_READ to access disk info

---

src/middlewared/middlewared/plugins/account_/privilege_roles.py

This is basic information about existing roles that webui needs.

NAS-125628 / 24.04 / Allow unauthorized access to role information

---

src/middlewared/middlewared/etc_files/rancher/k3s/flags.py
tests/api2/test_023_kubernetes.py

Relevant K3s PR: https://github.com/truenas/k3s/pull/41

NAS-124821 / 24.04 / Add changes to not have k3s config world readable

---

src/middlewared/middlewared/plugins/filesystem.py
src/middlewared/middlewared/plugins/filesystem_/stat_x.py

This commit adds immutable status to filesystem.listdir at no additional cost (since it's already available in statx output).

NAS-125677 / 24.04 / Add statx attributes to middleware statx

---

src/middlewared/middlewared/plugins/system_general/update.py
src/middlewared/middlewared/test/integration/assets/product.py
tests/api2/test_030_activedirectory.py
tests/api2/test_275_ldap.py

This commit limits API access for directory services users to enterprise license holders only.

NAS-125563 / 24.04 / Restrict ds_auth to Enterprise license

---

docs/source/middleware/audit.rst
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/audit/schema/middleware.py
src/middlewared/middlewared/pytest/unit/plugins/test_interface.py
src/middlewared/middlewared/restful.py
src/middlewared/middlewared/schema/processor.py
src/middlewared/middlewared/service/crud_service.py
src/middlewared/middlewared/service/sharing_service.py
src/middlewared/middlewared/test/integration/utils/audit.py
src/middlewared/middlewared/utils/type.py
tests/api2/test_account.py
tests/api2/test_audit_rest.py
tests/api2/test_audit_websocket.py
tests/api2/test_rest_api_upload.py
tests/conftest.py

NAS-125561 / 24.04 / REST API audit

---

src/middlewared/middlewared/etc_files/scst.conf.mako

Add `alias` to `scst.conf`
----
Successful CI run, plan to add a separate jira to enhance CI tests wrt alias.

NAS-120363 / 24.04 / Add support for alias

---

src/middlewared/middlewared/plugins/service.py

SERVICE_WRITE - may enable/disable all services
SHARING_SMB_WRITE - may enable/disable SMB service SHARING_NFS_WRITE - may enable/disable NFS service SHARING_ISCSI_WRITE - may enable/disable iSCSI service

NAS-125769 / 24.04 / Allow limited user to toggle enabled for services

---

src/middlewared/middlewared/pytest/unit/utils/test_cpu_util_amd.py

A unit test has been added for the changes added in https://github.com/truenas/middleware/pull/12755

NAS-125781 / 24.04 / Add unit test for edge case related to AMD CPU temperature

---

src/middlewared/middlewared/pytest/unit/utils/test_cpu_util_amd.py

A unit test has been added for the changes added in https://github.com/truenas/middleware/pull/12755
Original PR: https://github.com/truenas/middleware/pull/12758
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125781

NAS-125781 / 23.10.2 / Add unit test for edge case related to AMD CPU temperature (by Qubad786)

---

debian/debian/ix-netif.service

This PR is essentially a cosmetic change and no functionality is changed.

NAS-125786 / 24.04 / Clean before directive usage in ix-netif

---

src/middlewared/middlewared/plugins/pool_/dataset_info.py

This grants DATASET_READ access to some more public endpoints that were missed during initial round of roles plumbing for datasets.

NAS-125790 / 24.04 / Assign roles for dataset_info.py

---

src/middlewared/middlewared/plugins/ipmi_/chassis.py
src/middlewared/middlewared/plugins/ipmi_/lan.py
src/middlewared/middlewared/plugins/ipmi_/mc.py
src/middlewared/middlewared/plugins/ipmi_/sel.py

This allows READONLY role to access full range of IPMI-related info.

NAS-125793 / 24.04 / Expand IPMI info available to READONLY role

---

src/middlewared/middlewared/plugins/kmip/sync.py
src/middlewared/middlewared/plugins/kmip/update.py
src/middlewared/middlewared/role.py

This commit adds basic READ / WRITE roles for the KMIP plugin and grants READONLY administrator KMIP_READ access.

NAS-125798 / 24.04 / Add KMIP roles configuration

---

src/middlewared/middlewared/plugins/auth_/authenticate.py
tests/api2/test_account_privilege_authentication.py

This is preparatory commit for more robust session handling for accounts that must set new password. Provide PAM response details in auth.libpam_authenticate response.

NAS-125838 / 24.04 / Expand libpam_authenticate response

---

src/middlewared/middlewared/plugins/webui/main_dashboard.py

These changes are at the request of webUI team which came from when they implemented using this endpoint.

NAS-125919 / 24.04 / changes to sys_info for UI team

---

tests/api2/test_200_ftp.py

Widened the acceptance range from +8KB to +20KB
Fix flake8 issues.
(cherry picked from commit 699709e866e8bdf1d6a22181e308ccf1879bbd33) Fixed conflicts.

NAS-125546 / 23.10.2 / Make the bandwidth test more resilient. (#12634)

---

tests/api2/test_011_user.py
tests/api2/test_310_plugin.py
tests/api2/test_390_s3.py
tests/api2/test_470_system.py
tests/api2/test_790_update.py

removed custom plugin repos testing and changed plugins_branch to master
Changed the s3 test to verify the deprecation message
Fixed version verification and train verification for nightly build.

TE-1317 / Fixed and rework some API test

---

src/middlewared/middlewared/plugins/kerberos.py
src/middlewared/middlewared/plugins/ldap.py
src/middlewared/middlewared/plugins/nfs.py
tests/api2/test_001_ssh.py

This commit fixes a couple of typos and omissions that were missed during review of large clustering removal PR.

NAS-125966 / 24.04 / Fix regressions caused by cluster removal

---

src/middlewared/middlewared/plugins/system/info.py

This is needed by the webUI team.

NAS-126026 / 24.04 / add READONLY role to system.host_id

---

src/middlewared/middlewared/plugins/truenas.py

NAS-126027 / 24.04 / add READONLY to truenas.is_production

---

src/middlewared/middlewared/alert/source/active_directory.py
src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/smb.py
tests/api2/test_420_smb.py

We have deprecated this feature in Samba versions more recent than 4.15.

NAS-126074 / 13.1 / Remove AD monitor thread

---

src/middlewared/middlewared/plugins/failover_/event.py

The `failover.events.fenced_start_loop` method assumes that `failover.fenced.start` takes 1 second to return. This is not the case since the `fenced` daemon has functionality built-in to wait around 10 or so seconds to see if the reservations on the disk change. If the reservation keys change, then fenced assumes that the other node's fenced daemon is running and so backs off. This is by design and has been this way since the beginning.
This fixes the `fenced_start_loop` to take into account for this wait time and logs accurate messages in logs files. Before these changes, we're populating the log files with messages like these (notice timestamp)
```
[2024/01/08 12:37:35] (WARNING) failover.vrrp_master():376 - Entering MASTER on "eno1".
[2024/01/08 12:37:35] (WARNING) …
```

NAS-126698 / 24.04 / fix logic in failover.events.fenced_start_loop (by yocalebo)

---

src/middlewared/middlewared/plugins/pool_/dataset_encryption_info.py

This is needed for the UI team. These are exporting encryption keys so I consider that a write operation.

NAS-126756 / 24.04 / add roles to pool.dataset.export_keys* methods

---

src/middlewared/middlewared/plugins/vm/capabilities.py
src/middlewared/middlewared/plugins/vm/clone.py
src/middlewared/middlewared/plugins/vm/info.py
src/middlewared/middlewared/plugins/vm/memory.py
src/middlewared/middlewared/plugins/vm/pci.py
src/middlewared/middlewared/plugins/vm/usb.py
src/middlewared/middlewared/plugins/vm/vm_devices.py
src/middlewared/middlewared/plugins/vm/vm_display_info.py
src/middlewared/middlewared/plugins/vm/vm_lifecycle.py
src/middlewared/middlewared/plugins/vm/vm_memory_info.py
src/middlewared/middlewared/plugins/vm/vms.py
src/middlewared/middlewared/role.py
tests/api2/test_account_privilege_role_private_fields.py
tests/api2/test_vm_roles.py

PR adds roles for VM and VM device services endpoints.
Adds `READONLY` role for public endpoints in use by WebUI.

NAS-125784 / 24.04 / Add VM and VM device roles

---

tests/api2/test_023_kubernetes.py

This commit fixes 2 issues which we were seeing with k8s pod stats test. First issue was that sometimes netdata has not yet collected any stats from Kubernetes, and the test is attempting to retrieve non-existent stats, resulting in an error. The second problem is that when netdata does get stats, it initially provides zero values on the first update, leading to assertion errors in the test.
Here what we do now instead is that we make sure the cluster is up before proceeding with asserting stats and also ensure that the stats have been updated twice to make sure it has actually retrieved data which is relevant.

NAS-126742 / 24.04 / Fix k8s pod stats integration test

---

tests/api2/test_024_container.py

This commit tries to fix a random failure in image pruning integration test where sometimes the container has not yet been fully removed and we prune images and still find the image lying around as the associated container is still alive even though k8s thinks it's gone. So idea is to give it some grace period to close down and if it does not close in the given threshold, we fail with appropriate feedback.

NAS-126799 / 24.04 / Try to fix random pruning integration test failure

---

src/middlewared/middlewared/plugins/pool_/scrub.py

This fixes memory fragmentation issues in python process, as it would allocate a big chunk of memory. This amount of memory is rarely allocated, and over time, the previously allocated block might get fragmented again.
Original PR: https://github.com/truenas/middleware/pull/12889
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126782

NAS-126782 / 24.04 / PoolScrubService.__run: reduce memory usage during zpool history (by rkojedzinszky)

---

tests/api2/test_001_ssh.py

We should abort CI runs if required builtin groups are absent from the DB.

NAS-126817 / 24.04 / Fail tests if required groups are missing

---

src/middlewared/middlewared/plugins/audit/audit.py
tests/api2/test_audit_basic.py

Webui needs and endpoint through which to download generated audit reports that allows access for SYSTEM_AUDIT_READ role.
Users are only allowed to download files from their own audit reports directory.

NAS-126850 / 24.04-BETA.1 / Add dedicated endpoint to download audit reports

---

tests/api2/test_audit_basic.py

This adds test coverage that per-user audit directories are created properly and limited users can generate and download audit reports.

NAS-126865 / 24.10 / Test audit report generation for non-root users

---

tests/api2/test_audit_basic.py

This adds test coverage that per-user audit directories are created properly and limited users can generate and download audit reports.
Original PR: https://github.com/truenas/middleware/pull/12922
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126865

NAS-126865 / 24.04-RC.1 / Test audit report generation for non-root users (by anodos325)

---

src/middlewared/middlewared/plugins/directoryservices.py

We don't want to run though this method if controller is not MASTER. Additionally, we should fail early if SMB has not been properly configured (otherwise we will failure with unrelated errors later in this method).
Original PR: https://github.com/truenas/middleware/pull/12930
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126875

NAS-126875 / 24.04-RC.1 / Fail earlier in directoryservices.setup (by anodos325)

---

src/middlewared/middlewared/plugins/activedirectory.py

There are apparent cases of users manually calling the private `activedirectory.start` API via midclt whilst having an incomplete active directory configuration. This may allow winbindd to start and some AD integration to work, but at the cost of having service potentially get disabled during future health checks. This commit adds some rudimentary detection of this situation and will refuse to start the activedirectory service if we're misconfigured. This commit is for backport to Cobia. More recent versions will have more robust fixes.
Original PR: https://github.com/truenas/middleware/pull/12933
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126878

NAS-126878 / 23.10.2 / Forcibly disable AD service if misconfigured (by anodos325)

---

src/middlewared/middlewared/plugins/ipmi_/lan.py
src/middlewared/middlewared/service/core_service.py

…s()`
Original PR: https://github.com/truenas/middleware/pull/12976
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126980

NAS-126980 / 24.04-RC.1 / Fix `RuntimeError: Method ipmi.lan.query is public but has no @accept… (by themylogin)

---

src/middlewared/middlewared/plugins/failover_/remote.py

With this change the `failover.log` will also include an entry when the connection is reestablished.
```
[2024/01/25 07:59:27] (ERROR) failover.remote.run():52 - Persistent connection refused, retrying every 5 seconds
[2024/01/25 08:01:24] (INFO) failover.remote._on_connect():112 - Persistent connection reestablished
```
If `middlewared` is restarted on the other node, then we see a shorter outage:
```
[2024/01/25 08:23:13] (ERROR) failover.remote.run():52 - Persistent connection refused, retrying every 5 seconds
[2024/01/25 08:23:23] (INFO) failover.remote._on_connect():112 - Persistent connection reestablished
```

NAS-126986 / 24.10 / Improve logging wrt reestablishment on failover RemoteClient connection

---

src/middlewared/middlewared/plugins/failover_/remote.py

With this change the `failover.log` will also include an entry when the connection is reestablished.
```
[2024/01/25 07:59:27] (ERROR) failover.remote.run():52 - Persistent connection refused, retrying every 5 seconds
[2024/01/25 08:01:24] (INFO) failover.remote._on_connect():112 - Persistent connection reestablished
```
If `middlewared` is restarted on the other node, then we see a shorter outage:
```
[2024/01/25 08:23:13] (ERROR) failover.remote.run():52 - Persistent connection refused, retrying every 5 seconds
[2024/01/25 08:23:23] (INFO) failover.remote._on_connect():112 - Persistent connection reestablished
```
Original PR: https://github.com/truenas/middleware/pull/12979
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126986

NAS-126986 / 24.04-RC.1 / Improve logging wrt reestablishment on failover RemoteClient connection (by bmeagherix)

---

src/middlewared/middlewared/plugins/network.py

Typo because I screwed up original PR and then screwed up the "fix"....sigh

NAS-126991 / 24.10 / fix typo in network.py

---

src/middlewared/middlewared/plugins/network.py

Typo because I screwed up original PR and then screwed up the "fix"....sigh
Original PR: https://github.com/truenas/middleware/pull/12993
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126991

NAS-126991 / 24.04-RC.1 / fix typo in network.py (by yocalebo)

---

src/middlewared/middlewared/plugins/disk_/wipe.py

This fixes 2 primary issues:
- job progress reporting wasn't done properly because the `wrap` method wasn't being used
- when we do a QUICK wipe, progress reporting wasn't even being done

NAS-127025 / 24.10 / fix disk.wipe progress reporting

---

src/middlewared/middlewared/plugins/disk_/wipe.py

This fixes 2 primary issues:
- job progress reporting wasn't done properly because the `wrap` method wasn't being used
- when we do a QUICK wipe, progress reporting wasn't even being done
Original PR: https://github.com/truenas/middleware/pull/13011
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127025

NAS-127025 / 24.04-RC.1 / fix disk.wipe progress reporting (by yocalebo)

---

src/middlewared/middlewared/plugins/nfs.py
src/middlewared/middlewared/validators.py

Added validation checks to the NFS exports name field to prevent anomalous NFS export behaviors.

NAS-118281 / 13.1 / Improve validation of NFS exports name field

---

src/middlewared/middlewared/plugins/support.py
src/middlewared/middlewared/schema/string_schema.py
tests/api2/test_261_iscsi_cmd.py
tests/api2/test_charts_schema.py

NAS-127053 / 24.10 / Add max length validation to the support ticket title and description

---

src/middlewared/middlewared/plugins/interface/link_address.py
src/middlewared/middlewared/pytest/unit/plugins/test_interface_link_address.py

…icate hardware link addresses
Original PR: https://github.com/truenas/middleware/pull/13003
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127008

NAS-127008 / 23.10.2 / Do not use interface rename logic on systems that have NICs with dupl… (by themylogin)

---

src/middlewared/middlewared/plugins/interface/link_address.py
src/middlewared/middlewared/pytest/unit/plugins/test_interface_link_address.py

…icate hardware link addresses
Original PR: https://github.com/truenas/middleware/pull/13003
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127008

NAS-127008 / 24.04-RC.1 / Do not use interface rename logic on systems that have NICs with dupl… (by themylogin)

---

src/middlewared/middlewared/plugins/support.py
src/middlewared/middlewared/schema/string_schema.py
tests/api2/test_261_iscsi_cmd.py

git cherry-pick -x de42accb95956e59379c23bccb31bcd3668786df
git cherry-pick -x b89465312d5da5678f8ea18d53836a1da9972ff8
QE team found this issue
Original PR: https://github.com/truenas/middleware/pull/13015
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127053

NAS-127053 / 23.10.2 / Add max length validation to the support ticket title and description (by themylogin)

---

src/middlewared/middlewared/plugins/support.py
src/middlewared/middlewared/schema/string_schema.py
tests/api2/test_261_iscsi_cmd.py

git cherry-pick -x de42accb95956e59379c23bccb31bcd3668786df
git cherry-pick -x b89465312d5da5678f8ea18d53836a1da9972ff8
QE team found this issue
Original PR: https://github.com/truenas/middleware/pull/13015
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127053

NAS-127053 / 24.04-RC.1 / Add max length validation to the support ticket title and description (by themylogin)

---

tests/api2/test_catalog_sync.py

Catalog sync tests were improved and fixed in electriceel/dragonfish but the fixes were not backported to cobia.

NAS-127096 / 23.10.2 / Fix catalog sync tests in cobia

---

tests/api2/test_300_nfs.py

Enhance testing: Confirm NFS rpc port configurations using rpcinfo calls.

NAS-127097 / 24.10 / Enhance NFS rpc port configuration test

---

tests/api2/test_300_nfs.py

Add a CI test for the NFS `v4_domain` configuration option.
This NFS setting maps to a 'Domain' setting in the `General` section of /etc/idmapd.conf
Small amount of refactoring to reuse a config file parser.

NAS-127123 / 24.10 / Add NFS CI test for v4_domain configuration option

---

src/middlewared/middlewared/plugins/disk_/wipe.py
tests/api2/test_disk_wipe.py

git cherry-pick -x 6cabe19096e23f210bd4dfc628d12d9d1add4254
git cherry-pick -x e39bd6d6ab798cb895901cf589dfc94e4c7480e8
Original PR: https://github.com/truenas/middleware/pull/13051
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127026

NAS-127026 / 23.10.2 / Abort underlying thread when aborting disk wipe (by themylogin)

---

docs/source/middleware/jobs.rst
docs/source/middleware/roles.rst

This commit adds a basic description of some features that were added after the developer documentation was initially written.

NAS-127137 / 24.10 / Expand developer documentation related to roles

---

docs/source/middleware/jobs.rst
docs/source/middleware/roles.rst

This commit adds a basic description of some features that were added after the developer documentation was initially written.
Original PR: https://github.com/truenas/middleware/pull/13062
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127137

NAS-127137 / 24.04-RC.1 / Expand developer documentation related to roles (by anodos325)

---

src/middlewared/middlewared/plugins/truecommand/__init__.py

Needed by the UI team.
Original PR: https://github.com/truenas/middleware/pull/13071
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127106

NAS-127106 / 24.04-RC.1 / add readonly to truecommand.config events (by yocalebo)

---

src/middlewared/middlewared/plugins/filesystem.py

Add allocation_size key to filesystem.stat and filesystem.listdir output. This commit also expands documentation for filesystem.stat output.

NAS-127148 / 24.10 / Include information about allocation size

---

src/middlewared/middlewared/plugins/filesystem.py

Add allocation_size key to filesystem.stat and filesystem.listdir output. This commit also expands documentation for filesystem.stat output.
Original PR: https://github.com/truenas/middleware/pull/12286
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127148

NAS-127148 / 24.04-RC.1 / Include information about allocation size (by anodos325)

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/directoryservices.py
src/middlewared/middlewared/plugins/directoryservices_/secrets.py
src/middlewared/middlewared/plugins/idmap.py
src/middlewared/middlewared/plugins/kerberos.py
src/middlewared/middlewared/plugins/tdb/wrapper.py
tests/api2/test_030_activedirectory.py
tests/api2/test_035_ad_idmap.py

This commit refactors the portion of the directoryservices plugin that interacts with secrets.tdb to use our general-purpose TDB plugin and adds tests coverage for functionality.

NAS-127007 / 24.10 / Refactor directoryservices plugin

---

src/middlewared/middlewared/job.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/service/core_service.py
src/middlewared/middlewared/service/decorators.py
tests/api2/test_core_bulk.py

* Allow unauthorized access to core.bulk
* Authenticate calls in `core.bulk` and pass `app`
* Audit calls made with `core.bulk`

NAS-127070 / 24.10 / `core.bulk` and roles

---

src/middlewared/middlewared/job.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/service/core_service.py
src/middlewared/middlewared/service/decorators.py
tests/api2/test_core_bulk.py

* Allow unauthorized access to core.bulk
* Authenticate calls in `core.bulk` and pass `app`
* Audit calls made with `core.bulk`
Original PR: https://github.com/truenas/middleware/pull/13063
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127070

NAS-127070 / 24.04-RC.1 / `core.bulk` and roles (by themylogin)

---

src/freenas/usr/local/bin/truenas-nvdimm.py

Our minis platform start with `TRUENAS-M` but we don't fill in the version information on those platforms. This means `version.parse` crashes on strings that don't have any type of digits in them. This makes this script much more careful with how we parse the relevant information because this is called during install time. If this script crashes unexpectedly, the install/upgrade process will fail as well.

NAS-127199 / 24.10 / robustized truenas-nvdimm.py

---

src/freenas/usr/local/bin/truenas-nvdimm.py

Our minis platform start with `TRUENAS-M` but we don't fill in the version information on those platforms. This means `version.parse` crashes on strings that don't have any type of digits in them. This makes this script much more careful with how we parse the relevant information because this is called during install time. If this script crashes unexpectedly, the install/upgrade process will fail as well.
Original PR: https://github.com/truenas/middleware/pull/13084
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127199

NAS-127199 / 23.10.2 / robustized truenas-nvdimm.py (by yocalebo)

---

src/freenas/usr/local/bin/truenas-nvdimm.py

Our minis platform start with `TRUENAS-M` but we don't fill in the version information on those platforms. This means `version.parse` crashes on strings that don't have any type of digits in them. This makes this script much more careful with how we parse the relevant information because this is called during install time. If this script crashes unexpectedly, the install/upgrade process will fail as well.
Original PR: https://github.com/truenas/middleware/pull/13084
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127199

NAS-127199 / 23.10.3 / robustized truenas-nvdimm.py (by yocalebo)

---

src/freenas/usr/local/bin/truenas-nvdimm.py

Our minis platform start with `TRUENAS-M` but we don't fill in the version information on those platforms. This means `version.parse` crashes on strings that don't have any type of digits in them. This makes this script much more careful with how we parse the relevant information because this is called during install time. If this script crashes unexpectedly, the install/upgrade process will fail as well.
Original PR: https://github.com/truenas/middleware/pull/13084
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127199

NAS-127199 / 24.04-RC.1 / robustized truenas-nvdimm.py (by yocalebo)

---

src/middlewared/middlewared/plugins/catalogs_linux/update.py

This PR fixes a problem where we were still using temp dir when a new catalog was being added so we could validate it before adding it to the system. With the changes, now we use the apps dataset to hold the catalog and validate it for any issues.
Original PR: https://github.com/truenas/middleware/pull/13100
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127213

NAS-127213 / 24.04-RC.1 / Do not use ix temp dir when creating catalogs (by sonicaj)

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/account_/privilege.py

local and ds groups are written via group ID, but are returned as full group entries.

NAS-127268 / 24.10 / Fix schema for privilege plugin

---

src/freenas/usr/bin/install-dev-tools

Allow specifying --force for install-dev-tools in our CI

NAS-127318 / 24.10 / Pass arguments to disable-rootfs-protection

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py

In 777a55be1f09caf9822c04c7a0f56d6c77966de8 i added the logic to ignore events on interfaces that weren't marked critical for failover. However, that still doesn't fix the issue entirely because the non critical interface still gets put into the `self.event_queue` for processing. Interfaces that aren't marked critical for failover need to be ignored before ever being put into the `self.event_queue`. This commit moves, literally, the logic that was introduced in the above commit to the `VrrpFifoThread` which is the "publisher" in this pub/sub model. This makes it so that the interfaces are ignored and never get put into the `self.event_queue`. This was reproduced in-house and the changes were tested confirming it fixes the issue.

NAS-127359 / 24.10 / fix another HA logic issue

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py

In 777a55be1f09caf9822c04c7a0f56d6c77966de8 i added the logic to ignore events on interfaces that weren't marked critical for failover. However, that still doesn't fix the issue entirely because the non critical interface still gets put into the `self.event_queue` for processing. Interfaces that aren't marked critical for failover need to be ignored before ever being put into the `self.event_queue`. This commit moves, literally, the logic that was introduced in the above commit to the `VrrpFifoThread` which is the "publisher" in this pub/sub model. This makes it so that the interfaces are ignored and never get put into the `self.event_queue`. This was reproduced in-house and the changes were tested confirming it fixes the issue.
Original PR: …

NAS-127359 / 23.10.2 / fix another HA logic issue (by yocalebo)

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py

In 777a55be1f09caf9822c04c7a0f56d6c77966de8 i added the logic to ignore events on interfaces that weren't marked critical for failover. However, that still doesn't fix the issue entirely because the non critical interface still gets put into the `self.event_queue` for processing. Interfaces that aren't marked critical for failover need to be ignored before ever being put into the `self.event_queue`. This commit moves, literally, the logic that was introduced in the above commit to the `VrrpFifoThread` which is the "publisher" in this pub/sub model. This makes it so that the interfaces are ignored and never get put into the `self.event_queue`. This was reproduced in-house and the changes were tested confirming it fixes the issue.
Original PR: …

NAS-127359 / 24.04-RC.1 / fix another HA logic issue (by yocalebo)

---

src/middlewared/middlewared/plugins/vm/devices/cdrom.py

This commit adds changes to improve error handling for CDROM devices. Earlier if exec perms were not set we did raise a validation error but we weren't clear enough that exec perms were not set so the changes improve that part and let the user know that exec perms were not properly set.

NAS-126828 / 24.10 / Improve CDROM device validation errors

---

src/middlewared/middlewared/plugins/device_/vrrp_events.py

In 777a55be1f09caf9822c04c7a0f56d6c77966de8 i added the logic to ignore events on interfaces that weren't marked critical for failover. However, that still doesn't fix the issue entirely because the non critical interface still gets put into the `self.event_queue` for processing. Interfaces that aren't marked critical for failover need to be ignored before ever being put into the `self.event_queue`. This commit moves, literally, the logic that was introduced in the above commit to the `VrrpFifoThread` which is the "publisher" in this pub/sub model. This makes it so that the interfaces are ignored and never get put into the `self.event_queue`. This was reproduced in-house and the changes were tested confirming it fixes the issue.
Original PR: …

NAS-127359 / 23.10.3 / fix another HA logic issue (by yocalebo) (by bugclerk)

---

src/middlewared/middlewared/plugins/iscsi_/targets.py

Sorry, only noticed that I'd copied and pasted bad code **after** I'd fixed the source of the copy!  So, (almost) duplicate fix.

NAS-127381 / 24.10 / Fix another indentation error that was logging errors inside loop

---

src/middlewared/middlewared/plugins/iscsi_/targets.py

Sorry, only noticed that I'd copied and pasted bad code **after** I'd fixed the source of the copy!  So, (almost) duplicate fix.
Original PR: https://github.com/truenas/middleware/pull/13162
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127381

NAS-127381 / 23.10.3 / Fix another indentation error that was logging errors inside loop (by bmeagherix)

---

src/middlewared/middlewared/plugins/iscsi_/targets.py

Sorry, only noticed that I'd copied and pasted bad code **after** I'd fixed the source of the copy!  So, (almost) duplicate fix.
Original PR: https://github.com/truenas/middleware/pull/13162
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127381

NAS-127381 / 24.04-RC.1 / Fix another indentation error that was logging errors inside loop (by bmeagherix)

---

src/middlewared/middlewared/plugins/failover_/event.py

QE team is discovering edge cases with our HA failover logic and has pointed out the fact that we can do better with our logging. This fixes very minor logging typos so that the logs are accurate which will benefit more than just the development team but also the QE/Support teams.
Original PR: https://github.com/truenas/middleware/pull/13168
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127390

NAS-127390 / 23.10.2 / better HA logging (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/event.py

QE team is discovering edge cases with our HA failover logic and has pointed out the fact that we can do better with our logging. This fixes very minor logging typos so that the logs are accurate which will benefit more than just the development team but also the QE/Support teams.
Original PR: https://github.com/truenas/middleware/pull/13168
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127390

NAS-127390 / 23.10.3 / better HA logging (by yocalebo)

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

This is a pretty normal situation. E.g. if the DB has the pool named `tank`, but disks were not plugged to the system when it was booting (so boot-time pool import failed), but then the disks were hot-plugged and the pool is being imported explicitly using "import pool".

NAS-127416 / 24.10 / Do not crash if DB already has a pool that is being imported

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

This is a pretty normal situation. E.g. if the DB has the pool named `tank`, but disks were not plugged to the system when it was booting (so boot-time pool import failed), but then the disks were hot-plugged and the pool is being imported explicitly using "import pool".
Original PR: https://github.com/truenas/middleware/pull/13185
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127416

NAS-127416 / 24.04-RC.1 / Do not crash if DB already has a pool that is being imported (by themylogin)

---

src/middlewared/middlewared/plugins/chart_releases_linux/events.py
src/middlewared/middlewared/plugins/truecommand/portal.py
src/middlewared/middlewared/plugins/truecommand/update.py
src/middlewared/middlewared/plugins/vm/events.py

This PR adds changes to make sure no sensitive information is being disclosed from apps/tc/vm events.

NAS-127151 / 24.10 / Make sure there is no sensitive information in apps/tc/vm events plugins

---

src/middlewared/middlewared/plugins/chart_releases_linux/events.py
src/middlewared/middlewared/plugins/truecommand/portal.py
src/middlewared/middlewared/plugins/truecommand/update.py
src/middlewared/middlewared/plugins/vm/events.py

This PR adds changes to make sure no sensitive information is being disclosed from apps/tc/vm events.
Original PR: https://github.com/truenas/middleware/pull/13183
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127151

NAS-127151 / 24.04-RC.1 / Make sure there is no sensitive information in apps/tc/vm events plugins (by sonicaj)

---

src/middlewared/middlewared/plugins/chart_releases_linux/events.py
src/middlewared/middlewared/plugins/truecommand/portal.py
src/middlewared/middlewared/plugins/truecommand/update.py
src/middlewared/middlewared/plugins/vm/events.py

This PR adds changes to make sure no sensitive information is being disclosed from apps/tc/vm events.
Original PR: https://github.com/truenas/middleware/pull/13183
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127151

NAS-127151 / 23.10.3 / Make sure there is no sensitive information in apps/tc/vm events plugins (by sonicaj)

---

src/freenas/usr/lib/netdata/python.d/smart_log.chart.py

Some SSD disks don't add temperature in smartd attribute 194, but they add disk temperature in attribute 190. This causes problems in the netdata disk temp plugin because it doesn't include this attribute as a source of disk temperature.
(I observed this while on a teamviewer session with a user for a different issue)
Refactor the netdata smart plugin to consider attribute 190 if attribute 194 is not available so we are able to retrieve temperature of such disks as well.
- [Issue on guzu/hddtemp GitHub](https://github.com/guzu/hddtemp/issues/15)
- [Ask Ubuntu thread on SSD temperature sensor readout](https://askubuntu.com/questions/474669/ssd-temperature-sensor-readout-with-hddtemp)
Original PR: https://github.com/truenas/middleware/pull/13195
Jira URL: …

NAS-127455 / 24.04-RC.1 / Use 190 attr from smart if 194 is not available when reading disk temps (by Qubad786)

---

src/middlewared/middlewared/plugins/webui/enclosure.py

WebUI team has requested that we should always show the disk details even it's not currently a part of any zpool.

NAS-127470 / 24.10 / always include disk details in enclosure.dashboard

---

src/middlewared/middlewared/plugins/jbof/crud.py
src/middlewared/middlewared/plugins/jbof/functions.py

A few things that I've fixed while implementing ES24N enclosure support.
1. there were no callers of `get_sys_class_nvme` which was doing almost identical work to `get_sys_class_nvme_subsystem`
2. `get_sys_class_nvme_subsystem` was getting mostly duplicate data compared to `get_sys_class_nvme` but was abstracting the data away under the `nvme-subsys` directory names. This doesn't really buy us anything since those dir names are obtuse for the information we're getting out of if
3. move all logic to `get_sys_class_nvme` since we can very easily deduce all the information that we need by iterating over `/sys/class/nvme`
4. clean-up `jobf/crud.py` to use new function and remove a method that is no longer used
5. add doc-string in `jbof/crud.py`
6. fix flake8 issue in `jbof/crud.py`
7. remove …

NAS-127552 / 24.10 / simplify and clean-up nvme/jbof functions

---

src/middlewared/middlewared/plugins/jbof/crud.py
src/middlewared/middlewared/plugins/jbof/functions.py

A few things that I've fixed while implementing ES24N enclosure support.
1. there were no callers of `get_sys_class_nvme` which was doing almost identical work to `get_sys_class_nvme_subsystem`
2. `get_sys_class_nvme_subsystem` was getting mostly duplicate data compared to `get_sys_class_nvme` but was abstracting the data away under the `nvme-subsys` directory names. This doesn't really buy us anything since those dir names are obtuse for the information we're getting out of if
3. move all logic to `get_sys_class_nvme` since we can very easily deduce all the information that we need by iterating over `/sys/class/nvme`
4. clean-up `jobf/crud.py` to use new function and remove a method that is no longer used
5. add doc-string in `jbof/crud.py`
6. fix flake8 issue in `jbof/crud.py`
7. remove …

NAS-127552 / 24.04-RC.1 / simplify and clean-up nvme/jbof functions (by yocalebo)

---

tests/api2/test_260_iscsi.py

Robustize `waiting_for_iscsi_to_disconnect` by also waiting for session to disappear.
This is to eliminate a possible race during a few tests.

NAS-127560 / 24.10 / Robustize waiting_for_iscsi_to_disconnect

---

src/middlewared/middlewared/plugins/kerberos.py

Remove the legacy_validate method that was formerly used by the legacy django middleware for validation. Simplify check for whether to update our stored machine account keytab.

NAS-127610 / 24.10 / Make some minor improvements in kerberos.py

---

src/freenas/usr/local/bin/truenas-initrd.py

…r, and it was not set yet
Original PR: https://github.com/truenas/middleware/pull/13274
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127622

NAS-127622 / 24.04-RC.1 / Do not change `readonly` property when we are running in the installe… (by themylogin)

---

src/freenas/usr/local/bin/truenas-initrd.py

…r, and it was not set yet
Original PR: https://github.com/truenas/middleware/pull/13274
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127622

NAS-127622 / 24.04.0 / Do not change `readonly` property when we are running in the installe… (by themylogin)

---

src/middlewared/middlewared/alert/source/memory_errors.py

Typo in kwarg passed to CrontabSchedule.

NAS-127707 / 24.10 / Fix typo in memory error alert

---

src/middlewared/middlewared/plugins/sysdataset.py

If for some reason a process has an open handle on our old system dataset, log an error message and proceed with a lazy umount to avoid leaving system in broken state.

NAS-127724 / 24.10 / Try much harder to not break the system dataset

---

src/middlewared/middlewared/plugins/failover_/remote.py

…Series
Original PR: https://github.com/truenas/middleware/pull/13307
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127776

NAS-127776 / 24.04.0 / Do not spam HA logs with `OSError: [Errno 22] Invalid argument` on F-… (by themylogin)

---

src/middlewared/middlewared/plugins/kerberos.py

If the Active Directory service is deleted and user decides to actually delete the existing AD machine account keytab, we should make sure that potential references to it are removed from the AD form.
Original PR: https://github.com/truenas/middleware/pull/13303
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127772

NAS-127772 / 24.04.0 / Remove reference to AD kerberos principal (by anodos325)

---

src/middlewared/middlewared/etc_files/keepalived.conf.mako

…sent
Without this, the IPv6 address was being presented concurrently on both the ACTIVE and STANDBY controllers.
Note this issue only occurs when **both** IPv4 and IPv6 addresses are added to the **same** interface.
* See also https://github.com/acassen/keepalived/issues/2146
Original PR: https://github.com/truenas/middleware/pull/13317
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127807

NAS-127807 / 24.04-RC.1 / Add vrrp_sync_group when both IPv4 and IPv6 virtual addresses are pre… (by bmeagherix)

---

src/middlewared/middlewared/etc_files/keepalived.conf.mako

…sent
Without this, the IPv6 address was being presented concurrently on both the ACTIVE and STANDBY controllers.
Note this issue only occurs when **both** IPv4 and IPv6 addresses are added to the **same** interface.
* See also https://github.com/acassen/keepalived/issues/2146
Original PR: https://github.com/truenas/middleware/pull/13317
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127807

NAS-127807 / 24.04.0 / Add vrrp_sync_group when both IPv4 and IPv6 virtual addresses are pre… (by bmeagherix)

---

src/middlewared/middlewared/plugins/disk_/wipe.py

git cherry-pick -x d2a4818936c902a1212dfa55f36453c3e82a6f79
git cherry-pick -x 8476ac47440439be226846355032c6c3e3a0e923
Original PR: https://github.com/truenas/middleware/pull/13331
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127839

NAS-127839 / 24.04.0 / Flush buffers in `disk.wipe` (by themylogin)

---

src/freenas/debian/preinst
src/freenas/usr/share/spice-html5/spice-password-20240315.patch
src/freenas/usr/share/spice-html5/spice.css
src/freenas/usr/share/spice-html5/spice_auto.html

Add a bit of JS to the SPICE VM Viewer to ensure that passwords are displayed with *** instead of plaintext. 
Original PR: https://github.com/truenas/middleware/pull/13353
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127868

NAS-127868 / 24.04-RC.1 / NAS-127868 - Hide Passwords for SPICE Viewer (by kmoore134)

---

src/freenas/debian/preinst
src/freenas/usr/share/spice-html5/spice-password-20240315.patch
src/freenas/usr/share/spice-html5/spice.css
src/freenas/usr/share/spice-html5/spice_auto.html

Add a bit of JS to the SPICE VM Viewer to ensure that passwords are displayed with *** instead of plaintext. 
Original PR: https://github.com/truenas/middleware/pull/13353
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127868

NAS-127868 / 24.04.0 / NAS-127868 - Hide Passwords for SPICE Viewer (by kmoore134)

---

src/middlewared/middlewared/plugins/system_advanced/config.py

Malformed isolated GPU configurations affect the update operation of other system advanced settings because they are all validated at the same place in the system.advanced.update API.
Remove ability to update isolated GPU config from system.advanced.update to avoid this problem. Additionally, a separate endpoint `system.advanced.update_gpu_pci_ids` already exists to configure and validate isolated GPUs.

NAS-127590 / 24.10 / Remove ability to manipulate GPU isolation settings from system.advanced.update endpoint

---

tests/api2/test_001_ssh.py

This commit adds tests that iterate through our dataset schema and validate that the dataset settings and permissions are properly applied.

NAS-127840 / 24.10 / Add tests for boot pool configuration

---

src/middlewared/middlewared/alert/source/iscsi.py

When `ISCSIPortalIPAlertSource.check` runs on the STANDBY node of a HA pair-while ALUA has been enabled, it will present the Alert with all of the used Virtual IPs.  Filter them out.
Original PR: https://github.com/truenas/middleware/pull/13363
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127874

NAS-127874 / 24.04.0 / Prevent ISCSIPortalIPAlert for HA STANDBY with ALUA (by bmeagherix)

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

Fixes to the pool import process in NAS-123504 accidentally removed logic to normalize our ACL-related root-level dataset settings. This commit ensures that when pools are imported we strip out unsupported share_smb, share_nfs parameters as well as setting correct aclmode and aclinhert properties.

NAS-127867 / 24.10 / Normalize root-level dataset properties on import

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

Fixes to the pool import process in NAS-123504 accidentally removed logic to normalize our ACL-related root-level dataset settings. This commit ensures that when pools are imported we strip out unsupported share_smb, share_nfs parameters as well as setting correct aclmode and aclinhert properties.
Original PR: https://github.com/truenas/middleware/pull/13355
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127867

NAS-127867 / 24.04.0 / Normalize root-level dataset properties on import (by anodos325)

---

src/middlewared/middlewared/plugins/service_/services/lldp.py

This looks like a long-lived typo in the service config.

NAS-127933 / 13.3 / Fix LLDP plugin etc generate

---

src/freenas/etc/logrotate.d/scst
src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnfilters.conf.mako
src/middlewared/middlewared/etc_files/syslog-ng/syslog-ng.conf.mako

- Add `scst` related logging into _/var/log/scst.log_
- Add `logrotate` instructions

NAS-127340 / 24.10 / Move scst logs into /var/log/scst.log

---

tests/api2/test_001_ssh.py
tests/api2/test_003_network.py
tests/api2/test_007_systemdataset.py
tests/api2/test_008_pool.py

Detect critical failures earlier in test run and bail to provide engineering with VM in failed state.

NAS-127973 / 13.3 / Expand situations in which 13.3 will terminate test runs

---

src/middlewared/middlewared/test/integration/assets/smb.py
tests/api2/test_425_smb_protocol.py
tests/api2/test_smb_client.py

Add explicit tests for the xattr handlers for alternate data streams.

NAS-127927 / 24.10 / Expand SMB client testing

---

tests/api2/test_006_pool_and_sysds.py

This fixes the immediate issue whereby HA API pipeline was failing with `socket.timeout` issues. The reason why the `socket.timeout` is happening is fully understood but to keep changes minimal, I'll keep that PR separate from this one.

NAS-128059 / 24.10 / fix HA API

---

tests/api2/test_261_iscsi_cmd.py

- Better to use websocket as this is what the UI uses
- the REST test functions (`GET`, `POST`, `PUT`, `DELETE`) never use the VIP in a HA config (and are therefore susceptible to breakage when Node A is the STANDBY node).

NAS-128100 / 24.10 / Switch iSCSI tests from REST to websocket

---

src/middlewared/middlewared/plugins/chart_releases_linux/events.py

The `chart.release.stats` endpoint currently returns network statistics in cumulative output format. This poses challenges for the UI, as it requires network stats in per interval/second format.
Convert cumulative network statistics into per second format within the `chart.release.statistics` even sourcet, which is utilized by the UI to display chart release statistics.

NAS-128160 / 24.10 / Have app stats reported as per interval in event source

---

src/middlewared/middlewared/plugins/chart_releases_linux/events.py

The `chart.release.stats` endpoint currently returns network statistics in cumulative output format. This poses challenges for the UI, as it requires network stats in per interval/second format.
Convert cumulative network statistics into per second format within the `chart.release.statistics` even sourcet, which is utilized by the UI to display chart release statistics.
Original PR: https://github.com/truenas/middleware/pull/13451
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128160

NAS-128160 / 24.04.0 / Have app stats reported as per interval in event source (by Qubad786)

---

src/middlewared/middlewared/plugins/system/__init__.py

This commit fixes an issue where system boot id is currently changing on each middleware restart, we now introduce changes to make sure that it remains persistent across a single boot of the system itself and not just middleware.

NAS-128139 / 24.10 / Make sure system boot id is persistent across a single boot

---

src/middlewared/middlewared/plugins/system/__init__.py

This commit fixes an issue where system boot id is currently changing on each middleware restart, we now introduce changes to make sure that it remains persistent across a single boot of the system itself and not just middleware.
Original PR: https://github.com/truenas/middleware/pull/13446
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128139

NAS-128139 / 24.04.0 / Make sure system boot id is persistent across a single boot (by sonicaj)

---

src/middlewared/middlewared/plugins/failover.py

This commit fixes an issue where when we have a failover.upgrade job running and HA_UPGRADE is set to true there but it is still ongoing and a consumer (in our case that is UI) calls failover.upgrade_pending, we prematurely set HA_UPGRADE to false which results in upgrade completing on remote node but current node not saying that an upgrade is pending and can be finished by reboot because we had prematurely set the cached key to false.

NAS-127510 / 24.04.0 / Add a check in failover.upgrade_pending

---

src/middlewared/middlewared/plugins/failover.py

This commit fixes an issue where when we have a failover.upgrade job running and HA_UPGRADE is set to true there but it is still ongoing and a consumer (in our case that is UI) calls failover.upgrade_pending, we prematurely set HA_UPGRADE to false which results in upgrade completing on remote node but current node not saying that an upgrade is pending and can be finished by reboot because we had prematurely set the cached key to false.
Original PR: https://github.com/truenas/middleware/pull/13465
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127510

NAS-127510 / 24.10 / Add a check in failover.upgrade_pending (by sonicaj)

---

src/middlewared/middlewared/plugins/iscsi_/auth.py
src/middlewared/middlewared/plugins/iscsi_/extents.py
src/middlewared/middlewared/plugins/iscsi_/host_crud.py
src/middlewared/middlewared/plugins/iscsi_/host_target.py
src/middlewared/middlewared/plugins/iscsi_/initiator.py
src/middlewared/middlewared/plugins/iscsi_/iscsi_global.py
src/middlewared/middlewared/plugins/iscsi_/portal.py
src/middlewared/middlewared/plugins/iscsi_/target_to_extent.py
src/middlewared/middlewared/plugins/iscsi_/targets.py
tests/api2/test_audit_iscsi.py

Add audit for iSCSI management operations.

NAS-127769 / 24.10 / Add audit for iSCSI endpoints

---

tests/runtest.py

This import got lost in the recent churn.

NAS-128215 / 24.04.1 / Add missing socket import

---

tests/runtest.py

This import got lost in the recent churn.
Original PR: https://github.com/truenas/middleware/pull/13477
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128215

NAS-128215 / 24.04.0 / Add missing socket import (by bmeagherix)

---

tests/api2/test_011_user.py

This file has "organically" grown over the years but, more importantly, it wasn't maintained. We just kept adding to the pile. This is the necessary proverbial "yak shaving" that has to occur in projects. This does 2 primary things: 1. remove REST and replace with WS and 2. refactor and optimize so we're not making unnecessary calls to the TrueNAS. I've tested incessantly and the tests are all passing. The _only_ fallout was the seemingly random test that call `user.has_local_administrator_setup` which, again, doesn't actually seem to have anything to do with any of the tests in this file. That's just verifying that a local administrator has been setup on the TrueNAS. I've commented out that test since there isn't an obvious equivalent functionality with our websocket client and I was …

NAS-128258 / 24.10 / fix and improve test_011_user

---

tests/api2/test_011_user.py

This file has "organically" grown over the years but, more importantly, it wasn't maintained. We just kept adding to the pile. This is the necessary proverbial "yak shaving" that has to occur in projects. This does 2 primary things: 1. remove REST and replace with WS and 2. refactor and optimize so we're not making unnecessary calls to the TrueNAS. I've tested incessantly and the tests are all passing. The _only_ fallout was the seemingly random test that call `user.has_local_administrator_setup` which, again, doesn't actually seem to have anything to do with any of the tests in this file. That's just verifying that a local administrator has been setup on the TrueNAS. I've commented out that test since there isn't an obvious equivalent functionality with our websocket client and I was …

NAS-128258 / 24.04.1 / fix and improve test_011_user (by yocalebo)

---

tests/api2/test_enable_disable_services.py

Some breakage was introduced by NAS-128261 (which I approved)

NAS-128278 / 24.10 / Fix recent breakage

---

src/middlewared/middlewared/plugins/jbof/crud.py

This was introduced at the last moment during PR #13379

NAS-128282 / 24.10 / Fix bug in jbof.set_mgmt_ip

---

src/middlewared/middlewared/plugins/jbof/crud.py

This was introduced at the last moment during PR #13379
Original PR: https://github.com/truenas/middleware/pull/13516
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128282

NAS-128282 / 24.04.1 / Fix bug in jbof.set_mgmt_ip (by bmeagherix)

---

src/middlewared/middlewared/plugins/jbof/crud.py

This was introduced at the last moment during PR #13379
Original PR: https://github.com/truenas/middleware/pull/13516
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128282
Original PR: https://github.com/truenas/middleware/pull/13517
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128282

NAS-128282 / 24.04.0 / Fix bug in jbof.set_mgmt_ip (by bmeagherix) (by bugclerk)

---

src/middlewared/middlewared/plugins/jbof/redfish/client.py

Nice to be able to capture redfish traffic if necessary (was requested).

NAS-128290 / 24.10 / Add some (disabled by default) logging wrt redfish client

---

tests/api2/test_smb_share_crud_roles.py

This fixes a test that got broken on backport of code change.

NAS-128311 / 24.04.1 / Fix test on dragonfish

---

src/middlewared/middlewared/plugins/service_/services/cifs.py

It was observed in some of our testing VMs that samba-dcerpcd could be in running state without pidfile being created.

NAS-128313 / 13.3 / Adjust dcerpcd kill logic

---

src/middlewared/middlewared/plugins/iscsi_/extents.py

Breakage was introduced in PR #13273

NAS-128316 / 24.10 / Fix extent zvol space

---

src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/plugins/post_install.py
src/middlewared/middlewared/service_exception.py

This file will be written by the installer API server https://ixsystems.atlassian.net/browse/NAS-127428 to set up the network configuration (as discussed in NEP-045)

NAS-128359 / 24.10 / Apply settings from `/data/post_install.json`

---

src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/failover_/datastore.py
src/middlewared/middlewared/plugins/failover_/remote.py
src/middlewared/middlewared/utils/db.py
tests/api2/test_007_early_settings.py

Add options to `failover.send_file` and restrict the `mode` when calling.

NAS-128374 / 24.10 / Add options to failover.send_file

---

src/middlewared/middlewared/plugins/security/update.py
src/middlewared/middlewared/scripts/configure_fips.py

This commit fixes an issue where fips will not toggle value because /usr is not writable and fail.

NAS-128383 / 24.10 / Make sure /usr is writable when making fips changes

---

src/middlewared/middlewared/logger.py
src/middlewared/middlewared/main.py

This commit adds changes to log k8s api client exceptions to a separate file to reduce spam in middlewared logs and improve readability.

NAS-127517 / 24.10 / Log k8s api client exceptions to a separate file

---

src/middlewared/middlewared/plugins/vm/devices/pci.py
src/middlewared/middlewared/plugins/vm/devices/usb.py
src/middlewared/middlewared/plugins/vm/supervisor/supervisor.py

**Problem:**
An issue arises when the same PCI device is added to two virtual machines (VMs), and one of the VMs is already running. When the user attempts to start the second VM, QEMU raises an error indicating that the PCI device is already in use by another VM.
**Solution:**
To address this problem, validation for the PCI device has been updated. It now also considers whether the same PCI device is in use by another VM. If the PCI device is not in use by any other VM, it is marked as available for use or otherwise error out on middleware side that the device is already being used.

NAS-123677 / 24.10 / Improve error handling for already in use PCI devices

---

src/freenas/etc/nsswitch.conf

NAS-128644 / 24.10 / Add SSS module to base nsswitch.conf

---

src/middlewared/middlewared/etc_files/pam.d/pam.inc.mako

This commit adds basic SSSD integration with our existing pam modules. Based on sample pam config provided by debian.

NAS-128645 / 24.10 / Add SSSD to pam configuration

---

src/middlewared/middlewared/plugins/idmap.py

When generating synthetic accounts (ones used for user.query and group.query results) stop requiring the LDAP UID and GID to fit within the allocated idmap ranges in winbindd. We can do this safely now that we return whether group is `local` in nss module results. This is first step toward removal of legacy samba NT domain support as well.

NAS-128677 / 24.10 / Loosen restrictions for LDAP idmap validation

---

src/middlewared/middlewared/plugins/directoryservices_/cache.py

Due to legacy behavior with dscache.get_uncached_user we passed None for fields that were not used. user.get_user_obj and group.get_group_obj do not allow null values for these fields.

NAS-128789 / 24.10 / Fix AD cache retrieval issue

---

src/middlewared/middlewared/plugins/boot.py
src/middlewared/middlewared/plugins/disk_/swap_configure.py
src/middlewared/middlewared/plugins/zfs_/zfs_events.py

Another area for improvement that I found while investigating (c.f. https://github.com/truenas/middleware/pull/13660) is that I noticed 4 duplicate calls to our process pool were being made on middlewared startup. The duplicate calls were determining the disks of the boot pool. The particular system I investigated was an HA machine. The amount of these calls on non-HA would be half (so 2).
Either way, the boot disk information can be easily cached. This information rarely changes and when it does, we can reset the cache. On the system I tested these changes on, it reduced the number of calls to 1 (instead of 4) for determining the disks in the boot pool.
NOTE: Since this is a globally cached value, I've converted the object type to be immutable (tuple) from mutable (list). I've updated …

NAS-128772 / 24.10 / cache boot disks

---

src/middlewared/middlewared/main.py

… loop
Original PR: https://github.com/truenas/middleware/pull/10509
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119770

NAS-119770 / 13.3 / Fix typo that leads to jobs being managed from outside the main event… (by themylogin)

---

src/freenas/usr/lib/netdata/python.d/k3s_stats.chart.py

The network statistics for apps appear unusually high when the app is utilizing the host network. Upon investigation, it was discovered that for apps using the host network, Kubernetes employs the kube-bridge interface. Consequently, traffic passing from kube-bridge to the physical interface is duplicated, as traffic from all interfaces used by the pod is aggregated.
When a pod is utilizing the kube-bridge interface, only consider the traffic associated with the kube-bridge interface and disregard traffic from other interfaces. This approach acknowledges that all pod traffic traverses through the kube-bridge interface.

NAS-128471 / 24.10 / Fix app stats when they are using host network

---

src/freenas/usr/lib/netdata/python.d/k3s_stats.chart.py

The network statistics for apps appear unusually high when the app is utilizing the host network. Upon investigation, it was discovered that for apps using the host network, Kubernetes employs the kube-bridge interface. Consequently, traffic passing from kube-bridge to the physical interface is duplicated, as traffic from all interfaces used by the pod is aggregated.
When a pod is utilizing the kube-bridge interface, only consider the traffic associated with the kube-bridge interface and disregard traffic from other interfaces. This approach acknowledges that all pod traffic traverses through the kube-bridge interface.
Original PR: https://github.com/truenas/middleware/pull/13684
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128471

NAS-128471 / 24.04.1 / Fix app stats when they are using host network (by Qubad786)

---

src/middlewared/middlewared/plugins/audit/audit.py
src/middlewared/middlewared/plugins/audit/utils.py
tests/api2/test_audit_basic.py

Fix divide by zero issue.
Fix typo and flake8 issue.
Update CI tests to include disable of quota and reservation.
Original PR: https://github.com/truenas/middleware/pull/13686
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128854

NAS-128854 / 24.04.2 / Minimal fix for audit storage config. (by mgrimesix)

---

src/middlewared/middlewared/plugins/smb.py

This commit make two minor changes regarding time machine:
1. Always generate a volume UUID when creating a new SMB share. This field is only used in mDNS SRV record for the time machine service. Netatalk historically would regenerate the VUID on service restart without apparent issues. MacOS SMB servers generate randomized VUID on time machine share creation. This is slightly more aggressive than legacy behavior (which generated as-needed) but is consistent with MacOS behavior.
2. Ensure that `timemachine` is always flagged as True when our timemachine-related presets are used.

NAS-128892 / 24.10 / Minor time machine quality of life fixes

---

src/middlewared/middlewared/plugins/filesystem_/stat_x.py
src/middlewared/middlewared/pytest/unit/utils/test_statx.py

* Validate that output matches what we see from os.stat
* Validate that opening with dirfd works as expected
* Validate that opening with AT_EMPTY_PATH works as expected

NAS-128911 / 24.10 / Add basic tests for statx wrapper

---

src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_graphs.py

It was requested that we remove swap utilization being reported by reporting plugin.

NAS-128890 / 24.10 / Remove swap utilization from reporting

---

src/middlewared/middlewared/plugins/kubernetes_linux/update.py

Give concrete guidance to users about what they need to do to remediate the situation causing the ValidationError.

NAS-128995 / 24.10 / Improve error message for invalid ix-apps pool

---

src/middlewared/middlewared/plugins/kubernetes_linux/update.py

Give concrete guidance to users about what they need to do to remediate the situation causing the ValidationError.
Original PR: https://github.com/truenas/middleware/pull/13717
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128995

NAS-128995 / 24.04.2 / Improve error message for invalid ix-apps pool (by anodos325)

---

src/middlewared/middlewared/plugins/kubernetes_linux/update.py

Give concrete guidance to users about what they need to do to remediate the situation causing the ValidationError.
Original PR: https://github.com/truenas/middleware/pull/13717
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128995

NAS-128995 / 24.04.1 / Improve error message for invalid ix-apps pool (by anodos325)

---

tests/api2/test_audit_basic.py

Corrected the default configuration test.
Some refactor to better process the defaults.

NAS-129001 / 24.10 / Fix default config test

---

src/middlewared/middlewared/utils/filesystem/stat_x.py

When testing recursive operations with huge numbers of files it was determined that creating the statx function on every call accounted for large amount of overhead. This should never change and so it's safe to look up / define the function only once.

NAS-129018 / 24.10 / Improve statx performance

---

src/middlewared/middlewared/plugins/disk_/wipe.py

NAS-129050 / 24.10 / Fix typo in recent commit: pathlib.path should be pathlib.Path

---

tests/api2/test_200_ftp.py
tests/api2/test_300_nfs.py
tests/api2/test_440_snmp.py
tests/api2/test_vmware.py

Another `ip` -> `truenas_server.ip` fix (completing a recent change to this file in #13721)
Also `flake8`

NAS-129052 / 24.10 / Another ip -> truenas_server.ip fix

---

tests/api2/test_kubernetes_delegate_validation.py

This updates the kubernetes delegate validation test to use our new more verbose validation error message.

NAS-129061 / 24.10 / Fix kubernetes delegate validation test

---

tests/api2/test_kubernetes_delegate_validation.py

This updates the kubernetes delegate validation test to use our new more verbose validation error message.
Original PR: https://github.com/truenas/middleware/pull/13753
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129061

NAS-129061 / 24.04.2 / Fix kubernetes delegate validation test (by anodos325)

---

src/middlewared/middlewared/plugins/chart_releases_linux/events.py

App network stats are showing greater than the actual value. After investigation, the problem was found in cache values. We are caching values by reference, which causes issues because if the actual value updates, the cache updates as well.
Fix the cache issue by copying data into the cache. After fixing the cache issue, a new problem occurred where the network stats difference remained 0 for most of the time. This was fixed by caching the network rate and returning the cached network rate if the actual rate is 0.

NAS-129109 / 24.10 / Fix app stats event caching

---

src/middlewared/middlewared/plugins/chart_releases_linux/events.py

App network stats are showing greater than the actual value. After investigation, the problem was found in cache values. We are caching values by reference, which causes issues because if the actual value updates, the cache updates as well.
Fix the cache issue by copying data into the cache. After fixing the cache issue, a new problem occurred where the network stats difference remained 0 for most of the time. This was fixed by caching the network rate and returning the cached network rate if the actual rate is 0.
Original PR: https://github.com/truenas/middleware/pull/13766
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129109

NAS-129109 / 24.04.1 / Fix app stats event caching (by Qubad786)

---

src/middlewared/middlewared/plugins/chart_releases_linux/events.py

App network stats are showing greater than the actual value. After investigation, the problem was found in cache values. We are caching values by reference, which causes issues because if the actual value updates, the cache updates as well.
Fix the cache issue by copying data into the cache. After fixing the cache issue, a new problem occurred where the network stats difference remained 0 for most of the time. This was fixed by caching the network rate and returning the cached network rate if the actual rate is 0.
Original PR: https://github.com/truenas/middleware/pull/13766
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129109

NAS-129109 / 24.04.2 / Fix app stats event caching (by Qubad786)

---

tests/api2/test_network_configuration.py

Test was not taking HA differences into account.  Rectify.

NAS-129191 / 24.10 / Make test_changing_hostname HA aware

---

src/middlewared/middlewared/plugins/iscsi_/host_crud.py

Broken with iSCSI auditing was introduced in PR #13427.

NAS-129205 / 24.10 / Fix iscsi.host.batch_update

---

src/middlewared/middlewared/plugins/disk_/availability.py
tests/api2/test_006_pool_and_sysds.py

UI team is running into road-blocks implementing the new enclosure API. This resolves their current issues by adding a `disk.details` method that returns the exact same information as `disk.get_unused`. However, it also returns disks that are 'in use".
The only addition to the returned response is an `imported_zpool` key. This is self-explanatory on what it represents. Tons of our tests already depend on `disk.get_unused` working properly so there was no need to update those tests. However, i did update a few existing critical tests to exercise this new endpoint to ensure it behaves as intended.

NAS-128652 / 24.10 / add disk.details (for UI team)

---

src/middlewared/middlewared/plugins/etc.py

`etc.generate` now returns list of files / changes. Developers can use this as hint when files are changing (if needed).

NAS-129280 / 24.10 / Reduce log spam on etc file generation

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

We have had a total of 2 users complain about increase pool import times after upgrading from Cobia to Dragonfish. Fortunately, one of those users granted me remote access to their system and I was able to identify where the issue is.
Some notes:
1. both reporters have systems with > 10k snapshots (12k, and 89k respectively)
2. when `sharenfs` or `sharesmb` is set, something is iterating over every single snapshot of all child datasets on the pool
To make matters worse, the pool that I looked at was 5.4k RPM 6-wide RAIDz2 so waiting on spindle accesses play into the "speed" of this as well.
To recap, there are 2 issues:
1. there is a proper upstream zfs regression (this will be fixed (hopefully) in EE+)
2. the middleware can be a bit more intelligent by NOT updating properties unless the …

NAS-128913 / 24.04.2 / fix long boot times when >10k snapshots (by yocalebo)

---

src/middlewared/middlewared/plugins/chart_releases_linux/resources.py

We were showing pods which were no longer running for console access choices which would obviously not work as the pod is no longer active.
Make sure only those pods are shown as valid for pod console access choices which are actually running at that time.

NAS-128919 / 24.04.2 / Show only pods which are running when retrieving choices for pod console access

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

Add the various mini properties so that `front_loaded` and `front_slots` behave properly.

NAS-129471 / 24.10 / add mini slot tracking to new enclosure

---

src/freenas/debian/rules

Download most recent IANA enterprise numbers on build of the truenas-files package.

NAS-128598 / 24.10 / Add IANA Enterprise numbers file to truenas-files

---

src/middlewared/middlewared/plugins/vm/lifecycle.py

If >= 1 VM has been created on TrueNAS, the default 90 second timeout is applied during the shutdown of TrueNAS even if the VM isn't started. This changes it so that we don't actually do work unless there is a VM that is in `ACTIVE_STATES`.

NAS-129481 / 24.10 / dont hang shutdown for vms that arent started

---

src/middlewared/middlewared/plugins/vm/lifecycle.py

If >= 1 VM has been created on TrueNAS, the default 90 second timeout is applied during the shutdown of TrueNAS even if the VM isn't started. This changes it so that we don't actually do work unless there is a VM that is in `ACTIVE_STATES`.
Original PR: https://github.com/truenas/middleware/pull/13909
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129481

NAS-129481 / 24.04.3 / dont hang shutdown for vms that arent started (by yocalebo)

---

src/middlewared/middlewared/plugins/vm/lifecycle.py

If >= 1 VM has been created on TrueNAS, the default 90 second timeout is applied during the shutdown of TrueNAS even if the VM isn't started. This changes it so that we don't actually do work unless there is a VM that is in `ACTIVE_STATES`.
Original PR: https://github.com/truenas/middleware/pull/13909
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129481
Original PR: https://github.com/truenas/middleware/pull/13910
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129481

NAS-129481 / 24.04.2 / dont hang shutdown for vms that arent started (by yocalebo) (by bugclerk)

---

src/middlewared/middlewared/service/core_service.py

The method calls that are part of `core.download` are not being audited.
The parameters for `core.download` include 
When adding auditing of the audit subsystem it was discovered that method calls via `core.download` were not being audited.
This PR converts `core.download` to include auditing.

NAS-129695 / 24.10 / Change download method from call to call_with_audit.

---

src/middlewared/middlewared/plugins/iscsi_/targets.py

This log spam was introduced by fix in PR #13844

NAS-129712 / 24.10 / Do not attempt to cleanup None initiator

---

src/middlewared/middlewared/plugins/iscsi_/targets.py

This log spam was introduced by fix in PR #13844
Original PR: https://github.com/truenas/middleware/pull/13932
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129712

NAS-129712 / 24.04.3 / Do not attempt to cleanup None initiator (by bmeagherix)

---

src/middlewared/middlewared/plugins/kerberos.py

Break out of renewal loop if directory services are disabled.

NAS-129752 / 24.10 / Fix log spam related to kerberos ticket renewal

---

src/middlewared/middlewared/utils/tdb.py

These directories used to be created on initialization of tdb plugin.

NAS-129793 / 24.10 / Create tdb directories if needed

---

src/middlewared/middlewared/plugins/system/product.py

NAS-129881 / 24.10 / make system.product_name avail to readonly_admin

---

tests/api2/test_261_iscsi_cmd.py

Add `verify_client_count` function that repeats `get_client_count` calls a few times until it gets the expected value.

NAS-129956 / 24.10 / Robustize test_31_iscsi_sessions

---

src/middlewared/middlewared/plugins/smb_/groupmap.py

Some review comments were skipped prior to merging NAS-129929 fix. This commit expands documentation of groupmap functions and addresses an edge case where invalid groupmap entries could cause a keyerror to get raised.

NAS-130007 / 24.10 / Finish addressing review of SID handling PR

---

tests/api2/test_200_ftp.py

The issue started with the continual failure (now separately fixed with https://github.com/truenas/middleware/pull/14008)
The test was also not covering all cases: upload(pass, fail), download(pass,fail)
This PR fixes that testing hole.  Also refactored to make the test more readable.
Includes recent 'quit' exception fix.
Passing CI tests are [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1385/testReport/api2/test_200_ftp/).

NAS-127729 / 24.10 / Refactored and fixed FTP resume xfer test.

---

src/middlewared/middlewared/plugins/failover_/internal_interface.py

In recent PR #13971 some code was added to setup the HA middleware connection on middleware service restart.
In certain circumstances (i.e. particular hardware) this had a negative impact on the system boot; `middlewared` started (abortively) a couple of times before getting going, and the `ix-etc` service failed as a result.
We **_avoid_** the situation, by making the recently added call only occur when the system was ready.  (The original `ix-netif  -> pre_interface_sync` driven mechanism used at boot remains as it was.  Only the new mechanism for middleware restart is modified.)
---
Build with these changes has CI run [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1408/).
In addition, have loaded onto one system that was previously exhibiting the issue -> …

NAS-130005 / 24.10 / Only run failover.internal_interface.pre_sync when system is ready

---

tests/conftest.py

There are certain conditions under which we exit pytest early via a `fail` test asset. These usually represent serious errors that require attention, and should have a special indication within the jenkins pipeline (but still gather test results assets). This commit adds a custom return code for cases where we fail tests (EX_SOFTWARE / 70) for the situation. The value was chosen because it is significantly higher than the maximum pytest.ExitCode enum value and should not collide with future returncodes from upstream project.

NAS-130042 / 24.10 / Add custom exit code for fail() in test runs

---

tests/api2/test_999_pool_dataset_unlock.py

This test was being skipped due to removal of test dependency. This commit re-enables by removing the spurious dependency and fixes temporary test asset generation.

NAS-130072 / 24.10 / Fix test for pool encryption unlock on services

---

src/middlewared/middlewared/plugins/apps/app_scale.py
src/middlewared/middlewared/plugins/apps/cert_attachments.py
src/middlewared/middlewared/plugins/apps/crud.py
src/middlewared/middlewared/plugins/apps/ix_apps/metadata.py
src/middlewared/middlewared/plugins/apps/ix_apps/path.py
src/middlewared/middlewared/plugins/apps/metadata.py
src/middlewared/middlewared/plugins/docker/state_management.py

This PR adds ability for apps to be redeployed and certificate attachments so that apps consuming certs can be tracked/redeployed appropriately.

NAS-130086 / 24.10 / Add certificate attachments for apps

---

src/middlewared/middlewared/plugins/enclosure_/jbof/utils.py

NAS-130089 / 24.10 / fix copy and paste error

---

src/middlewared/middlewared/test/integration/assets/directory_service.py
tests/api2/test_275_ldap.py

Replace REST methods with WS and add test for caching.

NAS-130097 / 24.10 / Clean up LDAP CI test file

---

src/middlewared/middlewared/alert/source/jbof.py
src/middlewared/middlewared/pytest/unit/alert/source/test_jbof.py

Add JBOF alerts to notify the user of various abnormal situations wrt any configured ES24n.

NAS-127614 / 24.10 / JBOF alerts

---

tests/api2/test_nfs_share_crud_roles.py

NAS-130111 / 24.10 / fix failing test

---

src/freenas/usr/local/bin/truenas-grub.py

This configures the main grub entry to include the vendor name if supplied

NAS-130002 / 24.10 / Inject vendor in main grub.cfg

---

src/middlewared/middlewared/plugins/filesystem_/acl.py
tests/api2/test_pool_dataset_acl.py

Have filesystem.add_to_acl return boolean value indicating whether ACL was changed and shift the check for whether we need force flag to after the check for whether changes are needed.

NAS-130158 / 24.10 / Shift around checks in add_to_acl

---

tests/api2/test_530_ups.py

Add the ability to specify `dummy-ups` driver, and add some tests that utilize it.
(Also, first updated the existing tests to use WS client, but didn't otherwise modify them.)
---
Passing CI test is [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1547/).

NAS-129207 / 24.10 / Utilize NUT dummy-ups to facilitate UPS event CI testing

---

src/middlewared/middlewared/plugins/apps/crud.py
src/middlewared/middlewared/plugins/apps/resources.py
src/middlewared/middlewared/plugins/apps/resources_utils.py
src/middlewared/middlewared/plugins/apps/schema_normalization.py
src/middlewared/middlewared/plugins/catalog/apps_details.py
src/middlewared/middlewared/utils/gpu.py

This PR adds relevant middleware changes so GPU refs can be rendered and consumed appropriately.

NAS-130121 / 24.10 / Add support for GPU ref

---

src/middlewared/middlewared/plugins/apps/crud.py
src/middlewared/middlewared/plugins/apps/ix_apps/query.py

This PR adds changes to allow UI to retrieve app version details and config of apps when querying apps so it can actually allow edits.

NAS-130225 / 24.10 / Add changes to allow retrieving app version details and config when querying apps

---

tests/api2/test_pool_replace_disk.py

This one is still consistently failing but it's failing inside the `disk.get_instance` calls. This is because the VMs can be a bit unpredictable wrt to populating udev/disk/symlink info. To try and work-around this, I've wrapped these calls in a simple retry loop. Passing tests are [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1723/testReport/api2/test_pool_replace_disk/)

NAS-130295 / 24.10 / fix test_pool_replace_disk.py api failures

---

src/middlewared/middlewared/plugins/apps/app_scale.py
src/middlewared/middlewared/plugins/apps/crud.py
src/middlewared/middlewared/plugins/apps/ix_apps/path.py
src/middlewared/middlewared/plugins/apps/schema_action_context.py
src/middlewared/middlewared/plugins/apps/schema_normalization.py
src/middlewared/middlewared/plugins/kubernetes_to_docker/list_k8s_backups.py
src/middlewared/middlewared/plugins/kubernetes_to_docker/list_utils.py
src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py
src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate_config_utils.py
src/middlewared/middlewared/plugins/kubernetes_to_docker/secrets_utils.py
src/middlewared/middlewared/plugins/kubernetes_to_docker/utils.py
src/middlewared/middlewared/plugins/kubernetes_to_docker/yaml.py

This PR adds changes to allow migrating old apps to new apps.

NAS-130120 / 24.10 / Introduce a migration to allow migrating old apps to new apps

---

src/middlewared/middlewared/plugins/catalog/apps_details.py

Properly reflect a valid example of `catalog.apps` endpoint in return type documentation.

NAS-130328 / 24.10 / Fix catalog.apps example

---

src/middlewared/middlewared/plugins/apps/crud.py
src/middlewared/middlewared/plugins/apps/ix_apps/query.py

2 changes have been added here with both of them aiming to help assist the UI in showing relevant information for each app to the user without having to do additional parsing.

NAS-130382 / 24.10 / Separately report images being used by apps

---

src/middlewared/middlewared/logger.py
src/middlewared/middlewared/plugins/apps/ix_apps/docker/casing.py
src/middlewared/middlewared/plugins/apps/ix_apps/docker/images.py
src/middlewared/middlewared/plugins/apps/ix_apps/docker/query.py
src/middlewared/middlewared/plugins/apps/ix_apps/docker/utils.py
src/middlewared/middlewared/plugins/apps/logs.py
src/middlewared/middlewared/plugins/apps_images/client.py
src/middlewared/middlewared/plugins/apps_images/dockerhub_ratelimit.py
src/middlewared/middlewared/plugins/apps_images/images.py
src/middlewared/middlewared/plugins/apps_images/update_alerts.py
src/middlewared/middlewared/plugins/apps_images/utils.py
src/middlewared/middlewared/plugins/docker/state_management.py

This PR adds changes to introduce a service to manage docker images so we can query/pull/delete docker images and also see if there are updates available for some specific image.

NAS-130401 / 24.10 / Add a service to manage docker images

---

src/middlewared/middlewared/plugins/service.py

Generate audit trail when user changes service configuration to enable service on boot.

NAS-130425 / 24.10 / Audit service plugin configuration changes

---

src/middlewared/middlewared/plugins/smb.py

SCALE moved samba's passdb backend path out of the system dataset because of some edge cases where samba processes could prevent system dataset migration. This commit expands the list of samba-related directories that the middleware process manages.

NAS-130446 / 13.3 / Ensure required samba directories are created

---

src/middlewared/middlewared/plugins/account.py

Generate audit trail for when administrator account created.

NAS-130443 / 24.10 / Audit setup of administrator account

---

src/middlewared/middlewared/plugins/account_/2fa.py
src/middlewared/middlewared/plugins/auth_/2fa.py

Generate audit trail for changes related to two-factor authentication.

NAS-130441 / 24.10 / Add auditing for 2fa configuration

---

src/middlewared/middlewared/plugins/system_advanced/config.py
src/middlewared/middlewared/plugins/system_general/update.py

Generate audit trail for changes made via system.general and system.advanced.

NAS-130458 / 24.10 / Add auditing for system plugin changes

---

src/middlewared/middlewared/plugins/tunables.py

Generate an audit trail for users making changes to tunables.

NAS-130460 / 24.10 / Add auditing for tunable changes

---

docs/source/os/python.rst

Noticed an doc build error / mis-formatting without this.

NAS-130511 / 24.10 / Minor formatting fix

---

src/middlewared/middlewared/plugins/catalog/apps_details.py

Middleware was incorrectly app path.
Make sure correct path is reported for each app where the app actually lives.

NAS-130515 / 24.10 / Fix app location being reported

---

src/middlewared/middlewared/plugins/pool_/replace_disk.py

This endpoint was still using the `disk.get_unused` endpoint. This was changed back in https://github.com/truenas/middleware/pull/13802. The changes in the linked PR add clarity to "in use" and "unused" disks. The problem by using `disk.get_unused` is that this doesn't take into account if a disk isn't "in use" but has a zpool label still written to it (i.e. the disk is part of an exported zpool).
I've remedied this situation but have also added another safety belt that checks to make sure the disk that is being provided isn't also part of an _imported_ zpool.

NAS-130442 / 24.10 / fix pool.replace when disk is part of exported zpool

---

src/middlewared/middlewared/plugins/apps/compose_utils.py
src/middlewared/middlewared/plugins/apps/crud.py
src/middlewared/middlewared/plugins/apps/ix_apps/query.py
src/middlewared/middlewared/plugins/apps/ix_apps/utils.py
src/middlewared/middlewared/plugins/apps/pull_images.py
src/middlewared/middlewared/plugins/apps/upgrade.py
src/middlewared/middlewared/plugins/apps_images/images.py
src/middlewared/middlewared/plugins/apps_images/update_alerts.py

Logic has been added which allows UI/consumers to see if an app has images which are outdated and similarly pull images for that app if that is the case. For custom apps, modification has been done so that we mark app as ready for upgrade if it has container images which need to be updated and similar `app.upgrade` has been modified to account for that change.

NAS-130536 / 24.10 / Factor in container images as well when doing app upgrades

---

src/middlewared/middlewared/plugins/kubernetes_to_docker/trigger_migration.py

This PR adds changes to automatically trigger migration for old apps to new apps.

NAS-130448 / 24.10 / Add logic to automatically trigger migration for old apps to new apps

---

src/middlewared/middlewared/plugins/apps/crud.py

If an app had been stopped and then modified, middleware will start the app automatically.
Make sure only those apps are re-deployed which are not in stopped state when editing an app.

NAS-130555 / 24.10 / Do not start a stopped app on edits

---

src/middlewared/middlewared/plugins/smb_/util_net_conf.py

Add missing import of `MatchNotFound`
Also remove some unused imports.

NAS-130575 / 25.04 / Add missing import of MatchNotFound

---

src/middlewared/middlewared/alembic/versions/24.10/2024-08-12_15-53_discoveryauth.py

PR was overtaken inflight.  Tweak revision.
- https://github.com/truenas/middleware/pull/14203
- https://github.com/truenas/middleware/pull/14198

NAS-130592 / 24.10-RC.1 / Revise migration as PR was overtaken inflight

---

src/middlewared/middlewared/plugins/directoryservices_/ipa_join_mixin.py
src/middlewared/middlewared/plugins/ldap.py

It's theoretically possible that we can obtain an intial kerberos ticket via some temporary krb5.conf overrides but then fail to fully configure because IPA server does not have DNS properly configured. In this case we should generate an alert but continue working.

NAS-130576 / 25.04 / Add error handling for kerberos errors in IPA join job

---

src/middlewared/middlewared/plugins/directoryservices_/ipa_join_mixin.py
src/middlewared/middlewared/plugins/ldap.py

It's theoretically possible that we can obtain an intial kerberos ticket via some temporary krb5.conf overrides but then fail to fully configure because IPA server does not have DNS properly configured. In this case we should generate an alert but continue working.
Original PR: https://github.com/truenas/middleware/pull/14206
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130576

NAS-130576 / 24.10-RC.1 / Add error handling for kerberos errors in IPA join job (by anodos325)

---

src/middlewared/middlewared/plugins/directoryservices_/ipa_join_mixin.py
src/middlewared/middlewared/plugins/ldap.py

It's theoretically possible that we can obtain an intial kerberos ticket via some temporary krb5.conf overrides but then fail to fully configure because IPA server does not have DNS properly configured. In this case we should generate an alert but continue working.
Original PR: https://github.com/truenas/middleware/pull/14206
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130576

NAS-130576 / 24.10-BETA.1 / Add error handling for kerberos errors in IPA join job (by anodos325)

---

src/middlewared/middlewared/migration/0011_catalog_community_train.py
src/middlewared/middlewared/plugins/catalog/utils.py

This commit adds changes to add community train to preferred trains by default. Also it makes sure that enterprise users have correct trains setup.

NAS-130670 / 25.04 / Add community train to preferred trains by default

---

src/middlewared/middlewared/plugins/interface/link_address.py

…hould do this individually
Original PR: https://github.com/truenas/middleware/pull/14256
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130622

NAS-130622 / 24.10-BETA.1 / Do not propagate network interface renames between nodes, each node s… (by themylogin)

---

src/middlewared/middlewared/plugins/interface/link_address.py

…hould do this individually
Original PR: https://github.com/truenas/middleware/pull/14256
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130622

NAS-130622 / 24.10-RC.1 / Do not propagate network interface renames between nodes, each node s… (by themylogin)

---

src/middlewared/middlewared/plugins/apps/schema_action_context.py

This commit fixes ix volume creation props.

NAS-130705 / 25.04 / Fix ix volume creation properties

---

src/middlewared/middlewared/plugins/apps/schema_action_context.py

This commit fixes ix volume creation props.
Original PR: https://github.com/truenas/middleware/pull/14272
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130705

NAS-130705 / 24.10-RC.1 / Fix ix volume creation properties (by sonicaj)

---

src/middlewared/middlewared/plugins/zfs_/zfs_events.py

`ZfsDeadmanAlertClass` was removed by commit e70e6b53b62cccd6631fca0d022061404f4ec7e5 a long time ago.

NAS-130728 / 25.04 / Remove deadman alert creation logic

---

src/middlewared/middlewared/plugins/zfs_/zfs_events.py

`ZfsDeadmanAlertClass` was removed by commit e70e6b53b62cccd6631fca0d022061404f4ec7e5 a long time ago.
Original PR: https://github.com/truenas/middleware/pull/14291
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130728

NAS-130728 / 24.10-RC.1 / Remove deadman alert creation logic (by themylogin)

---

src/middlewared/middlewared/plugins/docker/update.py

We were not validating if pool specified by user actually exists for apps.

NAS-130751 / 25.04 / Make sure pool specified by user actually exists for apps

---

src/middlewared/middlewared/plugins/docker/update.py

We were not validating if pool specified by user actually exists for apps.
Original PR: https://github.com/truenas/middleware/pull/14304
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130751

NAS-130751 / 24.10-BETA.1 / Make sure pool specified by user actually exists for apps (by Qubad786)

---

src/middlewared/middlewared/plugins/docker/update.py

We were not validating if pool specified by user actually exists for apps.
Original PR: https://github.com/truenas/middleware/pull/14304
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130751

NAS-130751 / 24.10-RC.1 / Make sure pool specified by user actually exists for apps (by Qubad786)

---

tests/api2/test_425_smb_protocol.py

Newer MacOS clients may rename files on SMB shares via names that are not returned in the directory listing it requested. For example if source of rename is foo and target is Foo, it may try to rename Foo to Foo resulting in hitting an optimization in samba that turns this rename into a no-op. This commit expands tests specifically to cover this case.
Original PR: https://github.com/truenas/middleware/pull/14299
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130743

NAS-130743 / 24.10-RC.1 / Add test coverage for MacOS-style SMB renames (by anodos325)

---

src/middlewared/middlewared/utils/network_/procfs.py

The `read_proc_net` function does not generate correct addresses and does not support both big-endian and little-endian systems.
Updated routine generates correct ipv6 and ipv4 addresses from the hex values in /proc/net/tcp[6]

NAS-130765 / 25.04 / Fix read_proc_net.

---

src/middlewared/middlewared/utils/network_/procfs.py

The `read_proc_net` function does not generate correct addresses and does not support both big-endian and little-endian systems.
Updated routine generates correct ipv6 and ipv4 addresses from the hex values in /proc/net/tcp[6]
Original PR: https://github.com/truenas/middleware/pull/14316
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130765

NAS-130765 / 24.10-RC.1 / Fix read_proc_net. (by mgrimesix)

---

src/middlewared/middlewared/alert/source/auth.py

This commit addresses feedback from the documentation team to improve directions to end-user on how to resolve this alert.

NAS-130792 / 25.04 / Improve alert for admin account usage

---

src/middlewared/middlewared/plugins/apps/logs.py

Middleware should allow to retrieve logs of apps which are in deploying state.

NAS-130788 / 25.04 / Allow retrieving logs of apps in deploying state

---

src/middlewared/middlewared/alert/source/auth.py

This commit addresses feedback from the documentation team to improve directions to end-user on how to resolve this alert.
Original PR: https://github.com/truenas/middleware/pull/14332
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130792

NAS-130792 / 24.10-RC.1 / Improve alert for admin account usage (by anodos325)

---

src/middlewared/middlewared/job.py
src/middlewared/middlewared/service/decorators.py
tests/api2/test_job_lock.py

…se the same lock
Original PR: https://github.com/truenas/middleware/pull/14319
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130747

NAS-130747 / 24.10-RC.1 / Do not allow unprivileged users to see other users queued jobs that u… (by themylogin)

---

src/middlewared/middlewared/alert/source/volume_status.py

It seems that we can't rely solely on ZFS events for such an important matter.

NAS-130820 / 25.04 / Invalidate pool status alerts when pool states change

---

src/middlewared/middlewared/alert/source/volume_status.py

It seems that we can't rely solely on ZFS events for such an important matter.
Original PR: https://github.com/truenas/middleware/pull/14348
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130820

NAS-130820 / 24.10-BETA.1 / Invalidate pool status alerts when pool states change (by themylogin)

---

src/middlewared/middlewared/alert/source/volume_status.py

It seems that we can't rely solely on ZFS events for such an important matter.
Original PR: https://github.com/truenas/middleware/pull/14348
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130820

NAS-130820 / 24.10-RC.1 / Invalidate pool status alerts when pool states change (by themylogin)

---

src/middlewared/middlewared/plugins/failover_/event.py

Extract some iSCSI ALUA cleanup code into `iscsi_cleanup_alua_state` and catch exceptions.  Further, use the operations that succeeded/failed to act as gatekeepers for later steps.
----
iSCSI tests passed during [CI run](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/330/).

NAS-130847 / 25.04 / Make vrrp_master more robust wrt iSCSI ALUA on newly booted node

---

tests/api2/test_apps_images_roles.py
tests/api2/test_apps_roles.py
tests/api2/test_catalog_roles.py
tests/api2/test_docker_roles.py

This commit adds an integration tests to validate roles for apps plugin.

NAS-130882 / 25.04 / Add tests to verify roles for apps

---

src/middlewared/middlewared/service/decorators.py

Recent change was made in recent PR (#14319).  Update docs to match.
Original PR: https://github.com/truenas/middleware/pull/14388
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130888

NAS-130888 / 24.10-RC.1 / Update job decorator docstring to match recent code change (by bmeagherix)

---

src/middlewared/middlewared/plugins/failover_/event.py

Extract some iSCSI ALUA cleanup code into `iscsi_cleanup_alua_state` and catch exceptions.  Further, use the operations that succeeded/failed to act as gatekeepers for later steps.
----
iSCSI tests passed during [CI run](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/330/).
Original PR: https://github.com/truenas/middleware/pull/14364
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130847
Original PR: https://github.com/truenas/middleware/pull/14366
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130847

NAS-130847 / 24.04.2.1 / Make vrrp_master more robust wrt iSCSI ALUA on newly booted node (by bmeagherix) (by bugclerk)

---

src/middlewared/middlewared/job.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/pool_/pool.py
tests/api2/test_audit_pool.py

git cherry-pick -x 8b46e2ec8d8152c1f6c2b5041dc201b5fc5eeb65
git cherry-pick -x 10a978c789a5a4034beef02af354474664e48e3b
Original PR: https://github.com/truenas/middleware/pull/14357
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130438

NAS-130438 / 24.10-RC.1 / Jobs audit. `pool.update` audit (by themylogin)

---

src/middlewared/middlewared/alembic/versions/24.10/2024-08-30_20-33_docker_addr_pool.py
src/middlewared/middlewared/alembic/versions/24.10/2024-09-03_20-33_docker_addr_pool.py
src/middlewared/middlewared/etc_files/docker/daemon.json.py
src/middlewared/middlewared/plugins/docker/update.py
src/middlewared/middlewared/plugins/docker/validation_utils.py
src/middlewared/middlewared/pytest/unit/plugins/docker/test_docker_address_pools_validtaion.py

This PR adds changes to make address pools of docker service configurable so user can choose whatever address pools he/she wishes to consume for docker containers.

NAS-130981 / 24.10-RC.1 / Allow specifying custom address pools for docker service

---

src/middlewared/middlewared/alembic/versions/24.10/2024-08-30_20-33_docker_addr_pool.py
src/middlewared/middlewared/alembic/versions/24.10/2024-09-03_20-33_docker_addr_pool.py
src/middlewared/middlewared/alembic/versions/25.04/2024-09-04_00-35_merge.py
src/middlewared/middlewared/etc_files/docker/daemon.json.py
src/middlewared/middlewared/plugins/docker/update.py
src/middlewared/middlewared/plugins/docker/validation_utils.py
src/middlewared/middlewared/pytest/unit/plugins/docker/test_docker_address_pools_validtaion.py

This PR adds changes to make address pools of docker service configurable so user can choose whatever address pools he/she wishes to consume for docker containers.
Original PR: https://github.com/truenas/middleware/pull/14408
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130981

NAS-130981 / 25.04 / Allow specifying custom address pools for docker service (by sonicaj)

---

tests/api2/test_account.py

Forgot to removed an unused pytest import

NAS-130987 / 25.04 / Removed unused import

---

tests/api2/test_070_alertservice.py

[Passing test](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/415/console)

NAS-130927 / 25.04 / Remove REST calls in test_070_alertservice

---

tests/api2/test_audit_audit.py

[Passing test](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/432/console)

NAS-130917 / 25.04 / Remove REST calls from test_audit_audit

---

src/middlewared/middlewared/alembic/versions/24.10/2024-09-04_19-40_add_to_trust_store_field_for_cert.py
src/middlewared/middlewared/etc_files/generate_ssl_certs.py
src/middlewared/middlewared/plugins/crypto_/cert_entry.py
src/middlewared/middlewared/plugins/crypto_/certificate_authorities.py
src/middlewared/middlewared/plugins/crypto_/certificates.py

This PR adds changes to allow adding certificates to trusted store of the system.

NAS-129859 / 24.10-RC.1 / Allow adding certificates to system's trusted store

---

src/middlewared/middlewared/alembic/versions/24.10/2024-09-04_19-40_add_to_trust_store_field_for_cert.py
src/middlewared/middlewared/alembic/versions/25.04/2024-09-05_22-58_merge.py
src/middlewared/middlewared/etc_files/generate_ssl_certs.py
src/middlewared/middlewared/plugins/crypto_/cert_entry.py
src/middlewared/middlewared/plugins/crypto_/certificate_authorities.py
src/middlewared/middlewared/plugins/crypto_/certificates.py

This PR adds changes to allow adding certificates to trusted store of the system.
Original PR: https://github.com/truenas/middleware/pull/14429
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129859

NAS-129859 / 25.04 / Allow adding certificates to system's trusted store (by sonicaj)

---

tests/api2/test_005_interface.py

This test is only valid on HA systems and will fail on single node systems. Mark it accordingly. Format the file while I'm here as well.

NAS-131039 / 25.04 / fix test_005_interface:test_004 failing on single node tests

---

src/middlewared/middlewared/plugins/crypto_/certificates.py
tests/api2/test_certs.py

Certificate integration tests are failing as a new field was added to certs which is not applicable for CSRs.
Make sure proper validation is done when the trusted store field is supplied for CSRs and introduce a new integration test to account for the change.
Original PR: https://github.com/truenas/middleware/pull/14451
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131070

NAS-131070 / 24.10-RC.1 / Fix certificate integration test (by Qubad786)

---

src/middlewared/middlewared/alert/source/applications.py
src/middlewared/middlewared/logger.py
src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py

This PR adds changes to have a separate log file for app migrations and issue an alert as well if there are some apps which fail to migrate.

NAS-131078 / 25.04 / Separate logging for app migration

---

src/middlewared/middlewared/alert/source/applications.py
src/middlewared/middlewared/logger.py
src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py

This PR adds changes to have a separate log file for app migrations and issue an alert as well if there are some apps which fail to migrate.
Original PR: https://github.com/truenas/middleware/pull/14459
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131078

NAS-131078 / 24.10-RC.1 / Separate logging for app migration (by sonicaj)

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
src/middlewared/middlewared/plugins/enclosure_/enums.py
src/middlewared/middlewared/utils/license.py

This adds ES60G3 support. Tested on real hardware provided by platform team.

NAS-131096 / 25.04 / add ES60G3 support

---

src/middlewared/middlewared/plugins/apps/crud.py

This commit adds changes to retrieve custom app version detail template as there really isn't a set of questions etc here which are to be catered to.

NAS-131129 / 25.04 / Do not error out when schema for custom app is desired

---

src/middlewared/middlewared/plugins/apps/crud.py

This commit adds changes to retrieve custom app version detail template as there really isn't a set of questions etc here which are to be catered to.
Original PR: https://github.com/truenas/middleware/pull/14496
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131129

NAS-131129 / 24.10-RC.1 / Do not error out when schema for custom app is desired (by sonicaj)

---

tests/api2/test_audit_nfs.py

[Passing tests](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/602/console)!

NAS-130929 / 25.04 / Removed REST from test_audit_nfs

---

src/middlewared/middlewared/plugins/config.py
src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/sysdataset.py

Fix breakage introduced in a recent PR (#14546).

NAS-131394 / 25.04 / Fix call_remote parameter breakage wrt system.reboot

---

tests/unit/test_fenced.py

Cf. https://github.com/truenas/py-fenced/pull/54

NAS-131419 / 25.04 / add more fenced tests

---

src/middlewared/middlewared/alert/source/enclosure_status.py

Not sure how my local flake8 checks didn't pick this one up.

NAS-131448 / 25.04 / fix typo in enclosure alert

---

src/middlewared/middlewared/plugins/disk_/format.py

I was asked to investigate a GPT partition formatting issue and ended up discovering this problem. Looking through libparrted source, I discovered it keeps a global cache that can cause problems. The gist is that we need to remove the device from the cache so that it forces libparted to probe the device and see reality. Otherwise, there is possibility it sees invalid data (since devices can be overprovisioned) and cause IO operation failures. Traceback was
```
Invalid argument during seek for write on /dev/nvme11n1
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 208, in call_method
result = await self.middleware.call_with_audit(message['method'], serviceobj, methodobj, params, self) …
```

NAS-131564 / 25.04 / fix libparted IO operation on disk format

---

src/middlewared/middlewared/plugins/disk_/format.py

I was asked to investigate a GPT partition formatting issue and ended up discovering this problem. Looking through libparrted source, I discovered it keeps a global cache that can cause problems. The gist is that we need to remove the device from the cache so that it forces libparted to probe the device and see reality. Otherwise, there is possibility it sees invalid data (since devices can be overprovisioned) and cause IO operation failures. Traceback was
```
Invalid argument during seek for write on /dev/nvme11n1
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 208, in call_method
result = await self.middleware.call_with_audit(message['method'], serviceobj, methodobj, params, self) …
```

NAS-131564 / 24.10.0 / fix libparted IO operation on disk format (by yocalebo)

---

src/middlewared/middlewared/plugins/disk_/format.py

I was asked to investigate a GPT partition formatting issue and ended up discovering this problem. Looking through libparrted source, I discovered it keeps a global cache that can cause problems. The gist is that we need to remove the device from the cache so that it forces libparted to probe the device and see reality. Otherwise, there is possibility it sees invalid data (since devices can be overprovisioned) and cause IO operation failures. Traceback was
```
Invalid argument during seek for write on /dev/nvme11n1
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 208, in call_method
result = await self.middleware.call_with_audit(message['method'], serviceobj, methodobj, params, self) …
```

NAS-131564 / 24.10-RC.2 / fix libparted IO operation on disk format (by yocalebo)

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/acme_protocol.py
src/middlewared/middlewared/plugins/acme_protocol.py
src/middlewared/middlewared/plugins/acme_protocol_/schema.py

Passing: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1132/

NAS-131393 / 25.04 / Convert acme_protocol to new api style

---

src/middlewared/middlewared/plugins/rdma/constants.py
src/middlewared/middlewared/plugins/rdma/rdma.py

Add extensible private API to determine which RDMA services are supported.
Will be enhanced later when iSER is being worked on.

NAS-131603 / 25.04 / Add private API rdma.capable_services

---

src/middlewared/middlewared/plugins/vm/vms.py

When a VM's name is changed, its NVRAM (non-volatile memory) is not being preserved, which causes some VMs to fail to boot after the name change.
Ensure the NVRAM state is persisted even after the VM name is updated, allowing VMs to boot correctly post name change.

NAS-131605 / 25.04 / Make sure NVRAM file of VM is preserved when vm name is changed

---

src/middlewared/middlewared/plugins/vm/vms.py

When a VM's name is changed, its NVRAM (non-volatile memory) is not being preserved, which causes some VMs to fail to boot after the name change.
Ensure the NVRAM state is persisted even after the VM name is updated, allowing VMs to boot correctly post name change.
Original PR: https://github.com/truenas/middleware/pull/14635
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131605

NAS-131605 / 24.10.0 / Make sure NVRAM file of VM is preserved when vm name is changed (by Qubad786)

---

src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py

This commit improves error handling so we more appropriately clarify that an app cannot be migrated because it is using encrypted ix-volumes and we cannot migrate them to unencrypted datasets.

NAS-131561 / 25.04 / Appropriately clarify app can't be migrated because of encrypted ix-volumes

---

src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py

This commit improves error handling so we more appropriately clarify that an app cannot be migrated because it is using encrypted ix-volumes and we cannot migrate them to unencrypted datasets.
Original PR: https://github.com/truenas/middleware/pull/14645
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131561

NAS-131561 / 24.10.0 / Appropriately clarify app can't be migrated because of encrypted ix-volumes (by sonicaj)

---

src/freenas/usr/local/share/truenas/eula.html
src/middlewared/middlewared/plugins/truenas.py

Add a target attribute to the hyper-links in the EULA so that clicking on them opens them in a new tab or window.

NAS-128106 / 25.04 / open EULA in new tab

---

src/middlewared/middlewared/plugins/interface/configure.py

On an HA system, this is preventing IPv6 addresses from being configured on the interface because there is a race for when these link-local addresses are being added (and show up) to the OS and when keepalived (VIP service) configures the IPv6 VIP.
Doing some research, this logic was added back in 2020 here: https://github.com/truenas/middleware/pull/5901. The simple fact is that the kernel already provides EUI-64 generate link-local IPv6 addresses [Cf addr_gen_mode](https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt) Those changes were added in SCALE's infancy and so we probably glossed over the kernel's capability and just tried to make ourselves "feature parity". Anyways, we can remove this logic altogether and remove this race condition.
Furthermore, I've made changes …

NAS-131780 / 25.04 / remove our hand-rolled EUI-64 link-local addresses

---

src/middlewared/middlewared/plugins/interface/configure.py

On an HA system, this is preventing IPv6 addresses from being configured on the interface because there is a race for when these link-local addresses are being added (and show up) to the OS and when keepalived (VIP service) configures the IPv6 VIP.
Doing some research, this logic was added back in 2020 here: https://github.com/truenas/middleware/pull/5901. The simple fact is that the kernel already provides EUI-64 generate link-local IPv6 addresses [Cf addr_gen_mode](https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt) Those changes were added in SCALE's infancy and so we probably glossed over the kernel's capability and just tried to make ourselves "feature parity". Anyways, we can remove this logic altogether and remove this race condition.
Furthermore, I've made changes …

NAS-131780 / 24.10.0 / remove our hand-rolled EUI-64 link-local addresses (by yocalebo)

---

src/middlewared/middlewared/plugins/interface/configure.py

On an HA system, this is preventing IPv6 addresses from being configured on the interface because there is a race for when these link-local addresses are being added (and show up) to the OS and when keepalived (VIP service) configures the IPv6 VIP.
Doing some research, this logic was added back in 2020 here: https://github.com/truenas/middleware/pull/5901. The simple fact is that the kernel already provides EUI-64 generate link-local IPv6 addresses [Cf addr_gen_mode](https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt) Those changes were added in SCALE's infancy and so we probably glossed over the kernel's capability and just tried to make ourselves "feature parity". Anyways, we can remove this logic altogether and remove this race condition.
Furthermore, I've made changes …

NAS-131780 / 24.10.1 / remove our hand-rolled EUI-64 link-local addresses (by yocalebo)

---

src/middlewared/middlewared/main.py

Invalid calls were possible and this created a confusion https://ixsystems.atlassian.net/browse/NAS-131689

NAS-131782 / 25.04 / Check `params` type

---

src/middlewared/middlewared/pytest/unit/plugins/apps/test_construct_schema.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_get_latest_version.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_get_list_item_from_value.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_get_normalized_gpus.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_get_schema.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_normalize_CA.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_normalize_acl.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_normalize_and_validate.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_normalize_certificate.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_normalize_gpu_options.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_normalize_ix_volumes.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_normalize_questions.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_normalize_values.py

This PR adds unit tests for apps plugin covering various cases like constructing schema and normalizing various aspects of special schema refs.

NAS-131882 / 25.04 / Add unit tests for apps plugin

---

src/middlewared/middlewared/plugins/apps/ix_apps/path.py
src/middlewared/middlewared/plugins/apps/ix_volumes.py

This PR adds changes to expose an endpoint which tells if ix-volumes for an app exist or not so UI can conditionally show boolean flag when app is being deleted.
We want to have an ix-volume query/delete service in place for FT and the basics for that have been added in this ticket as well.

NAS-131714 / 25.04 / Add an endpoint which UI can use to conditionally show boolean flag for removing ix-volumes on app deletion

---

src/middlewared/middlewared/plugins/cloud_sync.py
src/middlewared/middlewared/rclone/base.py
src/middlewared/middlewared/rclone/remote/b2.py

The original PR does not fix the original issue due to my mistake. Reverting it.

NAS-131902 / 25.04 / Ensure `--multi-thread-cutoff` is at least twice the size of `chunk_size` for B2

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/static_route.py
src/middlewared/middlewared/plugins/network_/static_routes.py
tests/api2/test_staticroutes.py

Converts the staticroute CRUD endpoints to the new api paradigm.

NAS-131974 / 25.04 / convert staticroute.* plugin to new api decorator

---

src/middlewared/middlewared/plugins/system_advanced/serial.py

… not taking effect immediately.
Original PR: https://github.com/truenas/middleware/pull/14770
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131976

NAS-131976 / 24.10.1 / Fix toggling the "Show Text Console without Password Prompt" box does… (by themylogin)

---

src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/fseries_drive_identify.py

This is an edge-case that we need to try and work-around until OEM can give definitive answer/fix.

NAS-131863 / 25.04 / fix edge-case w/ drive ident on f-series

---

src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/fseries_drive_identify.py

This is an edge-case that we need to try and work-around until OEM can give definitive answer/fix.
Original PR: https://github.com/truenas/middleware/pull/14773
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131863

NAS-131863 / 24.10.0 / fix edge-case w/ drive ident on f-series (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/fseries_drive_identify.py

This is an edge-case that we need to try and work-around until OEM can give definitive answer/fix.
Original PR: https://github.com/truenas/middleware/pull/14773
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131863

NAS-131863 / 24.10.1 / fix edge-case w/ drive ident on f-series (by yocalebo)

---

src/middlewared/middlewared/api/v25_04_0/virt.py
src/middlewared/middlewared/plugins/virt/global.py
src/middlewared/middlewared/plugins/virt/instance.py

- Add image details
- virt.global.config event
- make sure "autostart" is always a boolean

NAS-130523 / 25.04 / Few fixes and improvements requested by UI team

---

tests/api2/test_190_filesystem.py

Passing tests: [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1531/testReport/api2/test_190_filesystem/)

NAS-130926 / 25.04 / remove REST from test_190

---

src/middlewared/middlewared/api/base/model.py
src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/common.py
src/middlewared/middlewared/api/v25_04_0/system_ntpserver.py
src/middlewared/middlewared/plugins/ntp.py
src/middlewared/middlewared/plugins/smb_/passdb.py
src/middlewared/middlewared/service/__init__.py
src/middlewared/middlewared/service/crud_service.py
src/middlewared/middlewared/service/decorators.py

This commit converts ntp.py to use new api_method as well as introducing and using a new `filterable_api_method` decorator for non-CRUD methods that were using legacy `filterable` decorator.

NAS-132045 / 25.04 / Convert NTP server plugin to api_method

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/truenas.py
src/middlewared/middlewared/plugins/truenas.py

I've tested all these endpoints by hand, all work without throwing errors!

NAS-132075 / 25.04 / Convert truenas.* endpoints to new API style

---

src/middlewared/middlewared/plugins/account.py

The schema is handled automatically by CRUDService. This commit also
removes usage of no_auth_required and no_authz_required decorators

NAS-132111 / 25.04 / Clean up filterable for user.query and group.query

---

src/middlewared/middlewared/api/base/types/__init__.py
src/middlewared/middlewared/api/base/types/filesystem.py
src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/filesystem.py
src/middlewared/middlewared/plugins/filesystem_/acl.py
tests/api2/test_190_filesystem.py
tests/api2/test_427_smb_acl.py

This contains mostly boiler-plate code with the addition of the following minor API enhancement:
* filesystem.chown and filesystem.setperm now allow specifying user or group by name.

NAS-132101 / 25.04 / Convert filesystem.chown and filesystem.setperm to api_method

---

src/middlewared/middlewared/plugins/apps/ix_apps/query.py

git cherry-pick -x de133bc1ee756622f120cd0d2ce35a1c3460ad92
git cherry-pick -x 651f3ff96ba7ba61732672dbb8969598eef85e69
This PR adds changes to account for UI team request to retrieve latest versions available for an app so that they don't have to make a new call for that. This is not expensive for middleware as we already have that information and it just needs to be exposed.
Original PR: https://github.com/truenas/middleware/pull/14818
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131983

NAS-131983 / 24.10.1 / Retrieve latest version of an app available when querying apps for UI (by sonicaj)

---

tests/api2/test_cloud_backup.py

https://github.com/truenas/middleware/pull/14782 changed the format of cloud backup task logs which broke one of our cloud backup tests.
Passing here: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1628/

NAS-132156 / 25.04 / Fix cloud backup test

---

tests/api2/test_cloud_backup.py

https://github.com/truenas/middleware/pull/14782 changed the format of cloud backup task logs which broke one of our cloud backup tests.
Passing here: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1628/
Original PR: https://github.com/truenas/middleware/pull/14838
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132156

NAS-132156 / 24.10.1 / Fix cloud backup test (by creatorcary)

---

src/middlewared/middlewared/plugins/docker/update.py

git cherry-pick -x 22ef7bc592b3e31f9682deeed7a01c728b266c6e
git cherry-pick -x 4cb22fa07ee4d051e80aec69e6c6fe9b6980af34
…lacks_nvidia_drivers`
Original PR: https://github.com/truenas/middleware/pull/14827
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132070

NAS-132070 / 24.10.1 / `docker.nvidia_status` method and event source to substitude `docker.… (by themylogin)

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/rdma_interface.py
src/middlewared/middlewared/plugins/rdma/interface/crud.py

Simple conversion to new api_method.

NAS-132158 / 25.04 / Convert rdma.interface to new api_method

---

src/middlewared/middlewared/plugins/network.py

This was brought to my attention by support team because a particular customer had run into this scenario. We allow "empty" bond configurations because, most often times, the user will put vlans on top of it. However, some users will mark the bond interface as critical for failover and will NOT mark the child interfaces critical for failover. This paints the false impression that when the bond goes down, a failover event will be generated. This is not the case because we act upon network events for generating failover events. If the bond has no IP address, then it will not generate a failover event and because the child interface isn't marked critical for failover, a failover will not take place.

NAS-132187 / 25.04 / prevent empty critical bond interfaces on HA

---

src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/update_/install.py

Utilize the much more performant boot environment plugin introduced in https://github.com/truenas/middleware/pull/14865

NAS-132302 / 25.04 / remove usage of legacy bootenv calls

---

src/middlewared/middlewared/plugins/network.py

There is no reason to show USB based NICs on most of our platforms. Currently, the only time a USB NIC shows up is on certain platforms when someone accesses IPMI via a browser session. Discussed with platform team but we can safely ignore these type of NICs universally. This ignores USB based NICs on all platforms that we sell with the exception of the MINI product line. If this isn't hardware we sell, the usb based nics will show up without issue.

NAS-132271 / 25.04 / ignore USB NICs on enterprise platforms

---

tests/README.md

It was pointed out to me that some have actually referenced this file (when they initially started) to get an idea of how to write/run tests. Let's improve this read me file with modern practices and bring it up to reality.

NAS-132305 / 25.04 / Fix and improve tests/README.md

---

src/middlewared/middlewared/plugins/apps/upgrade.py

This commit fixes an issue where middleware was sending an outdated event on app upgrade where the event payload showed that app upgrade is still available which was although not true later.
Original PR: https://github.com/truenas/middleware/pull/14893
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131849

NAS-131849 / 24.10.1 / Make sure middleware sends latest app configuratio on upgrade event (by sonicaj)

---

src/middlewared/middlewared/api/base/decorator.py
src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/netdata.py
src/middlewared/middlewared/api/v25_04_0/reporting.py
src/middlewared/middlewared/plugins/reporting/graphs.py
src/middlewared/middlewared/plugins/reporting/netdata_configure.py
src/middlewared/middlewared/plugins/reporting/netdata_web.py
src/middlewared/middlewared/plugins/reporting/rest.py
src/middlewared/middlewared/plugins/reporting/update.py
src/middlewared/middlewared/service/decorators.py

This PR converts reporting service to new api style and also extends `cli_private` functionality to `api_method` to make it easier to mark methods as private from the CLI.

NAS-131951 / 25.04 / Convert reporting service to new api style

---

tests/api2/test_cloud_backup.py

Passed: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1750/

NAS-132352 / 25.04 / Fix new cloud backup test

---

tests/api2/test_cloud_backup.py

Passed: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1750/
Original PR: https://github.com/truenas/middleware/pull/14905
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132352

NAS-132352 / 24.10.1 / Fix new cloud backup test (by creatorcary)

---

src/middlewared/middlewared/plugins/virt/instance.py
src/middlewared/middlewared/plugins/virt/instance_device.py
tests/api2/test_virt_002_instance.py

NAS-132417 / 25.04 / Fix creating instance with multiple devices without names

---

src/middlewared/middlewared/plugins/system_general/update.py

A user tries to update the timezone settings on the general page and they get this traceback....
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 110, in query
apps = list_apps(available_apps_mapping, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/ix_apps/query.py", line 126, in list_apps
with os.scandir(get_app_parent_config_path()) as scan:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/.ix-apps/app_configs'
```
That's mildly infuriating. But looking at this, I found we're doing really inefficient look-ups here. However, for the sake of this being back ported to 24.10.1, I've kept changes to a minimum. The solution is to not …

NAS-132407 / 25.04 / be smarter about checking ports in use

---

src/middlewared/middlewared/plugins/system_general/update.py

A user tries to update the timezone settings on the general page and they get this traceback....
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 110, in query
apps = list_apps(available_apps_mapping, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/ix_apps/query.py", line 126, in list_apps
with os.scandir(get_app_parent_config_path()) as scan:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/.ix-apps/app_configs'
```
That's mildly infuriating. But looking at this, I found we're doing really inefficient look-ups here. However, for the sake of this being back ported to 24.10.1, I've kept changes to a minimum. The solution is to not …

NAS-132407 / 24.10.1 / be smarter about checking ports in use (by yocalebo)

---

src/middlewared/middlewared/plugins/directoryservices_/activedirectory_join_mixin.py

If we're in the process of joining active directory we will already have a kerberos ticket available and so can skip the step where we restart the kerberos service. This adds additional hardening against imcomplete sysvol replication.

NAS-132248 / 25.04 / Avoid potentially unnecessary kerberos.start when activating AD

---

src/middlewared/middlewared/plugins/directoryservices_/activedirectory_join_mixin.py

If we're in the process of joining active directory we will already have a kerberos ticket available and so can skip the step where we restart the kerberos service. This adds additional hardening against imcomplete sysvol replication.
Original PR: https://github.com/truenas/middleware/pull/14909
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132248

NAS-132248 / 24.10.1 / Avoid potentially unnecessary kerberos.start when activating AD (by anodos325)

---

src/middlewared/middlewared/alembic/versions/25.04/2024-11-12_09-09_reporting_exporters.py
src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/reporting_exporters.py
src/middlewared/middlewared/etc_files/netdata/exporting.conf.mako
src/middlewared/middlewared/plugins/reporting/export.py
src/middlewared/middlewared/plugins/reporting/exporters/base.py
src/middlewared/middlewared/plugins/reporting/exporters/graphite.py

This PR converts reporting exporter service to new api style.

NAS-132340 / 25.04 / Move reporting exporters service to new api style

---

src/middlewared/middlewared/plugins/acme_protocol_/acme_svc.py
src/middlewared/middlewared/plugins/acme_protocol_/client_utils.py
src/middlewared/middlewared/plugins/acme_protocol_/issue_cert.py

This PR adds some ACME logic refactors to allow us to call cert issuance logic directly minimizing existing dependencies.

NAS-132457 / 25.04 / Minor ACME logic refactors

---

tests/api2/test_428_smb_rpc.py

Passing tests here: [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1807/testReport/api2/test_428_smb_rpc/)

NAS-130909 / 25.04 / remove REST from test_428

---

src/freenas/usr/local/libexec/collectd_alert.py
src/middlewared/middlewared/alert/source/collectd.py
src/middlewared/middlewared/alert/source/vmware_login.py
src/middlewared/middlewared/plugins/mail.py

A vulnerability involving python deserialization, CVE-2020-22083, was found and resolved.

NAS-132268 / 13.3 / Do not use pickle module unnecessarily

---

tests/api2/test_425_smb_protocol.py

Passing tests here: [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1817/testReport/api2/test_425_smb_protocol/)

NAS-130911 / 25.04 / remove REST from test_425

---

tests/api2/test_541_vm.py

Catching up with some more `dtype` attr changes in vm plugin.

NAS-132539 / 25.04 / Fix vm integration test

---

src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/mail.py

(cherry picked from commit bc3bd3a03beacd0f62e90f046971c5802b103a9a)

NAS-132268 / 13.0-U6.3 / fix mail.queue regression (#14961)

---

src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/mail.py

(cherry picked from commit bc3bd3a03beacd0f62e90f046971c5802b103a9a)

NAS-132268 / 13.3 / fix mail.queue regression (#14961)

---

src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/mail.py

(cherry picked from commit bc3bd3a03beacd0f62e90f046971c5802b103a9a)

NAS-132268 / 13.3-U1 / fix mail.queue regression (#14961)

---

src/middlewared/middlewared/plugins/cloud/crud.py
src/middlewared/middlewared/plugins/cloud/script.py
src/middlewared/middlewared/plugins/cloud/snapshot.py
src/middlewared/middlewared/plugins/cloud_backup/restic.py
src/middlewared/middlewared/plugins/cloud_backup/sync.py
src/middlewared/middlewared/plugins/cloud_sync.py
src/middlewared/middlewared/plugins/replication.py
src/middlewared/middlewared/pytest/unit/plugins/test_cloud_sync.py
src/middlewared/middlewared/schema/dict_schema.py
src/middlewared/middlewared/validators.py
tests/api2/test_341_pool_dataset_encryption.py
tests/api2/test_cloud_backup.py

git cherry-pick -x 64eb8c0ca1a17d1d1543aa5a3d0d15b85b3f7e83
git cherry-pick -x 41143b953148bc30533984e9d81045d3d6dd6ef6
git cherry-pick -x 2053c4a159a5b343d586184ddacffeb9d6d5a5bd
git cherry-pick -x 1920e01d1fa5e00443313a4164dc2dd31e7aa32d
git cherry-pick -x 87fcf46dc5a5265b7da7047e85e04fdab5adf08d
git cherry-pick -x 2c67364cce4c551c3a45bfc0ae01db30a1290c68
git cherry-pick -x 2fb4c8a79990f42c6a8803c63c934a642e47ef92
git cherry-pick -x ac3a061bd6b5bd4a7e85857bef78a0602aa3c557
git cherry-pick -x 8d4ab07974907da15deacae78f18ab0266b70bf0
git cherry-pick -x 0b1aed93f260c5305eb3027045c4c2798045cd49
git cherry-pick -x 6d2e299aaf03c80114cfe428b99d1924d731f293
git cherry-pick -x …

NAS-132345 / 24.10.1 / Implement TrueCloud snapshot and scripts config options (by creatorcary)

---

src/middlewared/middlewared/plugins/cloud_backup/restic.py

Even with the `--json` flag, not all restic messages are reported in JSON format.

NAS-132595 / 25.04 / Handle non-JSON progress messages in TrueCloud Backup

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

Increase the timeout associated with a non-HA ES24n import substantially.
A similar change was recently made for HA in PR #14975

NAS-132629 / 25.04 / Increase the timeout wrt ES24n import in import_on_boot

---

src/middlewared/middlewared/plugins/activedirectory.py

There has been an uptick in users complaining about hitting the activedirectory validation error that gets triggered when trying to change the server netbiosname while it is enabled. Make sure we're doing case-insensitive comparison for old and new names and include the names in the ValidationError message.

NAS-132122 / 25.04 / Do casefolded comparison of netbios names

---

src/middlewared/middlewared/plugins/activedirectory.py

There has been an uptick in users complaining about hitting the activedirectory validation error that gets triggered when trying to change the server netbiosname while it is enabled. Make sure we're doing case-insensitive comparison for old and new names and include the names in the ValidationError message.
Original PR: https://github.com/truenas/middleware/pull/14992
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132122

NAS-132122 / 24.10.1 / Do casefolded comparison of netbios names (by anodos325)

---

src/middlewared/middlewared/plugins/config.py

Since user is providing this file and method already replacing our configuration in many ways, the original usage doesn't pose a security risk. This change provides protection against a broken config file rewriting files outside the temporary directory used for extraction and causing undefined system behavior.
This commit uses Samba's safe_tarfile wrapper to extract the file with note to replace once we have a python version from upstream debian that supports the newer tarfile feature.

NAS-132572 / 25.04 / Safely extract user config

---

tests/api2/test_261_iscsi_cmd.py

Minor house-keeping update (before further changes).
- Add fixture `iscsi_running`
- Remove numbers from test
----
CI run with all _test_261_iscsi_cmd_ tests passing: [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1920/).

NAS-132654 / 25.04 / Tidy test_261_iscsi_cmd

---

src/middlewared/middlewared/plugins/ldap.py
tests/api2/test_ipa_join.py

Some users may have manually configured IPA integration by generating a keytab in IPA and uploading to our UI in 24.04 and earlier. Since there's no guarantee these keytabs were generated via proper IPA join, we default to legacy LDAP configuration, which is same as pre-24.10 and add an alert that we're basically running with a degraded capacity from what we could have.
Original PR: https://github.com/truenas/middleware/pull/14996
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132212

NAS-132212 / 24.10.1 / Improve handling for legacy IPA bind with kerberos principal (by anodos325)

---

src/middlewared/middlewared/utils/rootfs.py

With new `systemd-sysext` approach for nvidia drivers, we won't be able to write to `/usr` anymore at all. Fortunately, we only need to write there to temporarily remove `/usr/local/bin/dpkg` which blocks normal `/usr/bin/dpkg`. This issue can be resolved with new  `/usr/share/truenas/sysext-extensions/functioning-dpkg.raw`  (https://github.com/truenas/scale-build/pull/756).
We still keep old behavior if the target `usr` dataset does not belong to the currently running system (i.e. on initramfs updates on upgrade).
Merging this will break installing nvidia drivers and might break configuring FIPS.

NAS-132516 / 25.04 / Use `/usr/share/truenas/sysext-extensions/functioning-dpkg.raw` to temporarily allow `dpkg`

---

src/middlewared/middlewared/plugins/pool_/pool_disk_operations.py

Detaching or offlining disks should be audited.

NAS-132499 / 25.04 / audit certain disk activities

---

src/middlewared/middlewared/utils/rootfs.py

With new `systemd-sysext` approach for nvidia drivers, we won't be able to write to `/usr` anymore at all. Fortunately, we only need to write there to temporarily remove `/usr/local/bin/dpkg` which blocks normal `/usr/bin/dpkg`. This issue can be resolved with new  `/usr/share/truenas/sysext-extensions/functioning-dpkg.raw`  (https://github.com/truenas/scale-build/pull/756).
We still keep old behavior if the target `usr` dataset does not belong to the currently running system (i.e. on initramfs updates on upgrade).
Merging this will break installing nvidia drivers and might break configuring FIPS.
Original PR: https://github.com/truenas/middleware/pull/14958
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132516
Original PR: https://github.com/truenas/middleware/pull/15001
Jira URL: …

NAS-132516 / 24.10.1 / Use `/usr/share/truenas/sysext-extensions/functioning-dpkg.raw` to temporarily allow `dpkg` (by themylogin) (by bugclerk)

---

src/middlewared/middlewared/api/base/types/base/string.py
src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/cloud_backup.py
src/middlewared/middlewared/api/v25_04_0/common.py
src/middlewared/middlewared/plugins/cloud_backup/crud.py
src/middlewared/middlewared/plugins/cloud_backup/restore.py
src/middlewared/middlewared/plugins/cloud_backup/snapshot.py
src/middlewared/middlewared/plugins/cloud_backup/sync.py

Tests: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1964/

NAS-132068 / 25.04 / Convert cloud_backup to new api style

---

src/middlewared/middlewared/rclone/remote/s3.py
src/middlewared/middlewared/rclone/remote/storjix.py

…o in `cloudsync.credentials.verify`
Original PR: https://github.com/truenas/middleware/pull/15052
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132769

NAS-132769 / 24.10.1 / Fix `NOTICE: s3: s3 provider "" not known - please set correctly` als… (by themylogin)

---

src/middlewared/middlewared/plugins/docker/update.py

Accidentially removed by https://github.com/truenas/middleware/pull/15004, requested by UI team
Original PR: https://github.com/truenas/middleware/pull/15056
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132775

NAS-132775 / 24.10.1 / `docker.nvidia_present` (by themylogin)

---

src/middlewared/middlewared/api/v25_04_0/docker.py
src/middlewared/middlewared/plugins/docker/update.py

Accidentially removed by https://github.com/truenas/middleware/pull/15004, requested by UI team

NAS-132775 / 25.04 / `docker.nvidia_present`

---

tests/api2/test_audit_sudo.py

We strengthened our security posture by removing 2 `ALL ALL` entries from the sudoers file in fc3a785bb05fa21d5076773de640966c7c29f562. However, this cause a minor regression in the API tests.

NAS-132806 / 25.04 / fix test_audit_sudo tests

---

src/middlewared/middlewared/api/v25_04_0/pool_scrub.py

Fixes http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2050/testReport/junit/api2/test_006_pool_and_sysds/test_004_verify_pool_property_unused_disk_functionality/

NAS-132810 / 25.04 / Set defaults for `pool.scrub.create`

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/smb.py
src/middlewared/middlewared/plugins/smb.py

This commit convert smb.getacl and smb.setacl to new api_method.

NAS-132823 / 25.04 / Convert SMB share ACL methods to api_method

---

src/middlewared/middlewared/api/v25_04_0/filesystem.py
src/middlewared/middlewared/plugins/filesystem.py

This commit converts filesystem.stat and filesystem.statfs to new api_method.

NAS-132824 / 25.04 / Convert stat and statfs to api_method

---

src/middlewared/middlewared/plugins/cloud_sync.py

…list requests, etc.)
Original PR: https://github.com/truenas/middleware/pull/15090
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132809

NAS-132809 / 25.04 / Only call `get_task_extra_args` for cloud sync tasks (not for bucket … (by themylogin)

---

src/middlewared/middlewared/api/v25_04_0/filesystem.py
src/middlewared/middlewared/plugins/filesystem.py
src/middlewared/middlewared/utils/filesystem/attrs.py

This switches get/set ZFS attributes to api_method

NAS-132850 / 25.04 / Convert filesystem zfs-attr related endpoints to api_method

---

src/middlewared/middlewared/plugins/keychain.py

We should raise a ValidationError here instead of a CallError.

NAS-132839 / 25.04 / raise ValidationError instead of CallError

---

src/middlewared/middlewared/plugins/cloud_backup/restic.py

Passing cloud_backup tests: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2079/testReport/api2/test_008_cloud_backup/

NAS-132861 / 25.04 / Reduce verbosity of cloud_backup logging

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/vm.py
src/middlewared/middlewared/api/v25_04_0/vm_device.py
src/middlewared/middlewared/plugins/vm/capabilities.py
src/middlewared/middlewared/plugins/vm/clone.py
src/middlewared/middlewared/plugins/vm/devices/cdrom.py
src/middlewared/middlewared/plugins/vm/devices/device.py
src/middlewared/middlewared/plugins/vm/devices/display.py
src/middlewared/middlewared/plugins/vm/devices/nic.py
src/middlewared/middlewared/plugins/vm/devices/pci.py
src/middlewared/middlewared/plugins/vm/devices/storage_devices.py
src/middlewared/middlewared/plugins/vm/devices/usb.py
src/middlewared/middlewared/plugins/vm/disk_utils.py
src/middlewared/middlewared/plugins/vm/info.py
src/middlewared/middlewared/plugins/vm/lifecycle.py
src/middlewared/middlewared/plugins/vm/memory.py
src/middlewared/middlewared/plugins/vm/pci.py
src/middlewared/middlewared/plugins/vm/usb.py
src/middlewared/middlewared/plugins/vm/vm_devices.py
src/middlewared/middlewared/plugins/vm/vm_display_info.py
src/middlewared/middlewared/plugins/vm/vm_lifecycle.py
src/middlewared/middlewared/plugins/vm/vm_memory_info.py
src/middlewared/middlewared/plugins/vm/vms.py
tests/api2/test_541_vm.py
tests/api2/test_account_privilege_role_private_fields.py

Accepts style decorator has been removed from VM plugin.

NAS-132832 / 25.04 / Remove accepts style decorator from VM plugin

---

src/middlewared/middlewared/plugins/network.py

…rk interfaces
Original PR: https://github.com/truenas/middleware/pull/15114
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132567

NAS-132567 / 24.10.2 / Prevent infinite recursion on corrupted databases when deleting netwo… (by themylogin)

---

tests/api2/test_disk_wipe.py

Noticed this fail randomly under high CI infrastructure load. Let's robustize it a bit so we don't fail on transient external factors.

NAS-132885 / 25.04 / robustize test_disk_wipe

---

src/middlewared/middlewared/plugins/apps/schema_normalization.py

We are repeatedly checking if `/dev/kfd` exists and also doing that in an asynchronous method.
Cache checking if `/dev/kfd` exists.

NAS-132886 / 25.04 / Cache checking kfd existence

---

src/middlewared/middlewared/plugins/disk_/wipe.py

All of this logic is actually harmful to us because we're generating a bunch of unnecessary udev events when we wipe a disk. It's important to understand that the kernel will send events when a disk is opened for write and subsequently closed. Furthermore, we were sending another `BLKRRPART` ioctl unnecessarily. Again, opening the device and closing is enough.
This logic was added _BEFORE_ `disk.wipe` was fixed in https://github.com/truenas/middleware/pull/14742. The middle partition logic isn't needed because, again, this logic was added _BEFORE_ we understood that upstream `libblkid` has incorrect behavior wrt to zfs labels. An upstream PR has been opened and merged with them to fix this logic so that it stops (incorrectly) detecting zfs labels. Cf. NAS-130825. More importantly, …

NAS-132858 / 25.04 / remove unnecessary logic in disk.wipe

---

src/middlewared/middlewared/plugins/disk_/wipe.py

All of this logic is actually harmful to us because we're generating a bunch of unnecessary udev events when we wipe a disk. It's important to understand that the kernel will send events when a disk is opened for write and subsequently closed. Furthermore, we were sending another `BLKRRPART` ioctl unnecessarily. Again, opening the device and closing is enough.
This logic was added _BEFORE_ `disk.wipe` was fixed in https://github.com/truenas/middleware/pull/14742. The middle partition logic isn't needed because, again, this logic was added _BEFORE_ we understood that upstream `libblkid` has incorrect behavior wrt to zfs labels. An upstream PR has been opened and merged with them to fix this logic so that it stops (incorrectly) detecting zfs labels. Cf. NAS-130825. More importantly, …

NAS-132858 / 24.10.1 / remove unnecessary logic in disk.wipe (by yocalebo)

---

src/middlewared/middlewared/plugins/disk_/wipe.py

All of this logic is actually harmful to us because we're generating a bunch of unnecessary udev events when we wipe a disk. It's important to understand that the kernel will send events when a disk is opened for write and subsequently closed. Furthermore, we were sending another `BLKRRPART` ioctl unnecessarily. Again, opening the device and closing is enough.
This logic was added _BEFORE_ `disk.wipe` was fixed in https://github.com/truenas/middleware/pull/14742. The middle partition logic isn't needed because, again, this logic was added _BEFORE_ we understood that upstream `libblkid` has incorrect behavior wrt to zfs labels. An upstream PR has been opened and merged with them to fix this logic so that it stops (incorrectly) detecting zfs labels. Cf. NAS-130825. More importantly, …

NAS-132858 / 24.10.2 / remove unnecessary logic in disk.wipe (by yocalebo)

---

src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/virt/instance.py
tests/api2/test_virt_002_instance.py

Some containers do not have /bin/bash so we can't use it as a default.

Get first available shell in a container

---

src/middlewared/middlewared/plugins/update_/download.py
src/middlewared/middlewared/plugins/update_/install.py

2 things:
1. don't use `subprocess` when we have native bindings in python that do the same thing
2. bump up to sha256 since sha1 doesn't meet modern standards

NAS-132942 / 25.04 / use hashlib instead of subprocess

---

src/middlewared/middlewared/plugins/cloud_sync.py

git cherry-pick -x 9cc4ab9705e8132203f0575207f7c57a78914242
git cherry-pick -x d8e1afe0331f3a3db6a8c899bbf3e269ea6232aa
Cloud sync task might use up the refresh token and get a new one, and still fail to unrelated reason. We need to store the refresh token that it had put to its config file; otherwise, the next run will not work. This is the only cause of the described issue I can think of.
Original PR: https://github.com/truenas/middleware/pull/15156
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132851

NAS-132851 / 24.10.2 / Refresh cloud sync credentials even if cloud sync task fails (by themylogin)

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/app_image.py
src/middlewared/middlewared/plugins/apps_images/dockerhub_ratelimit.py
src/middlewared/middlewared/plugins/apps_images/images.py

Remove accepts style decorator from apps image plugin.

NAS-132985 / 25.04 / Remove accepts style decorator from apps_image plugin

---

src/middlewared/middlewared/etc_files/local/ssh/sshd_config.mako

Change to always setting UsePam for SSH access. This forces SSH session to set the loginuid via pam_loginuid and thereby ensures that audit logging entries are properly generated for interactive sessions.

NAS-132973 / 25.04 / Always use pam for ssh authentication

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/k8s_to_docker.py
src/middlewared/middlewared/plugins/kubernetes_to_docker/list_k8s_backups.py
src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py

Removes accepts style decorator from k8s to docker plugin and uses new api method instead.

NAS-133003 / 25.04 / Remove accepts style decorator from k8s to docker plugin

---

src/middlewared/middlewared/api/base/types/filesystem.py
src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/ftp.py
src/middlewared/middlewared/plugins/ftp.py

Converted FTP to new api.
Added 'Directory` to base/types/filesystem.py` as a common validator.
Passing CI tests can be found [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2173/).

NAS-133010 / 25.04 / Convert ftp to new api

---

src/middlewared/middlewared/apps/__init__.py
src/middlewared/middlewared/apps/websocket_app.py
src/middlewared/middlewared/main.py

Same as https://github.com/truenas/middleware/pull/15211, move `Application` into its own module and renamed it to `WebSocketApplication` and formatted it. There is no change in functionality.

NAS-133083 / 25.04 / Move Application into its own module

---

src/middlewared/middlewared/plugins/disk_/zfs_guid.py

No reason to use bidict here. There are many fancy, clever ways to create an inverse dictionary but since we're already iterating inside a for loop to create the `disk_to_guid` dict, just create another dict with the inverse values. It's no different than using `bidict`.

NAS-133133 / 25.04 / remove bidict from zfs_guid.py

---

src/middlewared/middlewared/plugins/nfs.py

Removing the unnecessary and incorrect websocket example.

NAS-133157 / 25.04 / Remove unnecessary and incorrect nfs.update example

---

tests/api2/test_cloud_backup.py

This is the only cloud_backup endpoint not covered by our api tests yet.
http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2331/

NAS-132728 / 25.04 / Add `cloud_backup.abort` test

---

src/middlewared/middlewared/plugins/failover_/enums.py

At the request of support team, update this text to be more accurate.

NAS-132040 / 25.04 / update disabled reasons enum

---

src/middlewared/middlewared/main.py

I added this way back in CORE days when we were trying to isolate and figure out a memory corruption issue that was specific to freeBSD. Needless to say, we've not had such issues on linux and so this option can be removed. I'd argue it's usefulness since it uses an exponentially more amount of memory to track memory. It's almost paradoxical. Anyways, remove it since it's unused and there are better ways to track memory usage on linux these days.

NAS-133219 / 25.04 / remove tracemalloc option

---

src/middlewared/middlewared/plugins/virt/instance_device.py

We want to keep allowing zvols to be used with incus containers and changes in validation have been made as such to reflect that.

NAS-133223 / 25.04 / Allow zvols for incus containers

---

src/middlewared/middlewared/plugins/pool_/pool.py

Cf. https://github.com/truenas/py-fenced/pull/61

NAS-133370 / 25.04 / improve fenced error message

---

src/middlewared/middlewared/plugins/smb.py

This should be dict rather than list.

NAS-133387 / 25.04 / Fix type for empty shares

---

src/middlewared/middlewared/plugins/config.py

We have since updated python which includes this CVE fix. We can go back to using native python module.

NAS-133447 / 25.04 / remove use of samba's safe_tarfile mitigation

---

src/middlewared/middlewared/plugins/enclosure_/nvme2.py

Found and tested fix on internal R30.

NAS-133414 / 25.04 / fix internal/front slots reporting for r30

---

src/middlewared/middlewared/plugins/enclosure_/nvme2.py

Found and tested fix on internal R30.
Original PR: https://github.com/truenas/middleware/pull/15322
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133414

NAS-133414 / 24.10.2 / fix internal/front slots reporting for r30 (by yocalebo)

---

src/middlewared/middlewared/plugins/pool_/attach_disk.py
src/middlewared/middlewared/plugins/pool_/dedup.py
src/middlewared/middlewared/plugins/pool_/expand.py
src/middlewared/middlewared/plugins/pool_/export.py
src/middlewared/middlewared/plugins/pool_/import_pool.py
src/middlewared/middlewared/plugins/pool_/info.py
src/middlewared/middlewared/plugins/pool_/pool.py
src/middlewared/middlewared/plugins/pool_/pool_disk_operations.py
src/middlewared/middlewared/plugins/pool_/pool_operations.py
src/middlewared/middlewared/plugins/pool_/replace_disk.py
src/middlewared/middlewared/plugins/pool_/resilver.py
src/middlewared/middlewared/role.py

These RBAC roles cover interaction with the pool plugin.

NAS-133465 / 25.04 / Add POOL_READ and POOL_WRITE roles

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/fc.py
src/middlewared/middlewared/plugins/fc/fc.py

Add new API definition for `fc.capable` including role.

NAS-133502 / 25.04 / Add new API definition for fc.capable including role.

---

src/middlewared/middlewared/plugins/acme_protocol.py
src/middlewared/middlewared/plugins/auth_/2fa.py
src/middlewared/middlewared/plugins/cron.py
src/middlewared/middlewared/plugins/disk.py
src/middlewared/middlewared/plugins/init_shutdown_script.py
src/middlewared/middlewared/plugins/ipmi_/lan.py
src/middlewared/middlewared/plugins/mail.py
src/middlewared/middlewared/plugins/network_/global_config.py
src/middlewared/middlewared/plugins/network_/static_routes.py
src/middlewared/middlewared/plugins/ntp.py
src/middlewared/middlewared/plugins/pool_/user_props.py
src/middlewared/middlewared/plugins/rsync.py
src/middlewared/middlewared/plugins/smart.py
src/middlewared/middlewared/plugins/snmp.py
src/middlewared/middlewared/plugins/ssh.py
src/middlewared/middlewared/plugins/sysdataset.py
src/middlewared/middlewared/plugins/tunables.py
src/middlewared/middlewared/plugins/ups.py
src/middlewared/middlewared/plugins/vmware.py
src/middlewared/middlewared/role.py
src/middlewared/middlewared/service/config_service.py
src/middlewared/middlewared/service/crud_service.py

This commit adds a role_prefix for all public CRUDService and ConfigService plugins, and raises an exception in a plugin of this type is created without a defined role_prefix.

NAS-133519 / 25.04 / require role_prefix for public CRUD / Config services

---

LICENSE.IX
debian/debian/copyright

Had some lingering out-dated information related to the licensing changes that we made awhile ago. Fix those up.

NAS-133534 / 25.04 / update debian/copyright and LICENSE.IX

---

src/middlewared/middlewared/plugins/iscsi_/targets.py
tests/api2/test_fibre_channel.py

- On target update, remove fcport if the `mode` has changed from either `FC` or `BOTH` to `ISCSI`.
- Add `test_target_mode_change` to exercise the above.
----
Passing (abridged) CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2609/).

NAS-133546 / 25.04 / Remove fcport if required on target mode update

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py
src/middlewared/middlewared/plugins/virt/utils.py
tests/api2/test_virt_vm.py

It was requested that we allow specifying VNC passwords for incus VMs.

NAS-133473 / 25.04 / Allow specifying VNC passwords for incus VMs

---

src/middlewared/middlewared/plugins/account.py

NAS-133608 / 25.04 / Fix star import in account.py

---

src/middlewared/middlewared/plugins/pool_/pool.py

This isn't used by us or anyone else so remove it.

NAS-133689 / 25.04 / remove dead endpoint (get_instance_by_name)

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/pool_dataset_details.py
src/middlewared/middlewared/plugins/pool_/dataset_details.py

Have to add `extra="allow"` since this does some fun recursion and I can't find a way to make pydantic happy without it.

NAS-133677 / 25.04 / Convert pool.dataset.details to new API

---

src/middlewared/middlewared/plugins/pool_/dataset_details.py

This reverts commit a8f5e9957491b74adba9653d9a66601194f926d4. Our `pool.dataset.query` (zfs.dataset.query) is an absolute trash fire. Since we freeze for beta tomorrow, i'll revert the optimization and investigate if we can do this more intelligently. With the changes as-is, it breaks `flat: True` and so the UI is busted.

NAS-133698 / 25.04 / Revert "optimize pool.dataset.details (#15436)"

---

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
src/middlewared/middlewared/utils/origin.py

This commit adds a header key to indicate whether nginx has flagged the session as https.

NAS-133754 / 25.04 / Fix check for https in ConnectionOrigin

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/datastore/write.py
src/middlewared/middlewared/pytest/unit/plugins/test_datastore.py
tests/api2/test_account.py

git cherry-pick -x e8a2bf0260bc15a4231482d6d427bfffed7569e0
git cherry-pick -x 000d0c72c13036460a75aae62b096364d2d4c9d3
git cherry-pick -x 0d4b584a5d245736c78ada1e6530f21dd63f52f1
Original PR: https://github.com/truenas/middleware/pull/15479
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133768

NAS-133768 / 24.10.2 / Validate groups on user create/update (by themylogin)

---

src/middlewared/middlewared/plugins/rdma/interface/crud.py
src/middlewared/middlewared/plugins/rdma/rdma.py

This commit grants NETWORK_INTERFACE role access to read and write data related to RDMA.

NAS-133793 / 25.10 / Add roles configuration for RDMA

---

src/middlewared/middlewared/plugins/rdma/interface/crud.py
src/middlewared/middlewared/plugins/rdma/rdma.py

This commit grants NETWORK_INTERFACE role access to read and write data related to RDMA.
Original PR: https://github.com/truenas/middleware/pull/15485
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133793

NAS-133793 / 25.04-RC.1 / Add roles configuration for RDMA (by anodos325)

---

src/middlewared/middlewared/etc_files/scst.conf.mako

Ensure we populate `node_name` and `parent_host` for NPIV targets, even if the physical port  does not have a target mapped to it.
Without this SCST could fail to start under certain configurations.
Rename `ha_node_wwpn_for_fcport` to `ha_node_wwpn_for_fcport_or_fchost` to properly the two types of parameters that it can (now) be called with.
----
CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2783/).

NAS-133834 / 25.10 / Ensure we populate node_name and parent_host for NPIV

---

src/middlewared/middlewared/api/v25_04_0/auth.py
src/middlewared/middlewared/apps/file_app.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/service/core_service.py
src/middlewared/middlewared/webui_auth.py
tests/api2/test_auth_token.py

* Allow creation of single-use auth tokens 
These authentication tokens are suitable for file downloads under enhanced security settings and were approved for use under STIG mode.
* Add ConnectionOrigin validation for file downloads. 
Prevent download links from being used from unexpected IP addresses.
* Remove unused legacy TrueCommand-related UI auth

NAS-133839 / 25.10 / Improve file download and allow in STIG mode

---

src/middlewared/middlewared/api/v25_04_0/auth.py
src/middlewared/middlewared/apps/file_app.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/service/core_service.py
src/middlewared/middlewared/webui_auth.py
tests/api2/test_auth_token.py

* Allow creation of single-use auth tokens 
These authentication tokens are suitable for file downloads under enhanced security settings and were approved for use under STIG mode.
* Add ConnectionOrigin validation for file downloads. 
Prevent download links from being used from unexpected IP addresses.
* Remove unused legacy TrueCommand-related UI auth
Original PR: https://github.com/truenas/middleware/pull/15502
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133839

NAS-133839 / 25.04-RC.1 / Improve file download and allow in STIG mode (by anodos325)

---

src/middlewared/middlewared/plugins/auth.py
tests/api2/test_auth_token.py

This commit adds validation that API user request to generate an authentication token for a job only succeeds if the job was initiated by the currently authenticated user.
This commit also adds auditing for when authenticated sessions generate API tokens.

NAS-133844 / 25.10 / validate download token generation

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py

It was requested by UI that it would be nice to expose root disk size of virt VMs.

NAS-133854 / 25.10 / Show root disk size of virt VMs

---

src/middlewared/middlewared/plugins/vm/clone.py
src/middlewared/middlewared/plugins/vm/lifecycle.py
src/middlewared/middlewared/plugins/vm/vm_devices.py
src/middlewared/middlewared/plugins/vm/vm_lifecycle.py
src/middlewared/middlewared/plugins/vm/vms.py

We are restricting users from creating, updating, cloning and starting Legacy VMs
Original PR: https://github.com/truenas/middleware/pull/15538
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133890

NAS-133890 / 25.04-BETA.1 / Prevent creating/updating/starting legacy VMs (by Qubad786)

---

src/middlewared/middlewared/plugins/vm/clone.py
src/middlewared/middlewared/plugins/vm/lifecycle.py
src/middlewared/middlewared/plugins/vm/vm_devices.py
src/middlewared/middlewared/plugins/vm/vm_lifecycle.py
src/middlewared/middlewared/plugins/vm/vms.py

We are restricting users from creating, updating, cloning and starting Legacy VMs
Original PR: https://github.com/truenas/middleware/pull/15538
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133890

NAS-133890 / 25.04-RC.1 / Prevent creating/updating/starting legacy VMs (by Qubad786)

---

src/middlewared/middlewared/plugins/pwenc.py

When `pwenc_secret` is missing, complex data structures are replaced with empty arrays/dictionaries, resulting in various crashes. The only remedy is to wipe out the affected tables entirely.
Original PR: https://github.com/truenas/middleware/pull/15498
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133757

NAS-133757 / 25.04-RC.1 / Prevent crashes when `pwenc_secret` is missing (by themylogin)

---

src/middlewared/middlewared/plugins/auth.py
tests/api2/test_authenticator_assurance_level.py
tests/api2/test_stig.py

We need to reply with a generic AUTH_ERR response rather than a CallError on authentication failure in STIG mode. We can't provide more details due to security considerations, but we can give a useful log message for admins.

NAS-133870 / 25.10 / Give proper error response to STIG auth

---

src/middlewared/middlewared/plugins/auth.py
tests/api2/test_authenticator_assurance_level.py
tests/api2/test_stig.py

We need to reply with a generic AUTH_ERR response rather than a CallError on authentication failure in STIG mode. We can't provide more details due to security considerations, but we can give a useful log message for admins.
Original PR: https://github.com/truenas/middleware/pull/15525
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133870

NAS-133870 / 25.04-RC.1 / Give proper error response to STIG auth (by anodos325)

---

src/middlewared/middlewared/plugins/update.py

https://github.com/truenas/middleware/pull/15571#issuecomment-2631923518

NAS-133989 / 25.10 / Failing to import removed symbol

---

src/middlewared/middlewared/plugins/update.py

https://github.com/truenas/middleware/pull/15571#issuecomment-2631923518
Original PR: https://github.com/truenas/middleware/pull/15579
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133989

NAS-133989 / 25.04-BETA.1 / Failing to import removed symbol (by creatorcary)

---

src/middlewared/middlewared/plugins/update.py

https://github.com/truenas/middleware/pull/15571#issuecomment-2631923518
Original PR: https://github.com/truenas/middleware/pull/15579
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133989

NAS-133989 / 25.04-RC.1 / Failing to import removed symbol (by creatorcary)

---

src/middlewared/middlewared/plugins/failover.py

The `ha_mode` endpoint is caching the return of `failover.enclosure.detect` on the class. However, `failover.enclosure.detect` is cached itself. This means we're double-caching. Remove the `HA_MODE` class attribute and cache in the `failover.enclosure.detect` method only.

NAS-134020 / 25.10 / stop double-caching HA_MODE

---

src/middlewared/middlewared/plugins/usage.py
tests/api2/test_usage_reporting.py

It was requested that we gather virt plugin usage statistics and relevant changes have been added to account for that.

NAS-133562 / 25.10 / Gather virt plugin metrics

---

tests/api2/test_virt_vm.py

NAS-134078 / 25.10 / Fix virt VM test

---

src/middlewared/middlewared/plugins/filesystem_/perm_check.py
src/middlewared/middlewared/utils/user_context.py

Follow-up to https://github.com/truenas/middleware/pull/15551
Original PR: https://github.com/truenas/middleware/pull/15553
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133945

NAS-133945 / 25.04-RC.1 / Make `run_with_user_context` crash if multiprocessing worker tries to import API (by themylogin)

---

src/middlewared/middlewared/plugins/failover.py

We were exposing to many private failover endpoints to the public or were enforcing schema validation when they were private. There is no need to do either. This does the following:
1. Remove public endpoints that aren't used by UI team
2. Remove schema validation on private endpoints
3. Remove dead endpoints that aren't used by anyone

NAS-134133 / 25.10 / Privatize certain failover endpoints

---

tests/api2/test_audit_websocket.py

We now raise exception if job id does not match an existing job for the user.

NAS-134087 / 25.10 / Use a proper job id for download token test

---

src/middlewared/middlewared/plugins/device.py

Typoed in https://github.com/truenas/middleware/pull/15550

NAS-134150 / 25.10 / fix typo in device.get_info

---

src/middlewared/middlewared/plugins/zfs_/dataset_encryption.py

entire plugin is private, no need to apply schema validation.

NAS-134140 / 25.10 / remove schema validation for private dataset_encryption endpoints

---

src/middlewared/middlewared/plugins/zfs_/pool.py

NAS-133207 / 25.10 / remove schema validation on zfs_/pool.py

---

src/middlewared/middlewared/plugins/docker/update.py

When we have 20+ running apps, we have seen that if we docker pool is unset or changed - what happens in the background is that ix-apps dataset is umounted after stopping docker service and the new one mounted (if anotehr pool has been selected).
However we have observed that that with 20+ running apps, docker does not cleanly exit and we are unable to umount ix-apps dataset because of that.
Make sure if pool attr is being changed, we stop all apps and then stop docker service as that results in a clean docker exit and we are able to umount ix-apps dataset without any issues.

NAS-134025 / 25.10 / Stop apps when pool attr for docker service is changed

---

src/middlewared/middlewared/api/base/jsonschema.py
src/middlewared/middlewared/api/base/model.py
src/middlewared/middlewared/api/base/server/doc.py

git cherry-pick -x 038296dadaf00b129200116bcc97b981fe502042
git cherry-pick -x 0e34f7e46f29b4f41a9a33e7d684269ac0763c66
Original PR: https://github.com/truenas/middleware/pull/15691
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134124

NAS-134124 / 25.04-RC.1 / Replication New API (by themylogin)

---

tests/api2/test_apps.py

We are seeing failures where docker pull limit is being exceeded, now in apps tests some changes have been made to not remove the image when we are creating the same app again and again as it will just exhaust the docker pull limit. 
Secondly some times app just gets to RUNNING state directly, so the tests have been made a bit loose on that end to allow for these varying states.

NAS-134085 / 25.10 / Fix random failures in apps tests

---

tests/api2/test_apps.py

We are seeing failures where docker pull limit is being exceeded, now in apps tests some changes have been made to not remove the image when we are creating the same app again and again as it will just exhaust the docker pull limit. 
Secondly some times app just gets to RUNNING state directly, so the tests have been made a bit loose on that end to allow for these varying states.
Original PR: https://github.com/truenas/middleware/pull/15702
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134085

NAS-134085 / 25.04-RC.1 / Fix random failures in apps tests (by Qubad786)

---

src/middlewared/middlewared/api/v25_04_0/smartctl.py
src/middlewared/middlewared/plugins/smart.py

git cherry-pick -x b412feb8b19a0f776c7d25cccd039781b534c429
git cherry-pick -x 2e3fd9f8a17aa88c47f3007a6005b223fd819458
Original PR: https://github.com/truenas/middleware/pull/15745
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134214

NAS-134214 / 25.04-RC.1 / Fix parsing `power_on_hours_ago` (by themylogin)

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/enclosure2.py
src/middlewared/middlewared/api/v25_10_0/__init__.py
src/middlewared/middlewared/api/v25_10_0/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/update.py
src/middlewared/middlewared/role.py

http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3017/

NAS-134059 / 25.10 / Add roles to enclosure2 and update plugins

---

tests/api2/test_428_smb_rpc.py

This commit adjusts the path in our CI tests for samba changes.

NAS-132269 / 25.10 / Adjust IPC path for samba changes

---

src/middlewared/middlewared/api/v25_04_0/virt_device.py
src/middlewared/middlewared/api/v25_10_0/virt_device.py
src/middlewared/middlewared/plugins/virt/device.py
src/middlewared/middlewared/plugins/virt/instance_device.py
src/middlewared/middlewared/utils/gpu.py
src/middlewared/middlewared/utils/iommu.py
src/middlewared/middlewared/utils/pci.py

PCI support for VM virt instances has been added.

NAS-134092 / 25.10 / Add PCI support for virt VM instances

---

src/middlewared/middlewared/api/v25_04_0/virt_device.py
src/middlewared/middlewared/plugins/virt/device.py
src/middlewared/middlewared/plugins/virt/instance_device.py
src/middlewared/middlewared/utils/gpu.py
src/middlewared/middlewared/utils/iommu.py
src/middlewared/middlewared/utils/pci.py

git cherry-pick -x 77e73e564e150bc98a6da61fa7be829ec419b198
git cherry-pick -x 53f99b7d2c7b2cb3553695587420daa8b82be355
PCI support for VM virt instances has been added.
Original PR: https://github.com/truenas/middleware/pull/15733
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134092

NAS-134092 / 25.04-RC.1 / Add PCI support for virt VM instances (by Qubad786)

---

src/middlewared/middlewared/api/v25_10_0/__init__.py

fix typo in __init__.py

---

src/middlewared/middlewared/plugins/virt/device.py
src/middlewared/middlewared/plugins/virt/instance_device.py
src/middlewared/middlewared/plugins/virt/utils.py

It was requested by UI team that we provide PCI devices description as well so users can know more about the PCI device which they have selected.
Original PR: https://github.com/truenas/middleware/pull/15826
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134360

NAS-134360 / 25.04-RC.1 / Add a description for PCI devices (by Qubad786)

---

src/middlewared/middlewared/plugins/virt/device.py
src/middlewared/middlewared/plugins/virt/instance_device.py
src/middlewared/middlewared/plugins/virt/utils.py

It was requested by UI team that we provide PCI devices description as well so users can know more about the PCI device which they have selected.
Original PR: https://github.com/truenas/middleware/pull/15826
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134360

NAS-134360 / 25.04.0 / Add a description for PCI devices (by Qubad786)

---

src/middlewared/middlewared/utils/disks_/disk_class.py

This ensures that we try really hard to return a proper serial number of a disk. This is mostly fixing 2x scenarios for which the serial is not being properly populated without these changes.
1. pmem devices that we use in our enterprise product populate a `uuid` attribute in sysfs which is what we use as a serial
2. proper SAS based disks do not have a `device/serial` file, however, they have a `vpd_pg80` file which is the contents of a SCSI Vital Product Data page 80 command being returned from the disk.

NAS-134524 / 25.10 / ensure we populate serial in get_disks()

---

src/middlewared/middlewared/api/base/server/ws_handler/rpc.py

Fix for master is in https://github.com/truenas/middleware/pull/15892/files

NAS-134580 / 25.04.0 / Fix crash on non-serializable method result

---

src/middlewared/middlewared/api/base/server/ws_handler/rpc.py

Fix for master is in https://github.com/truenas/middleware/pull/15892/files
Original PR: https://github.com/truenas/middleware/pull/15893
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134580

NAS-134580 / 25.04-RC.1 / Fix crash on non-serializable method result (by themylogin)

---

src/middlewared/middlewared/api/v25_10_0/__init__.py
src/middlewared/middlewared/api/v25_10_0/tunable.py
src/middlewared/middlewared/plugins/tunables.py
tests/api2/test_tunables.py

http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3389/

NAS-134568 / 25.10 / Convert tunable.*

---

src/middlewared/middlewared/utils/disks_/disk_class.py
src/middlewared/middlewared/utils/disks_/disk_io.py
tests/unit/test_get_disks.py

Fixes some typos causing these tests to fail.

NAS-134535 / 25.10 / fix typos in test_get_disks.py unit tests

---

src/middlewared/middlewared/plugins/virt/instance.py
tests/api2/test_virt_002_instance.py

This commit applies required idmap settings inside newly-created containers.

NAS-134613 / 25.10 / Apply idmap settings on new container creation

---

src/middlewared/middlewared/plugins/virt/instance.py
tests/api2/test_virt_002_instance.py

This commit applies required idmap settings inside newly-created containers.
Original PR: https://github.com/truenas/middleware/pull/15914
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134613

NAS-134613 / 25.04.0 / Apply idmap settings on new container creation (by anodos325)

---

src/middlewared/middlewared/api/v25_10_0/__init__.py
src/middlewared/middlewared/api/v25_10_0/update.py
src/middlewared/middlewared/plugins/update.py

http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3427/

NAS-134569 / 25.10 / Convert plugins/update.py

---

src/middlewared/middlewared/plugins/virt/disk.py
src/middlewared/middlewared/plugins/virt/global.py
src/middlewared/middlewared/plugins/virt/instance.py
src/middlewared/middlewared/plugins/virt/instance_device.py
src/middlewared/middlewared/plugins/virt/volume.py

Make sure virt plugin has an audit trail for various endpoints.
Original PR: https://github.com/truenas/middleware/pull/15903
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134533

NAS-134533 / 25.04.0 / Add audit trail for virt plugin (by Qubad786)

---

src/middlewared/middlewared/plugins/auth.py
tests/api2/test_auth_onetime.py

Prevent creation of single-use password for users with locked accounts or ones for which password authentication is disabled.

NAS-134722 / 25.10 / Add more validation to OTP generation

---

src/middlewared/middlewared/plugins/virt/instance.py

https://github.com/truenas/middleware/pull/15477 unnecessarily restricts the container based image choices. The `cdrom_agent` was used as the filter which excludes _containers_ unnecessarily. The following fixes have been applied:
1. if the image is a `cloud` variant (aka a cloud-init based image) we skip them since they're not supported right now
2. if the image has a `cdrom_agent` requirement and is a VM, we don't add it as a "VM" choice to be chosen by the end-user

NAS-134527 / 25.10 / fix how we filter containers/vms

---

src/middlewared/middlewared/plugins/virt/instance.py

https://github.com/truenas/middleware/pull/15477 unnecessarily restricts the container based image choices. The `cdrom_agent` was used as the filter which excludes _containers_ unnecessarily. The following fixes have been applied:
1. if the image is a `cloud` variant (aka a cloud-init based image) we skip them since they're not supported right now
2. if the image has a `cdrom_agent` requirement and is a VM, we don't add it as a "VM" choice to be chosen by the end-user
Original PR: https://github.com/truenas/middleware/pull/15976
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134527

NAS-134527 / 25.04.0 / fix how we filter containers/vms (by yocalebo)

---

src/middlewared/middlewared/plugins/virt/instance_device.py

Each time incus devices are converted to middleware format we are trace logging the same statement on different device types. I think it is better to remove this entirely as having logs here is just in my opinion spamming middleware.

NAS-134679 / 25.10 / Remove trace logging in instance device

---

src/middlewared/middlewared/plugins/virt/instance_device.py

Each time incus devices are converted to middleware format we are trace logging the same statement on different device types. I think it is better to remove this entirely as having logs here is just in my opinion spamming middleware.
Original PR: https://github.com/truenas/middleware/pull/15980
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134679

NAS-134679 / 25.04.0 / Remove trace logging in instance device (by Qubad786)

---

src/middlewared/middlewared/api/v25_10_0/pool.py

We had added validation earlier to not allow users to set a pool for incus which has whitespaces in it's name because incus is not able to handle pool names which have whitespaces in it. Now we are adding changes to not allow user to create/import a pool with a name which contains whitespaces.

NAS-134689 / 25.10 / Do not allow users to create pool with whitespaces in name

---

src/middlewared/middlewared/api/v25_10_0/__init__.py
src/middlewared/middlewared/api/v25_10_0/system_general_keymap.py
src/middlewared/middlewared/plugins/system_general/keymap.py
src/middlewared/middlewared/utils/kbdmap_choices.py

This converts `system.general.kbdmap_choices` to new API and also switches to parsing the `xml` provided file which is a better approach for programmatically building this list.

NAS-134783 / 25.10 / convert system.general.kbdmap_choices to new API

---

src/middlewared/middlewared/plugins/disk_/retaste.py

Convert disk.retaste to private endpoint. Never meant to be public.

NAS-134803 / 25.10 / move disk_/retaste.py to private endpoint

---

src/middlewared/middlewared/plugins/disk_/sync.py

These are private and simple endpoints, no reason to convert them.

NAS-134801 / 25.10 / remove accepts from disk_/sync.py

---

src/middlewared/middlewared/plugins/disk_/resize.py

This was never meant to be public.

NAS-134804 / 25.10 / move disk.resize to private endpoint

---

src/freenas/usr/lib/netdata/python.d/truenas_pool.chart.py

This commit adds changes to remove the run method override we have done for netdata to simplify the code.

NAS-134856 / 25.10 / Remove run override in pool netdata plugin

---

tests/api2/test_ipa_join.py

http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3618/

NAS-134898 / 25.10 / Fix test_admin_privilege

---

tests/api2/test_ipa_join.py

http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3618/
Original PR: https://github.com/truenas/middleware/pull/16059
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134898

NAS-134898 / 25.04.0 / Fix test_admin_privilege (by creatorcary)

---

src/middlewared/middlewared/plugins/reporting/realtime_reporting/pool.py

This commit adds changes to account for a case where we had reporting data stored for root dataset when a specific pool was there but that is not the case now.

NAS-134953 / 25.10 / Fix case when pool is no longer there

---

src/middlewared/middlewared/utils/disks_/disk_class.py

This adds smart related methods to the `disk_class.py::DiskEntry` class. It also adds a `translation` property which can be used by callers to understand if there is any type of command translation going on for the disk.
Nothing is using this, yet. Just plumbing it in so it can be used eventually.

NAS-134989 / 25.10 / add smart info to disk_class.py

---

src/middlewared/middlewared/plugins/virt/global.py

We were reporting json dict converted to string as is when showing error for storage pools and that has been improved.
Validation error now:
```
[EINVAL] virt_global_update.storage_pools: The pool 'tank' cannot be removed because it is currently used by the following asset(s):
- Virt-Instances: tank-container-1, tank-vm-1
- Virt-Volumes: alpine-standard-3.21.3-x86_64.iso, tank-vol, test-volume-1, test-volume-2
The pool 'mypool' cannot be removed because it is currently used by the following asset(s):
- Virt-Instances: mypool-container
- Virt-Volumes: mypool-volume
The pool 'test' cannot be removed because it is currently used by the following asset(s):
- Virt-Instances: container-1, vm-1
- Virt-Volumes: test-vol
```
Original PR: https://github.com/truenas/middleware/pull/16113
Jira URL: …

NAS-134982 / 25.04.1 / Better report validation error of storage pools (by Qubad786)

---

src/freenas/usr/lib/netdata/conf.d/python.d.conf
src/freenas/usr/lib/netdata/python.d/truenas_disk_temp.chart.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
src/middlewared/middlewared/plugins/reporting/utils.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
src/middlewared/middlewared/utils/disks_/disk_class.py

We had removed SMART netdata plugin when we removed SMART. Now a new plugin has been added to get disk temperature stats  from the disk utils we have.

NAS-135004 / 25.10 / Add plugin to retrieve disk temperatures

---

src/middlewared/middlewared/alert/source/disk_temp.py
src/middlewared/middlewared/api/v25_10_0/disk.py
src/middlewared/middlewared/plugins/disk_/temperature.py

This adds back the disk temperature alerts using the new kernel module interface that we extended.

NAS-135032 / 25.10 / add disk temperature alert (using new logic)

---

src/middlewared/middlewared/plugins/disk_/disk_events.py
src/middlewared/middlewared/plugins/disk_/retaste.py

Platform has very simple test to reproduce an issue whereby the standby controller doesn't retaste the disk AFTER it has been unlocked on active.
1. have SED disk on HA system
2. physically remove SED disk from HA system
3. physically reinsert SED disk on HA system
4. active controller receives a kernel udev event and `added_disk` kicks off and runs `disk.sed_unlock`
5. standby controller receives udev event, however, after the disk is unlocked it does not detect there are partitions on it
To remedy this situation following has been done:
1. add a `failover.call_remote` to `added_event` hook so that standby retastes the disk
2. change the private `disk.retaste` endpoint to receive a list of serial numbers of disks. (This is vitally important on HA because the `sd` or `nvme` device names …

NAS-135053 / 25.10 / fix partition detection on SED for HA

---

src/middlewared/middlewared/plugins/failover_/event.py

If DNS server information is configured on an HA active controller while the standby is non-functional, it means there is a risk the standby will be using invalid information. There exists a gap in how we bring up our services where-by we're not synchronizing the DNS nameserver information that is written to our database to the OS.

NAS-134988 / 25.10 / synchronize DNS on HA master event

---

src/middlewared/middlewared/plugins/failover_/event.py

If DNS server information is configured on an HA active controller while the standby is non-functional, it means there is a risk the standby will be using invalid information. There exists a gap in how we bring up our services where-by we're not synchronizing the DNS nameserver information that is written to our database to the OS.
Original PR: https://github.com/truenas/middleware/pull/16162
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134988

NAS-134988 / 25.04.1 / synchronize DNS on HA master event (by yocalebo)

---

src/middlewared/middlewared/api/v25_10_0/__init__.py
src/middlewared/middlewared/api/v25_10_0/systemdataset.py
src/middlewared/middlewared/plugins/sysdataset.py

http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3767/

NAS-135120 / 25.10 / convert systemdataset.*

---

src/middlewared/middlewared/api/v25_10_0/__init__.py
src/middlewared/middlewared/api/v25_10_0/network_general.py
src/middlewared/middlewared/plugins/network_/general.py

http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3768/

NAS-135118 / 25.10 / Convert network.general.summary

---

src/middlewared/middlewared/api/v25_10_0/__init__.py
src/middlewared/middlewared/api/v25_10_0/route.py
src/middlewared/middlewared/plugins/network_/route.py

http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3773/

NAS-135106 / 25.10 / Convert route namespace

---

src/middlewared/middlewared/api/v25_10_0/__init__.py
src/middlewared/middlewared/api/v25_10_0/kerberos.py
src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/kerberos.py
src/middlewared/middlewared/utils/directoryservices/krb5.py
src/middlewared/middlewared/utils/directoryservices/krb5_constants.py

This commit converts kerberos, kerberos.realm, and kerberos.keytab plugins to the new API.

NAS-132078 / 25.10 / Convert kerberos plugins to new API

---

src/middlewared/middlewared/plugins/virt/global.py

A user had adguard app configured where on wildcard IP the app was consuming port 53. When he tried to configure virt, it errored out with `Address already in use`. 
Make sure that we properly error out what is consuming port 53 so the user has an idea of what actually is happening and what steps can be taken to correct this.
i.e
```
[EINVAL] virt_global_update.pool: Port 53 is required for virtualization but is currently in use by the following services on wildcard IPs (0.0.0.0/::): 'adguard-home' application. Please reconfigure these services to bind to specific IP addresses instead of wildcard IPs.
```
Original PR: https://github.com/truenas/middleware/pull/16204
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134963

NAS-134963 / 25.04.1 / Better report validation error for 53 port when configuring virt (by Qubad786)

---

src/middlewared/middlewared/plugins/pool_/format_disks.py

If a zpool is being created while there are _UNRELATED_ SED drives that are not functioning, the act of formatting the disks should not fail. Instead of trying to unlock all disks during pool format, just try to unlock the disks that are being used to create the zpool.

NAS-135287 / 25.10 / dont unlock all disks in pool.format_disks

---

src/middlewared/middlewared/plugins/pool_/format_disks.py

If a zpool is being created while there are _UNRELATED_ SED drives that are not functioning, the act of formatting the disks should not fail. Instead of trying to unlock all disks during pool format, just try to unlock the disks that are being used to create the zpool.
Original PR: https://github.com/truenas/middleware/pull/16234
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135287

NAS-135287 / 25.04.1 / dont unlock all disks in pool.format_disks (by yocalebo)

---

src/middlewared/middlewared/plugins/test/mock.py

Fixed typo in mock usage alert message.

NAS-135289 / 25.10 / Fix typo in alert message.

---

src/middlewared/middlewared/plugins/docker/state_management.py
src/middlewared/middlewared/plugins/docker/update.py

git cherry-pick -x f1c3236977555524cf3ffa0c32ef3bbf3b575860
git cherry-pick -x 8e0553a48194ad82303e9da44c836475c2538663
We were not checking if an enterprise user is licensed to use apps and they could do so with consuming the API directly. Also while fixing this i saw that some validation steps we perform should be done before we try to mount docker related datasets which has been fixed/addressed as well.
Original PR: https://github.com/truenas/middleware/pull/16251
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135306

NAS-135306 / 25.04.1 / Only allow enterprise users to consume apps if they are licensed (by Qubad786)

---

src/middlewared/middlewared/api/base/decorator.py
src/middlewared/middlewared/api/base/server/doc.py
src/middlewared/middlewared/api/v25_04_1/__init__.py
src/middlewared/middlewared/api/v25_04_1/pool_dataset.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/pool_/dataset.py
src/middlewared_docs/generate_docs.py

git cherry-pick -x 3e569985ae973c5451f8eccb6e7855be290f337b
git cherry-pick -x e41d322dfb9120a64b3c18fc0cef9247a7300f3b
git cherry-pick -x 1d790cceff24ded883268a3f623ed6aa6a732455
Original PR: https://github.com/truenas/middleware/pull/16232
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135242

NAS-135242 / 25.04.1 / Bring back pool.dataset.destroy_snasphots (by themylogin)

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

Found by support team in field.

NAS-135342 / 25.10 / fix firmware version ident for ES60

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

Found by support team in field.
Original PR: https://github.com/truenas/middleware/pull/16261
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135342

NAS-135342 / 25.04.1 / fix firmware version ident for ES60 (by yocalebo)

---

README.md

The goal here is 3-fold.
1. remove legacy verbiage like "freeness"
2. remove information that causes "harm" by removing out-dated/invalid information.
3. simplify

NAS-135399 / 25.10 / rewrite README.md

---

README.md

The goal here is 3-fold.
1. remove legacy verbiage like "freeness"
2. remove information that causes "harm" by removing out-dated/invalid information.
3. simplify
Original PR: https://github.com/truenas/middleware/pull/16285
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135399

NAS-135399 / 25.04.1 / rewrite README.md (by yocalebo)

---

src/middlewared/middlewared/utils/origin.py

`socket.family` will always be `AF_INET` for internal nginx->middleware connections
Original PR: https://github.com/truenas/middleware/pull/16301
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135361

NAS-135361 / 25.04.1 / `get_tcp_ip_info` should determine socket family based on `X-Real-Remote-Addr` (by themylogin)

---

src/middlewared/middlewared/test/integration/assets/pool.py

Fix `another_pool` used by CI
If a pool is exported and reimported during the yield this can break the cleanup as the `id` may change.  Add a query to avoid.
----
CI test [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4030/).

NAS-135480 / 25.10 / Fix another_pool used by CI

---

src/middlewared/middlewared/test/integration/assets/pool.py

Fix `another_pool` used by CI
If a pool is exported and reimported during the yield this can break the cleanup as the `id` may change.  Add a query to avoid.
----
CI test [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4030/).
Original PR: https://github.com/truenas/middleware/pull/16310
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135480

NAS-135480 / 25.04.1 / Fix another_pool used by CI (by bmeagherix)

---

src/middlewared/middlewared/plugins/virt/instance_device.py

We want to allow users to have same host paths being mounted inside different containers.

NAS-135371 / 25.10 / Allow same host path to be mounted inside multiple containers

---

src/middlewared/middlewared/plugins/virt/instance_device.py

We want to allow users to have same host paths being mounted inside different containers.
Original PR: https://github.com/truenas/middleware/pull/16314
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135371

NAS-135371 / 25.04.1 / Allow same host path to be mounted inside multiple containers (by Qubad786)

---

src/middlewared/middlewared/plugins/audit/backend.py

Convert this private namespace to utilize the new api_method decorator.

NAS-135471 / 25.10 / convert AuditBackend to new api

---

src/middlewared/middlewared/plugins/mail_/gmail.py

(cherry picked from commit 9501b11999c2bff3b0142e6a7be3c4363815c665)

NAS-135394 / 25.04.1 / Persist updated GMail OAuth refresh token (#16302)

---

src/middlewared/middlewared/plugins/failover_/reboot.py

We're still setting phantom "remote system must be rebooted in order to finish upgrade" from time to time. Those are created in case the remote system fails to provide `system.reboot.info` but can provide `system.boot_id` (a legacy system).
Another case when this is possible is when the remote system is indeed upgraded but the first call fails to unrelated reason (we can't distinguish them, `failover.call_remote` does not provide such a mechanism). Let's double check that it really can't return `system.reboot.info` before adding such a reboot reason.

NAS-135238 / 25.04.1 / Try querying `system.reboot.info` once more in case the system is really upgraded, and the failure was just a hiccup.

---

src/middlewared/middlewared/plugins/account.py

Related to PR https://github.com/truenas/middleware/pull/16341, testing has shown the UI is sending `group: null` when someone tries to remove the primary group from a user on update. This is an invalid configuration and produces an error that isn't helpful. This changes the logic in the update endpoint so that an informative validation error is raised.

NAS-135551 / 25.10 / better validation error when group is None

---

src/middlewared/middlewared/plugins/iscsi_/extents.py
tests/api2/test_261_iscsi_cmd.py

- Ensure multiple iSCSI extent names don't get flattened to the same string
- Add CI `test__test_duplicate_extent_name`
----
CI [build](http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/1056/) & [run](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4124/) passes iSCSI tests.

NAS-135279 / 25.10 / Ensure multiple iSCSI extent names don't get flattened to the same string

---

src/middlewared/middlewared/plugins/nvmet/global.py
src/middlewared/middlewared/plugins/nvmet/host.py
src/middlewared/middlewared/plugins/nvmet/host_subsys.py
src/middlewared/middlewared/plugins/nvmet/namespace.py
src/middlewared/middlewared/plugins/nvmet/port.py
src/middlewared/middlewared/plugins/nvmet/port_subsys.py
src/middlewared/middlewared/plugins/nvmet/subsys.py

NAS-135595 / 25.10 / Remove nvmet from cli

---

src/middlewared/middlewared/api/v25_04_1/cloud_sync.py

This causes test_legacy_websocket.py to fail

NAS-135614 / 25.10 / Fix copy&paste error in 25.04.1 API

---

src/middlewared/middlewared/api/v25_04_1/cloud_sync.py

This causes test_legacy_websocket.py to fail
Original PR: https://github.com/truenas/middleware/pull/16369
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135614

NAS-135614 / 25.04.1 / Fix copy&paste error in 25.04.1 API (by themylogin)

---

src/middlewared/middlewared/alert/source/truenas_verify.py

Use stdout info from truenas_verify.
NOTE: This PR should be merged in conjunction with the same named PR in truenas_verify.

NAS-135492 / 25.10 / Improve root file system verify alert message.  

---

src/middlewared/middlewared/alert/source/truenas_verify.py

Use stdout info from truenas_verify.
NOTE: This PR should be merged in conjunction with the same named PR in truenas_verify.
Original PR: https://github.com/truenas/middleware/pull/16375
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135492

NAS-135492 / 25.04.1 / Improve root file system verify alert message.   (by mgrimesix)

---

src/middlewared/middlewared/api/v25_04_1/cloud_sync.py

Same as https://github.com/truenas/middleware/pull/16369

NAS-135656 / 25.10 / Fix copy&paste error in 25.04.1 API

---

src/middlewared/middlewared/api/v25_04_1/cloud_sync.py

Same as https://github.com/truenas/middleware/pull/16369
Original PR: https://github.com/truenas/middleware/pull/16399
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135656

NAS-135656 / 25.04.1 / Fix copy&paste error in 25.04.1 API (by themylogin)

---

src/middlewared/middlewared/api/v25_04_1/cloud_sync.py

Same as https://github.com/truenas/middleware/pull/16369
Original PR: https://github.com/truenas/middleware/pull/16399
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135656

NAS-135656 / 25.04.2 / Fix copy&paste error in 25.04.1 API (by themylogin)

---

src/middlewared/middlewared/plugins/iscsi_/extents.py

Discovered while diagnosing unrelated issues with our attachment delegate stuff.

NAS-135675 / 25.10 / stop blocking main event loop in iscsi.extent.delete

---

src/middlewared/middlewared/plugins/iscsi_/extents.py

Discovered while diagnosing unrelated issues with our attachment delegate stuff.
Original PR: https://github.com/truenas/middleware/pull/16410
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135675

NAS-135675 / 25.04.1 / stop blocking main event loop in iscsi.extent.delete (by yocalebo)

---

src/middlewared/middlewared/plugins/iscsi_/extents.py

Discovered while diagnosing unrelated issues with our attachment delegate stuff.
Original PR: https://github.com/truenas/middleware/pull/16410
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135675

NAS-135675 / 25.04.2 / stop blocking main event loop in iscsi.extent.delete (by yocalebo)

---

src/middlewared/middlewared/plugins/nvmet/namespace.py

Fix code that was based on code that was fixed in PR #16410

NAS-135676 / 25.10 / Stop blocking main event loop in nvmet.namespace.delete

---

src/middlewared/middlewared/plugins/account.py
tests/unit/test_shadow_account_policy.py

This commit adds a check for minimum password age when handling user.set_password calls. This check should not be added to general user.update calls because administrators may need to be able to reset user passwords even if they recently changed their password (users can be forgetful).

NAS-135674 / 25.10 / Add missing check for minimum password age

---

src/middlewared/middlewared/plugins/account.py
tests/unit/test_shadow_account_policy.py

This commit adds a check for minimum password age when handling user.set_password calls. This check should not be added to general user.update calls because administrators may need to be able to reset user passwords even if they recently changed their password (users can be forgetful).
Original PR: https://github.com/truenas/middleware/pull/16417
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135674

NAS-135674 / 25.04.2 / Add missing check for minimum password age (by anodos325)

---

src/middlewared/middlewared/plugins/account.py
tests/unit/test_shadow_account_policy.py

This commit adds a check for minimum password age when handling user.set_password calls. This check should not be added to general user.update calls because administrators may need to be able to reset user passwords even if they recently changed their password (users can be forgetful).
Original PR: https://github.com/truenas/middleware/pull/16417
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135674

NAS-135674 / 25.04.1 / Add missing check for minimum password age (by anodos325)

---

src/middlewared/middlewared/api/v25_04_0/alertservice.py
src/middlewared/middlewared/api/v25_04_0/cloud_backup.py
src/middlewared/middlewared/api/v25_04_0/crypto_ca_profiles.py
src/middlewared/middlewared/api/v25_04_0/docker.py
src/middlewared/middlewared/api/v25_04_0/docker_network.py
src/middlewared/middlewared/api/v25_04_0/initshutdownscript.py
src/middlewared/middlewared/api/v25_04_0/pool_resilver.py
src/middlewared/middlewared/api/v25_04_1/alert.py
src/middlewared/middlewared/api/v25_04_1/alertservice.py
src/middlewared/middlewared/api/v25_04_1/cloud_backup.py
src/middlewared/middlewared/api/v25_04_1/crypto_ca_profiles.py
src/middlewared/middlewared/api/v25_04_1/docker.py
src/middlewared/middlewared/api/v25_04_1/docker_network.py
src/middlewared/middlewared/api/v25_04_1/initshutdownscript.py
src/middlewared/middlewared/api/v25_04_1/pool_resilver.py
src/middlewared/middlewared/api/v25_04_2/alert.py
src/middlewared/middlewared/api/v25_04_2/alertservice.py
src/middlewared/middlewared/api/v25_04_2/cloud_backup.py
src/middlewared/middlewared/api/v25_04_2/crypto_ca_profiles.py
src/middlewared/middlewared/api/v25_04_2/docker.py
src/middlewared/middlewared/api/v25_04_2/docker_network.py
src/middlewared/middlewared/api/v25_04_2/initshutdownscript.py
src/middlewared/middlewared/api/v25_04_2/pool_resilver.py

git cherry-pick -x 18bc12e916fcebdbf75a12791486ef1eda19951b
git cherry-pick -x f30f9373bc856421a9a6568e66e966b2afa894db
Original PR: https://github.com/truenas/middleware/pull/16404
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135661

NAS-135661 / 25.04.2 / API flake8 (by themylogin)

---

src/middlewared/middlewared/plugins/auth.py
tests/api2/test_audit_websocket.py

This commit adds a new audit event type for middleware session logouts.
Original PR: https://github.com/truenas/middleware/pull/16420
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134865

NAS-134865 / 25.04.2 / Add auditing for middleware logouts (by anodos325)

---

src/middlewared/middlewared/plugins/pool_/dataset.py

Fix a regression in `pool.dataset.update` when a root dataset (aka zpool) is being updated via our API.

NAS-135718 / 25.10 / fix regression in pool.dataset.update

---

src/middlewared/middlewared/plugins/pool_/dataset.py

This fixes 5 API test failures related to aclmode testing.

NAS-135749 / 25.10 / fix aclmode validation regression

---

src/middlewared/middlewared/api/base/handler/model_provider.py
src/middlewared/middlewared/api/base/handler/version.py
src/middlewared/middlewared/main.py

Connecting to /websocket will attempt to use the 24.10 version of the API.
For all old versions of the API, we use factory functions to lazily load the version when it is needed. When a method model is not found in an older version (e.g. 24.10), we register it to the older version with a value of `None` since `None` is returned by this function when a `KeyError` is raised.
https://github.com/truenas/middleware/blob/accfe25027d247ab4e0cac2ba42a34eb6ca41972/src/middlewared/middlewared/main.py#L1385
The solution is to instead allow `KeyError` to propagate so that we make use of the `passthrough_nonexistent_methods` feature and use the most recent version of the method.
While here, I've also resolved a related FIXME comment and added more type hints. …

NAS-135643 / 25.04.1 / Fix API calls when connected to /websocket (by creatorcary)

---

src/middlewared/middlewared/api/base/handler/model_provider.py
src/middlewared/middlewared/api/base/handler/version.py
src/middlewared/middlewared/main.py

Connecting to /websocket will attempt to use the 24.10 version of the API.
For all old versions of the API, we use factory functions to lazily load the version when it is needed. When a method model is not found in an older version (e.g. 24.10), we register it to the older version with a value of `None` since `None` is returned by this function when a `KeyError` is raised.
https://github.com/truenas/middleware/blob/accfe25027d247ab4e0cac2ba42a34eb6ca41972/src/middlewared/middlewared/main.py#L1385
The solution is to instead allow `KeyError` to propagate so that we make use of the `passthrough_nonexistent_methods` feature and use the most recent version of the method.
While here, I've also resolved a related FIXME comment and added more type hints. …

NAS-135643 / 25.04.2 / Fix API calls when connected to /websocket (by creatorcary)

---

src/middlewared/middlewared/test/integration/utils/client.py

Backported from https://github.com/truenas/middleware/pull/16380

NAS-135790 / 25.04.2 / Fix test client with py_exceptions=False

---

src/middlewared/middlewared/api/__init__.py
src/middlewared/middlewared/api/base/handler/model_provider.py
src/middlewared/middlewared/api/base/handler/version.py
src/middlewared/middlewared/api/base/server/legacy_api_method.py
src/middlewared/middlewared/api/base/server/ws_handler/base.py
src/middlewared/middlewared/main.py

NAS-135785 / 25.10 / Address review of #16444

---

src/middlewared/middlewared/api/v25_10_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py

It was requested that we allow running containers in privileged mode and that support has been added.

NAS-135413 / 25.10 / Allow running containers in privileged mode

---

src/middlewared/middlewared/alert/source/zpool_capacity.py

Support team has requested that we update the zpool capacity alert. These changes implement what they've requested.

NAS-135831 / 25.10 / Update zpool capacity alert (support team request)

---

src/middlewared/middlewared/alert/source/sensors.py

Support team has requested that the PSU alerts that are raised in the UI also open a proactive support case with us. This implements the changes requested by them.
Original PR: https://github.com/truenas/middleware/pull/16485
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135832

NAS-135832 / 25.04.2 / make PSU alerts proactive (by yocalebo)

---

src/middlewared/middlewared/api/v25_10_0/app.py
src/middlewared/middlewared/plugins/catalog/apps.py
src/middlewared/middlewared/plugins/catalog/sync.py

This PR adds another attribute to `app.available` / `app.latest` which shows how popular an app is. Higher the value of this attribute means it is more popular in comparison to apps which have a lower value or no value present.

NAS-133590 / 25.10 / Allow sorting apps by popularity

---

src/middlewared/middlewared/utils/account/authenticator.py
tests/unit/test_shadow_account_policy.py

The PAM subsystem properly detects and processes an expired password condition.  By default, the condition is reported as a general failure.   The details of the error are included in failure messages.  We want to properly present the expiry condition to the user.  The password expiry check is performed in the 'account' section of PAM processing. 
We were not detecting the expiry condition because we were looking for it in the PAM 'authentication' section.
**The fix:**
Moved the expiry trap to after the pam account processing call.
**Also updated the CI unit tests:**
* Ensure clean state going in and exiting.
* Small tweak to `test__password_expiry_warning` to avoid false assert.
CI unit test [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/unit_tests/1396/)

NAS-135952 / 25.10 / Fix password expiry check

---

src/middlewared/middlewared/utils/account/authenticator.py
tests/unit/test_shadow_account_policy.py

The PAM subsystem properly detects and processes an expired password condition.  By default, the condition is reported as a general failure.   The details of the error are included in failure messages.  We want to properly present the expiry condition to the user.  The password expiry check is performed in the 'account' section of PAM processing. 
We were not detecting the expiry condition because we were looking for it in the PAM 'authentication' section.
**The fix:**
Moved the expiry trap to after the pam account processing call.
**Also updated the CI unit tests:**
* Ensure clean state going in and exiting.
* Small tweak to `test__password_expiry_warning` to avoid false assert.
CI unit test [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/unit_tests/1396/)
Original PR: …

NAS-135952 / 25.04.1 / Fix password expiry check (by mgrimesix) (by bugclerk)

---

src/middlewared/middlewared/plugins/virt/global.py
src/middlewared/middlewared/plugins/virt/instance.py
src/middlewared/middlewared/plugins/virt/instance_device.py
src/middlewared/middlewared/plugins/virt/websocket.py

Working on another PR and saw that our flake8 GitHub action is picking up quite a bit of issues in virt namespace.

NAS-135986 / 25.10 / flake8 clean-up

---

tests/api2/test_virt_001_global.py
tests/api2/test_virt_002_instance.py
tests/api2/test_virt_attachment_delegate.py
tests/api2/test_virt_instance_acl.py
tests/api2/test_virt_storage_pool.py
tests/api2/test_virt_vm.py

Working on some API test failures and need to disable these for the present moment.

NAS-136165 / 25.10 / disable virt tests for the moment

---

src/middlewared/middlewared/plugins/pwenc.py

* Discard directory services config
* Convert all local accounts to non-SMB
* Discard kerberos principals

NAS-136200 / 25.10 / Improve cleanup on resetting pwenc

---

src/middlewared/middlewared/plugins/network_/global_config.py

This commit fixes a spurious validation error when joining an AD domain in HA and simplifies the error message.

NAS-136206 / 25.10 / Fix validation for hostname change when joining domain

---

tests/api2/test_nvmet_tcp.py

Fix bug in `test__pool_export_import` exposed by recent improvement in validation (PR #16608).

NAS-136255 / 25.10 / Fix bug in test__pool_export_import

---

src/middlewared/middlewared/plugins/filesystem_/utils.py

This small PR fixes a few issues in the filesystem utils.

NAS-136263 / 25.10 / Fix issues in filesystem utils

---

src/middlewared/middlewared/plugins/filesystem_/utils.py

This small PR fixes a few issues in the filesystem utils.
Original PR: https://github.com/truenas/middleware/pull/16613

NAS-136263 / 25.04.2 / Fix issues in filesystem utils (by emmanuel-ferdman)

---

src/middlewared/middlewared/api/v25_10_0/smb.py

This commit adds documentation for remaining SMB fields.

NAS-136395 / 25.10 / Improve SMB server API documentation

---

src/middlewared/middlewared/alert/source/quota.py

Recent optimizations here introduced a subtle regression found by QE team. The problem is that zfs user properties are always strings but for our use-case, we need to cast some of then to integers so we can have this alert function as desired. This fixes the issue by casting the specific zfs user properties we're after.

NAS-136428 / 25.10 / fix QuotaAlertSource

---

src/middlewared/middlewared/plugins/directoryservices_/cache.py

This commit changes how the UNAVAIL return code is treated while building cache for SSSD when joined to IPA / LDAP. It may take some time for SSSD to initialize and build its own caches. In this case we can squash the NSS error and sleep a bit more to ensure we don't have failures.

NAS-135915 / 25.10 / Don't treat NSS UNAVAIL return code as fatal when building cache

---

src/middlewared/middlewared/api/v25_10_0/directory_services.py
src/middlewared/middlewared/plugins/directoryservices_/datastore.py

This commit expands our API documentation about the impacts of disabling vs leaving a domain and how to clear configuration via public API.

NAS-136519 / 25.10 / Expand docs on disabling and leaving domains

---

tests/unit/test_copytree.py
tests/unit/test_directory.py
tests/unit/test_tdb.py

These tests began to fail consistently in our unit tests pipelines when we switched to python 3.11 (possibly a change in GC behavior, but not worth investigating since the failures don't manifest when run manually).

NAS-136575 / 25.10 / Remove fd leak checks from unit tests

---

src/middlewared/middlewared/plugins/smb_/util_smbconf.py
tests/unit/test_smb_service.py

This adjusts unit tests for directory services and SMB share API changes

NAS-136629 / 25.10 / Fix SMB service unit test

---

tests/api2/test_300_nfs.py

The failure case was trapping `CallError, but the api_client call exception changed from `CallError` to `ClientException`.
That was the source of the failures.
Also includes tweak to `test_client_status` to improve error reporting (unexpected client mounts).

NAS-136172 / 25.10 / Changed exception trap from CallError to ClientException.

---

tests/api2/test_nvmet_tcp.py

Add some retries if necessary to robustize `test__global_sessions_loopback` (wrt session teardown).  Was failing (very) intermittantly.
(Tested locally)

NAS-136658 / 25.10 / Robustize nvmet CI test__global_sessions_loopback

---

src/middlewared/middlewared/test/integration/utils/__init__.py
src/middlewared/middlewared/test/integration/utils/ha.py
tests/directory_services/conftest.py
tests/sharing_protocols/conftest.py
tests/stig/conftest.py

Wait for HA to settle before beginning certain test runs.
----
CI [directoryservices_tests](http://jenkins.eng.ixsystems.net:8080/job/tests/job/directoryservices_tests/349/) & [sharing_protocols_tests](http://jenkins.eng.ixsystems.net:8080/job/tests/job/sharing_protocols_tests/16/).

NAS-136661 / 25.10 / Add ha_settle 

---

src/middlewared/middlewared/plugins/failover.py

Recently there's been an intermittent issue whereby a HA VM instantiation can report MISMATCH_NICS.  This can occur on a VM create or test run.
It _appears_ to be an issue arising from the `interface.persist_link_addresses` only getting called before the STANDBY controller is available.  (The "`link_address_b`" was `None` in the datastore query of `network.interface_link_address`.)
This PR includes a simple detect-and-fix that shouldn't cause any additional overhead unless the issue arises.
Tested on [this](http://jenkins.eng.ixsystems.net:8080/job/tests/job/sharing_protocols_tests/17/) CI run, and before the VM was torn down verified that the fix applied, thusly:
```
root@testZFF8IZZCEA-nodea[~]# grep Repaired /var/log/middlewared.log
[2025/07/11 12:52:37] (DEBUG) …
```

NAS-136664 / 25.10 / Avoid MISMATCH_NICS by forcing another persist_link_addresses

---

src/middlewared/middlewared/service/core_service.py

Docstring and comment in the change describes why this is needed.

NAS-136717 / 25.10 / allow unauthenticated calls to core.ping

---

src/middlewared/middlewared/plugins/failover_/reboot.py

I know that `remote_reboot_reasons` gets initialized by `load_remote_reboot_reasons` (and this won't change that), but recently I noticed a traceback during middleware startup.
```
[2025/07/15 10:23:50] (WARNING) middlewared.persist_link_addresses():44 - Exception while retrieving remote network interfaces: CallError('[EHOSTUNREACH] Unable
to determine remote node IP', 113)
[2025/07/15 10:23:50] (ERROR) failover.remote._on_connect():168 - Failed to run on_connect for remote client
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/remote.py", line 166, in _on_connect
cb(self.middleware)
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover.py", line 1190, in remote_status_event
middleware.call_sync('failover.status_refresh') …
```

NAS-136719 / 25.10 / Initialize FailoverRebootService.remote_reboot_reasons

---

src/middlewared/middlewared/plugins/directoryservices_/ipa_join_mixin.py

This commit adds a timeout for IPA-related management operations during domain join and leave. During some testing by the UI team an IPACTL operation to retrieve the IPA CA certificate from LDAP was seen to hang indefinitely. This is not readily reproducible and appeared to be in the libldap C library. The timeout value was an arbitrarily chosen high value to prevent the middleware job from being stuck basically forever.

NAS-136755 / 25.10 / Add timeouts for IPACTL operations

---

src/middlewared/middlewared/utils/directoryservices/krb5.py

Replication between KDCs can be slow (especially in our virtualized domains), and so we set a one hour affinity for a specific KDC after performing certain administrative operations. Originally the affinity information was written to the middleware run directory, but this is not ideal for HA because it's conceivable that the administrator will immediately test failovers after joining AD.
This commit changes the timeout so that its based on real time rather than monotonic time and shifts the file to directory_services directory in the system dataset.

NAS-136759 / 25.10 / Persist KDC affinity across HA failovers

---

src/middlewared/middlewared/utils/disks_/disk_class.py

Currently how disk identifier is calculated in `disk.query`, it factors in partition uuids as well if they are available and serial/lunid are not before falling back to using disk name as disk identifier. This introduces discrepancy between identifiers wherever they are going to be used elsewhere.
Factor in partition uuid when determining disk identifier in `DiskEntry` class to make sure that both implementations are as close as possible in terms of retrieving the same deterministic disk identifier.

NAS-136771 / 25.10 / Factor in partitions as well when generating disk identifier

---

src/middlewared/middlewared/plugins/system_advanced/gpu.py

Currently `system.advanced.get_gpu_pci_choices` is showing GPU slots which are not critical and can be isolated from the system. However this means that the user in the UI sometimes is not aware why a GPU which the system has is not showing up and why he cannot isolate it.
Update the endpoint UI uses so we report the GPU with the PCI slot which UI should use so middleware can isolate a GPU but also send another flag which shows if the GPU is critical or not. User should not be able to select this as an option but he can at least see that it is critical.
i.e
```
❯ midclt call system.advanced.get_gpu_pci_choices | jq
{
"Red Hat, Inc. QXL paravirtual graphic card [0000:00:02.0]": {
"pci_slot": "0000:00:02.0",
"uses_system_critical_devices": true,
"critical_reason": "Critical devices found: …
```

NAS-136653 / 25.10 / Update GPU PCI choices to reflect which GPU is critical

---

src/middlewared/middlewared/plugins/smb.py

This commit addresses a validation escape whereby a manual tester was able to set `EXTERNAL:server\\share` as a path in a share that didn't have the `EXTERNAL_SHARE` purpose.

NAS-136894 / 25.10 / Add validation to prevent setting external path in SMB share

---

src/middlewared/middlewared/alert/source/applications.py
src/middlewared/middlewared/plugins/apps/crud.py
src/middlewared/middlewared/plugins/apps/upgrade.py

This PR adds changes to have a single app update alert for apps instead of having separate alerts for each app as that can be quite noisy otherwise.

NAS-136916 / 25.10 / Have consolidated app update alert instead of separate alerts for each app

---

src/middlewared/middlewared/main.py

Type annotating middleware is an ongoing process. This particular PR represents some prep work for https://ixsystems.atlassian.net/browse/NAS-136965 with the primary goal of type hinting all `Middleware` attributes in `__init__`.
* Unset a few fields in `__init__` which had been initialized to `None`. They are initialized when `Middleware.run()` is called.
* Rework negative logic in `ws_can_access`
* Replace deprecated methods `Logger.warn` and `Thread.setDaemon`
http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/5435/

NAS-137002 / 26.04 / Expand type hints in `main.py`

---

tests/api2/test_acltype.py

Passing test here: [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/5447/testReport/api2/test_acltype/)

NAS-137016 / 26.04 / remove zfs.dataset.query from test_acltype.py

---

tests/api2/test_docker_backup.py

NAS-137023 / 26.04 / remove zfs.dataset.query from test_docker_backup.py

---

src/middlewared/middlewared/plugins/update_/config.py
src/middlewared/middlewared/plugins/update_/profile_.py

We were asked to change the new update profile code which this does. Also, I added all the logic to the `UpdateProfiles` enum class so we can keep everything in one place and not have duplicate code and keep everything into a single for loop.
Original PR: https://github.com/truenas/middleware/pull/16861

NAS-136902 / 25.10-BETA.1 / change update profile verbiage (by yocalebo)

---

src/middlewared/middlewared/plugins/update_/config.py
src/middlewared/middlewared/plugins/update_/profile_.py

We were asked to change the new update profile code which this does. Also, I added all the logic to the `UpdateProfiles` enum class so we can keep everything in one place and not have duplicate code and keep everything into a single for loop.
Original PR: https://github.com/truenas/middleware/pull/16861

NAS-136902 / 25.10-RC.1 / change update profile verbiage (by yocalebo)

---

src/middlewared/middlewared/plugins/update_/trains.py
src/middlewared/middlewared/pytest/unit/plugins/update/test_trains.py
src/middlewared/middlewared/utils/__init__.py

With the release of GoldEye, we've improved and refactored our update mechanism. To make the transition as easy as possible, we will download a separate trains file moving forward beginning in the GoldEye release.

NAS-137020 / 26.04 / add trains_v2.json

---

src/middlewared/middlewared/plugins/update_/trains.py
src/middlewared/middlewared/pytest/unit/plugins/update/test_trains.py
src/middlewared/middlewared/utils/__init__.py

With the release of GoldEye, we've improved and refactored our update mechanism. To make the transition as easy as possible, we will download a separate trains file moving forward beginning in the GoldEye release.
Original PR: https://github.com/truenas/middleware/pull/16883

NAS-137020 / 25.10-BETA.1 / add trains_v2.json (by yocalebo)

---

src/middlewared/middlewared/plugins/sysdataset.py

This removes pool.dataset.get_instance from system dataset plugin. Tests pass.

NAS-137084 / 26.04 / remove pool.dataset.get_instance from sysdataset.py

---

tests/api2/test_audit_alerts.py

To generate an alert on audit startup we made the audit database immutable.
However...
The audit 'setup' alert test started failing (did not generate an alert) because the startup process eliminated the 'VACUUM' operation.   
Creating a temporary 'corrupted' database restores the generation of an alert on 'setup'.
Local VM tested:
`[2025-08-11 16:35:16] api2/test_audit_alerts.py::test_audit_backend_alert[setup_state0] PASSED`

NAS-137110 / 26.04 / Fix audit alert CI test.

---

src/middlewared/middlewared/plugins/apps/ix_apps/lifecycle.py
src/middlewared/middlewared/plugins/apps/ix_apps/metadata.py
src/middlewared/middlewared/plugins/apps/ix_apps/setup.py
src/middlewared/middlewared/plugins/apps/ix_apps/utils.py
src/middlewared/middlewared/plugins/apps/metadata.py
src/middlewared/middlewared/plugins/apps/upgrade.py
src/middlewared/middlewared/plugins/docker/backup.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_quoted_str_dumper.py

This PR adds a custom YAML dumper (QuotedStrDumper) to ensure all string values in app configurations are properly quoted, preventing unintended type conversions.
Original PR: https://github.com/truenas/middleware/pull/16936

NAS-136877 / 25.10-RC.1 / Fix YAML string interpretation in app configs (by sonicaj)

---

src/middlewared/middlewared/plugins/jbof/crud.py

Found that on certain non-HA systems there could be a race condition that caused JBOF to not attach on boot.
Original PR: https://github.com/truenas/middleware/pull/16813

NAS-136834 / 25.04.2.2 / Avoid possible module load race condition (by bmeagherix)

---

src/middlewared/middlewared/alert/source/certificates.py
src/middlewared/middlewared/plugins/crypto_/renew_certs.py

This commit fixes an issue where some cert might have renew days set to null, we want to properly default to 10 in this case.

NAS-137199 / 26.04 / Fix certificate source alert

---

src/middlewared/middlewared/plugins/enclosure_/nvme2.py

with the new one received from the vendor.

NAS-137261 / 26.04 / Update R60 drive map

---

src/middlewared/middlewared/plugins/enclosure_/nvme2.py

with the new one received from the vendor.
Original PR: https://github.com/truenas/middleware/pull/17048

NAS-137261 / 25.10-RC.1 / Update R60 drive map (by creatorcary)

---

src/middlewared/middlewared/alert/source/smart.py
src/middlewared/middlewared/utils/disks_/disk_class.py

Empty SD card readers are causing the periodic SMART alert task to crash but it also exposed a few other issues.
1. `ThreadedAlertSource` does not have a `self.logger` attribute, have to access this through `self.middleware.logger`
2. Don't crash in this alert when we encounter (in this example) an empty SD card reader. smartctl crashes here with "unknown USB bridge"
3. if smartctl exits with an error, the json data doesn't have a top-level `device` key which we were accessing unsafely
4. add an option `raise_alert` keyword argument to the DiskEntry class to keep the same behavior previously but set that to false inside the SMART alert source
Original PR: https://github.com/truenas/middleware/pull/17142

NAS-137438 / 25.10-RC.1 / fix smart alert for empty SD card reader (by yocalebo)

---

src/middlewared/middlewared/plugins/vm/vm_devices.py

Missed some validation here that was found by UI team during implementation. Need to ensure the disk image exists in a proper location. Raise a proper validation error message otherwise.

NAS-137440 / 26.04 / better error message in vm.device.convert

---

src/middlewared/middlewared/plugins/pool_/dataset.py
src/middlewared/middlewared/plugins/pool_/dataset_create_utils.py

This replaces our usage of the legacy py-libzfs method with truenas_pylibzfs module. API has stayed the same and tests are passing.

NAS-137473 / 26.04 / use new libzfs library in pool.dataset.create

---

src/middlewared/middlewared/utils/secrets.py

This commit fixes a missing import in the secrets module.

Fix missing import in secrets module

---

.github/workflows/lint.yml
.github/workflows/unittests.yml

Unify and update our workflows to modern standards.

NAS-137686 / 26.04 / Unify github workflows

---

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako

See ticket for info. The two new paths are based on the existing `/ui` relative path location block.

NAS-137664 / 26.04 / Strict non-caching directives on three UI paths

---

src/middlewared/middlewared/plugins/audit/backend.py

This commit adjusts the audit backend query behavior for the newer version of SQL alchemy in trixie.

NAS-137727 / 26.04 / Fix audit.backend.query for trixie

---

src/middlewared/middlewared/plugins/device_/device_info.py

Ruby SED drives (PASCARI) use `EUI-64` format WWIDs. These `WWIDs` are not exposed as `ID_WWN` in udev properties. Without `ID_WWN` available, the `device.get_disks()` method cannot retrieve the lunid component. This caused Ruby drives to be stored in the middleware database with serial-only identifiers (e.g., `{serial}B1Q00278`) instead of full serial_lunid identifiers (e.g., `{serial_lunid}B1Q00278_00000000000000006479a707fc12e200`).
During SED unlock operations, `map_disks_to_passwd()` calls `disk.query()` which builds an `identifier_to_name` mapping using `disk.get_disks()`. This function reads WWIDs from sysfs where `EUI-64` identifiers ARE available, creating mapping entries with `serial_lunid`. The subsequent lookup in `disk_extend()` fails to match the database identifier …

NAS-137807 / 26.04 / Fix SED unlock for drives with EUI-64 WWIDs

---

src/middlewared/middlewared/plugins/device_/device_info.py

Ruby SED drives (PASCARI) use `EUI-64` format WWIDs. These `WWIDs` are not exposed as `ID_WWN` in udev properties. Without `ID_WWN` available, the `device.get_disks()` method cannot retrieve the lunid component. This caused Ruby drives to be stored in the middleware database with serial-only identifiers (e.g., `{serial}B1Q00278`) instead of full serial_lunid identifiers (e.g., `{serial_lunid}B1Q00278_00000000000000006479a707fc12e200`).
During SED unlock operations, `map_disks_to_passwd()` calls `disk.query()` which builds an `identifier_to_name` mapping using `disk.get_disks()`. This function reads WWIDs from sysfs where `EUI-64` identifiers ARE available, creating mapping entries with `serial_lunid`. The subsequent lookup in `disk_extend()` fails to match the database identifier …

NAS-137807 / 25.10.0 / Fix SED unlock for drives with EUI-64 WWIDs (by ixhamza)

---

src/middlewared/middlewared/api/v25_10_0/app.py
src/middlewared/middlewared/api/v25_10_0/filesystem.py
src/middlewared/middlewared/api/v26_04_0/app.py
src/middlewared/middlewared/api/v26_04_0/filesystem.py
src/middlewared/middlewared/event.py
src/middlewared/middlewared/plugins/apps/logs.py
src/middlewared/middlewared/plugins/filesystem.py

and clean up relevant docs and code.

NAS-137814 / 26.04 / Split off lines parameter from path for `filesystem.file_tail_follow`

---

src/middlewared/middlewared/plugins/vm/vm_devices.py

This crashes with KeyError because it's a typo. First check should be `stat` and not `statfs`.

NAS-137836 / 26.04 / fix KeyError in vm.device.convert

---

src/middlewared/middlewared/utils/cpu.py

During upgrade, when the migrations are being executed - sensors failed to initialize possibly because of being in the chroot env.
Lazy load sensors objects to ensure upgrades are safe.

NAS-137923 / 26.04 / Fix sensors initialization at module level

---

src/middlewared/middlewared/plugins/vm/vms.py
src/middlewared/middlewared/pytest/unit/plugins/test_vm.py

* `enable_secure_boot` and `bootloader_ovmf` are **create-time variables**, but their validation is currently part of the **common validation logic**, which also runs during updates.
* As a result, VMs created **before this change** are incorrectly validated during updates, leading to user-facing validation errors.
* Additionally, the transition to **Debian Trixie** has removed the `OVMF_CODE.fd` file from the available choices. This causes problems when users creates a VM without explicitly defining an OVMF value.
* Move the validation for `enable_secure_boot` and `bootloader_ovmf` to the **VM creation logic only**, preventing validation errors during updates.
* Updated the right default value for bootloader_ovmf .

NAS-137540 / 26.04 / Secureboot attrs should only be validated at create time
