src/middlewared/middlewared/plugins/interface/configure.py, src/middlewared/middlewared/plugins/rdma/interface/crud.py, src/middlewared/middlewared/plugins/rdma/rdma.py
When JBOF support was added, we added *all* RDMA interfaces to `rdma.interface.internal_interfaces`.  Instead only add those currently in use for JBOF purposes.
Likewise, in `rdma.get_link_choices` omit any interfaces that have been configured for general networking.
Original PR: https://github.com/truenas/middleware/pull/13289
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127697
=> NAS-127697 / 24.04.0 / Allow RDMA capable interfaces to be exposed for regular networking (by bmeagherix)

src/middlewared/middlewared/plugins/kerberos.py
If the Active Directory service is deleted and user decides to actually delete the existing AD machine account keytab, we should make sure that potential references to it are removed from the AD form.
=> NAS-127772 / 24.10 / Remove reference to AD kerberos principal

src/middlewared/middlewared/plugins/enclosure.py, src/middlewared/middlewared/plugins/enclosure_/sysfs_disks.py
This adds enclosure slot identification for the H series platform to the legacy enclosure code. It was simply omitted from the original PR adding this platform to our code base.
Original PR: https://github.com/truenas/middleware/pull/13304
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127709
=> NAS-127709 / 24.04.0 / drive ident for legacy enclosure hseries (by yocalebo)

src/middlewared/middlewared/plugins/system_advanced/config.py, src/middlewared/middlewared/plugins/system_advanced/gpu.py, src/middlewared/middlewared/plugins/system_general/ui.py, src/middlewared/middlewared/plugins/system_general/update.py, src/middlewared/middlewared/role.py, tests/api2/test_system_settings_roles.py
Roles were not assigned to general or advanced system settings which essentially meant that only users with administrator privileges would have been able to modify it. In the UI this meant that we have a lock icon next to update buttons for relevant forms etc.
Assign relevant roles to system settings and add additional integration tests to verify role-related changes.
=> NAS-127766 / 24.10 / Add roles for system.* services

src/middlewared/middlewared/plugins/system_advanced/config.py, src/middlewared/middlewared/plugins/system_advanced/gpu.py, src/middlewared/middlewared/plugins/system_general/ui.py, src/middlewared/middlewared/plugins/system_general/update.py, src/middlewared/middlewared/role.py, tests/api2/test_system_settings_roles.py
Roles were not assigned to general or advanced system settings which essentially meant that only users with administrator privileges would have been able to modify it. In the UI this meant that we have a lock icon next to update buttons for relevant forms etc.
Assign relevant roles to system settings and add additional integration tests to verify role-related changes.
Original PR: https://github.com/truenas/middleware/pull/13301
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127766
=> NAS-127766 / 24.04.0 / Add roles for system.* services (by Qubad786)

src/middlewared/middlewared/plugins/pool_/dataset_processes.py, src/middlewared/middlewared/plugins/sysdataset.py, tests/api2/test_pool_dataset_track_processes.py
Per request from automation team, backport fixes for:
NAS-127724 - If for some reason a process has an open handle on our old system dataset, log an error message and proceed with a lazy umount to avoid leaving system in broken state.
NAS-127671 - Fix error message for errors umounting sysdataset
=> Backport sysdataset fixes

src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py, src/middlewared/middlewared/plugins/jbof/functions.py
UI team was implementing the ES24N for DF and found that `disk.query` enclosure key was always null for drives in the ES24N. Closer inspection shows that I was mapping the nvme character device (i.e. `/dev/nvme2`) instead of the namespace block device (i.e. /dev/nvme2n1). This adds `namespaces` and `partitions` to `get_sys_class_nvme` and then fixes the disk mapping in `jbof_enclosures.py`
=> NAS-127812 / 24.10 / Fix es24n disk mapping

src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py, src/middlewared/middlewared/plugins/jbof/functions.py
UI team was implementing the ES24N for DF and found that `disk.query` enclosure key was always null for drives in the ES24N. Closer inspection shows that I was mapping the nvme character device (i.e. `/dev/nvme2`) instead of the namespace block device (i.e. /dev/nvme2n1). This adds `namespaces` and `partitions` to `get_sys_class_nvme` and then fixes the disk mapping in `jbof_enclosures.py`
Original PR: https://github.com/truenas/middleware/pull/13321
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127812
=> NAS-127812 / 24.04.0 / Fix es24n disk mapping (by yocalebo)

src/middlewared/middlewared/plugins/iscsi_/portal.py
When ALUA is enabled was displaying `address`/`netmask `rather than `address`/`address_b`
On a HA capable system, was displaying regular addresses in addition to the virtual addresses.
=> NAS-127813 / 24.10 / Fix iscsi.portal.listen_ip_choices

src/middlewared/middlewared/plugins/jbof/crud.py
This will permit the JBOF to be removed even if all communication with the JBOF has been lost.
(Did a minor refactor of parameters to `ensure_redfish_client_cached` while replicating the call, but another upcoming PR will take things further.)
=> NAS-127803 / 24.10 / Add optional force parameter to jbof.delete API

src/middlewared/middlewared/plugins/jbof/crud.py
This will permit the JBOF to be removed even if all communication with the JBOF has been lost.
(Did a minor refactor of parameters to `ensure_redfish_client_cached` while replicating the call, but another upcoming PR will take things further.)
Original PR: https://github.com/truenas/middleware/pull/13329
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127803
=> NAS-127803 / 24.04.0 / Add optional force parameter to jbof.delete API (by bmeagherix)

src/middlewared/middlewared/plugins/failover_/nftables.py
It is NOT obvious from the nfs man page, but it appears that if a family is not specified for a flush chain command then it defaults to ip.
(The man page does document similar behavior for TABLES.)
=> NAS-127851 / 24.10 / Update flush_chain_INPUT to flush both ip4 and ip6 tables

src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/smb.py
This commit reduces potential for API consumer actions during system dataset move to cause umount failures. Many operations during smb.configure will touch the system dataset via commands run in subprocesses.
=> NAS-127850 / 24.10 / Check for properly setup system dataset before SMB configure

src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/smb.py
This commit reduces potential for API consumer actions during system dataset move to cause umount failures. Many operations during smb.configure will touch the system dataset via commands run in subprocesses.
Original PR: https://github.com/truenas/middleware/pull/13332
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127850
=> NAS-127850 / 24.04.0 / Check for properly setup system dataset before SMB configure (by anodos325)

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
Customer upgraded to 23.10.2 and received a false alert for the ES12. This fixes it.
=> NAS-127852 / 24.10 / fix license alert for ES12

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
Customer upgraded to 23.10.2 and received a false alert for the ES12. This fixes it.
Original PR: https://github.com/truenas/middleware/pull/13343
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127852
=> NAS-127852 / 24.04-RC.1 / fix license alert for ES12 (by yocalebo)

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
Customer upgraded to 23.10.2 and received a false alert for the ES12. This fixes it.
Original PR: https://github.com/truenas/middleware/pull/13343
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127852
=> NAS-127852 / 24.04.0 / fix license alert for ES12 (by yocalebo)

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
Customer upgraded to 23.10.2 and received a false alert for the ES12. This fixes it.
Original PR: https://github.com/truenas/middleware/pull/13343
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127852
Original PR: https://github.com/truenas/middleware/pull/13345
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127852
=> NAS-127852 / 23.10.3 / fix license alert for ES12 (by yocalebo) (by bugclerk)

src/middlewared/middlewared/plugins/jbof/crud.py, src/middlewared/middlewared/plugins/jbof/redfish/client.py
We want to save the `mgmt_ip2` in the database (even if not supplied during the create), so that we can add robustness later.  (Splitting this functionality out to backport to 24.04, but won't avail of it until 24.10)
=> NAS-127856 / 24.10 / Detect and save mgmt_ip2 if not supplied during jbof.create

src/middlewared/middlewared/plugins/jbof/crud.py, src/middlewared/middlewared/plugins/jbof/redfish/client.py
We want to save the `mgmt_ip2` in the database (even if not supplied during the create), so that we can add robustness later.  (Splitting this functionality out to backport to 24.04, but won't avail of it until 24.10)
Original PR: https://github.com/truenas/middleware/pull/13341
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127856
=> NAS-127856 / 24.04.0 / Detect and save mgmt_ip2 if not supplied during jbof.create (by bmeagherix)

src/middlewared/middlewared/plugins/rdma/rdma.py
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/rdma/rdma.py", line 69, in get_link_choices
result.append({'rdma': link['ifname'], 'netdev': link['netdev']})
~~~~^^^^^^^^^^
KeyError: 'netdev'
```
=> NAS-127771 / 24.10 / Fix `KeyError` in `rdma.get_link_choices`

src/middlewared/middlewared/plugins/rdma/rdma.py
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/rdma/rdma.py", line 69, in get_link_choices
result.append({'rdma': link['ifname'], 'netdev': link['netdev']})
~~~~^^^^^^^^^^
KeyError: 'netdev'
```
Original PR: https://github.com/truenas/middleware/pull/13342
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127771
=> NAS-127771 / 24.04-RC.1 / Fix `KeyError` in `rdma.get_link_choices` (by themylogin)

src/middlewared/middlewared/plugins/rdma/rdma.py
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/rdma/rdma.py", line 69, in get_link_choices
result.append({'rdma': link['ifname'], 'netdev': link['netdev']})
~~~~^^^^^^^^^^
KeyError: 'netdev'
```
Original PR: https://github.com/truenas/middleware/pull/13342
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127771
=> NAS-127771 / 24.04.0 / Fix `KeyError` in `rdma.get_link_choices` (by themylogin)

src/freenas/usr/local/libexec/disable-rootfs-protection
Indicate to user that this requires being privileged user and account for possibility that /usr/sbin is not in user's PATH.
=> NAS-127873 / 24.10 / Improve error messages for disable-rootfs-protection

src/freenas/usr/local/libexec/disable-rootfs-protection
Indicate to user that this requires being privileged user and account for possibility that /usr/sbin is not in user's PATH.
Original PR: https://github.com/truenas/middleware/pull/13362
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127873
=> NAS-127873 / 24.04.0 / Improve error messages for disable-rootfs-protection (by anodos325)

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako, src/middlewared/middlewared/plugins/sysdataset.py
git cherry-pick -x 11aadb93cf4bcc1f6808709f19db23b3ecc98404
git cherry-pick -x 82176e034a1d5bf2774394427167fe34bb9fd8aa
git cherry-pick -x 1f882c8e7072fedfb9a771cdb0d1dda4bcb6ce99
git cherry-pick -x df43ce08ee6c2a0fab28847e25fcbf607ec1e4ac
Original PR: https://github.com/truenas/middleware/pull/13371
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127902
=> NAS-127902 / 24.04.0 / remove unused system datasets on fresh installs (by themylogin)

nas_ports/freenas/py-middlewared/Makefile
Several dependencies changed names and we no longer use py-zeroconf.
=> NAS-127903 / 13.3 / Fix build and runtime dependencies for middleware

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako, src/middlewared/middlewared/plugins/truecommand/wireguard.py, src/middlewared/middlewared/plugins/truenas.py, tests/api2/test_truecommand_roles.py
This PR adds changes to add a new endpoint which can be used to retrieve if system is being managed by Truecommand.
=> NAS-127150 / 24.10 / Add new endpoint to retrieve truecommand status

src/middlewared/middlewared/plugins/service_/on_config_upload.py
service.object raises MatchNotFound on error instead of KeyError
=> NAS-127922 / 24.10 / Fix error handling for configuration upload

src/middlewared/middlewared/plugins/service_/on_config_upload.py
service.object raises MatchNotFound on error instead of KeyError
Original PR: https://github.com/truenas/middleware/pull/13385
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127922
=> NAS-127922 / 24.04.0 / Fix error handling for configuration upload (by anodos325)

src/middlewared/middlewared/plugins/system_advanced/gpu.py, src/middlewared/middlewared/pytest/unit/plugins/test_pci_ids_for_gpu_isolation.py, src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_gpu_pci_choices.py
When GPU passthrough is desired, there are essentially 2 steps which need to be done:
1. Add GPU which is to be used for passthrough via `system.advanced` namespace
2. Create PCI devices for the GPU in question based on PCI devices it is consuming and any other which fall in the same iommu group (this happens during VM creation wizard)
For (2), we have an endpoint `vm.device.get_pci_ids_for_gpu_isolation` which UI should be consuming to find out PCI devices which should be created when user says he wants X GPU to be added to a VM.
For (1) however, UI was consuming the same endpoint and passing it's return argument to `system.advanced.update` which was bound to fail.
A new endpoint has been added `system.advanced.get_gpu_pci_choices` which basically does the parsing UI was already doing at …
=> NAS-127357 / 24.10 / Retrieve PCI slots in a new endpoint so that they are easily consumed by UI

src/middlewared/middlewared/plugins/system_advanced/gpu.py, src/middlewared/middlewared/pytest/unit/plugins/test_pci_ids_for_gpu_isolation.py, src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_gpu_pci_choices.py
When GPU passthrough is desired, there are essentially 2 steps which need to be done:
1. Add GPU which is to be used for passthrough via `system.advanced` namespace
2. Create PCI devices for the GPU in question based on PCI devices it is consuming and any other which fall in the same iommu group (this happens during VM creation wizard)
For (2), we have an endpoint `vm.device.get_pci_ids_for_gpu_isolation` which UI should be consuming to find out PCI devices which should be created when user says he wants X GPU to be added to a VM.
For (1) however, UI was consuming the same endpoint and passing it's return argument to `system.advanced.update` which was bound to fail.
A new endpoint has been added `system.advanced.get_gpu_pci_choices` which basically does the parsing UI was already doing at …
=> NAS-127357 / 24.04.0 / Retrieve PCI slots in a new endpoint so that they are easily consumed by UI (by Qubad786)

src/middlewared/middlewared/plugins/jbof/crud.py, src/middlewared/middlewared/plugins/jbof/redfish/client.py
Provide an API to allow the redfish interface to be configured.
- When changing an IOM it will direct the REST API calls through the **_other_** IOM.
- If it is unable to communicate with the changed IOM, it will undo the API call by restoring the previous values.
=> NAS-127905 / 24.10 / Add jbof.set_mgmt_ip API

src/middlewared/middlewared/plugins/jbof/crud.py, src/middlewared/middlewared/plugins/jbof/redfish/client.py
Provide an API to allow the redfish interface to be configured.
- When changing an IOM it will direct the REST API calls through the **_other_** IOM.
- If it is unable to communicate with the changed IOM, it will undo the API call by restoring the previous values.
Original PR: https://github.com/truenas/middleware/pull/13379
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127905
=> NAS-127905 / 24.04.0 / Add jbof.set_mgmt_ip API (by bmeagherix)

src/middlewared/middlewared/plugins/filesystem_/acl_template.py
When we generate template ACLs for users, we have option to include domain users and domain admins groups into the template return.
If idmap settings are misconfigured or someone has removed mappings for these default AD groups, then we need to warn but not crash.
=> NAS-127947 / 24.10 / Handle misconfigured AD idmap backends better in acltemplate

src/middlewared/middlewared/plugins/filesystem_/acl_template.py
When we generate template ACLs for users, we have option to include domain users and domain admins groups into the template return.
If idmap settings are misconfigured or someone has removed mappings for these default AD groups, then we need to warn but not crash.
Original PR: https://github.com/truenas/middleware/pull/13393
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127947
=> NAS-127947 / 24.04.0 / Handle misconfigured AD idmap backends better in acltemplate (by anodos325)

src/middlewared/middlewared/etc_files/local/wsdd.conf
wsdd fails to start in TrueNAS 13.3 due to configuration file differences.
=> NAS-127942 / 13.3 / Update wsdd configuration for version in Samba 4.19

src/middlewared/middlewared/logger.py
Avoid some log spam.
Found the following was occurring in syslog on DF and EE
```
Mar 21 18:07:06 truenas middlewared[14820]: [2024/03/21 18:07:06] (DEBUG) passlib.utils.compat.__getattr__():449 - loaded lazy attr 'SafeConfigParser': <class 'configparser.ConfigParser'>
Mar 21 18:07:06 truenas middlewared[14820]: [2024/03/21 18:07:06] (DEBUG) passlib.utils.compat.__getattr__():449 - loaded lazy attr 'NativeStringIO': <class '_io.StringIO'>
Mar 21 18:07:06 truenas middlewared[14820]: [2024/03/21 18:07:06] (DEBUG) passlib.utils.compat.__getattr__():449 - loaded lazy attr 'BytesIO': <class '_io.BytesIO'>
Mar 21 18:07:07 truenas middlewared[14855]: [2024/03/21 18:07:07] (DEBUG) passlib.utils.compat.__getattr__():449 - loaded lazy attr 'SafeConfigParser': <class 'configparser.ConfigParser'>
Mar …
```
=> NAS-127956 / 24.10 / Silence some syslog DEBUG spam from passlib.utils.compat

src/freenas/etc/ix.rc.d/ix-bsdloader, src/freenas/etc/ix.rc.d/ix-chelsio, src/freenas/etc/ix.rc.d/ix-etc, src/freenas/etc/ix.rc.d/ix-kinit, src/freenas/etc/ix.rc.d/ix-netif, src/freenas/etc/ix.rc.d/ix-nfsbind, src/freenas/etc/ix.rc.d/ix-nsswitch, src/freenas/etc/ix.rc.d/ix-preinit, src/freenas/etc/ix.rc.d/ix-savehostid, src/freenas/etc/ix.rc.d/ix-sed, src/freenas/etc/ix.rc.d/ix-shutdown, src/freenas/etc/ix.rc.d/ix-syncdisks, src/freenas/etc/ix.rc.d/ix-syncmultipaths, src/freenas/etc/ix.rc.d/ix-update, src/freenas/etc/ix.rc.d/ix-zfs
Upstream FreeBSD changes to rc.subr break parsing of rc scripts that have name variable containing a minus sign `-` in subtle ways.
=> NAS-127967 / 13.3 / Adjust ix.rc.d scripts for new rc.subr

tests/api2/test_008_pool.py, tests/conftest.py, tests/functions.py
There's not really any point to proceeding with tests if our attempt to create a pool fails.
=> NAS-127969 / 13.3 / Fail test run if pool not created

src/middlewared/middlewared/plugins/activedirectory_/cache.py, src/middlewared/middlewared/plugins/directoryservices.py, src/middlewared/middlewared/plugins/idmap.py, src/middlewared/middlewared/plugins/ldap.py, src/middlewared/middlewared/plugins/smb_/sharesec.py, tests/api2/test_030_activedirectory.py
This method was broken during removal of clustering from product, which was followed by significant refactor of directoryservices plugin for ElectricEel and so regression wasn't caught. Fix bug and add test.
=> NAS-127970 / 24.04.0 / Fix directory services initialization

src/middlewared/middlewared/plugins/activedirectory_/cache.py, src/middlewared/middlewared/plugins/idmap.py, src/middlewared/middlewared/plugins/ldap.py
Refactoring work related to choices for SMB share ACL users and groups revealed a long-standing bug whereby `smb` key was omitted from objects from directory services.
=> NAS-127970 / Fix user + group choices share ACL

src/middlewared/middlewared/logger.py
Avoid some log spam.
Found the following was occurring in syslog on DF and EE
```
Mar 21 18:07:06 truenas middlewared[14820]: [2024/03/21 18:07:06] (DEBUG) passlib.utils.compat.__getattr__():449 - loaded lazy attr 'SafeConfigParser': <class 'configparser.ConfigParser'>
Mar 21 18:07:06 truenas middlewared[14820]: [2024/03/21 18:07:06] (DEBUG) passlib.utils.compat.__getattr__():449 - loaded lazy attr 'NativeStringIO': <class '_io.StringIO'>
Mar 21 18:07:06 truenas middlewared[14820]: [2024/03/21 18:07:06] (DEBUG) passlib.utils.compat.__getattr__():449 - loaded lazy attr 'BytesIO': <class '_io.BytesIO'>
Mar 21 18:07:07 truenas middlewared[14855]: [2024/03/21 18:07:07] (DEBUG) passlib.utils.compat.__getattr__():449 - loaded lazy attr 'SafeConfigParser': <class 'configparser.ConfigParser'>
Mar …
```
=> NAS-127956 / 24.04.0 / Silence some syslog DEBUG spam from passlib.utils.compat (by bmeagherix)

src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
Currently the word `Temperature` exists on the Y axis/label for the UPS Temperature graph. PR adds the change to update label to reflect correct temperature unit i.e Celsius.
=> NAS-127900 / 24.10 / Fix CPU temperature unit label

src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
Currently the word `Temperature` exists on the Y axis/label for the UPS Temperature graph. PR adds the change to update label to reflect correct temperature unit i.e Celsius.
Original PR: https://github.com/truenas/middleware/pull/13408
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127900
=> NAS-127900 / 24.04.0 / Fix CPU temperature unit label (by Qubad786)

src/freenas/usr/local/etc/rc.d/collectd-daemon, tests/api2/test_007_systemdataset.py
There are various combinations of running state for the daemon
process monitoring the collectd process and the process that it
is monitoring. In some pathological cases the original script
could hang for up to 60 seconds on 13.0 and indefinitely in 13.3
This commit addresses the problem by doing the following:
* consolidates the pre-stop and post-stop functions into a single
stop function
* convert the rc script to use standard rc.subr functions to get pids
* validate that have pids we're trying to wait for
* Send a SIGKILL instead of SIGTERM to daemon process if the monitored
process has gone away.
=> NAS-128021 / 13.3 / Fix collectd-daemon RC script

src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/registry_global.py, src/middlewared/middlewared/plugins/smb_/registry_share.py, src/middlewared/middlewared/plugins/smb_/utils.py, tests/api2/test_435_smb_registry.py
Since the initial angelfish release in order to facilitate SMB clustering we have stored Samba's global section (services->SMB) in the samba registry via libsmbconf. 
Libsmbconf is more strict at validation of what gets written in the configuration. Some core users have copious smb_options with many comments in them. This shifts the function that was used for stripping comments from auxiliary parameters from sharing.smb to a utility function for consumption by both sharing.smb and services.smb.
=> NAS-128040 / 24.10 / Fix aux parameter comment parsing in services->SMB

src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/registry_global.py, src/middlewared/middlewared/plugins/smb_/registry_share.py, src/middlewared/middlewared/plugins/smb_/utils.py, tests/api2/test_435_smb_registry.py
Since the initial angelfish release in order to facilitate SMB clustering we have stored Samba's global section (services->SMB) in the samba registry via libsmbconf. 
Libsmbconf is more strict at validation of what gets written in the configuration. Some core users have copious smb_options with many comments in them. This shifts the function that was used for stripping comments from auxiliary parameters from sharing.smb to a utility function for consumption by both sharing.smb and services.smb.
Original PR: https://github.com/truenas/middleware/pull/13420
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128040
=> NAS-128040 / 24.04.0 / Fix aux parameter comment parsing in services->SMB (by anodos325)

src/middlewared/middlewared/etc_files/local/smb4.conf
Standalone servers should never have winbindd hang for a significant length of time. Aggressively time out winbind ops in case for some reason nsswitch has winbind in it.
This backports change from SCALE.
=> NAS-128058 / 13.3 / Set low winbind request timeout for standalone severs

src/middlewared/middlewared/plugins/smb.py, tests/api2/test_smb_share_crud_roles.py
There are various parameters in which the administrator can provide arbitrary commands and scripts to run via auxiliary parameters, some of which may be executed as the root user. This can present a risk of a limited administrator accidentally or intentionally performing actions on the NAS with privileges that are higher than intended.
=> NAS-127981 / 24.10 / Restrict changes to SMB aux parameters to FULL_ADMIN

src/middlewared/middlewared/plugins/smb.py, tests/api2/test_smb_share_crud_roles.py
There are various parameters in which the administrator can provide arbitrary commands and scripts to run via auxiliary parameters, some of which may be executed as the root user. This can present a risk of a limited administrator accidentally or intentionally performing actions on the NAS with privileges that are higher than intended.
Original PR: https://github.com/truenas/middleware/pull/13406
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127981
=> NAS-127981 / 24.04.0 / Restrict changes to SMB aux parameters to FULL_ADMIN (by anodos325)

src/middlewared/middlewared/plugins/service_/services/ups.py
This PR introduces changes to fix failing ups integration tests and fix the order in which UPS services should start.
=> NAS-128145 / 24.10 / Fix ups service not starting properly

src/middlewared/middlewared/plugins/service_/services/ups.py
This PR introduces changes to fix failing ups integration tests and fix the order in which UPS services should start.
Original PR: https://github.com/truenas/middleware/pull/13447
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128145
=> NAS-128145 / 24.04.0 / Fix ups service not starting properly (by sonicaj)

tests/api2/test_425_smb_protocol.py
During a recent test refactor (PR #12298), some breakage was introduced:
- Definition of `SMB_USER_CREATED` was removed, but some tests still depend upon it.
- Attempted to turn off `aapl_extensions` while `afp` enabled share still existed.
=> NAS-128141 / 24.10 / Fix some test breakage from recent refactor

src/middlewared/middlewared/alembic/versions/24.10/2024-03-21_12-15_add_global_system_id.py, src/middlewared/middlewared/alembic/versions/24.10/2024-04-01_20-15_add_global_system_id.py, src/middlewared/middlewared/migration/0009_system_global_id.py, src/middlewared/middlewared/plugins/system/globalid.py
We needed a way to uniquely identify ours systems with some IDs generated and store one time in the configuration database
Added a new table in database which holds uuid4 value saved in it on initial install of the system or upgrade of the system.
=> NAS-123519 / 24.10 / Add globally unique system ID

src/middlewared/middlewared/test/integration/utils/client.py, tests/api2/test_001_ssh.py, tests/api2/test_002_system_license.py, tests/api2/test_003_network_global.py, tests/api2/test_005_interface.py, tests/api2/test_006_pool_and_sysds.py, tests/conftest.py, tests/runtest.py
This makes the necessary changes to allow the `runtest.py` script work on our new jenkins infrastructure. There were an innumerable amount of issues (I'm exaggerating obviously) that were found while testing these changes so I'll list the most important ones:
1. our websocket client function `call` was never using the VIP on an HA system
2. because of this fact, the `log_test_name_to_middlewared_log` was causing the entire HA CI run to fail on the iSCSI tests. The reason why this was failing is because there is a test that fails over from the A to B node. This function was making a direct connection to the B node as well as the A node and so the connection was raising socket.timeout errors (as expected). This resolves that underlying issue by using the VIP (when appropriate)
3. The …
=> NAS-123721 / 24.10 / make runtest.py work with new jenkins

src/freenas/etc/systemd/system/netdata.service.d/override.conf
Some users are experiencing issues with Netdata not displaying UPS (Uninterruptible Power Supply) statistics. Upon investigation, it was found that the problem lies in the systemd service boot order. Netdata starts before the nut services, leading to the issue where Netdata attempts to report UPS stats before the UPS service is started during boot time.
Adjust the Netdata boot order by adding the nut service as a dependency in the Netdata service configuration.
(This was already fixed when we added `smartmontools.service` dependency but just adding `nut.target` for explicitness now)
=> NAS-127788 / 24.10 / Fix netdata boot time order wrt UPS

src/freenas/etc/systemd/system/netdata.service.d/override.conf
Some users are experiencing issues with Netdata not displaying UPS (Uninterruptible Power Supply) statistics. Upon investigation, it was found that the problem lies in the systemd service boot order. Netdata starts before the nut services, leading to the issue where Netdata attempts to report UPS stats before the UPS service is started during boot time.
Adjust the Netdata boot order by adding the nut service as a dependency in the Netdata service configuration.
(This was already fixed when we added `smartmontools.service` dependency but just adding `nut.target` for explicitness now)
Original PR: https://github.com/truenas/middleware/pull/13459
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127788
=> NAS-127788 / 24.04.0 / Fix netdata boot time order wrt UPS (by Qubad786)

src/middlewared/middlewared/test/integration/utils/client.py, src/middlewared/middlewared/test/integration/utils/ssh.py, tests/api2/test_005_interface.py, tests/api2/test_006_pool_and_sysds.py, tests/conftest.py, tests/functions.py, tests/runtest.py
As mentioned in https://github.com/truenas/middleware/pull/13450, this fixes the other issue whereby the REST related functions do not use the proper IP address on HA systems. This takes the work that @anodos325 pushed in https://github.com/truenas/middleware/pull/13438 but fixes a couple issues and tidies it up. This has been tested on new and old jenkins.
=> NAS-128174 / 24.10 / Make REST functions in CI use proper IP addresses on HA

src/middlewared/middlewared/plugins/failover.py
This PR fixes 2 bugs:
1) `failover.in_progress` not accounting for a job which might not have had started when it was called but system had registered it.
2) Endpoint we used to determine if remote node is active or not was only accounting for system being ready whereas in case of HA that is incomplete and it should account for remote node actually being available for consumption as failover event on remote can take some time as well.
=> NAS-128140 / 24.04.0 / Account for failover status when reporting backup node as ready

src/middlewared/middlewared/plugins/failover.py
This PR fixes 2 bugs:
1) `failover.in_progress` not accounting for a job which might not have had started when it was called but system had registered it.
2) Endpoint we used to determine if remote node is active or not was only accounting for system being ready whereas in case of HA that is incomplete and it should account for remote node actually being available for consumption as failover event on remote can take some time as well.
Original PR: https://github.com/truenas/middleware/pull/13464
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128140
=> NAS-128140 / 24.10 / Account for failover status when reporting backup node as ready (by sonicaj)

src/middlewared/middlewared/test/integration/utils/client.py, tests/api2/test_001_ssh.py, tests/api2/test_002_system_license.py, tests/api2/test_003_network_global.py, tests/api2/test_005_interface.py, tests/api2/test_006_pool_and_sysds.py, tests/conftest.py, tests/runtest.py
git cherry-pick -x ddb18da19386bd6c9d89c03446a76dcac2ee978a
git cherry-pick -x 79dcc1550ac3f52aca5ef6c041126e8c953c4532
git cherry-pick -x 50ee263efffd182b20e44d84268ef41ad4aa2550
git cherry-pick -x 78f128703dc20124f8adff821219b8d65b2390a9
git cherry-pick -x cc85d0cb5e23b90e1be79be676c74d6006ea5cc5
git cherry-pick -x 6c6cc0727ba8b62a5df4e94cddf7e6ed3cb9b95c
git cherry-pick -x ccd7302aec21d319add9fa0e348c67316cf5e1e8
git cherry-pick -x 06840691c587acc7415aae88694f3f19b19b24ed
git cherry-pick -x 8f8b402c939f661f5cc8b8b62ad62c08eb481c2a
git cherry-pick -x 25fece64a87f8eac5001c4c3af172edfa7cb06d7
git reset --hard …
=> NAS-123721 / 24.04.0 / make runtest.py work with new jenkins (by yocalebo)

tests/conftest.py
This is breaking all of the CI tests and I'm tired of dealing with it. It doesn't provide any benefit to log the test name to the remote controller. Especially since the remote controller doesn't even run the test. If we were to maintain this functionality, it means we're going to have to figure out which exact tests expect a failure here and which ones do not. That's too much maintenance overhead and doesn't provide any benefit.
NOTE: this still means we log this functionality on HA systems, it just means we log it on the controller that's actually running the test.
Original PR: https://github.com/truenas/middleware/pull/13453
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128164
=> NAS-128164 / 24.04.0 / remove notify_test* calls on HA (by yocalebo)

src/middlewared/middlewared/test/integration/utils/client.py, src/middlewared/middlewared/test/integration/utils/ssh.py, tests/api2/test_005_interface.py, tests/api2/test_006_pool_and_sysds.py, tests/conftest.py, tests/functions.py, tests/runtest.py
As mentioned in https://github.com/truenas/middleware/pull/13450, this fixes the other issue whereby the REST related functions do not use the proper IP address on HA systems. This takes the work that @anodos325 pushed in https://github.com/truenas/middleware/pull/13438 but fixes a couple issues and tidies it up. This has been tested on new and old jenkins.
Original PR: https://github.com/truenas/middleware/pull/13454
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128174
=> NAS-128174 / 24.04.0 / Make REST functions in CI use proper IP addresses on HA (by yocalebo)

src/freenas/etc/systemd/system/netdata.service.d/override.conf, src/middlewared/middlewared/etc_files/netdata/netdata.conf.mako, src/middlewared/middlewared/plugins/reporting/netdata_configure.py, src/middlewared/middlewared/plugins/reporting/utils.py, src/middlewared/middlewared/plugins/sysdataset.py, src/middlewared/middlewared/plugins/system_dataset/hierarchy.py
Netdata assigns itself a UUID which it stores in `/var/lib/netdata` and on upgrade we lose this which results in older reporting history not being available in the new BE.
Carry forward `/var/lib/netdata` to new BE and persist this state in system dataset like we are doing for the reporting data. Carrying forward state from older BE to new BE is being done in scale build repo (https://github.com/truenas/scale-build/pull/609).
=> NAS-127880 / 24.10 / Make sure netdata state persists across upgrades

src/middlewared/middlewared/alembic/versions/24.04/2024-04-03_14-10_cron.py
```
INFO  [alembic.runtime.migration] Running upgrade 6a7c2281f48e -> ea024b5dff95, Fix cron fields values, follow-up to NAS-125384
File "/usr/bin/alembic", line 33, in <module>
sys.exit(load_entry_point('alembic==1.8.1.dev0', 'console_scripts', 'alembic')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/alembic/config.py", line 590, in main
CommandLine(prog=prog).main(argv=argv)
File "/usr/lib/python3/dist-packages/alembic/config.py", line 584, in main
self.run_cmd(cfg, options)
File "/usr/lib/python3/dist-packages/alembic/config.py", line 561, in run_cmd
fn(
File "/usr/lib/python3/dist-packages/alembic/command.py", line 322, in upgrade
script.run_env()
File …
```
=> NAS-128222 / 24.10 / fix alembic crash

src/middlewared/middlewared/alembic/versions/24.04/2024-04-03_14-10_cron.py
```
INFO  [alembic.runtime.migration] Running upgrade 6a7c2281f48e -> ea024b5dff95, Fix cron fields values, follow-up to NAS-125384
File "/usr/bin/alembic", line 33, in <module>
sys.exit(load_entry_point('alembic==1.8.1.dev0', 'console_scripts', 'alembic')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/alembic/config.py", line 590, in main
CommandLine(prog=prog).main(argv=argv)
File "/usr/lib/python3/dist-packages/alembic/config.py", line 584, in main
self.run_cmd(cfg, options)
File "/usr/lib/python3/dist-packages/alembic/config.py", line 561, in run_cmd
fn(
File "/usr/lib/python3/dist-packages/alembic/command.py", line 322, in upgrade
script.run_env()
File …
```
=> NAS-128222 / 24.04.1 / fix alembic crash (by yocalebo)

src/middlewared/middlewared/alembic/versions/24.04/2024-04-03_14-10_cron.py
```
INFO  [alembic.runtime.migration] Running upgrade 6a7c2281f48e -> ea024b5dff95, Fix cron fields values, follow-up to NAS-125384
File "/usr/bin/alembic", line 33, in <module>
sys.exit(load_entry_point('alembic==1.8.1.dev0', 'console_scripts', 'alembic')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/alembic/config.py", line 590, in main
CommandLine(prog=prog).main(argv=argv)
File "/usr/lib/python3/dist-packages/alembic/config.py", line 584, in main
self.run_cmd(cfg, options)
File "/usr/lib/python3/dist-packages/alembic/config.py", line 561, in run_cmd
fn(
File "/usr/lib/python3/dist-packages/alembic/command.py", line 322, in upgrade
script.run_env()
File …
```
=> NAS-128222 / 24.04.0 / fix alembic crash (by yocalebo)

src/middlewared/middlewared/test/integration/utils/client.py
If using `runtest.py` against a **previously configured** HA system, and we are skipping `test_001_configure_interface`, then we may want to force the `truenas_server.ip` to the VIP.
=> Add USE_VIP to allow tests when HA/VIP already configured

src/middlewared/middlewared/test/integration/utils/client.py
If using `runtest.py` against a **previously configured** HA system, and we are skipping `test_001_configure_interface`, then we may want to force the `truenas_server.ip` to the VIP.
Original PR: https://github.com/truenas/middleware/pull/13486
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128224
=> NAS-128224 / 24.04.1 / Add USE_VIP to allow tests when HA/VIP already configured (by bmeagherix)

src/middlewared/middlewared/plugins/pool_/import_pool.py
In some cases users may have root dataset with NFSv4 acltype and an improper aclmode setting. This commit defaults to PASSTHROUGH aclmode in this case (which allows chmod to succeed if for some reason a non-trivial ACL is present).
=> NAS-128259 / 24.10 / Fix pool import normalization

src/middlewared/middlewared/plugins/pool_/import_pool.py
In some cases users may have root dataset with NFSv4 acltype and an improper aclmode setting. This commit defaults to PASSTHROUGH aclmode in this case (which allows chmod to succeed if for some reason a non-trivial ACL is present).
Original PR: https://github.com/truenas/middleware/pull/13492
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128259
=> NAS-128259 / 24.04.1 / Fix pool import normalization (by anodos325)

src/middlewared/middlewared/plugins/pool_/import_pool.py
In some cases users may have root dataset with NFSv4 acltype and an improper aclmode setting. This commit defaults to PASSTHROUGH aclmode in this case (which allows chmod to succeed if for some reason a non-trivial ACL is present).
Original PR: https://github.com/truenas/middleware/pull/13492
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128259
=> NAS-128259 / 24.04.0 / Fix pool import normalization (by anodos325)

src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/pytest/unit/utils/test_mountinfo.py, src/middlewared/middlewared/utils/osc/linux/mount.py
Bind mounts do not have unique device IDs and so device IDs cannot be treated as uniquely identifying a filesystem mount tree. This commit switches logic for getting tree to using statx return of stx_mnt_id.
filesystem.stat output is also expanded to include `mount_id` in return.
getmntinfo is also expanded to allow optimized retrieval of mount information by `mount_id`.
This bug could lead to spurious rejection of SMB share paths during path validation and possibly inaccurate information being presented in some filesystem API calls.
Original PR: https://github.com/truenas/middleware/pull/13500
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128267
=> NAS-128267 / 24.04.1 / Fix getmnttree and getmntinfo design issue (by anodos325)

src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/pytest/unit/utils/test_mountinfo.py, src/middlewared/middlewared/utils/osc/linux/mount.py
Bind mounts do not have unique device IDs and so device IDs cannot be treated as uniquely identifying a filesystem mount tree. This commit switches logic for getting tree to using statx return of stx_mnt_id.
filesystem.stat output is also expanded to include `mount_id` in return.
getmntinfo is also expanded to allow optimized retrieval of mount information by `mount_id`.
This bug could lead to spurious rejection of SMB share paths during path validation and possibly inaccurate information being presented in some filesystem API calls.
Original PR: https://github.com/truenas/middleware/pull/13500
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128267
=> NAS-128267 / 24.04.0 / Fix getmnttree and getmntinfo design issue (by anodos325)

src/middlewared/middlewared/plugins/service_/services/cifs.py
When stopping the SMB service via our API we must ensure that the on-demand samba-dcerpcd host process is terminated if it is currently running before returning from `service.stop`. Failure to do this may leave samba-dcerpcd in an inconsistent / unresponsive state.
=> NAS-128273 / 13.3 / Ensure samba-dcerpcd process is terminated

src/middlewared/middlewared/plugins/directoryservices.py
During QE testing it was observed that in-memory idmap backend settings of the idmap worker process was stale after reboot.
SIGHUP was insufficient to prompt reload and so this adds a winbind restart to ensure we always have correct configuration loaded.
=> NAS-128277 / 24.04.1 / Restart winbindd while initializing directory services

src/middlewared/middlewared/plugins/directoryservices.py
During QE testing it was observed that in-memory idmap backend settings of the idmap worker process was stale after reboot.
SIGHUP was insufficient to prompt reload and so this adds a winbind restart to ensure we always have correct configuration loaded.
Original PR: https://github.com/truenas/middleware/pull/13506
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128277
=> NAS-128277 / 24.04.0 / Restart winbindd while initializing directory services (by anodos325)

tests/api2/test_425_smb_protocol.py
During a recent test refactor (PR #12298), some breakage was introduced:
- Definition of `SMB_USER_CREATED` was removed, but some tests still depend upon it.
- Attempted to turn off `aapl_extensions` while `afp` enabled share still existed.
Original PR: https://github.com/truenas/middleware/pull/13445
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128141
=> NAS-128141 / 24.04.1 / Fix some test breakage from recent refactor (by bmeagherix)

src/middlewared/middlewared/plugins/directoryservices.py
This fixes a regression caused by a typo in a change to directory services startup.
=> NAS-128283 / 24.04.1 / Fix regression in middleware startup

src/middlewared/middlewared/plugins/directoryservices.py
This fixes a regression caused by a typo in a change to directory services startup.
Original PR: https://github.com/truenas/middleware/pull/13519
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128283
=> NAS-128283 / 24.04.0 / Fix regression in middleware startup (by anodos325)

src/middlewared/middlewared/plugins/jbof/redfish/client.py
Nice to be able to capture redfish traffic if necessary (was requested).
Original PR: https://github.com/truenas/middleware/pull/13523
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128290
=> NAS-128290 / 24.04.1 / Add some (disabled by default) logging wrt redfish client (by bmeagherix)

src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/plugins/filesystem_/stat_x.py
Typo specifying dirfd instead of dir_fd caused AT_FDCWD to be used instead of the desired O_PATH fd.
=> NAS-128300 / 24.10 / Fix typo in stat_x call

src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/plugins/filesystem_/stat_x.py
Typo specifying dirfd instead of dir_fd caused AT_FDCWD to be used instead of the desired O_PATH fd.
Original PR: https://github.com/truenas/middleware/pull/13529
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128300
=> NAS-128300 / 24.04.1 / Fix typo in stat_x call (by anodos325)

src/freenas/etc/sysctl.d/10-truenas.conf
The root cause of the issue was determined at
```
[2024/04/11 00:53:20] (ERROR) middlewared.settle_udev_events():16 - Failed to settle udev events: Failed to add inotify watch for /run/udev: Too many open files
```
not allowing middleware to correctly wait for the recently formatted partition to appear.
https://github.com/torvalds/linux/commit/92890123749bafc317bbfacbe0a62ce08d78efb7
=> NAS-128295 / 24.10 / Let kernel choose `fs.inotify.max_user_watches` automatically

src/freenas/etc/sysctl.d/10-truenas.conf
The root cause of the issue was determined at
```
[2024/04/11 00:53:20] (ERROR) middlewared.settle_udev_events():16 - Failed to settle udev events: Failed to add inotify watch for /run/udev: Too many open files
```
not allowing middleware to correctly wait for the recently formatted partition to appear.
https://github.com/torvalds/linux/commit/92890123749bafc317bbfacbe0a62ce08d78efb7
Original PR: https://github.com/truenas/middleware/pull/13528
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128295
=> NAS-128295 / 24.04.0 / Let kernel choose `fs.inotify.max_user_watches` automatically (by themylogin)

src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/plugins/filesystem_/stat_x.py
Typo specifying dirfd instead of dir_fd caused AT_FDCWD to be used instead of the desired O_PATH fd.
Original PR: https://github.com/truenas/middleware/pull/13529
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128300
=> NAS-128300 / 24.04.0 / Fix typo in stat_x call (by anodos325)

src/freenas/etc/sysctl.d/10-truenas.conf
The root cause of the issue was determined at
```
[2024/04/11 00:53:20] (ERROR) middlewared.settle_udev_events():16 - Failed to settle udev events: Failed to add inotify watch for /run/udev: Too many open files
```
not allowing middleware to correctly wait for the recently formatted partition to appear.
https://github.com/torvalds/linux/commit/92890123749bafc317bbfacbe0a62ce08d78efb7
Original PR: https://github.com/truenas/middleware/pull/13528
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128295
=> NAS-128295 / 24.04.1 / Let kernel choose `fs.inotify.max_user_watches` automatically (by themylogin)

src/middlewared/middlewared/plugins/ftp.py, src/middlewared/middlewared/plugins/nfs.py, src/middlewared/middlewared/plugins/nfs_/krb5.py, tests/api2/test_audit_ftp.py, tests/api2/test_audit_nfs.py
Add auditing of NFS and FTP.
NFS auditing includes configuration and share create, update and delete.
FTP auditing includes configuration only.
=> NAS-127770 / 24.10 / Add auditing of NFS and FTP

tests/api2/test_snmp_agent.py, tests/api2/test_system_general_ui_allowlist.py, tests/api2/test_user_admin.py
A few tests are failing because the `host()` function was changed during the move to the new jenkins instance. This fixes the remaining usages.
=> NAS-128310 / 24.10 / fix remaining usages of host() in api tests

tests/api2/test_snmp_agent.py, tests/api2/test_system_general_ui_allowlist.py, tests/api2/test_user_admin.py
A few tests are failing because the `host()` function was changed during the move to the new jenkins instance. This fixes the remaining usages.
Original PR: https://github.com/truenas/middleware/pull/13536
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128310
=> NAS-128310 / 24.04.1 / fix remaining usages of host() in api tests (by yocalebo)

src/freenas/usr/local/bin/truenas-initrd.py
git cherry-pick -x 06264d5b34d5b4ffd6dce38415208a1fd21b3262
git cherry-pick -x 1d23c7162538a9feebc0ddef4ec0c109583538fe
Original PR: https://github.com/truenas/middleware/pull/13539
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128301
=> NAS-128301 / 24.10 / Fix forced initrd update (by themylogin)

src/middlewared/middlewared/plugins/iscsi_/extents.py
Breakage was introduced in PR #13273
Original PR: https://github.com/truenas/middleware/pull/13546
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128316
=> NAS-128316 / 24.04.0 / Fix extent zvol space (by bmeagherix)

src/middlewared/middlewared/plugins/iscsi_/extents.py
Breakage was introduced in PR #13273
Original PR: https://github.com/truenas/middleware/pull/13546
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128316
=> NAS-128316 / 24.04.1 / Fix extent zvol space (by bmeagherix)

tests/api2/test_vm_roles.py
It's hard to really tell what's going on here because the `common_checks` function isn't documented but these 2 endpoints are not raising exceptions when using an "unprivileged" user account. However, they're not raising an exception because they're able to make the call to the endpoint. The issue is that `valid_role_exception` is set to True by default in `common_checks`. This fixes the tests.
=> NAS-128330 / 24.10 / fix vm role tests

tests/api2/test_vm_roles.py
It's hard to really tell what's going on here because the `common_checks` function isn't documented but these 2 endpoints are not raising exceptions when using an "unprivileged" user account. However, they're not raising an exception because they're able to make the call to the endpoint. The issue is that `valid_role_exception` is set to True by default in `common_checks`. This fixes the tests.
Original PR: https://github.com/truenas/middleware/pull/13549
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128330
=> NAS-128330 / 24.04.1 / fix vm role tests (by yocalebo)

src/middlewared/middlewared/plugins/filesystem_/perm_check.py, src/middlewared/middlewared/utils/user_context.py
The validation that ACL entries have ability to chdir to specified path had relatively terrible performance because it was forking a worker process for each change_to_user operation. This commit refactors so that we only fork once for validating the entire ACL.
This required refactoring our user context code to leave the saved UID and saved GID in-tact so that we can repeatedly setresuid and setresgid from same child process.
=> NAS-128337 / 24.10 / Speed up ACL execute permissions check

src/middlewared/middlewared/plugins/filesystem_/perm_check.py, src/middlewared/middlewared/utils/osc/linux/user_context.py
The validation that ACL entries have ability to chdir to specified path had relatively terrible performance because it was forking a worker process for each change_to_user operation. This commit refactors so that we only fork once for validating the entire ACL.
This required refactoring our user context code to leave the saved UID and saved GID in-tact so that we can repeatedly setresuid and setresgid from same child process.
Original PR: https://github.com/truenas/middleware/pull/13554
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128337
=> NAS-128337 / 24.04.1 / Speed up ACL execute permissions check (by anodos325)

src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py
When a disk is removed from ES24N, the REST API doesn't report a `SerialNumber` key. The fix is to check for the `State` key as being `Absent`. This fixes this particular issue but also adds a bit more guard-rails when mapping the disks for this platform. If we crash inside this function, the entirety of the enclosure section in the UI ceases to function which isn't desirable.
=> NAS-128339 / 24.10 / account for disk['State'] == 'Absent' on ES24N

src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py
When a disk is removed from ES24N, the REST API doesn't report a `SerialNumber` key. The fix is to check for the `State` key as being `Absent`. This fixes this particular issue but also adds a bit more guard-rails when mapping the disks for this platform. If we crash inside this function, the entirety of the enclosure section in the UI ceases to function which isn't desirable.
Original PR: https://github.com/truenas/middleware/pull/13556
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128339
=> NAS-128339 / 24.04.0 / account for disk['State'] == 'Absent' on ES24N (by yocalebo)

src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py
When a disk is removed from ES24N, the REST API doesn't report a `SerialNumber` key. The fix is to check for the `State` key as being `Absent`. This fixes this particular issue but also adds a bit more guard-rails when mapping the disks for this platform. If we crash inside this function, the entirety of the enclosure section in the UI ceases to function which isn't desirable.
Original PR: https://github.com/truenas/middleware/pull/13556
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128339
=> NAS-128339 / 24.04.1 / account for disk['State'] == 'Absent' on ES24N (by yocalebo)

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
I've found a bug in TrueNAS Scale 24.04-RC.1 which I reported here: https://ixsystems.atlassian.net/browse/NAS-128102
When a VM's display is bound to an IPv6 address like "::" using the "Bind" setting in the GUI, the resulting Nginx config is corrupt and Nginx refuses to start. This is because IPv6 addresses need to be surrounded by [] which is currently not the case. 
This bug has been introduced by [#12049](https://github.com/truenas/middleware/pull/12049). 
This PR fixes this by checking if the IP contains a colon, and if so, it adds the brackets to the address in the nginx config.
=> NAS-128102 / Fix IPv6 bind for VM display

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
I've found a bug in TrueNAS Scale 24.04-RC.1 which I reported here: https://ixsystems.atlassian.net/browse/NAS-128102
When a VM's display is bound to an IPv6 address like "::" using the "Bind" setting in the GUI, the resulting Nginx config is corrupt and Nginx refuses to start. This is because IPv6 addresses need to be surrounded by [] which is currently not the case. 
This bug has been introduced by [#12049](https://github.com/truenas/middleware/pull/12049). 
This PR fixes this by checking if the IP contains a colon, and if so, it adds the brackets to the address in the nginx config.
Original PR: https://github.com/truenas/middleware/pull/13439
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128102
=> NAS-128102 / 24.04.1 / NAS-128102 / Fix IPv6 bind for VM display (by Leseratte10)

src/middlewared/middlewared/migration/0010_nvram_attr_vms.py, src/middlewared/middlewared/plugins/vm/supervisor/domain_xml.py, src/middlewared/middlewared/plugins/vm/utils.py
During installation, some operating systems like Debian modify the nvram file, enabling the VM to boot up. However, when we upgrade the host system, this file is removed. QEMU then recreates the file, restoring it to the default value. Consequently, after the upgrade, the VM is unable to boot up again.
Ensure the persistence of nvram fd files after an upgrade by saving the under discussion files at `/data/subsystems/vm/nvram` and using them later after upgrade from the dir.
=> NAS-125816 / 24.10 / Properly save nvram file for UEFI based guests

tests/api2/test_iscsi.py
No need to replace whitespace with plus signs. ZFS will recognize and handle the space in the zvol name without issue. This is done in other tests in this file but seems to have been omitted from this particular test.
Original PR: https://github.com/truenas/middleware/pull/13572
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128362
=> NAS-128362 / 24.04.1 / fix iscsi_extent_locked test (by yocalebo)

src/middlewared/middlewared/test/integration/assets/roles.py, tests/api2/test_apps_roles.py, tests/api2/test_certificate_roles.py, tests/api2/test_iscsi_auth_crud_roles.py, tests/api2/test_iscsi_extent_crud_roles.py, tests/api2/test_iscsi_global_crud_roles.py, tests/api2/test_iscsi_host_crud_roles.py, tests/api2/test_iscsi_initiator_crud_roles.py, tests/api2/test_iscsi_portal_crud_roles.py, tests/api2/test_iscsi_target_crud_roles.py, tests/api2/test_iscsi_targetextent_crud_roles.py, tests/api2/test_nfs_share_crud_roles.py, tests/api2/test_smb_share_crud_roles.py, tests/api2/test_system_settings_roles.py, tests/api2/test_truecommand_roles.py, tests/api2/test_vm_roles.py, tests/conftest.py
This PR adds changes to improve implementation of `common_checks` to reduce the time it took to execute tests which were consuming this. Essentially what was happening was that we were creating a user on each run of that function which also meant that we were creating a dataset where both are costly operations. So now we use a fixture to cache these for the entire run of the test suite but make sure specific roles are updated to account for it.
=> NAS-128333 / 24.10 / Improve role checking logic to reduce tests execution tim

src/middlewared/middlewared/test/integration/assets/roles.py, tests/api2/test_apps_roles.py, tests/api2/test_certificate_roles.py, tests/api2/test_iscsi_auth_crud_roles.py, tests/api2/test_iscsi_extent_crud_roles.py, tests/api2/test_iscsi_global_crud_roles.py, tests/api2/test_iscsi_host_crud_roles.py, tests/api2/test_iscsi_initiator_crud_roles.py, tests/api2/test_iscsi_portal_crud_roles.py, tests/api2/test_iscsi_target_crud_roles.py, tests/api2/test_iscsi_targetextent_crud_roles.py, tests/api2/test_nfs_share_crud_roles.py, tests/api2/test_system_settings_roles.py, tests/api2/test_truecommand_roles.py, tests/api2/test_vm_roles.py, tests/conftest.py
git cherry-pick -x df62113a7253aca7964a9b0c31f223341baf093c
git cherry-pick -x a6e58868129c7db1dc8712d8a290d1adcbd88e13
git cherry-pick -x 2ddb38118188b0a84a6b26f808f0adf387f7e6df
git cherry-pick -x 66447ef153213768843d1791fb25b576fdfa6c6e
git cherry-pick -x ed7a494220777387c08c88823d3bf38f7606cbb9
git cherry-pick -x 48b6dadf7eb19b9ad224d1adff7f13c24f6703dc
git cherry-pick -x 76d4078d26f88e7dc152d8cb6c72129e0b88355d
git cherry-pick -x b31c6b95bf8a069ae62b856e904c4c8f0a24d267
git cherry-pick -x dc384a70a4e2199d183b46d272e520456992ee8f
git cherry-pick -x 98ca6b5d25562ee727813ee1842d39bb145a2f3a
git cherry-pick -x 5694e1c1a200ad6d8d61d4935243b867eac37873
git cherry-pick -x 0001b83a2a02a0af0b8968fd508d5f2335f4f7b4
git …
=> NAS-128333 / 24.04.1 / Improve role checking logic to reduce tests execution tim (by sonicaj)

src/middlewared/middlewared/plugins/network.py
Currently, the dropdown for the VMs Display bind address allows you to choose between 0.0.0.0 (all IPv4), :: (all IPv6) and 127.0.0.1 (localhost IPv4). ::1 (localhost IPv6) is not an option, so it's not possible to have a VM whose display is reachable over IPv6 but only from the local machine. 
This PR changes that, by making the code add "::1" to the list of loopback IPs in network.py as well, instead of just 127.0.0.1. 
Related to #13439
=> VMs: Consider ::1 a localhost IP as well

src/middlewared/middlewared/plugins/etc.py
Tweak perms that `etc.py` uses (with `mako`).
Original PR: https://github.com/truenas/middleware/pull/13580
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128372
=> NAS-128372 / 24.04.1 / Change permissions on the generated scst.conf (by bmeagherix)

src/middlewared/middlewared/plugins/etc.py
Tweak perms that `etc.py` uses (with `mako`).
Original PR: https://github.com/truenas/middleware/pull/13580
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128372
=> NAS-128372 / 24.04.0 / Change permissions on the generated scst.conf (by bmeagherix)

src/middlewared/middlewared/plugins/boot.py
Noticed breakage on HA STANDBY node (from PR #13280).
Repro'd from command line:
```
root@truenas-b[~]# midclt call boot.update_initramfs '{"database": "/data/freenas-v1.db"}'
expected str, bytes or os.PathLike object, not list
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 198, in call_method
result = await self.middleware.call_with_audit(message['method'], serviceobj, methodobj, params, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1467, in call_with_audit
result = await self._call(method, serviceobj, methodobj, params, app=app,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> NAS-128378 / 24.10 / Fix recent breakage in update_initramfs

src/middlewared/middlewared/plugins/zfs.py, src/middlewared/middlewared/plugins/zfs_/zfs_events.py
* We deprecated and removed an unused private API parameter in SCALE. Said parameter is also unused in 13.3 by both middleware and webui, and since it is a private API there is no guarantee of stability between versions.
* Recent versions of python-libzfs removed __getstate__() methods for python 3.10 compatibilty and replaced with asdict().
=> NAS-128373 / 13.3 / Update ZFS plugin for py-libzfs changes

src/middlewared/middlewared/plugins/failover_/event.py
Discovered by QE during testing. This is a typo, no functional change.
Original PR: https://github.com/truenas/middleware/pull/13588
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128388
=> NAS-128388 / 24.04.0 / fix typo in failover_/event.py (by yocalebo)

src/middlewared/middlewared/plugins/failover_/event.py
Discovered by QE during testing. This is a typo, no functional change.
Original PR: https://github.com/truenas/middleware/pull/13588
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128388
=> NAS-128388 / 24.04.1 / fix typo in failover_/event.py (by yocalebo)

src/middlewared/middlewared/plugins/jbof/crud.py
In NAS-128346 (PR #13469) added an optional `check` parameter to `set_mgmt_ip`.
This did **not** modify the preexisting code that tried to ensure we do not modify a redfish interface thru that _same_ interface.
However, this _will_ be necessary as we could be setting the interfaces to something inaccessible on the local network.
=> NAS-128371 / 24.10 / Do not switch IOMs in set_mgmt_ip when force is True

src/middlewared/middlewared/plugins/jbof/crud.py
In NAS-128346 (PR #13469) added an optional `check` parameter to `set_mgmt_ip`.
This did **not** modify the preexisting code that tried to ensure we do not modify a redfish interface thru that _same_ interface.
However, this _will_ be necessary as we could be setting the interfaces to something inaccessible on the local network.
Original PR: https://github.com/truenas/middleware/pull/13578
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128371
=> NAS-128371 / 24.04.0 / Do not switch IOMs in set_mgmt_ip when force is True (by bmeagherix)

tests/api2/test_009_fenced.py
This test needs to be updated to take advantage of all the improvements that have been added since migrating to the new jenkins. There should be no functional change in behavior.
Original PR: https://github.com/truenas/middleware/pull/13591
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128394
=> NAS-128394 / 24.04.1 / modernize test_009_fenced (by yocalebo)

src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/failover_/datastore.py, src/middlewared/middlewared/plugins/failover_/remote.py, src/middlewared/middlewared/utils/db.py, tests/api2/test_007_early_settings.py
Add options to `failover.send_file` and restrict the `mode` when calling.
Original PR: https://github.com/truenas/middleware/pull/13586
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128374
=> NAS-128374 / 24.04.0 / Add options to failover.send_file (by bmeagherix)

src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/failover_/datastore.py, src/middlewared/middlewared/plugins/failover_/remote.py, src/middlewared/middlewared/utils/db.py, tests/api2/test_007_early_settings.py
Add options to `failover.send_file` and restrict the `mode` when calling.
Original PR: https://github.com/truenas/middleware/pull/13586
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128374
=> NAS-128374 / 24.04.1 / Add options to failover.send_file (by bmeagherix)

src/middlewared/middlewared/plugins/security/update.py, src/middlewared/middlewared/scripts/configure_fips.py
This commit fixes an issue where fips will not toggle value because /usr is not writable and fail.
Original PR: https://github.com/truenas/middleware/pull/13594
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128383
=> NAS-128383 / 24.04.0 / Make sure /usr is writable when making fips changes (by sonicaj)

src/middlewared/middlewared/plugins/security/update.py, src/middlewared/middlewared/scripts/configure_fips.py
This commit fixes an issue where fips will not toggle value because /usr is not writable and fail.
Original PR: https://github.com/truenas/middleware/pull/13594
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128383
=> NAS-128383 / 24.04.1 / Make sure /usr is writable when making fips changes (by sonicaj)

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py, src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/detect_enclosure_freebsd.py, src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/detect_internal_interface_freebsd.py
Add HA KVM detection to CORE, for use in our new KVM/ixnode/jenkins CI.
=> NAS-128444 / 13.3 / Add HA KVM detection (IXKVM)

src/middlewared/middlewared/logger.py, src/middlewared/middlewared/plugins/reporting/netdata/client.py, src/middlewared/middlewared/plugins/reporting/rest.py
git cherry-pick -x 31644bacb2ed5371a4d0bd7eb76c0a64799db075
git cherry-pick -x 2f5f94303352700b988bef59372cb62efd6e9ad2
When Netdata is stopped for any reason, the middleware logs become flooded with connection errors, making it challenging to debug the actual issue.
Create a new Netdata log file to capture all Netdata-related logs. This will prevent the middleware logs from being filled with Netdata logs and help in more efficient debugging.
Original PR: https://github.com/truenas/middleware/pull/13608
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127111
=> NAS-127111 / 24.04.1 / Add separate logfile for netdata (by Qubad786)

tests/api2/test_iscsi.py
This reverts commit 355fb38154cdaf062da8e682bb2f70a98bb951e8.
Underlying issue with this test being addressed in PR #[230 ](https://github.com/truenas/zfs/pull/230)
=> NAS-128469 / 24.10 / Revert "fix iscsi_extent_locked test (#13572)"

tests/api2/test_iscsi.py
This reverts commit 355fb38154cdaf062da8e682bb2f70a98bb951e8.
Underlying issue with this test being addressed in PR #[230 ](https://github.com/truenas/zfs/pull/230)
Original PR: https://github.com/truenas/middleware/pull/13611
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128469
=> NAS-128469 / 24.04.1 / Revert "fix iscsi_extent_locked test (#13572)" (by bmeagherix)

src/middlewared/middlewared/plugins/network.py, src/middlewared/middlewared/plugins/reporting/events.py
In a fresh install, physical interfaces are not stored in the database. When the `reporting.realtime` event tries to retrieve the interface names from the database, it returns an empty list, resulting in network stats not being displayed.
Retrieve all interface names from `interface.query` for reporting events, which obtains interface information directly from the system if interfaces are not stored in the database.
=> NAS-128161 / 24.10 / Get all interface names for reporting

src/middlewared/middlewared/plugins/network.py, src/middlewared/middlewared/plugins/reporting/events.py
In a fresh install, physical interfaces are not stored in the database. When the `reporting.realtime` event tries to retrieve the interface names from the database, it returns an empty list, resulting in network stats not being displayed.
Retrieve all interface names from `interface.query` for reporting events, which obtains interface information directly from the system if interfaces are not stored in the database.
Original PR: https://github.com/truenas/middleware/pull/13577
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128161
=> NAS-128161 / 24.04.1 / Get all interface names for reporting (by Qubad786)

src/middlewared/middlewared/test/integration/assets/iscsi.py, tests/api2/test_iscsi_auth_network.py
Fix a bunch of tests that are failing in CI
- When running `iscsiadm` in tests precede with a `sudo` if we are not running as root.
- Improve _test_iscsi_auth_network.py_ in several ways
- Make `my_ip4` a fixture so it only needs to run once
- Extend `my_ip4` so that it can even handle NAT situations (`ssh` / `SSH_CLIENT`)
- `flake8` fixes
Also required the ZFS fix in PR #[230 ](https://github.com/truenas/zfs/pull/230)
=> NAS-128506 / 24.10 / Fix test iscsi auth network

src/middlewared/middlewared/test/integration/assets/iscsi.py, tests/api2/test_iscsi_auth_network.py
git cherry-pick -x 6f84e7d53f2c70a0b9a3fafdcb72c00b14eb18c2
git cherry-pick -x 7cd26dd90508b219b73f41890002ef5c8f008706
git cherry-pick -x dbbd64f0874452c34715f2244ac027be20106094
Fix a bunch of tests that are failing in CI
- When running `iscsiadm` in tests precede with a `sudo` if we are not running as root.
- Improve _test_iscsi_auth_network.py_ in several ways
- Make `my_ip4` a fixture so it only needs to run once
- Extend `my_ip4` so that it can even handle NAT situations (`ssh` / `SSH_CLIENT`)
- `flake8` fixes
Also required the ZFS fix in PR #[230 ](https://github.com/truenas/zfs/pull/230)
Original PR: …
=> NAS-128506 / 24.04.1 / Fix test iscsi auth network (by bmeagherix)

src/middlewared/middlewared/plugins/smb_/registry_global.py
This was an oversight in angelfish when we first switched to using registry for global parameters. Will not be backported to EE because we are removing this portion of SMB configuration from registry in that release.
=> NAS-128518 / 24.04.1 / Strip whitespace from smb_options before registry insertion

src/middlewared/middlewared/plugins/disk_/availability.py, src/middlewared/middlewared/plugins/webui/enclosure.py
The UI team is currently implementing the changes required to consume `webui.enclosure.dashboard` but they're missing some key items that make it awkward to deal with on their side. This does 3 primary things:
1. add `drive_bay_number` key to `webui.enclosure.dashboard`
2. add `drive_bay_number` and `id` keys to `disk.get_unused`
3. use `device.get_disks` in `disk.get_unused` instead of querying the disk table. The reason why we don't query the database table is because we have seen various edge-cases where disks are updated in kernel but our database doesn't get updated. This is hard to predict and is even harder to properly handle. The kernel already "caches" the disk info that we need so `device.get_disks` goes directly to the source of truth. This method has been optimized …
=> NAS-128546 / 24.10 / Improvements requested by UI team for new enclosure.dashboard

src/freenas/etc/systemd/system/nfsdcld.service.d/override.conf, src/middlewared/middlewared/etc_files/nfs.conf.d/local.conf.mako, src/middlewared/middlewared/plugins/nfs.py, src/middlewared/middlewared/plugins/nfs_/status.py, src/middlewared/middlewared/plugins/service_/services/nfs.py, src/middlewared/middlewared/plugins/system_dataset/hierarchy.py, tests/api2/test_001_ssh.py, tests/api2/test_300_nfs.py
NFS was not configured to properly support HA function.  NFS holds client state information in a database that, by default, is located at /var/lib/nfs.  To properly support failover we need that to be a shared directory.  For TrueNAS that is the system dataset.
Create and NFS entry in the system dataset.  Generate the necessary directory structure and to support upgrade we also initialize it with data from /var/lib/nfs.
In systemd we bind the NFS client tracking daemon to nfs-server to allow the transfer of the client tracking database.
Update the nfs configuration file with the path to the nfs data on the system dataset: `/var/db/system/nfs`
1. Updated the CI tests
2. Minor flake8 cleanup and refactoring
=> NAS-128399 / 24.10 / More nfs failover fixes

src/middlewared/middlewared/plugins/disk_/availability.py, src/middlewared/middlewared/plugins/disk_/info.py, src/middlewared/middlewared/plugins/disk_/sync.py, src/middlewared/middlewared/plugins/disk_/utils.py
https://github.com/truenas/middleware/pull/13622 introduced a subtle regression where-by the `identifier` key wasn't included in the response. I noticed that the function that does this can be moved into its own utility function so that I don't have to go through `self.middleware` to get the information. (self.middleware does incur some overhead and we want this endpoint to be as fast as possible)
I did the same for `get_valid_zfs_partition_type_uuids`.
=> NAS-128636 / 24.10 / add back identifier key to disk.get_unused

src/middlewared/middlewared/etc_files/smartd.py, src/middlewared/middlewared/plugins/smart.py, src/middlewared/middlewared/plugins/smart_/schedule.py, src/middlewared/middlewared/pytest/unit/etc_files/test_smartd.py, src/middlewared/middlewared/pytest/unit/plugins/smart/test_crud.py
`0` is a valid reference to Sunday in `crontab`, but is not a valid reference to Sunday in `smartd.conf`
=> NAS-128593 / 24.10 / Fix generating smartd.conf for items that run on Sundays

src/middlewared/middlewared/etc_files/smartd.py, src/middlewared/middlewared/plugins/smart.py, src/middlewared/middlewared/plugins/smart_/schedule.py, src/middlewared/middlewared/pytest/unit/etc_files/test_smartd.py, src/middlewared/middlewared/pytest/unit/plugins/smart/test_crud.py
`0` is a valid reference to Sunday in `crontab`, but is not a valid reference to Sunday in `smartd.conf`
Original PR: https://github.com/truenas/middleware/pull/13627
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128593
=> NAS-128593 / 24.04.1 / Fix generating smartd.conf for items that run on Sundays (by themylogin)

debian/debian/ix-reporting.service, debian/debian/rules, src/freenas/usr/lib/systemd/system-preset/10-truenas.preset, src/middlewared/middlewared/plugins/failover_/event.py, src/middlewared/middlewared/plugins/reporting/netdata_configure.py
We don't have netdata running on standby node but when passive boots there is a brief window when netdata starts because by default it is enabled to do so and then it leaves a spam in systemd logs.
Make sure netdata does not run on passive node and it only runs on the active node.
=> NAS-128613 / 24.10 / Do not start netdata on boot in HA

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/activedirectory_/cache.py, src/middlewared/middlewared/plugins/cache.py, src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/plugins/filesystem_/perm_check.py, src/middlewared/middlewared/plugins/ldap.py, src/middlewared/middlewared/utils/nss/grp.py, src/middlewared/middlewared/utils/nss/nss_common.py, src/middlewared/middlewared/utils/nss/pwd.py
This allows us to do module-specific NSS operations and provide information to API users about whether the user is local, from AD, or from LDAP server.
The changes are necessary for providing user/group cache for UI / middleware purposes after switching from nslcd to sssd for LDAP integration.
=> NAS-128640 / 24.10 / Add ctypes wrapper for NSS operations

src/middlewared/middlewared/plugins/ldap.py
SSSD does not automatically create its cache directories on startup.
=> NAS-128673 / 24.10 / Fix SSSD startup

src/middlewared/middlewared/plugins/device.py, src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py, src/middlewared/middlewared/plugins/system_advanced/serial.py
We need the ability for this endpoint to return the disk partition information if the `type` is `DISK`. The logic that implements this functionality has existed in our product for quite awhile now but it is behind a private endpoint.
Changes made are:
1. Convert the positional argument of a string and change it to accepting a dictionary object
2. add the 2 new boolean arguments that will be passed along as-is
3. Add a more details docstring (explaining the arguments that apply to the "DISK" type)
4. update the callers of this endpoint since the API has changed
=> NAS-127636 / 24.10 / Expose API arguments to device.get_info

src/middlewared/middlewared/alert/source/memory_errors.py
Class was created in PR #13285, but no level was set.
This caused the following error in CI tests:
```
FAILED api2/test_050_alert.py::test_02_get_alert_list_categories - AssertionError: {
"message": "'NotImplementedType' object has no attribute 'name'",
"traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/middlewared/restful.py\", line 849, in do\n    result = await self.middleware.call_with_audit(methodname, serviceobj, methodobj, method_args,\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/middlewared/main.py\", line 1477, in call_with_audit\n    result = await self._call(method, serviceobj, methodobj, params, app=app,\n …
```
=> NAS-128717 / 24.10 / Add missing level to MemorySizeMismatchAlertClass

tests/api2/test_030_activedirectory.py
Noticed the following error being raised in CI tests
```
ERROR api2/test_030_activedirectory.py::test_10_account_privilege_authentication - Failed: fixture function has more than one 'yield':
@pytest.fixture(scope="function")
def set_product_type(request):
if ha:
yield
with product_type():
yield
/home/jenkins/scale_build/master/api_tests/224/middleware/tests/api2/test_030_activedirectory.py:118
```
Introduced by PR #13236, so just give a minor tweak to keep that fix without introducing the above error.
=> NAS-128716 / 24.10 / Only have one yield in fixture

tests/api2/test_030_activedirectory.py
Noticed the following error being raised in CI tests
```
ERROR api2/test_030_activedirectory.py::test_10_account_privilege_authentication - Failed: fixture function has more than one 'yield':
@pytest.fixture(scope="function")
def set_product_type(request):
if ha:
yield
with product_type():
yield
/home/jenkins/scale_build/master/api_tests/224/middleware/tests/api2/test_030_activedirectory.py:118
```
Introduced by PR #13236, so just give a minor tweak to keep that fix without introducing the above error.
Original PR: https://github.com/truenas/middleware/pull/13646
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128716
=> NAS-128716 / 24.04.1 / Only have one yield in fixture (by bmeagherix)

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/cache.py, src/middlewared/middlewared/plugins/cron.py, src/middlewared/middlewared/plugins/idmap.py, src/middlewared/middlewared/plugins/pool_/dataset_quota_and_perms.py, src/middlewared/middlewared/plugins/rsync.py
For historical reasons this methods were originally a thin wrapper around dscache.get_uncached_user and dscache.get_uncached_group methods. There are no longer any direct callers of the private methods and so we can elmininate the wrapper and save an internal middleware call.
=> NAS-128712 / 24.10 / Simplify user.get_user_obj and group.get_group_obj

debian/debian/postinst
Disable auto-start of nslcd in the Dragonfish release.
The LDAP module manages the start and stop of nslcd as necessary.
_This should not be forward ported._
=> NAS-128651 / 24.04.1 / Disable nslcd auto-start in Dragonfish

src/middlewared/middlewared/alert/source/update.py
git cherry-pick -x e3dca01c5f2dd80641992386f518787201751c2d
git cherry-pick -x 8ca93f139a9092a4e525b013b14e54305883fd3e
There is no reason to have this alert if TrueNAS does not have an internet connection.
Original PR: https://github.com/truenas/middleware/pull/13653
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128692
=> NAS-128692 / 24.04.1 / Skip `Update Available` errors (by themylogin)

src/middlewared/middlewared/plugins/catalogs_linux/update.py
24.04.0 was released to the wild and we immediately got reports of increased CPU usage when browsing to the APPs web page. The UI team found that they had made a mistake by calling `chart.release.query` in a tight loop. While this is the "cause" of the increased CPU usage, it's not the root of why it's occurring. Further investigation showed me a cascading set of problems that built on one another.
1. UI called `chart.release.query` in a tight loop
2. `chart.release.query` called `catalog.query`
3. `catalog.query` called `zfs.dataset.query`
4. `zfs.dataset.query` is in the zfs plugin, so it gets executed in our process pool
5. because this was happening in a tight loop, our process pool became exhausted (each process in the pool will execute 5 tasks before being torn down and a new child …
=> NAS-128752 / 24.04.1 / fix catalog.query to stop calling zfs.dataset.query

src/middlewared/middlewared/plugins/catalogs_linux/update.py
24.04.0 was released to the wild and we immediately got reports of increased CPU usage when browsing to the APPs web page. The UI team found that they had made a mistake by calling `chart.release.query` in a tight loop. While this is the "cause" of the increased CPU usage, it's not the root of why it's occurring. Further investigation showed me a cascading set of problems that built on one another.
1. UI called `chart.release.query` in a tight loop
2. `chart.release.query` called `catalog.query`
3. `catalog.query` called `zfs.dataset.query`
4. `zfs.dataset.query` is in the zfs plugin, so it gets executed in our process pool
5. because this was happening in a tight loop, our process pool became exhausted (each process in the pool will execute 5 tasks before being torn down and a new child …
=> NAS-128752 / 24.10 / fix catalog.query to stop calling zfs.dataset.query (by yocalebo)

src/middlewared/middlewared/plugins/container_runtime_interface/client.py
This PR adds changes to better validate the response a docker registry sends for image digests as we have seen a rare case where the response was malformed which resulted in a `KeyError` whereas it should have been properly raised instead.
=> NAS-127946 / 24.10 / Improve validation of docker returned response when retrieving image manifests

src/middlewared/middlewared/plugins/catalogs_linux/update.py
This commit fixes an issue where we were not retrieving the correct catalog dir which resulted in catalog related operations to fail.
=> NAS-128787 / 24.10 / Fix catalog.query

src/middlewared/middlewared/plugins/activedirectory.py
This commit fixes an issue where we have a method which consumes a dict (`AD_SMBCONF_PARAMS`) which no longer exists. Changes were introduced in https://github.com/truenas/middleware/pull/13640 which make up for the usages of this method and this method is no longer used.
=> NAS-128786 / 24.10 / Fix breakage in AD

src/middlewared/middlewared/plugins/catalogs_linux/update.py
This commit fixes an issue where we were not retrieving the correct catalog dir which resulted in catalog related operations to fail.
Original PR: https://github.com/truenas/middleware/pull/13664
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128787
=> NAS-128787 / 24.04.1 / Fix catalog.query (by sonicaj)

src/middlewared/middlewared/main.py
Back in 23.10 I changed this setting to 5. (c.f. ced399a41ca). This has proven to be fine, however, we have had quite a few users from the community express "higher CPU usage" after upgrading to 24.04.0. (c.f. https://github.com/truenas/middleware/pull/13660 for details).
During the investigation of this problem, I've realized that I can further reduce the CPU usage by bumping this setting a bit. This is not a _solution_ but is a band-aid. There are tradeoffs with changing this. Lowering the value here means, less memory consumption for the total uptime of middlewared but increase CPU usage. Bumping this will lessen the CPU usage, but will increase the memory consumption. This value is based off anecdotal investigation on a dual-core CPU system that reproduced the "higher CPU usage" …
=> NAS-128762 / 24.10 / bump max_tasks_per_child to 20

src/middlewared/middlewared/main.py
Back in 23.10 I changed this setting to 5. (c.f. ced399a41ca). This has proven to be fine, however, we have had quite a few users from the community express "higher CPU usage" after upgrading to 24.04.0. (c.f. https://github.com/truenas/middleware/pull/13660 for details).
During the investigation of this problem, I've realized that I can further reduce the CPU usage by bumping this setting a bit. This is not a _solution_ but is a band-aid. There are tradeoffs with changing this. Lowering the value here means, less memory consumption for the total uptime of middlewared but increase CPU usage. Bumping this will lessen the CPU usage, but will increase the memory consumption. This value is based off anecdotal investigation on a dual-core CPU system that reproduced the "higher CPU usage" …
=> NAS-128762 / 24.04.1 / bump max_tasks_per_child to 20 (by yocalebo)

src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/util_param.py
Users will sometimes set completely invalid global SMB auxiliary parameters in the smb plugin such as "oplocks = no # does this work".
This is rejected by libparam and breaks samba entirely if written as-is. This commit improves validation by running global parameters through loadparm_ctx.set() so that we can check both the parameter name and its value.
=> NAS-128800 / 24.10 / Improve validation of SMB options

src/middlewared/middlewared/plugins/etc.py, src/middlewared/middlewared/pytest/unit/utils/test_write_if_changed.py, src/middlewared/middlewared/utils/io.py
1. use os.rename to overwrite config files. Avoid possibility of having applications read partially written configuration files by first writing the changed config to a temporary file, then renaming over existing file.
2. have write_if_changed allow specifying the desired permissions and ownership of the file. This allows us to ensure that ownership and permissions changes happen before we close and rename the file.
3. alter return value for write_if_changed from boolean indicating whether changes were written to a bitmask of changes made. This allows us to flag when permissions and ownership had to be altered (logging potentially unexpected CLI changes).
4. add optional non-default parameter to raise an exception if we had to change ownership and permissions. This exception can be used …
=> NAS-128802 / 24.10 / Improve configuration file generation

src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/plugins/pwenc.py
`file_receive` was susceptible to the TOCTOU race conditions when checking for a paths existence (or any path component) before opening said path. This should get rid of theoretical conditions and also switches to using the `fchmod`/`fchown` syscalls. I've also fixed a few flake8 issues while I'm here. There should be no functional change.
Original PR: https://github.com/truenas/middleware/pull/13600
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128404
=> NAS-128404 / 24.04.1 / Improve file receive (by yocalebo)

src/middlewared/middlewared/plugins/filesystem.py
Fix problem introduced by #13600 
Also fix a `flake8` complaint.
Fortunately the backport of the above PR (#13671) did **not** introduce the same issue.
----
Can see 
```
middlewared.service_exception.CallError: [EFAULT] name 'pwd' is not defined
```
[here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/271/console)
=> NAS-128827 / 24.10 / Re-add recently removed import of pwd, grp

src/middlewared/middlewared/pytest/unit/utils/test_nss.py, src/middlewared/middlewared/utils/nss/grp.py, src/middlewared/middlewared/utils/nss/pwd.py
We were omitting first NSS entry. Add basic CI tests to ensure
that our pwd and grp output matches what is expected from base
python module.
=> NAS-128828 / 24.10 / Fix off-by-one in getpwall and getgrall

src/middlewared/middlewared/etc_files/krb5.keytab.py, src/middlewared/middlewared/plugins/etc.py
We should use standard etc plugin methods to write kerberos keytab. This allows monitoring unexpected changes to permissions, owner, etc.
=> NAS-128838 / 24.10 / Use proper util for writing kerberos keytab

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py, src/middlewared/middlewared/plugins/kubernetes_linux/update.py
Since Cobia, users that use apps with a bridge interface have been broken because `kubernetes.validate_interfaces` was too strict on checking whether or not the interface is LINK_STATE_UP. It would only check once and then bail out.
This makes it so that instead of bailing out immediately when the interface isn't up, we actually wait for a bit for it to come online. This was reproduced on a system 100% of the time and after these changes, apps successfully started after a reboot.
I took the liberty to improve this method while we're here because it was calling `interface.query` too many times for no reason.
Finally, and arguably the most frustrating part of this endeavor is that, I fixed the fact that `kubernetes.validate_k8s_fs_setup` was swallowing errors from `validate_interfaces`. It …
=> NAS-127870 / 24.10 / fix starting apps with a bridge interface

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py, src/middlewared/middlewared/plugins/kubernetes_linux/update.py
Since Cobia, users that use apps with a bridge interface have been broken because `kubernetes.validate_interfaces` was too strict on checking whether or not the interface is LINK_STATE_UP. It would only check once and then bail out.
This makes it so that instead of bailing out immediately when the interface isn't up, we actually wait for a bit for it to come online. This was reproduced on a system 100% of the time and after these changes, apps successfully started after a reboot.
I took the liberty to improve this method while we're here because it was calling `interface.query` too many times for no reason.
Finally, and arguably the most frustrating part of this endeavor is that, I fixed the fact that `kubernetes.validate_k8s_fs_setup` was swallowing errors from `validate_interfaces`. It …
=> NAS-127870 / 24.04.1 / fix starting apps with a bridge interface (by yocalebo)

src/middlewared/middlewared/plugins/etc.py, src/middlewared/middlewared/pytest/unit/utils/test_write_if_changed.py, src/middlewared/middlewared/utils/io.py
This is beginning of plumbing for better tracking of configuration file changes that are made by middlewared.
```
root@truenas[~/middleware/src/middlewared]# midclt call etc.generate smb
[]
root@truenas[~/middleware/src/middlewared]# chmod 700 /etc/smb4.conf 
root@truenas[~/middleware/src/middlewared]# midclt call etc.generate smb
[{"path": "/etc/smb4.conf", "status": "CHANGED", "changes": ["PERMS"]}]
```
=> NAS-128835 / 24.10 / Add framework to have etc.generate return list of changes

src/freenas/etc/logrotate.d/netdata_override, src/middlewared/middlewared/etc_files/syslog-ng/syslog-ng.conf.mako
We have different log filters specified where we want to make sure that different sources i.e k3s/scst etc do not pollute other log files with their messages but unfortunately what in reality is happening is that we have their logs being logged to separate files but they are still getting logged in other log files i.e daemon.log etc which indicates that logs are being copied rather then redirected completely.
Add changes to make sure we don't process other log filters if we have a match for a filter earlier and once we have gone through our custom log file solutions we can finally have rest of the filters for other log files being processed.
=> NAS-128631 / 24.10 / Make sure we redirect logs to relevant log files instead of copying them

src/freenas/etc/logrotate.d/netdata_override, src/middlewared/middlewared/etc_files/syslog-ng/syslog-ng.conf.mako
git cherry-pick -x a056d0faef2c8ad3fbcae3b7b7a3b2c848b9f230
git cherry-pick -x 463f87b4593024afa88a0a675bd60b39154f6ace
git cherry-pick -x 0b48ec03e43c026e3b7b526b3230346a568c42d7
We have different log filters specified where we want to make sure that different sources i.e k3s/scst etc do not pollute other log files with their messages but unfortunately what in reality is happening is that we have their logs being logged to separate files but they are still getting logged in other log files i.e daemon.log etc which indicates that logs are being copied rather then redirected completely. …
=> NAS-128631 / 24.04.1 / Make sure we redirect logs to relevant log files instead of copying them (by Qubad786)

tests/api2/test_iscsi_auth_network.py
Tested against [SINGLE](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/317/) and [HA](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/318/).
=> NAS-128879 / 24.10 / Make tests HA compatible using truenas_server.ip

tests/api2/test_iscsi_auth_network.py
Tested against [SINGLE](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/317/) and [HA](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/318/).
Original PR: https://github.com/truenas/middleware/pull/13690
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128879
=> NAS-128879 / 24.04.2 / Make tests HA compatible using truenas_server.ip (by bmeagherix)

src/middlewared/middlewared/plugins/idmap.py, src/middlewared/middlewared/plugins/smb.py
Recent refactoring of SMB plugin overly reduced places where we regenerate the smb.conf file and restart SMB. When create a homes share we need to rewrite winbindd's template homedir parameter in the smb configuration before clearing caches and restarting winbindd.
Otherwise, the NSS plugin doesn't pick up the home directory changes and attempts to access home dir fails with ENOENT.
=> NAS-128884 / 24.10 / Fix home shares connectivity when AD enabled

tests/api2/test_030_activedirectory.py, tests/requirements.txt
CI test runs against HA were failing some tests in _test_030_activedirectory.py_ (e.g. `test_07_enable_leave_activedirectory`).  Modernize and tweak so that they work against both single-node and HA.
Note: had to add `dnspython` to the test requirements.txt in order to be able to trap `dns.resolver.NXDOMAIN` exceptions.
=> NAS-128839 / 24.10 / Fix modernize ad tests

src/middlewared/middlewared/test/integration/utils/system.py, tests/api2/test_300_nfs.py
It's been found that under some test scenarios systemd services need to be reset.
Added `reset_systemd_svcs` to do just that.
=> NAS-128895 / 24.10 / Move reset svcs  to middleware test utils

src/middlewared/middlewared/plugins/smb.py
Test `test_056_netbios_name_change_check_sid` was failing because the _smb4.conf_ file was not being rewritten (with the new `netbiosname`).  Rectify.
Also `flake8` fixes.
=> Fix test 056 netbios name change check sid

src/middlewared/middlewared/plugins/smb.py
This commit make two minor changes regarding time machine:
1. Always generate a volume UUID when creating a new SMB share. This field is only used in mDNS SRV record for the time machine service. Netatalk historically would regenerate the VUID on service restart without apparent issues. MacOS SMB servers generate randomized VUID on time machine share creation. This is slightly more aggressive than legacy behavior (which generated as-needed) but is consistent with MacOS behavior.
2. Ensure that `timemachine` is always flagged as True when our timemachine-related presets are used.
Original PR: https://github.com/truenas/middleware/pull/13696
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128892
=> NAS-128892 / 24.04.2 / Minor time machine quality of life fixes (by anodos325)

src/middlewared/middlewared/logger.py, src/middlewared/middlewared/plugins/container_runtime_interface/update_alerts.py
Changes have been made to add image's registry errors to separate file `/var/log/container_images.log` to avoid unnecessary noise in middleware logs.
=> NAS-128822 / 24.10 / Log container registry exceptions in separate file

src/middlewared/middlewared/plugins/pool_/import_pool.py
Import the pools during boot without mounting any of the datasets. Check on 'feature@encryption' for imported pool. If feature is not active, recursively mount the root datasets, which effectively mounts all datasets present on the pool.
If the encryption feature is active, continue and unlock the datasets.
=> NAS-127702 / 24.10 / Recursively mount root dataset during boot if it is not encrypted

tests/api2/test_007_early_settings.py
Newly added integration test checks the permission of `/data` dir and its contents to ensure that perms are like below: 
1. `u=rwX,g=,o=` on `/data` recursively ensuring every dir inside has `0o700` perms and every file has `0o600`
2. `0o755` on just `/data` itself
3. `0o755` recursively on `/data/subsystems`
Scale build change was added in the [PR](https://github.com/truenas/scale-build/pull/635).
=> NAS-128851 / 24.10 / Enhance permissions check on data directory

tests/api2/test_330_pool_acltype.py, tests/api2/test_340_pool_dataset.py, tests/api2/test_345_acl_nfs4.py, tests/api2/test_347_posix_mode.py, tests/api2/test_348_posix_acl.py, tests/api2/test_350_pool_dataset_quota_alert.py, tests/api2/test_420_smb.py, tests/api2/test_425_smb_protocol.py, tests/api2/test_427_smb_acl.py, tests/api2/test_428_smb_rpc.py, tests/api2/test_430_smb_sharesec.py, tests/api2/test_450_staticroutes.py, tests/api2/test_470_system.py, tests/protocols/ms_rpc.py, tests/protocols/nfs_proto.py, tests/protocols/smb_proto.py
Various test functions have now been modified to allow omitting the host IP (which in HA forces use of virtual IP).
This commit updates many tests to use the new functionality so that we have fewer failures on HA.
=> NAS-128983 / 24.10 / Fix several API test files for HA

src/middlewared/middlewared/plugins/disk_/swap_configure.py
This is a safety belt for 24.04.1. A more involved and proper fix will follow but this solves the immediate issue.
NOTE: if a user wants to re-enable the swap partition(s), they will need to run `swapon -a` manually or use a post-init script (which is what the overwhelming majority of users are doing on the forums, except they're doing `swapoff -a` :smile: )
=> NAS-128988 / 24.04.1 / disable swap by default

src/freenas/etc/sysctl.d/10-truenas.conf
It should allow system to swap anonymous pages actively when it is one step from OOM, while otherwise prefer to flush file-backed pages back into ZFS ARC, freeing more memory for it.
=> NAS-128788 / 24.10 / Set vm.swappiness=1

src/middlewared/middlewared/plugins/chart_releases_linux/schema.py, src/middlewared/middlewared/pytest/unit/plugins/chart_releases/test_chart_releases_schema.py
This commit fixes an issue where when we change max to max_ in middleware api for validators, this change was not addressed.
=> NAS-128590 / 24.10 / Fix Range validator args

src/middlewared/middlewared/plugins/chart_releases_linux/schema.py, src/middlewared/middlewared/pytest/unit/plugins/chart_releases/test_chart_releases_schema.py
This commit fixes an issue where when we change max to max_ in middleware api for validators, this change was not addressed.
Original PR: https://github.com/truenas/middleware/pull/13705
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128590
=> NAS-128590 / 24.04.1 / Fix Range validator args (by sonicaj)

src/middlewared/middlewared/plugins/chart_releases_linux/schema.py, src/middlewared/middlewared/pytest/unit/plugins/chart_releases/test_chart_releases_schema.py
This commit fixes an issue where when we change max to max_ in middleware api for validators, this change was not addressed.
Original PR: https://github.com/truenas/middleware/pull/13705
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128590
=> NAS-128590 / 24.04.2 / Fix Range validator args (by sonicaj)

src/middlewared/middlewared/plugins/reporting/netdata_configure.py
If someone resets the configuration database to defaults, middlewared service will not start-up on config upload. The reason why is because the netdata plugin isn't handling this specific case. This does 2 things:
1. be extra safe and catch all exceptions here so that we don't prevent the middlewared service from starting
2. use the proper methods to return the builtin user `netdata`
=> NAS-128998 / 24.04.2 / prevent middleware service from starting when config is reset

src/middlewared/middlewared/plugins/disk_/swap_configure.py
This is a safety belt for 24.04.1. A more involved and proper fix will follow but this solves the immediate issue.
NOTE: if a user wants to re-enable the swap partition(s), they will need to run `swapon -a` manually or use a post-init script (which is what the overwhelming majority of users are doing on the forums, except they're doing `swapoff -a` :smile: )
Original PR: https://github.com/truenas/middleware/pull/13710
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128988
=> NAS-128988 / 24.04.2 / disable swap by default (by yocalebo)

src/middlewared/middlewared/plugins/disk_/swap_configure.py
This crashes with `FileNotFoundError` because the argument to the function is a string.
=> NAS-129012 / 24.04.1 / fix swapoff typo

src/middlewared/middlewared/plugins/disk_/swap_configure.py
This crashes with `FileNotFoundError` because the argument to the function is a string. 
Original PR: https://github.com/truenas/middleware/pull/13732
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129012
=> NAS-129012 / 24.04.2 / fix swapoff typo (by yocalebo)

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
WebSocket connections require a long-running connection between the client and server. When using WebSocket connections with a reverse proxy in Nginx, a problem arises because reverse proxy connections follow the hop-by-hop protocol, meaning they open once and then close. To upgrade this connection to support WebSocket, the Upgrade header is used, which keeps the connection open on every hop. The main issue in the code is that we are not closing the connection ever. It remains open because this header is hard-coded. As a result, when a user opens their VM display more than 1000 times without rebooting, they start experiencing problems with the display.
Close the WebSocket connection when `http_upgrade` is none.
https://stackoverflow.com/questions/49488091/getting-connection-reset-by-peer-w …
=> NAS-128993 / 24.10 / Enhance WebSocket Handling with Dynamic Connection Header for VM Display devices

src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/pytest/unit/utils/test_statx.py, src/middlewared/middlewared/utils/filesystem/directory.py, src/middlewared/middlewared/utils/filesystem/stat_x.py
Bitwise comparisons with IntFlag enum types can incur significant cost if performing it repeatedly since it requires creating a new enum instance. Avoid this where possible. This also improves API for statx to make it more consistent with syscall interface.
=> NAS-129019 / 24.10 / More statx improvements

src/middlewared/middlewared/plugins/filesystem_/acl.py
It appears that there were a few instances where we had converted log messages to CallError without converting to an fstring.
=> NAS-129033 / 24.10 / Fix CallError arguments in ACL plugin

src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
It appears that there were a few instances where we had converted log messages to CallError without converting to an fstring.
Original PR: https://github.com/truenas/middleware/pull/13739
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129033
=> NAS-129033 / 24.04.2 / Fix CallError arguments in ACL plugin (by anodos325)

tests/api2/test_zzz_tests_completed.py
We have noticed some CI runs stalling right at the end of the `pytest` run.
For example, the following might have been printed to the console
```
...
...
= 50 failed, 1823 passed, 241 skipped, 4 warnings, 52 errors, 2 rerun in 10048.89s (2:47:28) =
```
Examination of the CI host system shows that the `pytest` command was still running.  It appears that that it stalled during its exit.  One potential cause for this is non-daemon threads that are still running.
This (pseudo) test is to gather some information immediately before finishing a `pytest` run.  Hopefully it will aide us track down the source of the stalls (if indeed caused by threads).
=> NAS-129027 / 24.10 / Add some tests to check the state of things before all tests are done

src/middlewared/middlewared/plugins/disk_/format.py
Found that CI test `test_002_create_permanent_zpool` started (intermittently) failing recently (following PR #13695 I believe).
The headline was
```
AssertionError: Unable to create test pool: ClientException("[Errno 2] No such file or directory: '/sys/block/sdf/sdf1/start'"). Aborting tests.
```
Reintroducing the `device.settle_udev_events` call removed in the above PR seems to rectify the issue.
----
Tested in CI runs #[399 ](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/399/) and #[400](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/400/)
=> NAS-129028 / 24.10 / Reintroduce device.settle_udev_events to avoid race

src/middlewared/middlewared/async_validators.py, src/middlewared/middlewared/pytest/unit/test_validators.py, src/middlewared/middlewared/validators.py
Convert `check_path_resides_within_volume` to a wrapper around a synchronous validator `check_path_resides_within_volume_sync` since basically all of logic there relies on stat-related calls.
=> NAS-129038 / 24.10 / Add synchronous version of standard path validator

src/middlewared/middlewared/plugins/zfs_/utils.py, tests/api2/test_zfs_dataset_list.py
… set
Original PR: https://github.com/truenas/middleware/pull/13742
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129042
=> NAS-129042 / 24.04.2 / Do not crash `zfs.dataset.unlocked_zvols_fast` when `volmode=full` is… (by themylogin)

src/middlewared/middlewared/plugins/disk_/format.py, src/middlewared/middlewared/plugins/disk_/wipe.py
As pointed out in recent PR: https://github.com/truenas/middleware/pull/13738, `device.settle_udev_events` is needed (sporadically) after partitioning disks. The reason why is that certain operations will generate udev events. We try to access the information before those events have been processed and so sysfs information will not be complete.
The problem by calling `settle_udev_events` is that it will tell udev to drain the entire event queue. The queue holds information for ALL hardware and related events. This means, depending on what the system is doing at the time this is called, it can block and wait for 120 seconds (default timeout).
This PR changes it so that `disk.get_partitions_quick` actually tries 10 times (maximum) for the sysfs files to be generated. While I'm here, I …
=> NAS-129045 / 24.10 / Improve disk.get_partitions_quick

tests/api2/test_014_failover_related.py, tests/api2/test_200_ftp.py, tests/api2/test_261_iscsi_cmd.py, tests/api2/test_278_freeipa.py, tests/api2/test_300_nfs.py, tests/api2/test_330_pool_acltype.py, tests/api2/test_440_snmp.py, tests/api2/test_audit_basic.py
In an earlier commit `ip` was removed from auto_conf generated by runtest.py. This exposed several remaining usages of it in our tests when running as a non-HA that were not caught in earlier testing.
=> NAS-129046 / 24.10 / Fix several test regressions due to removing ip

tests/protocols/smb_proto.py
Some of protocols functions wrap around `smbclient` rather than using python bindings. Ensure that virtual IP is used.
=> NAS-129056 / 24.10 / Fix VSS and SMB quota tests for HA

src/middlewared/middlewared/plugins/vm/devices/cdrom.py
Changes have been added to enhance validation for CDROM devices and avoid adding path which are not a file or are not under `/mnt`.
=> NAS-128961 / 24.10 / Improve CDROM device validation

src/middlewared/middlewared/etc_files/netdata/netdata.conf.mako, src/middlewared/middlewared/plugins/reporting/rest.py, src/middlewared/middlewared/plugins/reporting/utils.py, src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
cgroups plugin enabled useful stats (CPU, Memory and Disk activity) for systemd services and VMs.
Overhead of this plugin seems to be minimal to always enable it.
In the future we might consider making the plugins configurable.
This plugin was research as part of SOLN-230.
=> NAS-128723 / 24.10 / Enable cgroups plugin

src/middlewared/middlewared/plugins/interface/configure.py, src/middlewared/middlewared/plugins/network.py, tests/api2/test_005_interface.py
When creating a network interface, the system automatically configures IPv6 despite the default setting being False. In the UI, this creates an issue where the "Autoconfigure IPv6" checkbox is unchecked but the value under /proc/sys/net/ipv6/conf/[interface]/autoconf is 1.
This is also true of DHCP, but was fixed in the UI by setting the value to True specifically if we haven't created/configured the interface yet. I applied the same fix to ipv6_auto. I've also made it set the proper /proc/.../autoconf value when an existing interface is updated so the user's settings are respected.
=> NAS-128634 / 24.10 / Show IPv6 autoconf default, also reflect preference with sysctl

src/middlewared/middlewared/plugins/disk_/wipe.py
```
[2024/05/18 09:04:43] (ERROR) DiskService.get_partitions_quick():57 - Unexpected failure gathering partition info
File "/usr/lib/python3/dist-packages/middlewared/plugins/disk_/wipe.py", line 50, in get_partitions_quick
part_num = int((partdir / 'partition').read_text().strip())
~~~~~~~~^~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'posix.DirEntry' and 'str'
```
=> NAS-129112 / 24.10 / fix TypeError crash in disk.wipe

src/middlewared/middlewared/plugins/activedirectory.py
Remove some legacy behavior from before the secrets plugin was refactored to use common APIs for tdb plugin. When we leave AD our secrets entries are automatically deleted from secrets.tdb. Simply performing backup will also force them to be removed from our config file as well.
=> NAS-129118 / 24.10 / Fix log spam during AD leave

src/middlewared/middlewared/etc_files/local/sudoers.mako, src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnaudit.conf.mako, src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnfilters.conf.mako, src/middlewared/middlewared/plugins/audit/audit.py, src/middlewared/middlewared/plugins/audit/schema/sudo.py, src/middlewared/middlewared/plugins/audit/utils.py, tests/api2/test_audit_sudo.py
Add audit support for `sudo`
- Turn on JSON logging in _/etc/sudoers_, including logging sub commands (e.g. commands issued after `sudo bash`)
- Tweak the generation of _/etc/syslog-ng/conf.d/_{_tnaudit.conf_,_tnfilters.conf_}.  Unlike when we are adding audit support to our own code, we are not changing the events generated by sudo, merely **_mapping_** them into our audit framework.  So, several hand-rolled `filter`, `parser`, `rewrite `and `log`.  Also some code to allow suppressing the usual boilerplate.
- Add tests
=> NAS-128825 / 24.10 / Add auditing for sudo

src/middlewared/middlewared/plugins/smb.py
This commit fixes an issue where if a path in smb share did not exist, we were running an alert source which errored out and resulted in middleware spam and the alert source execution failing as well.
```
[2024/05/20 16:55:12] (ERROR) middlewared.check():138 - Failed to validate path field
File "/usr/lib/python3/dist-packages/middlewared/alert/source/smb.py", line 133, in check
await self.middleware.call(
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1575, in call
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1428, in _call
return await methodobj(*prepared_call.args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/service/sharing_service.py …
```
=> NAS-129126 / 24.10 / Do not spam middleware logs if path does not exist in smb share

src/middlewared/middlewared/plugins/smb.py
This commit fixes an issue where if a path in smb share did not exist, we were running an alert source which errored out and resulted in middleware spam and the alert source execution failing as well.
```
[2024/05/20 16:55:12] (ERROR) middlewared.check():138 - Failed to validate path field
File "/usr/lib/python3/dist-packages/middlewared/alert/source/smb.py", line 133, in check
await self.middleware.call(
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1575, in call
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1428, in _call
return await methodobj(*prepared_call.args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/service/sharing_service.py …
```
=> NAS-129126 / 24.04.2 / Do not spam middleware logs if path does not exist in smb share (by sonicaj)

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako, src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/truecommand/wireguard.py
This PR adds changes to backport some of the fixes which were made to SCALE and not backported to CORE and also fix an issue where wireguard service started on standby whenever the service was started on active. Reason behind that was that we propagate service actions to standby automatically by default and that is not desirable in this case as wireguard should only be running on 1 node at a time. To address that `truecommand` has been added to list of blacklisted services which shouldn't be touched when any of the service verb is called for it.
An edge case for nginx config has also been handled where we were not adding wireguard interface ip to listen directive on failover and a subsequent nginx config reload was warranted because of that.
Original PR: …
=> NAS-128704 / 24.10 / Fix truecommand issues on HA

src/middlewared/middlewared/etc_files/local/avahi/services/ADISK.service.py, src/middlewared/middlewared/etc_files/local/avahi/services/SMB.service.py, src/middlewared/middlewared/etc_files/local/avahi/services/nut.service.py, src/middlewared/middlewared/plugins/etc.py, src/middlewared/middlewared/plugins/service_/services/ups.py, src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/utils.py, src/middlewared/middlewared/utils/mdns.py, tests/api2/test_310_service_announcement.py
Use our own mako infrastructure to handle the mDNS SRV record for the NUT service.  This will override the file installed by the upstream debian package, and will only be present when UPS is configured/running.
Also include make several small fixes to allow unit tests pass.
=> NAS-129065 / 24.10 / Handle mDNS SRV record for NUT service

src/middlewared/middlewared/plugins/failover_/zpool_cachefile.py, src/middlewared/middlewared/plugins/system/product.py
Noticed that a CI test (`test_007_early_settings.test_data_dir_perms`, #13707) was failing because of the mode of _/data/license_ in a HA system.
Fix that particular issue.  (Other issues remain.)
=> NAS-129152 / 24.10 / Fix /data/license perms

src/middlewared/middlewared/plugins/disk_/swap_configure.py
`shell=True` is not allowed since we're doing asyncio based fork+exec'ing.....(gross). Anyways, properly run the command by putting params in a list.
=> NAS-129148 / 24.04.2 / no really disable swap

src/middlewared/middlewared/plugins/disk_/swap_configure.py
`shell=True` is not allowed since we're doing asyncio based fork+exec'ing.....(gross). Anyways, properly run the command by putting params in a list.
Original PR: https://github.com/truenas/middleware/pull/13774
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129148
=> NAS-129148 / 24.04.1 / no really disable swap (by yocalebo)

src/middlewared/middlewared/plugins/vm/utils.py, src/middlewared/middlewared/plugins/vm/vms.py
A user switched from virtualization supported TN system to virtualization not supported and encountered this issue where he couldn't query and  then remove the VMs from the TN system. 
PR adds the change to enable deletion of VMs even if virtualization is not supported. After the changes vm query will show the existing VMs but in error state like below. 
`"status": {
"state": "ERROR",
"pid": null,
"domain_state": "ERROR"
}`
=> NAS-128941 / 24.10 / Allow VM deletion if virtualization is not supported

tests/api2/test_011_user.py
Broken during a recent refactor (#13491).
Without additional with `pytest.raises(ValidationErrors):` we were jumping out on the first exception and not testing the remaining (expected) failures.
=> NAS-129164 / 24.10 / Fix (recently) broken test test_058_create_new_user_knownfails

src/middlewared/middlewared/pytest/unit/utils/test_nss.py, src/middlewared/middlewared/utils/nss/grp.py, src/middlewared/middlewared/utils/nss/pwd.py
Found that the nss wrapper pwd and grp were not failing in exactly the same manner as python builtin equivalents
For example:
```
>>> from middlewared.utils.nss import pwd
>>> import pwd as pypwd
>>>
>>> pwd.getpwuid(0)
struct_passwd(pw_name='root', pw_uid=0, pw_gid=0, pw_gecos='root', pw_dir='/root', pw_shell='/usr/bin/zsh', source='FILES')
>>> pypwd.getpwuid(0)
pwd.struct_passwd(pw_name='root', pw_passwd='x', pw_uid=0, pw_gid=0, pw_gecos='root', pw_dir='/root', pw_shell='/usr/bin/zsh')
>>>
>>> pypwd.getpwuid(-1)
  File "<stdin>", line 1, in <module>
KeyError: 'getpwuid(): uid not found: -1'
>>>
>>> pwd.getpwuid(-1)
  File "<stdin>", line 1, in <module>
  File …
```
=> NAS-129170 / 24.10 / Fix nss wrapper

src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py
Found that `ValueError` was being raised by the type of lookup we were doing.
=> NAS-129171 / 24.10 / Also catch ValueError when looking up JbofModels

src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py
Found that `ValueError` was being raised by the type of lookup we were doing.
Original PR: https://github.com/truenas/middleware/pull/13782
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129171
=> NAS-129171 / 24.04.1 / Also catch ValueError when looking up JbofModels (by bmeagherix)

src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py
Found that `ValueError` was being raised by the type of lookup we were doing.
Original PR: https://github.com/truenas/middleware/pull/13782
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129171
=> NAS-129171 / 24.04.2 / Also catch ValueError when looking up JbofModels (by bmeagherix)

tests/api2/test_435_smb_registry.py
A recent PR (#13696) means that a `ENHANCED_TIMEMACHINE` share requires `aapl_extentions` to be enabled.  Make it so.
=> NAS-129172 / 24.10 / Add setup_aapl_extensions to prevent test ERROR

src/middlewared/middlewared/plugins/failover_/event.py
I've discovered, while investigating an unrelated problem, that the HA failover process was "hung" waiting on non-ZFS related tasks (at least from the information that I could coerce out of the system). This happens rarely enough that unless you're prepared, it's very hard to gather the collateral quickly enough before the failover process has finished.
This is not a solution for that problem, but this makes it so that the failover process is extremely verbose around all operations. This will at least give us an _idea_ of an endpoint that could be "blocking" or causing a "longer than expected" amount of time to complete.
While I was here, I renamed the `start_apps_vms` method. We do not support VMs on HA at the moment so there is no reason to keep that logic here. Rename it accordingly. …
=> NAS-129169 / 24.04.2 / log ALL THE THINGS (by yocalebo)

src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py
OEM doesn't use strict naming convention of the model string in their firmware (like we expect). Another internal system showed us this fact and so this PR adds a "quirk" for the ES24N so that we're much more lenient with our checks and try really hard to see if this is an ES24N JBoF.
=> NAS-129171 / 24.10 / add is_this_an_es24n function

src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py
OEM doesn't use strict naming convention of the model string in their firmware (like we expect). Another internal system showed us this fact and so this PR adds a "quirk" for the ES24N so that we're much more lenient with our checks and try really hard to see if this is an ES24N JBoF.
Original PR: https://github.com/truenas/middleware/pull/13788
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129171
=> NAS-129171 / 24.04.2 / add is_this_an_es24n function (by yocalebo)

tests/api2/test_disk_wipe.py
On HA systems `fenced` will have a reference to the disk, so it will never have no references.  Change the test to accommodate.
=> NAS-129193 / 24.10 / Make test_disk_wipe_abort HA aware

tests/api2/test_341_pool_dataset_encryption.py
Simple breakage (manifested in HA when NodeA was not the ACTIVE node).
Also some `flake8` / tidy.
=> NAS-129194 / 24.10 / Fix HA breakage in test_create_a_normal_pool

src/middlewared/middlewared/plugins/crypto_/dhparams.py
The previous implementation of generating dhparam.pem did unnecessary things like print to console (this was purely to give visual feedback on Core) and make middleware calls to itself for a string path.
=> NAS-129188 / 24.10 / Refactored dhparam generation

src/middlewared/middlewared/test/integration/assets/roles.py, tests/api2/test_apps_roles.py
This PR fixes app roles integration tests which were failing because k8s was not running. Testing roles should not require k8s to be running, some changes have been made to accommodate for this and handle both cases when k8s is running or not running so we appropriately manage those cases and gracefully handle role based tests.
=> NAS-129197 / 24.10 / Fix failing app roles integration tests

tests/api2/test_disk_format.py
Api test is asserting because the check is invalid and incorrect (c.f. https://github.com/Distrotech/parted/blob/388bab890a4e09b09d2428c0e773ed083295f91b/parted/parted.c#L1643C51-L1643C61) for how parted does it)
We check for alignment in this same function here
```
assert partitions[0]['start_sector'] == first_sector
=> NAS-129200 / 24.10 / fix start_sector assert (invalid test)

src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnfilters.conf.mako
A fix for this is available in the SNMP tip, but not in any Debian version. This filter will be removed when Debian provides a version with the fix.
This syslog spamming occurs on any Linux TrueNAS that runs with the Debian snmp v5.9.3 and the Linux 6.6 or later kernel (e.g. Dragonfish)
This filter can be removed when the Debian snmpd package includes the fix. See https://ixsystems.atlassian.net/browse/NAS-129206
=> NAS-129124 / 24.10 / Add temporary filter to non-critical SNMP warning.

src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnfilters.conf.mako
A fix for this is available in the SNMP tip, but not in any Debian version. This filter will be removed when Debian provides a version with the fix.
This syslog spamming occurs on any Linux TrueNAS that runs with the Debian snmp v5.9.3 and the Linux 6.6 or later kernel (e.g. Dragonfish)
This filter can be removed when the Debian snmpd package includes the fix. See https://ixsystems.atlassian.net/browse/NAS-129206
Original PR: https://github.com/truenas/middleware/pull/13800
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129124
=> NAS-129124 / 24.04.2 / Add temporary filter to non-critical SNMP warning. (by mgrimesix)

src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
The `stats` schema is not defined in the `chart.release` schema, causing schema errors when using `chart.release.query` with stats for read-only user permissions.
Add the `stats` schema to the `chart.release` schema to resolve this error.
=> NAS-129187 / 24.10 / Add stats in chart.release entry schema

src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
The `stats` schema is not defined in the `chart.release` schema, causing schema errors when using `chart.release.query` with stats for read-only user permissions.
Add the `stats` schema to the `chart.release` schema to resolve this error.
Original PR: https://github.com/truenas/middleware/pull/13805
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129187
=> NAS-129187 / 24.04.2 / Add stats in chart.release entry schema (by Qubad786)

src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
The `stats` schema is not defined in the `chart.release` schema, causing schema errors when using `chart.release.query` with stats for read-only user permissions.
Add the `stats` schema to the `chart.release` schema to resolve this error.
Original PR: https://github.com/truenas/middleware/pull/13805
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129187
=> NAS-129187 / 24.04.1.1 / Add stats in chart.release entry schema (by Qubad786)

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py, src/middlewared/middlewared/plugins/kubernetes_linux/update.py
`route_interface_choices` returns a dictionary whose keys are the interface names and the values are the interface names OR the interface name suffixed with a colon and a description (if the user has set one OR if the OS set one on upgrade from CORE)
We need the interface name as the OS sees it since we end up checking files in sysfs. This fixes the scenario.
=> NAS-129150 / 24.10 / fix apps when interface has a description

src/middlewared/middlewared/etc_files/syslog-ng/syslog-ng.conf.mako, src/middlewared/middlewared/plugins/system_advanced/config.py
I noticed that the current rsyslog-ng implementation was buggy and didn't support IPv6 destinations. 
Entering an IPv6 IP as the syslog server failed due to input validation (both with the [] around the IP and without), and entering a hostname still only made it connect using IPv4. 
This PR should fix that issue. 
The regex for the input validation in the syslog server textbox has been changed to allow colons, percent signs and brackets [] as well which are needed for IPv6 adresses, and the template that creates the syslog-ng config has been modified to add the "ip-protocol(6) parameter. 
According to the documentation this parameter defaults to "4" making it only send data to IPv4 destinations, but setting it to "6" makes it support both IPv4 and IPv6 destinations, under the condition …
=> NAS-129269 / 24.10 / Make rsyslog support IPv6 destinations

src/middlewared/middlewared/plugins/etc.py
The permissions and owner of the snmpd.conf file did not match the Debian default.
This then generated an error:
`[2024/05/29 09:33:50] (ERROR) EtcService.make_changes():372 - /etc/snmp/snmpd.conf: unexpected changes [GID, PERMS] were made to configuration file that may allow unauthorized user to alter service behavior`
Change the permissions and owners to match the expected values.
=> NAS-129288 / 24.10 / Fix permissions and owner of snmpd.conf

src/middlewared/middlewared/plugins/smb_/constants.py
This commit makes the permissions set on smb.conf file match debian package defaults.
=> NAS-129305 / 24.10 / Remove execute permissions from smb.conf

debian/debian/control
This package is not required to build middleware and is now included in the base-packages in scale-build.
=> NAS-129308 / 24.10 / Remove cifs-utils from debian control

src/middlewared/middlewared/test/integration/assets/pool.py, tests/api2/test_006_pool_and_sysds.py, tests/api2/test_disk_format.py, tests/api2/test_disk_wipe.py
The disk.get_unused endpoint now actually returns disks that are "unused" (i.e. no partition zfs partition labels on them). We made a bad decision to show an `exported_zpool` key for disks but they showed up in "unused" disks.
`disk.details` now returns an `used` and `unused` set of keys that return disk information. There are `exported_zpool` and `imported_zpool` keys for each disk. If either of those are filled, they will show up in `disk.get_used` (or `disk.details['used']`).
Our `another_pool` context manager wasn't wiping the disks and so the zpool label was left on them even though the zpool was being exported. To fix the majority of tests, I've changed it so that we're now wiping (quickly) the disks that the `another_pool` context manager uses. This fixes the majority of tests. …
=> NAS-129327 / 24.10 / Fix the API tests that were (incorrectly) using disk.get_unused

src/middlewared/middlewared/etc_files/systemd.py, src/middlewared/middlewared/plugins/system/product.py, src/middlewared/middlewared/plugins/truenas.py
The `test_data_dir_perms` of the early_settings integration test was failing because some files, including `user-services.json`, `truenas-eula-pending`, and `dhparam.pem`, do not have `0o600` permissions when created by middlewared.
Specify the permissions of these files to be `0o600` when they are created by middlewared.
P.S permission for dhparam are not fixed as they should be handled in another PR we have open
=> NAS-129054 / 24.10 / Fix permissions on files under data directory

src/middlewared/middlewared/test/integration/assets/roles.py
Change the scope of the `change_unprivileged_user_fixture` to module.
Otherwise, the user remains in play and interferes with other tests (e.g. `test__smb_simple_share_validation`)
=> NAS-129341 / 24.10 / Change scope of unprivileged_user_fixture fixture to module

src/middlewared/middlewared/test/integration/assets/roles.py
Change the scope of the `change_unprivileged_user_fixture` to module.
Otherwise, the user remains in play and interferes with other tests (e.g. `test__smb_simple_share_validation`)
Original PR: https://github.com/truenas/middleware/pull/13824
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129341
=> NAS-129341 / 24.04.2 / Change scope of unprivileged_user_fixture fixture to module (by bmeagherix)

src/middlewared/middlewared/plugins/crypto_/dhparams.py
`DHPARAM_PEM_PATH` file when created has incorrect permissions applied which do not conform to what we want them to do.
Fix the permissions for `DHPARAM_PEM_PATH` and flake8 issues.
=> NAS-129355 / 24.10 / Fix dhparam permissions

src/middlewared/middlewared/common/smart/smartctl.py
```
[2024/06/02 12:00:37] (ERROR) DiskService.update():32 - update_smartctl_args_for_disks failed
File "/usr/lib/python3/dist-packages/middlewared/plugins/disk_/smartctl.py", line 27, in update
await asyncio_map(
File "/usr/lib/python3/dist-packages/middlewared/utils/asyncio_.py", line 19, in asyncio_map
return await asyncio.gather(*futures)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/utils/asyncio_.py", line 16, in func
return await real_func(arg)
^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/common/smart/smartctl.py", line 30, in get_smartctl_args
if device["vendor"].lower().strip() == "nvme":
^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```
Make sure …
=> NAS-129354 / 24.10 / Make sure vendor key exists before trying string operation

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
Catch ValueError instead of KeyError when accessing ControllerModels values with parentheses (line 118). Python enums throw ValueError when using parentheses.
=> NAS-129370 / 24.10 / Minor logical fix in enclosure_class._get_model_and_controller

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
Catch ValueError instead of KeyError when accessing ControllerModels values with parentheses (line 118). Python enums throw ValueError when using parentheses.
Original PR: https://github.com/truenas/middleware/pull/13831
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129370
=> NAS-129370 / 24.04.2 / Minor logical fix in enclosure_class._get_model_and_controller (by creatorcary)

src/middlewared/middlewared/plugins/network_/global_config.py
Users are entering incorrect proxy URL formats in the network configuration.
Add validation in the network global configuration to prevent users from adding incorrectly formatted proxy URLs.
Ref:
https://requests.readthedocs.io/en/latest/api/#requests.Session.proxies
https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support
=> NAS-129261 / 24.10 / Fix validation for httpproxy

src/middlewared/middlewared/plugins/pool_/import_pool.py
This was added in the backport to 24.04.2 but was missed in master. This adds it so the branches are aligned with each other.
=> NAS-129408 / 24.10 / add missing log statement when importing pool

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
We were including the 2nd virtual AHCI enclosure object in `enclosure2.query` which was causing `webui.enclosure.dashboard` to crash with a `KeyError`.
This fixes that logic and prevents the key error.
=> NAS-129273 / 24.10 / fix enclosure2.query logic on R20/MINI3XP/MINI3E

src/middlewared/Makefile
`reinstall_container` is broken (known) but we were still referencing the `install_client` in the `make reinstall` command.
After looking at this a bit closer, we don't need to install all of this on a truenas system. We simply need to reinstall middleware when the `make reinstall` command is issued.
=> NAS-129414 / 24.10 / fix makefile

src/middlewared/middlewared/plugins/disk_/availability.py
This method was changed but the docstring was copy and pasted from `disk.get_used`. Update it to reflect reality.
=> NAS-129429 / 24.10 / fix docstring for disk.get_unused

src/middlewared/middlewared/plugins/iscsi_/targets.py
When using the iSCSI wizard entries under `Initiator Groups` can be created one-per-target without any user interaction.  As such these therefore invite also being cleaned up without user interaction when the target is deleted.
Since when creating the target without using the wizard these entities can be reused/shared by several targets, during cleanup we check first that no other target is using them.
=> NAS-128872 / 24.10 / When deleting a target attempt to cleanup associated initiator

src/middlewared/middlewared/plugins/zfs_/dataset_actions.py
This PR supplements https://github.com/truenas/py-libzfs/pull/273 to allow us to mount datasets which have `canmount` set to `noauto`.
=> NAS-129441 / 24.10 / Allow force mounting zfs datasets

tests/api2/test_iscsi_auth_network.py
Update iSCSI test to take account that initiator may have been autodeleted.
This test was broken by recent PR #13844.
(Fix tested in shortened CI run [659 ](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/659/))
FYI, wrt the DF backport, have included this PR into the main feature backport (#13849)
=> NAS-129457 / 24.10 / Update iSCSI test to take account of initiator autodelete

src/middlewared/middlewared/main.py, tests/api2/test_475_syslog.py
With k8s removal, 2 problems were seen with logging:
1) Leftover `k8s_api.log` file
2) Syslog tests failing because they were relying on `app_mounts.log` to be around which is no longer the case
For (1) make sure that log file is no longer created and for second fix the test to make sure we adapt to our updated filters keeping in line with removal of k8s
=> NAS-129458 / 24.10 / Fix syslog tests

src/middlewared/middlewared/plugins/enclosure.py, src/middlewared/middlewared/plugins/enclosure_/enclosure2.py, src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_enclosure2_query.py
UI team asked me what the canonical way was for determining if the truenas system supported our enclosure plugin. I didn't know off the top of my head but I found the endpoint after some investigation. During that investigation, I realized we weren't calling this method internally so I've switched to using `truenas.is_ix_hardware` since that is the canonical way for determining this information.
=> NAS-129464 / 24.10 / call truenas.is_ix_hardware

src/middlewared/middlewared/plugins/reporting/utils.py, src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
With k8s being removed, we no longer need to factor in it's metrics when we calculate an approximation for netdata db size.
=> NAS-129459 / 24.10 / Adjust netdata db size after k8s removal

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py, src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py
=> NAS-129430 / 24.10 / fix drive count on mini-3.0-x+

src/middlewared/middlewared/plugins/failover_/disabled_reasons.py, src/middlewared/middlewared/plugins/sysdataset.py
Changes have been added to track system dataset migration state in HA machines so we can correctly report that is in place when UI consumes `failover.disabled.reasons` to see if we have any reason to mark HA has disabled for now.
=> NAS-128090 / 24.10 / Track system dataset migration state for failover disabled reasons

src/middlewared/middlewared/plugins/iscsi_/targets.py, tests/api2/test_iscsi_auth_network.py
When using the iSCSI wizard entries under `Initiator Groups` can be created one-per-target without any user interaction.  As such these therefore invite also being cleaned up without user interaction when the target is deleted.
Since when creating the target without using the wizard these entities can be reused/shared by several targets, during cleanup we check first that no other target is using them.
Original PR: https://github.com/truenas/middleware/pull/13844
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128872
=> NAS-128872 / 24.04.2 / When deleting a target attempt to cleanup associated initiator (by bmeagherix)

src/middlewared/middlewared/pytest/unit/utils/test_nss.py, src/middlewared/middlewared/utils/nss/grp.py, src/middlewared/middlewared/utils/nss/pwd.py
Since these databases can contain thousands or tens of thousands of entries it's a good idea to allow more memory-efficient iteration than creating a list with all entries.
Directory services will use these functions to build caches as part of PR to add IPA support.
=> NAS-129532 / 24.10 / Add generators for pwd and grp

src/freenas/debian/rules
Download most recent IANA enterprise numbers on build of the truenas-files package.
Original PR: https://github.com/truenas/middleware/pull/13868
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128598
=> NAS-128598 / 24.04.2 / Add IANA Enterprise numbers file to truenas-files (by anodos325)

src/middlewared/middlewared/plugins/idmap_/utils.py, src/middlewared/middlewared/utils/itertools.py
When building user and group caches we can end up with very large requests to libwbclient to resolve into SIDs. This commit breaks the large requests into chunks of 100 users and groups.
=> NAS-129531 / 24.10 / Break large winbind requests into smaller chunks

src/middlewared/middlewared/plugins/idmap_/utils.py, src/middlewared/middlewared/utils/itertools.py
When building user and group caches we can end up with very large requests to libwbclient to resolve into SIDs. This commit breaks the large requests into chunks of 100 users and groups.
Original PR: https://github.com/truenas/middleware/pull/13866
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129531
=> NAS-129531 / 24.04.2 / Break large winbind requests into smaller chunks (by anodos325)

src/middlewared/middlewared/plugins/directoryservices.py
We need to ensure that the idmap service is always restarted after generating a clean idmap configuration to ensure that the in-memory copy of the SMB configuration in winbindd contains required idmap entries for the builtin domain otherwise xid-to-sid requests will fail. This issue occurred for some users after rebooting TrueNAS.
=> NAS-129470 / 24.10 / Restart idmap service after SMB has been configured

src/middlewared/middlewared/plugins/directoryservices.py
We need to ensure that the idmap service is always restarted after generating a clean idmap configuration to ensure that the in-memory copy of the SMB configuration in winbindd contains required idmap entries for the builtin domain otherwise xid-to-sid requests will fail. This issue occurred for some users after rebooting TrueNAS.
Original PR: https://github.com/truenas/middleware/pull/13871
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129470
=> NAS-129470 / 24.04.2 / Restart idmap service after SMB has been configured (by anodos325)

src/middlewared/middlewared/plugins/account.py
The UI team requested that we present a more user-friendly error message to end-users. KeyError exception type is preserved in this case to minimize risk of regression.
=> NAS-129560 / 24.10 / Add more user-friendly error message on NSS wrapper fn

src/middlewared/middlewared/plugins/cache.py
The UI team requested that we present a more user-friendly error message to end-users. KeyError exception type is preserved in this case to minimize risk of regression.
Original PR: https://github.com/truenas/middleware/pull/13874
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129560
=> NAS-129560 / 24.04.2 / Add more user-friendly error message on NSS wrapper fn (by anodos325)

src/freenas/usr/local/bin/snmp-agent.py, src/middlewared/middlewared/etc_files/nfs.conf.d/local.conf.mako, src/middlewared/middlewared/plugins/boot_/format.py, src/middlewared/middlewared/plugins/disk_/power_management_linux.py, src/middlewared/middlewared/plugins/idmap.py, src/middlewared/middlewared/plugins/jbof/crud.py, src/middlewared/middlewared/plugins/pool_/dataset_encryption_lock.py, src/middlewared/middlewared/plugins/smart_/event_source.py, src/middlewared/middlewared/service/core_service.py, tests/api2/test_200_ftp.py, tests/api2/test_disk_wipe.py, tests/api2/test_snapshots.py
I noticed that we use the `int(x / y)` pattern in a few areas. While this is completely valid, especially for our use cases, it's better practice to do `x // y` instead. 
We only deal with positive numbers in all of these cases, so the truncation that `int` does is equivalent to floor division. The only difference becomes floating point rounding errors when we do our normal division inside of the `int`.
We likely wont deal with values large enough for these rounding errors to take effect, but especially since we're dealing with stat reporting it's in our best interest to ensure accuracy regardless.
=> NAS-129559 / 24.10 / Replace int(x/y) pattern with x // y

src/middlewared/middlewared/plugins/iscsi_/auth.py
With this change it'll present a prettier error message, e.g.:
`[EFAULT] Authorized access of 171 is being used by portal(s): 1800
`
=> NAS-129569 / 24.10 / Add missing str() in is_in_use_by_portals_targets

src/middlewared/middlewared/plugins/iscsi_/auth.py
With this change it'll present a prettier error message, e.g.:
`[EFAULT] Authorized access of 171 is being used by portal(s): 1800
`
Original PR: https://github.com/truenas/middleware/pull/13879
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129569
=> NAS-129569 / 24.04.2 / Add missing str() in is_in_use_by_portals_targets (by bmeagherix)

src/freenas/usr/lib/netdata/charts.d/nut_ups.chart.sh, src/middlewared/middlewared/etc_files/netdata/netdata.conf.mako
We were seeing logs being continuously written to, after investigation, we found that only the UPS plugin of netdata is causing issues. When UPS is not configured, the failed `upsc -l` command returns an error, spamming the Netdata logs and causing the log file size to increase continuously.
Modify the Netdata plugin to avoid executing the `upsc` command when `upsmon` process is not running. Additionally, disable access logs since only the `errors.log` is used for debugging, thereby preventing unnecessary log file growth.
=> NAS-129384 / 24.10 / Fix netdata spamming logs

src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tndestinations.conf.mako, src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnfilters.conf.mako, src/middlewared/middlewared/etc_files/syslog-ng/syslog-ng.conf.mako, tests/api2/test_475_syslog.py
The system logs were experiencing a high volume of entries due to routine operations reported by `k3s` and `systemd` for `cri-containerd` containers. This constant logging, including informational and routine operational messages, was leading to continuous writes to the boot pool, which could potentially affect system performance and disk longevity. Examples of such spamming include:
```
Jun 13 07:57:10 truenas systemd[1]: Started cri-containerd-2f73b0226a75644e2fd025bb494f2b1a424538ae0d0c034c1c95e06c893d7b31.scope - libcontainer container 2f73b0226a75644e2fd025bb494f2b1a424538ae0d0c034c1c95e06c893d7b31.
Jun 13 07:57:10 truenas systemd[1]: Started cri-containerd-dc1e1ebbbe7c44922b0d0f5d67f851bbae1b902f59a440dda2900abb3a43733d.scope - libcontainer container …
```
=> NAS-129383 / 24.04.2 / Prevent k3s from spamming logs

src/middlewared/middlewared/plugins/directoryservices.py, src/middlewared/middlewared/plugins/ldap.py
First one is in the directoryservices plugin
* sevice -> service
This one has functional impact that may result in-memory configuration of winbindd not being properly refreshed on boot.
Second one is a typo in an error message that we present users when for some reason the choose to try to set up an AD domain via the LDAP plugin.
=> NAS-129610 / 24.10 / Fix typos related to directory services

src/middlewared/middlewared/plugins/directoryservices.py, src/middlewared/middlewared/plugins/ldap.py
First one is in the directoryservices plugin
* sevice -> service
This one has functional impact that may result in-memory configuration of winbindd not being properly refreshed on boot.
Second one is a typo in an error message that we present users when for some reason the choose to try to set up an AD domain via the LDAP plugin.
Original PR: https://github.com/truenas/middleware/pull/13886
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129610
=> NAS-129610 / 24.04.2 / Fix typos related to directory services (by anodos325)

src/middlewared/middlewared/etc_files/docker/daemon.json.py, src/middlewared/middlewared/plugins/etc.py
Python etc files should be named after the file they are creating if FileShouldNotExist is raised within them. File contents should also be returned from the method so that we properly note when it is changing.
=> NAS-129619 / 24.10 / Fix docker etc file

src/freenas/etc/systemd/system/nvmf-connect@.service.d/override.conf, src/freenas/usr/local/bin/nvmf-connect.sh, src/freenas/usr/local/bin/nvmf-wrapper.sh
Jira Ticket: [NAS-128368](https://ixsystems.atlassian.net/browse/NAS-128368)
[NAS-128368](https://ixsystems.atlassian.net/browse/NAS-128368) reports three different issues related to NVMe-oF hotplugging:
NAS-128368 reports three different issues related to NVMe-oF hotplugging:
1. When a drive is physically removed while part of the pool, the Linux/zfs still sees it as ONLINE.
2. A drive is not visible to the OS upon insertion until the next drive is inserted, i.e., drive addition by OS is lagged by one event. For example, if a drive is inserted into Slot-1, it won't be added by Linux until another drive is inserted into a different slot. However, the addition of the next drive will then be lagged by the drive inserted after that.
3. If fenced is holding a drive, the new drive still points …
=> NAS-128368 / 24.10 / nvme-of: Remove/Add disk on discovery change event

src/middlewared/middlewared/plugins/failover_/event.py, src/middlewared/middlewared/plugins/failover_/virtual_ips.py
This fixes failover on SCALE in an edge-case scenario. The scenario is as follows:
1. configure `eno1` and `eno2` in the _same_ failover group
2. `eno2` is `LINK_STATE_DOWN` and `eno1` is functioning as normal
3. take down `eno1` on the primary controller
4. failover will _fail_ and a message like this is logged on the other controller. ``` Received MASTER event for 'eno1', but other interfaces (eno2) are still working on the MASTER node. Ignoring event.```
This happens because the _NEW_ controller that is becoming the primary will see `eno2` as being marked in the "backup" state locally. This is occurring because the interface is LINK_STATE_DOWN.
This fixes that scenario by adding a new `offline` list variable to `check_failover_groups` method. Instead of treating offline interfaces as …
=> NAS-129541 / 24.10 / only query UP ifaces in virtual ip plugin

src/middlewared/middlewared/plugins/failover_/event.py, src/middlewared/middlewared/plugins/failover_/virtual_ips.py
This fixes failover on SCALE in an edge-case scenario. The scenario is as follows:
1. configure `eno1` and `eno2` in the _same_ failover group
2. `eno2` is `LINK_STATE_DOWN` and `eno1` is functioning as normal
3. take down `eno1` on the primary controller
4. failover will _fail_ and a message like this is logged on the other controller. ``` Received MASTER event for 'eno1', but other interfaces (eno2) are still working on the MASTER node. Ignoring event.```
This happens because the _NEW_ controller that is becoming the primary will see `eno2` as being marked in the "backup" state locally. This is occurring because the interface is LINK_STATE_DOWN.
This fixes that scenario by adding a new `offline` list variable to `check_failover_groups` method. Instead of treating offline interfaces as …
=> NAS-129541 / 24.04.2 / only query UP ifaces in virtual ip plugin (by yocalebo)

src/freenas/usr/local/bin/scst_util.sh, src/middlewared/middlewared/plugins/dlm.py, src/middlewared/middlewared/plugins/failover_/event.py, src/middlewared/middlewared/plugins/iscsi_/alua.py, src/middlewared/middlewared/plugins/iscsi_/scst.py, src/middlewared/middlewared/plugins/iscsi_/targets.py
This PR contains a few components.
Summary:
- Better recovery when an service failover takes > 15 seconds
- Avoid service failover taking > 15 seconds (session teardown)
- Avoid STANDBY causing the ACTIVE node to reboot in certain circumstances
Add `logout_empty_ha_targets` and call from `standby_after_start`.  This will prevent targets that were suspended when the STANDBY node logged into them from remaining in place, preventing further logins once they have been unsuspended.
They will not recover without a fresh login.
Suspend iSCSI activity earlier in `vrrp_master` and force close all current sessions.
Also use `clear_suspend` to resume activity, either in `become_active` if it runs to conclusion, or later in `vrrp_master` if not.
It appears that during `vrrp_master`, and **_after_** …
=> NAS-129515 / 24.04.3 / Robustize ALUA

src/freenas/usr/local/bin/scst_util.sh, src/middlewared/middlewared/plugins/dlm.py, src/middlewared/middlewared/plugins/failover_/event.py, src/middlewared/middlewared/plugins/iscsi_/alua.py, src/middlewared/middlewared/plugins/iscsi_/scst.py, src/middlewared/middlewared/plugins/iscsi_/targets.py
This PR contains a few components.
Summary:
- Better recovery when an service failover takes > 15 seconds
- Avoid service failover taking > 15 seconds (session teardown)
- Avoid STANDBY causing the ACTIVE node to reboot in certain circumstances
Add `logout_empty_ha_targets` and call from `standby_after_start`.  This will prevent targets that were suspended when the STANDBY node logged into them from remaining in place, preventing further logins once they have been unsuspended.
They will not recover without a fresh login.
Suspend iSCSI activity earlier in `vrrp_master` and force close all current sessions.
Also use `clear_suspend` to resume activity, either in `become_active` if it runs to conclusion, or later in `vrrp_master` if not.
It appears that during `vrrp_master`, and **_after_** …
=> NAS-129515 / 24.04.2 / Robustize ALUA (by bmeagherix)

src/freenas/usr/local/bin/scst_util.sh, src/middlewared/middlewared/plugins/dlm.py, src/middlewared/middlewared/plugins/failover_/event.py, src/middlewared/middlewared/plugins/iscsi_/alua.py, src/middlewared/middlewared/plugins/iscsi_/scst.py, src/middlewared/middlewared/plugins/iscsi_/targets.py
This PR contains a few components.
Summary:
- Better recovery when an service failover takes > 15 seconds
- Avoid service failover taking > 15 seconds (session teardown)
- Avoid STANDBY causing the ACTIVE node to reboot in certain circumstances
Add `logout_empty_ha_targets` and call from `standby_after_start`.  This will prevent targets that were suspended when the STANDBY node logged into them from remaining in place, preventing further logins once they have been unsuspended.
They will not recover without a fresh login.
Suspend iSCSI activity earlier in `vrrp_master` and force close all current sessions.
Also use `clear_suspend` to resume activity, either in `become_active` if it runs to conclusion, or later in `vrrp_master` if not.
It appears that during `vrrp_master`, and **_after_** …
=> NAS-129515 / 24.10 / Robustize ALUA (by bmeagherix)

src/freenas/usr/lib/netdata/charts.d/nut_ups.chart.sh, src/middlewared/middlewared/etc_files/netdata/netdata.conf.mako
We were seeing logs being continuously written to, after investigation, we found that only the UPS plugin of netdata is causing issues. When UPS is not configured, the failed `upsc -l` command returns an error, spamming the Netdata logs and causing the log file size to increase continuously.
Modify the Netdata plugin to avoid executing the `upsc` command when `upsmon` process is not running. Additionally, disable access logs since only the `errors.log` is used for debugging, thereby preventing unnecessary log file growth.
Original PR: https://github.com/truenas/middleware/pull/13860
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129384
=> NAS-129384 / 24.04.3 / Fix netdata spamming logs (by Qubad786)

src/freenas/usr/lib/netdata/charts.d/nut_ups.chart.sh, src/middlewared/middlewared/etc_files/netdata/netdata.conf.mako
We were seeing logs being continuously written to, after investigation, we found that only the UPS plugin of netdata is causing issues. When UPS is not configured, the failed `upsc -l` command returns an error, spamming the Netdata logs and causing the log file size to increase continuously.
Modify the Netdata plugin to avoid executing the `upsc` command when `upsmon` process is not running. Additionally, disable access logs since only the `errors.log` is used for debugging, thereby preventing unnecessary log file growth.
Original PR: https://github.com/truenas/middleware/pull/13860
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129384
Original PR: https://github.com/truenas/middleware/pull/13884
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129384
=> NAS-129384 / 24.04.2 / Fix netdata spamming logs (by Qubad786) (by bugclerk)

src/middlewared/middlewared/main.py
We removed websocket logging in 2982c2cfa39921917b646b8e254a050765526e38 but we left out a usage which resulted un us dumping args for method calls and it is no longer required/needed to do that anymore.
=> NAS-129677 / 24.10 / Remove unnecessary dumping of args

src/freenas/usr/local/libexec/ipa_ctl.py, src/middlewared/middlewared/utils/directoryservices/ipactl_constants.py
This commit adds a basic helper script to manage different aspects of a FreeIPA join such as:
* Joining a freeipa domain
* Leaving a freeipa domain
* Setting up services (NFS / SMB)
* deleting services (NFS / SMB)
* Querying SMB domain information
=> NAS-129661 / 24.10 / Add basic FreeIPA connection control script

src/middlewared/middlewared/service/core_service.py
As per [NAS-129674](https://ixsystems.atlassian.net/browse/NAS-129674), `midclt call core.ping` would output `Not authorized` for users with the read-only admin role.
=> NAS-129674 / 24.10 / Give core.ping no_authz_required status

src/middlewared/middlewared/etc_files/nsswitch.conf.mako, src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/etc.py, src/middlewared/middlewared/plugins/ldap.py
Starting with glibc 2.33, the nsswitch.conf is automatically reloaded if the file is changed, which allows us to only keep needed nss modules present in the configuration file.
=> NAS-129676 / 24.10 / Regenerate nsswitch.conf as-needed

src/middlewared/middlewared/plugins/audit/audit.py
Fix audit dataset quota setting.   
We were using `refquota` when we should be using `quota`.
This change can be safely backported.
=> NAS-129693 / 24.10 / Change audit dataset quota setting from 'refquota' to 'quota'

src/middlewared/middlewared/plugins/audit/audit.py
Fix audit dataset quota setting.   
We were using `refquota` when we should be using `quota`.
This change can be safely backported.
Original PR: https://github.com/truenas/middleware/pull/13914
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129693
=> NAS-129693 / 24.04.3 / Change audit dataset quota setting from 'refquota' to 'quota' (by mgrimesix)

src/middlewared/middlewared/plugins/audit/audit.py
Fix audit dataset quota setting.   
We were using `refquota` when we should be using `quota`.
This change can be safely backported.
Original PR: https://github.com/truenas/middleware/pull/13914
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129693
=> NAS-129693 / 24.04.2 / Change audit dataset quota setting from 'refquota' to 'quota' (by mgrimesix)

src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/reporting/processes.py
For event sources we have the event name come in as `kubernetes.pod_log_follow:{"release_name":"emby", "pod_name":"emby-6cb49545f9-b6xsq", "container_name":"emby", "tail_lines": 500}`. Now when we try to see if a user which is not an administrator is able to actually access an event source and that event source has args specified like in the example earlier - we fail to pass the authorization check because we are gauging in the args passed in as well.
Make sure when we try to see if a consumer can subscribe to an event source we strip off the args specified for the event source.
=> NAS-129588 / 24.10 / Properly reference event name when subscribing to event sources

src/freenas/usr/lib/netdata/charts.d/nut_ups.chart.sh
We were using `ps -aux` for determining UPS service health status which is quite expensive especially when invoked periodically.
Check existence of upsmon pid file to determine if upsmon is running or not instead of using `ps`
=> NAS-129688 / 24.10 / Do not use ps for determining upsmon service status

src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/reporting/processes.py
For event sources we have the event name come in as `kubernetes.pod_log_follow:{"release_name":"emby", "pod_name":"emby-6cb49545f9-b6xsq", "container_name":"emby", "tail_lines": 500}`. Now when we try to see if a user which is not an administrator is able to actually access an event source and that event source has args specified like in the example earlier - we fail to pass the authorization check because we are gauging in the args passed in as well.
Make sure when we try to see if a consumer can subscribe to an event source we strip off the args specified for the event source.
Original PR: https://github.com/truenas/middleware/pull/13918
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129588
=> NAS-129588 / 24.04.3 / Properly reference event name when subscribing to event sources (by Qubad786)

src/middlewared/middlewared/migration/0003_iscsi_vendor.py, src/middlewared/middlewared/pytest/unit/middleware.py
The method `system.is_freenas` has been deprecated for 1+ year(s) and was recently removed [here](https://github.com/truenas/middleware/pull/13900) However, I missed other places where it was being called.
=> NAS-129714 / 24.10 / fix references to system.is_freenas

src/middlewared/middlewared/plugins/zfs_/utils.py, tests/api2/test_audit_basic.py
`zfs_/utils.py` was using hard-coded values for audit quota default settings.  The audit subsystem has these same values specified in `plugins/audit/utils.py`.   This PR removes the hard-coded values and replaces with the names associated with the default settings from `plugins/audit/utils.py`.
Includes a targeted CI test.
=> NAS-129719 / 24.10 / Replace hard-coded defaults with values from the audit/utils.py

src/middlewared/middlewared/plugins/idmap.py
When user / group enumeration are disabled for a directory service we rely on user.query and group.query to perform cache insertions as we have successes on lookups so that UI can present users with more useful options. This commit slightly refactors the getacl method for SMB shares to contribute to the lazy caching effort.
=> NAS-129735 / 24.10 / Force directory service cache insertion on share ACL read

src/middlewared/middlewared/plugins/idmap.py
When user / group enumeration are disabled for a directory service we rely on user.query and group.query to perform cache insertions as we have successes on lookups so that UI can present users with more useful options. This commit slightly refactors the getacl method for SMB shares to contribute to the lazy caching effort.
Original PR: https://github.com/truenas/middleware/pull/13926
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129735
=> NAS-129735 / 24.04.3 / Force directory service cache insertion on share ACL read (by anodos325)

tests/api2/test_smb_encryption.py, tests/protocols/smb_proto.py
This commit adds tests to validate that SMB clients can properly negotiate SMB encryption levels via normal protocol mechanisms.
=> NAS-129740 / 24.10 / Add tests for SMB client encryption

src/middlewared/middlewared/service/core_service.py, tests/api2/test_audit_basic.py
The change to add audit `core.download` was passing parameters incorrectly.  This resulted in breaking the API. 
The fix:  change the parameters from `*args` to `args`
=> NAS-129751 / 24.10 / Fix audit export test

src/middlewared/middlewared/plugins/jbof/redfish/__init__.py, src/middlewared/middlewared/plugins/jbof/redfish/client.py
This (`aiohttp`-based) async client is capable of transparently utilizing multiple redfish interfaces to the same JBOF.
It will be used by the new JBOF enclosure services for performing redfish operations.  (Will be introduced in a separate PR.)  When multiple JBOFs are present, this client will be used to fetch the data from them in parallel.
(The existing synchronous `requests`-based client is also being retained for initial setup/config operations.  With that client we _deliberately_ do **not** transparently handle switching between redfish interfaces.)
=> NAS-127804 / 24.10 / Add AsyncRedfishClient

src/middlewared/middlewared/test/integration/utils/call.py, src/middlewared/middlewared/test/integration/utils/client.py, tests/conftest.py
Store a persistent websocket client connection in the truenas_server object we allocate for test runs, and use this for general case where test simply uses `call` test utility. This is to avoid potentially running into issues with rate-limiting on auth endpoints.
=> NAS-129758 / 24.10 / Try to use persistent connection for CI tests

src/middlewared/middlewared/plugins/vm/utils.py, src/middlewared/middlewared/plugins/vm/vms.py
git cherry-pick -x 16a091204df0ca0986f52585414f878dc456514d
git cherry-pick -x 7585be9396b6b51f21481e54a9e14486cfb1d82b
A user switched from virtualization supported TN system to virtualization not supported and encountered this issue where he couldn't query and  then remove the VMs from the TN system. 
PR adds the change to enable deletion of VMs even if virtualization is not supported. After the changes vm query will show the existing VMs but in error state like below. 
`"status": {
"state": "ERROR",
"pid": null,
"domain_state": "ERROR"
}`
Original PR: …
=> NAS-128941 / 24.04.3 / Allow VM deletion if virtualization is not supported (by Qubad786)

src/middlewared/middlewared/alembic/versions/24.10/2024-06-26_19-44_add_smb_encryption.py, src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/constants.py, src/middlewared/middlewared/plugins/smb_/util_smbconf.py, src/middlewared/middlewared/pytest/unit/plugins/test_smb.py, tests/api2/test_smb_encryption.py
This commit adds a new SMB server global parameter for SMB transport encryption. It exposes 4 options:
DEFAULT -- follow upstream / truenas default (reflected as a null in db) -- currently NEGOTIATE
NEGOTIATE -- only encrypt transport if explicitly requested by the SMB client
DESIRED -- encrypt transport if supported by client during session negotiation.
REQUIRED -- always encrypt transport (rejecting access if client does not support encryption -- incompatible with SMB1 server).
=> NAS-129763 / 24.10 / Expose ability for users to configure SMB encryption behavior

tests/api2/test_snmp_agent.py
(Possibly following some recent changes in EE ...) When the snmp agent starts it takes a second or so before it initializes **all** the fields, so when the test was querying too quickly after starting it, the test failed.
Just add a short (2 second) delay to avoid the race.
(Passed test with this change in CI run [1019](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1019/))
=> NAS-129792 / 24.10 / Add settle delay after snmp start

src/freenas/usr/lib/modprobe.d/truenas.conf
- Setting zfs_arc_shrinker_limit=0 should make ARC more obedient to all kernel shrinker KPI requests, that should help to avoid OOMs.
- zfs_arc_pc_percent=300 should prevent file-backed part of page cache from getting bigger than 1/3 of ARC, that should help with ARC shrinking to its minimum by heavy mmap() I/O.  It is not perfect from perspective of adapting to different workloads, but the best we can do for now.
=> NAS-129533 / 24.10 / Tune ARC memory pressure parameters

src/freenas/usr/lib/modprobe.d/truenas.conf
- Setting zfs_arc_shrinker_limit=0 should make ARC more obedient to all kernel shrinker KPI requests, that should help to avoid OOMs.
- zfs_arc_pc_percent=300 should prevent file-backed part of page cache from getting bigger than 1/3 of ARC, that should help with ARC shrinking to its minimum by heavy mmap() I/O.  It is not perfect from perspective of adapting to different workloads, but the best we can do for now.
Original PR: https://github.com/truenas/middleware/pull/13949
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129533
=> NAS-129533 / 24.04.3 / Tune ARC memory pressure parameters (by amotin)

src/freenas/usr/lib/modprobe.d/truenas.conf
- Setting zfs_arc_shrinker_limit=0 should make ARC more obedient to all kernel shrinker KPI requests, that should help to avoid OOMs.
- zfs_arc_pc_percent=300 should prevent file-backed part of page cache from getting bigger than 1/3 of ARC, that should help with ARC shrinking to its minimum by heavy mmap() I/O.  It is not perfect from perspective of adapting to different workloads, but the best we can do for now.
Original PR: https://github.com/truenas/middleware/pull/13949
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129533
=> NAS-129533 / 24.04.2 / Tune ARC memory pressure parameters (by amotin)

src/middlewared/middlewared/plugins/audit/audit.py, src/middlewared/middlewared/plugins/audit/utils.py, tests/api2/test_audit_audit.py, tests/api2/test_audit_basic.py
Added auditing of audit ops.  Also includes:
- Returning to `refquota`
- Fixing a typo and converting the unit conversion divisions to `//`
Very minor cleanup of audit utils:  Fix Flake8 complaint about extra lines
Refactored test_audit_basic:
- Enhanced testing
-- More checks with ZFS dataset values
- Converted to using refquota.
Added CI tests for the new auditing in test_audit_audit.py.
=> NAS-129782 / 24.10 / Add auditing of audit ops

src/middlewared/middlewared/plugins/device_/device_info.py, src/middlewared/middlewared/plugins/disk_/disk_info.py
A fix was done here recently to ensure we maintain the start sector offset of the data partition for `pool.expand`. However, it uncovered the fact that we're not calculating the start _sector_ properly because the kernel has 0 documentation on these sysfs files (which is where we enumerate this information) and so we made an incorrect assumption of how it works. This manifests itself on 4kn drives. Almost all userspace tools for manipulating partitions will default to expecting the information is provided in sectors. Without these changes, we're not doing that properly. Reproduced in-house trivially and was able to test these changes afterwards.
NOTE: I will be pushing another proper PR with tests after this is merged. However, I need to add 4kn emulated drives to our VM environment for …
=> NAS-129750 / 24.10 / fix scrambing start sector of data partitions in pool.expand

src/middlewared/middlewared/plugins/device_/device_info.py, src/middlewared/middlewared/plugins/disk_/disk_info.py
A fix was done here recently to ensure we maintain the start sector offset of the data partition for `pool.expand`. However, it uncovered the fact that we're not calculating the start _sector_ properly because the kernel has 0 documentation on these sysfs files (which is where we enumerate this information) and so we made an incorrect assumption of how it works. This manifests itself on 4kn drives. Almost all userspace tools for manipulating partitions will default to expecting the information is provided in sectors. Without these changes, we're not doing that properly. Reproduced in-house trivially and was able to test these changes afterwards.
NOTE: I will be pushing another proper PR with tests after this is merged. However, I need to add 4kn emulated drives to our VM environment for …
=> NAS-129750 / 24.04.2 / fix scrambing start sector of data partitions in pool.expand (by yocalebo)

src/middlewared/middlewared/plugins/device_/device_info.py, src/middlewared/middlewared/plugins/disk_/disk_info.py
A fix was done here recently to ensure we maintain the start sector offset of the data partition for `pool.expand`. However, it uncovered the fact that we're not calculating the start _sector_ properly because the kernel has 0 documentation on these sysfs files (which is where we enumerate this information) and so we made an incorrect assumption of how it works. This manifests itself on 4kn drives. Almost all userspace tools for manipulating partitions will default to expecting the information is provided in sectors. Without these changes, we're not doing that properly. Reproduced in-house trivially and was able to test these changes afterwards.
NOTE: I will be pushing another proper PR with tests after this is merged. However, I need to add 4kn emulated drives to our VM environment for …
=> NAS-129750 / 24.04.3 / fix scrambing start sector of data partitions in pool.expand (by yocalebo)

src/middlewared/middlewared/test/integration/assets/iscsi.py
Found that a long distance between initiator and target could cause the test to fail.  Increase retries to allow more time (only used if necessary).
=> NAS-129802 / 24.10 / Make target_login_test_linux more robust by increasing retries

src/freenas/usr/local/bin/truenas-initrd.py
The `truenas-initrd.py` script is not correctly assessing the system state. As a result, it fails to handle specific situations like enabling dev tools. Furthermore, proper exception handling is not in place while restoring the system state.
Basically if for whatever reason this script errors out we were potentially left in an erroneous state and secondly when `install-dev-tools` had been executed and this got executed, it would change system state to readonly as well.
Also we were repeatedly unnecessarily doing `set_readonly(False)` on different function executions we have which was redundant if it had already executed once.
Correctly assess the system state, including dev tools, and restore the system state accordingly. Additionally, add exception handling and ensure the system state is …
=> NAS-129689 / 24.10 / Properly manage readonly state when executing initrd script

src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/pool_/pool.py, src/middlewared/middlewared/plugins/truecommand/update.py
Currently, `call_with_audit` is not working for APIs that have a return type defined but are jobs. This happens because `call_with_audit` tries to call `schema.dump` for the result, but instead of getting a dict, it gets a job object, which causes an error.
Dump the result only if the API has a return type and it is not a job.
=> NAS-129286 / 24.10 / Do not try to dump result when it is a job

src/middlewared/middlewared/plugins/account.py
Users may receive spurious validation error messages if they bind mount their home dataset to another filesystem path readonly because we are looking up filesystem by dev_t and not the stx_mnt_id.
This commit converts a filesystem.mount_info call for path or parent path into a filesystem.statfs call (which performs correct looup) for the same.
=> NAS-129791 / 24.10 / Fix validation for homedir mountinfo

src/middlewared/middlewared/plugins/enclosure_/enclosure2.py, src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py
Add drive identification support by implementing `set_slot_status` using the redfish `LocationIndicatorActive` attribute.
=> NAS-123835 / 24.10 / Add ES24N drive identification support

src/middlewared/middlewared/plugins/idmap.py
This commit restores previous behavior where we were relying on NSS lookups to convert posix IDs to names. This forced ordering based on names which means that `root` appears before `wheel`.
=> NAS-129827 / 24.10 / Force alphabetical ordering id_to_name results

src/middlewared/middlewared/plugins/idmap.py
This commit restores previous behavior where we were relying on NSS lookups to convert posix IDs to names. This forced ordering based on names which means that `root` appears before `wheel`.
Original PR: https://github.com/truenas/middleware/pull/13960
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129827
=> NAS-129827 / 24.04.3 / Force alphabetical ordering id_to_name results (by anodos325)

src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/network.py
Logged into an internal HA system and noticed that the system was half-updated. A controller was running newer version while the B controller was running old.
I saw that the A controller was master and was reporting that the nics didn't match between the controllers. Investigation found 2 issues:
- iterating over `/sys/class/net` included all entries inside that directory (including files) so this means, if a bond was created a "nic" was being picked up called `bonding_masters`. This is a file so we can fix this method by looking if the object inside `/sys/class/net` is a symlink
- the `failover.mismatch_nics` method was _always_ returning missing nics in the event of a failure because we had bad logic where we were always initializing the variable to a set (i.e. `or set()`) and `{'eno1', …
=> NAS-129862 / 24.10 / fix failover.mismatch_nics

src/middlewared/middlewared/plugins/enclosure_/nvme2.py, src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py
Platform team notified us of a particular gen3 m40 SKU that actually has 4-rear nvme drive bays supported. The proposed and agreed upon solution is to always report 4 rear nvme drive bays for all mseries platforms since they all "have them" but some of them do not have the pcie switch that cables those bays up. The ones that do not have the pcie switch will still show 4 bays but they will always be empty. Not the most elegant but is the best solution.
=> NAS-129539 / 24.10 / always show rear nvme on m-series

src/middlewared/middlewared/plugins/vm/vm_memory_info.py
The ZFS ARC (Adaptive Replacement Cache) is configured to use almost all available free memory. This often results in insufficient free memory to launch a virtual machine, triggering a concerning memory over-commitment dialog.
Include the shrinkable ZFS ARC cache in the calculation of free memory to prevent the ENOMEM (Out of Memory) warning.
=> NAS-129490 / 24.10 / Always include zfs cache as a free memory in vm memory info

src/middlewared/middlewared/api/base/excluded.py, src/middlewared/middlewared/api/v25_04_0/__init__.py, src/middlewared/middlewared/api/v25_04_0/api_key.py, src/middlewared/middlewared/plugins/account_/privilege.py, src/middlewared/middlewared/plugins/api_key.py, src/middlewared/middlewared/utils/allowlist.py
The goal of this PR is to continue replacing the old `@accepts` and `@returns` decorators with the new `@api_method` decorator which enforces types using Pydantic. The eventual end goal is to entirely replace the old style.
Please note that the type hints added will work with the Pydantic validation and with the `@api_method` decorator, but they are not entirely truthful. This is because I have preserved our use of dictionaries for now until further discussion can be had about whether to completely move to using Pydantic models instead of dictionaries. This will enforce greater type control and allow for nicer syntax (e.g. `data.name` instead of `data["name"]`, but it may come at the cost of sometimes needing to convert between dictionaries and Pydantic models.
=> NAS-129754 / 24.10 / Update `api_key.py` to use the new API style

src/middlewared/middlewared/plugins/account.py
Currently the only situation where an immutable user is not also a builtin user is the root-alternative account (admin). It's a POLA violation to allow deletion of immutable account.
=> NAS-129882 / 24.10 / Prevent deletion of immutable users

src/middlewared/middlewared/plugins/directoryservices_/util_cache.py, src/middlewared/middlewared/plugins/idmap.py, src/middlewared/middlewared/utils/tdb.py, tests/api2/test_030_activedirectory.py, tests/api2/test_040_ad_user_group_cache.py
This fixes the following issues:
1. Directory service cache query could return duplicate entries
2. Cache query result keys were out of sync with normal user.query and group.query
3. Detection of id_type_both was broken
Test coverage is added for the above through the following:
1. We were already using set of names returned from cache. Compare set length with original list length.
2. Grant privilege for user.query and group.query for our AD privilege tests. Since it's a limited user the output will pass through schema validation and raise error if they get out of sync with expected.
3. Check id_type_both is set when using RID backend.
There is still an outstanding issue that new schema has broken account queries for directory services as a limited user account. This will cause (2) to …
=> NAS-129879 / 24.10 / Fix issues with directory service cache build

src/middlewared/middlewared/api/base/decorator.py, src/middlewared/middlewared/api/v25_04_0/__init__.py, src/middlewared/middlewared/api/v25_04_0/common.py, src/middlewared/middlewared/api/v25_04_0/vendor.py, src/middlewared/middlewared/plugins/system/vendor/vendor.py
This new vendor plugin will be used in the soon upcoming [NAS-129798](https://ixsystems.atlassian.net/browse/NAS-129797).
Its job is simply to check for the existence of the vendor sentinel file /data/.vendor and return its contents, the vendor name.
I am also proposing two new common API models, `NoArgs` and `NoneReturn`.
=> NAS-129798 / 24.10 / New plugin that checks for the vendor sentinel file

src/middlewared/middlewared/etc_files/scst.conf.mako, src/middlewared/middlewared/plugins/iscsi_/global_linux.py
Previously we were replacing period with underscore in extent names to take account of differences between CORE and SCALE.
In this PR, also replace slash with dash.
(Also move this replacement a little earlier in `scst.conf.mako` so that logging will also be updated/robustness.)
=> NAS-129811 / 24.10 / Perform additional fixup wrt CORE ctl device names

src/middlewared/middlewared/etc_files/scst.conf.mako, src/middlewared/middlewared/plugins/iscsi_/global_linux.py
Previously we were replacing period with underscore in extent names to take account of differences between CORE and SCALE.
In this PR, also replace slash with dash.
(Also move this replacement a little earlier in `scst.conf.mako` so that logging will also be updated/robustness.)
Original PR: https://github.com/truenas/middleware/pull/13974
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129811
=> NAS-129811 / 24.04.3 / Perform additional fixup wrt CORE ctl device names (by bmeagherix)

src/middlewared/middlewared/service/core_service.py
Due to changes in behavior with new api_method decorator the _private attribute is always present for these methods and so we must explicitly check for whether it is True.
=> NAS-129901 / 24.10 / Fix REST methods with versioned API

src/middlewared/middlewared/plugins/pool_/attach_disk.py, src/middlewared/middlewared/plugins/pool_/format_disks.py, src/middlewared/middlewared/plugins/pool_/pool.py, src/middlewared/middlewared/plugins/pool_/replace_disk.py
`pool.format_disks` was being used where it expected job as input and it updated progress without discriminating from where it was being called which would result in incorrect job progress reporting.
Make sure we properly report job progress reporting for endpoints which consume `pool.format_disks`
=> NAS-129230 / 24.10 / Fix progress reporting in formatting disks and it's related usages

src/freenas/debian/preinst
The current log rotation setup has two netdata configurations: the original one and the overwritten one. These conflicting configurations cause issues while rotating logs.
Remove the original Netdata log rotation configuration during the middleware package installation.
=> NAS-129907 / 24.10 / Fix logrotate to work properly

tests/api2/test_zzz_tests_completed.py
The persistent client connection increases our thread count beyond what this test expects. This commit closes it since the connection shouldn't be needed anymore by this point in the test run.
=> Close persistent client connection at end of run

tests/api2/test_210_group.py
Auto-generated winbind groups will no longer resolve into unix groups when generating verbose groupmap output because winbind is no longer by default in the nsswitch.conf due to product improvements allowed by newer GCC in electric eel.
=> NAS-129922 / 24.10 / Fix groupmap test for nsswitch changes

tests/api2/test_user_admin.py
This fixes a test failure due to recent bugfix to prevent deletion of immutable users. The test in question manually edits the account.bsdusers table to allow testing logic related to case when root account is disabled, but then uses user.delete to remove the temporary admin account. The fix is to use datastore plugin to directly delete the new admin user.
=> NAS-129925 / 24.10 / Fix test cleanup after creating temporary admin user

src/middlewared/middlewared/test/integration/utils/client.py
For reasons yet understood, the jenkins pipeline doesn't seem to be reinstalling middleware properly. This meant that the rate limit logic that I added wasn't actually being tested during the CI/CD runs. (I just so happened to be testing manually by hand as well). After a new incremental was generated with the rate limit logic, a large amount of our "roles" related tests failed because they were tripping rate limit.
The `common_checks()` function isn't designed very well and is causing an absurd amount of `auth.login` calls during a test run. Instead of trying to fix that, I took path of least resistance and clear the global rate limit cache when we hit it in the `client` context manager function.
=> NAS-129934 / 24.10 / reset rate limit in client asset for integration tests

tests/api2/test_pool_dataset_acl.py
This adds back the simplified charts acl integration tests that were removed in https://github.com/truenas/middleware/pull/13987. Passing tests are [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1251/testReport/api2/test_pool_dataset_acl/)
=> NAS-129955 / 24.10 / add back simplified APPs acl tests

src/middlewared/middlewared/test/integration/utils/client.py, tests/api2/test_cloud_sync.py
This commit expands the information we can gather from the truenas_server test asset to include the IPs of the current active and standby controllers. These cannot be hard-coded because some tests may initiate reboots or failovers.
=> NAS-129927 / 24.10 / Fix cloudsync HA test

tests/api2/test_300_nfs.py
When introducing the rate limiting functionality in https://github.com/truenas/middleware/pull/13912, I had no choice but to update this file considerably. As part of this process, I caused a minor regression. The return values are an array and so an equivalency test will fail if the values of the array are out of order between the 2 different sides. Fix this by converting the values to a set (like the test did before I changed it). Passing tests are [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1258/testReport/api2/test_300_nfs/test_45_check_setting_runtime_debug/)
=> NAS-129958 / 24.10 / Fix a minor regression in NFS api tests

src/middlewared/middlewared/test/integration/assets/directory_service.py
We should properly clean up after failure in looking up AD domain. While this isn't great because it will report test failures that are external to TrueNAS, we can still get useful info out of test runs.
=> NAS-129963 / 24.10 / Remove fail from test runs on network issues

tests/api2/test_011_user.py
A distant refactor of test_011 caused a regression whereby the `UserAssets.ShareUser01` isn't being cleaned up after the test module runs. This caused an unrelated downstream test to fail (`test_simple_share`) because it asserts that there are 0 SMB share users by the time it runs.
The easiest path forward to fix this is to clean up the aforementioned account in `test_011` as the last step in that module. The link to the passing test is [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1304/testReport/api2/)
=> NAS-129972 / 24.10 / fix test_simple_share_validation

tests/api2/test_simple_share.py
This SMB test may fail if other tests fail to properly clean up temporary users. We should report the usernames so that it's easier to track down offending tests.
=> NAS-129973 / 24.10 / More verbosely indicate unexpected test state in SMB simple share test

src/middlewared/middlewared/plugins/disk_/disk_info.py, tests/api2/test_disk_format.py
Back in https://github.com/truenas/middleware/pull/13945, it was found that we were scrambling the start byte in the `pool.expand` method because we didn't consider 4kn formatted drives. After a long road of despair, the root cause of the problem was found but more importantly a solution was implemented. In my haste, I did not update this test (which was already failing) so I've gone ahead and fixed this test while here.
While working on this test, I uncovered a legitimate bug in our `get_partition_size_info()` function and so I've fixed that as well as tested for it here. The passing test is [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1321/testReport/api2/test_disk_format/)
=> NAS-129976 / 24.10 / Fix disk format api test

src/middlewared/middlewared/plugins/auth.py
The login_banner endpoint needs to be accessible, authenticated or not.
=> Fix login banner

src/middlewared/middlewared/plugins/nfs.py, tests/api2/test_300_nfs.py
The NFS share validation checks were too restrictive and were blocking valid configurations.
For example, we would block the following:
```
/mnt/tank/nfs 192.168.0.0/16(rw)
/mnt/tank/nfs 192.168.0.1(ro)
```
We will no longer block host entries that are overlapped by a network entry.
We _will_ continue to block overlapped network entries.
This PR also includes some refactoring in CI module:
- Move all pytest dependency checks to decorators
- Clean up parametrized tests and add ids
=> NAS-129577 / 24.10 / Relax NFS share validation

src/middlewared/middlewared/plugins/iscsi_/target_to_extent.py, src/middlewared/middlewared/plugins/iscsi_/targets.py, tests/api2/assets/websocket/iscsi.py, tests/api2/test_261_iscsi_cmd.py, tests/api2/test_262_iscsi_alua.py
When a LUN is removed from an ALUA target, we were already calling `iscsi.alua.removed_target_extent` to perform some fixup.  However, because this was being called on the STANDBY **before** the MASTER node was updated the LUN was still available and logged into by the STANDBY node.  Simply reordering _avoids_ the issue.
(For robustness, this PR also adds a check/delay to ensure that the LUN is removed from the MASTER before `removed_target_extent` is called on the STANDBY.)
Add CI tests to check proper operation wrt adding and removing LUNs from an existing ALUA target.  Separated these tests out into a new file (_test_262_iscsi_alua.py_) and structured to ease adding additional ALUA tests (e.g. to `TestFixtureConfiguredALUA`)
Passing CI test …
=> NAS-129776 / 24.10 / Fix iSCSI ALUA LUN removal issue

src/middlewared/middlewared/plugins/iscsi_/target_to_extent.py, src/middlewared/middlewared/plugins/iscsi_/targets.py, tests/api2/assets/websocket/iscsi.py, tests/api2/test_261_iscsi_cmd.py, tests/api2/test_262_iscsi_alua.py
git cherry-pick -x 6c32f2973ccd316f7d13ca831ea1bc4ed8499046
git cherry-pick -x fa80f4021bc602fe1504e4b3c27dce0ab97d1500
git cherry-pick -x 4bc6312b8516e67f723df8d877c48e16b9ed2e89
git cherry-pick -x 4626157cbe9697c7fed56dafacbe833f649093f4
git cherry-pick -x ef5835af70a9e6103b31952ec2b378305d2b296b
git cherry-pick -x d8d3ae1d774c07d8ef27838789e98e5c7de9a494
git cherry-pick -x 9a1fda3bb1403e16aa12e528b5c3a430ea9cd90a
git cherry-pick -x e9ca3b1de2c89e1aef827b3ba5c6eca12e881fd3
git cherry-pick -x 274a2446d4054750624ea4b20ba431e32d566149
When a LUN is removed from an ALUA target, we were …
=> NAS-129776 / 24.04.3 / Fix iSCSI ALUA LUN removal issue (by bmeagherix)

src/middlewared/middlewared/plugins/system_advanced/config.py
When users switch from system advanced TLS settings to UDP/TCP, they are unable to delete the certificate and certificate authority (CA) that were previously used by TLS settings. This occurs because the certificates still exist in the system advanced syslog settings. As a result, the middleware still sees those certificates as being used by the syslog.
Set the certificate and CA to null if TLS is not configured in the system advanced syslog settings.
=> NAS-129908 / 24.10 / Unset syslog certs if tls transport is not being used

src/middlewared/middlewared/plugins/auth.py, src/middlewared/middlewared/plugins/system_advanced/config.py
Our login banner endpoint needs to be accessible to unauthenticated users
This also fixes an issue from yesterday where I somehow changed the wrong endpoint, I don't know how that happened but I caught it
=> NAS-129999 / 24.10 / Fix login banner perms

tests/api2/test_200_ftp.py
Previously the `test_070_resume_xfer` test was failing _**every**_ time with:
```
processing = "download"
download_partial(ftpObj, remotefname, localfname, 768)
>               ftpObj.quit()
api2/test_200_ftp.py:1181: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.11/ftplib.py:659: in quit
resp = self.voidcmd('QUIT')
/usr/lib/python3.11/ftplib.py:286: in voidcmd
return self.voidresp()
/usr/lib/python3.11/ftplib.py:259: in voidresp
resp = self.getresp()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <ftplib.FTP object at 0x7fadb211af50>
def getresp(self):
resp = self.getmultiline()
if self.debugging:
print('*resp*', self.sanitize(resp))
self.lastresp = resp[:3]
c = resp[:1]
if c in {'1', '2', '3'}: …
```
=> NAS-130001 / 24.10 / Catch exception thrown by ftp QUIT.

src/middlewared/middlewared/api/v25_04_0/user.py, src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/directoryservices_/util_cache.py, src/middlewared/middlewared/plugins/idmap.py, src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/constants.py, src/middlewared/middlewared/plugins/smb_/groupmap.py, src/middlewared/middlewared/plugins/smb_/passdb.py, src/middlewared/middlewared/plugins/smb_/sid.py, src/middlewared/middlewared/plugins/smb_/util_groupmap.py, src/middlewared/middlewared/plugins/smb_/utils.py, src/middlewared/middlewared/pytest/unit/utils/test_groupmap.py, src/middlewared/middlewared/pytest/unit/utils/test_sid.py, src/middlewared/middlewared/utils/sid.py, src/middlewared/middlewared/utils/tdb.py, tests/api2/test_011_user.py, tests/api2/test_210_group.py, tests/api2/test_420_smb.py, tests/api2/test_smb_groupmap.py
Do not rely on Samba to generate a new system SID and make randomized
SID persistent across server changes. This is to help prevent admin
foot-shooting when they choose to make major server changes that force
Samba to regenrate a new SID and thus invalidate their share ACLs.
on production servers.
Since local user / group RID values are deterministic based on the id
key for user / group accounts, populate `sid` key in user.query and
group.query extend methods. Apply similar logic to short-circuit
SID conversion.
The nt_name key provides little value to API consumers and so remove
for account entries.
Remove subprocess call to `net groupmap` in favor of using our tdb
utilities to directly alter the group_mapping.tdb file. This generally
performs better and avoids having to synchronize …
=> NAS-129929 / 24.10 / Improve SID handling

src/freenas/debian/preinst, src/freenas/etc/tmpfiles.d/nut.conf, src/freenas/usr/lib/netdata/charts.d/nut_ups.chart.sh, src/middlewared/middlewared/etc_files/local/nut/ups_config.py, src/middlewared/middlewared/etc_files/local/nut/upssched.conf.mako
Currently, the Netdata user cannot access the `/run/nut/upsmon.pid` file, causing it to return dummy UPS data even after UPS is started. Furthermore, the dummy UPS data is causing problems in the Netdata UI because users can see the dummy UPS when using netdata webui, which doesn't actually exist. Additionally, there is an issue with the UPS graphs showing spikes instead of a straight line. This is due to the UPS chart.d plugin sleeping for 60 seconds, and the Netdata natural points flag not working correctly.
Refactor the UPS plugin to remove the need for dummy UPS data by not sending any metrics if the UPS is not running. This will keep the UPS plugin running without errors and it will start working normally once the UPS starts. Also, fix `/run/nut` permissions to make it accessible to …
=> NAS-129807 / 24.10 / Fix nut reporting in netdata

src/middlewared/middlewared/plugins/directoryservices_/cache.py
An area where nt_name was being added to cache query results was missed when user and group entries were being simplified, which caused the schema dump for restricted users to fail due to extra entry. This was not caught during testing due to AD restricted admin tests being skipped, but regression was caught by normal full CI runs.
=> NAS-130014 / 24.10 / Fix regression in restrict admin account query

src/middlewared/middlewared/plugins/vm/pci.py, src/middlewared/middlewared/plugins/vm/utils.py, src/middlewared/middlewared/pytest/unit/plugins/test_gpu_critical.py, src/middlewared/middlewared/pytest/unit/plugins/vm/test_pci_device_iommu_groups.py, src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_gpu_pci_choices.py, src/middlewared/middlewared/utils/gpu.py, src/middlewared/middlewared/utils/iommu.py, src/middlewared/middlewared/utils/pci.py
When we want to passthrough a GPU, what needs to happen is that all the IOMMU groups with all their devices including ones which are not GPU related in which the GPU's devices are placed need to be isolated.
Currently we had validation in place where we didn't allow to isolate a GPU if any of it's devices were critical for the system like CPU/memory etc - however this can result in a scenario where the following happens:
A GPU having a device which is in an IOMMU group which has a critical device, so when that GPU is going to be configured for passthrough and an attempt to start the VM is going to be made, that will crash.
Properly mark a GPU as critical covering the case discussed above so we don't allow isolating such GPU's in the first place. Secondly a reasonable critical reason has …
=> NAS-129905 / 24.10 / Mark GPU as critical if it has devices which are in an iommu group which has a critical device

tests/api2/test_420_smb.py, tests/api2/test_427_smb_acl.py, tests/api2/test_435_smb_registry.py
This commit cleans up some of the SMB CI tests and fixes a few issues:
* Rapid restarts of SMB service was hitting systemd service restart limit causing spurious test failures
* Dynamic generation of nsswitch.conf means that Owner Rights group will resolve via NSS and so the ACL inheritance test needs to use gid instead of name
* Convert a lot of test cases to use pytest fixtures to properly manage test state.
* Fix a few tests related to auxiliary parameters.
=> NAS-130015 / 24.10 / Fix failing SMB CI tests

src/middlewared/middlewared/plugins/smb_/groupmap.py, src/middlewared/middlewared/plugins/smb_/util_groupmap.py, src/middlewared/middlewared/pytest/unit/utils/test_groupmap.py
The SID check for user being member of BUILTIN\Administrators was failing due to a regression introduced by removing subprocess calls to net groupmap. This fixes how groupmem entries are generated and adds more comprehensive checks to remove unexpected entries.
=> NAS-130018 / 24.10 / Fix access issue for SMB quotas for local admins

tests/api2/test_draid_record_and_block_size.py
Now that our primary CI test runs are against HA targets we should avoid skipping due to HA whenever possible. The HA test runners are now capable of handling the larger disk count requirements..
=> NAS-130037 / 24.10 / Run DRAID tests on HA

src/middlewared/middlewared/plugins/apps/crud.py, src/middlewared/middlewared/plugins/apps/ix_apps/path.py, src/middlewared/middlewared/plugins/apps/resources.py, src/middlewared/middlewared/plugins/apps/rollback.py, src/middlewared/middlewared/plugins/apps/schema_action_context.py, src/middlewared/middlewared/plugins/apps/schema_normalization.py, src/middlewared/middlewared/plugins/apps/schema_utils.py, src/middlewared/middlewared/plugins/apps/schema_validation.py, src/middlewared/middlewared/plugins/apps/upgrade.py, src/middlewared/middlewared/plugins/apps/utils.py, src/middlewared/middlewared/plugins/catalog/apps_details.py
This PR restores features support in apps schema so app developer can have a way of retrieving information from the running SCALE instance.
We would be adding more refs but after coordinating with Stavros on what needs to be added so that we are enforcing it on apps side as well (that should be relatively straight forward now considering the framework is in place to support those).
=> NAS-130078 / 24.10 / Add features support for apps in app schema

src/middlewared/middlewared/alert/base.py, src/middlewared/middlewared/alert/source/audit.py, src/middlewared/middlewared/plugins/audit/audit.py, src/middlewared/middlewared/plugins/audit/backend.py, tests/api2/test_audit_alerts.py
* Add one-shot alert for failure to start audit backends.
* Add one-shot alert for failure to run audit setup configuration
* Add an audit 'health' check that performs a simple query every 20 mins and generate an alert if the query fails.
Some Flake8 cleanup.
Add CI tests for all three.
The CI test results are [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1456/testReport/api2/test_audit_alerts/).
=> NAS-127735 / 24.10 / Add alerts for critical audit service failures

src/middlewared/middlewared/plugins/directoryservices.py
This fixes two bugs that were introduced on fresh boot of TrueNAS and weren't caught in testing due to particulars of how reinstalling middleware happens in our CI. The method to create a persistent keyring was refactored away during development and a typo was present in code path only exercised on first boot.
=> NAS-130095 / 24.10 / Fix typos in directory services plugin

src/middlewared/middlewared/plugins/directoryservices_/cache.py
SSSD will report a domain as online while it is still building internal caches and unable to properly handle NSS requests. This commit adds checks / sleeps in the directory services cache fill method until a getpwent call to the SSS NSS module returns an entry.
=> NAS-130098 / 24.10 / Fix initial cache fill for LDAP and IPA

src/middlewared/middlewared/utils/directoryservices/krb5_constants.py, tests/api2/test_032_ad_kerberos.py
We still need to have a temporary ccache for validating credentials within secrets.tdb, and the test for klist output needs to be updated for the keyring-backed kerberos ccache.
=> NAS-130099 / 24.10 / Fix test regressions related to krb5 ccache change

tests/api2/test_audit_nfs.py
This API endpoint was removed in favor of automatically creating NFS configuration when joining AD / FreeIPA.
=> NAS-130102 / 24.10 / Remove test for auditing nfs.add_principal

tests/api2/test_278_freeipa.py
By the time we get to this test we've already accumulated a number of alerts. Simply check that the expected one is in the mix.
=> NAS-130113 / 24.10 / Fix alert test for legacy IPA bind

src/middlewared/middlewared/plugins/pool_/dataset.py, tests/api2/test_427_smb_acl.py
Some of our users are swapping out dataset configuration under Samba.  This can cause undefined behavior. 
User should be prompted to disable active shares / remove configuration before changing the following dataset properties:
`acltype`, `xattr`
Includes CI test.  Results are [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1483/testReport/api2/test_427_smb_acl/).
=> NAS-129743 / 24.10 / Prevent acltype and xattr dataset changes if hosting an SMB share

src/middlewared/middlewared/utils/directoryservices/krb5.py
It appears that `__tmp_krb5_keytab` was creating **two** temp files.
=> NAS-130127 / 24.10 / Extra temporary file created by __tmp_krb5_keytab

src/middlewared/middlewared/plugins/directoryservices.py
There was a middleware call typo in the file.
=> NAS-130140 / 24.10 / Fixed status directoryservices.py

src/middlewared/middlewared/etc_files/krb5.conf.py, src/middlewared/middlewared/plugins/directoryservices_/cache.py, src/middlewared/middlewared/plugins/directoryservices_/health.py, src/middlewared/middlewared/plugins/directoryservices_/ipa_join_mixin.py, src/middlewared/middlewared/plugins/ldap.py, tests/api2/test_275_ldap.py, tests/api2/test_ipa_join.py
This adds back in missing cherry-pick from development branch to properly grant privileges to the admins group in an IPA domain.
=> NAS-130116 / 24.10 / Fix ipa join admin privileges and keytab

src/middlewared/middlewared/etc_files/docker/daemon.json.py, src/middlewared/middlewared/utils/gpu.py
By bringing in docker proper, and using the upstream repo to follow latest stable release, we're able to clean this up since the hacks are no longer required (I've confirmed this on a system with 2x discrete nvidia gpus).
Furthermore, our `device.get_info` endpoint is entirely too complicated for what we do here when generating this daemon.json file. I've added a new `get_nvidia_gpus` function that is 100x faster than `device.get_info`. There is no functional change in behavior.
=> NAS-130119 / 24.10 / quick nvidia gpu detection for daemon.json

src/freenas/debian/rules, src/middlewared/middlewared/alert/source/admin_user.py, src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/config.py, src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/plugins/filesystem_/acl.py, tests/api2/test_001_ssh.py, tests/api2/test_user_truenas_admin.py
Existing systems will be kept intact. New users will only be able to install theri systems using `truenas_admin` username.
=> NAS-129997 / 24.10 / `admin` -> `truenas_admin`

src/middlewared/middlewared/plugins/directoryservices_/ipa_join_mixin.py, src/middlewared/middlewared/plugins/directoryservices_/join.py, src/middlewared/middlewared/plugins/ldap.py, src/middlewared/middlewared/plugins/smb_/util_smbconf.py, src/middlewared/middlewared/pytest/unit/plugins/test_smb.py, src/middlewared/middlewared/test/integration/assets/directory_service.py, tests/api2/test_ipa_join.py, tests/api2/test_ipa_leave.py
Although leaving IPA domain isn't exposed currently via public API or GUI, it is useful for cleaning up after CI runs.
This commit adds:
- internal endpoint to use nsupdate to remove DNS entries
- DNS-related tests for IPA domain
- tests for cleanly leaving IPA domain
=> NAS-130159 / 24.10 / Add IPA leave and expand testing

src/middlewared/middlewared/plugins/apps/resources.py, src/middlewared/middlewared/plugins/catalog/apps_details.py
`apps_validation` requires available node bind ips available in questions context so it can properly render available bind ips which user can consume with an application.
=> NAS-130170 / 24.10 / Add available node bind ips to questions context

tests/api2/test_420_smb.py
Each test run initializes the SMB netbiosname to a randomized value. We need to restore this after testing the a netbiosname change doesn't change the server's domain SID.
=> NAS-130174 / 24.10 / Prevent test run state pollution from test

src/middlewared/middlewared/etc_files/scst.conf.mako
When link-local addresses are included in Send Targets response, it can cause breakage at the initiator, depending on whether or not it handles the zone-index and/or whether the client interface names _happen_ to line up with the TrueNAS system.  This is currently broken in `open-iscsi`.
Since link-local addresses are non-routable, the safest approach is to not include them in the Send Targets output.  [If no non-link-local addresses are present then querying the link-local IPv6 will still include that address (only).]
(See upstream `scst` PR #[228 ](https://github.com/SCST-project/scst/pull/228)for more info)
---
CI run with passing iSCSI tests is [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1615/).
=> NAS-130178 / 24.10 / Disable IPv6 link_local addresses in Send Targets output

src/middlewared/middlewared/plugins/apps/compose_utils.py
When we have a running app and system is rebooted, any docker networks which might have been created don't have their associated interfaces anymore present after the reboot. So if an attempt to start the app is made, what happens is that process fails. For starting the app `docker compose up --force-recreate` is used, however this does not re-create the docker networks and eventually the interfaces as well which are associated with it. It fails with something like
```
Error response from daemon: failed to create endpoint ix-nginx-perms-1 on network ix-nginx_default: adding interface vethb6475a1 to bridge br-62cbfa232e0b failed: Device does not exist
```
We make sure whenever compose up action is desired, any networks in place are removed first for the app so that the app can safely start.
=> NAS-130199 / 24.10 / Make sure docker networks get recreated with compose up action

src/middlewared/middlewared/plugins/apps/crud.py, src/middlewared/middlewared/plugins/apps/ix_apps/metadata.py, src/middlewared/middlewared/plugins/apps/ix_apps/portals.py, src/middlewared/middlewared/plugins/apps/ix_apps/query.py
Portals or app install notes were not being shown when apps were being queried.
Portals / app install notes have been added to app metadata which is being saved to optimize querying them and it will be included in query output when querying apps.
=> NAS-130172 / 24.10 / Fix portals when querying apps

src/middlewared/middlewared/plugins/system_vendor/vendor.py
The existing grub generation code properly sets the vendor text, rerunning after we delete the `/data/.vendor` file generates our default TrueNAS Scale grub config
=> NAS-130161 / 24.10 / Regenerate grub config on unvendor

src/middlewared/middlewared/job.py
Parameters order was changed, but no callers use positional args so we're good.
=> NAS-130214 / 24.10 / Make `Job.wait_sync` signature match `Job.wait`

src/middlewared/middlewared/job.py, tests/api2/test_job_errno.py
We sometimes use errno to indiciate particular error reasons. Putting this in exc_info makes it easier for client to convert the job result back into a CallError without loss of information.
=> NAS-130192 / 24.10 / Include errno in exc_info for jobs

src/middlewared/middlewared/service/core_service.py, tests/api2/test_job_result.py
This commit makes it slightly easier to avoid user foot-shooting by defaulting to redacting job result in external calls to core.get_jobs.
=> NAS-130142 / 24.10 / Default to redacting result from core.get_jobs

src/middlewared/middlewared/plugins/iscsi_/extents.py, tests/api2/test_261_iscsi_cmd.py
When a user does a `zfs destroy` at the command line, middleware can end up in a situation where it cannot delete an iSCSI extent.  Rectify.
Added a CI test for this, plus one wrt `volthreading`.
---
Passing CI run is [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1628/).
=> NAS-130103 / 24.10 / Allow extent to be deleted even if underlying storage is missing

src/freenas/usr/local/bin/truenas-grub.py, src/middlewared/middlewared/plugins/support.py
On a vendored system, we want to prevent tickets made via the API from going through. On top of returning false in `is_available`, we also raise an error if the ticket creation API method is called directly.
I also updated the grub generation to match the paradigm in [this PR](https://github.com/truenas/truenas-installer/pull/87).
If there are other areas that need to have these safeguards, let me know!
=> NAS-130160 / 24.10 / Prevent bug tickets from vendored install

src/middlewared/middlewared/service/core_service.py
A recent change to exc_info dictionary inside core.get_jobs output was not reflected in the returns decorator schema.
=> NAS-130234 / 24.10 / Add errno entry to exc_info in core.get_jobs schema

tests/api2/test_001_ssh.py
We have 1 failing API test and its this one. This is a known problem and the OS team has been made aware. They're working on a fix but it's complicated so we'll skip it for now. We  have a high priority ticket internally.
=> NAS-130240 / 24.10 / skip known failing test

tests/api2/test_001_ssh.py
Multiple mount options are broken at boot so we'll skip the entire section for now.
=> NAS-130243 / 24.10 / really skip the final remaining failing test

tests/api2/test_002_system_license.py
Improve this test by:
1. using the `test.integration.utils::call` function
2. use pytest.mark.skipif decorator
Passing test is [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1654/testReport/api2/test_002_system_license/)
=> NAS-130242 / 24.10 / improve test_002

src/middlewared/middlewared/plugins/jbof/crud.py
During JBOF configuration only permit a single data-plane IP to be connected (per node).
=> NAS-127395 / 24.10 / Prevent ES24N multipath

src/middlewared/middlewared/plugins/network.py, tests/api2/test_005_interface.py
This prevents clearing `failover_group` from a NIC marked as `failover_critical`
=> NAS-130230 / 24.10 / Prevent removing failover group from critical interfaces

src/middlewared/middlewared/plugins/activedirectory.py
If DNS lookup fails due to broken networking or domain being inaccessible then this may fail with a dns.resolver exception and prevent disabling the activedirectory service.
=> NAS-130255 / 24.10 / Avoid DNS lookup when disabling Active Directory

src/middlewared/middlewared/plugins/directoryservices_/health.py
There are some edge cases with restarting middleware in which we can deadlock on the etc.generate lock for the kerberos group if we're joined to AD (by calling into directoryservices.health.check repeatedly). This fixes the issue by initializing the health state if required when we first enter the directoryservices.health.check method.
=> NAS-130256 / 24.10 / Avoid deadlocking during DS health initialization

src/middlewared/middlewared/alert/base.py, src/middlewared/middlewared/plugins/alert.py, src/middlewared/middlewared/plugins/cloud_sync.py
Dangling cloud sync task alerts should have been fixed in 22.12, but the issue presented itself again. Let's put an additional layer of protection.
=> NAS-129603 / 24.10 / Do not load alerts for resources that do not exist

src/middlewared/middlewared/plugins/apps/app_scale.py, src/middlewared/middlewared/plugins/apps/ix_apps/query.py
Now as on compose up action when we force_recreate resources (this happens when update_internal runs), we do compose down automatically to make sure we account for the docker case where it did not account for interfaces for networks. So running a stop job before running `update_internal` is redundant now and not required.
=> NAS-130263 / 24.10 / There is no need to stop when redeploying app now

src/middlewared/middlewared/plugins/apps/crud.py, src/middlewared/middlewared/plugins/apps/ix_apps/lifecycle.py, src/middlewared/middlewared/plugins/apps/rollback.py, src/middlewared/middlewared/plugins/apps/upgrade.py
It was requested by Stavros that app have more context passed to them when the app is rendering it's compose file - requested changes have been made and some minor improvements in upgrade have also been done.
=> NAS-130264 / 24.10 / Pass more context to apps when doing app operations

src/middlewared/middlewared/plugins/jbof/crud.py
Very unlikely that this alert will ever be raised, but it needs to be cleared on the subsequent reboot.
=> NAS-130312 / 24.10 / Clear JBOFTearDownFailure alert following reboot

tests/api2/test_261_iscsi_cmd.py
Add some retries if we don't have the expected number of entries.
----
Passing CI test run [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1726/)
=> NAS-129996 / 24.10 / Robustize get_iscsi_sessions function used in tests

src/middlewared/middlewared/plugins/network.py
We chose a poor method name `interface.internal_interfaces` isn't actually the interface names. It's the prefixes of interface names. QE found that the `ix-truecommand` interface was triggering an HA mismatch nics alert message. This fixes the problem.
=> NAS-130314 / 24.10 / properly exclude internal ifaces in get_nic_names

tests/api2/test_261_iscsi_cmd.py, tests/protocols/iscsi_proto.py
When run against a HA system `test_19_alua_config` will now perform **TWO** reboots to test failover/failback wrt iSCSI ALUA targets.
The second reboot is being added to return the system to the original ACTIVE node.  This means that subsequent tests will run on the same node that the previous tests started on.  This was requested to ease log analysis.
Took this opportunity to add an additional target/extent for the failback, and add (many) associated checks.
(Also refactored to move setting iscsi client `blocksize` into `iscsi_scsi_connect`, eliminating cruft.)
----
Passing CI run is [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1696/).
=> NAS-130273 / 24.10 / Add failback to ALUA config test

tests/api2/test_300_nfs.py, tests/runtest.py
The NFS syslog filter test has been historically problematic.  Most of the time the expected messages show up quickly in syslog. 
The issue being addressed here is that under certain, as yet unknown, conditions the expected syslog messages can take over a minute to show up.
We already have a wait loop.  This PR slightly extends the wait time.
Some other minor tweaks:
* Add some comments
* Always grab 30 lines from syslog
* Make the number of retries a variable.
=> NAS-130315 / 24.10 / Fix nfs syslog filter test

tests/api2/test_300_nfs.py, tests/runtest.py
Over the weekend there was a spate of failures on the NFS `manage gids` and `v4 domain` tests. 
It appears the problem was reading the config file too quickly. 
To avoid this in the future this PR adds a one second sleep between the `update` call and the parsing of the config file.
=> NAS-130317 / 24.10 / Robustize nfs manage gids and v4 domain tests

src/middlewared/middlewared/alert/source/datasets.py, src/middlewared/middlewared/plugins/catalog/apps_details.py, src/middlewared/middlewared/plugins/cloud_sync.py, src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/plugins/pool_/dataset.py, src/middlewared/middlewared/plugins/pool_/export.py, src/middlewared/middlewared/plugins/pool_/import_pool.py, src/middlewared/middlewared/validators.py
We treated `ix-applications` specially in different places to avoid spam and make sure nothing unintended happened as the dataset had custom properties in place. This is mostly true for `ix-apps` dataset as well where we don't want to show it's children in the UI to reduce spam and also make sure in other places where we managed `ix-applications`, we have similar handling in place for `ix-apps` to avoid breaking new apps functionality.
=> NAS-130324 / 24.10 / Treat ix-apps dataset specially in pool.dataset namespace

src/middlewared/middlewared/plugins/filesystem.py
ix-apps dataset is mounted to a special mountpoint in /mnt and so must be excluded explicitly only if path being listed is /mnt.
=> NAS-130326 / 24.10 / Properly exclude ix-apps dataset from filesystem.listdir

src/middlewared/middlewared/validators.py
The special mountpoint `/mnt/.ix-apps` will not be included in the volumes list and so will fail with normal check for whether the path resides within an expceted volume.
Since we no longer use ix-applications dataset for the purposes of our apps implmenetation we no longer need to stricty check for this dataset and raise a validation error.
=> NAS-130327 / 24.10 / Remove ix-apps reference to path validator

src/middlewared/middlewared/plugins/docker/update.py
When we switch from one pool to another pool in docker, it is not seamless because we are not stopping docker service and it is only being stopped if we unconfigure the docker pool first.
Make sure we stop docker service and then setup the other pool.
=> NAS-130330 / 24.10 / Fix switching docker pools

src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/util_sd.py, tests/api2/test_audit_smb.py
Add auditing for changes to smb.update, smb.getacl, smb.setacl, sharing.smb.create, sharing.smb.update, and sharing.smb.delete.
=> NAS-129295 / 24.10 / Audit changes to the SMB server configuration

src/middlewared/middlewared/plugins/catalog/apps_details.py
This commit adds changes to allow port choices for apps to start from 1 as we already validate if the port is in use or not (earlier it was 1025).
=> NAS-130341 / 24.10 / Allow port choices for apps to start from 1

src/middlewared/middlewared/plugins/vm.py
Switch to tcp mode for bhyve VNC sessions with community provided patch. Breaks some RGB color pallet in the WebVNC, but otherwise is reported as functional and restores basic VNC functionality. 
Note: Bhyve is unsupported in 13.3, we will not be doing any additional testing of this.
=> NAS-130278 / 13.3 / NAS-130278 - Community Patch - Switch to bhyve TCP mode to fix VNC connections

src/middlewared/middlewared/plugins/filesystem_/acl_template.py
Since this method was originally written the python winbind client bindings have changed so that the key is dns_name instead of alt_name.
=> NAS-130345 / 24.10 / Fix KeyError in acltemplate plugin

src/middlewared/middlewared/plugins/smb.py
This commit adds a missed cherry-pick from the testing branch where SMB share auditing was being validated. The phrasing was altered to match existing NFS share audit messages.
=> NAS-130346 / 24.10 / Fix audit messages for SMB shares

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/utils/crypto.py
Samba's python bindings provide what's needed to generate the hash used for passdb entries without having to work through hashlib and potentially forcibly enable legacy encryption.
=> NAS-130366 / 24.10 / Use Samba libraries to directly generate MD4

src/middlewared/middlewared/plugins/account.py
We've seen users upload invalid contents to the authorized key file for a local user. We can't prevent this foot-shooting, but we should squelch the error since our API fails pretty spectacularly here.
=> NAS-130414 / 24.10 / handle Unicode errors in authorized key file

tests/runtest.py
This somewhat reduces risk of two simultaneously booted HA VMs trying to get the same virtual IP as well as reducing the impact of an AD test run failing to properly clean up after itself.
=> NAS-130417 / 24.10 / Shuffle virtual IPs for VMs in runtest.py

src/middlewared/middlewared/plugins/pool_/dataset.py, tests/api2/test_audit_dataset.py
Generate audit trail when datasets created, updated, and deleted.
=> NAS-130420 / 24.10 / Add auditing for dataset CRUD operations

tests/api2/test_system_general_ui_rollback.py
This fixes our UI rollback test by wrapping our update dependent client calls in a contextmanager that retires connecting to the client or a set amount of tries.
[Passing test](http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1795/console)
=> NAS-130344 / 24.10 / Fixed UI rollback test

src/middlewared/middlewared/plugins/api_key.py, tests/api2/test_audit_api_key.py
Generate an audit trail for changes to API keys.
=> NAS-130428 / 24.10 / Add auditing for API key CRUD operations

src/freenas/etc/systemd/network/10-persistent-net.link
At time of writing, ntb on SCALE has pathological behavior related TCP/IP Window size calculation whereby the receiving side clamps the window size to 0 causing recalculation which, ultimately, ends with behavior described in https://en.wikipedia.org/wiki/Silly_window_syndrome. The work-around is to drop MTU size a bit which fixes the scenario altogether. When we discover why this is happening, we should remove the MTUBytes line in this file.
=> NAS-130434 / 24.10 / drop ntb0 MTU to 64000

src/freenas/etc/systemd/network/10-persistent-net.link
At time of writing, ntb on SCALE has pathological behavior related TCP/IP Window size calculation whereby the receiving side clamps the window size to 0 causing recalculation which, ultimately, ends with behavior described in https://en.wikipedia.org/wiki/Silly_window_syndrome. The work-around is to drop MTU size a bit which fixes the scenario altogether. When we discover why this is happening, we should remove the MTUBytes line in this file.
Original PR: https://github.com/truenas/middleware/pull/14136
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130434
=> NAS-130434 / 24.04.3 / drop ntb0 MTU to 64000 (by yocalebo)

src/middlewared/middlewared/plugins/account.py, tests/api2/test_password_reset.py
Generate an audit trail for when user account has password manually reset via dedicated API.
=> NAS-130433 / 24.10 / Audit user password reset

src/middlewared/middlewared/plugins/filesystem_/acl.py
It's technically possible that a user creates a zpool with the top level dataset configured with NFSv4 acltype and then modifies it via shell-based utilities outside of our API. In this case we need to allow skipping ACL path validation that prevents using the top-level dataset of a pool while calculating what our inherited ACL should be for a newly-created dataset.
=> NAS-130413 / 24.10 / Fix get inherited ACL when top-level ds has ACL

src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
It's technically possible that a user creates a zpool with the top level dataset configured with NFSv4 acltype and then modifies it via shell-based utilities outside of our API. In this case we need to allow skipping ACL path validation that prevents using the top-level dataset of a pool while calculating what our inherited ACL should be for a newly-created dataset.
Original PR: https://github.com/truenas/middleware/pull/14133
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130413
=> NAS-130413 / 24.04.3 / Fix get inherited ACL when top-level ds has ACL (by anodos325)

src/middlewared/middlewared/plugins/account.py
We don't currently consume this endpoint and have already marked it as deprecated. Remove it completely to eliminate an endpoint that allows unauthenticated access.
=> NAS-130444 / 24.10 / Remove deprecated user.set_root_password method

src/middlewared/middlewared/plugins/pool_/replace_disk.py, src/middlewared/middlewared/test/integration/assets/pool.py, tests/api2/test_pool_replace_disk.py
In https://github.com/truenas/middleware/commit/026691d39e4711107f40c7d0e8b48bbfc4788e9e, a commit was made to also wipe the disk that was being replaced when `pool.replace` was being called. I looked at that ticket but it's still not clear to me why this logic was added. In every possible scenario, it's entirely unnecessary to wipe the disk that is being replaced. Remove that logic and update `pool_replace_disk` api test accordingly. (also improve the test by documenting it as well).
=> NAS-130440 / 24.10 / fix pool.replace regression (introduced in 026691d39e4711107f40c7d0e8b48bbfc4788e9e)

src/middlewared/middlewared/plugins/replication.py, src/middlewared/middlewared/plugins/snapshot.py
Generate audit trail when users configure snapshots and replication.
=> NAS-130459 / 24.10 / Add audit trails for snapshot and replication tasks

src/middlewared/middlewared/plugins/apps/crud.py, src/middlewared/middlewared/plugins/apps/ix_apps/metadata.py, src/middlewared/middlewared/plugins/catalog/sync.py, src/middlewared/middlewared/plugins/docker/state_setup.py, src/middlewared/middlewared/plugins/kubernetes_to_docker/list_k8s_backups.py, src/middlewared/middlewared/plugins/kubernetes_to_docker/list_utils.py, src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py
This PR adds changes so that consumers can now execute app migration from k8s to docker even if it has already been applied. Motivation for this change is to allow users to migrate apps which were not migrated before because of perhaps the app not existing in the new catalog or it's migration script not being available on the apps side.
It also adds `migrated` flag which shows if the app was migrated over from k8s or is a newly installed app.
=> NAS-130450 / 24.10 / Add changes to allow executing apps migration more then once

src/middlewared/middlewared/plugins/pool_/replace_disk.py, src/middlewared/middlewared/test/integration/assets/pool.py, tests/api2/test_pool_replace_disk.py
In https://github.com/truenas/middleware/commit/026691d39e4711107f40c7d0e8b48bbfc4788e9e, a commit was made to also wipe the disk that was being replaced when `pool.replace` was being called. I looked at that ticket but it's still not clear to me why this logic was added. In every possible scenario, it's entirely unnecessary to wipe the disk that is being replaced. Remove that logic and update `pool_replace_disk` api test accordingly. (also improve the test by documenting it as well).
Original PR: https://github.com/truenas/middleware/pull/14151
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130440
=> NAS-130440 / 24.04.3 / fix pool.replace regression (introduced in 026691d39e4711107f40c7d0e8b48bbfc4788e9e) (by yocalebo)

src/middlewared/middlewared/plugins/filesystem_/acl.py, src/middlewared/middlewared/plugins/pool_/dataset.py
When TrueNAS is joined to active directory it's possible that the AD administrator has created nested security groups in such a way that it becomes non-trivial to validate whether a user can gain access to a path by virtue of being a member of a particular group.
This is because the nested security groups are flattened only when resolving the groups for a particular user via getgrouplist(3).
Since nested groups only exist if directory services are enabled, this bypass raises a ValidationError if the server is in a standalone configuration.
We still default to checking access (previous behavior) because using nested security groups in this way is a security anti-pattern as it renders the effective permissions on filesystem paths very difficult or impossible to easily audit.
=> NAS-130338 / 24.10 / Allow overriding execute check in setacl in some cases

src/middlewared/middlewared/plugins/vm/lifecycle.py
We were running into an issue where shutdown would be halted because of VMs even if they are not running. Changes were added (https://github.com/truenas/middleware/pull/13909) to not make an attempt to de-initialize vms if none of them are running but we still left a case.
Service's terminate methods are called when middleware is shutting down and in this case, what we were doing for VMs was:
1. Closing middleware libvirt socket connection
2. Reloading http service
Now for reasons unknown, during shutdown (2) would hang in conjunction with libvirtd for 120 secs. However (2) should not be executed at all in the first place.
Make sure we just close middleware libvirt connection when we are terminating middleware and when system is being shtudown, there is no need to actually reload http …
=> NAS-130472 / 24.10 / No need to reload http service when shutting down middleware

src/middlewared/middlewared/plugins/smb_/passdb.py
This uses new hard-coded passdb path in samba's cache dir. It removes some ability for users to override our compiled-in path options via auxiliary parameters, but such a configuration is unsupported.
=> NAS-130486 / 13.3 / Fix another case where incorrect passdb path used

src/middlewared/middlewared/plugins/filesystem_/acl.py, src/middlewared/middlewared/plugins/pool_/dataset.py
Per feedback from UI team, invert the value of skip_execute_check and rename to validate_effective_acl to give a better hint as to what it is for and dissuade users from the option.
=> NAS-130475 / 24.10 / Change field name for bypassing ACL validation

src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/kerberos.py, src/middlewared/middlewared/plugins/ldap.py
Generate audit trail for kerberos, AD, and LDAP changes.
=> NAS-130462 / 24.10 / Add auditing for directory services changes

src/middlewared/middlewared/plugins/failover.py
This commit generates audit-trail for some HA-related configuration changes.
=> NAS-130480 / 24.10 / Add failover plugin auditing

src/middlewared/middlewared/async_validators.py
As of Python 3.11, `asyncio.wait_for` raises the built-in `TimeoutError` ([doc page](https://docs.python.org/3.11/library/asyncio-task.html#asyncio.wait_for:~:text=Changed%20in%20version%203.11%3A%20Raises%20TimeoutError%20instead%20of%20asyncio.TimeoutError.)).
`asyncio.TimeoutError` is an alias of `TimeoutError` for backwards compatibility. However, `asyncio.futures.TimeoutError` is not defined and will cause an error.
=> NAS-130492 / 24.10 / fix-except

src/middlewared/middlewared/plugins/catalog/apps_details.py
This PR adds changes to not pass on unused ports to apps validation, this does not mean that ports will not be validated - but just that the end result would be users not being presented with a select field to select which port they want and instead having to type it in manually.
=> NAS-130493 / 24.10 / No need to provide unused ports to questions context

src/middlewared/middlewared/plugins/audit/backend.py, tests/api2/test_audit_basic.py
Order_by directives were not being applied to the generated SQL queryset that was being passed to the individual audit backend services. This wasn't caught because often filtering for generic audit queries happens via filter_list because the filters cannot be fully duplicated using native SQL features.
=> NAS-130490 / 24.10 / Fix order_by when using raw sql queries on audit backend

tests/api2/test_300_nfs.py
Add a commented out IPv6 NFS client test.
A call to `nfs.get_nfs4_clients` would generate an exception and fail if a client mounted using an IPv6 address.  This is fixed with a kernel change: https://github.com/truenas/linux/pull/188. 
However, the current CI environment does not fully support IPv6.  The test can be uncommented when IPv6 is available.
=> NAS-130437 / 24.10 / Test NFSv4 client info with IPv6 addresses

src/middlewared/middlewared/plugins/audit/audit.py, src/middlewared/middlewared/plugins/audit/utils.py
This is an optimization to improve memory consumption by default queries used by the webui. Initially we included SMB audit results by default with the expectation that user would specify the exact audited service they wanted to query. Since SMB audit logs can span upwards to hundreds of thousands of entries in some extreme cases we need to ensure that UI / API consumers use optimized SQL queryfilters with appropriate pagination.
=> NAS-130498 / 24.10 / Omit SMB audit results from audit.query output by default

src/middlewared/middlewared/plugins/snapshot.py
Adding an audit callback function with dataset name introduced a new failure condition for case where snapshot task matching the id does not exist.
=> NAS-130508 / 24.10 / Fix test regression in snapshot task deletion

src/middlewared/middlewared/plugins/apps/crud.py, src/middlewared/middlewared/plugins/apps/custom_app.py, src/middlewared/middlewared/plugins/apps/custom_app_utils.py, src/middlewared/middlewared/plugins/apps/ix_apps/lifecycle.py, src/middlewared/middlewared/plugins/apps/ix_apps/metadata.py, src/middlewared/middlewared/plugins/apps/ix_apps/path.py, src/middlewared/middlewared/plugins/apps/ix_apps/portals.py, src/middlewared/middlewared/plugins/apps/ix_apps/query.py, src/middlewared/middlewared/plugins/apps/ix_apps/setup.py, src/middlewared/middlewared/plugins/catalog/apps.py
This PR adds support for a custom app which essentially will be a custom provided docker compose file from the user.
=> NAS-130495 / 24.10 / Add support for deploying custom apps

src/middlewared/middlewared/plugins/apps/crud.py, src/middlewared/middlewared/plugins/apps/custom_app.py, src/middlewared/middlewared/plugins/apps/events.py, src/middlewared/middlewared/plugins/apps/ix_apps/query.py, src/middlewared/middlewared/plugins/apps/ix_apps/utils.py, src/middlewared/middlewared/plugins/apps/rollback.py, src/middlewared/middlewared/plugins/apps/upgrade.py, src/middlewared/middlewared/plugins/apps_images/images.py, src/middlewared/middlewared/plugins/docker/events.py, src/middlewared/middlewared/plugins/service_/services/docker.py
This PR adds changes to listen for docker events and based off those trigger app events so UI can get app status when the actual app's status changes and there is no need to poll for it.
=> NAS-130513 / 24.10 / Add app events

src/middlewared/middlewared/alembic/versions/24.10/2024-08-09_14-35_image_update.py, src/middlewared/middlewared/plugins/docker/state_management.py, src/middlewared/middlewared/plugins/docker/update.py, src/middlewared/middlewared/plugins/service_/services/docker.py
Checking image updates earlier used to be configurable as it could potentially result in users exhausting their rate limits for docker in conjunction with pulling images etc. Changes have been added to account for this so we allow user to toggle it as required and also progress reporting has been added when configuring docker service.
=> NAS-130517 / 24.10 / Make checking image updates configurable again

src/middlewared/middlewared/auth.py, src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/auth.py, src/middlewared/middlewared/pytest/unit/utils/test_audit.py, src/middlewared/middlewared/utils/audit.py
Populate `username` and `address` fields in middleware audit entries based on information from the middleware session.
The UI prominently displays the `username` field which is currently hard-coded to root. This commit adds a helper function to generate a username string based on the current authenticated credentials for the session generating the audit entry.
=> NAS-130485 / 24.10 / Improve auditing for middleware methods

tests/api2/test_300_nfs.py
Replace usage of pool.dataset.permission with filesystem.setperm.
=> NAS-130538 / 24.10 / Fix broken NFS test

src/middlewared/middlewared/plugins/apps_images/images.py
Changes were introduced recently to fix readonly role viewing apps but the same problem existed in `app.image` namespace as well and have been fixed here.
=> NAS-130537 / 24.10 / Fix readonly usage with app image

src/middlewared/middlewared/plugins/apps/ix_apps/docker/query.py
When re-deploying an app which had some failing containers i ran into this issue
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/ix_apps/docker/query.py", line 10, in list_resources_by_project
containers = client.containers.list(all=True, filters=label_filter, sparse=False)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/docker/models/containers.py", line 1018, in list
containers.append(self.get(r['Id']))
File "/usr/lib/python3/dist-packages/docker/models/containers.py", line 954, in get
resp = self.client.api.inspect_container(container_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
return f(self, …
```
=> NAS-130556 / 24.10 / Fix edge case when listing docker resources

src/middlewared/middlewared/plugins/apps/ix_apps/query.py
Currently, the Docker client is returning ports as strings, which is incompatible with our current port infrastructure. This is breaking the app's port validation.
Convert the ports used by the app to integers to ensure compatibility with the rest of the port infrastructure.
=> NAS-130558 / 24.10 / Fix ports type reported by docker

src/middlewared/middlewared/alert/source/auth.py, src/middlewared/middlewared/plugins/auth.py, src/middlewared/middlewared/utils/privilege.py
Since it's trivial for users to create dedicated service accounts for administrative purposes via RBAC we should add an alert per GPOS STIG.
=> NAS-127040 / 25.04 / Add alert for local admin account use

src/middlewared/middlewared/alert/source/auth.py, src/middlewared/middlewared/plugins/auth.py, src/middlewared/middlewared/utils/privilege.py
Since it's trivial for users to create dedicated service accounts for administrative purposes via RBAC we should add an alert per GPOS STIG.
Original PR: https://github.com/truenas/middleware/pull/14197
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127040
=> NAS-127040 / 24.10-RC.1 / Add alert for local admin account use (by anodos325)

src/middlewared/middlewared/plugins/smb_/util_net_conf.py
Add missing import of `MatchNotFound`
Also remove some unused imports.
Original PR: https://github.com/truenas/middleware/pull/14204
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130575
=> NAS-130575 / 24.10-RC.1 / Add missing import of MatchNotFound (by bmeagherix)

src/middlewared/middlewared/plugins/ldap.py
libldap (which we use for validation of LDAP DNs) apparently does not treat these extra spaces as invalid. We should strip whitespace on DN components before stripping the dn key from the LDAP base DN when trying to determine our kerberos realm name.
=> NAS-130574 / 25.04 / handle unexpected whitespace between LDAP DN components

src/middlewared/middlewared/plugins/ldap.py
libldap (which we use for validation of LDAP DNs) apparently does not treat these extra spaces as invalid. We should strip whitespace on DN components before stripping the dn key from the LDAP base DN when trying to determine our kerberos realm name.
Original PR: https://github.com/truenas/middleware/pull/14201
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130574
=> NAS-130574 / 24.10-BETA.1 / handle unexpected whitespace between LDAP DN components (by anodos325)

src/middlewared/middlewared/plugins/ldap.py
libldap (which we use for validation of LDAP DNs) apparently does not treat these extra spaces as invalid. We should strip whitespace on DN components before stripping the dn key from the LDAP base DN when trying to determine our kerberos realm name.
Original PR: https://github.com/truenas/middleware/pull/14201
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130574
=> NAS-130574 / 24.10-RC.1 / handle unexpected whitespace between LDAP DN components (by anodos325)

src/middlewared/middlewared/plugins/directoryservices_/ipa_join_mixin.py, src/middlewared/middlewared/plugins/directoryservices_/secrets.py, src/middlewared/middlewared/plugins/ldap.py
We need to initialize the value of machine account secret in secrets.tdb prior to actually setting the password via the net command.
Subprocessing is required because unlike other stored secrets, this is a packaged struct and so the simplest solution to writing it is to use existing tools (which is same behavior as FreeIPA samba setup script).
=> NAS-130562 / 25.04 / Fix setting machine account FreeIPA domain

src/middlewared/middlewared/plugins/directoryservices_/ipa_join_mixin.py, src/middlewared/middlewared/plugins/directoryservices_/secrets.py, src/middlewared/middlewared/plugins/ldap.py
We need to initialize the value of machine account secret in secrets.tdb prior to actually setting the password via the net command.
Subprocessing is required because unlike other stored secrets, this is a packaged struct and so the simplest solution to writing it is to use existing tools (which is same behavior as FreeIPA samba setup script).
Original PR: https://github.com/truenas/middleware/pull/14191
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130562
=> NAS-130562 / 24.10-BETA.1 / Fix setting machine account FreeIPA domain (by anodos325)

src/middlewared/middlewared/plugins/directoryservices_/ipa_join_mixin.py, src/middlewared/middlewared/plugins/directoryservices_/secrets.py, src/middlewared/middlewared/plugins/ldap.py
We need to initialize the value of machine account secret in secrets.tdb prior to actually setting the password via the net command.
Subprocessing is required because unlike other stored secrets, this is a packaged struct and so the simplest solution to writing it is to use existing tools (which is same behavior as FreeIPA samba setup script).
Original PR: https://github.com/truenas/middleware/pull/14191
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130562
=> NAS-130562 / 24.10-RC.1 / Fix setting machine account FreeIPA domain (by anodos325)

src/middlewared/middlewared/alembic/versions/24.10/2024-08-12_15-53_discoveryauth.py, src/middlewared/middlewared/alert/source/discovery_auth.py, src/middlewared/middlewared/plugins/iscsi_/auth.py, src/middlewared/middlewared/plugins/iscsi_/discovery_auth.py, src/middlewared/middlewared/plugins/iscsi_/portal.py, tests/api2/test_261_iscsi_cmd.py
In CORE _discovery authentication_ was tied to portals.  This is not the case for SCALE, where it is system-wide.
This PR covers the first step in modifying SCALE to reflect reality.  We will continue to re-use the Authorized Access groups which are also used in _target auth_.  Multiple groups can be specified for discovery auth & will be combined, with one caveat ... only a single `peeruser/peersecret` can be in use (for Mutual CHAP).  (Actually, this caveat is not new.)
Alerts will be generated both on migration and subsequently if multiple mutual CHAP peers are defined.  The `keyvalue` plugin used to communicate the various alerts generated on DB migration (as `middlewared` is not running at that point).
- Perform database migration
- Generate alerts from migration if appropriate
- Add …
=> NAS-130390 / 24.10 / Move discovery auth from per-portal to system-wide

src/middlewared/middlewared/alembic/versions/24.10/2024-08-12_15-53_discoveryauth.py, src/middlewared/middlewared/alert/source/discovery_auth.py, src/middlewared/middlewared/plugins/iscsi_/auth.py, src/middlewared/middlewared/plugins/iscsi_/discovery_auth.py, src/middlewared/middlewared/plugins/iscsi_/portal.py, tests/api2/test_261_iscsi_cmd.py
In CORE _discovery authentication_ was tied to portals.  This is not the case for SCALE, where it is system-wide.
This PR covers the first step in modifying SCALE to reflect reality.  We will continue to re-use the Authorized Access groups which are also used in _target auth_.  Multiple groups can be specified for discovery auth & will be combined, with one caveat ... only a single `peeruser/peersecret` can be in use (for Mutual CHAP).  (Actually, this caveat is not new.)
Alerts will be generated both on migration and subsequently if multiple mutual CHAP peers are defined.  The `keyvalue` plugin used to communicate the various alerts generated on DB migration (as `middlewared` is not running at that point).
- Perform database migration
- Generate alerts from migration if appropriate
- Add …
=> NAS-130390 / 25.04 / Move discovery auth from per-portal to system-wide (by bmeagherix)

debian/debian/rules
`ix-vendor` was never added to this list and was therefore not included in the build.
=> NAS-130595 / 25.04 / add `ix-vendor` to service list

debian/debian/rules
`ix-vendor` was never added to this list and was therefore not included in the build.
Original PR: https://github.com/truenas/middleware/pull/14217
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130595
=> NAS-130595 / 24.10-BETA.1 / add `ix-vendor` to service list (by creatorcary)

debian/debian/rules
`ix-vendor` was never added to this list and was therefore not included in the build.
Original PR: https://github.com/truenas/middleware/pull/14217
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130595
=> NAS-130595 / 24.10-RC.1 / add `ix-vendor` to service list (by creatorcary)

src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/auth.py, tests/api2/test_root_session_alert.py
Since we are toggling alerts potentially when performing logout the session logout method needs to be converted properly into an async coroutine like session longin, and we need to make callers to the function properly await it.
=> NAS-130598 / 25.04 / Fix handling of call to session logout

tests/api2/test_300_nfs.py, tests/protocols/nfs_proto.py
**Major refactoring of the NFS CI test module.**
- Converted the web socket calls
- Eliminated pytest 'depends'
- Expanded use of pytest fixtures
- Re-implemented the syslog filter test to remove instability
- Test suite runs faster which required additional reset of systemctl restart counter
=> NAS-130577 / 25.04 / Refactor NFS CI tests

src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/auth.py, tests/api2/test_root_session_alert.py
Since we are toggling alerts potentially when performing logout the session logout method needs to be converted properly into an async coroutine like session longin, and we need to make callers to the function properly await it.
Original PR: https://github.com/truenas/middleware/pull/14220
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130598
=> NAS-130598 / 24.10-RC.1 / Fix handling of call to session logout (by anodos325)

debian/debian/ix-netif.service, debian/debian/ix-vendor.service, src/middlewared/middlewared/plugins/system_vendor/vendor.py, src/middlewared/middlewared/scripts/vendor_service.py, src/middlewared/setup.py
A few issues fixed here:
1. ix-vendor.service created a cyclical dependency which was causing a cascading set of failures. Most notably, `system.ready` endpoint would get stuck returning `False` because `system.state` was stuck in `BOOTING`.
2. the `vendor_service.py` script wasn't getting installed, so after fixing the service file, it failed because it couldn't find the executable.
3. remove the use of `Client()` in `vendor_service.py` by adding a `get_vendor()` function to `system_vendor/vendor.py`. This simplifies the script and makes it more resilient.
4. Add a `-` to the `ExecStart` stanza in `ix-vendor.service`. This is required because we use some weird legacy entrypoints stuff to create executable files for these scripts defined in `middlewared/setup.py`. Because of this, the …
=> NAS-130624 / 25.04 / Fix system.ready and ix-vendor.service

debian/debian/ix-netif.service, debian/debian/ix-vendor.service, src/middlewared/middlewared/plugins/system_vendor/vendor.py, src/middlewared/middlewared/scripts/vendor_service.py, src/middlewared/setup.py
A few issues fixed here:
1. ix-vendor.service created a cyclical dependency which was causing a cascading set of failures. Most notably, `system.ready` endpoint would get stuck returning `False` because `system.state` was stuck in `BOOTING`.
2. the `vendor_service.py` script wasn't getting installed, so after fixing the service file, it failed because it couldn't find the executable.
3. remove the use of `Client()` in `vendor_service.py` by adding a `get_vendor()` function to `system_vendor/vendor.py`. This simplifies the script and makes it more resilient.
4. Add a `-` to the `ExecStart` stanza in `ix-vendor.service`. This is required because we use some weird legacy entrypoints stuff to create executable files for these scripts defined in `middlewared/setup.py`. Because of this, the …
=> NAS-130624 / 24.10-BETA.1 / Fix system.ready and ix-vendor.service (by yocalebo)

debian/debian/ix-netif.service, debian/debian/ix-vendor.service, src/middlewared/middlewared/plugins/system_vendor/vendor.py, src/middlewared/middlewared/scripts/vendor_service.py, src/middlewared/setup.py
A few issues fixed here:
1. ix-vendor.service created a cyclical dependency which was causing a cascading set of failures. Most notably, `system.ready` endpoint would get stuck returning `False` because `system.state` was stuck in `BOOTING`.
2. the `vendor_service.py` script wasn't getting installed, so after fixing the service file, it failed because it couldn't find the executable.
3. remove the use of `Client()` in `vendor_service.py` by adding a `get_vendor()` function to `system_vendor/vendor.py`. This simplifies the script and makes it more resilient.
4. Add a `-` to the `ExecStart` stanza in `ix-vendor.service`. This is required because we use some weird legacy entrypoints stuff to create executable files for these scripts defined in `middlewared/setup.py`. Because of this, the …
=> NAS-130624 / 24.10-RC.1 / Fix system.ready and ix-vendor.service (by yocalebo)

src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py, src/middlewared/middlewared/plugins/kubernetes_to_docker/trigger_migration.py, src/middlewared/middlewared/plugins/kubernetes_to_docker/utils.py
This PR adds changes to auto select the latest backup when migrating apps from k8s if none is explicitly specified.
=> NAS-130646 / 25.04 / Auto select latest backup to migrate apps from if none is specified

src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py, src/middlewared/middlewared/plugins/kubernetes_to_docker/trigger_migration.py, src/middlewared/middlewared/plugins/kubernetes_to_docker/utils.py
This PR adds changes to auto select the latest backup when migrating apps from k8s if none is explicitly specified.
Original PR: https://github.com/truenas/middleware/pull/14239
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130646
=> NAS-130646 / 24.10-BETA.1 / Auto select latest backup to migrate apps from if none is specified (by sonicaj)

src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py, src/middlewared/middlewared/plugins/kubernetes_to_docker/trigger_migration.py, src/middlewared/middlewared/plugins/kubernetes_to_docker/utils.py
This PR adds changes to auto select the latest backup when migrating apps from k8s if none is explicitly specified.
Original PR: https://github.com/truenas/middleware/pull/14239
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130646
=> NAS-130646 / 24.10-RC.1 / Auto select latest backup to migrate apps from if none is specified (by sonicaj)

src/middlewared/middlewared/api/base/server/ws_handler/rpc.py, src/middlewared/middlewared/main.py, src/middlewared/middlewared/pytest/unit/utils/test_limits.py, src/middlewared/middlewared/utils/limits.py, tests/api2/test_large_message.py
RFC5424 specifies that maximum size of SDATA for a syslog message as 64 KiB. Since these messages will in some circumstances be converted into audit entries and sent to remote syslog server we should set an upper bound on size of message we process (to prevent dropping audited messages). In principle there is no reason to ever be receiving giant messages.
=> NAS-130618 / 25.04 / Set maximum size of message we will parse

src/middlewared/middlewared/main.py, src/middlewared/middlewared/pytest/unit/utils/test_limits.py, src/middlewared/middlewared/utils/limits.py, tests/api2/test_large_message.py
RFC5424 specifies that maximum size of SDATA for a syslog message as 64 KiB. Since these messages will in some circumstances be converted into audit entries and sent to remote syslog server we should set an upper bound on size of message we process (to prevent dropping audited messages). In principle there is no reason to ever be receiving giant messages.
Original PR: https://github.com/truenas/middleware/pull/14225
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130618
=> NAS-130618 / 24.10-RC.1 / Set maximum size of message we will parse (by anodos325)

src/middlewared/middlewared/migration/0011_catalog_community_train.py, src/middlewared/middlewared/plugins/catalog/utils.py
This commit adds changes to add community train to preferred trains by default. Also it makes sure that enterprise users have correct trains setup.
Original PR: https://github.com/truenas/middleware/pull/14251
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130670
=> NAS-130670 / 24.10-BETA.1 / Add community train to preferred trains by default (by sonicaj)

src/middlewared/middlewared/migration/0011_catalog_community_train.py, src/middlewared/middlewared/plugins/catalog/utils.py
This commit adds changes to add community train to preferred trains by default. Also it makes sure that enterprise users have correct trains setup.
Original PR: https://github.com/truenas/middleware/pull/14251
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130670
=> NAS-130670 / 24.10-RC.1 / Add community train to preferred trains by default (by sonicaj)

src/middlewared/middlewared/plugins/apps/schema_action_context.py, src/middlewared/middlewared/plugins/apps/utils.py, src/middlewared/middlewared/plugins/docker/state_setup.py, src/middlewared/middlewared/plugins/docker/state_utils.py, src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py
1. add more default zfs properties to the internal apps dataset
2. convert the global mutable dictionary to an immutable dataclass to prevent the possibility of scrambling this object during runtime (the dataclass is also frozen so it's more memory efficient)
3. create a single thread to execute the disk I/O operations instead of a thread per move operation
4. lessen the amount of processes used in the process pool
Original PR: https://github.com/truenas/middleware/pull/14247
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130638
=> NAS-130638 / 24.10-BETA.1 / add more default zfs props for apps internal dataset (by yocalebo)

src/middlewared/middlewared/plugins/apps/schema_action_context.py, src/middlewared/middlewared/plugins/apps/utils.py, src/middlewared/middlewared/plugins/docker/state_setup.py, src/middlewared/middlewared/plugins/docker/state_utils.py, src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py
1. add more default zfs properties to the internal apps dataset
2. convert the global mutable dictionary to an immutable dataclass to prevent the possibility of scrambling this object during runtime (the dataclass is also frozen so it's more memory efficient)
3. create a single thread to execute the disk I/O operations instead of a thread per move operation
4. lessen the amount of processes used in the process pool
Original PR: https://github.com/truenas/middleware/pull/14247
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130638
=> NAS-130638 / 24.10-RC.1 / add more default zfs props for apps internal dataset (by yocalebo)

src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnaudit.conf.mako, src/middlewared/middlewared/test/integration/utils/audit.py, tests/api2/test_audit_basic.py, tests/api2/test_audit_sudo.py
The audit message_timestamp is supposed to be UTC.  This is not happing for sudo messages.  The message_timestamp for sudo is being output in local time.
This PR fixes that by changing the common setting to `C_UNIXTIME` and adding `fix-time-stamp("UTC") on the sudo rewrite.
This PR also adds a helper function to get audit entries and CI tests for MIDDLEWARE, SMB and SUDO timestamps.
=> NAS-130373 / 25.04 / Convert audit message_timestamp for sudo to UTC

src/middlewared/middlewared/plugins/pool_/dataset.py
Fix 1 issue:
- properly hide the `ix-apps` dataset (this is an internal dataset) from public facing API
Improve 1 other:
- no reason to call boot.pool_name each time someone calls `pool.dataset.query`. This information is static so we can use the BOOT_POOL_NAME_VALID array to accomplish the same task and save us a `self.middleware.call` call.
=> NAS-130695 / 25.04 / properly hide internal docker dataset

src/middlewared/middlewared/plugins/pool_/dataset.py
Fix 1 issue:
- properly hide the `ix-apps` dataset (this is an internal dataset) from public facing API
Improve 1 other:
- no reason to call boot.pool_name each time someone calls `pool.dataset.query`. This information is static so we can use the BOOT_POOL_NAME_VALID array to accomplish the same task and save us a `self.middleware.call` call.
Original PR: https://github.com/truenas/middleware/pull/14266
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130695
=> NAS-130695 / 24.10-BETA.1 / properly hide internal docker dataset (by yocalebo)

src/middlewared/middlewared/plugins/pool_/dataset.py
Fix 1 issue:
- properly hide the `ix-apps` dataset (this is an internal dataset) from public facing API
Improve 1 other:
- no reason to call boot.pool_name each time someone calls `pool.dataset.query`. This information is static so we can use the BOOT_POOL_NAME_VALID array to accomplish the same task and save us a `self.middleware.call` call.
Original PR: https://github.com/truenas/middleware/pull/14266
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130695
=> NAS-130695 / 24.10-RC.1 / properly hide internal docker dataset (by yocalebo)

src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnaudit.conf.mako, tests/api2/test_audit_sudo.py
The 'reject' path is missing the UTC timestamp fix.   Add fix-time-zone("UTC") to sudo 'reject' processing path.
See [NAS-130373](https://github.com/truenas/middleware/pull/14261) for additional information.
=> NAS-130706 / 25.04 / Add timestamp fix to sudo reject path

src/middlewared/middlewared/plugins/network.py, src/middlewared/middlewared/utils/network_/procfs.py, tests/api2/test_websocket_interface.py, tests/api2/test_websocket_local_ip.py
Testing an unrelated problem, I found that `app.query` was broken...which is a pretty significant issue. While that was broken, it brought me to the `interface.websocket_local_ip` endpoint. I discovered that we're calling fork+exec'ing in the main event loop to call `lsof` just to determine the IP address associated with the remote_port of the current websocket session. We can very easily gather this from procfs. While I was there I also improved `interface.websocket_interface`.
- fix interface.websocket_local_ip to not fork+exec
- add test for interface.websocket_local_ip
- add test for interface.websocket_interface
=> NAS-130707 / 25.04 / Improve interface.websocket_local_ip and add tests

src/middlewared/middlewared/plugins/network.py, src/middlewared/middlewared/utils/network_/procfs.py, tests/api2/test_websocket_interface.py, tests/api2/test_websocket_local_ip.py
Testing an unrelated problem, I found that `app.query` was broken...which is a pretty significant issue. While that was broken, it brought me to the `interface.websocket_local_ip` endpoint. I discovered that we're calling fork+exec'ing in the main event loop to call `lsof` just to determine the IP address associated with the remote_port of the current websocket session. We can very easily gather this from procfs. While I was there I also improved `interface.websocket_interface`.
- fix interface.websocket_local_ip to not fork+exec
- add test for interface.websocket_local_ip
- add test for interface.websocket_interface
Original PR: https://github.com/truenas/middleware/pull/14276
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130707
=> NAS-130707 / 24.10-RC.1 / Improve interface.websocket_local_ip and add tests (by yocalebo)

src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnaudit.conf.mako, src/middlewared/middlewared/test/integration/utils/audit.py, tests/api2/test_audit_basic.py, tests/api2/test_audit_sudo.py
The audit message_timestamp is supposed to be UTC.  This is not happing for sudo messages.  The message_timestamp for sudo is being output in local time.
This PR fixes that by changing the common setting to `C_UNIXTIME` and adding `fix-time-stamp("UTC") on the sudo rewrite.
This PR also adds a helper function to get audit entries and CI tests for MIDDLEWARE, SMB and SUDO timestamps.
Original PR: https://github.com/truenas/middleware/pull/14261
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130373
=> NAS-130373 / 24.10-RC.1 / Convert audit message_timestamp for sudo to UTC (by mgrimesix)

src/middlewared/middlewared/plugins/pool_/scrub.py
We noticed that our TrueNAS server never started scrubbing the disks even though we configured a task for this.
Some investigation showed that this was failing due to a recent optimization in 738fd2ad10eccb83fd080536c057b55996eba298. Namely, the following:
```diff
- run('zpool', 'history', name, encoding='utf-8')
+ run('sh', '-c', f'zpool history {shlex.quote(name)} | grep -E "zpool (scrub|create)"')
```
In case `zpool history` does not contain neither `zpool scrub` nor `zpool create` the command has exit status 1 which leads to an exception. I believe this is the case in our setup due to having imported the pool instead of creating it.
```
Traceback:
File "/usr/lib/python3/dist-packages/middlewared/plugins/pool_/scrub.py", line 283, in __run
last_scrubs = (await run(
^^^^^^^^^^
File …
```
=> NAS-130662 / 25.04 / Fix failing first-time scrub

src/middlewared/middlewared/plugins/pool_/scrub.py
We noticed that our TrueNAS server never started scrubbing the disks even though we configured a task for this.
Some investigation showed that this was failing due to a recent optimization in 738fd2ad10eccb83fd080536c057b55996eba298. Namely, the following:
```diff
- run('zpool', 'history', name, encoding='utf-8')
+ run('sh', '-c', f'zpool history {shlex.quote(name)} | grep -E "zpool (scrub|create)"')
```
In case `zpool history` does not contain neither `zpool scrub` nor `zpool create` the command has exit status 1 which leads to an exception. I believe this is the case in our setup due to having imported the pool instead of creating it.
```
Traceback:
File "/usr/lib/python3/dist-packages/middlewared/plugins/pool_/scrub.py", line 283, in __run
last_scrubs = (await run(
^^^^^^^^^^
File …
```
=> NAS-130662 / 24.10-RC.1 / Fix failing first-time scrub (by georgschoelly)

src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/network.py
As has been documented in past, these platforms auto-add a USB based NIC device when someone connects to the IPMI console. We accounted for this in `interface.query` however, we didn't account for this in `interface.get_nic_names`. Stepping back, however, we added `get_nic_names` because of the fact that `interface.query` was abnormally expensive on HA systems. In a completely unrelated situation, I found that we were fork+exec'ing for each interface _ONLY_ on HA systems. I fixed that problem here: https://github.com/truenas/middleware/pull/14177
Because of those changes, interface.query is significantly faster on HA. This means we can get rid of `interface.get_nic_names` and use the `interface.query` endpoint.
=> NAS-130625 / 25.04 / fix failover.mismatch_nics for h/f series appliances

src/middlewared/middlewared/plugins/failover.py, src/middlewared/middlewared/plugins/network.py
git cherry-pick -x 8c99be0c1c40535c77d4e39c6878ff322a112ba5
git cherry-pick -x aba25629d8c2c46416ad56b62e3e6f503fe19487
As has been documented in past, these platforms auto-add a USB based NIC device when someone connects to the IPMI console. We accounted for this in `interface.query` however, we didn't account for this in `interface.get_nic_names`. Stepping back, however, we added `get_nic_names` because of the fact that `interface.query` was abnormally expensive on HA systems. In a completely unrelated situation, I found that we were fork+exec'ing for each interface _ONLY_ on HA systems. I fixed that problem …
=> NAS-130625 / 24.10-BETA.1 / fix failover.mismatch_nics for h/f series appliances (by yocalebo) (by bugclerk)

src/middlewared/middlewared/plugins/apps/schema_utils.py
When the `update` parameter is set to true, the Dict object is not updating values according to the schema, which is causing issues during app updates.
Set `update` to false when constructing the schema during schema validation to ensure the values are updated correctly.
=> NAS-130679 / 25.04 / Fix edits for apps

src/middlewared/middlewared/plugins/apps/schema_utils.py
When the `update` parameter is set to true, the Dict object is not updating values according to the schema, which is causing issues during app updates.
Set `update` to false when constructing the schema during schema validation to ensure the values are updated correctly.
Original PR: https://github.com/truenas/middleware/pull/14293
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130679
=> NAS-130679 / 24.10-BETA.1 / Fix edits for apps (by Qubad786)

src/middlewared/middlewared/plugins/apps/schema_utils.py
When the `update` parameter is set to true, the Dict object is not updating values according to the schema, which is causing issues during app updates.
Set `update` to false when constructing the schema during schema validation to ensure the values are updated correctly.
Original PR: https://github.com/truenas/middleware/pull/14293
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130679
=> NAS-130679 / 24.10-RC.1 / Fix edits for apps (by Qubad786)

src/middlewared/middlewared/plugins/zfs_/zfs_events.py
These errors, if corrected, do not degrade vdev and don't cause `sysevent.fs.zfs.config_sync`.
Not able to add an integration test since causing these errors with `zinject` irreversibly makes the system barely usable.
=> NAS-130708 / 25.04 / Clear pool status alert cache when I/O errors occur on the pool

src/middlewared/middlewared/plugins/zfs_/zfs_events.py
These errors, if corrected, do not degrade vdev and don't cause `sysevent.fs.zfs.config_sync`.
Not able to add an integration test since causing these errors with `zinject` irreversibly makes the system barely usable.
Original PR: https://github.com/truenas/middleware/pull/14297
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130708
=> NAS-130708 / 24.10-RC.1 / Clear pool status alert cache when I/O errors occur on the pool (by themylogin)

src/middlewared/middlewared/rclone/remote/s3.py
Add Glacier Instant Retrieval storage class for AWS S3 Cloud Sync.
`GLACIER_IR` was added to Rclone in v1.58.0: https://rclone.org/changelog/#v1-58-0-2022-03-18
=> NAS-130744 / 25.04 / Add Glacier Instant Retrieval storage class to AWS S3 Cloud Sync Task configuration

src/middlewared/middlewared/plugins/enclosure_/constants.py, src/middlewared/middlewared/plugins/enclosure_/enclosure2.py, src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py, src/middlewared/middlewared/plugins/enclosure_/fseries_drive_identify.py, src/middlewared/middlewared/plugins/enclosure_/jbof/es24n.py, src/middlewared/middlewared/plugins/enclosure_/jbof/utils.py, src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py, src/middlewared/middlewared/plugins/enclosure_/nvme2.py, src/middlewared/middlewared/plugins/enclosure_/r30_drive_identify.py, src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py, src/middlewared/middlewared/plugins/enclosure_/sysfs_disks.py
This PR adds initial support for `drive_bay_light_status` in `enclosure2.query` and `webui.enclosure.dashboard` APIs.
Support is added for JBOF and SES based enclosures.  Generally, being able to read light status follows whether it is possible to
set it (as indicated by `supports_identify_light` in slot mappings).  However, this can be overridden by adding a specific
`supports_identify_light_status` key/value to slot mappings - e.g. for platforms where it is possible to set the light status, but **not** to read it back again.
Other changes:
- As requested, change the `enclosure2.set_slot_status` API `status` parameter.  It will now accept the strings **"ON"**, **"OFF"** or **"CLEAR"**.
- For SES based enclosures the `original slot` value was incorrect, resulting in an off-by-one wrt …
=> NAS-130011 / 25.04 / Add drive bay light status

src/middlewared/middlewared/plugins/enclosure_/constants.py, src/middlewared/middlewared/plugins/enclosure_/enclosure2.py, src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py, src/middlewared/middlewared/plugins/enclosure_/fseries_drive_identify.py, src/middlewared/middlewared/plugins/enclosure_/jbof/es24n.py, src/middlewared/middlewared/plugins/enclosure_/jbof/utils.py, src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py, src/middlewared/middlewared/plugins/enclosure_/nvme2.py, src/middlewared/middlewared/plugins/enclosure_/r30_drive_identify.py, src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py, src/middlewared/middlewared/plugins/enclosure_/sysfs_disks.py
This PR adds initial support for `drive_bay_light_status` in `enclosure2.query` and `webui.enclosure.dashboard` APIs.
Support is added for JBOF and SES based enclosures.  Generally, being able to read light status follows whether it is possible to
set it (as indicated by `supports_identify_light` in slot mappings).  However, this can be overridden by adding a specific
`supports_identify_light_status` key/value to slot mappings - e.g. for platforms where it is possible to set the light status, but **not** to read it back again.
Other changes:
- As requested, change the `enclosure2.set_slot_status` API `status` parameter.  It will now accept the strings **"ON"**, **"OFF"** or **"CLEAR"**.
- For SES based enclosures the `original slot` value was incorrect, resulting in an off-by-one wrt …
=> NAS-130011 / 24.10-RC.1 / Add drive bay light status (by bmeagherix)

src/freenas/etc/csh.login.template
The .warning file is in root's home directory and thus cannot be read by non-root users on login.
This solution puts it in the earlier block that checks for user root.
Another solution would be to move the warning file out of root's home directory.
Re-submitting to correct branch.
=> NAS-130748 / 13.3 / Prevent permission denied error for non-root csh/tcsh over ssh

src/middlewared/middlewared/plugins/apps/schema_action_context.py, src/middlewared/middlewared/plugins/docker/state_setup.py, src/middlewared/middlewared/plugins/docker/state_utils.py
This commit adds changes to properly retrieve create time props when making apps related datasets. Basically what happens is that on create time we are not considering update time props, they should be configured when we create the dataset and not on a subsequent call which will trigger state management to run again.
Essentially which are update only props are also create time props and should be applied when we actually create the dataset.
=> NAS-130749 / 25.04 / Properly retrieve create time props when making apps related datasets

src/middlewared/middlewared/plugins/apps/schema_action_context.py, src/middlewared/middlewared/plugins/docker/state_setup.py, src/middlewared/middlewared/plugins/docker/state_utils.py
This commit adds changes to properly retrieve create time props when making apps related datasets. Basically what happens is that on create time we are not considering update time props, they should be configured when we create the dataset and not on a subsequent call which will trigger state management to run again.
Essentially which are update only props are also create time props and should be applied when we actually create the dataset.
Original PR: https://github.com/truenas/middleware/pull/14303
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130749
=> NAS-130749 / 24.10-BETA.1 / Properly retrieve create time props when making apps related datasets (by sonicaj)

src/middlewared/middlewared/plugins/apps/schema_action_context.py, src/middlewared/middlewared/plugins/docker/state_setup.py, src/middlewared/middlewared/plugins/docker/state_utils.py
This commit adds changes to properly retrieve create time props when making apps related datasets. Basically what happens is that on create time we are not considering update time props, they should be configured when we create the dataset and not on a subsequent call which will trigger state management to run again.
Essentially which are update only props are also create time props and should be applied when we actually create the dataset.
Original PR: https://github.com/truenas/middleware/pull/14303
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130749
=> NAS-130749 / 24.10-RC.1 / Properly retrieve create time props when making apps related datasets (by sonicaj)

src/middlewared/middlewared/plugins/network.py
Recent addition of `test_websocket_interface` (in PR #14276) was failing frequently.
Apparently the VIP was not being handled well for HA systems.
Add search of `iface['state']['aliases']` if search of `iface['aliases']` does not yield a result.
=> NAS-130755 / 25.04 / Extend search for ip in websocket_interface

src/middlewared/middlewared/plugins/network.py
Recent addition of `test_websocket_interface` (in PR #14276) was failing frequently.
Apparently the VIP was not being handled well for HA systems.
Add search of `iface['state']['aliases']` if search of `iface['aliases']` does not yield a result.
Original PR: https://github.com/truenas/middleware/pull/14313
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130755
=> NAS-130755 / 24.10-RC.1 / Extend search for ip in websocket_interface (by bmeagherix)

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/constants.py, src/middlewared/middlewared/plugins/smb_/passdb.py, src/middlewared/middlewared/plugins/smb_/util_passdb.py, src/middlewared/middlewared/pytest/unit/utils/test_passdb.py, src/middlewared/middlewared/utils/tdb.py, tests/api2/test_011_user.py
This commit adds utility functions to pack / unpack samba's passdb.tdb file. This allows us to remove subprocess calls to manipulate our SMB entries and provides a clean mechanism for maintaining more robust account details in the future when we expand our user database objects. In ad-hoc testing this resulted in about a 2x speed improvement for user account CRUD operations.
=> NAS-130768 / 25.04 / Improve passdb handling

src/middlewared/middlewared/plugins/pool_/import_pool.py
This commit fixes an issue where if we have an unencrypted root dataset which has encrypted children, the root dataset will potentially be not mounted because of the changes introduced in https://github.com/truenas/middleware/pull/13553 as by default when we import a pool we don't mount any datasets.
=> NAS-130781 / 25.04 / Make sure we mount datasets which have encrypted children

src/middlewared/middlewared/plugins/pool_/import_pool.py
This commit fixes an issue where if we have an unencrypted root dataset which has encrypted children, the root dataset will potentially be not mounted because of the changes introduced in https://github.com/truenas/middleware/pull/13553 as by default when we import a pool we don't mount any datasets.
Original PR: https://github.com/truenas/middleware/pull/14325
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130781
=> NAS-130781 / 24.10-RC.1 / Make sure we mount datasets which have encrypted children (by sonicaj)

src/middlewared/middlewared/plugins/pool_/import_pool.py
This commit fixes an issue where if we have an unencrypted root dataset which has encrypted children, the root dataset will potentially be not mounted because of the changes introduced in https://github.com/truenas/middleware/pull/13553 as by default when we import a pool we don't mount any datasets.
Original PR: https://github.com/truenas/middleware/pull/14325
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130781
=> NAS-130781 / 24.10-BETA.1 / Make sure we mount datasets which have encrypted children (by sonicaj)

src/middlewared/middlewared/plugins/network.py
This is a subtle, but painful regression in EE. If we manage to get the remote port via the `X-Real-Remote-Port` header, it will be a string. We need to cast this to an `int` before passing it to `read_proc_net` or it won't work. Note, the logic for casting this to an int is the same as the `get_remote_addr_port` in `utils/nginx.py`.
NOTE: this does not affect master because we properly cast these to an int in the `TCPIPOrigin` class.
=> NAS-130785 / 24.10-RC.1 / fix interface.websocket_local_ip

src/middlewared/middlewared/alert/source/auth.py, src/middlewared/middlewared/plugins/auth.py, tests/api2/test_root_session_alert.py
In lieu of generating one-shot alerts when root-level account authenticates, generate a daily summary report of session IDs and addresses for clients that authenticated to the UI / API as a root account and limit such behavior to SCALE_ENTERPRISE.
Also add new daily alert for failed login attempts to the UI / API.
=> NAS-130676 / 25.04 /  Redesign root login alerts

src/middlewared/middlewared/alert/source/auth.py, src/middlewared/middlewared/plugins/auth.py, tests/api2/test_root_session_alert.py
In lieu of generating one-shot alerts when root-level account authenticates, generate a daily summary report of session IDs and addresses for clients that authenticated to the UI / API as a root account and limit such behavior to SCALE_ENTERPRISE.
Also add new daily alert for failed login attempts to the UI / API.
Original PR: https://github.com/truenas/middleware/pull/14324
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130676
=> NAS-130676 / 24.10-RC.1 /  Redesign root login alerts (by anodos325)

src/middlewared/middlewared/plugins/zfs_/zfs_events.py
These errors, if corrected, do not degrade vdev and don't cause `sysevent.fs.zfs.config_sync`.
Not able to add an integration test since causing these errors with `zinject` irreversibly makes the system barely usable.
Original PR: https://github.com/truenas/middleware/pull/14297
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130708
Original PR: https://github.com/truenas/middleware/pull/14298
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130708
=> NAS-130708 / 24.10-BETA.1 / Clear pool status alert cache when I/O errors occur on the pool (by themylogin) (by bugclerk)

src/middlewared/middlewared/plugins/ftp_/status.py, src/middlewared/middlewared/plugins/usage.py, src/middlewared/middlewared/test/integration/assets/ftp.py, src/middlewared/middlewared/test/integration/assets/nfs.py, tests/api2/test_usage_reporting.py
Add NFS and FTP usage statistics
- NFS
-- Enabled protocols, krb5 enabled, number of clients
- FTP
-- Number of connections
Added a simple CI test for the usage reporting
Added `connection_count` as an NFS service function.
Added `nfs_server` test asset and made the `config` parameter optional in the `ftp_server` test asset.
Test results are [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/269/).
=> NAS-130197 / 25.04 / Add NFS and FTP statistics to usage reporting

src/middlewared/middlewared/plugins/apps/logs.py
Middleware should allow to retrieve logs of apps which are in deploying state.
Original PR: https://github.com/truenas/middleware/pull/14334
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130788
=> NAS-130788 / 24.10-BETA.1 / Allow retrieving logs of apps in deploying state (by Qubad786)

src/middlewared/middlewared/plugins/apps/logs.py
Middleware should allow to retrieve logs of apps which are in deploying state.
Original PR: https://github.com/truenas/middleware/pull/14334
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130788
=> NAS-130788 / 24.10-RC.1 / Allow retrieving logs of apps in deploying state (by Qubad786)

src/middlewared/middlewared/plugins/boot.py, src/middlewared/middlewared/plugins/iscsi_/extents.py
This PR was 100% inspired by PR #14180
Add private API `boot.is_boot_pool_path` and call to prevent an iSCSI extent from being based on a ZVOL on the boot-pool.
=> NAS-130796 / 25.04 / Do not allow iSCSI extents to use zvols on boot-pool

src/freenas/etc/systemd/system/docker.service.d/override.conf, src/middlewared/middlewared/etc_files/docker/daemon.json.py
Docker after starting changes the default policy of forward chain to `DROP` which results in networking for VMs getting broken, we switch it back to `ACCEPT` after docker has started to restore connectivity to VMs.
=> NAS-130769 / 25.04 / Default to accept policy for forward chain

src/freenas/etc/systemd/system/docker.service.d/override.conf, src/middlewared/middlewared/etc_files/docker/daemon.json.py
Docker after starting changes the default policy of forward chain to `DROP` which results in networking for VMs getting broken, we switch it back to `ACCEPT` after docker has started to restore connectivity to VMs.
Original PR: https://github.com/truenas/middleware/pull/14338
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130769
=> NAS-130769 / 24.10-BETA.1 / Default to accept policy for forward chain (by Qubad786)

src/freenas/etc/systemd/system/docker.service.d/override.conf, src/middlewared/middlewared/etc_files/docker/daemon.json.py
Docker after starting changes the default policy of forward chain to `DROP` which results in networking for VMs getting broken, we switch it back to `ACCEPT` after docker has started to restore connectivity to VMs.
Original PR: https://github.com/truenas/middleware/pull/14338
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130769
=> NAS-130769 / 24.10-RC.1 / Default to accept policy for forward chain (by Qubad786)

src/middlewared/middlewared/plugins/failover.py
The `remote_nics` variable is explicitly checked that it is not `NoneType` before converting the list of dicts to a set. The comprehension needs to be inside the `else:` branch to prevent ` TypeError` crash.
=> NAS-130809 / 25.04 / fix TypeError crash in failover.mismatch_nics

src/middlewared/middlewared/plugins/failover.py
The `remote_nics` variable is explicitly checked that it is not `NoneType` before converting the list of dicts to a set. The comprehension needs to be inside the `else:` branch to prevent ` TypeError` crash.
Original PR: https://github.com/truenas/middleware/pull/14342
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130809
=> NAS-130809 / 24.10-RC.1 / fix TypeError crash in failover.mismatch_nics (by yocalebo)

tests/api2/test_audit_sudo.py
The Electric Eel release does not have the new `utc_now` function.   Change the sudo audit test to use `utcnow`.
=> NAS-130815 / 24.10-RC.1 / Remove usage of utc_now

src/middlewared/middlewared/service/core_service.py
Our convention for auditing is to not generate entries for purely internal calls to methods. This fixes an issue whereby the new apps implementation was calling internally into audited methods and crashing.
=> NAS-130813 / 25.04 / Fix internal callers for core.bulk

src/middlewared/middlewared/service/core_service.py
Our convention for auditing is to not generate entries for purely internal calls to methods. This fixes an issue whereby the new apps implementation was calling internally into audited methods and crashing.
Original PR: https://github.com/truenas/middleware/pull/14344
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130813
=> NAS-130813 / 24.10-RC.1 / Fix internal callers for core.bulk (by anodos325)

src/middlewared/middlewared/service/core_service.py
Our convention for auditing is to not generate entries for purely internal calls to methods. This fixes an issue whereby the new apps implementation was calling internally into audited methods and crashing.
Original PR: https://github.com/truenas/middleware/pull/14344
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130813
=> NAS-130813 / 24.10-BETA.1 / Fix internal callers for core.bulk (by anodos325)

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
Performance team saw a strange crash in the new enclosure because they have 1x ES60 returning a product string that is unexpected. This crashed because `self.model` was set to an empty string so accessing the 0th index, failed. This adds another conditional to make sure we have `self.model` attribute populated before accessing the 0th index.
=> NAS-130824 / 25.04 / fix edge-case crash in enclosure_class.py

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
Performance team saw a strange crash in the new enclosure because they have 1x ES60 returning a product string that is unexpected. This crashed because `self.model` was set to an empty string so accessing the 0th index, failed. This adds another conditional to make sure we have `self.model` attribute populated before accessing the 0th index.
Original PR: https://github.com/truenas/middleware/pull/14352
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130824
=> NAS-130824 / 24.10-RC.1 / fix edge-case crash in enclosure_class.py (by yocalebo)

src/middlewared/middlewared/plugins/iscsi_/targets.py
Add a (long) default timeout to `iscsi.target.logout_iqn`.  This will avoid non-terminating calls to `iscsi.target.logout_ha_targets`.
CI test run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/313/).
=> NAS-130814 / 25.04 / Add timeout to iscsi.target.logout_iqn

src/middlewared/middlewared/plugins/apps/ix_apps/docker/stats.py, src/middlewared/middlewared/plugins/apps/stats.py, src/middlewared/middlewared/plugins/apps/stats_util.py
This PR adds an event source for retrieving app statistics from docker.
=> NAS-130471 / 25.04 / Add an event source for app statistics

src/middlewared/middlewared/plugins/apps/ix_apps/docker/stats.py, src/middlewared/middlewared/plugins/apps/stats.py, src/middlewared/middlewared/plugins/apps/stats_util.py
This PR adds an event source for retrieving app statistics from docker.
Original PR: https://github.com/truenas/middleware/pull/14359
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130471
=> NAS-130471 / 24.10-RC.1 / Add an event source for app statistics (by sonicaj)

src/middlewared/middlewared/plugins/account_/constants.py, src/middlewared/middlewared/plugins/auth_/authenticate.py
If our dedicated middleware pam service file is for some reason missing we should try to regenerate it and if that fails then authentication should fail. The reason for this is that in the absence of the specified file libpam will fall through to the default PAM configuration, which could lead to unexpected behavior.
=> NAS-130855 / 25.04 / Fail pam authentication if service file missing

src/middlewared/middlewared/plugins/ups.py
The parameters to `failover.call_remote` were missing `[]`.
=> NAS-130866 / 25.04 / UPS shutdown event handling was failing to shutdown STANDBY node

src/middlewared/middlewared/plugins/ups.py
The parameters to `failover.call_remote` were missing `[]`.
Original PR: https://github.com/truenas/middleware/pull/14371
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130866
=> NAS-130866 / 24.10-RC.1 / UPS shutdown event handling was failing to shutdown STANDBY node (by bmeagherix)

tests/api2/test_apps_images_roles.py, tests/api2/test_apps_roles.py, tests/api2/test_catalog_roles.py, tests/api2/test_docker_roles.py
This commit adds an integration tests to validate roles for apps plugin.
Original PR: https://github.com/truenas/middleware/pull/14380
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130882
=> NAS-130882 / 24.10-RC.1 / Add tests to verify roles for apps (by sonicaj)

src/middlewared/middlewared/etc_files/docker/daemon.json.py
This commit defines custom address pools to optimize Docker network creation capacity. The pools are set to 172.30.0.0/16 and 172.31.0.0/16 with a /27 subnet size, allowing for up to 4096 Docker networks, each with 32 IP addresses. This change significantly increases the number of available Docker networks, which is crucial for adding large number of apps which are meant to run simultaneously because by default behaviour the capacity would roughly be at 32 networks meaning roughly 32 apps.
Original PR: https://github.com/truenas/middleware/pull/14370
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130861
=> NAS-130861 / 24.10-RC.1 / Define custom address pool capacity for docker (by sonicaj)

src/middlewared/middlewared/etc_files/docker/daemon.json.py
This commit defines custom address pools to optimize Docker network creation capacity. The pools are set to 172.30.0.0/16 and 172.31.0.0/16 with a /27 subnet size, allowing for up to 4096 Docker networks, each with 32 IP addresses. This change significantly increases the number of available Docker networks, which is crucial for adding large number of apps which are meant to run simultaneously because by default behaviour the capacity would roughly be at 32 networks meaning roughly 32 apps.
=> NAS-130861 / 25.04 / Define custom address pool capacity for docker

src/middlewared/middlewared/plugins/reporting/rest.py, src/middlewared/middlewared/plugins/vm/connection.py, src/middlewared/middlewared/plugins/vm/vms.py
While diagnosing another problem with libvirt, i saw we were not able to calculate netdata disk space because `vm.query` was failing there as libvirt was misbehaving (that's still being investigated).
Make sure `vm.query` does not fail if libvirt is not running.
=> NAS-130883 / 25.04 / Make sure vm.query does not fail

src/middlewared/middlewared/plugins/reporting/rest.py, src/middlewared/middlewared/plugins/vm/connection.py, src/middlewared/middlewared/plugins/vm/vms.py
While diagnosing another problem with libvirt, i saw we were not able to calculate netdata disk space because `vm.query` was failing there as libvirt was misbehaving (that's still being investigated).
Make sure `vm.query` does not fail if libvirt is not running.
Original PR: https://github.com/truenas/middleware/pull/14382
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130883
=> NAS-130883 / 24.10-RC.1 / Make sure vm.query does not fail (by Qubad786)

src/middlewared/middlewared/plugins/pool_/dataset.py, tests/api2/test_nfsv4_top_level_dataset.py
When we were doing initial development of TrueNAS SCALE (pre-angelfish) a bug was encountered when importing pools from FreeBSD in which the acltype could be set to OFF. Eventually this bug was fixed on the ZFS side, but it was still early days of testing NFSv4 acltype on SCALE and so we didn't want early-adopter migrators to have broken shares. Thus we normalized creation of new datasets to be POSIX acltype if user had selected to inherit from top-level dataset.
After a few releases and user bug reports we realized we needed to have specific ZFS dataset properties set depending on acltype. For example that the aclmode should be DISCARD (discard internal ZFS acl) because changing acltype does not remove the internal ZFS ACL and it could still be evaluated in zfs_zaccess calls. This …
=> NAS-130877 / 25.04 / Remove acltype normalization for datasets

src/middlewared/middlewared/plugins/apps/crud.py, src/middlewared/middlewared/plugins/vm/vm_display_info.py
With the changes introduced here: https://github.com/truenas/middleware/pull/14372, we no longer need to pass the `app` object around and call `websocket_local_ip`.
=> NAS-130886 / 25.04 / stop calling websocket_local_ip

src/middlewared/middlewared/plugins/pool_/dataset.py, tests/api2/test_nfsv4_top_level_dataset.py
When we were doing initial development of TrueNAS SCALE (pre-angelfish) a bug was encountered when importing pools from FreeBSD in which the acltype could be set to OFF. Eventually this bug was fixed on the ZFS side, but it was still early days of testing NFSv4 acltype on SCALE and so we didn't want early-adopter migrators to have broken shares. Thus we normalized creation of new datasets to be POSIX acltype if user had selected to inherit from top-level dataset.
After a few releases and user bug reports we realized we needed to have specific ZFS dataset properties set depending on acltype. For example that the aclmode should be DISCARD (discard internal ZFS acl) because changing acltype does not remove the internal ZFS ACL and it could still be evaluated in zfs_zaccess calls. This …
=> NAS-130877 / 24.10-RC.1 / Remove acltype normalization for datasets (by anodos325)

src/middlewared/middlewared/service/decorators.py
Recent change was made in recent PR (#14319).  Update docs to match.
=> NAS-130888 / 25.04 / Update job decorator docstring to match recent code change

src/middlewared/middlewared/plugins/failover_/event.py
Extract some iSCSI ALUA cleanup code into `iscsi_cleanup_alua_state` and catch exceptions.  Further, use the operations that succeeded/failed to act as gatekeepers for later steps.
----
iSCSI tests passed during [CI run](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/330/).
Original PR: https://github.com/truenas/middleware/pull/14364
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130847
=> NAS-130847 / 24.10-RC.1 / Make vrrp_master more robust wrt iSCSI ALUA on newly booted node (by bmeagherix)

src/middlewared/middlewared/alembic/versions/24.10/2024-08-30_22-13_cpu_topology_extension.py, src/middlewared/middlewared/plugins/vm/supervisor/domain_xml.py, src/middlewared/middlewared/plugins/vm/vms.py, src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_libvirt_xml.py
**Problem:**  
Users with AMD CPUs who have SMT (Simultaneous Multithreading) enabled are currently unable to passthrough their CPUs with SMT cores to guest VMs. This is because, by default, SMT support is disabled in libvirtd and requires specific features to be enabled.
**Solution:**  
Add a new field in the VMs configuration that allows users to enable SMT passthrough for their CPUs. When this field is enabled, the relevant features will be added to the CPU XML configuration, ensuring that SMT-enabled CPUs can be properly passed through to the guest if host passthrough is also enabled.
=> NAS-130967 / 24.10-RC.1 / Provide cpu topology extensions to VM if requested

src/freenas/etc/systemd/network/10-persistent-net.link
At time of writing, ntb on SCALE has pathological behavior related TCP/IP Window size calculation whereby the receiving side clamps the window size to 0 causing recalculation which, ultimately, ends with behavior described in https://en.wikipedia.org/wiki/Silly_window_syndrome. The work-around is to drop MTU size a bit which fixes the scenario altogether. When we discover why this is happening, we should remove the MTUBytes line in this file.
Original PR: https://github.com/truenas/middleware/pull/14136
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130434
Original PR: https://github.com/truenas/middleware/pull/14137
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130434
=> NAS-130434 / 24.04.2.1 / drop ntb0 MTU to 64000 (by yocalebo) (by bugclerk)

src/middlewared/middlewared/alembic/versions/24.10/2024-08-30_22-13_cpu_topology_extension.py, src/middlewared/middlewared/alembic/versions/25.04/2024-09-02_16-54_merge.py, src/middlewared/middlewared/plugins/vm/supervisor/domain_xml.py, src/middlewared/middlewared/plugins/vm/vms.py, src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_libvirt_xml.py
**Problem:**  
Users with AMD CPUs who have SMT (Simultaneous Multithreading) enabled are currently unable to passthrough their CPUs with SMT cores to guest VMs. This is because, by default, SMT support is disabled in libvirtd and requires specific features to be enabled.
**Solution:**  
Add a new field in the VMs configuration that allows users to enable SMT passthrough for their CPUs. When this field is enabled, the relevant features will be added to the CPU XML configuration, ensuring that SMT-enabled CPUs can be properly passed through to the guest if host passthrough is also enabled.
Original PR: https://github.com/truenas/middleware/pull/14392
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130967
=> NAS-130967 / 25.04 / Provide cpu topology extensions to VM if requested (by Qubad786)

src/middlewared/middlewared/plugins/vm/vms.py
**Problem:**  
During the shutdown process, `vm.query` attempts to establish a connection with libvirtd, which is already stopped by that time. This results in an attempt to start libvirtd, which fails because systemd does not permit services to start during shutdown.
**Solution:**  
Modify `vm.query` to prevent it from trying to establish a connection with libvirtd during the system's shutdown process, avoiding the issue entirely.
=> NAS-130968 / 25.04 / Do not attempt to start libvirt on shutdown

src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
It's technically possible that a user creates a zpool with the top level dataset configured with NFSv4 acltype and then modifies it via shell-based utilities outside of our API. In this case we need to allow skipping ACL path validation that prevents using the top-level dataset of a pool while calculating what our inherited ACL should be for a newly-created dataset.
Original PR: https://github.com/truenas/middleware/pull/14133
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130413
Original PR: https://github.com/truenas/middleware/pull/14141
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130413
=> NAS-130413 / 24.04.2.1 / Fix get inherited ACL when top-level ds has ACL (by anodos325) (by bugclerk)

src/middlewared/middlewared/plugins/pool_/dataset.py, tests/api2/test_nfsv4_top_level_dataset.py
When we were doing initial development of TrueNAS SCALE (pre-angelfish) a bug was encountered when importing pools from FreeBSD in which the acltype could be set to OFF. Eventually this bug was fixed on the ZFS side, but it was still early days of testing NFSv4 acltype on SCALE and so we didn't want early-adopter migrators to have broken shares. Thus we normalized creation of new datasets to be POSIX acltype if user had selected to inherit from top-level dataset.
After a few releases and user bug reports we realized we needed to have specific ZFS dataset properties set depending on acltype. For example that the aclmode should be DISCARD (discard internal ZFS acl) because changing acltype does not remove the internal ZFS ACL and it could still be evaluated in zfs_zaccess calls. This …
=> NAS-130877 / 24.04.2.1 / Remove acltype normalization for datasets (by anodos325) (by bugclerk)

src/middlewared/middlewared/plugins/alert.py, src/middlewared/middlewared/plugins/ups.py, tests/api2/test_530_ups.py
A recent change (PR #14319) changed the default `lock_queue_size` from `None` to `5`.
However, `ups.dismiss_alerts` was calling `alert.oneshot_delete` 6 times.  Further, shortly afterwards it was calling `alert.oneshot_create` which uses the same lock.  **Depending upon timing**, this _could_ result in the `alert.oneshot_create` not running.
Rectify(/avoid) by adding a `alert.oneshot_bulk_delete`, so that `ups.dismiss_alerts` only needs to make a single call.  (This has the added benefit of being slightly more efficient.)
(Choosing backport-24.10-RC.1 because the above mentioned PR was also backported there.)
=> NAS-130890 / 25.04 / Fix UPS events

src/middlewared/middlewared/plugins/alert.py, src/middlewared/middlewared/plugins/ups.py, tests/api2/test_530_ups.py
A recent change (PR #14319) changed the default `lock_queue_size` from `None` to `5`.
However, `ups.dismiss_alerts` was calling `alert.oneshot_delete` 6 times.  Further, shortly afterwards it was calling `alert.oneshot_create` which uses the same lock.  **Depending upon timing**, this _could_ result in the `alert.oneshot_create` not running.
Rectify(/avoid) by adding a `alert.oneshot_bulk_delete`, so that `ups.dismiss_alerts` only needs to make a single call.  (This has the added benefit of being slightly more efficient.)
(Choosing backport-24.10-RC.1 because the above mentioned PR was also backported there.)
Original PR: https://github.com/truenas/middleware/pull/14391
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130890
=> NAS-130890 / 24.10-RC.1 / Fix UPS events (by bmeagherix)

src/middlewared/middlewared/plugins/webui/enclosure.py, src/middlewared/middlewared/plugins/zfs_/pool_status.py, src/middlewared/middlewared/plugins/zfs_/status_util.py, tests/api2/test_zpool_status.py
`zpool.status` was not properly reporting path for disk properly when a spare had replaced a data disk.
We are now using `zpool status` for retrieving serialized information about the zpool so we can properly account for disk path being reported for spare based disks and that is much better optimized for a system with large number of disks as compared to py-libzfs.
=> NAS-127511 / 25.04 / Fix zpool status for reporting used spare disks correctly

src/middlewared/middlewared/plugins/webui/enclosure.py, src/middlewared/middlewared/plugins/zfs_/pool_status.py, src/middlewared/middlewared/plugins/zfs_/status_util.py, tests/api2/test_zpool_status.py
`zpool.status` was not properly reporting path for disk properly when a spare had replaced a data disk.
We are now using `zpool status` for retrieving serialized information about the zpool so we can properly account for disk path being reported for spare based disks and that is much better optimized for a system with large number of disks as compared to py-libzfs.
Original PR: https://github.com/truenas/middleware/pull/14262
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127511
=> NAS-127511 / 24.10-RC.1 / Fix zpool status for reporting used spare disks correctly (by Qubad786)

src/middlewared/middlewared/plugins/apps/crud.py, src/middlewared/middlewared/plugins/apps/ix_apps/query.py, src/middlewared/middlewared/plugins/apps/ix_apps/utils.py, src/middlewared/middlewared/plugins/apps/logs.py, src/middlewared/middlewared/plugins/apps/resources.py
Currently only those app's logs can be viewed which have containers which are either all running or at least one of them is in running or starting state. However this leads to the problem when an app has containers where all of them have crashed for any reason i.e bad configuration / app issues, unfortunately it is not possible to view logs for those apps yet.
A `CRASHED` state has been introduced which covers the case mentioned above where all the containers in the app if have crashed, that app is marked as `CRASHED` and we would still be able to view logs of such apps.
=> NAS-130995 / 25.04 / Allow retrieving logs of apps in crashed state

src/middlewared/middlewared/job.py, src/middlewared/middlewared/plugins/system/debug.py, src/middlewared/middlewared/plugins/test/rest.py, src/middlewared/middlewared/service/decorators.py, src/middlewared/middlewared/service_exception.py, tests/api2/test_rest_api_download.py
Adding this limit stops people from spamming debug generation, as most of the time just one job is required.
=> NAS-130653 / 25.04 / Updated debug generate lock queue size

src/middlewared/middlewared/job.py, src/middlewared/middlewared/plugins/system/debug.py, src/middlewared/middlewared/plugins/test/rest.py, src/middlewared/middlewared/service/decorators.py, src/middlewared/middlewared/service_exception.py, tests/api2/test_rest_api_download.py
Adding this limit stops people from spamming debug generation, as most of the time just one job is required. 
Original PR: https://github.com/truenas/middleware/pull/14301
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130653
=> NAS-130653 / 24.10-RC.1 / Updated debug generate lock queue size (by aiden3c)

tests/api2/test_005_interface.py
This test is only valid on HA systems and will fail on single node systems. Mark it accordingly. Format the file while I'm here as well.
Original PR: https://github.com/truenas/middleware/pull/14437
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131039
=> NAS-131039 / 24.10-RC.1 / fix test_005_interface:test_004 failing on single node tests (by yocalebo)

src/middlewared/middlewared/plugins/apps/resources.py
This commit adds changes to add an endpoint which UI can consume to retrieve available space in ix-apps dataset so it can show to a user when he wants to install an app that by default X space is available in ix-apps dataset.
=> NAS-131044 / 25.04 / Add an endpoint for UI to retrieve available space for ix-apps

src/middlewared/middlewared/plugins/apps/resources.py
This commit adds changes to add an endpoint which UI can consume to retrieve available space in ix-apps dataset so it can show to a user when he wants to install an app that by default X space is available in ix-apps dataset.
Original PR: https://github.com/truenas/middleware/pull/14441
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131044
=> NAS-131044 / 24.10-RC.1 / Add an endpoint for UI to retrieve available space for ix-apps (by sonicaj)

tests/api2/test_api_key.py
Passing tests here: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/523/testReport/api2/test_api_key/
=> NAS-130920 / 25.04 / remove REST from test_api_key.py

src/middlewared/middlewared/plugins/zfs_/pool_status.py, src/middlewared/middlewared/plugins/zfs_/status_util.py, tests/api2/test_zpool_status.py
Integration test for `zpool.status` was failing earlier because we were not using `filesystem.listdir` to list disks and hence the relevant mapping could not be generated which eventually led to failure of the test.
=> NAS-131017 / 25.04 / Fix zpool.status regression

src/middlewared/middlewared/plugins/zfs_/pool_status.py, src/middlewared/middlewared/plugins/zfs_/status_util.py, tests/api2/test_zpool_status.py
Integration test for `zpool.status` was failing earlier because we were not using `filesystem.listdir` to list disks and hence the relevant mapping could not be generated which eventually led to failure of the test.
Original PR: https://github.com/truenas/middleware/pull/14427
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131017
=> NAS-131017 / 24.10-RC.1 / Fix zpool.status regression (by Qubad786)

src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/utils/filesystem/directory.py, tests/api2/test_listdir_request_mask.py
The directory iterator we use is configurable about what file metdata to retrieve. This can in some situations significantly improve performance of generating directory listing.
This commit modifies the request mask we pass to the iterator based on the user-provided filter-options.
=> NAS-131037 / 25.04 / Be more selective about file metdata in listdir

src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/utils/filesystem/directory.py, tests/api2/test_listdir_request_mask.py
The directory iterator we use is configurable about what file metdata to retrieve. This can in some situations significantly improve performance of generating directory listing.
This commit modifies the request mask we pass to the iterator based on the user-provided filter-options.
Original PR: https://github.com/truenas/middleware/pull/14434
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131037
=> NAS-131037 / 24.10-RC.1 / Be more selective about file metdata in listdir (by anodos325)

src/middlewared/middlewared/plugins/docker/state_setup.py, src/middlewared/middlewared/plugins/kubernetes_to_docker/trigger_migration.py, src/middlewared/middlewared/utils/interface.py
This PR adds changes to try and wait for default interface to come up before trying to consume networking in apps, this is especially problematic for bridge interfaces as they can take some time to come in ready state.
=> NAS-130863 / 25.04 / Properly try waiting for default interface to come up before consuming in apps

src/middlewared/middlewared/plugins/docker/state_setup.py, src/middlewared/middlewared/plugins/kubernetes_to_docker/trigger_migration.py, src/middlewared/middlewared/utils/interface.py
This PR adds changes to try and wait for default interface to come up before trying to consume networking in apps, this is especially problematic for bridge interfaces as they can take some time to come in ready state.
Original PR: https://github.com/truenas/middleware/pull/14431
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130863
=> NAS-130863 / 24.10-RC.1 / Properly try waiting for default interface to come up before consuming in apps (by sonicaj)

src/middlewared/middlewared/plugins/apps/ix_apps/docker/networks.py, src/middlewared/middlewared/plugins/docker/network.py, src/middlewared/middlewared/plugins/interface/internal_ifaces.py, src/middlewared/middlewared/plugins/network.py
This PR adds changes to introduce a docker network crud from where we can retrieve configured docker networks and then we make sure that these interfaces are marked as internal because currently `interface.sync` is unconfiguring docker based interfaces which results in apps networking loss each time interfaces are synced.
=> NAS-131063 / 25.04 / Make sure docker networking is not broken after interface sync

src/middlewared/middlewared/plugins/apps/ix_apps/docker/networks.py, src/middlewared/middlewared/plugins/docker/network.py, src/middlewared/middlewared/plugins/interface/internal_ifaces.py
git cherry-pick -x 401665dd420d5ec1bd88a0dba98cb4ead7a1c71c
git cherry-pick -x d786298fab69faf928d58ba997c4f371ec493023
git cherry-pick -x 12b4296aec9eb13bf7d7b8d35a92136a6caa19fb
git reset --hard HEAD~5
git cherry-pick -x d156c5f173b3a4dc96b4e054eae858fd09bd8f22
This PR adds changes to introduce a docker network crud from where we can retrieve configured docker networks and then we make sure that these interfaces are marked as internal because currently `interface.sync` is unconfiguring docker based interfaces which results in apps networking loss each time interfaces are synced.
Original PR: …
=> NAS-131063 / 24.10-RC.1 / Make sure docker networking is not broken after interface sync (by sonicaj)

src/middlewared/middlewared/plugins/crypto_/certificates.py, tests/api2/test_certs.py
Certificate integration tests are failing as a new field was added to certs which is not applicable for CSRs.
Make sure proper validation is done when the trusted store field is supplied for CSRs and introduce a new integration test to account for the change.
=> NAS-131070 / 25.04 / Fix certificate integration test

src/middlewared/middlewared/alert/source/applications.py, src/middlewared/middlewared/plugins/apps/crud.py, src/middlewared/middlewared/plugins/apps/upgrade.py, src/middlewared/middlewared/plugins/catalog/sync.py, src/middlewared/middlewared/plugins/docker/state_management.py, src/middlewared/middlewared/plugins/docker/state_setup.py, src/middlewared/middlewared/plugins/docker/update.py
We are missing out on a notification mechanism for apps when they have upgrades available and this is accounted for in these changes by having an upgrade alert be generated when a new version of the app is available. While working on this, another issue was observed that docker image cache was not being updated on docker pool state changes which has been fixed as well.
=> NAS-130860 / 25.04 / Have upgrade alerts for apps

src/middlewared/middlewared/alert/source/applications.py, src/middlewared/middlewared/plugins/apps/crud.py, src/middlewared/middlewared/plugins/apps/upgrade.py, src/middlewared/middlewared/plugins/catalog/sync.py, src/middlewared/middlewared/plugins/docker/state_management.py, src/middlewared/middlewared/plugins/docker/state_setup.py, src/middlewared/middlewared/plugins/docker/update.py
We are missing out on a notification mechanism for apps when they have upgrades available and this is accounted for in these changes by having an upgrade alert be generated when a new version of the app is available. While working on this, another issue was observed that docker image cache was not being updated on docker pool state changes which has been fixed as well.
Original PR: https://github.com/truenas/middleware/pull/14458
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130860
=> NAS-130860 / 24.10-RC.1 / Have upgrade alerts for apps (by Qubad786)

src/middlewared/middlewared/plugins/pool_/pool.py, tests/api2/test_006_pool_and_sysds.py
These have been used pretty successfully for a number of years in Core and SCALE. We can just enable by default these days and get the corresponding performance boost.
=> NAS-131061 / 25.04 / enable SA-based xattrs by default on new pools

src/middlewared/middlewared/plugins/kubernetes_to_docker/trigger_migration.py
Automatic migration was failing due to a typo which has been fixed.
=> NAS-131085 / 25.04 / Fix app migration

src/middlewared/middlewared/plugins/kubernetes_to_docker/trigger_migration.py
Automatic migration was failing due to a typo which has been fixed.
Original PR: https://github.com/truenas/middleware/pull/14468
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131085
=> NAS-131085 / 24.10-RC.1 / Fix app migration (by Qubad786)

tests/api2/test_260_iscsi.py
Replace REST calls with websocket calls
In addition, made **extensive** use of (class scoped) fixtures, for better cleanup and also to facilitate reuse.
---
CI run with passing tests from this file [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/581/).
=> NAS-130931 / 25.04 / Replace REST calls with websocket calls

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/pytest/unit/utils/test_copytree.py, src/middlewared/middlewared/pytest/unit/utils/test_statx.py, src/middlewared/middlewared/utils/filesystem/acl.py, src/middlewared/middlewared/utils/filesystem/copy.py, src/middlewared/middlewared/utils/filesystem/directory.py, src/middlewared/middlewared/utils/filesystem/stat_x.py, src/middlewared/middlewared/utils/filesystem/utils.py, tests/api2/test_user_create_dir.py
User may have nologin shell causing the attempt to run cp in a
subprocess to fail due to failure to su to the user in question (due to
error in pam_open_session()).
After review of history for why we were subprocessing out to perform
this task, I failed to find a compelling reason why we could not simply
copy them without switching the user context.
This commit adds a new `copytree` filesystem utility that provides the
following features that are relevant to copying home directories.
1. ability to control behavior regarding whether the copy operation
will walk into child datasets. Generally this is not desired because
we have no design or provisions for creating child datasets within a
user home directory. This situation is most likely to arise when users
mistakenly set an incorrect path …
=> NAS-130696 / 25.04 / Fix issues with user.update endpoint

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/pytest/unit/utils/test_copytree.py, src/middlewared/middlewared/pytest/unit/utils/test_statx.py, src/middlewared/middlewared/utils/filesystem/acl.py, src/middlewared/middlewared/utils/filesystem/copy.py, src/middlewared/middlewared/utils/filesystem/directory.py, src/middlewared/middlewared/utils/filesystem/stat_x.py, src/middlewared/middlewared/utils/filesystem/utils.py, tests/api2/test_user_create_dir.py
User may have nologin shell causing the attempt to run cp in a
subprocess to fail due to failure to su to the user in question (due to
error in pam_open_session()).
After review of history for why we were subprocessing out to perform
this task, I failed to find a compelling reason why we could not simply
copy them without switching the user context.
This commit adds a new `copytree` filesystem utility that provides the
following features that are relevant to copying home directories.
1. ability to control behavior regarding whether the copy operation
will walk into child datasets. Generally this is not desired because
we have no design or provisions for creating child datasets within a
user home directory. This situation is most likely to arise when users
mistakenly set an incorrect path …
=> NAS-130696 / 24.10-RC.1 / Fix issues with user.update endpoint (by anodos325)

src/middlewared/middlewared/api/base/handler/accept.py, src/middlewared/middlewared/api/base/handler/dump_params.py, src/middlewared/middlewared/api/base/handler/inspect.py, src/middlewared/middlewared/api/base/handler/version.py, src/middlewared/middlewared/api/base/model.py, src/middlewared/middlewared/api/base/server/legacy_api_method.py, src/middlewared/middlewared/api/base/server/method.py, src/middlewared/middlewared/api/base/server/ws_handler/rpc_factory.py, src/middlewared/middlewared/main.py, src/middlewared/middlewared/pytest/unit/api/base/server/test_legacy_api_method.py, src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt.py, src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_default.py, src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_nested_model.py, src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_nested_model_list.py, src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_shortcuts.py, src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_validation.py, src/middlewared/middlewared/utils/service/crud.py
Continue implementing NEP 046 (Versioned API).
This code adds `/api/vXX.XX.X` endpoints for all API versions we have and provides data conversion routines between those versions.
There are no integration tests because we don't yet have two different API versions. The code is extensively covered by unit-tests. The integration testing was performed by adding a fake 24.10.0 API and ensuring everything works smoothly. Fake API code is not present in this PR.
=> NAS-130979 / 25.04 / Support legacy API

src/middlewared/middlewared/plugins/apps/crud.py, src/middlewared/middlewared/plugins/apps/metadata.py
When an app is in the progress of being deleted, UI is querying apps trying to retrieve app schema as well which we don't keep collectively cached and that errors out as this can/cannot happen that app folder has been removed but metadata has not been updated yet.
Before removing app from filesystem, remove app from collective metadata which is used to generate list of installed apps and then remove the app's related content from filesystem.
=> NAS-131086 / 25.04 / Fix app deletion edge case

src/middlewared/middlewared/plugins/apps/crud.py, src/middlewared/middlewared/plugins/apps/metadata.py
When an app is in the progress of being deleted, UI is querying apps trying to retrieve app schema as well which we don't keep collectively cached and that errors out as this can/cannot happen that app folder has been removed but metadata has not been updated yet.
Before removing app from filesystem, remove app from collective metadata which is used to generate list of installed apps and then remove the app's related content from filesystem.
Original PR: https://github.com/truenas/middleware/pull/14470
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131086
=> NAS-131086 / 24.10-RC.1 / Fix app deletion edge case (by Qubad786)

src/middlewared/middlewared/logger.py, src/middlewared/middlewared/plugins/apps/compose_utils.py
This PR adds changes to introduce a separate logging file for app lifecycle related issues as raising them in compose related jobs means that they will get logged to middlewared.log and this can then result into it becoming quite noisy.
=> NAS-131019 / 25.04 / Have separate logging file for logging app lifecycle issues

src/middlewared/middlewared/logger.py, src/middlewared/middlewared/plugins/apps/compose_utils.py
This PR adds changes to introduce a separate logging file for app lifecycle related issues as raising them in compose related jobs means that they will get logged to middlewared.log and this can then result into it becoming quite noisy.
Original PR: https://github.com/truenas/middleware/pull/14481
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131019
=> NAS-131019 / 24.10-RC.1 / Have separate logging file for logging app lifecycle issues (by sonicaj)

src/middlewared/middlewared/plugins/acme_protocol.py
This commit fixes a case where tos can be null which we get from an ACME provider. In the database we keep it as an empty string because this needs to go through the libraries we are using to generate an ACME certificate which can/cannot error out and unfortunately we don't have an ACME provider atm which gives a null tos to test a null case. Keeping it as an empty string in that case in database if tos received is null.
=> NAS-130694 / 25.04 / Handle potential case when tos can be null

src/middlewared/middlewared/plugins/acme_protocol.py
This commit fixes a case where tos can be null which we get from an ACME provider. In the database we keep it as an empty string because this needs to go through the libraries we are using to generate an ACME certificate which can/cannot error out and unfortunately we don't have an ACME provider atm which gives a null tos to test a null case. Keeping it as an empty string in that case in database if tos received is null.
Original PR: https://github.com/truenas/middleware/pull/14484
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130694
=> NAS-130694 / 24.10-RC.1 / Handle potential case when tos can be null (by sonicaj)

src/middlewared/middlewared/plugins/directoryservices.py, src/middlewared/middlewared/plugins/directoryservices_/ipa_health_mixin.py, src/middlewared/middlewared/plugins/directoryservices_/ldap_health_mixin.py, src/middlewared/middlewared/plugins/smb.py
This fix addresses a few minor issues with directory services state recovery.
1. Rather than simply failing directoryservices.setup if unhealthy, we should take recovery steps
2. If for some reason SSSD fails to start triggering a health check failure we should go through etc.generate steps to make sure we have all required files written before trying to start it again.
3. Always generate the nsswitch.conf after setting up directory services. This avoids possibilty of having SSSD / winbind running without them being present in nsswitch.conf on failover.
=> NAS-130709 / 25.04 / Fix LDAP status on failover

src/middlewared/middlewared/plugins/directoryservices.py, src/middlewared/middlewared/plugins/directoryservices_/ipa_health_mixin.py, src/middlewared/middlewared/plugins/directoryservices_/ldap_health_mixin.py, src/middlewared/middlewared/plugins/smb.py
This fix addresses a few minor issues with directory services state recovery.
1. Rather than simply failing directoryservices.setup if unhealthy, we should take recovery steps
2. If for some reason SSSD fails to start triggering a health check failure we should go through etc.generate steps to make sure we have all required files written before trying to start it again.
3. Always generate the nsswitch.conf after setting up directory services. This avoids possibilty of having SSSD / winbind running without them being present in nsswitch.conf on failover.
Original PR: https://github.com/truenas/middleware/pull/14480
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130709
=> NAS-130709 / 24.10-RC.1 / Fix LDAP status on failover (by anodos325)

tests/api2/test_005_interface.py
I'm still seeing this test fail on non HA systems and it's because I decorated the method with invalid logic. This fixes the decorator so that this test is, for real this time, skipped on _non_ HA systems.
=> NAS-131121 / 25.04 / fix skipif logic in test_005

tests/api2/test_005_interface.py
I'm still seeing this test fail on non HA systems and it's because I decorated the method with invalid logic. This fixes the decorator so that this test is, for real this time, skipped on _non_ HA systems.
Original PR: https://github.com/truenas/middleware/pull/14489
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131121
=> NAS-131121 / 24.10-RC.1 / fix skipif logic in test_005 (by yocalebo)

src/middlewared/middlewared/plugins/ntp.py
I'm working on removing REST calls from `test_500` and I've discovered a rather annoying behavior with the `system.ntpserver.create` endpoint. The problem is that we're _always_ testing whether or not the NTP peer that is being added is "reachable" disregarding the "force" flag. This means, no matter what, each NTP peer being added will wait up to 5 seconds before completing.
This changes it so that if the "force" flag is set to True it will not try to send ntp packets to the NTP peer.
=> NAS-131122 / 25.04 / dont test ntp peer if force is set to true

src/middlewared/middlewared/plugins/audit/audit.py, src/middlewared/middlewared/plugins/audit/utils.py, tests/api2/test_audit_basic.py
On HA systems each controller maintains an independent audit database.  Actions on a controller are reported only in the audit DB associated with that controller.
Provide the capability to query and download the audit DB from the 'other' controller.
If no controller is specified the audit action is performed on the 'current' controller.
If the controller is specified the audit action will be performed on the requested controller.
The controller can be specified by any of the following names:  'BACKUP', 'Standby', 'MASTER', 'Active'.
Passing CI tests: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/631/
=> NAS-130700 / 25.04 / Add support for remote controller audit query and download

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/smb.py, tests/api2/test_011_user.py
While fixing an unrelated bug that affected LDAP failover, a restart of the winbind service was removed from the directory services setup method. Changes to directory services health checks in electric eel improved error recovery and eliminated the need for this step.
Unfortunately, this removal exposed that user.get_user_obj and group.get_group_obj were still relying on winbind to perform SID resolution (which failed because winbind had not started yet on the server).
As of electric eel, the SID values for local accounts are derived from the `id` value of the user / group entry in their respective database table. This commit robustizes SID lookups for local accounts through get_obj methods by retrieving it via user.query and group.query.
Original PR: …
=> NAS-131114 / 24.10-RC.1 / Fix regression in getting sid_info for local users (by anodos325)

src/middlewared/middlewared/plugins/apps/stats_util.py
When we have multiple containers in a compose file and they are using multiple cores of the system, our calculation of cpu usage stats will be inaccurate as it assumes a single core and percentage goes well above 100% depending on system cores and the ones being used. This compose file can be used to replicate the issue
```
version: "3"
services:
cpu_stress_1:
image: ubuntu:latest
container_name: cpu_stress_1
command: "bash -c 'apt-get update && apt-get install -y stress && stress --cpu 4'"
deploy:
resources:
limits:
cpus: "2"
reservations:
cpus: "1"
cpu_stress_2:
image: ubuntu:latest
container_name: cpu_stress_2
command: "bash -c 'apt-get update && apt-get install -y stress && stress --cpu 4'"
deploy:
resources:
limits:
cpus: "2"
reservations:
cpus: "1"
cpu_stress_3:
image: ubuntu:latest …
```
=> NAS-131159 / 25.04 / Fix CPU stats in apps stats reporting

src/middlewared/middlewared/plugins/apps/stats_util.py
When we have multiple containers in a compose file and they are using multiple cores of the system, our calculation of cpu usage stats will be inaccurate as it assumes a single core and percentage goes well above 100% depending on system cores and the ones being used. This compose file can be used to replicate the issue
```
version: "3"
services:
cpu_stress_1:
image: ubuntu:latest
container_name: cpu_stress_1
command: "bash -c 'apt-get update && apt-get install -y stress && stress --cpu 4'"
deploy:
resources:
limits:
cpus: "2"
reservations:
cpus: "1"
cpu_stress_2:
image: ubuntu:latest
container_name: cpu_stress_2
command: "bash -c 'apt-get update && apt-get install -y stress && stress --cpu 4'"
deploy:
resources:
limits:
cpus: "2"
reservations:
cpus: "1"
cpu_stress_3:
image: ubuntu:latest …
```
=> NAS-131159 / 24.10-RC.1 / Fix CPU stats in apps stats reporting (by Qubad786)

src/middlewared/middlewared/plugins/apps/stats_util.py
When we have multiple containers in a compose file and they are using multiple cores of the system, our calculation of cpu usage stats will be inaccurate as it assumes a single core and percentage goes well above 100% depending on system cores and the ones being used. This compose file can be used to replicate the issue
```
version: "3"
services:
cpu_stress_1:
image: ubuntu:latest
container_name: cpu_stress_1
command: "bash -c 'apt-get update && apt-get install -y stress && stress --cpu 4'"
deploy:
resources:
limits:
cpus: "2"
reservations:
cpus: "1"
cpu_stress_2:
image: ubuntu:latest
container_name: cpu_stress_2
command: "bash -c 'apt-get update && apt-get install -y stress && stress --cpu 4'"
deploy:
resources:
limits:
cpus: "2"
reservations:
cpus: "1"
cpu_stress_3:
image: ubuntu:latest …
```
=> NAS-131159 / 24.10.0 / Fix CPU stats in apps stats reporting (by Qubad786)

src/middlewared/middlewared/plugins/apps/stats_util.py
While looking at the cpu stats logic, there is another edge case possibility where we might report cpu usage percentage as negative. This would happen when old stats have multiple containers running - the stats we get are cpu usage time in nanoseconds and that are aggregated for all containers in a single compose file.
Now when the app is being stopped for example, what can happen is that old stats has accumulative cpu usage time of 3 containers and currently there is only 1 container running - which means we will only have cpu usage time in nanoseconds of 1 container and that would be less then what we had in old stats and computing delta here would be negative.
If cpu delta is negative, we should just report cpu usage as 0 in that case as we can't reliably compute cpu usage anymore and …
=> NAS-131163 / 25.04 / Fix negative value reported for cpu app stats

src/middlewared/middlewared/plugins/apps/stats_util.py
While looking at the cpu stats logic, there is another edge case possibility where we might report cpu usage percentage as negative. This would happen when old stats have multiple containers running - the stats we get are cpu usage time in nanoseconds and that are aggregated for all containers in a single compose file.
Now when the app is being stopped for example, what can happen is that old stats has accumulative cpu usage time of 3 containers and currently there is only 1 container running - which means we will only have cpu usage time in nanoseconds of 1 container and that would be less then what we had in old stats and computing delta here would be negative.
If cpu delta is negative, we should just report cpu usage as 0 in that case as we can't reliably compute cpu usage anymore and …
=> NAS-131163 / 24.10-RC.1 / Fix negative value reported for cpu app stats (by Qubad786)

src/middlewared/middlewared/plugins/apps/stats_util.py
While looking at the cpu stats logic, there is another edge case possibility where we might report cpu usage percentage as negative. This would happen when old stats have multiple containers running - the stats we get are cpu usage time in nanoseconds and that are aggregated for all containers in a single compose file.
Now when the app is being stopped for example, what can happen is that old stats has accumulative cpu usage time of 3 containers and currently there is only 1 container running - which means we will only have cpu usage time in nanoseconds of 1 container and that would be less then what we had in old stats and computing delta here would be negative.
If cpu delta is negative, we should just report cpu usage as 0 in that case as we can't reliably compute cpu usage anymore and …
=> NAS-131163 / 24.10.0 / Fix negative value reported for cpu app stats (by Qubad786)

src/middlewared/middlewared/plugins/boot.py, src/middlewared/middlewared/plugins/iscsi_/extents.py, src/middlewared/middlewared/plugins/vm/devices/storage_devices.py, src/middlewared/middlewared/plugins/zfs_/validation_utils.py, src/middlewared/middlewared/service/sharing_service.py
There have been users who have created zvols with `zfs create` and then consumed them in VMs where the zvols resided in boot-pool.
Enhance validation to not allow users to specify zvols which reside on boot-pool.
=> NAS-130530 / 25.04 / Do not allow VMs to consume zvols on boot-pool

src/middlewared/middlewared/alembic/versions/25.04/2024-09-12_23-57_remove_nfs_v4_v3owner.py, src/middlewared/middlewared/plugins/nfs.py, tests/api2/test_300_nfs.py
The NFS configuration setting, `v4_v3owner` has always been an inactive and non-functional setting in SCALE.  It has been marked as deprecated in previous releases.
This PR removes the unused and non-functional v4_v3owner NFS configuration setting.
This PR includes an alembic migration and updates the NFS CI tests.
=> NAS-131056 / 25.04 / Remove deprecated v4_v3owner NFS configuration setting

src/middlewared/middlewared/plugins/apps/ix_apps/lifecycle.py, src/middlewared/middlewared/plugins/apps/ix_apps/metadata.py, src/middlewared/middlewared/plugins/apps/ix_apps/setup.py
This commit makes two minor changes to harden our ix-apps metadata to avoid crashes due to yaml_loads returning None instead of the expected dict. One reason this can happen is that the file in question is empty when read.
1. Switch to using the middleware io util `write_if_changed` This makes writes to the metadata yaml files de-facto atomic as we write to temporary file, flush it, then rename over existing file. Since the files are only used by middlewared I am proactively setting permissions on them to 0o600.
2. Add a wrapper around yaml.safe_load to return an empty dict instead of None type if file is empty. Consumers of these methods expect to receive a dict and so we must handle this edge case.
=> NAS-131168 / 25.04 / harden ix-apps metadata handling

src/middlewared/middlewared/plugins/apps/ix_apps/lifecycle.py, src/middlewared/middlewared/plugins/apps/ix_apps/metadata.py, src/middlewared/middlewared/plugins/apps/ix_apps/setup.py
This commit makes two minor changes to harden our ix-apps metadata to avoid crashes due to yaml_loads returning None instead of the expected dict. One reason this can happen is that the file in question is empty when read.
1. Switch to using the middleware io util `write_if_changed` This makes writes to the metadata yaml files de-facto atomic as we write to temporary file, flush it, then rename over existing file. Since the files are only used by middlewared I am proactively setting permissions on them to 0o600.
2. Add a wrapper around yaml.safe_load to return an empty dict instead of None type if file is empty. Consumers of these methods expect to receive a dict and so we must handle this edge case.
Original PR: https://github.com/truenas/middleware/pull/14510
Jira URL: …
=> NAS-131168 / 24.10.0 / harden ix-apps metadata handling (by anodos325)

src/middlewared/middlewared/plugins/apps/ix_apps/lifecycle.py, src/middlewared/middlewared/plugins/apps/ix_apps/metadata.py, src/middlewared/middlewared/plugins/apps/ix_apps/setup.py
This commit makes two minor changes to harden our ix-apps metadata to avoid crashes due to yaml_loads returning None instead of the expected dict. One reason this can happen is that the file in question is empty when read.
1. Switch to using the middleware io util `write_if_changed` This makes writes to the metadata yaml files de-facto atomic as we write to temporary file, flush it, then rename over existing file. Since the files are only used by middlewared I am proactively setting permissions on them to 0o600.
2. Add a wrapper around yaml.safe_load to return an empty dict instead of None type if file is empty. Consumers of these methods expect to receive a dict and so we must handle this edge case.
Original PR: https://github.com/truenas/middleware/pull/14510
Jira URL: …
=> NAS-131168 / 24.10-RC.1 / harden ix-apps metadata handling (by anodos325)

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/smb.py
Early in electric eel development, the SID values associated with local users and groups were changed to be deterministic based on their respective datastore table primary keys. A subsequent commit changed how this SID information was retrieved in user.get_user_obj and group.get_group_obj to ensure that we stopped relying on a winbind client connection (to robustize against edge case of user not having winbindd running). This SID information was obtained via user.query and group.query.
Unfortunately, the developer neglected to set an additional ['local', '=', True] filter for the query request (which limits to local users only), which resulted in call to directoryservices.cache.query when AD or LDAP is enabled. If the account is a local account then the cache lookup failure results in …
=> NAS-131178 / 25.04 / Fix recursion in getting SID info

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/smb.py
Early in electric eel development, the SID values associated with local users and groups were changed to be deterministic based on their respective datastore table primary keys. A subsequent commit changed how this SID information was retrieved in user.get_user_obj and group.get_group_obj to ensure that we stopped relying on a winbind client connection (to robustize against edge case of user not having winbindd running). This SID information was obtained via user.query and group.query.
Unfortunately, the developer neglected to set an additional ['local', '=', True] filter for the query request (which limits to local users only), which resulted in call to directoryservices.cache.query when AD or LDAP is enabled. If the account is a local account then the cache lookup failure results in …
=> NAS-131178 / 24.10.0 / Fix recursion in getting SID info (by anodos325)

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/smb.py
Early in electric eel development, the SID values associated with local users and groups were changed to be deterministic based on their respective datastore table primary keys. A subsequent commit changed how this SID information was retrieved in user.get_user_obj and group.get_group_obj to ensure that we stopped relying on a winbind client connection (to robustize against edge case of user not having winbindd running). This SID information was obtained via user.query and group.query.
Unfortunately, the developer neglected to set an additional ['local', '=', True] filter for the query request (which limits to local users only), which resulted in call to directoryservices.cache.query when AD or LDAP is enabled. If the account is a local account then the cache lookup failure results in …
=> NAS-131178 / 24.10-RC.1 / Fix recursion in getting SID info (by anodos325)

src/middlewared/middlewared/plugins/mail.py, tests/api2/test_mail_admins.py
Originally the mail.local_administrators only returned users who were members of the default builtin local administrators privilege by virtue of auxiliary group membership. This commit makes the logic more generic. Since the method was originally written we expanded user.query output to include information about the user's roles and so we can select all users with FULL_ADMIN privileges (which may be granted by non-default privilege sets).
=> NAS-131161 / 25.04 / Properly filter for local admins emails

src/middlewared/middlewared/plugins/mail.py, tests/api2/test_mail_admins.py
Originally the mail.local_administrators only returned users who were members of the default builtin local administrators privilege by virtue of auxiliary group membership. This commit makes the logic more generic. Since the method was originally written we expanded user.query output to include information about the user's roles and so we can select all users with FULL_ADMIN privileges (which may be granted by non-default privilege sets).
Original PR: https://github.com/truenas/middleware/pull/14515
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131161
=> NAS-131161 / 24.10.0 / Properly filter for local admins emails (by anodos325)

src/middlewared/middlewared/alert/source/failover_remote_inaccessible.py
`failover_related = True` isn't working by design. It's only by pure chance that our failover related alerts are all checking failover.licensed endpoint before running. Since this is being backported to 24.04.2.2, I'm keeping the changes as minimal as possible. I will, however, be pushing another PR to fix the `faliover_related` attribute more thoroughly.
=> NAS-131183 / 25.04 / fix HA inaccessible alert

src/middlewared/middlewared/alert/source/failover_remote_inaccessible.py
`failover_related = True` isn't working by design. It's only by pure chance that our failover related alerts are all checking failover.licensed endpoint before running. Since this is being backported to 24.04.2.2, I'm keeping the changes as minimal as possible. I will, however, be pushing another PR to fix the `faliover_related` attribute more thoroughly.
Original PR: https://github.com/truenas/middleware/pull/14521
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131183
=> NAS-131183 / 24.04.2.2 / fix HA inaccessible alert (by yocalebo)

src/middlewared/middlewared/alert/source/failover_remote_inaccessible.py
`failover_related = True` isn't working by design. It's only by pure chance that our failover related alerts are all checking failover.licensed endpoint before running. Since this is being backported to 24.04.2.2, I'm keeping the changes as minimal as possible. I will, however, be pushing another PR to fix the `faliover_related` attribute more thoroughly.
Original PR: https://github.com/truenas/middleware/pull/14521
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131183
=> NAS-131183 / 24.10.0 / fix HA inaccessible alert (by yocalebo)

src/middlewared/middlewared/alert/source/failover_remote_inaccessible.py
`failover_related = True` isn't working by design. It's only by pure chance that our failover related alerts are all checking failover.licensed endpoint before running. Since this is being backported to 24.04.2.2, I'm keeping the changes as minimal as possible. I will, however, be pushing another PR to fix the `faliover_related` attribute more thoroughly.
Original PR: https://github.com/truenas/middleware/pull/14521
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131183
=> NAS-131183 / 24.10-RC.1 / fix HA inaccessible alert (by yocalebo)
