src/middlewared/middlewared/plugins/iscsi_/extents.py
src/middlewared/middlewared/plugins/vm/devices/storage_devices.py
src/middlewared/middlewared/plugins/zfs_/validation_utils.py
src/middlewared/middlewared/service/sharing_service.py

There have been users who have created zvols with `zfs create` and then consumed them in VMs where the zvols resided in boot-pool.
Enhance validation to not allow users to specify zvols which reside on boot-pool.
Original PR: https://github.com/truenas/middleware/pull/14180
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130530

NAS-130530 / 24.10.0 / Do not allow VMs to consume zvols on boot-pool (by Qubad786)

---

src/middlewared/middlewared/plugins/smb_/sharesec.py

A faulty check for changed SMB share ACL was triggering datastore write on every check interval.

NAS-131232 / 25.04 / Fix SMB share ACL sync log spam

---

src/middlewared/middlewared/plugins/smb_/sharesec.py

A faulty check for changed SMB share ACL was triggering datastore write on every check interval.
Original PR: https://github.com/truenas/middleware/pull/14527
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131232

NAS-131232 / 24.10.0 / Fix SMB share ACL sync log spam (by anodos325)

---

src/middlewared/middlewared/plugins/smb_/sharesec.py

A faulty check for changed SMB share ACL was triggering datastore write on every check interval.
Original PR: https://github.com/truenas/middleware/pull/14527
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131232

NAS-131232 / 24.10-RC.1 / Fix SMB share ACL sync log spam (by anodos325)

---

src/middlewared/middlewared/pytest/unit/utils/test_groupmap.py
src/middlewared/middlewared/utils/crypto.py
src/middlewared/middlewared/utils/tdb.py
src/middlewared/middlewared/utils/user_api_key.py
tests/requirements.txt
tests/run_unit_tests.py
tests/unit/test_pam_tdb.py

This commit adds required middleware utils for writing pam_tdb contents for
user-linked API keys along with a local unit test framework to be used from
a jenkins pipeline.
A followup ticket will be created to implement API changes required for NEP.

NAS-131223 / 25.04 / Add basic utilities for manipulating pam_tdb data

---

src/middlewared/middlewared/alert/source/failover.py
src/middlewared/middlewared/alert/source/failover_disks.py
src/middlewared/middlewared/alert/source/failover_interfaces.py
src/middlewared/middlewared/alert/source/failover_nics.py
src/middlewared/middlewared/alert/source/failover_remote_inaccessible.py
src/middlewared/middlewared/plugins/alert.py

Back in 2021 ([vide](https://github.com/truenas/middleware/pull/8015)), the PM team decided that `SCALE_ENTERPRISE` no longer meant HA capable _ONLY_ hardware. This product type was extended to all iX branded appliances. This was a subtle, but profoundly impacting change. Specifically with how we handle things like alerts, for example. A recent alert was added (at the bequest of PM) to create proactive alerts when an HA system's other controller doesn't respond after a certain threshold of time ([vide](https://github.com/truenas/middleware/pull/14356)). Unfortunately, the incorrect (but non-intuitive) assumption was made that `failover_related = True` would run on _HA ONLY_ systems. This _was_ true back in 2021, however, it hasn't been true since. Further investigation showed that every …

NAS-131224 / 25.04 / Fix long-standing alert issue on HA

---

src/middlewared/middlewared/plugins/directoryservices.py
src/middlewared/middlewared/plugins/directoryservices_/cache.py

This commit fixes some errors introduced while renaming private directory services cache methods.
Original PR: https://github.com/truenas/middleware/pull/14533
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131265

NAS-131265 / 24.10.0 / Fix typo in cache refresh calls (by anodos325)

---

src/middlewared/middlewared/plugins/directoryservices.py
src/middlewared/middlewared/plugins/directoryservices_/cache.py

This commit fixes some errors introduced while renaming private directory services cache methods.
Original PR: https://github.com/truenas/middleware/pull/14533
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131265

NAS-131265 / 24.10-RC.1 / Fix typo in cache refresh calls (by anodos325)

---

debian/debian/ix-reboot.service
debian/debian/rules
src/freenas/usr/local/bin/scst_util.sh
src/middlewared/middlewared/plugins/failover_/event.py

Turn off any ALUA `cluster_mode` _**_before_**_ stopping _middlewared_ on reboot or shutdown.
Original PR: https://github.com/truenas/middleware/pull/14520
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131186

NAS-131186 / 24.10.0 / Add stop-alua to scst_util.sh and call before stopping middlewared (by bmeagherix)

---

src/middlewared/middlewared/plugins/docker/fs_manage.py
src/middlewared/middlewared/plugins/docker/state_management.py
src/middlewared/middlewared/plugins/docker/state_setup.py
src/middlewared/middlewared/plugins/docker/update.py
src/middlewared/middlewared/plugins/service_/services/docker.py
src/middlewared/middlewared/plugins/zfs_/dataset_actions.py

This PR adds changes to improve docker datasets mount/umount behavior. Earlier we used to mount/umount on docker service start/stop but that was excessive after discussion with Caleb and the finalized workflow was:
1. Mount on system boot if docker is configured
2. Umount/mount only if docker pool is changed

NAS-131208 / 25.04 / Improvements to mounting/umounting docker datasets

---

src/middlewared/middlewared/plugins/alert.py

A subtle typo is causing this crash on HA. It's happening because I'm appending a list to a list.
```
[2024/09/18 10:25:58] (ERROR) middlewared.job.run():504 - Job <bound method AlertService.process_alerts of <middlewared.plugins.alert.AlertService object at 0x7f2ac1ecd7d0>> failed
File "/usr/lib/python3/dist-packages/middlewared/job.py", line 489, in run
await self.future
File "/usr/lib/python3/dist-packages/middlewared/job.py", line 534, in __run_body
rv = await self.method(*args)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/alert.py", line 494, in process_alerts
await self.__run_alerts()
File "/usr/lib/python3/dist-packages/middlewared/plugins/alert.py", line 774, in __run_alerts
oalert.node = fi.other_node …
```

NAS-131293 / 25.04 / fix regression in alerts

---

src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
src/middlewared/middlewared/plugins/enclosure_/sysfs_disks.py

The legacy enclosure plugin has this logic but it wasn't copied over to the new enclosure plugin. H-series has to be handled specially when enumerating drives via sysfs. Furthermore, the `front_slots` property was incorrectly reporting 16 front slots when h-series only has 12.

NAS-131179 / 25.04 / fix drive identify on h-series

---

src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
src/middlewared/middlewared/plugins/enclosure_/sysfs_disks.py

The legacy enclosure plugin has this logic but it wasn't copied over to the new enclosure plugin. H-series has to be handled specially when enumerating drives via sysfs. Furthermore, the `front_slots` property was incorrectly reporting 16 front slots when h-series only has 12.
Original PR: https://github.com/truenas/middleware/pull/14540
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131179

NAS-131179 / 24.10.0 / fix drive identify on h-series (by yocalebo)

---

src/middlewared/middlewared/test/integration/utils/audit.py
tests/api2/test_audit_rest.py

While the REST tests I re-added are able to pass when run by themselves, it's become clear that they are upsetting the system state for the remaining tests that run after them, causing many errors and failures. I suspect a temporary user is not properly being deleted somewhere, but is not raising any alarm. Until I figure out what's going on I am removing these bad tests so we can continue using our test pipeline.

NAS-131304 / 25.04 / Revert NAS-131172

---

src/middlewared/middlewared/test/integration/assets/hostkvm.py
tests/api2/assets/websocket/iscsi.py
tests/api2/test_261_iscsi_cmd.py
tests/api2/test_262_iscsi_alua.py

Add a more extensive iSCSI ALUA test.
- Test that an ALUA target - without a LUN 0 - works correctly with only LUN 100.  The previous `test_33_no_lun_zero` tests purely from client perspective, but this new test (`test_alua_lun_100`) will also exercise the "internal" target used in ALUA.
- Test a non-trivial ALUA configuration.  This includes targets with no LUNs, one LUN, two LUNs & five LUNs - 10 targets, 16 LUNs in total.  With this config ...
- Use KVM `virsh` command to power off the current ACTIVE node (i.e. **not** a clean shutdown) and ensure that the previous STANDBY node serves the ALUA targets, as soon as failover is complete.
- Reset the current ACTIVE, and repower the previous ACTIVE and ensure that ALUA targets are served by both nodes.  (Clean simultaneous boot of both …

NAS-127298 / 25.04 / Add extensive iSCSI ALUA unit test

---

src/middlewared/middlewared/api/base/handler/accept.py
src/middlewared/middlewared/api/base/handler/dump_params.py
src/middlewared/middlewared/api/base/handler/result.py
src/middlewared/middlewared/api/base/model.py
src/middlewared/middlewared/api/base/types/base.py
src/middlewared/middlewared/api/v25_04_0/api_key.py
src/middlewared/middlewared/api/v25_04_0/cloud_sync.py
src/middlewared/middlewared/api/v25_04_0/group.py
src/middlewared/middlewared/api/v25_04_0/keychain.py
src/middlewared/middlewared/api/v25_04_0/user.py
src/middlewared/middlewared/pytest/unit/api/handler/accept/test_secret.py
src/middlewared/middlewared/pytest/unit/api/handler/result/test_secret.py
src/middlewared/middlewared/pytest/unit/api/handler/result/test_types.py
src/middlewared/middlewared/pytest/unit/test_service_crud_service.py

NAS-131143 / 25.04 / Always use python serializer and preserve types

---

src/middlewared/middlewared/plugins/apps/crud.py
src/middlewared/middlewared/plugins/apps/custom_app.py
src/middlewared/middlewared/plugins/apps/ix_apps/path.py

This PR adds changes to remove any app volume mount datasets created during installation in the event installation process failed for whatever reason. We are picky on this end and make sure we only remove them if the app volume dataset didn't exist before as when a user deletes an app, it's optional for him/her to remove the app volume mounts datasets and we don't want them nuked if a user installs an app with the same name and app install fails for whatever reason.

NAS-130966 / 25.04 / Make sure we delete any app volume mount datasets created on app install failure

---

src/middlewared/middlewared/plugins/apps/crud.py
src/middlewared/middlewared/plugins/apps/custom_app.py
src/middlewared/middlewared/plugins/apps/ix_apps/path.py

This PR adds changes to remove any app volume mount datasets created during installation in the event installation process failed for whatever reason. We are picky on this end and make sure we only remove them if the app volume dataset didn't exist before as when a user deletes an app, it's optional for him/her to remove the app volume mounts datasets and we don't want them nuked if a user installs an app with the same name and app install fails for whatever reason.
Original PR: https://github.com/truenas/middleware/pull/14544
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130966

NAS-130966 / 24.10.0 / Make sure we delete any app volume mount datasets created on app install failure (by sonicaj)

---

src/middlewared/middlewared/plugins/system/debug.py

The standby debug is downloaded via REST over the heartbeat and put into an io.BytesIO object. This bytes object doesn't store file metadata like mtime. To remedy the situation, simply update the mtime attribute after we add it to a TarInfo object before writing it to the parent archive. Without these changes, the mtime is empty which gets interpreted in many different ways depending on the OS that is interpreting the archive file.
This has been a _long_ standing issue.

NAS-131296 / 25.04 / fix modify time for HA debug archives

---

src/middlewared/middlewared/plugins/docker/state_management.py
src/middlewared/middlewared/plugins/service_/services/docker.py
src/middlewared/middlewared/test/integration/utils/docker.py
tests/api2/test_docker_setup.py

This PR adds basic docker configuration tests where we setup docker and make sure all the required datasets have required properties in place. While at it, some optimization has also been done to reduce number of `catalog.sync` calls going on because they were just redundant.

NAS-131351 / 25.04 / Add basic docker configuration integration tests

---

src/middlewared/middlewared/main.py

It is called from `notify_postinit` which is not an async function

NAS-131337 / 25.04 / Make `_setup_periodic_tasks` thread-safe

---

src/middlewared/middlewared/main.py

It is called from `notify_postinit` which is not an async function
Original PR: https://github.com/truenas/middleware/pull/14560
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131337

NAS-131337 / 24.10.0 / Make `_setup_periodic_tasks` thread-safe (by themylogin)

---

src/middlewared/middlewared/plugins/cloud_backup/restic.py
tests/api2/test_cloud_backup.py

This cache was neither used previously nor necessary (we don't retrieve same files from the backup constantly)

NAS-131318 / 25.04 / Get rid of `unable to open cache: unable to locate cache directory: neither $XDG_CACHE_HOME nor $HOME are defined`

---

src/middlewared/middlewared/plugins/directoryservices_/kerberos_health_mixin.py

Ensure that failed lookup of kerberos credential allows for us to perform kerberos recovery steps rather than simply erroring out.
Original PR: https://github.com/truenas/middleware/pull/14565
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131368

NAS-131368 / 24.10.0 / raise correct exception when doing krb5 health check (by anodos325)

---

debian/debian/ix-reboot.service
debian/debian/rules
src/freenas/usr/local/bin/scst_util.sh
src/middlewared/middlewared/plugins/failover_/event.py

git cherry-pick -x e9bdff159579b23044f4f82d59c9a17df90d6d6e
git cherry-pick -x 3d377965639fa9d428ef25a1904d6e72420341f3
git cherry-pick -x 778e91057e2172a9d76312e7f09d6d8273abb961
Turn off any ALUA `cluster_mode` _**_before_**_ stopping _middlewared_ on reboot or shutdown.
Original PR: https://github.com/truenas/middleware/pull/14520
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131186
Original PR: https://github.com/truenas/middleware/pull/14536
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131186

NAS-131186 / 24.04.2.3 / Add stop-alua to scst_util.sh and call before stopping middlewared (by bmeagherix) (by bugclerk)

---

src/middlewared/middlewared/plugins/reporting/netdata/graphs.py

When the UPS service is started after a long period, null values distort the mean calculation because they are included in the average. Furthermore, for datasets larger than 3000 points, Netdata reduces the number of points by creating 3000 groups and calculating the average for each group to get single datapoint. Null values affect the accuracy of these group calculations as well.
Skip all zero values when calculating the mean and use the median to represent a single data point in a group if Netdata has more than 3000 data points. This will ensure more accurate aggregation.

NAS-131115 / 25.04 / Fix null data points in UPS stats

---

src/middlewared/middlewared/plugins/reporting/netdata/graphs.py

When the UPS service is started after a long period, null values distort the mean calculation because they are included in the average. Furthermore, for datasets larger than 3000 points, Netdata reduces the number of points by creating 3000 groups and calculating the average for each group to get single datapoint. Null values affect the accuracy of these group calculations as well.
Skip all zero values when calculating the mean and use the median to represent a single data point in a group if Netdata has more than 3000 data points. This will ensure more accurate aggregation.
Original PR: https://github.com/truenas/middleware/pull/14572
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131115

NAS-131115 / 24.10.0 / Fix null data points in UPS stats (by Qubad786)

---

src/middlewared/middlewared/plugins/directoryservices_/activedirectory_health_mixin.py

It is theoretically possible that the smb.conf file is not properly configured for AD causing health check to ping_dc to fail. This commit adds a potential recovery step where we regenerate the smb.conf and restart winbindd.

NAS-131379 / 25.04 / Add recovery step for case where we fail to ping_dc

---

src/middlewared/middlewared/plugins/directoryservices_/activedirectory_health_mixin.py

It is theoretically possible that the smb.conf file is not properly configured for AD causing health check to ping_dc to fail. This commit adds a potential recovery step where we regenerate the smb.conf and restart winbindd.
Original PR: https://github.com/truenas/middleware/pull/14571
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131379

NAS-131379 / 24.10.0 / Add recovery step for case where we fail to ping_dc (by anodos325)

---

tests/api2/test_262_iscsi_alua.py

Recent PR (#14546) added a required `reason` parameter to `system.reboot`.
The call location in this PR was missed in that PR: add a reason.

NAS-131398 / 25.04 / Add reason to call to system.reboot in ALUA test

---

src/middlewared/middlewared/utils/filesystem/copy.py
tests/unit/test_copytree.py

This commit ensures that our copytree preserves xattrs, acls, timestamp, etc from source directory on target directory. An explicit test for this is added as well.

NAS-131406 / 25.04 / Ensure that we preserve metadata on root directory

---

src/middlewared/middlewared/pytest/unit/utils/test_copytree.py
src/middlewared/middlewared/utils/filesystem/copy.py

This commit ensures that our copytree preserves xattrs, acls, timestamp, etc from source directory on target directory. An explicit test for this is added as well.
Original PR: https://github.com/truenas/middleware/pull/14580
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131406

NAS-131406 / 24.10.0 / Ensure that we preserve metadata on root directory (by anodos325)

---

src/middlewared/middlewared/plugins/cloud_sync.py
src/middlewared/middlewared/rclone/remote/storjix.py
tests/api2/test_cloud_sync_storj.py

Currently the returned `CallError` is "An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid." To save the user some research, we can clarify this message to the `ValidationError` "Bucket name can only contain lowercase letters, numbers, and hyphens" which is verbatim in the [storj documentation](https://storj.dev/support/object-browser#:~:text=The%20bucket%20name%20can%20only%20contain%20lowercase%20letters%2C%20numbers%2C%20and%20hyphens.) or "The bucket name must be between 3-63 characters in length and cannot contain uppercase."
[s3 bucket naming rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) (we do not enforce them all!)
We should ask UI to render these errors as red validation text as …

NAS-131330 / 25.04 / Better error handling for bad storj bucket name

---

src/middlewared/middlewared/plugins/service_/services/docker.py

This commit adds changes to bump docker start timeout to 120 secs because docker on HDDs can take some time to initialize, even this is not fool proof but after discussing with Caleb we have decided to bump this for now.

NAS-131400 / 25.04 / Bump docker service start timeout to 120 secs

---

src/middlewared/middlewared/plugins/reporting/netdata_configure.py
src/middlewared/middlewared/plugins/sysdataset.py
tests/api2/test_system_dataset.py

When system dataset is being migrated, if we have a pool from where it i being migrated - we are temporarily mounting it to another location before it is mounted at it's rightful place so we can copy over data.
However during this transition, we have post mount actions being executed which is not alright and can trigger different failures which in the case i ended up finding this was an issue related to netdata setup not being properly executed.
Ensure all post mount actions only when the system dataset is mounted at it's rightful place i.e `/var/db/system`. Additionally, permissions for ix-state directory in netdata are corrected if any exception occurs on the first time system tries to setup netdata.

NAS-131370 / 25.04 / Fix post mount actions execution on system dataset setup

---

src/middlewared/middlewared/plugins/reporting/netdata_configure.py
src/middlewared/middlewared/plugins/sysdataset.py
tests/api2/test_system_dataset.py

When system dataset is being migrated, if we have a pool from where it i being migrated - we are temporarily mounting it to another location before it is mounted at it's rightful place so we can copy over data.
However during this transition, we have post mount actions being executed which is not alright and can trigger different failures which in the case i ended up finding this was an issue related to netdata setup not being properly executed.
Ensure all post mount actions only when the system dataset is mounted at it's rightful place i.e `/var/db/system`. Additionally, permissions for ix-state directory in netdata are corrected if any exception occurs on the first time system tries to setup netdata.
Original PR: https://github.com/truenas/middleware/pull/14567
Jira URL: …

NAS-131370 / 24.10.0 / Fix post mount actions execution on system dataset setup (by Qubad786)

---

src/freenas/etc/modprobe.d/blacklist-qla2xxx.conf
src/freenas/etc/modprobe.d/qla2xxx_scst.conf

We will use the SCST provided `qla2xxx_scst` kernel module for Fibre Channel target, rather than the upstream kernel `qla2xxx` module.  Further, do **not** use it in initiator mode.

NAS-131422 / 25.04 / Choose qla2xxx_scst kernel module for FC target

---

tests/unit/test_fenced.py

Use the load_disks_impl function in the fenced unit test. This function is the entry point for loading disks.

NAS-131431 / 25.04 / use load_disks_impl in fenced unit test

---

src/middlewared/middlewared/alert/source/enclosure_status.py

Starting in FT, most everyone has migrated over to using the new enclosure plugin. However, we still have some straggling code using the old enclosure logic. This updates the enclosure alert to use the new enclosure plugin.
Summary of what was done:
1. remove the legacy z-series hardware checks (this platform has been EOL for years and we no longer provide support on it at all)
2. update the logic to use the new enclosure plugin (NOTE: using a frozen dataclass since it's much more memory efficient and we're caching all bad elements on the class during runtime)
3. use a bit of type annotations and clarify variable names to make it more human readable
4. fix the formatting of the file while i'm here

NAS-131446 / 25.04 / Fix enclosure alert

---

tests/unit/test_copytree.py

We need to set mtime after generating our test data otherwise we get invalid results.

NAS-131447 / 25.04 / Fix source directory utime in unit test

---

src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py

The slot mapping for the R20/R20B platforms were very clearly copy and pasted incorrectly because they have the same mapping as the R20A. QE has tested drive identify logic on an R20B and the lights are way off. This should fix it.

NAS-131420 / 25.04 / fix copy/paste error for r20/r20b slot mapping

---

src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py

The slot mapping for the R20/R20B platforms were very clearly copy and pasted incorrectly because they have the same mapping as the R20A. QE has tested drive identify logic on an R20B and the lights are way off. This should fix it.
Original PR: https://github.com/truenas/middleware/pull/14598
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131420

NAS-131420 / 24.10.0 / fix copy/paste error for r20/r20b slot mapping (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure.py
src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/failover_/event.py

This method is unnecessary. It's clearing identify/fault lights on ALL disks based on certain zpool events and/or on failover event. That's a POLA violation since the user explicitly turns on these lights. They shouldn't automatically get turned off based on certain events. (We've already discussed a similar POLA violation surrounding this logic in UI awhile ago. So this brings us in line with how our UI behaves as well.)

NAS-131457 / 25.04 / remove enclosure.sync_zpool

---

src/middlewared/middlewared/plugins/system/product.py

Remove some obsolete code in `system.feature_enabled`.  No longer need to check for CORE in SCALE codebase.  (Wasteful)

NAS-131470 / 25.04 / No longer need to check wrt CORE in SCALE codebase

---

src/middlewared/middlewared/plugins/disk_/format.py

This reverts commit 967a2962d0c2a5804e6bb4db55d86eea9c3ebae2 because the RC candidates are not considered enterprise ready.

NAS-131572 / 24.10-RC.2 / Revert "fix libparted IO operation on disk format (#14613)"

---

src/middlewared/middlewared/alembic/versions/24.10/2024-09-03_20-33_docker_addr_pool.py
src/middlewared/middlewared/alembic/versions/24.10/2024-10-03_20-46_docker_address_pool.py
src/middlewared/middlewared/plugins/docker/update.py

This PR adds changes to update default docker address pool to use what docker uses but instead of having a size of `16` for each docker network, we use `24` so user can still get to consume at least 4096 docker networks this way.
Problem with earlier default was that users who were using apps in BETA and had 15 number of apps installed, each docker network was huge with a size of `16` which meant users could only create `15` apps with the default docker addr pool before it started consuming `192.168.0.0/16`. Then we made the change to use a smaller size per docker network and using base as `172.30/31.0.0/16` which was fine but the problem was users having 15 apps were already consuming this addr pool which resulted in docker exhausting all addr pools and refusing to start.
The current …

NAS-131485 / 24.10-RC.2 / Update default docker address pool (by sonicaj)

---

src/middlewared/middlewared/alembic/versions/24.10/2024-09-03_20-33_docker_addr_pool.py
src/middlewared/middlewared/alembic/versions/24.10/2024-10-03_20-46_docker_address_pool.py
src/middlewared/middlewared/plugins/docker/update.py

This PR adds changes to update default docker address pool to use what docker uses but instead of having a size of `16` for each docker network, we use `24` so user can still get to consume at least 4096 docker networks this way.
Problem with earlier default was that users who were using apps in BETA and had 15 number of apps installed, each docker network was huge with a size of `16` which meant users could only create `15` apps with the default docker addr pool before it started consuming `192.168.0.0/16`. Then we made the change to use a smaller size per docker network and using base as `172.30/31.0.0/16` which was fine but the problem was users having 15 apps were already consuming this addr pool which resulted in docker exhausting all addr pools and refusing to start.
The current …

NAS-131485 / 24.10.0 / Update default docker address pool

---

src/middlewared/middlewared/alembic/versions/24.10/2024-09-03_20-33_docker_addr_pool.py
src/middlewared/middlewared/alembic/versions/24.10/2024-10-03_20-46_docker_address_pool.py
src/middlewared/middlewared/alembic/versions/25.04/2024-10-04_00-45_merge.py
src/middlewared/middlewared/plugins/docker/update.py

This PR adds changes to update default docker address pool to use what docker uses but instead of having a size of `16` for each docker network, we use `24` so user can still get to consume at least 4096 docker networks this way.
Problem with earlier default was that users who were using apps in BETA and had 15 number of apps installed, each docker network was huge with a size of `16` which meant users could only create `15` apps with the default docker addr pool before it started consuming `192.168.0.0/16`. Then we made the change to use a smaller size per docker network and using base as `172.30/31.0.0/16` which was fine but the problem was users having 15 apps were already consuming this addr pool which resulted in docker exhausting all addr pools and refusing to start.
The current …

NAS-131485 / 25.04 / Update default docker address pool (by sonicaj)

---

src/freenas/usr/local/libexec/disable-rootfs-protection
src/middlewared/middlewared/alert/base.py
src/middlewared/middlewared/alert/source/auth.py
src/middlewared/middlewared/alert/source/enclosure_status.py
src/middlewared/middlewared/alert/source/failover.py
src/middlewared/middlewared/alert/source/failover_disks.py
src/middlewared/middlewared/alert/source/failover_interfaces.py
src/middlewared/middlewared/alert/source/failover_nics.py
src/middlewared/middlewared/alert/source/failover_remote_inaccessible.py
src/middlewared/middlewared/alert/source/failover_sync.py
src/middlewared/middlewared/alert/source/jbof.py
src/middlewared/middlewared/alert/source/legacy_mini_bmc.py
src/middlewared/middlewared/alert/source/license_status.py
src/middlewared/middlewared/alert/source/memory_errors.py
src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py
src/middlewared/middlewared/alert/source/proactive_support.py
src/middlewared/middlewared/alert/source/sata_dom_wear.py
src/middlewared/middlewared/alert/source/sensors.py
src/middlewared/middlewared/alert/source/usb_storage.py
src/middlewared/middlewared/plugins/account_/2fa.py
src/middlewared/middlewared/plugins/catalog/update.py
src/middlewared/middlewared/plugins/disk.py
src/middlewared/middlewared/plugins/failover_/fenced.py
src/middlewared/middlewared/plugins/mail.py
src/middlewared/middlewared/plugins/system/product.py
src/middlewared/middlewared/test/integration/assets/product.py
src/middlewared/middlewared/utils/__init__.py

--------------------
The product types, 'SCALE' and 'SCALE_ENTERPRISE' are not defined anywhere.  We test for the product type in many places, each time using a hard-coded string. 
This presents two problems:  Increased possibility of typos and missing a single source of truth for the product type identifier.
-------------------
Add a product type class, 'ProductType' to `system/product.py`.
Replace the hard-coded strings with the class variables.
Note: The enum class was not used solely because it required appending `.value` to the name.
Also fixed various minor flake8 issues.

NAS-131582 / 25.04 / Replace usage of hard-coded strings for the product type

---

src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py

This commit adds changes so that for any app which fails to deploy after migration, we don't consider it as unsuccessfully migrated because migration actually means that app migrated from k8s to docker perfectly - not that it is running healthy in docker. That is a separate issue and will be tackled as such. For example for any such app, if the migration is re-triggered - it is not going to try and migrate the app again because it has already been migrated successfully to docker.

NAS-131597 / 25.04 / Consider app is migrated even if it fails to deploy after migration

---

src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py

This commit adds changes so that for any app which fails to deploy after migration, we don't consider it as unsuccessfully migrated because migration actually means that app migrated from k8s to docker perfectly - not that it is running healthy in docker. That is a separate issue and will be tackled as such. For example for any such app, if the migration is re-triggered - it is not going to try and migrate the app again because it has already been migrated successfully to docker.
Original PR: https://github.com/truenas/middleware/pull/14623
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131597

NAS-131597 / 24.10.0 / Consider app is migrated even if it fails to deploy after migration (by sonicaj)

---

src/middlewared/middlewared/api/v25_04_0/acme_protocol.py

The new api style definition in `acme_protocol.py` (see https://github.com/truenas/middleware/pull/14600) caused a pydantic warning due to the model I defined having an attribute named `schema` which conflicts with an attribute of pydantic's `BaseModel` class.
The fix here is the same as it would be for any field having a reserved keyword name which is to define the name as an alias using `Field`.

NAS-131616 / 25.04 / Fix `UserWarning: Field name "schema" in "DNSAuthenticatorSchemaEntry"...` on login

---

src/middlewared/middlewared/plugins/alert.py

The previous PR https://github.com/truenas/middleware/pull/14615 broke our cli by changing what the alertclasses.update endpoint accepts.

NAS-131659 / 25.04 / fix `AlertClassesUpdateArgs`

---

src/middlewared/middlewared/alembic/versions/25.04/2024-10-04_18-09_add_nfs_rdma.py
src/middlewared/middlewared/etc_files/nfs.conf.d/local.conf.mako
src/middlewared/middlewared/plugins/nfs.py
src/middlewared/middlewared/validators.py
tests/api2/test_300_nfs.py

This PR allows a TrueNAS SCALE Enterprise server  with an RDMA NIC to be configured to support NFS over RDMA.
Enabling RDMA is restricted to Enterprise licensed servers with an RDMA capable NIC installed.
- Extend the NFS configuration database with an NFS 'rdma' configuration setting. 
- Update the NFS config mako to include RDMA configuration when requested. 
- Update the NFS plugin to support the new 'rdma' setting. 
- Update the 'Port' validator to include an optional exclude list. Update the CI port test.
More testing and tests will follow.

NAS-131091 / 25.04 / Enable NFS over RDMA

---

src/middlewared/middlewared/plugins/apps/app_scale.py
src/middlewared/middlewared/plugins/apps/events.py
src/middlewared/middlewared/plugins/apps/ix_apps/utils.py
src/middlewared/middlewared/plugins/apps/utils.py

Some apps when they are being stopped, we report `CRASHED` state for them. `CRASHED` state for us when we have containers available but they have exited.
There isn't a clean way to address this as we are not getting relevant details from docker wrt this so we can determine that a container is in a stopping state and we then appropriately address the case - so what has been done is that we temporarily add a cache key to suppress events for that app when it is being stopped and send STOPPING/STOPPED event manually.

NAS-131574 / 25.04 / Don't report crashed state when stopping an app

---

src/middlewared/middlewared/plugins/apps/app_scale.py
src/middlewared/middlewared/plugins/apps/events.py
src/middlewared/middlewared/plugins/apps/ix_apps/utils.py
src/middlewared/middlewared/plugins/apps/utils.py

Some apps when they are being stopped, we report `CRASHED` state for them. `CRASHED` state for us when we have containers available but they have exited.
There isn't a clean way to address this as we are not getting relevant details from docker wrt this so we can determine that a container is in a stopping state and we then appropriately address the case - so what has been done is that we temporarily add a cache key to suppress events for that app when it is being stopped and send STOPPING/STOPPED event manually.
Original PR: https://github.com/truenas/middleware/pull/14630
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131574

NAS-131574 / 24.10.0 / Don't report crashed state when stopping an app (by Qubad786)

---

src/freenas/etc/systemd/system/docker.service.d/override.conf

This PR restores IPv6 connectivity in VMs when enabling Docker. 
It's basically the same as the following PR, but for IPv6:
- https://github.com/truenas/middleware/pull/14338 by @Qubad786
The fix was confirmed working on TrueNAS Scale 24.10-RC.1 and 24.10-RC.2 systems.
The PR targets master / 25.04, but it should also really be backported to 24.10.
---
JIRA URL: https://ixsystems.atlassian.net/browse/NAS-131573
See both of my recent comments in the JIRA ticket for more details on the underlying issue: [comment 1](https://ixsystems.atlassian.net/browse/NAS-131573?focusedCommentId=279491), [comment 2](https://ixsystems.atlassian.net/browse/NAS-131573?focusedCommentId=279494).
This is the Moby GitHub issue tracking the underlying bug:
- https://github.com/moby/moby/issues/48365
---
Like …

NAS-131573 / 25.04 / Default to accept policy for IPv6 forward chain

---

src/freenas/etc/systemd/system/docker.service.d/override.conf

This PR restores IPv6 connectivity in VMs when enabling Docker. 
It's basically the same as the following PR, but for IPv6:
- https://github.com/truenas/middleware/pull/14338 by @Qubad786
The fix was confirmed working on TrueNAS Scale 24.10-RC.1 and 24.10-RC.2 systems.
The PR targets master / 25.04, but it should also really be backported to 24.10.
---
JIRA URL: https://ixsystems.atlassian.net/browse/NAS-131573
See both of my recent comments in the JIRA ticket for more details on the underlying issue: [comment 1](https://ixsystems.atlassian.net/browse/NAS-131573?focusedCommentId=279491), [comment 2](https://ixsystems.atlassian.net/browse/NAS-131573?focusedCommentId=279494).
This is the Moby GitHub issue tracking the underlying bug:
- https://github.com/moby/moby/issues/48365
---
Like …

NAS-131573 / 24.10.0 / Default to accept policy for IPv6 forward chain (by TheJulianJES)

---

src/middlewared/middlewared/plugins/pool_/dataset.py
src/middlewared/middlewared/plugins/zfs_/dataset.py
tests/api2/test_427_smb_acl.py

The xattr parameter was initially exposed to end-users to allow option to set what was at the time a new-ish ZFS feature to store xattrs in sa instead of xattr directory. Since this time we've changed the default and there is no longer a reason to allow setting the legacy DIR mode. This allows us to be agnostic as to upstream OpenZFS changes regarding the defaults for the xattr property and meaning of "on".

NAS-131685 / 25.04 / Remove xattr from available dataset properties

---

src/middlewared/middlewared/plugins/pool_/dataset.py
src/middlewared/middlewared/plugins/zfs_/dataset.py
tests/api2/test_427_smb_acl.py

The xattr parameter was initially exposed to end-users to allow option to set what was at the time a new-ish ZFS feature to store xattrs in sa instead of xattr directory. Since this time we've changed the default and there is no longer a reason to allow setting the legacy DIR mode. This allows us to be agnostic as to upstream OpenZFS changes regarding the defaults for the xattr property and meaning of "on".
Original PR: https://github.com/truenas/middleware/pull/14636
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131685

NAS-131685 / 24.10.0 / Remove xattr from available dataset properties (by anodos325)

---

src/middlewared/middlewared/plugins/zfs_/pool_status.py

The current `zpool status` is incorrectly handling the "replacing" vdev type, which appears only during an ongoing resilvering process. This is causing a "path not found" key error, as it treats the replacing vdev as a regular vdev.
Updated `zpool status` to properly handle and manage the "replacing" vdev type during resilvering, preventing key errors.

NAS-131547 / 25.04 / Appropriately handle resilvering case with zpool status report

---

src/middlewared/middlewared/plugins/zfs_/pool_status.py

The current `zpool status` is incorrectly handling the "replacing" vdev type, which appears only during an ongoing resilvering process. This is causing a "path not found" key error, as it treats the replacing vdev as a regular vdev.
Updated `zpool status` to properly handle and manage the "replacing" vdev type during resilvering, preventing key errors.
Original PR: https://github.com/truenas/middleware/pull/14639
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131547

NAS-131547 / 24.10.0 / Appropriately handle resilvering case with zpool status report (by Qubad786)

---

src/middlewared/middlewared/plugins/directoryservices_/activedirectory_join_mixin.py

During multi-dc testing in preparation to cutover to new CI domain it was observed that delayed sysvol replication after a fresh join could cause our post-join setup step in which we regenerate the krb5.conf and perform kinit with the AD machine account keytab could fail due to us talking to a DC that had not received updated account information yet. This commit changes the order of operations when we activate AD so that we first wait for winbindd to mark the domain as ONLINE before we try to set up kerberos.

NAS-131697 / 25.04 / Fix domain join with multiple DCs

---

src/middlewared/middlewared/plugins/directoryservices_/activedirectory_join_mixin.py

During multi-dc testing in preparation to cutover to new CI domain it was observed that delayed sysvol replication after a fresh join could cause our post-join setup step in which we regenerate the krb5.conf and perform kinit with the AD machine account keytab could fail due to us talking to a DC that had not received updated account information yet. This commit changes the order of operations when we activate AD so that we first wait for winbindd to mark the domain as ONLINE before we try to set up kerberos.
Original PR: https://github.com/truenas/middleware/pull/14643
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131697

NAS-131697 / 24.10.0 / Fix domain join with multiple DCs (by anodos325)

---

src/middlewared/middlewared/plugins/enclosure_/ses_enclosures2.py
src/middlewared/middlewared/plugins/failover_/detect_enclosure.py

Remove the call to the legacy endpoint in the failover enclosure detection plugin. This makes changes so we can use the `Enclosure` class that already takes care of doing a bunch of identification. This allows us to use properties like `is_mseries` or `is_xseries` accordingly. Tested on both m60 and x20 with no regressions.

NAS-131467 / 25.04 / remove call to enclosure.list_ses_enclosures

---

src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py

Worked with platform team on an internal R50BM that was experiencing enclosure problems. Found that I had copy and pasted the rear nvme drive bay logic from the M30 which doesn't apply to the R50 series. The m-series have 24 front drive bays and 4 rear nvmes while the R50 series has 48 top loaded drives plus 2,3 and 4 rear nvme drives. This fixes the typo and I confirmed fixes the issue that was being experienced.

NAS-131717 / 25.04 / fix r50 series nvme enclosure maps

---

src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py

Worked with platform team on an internal R50BM that was experiencing enclosure problems. Found that I had copy and pasted the rear nvme drive bay logic from the M30 which doesn't apply to the R50 series. The m-series have 24 front drive bays and 4 rear nvmes while the R50 series has 48 top loaded drives plus 2,3 and 4 rear nvme drives. This fixes the typo and I confirmed fixes the issue that was being experienced.
Original PR: https://github.com/truenas/middleware/pull/14651
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131717

NAS-131717 / 24.10.0 / fix r50 series nvme enclosure maps (by yocalebo)

---

tests/api2/test_300_nfs.py

Some NFS CI tests have started failing.
It _appears_ a reset of the restart counters might fix the recent CI test failures.
Also removed an inappropriate bind_ip test.

NAS-131719 / 25.04 / Fix NFS CI tests

---

src/middlewared/middlewared/plugins/docker/update.py
tests/api2/test_docker_setup.py

This PR fixes a case which is only valid for FT that when address pool property is changed, we are not mounting docker datasets again. An integration test has been added to this end as well to make sure we catch such cases sooner.

NAS-131704 / 25.04 / Make sure docker datasets are mounted if address pools are changed only

---

src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
src/middlewared/middlewared/plugins/enclosure_/nvme2.py
src/middlewared/middlewared/plugins/enclosure_/ses_enclosures2.py
src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py
src/middlewared/middlewared/plugins/failover_/detect_enclosure.py

We do not have a MINI 3.0 X version 1.0 internally to test these changes on, however, we do have a non-version 1.0 which is essentially the same device just cabled so slightly differently.
I have added the mapping based on physically identifying drives on the non-version 1.0 and working backwards from there. Most of the changes here are related to 2 changes:
1. updating docstrings to reflect reality
2. removing the need to pass the `dmi` object around. Instead I use our dedicated `ixhardware` module (which does the exact same thing but provides me the ability to access the `system_version` buffer which is needed for the mini 3.0 x version 1.0 platform.
I have tested these changes on (with no regressions):
1. m60 with 12x ES102's connected
3. mini 3.0 x (NON version 1.0)
4. random hardware …

NAS-131305 / 25.04 / fix MINI 3.0 X (vers 1.0) drive mapping

---

src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
src/middlewared/middlewared/plugins/enclosure_/nvme2.py
src/middlewared/middlewared/plugins/enclosure_/ses_enclosures2.py
src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py

We do not have a MINI 3.0 X version 1.0 internally to test these changes on, however, we do have a non-version 1.0 which is essentially the same device just cabled so slightly differently.
I have added the mapping based on physically identifying drives on the non-version 1.0 and working backwards from there. Most of the changes here are related to 2 changes:
1. updating docstrings to reflect reality
2. removing the need to pass the `dmi` object around. Instead I use our dedicated `ixhardware` module (which does the exact same thing but provides me the ability to access the `system_version` buffer which is needed for the mini 3.0 x version 1.0 platform.
I have tested these changes on (with no regressions):
1. m60 with 12x ES102's connected
3. mini 3.0 x (NON version 1.0)
4. random hardware …

NAS-131305 / 24.10.0 / fix MINI 3.0 X (vers 1.0) drive mapping (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
src/middlewared/middlewared/plugins/enclosure_/nvme2.py
src/middlewared/middlewared/plugins/enclosure_/ses_enclosures2.py
src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py

We do not have a MINI 3.0 X version 1.0 internally to test these changes on, however, we do have a non-version 1.0 which is essentially the same device just cabled so slightly differently.
I have added the mapping based on physically identifying drives on the non-version 1.0 and working backwards from there. Most of the changes here are related to 2 changes:
1. updating docstrings to reflect reality
2. removing the need to pass the `dmi` object around. Instead I use our dedicated `ixhardware` module (which does the exact same thing but provides me the ability to access the `system_version` buffer which is needed for the mini 3.0 x version 1.0 platform.
I have tested these changes on (with no regressions):
1. m60 with 12x ES102's connected
3. mini 3.0 x (NON version 1.0)
4. random hardware …

NAS-131305 / 24.10.1 / fix MINI 3.0 X (vers 1.0) drive mapping (by yocalebo) (by bugclerk)

---

src/middlewared/middlewared/test/integration/utils/docker.py
tests/api2/test_006_pool_and_sysds.py

In OpenZFS 2.3 the meaning of xattr=on changed from dir to sa which means that "ON" is now the expected value for the top-level dataset of a new zpool.

NAS-131749 / 25.04 / update test for xattr=on changes

---

src/middlewared/middlewared/plugins/smb.py
src/middlewared/middlewared/plugins/smb_/util_smbconf.py
src/middlewared/middlewared/pytest/unit/plugins/test_smb.py

Enable SMB parameters required for support of VEEAM fast copy if TrueNAS is enterprise-licensed. SMB protocol functional tests will be added in followup commit.

NAS-131750 / 25.04 / Add middleware backend support for SMB fast copy

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/datastore/read.py
src/middlewared/middlewared/test/integration/assets/account.py

It seems that the original code for updating user-group relationships (that was never touched since it was written in 2017) contains an error:
https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/account.py#L1367
`gms` is an array of `account.bsdgroupmembership` objects, so `gm["id"]` has a Row ID type for `account.bsdgroupmembership` table. `groups` is an array of Row IDs for `account.bsdgroup` table. `gm['id'] not in groups` check has no sense, it compares Row IDs of different tables.
This is probably the root cause of a rare bug where the following code
```
from truenas_api_client import Client
c = Client()
while True:
user = c.call('user.query', [['username', '=', 'smbuser']], {'get': True})
pk = c.call('user.update', user['id'], …
```

NAS-131456 / 25.04 / Update user-group memberships using datastore

---

tests/api2/test_system_settings_roles.py

We have an integration test to test role of `system.advanced.update_gpu_pci_ids` which basically when called updates initramfs as well and this potentially times out in our CI pipeline.
There is no actual need to call the endpoint when we can check the roles without actually getting the endpoint to work. The common utility we have in place already handles this nicely where the role is asserted without actually getting the endpoint to execute because role based exceptions should be raised before the method is actually executed.

NAS-131748 / 25.04 / Make sure isolated gpu roles test don't timeout

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/datastore/read.py
src/middlewared/middlewared/test/integration/assets/account.py

It seems that the original code for updating user-group relationships (that was never touched since it was written in 2017) contains an error:
https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/account.py#L1367
`gms` is an array of `account.bsdgroupmembership` objects, so `gm["id"]` has a Row ID type for `account.bsdgroupmembership` table. `groups` is an array of Row IDs for `account.bsdgroup` table. `gm['id'] not in groups` check has no sense, it compares Row IDs of different tables.
This is probably the root cause of a rare bug where the following code
```
from truenas_api_client import Client
c = Client()
while True:
user = c.call('user.query', [['username', '=', 'smbuser']], {'get': True})
pk = c.call('user.update', user['id'], …
```

NAS-131456 / 24.10.1 / Update user-group memberships using datastore (by themylogin)

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/datastore/read.py
src/middlewared/middlewared/test/integration/assets/account.py

It seems that the original code for updating user-group relationships (that was never touched since it was written in 2017) contains an error:
https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/account.py#L1367
`gms` is an array of `account.bsdgroupmembership` objects, so `gm["id"]` has a Row ID type for `account.bsdgroupmembership` table. `groups` is an array of Row IDs for `account.bsdgroup` table. `gm['id'] not in groups` check has no sense, it compares Row IDs of different tables.
This is probably the root cause of a rare bug where the following code
```
from truenas_api_client import Client
c = Client()
while True:
user = c.call('user.query', [['username', '=', 'smbuser']], {'get': True})
pk = c.call('user.update', user['id'], …
```

NAS-131456 / 24.10.0 / Update user-group memberships using datastore (by themylogin)

---

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py

Don't pollute the webUI with tracebacks for an edge-case crash. Catch the exception and log it instead.

NAS-131778 / 25.04 / handle edge-case crash for nvdimm alert

---

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py

Don't pollute the webUI with tracebacks for an edge-case crash. Catch the exception and log it instead.
Original PR: https://github.com/truenas/middleware/pull/14672
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131778

NAS-131778 / 24.10.0 / handle edge-case crash for nvdimm alert (by yocalebo)

---

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py

Don't pollute the webUI with tracebacks for an edge-case crash. Catch the exception and log it instead.
Original PR: https://github.com/truenas/middleware/pull/14672
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131778

NAS-131778 / 24.10.1 / handle edge-case crash for nvdimm alert (by yocalebo)

---

src/middlewared/middlewared/job.py

This is especially painful in debug: if a job returns an invalid result, we lose the results of all other jobs.

NAS-131772 / 25.04 / Fix entire `core.get_jobs` crashing if one job fails to dump its result

---

src/middlewared/middlewared/plugins/enclosure_/r30_drive_identify.py

Clarification (and updates to internal documentation) from the platform team helped resolved the issue with identifying drives on the R30 platform. These commands need to always be ran.

NAS-131568 / 25.04 / fix drive identify on R30

---

src/middlewared/middlewared/job.py

This is especially painful in debug: if a job returns an invalid result, we lose the results of all other jobs.
Original PR: https://github.com/truenas/middleware/pull/14614
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131772

NAS-131772 / 24.10.0 / Fix entire `core.get_jobs` crashing if one job fails to dump its result (by themylogin)

---

src/middlewared/middlewared/plugins/enclosure_/r30_drive_identify.py

Clarification (and updates to internal documentation) from the platform team helped resolved the issue with identifying drives on the R30 platform. These commands need to always be ran.
Original PR: https://github.com/truenas/middleware/pull/14662
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131568

NAS-131568 / 24.10.1 / fix drive identify on R30 (by yocalebo)

---

src/middlewared/middlewared/job.py

This is especially painful in debug: if a job returns an invalid result, we lose the results of all other jobs.
Original PR: https://github.com/truenas/middleware/pull/14614
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131772

NAS-131772 / 24.10.1 / Fix entire `core.get_jobs` crashing if one job fails to dump its result (by themylogin)

---

src/middlewared/middlewared/main.py

Invalid calls were possible and this created a confusion https://ixsystems.atlassian.net/browse/NAS-131689
Original PR: https://github.com/truenas/middleware/pull/14680
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131782

NAS-131782 / 24.10.1 / Check `params` type (by themylogin)

---

src/middlewared/middlewared/plugins/disk_/retaste.py
src/middlewared/middlewared/plugins/failover_/event.py

A couple issues have been found internally surrounding SED drives and how we unlock them. This is SCALE specific and so after consultation with the OS team, we're trying to implement changes which fix these problems.
1. On MASTER failover event, notify the standby controller to retaste the disks after we unlock any SED drives
2. On BACKUP failover event, retaste the disks to ensure we're "up to date" with partition information
3. Change the `disk.retaste` job to only queue up 1 job (including the currently running job)
4. stop using `libudev` in the `disk.retaste` endpoint since the udev database can be in flux by the time we query it. Instead we'll use device node names in `/dev`.
Original PR: https://github.com/truenas/middleware/pull/14690
Jira URL: …

NAS-129366 / 24.10.1 / Try to fix SED unlock issues on HA SCALE (by yocalebo)

---

src/middlewared/middlewared/plugins/apps/ix_apps/query.py
src/middlewared/middlewared/plugins/apps/ix_apps/utils.py

This PR aims to improve how we report in what state the app is in right now. Before we get to what we are doing in this PR, some context here - so when we have a compose file which has multiple dependencies, the services dependent on the service running right now won't start unless the service they depend on finishes gracefully - in this case docker does create containers for these services which are waiting to start but does not actually start them.
What was happening with our earlier logic was that when we started an app - we reported it as deploying -> crashed -> deploying -> running (for some apps), this happened because there were some dependencies involved and when 1 dependency finished executing, there wasn't another container running atm and we marked it as crashed which is …

NAS-131763 / 25.04 / Improve app status reporting

---

src/middlewared/middlewared/plugins/apps/ix_apps/query.py
src/middlewared/middlewared/plugins/apps/ix_apps/utils.py

This PR aims to improve how we report in what state the app is in right now. Before we get to what we are doing in this PR, some context here - so when we have a compose file which has multiple dependencies, the services dependent on the service running right now won't start unless the service they depend on finishes gracefully - in this case docker does create containers for these services which are waiting to start but does not actually start them.
What was happening with our earlier logic was that when we started an app - we reported it as deploying -> crashed -> deploying -> running (for some apps), this happened because there were some dependencies involved and when 1 dependency finished executing, there wasn't another container running atm and we marked it as crashed which is …

NAS-131763 / 24.10.0 / Improve app status reporting (by sonicaj)

---

src/middlewared/middlewared/plugins/apps/ix_apps/query.py
src/middlewared/middlewared/plugins/apps/ix_apps/utils.py

This PR aims to improve how we report in what state the app is in right now. Before we get to what we are doing in this PR, some context here - so when we have a compose file which has multiple dependencies, the services dependent on the service running right now won't start unless the service they depend on finishes gracefully - in this case docker does create containers for these services which are waiting to start but does not actually start them.
What was happening with our earlier logic was that when we started an app - we reported it as deploying -> crashed -> deploying -> running (for some apps), this happened because there were some dependencies involved and when 1 dependency finished executing, there wasn't another container running atm and we marked it as crashed which is …

NAS-131763 / 24.10.1 / Improve app status reporting (by sonicaj)

---

src/middlewared/middlewared/plugins/failover_/event.py

App migrations are not being executed on HA-capable machines, which prevents chart releases from Dragonfish (DF) or older versions from being migrated to new apps in Electric Eel (EE).
Enable app migrations to run on the active node during failover, allowing for successful app migration on HA systems.

NAS-131799 / 25.04 / Make sure apps are migrated in HA

---

src/middlewared/middlewared/plugins/failover_/event.py

App migrations are not being executed on HA-capable machines, which prevents chart releases from Dragonfish (DF) or older versions from being migrated to new apps in Electric Eel (EE).
Enable app migrations to run on the active node during failover, allowing for successful app migration on HA systems.
Original PR: https://github.com/truenas/middleware/pull/14698
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131799

NAS-131799 / 24.10.0 / Make sure apps are migrated in HA (by Qubad786)

---

src/middlewared/middlewared/plugins/failover_/event.py

App migrations are not being executed on HA-capable machines, which prevents chart releases from Dragonfish (DF) or older versions from being migrated to new apps in Electric Eel (EE).
Enable app migrations to run on the active node during failover, allowing for successful app migration on HA systems.
Original PR: https://github.com/truenas/middleware/pull/14698
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131799

NAS-131799 / 24.10.1 / Make sure apps are migrated in HA (by Qubad786)

---

src/middlewared/middlewared/plugins/audit/audit.py
tests/api2/test_audit_basic.py

----
An `audit.query` to the remote controller returns an empty result if the remote controller is unable to respond.  This is incorrect behavior and results in a false interpretation of the query.
----
Raise an exception when the remote controller does not respond to an `audit.query`.
The test involves generating an audit event on the remote node.  The event is an attempt to delete a built-in user.
Updated passing test can be found [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1353/).

NAS-131690 / 25.04 / Allow remote audit call to return exception if unresponsive.

---

src/middlewared/middlewared/plugins/account.py
tests/api2/test_password_reset.py

When a non-full_admin user is authenticated to our API, that user must provide (and it be validated correctly) the current password if they so choose to change their password. This is also required by STIG SRG-OS-000373-GPOS-00158. A test has been added to validate this functionality.
Passing tests are [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1376/testReport/api2/test_password_reset/)

NAS-131826 / 25.04 / Enforce old password for non-FULL_ADMIN users

---

src/middlewared/middlewared/plugins/account.py
tests/api2/test_password_reset.py

When a non-full_admin user is authenticated to our API, that user must provide (and it be validated correctly) the current password if they so choose to change their password. This is also required by STIG SRG-OS-000373-GPOS-00158. A test has been added to validate this functionality.
Passing tests are [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1376/testReport/api2/test_password_reset/)
Original PR: https://github.com/truenas/middleware/pull/14701
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131826

NAS-131826 / 24.10.0 / Enforce old password for non-FULL_ADMIN users (by yocalebo)

---

src/middlewared/middlewared/plugins/account.py
tests/api2/test_password_reset.py

When a non-full_admin user is authenticated to our API, that user must provide (and it be validated correctly) the current password if they so choose to change their password. This is also required by STIG SRG-OS-000373-GPOS-00158. A test has been added to validate this functionality.
Passing tests are [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1376/testReport/api2/test_password_reset/)
Original PR: https://github.com/truenas/middleware/pull/14701
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131826

NAS-131826 / 24.10.1 / Enforce old password for non-FULL_ADMIN users (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

The picture in the UI isn't loading properly because the UI has more strict checks on their side for determining what model picture they use. The r40 is front loaded and not top loaded.

NAS-131807 / 25.04 / fix r40 picture loading in UI

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

The picture in the UI isn't loading properly because the UI has more strict checks on their side for determining what model picture they use. The r40 is front loaded and not top loaded.
Original PR: https://github.com/truenas/middleware/pull/14705
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131807

NAS-131807 / 24.10.0 / fix r40 picture loading in UI (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

The picture in the UI isn't loading properly because the UI has more strict checks on their side for determining what model picture they use. The r40 is front loaded and not top loaded.
Original PR: https://github.com/truenas/middleware/pull/14705
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131807

NAS-131807 / 24.10.1 / fix r40 picture loading in UI (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/sysfs_disks.py

Drive slots 5, 6, 7, 8 weren't being lit up because there is a kernel bug where sysfs is populating `slot` files with duplicate integers for more than 1 disk slot (i.e. `enclosure/**/dir1/slot == 4` and `enclosure/**/dir2/slot == 4`). This breaks the design of our enclosure drive mapping logic and so I've had to put in a quirk for this particular platform when drives are being lit up using our API. I've confirmed with QE team that with these fixes in, all drive light up exactly as intended.

NAS-131817 / 25.04 / fix slots 5,6,7,8 on hseries

---

src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/sysfs_disks.py

Drive slots 5, 6, 7, 8 weren't being lit up because there is a kernel bug where sysfs is populating `slot` files with duplicate integers for more than 1 disk slot (i.e. `enclosure/**/dir1/slot == 4` and `enclosure/**/dir2/slot == 4`). This breaks the design of our enclosure drive mapping logic and so I've had to put in a quirk for this particular platform when drives are being lit up using our API. I've confirmed with QE team that with these fixes in, all drive light up exactly as intended.
Original PR: https://github.com/truenas/middleware/pull/14704
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131817

NAS-131817 / 24.10.0 / fix slots 5,6,7,8 on hseries (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/sysfs_disks.py

Drive slots 5, 6, 7, 8 weren't being lit up because there is a kernel bug where sysfs is populating `slot` files with duplicate integers for more than 1 disk slot (i.e. `enclosure/**/dir1/slot == 4` and `enclosure/**/dir2/slot == 4`). This breaks the design of our enclosure drive mapping logic and so I've had to put in a quirk for this particular platform when drives are being lit up using our API. I've confirmed with QE team that with these fixes in, all drive light up exactly as intended.
Original PR: https://github.com/truenas/middleware/pull/14704
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131817

NAS-131817 / 24.10.1 / fix slots 5,6,7,8 on hseries (by yocalebo)

---

src/middlewared/middlewared/api/v25_04_0/alert.py

In https://github.com/truenas/middleware/pull/14615 I incorrectly typed `Alert.datetime` and `Alert.last_occurrence` as `str` instead of `datetime`. As it turns out, pydantic handles `datetime` similarly to how our old `Datetime` schema works https://docs.pydantic.dev/2.0/usage/types/datetime/#:~:text=datetime%20fields%20will,as%20Unix%20time.

NAS-131825 / 25.04 / Use `datetime` type in the Alert model instead of `str`

---

src/middlewared/middlewared/plugins/cloud/crud.py
src/middlewared/middlewared/plugins/cloud_backup/crud.py
src/middlewared/middlewared/plugins/cloud_backup/init.py
src/middlewared/middlewared/plugins/cloud_backup/restic.py

Our current implementation of `cloud_backup.create` has the soft requirement that the bucket should already exist. It is a soft requirement because it will create the bucket improperly and not raise an error if the bucket does not already exist. This forces the UI to call `cloudsync.create_bucket` before calling `cloud_backup.create`, but the bucket should never be created if the latter call fails.
With this change in `cloud_backup.init`, bucket creation will be handled properly if needed so that the UI no longer needs to call `cloudsync.create_bucket`.

NAS-131857 / 25.04 / Create new bucket on cloud_backup.init if it doesn't exist yet

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

I learned this is the only front loaded, 48 bay system we sell. Update the property so the UI allows the enclosure page to be responsive. Otherwise, it's broken subtly.

NAS-131875 / 25.04 / fix R40 webUI behavior

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

I learned this is the only front loaded, 48 bay system we sell. Update the property so the UI allows the enclosure page to be responsive. Otherwise, it's broken subtly.
Original PR: https://github.com/truenas/middleware/pull/14715
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131875

NAS-131875 / 24.10.0 / fix R40 webUI behavior (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

I learned this is the only front loaded, 48 bay system we sell. Update the property so the UI allows the enclosure page to be responsive. Otherwise, it's broken subtly.
Original PR: https://github.com/truenas/middleware/pull/14715
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131875

NAS-131875 / 24.10.1 / fix R40 webUI behavior (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py

The x-series platform is the same chassis as the ES12. During another round of testing, found the drive slots were off ever so slightly. This fixes the problem.

NAS-131874 / 25.04 / fix xseries drive mapping

---

src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py

The x-series platform is the same chassis as the ES12. During another round of testing, found the drive slots were off ever so slightly. This fixes the problem.
Original PR: https://github.com/truenas/middleware/pull/14714
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131874

NAS-131874 / 24.10.0 / fix xseries drive mapping (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py

The x-series platform is the same chassis as the ES12. During another round of testing, found the drive slots were off ever so slightly. This fixes the problem.
Original PR: https://github.com/truenas/middleware/pull/14714
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131874

NAS-131874 / 24.10.1 / fix xseries drive mapping (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/r30_drive_identify.py

This system has very strange drive slot mappings. Consulted documentation again and found I simply didn't do this section right the first time. This fixes it.
Original PR: https://github.com/truenas/middleware/pull/14722
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131879

NAS-131879 / 24.10.0 / fix r30 drive identify logic (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/r30_drive_identify.py

This system has very strange drive slot mappings. Consulted documentation again and found I simply didn't do this section right the first time. This fixes it.
Original PR: https://github.com/truenas/middleware/pull/14722
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131879

NAS-131879 / 24.10.1 / fix r30 drive identify logic (by yocalebo)

---

src/middlewared/middlewared/plugins/crypto_/crypto_key.py
src/middlewared/middlewared/plugins/crypto_/generate_utils.py
src/middlewared/middlewared/plugins/crypto_/utils.py
src/middlewared/middlewared/pytest/unit/plugins/crypto/certs.py
tests/api2/test_certs.py

This PR adds changes to fix the case when an external CA is imported in TN and that CA is used to sign a CSR, the generated cert's issuer DN's componets are shuffled/out of order and do not match the order in the CA. With these changes, the original order of Relative Distinguished Names (RDNs) in the Subject field is preserved when generating a Certificate using an imported CA. By maintaining the sequence of RDNs, the CSRs signed by the Certificate Authority (CA) will reflect the same order of Issuer DN as in the CA's Subject DN ([RFC 3280](https://www.rfc-editor.org/rfc/rfc3280#section-4.1.2.4) on page 91).

NAS-130280 / 25.04 / Make sure issuer subject is preserved when CSR is signed

---

src/middlewared/middlewared/plugins/crypto_/crypto_key.py
src/middlewared/middlewared/plugins/crypto_/generate_utils.py
src/middlewared/middlewared/plugins/crypto_/utils.py
src/middlewared/middlewared/pytest/unit/plugins/crypto/certs.py
tests/api2/test_certs.py

This PR adds changes to fix the case when an external CA is imported in TN and that CA is used to sign a CSR, the generated cert's issuer DN's componets are shuffled/out of order and do not match the order in the CA. With these changes, the original order of Relative Distinguished Names (RDNs) in the Subject field is preserved when generating a Certificate using an imported CA. By maintaining the sequence of RDNs, the CSRs signed by the Certificate Authority (CA) will reflect the same order of Issuer DN as in the CA's Subject DN ([RFC 3280](https://www.rfc-editor.org/rfc/rfc3280#section-4.1.2.4) on page 91).
Original PR: https://github.com/truenas/middleware/pull/14669
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130280

NAS-130280 / 24.10.1 / Make sure issuer subject is preserved when CSR is signed (by sonicaj)

---

src/freenas/usr/bin/install-dev-tools

This commit adds python3-cryptography to list of deps which should be installed when dev-tools are being installed. TrueNAS already has this (and it pulls it from debian), however our test runners when they execute - they don't have this and it is required to run the integration tests.

NAS-131883 / 25.04 / Add python3-cryptography to list of dev packages

---

src/freenas/usr/bin/install-dev-tools

This commit adds python3-cryptography to list of deps which should be installed when dev-tools are being installed. TrueNAS already has this (and it pulls it from debian), however our test runners when they execute - they don't have this and it is required to run the integration tests.
Original PR: https://github.com/truenas/middleware/pull/14727
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131883

NAS-131883 / 24.10.1 / Add python3-cryptography to list of dev packages (by sonicaj)

---

src/middlewared/middlewared/auth.py
src/middlewared/middlewared/plugins/auth_/authenticate.py

During the upgrade process we import middleware in a chroot environment which breaks setup of the AuthenticationContext dataclass since the ctype symbol lookup for pam_start fails.
This commit makes it so that we don't initialize a pam context for App instances until endpoint auth.libpam_authenticate is called.

NAS-131893 / 25.04 / lazy-initialize pam context

---

src/middlewared/middlewared/plugins/apps/custom_app.py

This PR makes sure that app information is sent in `ADDED` event when custom apps are being installed and not just the name of the app itself.

NAS-131885 / 25.04 / Fix added event when installing custom app

---

src/middlewared/middlewared/plugins/apps/custom_app.py

This PR makes sure that app information is sent in `ADDED` event when custom apps are being installed and not just the name of the app itself.
Original PR: https://github.com/truenas/middleware/pull/14729
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131885

NAS-131885 / 24.10.1 / Fix added event when installing custom app (by sonicaj)

---

src/middlewared/middlewared/schema/string_schema.py

This commit updates error message for hostpath schema so if path is missing, we outline that it could just be that the path does not exist or that the underlying dataset may be locked.

NAS-131795 / 25.04 / Improve error message for hostpath schema

---

tests/api2/test_001_ssh.py

The test needed to be updated slightly, since some options like `RW,XATTR,NOACL,CASESENSISTIVE` are present in `super_opts` instead of `mount_opts`.
```
{
"mount_id": 28,
"parent_id": 27,
"device_id": {
"major": 0,
"minor": 25,
"dev_t": 25
},
"root": "/",
"mountpoint": "/audit",
"mount_opts": [
"RW",
"NOSUID",
"NODEV",
"NOEXEC",
"NOATIME"
],
"fs_type": "zfs",
"mount_source": "boot-pool/ROOT/25.04.0-MASTER-20241018-005230/audit",
"super_opts": [
"RW",
"XATTR",
"NOACL",
"CASESENSITIVE"
]
},
```
Related ZFS PRs[[1](https://github.com/truenas/zfs/pull/257)][[2](https://github.com/truenas/zfs/pull/257)] are merged in TrueNAS ZFS.
[Updated API test run](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1413/#showFailuresLink) was successful.

NAS-127825 / 25.04 / Enable the API test for mount options

---

tests/api2/test_001_ssh.py

The test needed to be updated slightly, since some options like `RW,XATTR,NOACL,CASESENSISTIVE` are present in `super_opts` instead of `mount_opts`.
```
{
"mount_id": 28,
"parent_id": 27,
"device_id": {
"major": 0,
"minor": 25,
"dev_t": 25
},
"root": "/",
"mountpoint": "/audit",
"mount_opts": [
"RW",
"NOSUID",
"NODEV",
"NOEXEC",
"NOATIME"
],
"fs_type": "zfs",
"mount_source": "boot-pool/ROOT/25.04.0-MASTER-20241018-005230/audit",
"super_opts": [
"RW",
"XATTR",
"NOACL",
"CASESENSITIVE"
]
},
```
Related ZFS PRs[[1](https://github.com/truenas/zfs/pull/257)][[2](https://github.com/truenas/zfs/pull/257)] are merged in TrueNAS ZFS.
[Updated API test run](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1413/#showFailuresLink) was successful.
Original PR: …

NAS-127825 / 24.10.1 / Enable the API test for mount options (by usaleem-ix)

---

src/middlewared/middlewared/plugins/disk_/wipe.py
tests/api2/test_disk_wipe.py

This fixes disk.wipe to actually zero the first and last 32MB of the disk being wiped. We have seen a few reports of users on SCALE where libblkid is reporting partition information on disks that should _not_ be there. There is a separate libblkid bug related to ZFS and the OS team is working on that separately, however, this was trivially reproducible by writing another filesystems label "magic string" and then running `disk.wipe` on it preventing that file system label from being removed. This boils down to the API in python interpreting and doing something with null characters instead of 0's. The fix is quite simple really and I've improved the `disk.wipe` test to ensure this does not get missed in the future. Tests are passing.

NAS-131171 / 25.04 / fix disk.wipe

---

src/middlewared/middlewared/plugins/disk_/wipe.py
tests/api2/test_disk_wipe.py

This fixes disk.wipe to actually zero the first and last 32MB of the disk being wiped. We have seen a few reports of users on SCALE where libblkid is reporting partition information on disks that should _not_ be there. There is a separate libblkid bug related to ZFS and the OS team is working on that separately, however, this was trivially reproducible by writing another filesystems label "magic string" and then running `disk.wipe` on it preventing that file system label from being removed. This boils down to the API in python interpreting and doing something with null characters instead of 0's. The fix is quite simple really and I've improved the `disk.wipe` test to ensure this does not get missed in the future. Tests are passing.
Original PR: …

NAS-131171 / 24.10.0 / fix disk.wipe (by yocalebo)

---

src/middlewared/middlewared/plugins/disk_/wipe.py
tests/api2/test_disk_wipe.py

This fixes disk.wipe to actually zero the first and last 32MB of the disk being wiped. We have seen a few reports of users on SCALE where libblkid is reporting partition information on disks that should _not_ be there. There is a separate libblkid bug related to ZFS and the OS team is working on that separately, however, this was trivially reproducible by writing another filesystems label "magic string" and then running `disk.wipe` on it preventing that file system label from being removed. This boils down to the API in python interpreting and doing something with null characters instead of 0's. The fix is quite simple really and I've improved the `disk.wipe` test to ensure this does not get missed in the future. Tests are passing.
Original PR: …

NAS-131171 / 24.10.1 / fix disk.wipe (by yocalebo)

---

src/middlewared/middlewared/plugins/apps/ix_apps/path.py
src/middlewared/middlewared/plugins/apps/ix_volumes.py

This PR adds changes to expose an endpoint which tells if ix-volumes for an app exist or not so UI can conditionally show boolean flag when app is being deleted.
We want to have an ix-volume query/delete service in place for FT and the basics for that have been added in this ticket as well.
Original PR: https://github.com/truenas/middleware/pull/14741
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131714

NAS-131714 / 24.10.1 / Add an endpoint which UI can use to conditionally show boolean flag for removing ix-volumes on app deletion (by sonicaj)

---

src/middlewared/middlewared/api/v25_04_0/auth.py
src/middlewared/middlewared/plugins/auth.py
tests/api2/test_twofactor_auth.py

If we have an in-progress authentication attempt, allow client to
abandon current stage in favor of restarting the authentication process.
In this case since we haven't generated a success or failure record
for the authentication attempt, log it as an OTP failure with a special
message that OTP validation was abandoned.
Add a new dedicated API endpoint to continue a login_ex request that
returned OTP_REQUIRED. This is named `auth.login_ex_continue` so that
we have potential to expand it in the future if we add support for
other login mechanisms that require conversation with client and
server.

NAS-131914 / 25.04 / Relax next mechanism requirement for OTP_TOKEN

---

tests/api2/test_001_ssh.py

Today PR #14737 "enabled the API test for mount options", but it failed to restore `NOSUID` which had been filtered out pending the ZFS fix in [NAS-127825](https://ixsystems.atlassian.net/browse/NAS-127825).
Passing CI here: [1437](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1437/)

NAS-131920 / 25.04 / Restore NOSUID to test_008_check_root_dataset_settings

---

src/middlewared/middlewared/alert/base.py
src/middlewared/middlewared/api/base/handler/result.py
tests/unit/test_api.py

This fix https://github.com/truenas/middleware/pull/14712 introduced the new problem of non-full_admin users receiving `datetime_` instead of `datetime` on `alert.list`. This revealed the broader issue of our new-style API call results not respecting field aliases in serialization.
I've also cleaned up the type annotations in alert.py.

NAS-131910 / 25.04 / Fix non-fulladmin user getting `datetime_` instead of `datetime` on `alert.list`

---

src/middlewared/middlewared/plugins/nfs.py
src/middlewared/middlewared/plugins/nfs_/fs_attachment_delegate.py
src/middlewared/middlewared/plugins/service_/services/nfs.py
src/middlewared/middlewared/plugins/sysdataset.py
src/middlewared/middlewared/test/integration/assets/pool.py
src/middlewared/middlewared/test/integration/utils/failover.py
tests/api2/test_300_nfs.py
tests/protocols/__init__.py

Deleting a pool that holds the system dataset while NFS is active can cause a failure to delete the pool.
The fix for this is to temporarily stop NFS during the system dataset move operation.
This PR also includes:
- CI test for the pool delete condition (main topic)
- Better management of `/proc/fs/nfsd/nfsv4recoverydir` and a CI test
- Adding `wait_for_standby` routine in failover test utils
- Added `# noqa` to a few lines to avoid flake8 complaints
Passing HA CI NFS tests can be found [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1452/).
Passing standalone CI NFS tests can be found [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1453/)

NAS-131570 / 25.04 / Fix pool deletion with active NFS shares.

---

src/middlewared/middlewared/api/v25_04_0/group.py
src/middlewared/middlewared/api/v25_04_0/user.py
src/middlewared/middlewared/plugins/account.py
tests/api2/test_011_user.py
tests/api2/test_account_duplicate_uid_gid.py

After internal discussion the valid use-cases for allowing groups with duplicate gids are few and far between, but the risk of novice users accidentally exposing themselves to unexpected disclosure of information is not obscure. Hence, we are removing this quasi-feature from the v25.04 API before it's finalized. This same argument for allowing API consumers to change the uid for users and gid for groups can be made. In this case the functionality was never exposed via the webui.

NAS-131894 / 25.04 / prevent mistakes related to uids and gids in accounts plugin

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/rdma.py
src/middlewared/middlewared/plugins/rdma/rdma.py

To support the rdma configuration setting in the UI the newish `rdma.capable_services` routine is required as a public method.  As such, we need to convert it from private to public.
_As part of that change_, the entire `rdma.py` service module was converted to the new api method.
Also fixed a couple flake8 issues.

NAS-131944 / 25.04 / Convert rdma to new api method.

---

src/middlewared/middlewared/api/v25_04_0/common.py
src/middlewared/middlewared/validators.py

The transition to new api_method made query-options too restrictive and did not implement validator for query-filters. This commit plumbs in our existing middleware validators into these models.

NAS-131942 / 25.04 / User proper validators for query-filters and query-options

---

src/middlewared/middlewared/plugins/failover_/event.py

This commit fixes erroneous logging and apps functionality in HA on failover event for EE because a certain block code is not relevant for EE and that logic is already ingrained in docker start service endpoint.

NAS-131953 / 24.10.1 / Fix apps for HA in EE

---

src/middlewared/middlewared/plugins/failover_/event.py

This commit fixes erroneous logging and apps functionality in HA on failover event for EE because a certain block code is not relevant for EE and that logic is already ingrained in docker start service endpoint.
Original PR: https://github.com/truenas/middleware/pull/14761
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131953

NAS-131953 / 24.10.0 / Fix apps for HA in EE (by sonicaj)

---

src/middlewared/middlewared/plugins/failover_/reboot.py

This method is used in both async and non-async contexts. The original implementation causes the following exception when used from the async context
```
[2024/10/24 06:15:41] (ERROR) middlewared.wrap():1773 - Unhandled exception in event handler
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1771, in wrap
await handler(self, event_type, kwargs)
File "/usr/lib/python3/dist-packages/middlewared/plugins/failover_/reboot.py", line 184, in remote_reboot_info
middleware.call_sync('failover.reboot.send_event', background=True)
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1656, in call_sync
raise RuntimeError('You cannot use call_sync from main thread')
RuntimeError: You cannot use call_sync …
```

NAS-131916 / 25.04 / Fix sending `failover.reboot.info`

---

src/middlewared/middlewared/utils/disks.py

This significantly speeds up `get_disk_names`. Furthermore, it bypasses libudev. The udev cache is fickle and can be invalidated on a whim (even though the disk still exists).
Since this is such a critical part of our code, it's best to iterate `/dev` and pull out the valid disks. This is the exact same methodology used in `fenced` and that program has no room for failure.
This uses `scandir` instead of `iterdir`, the latter enumerating the entire contents of the directory into a list object before being returned to the caller (inefficient). We also use a filter, lambda expression since python3.12 (or 3.13) will inline these expressions further improving performance. Finally, fix a flake8 error while I'm here.

NAS-131973 / 25.04 / significantly speed up get_disk_names()

---

src/middlewared/middlewared/plugins/apps/upgrade.py

This commit adds changes to not allow upgrading an app if it is in stopped state, after discussing with Stavros we believe that is the best way to move forward as to actually be able to ensure that an app gets properly migrated over to the newer version, ideally it should be in a state other then stopped (deploying/running/crashed etc).

NAS-131842 / 25.04 / Only allow upgrading an app if it is not in stopped state

---

src/middlewared/middlewared/plugins/apps/upgrade.py

This commit adds changes to not allow upgrading an app if it is in stopped state, after discussing with Stavros we believe that is the best way to move forward as to actually be able to ensure that an app gets properly migrated over to the newer version, ideally it should be in a state other then stopped (deploying/running/crashed etc).
Original PR: https://github.com/truenas/middleware/pull/14763
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131842

NAS-131842 / 24.10.1 / Only allow upgrading an app if it is not in stopped state (by sonicaj)

---

src/middlewared/middlewared/plugins/nfs.py
src/middlewared/middlewared/plugins/nfs_/fs_attachment_delegate.py
src/middlewared/middlewared/plugins/service_/services/nfs.py
src/middlewared/middlewared/plugins/sysdataset.py
src/middlewared/middlewared/test/integration/assets/pool.py
src/middlewared/middlewared/test/integration/utils/failover.py
tests/protocols/__init__.py

git cherry-pick -x 00b3d399b4463d30a92190ac82173c01d294ed55
git cherry-pick -x 412cf97770a84309e907d365d8fbb7d7d4bb1117
git cherry-pick -x c1c8ab37e9b5f22c3f15301111708e1b982f9267
Deleting a pool that holds the system dataset while NFS is active can cause a failure to delete the pool.
The fix for this is to temporarily stop NFS during the system dataset move operation.
This PR also includes:
- CI test for the pool delete condition (main topic)
- Better management of `/proc/fs/nfsd/nfsv4recoverydir` and a CI test
- Adding `wait_for_standby` routine in failover test utils
- Added `# noqa` …

NAS-131570 / 24.10.1 / Fix pool deletion with active NFS shares. (by mgrimesix)

---

src/middlewared/middlewared/plugins/network.py

For REST calls being made in EE, we are not able to retrieve local ip in our `websocket_local_ip` endpoint as that expects a websocket connection and any endpoint consuming this will fail when the endpoint is consumed via REST.
After discussion with Caleb, we don't want to try and retrieve local ip for REST in EE and we should gracefully just handle it.

NAS-131903 / 24.10.1 / Properly handle case when local IP is not retrievable via application during REST call

---

src/middlewared/middlewared/plugins/docker/attachments.py
src/middlewared/middlewared/plugins/docker/state_management.py
src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/test/integration/assets/docker.py
tests/api2/test_apps.py
tests/api2/test_docker_setup.py

This PR fixes an issue in FT where we are differently handling applications dataset being mounted/umounted - which in it's current state resulted in the apps dataset to be mounted even if root dataset was locked (as apps dataset is un-encrypted). While i am here, i have also fixed docker integration test to properly make use of fixture and added integration test to handle the encryption case as well.

NAS-132002 / 25.04 / Make sure apps are correctly handled with root dataset being encrypted in FT

---

src/middlewared/middlewared/pytest/unit/utils/test_disk_names.py

We have recently separated getting disk names from middleware and moved it to it's own util and here unit tests have been added to validate the function.

NAS-132005 / 25.04 / Add unit test to validate disk names

---

src/middlewared/middlewared/api/v25_04_0/virt.py
src/middlewared/middlewared/plugins/virt/global.py

UI team has complained they are not allowed to use `""` as value for pool/bridge and these are returned by pool_choices/bridge_choices.
choices cannot return `null` as keys in a dict, hence the need to support empty string.

NAS-130523 / 25.04 / Allow null for pool/bridge

---

src/middlewared/middlewared/test/integration/utils/mock.py
tests/api2/test_mock_remote.py

Add an optional remote parameter to the mock fixture, that will cause the mock to occur on the remote node in a HA pair.

NAS-132011 / 25.04 / Add ability to allow method on remote node to be mocked

---

src/middlewared/middlewared/pytest/unit/plugins/apps/test_list_apps.py

This PR adds unit tests to test out the functionality of `list_apps` utility and make sure that it reports the correct and intended app states according to the container state.

NAS-132004 / 25.04 / Add unit tests for validating app states

---

src/middlewared/middlewared/api/v25_04_0/alert.py
src/middlewared/middlewared/plugins/alert.py

https://github.com/truenas/middleware/pull/14615 incorrectly set the args and result models for `alertclasses.update`. After some experimentation, it seems like there is no way to perfectly match the current schema for "accepts" and "returns" without doing some ugly things with pydantic that don't fit nicely into how we have been implementing the new API style. This PR changes the schema for `alertclasses.update` without breaking the endpoint and preserves the syntax we have been using for the new API style.
<details>
<summary>Current schema</summary>
```json
"accepts": [
{
"type": "object",
"properties": {
"classes": {
"type": "object",
"properties": {},
"additionalProperties": true,
"_name_": "classes",
"title": "classes",
"default": {},
"_required_": false,
"_attrs_order_": []
}
}, …
```

Convert `alertclasses.update` to new api style

---

src/middlewared/middlewared/plugins/vm/devices/nic.py
src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_devices_validation.py

Libvirt does not allow NIC MAC addresses to start with `ff`, which causes VMs to break until a reboot is performed.
Add validation to the NIC configuration to prevent MAC addresses from starting with `ff` for VMs.

NAS-131832 / 25.04 / Better validate VM NIC mac address

---

tests/api2/test_twofactor_auth.py

These are tripping the rate limit logic in middleware. There is already a function level fixture for clearing the rate limit using the root account, so I simply passed that fixture to the remaining tests.

NAS-132059 / 25.04 / Fix failing 2fa tests

---

src/middlewared/middlewared/service/core_service.py
tests/api2/test_job_logs.py

@yocalebo please note that this only fixes half of the real issue. I created a new ticket for you to review and determine fix version https://ixsystems.atlassian.net/browse/NAS-132031
Original PR: https://github.com/truenas/middleware/pull/14790
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132001

NAS-132001 / 24.10.1 / Fix `__job_by_credential_and_id` crashing for non-full-admins and internally ran jobs (by themylogin)

---

src/middlewared/middlewared/alembic/versions/25.04/2024-10-29_12-43_vm_zvol_serial.py
src/middlewared/middlewared/plugins/vm/devices/storage_devices.py
src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_devices_xml.py

When disk devices are created in VMs, they don't have a serial present. Some types of disks may have an autogenerated one from libvirt but then we can potentially get persistence issues wrt serials and for some types, libvirt doesn't even add auto-generated ones.
Generate a random serial number and assign it to VM disks making sure the serial persists across the device lifecycle.

NAS-131785 / 25.04 / Make sure serial is specified for all VM disk devices

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

The original regex code for this platform is as follows: `re.compile(r"(ECStream|iX) 4024J")` which basically means contains those patterns. This was misinterpreted in the new enclosure plugin. The new enclosure plugin is more strict with its firmware string checks and looks for an exact match of those patterns. This is invalid because the ES24 firmware string (that's what these patterns are matching on) actually end with `s` or `p`. To resolve this we'll use `startswith` operation on the firmware string. After these changes, it was confirmed to fix ES24 enclosure detection.

NAS-132067 / 25.04 / fix ES24 enclosure detection

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

The original regex code for this platform is as follows: `re.compile(r"(ECStream|iX) 4024J")` which basically means contains those patterns. This was misinterpreted in the new enclosure plugin. The new enclosure plugin is more strict with its firmware string checks and looks for an exact match of those patterns. This is invalid because the ES24 firmware string (that's what these patterns are matching on) actually end with `s` or `p`. To resolve this we'll use `startswith` operation on the firmware string. After these changes, it was confirmed to fix ES24 enclosure detection.
Original PR: https://github.com/truenas/middleware/pull/14805
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132067

NAS-132067 / 24.10.1 / fix ES24 enclosure detection (by yocalebo)

---

src/middlewared/middlewared/api/base/model.py
src/middlewared/middlewared/pytest/unit/test_service_crud_service.py

All fields in the query result must be non-required since we can query subsets of fields.

NAS-132042 / 25.04 / Make all fields in query results non-required

---

src/middlewared/middlewared/plugins/filesystem_/acl_template.py

This error crept in while addressing various reviews and causes all acltemplate entries to be returned as None in query results.

NAS-132106 / 25.04 / Fix missing return value for acltemplate extend method

---

src/middlewared/middlewared/api/base/decorator.py
src/middlewared/middlewared/api/v25_04_0/auth.py
src/middlewared/middlewared/auth.py
src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/ntp.py
src/middlewared/middlewared/plugins/smb_/passdb.py
src/middlewared/middlewared/pytest/unit/utils/test_audit.py
src/middlewared/middlewared/service/decorators.py
src/middlewared/middlewared/test/integration/assets/keychain.py
src/middlewared/middlewared/utils/audit.py
src/middlewared/middlewared/utils/privilege.py
tests/api2/test_auth_token.py
tests/api2/test_keychain_ssh.py
tests/api2/test_replication_utils.py

This is mostly boiler-plate code with exception of the following:
1. default for match_origin in auth.generate_token to True as a general improvement to product security.
2. TrueNasNodeSessionManagerCredentials class was renamed to TruenasNodeSessionManagerCredentials to ensure that generated credentials class name is TRUENAS_NODE rather than TRUE_NAS_NODE.
3. auth.generate_token was changed from not_auth_required with separate internal check for session being authenticated to no_authz_required.
4. api_method is extended to support no_authz_required and no_auth_required kwargs.

NAS-132069 / 25.04 / Convert remaining auth plugin to api_method

---

src/middlewared/middlewared/plugins/apps/ix_apps/query.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_list_apps.py

This PR adds changes to account for UI team request to retrieve latest versions available for an app so that they don't have to make a new call for that. This is not expensive for middleware as we already have that information and it just needs to be exposed.

NAS-131983 / 25.04 / Retrieve latest version of an app available when querying apps for UI

---

src/middlewared/middlewared/plugins/apps/crud.py
src/middlewared/middlewared/plugins/zfs_/dataset.py

This PR adds changes to allow removing ix-volumes of apps which were migrated over from k8s. When we migrated apps from k8s and they had ix-volumes, what we did was that we created a clone and promoted the clone under the new ix-apps dataset. So in order to delete these ix-volumes, we want to properly make sure all dependents are removed.

NAS-131911 / 25.04 / Allow removing ix-volumes of apps which were migrated from k8s

---

src/middlewared/middlewared/plugins/apps/crud.py
src/middlewared/middlewared/plugins/zfs_/dataset.py

This PR adds changes to allow removing ix-volumes of apps which were migrated over from k8s. When we migrated apps from k8s and they had ix-volumes, what we did was that we created a clone and promoted the clone under the new ix-apps dataset. So in order to delete these ix-volumes, we want to properly make sure all dependents are removed.
Original PR: https://github.com/truenas/middleware/pull/14810
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131911

NAS-131911 / 24.10.1 / Allow removing ix-volumes of apps which were migrated from k8s (by sonicaj)

---

src/middlewared/middlewared/plugins/cloud_backup/restic.py
src/middlewared/middlewared/plugins/cloud_backup/restore.py
src/middlewared/middlewared/plugins/cloud_backup/sync.py

git cherry-pick -x 4751f4dfa968b9ba42a4aef90153c6d98c53cbbc
git cherry-pick -x 4f412bfd3779ca75f21f93b02ea27ba7d2cecbff
git cherry-pick -x 228cd2c2bbc12b2aaa2ca66fc9eddce689c487a6
git cherry-pick -x dc40c11aa7ed9344b00a6a58f7c948fd6f16472c
git cherry-pick -x 0ed403a58f2f02e47424fd120269fab31188ae0d
git cherry-pick -x 6b5d518c31826f754c0e1caa18a7cc657903f1c0
git cherry-pick -x b47c435a28f42ce8eda91a7a3cec47af1eb352b9
git cherry-pick -x 49990e396e018e81839c9661de9dd1e8dcc08bca
Our TrueCloud Backup Tasks use restic to back up local data. The procedure we use to capture restic's output does …

NAS-131804 / 24.10.1 / Show progress on cloud_backup.sync and restore (by creatorcary)

---

src/middlewared/middlewared/plugins/failover_/event.py

This fixes a bug in our HA logic whereby we're mistakenly ignoring interfaces that are marked critical for failover (treating them as non-critical for failover).
The explanation is simple and I'm surprised we're only now seeing this issue. I check to see if the left operand is `in` the right operand. This means left operand strings with a value of `ens4` will evaluate to true if the right side of the operand is of string `ens4d1`.
The solution is to make sure the left and right operands are equivalent.

NAS-132115 / 25.04 / fix HA logic bug

---

src/middlewared/middlewared/plugins/failover_/event.py

This fixes a bug in our HA logic whereby we're mistakenly ignoring interfaces that are marked critical for failover (treating them as non-critical for failover).
The explanation is simple and I'm surprised we're only now seeing this issue. I check to see if the left operand is `in` the right operand. This means left operand strings with a value of `ens4` will evaluate to true if the right side of the operand is of string `ens4d1`.
The solution is to make sure the left and right operands are equivalent.
Original PR: https://github.com/truenas/middleware/pull/14820
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132115

NAS-132115 / 24.10.1 / fix HA logic bug (by yocalebo)

---

src/middlewared/middlewared/plugins/filesystem_/utils.py

This fixes an avenue for raising a KeyError when generating a POSIX ACL string during validation for acltemplate entry insertion of POSIX ACL.

NAS-132127 / 25.04 / Fix KeyError when generating POSIX ACL string

---

src/middlewared/middlewared/job.py
src/middlewared/middlewared/plugins/cloud_sync.py
src/middlewared/middlewared/plugins/replication.py
src/middlewared/middlewared/service/core_service.py
src/middlewared/middlewared/service/decorators.py
tests/api2/test_job_logs.py

git cherry-pick -x b2b54218fbc50bc5f6c1f8bb6e41e3994370aa56
git cherry-pick -x a2945013442c1744e15d621962cf7f5f55a97891
[NAS-132001: core.job_download_logs AttributeError crash](https://ixsystems.atlassian.net/browse/NAS-132001) occurred when a non-full-admin user attempted to download the logs of `replication.run`
This `replication.run` was called by an internal zettarepl scheduler and thus is an internally ran job. Non-full-admins can only download the logs of the jobs they started themselves.
Without this fix, an attempt of a non-full-admin user to download the logs of an …

NAS-132031 / 24.10.1 / Introduce job `read_roles` that will allow users to access jobs that … (by themylogin)

---

src/middlewared/middlewared/plugins/failover_/event.py

This fixes a bug in our HA logic whereby we're mistakenly ignoring interfaces that are marked critical for failover (treating them as non-critical for failover).
The explanation is simple and I'm surprised we're only now seeing this issue. I check to see if the left operand is `in` the right operand. This means left operand strings with a value of `ens4` will evaluate to true if the right side of the operand is of string `ens4d1`.
The solution is to make sure the left and right operands are equivalent.
Original PR: https://github.com/truenas/middleware/pull/14820
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132115
Original PR: https://github.com/truenas/middleware/pull/14825
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132115

NAS-132115 / 24.10.0.1 / fix HA logic bug (by yocalebo) (by bugclerk)

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

The original regex code for this platform is as follows: `re.compile(r"(ECStream|iX) 4024J")` which basically means contains those patterns. This was misinterpreted in the new enclosure plugin. The new enclosure plugin is more strict with its firmware string checks and looks for an exact match of those patterns. This is invalid because the ES24 firmware string (that's what these patterns are matching on) actually end with `s` or `p`. To resolve this we'll use `startswith` operation on the firmware string. After these changes, it was confirmed to fix ES24 enclosure detection.
Original PR: https://github.com/truenas/middleware/pull/14805
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132067
Original PR: https://github.com/truenas/middleware/pull/14806
Jira URL: …

NAS-132067 / 24.10.0.1 / fix ES24 enclosure detection (by yocalebo) (by bugclerk)

---

src/middlewared/middlewared/plugins/disk_/retaste.py
src/middlewared/middlewared/plugins/failover_/event.py

A couple issues have been found internally surrounding SED drives and how we unlock them. This is SCALE specific and so after consultation with the OS team, we're trying to implement changes which fix these problems.
1. On MASTER failover event, notify the standby controller to retaste the disks after we unlock any SED drives
2. On BACKUP failover event, retaste the disks to ensure we're "up to date" with partition information
3. Change the `disk.retaste` job to only queue up 1 job (including the currently running job)
4. stop using `libudev` in the `disk.retaste` endpoint since the udev database can be in flux by the time we query it. Instead we'll use device node names in `/dev`.
Original PR: https://github.com/truenas/middleware/pull/14690
Jira URL: …

NAS-129366 / 24.10.0.1 / Try to fix SED unlock issues on HA SCALE (by yocalebo) (by bugclerk)

---

src/middlewared/middlewared/plugins/failover_/event.py

This fixes a bug in our HA logic whereby we're mistakenly ignoring interfaces that are marked critical for failover (treating them as non-critical for failover).
The explanation is simple and I'm surprised we're only now seeing this issue. I check to see if the left operand is `in` the right operand. This means left operand strings with a value of `ens4` will evaluate to true if the right side of the operand is of string `ens4d1`.
The solution is to make sure the left and right operands are equivalent.
Original PR: https://github.com/truenas/middleware/pull/14820
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132115
Original PR: https://github.com/truenas/middleware/pull/14825
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132115
Original PR: …

NAS-132115 / 24.04.2.4 / fix HA logic bug (by yocalebo) (by bugclerk) (by bugclerk)

---

src/middlewared/middlewared/plugins/disk_/retaste.py
src/middlewared/middlewared/plugins/failover_/event.py

A couple issues have been found internally surrounding SED drives and how we unlock them. This is SCALE specific and so after consultation with the OS team, we're trying to implement changes which fix these problems.
1. On MASTER failover event, notify the standby controller to retaste the disks after we unlock any SED drives
2. On BACKUP failover event, retaste the disks to ensure we're "up to date" with partition information
3. Change the `disk.retaste` job to only queue up 1 job (including the currently running job)
4. stop using `libudev` in the `disk.retaste` endpoint since the udev database can be in flux by the time we query it. Instead we'll use device node names in `/dev`.
Original PR: https://github.com/truenas/middleware/pull/14690
Jira URL: …

NAS-129366 / 24.04.2.4 / Try to fix SED unlock issues on HA SCALE (by yocalebo) (by bugclerk) (by bugclerk)

---

src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/test/integration/assets/keychain.py
tests/api2/test_auth_token.py
tests/api2/test_keychain_ssh.py
tests/api2/test_replication_utils.py

The UI team does not use this feature for semi-automatic replication setup and so it's safe for us to match origin for tokens by default.

NAS-132141 / 24.10.1 / Change default for token match-origin

---

src/middlewared/middlewared/plugins/fc/utils.py

Found a platform where the `dmidecode -t9` output included a `.1`, but not a `.0` bus address.
```
...
Handle 0x0047, DMI type 9, 17 bytes
System Slot Information
Designation: CPU1 Slot2 PCI-E 3.0 X16
Type: x16 PCI Express 3 x16
Current Usage: In Use
Length: Long
ID: 2
Characteristics:
3.3 V is provided
PME signal is supported
SMBus signal is supported
Bus Address: 0000:3b:00.4
Handle 0x0049, DMI type 9, 17 bytes
System Slot Information
Designation: CPU1 Slot3 PCI-E 3.0 X8
Type: x8 PCI Express 3 x8
Current Usage: In Use
Length: Short
ID: 3
Characteristics:
3.3 V is provided
PME signal is supported
SMBus signal is supported
Bus Address: 0000:18:00.1
Handle 0x004B, DMI type 9, 17 bytes
System Slot Information
Designation: CPU2 Slot4 PCI-E 3.0 X16
Type: x16 PCI Express 3 x16
Current Usage: …
```

NAS-132157 / 25.04 / Robustize dmi_pci_slot_info

---

src/middlewared/middlewared/plugins/boot.py
src/middlewared/middlewared/utils/rootfs.py

As per @usaleem-ix's explanation
> There was an issue in ZFS, datasets mounted during boot did not have correct permissions because mount command from busybox was used in initramfs to  mount the datasets. this mount command does mount syscall directly into the kernel, bypassing the mount helper program also used by mount from util-linux package, that is available when boot is completed. https://ixsystems.atlassian.net/browse/NAS-127825
> This issue was fixed recently. Now on SCALE, we have datasets like usr, etc and others now mounted with correct permissions. We set readonly=on for /usr, same goes for root (/). We do this from fhs.py in scale-build. These options were not being enforced previously, but after the fix for NAS-127825 this test case broke.

NAS-132164 / 25.04 / Fix `ReadonlyRootfsManager` not really making rootfs writeable

---

src/middlewared/middlewared/plugins/boot.py
src/middlewared/middlewared/utils/rootfs.py

git cherry-pick -x 23149f7357b7177fcf4197ca260dac15044eaf9d
git cherry-pick -x bcf985a240fa9648088f484383179060fec895fc
As per @usaleem-ix's explanation
> There was an issue in ZFS, datasets mounted during boot did not have correct permissions because mount command from busybox was used in initramfs to  mount the datasets. this mount command does mount syscall directly into the kernel, bypassing the mount helper program also used by mount from util-linux package, that is available when boot is completed. https://ixsystems.atlassian.net/browse/NAS-127825
> This issue was fixed recently. …

NAS-132164 / 24.10.1 / Fix `ReadonlyRootfsManager` not really making rootfs writeable (by themylogin)

---

src/middlewared/middlewared/plugins/enclosure.py

I was made aware of an internal system that had been upgraded to 24.10.0 and disks weren't showing up. After investigation I found that `disk.sync_all` was crashing with this error:
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure.py", line 367, in __init__
enclosure = Enclosure(num, data, stat, product_name)
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure.py", line 415, in __init__
self._parse(data)
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure.py", line 426, in _parse
self.map_disks_to_enclosure_slots(is_hseries)
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure.py", line 549, in map_disks_to_enclosure_slots
self.append(info)
File …
```

NAS-132177 / 25.04 / fix disk.sync_all edge-case crash

---

src/middlewared/middlewared/plugins/enclosure.py

I was made aware of an internal system that had been upgraded to 24.10.0 and disks weren't showing up. After investigation I found that `disk.sync_all` was crashing with this error:
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure.py", line 367, in __init__
enclosure = Enclosure(num, data, stat, product_name)
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure.py", line 415, in __init__
self._parse(data)
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure.py", line 426, in _parse
self.map_disks_to_enclosure_slots(is_hseries)
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure.py", line 549, in map_disks_to_enclosure_slots
self.append(info)
File …
```

NAS-132177 / 24.10.0.1 / fix disk.sync_all edge-case crash (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure.py

I was made aware of an internal system that had been upgraded to 24.10.0 and disks weren't showing up. After investigation I found that `disk.sync_all` was crashing with this error:
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure.py", line 367, in __init__
enclosure = Enclosure(num, data, stat, product_name)
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure.py", line 415, in __init__
self._parse(data)
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure.py", line 426, in _parse
self.map_disks_to_enclosure_slots(is_hseries)
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure.py", line 549, in map_disks_to_enclosure_slots
self.append(info)
File …
```

NAS-132177 / 24.10.1 / fix disk.sync_all edge-case crash (by yocalebo)

---

src/middlewared/middlewared/plugins/network.py

This was brought to my attention by support team because a particular customer had run into this scenario. We allow "empty" bond configurations because, most often times, the user will put vlans on top of it. However, some users will mark the bond interface as critical for failover and will NOT mark the child interfaces critical for failover. This paints the false impression that when the bond goes down, a failover event will be generated. This is not the case because we act upon network events for generating failover events. If the bond has no IP address, then it will not generate a failover event and because the child interface isn't marked critical for failover, a failover will not take place.
Original PR: https://github.com/truenas/middleware/pull/14851
Jira URL: …

NAS-132187 / 24.10.1 / prevent empty critical bond interfaces on HA (by yocalebo)

---

src/middlewared/middlewared/plugins/idmap.py
src/middlewared/middlewared/plugins/smb_/sharesec.py

As part of effort to remove places where private methods use legacy schema, this commit replaces @filterable with @filterable_api_method
* smb.sharesec
* idmap

use filterable_api_method in smb.sharesec and idmap

---

src/middlewared/middlewared/plugins/ldap.py
src/middlewared/middlewared/utils/directoryservices/ipa.py
tests/unit/test_directory_services.py

This commit fixes a parsing bug that slipped into the translation of LDAP config into IPA config for electric eel. We had to layer IPA config on LDAP config due to time crunch for the release.

NAS-132192 / 25.04 / Fix incorrect translation of LDAP basedn to realm

---

src/middlewared/middlewared/plugins/apps/ix_apps/query.py
src/middlewared/middlewared/plugins/apps/pull_images.py
src/middlewared/middlewared/plugins/apps/upgrade.py

This PR adds some changes so we now mark custom apps as having an upgrade available if there are image updates available for the custom app.

NAS-132202 / 25.04 / Mark app as having upgrade available if it's a custom app and there are image updates available

---

src/middlewared/middlewared/plugins/apps/ix_apps/query.py
src/middlewared/middlewared/plugins/apps/pull_images.py
src/middlewared/middlewared/plugins/apps/upgrade.py

This PR adds some changes so we now mark custom apps as having an upgrade available if there are image updates available for the custom app.
Original PR: https://github.com/truenas/middleware/pull/14856
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132202

NAS-132202 / 24.10.1 / Mark app as having upgrade available if it's a custom app and there are image updates available (by sonicaj)

---

src/middlewared/middlewared/plugins/jbof/crud.py
src/middlewared/middlewared/plugins/rdma/interface/crud.py

Handle some exceptions so that we more fully tear down a JBOF, even if we can't currently communicate with it.
Original PR: https://github.com/truenas/middleware/pull/14863
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131955

NAS-131955 / 24.10.1 / Removing ES24N shelves left cruft in the database (by bmeagherix)

---

src/middlewared/middlewared/plugins/fcport.py

This change will avoid a `KeyError` for NPIV configurations when ALUA is disabled.

NAS-132270 / 25.04 / Improve fcport.status when ALUA is disabled

---

tests/api2/test_virt_002_instance.py

I dont have a great explanation why, probably nmap-ncat behaves differently and maybe a race condition (I couldn't reproduce locally), but with ubuntu and built-in nc we dont seem to have that problem:
http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1707/#showFailuresLink

NAS-132186 / 25.04 / Fix proxy test

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/pool.py
src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/pool_/dedup.py
src/middlewared/middlewared/plugins/pool_/pool.py
src/middlewared/middlewared/plugins/zfs_/pool_actions.py
tests/api2/test_dedup_pool_table_quota.py

It was requested that we expose ability to prefetch/prune ddt entries and relevant changes have been added to accommodate that. Also it was requested that we preferably prefetch after pool has been imported and those changes have been accommodated as well on both pool import and failover.

NAS-131249 / 25.04 / Add middleware hooks to configure dedup_table* fields

---

src/middlewared/middlewared/plugins/network.py

There is no reason to show USB based NICs on most of our platforms. Currently, the only time a USB NIC shows up is on certain platforms when someone accesses IPMI via a browser session. Discussed with platform team but we can safely ignore these type of NICs universally. This ignores USB based NICs on all platforms that we sell with the exception of the MINI product line. If this isn't hardware we sell, the usb based nics will show up without issue.
Original PR: https://github.com/truenas/middleware/pull/14875
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132271

NAS-132271 / 24.10.1 / ignore USB NICs on enterprise platforms (by yocalebo)

---

src/middlewared/middlewared/plugins/boot_/environments.py

This is changing the datetime object into a string which doesn't match the schema annotation.

NAS-132303 / 25.04 / remove strftime call in boot.environment.query

---

tests/runtest.py

The change that introduced `parse_test_name` broke `--tests` handling as the "api2" prefix was missing.

NAS-132306 / 25.04 / Fix --tests handling

---

src/middlewared/middlewared/plugins/cache.py

Our `api_method` decorator was designed (primarily) for public facing endpoints. However, for a private service like the `CacheService`, there is no reason to go through the boilerplate of adding all the arguments/returns. It's much easier and better (imo) to simply keep it marked private and remove the `@accepts` decorator. I've used builtin annotations to keep some semblance of what argument types are being passed to each method. This was easiest path forward without breaking backwards compatibility. There should be no change in functionality.

NAS-132307 / 25.04 / remove accepts from CacheService plugin

---

src/middlewared/middlewared/plugins/hardware/virt_detection.py

This is a private plugin that uses an upstream provided tool to detect if we're virtualized. This will be used, mostly, in the debug capturing process but also for a future commit (or any for that matter) that depends on determining if we're virtualized.
Original PR: https://github.com/truenas/middleware/pull/14886
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132314

NAS-132314 / 24.10.1 / add hardware.virtualization plugin (by yocalebo)

---

src/middlewared/middlewared/api/base/types/iscsi.py
src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/iscsi_extent.py
src/middlewared/middlewared/plugins/iscsi_/extents.py
tests/api2/test_261_iscsi_cmd.py

Converts the `iscsi.extent` endpoints to the new api paradigm.
----
Clear CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1714/):

NAS-132267 / 25.04 / Convert iscsi.extent.* to new api

---

src/middlewared/middlewared/migration/0010_nvram_attr_vms.py
src/middlewared/middlewared/migration/0012_libvirt_uid_gid.py
src/middlewared/middlewared/plugins/vm/utils.py

After talking with Andrew, we decided to change libvirt's default uid/gid as it has a high potential for a clash with the default uid/gid in place. A uid/gid has been chosen for libvirt which is under 1000 and reduces a potential clash with a user configured uid/gid.

NAS-131695 / 25.04 / Change libvirt default uid/gid

---

src/middlewared/middlewared/plugins/kubernetes_to_docker/secrets_utils.py

This commit makes sure when we are listing secrets of an app from k8s era, we safely handle `UnicodeDecodeError` which can come when a secret potentially gets corrupted (we did this in DF and earlier already when we used to list apps). Such a secret in this case is missed and we get the next secret available for the app.

NAS-132077 / 25.04 / Make sure helm secret is safely serialized when listing k8s backups

---

src/middlewared/middlewared/plugins/kubernetes_to_docker/secrets_utils.py

This commit makes sure when we are listing secrets of an app from k8s era, we safely handle `UnicodeDecodeError` which can come when a secret potentially gets corrupted (we did this in DF and earlier already when we used to list apps). Such a secret in this case is missed and we get the next secret available for the app.
Original PR: https://github.com/truenas/middleware/pull/14890
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132077

NAS-132077 / 24.10.1 / Make sure helm secret is safely serialized when listing k8s backups (by sonicaj)

---

src/middlewared/middlewared/api/v25_04_0/auth.py
src/middlewared/middlewared/plugins/auth.py

This endpoint is now redundant. All known consumers have switched to using `auth.login_ex` for two-factor authentication.

NAS-132140 / 25.04 / Remove auth.two_factor_auth endpoint

---

src/middlewared/middlewared/plugins/apps/crud.py
src/middlewared/middlewared/plugins/apps/ix_apps/query.py

This PR adds changes to account for the case where a custom app might have invalid compose file in place and deletion of that app fails. We only allow it if there are no active resources belonging to that custom app and user has explicitly requested to move forward.

NAS-132216 / 25.04 / Allow deletion of a custom app which has invalid compose file

---

src/middlewared/middlewared/api/v25_04_0/filesystem.py
tests/api2/test_filesystem_setperm_strip_acl.py

The UI team uses the combination of no mode with stripacl to strip ACLs from paths.

NAS-132266 / 25.04 / Allow filesystem.setperm to not have mode specified

---

tests/runtest.py

A previous fix (#14880) did not take account of when an absolute path is provided to `--tests`.  Rectify.
With this the following all work:
```
~/truenas/middleware/tests$ ./runtest.py -v --ip scale3 --interface enp0s8 --password password --test test_mock_remote.py
~/truenas/middleware/tests$ ./runtest.py -v --ip scale3 --interface enp0s8 --password password --test api2/test_mock_remote.py
~/truenas/middleware/tests$ ./runtest.py -v --ip scale3 --interface enp0s8 --password password --tests test_mock_remote.py
~/truenas/middleware/tests$ ./runtest.py -v --ip scale3 --interface enp0s8 --password password --tests api2/test_mock_remote.py
~/truenas/middleware/tests$ ./runtest.py -v --ip scale3 --interface enp0s8 --password password --tests …
```

NAS-132361 / 25.04 / Fix runtest.py when an absolute path is provided to --tests

---

src/middlewared/middlewared/alembic/versions/25.04/2024-10-29_12-43_vm_zvol_serial.py

A migration was added to make VM devices attributes field to be encrypted in EE and backported to FT. However now on FT when migrations are executed, EE migrations run first which makes the field encrypted and then when a migration runs which touches the `vm_device` table, that fails to execute properly as the field is encrypted now.
Make sure we treat `attributes` column as encrypted when running the relevant migration in FT.

NAS-132351 / 25.04 / Fix disk device serial migration

---

src/middlewared/middlewared/api/v25_04_0/acme_dns_authenticator.py
src/middlewared/middlewared/api/v25_04_0/docker.py
src/middlewared/middlewared/api/v25_04_0/pool.py

As pointed out in upstream documentation [here](https://docs.pydantic.dev/latest/api/types/#pydantic.types.conint--__tabbed_1_1), the `conint` function has been deprecated. This PR removes the usages of said function and uses the proper method based on the documentation. There is no change in functionality.

NAS-132420 / 25.04 / The conint function has been deprecated.

---

src/middlewared/middlewared/api/v25_04_0/truenas.py

On a freshly installed nightly image on first login, the EULA is shown to the end-user. However, it's showing a traceback
```
Error: Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 215, in call_method
result = lam._adapt_result(result)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/api/base/server/legacy_api_method.py", line 75, in _adapt_result
return self.adapter.adapt(
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/api/base/handler/version.py", line 100, in adapt
value = validate_model(current_version_model, value)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/api/base/handler/accept.py", line 80, in validate_model
raise verrors from None …
```

NAS-132383 / 25.04 / fix str length error on EULA

---

src/middlewared/middlewared/test/integration/assets/two_factor_auth.py
tests/api2/test_twofactor_auth.py

git cherry-pick -x 402fb58d5aca8db6e0f011addfd4624d85b5df3c
git cherry-pick -x 85571ecd40790f6c2c55e2cc34b5fc9e945e3f58
Original PR: https://github.com/truenas/middleware/pull/14914
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132431

NAS-132431 / 24.10.1 / Fix random false positives in OTP tests (by themylogin)

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

We don't have this platform internally, we have the legacy (the pre 1.0 version model) and so it's impossible to test this otherwise. However, we have a user in the field that has this model that is hitting this error message
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure_/ses_enclosures2.py", line 25, in get_ses_enclosures
rv.append(Enclosure(bsg, f'/dev/{sg.name}', status).asdict())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure_/enclosure_class.py", line 43, in __init__
self.disks_map = self._get_array_device_mapping_info()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure_/enclosure_class.py", line 255, in _get_array_device_mapping_info
for …
```

NAS-132377 / 25.04 / fix MINI-3.0-X vers 1.0 enclosure page

---

src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py

We don't have this platform internally, we have the legacy (the pre 1.0 version model) and so it's impossible to test this otherwise. However, we have a user in the field that has this model that is hitting this error message
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure_/ses_enclosures2.py", line 25, in get_ses_enclosures
rv.append(Enclosure(bsg, f'/dev/{sg.name}', status).asdict())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure_/enclosure_class.py", line 43, in __init__
self.disks_map = self._get_array_device_mapping_info()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/plugins/enclosure_/enclosure_class.py", line 255, in _get_array_device_mapping_info
for …
```

NAS-132377 / 24.10.1 / fix MINI-3.0-X vers 1.0 enclosure page (by yocalebo)

---

src/middlewared/middlewared/api/v25_04_0/api_key.py
src/middlewared/middlewared/plugins/api_key.py
tests/api2/test_api_key.py

* always include `key` in update response. This will be set to None if the key is not being reset
* allow None as a key type in entry with key.

NAS-132460 / 25.04 / fix api_key.update schema

---

src/middlewared/middlewared/alembic/versions/25.04/2024-11-10_12-23_vm_device_dtype.py
src/middlewared/middlewared/plugins/interface/link_address.py
src/middlewared/middlewared/plugins/pool_/dataset_details.py
src/middlewared/middlewared/plugins/pool_/unlock.py
src/middlewared/middlewared/plugins/usage.py
src/middlewared/middlewared/plugins/vm/attachments.py
src/middlewared/middlewared/plugins/vm/clone.py
src/middlewared/middlewared/plugins/vm/devices/cdrom.py
src/middlewared/middlewared/plugins/vm/devices/display.py
src/middlewared/middlewared/plugins/vm/devices/nic.py
src/middlewared/middlewared/plugins/vm/devices/pci.py
src/middlewared/middlewared/plugins/vm/devices/storage_devices.py
src/middlewared/middlewared/plugins/vm/devices/usb.py
src/middlewared/middlewared/plugins/vm/supervisor/supervisor.py
src/middlewared/middlewared/plugins/vm/vm_devices.py
src/middlewared/middlewared/plugins/vm/vm_display_info.py
src/middlewared/middlewared/plugins/vm/vm_lifecycle.py
src/middlewared/middlewared/plugins/vm/vms.py
src/middlewared/middlewared/pytest/unit/plugins/test_interface_link_address.py
src/middlewared/middlewared/pytest/unit/plugins/vm/test_attachments.py
src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_devices_validation.py
src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_devices_xml.py

In order to remove `accepts` from VM plugin, we need to move `dtype` key to inside of `vm_device.attributes` as that is how the new api style models will work with VM devices. However this change is extensive/involved and has been done separately before the actual removal of accepts decorator from VM plugin so that it is easier to review/manage the changes where accepts decorator is removed.

NAS-132402 / 25.04 / Refactor dtype key in VM device attrs

---

src/middlewared/middlewared/plugins/boot_/environments.py
tests/api2/test_boot_environments.py

UI received the following traceback on certain endpoints
```
File "<stdin>", line 1, in <module>
File "/usr/lib/python3/dist-packages/truenas_api_client/legacy.py", line 416, in call
return self.wait(c, callback=callback, job=job, timeout=timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/truenas_api_client/legacy.py", line 435, in wait
raise ValidationErrors(c.extra)
truenas_api_client.exc.ValidationErrors: [EINVAL] result: Input should be a valid dictionary or instance of BootEnvironmentEntry
```
This is because the result annotation didn't match what was being returned. This fixes said issue and also updates the test to be more explicit about the returned objects.

NAS-132462 / 25.04 / Fix schema annotations for new boot.environment plugin

---

src/middlewared/middlewared/api/v25_04_0/iscsi_extent.py

A recent PR (#14868) added a modern API definition for `iscsi.extent.*`   This PR fixes some issues observed.

NAS-132430 / 25.04 / Fix iscsi.extent.* API definition

---

src/middlewared/middlewared/api/v25_04_0/group.py

NSS apis return list of group names, not gids.

NAS-132461 / 25.04 / Fix schema for group.get_group_obj

---

src/middlewared/middlewared/plugins/cloud_backup/sync.py

Patterns can be given when creating a TrueCloud Backup task that will exclude matching directories and files from the backup.
https://restic.readthedocs.io/en/latest/040_backup.html#excluding-files

NAS-131723 / 25.04 / Add exclusion support for TrueCloud backup tasks

---

src/middlewared/middlewared/plugins/cloud_backup/sync.py

Patterns can be given when creating a TrueCloud Backup task that will exclude matching directories and files from the backup.
https://restic.readthedocs.io/en/latest/040_backup.html#excluding-files
Original PR: https://github.com/truenas/middleware/pull/14900
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131723

NAS-131723 / 24.10.1 / Add exclusion support for TrueCloud backup tasks (by creatorcary)

---

src/middlewared/middlewared/etc_files/scst.conf.mako
src/middlewared/middlewared/plugins/iscsi_/alua.py
src/middlewared/middlewared/plugins/iscsi_/scst.py
tests/api2/test_fibre_channel.py

Avoid some fragility when toggling ALUA on.
Found that needed to **skip** the NPIV target in `scst.conf` when `standby_write_empty_config` was true, and add them afterwards.  Avoids a `scstadmin` load error on the (required) subsequent service reload.
Also, **always** write physical port targets to `scst.conf` as these will otherwise be auto-added by SCST - with a potentially clashing `rel_tgt_id`.  CI tests needed to be updated to take account of this change.
Finally, implemented some changes wrt ALUA failover.  Previously all targets were iSCSI, whereas now `iscsi.alua.become_active` and `iscsi.alua.removed_target_extent` need to take slightly different actions depending on the target mode.  This also necessitated some minor (private) API changes in `iscsi.scst`.

NAS-132347 / 25.04 / Fix Fibre Channel ALUA

---

src/middlewared/middlewared/api/base/types/user.py

AD usernames may actually contain large portion of UTF character set.
Example:
```
root@testMYW4RQDK8Q[~]# getent passwd ACME\\Блин
ACME\блин:*:100011617:100000514::/var/empty:/bin/sh
```
This means our validation for names where they may be remote must be very relaxed. To simplify matters I'm simply requiring a minimum length of 1 character. We can tighten up if required in the future.

NAS-132476 / 25.04 / fix validator for remote usernames

---

src/middlewared/middlewared/alert/source/applications.py
src/middlewared/middlewared/plugins/apps/upgrade.py

This PR adds changes to not query all apps when deleting all upgrade alerts for apps, this is useful when pool is being unset or being changed and there is no need to actually query apps at this point (this can also be a cause of failure if user has malformed apps dataset which is another issue but at least he should be able to unset/switch pools).

NAS-132483 / 25.04 / There is no need to query all apps when clearing upgrade alerts for all apps

---

src/middlewared/middlewared/alert/source/applications.py
src/middlewared/middlewared/plugins/apps/upgrade.py

This PR adds changes to not query all apps when deleting all upgrade alerts for apps, this is useful when pool is being unset or being changed and there is no need to actually query apps at this point (this can also be a cause of failure if user has malformed apps dataset which is another issue but at least he should be able to unset/switch pools).
Original PR: https://github.com/truenas/middleware/pull/14938
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132483

NAS-132483 / 24.10.1 / There is no need to query all apps when clearing upgrade alerts for all apps (by sonicaj)

---

src/middlewared/middlewared/plugins/smb.py

A commit to remove the filesystem.acl_is_trivial endpoint introduced a regression for creating a DFS proxy share due to more strict path validation in filesystem.stat. This commit first checks whether the path is internal to TrueNAS before calling stat on it.

NAS-132489 / 25.04 / Fix SMB external paths

---

tests/api2/test_account_privilege_role_private_fields.py
tests/api2/test_pool_dataset_unlock_restart_vms.py

With recent `dtype` changes in vm devices, some integration tests were left out which needed to be updated and have been updated.

NAS-132492 / 25.04 / Fix VM integration test

---

src/middlewared/middlewared/api/v25_04_0/virt.py
src/middlewared/middlewared/plugins/virt/instance_device.py

We can probably improve performance / save cpu cycles if we make description optional in the API call and add context to not call choices multiple times, but might not be worth it. Just let me know.

NAS-132424 / 25.04 / Add description to devices

---

src/freenas/usr/local/libexec/collectd_alert.py
src/middlewared/middlewared/alert/source/collectd.py
src/middlewared/middlewared/alert/source/vmware_login.py
src/middlewared/middlewared/plugins/mail.py

* dont use pickle in collectd_alert.py
* remove unused alert
* dont use pickle in mail.py
* dont use pickel in collectd.py alert
(cherry picked from commit 6ad8c1ce3082b22c0feca364ce52e645fd80d858)
A vulnerability involving python deserialization, CVE-2020-22083, was found and resolved.

NAS-132268 / 13.0-U6.3 / Do not use pickle module unnecessarily (#14945)

---

src/freenas/usr/local/libexec/collectd_alert.py
src/middlewared/middlewared/alert/source/collectd.py
src/middlewared/middlewared/alert/source/vmware_login.py
src/middlewared/middlewared/plugins/mail.py

* dont use pickle in collectd_alert.py
* remove unused alert
* dont use pickle in mail.py
* dont use pickel in collectd.py alert
(cherry picked from commit 6ad8c1ce3082b22c0feca364ce52e645fd80d858)
A vulnerability involving python deserialization, CVE-2020-22083, was found and resolved.

NAS-132268 / 13.0 / Do not use pickle module unnecessarily (#14945)

---

tests/api2/test_legacy_websocket.py

This test is no longer needed since we perform return validation by default for everybody.

NAS-132524 / 25.04 / remove unnecessary test

---

src/middlewared/middlewared/api/v25_04_0/rdma.py
src/middlewared/middlewared/plugins/rdma/rdma.py

1. Ensure we get **all** link choices.
2. We are returning a **list** of cards
(Currently, this API will just be used for `ixdiagnose`.)

NAS-132530 / 25.04 / Fix API for rdma.get_card_choices

---

src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/mail.py

Previous commit a67d4cadb67f6a7ee35e660a5150d0527dc78693 introduced a regression in the `mail.queue` deserialization because we're writing non-json serializable data. Revert the json changes and instead, create a directory (/var/run/middlewared) and chmod to 700 and put the mail file in that directory.

NAS-132268 / 13.0 / fix mail.queue regression

---

src/middlewared/middlewared/plugins/rdma/rdma.py

Users with SHARING_ADMIN role should be able to view and modify NFS services. 
Viewing the available RDMA capabilities should be included.
This PR allows users with the SHARIN_ADMIN role to view RDMA capabilities.

NAS-132501 / 25.04 / Allow share administrators to view the available RDMA capabilities.

---

src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/jbof/crud.py

Found that `vrrp_master` could fail to import pools that were based on ES24n.  Increase timeout dramatically to avoid this.

NAS-132599 / 25.04 / Increase ES24n import timeout

---

src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/jbof/crud.py

Found that `vrrp_master` could fail to import pools that were based on ES24n.  Increase timeout dramatically to avoid this.
Original PR: https://github.com/truenas/middleware/pull/14975
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132599

NAS-132599 / 24.10.1 / Increase ES24n import timeout (by bmeagherix)

---

src/middlewared/middlewared/api/base/server/ws_handler/rpc.py

According to https://www.jsonrpc.org/specification#request_object, the `params` object may be omitted. 
```
params
A Structured value that holds the parameter values to be used during the invocation of the method. This member MAY be omitted.
```
We're crashing with the below traceback
```
[2024/11/19 07:16:10] (ERROR) middlewared.process():251 - Unhandled exception in JSON-RPC message handler
File "/usr/lib/python3/dist-packages/middlewared/api/base/server/ws_handler/rpc.py", line 249, in process
await self.process_message(app, message)
File "/usr/lib/python3/dist-packages/middlewared/api/base/server/ws_handler/rpc.py", line 277, in process_message
asyncio.ensure_future(self.process_method_call(app, id_, method, message["params"]))
~~~~~~~^^^^^^^^^^ …
```

NAS-132605 / 25.04 / params property is optional in JSON-RPC spec

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

If a user downgrades to DF or earlier and he had ix-apps dataset, and he comes back to EE or later, what will happen is that the mountpoint for ix-apps would be reset because of the logic we have in place to reset any custom mountpoints any user might have. So changes have been added to ensure that ix-apps dataset always has a consistent mountpoint set because then EE or later can treat it as apps dataset (if apps are configured) which will result in various errors as it would not be mounted where we want it to be mounted

NAS-132169 / 25.04 / Make sure ix-apps mountpoint is correct

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

If a user downgrades to DF or earlier and he had ix-apps dataset, and he comes back to EE or later, what will happen is that the mountpoint for ix-apps would be reset because of the logic we have in place to reset any custom mountpoints any user might have. So changes have been added to ensure that ix-apps dataset always has a consistent mountpoint set because then EE or later can treat it as apps dataset (if apps are configured) which will result in various errors as it would not be mounted where we want it to be mounted
Original PR: https://github.com/truenas/middleware/pull/14937
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132169

NAS-132169 / 24.10.1 / Make sure ix-apps mountpoint is correct (by sonicaj)

---

src/middlewared/middlewared/plugins/cloud_backup/restic.py

Even with the `--json` flag, not all restic messages are reported in JSON format.
Original PR: https://github.com/truenas/middleware/pull/14974
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132595

NAS-132595 / 24.10.1 / Handle non-JSON progress messages in TrueCloud Backup (by creatorcary)

---

src/middlewared/middlewared/plugins/apps/ix_apps/portals.py

An ipv6 URL must be properly escaped which wasn't being done if a user had specified ipv6 url for a docker app as the app's portal. While proper ipv6 support is not present in EE for docker, this bug from middleware side breaks portal webui button on the UI side.
Properly escape/normalize ipv6 url if that is being used in app portal.

NAS-132071 / 24.10.1 / Fix reporting app portal URI when ipv6 is used

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

Increase the timeout associated with a non-HA ES24n import substantially.
A similar change was recently made for HA in PR #14975
Original PR: https://github.com/truenas/middleware/pull/14986
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132629

NAS-132629 / 24.10.1 / Increase the timeout wrt ES24n import in import_on_boot (by bmeagherix)

---

src/middlewared/middlewared/plugins/support.py

A new contract type was added here: https://github.com/truenas/licenselib/pull/3. Put the proactive logic inside the license library (which seems more appropriate anyways). The PR that adds this new function is: https://github.com/truenas/licenselib/pull/6

NAS-132626 / 25.04 / call proactive_support_allowed()

---

src/middlewared/middlewared/etc_files/netdata/netdata.conf.mako
src/middlewared/middlewared/plugins/reporting/events.py
src/middlewared/middlewared/plugins/reporting/realtime_reporting/cpu.py
src/middlewared/middlewared/plugins/reporting/utils.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_stats_func.py

We have been getting per core CPU stats with netdata which is unnecessary and may not be uniform across all systems. With FT we have made a breaking change to streamline that process and only retrieve collective CPU stats giving us 3 benefits:
1. Streamlining stats for any machine
2. Avoiding doing excessive computation each interval in reporting realtime
3. Reducing disk space as we have reduced the data points we want netdata to collect

NAS-132473 / 25.04 / Refactor realtime CPU stats

---

src/middlewared/middlewared/plugins/apps/port_attachments.py

This PR fixes a problem where when adding application ports to the port attachment delegate, we currently use the IP `0.0.0.0` instead of the specific IP to which the port is bound. This causes issues for users who have created a custom app and bound a port to a specific IP, as they are unable to bind the same port to a different IP.

NAS-131797 / 25.04 / Properly capture IP on which a port is bound to in apps port delegate

---

src/middlewared/middlewared/plugins/apps/port_attachments.py

This PR fixes a problem where when adding application ports to the port attachment delegate, we currently use the IP `0.0.0.0` instead of the specific IP to which the port is bound. This causes issues for users who have created a custom app and bound a port to a specific IP, as they are unable to bind the same port to a different IP.
Original PR: https://github.com/truenas/middleware/pull/14990
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131797

NAS-131797 / 24.10.1 / Properly capture IP on which a port is bound to in apps port delegate (by sonicaj)

---

src/middlewared/middlewared/plugins/config.py

Since user is providing this file and method already replacing our configuration in many ways, the original usage doesn't pose a security risk. This change provides protection against a broken config file rewriting files outside the temporary directory used for extraction and causing undefined system behavior.
This commit uses Samba's safe_tarfile wrapper to extract the file with note to replace once we have a python version from upstream debian that supports the newer tarfile feature.
Original PR: https://github.com/truenas/middleware/pull/14969
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132572

NAS-132572 / 24.10.1 / Safely extract user config (by anodos325)

---

src/middlewared/middlewared/plugins/ldap.py
tests/api2/test_ipa_join.py

Some users may have manually configured IPA integration by generating a keytab in IPA and uploading to our UI in 24.04 and earlier. Since there's no guarantee these keytabs were generated via proper IPA join, we default to legacy LDAP configuration, which is same as pre-24.10 and add an alert that we're basically running with a degraded capacity from what we could have.

NAS-132212 / 25.04 / Improve handling for legacy IPA bind with kerberos principal

---

src/middlewared/middlewared/utils/rootfs.py

With new `systemd-sysext` approach for nvidia drivers, we won't be able to write to `/usr` anymore at all. Fortunately, we only need to write there to temporarily remove `/usr/local/bin/dpkg` which blocks normal `/usr/bin/dpkg`. This issue can be resolved with new  `/usr/share/truenas/sysext-extensions/functioning-dpkg.raw`  (https://github.com/truenas/scale-build/pull/756).
We still keep old behavior if the target `usr` dataset does not belong to the currently running system (i.e. on initramfs updates on upgrade).
Merging this will break installing nvidia drivers and might break configuring FIPS.
Original PR: https://github.com/truenas/middleware/pull/14958
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132516

NAS-132516 / 24.10.2 / Use `/usr/share/truenas/sysext-extensions/functioning-dpkg.raw` to temporarily allow `dpkg` (by themylogin)

---

src/middlewared/middlewared/plugins/iscsi_/auth.py

Was doing reload on `iscsi.auth.create` and `iscsi.auth.update`, but not on `iscsi.auth.delete`.  Rectify.

NAS-132681 / 25.04 / Reload iscsitarget on iscsi.auth.delete

---

src/middlewared/middlewared/plugins/iscsi_/auth.py

git cherry-pick -x 932bfbc35d9c4efce59f01f938c7e04a8943329f
git cherry-pick -x 510930b97aaadde14979666542ec75aee9f5b689
Was doing reload on `iscsi.auth.create` and `iscsi.auth.update`, but not on `iscsi.auth.delete`.  Rectify.
Original PR: https://github.com/truenas/middleware/pull/15006
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132681

NAS-132681 / 24.10.2 / Reload iscsitarget on iscsi.auth.delete (by bmeagherix)

---

tests/api2/test_smb_write_offset.py

We need to validate we can write above 16 TiB offset and that we get properly stopped writing about 64 TiB offset.

NAS-132662 / 25.04 / Add test for maximum SMB valid pwrite range

---

src/middlewared/middlewared/plugins/activedirectory.py

When netbiosalias is set in SMB configuration and omitted from the payload in the AD form, it gets populated as an empty list causing a ValidationError to be raised (because we don't allow changing netbios configuration while AD is enabled). Unfortunately, some howto guides online have recommended users to set the netbiosname and netbios alias to the same value, and as is the way of such things this advice is both unnecessary and detremental. This means that users who followed such guides are now unable to modify their AD configuration through the webui (which no longer sets the netbiosalias by default).
Set the default for netbiosalias to None in the AD plugin so that it does not default to an empty list. None is treated as a special value indicating that the existing netbios aliases …

NAS-132684 / 25.04 / Handle case where netbiosalias is omitted from AD payload

---

tests/api2/test_smb_write_offset.py

We need to validate we can write above 16 TiB offset and that we get properly stopped writing about 64 TiB offset.
Original PR: https://github.com/truenas/middleware/pull/14998
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132662

NAS-132662 / 24.10.2 / Add test for maximum SMB valid pwrite range (by anodos325)

---

src/middlewared/middlewared/plugins/activedirectory.py

When netbiosalias is set in SMB configuration and omitted from the payload in the AD form, it gets populated as an empty list causing a ValidationError to be raised (because we don't allow changing netbios configuration while AD is enabled). Unfortunately, some howto guides online have recommended users to set the netbiosname and netbios alias to the same value, and as is the way of such things this advice is both unnecessary and detremental. This means that users who followed such guides are now unable to modify their AD configuration through the webui (which no longer sets the netbiosalias by default).
Set the default for netbiosalias to None in the AD plugin so that it does not default to an empty list. None is treated as a special value indicating that the existing netbios aliases …

NAS-132684 / 24.10.2 / Handle case where netbiosalias is omitted from AD payload (by anodos325)

---

src/middlewared/middlewared/plugins/activedirectory.py

When netbiosalias is set in SMB configuration and omitted from the payload in the AD form, it gets populated as an empty list causing a ValidationError to be raised (because we don't allow changing netbios configuration while AD is enabled). Unfortunately, some howto guides online have recommended users to set the netbiosname and netbios alias to the same value, and as is the way of such things this advice is both unnecessary and detremental. This means that users who followed such guides are now unable to modify their AD configuration through the webui (which no longer sets the netbiosalias by default).
Set the default for netbiosalias to None in the AD plugin so that it does not default to an empty list. None is treated as a special value indicating that the existing netbios aliases …

NAS-132684 / 24.10.1 / Handle case where netbiosalias is omitted from AD payload (by anodos325)

---

src/middlewared/middlewared/etc_files/scst.conf.mako
src/middlewared/middlewared/plugins/etc.py

Add support for discovery auth:
- Write the `iscsi.auth` user/secret as the `IncomingUser` in _/etc/scst.conf_
- Write a single peeruser/peersecret as the `OutgoingUser` if Mutual CHAP discovery auth has been specified.
- Further, in HA systems write the `internal_portal` so that discovery auth does **not** apply to HA "internal" targets.
----
CI build with no regressions [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1926/) or [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1943/).
New CI tests will be added as part of NAS-130509 (PR #15010)

NAS-130489 / 25.04 / Add support for discovery auth

---

tests/api2/test_261_iscsi_cmd.py
tests/protocols/__init__.py
tests/protocols/iscsi_proto.py

Add a CI unit test `test__discover_from_initiator` that ensures that Discovery auth operates as expected.
It will use `ISCSIDiscover` which is a wrapper around some functionality that we [pushed](https://github.com/python-scsi/cython-iscsi/pull/9) upstream into `cython-iscsi`.

NAS-130509 / 25.04 / Add CI test for discovery auth

---

src/middlewared/middlewared/alert/service/mattermost.py

Mattermost does not render html code sent in
messages. This edit removes/replaces html code from
the message text and adopts the markdown formatting
used by Mattermost.

NAS-132712 / 25.04 / Fix alert text format for Mattermost.

---

src/middlewared/middlewared/alert/service/mattermost.py

Mattermost does not render html code sent in
messages. This edit removes/replaces html code from
the message text and adopts the markdown formatting
used by Mattermost.
Original PR: https://github.com/truenas/middleware/pull/15025
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132712

NAS-132712 / 24.10.2 / Fix alert text format for Mattermost. (by nicodemusjls)

---

src/middlewared/middlewared/alert/service/mattermost.py

Mattermost does not render html code sent in
messages. This edit removes/replaces html code from
the message text and adopts the markdown formatting
used by Mattermost.
Original PR: https://github.com/truenas/middleware/pull/15025
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132712
Original PR: https://github.com/truenas/middleware/pull/15030
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132712

NAS-132712 / 24.10.1 / Fix alert text format for Mattermost. (by nicodemusjls) (by bugclerk)

---

src/middlewared/middlewared/plugins/enclosure_/enums.py

The H30 is exactly the same as H10/H20 so all of the detection logic is in place. Simply need to add the model to the enum and everything else will just work.
Original PR: https://github.com/truenas/middleware/pull/14587
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131410

NAS-131410 / 24.10.2 / add H30 to enclosure plugin (by yocalebo)

---

src/middlewared/middlewared/plugins/cloud_backup/init.py

When a TrueCloud Backup task backup is interrupted, either by a user abort or due to some other condition, a stale lock is left on the Storj repository which prevents any subsequent access to the repository. This change runs `restic unlock` before any repository access to ensure that stale locks are removed first.
Non-stale locks will not be removed since the `--remove-all` flag is not used.

NAS-132612 / 25.04 / Remove stale locks before any TrueCloud Backup operation

---

src/middlewared/middlewared/plugins/zfs_/pool_status.py
tests/api2/test_alert.py
tests/api2/test_zpool_status.py

Someone named one of their zpools `disks`..... A strange zpool name but it caused a key collision in `zpool.status`. Place all zpools underneath a top-level `pools` key to prevent this scenario.

NAS-132742 / 25.04 / fix key collision in zpool.status

---

tests/api2/assets/websocket/pool.py
tests/api2/test_261_iscsi_cmd.py
tests/api2/test_262_iscsi_alua.py
tests/api2/test_fibre_channel.py

Recently saw some **_occasional_** race conditions in tests where would create a zvol and then the subsequent code to use it in an extent complained that it didn't exist.  Rectify with a check/delay.
- Refactor 3 different variants of `zvol` (or `zvol_dataset`) our of their respective test files and create a new version that includes a check/delay for the zvol (will delay up to 5 seconds).
- Refactor all callers as necessary.  (Previously had 2 different ways of specifying size, now just use a MB count).
----
CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2010/) ... has another (unrelated) intermittent error that will be addressed elsewhere/shortly.

NAS-132752 / 25.04 / Refactor out zvol create function and include wait_zvol check

---

src/middlewared/middlewared/rclone/remote/s3.py
src/middlewared/middlewared/rclone/remote/storjix.py

…o in `cloudsync.credentials.verify`
Original PR: https://github.com/truenas/middleware/pull/15052
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132769

NAS-132769 / 24.10.2 / Fix `NOTICE: s3: s3 provider "" not known - please set correctly` als… (by themylogin)

---

src/middlewared/middlewared/plugins/docker/update.py

Accidentially removed by https://github.com/truenas/middleware/pull/15004, requested by UI team

NAS-132775 / 24.10.2 / `docker.nvidia_present`

---

tests/api2/test_audit_sudo.py

We strengthened our security posture by removing 2 `ALL ALL` entries from the sudoers file in fc3a785bb05fa21d5076773de640966c7c29f562. However, this cause a minor regression in the API tests.
Original PR: https://github.com/truenas/middleware/pull/15060
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132806

NAS-132806 / 24.10.2 / fix test_audit_sudo tests (by yocalebo)

---

src/middlewared/middlewared/plugins/disk_/format.py
tests/api2/test_disk_wipe.py

We found that `disk.wipe` wasn't working properly and was subsequently fixed in https://github.com/truenas/middleware/pull/14742. However, when a zpool is created the `disk.format` method is eventually called which is using `libparted`. After some investigation, that library isn't wiping all traces of filesystems on the disk. Since `disk.wipe` was fixed, just remove the `libparted` usage and call the former instead. I've also added an explicit test for this scenario.
Original PR: https://github.com/truenas/middleware/pull/15068
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132816

NAS-132816 / 24.10.1 / Fix disk.format (by yocalebo)

---

src/middlewared/middlewared/api/v25_04_0/filesystem.py
src/middlewared/middlewared/plugins/filesystem.py
src/middlewared/middlewared/utils/filesystem/stat_x.py
tests/api2/test_190_filesystem.py
tests/api2/test_435_smb_registry.py
tests/api2/test_account_privilege_role.py
tests/api2/test_large_message.py

This commit converts the two filesystem API endpoints `filesystem.listdir` and `filesystem.mkdir` to new api_method.
As part of this change, the deprecated way of calling filesystem.mkdir using positional arguments was removed.

NAS-132812 / 25.04 / Convert listdir and mkdir to api_method

---

src/middlewared/middlewared/plugins/enclosure_/sysfs_disks.py

QE team found the H30 drive identification wasn't working. This platform has to be handled specially and it was simply omitted from the drive identify logic. QE confirmed this fixes the behavior.

NAS-132842 / 25.04 / fix H30 drive identification

---

src/middlewared/middlewared/plugins/enclosure_/sysfs_disks.py

QE team found the H30 drive identification wasn't working. This platform has to be handled specially and it was simply omitted from the drive identify logic. QE confirmed this fixes the behavior.
Original PR: https://github.com/truenas/middleware/pull/15082
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132842

NAS-132842 / 24.10.1 / fix H30 drive identification (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/sysfs_disks.py

QE team found the H30 drive identification wasn't working. This platform has to be handled specially and it was simply omitted from the drive identify logic. QE confirmed this fixes the behavior.
Original PR: https://github.com/truenas/middleware/pull/15082
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132842

NAS-132842 / 24.10.2 / fix H30 drive identification (by yocalebo)

---

tests/api2/test_default_locale.py

We should not have any default locale as https://wiki.debian.org/Locale suggests ("If you have users who access the system through ssh, it is recommended that you choose None as your default locale").
Messages like this appear without this file
```
root@truenas[~]# tail -1 /var/log/error
Nov 20 21:17:01 truenas CRON[399613]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directory

NAS-132639 / 25.04 / Add empty `/etc/default/locale` file to be read by `/etc/pam.d/sshd`

---

tests/api2/test_default_locale.py

We should not have any default locale as https://wiki.debian.org/Locale suggests ("If you have users who access the system through ssh, it is recommended that you choose None as your default locale").
Messages like this appear without this file
```
root@truenas[~]# tail -1 /var/log/error
Nov 20 21:17:01 truenas CRON[399613]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directory
Original PR: https://github.com/truenas/middleware/pull/15085
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132639

NAS-132639 / 24.10.2 / Add empty `/etc/default/locale` file to be read by `/etc/pam.d/sshd` (by yocalebo)

---

src/freenas/root/.warning
src/freenas/root/.zlogin
src/middlewared/middlewared/etc_files/motd.mako

This warning originally only displayed in root shell. As users are switching to having multiple admin accounts, we need to provide constructive notice that what they are doing is potentially unsupported and may result in terrible things.

NAS-132846 / 25.04 / Move warning about changes from shell to MOTD

---

src/freenas/root/.warning
src/freenas/root/.zlogin
src/middlewared/middlewared/etc_files/motd.mako

This warning originally only displayed in root shell. As users are switching to having multiple admin accounts, we need to provide constructive notice that what they are doing is potentially unsupported and may result in terrible things.
Original PR: https://github.com/truenas/middleware/pull/15086
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132846

NAS-132846 / 24.10.2 / Move warning about changes from shell to MOTD (by anodos325)

---

src/middlewared/middlewared/plugins/cloud_sync.py

…list requests, etc.)
Original PR: https://github.com/truenas/middleware/pull/15090
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132809

NAS-132809 / 24.10.1 / Only call `get_task_extra_args` for cloud sync tasks (not for bucket … (by themylogin)

---

src/middlewared/middlewared/plugins/keychain.py

We should raise a ValidationError here instead of a CallError.
Original PR: https://github.com/truenas/middleware/pull/15091
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132839

NAS-132839 / 24.10.1 / raise ValidationError instead of CallError (by yocalebo)

---

src/middlewared/middlewared/plugins/keychain.py

We should raise a ValidationError here instead of a CallError.
Original PR: https://github.com/truenas/middleware/pull/15091
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132839
Original PR: https://github.com/truenas/middleware/pull/15097
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132839

NAS-132839 / 24.10.2 / raise ValidationError instead of CallError (by yocalebo) (by bugclerk)

---

tests/api2/test_audit_basic.py

Every once in a while the basic HA audit test would fail.  Possibly because earlier tests generated audit events that confused this test.  Possibly because the remote node was slow to respond.
This PR addresses both conditions by improving the query filter and adding a couple more retry loops.
Also improved the assert output in case more tweaks are necessary.
Test results are [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2069/).

NAS-132195 / 25.04 / Improve audit HA test

---

src/middlewared/middlewared/api/base/types/base/string.py
src/middlewared/middlewared/api/v25_04_0/filesystem.py
src/middlewared/middlewared/plugins/filesystem.py

This commit converts remaining methods in filesystem plugin to the new schema design, and adjusts maximum long string value to match the historic maximum size of a file we receive. We really don't want to handle any strings larger than this in our API.

NAS-132854 / 25.04 / Convert filesystem plugin to new api_method

---

src/middlewared/middlewared/plugins/disk_/format.py

A fix of `disk.format` exposed another issue where-by `disk.wipe` is running `disk.sync <disk>` for every disk that is in the format list. This eventually leads to smartd failing to be restarted because we're restarting the smartd service for every disk that gets formatted. Fix the issue by not restarting smartd for each disk by setting synccache to False.

NAS-132862 / 25.04 / dont synccache in disk.format

---

src/middlewared/middlewared/plugins/disk_/format.py

A fix of `disk.format` exposed another issue where-by `disk.wipe` is running `disk.sync <disk>` for every disk that is in the format list. This eventually leads to smartd failing to be restarted because we're restarting the smartd service for every disk that gets formatted. Fix the issue by not restarting smartd for each disk by setting synccache to False.
Original PR: https://github.com/truenas/middleware/pull/15104
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132862

NAS-132862 / 24.10.1 / dont synccache in disk.format (by yocalebo)

---

src/middlewared/middlewared/plugins/disk_/format.py

A fix of `disk.format` exposed another issue where-by `disk.wipe` is running `disk.sync <disk>` for every disk that is in the format list. This eventually leads to smartd failing to be restarted because we're restarting the smartd service for every disk that gets formatted. Fix the issue by not restarting smartd for each disk by setting synccache to False.
Original PR: https://github.com/truenas/middleware/pull/15104
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132862

NAS-132862 / 24.10.2 / dont synccache in disk.format (by yocalebo)

---

src/middlewared/middlewared/plugins/cloud_backup/restic.py

Passing cloud_backup tests: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2079/testReport/api2/test_008_cloud_backup/
Original PR: https://github.com/truenas/middleware/pull/15105
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132861

NAS-132861 / 24.10.1 / Reduce verbosity of cloud_backup logging (by creatorcary)

---

src/middlewared/middlewared/plugins/cloud_backup/restic.py

Passing cloud_backup tests: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2079/testReport/api2/test_008_cloud_backup/
Original PR: https://github.com/truenas/middleware/pull/15105
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132861

NAS-132861 / 24.10.2 / Reduce verbosity of cloud_backup logging (by creatorcary)

---

src/middlewared/middlewared/api/v25_04_0/keychain.py

Fixes a regression that causes `keychaincredential.setup_ssh_connection` to fail on validation when using an existing private key.
Ideally, we should eliminate the `generate_key` field entirely but this will require a change in the webui if/when we do.

NAS-132869 / 25.04 / fix KeychainCredentialSetupSSHConnectionArgs.private_key

---

src/middlewared/middlewared/plugins/apps/schema_normalization.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_normalize_gpu_options.py

Linked with https://github.com/truenas/apps_validation/pull/58

NAS-132878 / 25.04 / add kfd device flag existence

---

tests/api2/test_disk_wipe.py

Noticed this fail randomly under high CI infrastructure load. Let's robustize it a bit so we don't fail on transient external factors.
Original PR: https://github.com/truenas/middleware/pull/15119
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132885

NAS-132885 / 24.10.1 / robustize test_disk_wipe (by yocalebo)

---

tests/api2/test_disk_wipe.py

Noticed this fail randomly under high CI infrastructure load. Let's robustize it a bit so we don't fail on transient external factors.
Original PR: https://github.com/truenas/middleware/pull/15119
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132885

NAS-132885 / 24.10.2 / robustize test_disk_wipe (by yocalebo)

---

debian/debian/postinst

As mentioned in the ticket, the ipa-epn.service fails to start and is in conflict with our support for IPA.
Disable systemd ipa-epn.service
Safe to backport to 24.10.2

NAS-132640 / 25.04 / Apply systemctl mask to ipa-epn.service

---

src/freenas/root/.zlogin
src/middlewared/middlewared/migration/0013_root_zlogin.py
tests/api2/test_root_zlogin.py

Remove this for a few reasons:
1. we're actively marketing the root account be disabled on TrueNAS (for security reasons)
2. we _only_ run this automatically for the root account and so no other user gets this message
3. we're calling it always (even on non-HA systems)
4. it can block for quite awhile on HA systems depending on the state of HA (unavoidable)
After discussion with support team, we've decided to just remove this to keep the fix simple (instead of trying to figure out how to call this dynamically based on hardware/user/etc).

NAS-132845 / 25.04 / remove .zlogin for root account

---

src/freenas/root/.zlogin
src/middlewared/middlewared/migration/0013_root_zlogin.py
tests/api2/test_root_zlogin.py

Remove this for a few reasons:
1. we're actively marketing the root account be disabled on TrueNAS (for security reasons)
2. we _only_ run this automatically for the root account and so no other user gets this message
3. we're calling it always (even on non-HA systems)
4. it can block for quite awhile on HA systems depending on the state of HA (unavoidable)
After discussion with support team, we've decided to just remove this to keep the fix simple (instead of trying to figure out how to call this dynamically based on hardware/user/etc).
Original PR: https://github.com/truenas/middleware/pull/15118
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132845

NAS-132845 / 24.10.2 / remove .zlogin for root account (by yocalebo)

---

src/middlewared/middlewared/plugins/disk_/disk_info.py
src/middlewared/middlewared/plugins/disk_/gpt_utils.py

We have a subtle race condition whereby when `disk.format` is called it generates a series of `remove -> change -> add` udev events for the partition (`sda1`). When the remove event is generated, the `/dev/disk/by-partuuid` symlink is torn down. This is rather ridiculous because it's prone to race conditions by design. Further investigation showed that by simply opening a parent block device (with an existing partition on it), a `remove -> change -> add` series of events are generated for the device JUST BY SIMPLY CLOSING THE DEVICE AND WRITING NOTHING.
I've come to the (personal) conclusion that udevd is a travesty. ANYWAYS, to try and work around this I do 2 things:
1. just read the block device directly and parse gpt partition information
2. once we've done that, then we will go back …

NAS-132858 / 25.04 / improve disk.format and udev partuuid race

---

src/middlewared/middlewared/plugins/disk_/disk_info.py
src/middlewared/middlewared/plugins/disk_/gpt_utils.py

We have a subtle race condition whereby when `disk.format` is called it generates a series of `remove -> change -> add` udev events for the partition (`sda1`). When the remove event is generated, the `/dev/disk/by-partuuid` symlink is torn down. This is rather ridiculous because it's prone to race conditions by design. Further investigation showed that by simply opening a parent block device (with an existing partition on it), a `remove -> change -> add` series of events are generated for the device JUST BY SIMPLY CLOSING THE DEVICE AND WRITING NOTHING.
I've come to the (personal) conclusion that udevd is a travesty. ANYWAYS, to try and work around this I do 2 things:
1. just read the block device directly and parse gpt partition information
2. once we've done that, then we will go back …

NAS-132858 / 24.10.1 / improve disk.format and udev partuuid race (by yocalebo)

---

src/middlewared/middlewared/plugins/disk_/disk_info.py
src/middlewared/middlewared/plugins/disk_/gpt_utils.py

We have a subtle race condition whereby when `disk.format` is called it generates a series of `remove -> change -> add` udev events for the partition (`sda1`). When the remove event is generated, the `/dev/disk/by-partuuid` symlink is torn down. This is rather ridiculous because it's prone to race conditions by design. Further investigation showed that by simply opening a parent block device (with an existing partition on it), a `remove -> change -> add` series of events are generated for the device JUST BY SIMPLY CLOSING THE DEVICE AND WRITING NOTHING.
I've come to the (personal) conclusion that udevd is a travesty. ANYWAYS, to try and work around this I do 2 things:
1. just read the block device directly and parse gpt partition information
2. once we've done that, then we will go back …

NAS-132858 / 24.10.2 / improve disk.format and udev partuuid race (by yocalebo)

---

src/middlewared/middlewared/plugins/smb.py

This call was removed as part of refactoring to remove the registry configuration and not caught in testing because it would only appear on a reboot.

NAS-132929 / 25.04 / Add back in call to set smb.configured

---

src/middlewared/middlewared/etc_files/proftpd/proftpd.motd.mako

The blank lines in the banner are causing Reolink cameras to fail.
Changing the management of the banner from python to mako introduced blank lines in the banner.
Between Dragonfish and Electric Eel the default banner went from:
`230-Welcome to TrueNAS FTP Server`
to
```
230-
Welcome to TrueNAS FTP Server
```
These extra carriage returns confused the Reolink camera causing login failures.
This PR restores the previous default banner.
NOTE: Without this PR a custom banner will _not_ avoid the extra carriage returns.

NAS-132701 / 25.04 / Clean up FTP banner

---

src/middlewared/middlewared/etc_files/proftpd/proftpd.motd.mako

The blank lines in the banner are causing Reolink cameras to fail.
Changing the management of the banner from python to mako introduced blank lines in the banner.
Between Dragonfish and Electric Eel the default banner went from:
`230-Welcome to TrueNAS FTP Server`
to
```
230-
Welcome to TrueNAS FTP Server
```
These extra carriage returns confused the Reolink camera causing login failures.
This PR restores the previous default banner.
NOTE: Without this PR a custom banner will _not_ avoid the extra carriage returns.
Original PR: https://github.com/truenas/middleware/pull/15148
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132701

NAS-132701 / 24.10.2 / Clean up FTP banner (by mgrimesix)

---

src/middlewared/middlewared/main.py

UI team discovered this because of the new API scheme being implemented. Come to find out, we had a completely separate "pong" handler that wasn't under any type of protections that we enforce for any of our other endpoints. After speaking with the security team, the best is to just remove this. The equivalent is `core.ping`. UI team has transitioned to using this as well.

NAS-132642 / 25.04 / remove unnecessary pong handler

---

src/middlewared/middlewared/api/v25_04_0/vm.py
src/middlewared/middlewared/plugins/pool_/dataset_details.py

With recent shift to pydantic models for VM plugins, we had changed how we were retrieving vm devices which resulted in `pool.dataset.details` not working when disk based vm devices were being used.
Properly retrieve vms which are consuming datasets when retrieving dataset details.

NAS-132905 / 25.04 / Properly retrieve vms in dataset details

---

src/middlewared/middlewared/plugins/enclosure.py

This was (mistakingly) removed in https://github.com/truenas/middleware/pull/15127. Add it back so UI continues to operate.

NAS-132934 / 25.04 / add (back) enclosure.update

---

src/middlewared/middlewared/plugins/cloud_sync.py

Cloud sync task might use up the refresh token and get a new one, and still fail to unrelated reason. We need to store the refresh token that it had put to its config file; otherwise, the next run will not work. This is the only cause of the described issue I can think of.

NAS-132851 / 25.04 / Refresh cloud sync credentials even if cloud sync task fails

---

src/middlewared/middlewared/api/v25_04_0/static_route.py

Similar to how `docker.config` was returning ip objects, this is also returning ip objects. However for the former, `truenas_api_client` had changes in place to convert python objects to serializable objects but that changed the format of the output. For static routes, this resulted in error when we tried to query them
```
[2024/12/08 23:53:59] (ERROR) asyncio.default_exception_handler():1771 - Task exception was never retrieved
future: <Task finished name='Task-1226' coro=<RpcWebSocketHandler.process_method_call() done, defined at /usr/lib/python3/dist-packages/middlewared/api/base/server/ws_handler/rpc.py:279> exception=TypeError('Object of type IPv4Network is not JSON serializable')>
File "/usr/lib/python3/dist-packages/middlewared/api/base/server/ws_h …
```

NAS-132958 / 25.04 / Fix static route entry

---

src/middlewared/middlewared/plugins/smb_/util_smbconf.py
src/middlewared/middlewared/utils/io.py
tests/unit/test_smb_share.py

When io_uring is globally disabled we should omit from share VFS objects.

NAS-132956 / 25.04 / Make smb.conf generation aware of io_uring global enabled

---

src/freenas/usr/lib/netdata/conf.d/python.d.conf
src/freenas/usr/lib/netdata/python.d/truenas_meminfo.chart.py
src/middlewared/middlewared/plugins/reporting/events.py
src/middlewared/middlewared/plugins/reporting/realtime_reporting/arcstat.py
src/middlewared/middlewared/plugins/reporting/realtime_reporting/memory.py
src/middlewared/middlewared/plugins/reporting/utils.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_stats_func.py
src/middlewared/middlewared/utils/metrics/meminfo.py

We had tons of unnecessary metrics in realtime reporting which was extra and caused an extra overhead. With the current changes, what has been done is that we have removed the bloat and added a new memory plugin for netdata and will be using that to retrieve relevant memory datapoints we want.

NAS-132474 / 25.04 / Refactor realtime reporting memory

---

src/middlewared/middlewared/api/base/handler/accept.py
src/middlewared/middlewared/api/base/handler/dump_params.py
src/middlewared/middlewared/api/base/handler/result.py
src/middlewared/middlewared/api/base/handler/version.py
src/middlewared/middlewared/api/base/server/legacy_api_method.py
src/middlewared/middlewared/api/base/server/method.py
src/middlewared/middlewared/job.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/pytest/unit/api/base/server/test_legacy_api_method.py
src/middlewared/middlewared/restful.py
src/middlewared/middlewared/service/core_service.py
tests/api2/test_legacy_websocket.py

Previously, `call_with_audit` was redacting the secrets. This caused issues when its result was passed to the API versions conversion code (as it was trying to validate `port="********"` as integer).

NAS-132676 / 25.04 / Only redact secrets when the method return value is passed to the user

---

src/middlewared/middlewared/api/v25_04_0/smb.py
tests/api2/test_435_smb_registry.py
tests/api2/test_simple_share.py

This fixes two failing auxiliary parameters tests that were caused because the output type of a private API for SMB share parameters was changed from string to a list in some cases.
It also fixes a test regression for case where SMB share precheck is called without arguments.

NAS-132989 / 25.04 / Fix failing SMB tests

---

src/middlewared/middlewared/plugins/hardware/cpu.py

These endpoints were initially added for our performance team to be added so that they can quickly toggle these governor settings to see if it had any impact on the numbers. Instead of converting these to new api, just mark this plugin private. It's not used by UI team and was never designed otherwise. While I'm here, format the file and use an enum to reduce a bunch of statically typed strings.

NAS-132991 / 25.04 / make hardware.cpu plugin private

---

src/middlewared/middlewared/service/config_service.py
tests/api2/test_job_credentials.py

When we have pair of update/do_update methods for a ConfigService we need to pass the authenticated credentials between them so that the latter method is called with appropriate privileges. If this doesn't happen, then in addition to the obvious problem of getting a privileged credential passed to the do_update method we also lose credential information for a job log if the method has a job decorator.

NAS-133007 / 25.04 / Pass app for update method for ConfigService

---

src/middlewared/middlewared/service/config_service.py
tests/api2/test_job_credentials.py

When we have pair of update/do_update methods for a ConfigService we need to pass the authenticated credentials between them so that the latter method is called with appropriate privileges. If this doesn't happen, then in addition to the obvious problem of getting a privileged credential passed to the do_update method we also lose credential information for a job log if the method has a job decorator.
Original PR: https://github.com/truenas/middleware/pull/15173
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133007

NAS-133007 / 24.10.2 / Pass app for update method for ConfigService (by anodos325)

---

src/middlewared/middlewared/service/config_service.py
tests/api2/test_job_credentials.py

When we have pair of update/do_update methods for a ConfigService we need to pass the authenticated credentials between them so that the latter method is called with appropriate privileges. If this doesn't happen, then in addition to the obvious problem of getting a privileged credential passed to the do_update method we also lose credential information for a job log if the method has a job decorator.
Original PR: https://github.com/truenas/middleware/pull/15173
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133007

NAS-133007 / 24.10.1 / Pass app for update method for ConfigService (by anodos325)

---

src/middlewared/middlewared/plugins/disk_/gpt_utils.py

This is crashing with TypeError because I'm returning a boolean instead of honoring the type annotations. Change it to return an empty list to fix the error.
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/disk_/disk_info.py", line 142, in gptid_from_part_type
for i in filter(lambda x: x.part_type_guid == part_type, read_gpt_partitions(disk)):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not iterable

NAS-133021 / 25.04 / fix TypeError in read_gpt_partitions

---

src/middlewared/middlewared/plugins/disk_/gpt_utils.py

This is crashing with TypeError because I'm returning a boolean instead of honoring the type annotations. Change it to return an empty list to fix the error.
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/disk_/disk_info.py", line 142, in gptid_from_part_type
for i in filter(lambda x: x.part_type_guid == part_type, read_gpt_partitions(disk)):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not iterable
Original PR: https://github.com/truenas/middleware/pull/15180
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133021

NAS-133021 / 24.10.1 / fix TypeError in read_gpt_partitions (by yocalebo)

---

src/middlewared/middlewared/plugins/disk_/gpt_utils.py

This is crashing with TypeError because I'm returning a boolean instead of honoring the type annotations. Change it to return an empty list to fix the error.
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/disk_/disk_info.py", line 142, in gptid_from_part_type
for i in filter(lambda x: x.part_type_guid == part_type, read_gpt_partitions(disk)):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not iterable
Original PR: https://github.com/truenas/middleware/pull/15180
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133021

NAS-133021 / 24.10.2 / fix TypeError in read_gpt_partitions (by yocalebo)

---

tests/api2/test_stig.py

The test was not updated when a typo in the error string was fixed during the review process.

NAS-133041 / 25.04 / Fix typo in STIG test

---

src/middlewared/middlewared/plugins/docker/state_management.py

git cherry-pick -x be04dfff9e2327d7c6225b740a426a267522e3c0
git cherry-pick -x a0e98d2bd43065077da8fc44527f38497d3bf0d2
Original PR: https://github.com/truenas/middleware/pull/15179
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133020

NAS-133020 / 25.04 / Remove `nvidia` leftovers (by themylogin)

---

src/middlewared/middlewared/plugins/pool_/pool.py

py-libzfs is updated in https://github.com/truenas/py-libzfs/pull/293 to not retrieve `dedupcached` property along with other hidden zpool properties.

NAS-132988 / 25.04 / Remove dedupcached property

---

src/middlewared/middlewared/plugins/docker/update.py

git cherry-pick -x 797bed1eec2db65c43509a4794f395bb387c7e82
git cherry-pick -x 5f1661434aa23c1bfad72fd4c720740f61e1b70b
Original PR: https://github.com/truenas/middleware/pull/15188
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133038

NAS-133038 / 25.04 / Run `ldconfig` after loading nvidia sysext (by themylogin)

---

src/middlewared/middlewared/plugins/reporting/events.py
src/middlewared/middlewared/plugins/service.py
src/middlewared/middlewared/utils/os.py
tests/unit/test_terminate_pid.py

psutil is expensive in about every way imaginable. This method doesn't require using it so I've simplified the method to use built-in modules provided by python.
1. add validation to `terminate_process` since it allowed terminating pid 0 or middlewared (itself)
2. make it private, there is no reason for this to be a public method (UI, TC doesn't call it)

NAS-133058 / 25.04 / simplify service.terminate_process

---

src/middlewared/middlewared/api/base/types/filesystem.py
src/middlewared/middlewared/api/v25_04_0/ftp.py
src/middlewared/middlewared/async_validators.py
src/middlewared/middlewared/plugins/ftp.py
src/middlewared/middlewared/validators.py

Expanded the function of `check_path_resides_within_volume` to replace the schema check .
Add optional `must_be_dir` bool to check_path_resides_within_volume[_sync]. 
Add directory validation for `anonpath` to FTP update method.
---
Passing CI tests [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2216/testReport/api2.test_200_ftp/).

NAS-133043 / 25.04 / Remove Directory validator from new api schema.

---

src/middlewared/middlewared/plugins/iscsi_/extents.py
src/middlewared/middlewared/plugins/iscsi_/global_linux.py
src/middlewared/middlewared/plugins/pool_/dataset.py
tests/api2/test_261_iscsi_cmd.py

git cherry-pick -x b4b7f7501ca3d512c2af120cd2cd4fef723f8853
git cherry-pick -x 6a93be9263c4bd9b0cc65ab5867892eaded0843b
git cherry-pick -x 0e803cfe2e4bc84a37a3a8a79c066e865a39d361
git reset --hard HEAD~4
git cherry-pick -x bca13acb365ef5e95de7a111af2f78fb061ee4d1
If a SCST extent is based upon a zvol, then keep the extent `ro` setting in sync with the zvol `readonly` property.
- Update extent `ro` prop if zvol `readonly` changes.
- Update zvol `readonly` prop if extent is `ro` changed
- Add unit test `test__target_readonly_extent`
----
- CI test run is [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2190/).
- Also …

NAS-132959 / 24.10.2 / Mark extent read-only if underlying zvol is R/O (by bmeagherix)

---

src/middlewared/middlewared/plugins/system/info.py
src/middlewared/middlewared/utils/cpu.py

We were double-caching CPU information in our system.cpu_info method and the `get_cpu_info` function. This does 3 primary things:
1. stop double-caching this information
2. remove duplicate functions that do the same thing and standardize all callers
3. remove psutil module from `utils/cpu.py`

NAS-133068 / 25.04 / Fix double-caching cpu info

---

src/middlewared/middlewared/plugins/service.py

Allowing negative PIDs would wreak havoc in ways we're not prepared. Let's just prevent negative PIDs altogether.

NAS-133070 / 25.04 / Prevent negative PIDs in terminate_process

---

src/middlewared/middlewared/plugins/failover_/event.py

QE has hit a rather rare, but painful, error whereby the secret seed between the controllers didn't match. To remedy this problem, we take the approach to always sync the pwenc_secret file from the active controller in the backup function. This ensures they stay in sync with one another.

NAS-133074 / 25.04 / always reinitialize pwenc in vrrp_backup

---

src/middlewared/middlewared/plugins/failover_/event.py

QE has hit a rather rare, but painful, error whereby the secret seed between the controllers didn't match. To remedy this problem, we take the approach to always sync the pwenc_secret file from the active controller in the backup function. This ensures they stay in sync with one another.
Original PR: https://github.com/truenas/middleware/pull/15204
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133074

NAS-133074 / 24.10.1 / always reinitialize pwenc in vrrp_backup (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/event.py

QE has hit a rather rare, but painful, error whereby the secret seed between the controllers didn't match. To remedy this problem, we take the approach to always sync the pwenc_secret file from the active controller in the backup function. This ensures they stay in sync with one another.
Original PR: https://github.com/truenas/middleware/pull/15204
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133074
Original PR: https://github.com/truenas/middleware/pull/15206
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133074

NAS-133074 / 24.10.2 / always reinitialize pwenc in vrrp_backup (by yocalebo) (by bugclerk)

---

src/middlewared/middlewared/main.py
src/middlewared/middlewared/webshellapp/webshell.py

This is merely a refactor of the web shell related logic and moving it to its own module to clear up `main.py`. There should be no change in behavior.

NAS-133075 / 25.04 / Move web shell logic to its own module

---

src/middlewared/middlewared/api/base/model.py
src/middlewared/middlewared/api/base/types/fc.py
src/middlewared/middlewared/api/base/types/filesystem.py
src/middlewared/middlewared/api/base/types/string.py
src/middlewared/middlewared/api/base/types/user.py
src/middlewared/middlewared/api/v25_04_0/api_key.py
src/middlewared/middlewared/api/v25_04_0/common.py
src/middlewared/middlewared/api/v25_04_0/ftp.py
src/middlewared/middlewared/api/v25_04_0/iscsi_extent.py
src/middlewared/middlewared/api/v25_04_0/reporting.py
src/middlewared/middlewared/api/v25_04_0/snmp.py
src/middlewared/middlewared/api/v25_04_0/user.py
src/middlewared/middlewared/pytest/unit/api/handler/accept/test_accept_1.py
src/middlewared/middlewared/service/config_service.py
src/middlewared/middlewared/service/crud_service.py

There is no reason to use `typing_extensions` since we can use python's builtin `typing` module.

NAS-133098 / 25.04 / typing_extensions -> typing

---

src/middlewared/middlewared/plugins/apps_images/client.py
src/middlewared/middlewared/plugins/disk_/temperature.py
src/middlewared/middlewared/plugins/support.py
src/middlewared/middlewared/plugins/truecommand/connection.py

async_timeout 3rd party module has been deprecated because the identical functionality exists within python's builtin modules. Use that instead.

NAS-133102 / 25.04 / async_timeout -> asyncio.timeout

---

src/middlewared/middlewared/plugins/failover_/fenced.py
src/middlewared/middlewared/plugins/system/cli.py
src/middlewared/middlewared/utils/os.py

This adds a helper function `get_pids` that allows us to replace the `psutil.process_iter` method. The latter being dramatically more expensive to run. There should be no change in behavior.

NAS-133106 / 25.04 / psutil.process_iter -> get_pids

---

src/middlewared/middlewared/etc_files/audit_setup.py
src/middlewared/middlewared/plugins/etc.py
src/middlewared/middlewared/utils/auditd.py
tests/unit/test_auditd_rules.py

Configure auditd rules depending on middleware stig configuration. These are configured by writing symlinks to the auditd rules.d directory. The actual rules sets are defined in separate git repository and are not modified at runtime. This commit also adds some basic tests.

NAS-133112 / 25.04 / Add auditd rules to middleware configuration

---

src/middlewared/middlewared/plugins/vm/devices/display.py
src/middlewared/middlewared/utils/os.py

Use `get_pids()` in vm/devices/display.py to terminate the web console process.
Jira: https://ixsystems.atlassian.net/browse/NAS-133119

NAS-133119 / 25.04 / remove psutil from devices/display.py

---

tests/unit/test_copytree.py

This commit changes the scope for getting the count of open file descriptors for our copytree tests. This gives more accurate view of where an fd may leak during the test runs and eliminates a potential area for false-positives.

Change scope of getting FD count in unit test fixture

---

src/middlewared/middlewared/utils/os.py

This adds the process name to `PidEntry` so that `get_pids` output is a bit more familiar to consumers.
Jira: https://ixsystems.atlassian.net/browse/NAS-133120

NAS-133120 / 25.04 / add name to PidEntry

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/iscsi_target.py
src/middlewared/middlewared/plugins/iscsi_/targets.py
src/middlewared/middlewared/plugins/iscsi_/utils.py
tests/api2/test_iscsi_auth_network.py

Convert `iscsi.target.*` to new api.
Also needed to update/correct some CI tests now that the underlying API is stricter.  (A similar tightening of API was recently seen wrt network `staticroute`)
---
CI with only _test_iscsi_auth_network.py_ failures [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2301/).  Manually tested the updated test.

NAS-133124 / 25.04 / Convert iscsi.target.* to new api

---

src/middlewared/middlewared/apps/webshell_app.py
src/middlewared/middlewared/utils/os.py

This removes the final user of `psutil`. After investigation (and testing), I realized that someone had already added an `abort()` method to the shell worker thread. This is all that's needed to be called to ensure the `login` parent process AND the immediate child process (the shell) is terminated including all children below it.
I changed to using kill process group id so that it handles all dependents for us instead of generating a list of child processes unnecessarily.

NAS-133125 / 25.04 / remove psutil from webshell_app.py

---

src/middlewared/middlewared/plugins/iscsi_/utils.py

Again, no reason to use bidict in iscsi_/utils.py when we're dealing with a 3x key-value dictionary. We can accomplish exact same behavior natively by sub-classing a dict and adding a property. The users of `AUTHMETHOD_LEGACY_MAP` will not notice a difference.

NAS-133149 / 25.04 / remove bidict from iscsi_/utils.py

---

src/middlewared/middlewared/api/v25_04_0/iscsi_target.py
src/middlewared/middlewared/plugins/iscsi_/targets.py
tests/api2/assets/websocket/iscsi.py
tests/api2/test_261_iscsi_cmd.py

Add an additional optional `delete_extents` parameter to `iscsi.target.delete`
Add iSCSI unit test `test__target_delete_extents`
---
Passing CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2314/).

NAS-133001 / 25.04 / Add flag to delete extents when removing a target

---

src/middlewared/middlewared/api/v25_04_0/user.py
src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/pytest/unit/plugins/test_user_ssh_enabled_validation.py

This PR adds changes to not allow to enable ssh password login for user where 2fa secret has not been configured for the user and fixes a couple of bugs on the user pydantic model.

NAS-132659 / 25.04 / Don't alow to enable ssh password login for user where 2fa secret is not available

---

src/middlewared/middlewared/api/v25_04_0/user.py
src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/pytest/unit/plugins/test_user_ssh_enabled_validation.py

This PR adds changes to not allow to enable ssh password login for user where 2fa secret has not been configured for the user and fixes a couple of bugs on the user pydantic model.
Original PR: https://github.com/truenas/middleware/pull/15157
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132659

NAS-132659 / 24.10.2 / Don't alow to enable ssh password login for user where 2fa secret is not available (by sonicaj)

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/virt_device.py
src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/api/v25_04_0/virt_volume.py
src/middlewared/middlewared/logger.py
src/middlewared/middlewared/plugins/virt/attachments.py
src/middlewared/middlewared/plugins/virt/device.py
src/middlewared/middlewared/plugins/virt/instance.py
src/middlewared/middlewared/plugins/virt/instance_device.py
src/middlewared/middlewared/plugins/virt/utils.py
src/middlewared/middlewared/plugins/virt/volume.py
src/middlewared/middlewared/test/integration/assets/virt.py
tests/api2/test_virt_vm.py

VM support has been added to virt plugin which allows specifying VM based images to be used for VM creation or not using a source image at VM creation and later using an ISO to bootstrap the VM.
For an ISO to be used with a VM, the iso needs to be imported as an incus volume and then that incus volume attached to the virt instance. A CRUD for virt volumes has been added and the ability to import iso as a virt volume which then can later be attached to virt VM instance. Virt volumes are currently only supported for VMs.
While we are here, validation has been improved and some bug fixes have been done wrt USB/GPU devices.

NAS-132946 / 25.04 / Complete VM support in virt plugin

---

tests/api2/test_440_snmp.py

This removes unnecessary lines in the file and fixes imports. No functional change.

NAS-133171 / 25.04 / touch-up test_440_snmp.py

---

tests/api2/test_035_ad_idmap.py

Fix imports and remove superfluous lines from test_035_ad_idmap.py. There is no change in functionality. (passing tests are [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2335/console)

NAS-133179 / 25.04 / touch-up test_035

---

tests/api2/test_port_delegates.py

The port delegate CI test is failing when setting an FTP port.
The problem is previous tests left FTP configured with `onlyanonymous` enabled.  This setting requires a valid path for the anonymous directory.  Additional factor playing into the failure is that the new api method does parameter checking in a slightly different order.
The fix:   Return `onlyanonymous` to false before commencing the failing test.
Passing test here: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2338/

NAS-133186 / 25.04 / Fix port delegate test

---

tests/api2/test_usage_reporting.py

NFS client reporting is not terribly deterministic.
NFSv3 client info can be found in `/var/db/system/nfs/rmtab` and in `ss` output.  The info in `rmtab` is notoriously inaccurate in that it's updated by the client via `mount` and `umount` commands.  Since we currently do no clear `rmtab` this nearly always results in stale entries.  See https://ixsystems.atlassian.net/browse/NAS-131762
NFSv4 clients are connection based, but they use a periodic refresh to remind the server of their presence and there is a call back to notify 'attached' clients.  Thus, after an NFS server start it can take a second or two for all the clients to report their 
status.
Passing test here: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2337/

NAS-133018 / 25.04 / Fix up test to match reality of NFS client reporting.

---

src/middlewared/middlewared/utils/rootfs.py

Cf. https://github.com/truenas/binaries/pull/11

NAS-133110 / 25.04 / add force_usr_rw option to ReadonlyRootfsManager

---

src/middlewared/middlewared/utils/rootfs.py

Cf. https://github.com/truenas/binaries/pull/11
Original PR: https://github.com/truenas/middleware/pull/15243
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133110

NAS-133110 / 24.10.2 / add force_usr_rw option to ReadonlyRootfsManager (by yocalebo)

---

tests/api2/test_261_iscsi_cmd.py
tests/api2/test_262_iscsi_alua.py

Add some `SYNCHRONIZE_CACHE (10)` calls to ALUA tests to make them more reliable wrt data being committed to stable storage.
Also add `test__synchronize_cache` to formally test the behavior.
----
Full CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2341/).  Shorter runs [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2345/) and [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2346/).

NAS-132193 / 25.04 / Improve api2.test_262_iscsi_alua

---

src/middlewared/middlewared/plugins/crypto_/certificates.py

This commit improves validation where we make sure a CSR cannot be added to system's trusted store as that does not actually materialize.

NAS-133181 / 25.04 / Improve validation for adding CSR to system's trusted store

---

src/middlewared/middlewared/plugins/vm/vm_memory_info.py

2c636bc35c8 caused a regression in the test. Instead of returning a float, we need to return an integer.

NAS-133215 / 25.04 / fix failing memory API test

---

src/middlewared/middlewared/plugins/network_/global_config.py
tests/api2/test_nameservers.py

`verrors` is being overwritten and so the `validate_nameservers` method isn't being applied. We're supposed to be preventing localhost from being used as a DNS server. Since the `verrors` object is being overwritten, the validation isn't being applied.
I've fixed the problem of the verrors object being overwritten, and I've also added a test to ensure this doesn't happen again.

NAS-133211 / 25.04 / Fix validate_nameservers()

---

src/middlewared/middlewared/plugins/network_/global_config.py
tests/api2/test_nameservers.py

`verrors` is being overwritten and so the `validate_nameservers` method isn't being applied. We're supposed to be preventing localhost from being used as a DNS server. Since the `verrors` object is being overwritten, the validation isn't being applied.
I've fixed the problem of the verrors object being overwritten, and I've also added a test to ensure this doesn't happen again. 
Original PR: https://github.com/truenas/middleware/pull/15257
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133211

NAS-133211 / 24.10.2 / Fix validate_nameservers() (by yocalebo)

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/iscsi_target_to_extent.py
src/middlewared/middlewared/plugins/iscsi_/target_to_extent.py
tests/api2/assets/websocket/iscsi.py
tests/api2/test_261_iscsi_cmd.py

- Convert `iscsi.targetextent.*` to new API
- Test `iscsi.targetextent.create` with no `lunid`
---
Abridged CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2349/) (one unrelated failure/race)

NAS-133214 / 25.04 / Convert iscsi.targetextent.* to new api

---

src/middlewared/middlewared/plugins/vm/lifecycle.py

Deleting a VM is failing because de-initializing the VM is resulting in a key error due to recent schema changes.
Resolve the key error during the de-initialization process by safely retrieving the keys.

NAS-133222 / 25.04 / Fix VM de-initialisation

---

src/middlewared/middlewared/plugins/apps/ix_apps/lifecycle.py

It was requested that we expose scale version in the metadata provided to app developer so actions can be taken consciously when rendering the relevant compose files.

NAS-133184 / 25.04 / Expose scale version in app metadata

---

src/middlewared/middlewared/etc_files/syslog-ng/syslog-ng.conf.mako

The mako template was inserting a new line instead of a literal newline character. This apparently accidentally works in the syslog-ng configuration, but looks bad.

NAS-133257 / 25.04 / Fix mako formatting of syslog-ng message template

---

src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnaudit.conf.mako
src/middlewared/middlewared/etc_files/syslog-ng/syslog-ng.conf.mako
src/middlewared/middlewared/plugins/audit/utils.py

Enable the af_unix plugin for auditd and configure syslog-ng and middleware to handle messages written
to a syslog-ng unix domain socket for auditd messages.
The application reading auditd messages from af_unix socket and rewriting for syslog-ng consumption is in separate PR.
Once that is merged, tests will be added to tests/unit.

NAS-133244 / 25.04 / Add auditd socket configuration

---

src/middlewared/middlewared/plugins/zfs_/dataset_actions.py
src/middlewared/middlewared/plugins/zfs_/utils.py

This moves the logic that exists in `zfs.dataset.path_to_dataset` to its own function so that consumers don't have to use a process in the process pool to determine this information. There is no change in behavior.
I also added a `paths_to_datasets_impl` method which will be used in https://github.com/truenas/middleware/pull/15247

NAS-133274 / 25.04 / move path_to_dataset outside process pool

---

src/middlewared/middlewared/api/v25_04_0/docker.py
src/middlewared/middlewared/plugins/docker/backup.py
src/middlewared/middlewared/plugins/docker/restore_backup.py
src/middlewared/middlewared/plugins/docker/state_utils.py
src/middlewared/middlewared/plugins/docker/utils.py

This PR adds ability to backup/restore apps and also to take an automatic backup when a system upgrade is performed.

NAS-133226 / 25.04 / Add ability to backup/restore apps

---

src/middlewared/middlewared/etc_files/pam.d/middleware-api-key.mako

This fixes a typo that caused pam authentication failures for API key authentication in nightlies.

NAS-133306 / 25.04 / Fix API key authentication

---

src/middlewared/middlewared/plugins/smb_/util_smbconf.py

This configuration was lost when removing clustering-related registry configuration in Electric Eel.

NAS-133301 / 25.04 / Forcibly disable spotlight-related RPC servers

---

src/middlewared/middlewared/plugins/smb_/util_smbconf.py

This configuration was lost when removing clustering-related registry configuration in Electric Eel.
Original PR: https://github.com/truenas/middleware/pull/15274
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133301

NAS-133301 / 24.10.2 / Forcibly disable spotlight-related RPC servers (by anodos325)

---

src/freenas/usr/local/libexec/disable-rootfs-protection

Users who want to hack on TrueNAS are running into issues where they get an uninformative message when trying to install dev tools.
This commit gives them some hints about what they need to do.

NAS-133318 / 25.04 / Detect when /usr is a system extension when going to dev mode

---

src/freenas/usr/local/libexec/disable-rootfs-protection

Users who want to hack on TrueNAS are running into issues where they get an uninformative message when trying to install dev tools.
This commit gives them some hints about what they need to do.
Original PR: https://github.com/truenas/middleware/pull/15280
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133318

NAS-133318 / 24.10.2 / Detect when /usr is a system extension when going to dev mode (by anodos325)

---

src/middlewared/middlewared/api/base/decorator.py
src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/app.py
src/middlewared/middlewared/api/v25_04_0/app_ix_volume.py
src/middlewared/middlewared/plugins/apps/app_scale.py
src/middlewared/middlewared/plugins/apps/crud.py
src/middlewared/middlewared/plugins/apps/custom_app.py
src/middlewared/middlewared/plugins/apps/ix_volumes.py
src/middlewared/middlewared/plugins/apps/pull_images.py
src/middlewared/middlewared/plugins/apps/resources.py
src/middlewared/middlewared/plugins/apps/rollback.py
src/middlewared/middlewared/plugins/apps/upgrade.py
src/middlewared/middlewared/service/crud_service.py
src/middlewared/middlewared/service/decorators.py

Removes accept style decorator from app plugin.

NAS-131559 / 25.04 / Remove accepts style decorator from apps plugin

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py

These might be important for users to know which uid/gid to use when sharing data between host and container.

NAS-133159 / 25.04 / Expose idmap

---

src/middlewared/middlewared/api/v25_04_0/api_key.py
src/middlewared/middlewared/etc_files/pam.d/middleware-api-key.mako
tests/api2/test_api_key.py

The API key CRUD interface returns the plain-text of the key to be used for authentication in the following scenarios:
1. api_key.create (new api key created)
2. api_key.update (with option specified to renew the key)
Users who do not have the API_KEY_WRITE privilege, but do have general API_KEY_READ access are allowed to create API keys for their own account. This means that the returned plain-text key must not be marked as secret otherwise it will be redacted and not usable. This is not a security concern since plain-text keys are not stored on TrueNAS (they are only returned to account that will be using the key in this case).
This PR also fixes a broken test that should have caught the redacted key value, and also fixes a bug in pam_tdb generation.

NAS-133012 / 25.04 / Fix API keys for restricted admins

---

src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/failover_/nftables.py
src/middlewared/middlewared/plugins/failover_/zpool_cachefile.py

These are private endpoints that don't need to be decorated with @accepts.

NAS-133327 / 25.04 / Remove @accepts from certain failover endpoints

---

src/middlewared/middlewared/logger.py
tests/unit/test_logger.py

This commit ensures that python tracebacks are properly sent to remote syslog server and inserted into our own log files via syslog-ng. Records are converted to single-line and tracebacks and associated stack information are parameterized to allow for easier automated parsing of log entries.
Messages will have format as follows:
`<message> exception=<exception> stack=<stack>`

NAS-133329 / 25.04 / Fix python tracebacks for syslog messages

---

src/middlewared/middlewared/logger.py
tests/unit/test_logger.py

Including a timestamp in the JSON data for python exceptions simplifies parsing.

NAS-133335 / 25.04 / Add timestamp to structured log data

---

src/middlewared/middlewared/plugins/fc/fc_host.py

Fix issues with the `_validate` method used during `fc.fc_host.create` and `fc.fc_host.update`.  The fundamental issue was during an update use the `data` as-is.  (e.g. we do not need to check `wwpn` changes if none are being requested.)
This helps avoid some fragility e.g. if STANDBY node in HA is currently down, we can still update NPIV setting.
----
Short passing CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2438/).

NAS-133249 / 25.04 / Make fc.fc_host._validate more robust vs HA STANDBY unavailable

---

src/middlewared/middlewared/plugins/service_/services/docker.py

By default, Docker does not enable Router Advertisements (RA) for IPv6 networks.  
Enable the forwarding of Router Advertisements (RA) for IPv6 networks by using the sysctl argument `net.ipv6.conf.enp1s0.accept_ra`.  
For more details, you can refer to the following issue:  
[Docker for Linux Issue #844](https://github.com/docker/for-linux/issues/844)

NAS-133227 / 25.04 / Fix docker wiping ipv6 default route

---

src/middlewared/middlewared/logger.py

The asyncssh library unfortunately causes log spam on middleware startup and leaks into /var/log/syslog.

NAS-133337 / 25.04 / Silence CryptographyDeprecationWarning

---

src/middlewared/middlewared/plugins/pool_/dataset.py
tests/api2/test_pool_dataset_user_props.py

There is no way currently to not retrieve user properties when retrieving dataset details from `pool.dataset` namespace, hence changes have been added to make that configurable.

NAS-133056 / 25.04 / Allow not retrieving user props for datasets

---

src/middlewared/middlewared/plugins/virt/global.py
src/middlewared/middlewared/plugins/virt/instance.py
src/middlewared/middlewared/plugins/virt/license.py
src/middlewared/middlewared/pytest/unit/plugins/virt/test_virt_license.py

We need to have a license check in place to not let enterprise consumers consume virt plugin if they are not licensed for it.

NAS-133326 / 25.04 / Add enterprise license check for virt plugin

---

src/middlewared/middlewared/plugins/kerberos.py

* Apply schema to validation error message
* Prevent empty string
* Properly check that file provides at least one keytab entry

NAS-133364 / 25.04 / Improve keytab validation

---

src/middlewared/middlewared/plugins/kerberos.py

* Apply schema to validation error message
* Prevent empty string
* Properly check that file provides at least one keytab entry
Original PR: https://github.com/truenas/middleware/pull/15297
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133364

NAS-133364 / 24.10.2 / Improve keytab validation (by anodos325)

---

src/middlewared/middlewared/apps/file_app.py
src/middlewared/middlewared/apps/webshell_app.py
src/middlewared/middlewared/apps/websocket_app.py

When this was refactored to be a separate file, the json library was changed to one that does not support dumping a python set.

NAS-133372 / 25.04 / Fix legacy websocket API serialization

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/smb.py

This commit switches the SMB and AD plugins to use common validation code for netbios name changes when AD is enabled.

NAS-133167 / 25.04 / Fix netbiosname validation logic if AD enabled

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/smb.py

This commit switches the SMB and AD plugins to use common validation code for netbios name changes when AD is enabled.
Original PR: https://github.com/truenas/middleware/pull/15301
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133167

NAS-133167 / 24.10.2 / Fix netbiosname validation logic if AD enabled (by anodos325)

---

src/middlewared/middlewared/plugins/mail.py

bc57695c1acddeb321748d46a9ad175de2be7980 added oauth support for outlook.com mail users because Microsoft deprecated plain authentication to their servers. A migration was added that conditionally adds the `provider` key to the `oauth` column to the database. Because this is conditional the `provider` key is not guaranteed to exist in the database. We're unsafely checking for the `provider` key everywhere and so during start-up, we're crashing with a `KeyError` during middleware initialization which prevents the parent process from starting. This was seen during QE testing uploading a CORE database to a FT install.
Original PR: https://github.com/truenas/middleware/pull/15304
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133380

NAS-133380 / 25.04 / Fix KeyError preventing middleware from starting (by yocalebo)

---

src/middlewared/middlewared/plugins/audit/backend.py

This avoids hitting process pool early. We just need to eventually get around to pruning the databases.

NAS-133388 / 25.04 / Avoid querying audit config early in middleware startup

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/iscsi_initiator.py
src/middlewared/middlewared/plugins/iscsi_/initiator.py
tests/api2/test_261_iscsi_cmd.py

Convert `iscsi.initiator.*` to new API
Enhanced `test__initiator_group` to include a test that _actually_ exercised an `update`.
----
Passing (wrt iSCSI) CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2464/).

NAS-133391 / 25.04 / Convert iscsi.initiator.* to new API

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/smb.py

* Workgroup should not be allowed to be changed when AD is enabled.
* Fix indentation of block setting that netbios names were changed.

NAS-133396 / 25.04 / Fix regression in AD-related validation

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/smb.py

* Workgroup should not be allowed to be changed when AD is enabled.
* Fix indentation of block setting that netbios names were changed.
Original PR: https://github.com/truenas/middleware/pull/15310
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133396

NAS-133396 / 24.10.2 / Fix regression in AD-related validation (by anodos325)

---

src/middlewared/middlewared/api/base/server/ws_handler/rpc.py
src/middlewared/middlewared/pytest/unit/api/base/server/ws_handler.py

I've been working on investigating why middlewared daemon is taking > 10 seconds to be restarted. During this time, I profiled a running middlewared instance while our full CI test was running against it.
Investigating the flamegraph showed an abnormal amount of time spent in the 3rd party `jsonschema` module.
This is way too much time spent validating messages that adhere to an extremely simple message format (JSON-RPC 2.0). I've added a `validate_message` coroutine that replaces the need to call `jsonschema.validate`. I made it a `staticmethod` so that it could easily be unit tested. I also added unit tests.
This is easy to run some synthetic tests to compare the times before and after the changes. In my tests I'm seeing a ridiculous difference in time. I ran each method a total of 10k …

NAS-133398 / 25.04 / Dramatically speed up processing messages

---

src/middlewared/middlewared/plugins/zfs_/dataset.py
src/middlewared/middlewared/plugins/zfs_/dataset_actions.py
src/middlewared/middlewared/plugins/zfs_/dataset_encryption.py
src/middlewared/middlewared/plugins/zfs_/dataset_quota.py
src/middlewared/middlewared/plugins/zfs_/disks.py
src/middlewared/middlewared/plugins/zfs_/pool.py
src/middlewared/middlewared/plugins/zfs_/pool_actions.py
src/middlewared/middlewared/plugins/zfs_/pool_wait.py
src/middlewared/middlewared/plugins/zfs_/snapshot.py
src/middlewared/middlewared/plugins/zfs_/snapshot_actions.py

The process pool has served us well-enough these many years. It was added because libzfs wasn't thread-safe and because we had some subtle and hard to find memory leaks in py-libzfs. The obvious solution for these problems was to use a process pool. Over the past few years, libzfs and py-libzfs have had numerous improvements. Upstream zfs has made significant improvements in making their api thread-safe. py-libzfs has also had memory leak fixes over the last couple of years.
Furthermore, the `py-libzfs` module that we wrote uses a global mutex at the _module_ level. This is another layer of protection for the sharp-edges about thread-safety. Working on unrelated issues, I had the random idea to disable the process pool and run our entire CI test against it. To my pleasant surprise, the …

NAS-133405 / 25.04 / Disable process pool

---

src/middlewared/middlewared/alembic/versions/25.04/25.04-2025-01-06_17-16_remove-nfs-v4_owner_major.py
src/middlewared/middlewared/plugins/nfs.py
tests/api2/test_300_nfs.py

The v4_owner_major NFS setting is not used in the SCALE product.

NAS-133426 / 25.04 / Remove unused NFS setting: v4_owner_major

---

src/middlewared/middlewared/plugins/audit/backend.py

This avoids hitting process pool early. We just need to eventually get around to pruning the databases.

Avoid querying audit config early in middleware startup (#15307)

---

src/middlewared/middlewared/api/base/server/ws_handler/rpc.py

Does 2 primary things (both of which are still sufficiently unit tested).
1. Move the `TypeError` to `process_message` (caller) so that we can send a formatted message before closing websocket connection
2. In the event `validate_message` fails because it's missing the "id" member, we need to access that member safely (i.e. message.get("id") instead of message["id"])
There is no functional change here. Just better behavior when we receive malformed messages.

NAS-133451 / 25.04 / fix edge-case crashes in rpc.py

---

src/middlewared/middlewared/api/v25_04_0/auth.py
src/middlewared/middlewared/plugins/auth.py
tests/api2/test_authenticator_assurance_level.py

On successful authentication pass the current authenticator level in response message so that API client can determine whether they can generate auth tokens.

NAS-133444 / 25.04 / Expose authenticator level in login_ex response

---

src/freenas/usr/lib/systemd/network/10-enp135_141_s0f0np0_mlx.link
src/freenas/usr/lib/systemd/network/10-enp135_141_s0f1np1_mlx.link
src/freenas/usr/lib/systemd/network/10-enp135_s0f4_cxgb.link
src/freenas/usr/lib/systemd/network/10-enp135_s0f4d1_cxgb.link
src/freenas/usr/lib/systemd/network/10-enp141_s0f4_cxgb.link
src/freenas/usr/lib/systemd/network/10-enp141_s0f4d1_cxgb.link

The same NIC naming peculiarity (for when a certain pci slot being enumerated) on the f-series is a platform quirk, so we need to apply the same NIC renaming logic to our chelsio NIC as well.
NOTE: The Chelsio NIC has 2 NIC ports hanging off the same pci bus and function but I could not find a way to rename based on the "dev_port" attribute. Instead, we just name on parent pci path and INTERFACE name property (which is the original name. Platform team has said this should be fine as an identifier).
While I'm here, I renamed the existing `*.link` files to have `mlx` in the name to (hopefully) help reader understand those are files for the Mellanox NIC.

NAS-132896 / 25.04 / add systemd.link files for f-series chelsio NICs

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/device.py
src/middlewared/middlewared/plugins/device.py

I believe this is our only public endpoint under the `device` namespace so this PR takes care of the `device` plugin.

NAS-133418 / 25.04 / Convert `device.get_info` to new api

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/iscsi_portal.py
src/middlewared/middlewared/plugins/iscsi_/portal.py
tests/api2/assets/websocket/iscsi.py
tests/api2/test_261_iscsi_cmd.py
tests/api2/test_audit_iscsi.py
tests/api2/test_iscsi_auth_network.py

Convert `iscsi.portal.*` to new API
Also remove last vestiges of obsolete `discovery_authmethod` and `discovery_authgroup`.  In SCST these are global rather than being tied to a particular portal.
----
Passing abridged CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2519/).

NAS-133468 / 25.04 / Convert iscsi.portal.* to new API

---

src/middlewared/middlewared/main.py
tests/api2/test_account_privilege_role.py

If the API user call to subscribe to and endpoint whilst specifying arguments.
For example,
```
"virt.instance.metrics:{\"id\": \"test\"}"
```
We should omit the args from the authorization check:
```
"virt.instance.metrics"
```

NAS-133474 / 25.04 / Fix authorization checks for subscriptions with args

---

src/middlewared/middlewared/plugins/docker/update.py

Certain apps have the ability to choose GPUs for various tasks (Plex is a popular one). Users have noticed that plex (and other apps) no longer provide a list of their nvidia gpus. I tracked this down to the simple fact that we're not loading the `nvidia_drm` kernel module. This module is responsible for populating the `/dev/dri` directory with `render` nodes which is subsequently used by apps (like plex).

NAS-133250 / 25.04 / fix loading nvidia kernel modules

---

src/middlewared/middlewared/plugins/directoryservices.py

This was an oversight when adding RBAC to directory services.

NAS-133466 / 25.04 / Add RBAC role for directory sevices status events

---

src/middlewared/middlewared/plugins/docker/update.py

Certain apps have the ability to choose GPUs for various tasks (Plex is a popular one). Users have noticed that plex (and other apps) no longer provide a list of their nvidia gpus. I tracked this down to the simple fact that we're not loading the `nvidia_drm` kernel module. This module is responsible for populating the `/dev/dri` directory with `render` nodes which is subsequently used by apps (like plex).
Original PR: https://github.com/truenas/middleware/pull/15339
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133250

NAS-133250 / 24.10.2 / fix loading nvidia kernel modules (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure_/nvme2.py

This key needs to be added for r30/f-series for the UI to function properly.

NAS-133475 / 25.04 / add front_loaded key to r30

---

src/middlewared/middlewared/plugins/directoryservices.py

This commit changes us from using a simple health check to actually trying to recover directory services during the initialization step. `directoryservices.health.recover` performs a health check first and so the change here is not large (apart from recovery attempt).

NAS-133235 / 25.04 / Make recovery attempt when initializing directory services

---

src/middlewared/middlewared/plugins/directoryservices.py

This commit changes us from using a simple health check to actually trying to recover directory services during the initialization step. `directoryservices.health.recover` performs a health check first and so the change here is not large (apart from recovery attempt).
Original PR: https://github.com/truenas/middleware/pull/15348
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133235

NAS-133235 / 24.10.2 / Make recovery attempt when initializing directory services (by anodos325)

---

src/middlewared/middlewared/plugins/auth.py
tests/api2/test_authenticator_assurance_level.py

We don't allow these for auth and so users shouldn't be allowed to generate them.

NAS-133453 / 25.04 / Prevent users from generating auth tokens when STIG

---

src/middlewared/middlewared/plugins/security/update.py

We really need to make sure admin doesn't lock himself out when enabling GPOS STIG compatibility.

NAS-133470 / 25.04 / Improve validation error message regarding 2FA

---

src/middlewared/middlewared/plugins/zfs_/dataset.py
src/middlewared/middlewared/plugins/zfs_/dataset_actions.py
src/middlewared/middlewared/plugins/zfs_/dataset_encryption.py
src/middlewared/middlewared/plugins/zfs_/dataset_quota.py
src/middlewared/middlewared/plugins/zfs_/disks.py
src/middlewared/middlewared/plugins/zfs_/pool.py
src/middlewared/middlewared/plugins/zfs_/pool_actions.py
src/middlewared/middlewared/plugins/zfs_/pool_wait.py
src/middlewared/middlewared/plugins/zfs_/snapshot.py
src/middlewared/middlewared/plugins/zfs_/snapshot_actions.py

Been keeping an eye on an internal system running with these changes the past couple days and parent process memory consumption slowly grows without stopping. Not surprising since we've been here before. Bring back the process pool to alleviate the memory leak issues. This reverts commit 6c1de368b991d2466a06c6593759445c5512cc7f.

NAS-133489 / 25.04 / Revert "disable process pool (#15314)"

---

src/middlewared/middlewared/plugins/test/mock.py
tests/conftest.py

Previously, the presence of this role was defined by whether `test.set_mock` was called during the middleware lifetime. This yields to partial tests run failing.

NAS-133491 / 25.04 / Always add `MOCK` role when running tests

---

src/middlewared/middlewared/rclone/remote/s3.py

git cherry-pick -x c6ea9b5475b12ee8c966ca0fb57d5bdee950dae6
git cherry-pick -x a13693f9329e2eaafdb692511b7ae9c36a1fcecd
Original PR: https://github.com/truenas/middleware/pull/15354
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133492

NAS-133492 / 24.10.2 / Fix AWS S3 endpoint URL for restic (by themylogin)

---

src/middlewared/middlewared/api/base/server/ws_handler/rpc.py
src/middlewared/middlewared/pytest/unit/api/base/server/test_ws_handler.py

Recent renaming of this test (so that it's actually ran) was done in https://github.com/truenas/middleware/pull/15356. Now that it's being ran, it was failing. During investigation, the fuzzing portion of the tests exposed a minor bug so I fixed that as well.

NAS-133497 / 25.04 / fix test_ws_handler unit test

---

debian/debian/ix-zfs.service

Internally, we have a system where device names for disks (i.e. `sda`) are changing on boot. This isn't that surprising since the kernel doesn't guarantee uniqueness. However, it is surprising when the device name changes and `sed_unlock_all` doesn't even _attempt_ to unlock the disk whose name changed.
After reproducing this in-house 100% of the time, I found that `disk.sed_unlock_all` is being called _before_ `disk.sync_all` is complete. To remedy the situation, I correct boot dependencies for the systemd.unit service files.

NAS-132518 / 25.04 / fix SED disk unlock at boot

---

debian/debian/ix-zfs.service

Internally, we have a system where device names for disks (i.e. `sda`) are changing on boot. This isn't that surprising since the kernel doesn't guarantee uniqueness. However, it is surprising when the device name changes and `sed_unlock_all` doesn't even _attempt_ to unlock the disk whose name changed.
After reproducing this in-house 100% of the time, I found that `disk.sed_unlock_all` is being called _before_ `disk.sync_all` is complete. To remedy the situation, I correct boot dependencies for the systemd.unit service files.
Original PR: https://github.com/truenas/middleware/pull/15360
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132518

NAS-132518 / 24.10.2 / fix SED disk unlock at boot (by yocalebo)

---

src/middlewared/middlewared/api/base/decorator.py
src/middlewared/middlewared/plugins/account_/2fa.py
src/middlewared/middlewared/plugins/account_/builtin_administrator.py
src/middlewared/middlewared/plugins/alert.py
src/middlewared/middlewared/plugins/boot_/environments.py
src/middlewared/middlewared/plugins/cloud_backup/restore.py
src/middlewared/middlewared/plugins/cloud_backup/snapshot.py
src/middlewared/middlewared/plugins/cloud_backup/sync.py
src/middlewared/middlewared/plugins/config.py
src/middlewared/middlewared/plugins/cron.py
src/middlewared/middlewared/plugins/docker/update.py
src/middlewared/middlewared/plugins/enclosure_/enclosure_label.py
src/middlewared/middlewared/plugins/filesystem.py
src/middlewared/middlewared/plugins/init_shutdown_script.py
src/middlewared/middlewared/plugins/keychain.py
src/middlewared/middlewared/plugins/pool_/scrub.py
src/middlewared/middlewared/plugins/snapshot.py
src/middlewared/middlewared/plugins/snapshot_/task_retention.py
src/middlewared/middlewared/plugins/system/lifecycle.py
src/middlewared/middlewared/plugins/truenas.py
src/middlewared/middlewared/plugins/virt/volume.py
src/middlewared/middlewared/pytest/unit/api/base/server/test_legacy_api_method.py
src/middlewared/middlewared/role.py

This commit is in response to regressions that have crept into the product since 24.10 affecting restricted admins roles. To simplify development, middleware will refuse to start if a public api_method is present with the following characteristics:
1. requires authorization
2. requires authentication
3. does not have roles defined
This commit fixes the API definitions of current methods that do not have proper roles definitions.

NAS-133480 / 25.04 / Crash if public api_method does not have roles

---

src/middlewared/middlewared/plugins/failover_/detect_enclosure.py

During early testing of FT on HA, QE found x-series was not working. This is because we're not correctly identifying the nodes position in the head-unit.

NAS-133420 / 25.04 / fix controller position logic for x-series

---

src/middlewared/middlewared/plugins/disk.py
src/middlewared/middlewared/plugins/disk_/sed.py

I need to work on another SED related issue and it will make it easier to move all SED related methods to the `sed.py` file. This just copies and pastes the methods from disk.py to sed.py. There is no change in behavior.

NAS-133506 / 25.04 / move sed methods to sed.py

---

src/middlewared/middlewared/plugins/disk.py
src/middlewared/middlewared/plugins/disk_/sed.py

I need to work on another SED related issue and it will make it easier to move all SED related methods to the `sed.py` file. This just copies and pastes the methods from disk.py to sed.py. There is no change in behavior.
Original PR: https://github.com/truenas/middleware/pull/15365
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133506

NAS-133506 / 24.10.2 / move sed methods to sed.py (by yocalebo)

---

src/middlewared/middlewared/plugins/apps/compose_utils.py

Improves error message when a rate limit is detected.
There are lots of tickets where the generic message to look in the log file appears.
But its just the rate limit making the app install fail.
Example: https://ixsystems.atlassian.net/browse/NAS-133507

NAS-133510 / 25.04 / Improve error message when an app fails to install

---

src/middlewared/middlewared/plugins/apps/compose_utils.py

Improves error message when a rate limit is detected.
There are lots of tickets where the generic message to look in the log file appears.
But its just the rate limit making the app install fail.
Example: https://ixsystems.atlassian.net/browse/NAS-133507
Original PR: https://github.com/truenas/middleware/pull/15371
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133510

NAS-133510 / 24.10.2 / Improve error message when an app fails to install (by stavros-k)

---

src/freenas/usr/lib/netdata/python.d/cputemp.chart.py
src/middlewared/middlewared/plugins/reporting/events.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
src/middlewared/middlewared/plugins/reporting/utils.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py

It was requested by UI that they don't require per core temperature anymore and changes have been made to only have aggregated CPU temperature saved of all cores and similarly retrieved instead of having all the temperature data serialized per core.

NAS-133443 / 25.04 / Only retrieve aggregated CPU temperature

---

src/middlewared/middlewared/plugins/disk_/sed.py
src/middlewared/middlewared/utils/sed.py

sedutil-cli (by default) uses an asinine, non-portable "hashing" mechanism for the password. This means the password you typed on freeBSD to setup the drive will NOT work when given on linux (and vice versa). Since we're now stuck with this head-ache, we'll try again with the `-freebsdCompat` flag.
This does 3 primary things:
1. move the actual logic for unlocking a disk to utility functions inside `utils/sed.py`
2. if we fail to unlock a disk, try again with the `-freebsdCompat` flag
3. unify, simplify, and add comments to`disk.sed_unlock_all` and `disk.sed_unlock` and various other methods that I added
This has been tested on an internal system where we reproduced this issue and there are no regressions, more importantly is that disks initialized on CORE now successfully unlock on …

NAS-133328 / 25.04 / Use -freebsdCompat flag for sedutil-cli

---

src/middlewared/middlewared/alembic/versions/25.04/2025-01-13_20-25_app_registries.py
src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/app_image.py
src/middlewared/middlewared/api/v25_04_0/app_registry.py
src/middlewared/middlewared/etc_files/docker/config.json.py
src/middlewared/middlewared/plugins/app_registry/crud.py
src/middlewared/middlewared/plugins/app_registry/utils.py
src/middlewared/middlewared/plugins/app_registry/validate_registry.py
src/middlewared/middlewared/plugins/apps/compose_utils.py
src/middlewared/middlewared/plugins/apps/ix_apps/docker/images.py
src/middlewared/middlewared/plugins/apps_images/images.py
src/middlewared/middlewared/plugins/apps_images/utils.py
src/middlewared/middlewared/plugins/etc.py
src/middlewared/middlewared/plugins/service_/services/docker.py

It was requested that we allow consumers to log in to different docker registries so consumers can consume registries which might require authentication or also to bypass any rate limits which consumer might be hitting.

NAS-130876 / 25.04 / Allow logging in to different docker registries

---

src/freenas/etc/systemd/system/auditd.service.d/override.conf

This commit adds a systemd unit overrid for the auditd service so that it becomes responsible for upholding the systemd unit that controls the audit message parser.

NAS-133258 / 25.04 / Add auditd systemd unit override

---

src/middlewared/middlewared/api/base/server/ws_handler/rpc.py
src/middlewared/middlewared/pytest/unit/api/base/server/test_ws_handler.py
src/middlewared/middlewared/pytest/unit/utils/test_limits.py
src/middlewared/middlewared/utils/limits.py

The following traceback occurred when the message was `[]`:
```
File "/usr/lib/python3/dist-packages/aiohttp/web_protocol.py", line 477, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/aiohttp/web_app.py", line 559, in _handle
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/aiohttp/web_middlewares.py", line 105, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/aiohttp/web_urldispatcher.py", line 210, in handler_wrapper
result = await result
^^^^^^^^^^^^ …
```

NAS-132669 / 25.04 / Make `parse_message` ensure that the message is a dict

---

src/middlewared/middlewared/api/v25_04_0/rdma.py
src/middlewared/middlewared/plugins/rdma/constants.py
src/middlewared/middlewared/plugins/rdma/rdma.py

Add `iSER` to `rdma.capable_protocols`, using the same criteria as for `NFS(/RDMA)`.

NAS-133536 / 25.04 / Add iSER to rdma.capable_protocols

---

src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py

This enables drive identify on the r10, r20a, r40, r50/b/bm platforms per discussion with QE and platform teams.

NAS-133501 / 25.04 / expose r-series drive identify

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py
tests/api2/test_virt_vm.py

UI requested that we standardize `virt.instance.update` similar to how `virt.instance.create` works and an explicit `enable_vnc` field has been added on that end for `virt.instance.update` to account for this.

NAS-133435 / 25.04 / Standardize vnc fields in virt instance update

---

src/middlewared/middlewared/plugins/iscsi_/targets.py
tests/api2/test_fibre_channel.py

- When deleting a target remove any corresponding `fcport` mapping.  (Fixes foreign key constraint failure.)
- Add `test_target_delete` to test deletion of a mapped fibre channel target
----
Passing (abridged) CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2601/).

NAS-133544 / 25.04 / Delete fcport target mapping on target delete

---

src/freenas/etc/systemd/system/docker.service.d/override.conf
src/middlewared/middlewared/plugins/service_/services/docker.py

This PR adds changes to better handle docker state when HDDs are being used for apps. Basically what was happening was that when HDDs based pool is being used for starting apps, it can take a few minutes to get apps to start - while we were waiting for 2 minutes earlier and then setting our status to failure. Now systemd would after a few minutes have docker start just fine but middleware would report it as being in failed state.
The changes being done here have made sure that middleware reflects systemd status and systemd fails docker service after 15 minutes of waiting for it to start (earlier docker had removed the systemd time limit which meant systemd would not have been marking it as failed to start and would wait).

NAS-133437 / 25.04 / Better handle docker not starting on boot when on HDDs

---

src/middlewared/middlewared/plugins/account_/privilege.py
src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/plugins/docker/state_management.py
src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
src/middlewared/middlewared/plugins/system/__init__.py

Many registered events lack RBAC roles preventing UI from working properly in STIG mode or under restricted admin.

NAS-133570 / 25.04 / define roles for registered middleware events

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py
tests/api2/test_virt_vm.py

Currently to consume iso with virt instances, we have following steps:
1. Create an incus volume which is basically importing iso
2. Create an empty VM
3. Attach the incus volume to VM
4. Reboot the VM
Aim of these changes is to simplify 2/3 and merge it into a single step so it is simpler for consumers.

NAS-133539 / 25.04 / Allow cleaner way to consume ISO with virt VM instances

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/webui_main_dashboard.py
src/middlewared/middlewared/plugins/webui/main_dashboard.py

While I was here working on this, I tested on a non-HA system and saw this endpoint taking ~2 seconds to return. This is because it's calling `failover.call_remote` on all systems (including non-HA). Fix this by only calling that on HA licensed machines.

NAS-133583 / 25.04 / Convert webui.main.dashboard.sys_info to new API

---

src/middlewared/middlewared/api/base/types/__init__.py
src/middlewared/middlewared/api/base/types/network.py
src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/nfs.py
src/middlewared/middlewared/plugins/nfs.py
src/middlewared/middlewared/plugins/nfs_/validators.py
tests/api2/test_300_nfs.py

Convert NFS config to new api.
Added a common 'TcpPort' type.
Addressed additional comments.  Moved all field_validator tests to new validator module in plugins/nfs_.
Updated the CI tests.
Passes NFS CI [tests]( http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2613/)
Ignore the spurrious failure in  test_008_check_root_dataset_settings.

NAS-131665 / 25.04 / Convert NFS config to new api.

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py
tests/api2/test_virt_vm.py

It was requested that we allow bootstrapping a virt VM with a zvol. This is helpful for cases where a VM was created in libvirt and it's OS resides on a zvol and that same VM is to be ported over to virt plugin - this makes the process straight forward.

NAS-133584 / 25.04 / Allow bootstrapping virt VM with zvol

---

src/middlewared/middlewared/plugins/auth.py

We were not generating an audit log entry when an authenticated middleware session calls auth.login* endpoints to change its effective credential.

NAS-133496 / 25.04 / Generate audit trail for when middleware session changes cred

---

src/middlewared/middlewared/api/v25_04_0/auth.py
src/middlewared/middlewared/auth.py
src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/plugins/auth_/authenticate.py
src/middlewared/middlewared/utils/auth.py
tests/api2/test_030_activedirectory.py
tests/api2/test_auth_onetime.py
tests/api2/test_authenticator_assurance_level.py
tests/unit/test_otpw_manager.py

This commit adds an API endpoint for administrator with ACCOUNT_WRITE privileges to create single-use passwords for user accounts that allow the user to authenticate to the truenas server. This is needed for STIG environments to allow administrators to help with creating new user accounts so that the user can authenticate to the TrueNAS server in order to configure two-factor authentication.
The single-use password may be used with the auth.login_ex mechanism ONETIME_PASSWORD.

NAS-133469 / 25.04 / Add ability for administrator to create onetime passwords

---

src/middlewared/middlewared/plugins/audit/audit.py

The SYSTEM audit database records a large number of events since it's being fed by auditd. This means we probably don't want to overload users with its results in our UI.

NAS-133588 / 25.04 / Exclude SYSTEM audit db from generic audit.query

---

src/middlewared/middlewared/etc_files/docker/daemon.json.py

Currently, IPv6 is not being configured by default for Docker networks. This is inconsistent with a previous change where IPv6 was enabled for Docker's main bridge network.  
Ensure that IPv6 is configured by default for all Docker networks.

NAS-133523 / 25.04 / Make sure ipv6 is enabled by default for docker networks

---

src/middlewared/middlewared/plugins/virt/instance.py

By default we have a 5 minute timeout on incus jobs which can not be sufficient when pulling large images. 
Pulling image on incus side is a job on incus and we were waiting for 5 minutes for the job to complete but as that was not sufficient to download large images, the timeout has been increased to make sure we don't cancel the job half way.

NAS-133528 / 25.04 / Increase timeout when pulling incus images on instance creation

---

src/middlewared/middlewared/api/v25_04_0/acme_dns_authenticator.py
src/middlewared/middlewared/plugins/acme_protocol_/authenticators/digitalocean.py
src/middlewared/middlewared/plugins/acme_protocol_/authenticators/factory.py

This PR adds digitalocean ACME Authenticator
Closes: https://forums.truenas.com/t/add-digitalocean-as-acme-dns-authenicator/29879
cc @sonicaj

NAS-133594 / 25.04 / feat: add digitalocean ACME Authenticator

---

src/middlewared/middlewared/apps/webshell_app.py

Allow VM virt shells to be consumed so users can use the UI to get into VM shells.

NAS-133483 / 25.04 / Expose VM virt shells for consumption

---

src/middlewared/middlewared/api/v25_04_0/keychain.py
src/middlewared/middlewared/plugins/keychain.py
src/middlewared/middlewared/plugins/keychain_/ssh_connections.py

This will improve readability of our docs and move away from our old schema definitions/validation.
http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2608/

NAS-132865 / 25.04 / Clean up old validation for `keychaincredential`, make API definitions more precise

---

src/middlewared/middlewared/plugins/disk_/sed.py

SED functionality was moved to its own file in 416f697b2c7 however, it was moved into a class without a `query` method. Since this isn't a CRUDService, this is failing with
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/disk_/sed.py", line 64, in sed_unlock
disk = await self.query([('name', '=', disk_name)], {'extra': {'passwords': True}})
^^^^^^^^^^
AttributeError: 'DiskService' object has no attribute 'query'

NAS-133602 / 24.10.2 / self.query -> self.middleware.call('disk.query')

---

src/middlewared/middlewared/plugins/truenas_connect/update.py

This PR adds changes to default back to system generated cert for TrueNAS once TNC has been disabled. We have logic in place which will see if system generated cert is still valid i.e not expired and if it is not use it, otherwise generate a new one and consume it.

NAS-133587 / 25.04 / Use system generated cert after TNC has been revoked

---

src/middlewared/middlewared/api/v25_04_0/webui_main_dashboard.py

License will be a dict or None.

NAS-133603 / 25.04 / fix type annotation for dashboard.sys_info

---

src/middlewared/middlewared/plugins/cloud_backup/sync.py

Currently our `keep_last` setting only deletes snapshots without removing the files that those snapshots reference (see [restic docs](https://restic.readthedocs.io/en/stable/060_forget.html)). Over time, this can waste a lot of space in the user's Storj repositories.
Note that pruning uses some space in the repository, so pruning may fail if it runs out of available space. Users should heed storage warnings when their available space runs low.

NAS-133482 / 25.04 / Prune restic snapshots after every cloud_backup sync

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/crypto_cert_profiles.py
src/middlewared/middlewared/plugins/crypto_/cert_profiles.py
src/middlewared/middlewared/plugins/truenas_connect/cert_utils.py
src/middlewared/middlewared/plugins/webui/crypto.py

This one is interesting, it's a static set of information that isn't changing but we return it in public methods. I've moved it over to our new api_method scheme.
It's a bit verbose, however, we now get programmatic api generation for each field (instead of copying a docstring that someone may, or may not read) and it's now "protected" between each version of truenas.

NAS-133606 / 25.04 / convert cert/csr profiles to new api

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/crypto_ca_profiles.py
src/middlewared/middlewared/api/v25_04_0/crypto_cert_profiles.py
src/middlewared/middlewared/plugins/crypto_/ca_profiles.py
src/middlewared/middlewared/plugins/crypto_/cert_profiles.py
src/middlewared/middlewared/plugins/webui/crypto.py

Same idea that is being done in https://github.com/truenas/middleware/pull/15411

NAS-133619 / 25.04 / Convert ca_profiles.py to new api

---

src/middlewared/middlewared/api/v25_04_0/app.py
src/middlewared/middlewared/plugins/apps/resources.py
src/middlewared/middlewared/plugins/apps/rollback.py
src/middlewared/middlewared/plugins/apps/upgrade.py
src/middlewared/middlewared/plugins/apps/utils.py
src/middlewared/middlewared/plugins/zfs_/dataset_actions.py
src/middlewared/middlewared/plugins/zfs_/utils.py

This PR adds changes to allow taking snapshots of host paths associated with an app and also allowing them to rollback optionally.

NAS-130088 / 25.04 / Allow taking snapshots of host paths associated with an app

---

src/middlewared/middlewared/role.py

The authentication methods used by TrueNAS connect aren't supported in GPOS STIG mode and so the admins should not be allowed to configure it.

NAS-133626 / 25.04 / Prevent enabling TrueNAS connect while in STIG mode

---

src/middlewared/middlewared/etc_files/krb5.keytab.py
src/middlewared/middlewared/plugins/directoryservices_/activedirectory_join_mixin.py
src/middlewared/middlewared/plugins/kerberos.py
src/middlewared/middlewared/plugins/smb_/constants.py
src/middlewared/middlewared/plugins/smb_/util_smbconf.py
src/middlewared/middlewared/utils/directoryservices/krb5.py
src/middlewared/middlewared/utils/directoryservices/krb5_constants.py

Various winbind / libads parameters and commands changed in samba 4.21 and so we need to adjust.

NAS-133586 / 25.04 / Fix domain join in Samba 4.21

---

src/freenas/usr/lib/systemd/system-preset/10-truenas.preset
src/middlewared/middlewared/etc_files/nscd.conf.mako
tests/unit/test_after_boot_services.py

nscd is not automatically starting at boot.   It should be.
It was `disabled` in `10-truenas.preset` for reasons that are no longer valid. 
Removing the nscd prese disable from `10-truenas.preset` also repairs systems in the field on upgrade.
Add a comment in nscd.conf.mako.
Add a unit test for services at boot.

NAS-133601 / 25.04 / Remove nscd from disable preset.

---

src/middlewared/middlewared/role.py
tests/unit/test_role_manager.py

Add a sanity check that we never grant a READ role access to a CRUD/Config method.
This commit also updates our check on STIG roles to add the TRUENAS_CONNECT role to the expected STIG roles.
This commit also adds a few tests to validate that the role manager is raising expected exceptions in some scenarios.

NAS-133637 / 25.04 / Add role manage sanity check and tests

---

src/middlewared/middlewared/plugins/account_/privilege_roles.py
src/middlewared/middlewared/plugins/cron.py
src/middlewared/middlewared/plugins/init_shutdown_script.py
tests/unit/test_role_manager.py

This commit adds a private API endpoint to dump current role manager contents and adds a unit test to verify that the methods explicitly granted to the FULL_ADMIN role have not changed. This provides coverage for a regression that granted virt write methods in STIG mode to users with FULL_ADMIN privilege.

NAS-133638 / 25.04 / Add unit test for role_manager FULL_ADMIN allowlist

---

src/middlewared/middlewared/api/v25_04_0/__init__.py
src/middlewared/middlewared/api/v25_04_0/iscsi_global.py
src/middlewared/middlewared/plugins/iscsi_/global_linux.py
src/middlewared/middlewared/plugins/iscsi_/iscsi_global.py
src/middlewared/middlewared/plugins/iscsi_/status.py

Convert `iscsi.global.*` to new API
(Note: `max_xmit_data_segment_length` was returned previously, but was not documented.  Now corrected.)
----
Passing abridged CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2648/).

NAS-133641 / 25.04 / Convert iscsi.global.* to new API

---

src/middlewared/middlewared/plugins/account_/privilege.py
src/middlewared/middlewared/role.py
src/middlewared/middlewared/utils/allowlist.py
src/middlewared/middlewared/utils/privilege.py
src/middlewared/middlewared/utils/privilege_constants.py

There are several places in the codebase where we return or evaluate the dictionary `{"method": "*", "resource": "*"}`.
Place this in a privilege_constants file that has minimal imports to avoid potential issues with circular imports and to speed up usage in external applications and unit tests.

NAS-133640 / 25.04 / Use ALLOW_LIST_FULL_ADMIN where practical

---

src/middlewared/middlewared/plugins/crypto_/cert_info.py
src/middlewared/middlewared/plugins/system_general/country.py
src/middlewared/middlewared/utils/country_codes.py

Simplify the country code choices dramatically. When looking at this, I have no idea where `'/etc/iso_3166_2_countries.csv'` is coming from. Debian ships `iso-codes` package which puts this info in `/usr/share/iso-codes/`. So this switches to using what upstream uses instead of an unknown source. Also, add a utility function and call that instead.

NAS-133661 / 25.04 / simplify country_choices endpoints

---

src/middlewared/middlewared/api/v25_04_0/cloud_sync.py
src/middlewared/middlewared/rclone/remote/onedrive.py

Nothing can be done about unusable drives being listed via API, they're indistinguishable from normal drives. At least let's add their names and description (those are `AEEE102E-CFF8-4E2A-89C6-03841FF83500` / `Document library to store albums and album items` and `ODCMetadataArchive` / `ODC Archived Metadata`) to help user identify them.

NAS-133663 / 25.04 / Add OneDrive name and description to the drives list

---

src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/utils/auth.py
src/middlewared/middlewared/utils/origin.py
tests/unit/test_stig.py

We should only return the wildcard allowlist when the root unix domain socket session is not created by an interactive shell session. This is achieved by storing the loginuid for the middleware client pid and checking as part of the check_permission call.
This ensures that STIG restrictions are properly evaluated for users who use midclt, midcli, etc from shell.

NAS-133651 / 25.04 / Reduce situations in which hard-coded root privilege returned

---

src/middlewared/middlewared/plugins/pool_/dataset_details.py

Explicitly pass in valid pools to `pool.dataset.query` so we're not querying boot pool information. Even though `pool.dataset.query` doesn't return boot pool information, it still asks zfs for that information by default. To skip the boot pool, we need to explicitly query the zpools we're interested in. This can, potentially, save a tremendous amount of time on systems that have a large amount of boot environments.

NAS-132908 / 25.04 / optimize pool.dataset.details

---

src/middlewared/middlewared/api/v25_04_0/nfs.py
tests/api2/test_300_nfs.py

The number of hosts and/or networks entries for NFS shares is unbounded.  This allows for undesirable behaviors where users specify _many_ entries.  Long host or network lists cause timeouts when applying the configuration.  We want to discourage this behavior.  Better to use groups, network ranges or directory services.
This PR limits the hosts and networks lists to 42 entries.  This value is somewhat arbitrary, but a good compromise to allow a list just not an excessive list.
Abbreviated tests (ignore failures or timeouts in the setup tests) are [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2661/):

NAS-131451 / 25.04 / Limit the number of host and network entries in NFS share config

---

src/freenas/usr/lib/netdata/python.d/cputemp.chart.py
src/middlewared/middlewared/plugins/reporting/events.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
src/middlewared/middlewared/plugins/reporting/utils.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py

This reverts commit 40b903e3fd7658f6b3ead6b034676da34ef25db3. We want to bring back per core CPU temperature reporting and to make some other amends on this end but to keep the diff clean, the changes where we aggregated them - those have been reverted and rest of the changes for CPU will come along side this.

NAS-133681 / 25.04 / Revert "Only retrieve aggregated CPU temperature"

---

src/middlewared/middlewared/plugins/pool_/unlock.py

This endpoint isn't used anywhere so remove it.

NAS-133687 / 25.04 / remove dead endpoint (unlock_services_restart_choices)

---

src/middlewared/middlewared/plugins/filesystem_/acl.py

This commit introduces additional validation to check whether the path on which user is trying to change permissions is set to readonly. This appears to be a fairly common occurance with our SCALE userbase and so we need to cleanly explain why they can't do this.

NAS-133703 / 25.04 / Raise ValidationError on perm change for readonly paths

---

src/middlewared/middlewared/plugins/apps/migration_utils.py
src/middlewared/middlewared/plugins/apps/upgrade.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_migration_utils.py
src/middlewared/middlewared/pytest/unit/plugins/apps/test_upgrade_values.py

We would like support for app config migrations so app developer can mutate/change key/value pairs of the config while maintaining original consumer's existing configuration to make sure it complies with the new upgraded schema of the app.

NAS-133616 / 25.04 / Introduce support for app config migrations

---

src/middlewared/middlewared/plugins/network_/global_config.py
src/middlewared/middlewared/utils/__init__.py
tests/unit/test_are_indices_in_consecutive_order.py

My present self is often disappointed with my past self. The validation logic I wrote back in 2023 is bad...The logic fails when a 3rd name server is given. It crashes like so:
```
middlewared.service_exception.ValidationErrors: [EINVAL] global_configuration_update.nameserver1.nameserver2.nameserver3.nameserver0: When providing nameservers, they must be provided in consecutive order (i.e. nameserver1, nameserver2, nameserver3)
```
I've noticed (and fixed) 2 issues here:
1. the `schema` variable is being overwritten (it's being passed into this method)
2. the logic for validation consecutiveness was wrong. Add an `are_indices_in_consecutive_order` helper function that is documented and explains what it does.

NAS-133635 / 25.04 / Fix nameserver validation logic

---

src/middlewared/middlewared/plugins/network_/global_config.py
src/middlewared/middlewared/utils/__init__.py

My present self is often disappointed with my past self. The validation logic I wrote back in 2023 is bad...The logic fails when a 3rd name server is given. It crashes like so:
```
middlewared.service_exception.ValidationErrors: [EINVAL] global_configuration_update.nameserver1.nameserver2.nameserver3.nameserver0: When providing nameservers, they must be provided in consecutive order (i.e. nameserver1, nameserver2, nameserver3)
```
I've noticed (and fixed) 2 issues here:
1. the `schema` variable is being overwritten (it's being passed into this method)
2. the logic for validation consecutiveness was wrong. Add an `are_indices_in_consecutive_order` helper function that is documented and explains what it does.
Original PR: https://github.com/truenas/middleware/pull/15423
Jira URL: …

NAS-133635 / 24.10.2 / Fix nameserver validation logic (by yocalebo)

---

src/middlewared/middlewared/plugins/kubernetes_to_docker/secrets_utils.py

Currently, when comparing Helm secret versions, the comparison is being performed as strings. This causes issues with two-digit versions not being compared correctly, leading to older app versions being migrated instead of the correct ones.
Resolve this issue by converting the Helm version strings into integers before performing the comparison. This ensures accurate version comparisons during app migration.

NAS-133717 / 25.04 / Properly compare helm secrets version numbers

---

src/freenas/usr/local/libexec/disable-rootfs-protection

There are some scenarios where we want to skip the check for the root filesystem (for instance in some jenkins pipelines) if the operation has the force parameter set.

NAS-133716 / 25.04 / Skip /usr fs check when disabling protection if forced

---

src/middlewared/middlewared/api/v25_04_0/auth.py
src/middlewared/middlewared/plugins/api_key.py
src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/test/integration/utils/client.py
src/middlewared/middlewared/utils/origin.py
tests/api2/test_api_key.py

This commit adds a new attribute (secure_transport) to ConnectionOrigin to indicate whether the websocket session has secure transport. This flag is set in the following scenarios:
1) AF_UNIX
2) localhost
3) https / wss
New behavior based on security team feedback is introduced in this commit such that API keys will be automatically revoked when used over insecure transport. This is to prevent them being used in replay attacks.

NAS-133053 / 25.04 / Disable API keys if used over insecure transport

---

src/middlewared/middlewared/alert/source/api_key.py
src/middlewared/middlewared/utils/auth.py

Insert dashes into password chunks for one-time passwords so that
```
1_mLHJWwcR2EaxlGOLSuSDO88z
```
becomes
```
1_mLHJWw-cR2Eax-lGOLSu-SDO88z
```
Which is simpler for end-users to read if required.

NAS-133721 / 25.04 / Make onetime password more readable

---

src/middlewared/middlewared/api/v25_04_0/crypto_ca_profiles.py

Regression introduced when moving this to new API schema (https://github.com/truenas/middleware/pull/15417). The profiles need to be under a top-level `CA` key.

NAS-133737 / 25.04 / fix CA profile choices

---

src/middlewared/middlewared/api/v25_04_0/pool_dataset_details.py

Trying to specify all of the fields in this endpoint is proving to be very finicky. Since we're freezing for BETA, let's error on side of caution and have a loose annotation (instead of trying to be narrow).

NAS-133739 / 25.04 / fix pool.dataset.details validation

---

src/middlewared/middlewared/api/v25_04_0/app_registry.py

We should be defaulting to `index.docker.io/v1/` because the URI we are using currently is valid but does not work with docker compose so we should default to one which would work in both cases i.e docker compose and explicitly pulling images

NAS-133752 / 25.04 / Change default URI of docker registry

---

src/middlewared/middlewared/api/__init__.py
src/middlewared/middlewared/api/base/types/urls.py
src/middlewared/middlewared/api/current.py
src/middlewared/middlewared/api/v25_04_0/api_key.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/datastore/connection.py
src/middlewared/middlewared/plugins/datastore/read.py
src/middlewared/middlewared/plugins/zettarepl.py
src/middlewared/middlewared/pytest/unit/test_service_cli_descriptions.py
src/middlewared/middlewared/service/__init__.py
src/middlewared/middlewared/service/core_service.py
src/middlewared/middlewared/service/crud_service.py
src/middlewared/middlewared/service/decorators.py
src/middlewared/middlewared/utils/__init__.py
src/middlewared/middlewared/utils/allowlist.py
src/middlewared/middlewared/utils/plugins.py
src/middlewared/middlewared/worker.py

Previously, ZFS process pool was importing pydantic API. Middleware was waiting for it to finish during the startup (as middleware startup calls ZFS modules). The middleware startup time included 3 pydantic API import waits (middleware itself + 3 ZFS workers).
Now, it's only importing pydantic API once.

NAS-133709 / 25.04 / Do not import middleware API in ZFS process pool

---

src/middlewared/middlewared/plugins/disk_/sed.py

Add missing `await` in `sed_unlock_all`.  Seems to have been introduced in PR #15375
Noticed 
```
/usr/lib/python3/dist-packages/middlewared/plugins/disk_/sed.py:85: RuntimeWarning: coroutin>
```
in `systemctl status middlewared` output.
Add an `await`.

NAS-133759 / 25.04 / Add missing await in sed_unlock_all

---

src/middlewared/middlewared/plugins/virt/volume.py

We improve validation when creating/importing virt volumes here so that we can raise errors in a meaningful way.

NAS-133766 / 25.04 / Improve validation for virt volumes

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py

Allow consumers to specify secure boot for VMs

NAS-133424 / 25.04 / Add support for specifying secureboot for VMs in virt

---

src/middlewared/middlewared/plugins/auth_/2fa.py
src/middlewared/middlewared/test/integration/assets/two_factor_auth.py
tests/api2/test_stig.py

Users should not be able to lock themselves out of the system by disabling 2FA in STIG mode.

NAS-133742 / 25.04 / Expand validation for changing 2FA settings while in STIG mode

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py

We would like the root device's size in incus virt instance to be configurable so users can increase/decrease that based on what their requirement would be.

NAS-133778 / 25.04 / Make root device in virt instance to be configurable on creation

---

src/middlewared/middlewared/plugins/virt/instance.py

We do not want to show those incus images as valid which are cloud based as they require agent to be installed/setup which is obviously not going to be the case

NAS-133772 / 25.04 / Ignore cloud based images in virt plugin for VMs

---

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako

This commit fixes an issue where if nginx is listening to some specific IP other then wildcard and we add wireguard interface address but wireguard interface is not up (whihc happpens on boot) and this results in nginx not starting.

NAS-133334 / 25.10 / Only add wireguard address if wireguard interface is up

---

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako

This commit fixes an issue where if nginx is listening to some specific IP other then wildcard and we add wireguard interface address but wireguard interface is not up (whihc happpens on boot) and this results in nginx not starting.
Original PR: https://github.com/truenas/middleware/pull/15487
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133334

NAS-133334 / 25.04-RC.1 / Only add wireguard address if wireguard interface is up (by sonicaj)

---

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako

This commit fixes an issue where if nginx is listening to some specific IP other then wildcard and we add wireguard interface address but wireguard interface is not up (whihc happpens on boot) and this results in nginx not starting.

Only add wireguard address if wireguard interface is up (#15487)

---

src/freenas/usr/lib/netdata/python.d/cputemp.chart.py
src/freenas/usr/lib/netdata/python.d/truenas_cpu_usage.chart.py
src/middlewared/middlewared/etc_files/netdata/netdata.conf.mako
src/middlewared/middlewared/plugins/reporting/events.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
src/middlewared/middlewared/plugins/reporting/realtime_reporting/cpu.py
src/middlewared/middlewared/plugins/reporting/utils.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_stats_func.py
src/middlewared/middlewared/pytest/unit/utils/test_cpu_usage_util.py
src/middlewared/middlewared/utils/metrics/cpu_usage.py

It was requested that we make some refactoring changes to our CPU reporting. Following points have been catered to:
1. `/proc/stat` has been disabled
2. CPU stats like `user/nice etc` are not being saved/retrieved
3. We were calculating the usage incorrectly which has been addressed
4. Data structure of CPU stats has been changed in realtime reporting
Example payload of what we send in realtime reporting for CPU metrics
```
"cpu": {
"cpu": {
"usage": 33,
"temp": null
},
"cpu0": {
"usage": 100,
"temp": null
},
"cpu1": {
"usage": 1,
"temp": null
},
"cpu2": {
"usage": 0,
"temp": null
}
},
```

NAS-133683 / 25.04 / Refactor CPU reporting

---

src/middlewared/middlewared/etc_files/scst.conf.mako

Ensure we populate `node_name` and `parent_host` for NPIV targets, even if the physical port  does not have a target mapped to it.
Without this SCST could fail to start under certain configurations.
Rename `ha_node_wwpn_for_fcport` to `ha_node_wwpn_for_fcport_or_fchost` to properly the two types of parameters that it can (now) be called with.
----
CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2783/).
Original PR: https://github.com/truenas/middleware/pull/15495
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133834

NAS-133834 / 25.04-RC.1 / Ensure we populate node_name and parent_host for NPIV (by bmeagherix)

---

src/middlewared/middlewared/plugins/auth.py
tests/api2/test_auth_token.py

This commit adds validation that API user request to generate an authentication token for a job only succeeds if the job was initiated by the currently authenticated user.
This commit also adds auditing for when authenticated sessions generate API tokens.
Original PR: https://github.com/truenas/middleware/pull/15508
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133844

NAS-133844 / 25.04-RC.1 / validate download token generation (by anodos325)

---

src/middlewared/middlewared/plugins/account.py
tests/api2/test_password_reset.py

When provisioning new admin users on TrueNAS the sysadmin may provide the user with a one-time password in order to set up their own credentials. This means that OTPW authentication should be allowed to set the associated user's password.

NAS-133762 / 25.10 / Allow password change for OTPW sessions

---

src/middlewared/middlewared/plugins/account.py
tests/api2/test_password_reset.py

When provisioning new admin users on TrueNAS the sysadmin may provide the user with a one-time password in order to set up their own credentials. This means that OTPW authentication should be allowed to set the associated user's password.
Original PR: https://github.com/truenas/middleware/pull/15472
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133762

NAS-133762 / 25.04-RC.1 / Allow password change for OTPW sessions (by anodos325)

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py

It was requested by UI that it would be nice to expose root disk size of virt VMs.
Original PR: https://github.com/truenas/middleware/pull/15512
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133854

NAS-133854 / 25.04-RC.1 / Show root disk size of virt VMs (by Qubad786)

---

src/middlewared/middlewared/plugins/apps/ix_apps/query.py

We are not normalizing ipv6 URL for users who had apps installed before we added proper support for ipv6.
Thank you @mortie for catching this and pushing a PR, much appreciated 🚀

NAS-133856 / 25.10 / Make sure app portal URI is properly normalized

---

src/middlewared/middlewared/plugins/virt/instance.py

It is possible in certain scenarios that incus on instance creation raises an error which we propagate but the instance still does get created - although can't be used until some more settings are tweaked. This is not very reliable and in these cases after discussing with William, we should be nuking the instance if it has been created as `virt.instance.create` had failed.

NAS-133859 / 25.10 / Make sure virt instance is not created if create call fails

---

src/middlewared/middlewared/plugins/virt/instance.py

It is possible in certain scenarios that incus on instance creation raises an error which we propagate but the instance still does get created - although can't be used until some more settings are tweaked. This is not very reliable and in these cases after discussing with William, we should be nuking the instance if it has been created as `virt.instance.create` had failed.
Original PR: https://github.com/truenas/middleware/pull/15515
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133859

NAS-133859 / 25.04-RC.1 / Make sure virt instance is not created if create call fails (by Qubad786)

---

src/middlewared/middlewared/plugins/fcport.py

When a CORE FC config is migrated to SCALE, some manual fixup will be required to remap the targets to the the SCALE equivalents (e.g. `isp0` -> `fc0`).  In the meantime we do not want `fcport.status` to crash because this will prevent the UI from displaying the _Fibre Channel Ports_ tab.

NAS-133862 / 25.10 / Prevent fcport.status exception when CORE config not migrated

---

src/middlewared/middlewared/etc_files/scst.conf.mako
tests/api2/test_fibre_channel.py

A recent PR (#15495) ensured that we added `node_name` and `parent_host` for NPIV targets.  However the CI test was not updated to reflect this, leading to CI test failures (e.g. [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2837/))
Update the test to include `node_name` and `parent_host` for NPIV targets.
Further, noticed that previous PR did **not** make the change for non-HA systems.  Rectify.
With these changes the CI test pass against both HA and non-HA systems.

NAS-133885 / 25.10 / More Fibre Channel NPIV fixes

---

src/middlewared/middlewared/etc_files/scst.conf.mako
tests/api2/test_fibre_channel.py

A recent PR (#15495) ensured that we added `node_name` and `parent_host` for NPIV targets.  However the CI test was not updated to reflect this, leading to CI test failures (e.g. [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2837/))
Update the test to include `node_name` and `parent_host` for NPIV targets.
Further, noticed that previous PR did **not** make the change for non-HA systems.  Rectify.
With these changes the CI test pass against both HA and non-HA systems.
Original PR: https://github.com/truenas/middleware/pull/15527
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133885

NAS-133885 / 25.04-RC.1 / More Fibre Channel NPIV fixes (by bmeagherix)

---

src/middlewared/middlewared/plugins/fcport.py

When a CORE FC config is migrated to SCALE, some manual fixup will be required to remap the targets to the the SCALE equivalents (e.g. `isp0` -> `fc0`).  In the meantime we do not want `fcport.status` to crash because this will prevent the UI from displaying the _Fibre Channel Ports_ tab.
Original PR: https://github.com/truenas/middleware/pull/15521
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133862

NAS-133862 / 25.04-RC.1 / Prevent fcport.status exception when CORE config not migrated (by bmeagherix)

---

src/middlewared/middlewared/utils/disks_/__init__.py
src/middlewared/middlewared/utils/disks_/get_disks.py
src/middlewared/middlewared/utils/disks_/private_utils.py

We need to clean up how we enumerate disks. The SED investigations have exposed some very obvious issues in this area. This is the first step at adding stand-alone functions for this task. Please note that there is some duplicate functionality spread out all over our code in this area, but this will be used as the "source" moving forward. Most importantly, however, is that we have an oustanding SED unlock issue that we need to address but we need the `get_disks` function that I've written in here first.
On an internal system with ~1.2k+ disks, this takes ~0.23 seconds to complete. That's pretty darn good since it enumerates the serial AND "lunid" information of each disk in real-time. Careful reviewers will note that it uses the udevd database which is not the end of the world. Udevd does …

NAS-133888 / 25.10 / Initial round of disk enumeration improvements

---

src/middlewared/middlewared/api/v25_04_0/user.py
src/middlewared/middlewared/plugins/account_/2fa.py
tests/unit/test_role_manager.py

This commit removes several 2FA-related public endpoints from the API as they are unused by the UI team and are of dubious benefit.
The API response for resetting a user's 2FA token now includes the token in the response. This simplifies the task for API users to generate a 2FA token for a user and presenting it for use by removing the necessity to call `auth.me` after generating the token.

NAS-133899 / 25.10 / Reduce number of 2FA public endpoints

---

src/middlewared/middlewared/api/v25_04_0/user.py
src/middlewared/middlewared/plugins/account_/2fa.py
tests/unit/test_role_manager.py

This commit removes several 2FA-related public endpoints from the API as they are unused by the UI team and are of dubious benefit.
The API response for resetting a user's 2FA token now includes the token in the response. This simplifies the task for API users to generate a 2FA token for a user and presenting it for use by removing the necessity to call `auth.me` after generating the token.

NAS-133899 / 25.04 / Reduce number of 2FA public endpoints (#15533)

---

src/middlewared/middlewared/plugins/zfs_/utils.py

https://github.com/truenas/middleware/pull/15247 caused a regression because it lazy imports the BOOT_POOL_NAME module variable. Seems like the usage plugin is being loaded before this is being set so call path ends up crashing like so:
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/zfs_/utils.py", line 362, in path_to_dataset_impl
if is_child(ds_name, BOOT_POOL_NAME):
File "/usr/lib/python3/dist-packages/middlewared/utils/path.py", line 156, in is_child
if os.path.isabs(child) or os.path.isabs(parent):
^^^^^^^^^^^^^^^^^^^^^
File "<frozen posixpath>", line 62, in isabs
TypeError: expected str, bytes or os.PathLike object, not NoneType
"""
The above exception was the direct cause of the following exception: …
```

NAS-133918 / 25.10 / fix usage plugin crash

---

src/middlewared/middlewared/plugins/zfs_/utils.py

https://github.com/truenas/middleware/pull/15247 caused a regression because it lazy imports the BOOT_POOL_NAME module variable. Seems like the usage plugin is being loaded before this is being set so call path ends up crashing like so:
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/zfs_/utils.py", line 362, in path_to_dataset_impl
if is_child(ds_name, BOOT_POOL_NAME):
File "/usr/lib/python3/dist-packages/middlewared/utils/path.py", line 156, in is_child
if os.path.isabs(child) or os.path.isabs(parent):
^^^^^^^^^^^^^^^^^^^^^
File "<frozen posixpath>", line 62, in isabs
TypeError: expected str, bytes or os.PathLike object, not NoneType
"""
The above exception was the direct cause of the following exception: …
```

NAS-133918 / 25.04-RC.1 / fix usage plugin crash (by yocalebo)

---

src/middlewared/middlewared/plugins/disk.py
src/middlewared/middlewared/plugins/disk_/sed.py

git cherry-pick -x 1862a8c0964c824148fbe52b5402d102fca45464
git cherry-pick -x 3231a7c621875d2f54743b86955acb1ac65b8e76
git cherry-pick -x d07547ba67fdea74f757bbcd76f3d608b433894c
git cherry-pick -x ea8042877db897741c79340249692c54f5e2cc01
Original PR: https://github.com/truenas/middleware/pull/15531
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133892
Original PR: https://github.com/truenas/middleware/pull/15532
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133892

NAS-133892 / 25.10 / Unlock SED drives using disk `real_name` (by themylogin) (by bugclerk)

---

src/middlewared/middlewared/plugins/pwenc.py

When `pwenc_secret` is missing, complex data structures are replaced with empty arrays/dictionaries, resulting in various crashes. The only remedy is to wipe out the affected tables entirely.

NAS-133757 / 25.10 / Prevent crashes when `pwenc_secret` is missing

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py

This is required to tell whether or not secure boot option for instance should be allowed.

NAS-133959 / 25.10 / Add `secureboot` to image choices

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py

This is required to tell whether or not secure boot option for instance should be allowed.
Original PR: https://github.com/truenas/middleware/pull/15530
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133959

NAS-133959 / 25.04-BETA.1 / Add `secureboot` to image choices (by william-gr)

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py

This is required to tell whether or not secure boot option for instance should be allowed.
Original PR: https://github.com/truenas/middleware/pull/15530
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133959

NAS-133959 / 25.04-RC.1 / Add `secureboot` to image choices (by william-gr)

---

src/freenas/usr/lib/netdata/python.d/cputemp.chart.py
src/freenas/usr/lib/netdata/python.d/truenas_cpu_usage.chart.py
src/middlewared/middlewared/etc_files/netdata/netdata.conf.mako
src/middlewared/middlewared/plugins/reporting/events.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
src/middlewared/middlewared/plugins/reporting/realtime_reporting/cpu.py
src/middlewared/middlewared/plugins/reporting/utils.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_stats_func.py
src/middlewared/middlewared/pytest/unit/utils/test_cpu_usage_util.py
src/middlewared/middlewared/utils/metrics/cpu_usage.py

It was requested that we make some refactoring changes to our CPU reporting. Following points have been catered to:
1. `/proc/stat` has been disabled
2. CPU stats like `user/nice etc` are not being saved/retrieved
3. We were calculating the usage incorrectly which has been addressed
4. Data structure of CPU stats has been changed in realtime reporting
Example payload of what we send in realtime reporting for CPU metrics
```
"cpu": {
"cpu": {
"usage": 33,
"temp": null
},
"cpu0": {
"usage": 100,
"temp": null
},
"cpu1": {
"usage": 1,
"temp": null
},
"cpu2": {
"usage": 0,
"temp": null
}
},
```
Original PR: https://github.com/truenas/middleware/pull/15445
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133683

NAS-133683 / 25.04-RC.1 / Refactor CPU reporting (by Qubad786)

---

src/middlewared/middlewared/plugins/catalog/apps_util.py
src/middlewared/middlewared/pytest/unit/plugins/catalog/test_min_max_scale_version_update.py

We likely need to make a copy of `app_metadata` to `chart_metadata` in all the generated `app_versions.json` files in apps repo, so EE systems will perform the correct check. 
https://github.com/truenas/apps/blob/05463c559bc6060c02a0bde7ca1877336efda95a/trains/stable/emby/app_versions.json#L11

NAS-133965 / 25.10 / fixes a typo in version checking for apps

---

src/middlewared/middlewared/plugins/catalog/apps_util.py
src/middlewared/middlewared/pytest/unit/plugins/catalog/test_min_max_scale_version_update.py

We likely need to make a copy of `app_metadata` to `chart_metadata` in all the generated `app_versions.json` files in apps repo, so EE systems will perform the correct check. 
https://github.com/truenas/apps/blob/05463c559bc6060c02a0bde7ca1877336efda95a/trains/stable/emby/app_versions.json#L11
Original PR: https://github.com/truenas/middleware/pull/15520
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133965

NAS-133965 / 25.04-RC.1 / fixes a typo in version checking for apps (by stavros-k)

---

src/middlewared/middlewared/plugins/update.py

We no longer need to perform this snapshot since this we now store AD secrets in our database and have better upgrade processes.

NAS-133973 / 25.10 / Remove samba dataset snapshot on upgrade

---

src/middlewared/middlewared/plugins/update.py

We no longer need to perform this snapshot since this we now store AD secrets in our database and have better upgrade processes.
Original PR: https://github.com/truenas/middleware/pull/15571
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133973

NAS-133973 / 25.04-RC.1 / Remove samba dataset snapshot on upgrade (by anodos325)

---

src/middlewared/middlewared/plugins/update.py

We no longer need to perform this snapshot since this we now store AD secrets in our database and have better upgrade processes.
Original PR: https://github.com/truenas/middleware/pull/15571
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133973

NAS-133973 / 25.04-BETA.1 / Remove samba dataset snapshot on upgrade (by anodos325)

---

src/middlewared/middlewared/api/v25_04_0/privilege.py
src/middlewared/middlewared/plugins/account_/privilege.py

In various circumstances the privilege table may refer to gids that from the perspective of TrueNAS no longer exist. In this case a minimal entry is returned with basic gid and sid information so that the admin has a way of determining whether to delete it.

NAS-133910 / 25.10 / Add schema handling for unmapped groups in privileges

---

src/middlewared/middlewared/api/v25_04_0/privilege.py
src/middlewared/middlewared/plugins/account_/privilege.py

In various circumstances the privilege table may refer to gids that from the perspective of TrueNAS no longer exist. In this case a minimal entry is returned with basic gid and sid information so that the admin has a way of determining whether to delete it.
Original PR: https://github.com/truenas/middleware/pull/15570
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133910

NAS-133910 / 25.04-RC.1 / Add schema handling for unmapped groups in privileges (by anodos325)

---

src/middlewared/middlewared/plugins/support.py
src/middlewared/middlewared/plugins/system/info.py
src/middlewared/middlewared/plugins/webui/main_dashboard.py
src/middlewared/middlewared/utils/__init__.py

No reason to show `TrueNAS-` or `COMMUNITY_EDITION` or `ENTERPRISE`. The first is implied and the other two are implementation details.

NAS-133972 / 25.10 / Fix public view of version string

---

src/middlewared/middlewared/plugins/support.py
src/middlewared/middlewared/plugins/system/info.py
src/middlewared/middlewared/plugins/webui/main_dashboard.py
src/middlewared/middlewared/utils/__init__.py

No reason to show `TrueNAS-` or `COMMUNITY_EDITION` or `ENTERPRISE`. The first is implied and the other two are implementation details.
Original PR: https://github.com/truenas/middleware/pull/15572
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133972

NAS-133972 / 25.04-BETA.1 / Fix public view of version string (by yocalebo)

---

src/middlewared/middlewared/plugins/support.py
src/middlewared/middlewared/plugins/system/info.py
src/middlewared/middlewared/plugins/webui/main_dashboard.py
src/middlewared/middlewared/utils/__init__.py

No reason to show `TrueNAS-` or `COMMUNITY_EDITION` or `ENTERPRISE`. The first is implied and the other two are implementation details.
Original PR: https://github.com/truenas/middleware/pull/15572
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133972

NAS-133972 / 25.04-RC.1 / Fix public view of version string (by yocalebo)

---

src/middlewared/middlewared/plugins/iscsi_/global_linux.py

Recently added additional reporting to upstream SCST.  Now use this to detect if a session is iSCSI or iSER.
----
Have performed some manual tests (seeing as require a RoCE card to perform iSER).

NAS-133848 / 25.10 / Read iSCSI session transport from kernel sys interface

---

src/middlewared/middlewared/plugins/iscsi_/global_linux.py

Recently added additional reporting to upstream SCST.  Now use this to detect if a session is iSCSI or iSER.
----
Have performed some manual tests (seeing as require a RoCE card to perform iSER).
Original PR: https://github.com/truenas/middleware/pull/15586
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133848

NAS-133848 / 25.04-RC.1 / Read iSCSI session transport from kernel sys interface (by bmeagherix)

---

src/middlewared/middlewared/plugins/crypto_/cert_info.py
src/middlewared/middlewared/plugins/system_general/country.py
src/middlewared/middlewared/utils/country_codes.py

I have this tendency to cache functions that return mutable objects. That can lead to a set of issues that no one should have to endure :smile:.
I'll start fixing these 1-by-1 so I started with `get_country_codes` function.

NAS-134005 / 25.10 / cache immutable type in get_country_codes

---

src/middlewared/middlewared/plugins/crypto_/cert_info.py
src/middlewared/middlewared/plugins/system_general/country.py
src/middlewared/middlewared/utils/country_codes.py

I have this tendency to cache functions that return mutable objects. That can lead to a set of issues that no one should have to endure :smile:.
I'll start fixing these 1-by-1 so I started with `get_country_codes` function.
Original PR: https://github.com/truenas/middleware/pull/15587
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134005

NAS-134005 / 25.04-RC.1 / cache immutable type in get_country_codes (by yocalebo)

---

src/middlewared/middlewared/plugins/system/dmi.py
src/middlewared/middlewared/plugins/truenas.py

`parse_dmi` in `ixhardware` module was being cached and then we were caching `dmidecode_info` which calls `dmidecode_info_internal` which was also being cached.
Dependent PR at: https://github.com/truenas/ixhardware/pull/6

NAS-134012 / 25.10 / stop triple caching DMI info

---

src/middlewared/middlewared/plugins/ipmi_/lan.py

Same reasoning for the changes I did in https://github.com/truenas/ixhardware/pull/6. When caching objects, they need to be of an immutable type. This changes this function to return a tuple of integers instead of a list of integers.

NAS-134017 / 25.10 / change lan_channels cache to immutable type

---

src/middlewared/middlewared/plugins/system_general/timezone.py
src/middlewared/middlewared/utils/timezone_choices.py

Again, don't need to cache mutable objects. While I'm here, took the liberty to remove an unnecessary `subprocess` call. We can get the same information via reading the tzdata.zi file provided by upstream Debian.

NAS-134026 / 25.10 / change timezone_choices cache to immutable type

---

src/middlewared/middlewared/plugins/security/update.py

This commit fixes two bugs regarding updates to system security settings on the HA platform
1) We were emitting the event that reboot is required before the
standby controller finished rebooting and HA was in a healthy
state.
2) We need to make sure database changes are synced to standby
controller before reconfiguring FIPS settings and rebooting.

NAS-133449 / 25.10 / Fix system.security.update on HA

---

src/middlewared/middlewared/plugins/security/update.py

This commit fixes two bugs regarding updates to system security settings on the HA platform
1) We were emitting the event that reboot is required before the
standby controller finished rebooting and HA was in a healthy
state.
2) We need to make sure database changes are synced to standby
controller before reconfiguring FIPS settings and rebooting.
Original PR: https://github.com/truenas/middleware/pull/15599
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133449

NAS-133449 / 25.04-RC.1 / Fix system.security.update on HA (by anodos325)

---

src/middlewared/middlewared/api/base/model.py
src/middlewared/middlewared/pytest/unit/api/base/test_excluded.py

Fix tests following #15462
Applying `serialize_as_any` across the board for all BaseModels was a mistake since it makes serialization far less reliable as opposed to always producing a dictionary. Using the same `undefined` object for `NotRequired` as the one returned by `excluded_field` was also a mistake since it invited overlap between the behavior of `NotRequired` fields and `Excluded` fields.
Solution:
- Use a new singleton class for `NotRequired`
- Disable `serialize_as_any` so that fields are serialized according to their annotations only, not according to their values
- Enable `arbitrary_types_allowed` so that `NotRequired` and other custom types can be used as field annotations
- Update the annotations of all fields with `NotRequired` as their default in BaseModel's metaclass …

NAS-134037 / 25.10 / Fix `NotRequired`

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py

git cherry-pick -x ad41091a9d77720d8b9e20e2d76eed9bcb62bcd3
git cherry-pick -x 379c4264d8200f087d64ef613ce3470cfbe7f46f
git cherry-pick -x f8e9723d6196a76f78deda903e4188a596b7ddfa
This will be used in https://ixsystems.atlassian.net/browse/NAS-133963
Original PR: https://github.com/truenas/middleware/pull/15598
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134056

NAS-134056 / 25.04-RC.1 / Add `secureboot` to the installed instance image attributes (by william-gr)

---

src/middlewared/middlewared/api/base/server/ws_handler/rpc.py

Instead of timing out, we should catch the error and send it to the client to assist with debugging.
http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2916/
Original PR: https://github.com/truenas/middleware/pull/15582
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133996

NAS-133996 / 25.04-RC.1 / Send error when middleware response fails to serialize (by creatorcary)

---

src/middlewared/middlewared/etc_files/smartd.py

Crash seen in https://ixsystems.atlassian.net/browse/NAS-133954
Original PR: https://github.com/truenas/middleware/pull/15618
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134070

NAS-134070 / 25.04-RC.1 / `smart_support` key is not always available` (by themylogin)

---

src/middlewared/middlewared/plugins/reporting/netdata/graphs.py

`get_identifiers` in CPU plugin is not being used and was brought in accidentally during a refactor and is being removed.

NAS-134073 / 25.10 / Remove redundant get_identifiers in cpu graph

---

src/middlewared/middlewared/plugins/reporting/netdata/graphs.py

`get_identifiers` in CPU plugin is not being used and was brought in accidentally during a refactor and is being removed.
Original PR: https://github.com/truenas/middleware/pull/15622
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134073

NAS-134073 / 25.04-RC.1 / Remove redundant get_identifiers in cpu graph (by Qubad786)

---

src/middlewared/middlewared/plugins/usage.py
tests/api2/test_usage_reporting.py

It was requested that we gather virt plugin usage statistics and relevant changes have been added to account for that.
Original PR: https://github.com/truenas/middleware/pull/15612
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133562

NAS-133562 / 25.04-RC.1 / Gather virt plugin metrics (by Qubad786)

---

src/middlewared/middlewared/plugins/apps_images/client.py
src/middlewared/middlewared/plugins/apps_images/dockerhub_ratelimit.py

If a consumer configures app registry for dockerhub, the registry is being used when pulling images from dockerhub - however we have an endpoint which shows remaining left pull limit and that is not accounting for the creds user has already provided for dockerhub.
Make sure we correctly report docker hub rate limit if docker registry creds have already been provided to the system.

NAS-134060 / 25.10 / Use app registry credentials when retrieving dockerhub limit

---

src/middlewared/middlewared/api/v25_04_0/keychain.py

git cherry-pick -x fac029c263a5251f1ef14ab1fbc51d675905cecf
git cherry-pick -x b69661c36a1547b8582f0690cad2dcf769784325
Original PR: https://github.com/truenas/middleware/pull/15617
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133954

NAS-133954 / 25.04-RC.1 / Fix keychaincredentials schema errors (by themylogin)

---

src/middlewared/middlewared/plugins/apps_images/client.py
src/middlewared/middlewared/plugins/apps_images/dockerhub_ratelimit.py

If a consumer configures app registry for dockerhub, the registry is being used when pulling images from dockerhub - however we have an endpoint which shows remaining left pull limit and that is not accounting for the creds user has already provided for dockerhub.
Make sure we correctly report docker hub rate limit if docker registry creds have already been provided to the system.
Original PR: https://github.com/truenas/middleware/pull/15625
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134060

NAS-134060 / 25.04-BETA.1 / Use app registry credentials when retrieving dockerhub limit (by Qubad786)

---

src/middlewared/middlewared/utils/cpu.py

This adds an `ht_map` attribute to the `CpuInfo` dictionary. This is needed for open PR: https://github.com/truenas/middleware/pull/15514.
While here:
1. fix type annotations
2. add docstrings

NAS-134071 / 25.10 / add ht_map to CpuInfo

---

src/middlewared/middlewared/utils/cpu.py

This adds an `ht_map` attribute to the `CpuInfo` dictionary. This is needed for open PR: https://github.com/truenas/middleware/pull/15514.
While here:
1. fix type annotations
2. add docstrings
Original PR: https://github.com/truenas/middleware/pull/15620
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134071

NAS-134071 / 25.04-RC.1 / add ht_map to CpuInfo (by yocalebo)

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/api/v25_10_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py
src/middlewared/middlewared/plugins/virt/utils.py
tests/api2/test_virt_002_instance.py

We allow setting root disk size for virt VMs and changes have been made to allow updating root disk size a well for virt VMs.

NAS-133934 / 25.10 / Allow updating root disk size for virt VM instances

---

src/middlewared/middlewared/plugins/apps_images/client.py
src/middlewared/middlewared/plugins/apps_images/dockerhub_ratelimit.py

If a consumer configures app registry for dockerhub, the registry is being used when pulling images from dockerhub - however we have an endpoint which shows remaining left pull limit and that is not accounting for the creds user has already provided for dockerhub.
Make sure we correctly report docker hub rate limit if docker registry creds have already been provided to the system.
Original PR: https://github.com/truenas/middleware/pull/15625
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134060

NAS-134060 / 25.04-RC.1 / Use app registry credentials when retrieving dockerhub limit (by Qubad786)

---

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako

TrueConnect needs access to /download to be able to remotely download a debug.

NAS-133727 / 25.10 / Make CORS policy exception for internal URLs like TrueConnect

---

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako

TrueConnect needs access to /download to be able to remotely download a debug.
Original PR: https://github.com/truenas/middleware/pull/15621
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133727

NAS-133727 / 25.04-RC.1 / Make CORS policy exception for internal URLs like TrueConnect (by creatorcary)

---

src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/failover_/datastore.py
src/middlewared/middlewared/restful.py

This commit switches the failover plugin to consuming single-use API tokens for performing file sends across the heartbeat connection.
This is an interim fix until we have better file-related read / write APIs.
This commit also relaxes authentication requirements for STIG mode to allow single-use API tokens for REST authentication. This is specifically for the file upload / download endpoints.

NAS-134080 / 25.10 / Generate single-use API tokens for failover plugin

---

src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/failover_/datastore.py
src/middlewared/middlewared/restful.py

This commit switches the failover plugin to consuming single-use API tokens for performing file sends across the heartbeat connection.
This is an interim fix until we have better file-related read / write APIs.
This commit also relaxes authentication requirements for STIG mode to allow single-use API tokens for REST authentication. This is specifically for the file upload / download endpoints.
Original PR: https://github.com/truenas/middleware/pull/15638
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134080

NAS-134080 / 25.04-RC.1 / Generate single-use API tokens for failover plugin (by anodos325)

---

src/freenas/usr/local/sbin/hactl

If system is in STIG mode, this will fail because `system.dmidecode_info` is a private method and we don't allow private methods to be called from external entities when STIG has been enabled.

NAS-134094 / 25.10 / fix hactl calling private methods

---

src/freenas/usr/local/sbin/hactl

If system is in STIG mode, this will fail because `system.dmidecode_info` is a private method and we don't allow private methods to be called from external entities when STIG has been enabled.
Original PR: https://github.com/truenas/middleware/pull/15643
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134094

NAS-134094 / 25.04-RC.1 / fix hactl calling private methods (by yocalebo)

---

tests/api2/test_system_general_ui_rollback.py

Rewritten test is double the code and fails always, not sometimes. Let's roll back, see how the original code flakes and fix that.
Original PR: https://github.com/truenas/middleware/pull/15645
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134097

NAS-134097 / 25.04-RC.1 / Bring back original `test_system_general_ui_rollback.py` (by themylogin)

---

src/middlewared/middlewared/plugins/filesystem_/perm_check.py
src/middlewared/middlewared/utils/user_context.py

Follow-up to https://github.com/truenas/middleware/pull/15551

NAS-133945 / 25.10 / Make `run_with_user_context` crash if multiprocessing worker tries to import API

---

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako

Remove some nginx logic for handling deprecated TC authentication type
that is not required anymore since the middleware path was removed.

NAS-133849 / 25.10 / Remove handling for POST requests for legacy TC

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py

We regressed with a change introduced by 6bc0a1255614cfbebbcb57ba29495131ddb8b9e8, secure boot key is added back to image choices as pydantic will error out otherwise

NAS-134119 / 25.10 / Specify secure boot key in image choices

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py

We regressed with a change introduced by 6bc0a1255614cfbebbcb57ba29495131ddb8b9e8, secure boot key is added back to image choices as pydantic will error out otherwise
Original PR: https://github.com/truenas/middleware/pull/15654
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134119

NAS-134119 / 25.04-RC.1 / Specify secure boot key in image choices (by Qubad786)

---

tests/api2/test_zzzz_stig.py

We've still got some failing STIG tests because of them tripping rate limit logic. Change the cache clear fixture to be autouse=True. This resolves the regressing tests.

NAS-134132 / 25.10 / Fix STIG API tests

---

tests/api2/test_zzzz_stig.py

We've still got some failing STIG tests because of them tripping rate limit logic. Change the cache clear fixture to be autouse=True. This resolves the regressing tests.
Original PR: https://github.com/truenas/middleware/pull/15656
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134132

NAS-134132 / 25.04-RC.1 / Fix STIG API tests (by yocalebo)

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/api/v25_10_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py

In certain race conditions i.e stopping/crashing a virt instance, it is possible that netmask is an empty string returned by incus which breaks our query logic which in turn breaks consumers of `virt.instance.query`.
Gracefully handle the case when netmask is reported as an empty string

NAS-134104 / 25.10 / Fix netmask being empty string

---

src/middlewared/middlewared/api/v25_04_0/virt_instance.py
src/middlewared/middlewared/plugins/virt/instance.py

git cherry-pick -x d6975d89b23f87119b8162172199a1ed163d2c19
git cherry-pick -x 0464eafd719c08ff391be3f5c3013eabafe5370e
In certain race conditions i.e stopping/crashing a virt instance, it is possible that netmask is an empty string returned by incus which breaks our query logic which in turn breaks consumers of `virt.instance.query`.
Gracefully handle the case when netmask is reported as an empty string
Original PR: https://github.com/truenas/middleware/pull/15660
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134104

NAS-134104 / 25.04-RC.1 / Fix netmask being empty string (by Qubad786)

---

tests/api2/test_audit_websocket.py

We now raise exception if job id does not match an existing job for the user.
Original PR: https://github.com/truenas/middleware/pull/15650
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134087

NAS-134087 / 25.04-RC.1 / Use a proper job id for download token test (by anodos325)

---

src/freenas/usr/lib/netdata/python.d/cputemp.chart.py
src/middlewared/middlewared/utils/cpu.py

Currently, the Netdata CPU temperature plugin does not report temperatures for virtual cores.  
Mirror the temperature readings from physical cores to their respective virtual cores, similar to how **htop** handles it.
Ref: https://unix.stackexchange.com/questions/400605/understanding-core-ids

NAS-133858 / 25.10 / Make sure CPU temperature is reported for virtual cores

---

src/freenas/usr/lib/netdata/python.d/cputemp.chart.py
src/middlewared/middlewared/utils/cpu.py

Currently, the Netdata CPU temperature plugin does not report temperatures for virtual cores.  
Mirror the temperature readings from physical cores to their respective virtual cores, similar to how **htop** handles it.
Ref: https://unix.stackexchange.com/questions/400605/understanding-core-ids
Original PR: https://github.com/truenas/middleware/pull/15514
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133858

NAS-133858 / 25.04-RC.1 / Make sure CPU temperature is reported for virtual cores (by Qubad786)

---

tests/api2/test_device_get_disk_names.py

This test is no longer needed after https://github.com/truenas/middleware/pull/15550 was merged.

NAS-134149 / 25.10 / remove unnecessary api test

---

src/middlewared/middlewared/plugins/acme_protocol_/authenticators/cloudflare.py

The old error message was really confusing when I set up the ACME DNS Authenticators using Cloudflare. I didn’t even know there were two ways to connect API in Cloudflare. So, I believe the error message should be slightly updated.

NAS-134148 / 25.10 / clarify ACME DNS-Authenticators cloudflare error message

---

src/middlewared/middlewared/plugins/zfs_/dataset_encryption.py

This fixes regressions introduced in https://github.com/truenas/middleware/pull/15663

NAS-134179 / 25.10 / fix dataset encryption API test failures

---

src/middlewared/middlewared/plugins/disk_/availability.py

NAS-134182 / 25.10 / Restore default to `disk.get_unused.join_partitions`

---

src/middlewared/middlewared/api/base/decorator.py
src/middlewared/middlewared/api/v25_10_0/smb.py
src/middlewared/middlewared/plugins/filesystem_/acl.py
src/middlewared/middlewared/plugins/ntp.py
src/middlewared/middlewared/plugins/rdma/rdma.py
src/middlewared/middlewared/plugins/smb.py
src/middlewared/middlewared/pytest/unit/api/handler/decorator.py

http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3023/

NAS-133901 / 25.10 / Do not allow roles to be set on private endpoints

---

src/middlewared/middlewared/plugins/system_general/update.py

This commit adds changes to only validate cert if it has changed because we have seen a case where user's cert had expired and he had http to https redirect enabled and could not unset the redirect because of the cert still being validated.
Original PR: https://github.com/truenas/middleware/pull/15676
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133719

NAS-133719 / 25.04-RC.1 / Only validate certificate if it has changed (by sonicaj)

---

src/middlewared/middlewared/plugins/zfs_/dataset.py

Same reasoning as outlined in https://github.com/truenas/middleware/pull/15663. Remove schema validation on the internal, private zfs_/dataset.py endpoints. Added docstrings to the endpoints that needed them.

NAS-134160 / 25.10 / remove schema validation on zfs_/dataset.py

---

src/middlewared/middlewared/api/v25_04_0/core.py

git cherry-pick -x 37f7d927e33102b9cecca97f3bd53f8bf834ad42
git cherry-pick -x 50d0f3f9803ee56978565cfc6bd4e2c05904fb15
Original PR: https://github.com/truenas/middleware/pull/15682
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134180

NAS-134180 / 25.04-RC.1 / Remove `extra="forbid"` for `CoreSetOptionsOptions` (by themylogin)

---

src/middlewared/middlewared/plugins/docker/update.py

When we have 20+ running apps, we have seen that if we docker pool is unset or changed - what happens in the background is that ix-apps dataset is umounted after stopping docker service and the new one mounted (if anotehr pool has been selected).
However we have observed that that with 20+ running apps, docker does not cleanly exit and we are unable to umount ix-apps dataset because of that.
Make sure if pool attr is being changed, we stop all apps and then stop docker service as that results in a clean docker exit and we are able to umount ix-apps dataset without any issues.
Original PR: https://github.com/truenas/middleware/pull/15686
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134025

NAS-134025 / 25.04-RC.1 / Stop apps when pool attr for docker service is changed (by Qubad786)

---

tests/api2/test_261_iscsi_cmd.py
tests/api2/test_262_iscsi_alua.py

Some ALUA tests were going AWOL because a previous failure had left failover administratively disabled.  Add an explicit check that this is not the case.
----
Passing (abridged) CI [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3083/).

NAS-134175 / 25.10 / Ensure failover has not been disabled

---

tests/api2/test_261_iscsi_cmd.py
tests/api2/test_262_iscsi_alua.py

Some ALUA tests were going AWOL because a previous failure had left failover administratively disabled.  Add an explicit check that this is not the case.
----
Passing (abridged) CI [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3083/).
Original PR: https://github.com/truenas/middleware/pull/15699
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134175

NAS-134175 / 25.04-RC.1 / Ensure failover has not been disabled (by bmeagherix)

---

src/middlewared/middlewared/alembic/versions/25.04/2025-02-11_22-45_iser.py
src/middlewared/middlewared/api/v25_04_0/iscsi_global.py
src/middlewared/middlewared/plugins/iscsi_/iscsi_global.py
src/middlewared/middlewared/plugins/iscsi_/iser.py
src/middlewared/middlewared/plugins/service_/services/iscsitarget.py

- Add iSER setting (`iser`) to `iscsi.global`.  Kernel module will only be loaded if enabled.
- Alembic migration for iSER configuration setting
----
CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3081/)

NAS-134170 / 25.04 / Add iser setting to iscsi.global

---

src/middlewared/middlewared/alembic/versions/25.04/2025-02-11_22-45_iser.py
src/middlewared/middlewared/api/v25_04_0/iscsi_global.py
src/middlewared/middlewared/api/v25_10_0/iscsi_global.py
src/middlewared/middlewared/plugins/iscsi_/iscsi_global.py
src/middlewared/middlewared/plugins/iscsi_/iser.py
src/middlewared/middlewared/plugins/service_/services/iscsitarget.py

- Add iSER setting (`iser`) to `iscsi.global`.  Kernel module will only be loaded if enabled.
- Alembic migration for iSER configuration setting
----
CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3081/)
Original PR: https://github.com/truenas/middleware/pull/15698
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134170
----
Since 25.10 does not yet have **any** alembic entries, no merge migration is required.

NAS-134170 / 25.10 / Add iser setting to iscsi.global (by bmeagherix)

---

src/middlewared/middlewared/api/v25_04_0/virt_device.py
src/middlewared/middlewared/api/v25_10_0/virt_device.py
src/middlewared/middlewared/plugins/virt/disk.py

It was requested that we port importing/exporting disk images functionality to virt plugin and that has been done. (Similar changes from VM plugin are being removed in another PR https://github.com/truenas/middleware/pull/15658).

NAS-133751 / 25.10 / Allow importing/exporting disk images in virt plugin

---

src/middlewared/middlewared/api/v25_04_0/virt_device.py
src/middlewared/middlewared/plugins/virt/disk.py

git cherry-pick -x d34d4eabb34326af3a97e9aae4e616af3e0ad3ee
git cherry-pick -x a992c09ba26bd9a6819f62f10a4b949056f97b81
It was requested that we port importing/exporting disk images functionality to virt plugin and that has been done. (Similar changes from VM plugin are being removed in another PR https://github.com/truenas/middleware/pull/15658).
Original PR: https://github.com/truenas/middleware/pull/15690
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133751

NAS-133751 / 25.04-RC.1 / Allow importing/exporting disk images in virt plugin (by Qubad786)

---

src/middlewared/middlewared/alembic/versions/25.04/2025-02-14_15-13_nfs_add_snapdir.py
src/middlewared/middlewared/api/v25_04_0/nfs.py
src/middlewared/middlewared/etc_files/exports.mako
src/middlewared/middlewared/plugins/nfs.py
tests/api2/test_nfs_snapdir.py
tests/protocols/nfs_proto.py

This commit adds support for the new exports "zfs_snapdir" line for enterprise customers.

NAS-132120 / 25.04-RC.1 / Add API to enable ZFS snapdir access over NFS

---

src/middlewared/middlewared/alembic/versions/25.04/2025-02-14_15-13_nfs_add_snapdir.py
src/middlewared/middlewared/api/v25_04_0/nfs.py
src/middlewared/middlewared/etc_files/exports.mako
src/middlewared/middlewared/plugins/nfs.py
tests/api2/test_nfs_snapdir.py
tests/protocols/nfs_proto.py

This commit adds support for the new exports "zfs_snapdir" line for enterprise customers.
Original PR: https://github.com/truenas/middleware/pull/15706
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132120

NAS-132120 / 25.10 / Add API to enable ZFS snapdir access over NFS (by anodos325)

---

src/middlewared/middlewared/plugins/ipmi_/sensors.py

This isn't used by anyone except internally for our alert framework. Remove it from public api.

NAS-134228 / 25.10 / remove ipmi_/sensors.py from public api

---

src/freenas/usr/local/bin/nvmf-connect.sh

Removing power from the ES24N shelf does not trigger events on the discovery controller except for an Interface Link Down. Shelf drives keep retrying until a 10-minute timeout. After power restoration, it takes about 10 seconds to connect, yet the remote discovery log shows no entries. A discovery change event then removes all drives since the ES24N shelf reports none. One minute after Link Up, a Link Down occurs, followed by another Link Up a few seconds later that triggers a change event during which some entries, notably CM7 drives, are missed.
To address this, wait for the timeout to complete if the shelf was previously empty during a discovery change event on power restore. This avoids acting on incomplete discovery logs and ensures proper drive reconnection. In addition, when …

NAS-134183 / 25.10 / nvme-of: wait for timeout to pass if shelf was empty

---

src/freenas/usr/local/bin/nvmf-connect.sh

Removing power from the ES24N shelf does not trigger events on the discovery controller except for an Interface Link Down. Shelf drives keep retrying until a 10-minute timeout. After power restoration, it takes about 10 seconds to connect, yet the remote discovery log shows no entries. A discovery change event then removes all drives since the ES24N shelf reports none. One minute after Link Up, a Link Down occurs, followed by another Link Up a few seconds later that triggers a change event during which some entries, notably CM7 drives, are missed.
To address this, wait for the timeout to complete if the shelf was previously empty during a discovery change event on power restore. This avoids acting on incomplete discovery logs and ensures proper drive reconnection. In addition, when …

NAS-134183 / 25.04-RC.1 / nvme-of: wait for timeout to pass if shelf was empty (by ixhamza)

---

src/middlewared/middlewared/api/v25_04_0/smb.py

The docstring that I added in the `normalize_bindips` method should explain it sufficiently.
Original PR: https://github.com/truenas/middleware/pull/15729
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133947

NAS-133947 / 25.04-RC.1 / fix bindip in smb plugin (by yocalebo)

---

src/middlewared/middlewared/api/v25_04_0/auth.py
src/middlewared/middlewared/api/v25_10_0/auth.py
src/middlewared/middlewared/auth.py
src/middlewared/middlewared/service/core_service.py

This commit fixes an issue that was preventing STIG mode file downloads as
well as a few opportuninistic fixes.
* Add LOGIN_ONETIME_PASSWORD to session types enum
* Allow token generation for user sessions
* Add comments to explain generate_tokens arguments in download method

NAS-134277 / 25.10 / Allow file downloads STIG mode

---

src/middlewared/middlewared/api/v25_04_0/auth.py
src/middlewared/middlewared/auth.py
src/middlewared/middlewared/service/core_service.py

This commit fixes an issue that was preventing STIG mode file downloads as
well as a few opportunistic fixes.
* Add LOGIN_ONETIME_PASSWORD to session types enum
* Allow token generation for user sessions
* Add comments to explain generate_tokens arguments in download method
Original PR: https://github.com/truenas/middleware/pull/15736
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134277

NAS-134277 / 25.04-RC.1 / Allow file downloads STIG mode (by anodos325)

---

src/middlewared/middlewared/alert/source/smb.py
src/middlewared/middlewared/plugins/smb_/passdb.py

This commit adds a oneshot alert for case where users lack an SMB hash, which can occur if config file was restored without the secret seed. The alert is deliberately not toggled by CRUD methods for accounts to keep it simple for what should be an obscure edge-case.

NAS-134202 / 25.10 / Add alert for missing SMB user hashes

---

src/middlewared/middlewared/alert/source/smb.py
src/middlewared/middlewared/plugins/smb_/passdb.py

This commit adds a oneshot alert for case where users lack an SMB hash, which can occur if config file was restored without the secret seed. The alert is deliberately not toggled by CRUD methods for accounts to keep it simple for what should be an obscure edge-case.
Original PR: https://github.com/truenas/middleware/pull/15738
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134202

NAS-134202 / 25.04-RC.1 / Add alert for missing SMB user hashes (by anodos325)

---

src/middlewared/middlewared/plugins/smb.py
src/middlewared/middlewared/plugins/smb_/constants.py
src/middlewared/middlewared/plugins/smb_/util_smbconf.py
tests/unit/test_smb_service.py
tests/unit/test_smb_share.py

This commit disables SMB2/3 lease support globally when multiprotocol SMB shares are enabled. This is because despite kernel_oplocks being a per-share parameter in libsmbconf, it is incompatible with SMB2/3 lease support and can lead to unexpected failures depending on the order in which the SMB client has negotiated its first SMB tree connect.
Validation logic is simplified by making this share type mutually exclusive with AAPL extension support because timemachine -- the main driver for enabling this -- requires SMB2/3 lease support.

NAS-133680 / 25.10 / Disable SMB2 lease support in multiprotocol SMB mode

---

src/middlewared/middlewared/plugins/smb.py
src/middlewared/middlewared/plugins/smb_/constants.py
src/middlewared/middlewared/plugins/smb_/util_smbconf.py
tests/unit/test_smb_service.py
tests/unit/test_smb_share.py

This commit disables SMB2/3 lease support globally when multiprotocol SMB shares are enabled. This is because despite kernel_oplocks being a per-share parameter in libsmbconf, it is incompatible with SMB2/3 lease support and can lead to unexpected failures depending on the order in which the SMB client has negotiated its first SMB tree connect.
Validation logic is simplified by making this share type mutually exclusive with AAPL extension support because timemachine -- the main driver for enabling this -- requires SMB2/3 lease support.
Original PR: https://github.com/truenas/middleware/pull/15740
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133680

NAS-133680 / 25.04-RC.1 / Disable SMB2 lease support in multiprotocol SMB mode (by anodos325)

---

src/middlewared/middlewared/etc_files/pam.d/common-auth.mako
src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/utils/auth.py

SRG-OS-000480-GPOS-00226 requires that the OS enforce a delay of at least 4 seconds between logon prompts following a failed logon attempt. This commit adds an additional failure delay when in STIG mode to meet this requirement.

NAS-133911 / 25.10 / Increase auth failure delay to minimum of 4 seconds

---

src/middlewared/middlewared/etc_files/pam.d/common-auth.mako
src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/utils/auth.py

SRG-OS-000480-GPOS-00226 requires that the OS enforce a delay of at least 4 seconds between logon prompts following a failed logon attempt. This commit adds an additional failure delay when in STIG mode to meet this requirement.
Original PR: https://github.com/truenas/middleware/pull/15742
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133911

NAS-133911 / 25.04-RC.1 / Increase auth failure delay to minimum of 4 seconds (by anodos325)

---

src/middlewared/middlewared/api/v24_10/cloud_sync.py
src/middlewared/middlewared/api/v25_04_0/cloud_sync.py
src/middlewared/middlewared/api/v25_04_0/keychain.py

git cherry-pick -x 358481bad55c8c8f9d8aef048822d257d358342d
git cherry-pick -x 8004c5f79925e77521ee0751e7e50524831212b6
Original PR: https://github.com/truenas/middleware/pull/15746
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134279

NAS-134279 / 25.04-RC.1 / Use `LongString` for cloud credential errors (by themylogin)

---

src/middlewared/middlewared/plugins/update.py

Various methods were changed in a previous commit to require FULL_ADMIN without updating our unit tests. This commit changes the required role to SYSTEM_UPDATE_WRITE.

NAS-134293 / 25.10 / Convert update plugin to use SYSTEM_UPDATE_WRITE

---

src/middlewared/middlewared/utils/auth.py

This commit fixes a typo in the function to get the current failure delay interval.
Original PR: https://github.com/truenas/middleware/pull/15752
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134288

NAS-134288 / 25.04-RC.1 / Fix auth failure delay (by anodos325)

---

src/middlewared/middlewared/plugins/update.py

Various methods were changed in a previous commit to require FULL_ADMIN without updating our unit tests. This commit changes the required role to SYSTEM_UPDATE_WRITE.
Original PR: https://github.com/truenas/middleware/pull/15757
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134293

NAS-134293 / 25.04-RC.1 / Convert update plugin to use SYSTEM_UPDATE_WRITE (by anodos325)

---

src/middlewared/middlewared/role.py

This commit removes a case where we short-circuit the roles composition when user has FULL_ADMIN privilege in non-STIG mode. This change makes it so that the webui can properly check roles.

NAS-134292 / 25.10 / Always build roles array when composing privilege

---

src/middlewared/middlewared/role.py

This commit removes a case where we short-circuit the roles composition when user has FULL_ADMIN privilege in non-STIG mode. This change makes it so that the webui can properly check roles.
Original PR: https://github.com/truenas/middleware/pull/15756
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134292

NAS-134292 / 25.04-RC.1 / Always build roles array when composing privilege (by anodos325)

---

src/middlewared/middlewared/api/v25_04_0/rdma_interface.py
src/middlewared/middlewared/api/v25_10_0/rdma_interface.py

After the address field has been validated as a proper ip address, we need to return the ip address as a string and not as a `ipaddress.IPv4Address` or `ipaddress.IPv6Address` type.
A future PR should consider adding our own `IPvAnyAddress` type that does just this since we're not used to getting the class type inside middleware.

NAS-134234 / 25.10 / fix deserialization of IPvAnyAddress for rdma api

---

src/middlewared/middlewared/api/v25_04_0/rdma_interface.py

After the address field has been validated as a proper ip address, we need to return the ip address as a string and not as a `ipaddress.IPv4Address` or `ipaddress.IPv6Address` type.
A future PR should consider adding our own `IPvAnyAddress` type that does just this since we're not used to getting the class type inside middleware.
Original PR: https://github.com/truenas/middleware/pull/15761
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134234

NAS-134234 / 25.04-RC.1 / fix deserialization of IPvAnyAddress for rdma api (by yocalebo)

---

src/middlewared/middlewared/api/v25_10_0/__init__.py
src/middlewared/middlewared/api/v25_10_0/ups.py
src/middlewared/middlewared/plugins/ups.py

UPS plugin has been converted to use pydantic models.

NAS-134128 / 25.10 / Convert UPS plugin to use pydantic models

---

src/middlewared/middlewared/plugins/api_key.py
src/middlewared/middlewared/role.py

Currently API key authentication is disabled in STIG mode. This commit prevents users from having write permissions to the plugin to avoid a misapprehension that they will be able to auth using them in STIG mode.

NAS-134065 / 25.10 / Disable API_KEY role in GPOS STIG mode

---

src/middlewared/middlewared/plugins/api_key.py
src/middlewared/middlewared/role.py

Currently API key authentication is disabled in STIG mode. This commit prevents users from having write permissions to the plugin to avoid a misapprehension that they will be able to auth using them in STIG mode.
Original PR: https://github.com/truenas/middleware/pull/15765
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134065

NAS-134065 / 25.04-RC.1 / Disable API_KEY role in GPOS STIG mode (by anodos325)

---

src/middlewared/middlewared/plugins/security/update.py

This feature is incompatible with apps / vms and so we should have some sanity checks.

NAS-134045 / 25.10 / Prevent enabling STIG if apps / vms are configured

---

src/middlewared/middlewared/plugins/security/update.py

This feature is incompatible with apps / vms and so we should have some sanity checks.
Original PR: https://github.com/truenas/middleware/pull/15767
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134045

NAS-134045 / 25.04-RC.1 / Prevent enabling STIG if apps / vms are configured (by anodos325)

---

src/middlewared/middlewared/plugins/pool_/dataset_processes.py

This commit fixes an issue where pid for dataset processes is being reported as a string which causes problems when trying to consume as expectation is it will be an integer.
i.e
```
❯ midclt call -j pool.export 41 '{"cascade": true, "destroy": true}'
Status: Terminating processes that are using this pool
Total Progress: [########________________________________] 20.00%
'<=' not supported between instances of 'str' and 'int'
File "/usr/lib/python3/dist-packages/middlewared/job.py", line 515, in run
await self.future
File "/usr/lib/python3/dist-packages/middlewared/job.py", line 560, in __run_body
rv = await self.method(*args)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 174, in nf
return await …
```

NAS-134311 / 25.10 / Make sure pid is reported as integer

---

src/middlewared/middlewared/plugins/pool_/dataset_processes.py

This commit fixes an issue where pid for dataset processes is being reported as a string which causes problems when trying to consume as expectation is it will be an integer.
i.e
```
❯ midclt call -j pool.export 41 '{"cascade": true, "destroy": true}'
Status: Terminating processes that are using this pool
Total Progress: [########________________________________] 20.00%
'<=' not supported between instances of 'str' and 'int'
File "/usr/lib/python3/dist-packages/middlewared/job.py", line 515, in run
await self.future
File "/usr/lib/python3/dist-packages/middlewared/job.py", line 560, in __run_body
rv = await self.method(*args)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 174, in nf
return await …
```

NAS-134311 / 25.04-RC.1 / Make sure pid is reported as integer (by sonicaj)

---

src/middlewared/middlewared/plugins/api_key.py

This commit shifts STIG checks to only occur in create and update methods, which in addition to fixing a testing regression also allows for admins to delete existing API keys if needed.

NAS-134316 / 25.10 / Fix API key deletion

---

tests/api2/test_428_smb_rpc.py

This commit adjusts the path in our CI tests for samba changes.
Original PR: https://github.com/truenas/middleware/pull/15772
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132269

NAS-132269 / 25.04-RC.1 / Adjust IPC path for samba changes (by anodos325)

---

src/middlewared/middlewared/plugins/api_key.py

This commit shifts STIG checks to only occur in create and update methods, which in addition to fixing a testing regression also allows for admins to delete existing API keys if needed.
Original PR: https://github.com/truenas/middleware/pull/15771
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134316

NAS-134316 / 25.04-RC.1 / Fix API key deletion (by anodos325)

---

src/middlewared/middlewared/alert/source/truenas_verify.py
src/middlewared/middlewared/plugins/audit/audit.py
src/middlewared/middlewared/plugins/audit/utils.py

Scheduled cryptographic verification of the OS file system
----------------------------------------------------------------
This PR should be merged with the same named PRs in `truenas_verify` and `scale-build`
- Added scheduled cryptographic verification via Alert `check`.  The current schedule is once every 60 minutes.
- Discrepancies found during the scheduled runs are logged to `syslog`
- Install and update:  Generate a version tagged discrepancy log in `/var/log/audit` directory.
NOTE: A verification run can take several seconds on a VM.  This time is added to the initial boot and update boots.  All other boots are not impacted.
---------------------------------------------------------------
**CI tests and update to the diagnostic will be done in separate PRs**

NAS-133968 / 25.10 / Add scheduled cryptographic verification of OS file system for STIG

---

src/middlewared/middlewared/plugins/zfs_/pool_utils.py

Adjust iteration order in find_vdev() to prioritize data vdevs over root-level spares. Previously, the function did not respect vdev hierarchy, leading it to incorrectly return root-level spare vdevs instead of the USED spare (which becomes a data vdev). By restructuring the loop order (placing the while under the for), data vdevs are checked first, ensuring py-libzfs detaches the correct vdev and avoids root-level detachment errors.

NAS-132536 / 25.10 / fix find_vdev() ordering to resolve USED spare detach failure

---

src/middlewared/middlewared/plugins/zfs_/pool_utils.py

Adjust iteration order in find_vdev() to prioritize data vdevs over root-level spares. Previously, the function did not respect vdev hierarchy, leading it to incorrectly return root-level spare vdevs instead of the USED spare (which becomes a data vdev). By restructuring the loop order (placing the while under the for), data vdevs are checked first, ensuring py-libzfs detaches the correct vdev and avoids root-level detachment errors.
Original PR: https://github.com/truenas/middleware/pull/15791
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132536

NAS-132536 / 25.04-RC.1 / fix find_vdev() ordering to resolve USED spare detach failure (by ixhamza)

---

src/middlewared/middlewared/plugins/pool_/pool_disk_operations.py

Fixing a bug with detaching INUSE hot-spares in https://github.com/truenas/middleware/pull/15791 exposed another bug whereby we're failing with EBUSY errors. This is because we're trying to wipe a hot-spare that is INUSE and still in the zpool. Regardless of that bug, we should not be wiping disks on zpool detach. Wiping a disk should be an explicit operation requested by the end-user.

NAS-134345 / 25.10 / dont wipe disks on zpool detach
