gui/templates/storage/volumestatus_datagrid.html
=> Fix traceback in Volume Status

src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh
=> fix(master) add sas3flash -listall for M series

src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh
=> fix(stable) add sas3flash -listall for M series

gui/directoryservice/forms.py
=> Hide User & Group base fields - They aren't supported right now

src/freenas/etc/directoryservice/LDAP/ctl, src/freenas/etc/directoryservice/rc.LDAP
=> Fix broken LDAP Kerberos

src/middlewared/middlewared/alert/base.py
=> fix(alert): Allow lists as alert arguments

src/middlewared/middlewared/plugins/datastore.py
=> datastore.dump_json

tests/api2/webdav_bsd.py, tests/api2/webdav_osx.py
=> add webdav sharing url change

src/freenas-sysctl/directoryservice.c
=> Remove leftover NT4 node

src/freenas-sysctl/directoryservice.c, src/freenas-sysctl/middlewared.c, src/freenas-sysctl/utils.c
=> sysctl configuration for cache & enum (off by default & hidden)

src/freenas-sysctl/directoryservice.c
=> Use proper sysctl trees

src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
=> fix(master) remove 'net usersidlist' from freenas-debug

src/middlewared/middlewared/plugins/rsync.py
While I'm here fix regenerating crontab.
Ticket:	#37862
=> fix(middlewared/rsync): adding rsync task with validate_rpath as false

src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
=> fix(stable) remove 'net usersidlist' from freenas-debug

src/middlewared/middlewared/alert/source/ipmi_sel.py
https://img.devrant.com/devrant/rant/r_34979_J95rY.gif
=> Fix IPMI SEL alerts

src/middlewared/middlewared/alert/source/ntp_status.py
as well as some other related sanity checks. More thorough ones can be derived.
Ticket: #21458
=> Add NTP alert, in case peer is not reachable

src/middlewared/middlewared/alert/source/ntp_status.py
=> fix(alert): Add UnavailableException to NTPStatusAlertSource

gui/account/migrations/0008_migrate_legacy_values.py
This commit updates all users who had a legacy value for the shell nologin which was causing unintended changes
Ticket: #36168
=> Legacy shell values updated

gui/templates/freeadmin/alert_status.html
=> Fix INFO alerts being shown as CRITICAL

src/middlewared/middlewared/async_validators.py, src/middlewared/middlewared/plugins/crypto.py, src/middlewared/middlewared/plugins/iscsi.py, src/middlewared/middlewared/plugins/smart.py, src/middlewared/middlewared/schema.py, src/middlewared/middlewared/validators.py
=> Forbid duplicate e-mail addresses in SMART configuration

src/freenas/boot/brand-FreeNAS.4th, src/freenas/boot/logo-FreeNAS.4th
I used the logo SVG from the webui assets folder, cleaned up the
document a bit, exported to PNG with Inkscape, and converted the image
to text with https://www.text-image.com/convert/ascii.html
The generated text needed a bit of cleanup, then it was run through a
Python script to turn it into Forth code:
https://gist.github.com/freqlabs/02e66c6d676cd156bc60facf9b6e879e
Also fixed a comment and whitespace in the brand artwork.
Ticket: #38699
=> tkt-38699: Replace text logo with ascii art

gui/vm/views.py, src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/network.py, src/middlewared/middlewared/plugins/vm.py
=> tkt-36293: fix(middlewared/vm): get ip from websocket or use provided host for vnc

src/middlewared/middlewared/plugins/vm.py
=> tkt-26434: fix(middlewared/vm): raise errors when VM fails to start

gui/api/resources.py
=> tkt-37590: fix(gui): typo

src/middlewared/middlewared/plugins/unauthorized_reboot_alert.py
=> fix(master) fix verbiage for unauthorized email alerts

src/middlewared/middlewared/plugins/mdns.py
=> Wait for /etc/resolv.conf to be available and valid

src/middlewared/middlewared/plugins/unauthorized_reboot_alert.py
=> tkt-38898 (stable) fix verbiage for unauthorized email alerts

gui/system/views.py, nas_ports/freenas/py-middlewared/Makefile, src/middlewared/middlewared/assets/templates/mail.html, src/middlewared/middlewared/plugins/mail.py, src/middlewared/middlewared/plugins/unauthorized_reboot_alert.py, src/middlewared/middlewared/plugins/update.py, src/middlewared/middlewared/plugins/zfs.py, src/middlewared/middlewared/utils/__init__.py
Probably someone who has sense how our E-Mails would be like should take this from me on this point. I've just added a blue bar on top of message.
=> tkt-26361: Implement high-level function for sending e-mail

src/middlewared/middlewared/plugins/jail.py
This commit forces plugins acceptance from middlewared's end
Ticket: #38355
=> tkt-38355: License acceptance for plugins fix

src/freenas/etc/rc.conf, src/middlewared/middlewared/plugins/jail.py, src/middlewared/middlewared/plugins/network.py
=> tkt-38155: fix(middlewared/jail): add default gateway interface to vnet jail bridge

src/middlewared/middlewared/plugins/nfs.py
Legacy UI was sending null values which nfs plugin was rejecting. This commit fixes that.
Ticket: #38575
=> tkt-38575: Null values fix in NFS plugin

gui/services/forms.py, gui/services/models.py, src/middlewared/middlewared/plugins/iscsi.py
A range of errors was introduced when null was disallowed in middlewared. This commit fixes that and other minor improvements to the code base
Ticket: #36698
=> tkt-36698: Null values fix for iSCSI plugin

src/middlewared/middlewared/plugins/auth.py, src/middlewared/middlewared/plugins/datastore.py, src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/sysdataset.py, src/middlewared/middlewared/plugins/zfs.py, src/middlewared/middlewared/pytest/unit/test_schema.py, src/middlewared/middlewared/schema.py, src/middlewared/middlewared/service.py
=> tkt-39418: null=True should not imply default=None

gui/api/resources.py, gui/middleware/notifier.py, gui/storage/models.py, gui/storage/views.py, src/middlewared/middlewared/alert/source/volume_version.py, src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/zfs.py
This commit moves the functionality of upgrading a ZFS volume from legacy to Middlewared
Ticket: #37594
=> tkt-37594: Volume upgrade moved to Middelwared

gui/freeadmin/static/lib/js/freeadmin/CloudSync.js, gui/freeadmin/static/lib/js/freeadmin/templates/cloudsync.html
=> tkt-36778: fix(oldgui): Allow saving cloud sync even if bucket listing failed

src/middlewared/middlewared/plugins/vm.py
=> tkt-39598: fix(vm): make sure to UP bridge if it already exists

gui/api/resources.py, gui/middleware/notifier.py, gui/storage/views.py, gui/system/views.py, src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/zfs.py
This commit moves the on demand scrub functionality of volumes from legacy to Middlewared.
Ticket: #37598
=> tkt-37598: Volume: Scrub moved to Middlewared

gui/api/resources.py, gui/common/forms.py, gui/freeadmin/static/lib/js/freeadmin/form/Cron.js, gui/storage/models.py, gui/tasks/models.py
This commit adds support for legacy UI to support a more flexible syntax of cron.
Ticket: #39762
=> Legacy UI updated to format a wider cron syntax

gui/services/forms.py
This commit sorts the devices list for extents in legacy UI.
Ticket: #35659
=> Extent Devices list sorted in Legacy UI

src/middlewared/middlewared/plugins/vm.py
=> fix(middlewared): rollback VM creation if anything goes wrong

gui/freeadmin/static/lib/js/freeadmin/Update.js
This commit fixes an issue where a user was able to downgrade his version via legacy UI.
Ticket: #38943
=> tkt-38943: Disallowing unwanted version downgrades in legacy

src/middlewared/middlewared/plugins/vm.py
=> tkt-39223: - Update RancherOS to 1.4.

nas_ports/freenas/freenas-migrate93/Makefile, nas_ports/freenas/freenas-migrate93/distinfo
feat: Show console messages in the footer for truenas
Also remove extra lines per PEP
Ticket: #33270
=> tkt-33270: Bump freenas-migrate93 repo

src/middlewared/middlewared/plugins/stats.py
=> tkt-40788: fix(middlewared/stats): use CallError on rrdtool failure

gui/services/models.py
(cherry picked from commit 1d61337ea20e67729f1cb78ae8cf102613d87385)
(11.1-stable)
Ticket:  #40688
=> Close out block and PEP8 fixes

src/freenas/etc/directoryservice/DomainController/ctl
(cherry picked from commit 1d3dd3eb1c80ff34b3f487cb91cc1fc3753ea1e1)
(11.1-stable)
Ticket: #40668
=> Ticket: #36588

gui/choices.py, gui/services/forms.py, gui/services/views.py, gui/system/models.py
Ticket: #27948
(cherry picked from commit b1493fd7c8bbee28d89f8472d65aedc08a042ffd)
(11.1-stable ticket)
Ticket: #40572
=> Allow binding to loopback address

src/middlewared/middlewared/plugins/mdns.py
Ticket: #28095
(cherry picked from commit 2de2be9509681c64cf0710db8bf1261d3e98a58e)
(cherry picked from commit af841b7107d3de83da1f3c09ddd8826f5eff6694)
(11.1-stable)
Ticket: #40640
=> Monitor mdnsd and restart if necessary. Avoid tracebacks.

src/middlewared/middlewared/etc_files/nsswitch.conf
(cherry picked from commit 1c925b36cc749de86ca7b14581a4e5a490e2fd80)
(11.1-stable)
Ticket: #40684
=> Place winbind after nis and ldap in nsswitch.conf

gui/system/migrations/0022_cert_serial.py
=> Fix dependency

gui/api/resources.py, gui/common/forms.py
This commit is a bug fix for a PR which enhanced the cron syntax support in legacy UI. In this commit, support is added for a wider acceptance of cron syntax with a bug fix for the previous PR.
Ticket: #39762
=> tkt-39762: Bug fix for enhancing cron syntax in legacy UI

src/middlewared/middlewared/plugins/jail.py
Dependent on iocage PR, will return progress and up to date descriptions of each stage.
Ticket: #36948
=> tkt-36948: feat(plugin/jail): Use callback to return plugin progress

gui/account/forms.py, src/middlewared/middlewared/plugins/account.py
This commit fixes a bug where a user resource couldn't be updated if the home_mode attr was not specified in the payload.
Ticket: #40780
=> tkt-40780: Bug fix for api v1

src/freenas/root/.zshrc
=> tkt-36473: feat(zsh): improve prompt and add useful bindkeys

src/middlewared/middlewared/plugins/vm.py
VMs can be started with `overcommit` flag or not.
If overcommit is true we only account for memory actually in use at the
same instant, provided shrink of arc_max, subtracting used swap.
If overcommit is false we try to account for all the memory the VM is
supposed to have available, provided shrink of arc_max, subtracting used swap.
Said logic is implemented in vm.get_available_memory.
Ticket:	#40500
=> tkt-40500: fix(middlewared/vm): refactor how memory is accounted

src/middlewared/middlewared/plugins/vm.py
=> tkt-41064: feat(middlewared/vm): return vm status in vm.query

src/middlewared/middlewared/plugins/vm.py
While I'm here improve clone method.
Ticket:	#40181
=> tkt-40181: fix(middlewared/vm): do not allow multiple VMs with same name

src/freenas/etc/ix.rc.d/ix-inadyn
=> tkt-41272: fix(dyndns): Properly encode passwords in inadyn config

src/middlewared/middlewared/common/smart/smartctl.py, src/middlewared/middlewared/pytest/unit/common/smart/test_smartctl.py
=> tkt-41056: fix(smart): Remove redundant mrsas checks

src/freenas/etc/ix.rc.d/ix-inadyn
=> tkt-41395: fix(dyndns): Properly encode passwords in inadyn config

src/middlewared/middlewared/common/smart/smartctl.py, src/middlewared/middlewared/pytest/unit/common/smart/test_smartctl.py
git cherry-pick d841506f7f27801949dc33d052403741fc11ba99
Ticket: #41056
=> tkt-41400: fix(smart): Remove redundant mrsas checks

src/middlewared/middlewared/logger.py, src/middlewared/middlewared/main.py
=> tkt-41365: feat(middlewared): limit sentry crash reporting

src/middlewared/middlewared/plugins/jail.py
For RELEASE fetching, this will just be a single item array with the value True. For plugins however, it will be the post install notes the users should be shown. One line per item in the array.
=> tkt-40492: feat(plugins): Return a dict with the return value

src/freenas/etc/ix.rc.d/ix-syncdisks, src/freenas/etc/ix.rc.d/ix-syncmultipaths
=> tkt-40864:  Do boot-time disk.multipath_sync after ZFS volume imports

src/middlewared/middlewared/plugins/nfs.py
=> tkt-41435: Allow netgroups in NFS share authorized hosts and IP addresses

gui/choices.py, gui/services/forms.py, gui/services/models.py, src/middlewared/middlewared/plugins/smb.py
This commit adds more choices to the smb plugin for charset fields and moves the generation of charset choices to Middlewared from legacy UI.
Ticket: #41556
=> Updated Charset choices in Middlewared for smb plugin

src/middlewared/middlewared/plugins/vm.py
=> tkt-41580: fix(middlewared/vm): make sure sectorsize is an int

src/middlewared/middlewared/plugins/vm.py
=> tkt-41598: fix(middlewared/vm): validate DISK device

src/freenas/usr/local/bin/freenas-debug, src/freenas/usr/local/libexec/freenas-debug/jails_ng/jails_ng.sh
Calls the iocage debug command
FreeNAS side of https://github.com/freenas/iocage/pull/14
Ticket: #41196
=> tkt-41196: fix(fndebug/jails): Add iocage to this

src/middlewared/middlewared/plugins/jail.py
This ticket improves the validation process for source and destination fields in jails plugin for fstab call.
Ticket: #41060
=> Validation improved for jails fstab

src/freenas/usr/local/libexec/freenas-debug/active_directory/active_directory.sh, src/freenas/usr/local/libexec/freenas-debug/afp/afp.sh, src/freenas/usr/local/libexec/freenas-debug/domain_controller/domain_controller.sh, src/freenas/usr/local/libexec/freenas-debug/iscsi/iscsi.sh, src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh, src/freenas/usr/local/libexec/freenas-debug/smart/smart.sh, src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
=> fix(master) fix misleading verbiage in freenas-debug modules

src/freenas/usr/local/libexec/freenas-debug/active_directory/active_directory.sh, src/freenas/usr/local/libexec/freenas-debug/afp/afp.sh, src/freenas/usr/local/libexec/freenas-debug/domain_controller/domain_controller.sh, src/freenas/usr/local/libexec/freenas-debug/iscsi/iscsi.sh, src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh, src/freenas/usr/local/libexec/freenas-debug/smart/smart.sh, src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
=> fix(stable) fix misleading verbiage in freenas-debug modules

src/middlewared/middlewared/webui_auth.py
=> tkt-40344: fix(middlewared): use text/html content type

src/middlewared/middlewared/plugins/jail.py
Ugly, but what can ya do.
Ticket: #37802
=> tkt-37802: fix(jails/fstab): Make sure we escape spaces how fstab likes

src/middlewared/middlewared/plugins/jail.py
This commit improves validation when creating jails by ensuring that if a jail with the same name exists, we shouldn't go and try to create another one. Secondly, in case of any failure with jail creation, a call is made to delete any resources which still might be allocated.
Ticket: #41694
=> tkt-41694: Improve validation for jail creation

docs/api/resources/storage.rst
This commit updates documentation for unlocking a locked volume via api v1.
Ticket: 42006
=> tkt-42006: Update documentation for unlocking volume

gui/freeadmin/site.py, gui/templates/freeadmin/alert_status.html
=> tkt-42413: fix(alert): Show node name for TrueNAS alerts

src/middlewared/middlewared/plugins/vm.py
=> tkt-42371: fix(middlewared/vm): typo

src/middlewared/middlewared/rclone/remote/google_drive.py
=> tkt-41640: feat(cloud_sync): Google Team Drive support

src/freenas/etc/ix.rc.d/ix-collectd
=> tkt-42725: fix(collectd): Add LogOnce option for df plugin

src/middlewared/middlewared/plugins/jail.py
=> tkt-42761: fix(plugins): Append N/A for version and revision if INDEX doesn't exist

src/middlewared/middlewared/plugins/unscheduled_reboot_alert.py
This is dependant on truenas PR # 178
=> fix(master) read data from file descriptor using OS syscalls

src/middlewared/middlewared/plugins/notifier.py
=> tkt-44075: fix(middlewared/notifier): regression in notifier.ds_get_idmap_object

src/middlewared/middlewared/plugins/disk.py
=> tkt-43811: fix(middlewared/disk): boot.get_disks is no longer an async generator

nas_ports/freenas/py-middlewared/Makefile, src/freenas/usr/local/bin/trueview_stats.sh, src/middlewared/middlewared/plugins/trueview.py
trueview_stats.sh is a proof of concept from Ken Moore which will be
used in True View to gather real time statistics.
=> tkt-44526: feat(middleware/trueview): add trueview.stats event source

src/freenas/etc/ix.rc.d/ix-syncdisks, src/middlewared/middlewared/plugins/disk.py
Ticket:	#44636
(cherry picked from commit 297eb9946d091e1c399a5878b4367f080a7e0448)
=> tkt-42042: feat(middlewared/disk): avoid creating multipath on truenas

gui/storage/forms.py
This commit fixes a bug which prevented users from deleting comments in datasets.
Ticket: #44581
=> tkt-44581: Bug fix for editing datasets

gui/services/utils.py, gui/tools/smart_alert.py
=> tkt-44240: Fix removing SMART alerts for device names (it only worked with paths)

gui/services/utils.py, gui/tools/smart_alert.py
=> tkt-44940: Fix removing SMART alerts for device names (it only worked with paths)

src/freenas/etc/rc.conf
=> tkt-44900: Add --continue-on-error for inadyn to prevent it from exiting on error

src/middlewared/middlewared/logger.py, src/middlewared/middlewared/main.py
Also fix a number of other issues with logging
=> tkt-44482: Fix crash when deleting pool that has system dataset on it

gui/services/models.py, src/freenas/etc/rc.conf, src/middlewared/middlewared/plugins/service.py
=> tkt-44958: Add --continue-on-error for inadyn to prevent it from exiting on error

src/middlewared/middlewared/plugins/jail.py
- Rename uuid -> name for text, as UUID is not a concern to FreeNAS
- Have more verbose progress for fetching
Ticket: #36943
=> tkt-36943: feat(jail/create): Add progress to jail creation and fetching

src/middlewared/middlewared/plugins/etc.py
=> tkt-44790: fix(middlewared/etc): run getpwnam/getgrnam in a thread

src/middlewared/middlewared/plugins/boot.py
=> tkt-45072: fix(middlewared/boot): regression on boot attach and replace

src/freenas/etc/ix.rc.d/ix-syncmultipaths, src/middlewared/middlewared/plugins/disk.py
=> tkt-44636: feat(middlewared/disk): avoid creating multipath on truenas

src/freenas/usr/local/bin/trueview_stats.sh
=> fix(middlewared/trueview): remove debugging echo

src/middlewared/middlewared/plugins/cloud_sync.py, src/middlewared/middlewared/service.py
=> tkt-44991: Fix creating cloud credentials with duplicate names

src/middlewared/middlewared/plugins/nfs.py
=> tkt-45849: Disallow NFS share without paths

src/middlewared/middlewared/plugins/alert.py
=> tkt-45794: Fix restoring gone alert

src/middlewared/middlewared/alert/service/snmp_trap.py
=> tkt-45732: Move pysnmp initialization to thread

src/middlewared/middlewared/plugins/vm.py
=> tkt-46018: fix(middlewared/vm): rebooting a VM

src/middlewared/middlewared/main.py
=> tkt-45743: fix(middlewared): do not fail if `features` is not provided

src/middlewared/middlewared/plugins/disk.py
=> tkt-45721: fix(middlewared/disk): do not make diskinfo fatal, instead skip it

src/middlewared/middlewared/plugins/pool.py
=> tkt-45717: fix(middlewared/pool): `encrypted_disk` may be null

gui/services/migrations/0018_add_asigra_service.py
=> Fat fingered: s/freenas/freenasUI/

src/freenas/usr/local/bin/trueview_stats.sh
=> tkt-47026: feat(trueview_stats): update to include CPU temp and strict gstat

src/middlewared/middlewared/plugins/vm.py
=> tkt-45871: fix(middlewared/vm): raise error if trying to bridge with its own iface

src/middlewared/middlewared/plugins/jail.py
This is to avoid gratuitous exceptions later down the line.
Ticket: #45750
=> tkt-45750: Catch iocage not having a pool activated and reraise as CallError

src/freenas/usr/local/sbin/migrate_warden.py
- Before we used whatever the template was used to create warden jails as the source of truth.  We now use the world's version from jailpath/bin/sh.
- Fix fstab not existing causing a failed migration
Ticket: #46927
=> tkt-46927: fix(warden/migration): Use proper RELEASE

gui/services/views.py
=> Use template file for JNLP file

src/middlewared/middlewared/plugins/vm.py
=> tkt-43866: fix(middlewared/vm): make sure to use unique name for cloned zvol

gui/vm/migrations/0007_device_order.py
=> tkt-46271: fix(vm); preserve original VM devices order

src/middlewared/middlewared/plugins/filesystem.py
=> tkt-47213: feat(middlewared/filesystem): implement filesystem.statfs

src/middlewared/middlewared/rclone/remote/b2.py
=> tkt-45904: Adjust B2 settings titles according to rclone documentation

src/middlewared/middlewared/etc_files/smartd.py
=> tkt-31729: Fix typo in smartd.py

src/middlewared/middlewared/plugins/vm.py
=> tkt-48096: fix(vm): vnc_port may be null

nas_ports/freenas/freenas-ui/Makefile
=> tkt-47580: fix(ports): py-ldap was renamed

nas_ports/freenas/py-middlewared/Makefile
=> tkt-38719: feat(ports): add acme/certbot required ports

src/freenas/etc/ix.rc.d/ix-syslogd
=> tkt-47393 prevent duplicate entries in newsyslog.conf

src/freenas/etc/ix.rc.d/ix-syslogd
=> tkt-47393 prevent duplicate entires in newsyslog.conf (master)

src/middlewared/middlewared/main.py
=> tkt-46821: fix(middlewared): disable loop debug for 11.1

gui/middleware/notifier.py, gui/system/views.py, src/middlewared/middlewared/plugins/service.py
Unused in FreeNAS.
Ticket:	#47514
=> tkt-47514: fix(middlewared/service): add wait and sync to service verbs API

src/middlewared/middlewared/rclone/remote/b2.py
git cherry-pick 442444a0113879fa5ffadd2dabf58619953a62bf
Ticket: #45904
=> tkt-47591: Adjust B2 settings titles according to rclone documentation

src/middlewared/middlewared/plugins/jail.py
This commit adds support for a keyword to be passed in when creating jails configured for ipv6.
Ticket: #48636
=> tkt-48636: Add ipv6 keyword check in ip validator

src/freenas/etc/rc.conf.local
=> tkt-48042: fix(asigra): path for postgresql

tests/api2/auth.py, tests/api2/boot.py, tests/api2/certificate.py, tests/api2/certificateauthority.py, tests/api2/core.py, tests/api2/device.py, tests/api2/filesystem.py, tests/api2/nfs.py, tests/api2/service.py, tests/api2/system.py, tests/api2/vm.py, tests/api2/vmware.py, tests/runtest.py
I am adding vm, vmware, boot, core, certificateauthority, certificate, device filesystem, and service API v2 test. I also have added check invalid user/password and generate token tests to auth api v2 tests.
=> QA-Test tkt-48823 adding various API v2 tests

src/middlewared/Makefile, src/middlewared/middlewared/main.py, src/middlewared/middlewared/service.py, src/middlewared/middlewared/worker.py
=> tkt-37458: Python 3.7 as default

src/freenas-installer/etc/install.sh
Awk has its own pattern matching functionality, so grep before awk can
be eliminated.
Selecting a fixed field can be more efficiently performed with cut.
Misc whitespace/punctuation fixes.
This has no functional change, just needed a commit so we can do this:
DEPENDS: https://github.com/freenas/build/tree/feat-47015
=> [install.sh] Simplify pipelines involving awk

nas_ports/freenas/py-middlewared/Makefile
=> fix(build): fare -> flare

src/freenas/etc/rc.conf.local
=> tkt-49378: fix(asigra): only start it for non-HA

tests/api2/jail.py, tests/api2/update.py
If the time is out The test will fail and skip all test related to that test.
=> QA-Test tkt-49873 Adding timeout 10 minutes for update and jail api test

src/freenas/root/.zshrc
=> tkt-50233: fix(zsh): remove ^H bindkey, incompatible with some terminals

tests/api2/core.py, tests/api2/pool.py
Adding a skip to core/download test until the random problem is pinpoint
=> QA-Test tkt-50398 Adding a skip to core/download test 

src/middlewared/middlewared/plugins/vm.py
=> tkt-50236: - Update RancherOS to version 1.4.1.

src/middlewared/middlewared/plugins/vm.py
=> tkt-50236: - Update RancherOS to version 1.4.1. (#1886)

src/middlewared/middlewared/plugins/jail.py
=> tkt-50409: fix(jail): Use correct pkg branch for listing remote available plugins

src/middlewared/middlewared/plugins/jail.py
=> tkt-50456: fix(jail): Use correct pkg branch for listing remote available plugins

src/freenas/etc/gettytab.template, src/freenas/etc/ix.rc.d/ix-ttys, src/freenas/etc/netcli
This PR is to make sure that netcli is used at all times and we display the web UI URL if consolemenu  option is unchecked in the system.
Ticket: #26237
=> tkt-26237: Use netcli at all times

src/freenas/etc/netcli
This PR fixes an issue which occurred when installing a freenas iso.
Ticket: #26237
=> Make exception handling more broad in netcli

gui/freeadmin/models/fields.py
(cherry picked from commit ad142679da3cc5aff290c335a0e10289b61821f2)
=> tkt-48491: Handle pwenc_decrypt errors in EncryptedDictField

src/middlewared/middlewared/plugins/service.py
=> tkt-43196: fix(smart): Fix smart config not being regenerated when reloading smartd

src/freenas/etc/ix.rc.d/ix-smartd
=> tkt-42773: fix(smart): Remove redundant mrsas checks

src/middlewared/middlewared/plugins/pool.py
=> tkt-50871: fix(middlewared/pool): get correct disks for locked pool

src/freenas/etc/ix.rc.d/ix-sudoers, src/freenas/etc/ix.rc.d/ix-syslogd
base point for /usr/local/etc/tmpfs now
=> Fix for 12.0 where we can have /conf/base/usr__local__etc as the

tests/api2/pool.py, tests/api2/update.py, tests/install.exp, tests/runtest.py
Adding missing tests to verify files for pool.import in pool API v2 test
Adding install.expect change and get_job.text for the update api v2 test.
I did add change to install.expec to continue on failed installation, ixautomation will take care of the problem.
=> QA-Test tkt-50896

src/freenas/etc/ix.rc.d/ix-nginx
This commit fixes a bug to make sure ix-nginx parses the listfield change accordingly for ip fields.
Ticket: #33918
=> Fix bug in ix-nginx

gui/system/forms.py, gui/templates/system/cloudcredentials_add.html, gui/templates/system/cloudcredentials_edit.html, src/middlewared/middlewared/plugins/cloud_sync.py
=> tkt-38550: Add Credential validation to System/Cloud Credentials

src/middlewared/setup.py
=> tkt-50885: Add assets to the middleware distribution

tests/api2/interfaces.py
* also added more results text for all assert
=> QA-Test tkt-51810 change interfaces/query for interfaces

tests/install.exp
* Added all install layout in comments
* Change some expect string
=> QA-Test tkt-51799 Update test/install.exp

src/middlewared/middlewared/plugins/jail.py
Depends on freenas/iocage side of PR
- We now can supply callbacks for progress to check_jail_existence
- exec is no longer returning bytes
- Simplified jail updating call to utilize upstream's lib
- Jail updating is now given progress along with a job description to keep track of output.
Ticket: #37742
=> tkt-37742: feat(jail/update_to_latest_patch): Add progress

gui/vm/forms.py
=> Update default size for Docker Disk File

src/middlewared/middlewared/plugins/jail.py
These two tickets dovetail together, so they're combined into a single PR to reduce unnecessary diffs.
Relies on the iocage PR: https://github.com/freenas/iocage/pull/60
- Add a new dict for options
- RELEASE is now optional, only if the jail is a Plugin
- Add upgrade progress, this changes depending on the type of jail.
- Use iocage's lib for this to reduce amount of stale code
Ticket: #50167
Ticket: #51863
=> tkt-50167: feat(jail/upgrade): Upgrade progress and plugin upgrades

src/middlewared/middlewared/plugins/jail.py
=> tkt-51920: fix(jail/exec): Return a string with stdout or stderr if a process fails

src/middlewared/middlewared/plugins/pool.py
=> tkt-50621: feat(middlewared/pool): document pool.* methods

src/middlewared/middlewared/plugins/service.py
=> tkt-50819: fix(smart): Fix smart config not being regenerated when reloading smartd

gui/middleware/encryption.py, gui/middleware/notifier.py
git cherry-pick c26511647a7bafdc35711fca5176853e53a94944
git cherry-pick da34fbaeee4a5431ba0ad2bd9371e0d3b55a3f8c
=> tkt-50797:  Unblock SIGCHLD before running /usr/sbin/service

gui/middleware/encryption.py, gui/middleware/notifier.py
git cherry-pick c26511647a7bafdc35711fca5176853e53a94944
git cherry-pick da34fbaeee4a5431ba0ad2bd9371e0d3b55a3f8c
=> tkt-50786:  Unblock SIGCHLD before running /usr/sbin/service

src/middlewared/middlewared/plugins/account.py
=> tkt-52149: fix(middlewared/account): allow sshpubkey to be null

gui/middleware/notifier.py, src/winacl/Makefile, src/winacl/winacl.1, src/winacl/winacl.c
Simplify winacl, protect from device traversal, add option to not follow symlinks, and add manpage.
=> tkt-51502: Fix 51502

src/middlewared/middlewared/plugins/jail.py
This avoids surprises later on.
Ticket: #52206
=> tkt-52206: fix(plugins/jail): Use fstab defaults

src/middlewared/middlewared/plugins/jail.py
=> tkt-53089: fix(plugins/jail): Let iocage handle the raising we just want the attr

src/middlewared/middlewared/plugins/vm.py
=> tkt-53215: fix(middlewared/vm): handle null sectorsize

src/middlewared/middlewared/plugins/vm.py
=> tkt-53433: fix(middlewared/vm): handle null sectorsize (by william-gr)

gui/storage/migrations/0011_update_weekday.py, src/middlewared/middlewared/plugins/pool.py
This commit fixes an issue with resilver service making sure that a weekday is selected at all times and adds a migration which reflects this across periodic snapshots and resilver model.
Ticket: #53235
=> tkt-53235: Bug fix for Resilver and Periodic Snapshots

src/middlewared/middlewared/plugins/jail.py
While I'm here make start/stop more robust and allow them to be idempotent.
Ticket: #53575
=> tkt-53575: feat(plugins/jail): Add restart method

src/middlewared/middlewared/plugins/cloud_sync.py
This is not an issue for 11.1/11.3
=> tkt-53676: Fix traceback creating cloud sync without encryption_password

docs/api/resources/storage.rst, gui/api/resources.py, gui/storage/forms.py, gui/storage/views.py, gui/templates/storage/lock.html, src/middlewared/middlewared/plugins/pool.py
This commit ensures that a passphrase is required when locking a pool to prevent unauthorized personnel accidentally locking the pool.
Ticket: #34591
=> tkt-34591: Require passphrase to lock pool

src/middlewared/middlewared/plugins/disk.py
Mirror created by installer and not managed by middlewared.
Ticket:	#50772
=> tkt-53907: feat(middlewared/disk): look for textdump on existing mirror (by william-gr)

tests/api2/interfaces.py
* on iX network ip broadcast and ip address are different.
=> QA-Test tkt-54081 removing broadcast variable 

src/middlewared/middlewared/plugins/mdns.py
While I'm here improve lock syntax.
Ticket:	#53898
=> tkt-53898: fix(middlewared/mdns): avoid traceback by making sure thread exists

src/middlewared/middlewared/plugins/mdns.py
While I'm here improve lock syntax.
Ticket:	#53898
=> tkt-54105: fix(middlewared/mdns): avoid traceback by making sure thread exists (by william-gr)

src/middlewared/middlewared/plugins/jail.py
=> tkt-53883: fix(middlewared/jail): handle exception on boot without pools

src/middlewared/middlewared/plugins/jail.py
=> tkt-54132: fix(middlewared/jail): handle exception on boot without pools (by william-gr)

src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/sysdataset.py
=> tkt-54063: fix(middlewared/pool): properly migrate system dataset on export

src/middlewared/middlewared/plugins/network.py
=> tkt-52757: fix(middlewared/network): skip epair/tun/tap on attach event

gui/freeadmin/static/lib/js/freeadmin/Update.js
- Renamed to better communicate system behavior.
- Tested on FreeNAS hardware: no issues.
=> 11.2 Branch: Rename "Automatic check for updates" on System/Update page:

docs/api/resources/services.rst, gui/api/test_services.py, gui/choices.py, gui/services/forms.py, gui/services/migrations/0001_initial.py, gui/services/migrations/0022_remove_smb_doscharset.py, gui/services/models.py, src/freenas/usr/local/libexec/nas/generate_smb4_conf.py, src/middlewared/middlewared/plugins/smb.py
This commit removes DOS Charset and it's usages from SMB Services.
Ticket: #36833
=> tkt-36833: Remove DOS Charset from SMB Service

gui/system/migrations/0022_cloud_sync.py
=> tkt-53613: fix(migration): catch exception on cloud sync credentials decrypt

src/middlewared/middlewared/plugins/jail.py
This avoids surprises later on.
Ticket: #52206
=> tkt-53350: fix(plugins/jail): Use fstab defaults (by skarekrow)

gui/system/migrations/0022_cloud_sync.py
Ticket:	#53613
(cherry picked from commit bace7a7b3eddc641bbe1dd0e09beebd5d1003896)
=> tkt-54375: fix(migration): catch exception on cloud sync credentials decrypt

gui/middleware/notifier.py
=> tkt-48184: Change dataset aclmode before trying to change permissions.

src/middlewared/middlewared/plugins/datastore.py, src/middlewared/middlewared/plugins/iscsi.py, src/middlewared/middlewared/plugins/zfs.py, src/middlewared/middlewared/utils/__init__.py
git cherry-pick f52fc035057717c7dca92221729b9b47d9b384d6
git cherry-pick 1bf9f94aab2869e3557fc4ab930cd6b87d6c59d4
git cherry-pick a86255c496b397e8618b6c8bb6fa33664a63163f
=> tkt-54630: Allow to select attributes on queries (by william-gr)

src/freenas/etc/netcli
If the user wants to configure failover settings, we also ask if they want to set it critical for failover
Ticket: #26279
=> tkt-54747: feat(netcli): Add critical for failover dialog (by skarekrow)

src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh
cherry-pick commit from master: https://github.com/freenas/freenas/pull/2020/commits/09a05473e6b2e25b723ccde1f103075b9b5cbd99
=> tkt-55734 (stable) fix freenas-debug hang

src/freenas/etc/ix.rc.d/ix-crontab
Redmine: https://redmine.ixsystems.com/issues/28182
1. don't run these cronjobs on the passive controller
2. remove the old ix-crontab-custom entry that is no longer used
=> tkt-28182 (master) don't run cron jobs on truenas passive controllers

src/freenas/etc/ix.rc.d/ix-crontab
Redmine: https://redmine.ixsystems.com/issues/28182
cherry-picked from: 5e9e1bd
=> tkt-28182 (11.1) don't run cron jobs on truenas passive controllers

src/freenas/etc/ix.rc.d/ix-crontab
Redmine: https://redmine.ixsystems.com/issues/28182
cherry-picked from: https://github.com/freenas/freenas/pull/2025/commits/5e9e1bd72bc95ca41a7c64902c359e0f393b4305
=> tkt-28182 (11.2) don't run cron jobs on truenas passive controllers

src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh
Missed the 11.2 branch
cherry-pick commit from master: https://github.com/freenas/freenas/commit/09a05473e6b2e25b723ccde1f103075b9b5cbd99
=> tkt-55734 (11.2) fix freenas-debug hang

src/middlewared/middlewared/plugins/cloud_sync.py
git cherry-pick be9324aab7d62defe1c8850e3fb50a4ada7411d1
=> tkt-56079: Ensure that cloud sync is ran against dataset (by themylogin)

gui/system/utils.py, gui/system/views.py
This commit fixes a circular import issue in certificates.
Ticket: #56256
=> tkt-56256: Fix Circular import issue

gui/services/forms.py, gui/services/migrations/0002_add_s3_service.py, gui/services/models.py, src/middlewared/middlewared/plugins/s3.py
This commit improves validation for s3 service in middlewared wrt storage_path attribute.
Ticket: #56121
=> tkt-56121: Improve validation for s3 Service

src/freenas/usr/local/etc/nginx/nginx.conf
This commit fixes a bug in default nginx conf file which made nginx fail.
Ticket: #56337
=> tkt-56337: Fix default nginx conf file

src/freenas/usr/local/bin/trueview_stats.sh
Several updates:
1. Fix label parsing for the ifstat output
2. Add sysctl information for all ZFS arc stats
3. Add process stats using "ps"
4. Disable the in-kernel memory zone stats (not useful - save a lot of bandwidth/time)
Total effect seems to make the script run faster and return more useful info.
=> tkt-56508: Update trueview_stats.sh

src/freenas/usr/local/bin/trueview_stats.sh
Several updates:
1. Fix label parsing for the ifstat output
2. Add sysctl information for all ZFS arc stats
3. Add process stats using "ps"
4. Disable the in-kernel memory zone stats (not useful - save a lot of bandwidth/time)
Total effect seems to make the script run faster and return more useful info.
=> tkt-56511: Update trueview_stats.sh (by beanpole135)

src/freenas/etc/rc.d/ix-update-scripts, src/middlewared/middlewared/main.py
=> tkt-54573: feat(middlewared): write loading progress to console on boot

src/middlewared/middlewared/plugins/jail.py
Requires PR for Ticket #51997 to be merged first.
- Return True when done
Ticket: #56247
=> tkt-56247: fix(jail/rc): Log starting and stopping jails on boot

src/middlewared/middlewared/logger.py, src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/jail.py, src/middlewared/middlewared/worker.py
Requires PR for Ticket #51997 to be merged first.
Return True when done
Ticket: #56247
=> tkt-56247: STABLE: fix(jail/rc): Log starting and stopping jails on boot

src/middlewared/middlewared/plugins/jail.py
FreeNAS side of https://github.com/freenas/iocage/pull/80
- Allow destruction of CORRUPTED jails
- Add logging configuration to process pools, currently only uses console.
FreeNAS Ticket: #51997
=> tkt-51997: STABLE: fix(jail): Log misconfigured jails

gui/network/forms.py, src/freenas/etc/netcli
=> tkt-56628: fix(vlan): make sure we have a parent interface with `up`

gui/network/forms.py, src/freenas/etc/netcli
=> tkt-56643: fix(vlan): make sure we have a parent interface with `up` (by william-gr)

gui/network/forms.py, src/freenas/etc/netcli
=> tkt-56646: fix(vlan): make sure we have a parent interface with `up` (by william-gr)

src/freenas/etc/ix.rc.d/ix-collectd
For TN-11.1-U6.2
Redmine: https://redmine.ixsystems.com/issues/55998
=> tkt:56430 (11.1-U6.2) exclude snapdirs from collectd df output

src/freenas/etc/rc.d/ix-update-scripts, src/middlewared/middlewared/main.py
git cherry-pick 5dcd25b445f9257399158bbdae3fb529ae4f920b
git cherry-pick e5fe5ba3cc2a9f9eff158eda0c9dda6f2ecf6e82
git cherry-pick 49b0d7f2ee37fabcde5744b1a3f2d7af2df4008a
Ticket:	#54573
=> tkt-56526: feat(middlewared): write loading progress to console on boot (by william-gr)

gui/templates/freeadmin/index.html, gui/templates/menubar.html
=> tkt-54924: fix(gui): url for legacy UI doc

gui/templates/freeadmin/index.html, gui/templates/menubar.html
=> tkt-56499: fix(gui): url for legacy UI doc

docs/api/resources/storage.rst, gui/api/resources.py
This commit fixes a bug where there was an issue with how api v1 handles cloned zvols.
Ticket: #57141
=> Bug fix for cloned zvols

docs/api/resources/storage.rst, gui/api/resources.py
This commit fixes a bug where there was an issue with how api v1 handles cloned zvols.
Ticket: #57141
=> tkt-57528: Bug fix for cloned zvols

src/middlewared/middlewared/plugins/vm.py
=> tkt-57060: - Update RancherOS to v1.4.2 that address CVE-2018-17182.

src/freenas/etc/netcli
=> tkt-58662: fix(netcli): interfaces lookup model name

src/freenas/etc/netcli
=> tkt-58734: fix(netcli): interfaces lookup model name (by william-gr)

src/middlewared/middlewared/plugins/vm.py
=> tkt-58860: fix(middlewared/vm): make sure device VM exists

src/freenas/etc/rc.conf
=> tkt-58968: fix(rc): do not try to load gmirror (builtin module)

tests/api2/core.py
I am splitting test 6 to get info to download and I put the download in test 8
test 7 is to look at the job state of the download is RUNNING
test 9 is to look at the job state of the download is SUCCESS
=> QA-Test tkt-59049 Adding tests for core api v2

src/freenas/usr/local/libexec/nas/scrub
=> tkt-39787: fix(scrub): allow freenas-boot scrub to run on passive/standby

gui/freeadmin/static/lib/js/freeadmin/UnacceptEula.js, gui/support/urls.py, gui/support/views.py, gui/templates/support/home.html, gui/templates/support/license_update.html, src/freenas-installer/etc/install.sh
git cherry-pick 1948c3ed9222bee0545de5c1e07bb4dbd24bbfd7
git cherry-pick 24797809f27e3a0bec5f2ed0406c7a2433f871ee
git cherry-pick b556f58608a2f17a62c0dbbfa8ab4191bea5af6c
=> tkt-59328: Fix EULA (by themylogin)

gui/vm/forms.py
=> tkt-27886: fix(vm): include VLAN parent as possible choice

gui/storage/views.py, src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/zfs.py
If umounting a dataset fails EBUSY error will be raised.
Ticket:	#28215
=> tkt-28215: feat(middlewared/pool): allow to force deletion of datasets

gui/vm/forms.py
=> tkt-28778: fix(gui): regenerate VM NIC choices

src/middlewared/middlewared/plugins/device.py
shlex fails to parse any messages with multiple words as value.
Ticket:	#35263
=> tkt-35263: fix(middlewared/device): parse devd messages using "=" as separator

src/middlewared/middlewared/plugins/replication.py
This can lead to freezes if remote host is not responsive or even a deadlock when remote host is localhost
=> tkt-59760: Fix using synchronous middleware client in asynchronous middleware code (by themylogin)

src/middlewared/middlewared/plugins/iscsi.py
This commit fixes a bug where we were not able to update the value of an iscsi extent disk. Secondly it normalizes the output of iscsi.extent.query with iscsi.extent.create enabling users to see the name of the disk which they selected when creating the disk ( if it was specified while creating ).
Ticket: #55692
=> tkt-55692: Bug fix for iscsi extents

src/freenas/etc/ix.rc.d/ix-update
=> fix(rc): retain same order as before the removal of ix-passwd

src/freenas/etc/ix.rc.d/ix-collectd, src/freenas/etc/ix.rc.d/ix-crontab
pull in remaining PR's for TN 11.1-U6.2 build
=> tkt-55998 (pull in final PR's for TN U6.2 build)

src/freenas/etc/motd.template
=> tkt-59697: fix(motd): bump year in copyright

src/middlewared/middlewared/plugins/jail.py
Also strip \r as it's not needed in these messages.
Ticket: #54717
=> tkt-54717: feat(jail/fetch): Set downloading progress

src/middlewared/middlewared/plugins/etc.py
=> tkt-61089: fix(middlewared/etc): syntax error introduced 3ed90a7

src/freenas/etc/rc.conf.local
=> tkt-61290: feat(ha): add support for BHYVE internal interfaces (by william-gr)

gui/directoryservice/models.py, gui/services/models.py
Redmine: https://redmine.ixsystems.com/issues/61881
=> tkt-61881 (master) externally signed cert fixes for webUI

src/freenas/etc/motd
=> tkt-60660: fix(motd): bump year in copyright (by william-gr)

gui/vm/forms.py
=> tkt-59445: fix(vm): include VLAN parent as possible choice (by william-gr)

gui/directoryservice/models.py, gui/services/models.py
Redmine: https://redmine.ixsystems.com/issues/61881
Cherry pick from master here: https://github.com/freenas/freenas/pull/2188
=> tkt-61881 (11.1) externally signed cert fixes for webUI

gui/directoryservice/models.py, gui/services/models.py
Redmine: https://redmine.ixsystems.com/issues/61881
Cherry pick from master here: https://github.com/freenas/freenas/pull/2188
=> tkt-61881 (11.2) externally signed cert fixes for webUI

gui/vm/forms.py
git cherry-pick 91f5a27f84e0cdc32a165d30221615c6aa1e72cb
Ticket:	#28778
=> tkt-59544: fix(gui): regenerate VM NIC choices (by william-gr)

src/freenas/usr/local/libexec/nas/scrub
=> tkt-59301: fix(scrub): allow freenas-boot scrub to run on passive/standby (by william-gr)

src/middlewared/middlewared/plugins/replication.py
This can lead to freezes if remote host is not responsive or even a deadlock when remote host is localhost
=> tkt-59625: Fix using synchronous middleware client in asynchronous middleware code

gui/network/forms.py, src/middlewared/middlewared/plugins/network.py
=> tkt-61128: fix(gui): properly show network errors and save w/o hostname virtual

docs/api/resources/storage.rst, gui/api/resources.py
This commit fixes a bug where there was an issue with how api v1 handles cloned zvols.
Ticket: #57141
=> tkt-57519: Bug fix for cloned zvols

gui/services/forms.py, gui/services/migrations/0002_add_s3_service.py, gui/services/models.py, src/middlewared/middlewared/plugins/s3.py
This commit improves validation for s3 service in middlewared wrt storage_path attribute.
Ticket: #56121
=> tkt-56112: Improve validation for s3 Service

src/middlewared/middlewared/plugins/jail.py
=> tkt-61884: fix(jail/fstab): Join the exceptions that iocage will return

src/middlewared/middlewared/plugins/jail.py
git cherry-pick 8a74a3797e26b4b66149e3e394237a2aed5f3283
git cherry-pick a633e454eb6f7f3d5b42848ae62eb63be45f93d7
Ticket: #61884
=> tkt-62343: fix(jail/fstab): Join the exceptions that iocage will return (by skarekrow)

src/middlewared/middlewared/plugins/jail.py
git cherry-pick edf61db49652913a3d452fe7c4dc3ca39f4ba10d
Also strip \r as it's not needed in these messages.
Ticket: #54717
=> tkt-60714: feat(jail/fetch): Set downloading progress (by skarekrow)

src/middlewared/middlewared/plugins/disk.py
=> tkt-62001: fix(middlewared/disk): backport label_to_disk required by pool.get_disks

gui/storage/forms.py
=> tkt-62430: fix(gui): do not send passphrase if its empty

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf
This commit removes a leftover usage of vcenter in nginx configuration file which affects the creation of nginx configuration file.
Ticket: #62901
=> tkt-62901: Bug fix for nginx conf

src/freenas/etc/ix.rc.d/ix-nginx
This commit removes a leftover usage of vcenter in nginx configuration file which affects the creation of nginx configuration file.
Ticket: #62910
=> tkt-62910: Bug fix for nginx conf

src/freenas/etc/ix.rc.d/ix-nginx
This commit removes a leftover usage of vcenter in nginx configuration file which affects the creation of nginx configuration file.
Ticket: #62910
=> tkt-62928: Bug fix for nginx conf (by sonicaj)

src/freenas/etc/motd.template
This commit updates motd message concerning copyrights year to 2019.
Ticket: #59697
=> tkt-59697: Update motd

src/middlewared/middlewared/plugins/zfs.py
=> tkt-62703: fix(middlewared/zfs): do not raise exception if snapshot does not exist

src/freenas/boot/loader.conf
Cherry picked from 6f79caa8a205bee8875f647086c7f23cf2823979
=> tkt-43558: [loader.conf] Raise max TCP segment queue length (#2185)

gui/common/freenasldap.py, gui/freeadmin/forms.py
Redmine: https://redmine.ixsystems.com/issues/63414
=> tkt-63414: fix trusted domain users/groups in webUI

src/middlewared/middlewared/plugins/zfs.py
=> tkt-60759: fix(middlewared/zfs): do not get all datasets on zfs.pool.query

src/middlewared/middlewared/plugins/zfs.py
=> tkt-64251: fix(middlewared/zfs): do not get all datasets on zfs.pool.query (by william-gr)

gui/common/freenasldap.py, gui/freeadmin/forms.py
Redmine: https://redmine.ixsystems.com/issues/63414
=> tkt-64206: fix trusted domain users/groups in webUI (by yocalebo)

gui/common/freenasldap.py, gui/freeadmin/forms.py
Redmine: https://redmine.ixsystems.com/issues/63414
=> tkt-64215: fix trusted domain users/groups in webUI (by yocalebo)

src/middlewared/middlewared/plugins/pool.py
=> tkt-64284: fix(middlewared/pool): handle pool not found traceback

src/middlewared/middlewared/restful.py
=> tkt-64593: feat(middlewared/restful): output message and traceback on any error

gui/network/forms.py
=> tkt-64053: fix(gui/api): clean up main ipv4 field if DHCP is checked

gui/network/forms.py
=> tkt-64764: fix(gui/api): clean up main ipv4 field if DHCP is checked (by william-gr)

src/middlewared/middlewared/plugins/crypto.py
This commit introduces a change where we disallow any non ec based key of length less then 1024 when a certificate is created.
Ticket: #62892
=> tkt-62892: Disallow keys of length less then 1024

src/freenas/etc/ttys.template
on virtual terminals that may not exist when using bhyve
Ticket: #65025
=> Update our default /etc/ttys file to not try and spawn lots of sessions

src/freenas/etc/ix.rc.d/ix-etc
=> Add fix to ix-etc which ensures we re-run cap_mkdb on login.conf

gui/middleware/notifier.py, src/middlewared/middlewared/plugins/pwenc.py
This commit fixes a bug where encrypted dict field could not be used in middlewared setup stage.
=> tkt-66331: Bug fix for pwenc

src/middlewared/middlewared/plugins/iscsi.py
This commit improves the validation error message outlining the case for lowercase names in iSCSI.
Ticket: #66048
=> tkt-66048: Naming correction for iSCSI

src/middlewared/middlewared/etc_files/local/netdata/alarms.py, src/middlewared/middlewared/plugins/netdata.py
This commit makes sure that the changes reflected in netdata port are reflected in netdata service in middlewared as well. It also improves how we read/write alarm configurations.
Ticket: #67035
=> Update Netdata Service

src/middlewared/middlewared/plugins/mail.py
git cherry-pick 03532c5df6c8a045364b471056e8251986faac02
git cherry-pick 6463826abe62c4e93c2df12b8a83cc25b4cea9ab
While I'm here also make sure only ValueError is not logged.
Ticket:	#67618
=> tkt-68079: Only allow ascii password (by william-gr)

src/middlewared/middlewared/plugins/jail.py
=> tkt-67530: fix(jail/fetch): Grab all command output for plugin post_installs

src/middlewared/middlewared/plugins/jail.py
=> tkt-68187: fix(jail/fetch): Grab all command output for plugin post_installs (by skarekrow)

gui/settings.py
=> tkt-68203: fix(gui): we dont need debug messages from ws4py (by william-gr)

src/middlewared/middlewared/plugins/vm.py
=> tkt-67944: fix(middlewared/vm): make sure the dir structure exists when creating VM

src/middlewared/middlewared/plugins/vm.py
=> tkt-68221: fix(middlewared/vm): make sure the dir structure exists when creating VM (by william-gr)

src/middlewared/middlewared/plugins/vm.py
=> tkt-29409: feat(vm): Add VM name as description to created tap

src/middlewared/middlewared/plugins/update.py
=> tkt-65589: fix(middlewared/update): use description from trains.txt

src/middlewared/middlewared/plugins/update.py
=> tkt-68493: fix(middlewared/update): use description from trains.txt (by william-gr)

src/middlewared/middlewared/plugins/vm.py
=> tkt-68473: feat(vm): Add VM name as description to created tap (by skarekrow)

src/freenas/etc/motd
This commit bumps year in copyright to 2019.
Ticket: #60660
=> tkt-60660: Bump year in copyright

src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/zfs.py
=> tkt-61632: fix(middlewared/zfs): detaching disks when a guid is used on replace

src/middlewared/middlewared/plugins/disk.py
=> tkt-40560: fix(middlewared/disk): try to remove disks from graid

gui/sharing/models.py
We decided to hide / auto-generate this field.
=> tkt-23359: Remove unnecessary tooltip for vuid

gui/sharing/models.py
We decided to hide / auto-generate this field.
=> tkt-68835: Remove unnecessary tooltip for vuid (by anodos325)

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf
This commit enables gzip compression for nginx.
Ticket: #64377
=> tkt-64377: Gzip compression in nginx

src/middlewared/middlewared/plugins/disk.py, src/middlewared/middlewared/plugins/ipmi.py, src/middlewared/middlewared/plugins/mail.py, src/middlewared/middlewared/plugins/system.py, src/middlewared/middlewared/plugins/vm.py, src/middlewared/middlewared/plugins/vmware.py
git cherry-pick 4a9e8540951995b2f464af78d0d039246f3a3421
=> tkt-69465: fix(middlewared): it reads `private` not `password` (by william-gr)

src/freenas/etc/rc.conf
=> Revert "tkt-58995: fix(rc): do not try to load gmirror (builtin module) (by william-gr)"

src/middlewared/middlewared/plugins/cloud_sync.py, src/middlewared/middlewared/rclone/remote/sftp.py
git cherry-pick cdbe8bcf795c2d91732c2ef453b88bda949855c8
=> tkt-69771: fix(cloudsync): Make SFTP pass/key_file fields not required (by themylogin)

gui/services/migrations/0026_s3_fields.py
This commit fixes a migration dependency and name so that migrations are applied properly.
=> Change migration name

src/middlewared/middlewared/main.py, src/middlewared/middlewared/utils/lock.py
Allow up to 10 calls to happen concurrently with a hard limit of 20
(calls above that start getting refused).
Ticket:	#69339
=> tkt-69339: feat(middlewared): add a semaphore for calls within the same connection

gui/freeadmin/static/lib/js/freeadmin.js, gui/system/forms.py, src/middlewared/middlewared/plugins/crypto.py
This PR aims to introduce the following changes:
1) Introduce CryptoKeyService
1) Use cryptography library for our crypto plugin's backend which is more well maintained
2) Introduce ec based keys creation in both middlewared and legacy UI
3) Consolidate x509 certificates and public/private keys logic which will include generation, parsing and validation
4) Fixes a bug where when we signed CSR's, we lost their SAN extension which then were not reflected in the newly generated certificate
Ticket: #64581
=> Introduce Elliptic Curve Based Keys

src/freenas/etc/netcli
Ticket:	#58662
(cherry picked from commit e69396096f4c3a3c27d8816d7041310fddf77a37)
(cherry picked from commit 3cb0ee083219bd1d4d12f1c5a7a86b90906343d8)
=> tkt-56643: fix(netcli): interfaces lookup model name

src/middlewared/middlewared/plugins/update.py
This commit fixes a bug where we did not wait for a coroutine
=> Update bug fix

src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/sysdataset.py
This PR introduces the following changes:
1) We don't lock a pool which is being used by system dataset
2) We don't allow end user to set/change passphrase for a pool which is being used by system dataset
3) We don't allow system datasets to be configured with any pool which has a passphrase set
Ticket: #71971
=> Configure Encrypted Pools Correctly

src/middlewared/middlewared/plugins/boot.py
This commit adds a new endpoint for updating boot scrub interval value as the previous case made us validate all the other system.advanced service attributes as well.
=> tkt-72113: New API endpoint for Boot Scrub

src/middlewared/middlewared/utils/__init__.py
This commits adds filters to negate startswith and endswith filters which are already present in middlewared.
=> Add More Filters

src/middlewared/middlewared/plugins/mail.py
As per https://redmine.ixsystems.com/issues/67618#note-19
=> 67618: Fix email password error text (8-bit to 7-bit)

src/middlewared/middlewared/plugins/mail.py
Per https://redmine.ixsystems.com/issues/67618#note-19
=> 67618: Fix email password error message (11.2 PR)

gui/reporting/rrd.py, gui/reporting/urls.py, gui/templates/reporting/index.html, src/freenas/etc/ix.rc.d/ix-ups, src/freenas/usr/local/bin/custom-upssched-cmd, src/freenas/usr/local/etc/sudoers, src/middlewared/middlewared/etc_files/local/collectd.conf, src/middlewared/middlewared/plugins/reporting.py, src/middlewared/middlewared/plugins/service.py, src/middlewared/middlewared/plugins/ups.py
This PR aims to introduce following changes:
1) Include statistics in emails on various UPS events for the UPS battery's current status
2) Add a collectd plugin to collect UPS statistics
3) Show UPS statistics in UI
=> tkt-34143: UPS Stats

src/middlewared/middlewared/utils/__init__.py
This commits adds filters to negate startswith and endswith filters which are already present in middlewared.
=> tkt-72499: Add More Filters

src/freenas/etc/ix.rc.d/ix-fstab, src/middlewared/middlewared/etc_files/fstab, src/middlewared/middlewared/etc_files/fstab_configure.py, src/middlewared/middlewared/plugins/etc.py, src/middlewared/middlewared/plugins/service.py
This PR aims to move ix-fstab to etc plugin.
Ticket: #70210
=> tkt-70210: Move ix-fstab to etc

src/middlewared/middlewared/alert/source/multipaths.py
This commits fixes an alert where we had a leftover usage of old multipath function.
=> Bug fix for alerts

src/middlewared/middlewared/plugins/vm.py
=> tkt-73729: fix(bhyve): prevent setting vfs.zfs.arc_max to lower than vfs.zfs.arc… (by themylogin)

src/freenas/etc/ix.rc.d/ix-preinit, src/middlewared/middlewared/plugins/init_shutdown_script.py
This PR aims to bring the functionality of ix-preinit to the etc plugin.
Ticket: #70282
=> tkt-70282:  Convert ix-preinit to etc

src/freenas/etc/rc.d/ix-postinit, src/middlewared/middlewared/plugins/init_shutdown_script.py, src/middlewared/middlewared/service.py
This PR aims to move ix-postinit functionality to Middlewared.
Ticket: #70291
=> tkt-70291: Convert ix-postinit to Middlewared

gui/services/migrations/0026_delete_vm_kmem_size_tunable.py
=> [migrations] Fix typo

src/freenas/etc/rc.conf
This enables the microcode update service.
Ticket: #39099
=> tkt-39099: Let the microcode update, if applicable.

src/middlewared/middlewared/plugins/crypto.py
=> tkt-72081: fix(middlewared/crypto): make sure directory tree exists

src/middlewared/middlewared/plugins/multipath.py
(cherry picked from commit be16a870ed6509e96540c91b043956a587f019eb)
=> feat(middlewared/multipath): unused logging and drop old formatting

src/middlewared/middlewared/plugins/disk.py
=> tkt-71443: fix(middlewared/disk): backport `devname` from master

src/middlewared/middlewared/etc_files/fstab_configure.py
This commit addresses reviews for ix-fstab conversion to middlewared.
=> Address fstab reviews

src/freenas/usr/local/etc/sudoers, src/middlewared/middlewared/etc_files/local/sudoers
This commit removes sudoers base file and moves the default sudoers data to the etc plugin
=> tkt-70345: Remove sudoers base file

src/middlewared/middlewared/plugins/iscsi.py
This commit improves validation for querying portals and initiators before trying to insert them as a foreign key in database.
Ticket: #70581
=> Improve iscsi validation

src/middlewared/middlewared/plugins/boot.py
This commit adds a new endpoint for updating boot scrub interval value as the previous case made us validate all the other system.advanced service attributes as well.
=> tkt-72123: New API endpoint for Boot Scrub (by sonicaj)

src/middlewared/middlewared/etc_files/fstab, src/middlewared/middlewared/plugins/disk.py
=> tkt-35560: feat(middlewared/disk): only set up swap for disks with configured pools

src/freenas/etc/find_alias_for_smtplib.py, src/middlewared/middlewared/plugins/account.py
This commit fixes a recursive dependency for aliases which resulted in an infinite loop.
Ticket: #75532
=> tkt-75532: Fix recursive dependency for aliases

src/freenas/etc/find_alias_for_smtplib.py, src/middlewared/middlewared/plugins/account.py
This commit fixes a recursive dependency for aliases which resulted in an infinite loop.
Ticket: #75532
=> tkt-75991: Fix recursive dependency for aliases (by sonicaj)

src/freenas/etc/netcli
=> tkt-75019: fix(netcli): restore ability to change root password without middlewa… (by themylogin)

src/freenas/etc/netcli
=> tkt-75010: fix(netcli): restore ability to change root password without middlewa… (by themylogin)

src/freenas/usr/local/libexec/freenas-debug/network/network.sh
https://redmine.ixsystems.com/issues/75171
=> tkt-75171: change netstat -i to netstat -in in freenas-debug

src/freenas/usr/local/libexec/freenas-debug/network/network.sh
Redmine: https://redmine.ixsystems.com/issues/75180
=> tkt-75180: change arp -a to arp -an in freenas-debug

src/freenas/usr/local/libexec/freenas-debug/network/network.sh
Redmine: https://redmine.ixsystems.com/issues/75180
=> tkt-76098: change arp -a to arp -an in freenas-debug (by yocalebo)

src/freenas/usr/local/libexec/freenas-debug/network/network.sh
https://redmine.ixsystems.com/issues/75171
=> tkt-76080: change netstat -i to netstat -in in freenas-debug (by yocalebo)

src/freenas/usr/local/libexec/freenas-debug/network/network.sh
https://redmine.ixsystems.com/issues/75171
=> tkt-76089: change netstat -i to netstat -in in freenas-debug (by yocalebo)

gui/system/utils.py
…ller debug
Redmine: https://redmine.ixsystems.com/issues/75181
=> tkt-76099: change middleware job timeout to 10mins for passive contro… (by yocalebo)

gui/system/models.py, src/middlewared/middlewared/plugins/crypto.py
This commit makes sure that we don't set SAN in the subject of CSR's/certs.
Ticket: #72571
=> tkt-72571: Remove SAN from subject

src/middlewared/middlewared/plugins/crypto.py
This commit simplifies SAN extraction code in middlewared and also makes sure that we trust the extension of SAN instead of it being in the subject as specified by RFC 5280.
=> tkt-76108: Simplify SAN code in middlewared

src/middlewared/middlewared/plugins/pool.py
Otherwise we are stopping iocage jails that are unrelated to this pool.
Ticket: #74569
=> tkt-74569: fix(pool/export): Only stop jails if the pool is the same as activated

gui/tools/autorepl.py
git cherry-pick b43391569e38723fee6be3789cac269e45118231
=> tkt-76179: Remove unsupported ciphers (they were not used anyway) (by themylogin)

gui/storage/models.py
git cherry-pick a7a5f4339553f470fa4b30f1eee5ca2819a86b76
git cherry-pick b6212f17b3389fcf2fc955ec87ec308883c843ff
Otherwise we are stopping iocage jails that are unrelated to this pool.
Ticket: #74569
=> tkt-76162: fix(pool/export): Only stop jails if the pool is the same as activated (by skarekrow)

src/middlewared/middlewared/alert/base.py, src/middlewared/middlewared/alert/service/aws_sns.py, src/middlewared/middlewared/alert/service/hipchat.py, src/middlewared/middlewared/alert/service/mail.py, src/middlewared/middlewared/alert/service/mattermost.py, src/middlewared/middlewared/alert/service/slack.py, src/middlewared/middlewared/plugins/system.py
git cherry-pick 8bc5fb856473c7b674b8827425347b67e73cf612
git cherry-pick de61932c25d5b75720aa70fac586ed501daefb69
git cherry-pick 200eb6aa3810effd9fa173fb723247c0b052ec22
=> tkt-76215:  Add product name and hostname to alerts body (by themylogin)

gui/storage/forms.py
git cherry-pick e220bbd78891e285e2a591560f689be0b4d423ea
Ticket:	#34636
=> tkt-76350: feat(mw|gui): reload iscsi when zvol size changes (by william-gr)

gui/system/forms.py
This commit updates tooltip for SMTP server password field.
Ticket: #73866
=> tkt-73866: Update tooltip for password field

src/middlewared/middlewared/plugins/smb.py
- Allow multiple shares to have same path.
- Prevent multiple shares with same name.
=> tkt-74551: Allow multiple SMB shares with same path

gui/system/forms.py
This commit updates tooltip for SMTP server password field.
Ticket: #73866
=> tkt-76360: Update tooltip for password field (by sonicaj)

src/middlewared/middlewared/plugins/smb.py
- Allow multiple shares to have same path.
- Prevent multiple shares with same name.
=> tkt-76386: Allow multiple SMB shares with same path (by anodos325)

src/freenas/etc/rc.conf.local
Redmine: https://redmine.ixsystems.com/issues/76242
=> tkt-76242: let truenas ha code manage smartd service

src/freenas/etc/rc.conf.local
Redmine: https://redmine.ixsystems.com/issues/76242
=> tkt-76450: let truenas ha code manage smartd service (by yocalebo)

src/freenas/etc/rc.conf.local
I must not know how to use the bugclerk.
(cherry picked from commit a0357726198089ac8034e436f35b61cbb539167e)
=> tkt-76459: let truenas ha code manage smartd service

src/middlewared/middlewared/plugins/vm.py, src/middlewared/middlewared/service.py
=> tkt-44779: feat(vm/clone): Allow cloning by name

src/middlewared/middlewared/plugins/system.py
=> tkt-76594: feat(middlewared/system): implement system.general.ui_certificate_choices

src/middlewared/middlewared/plugins/system.py
=> tkt-76639: feat(middlewared/system): implement system.general.ui_certificate_choices (by william-gr)

src/middlewared/middlewared/plugins/crypto.py
This commit updates certificate extend method so that we can easily distinguish between different types of certs.
=> Update certificate extend method

src/middlewared/middlewared/plugins/jail.py, src/middlewared/middlewared/service.py
Let's us troubleshoot any jail problems easier
Ticket: #42815
=> tkt-42815: fix(jail/logging): We want iocage to be in debug mode for operations

src/freenas/etc/rc.conf.local
Redmine: https://redmine.ixsystems.com/issues/76242
=> tkt-76459: let truenas ha code manage smartd service (by yocalebo)

src/middlewared/middlewared/plugins/jail.py
git cherry-pick b6bef5998d4760abfaf1fdcdafe3c3de68091c0d
Ticket: #73047
=> tkt-73054: feat(jail/stop): Add force flag to stop (by skarekrow)

src/middlewared/middlewared/plugins/vm.py
=> tkt-74515: fix(vm): vnc web url when host is an ipv6 address

gui/tools/autorepl.py
Redmine: https://redmine.ixsystems.com/issues/76431
=> tkt-76431: ensure variables are stripped of leading/trailing whitespace

gui/tools/autorepl.py
Redmine: https://redmine.ixsystems.com/issues/76431
=> tkt-77215: ensure variables are stripped of leading/trailing whitespace (by yocalebo)

gui/tools/autorepl.py
Redmine: https://redmine.ixsystems.com/issues/76431
=> tkt-77224: ensure variables are stripped of leading/trailing whitespace (by yocalebo)

src/middlewared/middlewared/plugins/vm.py
git cherry-pick 45127a3e186d021fd07dfda35d8364480e2823c0
Ticket:	#74515
=> tkt-77206: fix(vm): vnc web url when host is an ipv6 address (by william-gr)

src/middlewared/middlewared/plugins/vm.py
=> tkt-42923: fix(vm/start): We now validate on start

src/freenas/usr/local/lib/collectd_pyplugins/disktemp.py, src/middlewared/middlewared/plugins/disk.py
git cherry-pick c5b1b9584cc765df49e7add17d3f5e7a24ded4b3
git cherry-pick a1ae15a381232bc5b093ac3a612446db1e8408e5
=> tkt-76531: fix(collectd): Do not poll for temperature on drives with SMART disabled (by themylogin)

gui/common/freenasldap.py
Fix regression with user/group validation in AD environments
=> tkt-76000: Fix regression with user/group validation in AD environments

gui/middleware/notifier.py
This commit fixes a regression from the multipath changes we introduced earlier.
=> tkt-77368: Bug fix for multipath

src/autotune/files/autotune.py
(cherry-picked from [362cbaf](https://github.com/freenas/freenas/commit/362cbaffa4444411c515e8bf5daba2082ee94ac2) and [7766816](https://github.com/freenas/freenas/commit/776681646d55800b6d617e9204fbdb86bf9a74c2))
Ticket: #73917
=> [autotune] Don't touch vm.kmem_size (11.1)

src/autotune/files/autotune.py
(cherry-picked from 362cbaffa4444411c515e8bf5daba2082ee94ac2 and 776681646d55800b6d617e9204fbdb86bf9a74c2)
Ticket: #73917
=> [autotune] Don't touch vm.kmem_size (11.2)

gui/choices.py
(cherry picked from commit 4bef0d671920851cd2e17309770aa9d8d36e4004)
=> tkt-71939: Elaborate LDAP_SSL_CHOICES.

src/freenas/etc/ix.rc.d/ix-zfs
=> tkt-76612: fix(rc): midclt is not in PATH for boot

src/middlewared/middlewared/etc_files/local/nut/ups.conf, src/middlewared/middlewared/etc_files/local/nut/upsd.conf, src/middlewared/middlewared/etc_files/local/nut/upsd.users, src/middlewared/middlewared/plugins/ups.py
@sonicaj did you drop these on purpose?
=> Restore UPS extra options

gui/api/resources.py
Regressed in 986e3d75 .
Ticket:	#65943
=> tkt-65943: fix(api): id should be allowed for volume

gui/api/resources.py
Regressed in 986e3d75 .
Ticket:	#65943
=> tkt-77800: fix(api): id should be allowed for volume (by william-gr)

src/middlewared/middlewared/plugins/account.py
=> tkt-77719: fix(middlewared/account): do not leave a new homedir behind on error

src/middlewared/middlewared/plugins/update.py
=> tkt-78168: fix(middlewared/update): set user train on update.update

src/middlewared/middlewared/plugins/update.py
=> tkt-78205: fix(middlewared/update): set user train on update.update (by william-gr)

gui/common/freenasldap.py, gui/directoryservice/forms.py, gui/directoryservice/migrations/0006_certificate_model.py, gui/directoryservice/models.py, src/freenas/usr/local/libexec/nas/generate_sssd_conf.py, src/middlewared/middlewared/etc_files/local/nslcd.conf, src/middlewared/middlewared/etc_files/local/nss_ldap.conf, src/middlewared/middlewared/etc_files/local/openldap/ldap.conf
This PR aims to bring the following changes:
1) Migrate CA's to Certificates in Directory Services
2) Remove all CA related usages in Directory Services
3) Bug fix which for ldap.conf which would result in failure to generate ldap.conf under certain conditions because of an exception raised
Ticket: #76440
=> tkt-76440: Migrate CA's to Certificate in Directory Services

README.md
Hi, the table was broken so I opened this PR to fix it :)
=> Fix broken table in README

gui/system/alert.py
Redmine: https://redmine.ixsystems.com/issues/78636
=> tkt-78636: return empty list on failure for alert system

src/middlewared/middlewared/plugins/zfs.py
=> tkt-78286: fix(middlewared/zfs): mount dataset after snapshot clone

src/middlewared/middlewared/plugins/pool.py
=> tkt-78340: fix(middlewared/pool): configure swaps after importing pools on boot

src/middlewared/middlewared/main.py
=> tkt-78825: fix(middlewared): use login(1) for webshell

nas_ports/freenas/py-middlewared/Makefile, src/middlewared/middlewared/plugins/reporting.py
Its too heavy of a module, bringing too many dependencies.
Ticket:	#71489
=> tkt-71489: feat(middleware/reporting): do not use pandas module

src/middlewared/middlewared/plugins/jail.py
Other side of iocage ticket
Ticket: #76864
=> tkt-76864: fix(jail/fstab): Remove replacement of spaces and split on tabs

src/middlewared/middlewared/plugins/jail.py
Other side of iocage ticket
Ticket: #76864
=> tkt-79824: fix(jail/fstab): Remove replacement of spaces and split on tabs (by skarekrow)

src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Redmine: https://redmine.ixsystems.com/issues/80337
=> tkt-80337: fix regression in unified smb configuration

src/middlewared/middlewared/etc_files/local/apache24/Includes/webdav.conf, src/middlewared/middlewared/plugins/webdav.py
This commit makes sure webdav share directories exist when we create/update or start webdav service.
Ticket: #79851
=> tkt-79851: Ensure webdav share directories exist

src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Redmine: https://redmine.ixsystems.com/issues/80337
=> tkt-80373: fix regression in unified smb configuration (by yocalebo)

src/middlewared/middlewared/plugins/device.py
We dont want a stacktrace in that case.
=> fix(middleware/device): handle ConnectionRefusedError

src/middlewared/middlewared/plugins/iscsi.py
=> tkt-80085: fix(middleawre/iscsi): do not allow duplicate tags for iSCCI Auth

docs/api/resources/sharing.rst, gui/api/resources.py, gui/freeadmin/static/lib/js/freeadmin.js, gui/sharing/admin.py, gui/sharing/forms.py, gui/sharing/migrations/0015_add_shadow_copy_checkbox.py, gui/sharing/models.py, src/middlewared/middlewared/etc_files/local/smb4_share.conf, src/middlewared/middlewared/plugins/smb.py
- Add checkbox to GUI "enable snapshots"
- Remove snapshot task selection dropdown
=> tkt-76621: Implement shadow_copy_zfs as default

gui/vm/migrations/0009_auto_20190315_1058.py
This commit checks if a volume exists before selecting the first volume as in the case where we don't have any volumes i.e build, this will result in a failure.
=> Volume check in migration

gui/services/forms.py, src/middlewared/middlewared/etc_files/local/rsyncd.conf, src/middlewared/middlewared/plugins/rsync.py
This PR fixes following issues with rsync plugin:
1) Correctly generating the rsyncd configuration file
2) Correcting escape issues with remote/local paths
3) Introducing validation to rsync mod service
Ticket: #81399
=> tkt-81399: Bug fixes in Rsync Plugin

gui/storage/views.py, src/middlewared/middlewared/plugins/vmware.py, tests/api2/vmware.py
This commit removes duplicates and sorts the datastores which are fetched for vmware plugin in legacy UI.
Ticket: #72957
=> tkt-72957: Improve datastore listing in vmware

src/middlewared/middlewared/pytest/functional/test_0095_vmware.py, tests/api2/vmware.py
This commit updates vmware tests to reflect the new format returned by get_datastores call.
=> Update vmware tests

nas_ports/freenas/py-middlewared/Makefile
=> tkt-83371: feat(ports): hook up py-cam

src/middlewared/middlewared/etc_files/smartd.py, src/middlewared/middlewared/plugins/service.py, src/middlewared/middlewared/pytest/unit/etc_files/test_smartd.py
git cherry-pick 0f98ef8590acacedbe0db6195ead295d7fa2caec
git cherry-pick c115e3e2127b86284294d3b91cbbd15c95c86d2c
=> tkt-79104: fix(smart): Fix SMART service startup (by themylogin)

gui/middleware/notifier.py, src/freenas/etc/ix.rc.d/ix-collectd, src/freenas/etc/ix.rc.d/ix-ldap, src/freenas/etc/ix.rc.d/ix-loader, src/freenas/etc/ix.rc.d/ix-ups, src/freenas/etc/rc.d/ix-update-scripts, src/freenas/usr/local/bin/freenas-debug, src/freenas/usr/local/bin/ixdiagnose, src/freenas/usr/local/libexec/freenas-debug/smart/smart.sh, src/middlewared/middlewared/plugins/sysdataset.py
git cherry-pick 3f9173d917fc66110ef2fbe2b46b0b43e21356f1
=> tkt-82650: Be a bit more safer on our rm(1) usages (by william-gr)

gui/choices.py, gui/services/migrations/0001_initial.py, gui/services/models.py, src/middlewared/middlewared/plugins/dyndns.py
This commit exposes supported Dynamic DNS Providers choices in middlewared.
Ticket: #83700
=> tkt-83700: Expose Supported Dynamic DNS Providers

src/middlewared/middlewared/plugins/zfs.py
=> tkt-79158: fix(middlewared/zfs): mount dataset after snapshot clone (by william-gr)

src/middlewared/middlewared/plugins/iscsi.py
git cherry-pick 48b120a0069635e7e3b5b6a08cf39afeac807b06
Ticket:	#80085
=> tkt-80724: fix(middleawre/iscsi): do not allow duplicate tags for iSCCI Auth (by william-gr)

gui/services/forms.py, src/middlewared/middlewared/plugins/rsync.py
git cherry-pick 8d6c5223f5ed6deceb479a2bd8f00b08ce2ee3ba
git cherry-pick c1a17e2129900d69566e4bd736e4d09f38c03f90
This PR fixes following issues with rsync plugin:
1) Correctly generating the rsyncd configuration file
2) Correcting escape issues with remote/local paths
3) Introducing validation to rsync mod service
Ticket: #81399
=> tkt-82713: Bug fixes in Rsync Plugin (by sonicaj)

nas_ports/freenas/py-middlewared/Makefile
=> tkt-83379: feat(ports): hook up py-cam

gui/choices.py, gui/services/migrations/0001_initial.py, gui/services/models.py, src/middlewared/middlewared/plugins/dyndns.py
This commit exposes supported Dynamic DNS Providers choices in middlewared.
Ticket: #83700
=> tkt-83731: Expose Supported Dynamic DNS Providers (by sonicaj)

src/freenas/usr/local/libexec/nas/generate_ctl_conf.py
Backport of #2545 to freenas/11.2-stable
Ticket: #73569
=> (11.2-stable) Fix quoting of generated values in ctl.conf

src/freenas/usr/local/lib/collectd_pyplugins/disktemp.py
=> tkt-83147: feat(collectd): try to use `cam` to get temperature for SCSI disks

src/freenas/usr/local/lib/collectd_pyplugins/disktemp.py
git cherry-pick 693f8cdac824f1af852bb1c7a244b5e253cf07a9
Ticket:	#83147
=> tkt-83875: feat(collectd): try to use `cam` to get temperature for SCSI disks (by william-gr)

src/middlewared/middlewared/etc_files/rc.conf.py, src/middlewared/middlewared/plugins/nfs.py
@yocalebo is this what you wanted yesterday?
=> Normalize NFSv4 and TN HA

src/middlewared/middlewared/plugins/mdns.py
=> tkt-84052: fix(middlewared/mdns): deadlock waiting for dns

src/middlewared/middlewared/plugins/jail.py
=> tkt-29578: feat(jail/fetch): Add secure fetching

gui/choices.py, src/middlewared/middlewared/job.py, src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/zfs.py, src/middlewared/middlewared/utils/__init__.py, src/middlewared/middlewared/worker.py
git cherry-pick efa67bc4e8f794e7b654f3a1fa8102079c03c22c
git cherry-pick 6fcbb7ee552cdd44c1d1e62641440d014ded1b5b
git cherry-pick ee8a95ec9173955cbb98cb4f762af8835e93b9a4
git cherry-pick f07104c1857cda0b369de5e5a2cfd421d6b0a7bb
=> tkt-83908: Run zfs services in the process poll (by william-gr)

tests/api2/afp.py
=> QE tkt-84443 adding afp tests to make sure that afp.update {} does not change apf data

src/middlewared/middlewared/plugins/jail.py
=> tkt-39653: fix(jail/fetch): Remove plugin index workaround

src/middlewared/middlewared/plugins/zfs.py
=> tkt-84771: fix(middlewared/zfs): do not sue coroutine for libzfs routines

src/middlewared/middlewared/etc_files/local/nut/upsmon.conf, src/middlewared/middlewared/plugins/ups.py
This PR improves UPS validation making sure certain fields are always required by UPS Service else it will fail to start.
Ticket: NAS-101320
=> Improve UPS Validation

src/middlewared/middlewared/plugins/jail.py, tests/api2/jail.py
Update tests to reflect this
NAS-101362
=> fix(jail): Make start, stop, restart and exec jobs

src/middlewared/middlewared/plugins/cloud_sync.py, src/middlewared/middlewared/plugins/cron.py, src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/replication.py, src/middlewared/middlewared/plugins/rsync.py, src/middlewared/middlewared/plugins/smart.py, src/middlewared/middlewared/plugins/snapshot.py, src/middlewared/middlewared/schema.py
This PR adds defaults for services using Cron Schema to ensure that we specify the defaults in the service's Cron Schema.
Ticket: NAS-101376
=> Defaults for Cron Schema

src/middlewared/middlewared/plugins/alert.py
git cherry-pick -x 68933ef734315f66b148efede5bc6e09be4af9fc
git cherry-pick -x 7aa2a254777eb177f127239cf10b61dfc88c2f3b
=> NAS-101386 / 11.3 /  Do not run alerts if failover is not complete yet (by themylogin)

src/middlewared/middlewared/plugins/sysdataset.py
freenas-boot will now host system dataset on first boot.
Once a pool is created the system dataset will be migrated to the data
pool.
NAS-101372
=> tkt-101372: NAS-101372 feat(middlewared/sysdataset): use freenas-boot, temporarily

gui/system/forms.py, src/middlewared/middlewared/plugins/alert.py
git cherry-pick -x 726ed446a0691682c44ebe3f3cab274f4d0f3737
git cherry-pick -x 076bf3f5206a3384dfb558a34eae58928a6a060c
=> NAS-101074 / 11.3 /  Block VolumeStatus alert source while creating pool (by themylogin)

src/middlewared/middlewared/plugins/pool.py
=> NAS-101374 / 11.3 / fix(middlewared/pool): also treat 0 as "none"

src/middlewared/middlewared/plugins/update.py
=> NAS-101368 / 11.3 / fix(middlewared/update): allow `null` destination

src/freenas/etc/netcli
https://jira.ixsystems.com/browse/NAS-101226
=> NAS-101226: Clarify "reset interface" message

gui/api/utils.py
=> NAS-100933 / 11.3 / fix(api): handle MultipleObjectsReturned for Config models

src/middlewared/middlewared/plugins/pool.py
=> NAS-101374 / 11.2 / fix(middlewared/pool): also treat 0 as "none" (by william-gr)

gui/api/utils.py
=> NAS-100933 / 11.2 / fix(api): handle MultipleObjectsReturned for Config models (by william-gr)

src/middlewared/middlewared/plugins/boot.py
=> NAS-101205 / 11.2 / feat(middlewared/boot): create swap partition if boot disk has one

src/middlewared/middlewared/plugins/disk.py
=> NAS-101185 / 11.3 / fix(middlewared/disk): do not try to savecore on used single disk swap

src/middlewared/middlewared/plugins/disk.py
git cherry-pick -x b9a1245f80b4df135448cdd02442d71e5bb13a17
Ticket:	NAS-101185
=> NAS-101185 / 11.2 / fix(middlewared/disk): do not try to savecore on used single disk swap (by william-gr)

src/freenas/usr/local/libexec/freenas-debug/ldap/ldap.sh
Jira: https://jira.ixsystems.com/browse/NAS-101431
=> NAS-101431 / 11.3 / remove expensive LDAP operations in freenas-debug

src/freenas/usr/local/libexec/freenas-debug/ldap/ldap.sh
Jira: https://jira.ixsystems.com/browse/NAS-101431
=> NAS-101431 / 11.1 / remove expensive LDAP operations in freenas-debug (by yocalebo)

src/freenas/usr/local/libexec/freenas-debug/ldap/ldap.sh
Jira: https://jira.ixsystems.com/browse/NAS-101431
=> NAS-101431 / 11.2 / remove expensive LDAP operations in freenas-debug (by yocalebo)

gui/system/forms.py
=> NAS-101435 / 11.3 / fix(gui): log failed delete and raise original exception

gui/system/forms.py
=> NAS-101435 / 11.2 / fix(gui): log failed delete and raise original exception (by william-gr)

src/middlewared/middlewared/plugins/alert.py
git cherry-pick -x 43b288aef43a9b0a3839bf39ba07aefd23992980
=> NAS-101212 / 11.3 / Do not show tracebacks for failover remote call errors (by themylogin)

gui/storage/forms.py
=> NAS-101418 / 11.3 / fix(gui): destroying zvol

tests/api2/ups.py
Adding more tests for verifying output of PUT and GET, and make it more
visible.
=> QE tkt-86099 Cherry pick "Adding driver to PUT UPS test"

src/freenas/etc/ix.rc.d/ix-shutdown, src/middlewared/middlewared/plugins/alert.py, src/middlewared/middlewared/plugins/system.py
git cherry-pick -x 8cf49aced14898aec6bc4e32f2844e32c5fbdd46
git cherry-pick -x 7d80f1721ca82ca0ca3698d13463a5cba3a0c25a
=> NAS-101178 / 11.3 / Nas 101178 (by themylogin)

src/freenas/etc/find_alias_for_smtplib.py
=> NAS-101425 / 11.3 / fix(mail): infinite loop aliases

src/freenas/etc/find_alias_for_smtplib.py
=> NAS-101425 / 11.2 / fix(mail): infinite loop aliases (by william-gr)

src/middlewared/middlewared/plugins/network.py
=> NAS-101416 / 11.3 / fix(middlewared/network): do not allow bridge as VLAN parent

src/middlewared/middlewared/alert/source/scrub_paused.py, src/middlewared/middlewared/plugins/zfs.py
git cherry-pick -x 802da281bc9e0e6034973958572324679b58a4a1
=> NAS-101487 / 11.3 / Fix ScrubPausedAlertSource using libzfs (by themylogin)

src/freenas/etc/ix.rc.d/ix-syncmultipaths, src/middlewared/middlewared/plugins/disk.py
This reverts commit d6e188498703bd088f444b4c44f10b0d16679855.
=> NAS-100408 / 11.3 / Revert "feat(middlewared/disk): avoid creating multipath on truenas"

src/freenas/etc/ix.rc.d/ix-syncmultipaths, src/middlewared/middlewared/plugins/disk.py
This reverts commit d6e188498703bd088f444b4c44f10b0d16679855.
=> NAS-100408 / 11.2 / Revert "feat(middlewared/disk): avoid creating multipath on truenas" (by william-gr)

src/freenas/etc/ix.rc.d/ix-update
This reverts commit 53102012d4864c01a51da6f51469a8a794a71cb9.
=> NAS-100734 / 11.2 / Revert "Fix "unscheduled system reboot" alert after update"

src/freenas/etc/ix.rc.d/ix-update
This reverts commit 53102012d4864c01a51da6f51469a8a794a71cb9.
=> NAS-100734 / 11.3 / Revert "Fix "unscheduled system reboot" alert after update" (by themylogin)

gui/tools/autorepl.py
Jira: https://jira.ixsystems.com/browse/NAS-101496
=> NAS-101496 / 11.1 / fix legacy replication to allow spaces in dataset names

src/middlewared/middlewared/plugins/ipmi.py
=> NAS-101517 / 11.3 / fix(middlewared/ipmi): allow `null` vlan

src/freenas/usr/local/etc/syslog-ng.conf.freenas
git cherry-pick -x b508ec7e9fa4b6515b91c3fa09f23f609918f914
=> NAS-101512 / 11.2 / fix(syslog): use latest syslog-ng version (by themylogin)

src/freenas/usr/local/etc/syslog-ng.conf.freenas
git cherry-pick -x b508ec7e9fa4b6515b91c3fa09f23f609918f914
=> NAS-101512 / 11.1 / fix(syslog): use latest syslog-ng version (by themylogin)

src/freenas/usr/local/etc/syslog-ng.conf.freenas
=> NAS-100988 / 11.3 / fix(syslog): listen on loopback only

src/middlewared/middlewared/plugins/disk.py, src/middlewared/middlewared/plugins/pool.py
=> NAS-100194 / 11.3 / feat(middlewared/pool): format disks in parallel for create/destroy

src/freenas/usr/local/etc/syslog-ng.conf.freenas
=> NAS-100988 / 11.1 / fix(syslog): listen on loopback only (by william-gr)

src/middlewared/middlewared/plugins/sysdataset.py
=> NAS-101409 / 11.3 / fix(middlewared/sysdataset): pass exclude_pool to setup method

gui/system/migrations/0042_2fa_authentication.py, gui/system/models.py, src/middlewared/middlewared/etc_files/local/ssh/sshd_config, src/middlewared/middlewared/etc_files/local/users.oath, src/middlewared/middlewared/etc_files/pam.d/sshd, src/middlewared/middlewared/plugins/auth.py, src/middlewared/middlewared/plugins/etc.py, src/middlewared/middlewared/utils/exceptions.py
This PR introduces Two Factor Authentication with following changes:
1) Introduces a service to manage 2FA.
2) Supports TOTP ( time based OTP ) only for right now as it is generally considered more secure then standard HOTP ( counter based ) which can be valid for unknown period of time.
3) Ability to use google authenticator or other 2FA apps.
Ticket: NAS-100123
=> Two-Factor Authentication

src/middlewared/middlewared/plugins/disk.py
=> NAS-101571 / 11.3 / fix(middleware/disk): typos setting `disk_type`

src/middlewared/middlewared/plugins/zfs.py
=> NAS-101303 / 11.3 / fix(middlewared/zfs): handle ENOENT on snapshot query

src/middlewared/middlewared/plugins/zfs.py
=> NAS-101303 / 11.2 / fix(middlewared/zfs): handle ENOENT on snapshot query (by william-gr)

src/middlewared/middlewared/plugins/network.py
=> NAS-101574 / 11.3 / feat(middlewared/network): do not allow interfaces changes with HA enabled

src/middlewared/middlewared/plugins/jail.py
This commit inreases the ip formats we currently support to create jails reflecting iocage. This is particularly needed for new UI so they can just pass ip for vnet+ip jails.
=> NAS-101572 / 11.3 / Allow more ip formats for jails

src/middlewared/middlewared/plugins/alert.py
git cherry-pick -x c04330c5fa2c88411a409e94dd39ce9e6308807c
=> NAS-101588 / 11.3 / Respect alert service enabled field (by themylogin)

gui/tools/autorepl.py
Jira: https://jira.ixsystems.com/browse/NAS-101496
=> NAS-101496 / 11.2 / fix legacy replication after QA failure

gui/tools/autorepl.py
Jira: https://jira.ixsystems.com/browse/NAS-101496
=> NAS-101496 / 11.1 / fix legacy replication after QA failure (by yocalebo)

tests/api2/ups.py
=> QE tkt-86739 Adding FreeNAS API test to start and stop ups service

gui/network/forms.py
=> NAS-100773 / 11.3 / fix(gui): create VLAN interface with `up`

src/middlewared/middlewared/etc_files/loader.py
=> NAS-101654 / 11.3 / feat(etc/loader): disable kern.cam.boot_delay for VMs

tests/api2/tunable.py
Adding more test to get tunable objects
Adding test to make sure that tunable is deleted
=> QE tkt-87014 Modified tunable API testing to get the id

gui/system/forms.py
=> NAS-101723 / 11.3 / fix(gui): deleting alert service

gui/system/forms.py
=> NAS-101723 / 11.2 / fix(gui): deleting alert service (by william-gr)

src/middlewared/middlewared/plugins/pool.py
=> NAS-101710 / 11.3 / fix(middleawared/pool); do not skip importing a pool on first error

src/middlewared/middlewared/alert/base.py
=> NAS-101728 / 11.3 / fix(middlewared/alert): fix formatting for threaded alert services

src/middlewared/middlewared/alert/base.py
=> NAS-101728 / 11.2 / fix(middlewared/alert): fix formatting for threaded alert services (by william-gr)

src/middlewared/middlewared/plugins/jail.py
=> NAS-101668 / 11.3 / fix(jail/fstab): We should split on both spaces and tabs

src/middlewared/middlewared/plugins/jail.py
Will show all branches available on the plugin index
NAS-101776
=> NAS-101776 / 11.3 / feat(jail/list_resource): Add branches to enum

gui/freeadmin/static/lib/js/freeadmin/CloudSync.js, gui/tasks/widgets.py
git cherry-pick -x 6e69924f3551d81ee9ae05ed4d32be64253dfcd0
=> NAS-101757 / 11.2 / Fix cloud sync legacy UI javascript escaping bug (by themylogin)

src/middlewared/middlewared/plugins/network.py
=> NAS-101799 / 11.3 / feat(middlewared/network): return number of seconds remaining

src/middlewared/middlewared/plugins/jail.py
=> NAS-101809 / 11.3 / fix(jail/list_resource): Return a list of dicts for BRANCHES

src/middlewared/middlewared/plugins/sysdataset.py
=> NAS-101808 / 11.2 / fix(middlewared/sysdataset): set update=True

src/middlewared/middlewared/plugins/sysdataset.py
=> NAS-101808 / 11.1 / fix(middlewared/sysdataset): set update=True (by william-gr)

src/middlewared/middlewared/etc_files/rc.conf.py
git cherry-pick -x 3e65bacc6b39b2dca364e910286f6ef049956f26
=> NAS-101789 / 11.3 / Disable netdata on passive controller (by themylogin)

src/middlewared/middlewared/plugins/service.py
@william-gr I've decided to remove this commit from https://github.com/freenas/freenas/pull/3063 because I've found this https://github.com/freenas/freenas/commit/f78bc8f78868298e204e5e74a7433f0585523add
However, in my tests minio rc script perfectly works with this patch
=> Better feedback from _system

src/middlewared/middlewared/plugins/alert.py
git cherry-pick -x d5bd0698bcfee652b84ed98c44853266b7788899
…node
=> NAS-101821 / 11.3 / Do not report transport-related errors when running alerts on backup … (by themylogin)

src/middlewared/middlewared/alert/source/volume_rekey.py
git cherry-pick -x 155da784b451441f71cd4403a8e745966b1ec9aa
=> NAS-101825 / 11.3 / Make Volume Rekey Alert worth reporting to iX as it was in 11.1 (by themylogin)

src/middlewared/middlewared/plugins/smart.py
This commit adds support in middlewared so a user can trigger manual smartctl tests for disks specified.
Ticket: NAS-100104
=> NAS-100104 / 12 / Run manual smartctl tests

gui/middleware/notifier.py, src/middlewared/middlewared/plugins/disk.py
Instead of a full sync at the end.
Ticket:	NAS-101854
=> NAS-101854 / 11.2 / fix(gui): avoid syncing disk table on every disk format

src/middlewared/middlewared/alert/base.py, src/middlewared/middlewared/plugins/alert.py
git cherry-pick -x 0cf08116075c100f377f2f633696ac9c1dfeadd7
git cherry-pick -x 497ff80e557a35cee33181eeda948db5243c6448
git cherry-pick -x 2bcb7b569d9058d9e45d3a3fa927eb498b2e5483
…ert fails
=> NAS-101675 / 11.3 / Generate an alert when creating a new ticket for TrueNAS proactive al… (by themylogin)

src/middlewared/middlewared/plugins/usage.py
This will collect anonymous data that can be aggregated.
NAS-101420
=> feat(usage): Add usage collector plugin

src/middlewared/middlewared/plugins/jail.py
…in resource
This will allow the UI to request a cache busting call with a button to get up to date INDEX information for plugins.
NAS-101604
=> NAS-101604 / 11.2 / feat(jail/list_resource): Allow avoiding the cache on the remote plug… (by skarekrow)

src/freenas/usr/local/etc/syslog-ng.conf.freenas
=> Revert "NAS-100988 / 11.1 / fix(syslog): listen on loopback only (by william-gr)"

src/middlewared/middlewared/plugins/smb.py
Applying default permissions over an existing dataset can take a considerable amount of time. Move to job to avoid timeouts.
=> NAS-101445 / 11.2 / Move 'apply default perms' to a middleware job

src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
When users alter zfs acls through File Explorer / SMB, posix mode will often
be altered because nfs4:mode = special (SMB client has no knowledge of
special ACEs (owner@, group@). This can in edge cases result in a mode
such as 0070. MacOS clients will effectively strip the extended ACL information
when copying the file to the client. There are cases where an admin who has
intimate knowledge of nfs4 acls may want to have this enabled, but in the case
of FreeNAS 11.2 with nfs4:mode = special, it is probably best to turn this off
by default.
=> NAS-101685 / 11.2 / Default to fruit:nfs_aces = no

src/middlewared/middlewared/plugins/jail.py
=> NAS-101895 / 11.2 / fix(middlewared/jail): try/except DC block

src/middlewared/middlewared/plugins/jail.py
FreeNAS side for https://github.com/iocage/iocage/pull/923
If an index is not supplied and the action isn’t LIST, we expect a source and destination. In addition we supply a default for source and destination if an index is supplied.
NAS-101531
=> NAS-101531 / 11.2 / fix(jail/fstab): Add more validation (by skarekrow)

src/middlewared/middlewared/plugins/jail.py
This commit introduces following changes:
1) Removes 'edit' option from fstab api because 'edit' action in iocage refers to an interactive session.
2) Make sure right params exist for add/replace/remove actions.
3) Always set up reasonable defaults for iocage api which fixes a bug where replace failed as we forced src/destination to be empty strings.
Ticket: #101525
=> NAS-101525 / 11.3 / Improve fstab validation

src/freenas/etc/ix.rc.d/ix-nginx
=> NAS-101918 / 11.2 / feat(nginx): only enable /ui for FreeNAS

gui/storage/views.py
This commit improves scrub actions validations making sure the user is appropriately informed if a scrub cannot be paused/started/stopped for some reason.
Ticket: #NAS-101822
=> NAS-101822 / 11.3 / Improve scrub actions validation in legacy UI

gui/services/migrations/0032_openvpn_models.py, gui/services/models.py, gui/system/migrations/0044_revoked_field.py, gui/system/models.py, src/freenas/etc/ix.rc.d/ix-etc, src/middlewared/middlewared/alert/source/certificates.py, src/middlewared/middlewared/etc_files/generate_ssl_certs.py, src/middlewared/middlewared/etc_files/local/nginx/nginx.conf, src/middlewared/middlewared/etc_files/local/openvpn/client/openvpn_client.conf, src/middlewared/middlewared/etc_files/local/openvpn/server/openvpn_server.conf, src/middlewared/middlewared/etc_files/rc.conf.py, src/middlewared/middlewared/plugins/crypto.py, src/middlewared/middlewared/plugins/etc.py, src/middlewared/middlewared/plugins/service.py, src/middlewared/middlewared/plugins/vpn.py, src/middlewared/middlewared/pytest/unit/test_schema.py, src/middlewared/middlewared/schema.py
This PR aims to introduces the following changes:
1) Ability to use FN/TN as an OpenVPN Server.
2) Ability to use FN/TN as an OpenVPN Client.
3) Ability to revoke certificates which have been compromised.
4) Manage extensions for certificates.
Ticket: NAS-100114
=> NAS-100114 / 12 / OpenVPN as a Service

src/freenas/usr/local/libexec/freenas-debug/system/system.sh
=> NAS-101954 / 11.3 / add swap usage to top output in freenas-debug

gui/tools/autorepl.py
git cherry-pick -x bec110602b79430988500326ecac93c336a61d99
=> NAS-101826 / 11.3 / Do not crash autorepl.py on misconfigured SSH connection (by themylogin)

src/freenas/usr/local/lib/collectd_pyplugins/disktemp.py, src/middlewared/middlewared/plugins/disk.py
git cherry-pick -x faa39e94097ab24bbbfe9e103c34f98e5612e3f7
=> NAS-100735 / 11.3 / Fix HDDs not entering standby (by themylogin)

gui/tools/autosnap.py, src/middlewared/middlewared/plugins/vmware.py
git cherry-pick -x 25363e8cb63f35cef9c02e3ce4c7623b015091b0
=> NAS-101944 / 11.3 / New VMware snapshot flags (by themylogin)

gui/system/forms.py
git cherry-pick -x a7feae53e2a7dfb75971b8db85f3a33f07761b0c
=> NAS-101823 / 11.3 / Fix Alert Services tab glitch (by themylogin)

src/middlewared/middlewared/plugins/vm.py
=> NAS-101261 / 11.3 / fix(middlewared/vm): add 1400x1050 to possible choices

src/middlewared/middlewared/plugins/update.py
=> NAS-101877 / 11.3 / feat(middlewared/update): implement `update.set_train`

src/middlewared/middlewared/alert/base.py, src/middlewared/middlewared/plugins/alert.py
git cherry-pick -x d77efc3ce6dc82b37980983313a10f856f9557d2
git cherry-pick -x 15662ed62be15413b96540bb149a4ee15dbf0d0e
=> NAS-101982 / 11.3 /  Better test alert message (by themylogin)

gui/system/forms.py, gui/system/views.py, src/middlewared/middlewared/plugins/config.py
This PR adds the ability to be able to download/upload config with encrypted pool keys.
Ticket: #NAS-101827
=> NAS-101827 / 11.3 / Download/Upload config with encrypted pool keys

src/middlewared/middlewared/plugins/jail.py
This commit introduces the ability to specify a custom jail name which can be used to create a plugin. It does not break the existing API and introduces another field for the custom field name which can be passed over. If that is not passed, default behaviour is to use the plugin's name.
=> NAS-101625 / 11.3 / Ability to specify jail name when fetching plugin

src/middlewared/middlewared/plugins/vmware.py
git cherry-pick -x 034ec4978a8ff612ef19a8ba363d3bdb5db63544
=> NAS-101956 / 11.3 / Fix VMWareService.get_datastores():195 - Unknown volume type "other" (by themylogin)

src/middlewared/middlewared/plugins/jail.py, src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/restful.py, src/middlewared/middlewared/schema.py
This PR aims to fixes errors outlined by swagger in our schema layer.
Ticket: #NAS-101447
=> NAS-101447 / 11.3 / Swagger definition issues

tests/api2/filesystem.py
Change assert for acl to False in test 03
=> QE NAS-102065 Fix results.test syntax in filesystem API testing

tests/api2/pool_dataset.py
and changing test to get getacl with pytest instead of for loop
=> QE NAS-102079 Adding the missing default_acl variable

src/middlewared/middlewared/plugins/disk.py
=> NAS-102081 / 11.2 / fix(middlewared/disk): add default value for sycn in disk.wipe

src/middlewared/middlewared/plugins/jail.py
This will allow the GUI to mimic iocage’s cli look.
NAS-100551
=> NAS-100551 / 11.3 / feat(jail): Add jid to returned dictionary

src/freenas-installer/etc/installer12.sh
=> Install kernel-debug with other OS bits, and make sure a failure

src/middlewared/middlewared/plugins/jail.py
=> Address William’s review

src/middlewared/middlewared/plugins/bootenv.py, src/middlewared/middlewared/plugins/datastore.py, src/middlewared/middlewared/plugins/zfs.py
This PR aims to introduce changes to make sure we accurately retrieve boot environment space with focus being on displaying space such as how much space would be freed if the respective BE is deleted.
Ticket: #NAS-102021
=> NAS-102021 / 12 / Accurately Retrieve Boot Environment space

gui/directoryservice/forms.py, src/middlewared/middlewared/etc_files/pam.d/ftp, src/middlewared/middlewared/etc_files/pam.d/ftpd, src/middlewared/middlewared/etc_files/pam.d/netatalk, src/middlewared/middlewared/etc_files/pam.d/pam.inc, src/middlewared/middlewared/etc_files/pam.d/samba, src/middlewared/middlewared/etc_files/pam.d/sshd, src/middlewared/middlewared/plugins/kerberos.py, src/middlewared/middlewared/plugins/ldap.py
- Add pam_krb5 to pam config if we have kerberized LDAP environment.
- Fix error where legacy UI wasn't encrypting the keytab inserting it.
- Fix various issues related to kinit in LDAP environment.
=> NAS-102091 / 11.3 / Fix ldap plugin for kerberized LDAP environments

src/middlewared/middlewared/plugins/jail.py
This will append the PLUGIN_INFO to a plugin for the UI to display in a web element, otherwise null.
NAS-100818
=> NAS-100818 / 11.3 / feat(jail/list_resource): Return PLUGIN_INFO

src/middlewared/middlewared/plugins/s3.py
=> NAS-102120 / 11.3 / Fix key error in s3 plugin

gui/tasks/migrations/0014_ini_comment_field.py, gui/tasks/models.py, src/middlewared/middlewared/plugins/init_shutdown_script.py, src/middlewared/middlewared/validators.py
This commit adds a migration and updates the initshutdown model to include a comment field.
=> NAS-100209 / 12 / Add comment field for  initshutdown model

src/middlewared/middlewared/plugins/idmap.py
- overlap with previously configured idmap range
- overlap between DS_TYPE_ACTIVEDIRECTORY and DS_TYPE_DEFAULT_DOMAIN if AD backend is autorid
- overlap with disabled directory services
- overlap between separate AD domains with the 'ad' backend.
=> NAS-102169 / 11.3 / Allow idmap range overlaps in some situations

tests/api1/ad_bsd.py, tests/api1/ad_osx.py
=> QE NAS-102192 Fix API v1 activedirectory testing for osx and bsd

src/middlewared/middlewared/plugins/jail.py, src/middlewared/middlewared/service.py
This PR introduces changes to reliably retrieve plugin versions using `packagesite` defined for each plugin.
=> NAS-100704 / 11.3 / Retrieve plugin versions

src/middlewared/middlewared/plugins/jail.py
This PR aims to normalize how we list plugins and templates opting to use dictionaries instead of lists which is very hard to use.
=> NAS-102168 / 11.3 / Normalize listing resources in jail plugin

src/middlewared/middlewared/plugins/pool.py
Erin ask me for this for https://jira.ixsystems.com/browse/NAS-102199
=> pool.filesystem_choices: filter by type

src/middlewared/middlewared/plugins/jail.py
If a plugin jail is renamed, we are unable to show the correct versions for it. This commit fixes the issue by correctly identifying which plugin a plugin jail represents.
=> NAS-102205 / 11.3 / Bug fix for renamed plugin jails

src/middlewared/middlewared/plugins/cloud_sync.py
=> NAS-102221 / 11.2 / fix(middlewared/cloud_sync): do not require all attributes on update

src/middlewared/middlewared/plugins/jail.py
This commit exposes api in jail plugin allowing users to clone jails via jail plugin.
=> NAS-101090 / 11.3 / Expose cloning method for jails in jail plugin

src/freenas/usr/local/libexec/freenas-debug/jails/jails.sh
Ticket: NAS-102225
Disable the Jails section of the freenas debug for TrueNAS in 11.2
=> NAS-102225 / 11.2 / disable jails section for truenas

src/freenas/usr/local/libexec/freenas-debug/jails/jails.sh
=> NAS-102225 / 11.3 / only run this section on freenas and truenas licensed for jails

src/middlewared/middlewared/plugins/jail.py
=> NAS-102183 / 11.3 / fix(jail/common_validation): Validate jail names as well

gui/directoryservice/forms.py, src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/kerberos.py
Remove requirement for netbios name in AD form.
=> NAS-102230 / 11.3 / Fix AD plugin for APIv1

src/middlewared/middlewared/plugins/network.py
=> NAS-102212 / 11.3 / fix(middlewared/network): clear pending changes on rollback

src/middlewared/middlewared/plugins/vm.py
=> NAS-101482 / 11.3 / fix(vm): Correctly overcommit memory

src/middlewared/middlewared/job.py, src/middlewared/middlewared/plugins/cloud_sync.py
git cherry-pick -x a250dbde70c93d77c259a6ae89e3271868268765
git cherry-pick -x 41a5cbc42845746c49ab2eaa166c36f659b8f7d1
git cherry-pick -x 88e4749d3c7512c33e8c456795fb7f4be45485cc
git cherry-pick -x b936a3e2762a8709fec077591a1d456abc2b99d4
=> NAS-102226 / 11.3 /  Explain DropBox path/restricted_content/ error (by themylogin)

src/middlewared/middlewared/client/client.py, src/middlewared/middlewared/plugins/pool.py
=> NAS-102190 / 11.3 / feat(middlewared/pool): translate a few zfs error codes and document it

src/middlewared/middlewared/plugins/jail.py
This commit exposes a force flag for destroying a jail in jail plugin.
=> NAS-102281 / 11.3 / Expose destroying jail force flag

src/middlewared/middlewared/plugins/vm.py
This adds a bool to allow the UI to implement a checkbox for zvol cleanup during vm deletion.
NAS-100292
=> NAS-100292 / 11.3 / feat(vm/delete): Allow deleting DISKs

gui/freeadmin/static/lib/js/freeadmin.js, gui/system/forms.py, src/middlewared/middlewared/plugins/sysdataset.py
Reboot passive controller after system dataset changes
=> NAS-101725 / 11.3 / Reboot passive storage controller after system dataset changes (by anodos325)

src/middlewared/middlewared/plugins/datastore.py, src/middlewared/middlewared/restful.py, src/middlewared/middlewared/service_exception.py, src/middlewared/middlewared/utils/__init__.py
We want these to be a 404 instead of a 500
NAS-102203
=> NAS-102203 / 11.3 / fix(restful): Catch IndexErrors

src/middlewared/middlewared/plugins/nfs.py, src/middlewared/middlewared/pytest/unit/plugins/test_nfs.py
git cherry-pick -x 679326ce600ab2d16004780d05bf8a0093ed7639
=> NAS-102229 / 11.2 / Make NFS checks more sane (by themylogin)

src/middlewared/middlewared/plugins/jail.py
This commit makes use of new api for listing resources.
=> NAS-102412 / 11.3 / Use new api for listing resources in jail plugin

src/middlewared/middlewared/etc_files/afpd.py, src/middlewared/middlewared/plugins/notifier.py
This commit fixes a bug where we defined a variable in a different scope and used in a different one.
=> Bug fix for an unreferenced variable

src/middlewared/middlewared/plugins/jail.py
1) Expose compression algorithm selection for import/export of a jail.
2) Expose path selection for where a compressed jail might live when we import a jail.
=> NAS-102494 / 11.3 / Expose compression algorithm selection for import/export of jail

docs/api/resources/sharing.rst, gui/sharing/forms.py, src/middlewared/middlewared/plugins/smb.py
This is now being handled by the New UI.
=> NAS-102522 / 11.3 / Remove 'apply default permissions' from middleware and legacy UI

src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/idmap.py
- Remove unnecessary SMB service restart
- Make AD-related NTP changes a job
=> NAS-102526 / 11.3 / Optimize AD start

src/middlewared/middlewared/plugins/jail.py
Before they would simply return.
NAS-100512
=> NAS-100512 / 11.2 / fix(jail/update): Update plugins properly in 11.2

src/middlewared/middlewared/plugins/acme_protocol.py, src/middlewared/middlewared/plugins/crypto.py
This commit fixes a regression where we were enforcing a max length on csr strings.
=> NAS-102590 / 11.3 / Bug fix for csr

src/middlewared/middlewared/plugins/account.py
=> NAS-102610 / 11.3 / fix(middlewared/account): normalize user email

tests/api2/tunable.py
also change status code to 404
=> QE NAS-102589 change number of the second test 11 to 12

src/middlewared/middlewared/plugins/jail.py
This commit exposes docurl property when listing plugins ( if available ).
=> NAS-102625 / 11.3 / Expose docurl property when querying for plugins

gui/services/migrations/0020_make_lunid_non_null.py
=> NAS-102648 / 11.3 / fix(migration): add used lun ids to the list so we dont reuse it

gui/services/migrations/0020_make_lunid_non_null.py
=> NAS-102648 / 11.2 / fix(migration): add used lun ids to the list so we dont reuse it (by william-gr)

src/middlewared/middlewared/plugins/alert.py
=> NAS-102665 / 11.3 / fix(middlewared/alert): do not let alert jobs queue up

src/middlewared/middlewared/plugins/jail.py
This PR introduces changes to ensure that iocage is not set up on jail/plugin query.
=> NAS-102692 / 11.3 / Ensure iocage is not setup on jail/plugin query

src/middlewared/middlewared/plugins/network.py
=> NAS-102614 / 11.3 / feat(middlewared/network): allow null description for interface

src/middlewared/middlewared/plugins/alert.py
git cherry-pick -x 4246330c140c707a2cbc3be5909b141160ea32c0
Ticket:	NAS-102665
=> NAS-102665 / 11.2 / fix(middlewared/alert): do not let alert jobs queue up (by william-gr)

src/middlewared/middlewared/plugins/pool.py
=> NAS-102631 / 11.3 / fix(middlewared/pool): make sure its not the last pool on system for HA

src/middlewared/middlewared/plugins/init_shutdown_script.py
This commit fixes an import error where range validator import failed.
=> Bug fix for import error

gui/freeadmin/static/lib/js/freeadmin.js, gui/system/forms.py, src/middlewared/middlewared/alert/service/slack.py
git cherry-pick -x e30a51d1845121187b624f9b3190b5d3bc2eb738
=> NAS-102698 / 11.2 / Slack field "detailed" does not exist (by themylogin)

src/freenas/etc/netcli
=> NAS-102617 / 11.3 / fix(netcli): use "networkgeneral" reload service for rc.conf regen

src/middlewared/middlewared/alert/service/aws_sns.py, src/middlewared/middlewared/alert/service/hipchat.py, src/middlewared/middlewared/alert/service/influxdb_.py, src/middlewared/middlewared/alert/service/mail.py, src/middlewared/middlewared/alert/service/mattermost.py, src/middlewared/middlewared/alert/service/opsgenie.py, src/middlewared/middlewared/alert/service/pagerduty.py, src/middlewared/middlewared/alert/service/slack.py, src/middlewared/middlewared/alert/service/victorops.py
git cherry-pick -x 115ccad2d01a9a5d83c8f40f9d38c103b348b799
=> NAS-102579 / 11.2 / Fix mess in alert service schemas (by themylogin)

src/middlewared/middlewared/plugins/update.py
=> NAS-102638 / 11.3 / fix(middlewared/update): check for update on standby for legacy upgrade

src/middlewared/middlewared/etc_files/crontab
Looks like it was accidentally removed while porting
=> Bring freenas-boot scrub back

gui/storage/forms.py
=> NAS-102747 / 11.3 / fix(gui): convert 1M to 1024K used in middlewared

src/middlewared/middlewared/plugins/alert.py
git cherry-pick -x 4d91a6924384ea100fcf59dbb738b9d016db7bc7
=> NAS-102548 / 11.3 / Do not load DB alerts on failover, it is stale cache (by themylogin)

src/middlewared/middlewared/plugins/reporting.py
=> NAS-102728 / 11.3 / fix(middlewared/reporting): do not show graphs if there is no data

src/middlewared/middlewared/alert/source/active_directory.py, src/middlewared/middlewared/alert/source/ldap.py, src/middlewared/middlewared/alert/source/nis.py, src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/cache.py, src/middlewared/middlewared/plugins/ldap.py
Also add ability to get basic domain info from AD.
=> NAS-102776 / 11.3 / Add health checks for LDAP and NIS

gui/freeadmin/sqlite3_ha/base.py
=> NAS-101611 / 11.3 / fix(ha): catch up sqlparse behavior change

gui/freeadmin/sqlite3_ha/base.py
=> NAS-101611 / 11.2 / fix(ha): catch up sqlparse behavior change (by william-gr)

src/middlewared/middlewared/plugins/network.py
=> NAS-102741 / 11.2 / fix(middlewared/network): properly revert back to MTU 1500

src/middlewared/middlewared/etc_files/smartd.py, src/middlewared/middlewared/pytest/unit/etc_files/test_smartd.py
Spent two days chasing this, God forgive me.
=> NAS-102789 / 11.3 / Bring back lost S.M.A.R.T. option

src/middlewared/middlewared/etc_files/smartd.py, src/middlewared/middlewared/pytest/unit/etc_files/test_smartd.py
Spent two days chasing this, God forgive me.
=> NAS-102789 / 11.2 / Bring back lost S.M.A.R.T. option (by themylogin)

gui/tasks/models.py, src/middlewared/middlewared/alert/source/rsync.py, src/middlewared/middlewared/plugins/rsync.py
This PR introduces alerts for rsync tasks if quiet attribute of a rsync task is disabled.
=> NAS-102813 / 11.3 / Rsync task reporting

src/middlewared/middlewared/main.py
Event loop is not running between the calls of `loop.run_until_complete`. Some IO thread (spawned e.g. in plugin setup function) that uses `run_coroutine` can get a false feeling of middleware being terminated because event loop is shut down.
=>  Fix RuntimeError("Middleware is terminating") in the middle of initialization

gui/api/utils.py
This PR makes sure that required services are properly restarted/reloaded after an object is deleted via api v1.
=> NAS-102874 / 11.2 / Properly restart/reload services on object deletion ( api v1 )

src/middlewared/middlewared/plugins/jail.py
This commit moves listing branches from jail service to plugin service as it makes more sense to have it in plugin service wrt usages.
=> NAS-102883 / 11.3 / Change listing branches service
