truenas/middleware

- src/middlewared/middlewared/alembic/versions/25.04/2025-02-19_18-47_remove_blacklisted_aux_params.py
This commit removes some known-bad auxiliary parameters that are now blacklisted in fangtooth. This is especially true for "vfs objects" overrides which are one of the leading causes of issues for people migrating from really old Core installs.
> NAS-132911 / 25.04-RC.1 / Forcefully remove known-bad share-level aux params

- src/middlewared/middlewared/alembic/versions/25.04/2025-02-19_18-47_remove_blacklisted_aux_params.py
This commit removes some known-bad auxiliary parameters that are now blacklisted in fangtooth. This is especially true for "vfs objects" overrides which are one of the leading causes of issues for people migrating from really old Core installs.
Original PR: https://github.com/truenas/middleware/pull/15790
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132911
> NAS-132911 / 25.10 / Forcefully remove known-bad share-level aux params (by anodos325)

- src/middlewared/middlewared/plugins/smb_/util_passdb.py
- tests/api2/test_smb_camelcase.py
This is a subtle regression caused by removing subprocessing to pdbedit. The passdb.tdb file gets written by samba tools to have keys forced to lower case. Our direct tdb library usage was resulting in keys that contained upper-case characters causing samba to fail to look up usernames. This slipped by testing because our UI and general unix admin defaults are always to use lowercase names.
> NAS-134346 / 25.10 / Force passdb.tdb username keys to lower case

- src/middlewared/middlewared/plugins/smb_/util_passdb.py
- tests/api2/test_smb_camelcase.py
This is a subtle regression caused by removing subprocessing to pdbedit. The passdb.tdb file gets written by samba tools to have keys forced to lower case. Our direct tdb library usage was resulting in keys that contained upper-case characters causing samba to fail to look up usernames. This slipped by testing because our UI and general unix admin defaults are always to use lowercase names.
Original PR: https://github.com/truenas/middleware/pull/15795
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134346
> NAS-134346 / 25.04-RC.1 / Force passdb.tdb username keys to lower case (by anodos325)

- src/freenas/usr/local/sbin/hactl
- tests/api2/test_014_failover_related.py
The `takeover` command is rarely used by support team and `giveback` even more so. `failover.call_remote` is a private endpoint that we should not call from external scripts so this removes 1 of those callers.
> NAS-134340 / 25.10 / Remove takeover/giveback sub-commands in hactl

- src/middlewared/middlewared/alert/source/truenas_verify.py
- src/middlewared/middlewared/plugins/audit/audit.py
- src/middlewared/middlewared/plugins/audit/utils.py
Scheduled cryptographic verification of the OS file system
----------------------------------------------------------------
This PR should be merged with the same named PRs in `truenas_verify` and `scale-build`
- Added scheduled cryptographic verification via Alert `check`.  The current schedule is once every 60 minutes.
- Discrepancies found during the scheduled runs are logged to `syslog`
- Install and update:  Generate a version tagged discrepancy log in `/var/log/audit` directory.
NOTE: A verification run can take several seconds on a VM.  This time is added to the initial boot and update boots.  All other boots are not impacted.
---------------------------------------------------------------
**CI tests and update to the diagnostic will be done in separate PRs**
Original PR: …
> NAS-133968 / 25.04-RC.1 / Add scheduled cryptographic verification of OS file system for STIG (by mgrimesix)

- src/middlewared/middlewared/plugins/virt/global.py
Incus is not gracefully able to handle pools which have spaces in their names and while creating various resources it fails as it is not properly able to escape the space.
Until this is fixed upstream, validation has been added to prevent users from selecting such pools which have spaces in their names after discussing with William.
Original PR: https://github.com/truenas/middleware/pull/15800
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134244
> NAS-134244 / 25.04-RC.1 / Improve pool selection validation for virt (by Qubad786)

- tests/api2/test_435_smb_registry.py
Recently this SMB preset was flagged as incompatible with aapl_extensions. This commit adjusts one of the older tests to ensure that we have them disabled before toggling the preset.
> NAS-134291 / 25.10 / Fix registry test for multiprotocol NFS

- tests/api2/test_435_smb_registry.py
Recently this SMB preset was flagged as incompatible with aapl_extensions. This commit adjusts one of the older tests to ensure that we have them disabled before toggling the preset.
Original PR: https://github.com/truenas/middleware/pull/15754
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134291
> NAS-134291 / 25.04-RC.1 / Fix registry test for multiprotocol NFS (by anodos325)

- src/middlewared/middlewared/plugins/failover_/remote.py
This endpoint is consumed by internal callers only. Move it to private namespace and remove from public api.
> NAS-134338 / 25.10 / move failover.call_remote to private api

- src/middlewared/middlewared/api/v25_04_0/virt_volume.py
- src/middlewared/middlewared/api/v25_10_0/virt_volume.py
- tests/api2/test_virt_vm.py
We had limited validation for virt volume names which resulted in incus erroring out when trying to create virt volumes, so validation has been improved on this end to better validate virt volume names.
> NAS-134204 / 25.10 / Properly validate virt volume names

- src/middlewared/middlewared/api/v25_04_0/virt_volume.py
- tests/api2/test_virt_vm.py
git cherry-pick -x b7defa2224b716a6c97a9d8013cf9b26f9ecf1ea
git cherry-pick -x 4676052f5547c4ec2d582f283d9b9c89deb59b83
We had limited validation for virt volume names which resulted in incus erroring out when trying to create virt volumes, so validation has been improved on this end to better validate virt volume names.
Original PR: https://github.com/truenas/middleware/pull/15796
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134204
> NAS-134204 / 25.04-RC.1 / Properly validate virt volume names (by Qubad786)

- src/middlewared/middlewared/plugins/virt/device.py
We only want to show those PCI devices in choices which are not critical and have no error associated with them.
> NAS-134362 / 25.10 / Do not show a PCI device in choices if there is an error

- src/middlewared/middlewared/plugins/virt/device.py
We only want to show those PCI devices in choices which are not critical and have no error associated with them.
Original PR: https://github.com/truenas/middleware/pull/15806
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134362
> NAS-134362 / 25.04-RC.1 / Do not show a PCI device in choices if there is an error (by Qubad786)

- tests/unit/test_role_manager.py
This commit updates the role manager unit test so that the API_KEY plugin is in set of expected nostig roles.
> NAS-134353 / 25.10 / Adjust unit test for API_KEY STIG

- tests/unit/test_role_manager.py
This commit updates the role manager unit test so that the API_KEY plugin is in set of expected nostig roles.
Original PR: https://github.com/truenas/middleware/pull/15802
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134353
> NAS-134353 / 25.04-RC.1 / Adjust unit test for API_KEY STIG (by anodos325)

- src/middlewared/middlewared/plugins/service_/services/iscsitarget.py
Do not start `iscsitarget` on STANDBY node unless ALUA is enabled.
----
Abridged CI [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3206/).
> NAS-133925 / 25.10 / Do not start iscsitarget on STANDBY node unless ALUA is enabled.

- src/middlewared/middlewared/plugins/service_/services/iscsitarget.py
Do not start `iscsitarget` on STANDBY node unless ALUA is enabled.
----
Abridged CI [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3206/).
Original PR: https://github.com/truenas/middleware/pull/15809
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133925
> NAS-133925 / 25.04-RC.1 / Do not start iscsitarget on STANDBY node unless ALUA is enabled. (by bmeagherix)

- src/middlewared/middlewared/plugins/smb.py
- src/middlewared/middlewared/test/integration/assets/smb.py
- tests/api2/test_smb_delete_share_dataset.py
The default for lockable fileystem delegates is to delete the datastore entry directly, which bypasses the share method to delete the datastore. This has the effect of bypassing our code to cleanly close the share resulting in SMB sessions keeping the dataset busy and preventing deletion.
> NAS-134378 / 25.10 / Ensure that SMB attachment delegate properly removes share

- src/middlewared/middlewared/plugins/smb.py
- src/middlewared/middlewared/test/integration/assets/smb.py
- tests/api2/test_smb_delete_share_dataset.py
The default for lockable fileystem delegates is to delete the datastore entry directly, which bypasses the share method to delete the datastore. This has the effect of bypassing our code to cleanly close the share resulting in SMB sessions keeping the dataset busy and preventing deletion.
Original PR: https://github.com/truenas/middleware/pull/15815
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134378
> NAS-134378 / 25.04.0 / Ensure that SMB attachment delegate properly removes share (by anodos325)

- src/middlewared/middlewared/plugins/smb.py
- src/middlewared/middlewared/test/integration/assets/smb.py
- tests/api2/test_smb_delete_share_dataset.py
The default for lockable fileystem delegates is to delete the datastore entry directly, which bypasses the share method to delete the datastore. This has the effect of bypassing our code to cleanly close the share resulting in SMB sessions keeping the dataset busy and preventing deletion.
Original PR: https://github.com/truenas/middleware/pull/15815
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134378
> NAS-134378 / 25.04-RC.1 / Ensure that SMB attachment delegate properly removes share (by anodos325)

- src/middlewared/middlewared/api/v25_04_0/virt_device.py
- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
- src/middlewared/middlewared/api/v25_10_0/virt_device.py
- src/middlewared/middlewared/api/v25_10_0/virt_instance.py
- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/plugins/virt/instance_device.py
- src/middlewared/middlewared/plugins/virt/utils.py
- tests/api2/test_virt_002_instance.py
- tests/api2/test_virt_vm.py
We would like to expose specifying IO bus for disk devices so users can have it configurable. This is helpful especially in cases like where in the OS virtio drivers etc are not already present and if disk is attached in virito mode - drivers need to be attached/setup as ewll which makes it a more complex problem to tackle.
So in this case, users can set it to something like NVME whose drivers are already available in the base OS making it a much simpler way to setup the VM.
> NAS-134250 / 25.10 / Expose specifying IO bus for disk devices

- src/middlewared/middlewared/api/v25_04_0/virt_device.py
- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/plugins/virt/instance_device.py
- src/middlewared/middlewared/plugins/virt/utils.py
- tests/api2/test_virt_002_instance.py
- tests/api2/test_virt_vm.py
git cherry-pick -x 56b4f4d4377a6b9913c51081a972ba157087abed
git cherry-pick -x 909317e372a0e3187ee9d92c129c5103ecbe4fb0
We would like to expose specifying IO bus for disk devices so users can have it configurable. This is helpful especially in cases like where in the OS virtio drivers etc are not already present and if disk is attached in virito mode - drivers need to be attached/setup as ewll which makes it a more complex problem to tackle.
So in this case, users can set it to something like NVME whose drivers are already available in the base OS making it a much simpler way to setup the VM.
Original PR: …
> NAS-134250 / 25.04-RC.1 / Expose specifying IO bus for disk devices (by Qubad786)

- src/middlewared/middlewared/api/v25_04_0/virt_device.py
- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/plugins/virt/instance_device.py
- src/middlewared/middlewared/plugins/virt/utils.py
- tests/api2/test_virt_002_instance.py
- tests/api2/test_virt_vm.py
git cherry-pick -x 56b4f4d4377a6b9913c51081a972ba157087abed
git cherry-pick -x 909317e372a0e3187ee9d92c129c5103ecbe4fb0
We would like to expose specifying IO bus for disk devices so users can have it configurable. This is helpful especially in cases like where in the OS virtio drivers etc are not already present and if disk is attached in virito mode - drivers need to be attached/setup as ewll which makes it a more complex problem to tackle.
So in this case, users can set it to something like NVME whose drivers are already available in the base OS making it a much simpler way to setup the VM.
Original PR: …
> NAS-134250 / 25.04.0 / Expose specifying IO bus for disk devices (by Qubad786)

- tests/api2/assets/websocket/iscsi.py
- tests/api2/test_261_iscsi_cmd.py
Add `test__initiators` to ensure that only permitted initiators are able to access a target.
Wiring this necessitated fixing `initiator_portal` test utility so that the initiators _actually_ get wired up.  This had subsequent breakage as initiators then were automatically torn down in certain circumstances.  Refactor tests slightly to counter this.
----
Abridged CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3222/).
> NAS-134391 / 25.10 / Add iSCSI CI test__initiators

- debian/debian/postinst
- tests/unit/test_after_boot_services.py
The Debian default is to always run the rpcbind daemon, it starts at boot regardless if it's required. 
On TrueNAS, this rpcbind is used only by NFS. 
This PR defaults rpcbind to disabled.   On NFS start, rpcbind will become  `active` and report `running`.   On NFS stop rpcbind will 
become `inactive` and report `dead`.
A CI test was added to confirm the rpcbind state at boot.
> NAS-134351 / 25.10 / Prevent rpcbind from starting at boot by default

- debian/debian/postinst
- tests/unit/test_after_boot_services.py
The Debian default is to always run the rpcbind daemon, it starts at boot regardless if it's required. 
On TrueNAS, this rpcbind is used only by NFS. 
This PR defaults rpcbind to disabled.   On NFS start, rpcbind will become  `active` and report `running`.   On NFS stop rpcbind will 
become `inactive` and report `dead`.
A CI test was added to confirm the rpcbind state at boot.
Original PR: https://github.com/truenas/middleware/pull/15830
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134351
> NAS-134351 / 25.04.0 / Prevent rpcbind from starting at boot by default (by mgrimesix)

- src/middlewared/middlewared/plugins/virt/device.py
- src/middlewared/middlewared/plugins/virt/instance_device.py
- src/middlewared/middlewared/plugins/virt/utils.py
It was requested by UI team that we provide PCI devices description as well so users can know more about the PCI device which they have selected.
> NAS-134360 / 25.10 / Add a description for PCI devices

- src/middlewared/middlewared/plugins/audit/audit.py
- src/middlewared/middlewared/plugins/audit/utils.py
- tests/api2/test_truenas_verify.py
- tests/unit/test_truenas_verify.py
We are not properly processing the results of `truenas_verify`.  This started with [#15678](https://github.com/truenas/middleware/pull/15678).
This PR fixes the processing issues.
Moved CI tests from `api2` to `unit`.   Added tests for each use case.
CI testing of the STIG mode and alert generation is not yet included.
Passing  CI unit tests: http://jenkins.eng.ixsystems.net:8080/job/tests/job/unit_tests/876/
> NAS-134432 / 25.10 / Fix call processing of truenas_verify.

- src/middlewared/middlewared/utils/iommu.py
Host bridge device needs to be marked as critical because it can potentially result in the system being inaccessible as it is required by the host to function properly.
> NAS-134361 / 25.10 / Mark PCI host bridge device as critical

- src/middlewared/middlewared/utils/iommu.py
Host bridge device needs to be marked as critical because it can potentially result in the system being inaccessible as it is required by the host to function properly.
Original PR: https://github.com/truenas/middleware/pull/15841
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134361
> NAS-134361 / 25.04-RC.1 / Mark PCI host bridge device as critical (by Qubad786)

- src/middlewared/middlewared/utils/iommu.py
Host bridge device needs to be marked as critical because it can potentially result in the system being inaccessible as it is required by the host to function properly.
Original PR: https://github.com/truenas/middleware/pull/15841
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134361
> NAS-134361 / 25.04.0 / Mark PCI host bridge device as critical (by Qubad786)

- src/middlewared/middlewared/plugins/virt/instance.py
A deque is more efficient and performant and fits the use-case perfectly here. Use it instead.
> NAS-134446 / 25.10 / use a deque in error path in virt.instance.start

- src/middlewared/middlewared/plugins/virt/instance.py
A deque is more efficient and performant and fits the use-case perfectly here. Use it instead.
Original PR: https://github.com/truenas/middleware/pull/15844
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134446
> NAS-134446 / 25.04.0 / use a deque in error path in virt.instance.start (by yocalebo)

- src/middlewared/middlewared/plugins/virt/instance.py
- tests/api2/test_virt_002_instance.py
This commit reads our local account related idmap namespace configuration and applies it to incus instances. Since raw.idmap changes require a container restart in order to be effective we apply fresh idmap configuration prior to instance start / restart.
> NAS-134440 / 25.10 / Apply idmap configuration to incus instances

- src/middlewared/middlewared/plugins/virt/instance.py
- tests/api2/test_virt_002_instance.py
This commit reads our local account related idmap namespace configuration and applies it to incus instances. Since raw.idmap changes require a container restart in order to be effective we apply fresh idmap configuration prior to instance start / restart.
Original PR: https://github.com/truenas/middleware/pull/15839
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134440
> NAS-134440 / 25.04-RC.1 / Apply idmap configuration to incus instances (by anodos325)

- src/middlewared/middlewared/plugins/virt/instance.py
- tests/api2/test_virt_002_instance.py
This commit reads our local account related idmap namespace configuration and applies it to incus instances. Since raw.idmap changes require a container restart in order to be effective we apply fresh idmap configuration prior to instance start / restart.
Original PR: https://github.com/truenas/middleware/pull/15839
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134440
> NAS-134440 / 25.04.0 / Apply idmap configuration to incus instances (by anodos325)

- src/middlewared/middlewared/utils/disks_/get_disks.py
- src/middlewared/middlewared/utils/disks_/gpt_parts.py
- src/middlewared/middlewared/utils/disks_/private_utils.py
- tests/unit/test_gpt_parts.py
This adds the ability to read GPT partition information directly from drives using pure python. We have an ever-increasing amount of pressure to optimize our code. Disk related information is a "hot" area that we're trying to improve. We were spoiled on freeBSD with GEOM subsystem.
Anyways, on a system with 1294 GPT formatted disks, this returns in ~1.3 seconds. On the same system, the average time to call `device.get_disks true` (which includes gpt partitions) takes ~9.79 seconds. This means the newly added logic is running ~152.7% faster.
Currently, nothing uses this so there is 0 risk of adding it. In the future, this will eventually be used.
SIDE NOTE: The `device.get_disks` method is returning more information than what `get_disks(get_partitions=True)` does, however, the argument is …
> NAS-134473 / 25.10 / Add efficient method for reading GPT partitions on drives

- src/middlewared/middlewared/utils/disks_/get_disks.py
- src/middlewared/middlewared/utils/disks_/gpt_parts.py
- tests/unit/test_get_disks.py
This adds the ability to filter disks that are returned from `get_disks()`. Since this is done before we enumerate information, this can dramatically decrease the time it takes to return (instead it yields all disks by default).
> NAS-134478 / 25.10 / Add name filters to get_disks()

- src/middlewared/middlewared/test/integration/assets/virt.py
- tests/api2/test_virt_instance_acl.py
This commit adds a minimal functional test that our uid and gid idmaps work correctly with NFSv4 acltype datasets within a container.
> NAS-134476 / 25.10 / Add functional test for NFSv4 ACL in containers

- src/middlewared/middlewared/test/integration/assets/virt.py
- tests/api2/test_virt_instance_acl.py
This commit adds a minimal functional test that our uid and gid idmaps work correctly with NFSv4 acltype datasets within a container.
Original PR: https://github.com/truenas/middleware/pull/15851
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134476
> NAS-134476 / 25.04.0 / Add functional test for NFSv4 ACL in containers (by anodos325)

- src/middlewared/middlewared/plugins/service_/services/iscsitarget.py
On service restart avoid injecting iSER module while deactivating.
> NAS-134449 / 25.10 / On service restart avoid injecting iSER module while deactivating

- src/middlewared/middlewared/plugins/service_/services/iscsitarget.py
On service restart avoid injecting iSER module while deactivating.
Original PR: https://github.com/truenas/middleware/pull/15854
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134449
> NAS-134449 / 25.04.0 / On service restart avoid injecting iSER module while deactivating (by bmeagherix)

- src/middlewared/middlewared/test/integration/assets/virt.py
- tests/api2/test_virt_002_instance.py
- tests/api2/test_virt_instance_acl.py
This commit shifts the incus instance tests toward using our common virt test assets and begins to use pytest fixtures for handling common test state.
> NAS-134484 / 25.10 / Use common test assets for incus instance

- src/middlewared/middlewared/test/integration/assets/virt.py
- tests/api2/test_virt_002_instance.py
- tests/api2/test_virt_instance_acl.py
This commit shifts the incus instance tests toward using our common virt test assets and begins to use pytest fixtures for handling common test state.
Original PR: https://github.com/truenas/middleware/pull/15858
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134484
> NAS-134484 / 25.04.0 / Use common test assets for incus instance (by anodos325)

- src/middlewared/middlewared/utils/disks_/get_disks.py
Last minute suggestion introduced a regression which breaks the ability to call `list(get_disks())`.
> NAS-134495 / 25.10 / fix get_disks()

- src/middlewared/middlewared/plugins/virt/instance_device.py
- src/middlewared/middlewared/test/integration/assets/virt.py
- tests/api2/test_virt_002_instance.py
This commit restricts what we consider to be valid paths for incus containers to dataset mountpoints within known storage pools.
> NAS-134483 / 25.10 / Expand validation for incus paths in middleware

- src/middlewared/middlewared/plugins/pool_/pool.py
For reasons not fully understood, `ix-syncdisks.service` is failing at boot only. After system is booted, it can be called without issue. This prevents our `storage_disk` table from being populated with disk information. This causes a cascading set of failures because creating a zpool fails. This fixes all of the problems by using the new `get_disks` function in the `_process_topology`. (`get_disks` is written in a way that will render storing disk information in our database obsolete.)
Passing test run: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3342
> NAS-134512 / 25.10 / use get_disks() in _process_topology()

- src/middlewared/middlewared/plugins/disk_/availability.py
- src/middlewared/middlewared/utils/disks_/disk_class.py
Same issue as described in https://github.com/truenas/middleware/pull/15869. The biggest issue is that this is only failing on fresh install on first boot. Anytime I try to get on a system, the issue doesn't reproduce.
> NAS-134517 / 25.10 / fix disk.check_disk_availability

- src/middlewared/middlewared/plugins/pool_/dataset.py
- tests/api2/test_pool_dataset_acl.py
This commit fixes an oversight for extra validation of acltype changes. The validation was added because our userbase was changing the acltype ZFS property on active SMB shares causing samba to assert due to the ACL xattrs being ripped out from under it.
Unfortunately, the original commit did not properly account for the possibility that dataset properties can be set to INHERIT.
> NAS-134516 / 25.10 / Fix check for whether acltype has changed

- src/middlewared/middlewared/plugins/pool_/dataset.py
- tests/api2/test_pool_dataset_acl.py
This commit fixes an oversight for extra validation of acltype changes. The validation was added because our userbase was changing the acltype ZFS property on active SMB shares causing samba to assert due to the ACL xattrs being ripped out from under it.
Unfortunately, the original commit did not properly account for the possibility that dataset properties can be set to INHERIT.
Original PR: https://github.com/truenas/middleware/pull/15870
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134516
> NAS-134516 / 25.04.0 / Fix check for whether acltype has changed (by anodos325)

- src/middlewared/middlewared/plugins/apps_images/images.py
- src/middlewared/middlewared/plugins/docker/network.py
- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/service/crud_service.py
- src/middlewared/middlewared/service/decorators.py
Using `@filterable` in new-style API classes prevents `query` method from appearing in the docs. Let's prohibit this and offer an alternative.
> NAS-134382 / 25.10 / Forbid `@filterable` methods for new-style API classes

- src/middlewared/middlewared/plugins/apps_images/images.py
- src/middlewared/middlewared/plugins/docker/network.py
- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/service/crud_service.py
- src/middlewared/middlewared/service/decorators.py
Using `@filterable` in new-style API classes prevents `query` method from appearing in the docs. Let's prohibit this and offer an alternative.
Original PR: https://github.com/truenas/middleware/pull/15874
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134382
> NAS-134382 / 25.04.0 / Forbid `@filterable` methods for new-style API classes (by themylogin)

- src/middlewared/middlewared/plugins/pwenc.py
https://github.com/truenas/middleware/pull/15850 caused a regression where-by `disk.query` is returning an empty array. This is because `ix-syncdisks.service` was failing. That service was failing because `middlewared.service` was failing. This service is failing because of this
```
Mar  3 05:30:41 truenas middlewared[1046]:   File "/usr/lib/python3/dist-packages/middlewared/plugins/pwenc.py", line 49, in _reset_passwords
Mar  3 05:30:41 truenas middlewared[1046]:     self.middleware.call_sync('datastore.sql', 'DELETE FROM vm_device')
Mar  3 05:30:41 truenas middlewared[1046]:   File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1002, in call_sync
Mar  3 05:30:41 truenas middlewared[1046]:     return self.run_coroutine(methodobj(*prepared_call.args))
Mar  3 05:30:41 truenas …
```
> NAS-134531 / 25.10 / fix middlewared.service start-up

- src/middlewared/middlewared/plugins/virt/global.py
During incus storage setup the TrueNAS middleware calls into a private incus recovery API in order to rebuild the incus configuration from data in the specified path. It is not very obvious that we're doing this and why we're doing this and so this commit adds a brief developer-facing comment based on discussion with the solutions team.
> NAS-134532 / 25.10 / Add comment explaining incus private API usage

- src/middlewared/middlewared/plugins/virt/global.py
During incus storage setup the TrueNAS middleware calls into a private incus recovery API in order to rebuild the incus configuration from data in the specified path. It is not very obvious that we're doing this and why we're doing this and so this commit adds a brief developer-facing comment based on discussion with the solutions team.
Original PR: https://github.com/truenas/middleware/pull/15879
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134532
> NAS-134532 / 25.04.0 / Add comment explaining incus private API usage (by anodos325)

- src/middlewared/middlewared/etc_files/nfs.conf.mako
- tests/api2/test_300_nfs.py
/usr/etc is by default Read-Only on TrueNAS.  Recent change in nfs mako attempted delete /usr/etc/nfs.conf which resulted in an exception. 
This PR fixes that issue and enhances the CI for improved reporting of conf file parsing.
Add try block around file delete in mako.
Update the CI test to better report where the parsing error occurred.
Passing CI tests: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3371/
> NAS-134550 / 25.10 / Fix nfs conf mako

- src/middlewared/middlewared/etc_files/nfs.conf.mako
- tests/api2/test_300_nfs.py
/usr/etc is by default Read-Only on TrueNAS.  Recent change in nfs mako attempted delete /usr/etc/nfs.conf which resulted in an exception. 
This PR fixes that issue and enhances the CI for improved reporting of conf file parsing.
Add try block around file delete in mako.
Update the CI test to better report where the parsing error occurred.
Passing CI tests: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3371/
Original PR: https://github.com/truenas/middleware/pull/15883
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134550
> NAS-134550 / 25.04.0 / Fix nfs conf mako (by mgrimesix)

- src/middlewared/middlewared/test/integration/utils/client.py
This commit adds a simple wrapper to bypass our safety checks for using py_exceptions when we're
using our CI test assets.
> Bypass py_exceptions check in API client for CI

- src/middlewared/middlewared/test/integration/utils/client.py
This commit adds a simple wrapper to bypass our safety checks for using py_exceptions when we're
using our CI test assets.
Original PR: https://github.com/truenas/middleware/pull/15885
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134561
> NAS-134561 / 25.04.0 / Bypass py_exceptions check in API client for CI (by anodos325)

- src/middlewared/middlewared/alembic/versions/25.04/2025-03-03_21-02_apps-userns-idmap.py
This change sets a DIRECT userns_idmap for the apps user and group so that this UID / GID always resolve in incus containers. The reason for this is that our userbase is already somewhat familiar with the idea that there are these "apps" accounts that are available for setting permissions to make things outside the host work. Having a single group that can be added to grant access to both apps and containers is simpler and avoids the need for a UI implementation of the userns_idmap field for the 25.04 release candidate.
> NAS-134560 / 25.04.0 / Add migration to add userns_idmap for apps user and group

- src/middlewared/middlewared/alembic/versions/25.04/2025-03-03_21-02_apps-userns-idmap.py
This change sets a DIRECT userns_idmap for the apps user and group so that this UID / GID always resolve in incus containers. The reason for this is that our userbase is already somewhat familiar with the idea that there are these "apps" accounts that are available for setting permissions to make things outside the host work. Having a single group that can be added to grant access to both apps and containers is simpler and avoids the need for a UI implementation of the userns_idmap field for the 25.04 release candidate.
Original PR: https://github.com/truenas/middleware/pull/15886
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134560
> NAS-134560 / 25.04-RC.1 / Add migration to add userns_idmap for apps user and group (by anodos325)

- src/middlewared/middlewared/alembic/versions/25.04/2025-03-03_21-02_apps-userns-idmap.py
- src/middlewared/middlewared/alembic/versions/25.10/2025-03-04_13-19_merge-migration.py
This change sets a DIRECT userns_idmap for the apps user and group so that this UID / GID always resolve in incus containers. The reason for this is that our userbase is already somewhat familiar with the idea that there are these "apps" accounts that are available for setting permissions to make things outside the host work. Having a single group that can be added to grant access to both apps and containers is simpler and avoids the need for a UI implementation of the userns_idmap field for the 25.04 release candidate.
Original PR: https://github.com/truenas/middleware/pull/15886
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134560
> NAS-134560 / 25.10 / Add migration to add userns_idmap for apps user and group (by anodos325)

- src/middlewared/middlewared/plugins/account_/sync_builtin.py
On totally fresh installs the apps user / group is not present until we run a migration to sync up builtin accounts. This commit ensures that the userns_idmap value is set correctly on fresh install.
> NAS-134588 / 25.10 / Ensure apps userns_idmap set correctly on fresh install

- src/middlewared/middlewared/plugins/failover.py
Our `failover.update` always sets the master node to the return of `failover.node` regardless of whatever is passed to `failover.update.master`.
Tests: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3373/
> NAS-134330 / 25.10 / Respect `master` parameter in `failover.update`

- src/middlewared/middlewared/plugins/account_/sync_builtin.py
On totally fresh installs the apps user / group is not present until we run a migration to sync up builtin accounts. This commit ensures that the userns_idmap value is set correctly on fresh install.
Original PR: https://github.com/truenas/middleware/pull/15897
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134588
> NAS-134588 / 25.04.0 / Ensure apps userns_idmap set correctly on fresh install (by anodos325)

- src/middlewared/middlewared/plugins/account_/sync_builtin.py
On totally fresh installs the apps user / group is not present until we run a migration to sync up builtin accounts. This commit ensures that the userns_idmap value is set correctly on fresh install.
Original PR: https://github.com/truenas/middleware/pull/15897
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134588
> NAS-134588 / 25.04-RC.1 / Ensure apps userns_idmap set correctly on fresh install (by anodos325)

- src/middlewared/middlewared/plugins/auth_/2fa.py
- src/middlewared/middlewared/plugins/security/update.py
We should never have combination of mandatory OTP and 2FA being enabled. This happened due to a chain of events stemming from enabling STIG mode after a failed HA upgrade.
> NAS-134586 / 25.10 / Forcibly lower authenticator assurance level if 2FA disabled

- src/middlewared/middlewared/plugins/virt/instance_device.py
- tests/api2/test_virt_002_instance.py
- tests/api2/test_virt_vm.py
It was requested that we don't allow zvols to be used for virt containers because of the complexity required for setting it up actually for consumption with the container. So for the time being it is being disabled.
> NAS-134554 / 25.10 / Do not allow zvols for virt containers

- src/middlewared/middlewared/plugins/virt/instance_device.py
- tests/api2/test_virt_002_instance.py
- tests/api2/test_virt_vm.py
It was requested that we don't allow zvols to be used for virt containers because of the complexity required for setting it up actually for consumption with the container. So for the time being it is being disabled.
Original PR: https://github.com/truenas/middleware/pull/15904
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134554
> NAS-134554 / 25.04.0 / Do not allow zvols for virt containers (by Qubad786)

- src/middlewared/middlewared/plugins/virt/instance_device.py
- tests/api2/test_virt_002_instance.py
- tests/api2/test_virt_vm.py
It was requested that we don't allow zvols to be used for virt containers because of the complexity required for setting it up actually for consumption with the container. So for the time being it is being disabled.
Original PR: https://github.com/truenas/middleware/pull/15904
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134554
> NAS-134554 / 25.04-RC.1 / Do not allow zvols for virt containers (by Qubad786)

- src/middlewared/middlewared/plugins/account.py
- src/middlewared/middlewared/plugins/account_/constants.py
- tests/unit/test_builtin_gid.py
Historically TrueNAS has done little to limit the changes admins can make to builtin groups (root, sssd, ntp, sudo, etc). This usually isn't problematic because admins know enough to not alter builtin groups. This is because changes to them can cause undefined system behavior, including introducing security vulnerabilities. This commit introduces additional validation to prevent problematic changes to these special system groups.
> NAS-134606 / 25.10 / restrict changes to builtin groups

- src/middlewared/middlewared/plugins/account.py
- src/middlewared/middlewared/plugins/account_/constants.py
- tests/unit/test_builtin_gid.py
Historically TrueNAS has done little to limit the changes admins can make to builtin groups (root, sssd, ntp, sudo, etc). This usually isn't problematic because admins know enough to not alter builtin groups. This is because changes to them can cause undefined system behavior, including introducing security vulnerabilities. This commit introduces additional validation to prevent problematic changes to these special system groups.
Original PR: https://github.com/truenas/middleware/pull/15908
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134606
> NAS-134606 / 25.04.0 / restrict changes to builtin groups (by anodos325)

- src/middlewared/middlewared/plugins/virt/instance_device.py
When a VM is not in stopped state and we try to update `io_bus` attr for disks, that will result in VM hanging.
Make sure we do not allow changing `io_bus` for virt disks if VM is in running state.
> NAS-134488 / 25.10 / Improve validation while changing io_bus for virt disks

- src/middlewared/middlewared/plugins/virt/instance_device.py
When a VM is not in stopped state and we try to update `io_bus` attr for disks, that will result in VM hanging.
Make sure we do not allow changing `io_bus` for virt disks if VM is in running state.
Original PR: https://github.com/truenas/middleware/pull/15891
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134488
> NAS-134488 / 25.04.0 / Improve validation while changing io_bus for virt disks (by Qubad786)

- src/middlewared/middlewared/plugins/account.py
A change in PR #15908 used the wrong key for `existing_groups`.
> NAS-134630 / 25.10 / Fix recently added check, use dbid as key not 'dbid' string

- src/middlewared/middlewared/plugins/account.py
A change in PR #15908 used the wrong key for `existing_groups`.
Original PR: https://github.com/truenas/middleware/pull/15919
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134630
> NAS-134630 / 25.04.0 / Fix recently added check, use dbid as key not 'dbid' string (by bmeagherix)

- src/middlewared/middlewared/plugins/account.py
Additional fix to PR #15908
This was already added to the backport of PR #15919, so does NOT need to be backported.
> NAS-134632 / 25.10 / Further fixes wrt restrict changes to builtin groups

- src/middlewared/middlewared/plugins/zfs_/utils.py
- tests/api2/test_virt_vm.py
This commit prevents zvols within ix-virt from being exposed as choices within the virt and iscsi plugins. Prior to this change users could create a zvol via virt.volume.create and its /dev/zvol path was presented as a disk choice for other VMs, which allowed for having the same zvol mounted rw in two VMs simultaneously.
> NAS-134634 / 25.10 / Do not present incus-managed zvols to middleware

- src/middlewared/middlewared/plugins/zfs_/utils.py
- tests/api2/test_virt_vm.py
This commit prevents zvols within ix-virt from being exposed as choices within the virt and iscsi plugins. Prior to this change users could create a zvol via virt.volume.create and its /dev/zvol path was presented as a disk choice for other VMs, which allowed for having the same zvol mounted rw in two VMs simultaneously.
Original PR: https://github.com/truenas/middleware/pull/15923
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134634
> NAS-134634 / 25.04.0 / Do not present incus-managed zvols to middleware (by anodos325)

- src/middlewared/middlewared/plugins/virt/instance.py
If idmap configuration has changed while a virt instance was running and an attempt to restart it is done, what happens is that the new configuration fails to apply as it will only apply if the instance is not running.
Make sure instance is stopped and then apply relevant idmap changes.
> NAS-134640 / 25.10 / Do not attempt to update idmap on running virt instance

- src/middlewared/middlewared/plugins/virt/instance.py
If idmap configuration has changed while a virt instance was running and an attempt to restart it is done, what happens is that the new configuration fails to apply as it will only apply if the instance is not running.
Make sure instance is stopped and then apply relevant idmap changes.
Original PR: https://github.com/truenas/middleware/pull/15926
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134640
> NAS-134640 / 25.04-RC.1 / Do not attempt to update idmap on running virt instance (by Qubad786)

- src/middlewared/middlewared/plugins/virt/instance.py
If idmap configuration has changed while a virt instance was running and an attempt to restart it is done, what happens is that the new configuration fails to apply as it will only apply if the instance is not running.
Make sure instance is stopped and then apply relevant idmap changes.
Original PR: https://github.com/truenas/middleware/pull/15926
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134640
> NAS-134640 / 25.04.0 / Do not attempt to update idmap on running virt instance (by Qubad786)

- src/middlewared/middlewared/alembic/versions/25.10/2025-03-06_01-25_remove_syslog_tls_certificate_authority.py
- src/middlewared/middlewared/etc_files/syslog-ng/syslog-ng.conf.mako
- src/middlewared/middlewared/plugins/system_advanced/config.py
- src/middlewared/middlewared/plugins/system_advanced/syslog.py
- tests/api2/test_475_syslog.py
Removed `syslog_tls_certificate authority_id`  from system.advanced database (includes migration).
When TLS is selected we now always include the file containing ca certs.  
Includes a simple CI test.
> NAS-134597 / 25.10 / Removed certificate_authority management requirement from syslog config.

- src/middlewared/middlewared/plugins/virt/device.py
- src/middlewared/middlewared/plugins/virt/instance_device.py
- tests/api2/test_virt_vm.py
This is related to NAS-134583. The UI team needs an API to provide consistent choices for VM disks. This slight refactor does two things:
1. includes virt.volumes in API response
2. excludes in-use choices from API response
The second point is relevant to API consumers because it makes this API consistent with how choices are handled in other plugins, e.g. iscsi.extents.disk_choices.
> NAS-134641 / 25.10 / Provide improved disk_choices results for API consumers

- src/middlewared/middlewared/plugins/virt/device.py
- src/middlewared/middlewared/plugins/virt/instance_device.py
- tests/api2/test_virt_vm.py
This is related to NAS-134583. The UI team needs an API to provide consistent choices for VM disks. This slight refactor does two things:
1. includes virt.volumes in API response
2. excludes in-use choices from API response
The second point is relevant to API consumers because it makes this API consistent with how choices are handled in other plugins, e.g. iscsi.extents.disk_choices.
Original PR: https://github.com/truenas/middleware/pull/15929
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134641
> NAS-134641 / 25.04.0 / Provide improved disk_choices results for API consumers (by anodos325)

- src/middlewared/middlewared/plugins/virt/global.py
- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/plugins/virt/utils.py
- tests/api2/test_virt_vm.py
For VM based virt instances, if any had vnc password configured - that was visible in ps command output as it was being passed as command line argument to qemu.
Make sure VNC password is not exposed in ps output.
> NAS-134584 / 25.10 / Make sure VNC password is not visible in ps

- src/middlewared/middlewared/plugins/virt/global.py
- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/plugins/virt/utils.py
- tests/api2/test_virt_vm.py
For VM based virt instances, if any had vnc password configured - that was visible in ps command output as it was being passed as command line argument to qemu.
Make sure VNC password is not exposed in ps output.
Original PR: https://github.com/truenas/middleware/pull/15930
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134584
> NAS-134584 / 25.04-RC.1 / Make sure VNC password is not visible in ps (by Qubad786)

- src/middlewared/middlewared/plugins/virt/global.py
- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/plugins/virt/utils.py
- tests/api2/test_virt_vm.py
For VM based virt instances, if any had vnc password configured - that was visible in ps command output as it was being passed as command line argument to qemu.
Make sure VNC password is not exposed in ps output.
Original PR: https://github.com/truenas/middleware/pull/15930
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134584
> NAS-134584 / 25.04.0 / Make sure VNC password is not visible in ps (by Qubad786)

- src/middlewared/middlewared/plugins/account_/constants.py
We need to manage membership of the FTP group to control FTP access with default configuration.
This fixes a regression caused by a previous commit to introduce restrictions on changes that
admins can make to builtin groups.
**Changes:**
Add the FTP group to the whitelist of builtin groups that are allowed membership changes.
**Testing:**
No additional testing required. This was caught by automated testing.
|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   | None - backend change only
|WebUI           | None - backend change only
> NAS-134646 / 25.10 / Add the FTP group to builtin group whitelist

- src/middlewared/middlewared/plugins/account_/constants.py
We need to manage membership of the FTP group to control FTP access with default configuration.
This fixes a regression caused by a previous commit to introduce restrictions on changes that
admins can make to builtin groups.
**Changes:**
Add the FTP group to the whitelist of builtin groups that are allowed membership changes.
**Testing:**
No additional testing required. This was caught by automated testing.
|Affects         |Reasoning
|----------------|-------------------------------
|Documentation   | None - backend change only
|WebUI           | None - backend change only
Original PR: https://github.com/truenas/middleware/pull/15936
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134646
> NAS-134646 / 25.04.0 / Add the FTP group to builtin group whitelist (by anodos325)

- tests/api2/test_011_user.py
The automation test for managing local accounts was using gid 0 for validating whether updating group membership works. This commit adjusts the test to using our truenas administrators group.
> NAS-134652 / 25.10 / Adjust CI test to not use the root group

- src/middlewared/middlewared/plugins/virt/global.py
- src/middlewared/middlewared/plugins/virt/instance.py
`virt.instance` namespace was missing job locks which could result in race condition. So, job locks have been added to `create`, `update`, `delete`, `start`, `stop`, and `restart` endpoints.
> NAS-134444 / 25.10 / Add job locks on virt instance operations

- src/middlewared/middlewared/plugins/virt/global.py
- src/middlewared/middlewared/plugins/virt/instance.py
`virt.instance` namespace was missing job locks which could result in race condition. So, job locks have been added to `create`, `update`, `delete`, `start`, `stop`, and `restart` endpoints.
Original PR: https://github.com/truenas/middleware/pull/15849
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134444
> NAS-134444 / 25.04.0 / Add job locks on virt instance operations (by Qubad786)

- tests/api2/test_011_user.py
The automation test for managing local accounts was using gid 0 for validating whether updating group membership works. This commit adjusts the test to using our truenas administrators group.
Original PR: https://github.com/truenas/middleware/pull/15940
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134652
> NAS-134652 / 25.04.0 / Adjust CI test to not use the root group (by anodos325)

- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
- src/middlewared/middlewared/pytest/unit/plugins/virt/test_virt_instance_env.py
git cherry-pick -x 73b39900026858bc4d13b067264149f9a887a39b
git cherry-pick -x a518e799eb25d8f2884894633d3bffdd0a97a232
Earlier we were allowing anything to be specified for key/value in a virt instance's environment. This has been restricted by adding some basic validation to what kind of values are allowed (inspired from https://linuxcontainers.org/incus/docs/main/environment/).
Original PR: https://github.com/truenas/middleware/pull/15931
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134489
> NAS-134489 / 25.04.0 / Validate key/values for virt instance's environment variables (by Qubad786)

- src/middlewared/middlewared/plugins/account_/privilege.py
In PR #15832 an additional (`userns_idmap`) check was added to `_validate`.  However, when the local group is not present this causes a `KeyError` exception.  If we have already detected that the group is not present, then skip the second check.
----
CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3494/).
> NAS-134693 / 25.10 / If local group does not exist then skip the userns_idmap check

- src/middlewared/middlewared/plugins/account_/privilege.py
In PR #15832 an additional (`userns_idmap`) check was added to `_validate`.  However, when the local group is not present this causes a `KeyError` exception.  If we have already detected that the group is not present, then skip the second check.
----
CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3494/).
Original PR: https://github.com/truenas/middleware/pull/15951
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134693
> NAS-134693 / 25.04.0 / If local group does not exist then skip the userns_idmap check (by bmeagherix)

- src/middlewared/middlewared/utils/auditd.py
- tests/unit/test_auditd_rules.py
Add common audit rules to trap reboot and shutdown events instigated via command line.
Added simple CI test to confirm rule exists for STIG and non-STIG.
This relies on companion changes in the `audit_rules` repo.
> NAS-134627 / 25.10 / Add reboot and shutdown audit rules

- src/middlewared/middlewared/utils/auditd.py
- tests/unit/test_auditd_rules.py
Add common audit rules to trap reboot and shutdown events instigated via command line.
Added simple CI test to confirm rule exists for STIG and non-STIG.
This relies on companion changes in the `audit_rules` repo.
Original PR: https://github.com/truenas/middleware/pull/15954
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134627
> NAS-134627 / 25.04.0 / Add reboot and shutdown audit rules (by mgrimesix)

- src/middlewared/middlewared/alert/source/auth.py
The webui does not parse Markdown in alert texts, but it does format HTML.
> NAS-131175 / 25.10 / Replace Markdown with HTML in `AdminSessionAlertClass.text`

- src/middlewared/middlewared/plugins/security/update.py
This PR adds changes to not have docker/incus be configured at the time incus is configured. Motivation behind this is that if we don't want to allow users to have apps/vms when STIG is enabled, there is no reason to have docker/incus daemons run when this is being configured. Secondly we already don't allow to change TNC settings when STIG is enabled, however we were not validating if TNC was already configured at the time STIG was being enabled, so a validation for that has been added as well.
> NAS-134742 / 25.10 / Improve validation when configuring STIG mode

- src/middlewared/middlewared/plugins/security/update.py
This PR adds changes to not have docker/incus be configured at the time incus is configured. Motivation behind this is that if we don't want to allow users to have apps/vms when STIG is enabled, there is no reason to have docker/incus daemons run when this is being configured. Secondly we already don't allow to change TNC settings when STIG is enabled, however we were not validating if TNC was already configured at the time STIG was being enabled, so a validation for that has been added as well.
Original PR: https://github.com/truenas/middleware/pull/15968
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134742
> NAS-134742 / 25.04.0 / Improve validation when configuring STIG mode (by sonicaj)

- src/middlewared/middlewared/plugins/smb_/util_smbconf.py
- tests/unit/test_smb_share.py
There is supposed to be a space in the configuration parameter for VFS fruit that I accidentally omitted when refactoring from the registry share configuration to flat files. The vfs_fruit parameter "time machine" controls whether the server advertises SMB2_CRTCTX_AAPL_FULL_SYNC among the filesystem capabilities for a share. Originally, this feature was required for time machine, but later MacOS versions appear to not require this.
Unfortunately, smbtorture also does not check for this capability in its tests which means that internally there was no coverage for this typo. Functional test coverage will be added once our jenkins VMs have updated py-libsmb.
> NAS-134738 / 25.10 / Fix typo in vfs_fruit configuration

- src/middlewared/middlewared/plugins/smb_/util_smbconf.py
- tests/unit/test_smb_share.py
There is supposed to be a space in the configuration parameter for VFS fruit that I accidentally omitted when refactoring from the registry share configuration to flat files. The vfs_fruit parameter "time machine" controls whether the server advertises SMB2_CRTCTX_AAPL_FULL_SYNC among the filesystem capabilities for a share. Originally, this feature was required for time machine, but later MacOS versions appear to not require this.
Unfortunately, smbtorture also does not check for this capability in its tests which means that internally there was no coverage for this typo. Functional test coverage will be added once our jenkins VMs have updated py-libsmb.
Original PR: https://github.com/truenas/middleware/pull/15974
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134738
> NAS-134738 / 25.04.0 / Fix typo in vfs_fruit configuration (by anodos325)

- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
- src/middlewared/middlewared/api/v25_10_0/virt_instance.py
If force flag is unset and timeout is not specified, there are cases where a virt instance can hang indefinitely on stopping/restarting it.
Make sure that when force flag is not set, we force the user to specify a timeout value so we don't have a job which is indefinitely stuck.
> NAS-134585 / 25.10 / Make sure timeout is set when force is unset on stopping/restarting virt instance

- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
git cherry-pick -x e4f2df52c72477d73456f7aeeec434693ab31f26
git cherry-pick -x 7da9e5e02c0060b95bb5280e7ad7e6aeda138d6e
If force flag is unset and timeout is not specified, there are cases where a virt instance can hang indefinitely on stopping/restarting it.
Make sure that when force flag is not set, we force the user to specify a timeout value so we don't have a job which is indefinitely stuck.
Original PR: https://github.com/truenas/middleware/pull/15979
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134585
> NAS-134585 / 25.04.0 / Make sure timeout is set when force is unset on stopping/restarting virt instance (by Qubad786)

- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
- src/middlewared/middlewared/api/v25_10_0/virt_instance.py
`raw` attribute can contain VNC password configuration so we should mark it as a secret in the pydantic model.
> NAS-134733 / 25.10 / Mark raw attribute in virt instance as secret in the API

- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
git cherry-pick -x 54bebb6c936ad46eb7f3f33b1e47a8b0c591a679
git cherry-pick -x 45e64aa310424ebce69346f218b8bb712d7fd8a4
`raw` attribute can contain VNC password configuration so we should mark it as a secret in the pydantic model.
Original PR: https://github.com/truenas/middleware/pull/15983
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134733
> NAS-134733 / 25.04.0 / Mark raw attribute in virt instance as secret in the API (by Qubad786)

- src/middlewared/middlewared/alembic/versions/25.04/2025-03-07_13-40_add-incus-storage-pools.py
- src/middlewared/middlewared/api/v25_04_0/virt_device.py
- src/middlewared/middlewared/api/v25_04_0/virt_global.py
- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
- src/middlewared/middlewared/api/v25_04_0/virt_volume.py
- src/middlewared/middlewared/plugins/virt/attachments.py
- src/middlewared/middlewared/plugins/virt/global.py
- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/plugins/virt/instance_device.py
- src/middlewared/middlewared/plugins/virt/utils.py
- src/middlewared/middlewared/plugins/virt/volume.py
- src/middlewared/middlewared/test/integration/assets/virt.py
- tests/api2/test_virt_storage_pool.py
- tests/unit/test_virt_utils.py
This commit adds the ability for the administrator to configure multiple storage pools for incus on TrueNAS. This is required in order to give administrators flexibility about where to store instances and the ability to shift them to different storage pools.
Due to the complexity of potential incus instance configurations, failure to initialize any incus storage pool is treated from the standpoint of middleware as a global failure to properly set up the virt plugin.
Since it touches all areas of the virt plugin APIs it is a pre-requisite for developing backup / restore and snapshot endpoints.
The middleware virt plugin has been changed in the following ways:
* virt.global.config / virt.global.update -- these methods now have a storage_pools key, that provides a list of ZFS pools that are …
> NAS-134688 / 25.04.0 / Add support for multiple storage pools to incus

- src/middlewared/middlewared/alembic/versions/25.04/2025-03-07_13-40_add-incus-storage-pools.py
- src/middlewared/middlewared/alembic/versions/25.10/2025-03-13_20-14_merge-migration-incus-storage-pools.py
- src/middlewared/middlewared/api/v25_04_0/virt_device.py
- src/middlewared/middlewared/api/v25_04_0/virt_global.py
- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
- src/middlewared/middlewared/api/v25_04_0/virt_volume.py
- src/middlewared/middlewared/api/v25_10_0/virt_device.py
- src/middlewared/middlewared/api/v25_10_0/virt_global.py
- src/middlewared/middlewared/api/v25_10_0/virt_instance.py
- src/middlewared/middlewared/api/v25_10_0/virt_volume.py
- src/middlewared/middlewared/plugins/virt/attachments.py
- src/middlewared/middlewared/plugins/virt/global.py
- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/plugins/virt/instance_device.py
- src/middlewared/middlewared/plugins/virt/utils.py
- src/middlewared/middlewared/plugins/virt/volume.py
- src/middlewared/middlewared/pytest/unit/plugins/virt/test_virt_instance_env.py
- src/middlewared/middlewared/test/integration/assets/virt.py
- tests/api2/test_virt_storage_pool.py
- tests/unit/test_virt_utils.py
This commit adds the ability for the administrator to configure multiple storage pools for incus on TrueNAS. This is required in order to give administrators flexibility about where to store instances and the ability to shift them to different storage pools.
Due to the complexity of potential incus instance configurations, failure to initialize any incus storage pool is treated from the standpoint of middleware as a global failure to properly set up the virt plugin.
Since it touches all areas of the virt plugin APIs it is a pre-requisite for developing backup / restore and snapshot endpoints.
The middleware virt plugin has been changed in the following ways:
* virt.global.config / virt.global.update -- these methods now have a storage_pools key, that provides a list of ZFS pools that are …
> NAS-134688 / 25.10 / Add support for multiple storage pools to incus (by anodos325)

- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/test/integration/assets/virt.py
There has been a case where an incus instance was not able to delete because incus complained that it can't delete a running instance. I have not been able to reproduce it specifically but there was a case which was being missed which was that if the instance is in `UNKNOWN` state which it can be but very briefly - that can result in this issue.
Make sure if instance is not stopped, we attempt to force stop it before attempting deletion and if it fails (which it can if the instance is already stopped, we just silently log it) and let deletion go through.
> NAS-134443 / 25.10 / Make sure virt instance is stopped before attempting to delete it

- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/test/integration/assets/virt.py
There has been a case where an incus instance was not able to delete because incus complained that it can't delete a running instance. I have not been able to reproduce it specifically but there was a case which was being missed which was that if the instance is in `UNKNOWN` state which it can be but very briefly - that can result in this issue.
Make sure if instance is not stopped, we attempt to force stop it before attempting deletion and if it fails (which it can if the instance is already stopped, we just silently log it) and let deletion go through.
Original PR: https://github.com/truenas/middleware/pull/15988
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134443
> NAS-134443 / 25.04.0 / Make sure virt instance is stopped before attempting to delete it (by Qubad786)

- tests/unit/test_copytree.py
This commit changes to using a set comparison insted of list comparison for directory contents.
> NAS-134777 / 25.10 / Fix copytree unit test failures

- src/middlewared/middlewared/plugins/virt/utils.py
- src/middlewared/middlewared/plugins/zfs_/utils.py
This commit fixes an issue with the incus storage pool ZFS user property prefix and puts it in the enum of truenas-manaaged user properties.
> NAS-134781 / 25.10 / Standardize prefix for incus storage pool property

- src/middlewared/middlewared/plugins/virt/utils.py
- src/middlewared/middlewared/plugins/zfs_/utils.py
This commit fixes an issue with the incus storage pool ZFS user property prefix and puts it in the enum of truenas-manaaged user properties.
Original PR: https://github.com/truenas/middleware/pull/15993
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134781
> NAS-134781 / 25.04.0 / Standardize prefix for incus storage pool property (by anodos325)

- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
- src/middlewared/middlewared/api/v25_04_0/virt_volume.py
A small diff between 2504 and 2510 had leaked in backporting changes and is being fixed.
Original PR: https://github.com/truenas/middleware/pull/15989
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134764
> NAS-134764 / 25.04.0 / Fix discrepancy between 2510 and 2504 virt pydantic models (by Qubad786)

- tests/unit/test_auditd_rules.py
The STIG unit test is failing because the recently added test used an incorrect string.  The test used the _source_ rule, but the `augenrules` utility reformats the rule.
Updated the test to use the rule as formatted by `augenrules`.
The auditd rule is included in 25.04.0 and this test fix should be backported accordingly.
> NAS-134795 / 25.10 / Fix stig unit test.

- tests/unit/test_auditd_rules.py
The STIG unit test is failing because the recently added test used an incorrect string.  The test used the _source_ rule, but the `augenrules` utility reformats the rule.
Updated the test to use the rule as formatted by `augenrules`.
The auditd rule is included in 25.04.0 and this test fix should be backported accordingly.
Original PR: https://github.com/truenas/middleware/pull/16000
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134795
> NAS-134795 / 25.04.0 / Fix stig unit test. (by mgrimesix)

- src/middlewared/middlewared/plugins/pool_/import_pool.py
- src/middlewared/middlewared/plugins/pool_/pool.py
git cherry-pick -x 555ea46582899fff53135fec9188f2b999a6b350
git cherry-pick -x a510b66662b38ac00395f81d3d5e4187a203d11b
We had added validation earlier to not allow users to set a pool for incus which has whitespaces in it's name because incus is not able to handle pool names which have whitespaces in it. Now we are adding changes to not allow user to create/import a pool with a name which contains whitespaces.
Original PR: https://github.com/truenas/middleware/pull/15984
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134689
> NAS-134689 / 25.04.0 / Do not allow users to create pool with whitespaces in name (by Qubad786)

- src/middlewared/middlewared/plugins/disk_/info.py
This is private so no reason to expose to public, therefore preventing us from needing to convert it.
> NAS-134806 / 25.10 / remove accepts from disk.info

- src/middlewared/middlewared/plugins/disk_/identify.py
This is private so no reason to expose to public, therefore preventing us from needing to convert it.
> NAS-134805 / 25.10 / remove accepts from device_to_identifier

- src/middlewared/middlewared/plugins/virt/global.py
We are doing `rm -rf` on a path where the path is coming from the variable. Now we want to be really careful with what the variable holds to as we are doing a `rm -rf` here, so instead of using the variable, the path is being hard coded directly (we don't have any other usages of the variable either) to prevent an accidental mistake on the dev part and this resulting in accidentally nuking something else.
> NAS-134796 / 25.10 / Do not use a variable when doing rm -rf

- tests/api2/test_virt_002_instance.py
Virt integration tests need to be updated to account for latest force flag changes on stop/restart endpoints.
> NAS-134773 / 25.10 / Fix virt integration tests

- tests/api2/test_virt_002_instance.py
Virt integration tests need to be updated to account for latest force flag changes on stop/restart endpoints.
Original PR: https://github.com/truenas/middleware/pull/16012
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134773
> NAS-134773 / 25.04.0 / Fix virt integration tests (by Qubad786)

- src/middlewared/middlewared/plugins/virt/global.py
We are doing `rm -rf` on a path where the path is coming from the variable. Now we want to be really careful with what the variable holds to as we are doing a `rm -rf` here, so instead of using the variable, the path is being hard coded directly (we don't have any other usages of the variable either) to prevent an accidental mistake on the dev part and this resulting in accidentally nuking something else.
Original PR: https://github.com/truenas/middleware/pull/16015
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134796
> NAS-134796 / 25.04.0 / Do not use a variable when doing rm -rf (by Qubad786)

- src/middlewared/middlewared/plugins/pool_/import_pool.py
- src/middlewared/middlewared/plugins/pool_/pool.py
Improving error message for a pool name containing whitespaces as regex being shown in validation error is not very UX friendly.
> NAS-134810 / 25.04.0 / Improve error message for pool name containing whitespaces

- src/middlewared/middlewared/plugins/virt/device.py
There could be USB devices which either don't support string descriptors or could be malfunctioning which will result in our usb choices endpoint to break down.
Safely retrieve product/manufacturer information in this case - we should expect a small subset of users who could be affected by this so marking the USB device as unknown should be good enough.
> NAS-134715 / 25.10 / Gracefully handle unsupported USB string descriptors

- src/middlewared/middlewared/plugins/virt/device.py
There could be USB devices which either don't support string descriptors or could be malfunctioning which will result in our usb choices endpoint to break down.
Safely retrieve product/manufacturer information in this case - we should expect a small subset of users who could be affected by this so marking the USB device as unknown should be good enough.
Original PR: https://github.com/truenas/middleware/pull/16017
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134715
> NAS-134715 / 25.04.0 / Gracefully handle unsupported USB string descriptors (by Qubad786)

- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/plugins/virt/instance_device.py
- src/middlewared/middlewared/test/integration/assets/virt.py
- tests/api2/test_virt_vm.py
Same source could be currently added to multiple disk devices of same/different virt instances.
Make sure we don't allow same source to be configured across multiple disk devices or same/different virt instances by having proper validation in place.
> NAS-134702 / 25.10 / Make sure same source is not added to multiple devices

- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/plugins/virt/instance_device.py
- src/middlewared/middlewared/test/integration/assets/virt.py
- tests/api2/test_virt_vm.py
Same source could be currently added to multiple disk devices of same/different virt instances.
Make sure we don't allow same source to be configured across multiple disk devices or same/different virt instances by having proper validation in place.
Original PR: https://github.com/truenas/middleware/pull/16013
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134702
> NAS-134702 / 25.04.0 / Make sure same source is not added to multiple devices (by Qubad786)

- src/middlewared/middlewared/plugins/virt/global.py
- src/middlewared/middlewared/plugins/virt/volume.py
- tests/api2/test_virt_vm.py
Currently if a user tries to create a volume with a name where the underlying zfs dataset already exists, that will result in volume creation to fail and the dataset lying there to get deleted by incus.
Make sure we translate the volume name/pool to zfs dataset and check if the underlying dataset exists before or not as otherwise incus will force delete it.
> NAS-134708 / 25.10 / Add better validation for existing zfs dataset against volume names

- src/middlewared/middlewared/plugins/virt/global.py
- src/middlewared/middlewared/plugins/virt/volume.py
- tests/api2/test_virt_vm.py
Currently if a user tries to create a volume with a name where the underlying zfs dataset already exists, that will result in volume creation to fail and the dataset lying there to get deleted by incus.
Make sure we translate the volume name/pool to zfs dataset and check if the underlying dataset exists before or not as otherwise incus will force delete it.
Original PR: https://github.com/truenas/middleware/pull/16016
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134708
> NAS-134708 / 25.04.0 / Add better validation for existing zfs dataset against volume names (by Qubad786)

- src/freenas/usr/lib/netdata/conf.d/python.d.conf
- src/freenas/usr/lib/netdata/python.d/truenas_pool.chart.py
- src/middlewared/middlewared/plugins/reporting/events.py
- src/middlewared/middlewared/plugins/reporting/realtime_reporting/__init__.py
- src/middlewared/middlewared/plugins/reporting/realtime_reporting/pool.py
- src/middlewared/middlewared/plugins/reporting/rest.py
- src/middlewared/middlewared/plugins/reporting/utils.py
- src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
- src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_stats_func.py
- src/middlewared/middlewared/utils/metrics/pool_stats.py
This PR adds changes to retrieve root dataset's usage information in realtime reporting so TNC heartbeat can consume that information.
> NAS-134387 / 25.10 / Add root datasets information to realtime reporting

- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
- src/middlewared/middlewared/api/v25_10_0/virt_instance.py
The memory error message is confusing on the UI side currently where UI allows users to specify something like `32 MiB` as well and middleware saying input should be greater then xyz.
Be more descriptive in the error message so it is acceptable on the UI side as well.
> NAS-134445 / 25.10 / Improve confusing error message

- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
git cherry-pick -x b347004f5f74c10d75145a695c3a2b82bfb6b6ab
git cherry-pick -x 8e0043609a6c273d485b3787608176ab3fe32e23
The memory error message is confusing on the UI side currently where UI allows users to specify something like `32 MiB` as well and middleware saying input should be greater then xyz.
Be more descriptive in the error message so it is acceptable on the UI side as well.
Original PR: https://github.com/truenas/middleware/pull/16030
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134445
> NAS-134445 / 25.04.0 / Improve confusing error message (by Qubad786)

- src/middlewared/middlewared/plugins/enclosure_/map2.py
The `else` branch on line 74 was never being reached when this was originally written. The internal R40 we have uses the `if` branch on line 71. We have _another_ R40 in-house where-by the `else` branch is exercised. It crashes with an `IndexError` because we're associating the `head_unit_idx` variable with the incorrect value. Fix this by accessing index position 1 instead of 0. This fixes the crash, thereby fixing the UI enclosure page for this particular variant of the R40.
> NAS-134852 / 25.10 / use correct tuple position for mapping R40

- src/middlewared/middlewared/plugins/enclosure_/map2.py
The `else` branch on line 74 was never being reached when this was originally written. The internal R40 we have uses the `if` branch on line 71. We have _another_ R40 in-house where-by the `else` branch is exercised. It crashes with an `IndexError` because we're associating the `head_unit_idx` variable with the incorrect value. Fix this by accessing index position 1 instead of 0. This fixes the crash, thereby fixing the UI enclosure page for this particular variant of the R40.
Original PR: https://github.com/truenas/middleware/pull/16026
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134852
> NAS-134852 / 25.04.0 / use correct tuple position for mapping R40 (by yocalebo)

- src/middlewared/middlewared/api/v25_04_0/virt_volume.py
- src/middlewared/middlewared/api/v25_10_0/virt_volume.py
- src/middlewared/middlewared/plugins/virt/volume.py
- tests/api2/test_virt_storage_pool.py
This commit adds an API endpoint to allow converting existing zvols into custom incus volumes. The new API endpoint takes the following parameters:
to_import - list of zvols to import as custom storage volumes in incus.
clone - boolean (default False) clone and promote a temporary snapshot of the zvol into a custom storage volume. This is an option for users who are more paranoid about migration.
This endpoint takes multiple zvols because the recovery operation is somewhat slow and expensive. It's better to do everything in one large batch.
> NAS-134807 / 25.10 / Allow import of zvols into incus volumes

- src/middlewared/middlewared/api/v25_04_0/virt_volume.py
- src/middlewared/middlewared/plugins/virt/volume.py
- tests/api2/test_virt_storage_pool.py
This commit adds an API endpoint to allow converting existing zvols into custom incus volumes. The new API endpoint takes the following parameters:
to_import - list of zvols to import as custom storage volumes in incus.
clone - boolean (default False) clone and promote a temporary snapshot of the zvol into a custom storage volume. This is an option for users who are more paranoid about migration.
This endpoint takes multiple zvols because the recovery operation is somewhat slow and expensive. It's better to do everything in one large batch.
Original PR: https://github.com/truenas/middleware/pull/16011
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134807
> NAS-134807 / 25.04.0 / Allow import of zvols into incus volumes (by anodos325)

- src/middlewared/middlewared/alembic/versions/25.04/2024-11-05_23-35_authenticator_normalization.py
- src/middlewared/middlewared/plugins/pwenc.py
This PR fixes out one of our migrations where we were not taking into account that certain columns could be null if the secret seed had changed and expected them to behave as they were decrypted.
So the changes now go through those rows and update them appropriately including their usage to make sure if secret seed has been changed, we reset the database to a form which is acceptable to middleware.
While i was here, i noticed that we are not resetting ACME DNS authenticator table when secret seed is reset, so that has been done as well including cert dns mapping.
> NAS-134728 / 25.10 / Make sure migration does not fail if user has encrypted fields not readable in DNS auth table

- src/middlewared/middlewared/alembic/versions/25.04/2024-11-05_23-35_authenticator_normalization.py
- src/middlewared/middlewared/plugins/pwenc.py
This PR fixes out one of our migrations where we were not taking into account that certain columns could be null if the secret seed had changed and expected them to behave as they were decrypted.
So the changes now go through those rows and update them appropriately including their usage to make sure if secret seed has been changed, we reset the database to a form which is acceptable to middleware.
While i was here, i noticed that we are not resetting ACME DNS authenticator table when secret seed is reset, so that has been done as well including cert dns mapping.
Original PR: https://github.com/truenas/middleware/pull/16024
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134728
> NAS-134728 / 25.04.0 / Make sure migration does not fail if user has encrypted fields not readable in DNS auth table (by sonicaj)

- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/plugins/virt/volume.py
- src/middlewared/middlewared/pytest/unit/utils/test_size_normalization.py
- src/middlewared/middlewared/utils/size.py
Users can manually manipulate sizes for incus instances which will break how we are parsing out sizes and that would be disastrous as querying is used extensively in middleware.
Better parse out various variations which can occur and report in bytes finally.
> NAS-134809 / 25.10 / Better parse out size for virt instances

- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/plugins/virt/volume.py
- src/middlewared/middlewared/pytest/unit/utils/test_size_normalization.py
- src/middlewared/middlewared/utils/size.py
Users can manually manipulate sizes for incus instances which will break how we are parsing out sizes and that would be disastrous as querying is used extensively in middleware.
Better parse out various variations which can occur and report in bytes finally.
Original PR: https://github.com/truenas/middleware/pull/16022
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134809
> NAS-134809 / 25.04.0 / Better parse out size for virt instances (by Qubad786)

- src/middlewared/middlewared/plugins/virt/instance.py
Windows does not has built-in drivers of NVME for installation media, so when setting source type to ISO and choosing a windows image to bootstrap a VM - that does not sit well by default as we default to NVME IO bus.
`VIRTIO-SCSI` is a better default for installation media when source type is set to ISO as most popular OS support it out of the box.
Tested with Windows/Ubuntu/debian
```
Win11_24H2_English_x64_incus.iso:
boot.priority: "1"
io.bus: virtio-scsi
pool: evo
source: Win11_24H2_English_x64_incus.iso
---
ubuntu-24.04.1-live-server-amd64.iso:
boot.priority: "1"
io.bus: virtio-scsi
pool: evo
source: ubuntu-24.04.1-live-server-amd64.iso
type: disk
---
debian-12.7.0-amd64-netinst.iso:
boot.priority: "1"
io.bus: virtio-scsi
pool: evo
source: debian-12.7.0-amd64-netinst.iso
type: disk …
```
> NAS-134768 / 25.10 / Use virtio-scsi when source type is iso

- src/middlewared/middlewared/plugins/virt/instance.py
Windows does not has built-in drivers of NVME for installation media, so when setting source type to ISO and choosing a windows image to bootstrap a VM - that does not sit well by default as we default to NVME IO bus.
`VIRTIO-SCSI` is a better default for installation media when source type is set to ISO as most popular OS support it out of the box.
Tested with Windows/Ubuntu/debian
```
Win11_24H2_English_x64_incus.iso:
boot.priority: "1"
io.bus: virtio-scsi
pool: evo
source: Win11_24H2_English_x64_incus.iso
---
ubuntu-24.04.1-live-server-amd64.iso:
boot.priority: "1"
io.bus: virtio-scsi
pool: evo
source: ubuntu-24.04.1-live-server-amd64.iso
type: disk
---
debian-12.7.0-amd64-netinst.iso:
boot.priority: "1"
io.bus: virtio-scsi
pool: evo
source: debian-12.7.0-amd64-netinst.iso
type: disk …
```
> NAS-134768 / 25.04.0 / Use virtio-scsi when source type is iso (by Qubad786)

- src/middlewared/middlewared/plugins/ipmi_/lan.py
Fix a KeyError crash by initializing the dictionary with the `vlan_id_enable` key. Not all IPMI implementations support vlans.
Original PR: https://github.com/truenas/middleware/pull/16044
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134736
> NAS-134736 / 25.04.0 / fix KeyError crash in ipmi.lan.query (by yocalebo)

- src/middlewared/middlewared/plugins/enclosure_/map2.py
This fixes a wiring variant of the R40 that we ship. This was after discussion with platform team and testing on internal hardware. This is a very targeted change so risk of regression for other platforms is essentially 0.
> NAS-134878 / 25.10 / Fix R40 drive mapping according to current MPI wiring

- src/middlewared/middlewared/plugins/security/update.py
The typo is the source of the generated trace.
> NAS-134658 / 25.10 / Fix typo. STIG -> GPOSSTIG

- src/middlewared/middlewared/api/v25_10_0/disk.py
This PR adds changes to fix disk details/used endpoints as they are erroring out atm. Basically for details endpoint, we want list + dict as return type being valid and for it's arguments we want to make sure consumer can get away with `disk.details` instead of doing `disk.details '{}'` because we have existing consumers which rely on this behaviour. Secondly return type for disk used endpoint needed to be addressed.
> NAS-134887 / 25.10 / Fix disk details/used methods

- src/middlewared/middlewared/plugins/idmap.py
Apparently some admins will set an empty string for the shell for their LDAP users. This commit converts that invalid value to nologin.
> NAS-134713 / 25.10 / Override empty string for LDAP-provided shell

- src/middlewared/middlewared/plugins/idmap.py
Apparently some admins will set an empty string for the shell for their LDAP users. This commit converts that invalid value to nologin.
Original PR: https://github.com/truenas/middleware/pull/15955
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134713
> NAS-134713 / 25.04.0 / Override empty string for LDAP-provided shell (by anodos325)

- tests/api2/test_ftp_crud_roles.py
It's a private api.
The role was removed here: https://github.com/truenas/middleware/pull/15939
This eliminates the failing and unnecessary test.
> NAS-134899 / 25.10 / Remove FTP connection count CRUD test.

- src/middlewared/middlewared/plugins/network.py
- src/middlewared/middlewared/plugins/virt/global.py
If incus settings are changed, they are not reflected in the incus configuration currently and if a bridge is specified to be used with incus, that bridge can be deleted even though it is specified in virt settings.
i.e
```
❯ incus network show incusbr0
config:
ipv4.address: 10.0.0.3/24
ipv4.nat: "true"
ipv6.address: fd42:6de4:130e:129d::1/64
ipv6.nat: "true"
description: ""
name: incusbr0
type: bridge
used_by:
- /1.0/instances/ubuntu-c2
- /1.0/instances/ubuntu-v10
- /1.0/instances/ubuntu-v11
- /1.0/instances/ubuntu-v9
- /1.0/profiles/default
managed: true
status: Created
locations:
- none
project: default
❯ 
❯ midclt call -j virt.global.update '{"storage_pools": ["tank"], "pool": "tank", "v4_network": "10.2.2.3/24", "v6_network": "fd42:6de4:130e:129d::1/64"}'
Status: (none)
Total …
```
> NAS-134716 / 25.10 / Make sure incus networking settings are reflected in incus

- src/middlewared/middlewared/api/v25_10_0/virt_device.py
- src/middlewared/middlewared/plugins/virt/instance_device.py
UI wanted a simpler way to allow users to select which disk they want to boot virt VM instance from. After discussing with William, an endpoint has been added which when called will get the boot priorities of existing devices and then set the boot priority of the specified disk higher then the highest one already configured to make sure OS boots from the specified disk.
> NAS-134737 / 25.10 / Expose an endpoint to let consumer select which disk should be used to boot OS

- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
- src/middlewared/middlewared/api/v25_10_0/virt_instance.py
- src/middlewared/middlewared/plugins/virt/instance.py
- tests/api2/test_virt_vm.py
We allow a streamlined process for creating a VM which boots from ISO/ZVOL/IMAGE already and now a change has been added to allow creating a VM which will boot from a BLOCK based virt volume.
> NAS-134896 / 25.10 / Allow using a virt volume as a source type when creating a VM

- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
- src/middlewared/middlewared/plugins/virt/instance.py
- tests/api2/test_virt_vm.py
git cherry-pick -x fde6e94a62d316bdfd36007a7a5a7631fb38e127
git cherry-pick -x 65fdd60ac3ebe588c4b533543a8c6dba0cb7a443
We allow a streamlined process for creating a VM which boots from ISO/ZVOL/IMAGE already and now a change has been added to allow creating a VM which will boot from a BLOCK based virt volume.
Original PR: https://github.com/truenas/middleware/pull/16062
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134896
> NAS-134896 / 25.04.0 / Allow using a virt volume as a source type when creating a VM (by Qubad786)

- src/freenas/usr/lib/modules-load.d/truenas.conf
This kernel module has been extended to report SCSI (SAS) drive temperatures via sysfs. Let's load it always. This PR is a prerequisite for a following PR.
> NAS-134929 / 25.10 / load drivetemp kernel module

- src/middlewared/middlewared/plugins/network.py
- src/middlewared/middlewared/plugins/virt/global.py
If incus settings are changed, they are not reflected in the incus configuration currently and if a bridge is specified to be used with incus, that bridge can be deleted even though it is specified in virt settings.
i.e
```
❯ incus network show incusbr0
config:
ipv4.address: 10.0.0.3/24
ipv4.nat: "true"
ipv6.address: fd42:6de4:130e:129d::1/64
ipv6.nat: "true"
description: ""
name: incusbr0
type: bridge
used_by:
- /1.0/instances/ubuntu-c2
- /1.0/instances/ubuntu-v10
- /1.0/instances/ubuntu-v11
- /1.0/instances/ubuntu-v9
- /1.0/profiles/default
managed: true
status: Created
locations:
- none
project: default
❯ 
❯ midclt call -j virt.global.update '{"storage_pools": ["tank"], "pool": "tank", "v4_network": "10.2.2.3/24", "v6_network": "fd42:6de4:130e:129d::1/64"}'
Status: (none)
Total …
```
> NAS-134716 / 25.04.0 / Make sure incus networking settings are reflected in incus (by Qubad786)

- src/middlewared/middlewared/plugins/network.py
- src/middlewared/middlewared/plugins/virt/global.py
If incus settings are changed, they are not reflected in the incus configuration currently and if a bridge is specified to be used with incus, that bridge can be deleted even though it is specified in virt settings.
i.e
```
❯ incus network show incusbr0
config:
ipv4.address: 10.0.0.3/24
ipv4.nat: "true"
ipv6.address: fd42:6de4:130e:129d::1/64
ipv6.nat: "true"
description: ""
name: incusbr0
type: bridge
used_by:
- /1.0/instances/ubuntu-c2
- /1.0/instances/ubuntu-v10
- /1.0/instances/ubuntu-v11
- /1.0/instances/ubuntu-v9
- /1.0/profiles/default
managed: true
status: Created
locations:
- none
project: default
❯ 
❯ midclt call -j virt.global.update '{"storage_pools": ["tank"], "pool": "tank", "v4_network": "10.2.2.3/24", "v6_network": "fd42:6de4:130e:129d::1/64"}'
Status: (none)
Total …
```
> NAS-134716 / 25.04.0 / Make sure incus networking settings are reflected in incus (by Qubad786) (by bugclerk)

- src/middlewared/middlewared/plugins/nfs_/debug.py
The NFS `get_debug` and `set_debug` are private methods (not included in the versioned api) but are also used to help debug customer issues.  As such maintaining the validation on the 'set' command is good.  
This PR moves the `nfs.get_debug` and `nfs.set_debug` methods to the new api method.
The passing CI is [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3622/testReport/).
> NAS-134908 / 25.10 / Convert private nfs debug to new api.

- src/middlewared/middlewared/utils/disks_/disk_class.py
With the drivetemp kernel module now reporting SAS drive temperatures, we're able to retrieve drive temperatures for all drive types (SATA/SAS/NVMe) via the `hwmon` interface via sysfs. This adds a `temp` method to retrieve said temperatures.
NOTE: This has not been plumbed in anywhere (yet). That will come in a subsequent PR.
> NAS-134930 / 25.10 / add temperature data to disk_class.py

- src/middlewared/middlewared/plugins/virt/volume.py
Uploading a 2 GiB iso currently is taking around 3 minutes 20 secs which is not very nice.
Be more aggressive about each chunk size we read from the job pipe and with the changes done, we are at 32 seconds approximately for an ISO of 2 GiB.
> NAS-134552 / 25.10 / Be more aggressive in reading contents from pipe

- src/middlewared/middlewared/plugins/virt/volume.py
Uploading a 2 GiB iso currently is taking around 3 minutes 20 secs which is not very nice.
Be more aggressive about each chunk size we read from the job pipe and with the changes done, we are at 32 seconds approximately for an ISO of 2 GiB.
Original PR: https://github.com/truenas/middleware/pull/16065
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134552
> NAS-134552 / 25.04.0 / Be more aggressive in reading contents from pipe (by Qubad786)

- src/middlewared/middlewared/plugins/virt/volume.py
Uploading a 2 GiB iso currently is taking around 3 minutes 20 secs which is not very nice.
Be more aggressive about each chunk size we read from the job pipe and with the changes done, we are at 32 seconds approximately for an ISO of 2 GiB.
Original PR: https://github.com/truenas/middleware/pull/16065
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134552
> NAS-134552 / 25.04.1 / Be more aggressive in reading contents from pipe (by Qubad786)

- src/middlewared/middlewared/utils/disks_/disk_class.py
6e01bf80c2b forgot to add logic when the `relative_path` kwarg is passed to it. This fixes said logic.
> NAS-134951 / 25.10 / fix __opener method in disk_class.py

- src/middlewared/middlewared/plugins/config.py
If we upload a config file that does not contain pwenc secret or `authorized_keys` files, we must remove old pwenc secret and `authorized_keys` files so that they are not unintentionally re-used.
When uploading a config file that uses the current pwenc secret (but does not contain a pwenc secret), the migration does not "see" the "new" secret and does not perform data migration. However, after a reboot, previous pwenc secret was being used, leading to unmigrated data being decryptable again (and subsequenr crash).
This also fixes the potential case of unintentionally allowing unexpected SSH keys to access the system.
> NAS-134952 / 25.10 / Unlink leftover files when uploading a config that is lacking some files

- src/middlewared/middlewared/plugins/config.py
If we upload a config file that does not contain pwenc secret or `authorized_keys` files, we must remove old pwenc secret and `authorized_keys` files so that they are not unintentionally re-used.
When uploading a config file that uses the current pwenc secret (but does not contain a pwenc secret), the migration does not "see" the "new" secret and does not perform data migration. However, after a reboot, previous pwenc secret was being used, leading to unmigrated data being decryptable again (and subsequenr crash).
This also fixes the potential case of unintentionally allowing unexpected SSH keys to access the system.
Original PR: https://github.com/truenas/middleware/pull/16091
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134952
> NAS-134952 / 25.04.0 / Unlink leftover files when uploading a config that is lacking some files (by themylogin)

- src/middlewared/middlewared/plugins/config.py
If we upload a config file that does not contain pwenc secret or `authorized_keys` files, we must remove old pwenc secret and `authorized_keys` files so that they are not unintentionally re-used.
When uploading a config file that uses the current pwenc secret (but does not contain a pwenc secret), the migration does not "see" the "new" secret and does not perform data migration. However, after a reboot, previous pwenc secret was being used, leading to unmigrated data being decryptable again (and subsequenr crash).
This also fixes the potential case of unintentionally allowing unexpected SSH keys to access the system.
Original PR: https://github.com/truenas/middleware/pull/16091
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134952
> NAS-134952 / 25.04.1 / Unlink leftover files when uploading a config that is lacking some files (by themylogin)

- src/middlewared/middlewared/etc_files/sssd/sssd.conf.mako
This commit removes a stray comment from the sssd configuraiton from when we were using nss-pam-ldapd for LDAP functionality.
> NAS-134981 / 25.10 / Remove comment from head of sssd.conf file

- src/middlewared/middlewared/etc_files/sssd/sssd.conf.mako
This commit removes a stray comment from the sssd configuraiton from when we were using nss-pam-ldapd for LDAP functionality.
Original PR: https://github.com/truenas/middleware/pull/16094
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134981
> NAS-134981 / 25.04.1 / Remove comment from head of sssd.conf file (by anodos325)

- src/middlewared/middlewared/etc_files/sssd/sssd.conf.mako
We were using the first hostname provided by the admin in the LDAP configuration for naming the domain section of the sssd.config.
This is a cosmetic change to prevent user confusion, and mirrors configuration in Example section of man (5) sssd.conf.
> NAS-134985 / 25.10 / Hard-code LDAP domain name in sssd.config

- src/middlewared/middlewared/etc_files/sssd/sssd.conf.mako
We were using the first hostname provided by the admin in the LDAP configuration for naming the domain section of the sssd.config.
This is a cosmetic change to prevent user confusion, and mirrors configuration in Example section of man (5) sssd.conf.
Original PR: https://github.com/truenas/middleware/pull/16096
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134985
> NAS-134985 / 25.04.1 / Hard-code LDAP domain name in sssd.config (by anodos325)

- src/middlewared/middlewared/plugins/activedirectory.py
- src/middlewared/middlewared/plugins/directoryservices_/ipa_join_mixin.py
This commit fixes an out-of-order operation in error handling
in cleanup in case of IPA join failure due to invalid DNS
configuration (failure to detect kerberos realm).
During the investigation of a sentry-reported error, additional
obscure edge cases were discovered related to users partially
configuring AD + LDAP plugins that could also lead to a
constraint violation in other code paths. These are now
protected against and will be fully addressed in 25.10 when
AD and LDAP plugins stored in a single table.
Original PR: https://github.com/truenas/middleware/pull/16102
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134992
> NAS-134992 / 25.04.1 / Prevent constraint violation on kerberos realm deletion (by anodos325)

- src/middlewared/middlewared/plugins/directoryservices_/health.py
- src/middlewared/middlewared/utils/directoryservices/health.py
directoryservices.health.recover is a private endpoint that is used to recover from various FAULTED conditions that may arise in directory services. The initial design was to perform a health check, get the error, recover from the error, and then redo the health check.
This runs into a problem if, for instance, there are multiple reasons why the directory service is faulted. The recovery attempt will fix one problem, but leave the others (which are also potentially recoverable).
This commit adjusts the internal behavior of the private API endpoint so that it will step through configuration problems attempting to fix them unless one of two condition occurs:
1. Max retry attempts is hit
2. Recovery fails with same reason twice in a row
> NAS-132600 / 25.10 / Improve directoryservices.health.recover

- src/middlewared/middlewared/plugins/directoryservices_/health.py
- src/middlewared/middlewared/utils/directoryservices/health.py
directoryservices.health.recover is a private endpoint that is used to recover from various FAULTED conditions that may arise in directory services. The initial design was to perform a health check, get the error, recover from the error, and then redo the health check.
This runs into a problem if, for instance, there are multiple reasons why the directory service is faulted. The recovery attempt will fix one problem, but leave the others (which are also potentially recoverable).
This commit adjusts the internal behavior of the private API endpoint so that it will step through configuration problems attempting to fix them unless one of two condition occurs:
1. Max retry attempts is hit
2. Recovery fails with same reason twice in a row
Original PR: …
> NAS-132600 / 25.04.1 / Improve directoryservices.health.recover (by anodos325)

- src/middlewared/middlewared/plugins/directoryservices.py
- src/middlewared/middlewared/plugins/smb.py
- src/middlewared/middlewared/plugins/sysdataset.py
This commit alters the order and circumstances in which smb.configure is called. Originally this was called during system dataset setup and during directory services setup. The new behavior is to have SMB-related directories automatically created when the system dataset setup is complete (triggered via hook) and call into the larger method of configuring the SMB service during directory services initialization. This resolves a race between smb.configure and directoryservice.setup calls that could occur during vrrp_master events.
> NAS-132103 / 25.10 / Simplify smb.configure logic for HA failover

- src/middlewared/middlewared/plugins/directoryservices.py
- src/middlewared/middlewared/plugins/smb.py
- src/middlewared/middlewared/plugins/sysdataset.py
This commit alters the order and circumstances in which smb.configure is called. Originally this was called during system dataset setup and during directory services setup. The new behavior is to have SMB-related directories automatically created when the system dataset setup is complete (triggered via hook) and call into the larger method of configuring the SMB service during directory services initialization. This resolves a race between smb.configure and directoryservice.setup calls that could occur during vrrp_master events.
Original PR: https://github.com/truenas/middleware/pull/16105
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132103
> NAS-132103 / 25.04.0 / Simplify smb.configure logic for HA failover (by anodos325)

- src/middlewared/middlewared/plugins/directoryservices.py
- src/middlewared/middlewared/plugins/smb.py
- src/middlewared/middlewared/plugins/sysdataset.py
This commit alters the order and circumstances in which smb.configure is called. Originally this was called during system dataset setup and during directory services setup. The new behavior is to have SMB-related directories automatically created when the system dataset setup is complete (triggered via hook) and call into the larger method of configuring the SMB service during directory services initialization. This resolves a race between smb.configure and directoryservice.setup calls that could occur during vrrp_master events.
Original PR: https://github.com/truenas/middleware/pull/16105
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132103
> NAS-132103 / 25.04.1 / Simplify smb.configure logic for HA failover (by anodos325)

- src/middlewared/middlewared/api/v25_10_0/pool.py
- src/middlewared/middlewared/plugins/pool_/pool.py
- tests/api2/test_pool_spare.py
1. pool.create enforces at least one data vdev is provided. The conversion pr #15848 made this the case for pool.update as well (it should not be).
2. The conversion PR fixed a typo that caused no more than one spare disk to be allowed. The typo had actually been preventing this incorrect behavior.
> NAS-134996 / 25.10 / Fix two issues with the pool.* conversion

- src/middlewared/middlewared/plugins/virt/global.py
We were reporting json dict converted to string as is when showing error for storage pools and that has been improved.
Validation error now:
```
[EINVAL] virt_global_update.storage_pools: The pool 'tank' cannot be removed because it is currently used by the following asset(s):
- Virt-Instances: tank-container-1, tank-vm-1
- Virt-Volumes: alpine-standard-3.21.3-x86_64.iso, tank-vol, test-volume-1, test-volume-2
The pool 'mypool' cannot be removed because it is currently used by the following asset(s):
- Virt-Instances: mypool-container
- Virt-Volumes: mypool-volume
The pool 'test' cannot be removed because it is currently used by the following asset(s):
- Virt-Instances: container-1, vm-1
- Virt-Volumes: test-vol
```
> NAS-134982 / 25.10 / Better report validation error of storage pools

- src/middlewared/middlewared/alert/source/smart.py
- src/middlewared/middlewared/plugins/disk_/smart.py
- src/middlewared/middlewared/utils/disks_/disk_class.py
This is at the behest of the support team.
1. add 2x specific SMART alerts (these are used heavily to indicate predictive drive failures)
2. simplify the `smart_test` private endpoint
> NAS-135019 / 25.10 / Add some SMART alerts

- src/middlewared/middlewared/alert/source/memory_errors.py
The `failover.call_remote` was missing a parameter in `MemorySizeMismatchAlertSource`.
> NAS-135023 / 25.10 / Fix call_remote in MemorySizeMismatchAlertSource

- src/freenas/usr/lib/netdata/python.d/truenas_disk_stats.chart.py
- src/middlewared/middlewared/plugins/reporting/events.py
- src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
- src/middlewared/middlewared/plugins/reporting/rest.py
- src/middlewared/middlewared/plugins/truenas_connect/heartbeat.py
- src/middlewared/middlewared/utils/disk_stats.py
There were a few problems with our disk stats plugin:
1. The conditionals in place in the disk stats plugin to detect if disk has changed won't work if a single disk was replaced with another one as the counts of the cached mapping won't change in this regard.
2. There is no need to get the same information twice in the netdata plugin i.e once when length change is detected and secondly when stats are actually retrieved and normalized.
3. Context building for historical reporting of disk stats can be improved using new implementation of disk querying.
Addressing (1), we do not do any fancy caching mechanism as that is not required really and when we get the information we just use the values we have retrieved for disk id already via disk stats implementation. In netdata plugin, we have no …
> NAS-135031 / 25.10 / Fix disk stats netdata plugin

- src/middlewared/middlewared/alert/source/memory_errors.py
Working on unrelated tickets, I noticed an internal HA system have an error message in the alert system.
```
"key": "{\"source_name\": \"MemorySizeMismatch\", \"traceback\": \"'>=' not supported between instances of 'dict' and 'int'\"}"
```
Investigating showed further that the alert was broken. After fixing this issue, I saw this alert get raised on a machine because the `MemTotal` values presented by procfs were off by 12 bytes. This is expected behavior because of how UEFI can reserve RAM at each boot. After discussion with OS team, we decided it safe to consider 2% of a difference between controllers to be large enough for this alert to be raised.
> NAS-135048 / 25.10 / fix MemorySizeMismatch alert

- src/middlewared/middlewared/alert/source/memory_errors.py
Working on unrelated tickets, I noticed an internal HA system have an error message in the alert system.
```
"key": "{\"source_name\": \"MemorySizeMismatch\", \"traceback\": \"'>=' not supported between instances of 'dict' and 'int'\"}"
```
Investigating showed further that the alert was broken. After fixing this issue, I saw this alert get raised on a machine because the `MemTotal` values presented by procfs were off by 12 bytes. This is expected behavior because of how UEFI can reserve RAM at each boot. After discussion with OS team, we decided it safe to consider 2% of a difference between controllers to be large enough for this alert to be raised.
Original PR: https://github.com/truenas/middleware/pull/16126
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135048
> NAS-135048 / 25.04.1 / fix MemorySizeMismatch alert (by yocalebo)

- src/middlewared/middlewared/api/v25_10_0/virt_instance.py
- src/middlewared/middlewared/plugins/virt/instance.py
- tests/api2/test_virt_vm.py
We now allow creating virt instances using virt volumes which can be created using zvols (we recently allowed importing zvol as virt volumes). Here it was requested by UI that they are no longer now consuming ZVOL as source type and so it can be removed from middleware.
> NAS-134913 / 25.10 / ZVOL source type being removed from virt instance creation

- src/middlewared/middlewared/plugins/virt/instance_device.py
- tests/api2/test_virt_vm.py
When `virt.instance.set_bootable_disk` endpoint is called, the selected disk loses it's `io_bus` value.
Ensure that the selected disk's `io_bus` value persists.
> NAS-135052 / 25.10 / Fix io_bus not persisting when selecting bootable disk

- src/middlewared/middlewared/pytest/unit/helpers.py
- src/middlewared/middlewared/pytest/unit/plugins/test_datastore.py
- src/middlewared/middlewared/sqlalchemy.py
- src/middlewared/middlewared/utils/plugins.py
- tests/api2/test_300_nfs.py
Passing `list` to `sa.JSON` does not work unless we use `TypeDecorator` instead of `UserDefinedType`.
Original PR: https://github.com/truenas/middleware/pull/16130
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135035
> NAS-135035 / 25.04.1 / JSON database columns should use their type param  (by creatorcary)

- src/middlewared/middlewared/plugins/disk_/disk_events.py
- src/middlewared/middlewared/plugins/disk_/retaste.py
Platform has very simple test to reproduce an issue whereby the standby controller doesn't retaste the disk AFTER it has been unlocked on active.
1. have SED disk on HA system
2. physically remove SED disk from HA system
3. physically reinsert SED disk on HA system
4. active controller receives a kernel udev event and `added_disk` kicks off and runs `disk.sed_unlock`
5. standby controller receives udev event, however, after the disk is unlocked it does not detect there are partitions on it
To remedy this situation following has been done:
1. add a `failover.call_remote` to `added_event` hook so that standby retastes the disk
2. change the private `disk.retaste` endpoint to receive a list of serial numbers of disks. (This is vitally important on HA because the `sd` or `nvme` device names …
> NAS-135053 / 25.04.1 / fix partition detection on SED for HA (by yocalebo)

- src/middlewared/middlewared/plugins/smb_/util_passdb.py
It appears that some users may have a wildcard character with
accounts that have SMB enabled. This commit shifts NT hash
conversion from hex value to earlier and raises a ValueError
if it fails. The ValueError will get picked up when doing bulk
sync of passdb file and converted into an alert for user to
redo their password.
> NAS-135059 / 25.10 / Flag smbhash of '*' as broken for passdb insertion

- src/middlewared/middlewared/plugins/smb_/util_passdb.py
It appears that some users may have a wildcard character with
accounts that have SMB enabled. This commit shifts NT hash
conversion from hex value to earlier and raises a ValueError
if it fails. The ValueError will get picked up when doing bulk
sync of passdb file and converted into an alert for user to
redo their password.
Original PR: https://github.com/truenas/middleware/pull/16137
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135059
> NAS-135059 / 25.04.1 / Flag smbhash of '*' as broken for passdb insertion (by anodos325)

- src/middlewared/middlewared/plugins/smb_/util_passdb.py
It appears that some users may have a wildcard character with
accounts that have SMB enabled. This commit shifts NT hash
conversion from hex value to earlier and raises a ValueError
if it fails. The ValueError will get picked up when doing bulk
sync of passdb file and converted into an alert for user to
redo their password.
Original PR: https://github.com/truenas/middleware/pull/16137
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135059
> NAS-135059 / 25.04.0 / Flag smbhash of '*' as broken for passdb insertion (by anodos325)

- src/middlewared/middlewared/plugins/pool_/dataset_details.py
Fix 2 issues:
1. properly stat the zvol's path
2. properly normalize the zvol's name (spaces in zvol names are replaced with plus signs in /dev/ directory)
Minor optimization:
1. short-circuit in get_iscsi_shares() based on dataset type (i.e. zvol or filesystem)
> NAS-135041 / 25.10 / fix zvol detection in pool.dataset.details

- src/middlewared/middlewared/plugins/pool_/dataset_details.py
Fix 2 issues:
1. properly stat the zvol's path
2. properly normalize the zvol's name (spaces in zvol names are replaced with plus signs in /dev/ directory)
Minor optimization:
1. short-circuit in get_iscsi_shares() based on dataset type (i.e. zvol or filesystem)
Original PR: https://github.com/truenas/middleware/pull/16143
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135041
> NAS-135041 / 25.04.1 / fix zvol detection in pool.dataset.details (by yocalebo)

- src/middlewared/middlewared/plugins/reporting/events.py
- tests/api2/test_reporting_realtime.py
5a9e300141e introduced the `failed_to_connect` paradigm but I've been told that the UI team has never used it. They actually have a bug whereby they're not guarding against this type of response. I'm doing 2 things here (after discussion with UI team).
1. remove that response altogether (it's not used)
2. don't send events if we don't have any data to report
> NAS-135091 / 25.10 / remove failed_to_connect in reporting.realtime

- src/middlewared/middlewared/plugins/pool_/dataset_details.py
This was changed by mistake in 064f768d953. It has to be because I was testing my changes locally and then mistakenly included this in the upstream PR :man_facepalming:
> NAS-134463 / 25.10 / fix {ref}quota_warning properties in pool.dataset.details

- src/middlewared/middlewared/plugins/account.py
- src/middlewared/middlewared/plugins/security/update.py
- src/middlewared/middlewared/pytest/unit/plugins/test_user_ssh_enabled_validation.py
- tests/api2/test_zzzz_stig.py
Enforce STIG rule (SRG-OS-000109-GPOS-00056) that all users be individually identified and authenticated.
This excludes accounts such as 'root' and 'truenas_admin'.
Passing CI tests are [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3778/).
> NAS-134576 / 25.10 / STIG rule: All users individually identified and authenticated

- src/middlewared/middlewared/plugins/failover_/reboot.py
```
1 validation error for FailoverRebootOtherNodeResult
result
Input should be None [type=none_required, input_value=True, input_type=bool]
```
> NAS-135123 / 25.10 / Fix validation error for FailoverRebootOtherNodeResult

- src/middlewared/middlewared/plugins/failover_/reboot.py
```
1 validation error for FailoverRebootOtherNodeResult
result
Input should be None [type=none_required, input_value=True, input_type=bool]
```
Original PR: https://github.com/truenas/middleware/pull/16166
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135123
> NAS-135123 / 25.04.1 / Fix validation error for FailoverRebootOtherNodeResult (by themylogin)

- src/middlewared/middlewared/plugins/account.py
- src/middlewared/middlewared/plugins/security/update.py
- src/middlewared/middlewared/pytest/unit/plugins/test_user_ssh_enabled_validation.py
- tests/api2/test_zzzz_stig.py
Enforce STIG rule (SRG-OS-000109-GPOS-00056) that all users be individually identified and authenticated.
This excludes accounts such as 'root' and 'truenas_admin'.
Passing CI tests are [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3778/).
Original PR: https://github.com/truenas/middleware/pull/16115
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134576
> NAS-134576 / 25.04.1 / STIG rule: All users individually identified and authenticated (by mgrimesix)

- tests/api2/test_audit_basic.py
https://github.com/truenas/middleware/pull/16166 changed the return of `failover.reboot.other_node` from `True` to `None` on success.
> NAS-135133 / 25.10 / fix test_audit_ha_query

- tests/api2/test_audit_basic.py
https://github.com/truenas/middleware/pull/16166 changed the return of `failover.reboot.other_node` from `True` to `None` on success.
Original PR: https://github.com/truenas/middleware/pull/16174
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135133
> NAS-135133 / 25.04.1 / fix test_audit_ha_query (by creatorcary)

- src/middlewared/middlewared/plugins/fc/fc.py
- src/middlewared/middlewared/plugins/fc/fc_host.py
- tests/api2/test_fibre_channel.py
Add a backup mechanism to `fc.fc_host.wire` to handle platforms that lack certain DMI information, and thus have no 'slot' in the information returned by `fc.fc_hosts`
Also:
- Allow clearing cached `fc.fc_host_nport_wwpn_choices` (for CI)
- Some `flake8` fixes
- Add `TestFixtureNoSlotFibreChannel::test_wired` to test the new mechanism
----
- Custom build #[1025](http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/1025/) - [tests](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3797/) passed.
- Non-HA fix tested locally.
> NAS-135126 / 25.10 / Handle platforms without FC PCI slot info

- src/middlewared/middlewared/plugins/test/rest.py
https://github.com/truenas/middleware/pull/16177
We want to keep our REST tests for now which will require the `resttest` endpoints to remain exposed to the REST API.
> NAS-135136 / 25.10 / set resttest methods private individually

- tests/api2/test_011_user.py
This commit fixes a missing import from test_011 caused by a missed cherry-pick from a testing branch.
> Fix missing import in test_011

- src/middlewared/middlewared/plugins/smb.py
With the current design for HA in TrueNAS, the active and standby controllers have different netbios names. This commit forcibly flushes samba's gencache after setting up samba directories and the smb.conf file, but before the remaining local account setup steps.
> NAS-135137 / 25.10 / Fix SMB guest account on HA when standalone

- src/freenas/usr/local/bin/truenas-set-authentication-method.py
This commit ensures that setting up initial account will properly set the last_password_change value so as to not have the admin account immediately locked.
> NAS-135144 / 25.10 / Fix initial admin user setup

- src/middlewared/middlewared/plugins/smb.py
With the current design for HA in TrueNAS, the active and standby controllers have different netbios names. This commit forcibly flushes samba's gencache after setting up samba directories and the smb.conf file, but before the remaining local account setup steps.
Original PR: https://github.com/truenas/middleware/pull/16186
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135137
> NAS-135137 / 25.04.1 / Fix SMB guest account on HA when standalone (by anodos325)

- src/freenas/usr/local/bin/truenas-set-authentication-method.py
This commit ensures that setting up initial account will properly set the last_password_change value so as to not have the admin account immediately locked.
Original PR: https://github.com/truenas/middleware/pull/16188
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135144
> NAS-135144 / 25.04.1 / Fix initial admin user setup (by anodos325)

- src/middlewared/middlewared/plugins/idmap_/idmap_winbind.py
This commit changes how we convert ID_TYPE_BOTH into a string for backend consumption. Originally we were translating it to 'BOTH' with the understanding that the underlying SID maps to both a user and a group in the NSS backend. This apparently got mapped to 'Unknown' in our UI, which appears very broken to our enterprise userbase. This commit dumbs down the backend somewhat so that we no longer report 'BOTH' and resolve to either USER or GROUP based on the underlying sid_type of the winbind entry.
> NAS-135103 / 25.10 / Convert ID_TYPE_BOTH to either USER or GROUP

- src/middlewared/middlewared/plugins/idmap_/idmap_winbind.py
This commit changes how we convert ID_TYPE_BOTH into a string for backend consumption. Originally we were translating it to 'BOTH' with the understanding that the underlying SID maps to both a user and a group in the NSS backend. This apparently got mapped to 'Unknown' in our UI, which appears very broken to our enterprise userbase. This commit dumbs down the backend somewhat so that we no longer report 'BOTH' and resolve to either USER or GROUP based on the underlying sid_type of the winbind entry.
Original PR: https://github.com/truenas/middleware/pull/16148
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135103
> NAS-135103 / 25.04.1 / Convert ID_TYPE_BOTH to either USER or GROUP (by anodos325)

- src/middlewared/middlewared/test/integration/assets/directory_service.py
- tests/api2/test_275_ldap.py
This commit tweaks our LDAP test assets and tests slightly for a new openldap server in the jenkins pipeline.
> NAS-135169 / 25.10 / Adjust LDAP-related tests for new LDAP server

- src/middlewared/middlewared/test/integration/assets/directory_service.py
- tests/api2/test_275_ldap.py
This commit tweaks our LDAP test assets and tests slightly for a new openldap server in the jenkins pipeline.
Original PR: https://github.com/truenas/middleware/pull/16193
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135169
> NAS-135169 / 25.04.1 / Adjust LDAP-related tests for new LDAP server (by anodos325)

- src/middlewared/middlewared/plugins/datastore/event.py
- src/middlewared/middlewared/plugins/datastore/read.py
- src/middlewared/middlewared/plugins/datastore/util.py
- src/middlewared/middlewared/plugins/datastore/write.py
I went back and forth on whether or not we even want to use the new API paradigm for these private methods but I ended up converting it as-is with what we were doing in the legacy API.
NOTE: The `datastore.query` endpoint can't be converted since it's the definition for the `query-options` object for our legacy API and we still have endpoints using legacy API.
> NAS-135100 / 25.10 / Move datastore/* plugins to new API (make them private)

- src/middlewared/middlewared/api/v25_10_0/system_advanced.py
- src/middlewared/middlewared/plugins/system_advanced/config.py
- src/middlewared/middlewared/plugins/system_advanced/serial.py
- src/middlewared/middlewared/plugins/system_advanced/syslog.py
http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3792/
> NAS-135127 / 25.10 / Convert remaining system.advanced namespace

- src/middlewared/middlewared/alert/base.py
This commit fixes a mismatch in objects related to Alert Categories that was introduced by a recent merge to add account policies to TrueNAS. A check is also added to prevent middleware startup if the alert categories get out of sync since I may not be the only developer who will somehow overlook this.
> NAS-135181 / 25.10 / Fix mismatch between AlertCategory enum and dict

- src/middlewared/middlewared/plugins/security/update.py
This improves the docstring to give a basic overview of features controlled by system.security.update and emphasize that they are only available for TrueNAS enterprise.
Original PR: https://github.com/truenas/middleware/pull/16200
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135195
> NAS-135195 / 25.04.1 / Improve docstring for system.security.update (by anodos325)

- tests/unit/test_role_manager.py
This commit expands the whitelist we keep of expected plugins for FULL_ADMIN role. This helps us to ensure that we don't have any unexpected endpoints becoming available in GPOS STIG mode.
> NAS-135215 / 25.10 / Expand whitelist of FULL_ADMIN endpoints

- src/middlewared/middlewared/utils/security.py
This commit avoids setting flag that root must set its password. In some situations the root account may never have had an explicit password set, but we need to leave account open interactive sessions.
> NAS-135222 / 25.10 / Fix ability to su to root

- src/middlewared/middlewared/utils/security.py
This commit avoids setting flag that root must set its password. In some situations the root account may never have had an explicit password set, but we need to leave account open interactive sessions.
Original PR: https://github.com/truenas/middleware/pull/16211
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135222
> NAS-135222 / 25.04.1 / Fix ability to su to root (by anodos325)

- src/middlewared/middlewared/plugins/directoryservices_/cache.py
- src/middlewared/middlewared/plugins/idmap.py
https://github.com/truenas/middleware/pull/16207 added validation to the private endpoint `directoryservices.cache._insert` that we weren't doing before. This has caused some failures in our API tests.
Add `ssh_password_enabled` and `twofactor_auth_configured` to the returns of `idmap.synthetic_user` to match the `UserEntry` schema; also rearrange the fields to match the order they appear in `UserEntry`.
> NAS-135245 / 25.10 / Fix directoryservices.cache._retrieve

- src/middlewared/middlewared/plugins/iscsi_/targets.py
Revert the behavior previously requested in NAS-128872.
We will no longer auto-delete initiators if all associated targets are deleted.
> NAS-135243 / 25.10 / Do not delete initiator group when last target in use is deleted

- src/middlewared/middlewared/plugins/iscsi_/targets.py
Revert the behavior previously requested in NAS-128872.
We will no longer auto-delete initiators if all associated targets are deleted.
Original PR: https://github.com/truenas/middleware/pull/16218
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135243
> NAS-135243 / 25.04.1 / Do not delete initiator group when last target in use is deleted (by bmeagherix)

- src/middlewared/middlewared/api/base/types/user.py
- src/middlewared/middlewared/api/v25_04_0/user.py
- src/middlewared/middlewared/api/v25_04_1/user.py
- src/middlewared/middlewared/api/v25_10_0/user.py
- tests/api2/test_account.py
This fixes a regression in local username validation that allowed non-portable characters to be used in usernames.
> NAS-135265 / 25.10 / Fix validation for local usernames

- src/middlewared/middlewared/api/base/types/user.py
- src/middlewared/middlewared/api/v25_04_0/user.py
- src/middlewared/middlewared/api/v25_04_1/user.py
- tests/api2/test_account.py
This fixes a regression in local username validation that allowed non-portable characters to be used in usernames.
Original PR: https://github.com/truenas/middleware/pull/16221
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135265
> NAS-135265 / 25.04.1 / Fix validation for local usernames (by anodos325)

- src/middlewared/middlewared/plugins/directoryservices_/util_cache.py
- src/middlewared/middlewared/plugins/idmap.py
Our directory services cache builds out UserEntry objects from passwd responses. An empty pw_shell is a valid response that the OS reinterprets as /bin/sh. See man (5) passwd. This commit performs this translation explicitly in order to make things clearer for the administrator and to avoid validation errors on the user.query API response.
> NAS-135274 / 25.10 / Fix empty shell entry in DS cache

- src/middlewared/middlewared/plugins/directoryservices_/util_cache.py
- src/middlewared/middlewared/plugins/idmap.py
Our directory services cache builds out UserEntry objects from passwd responses. An empty pw_shell is a valid response that the OS reinterprets as /bin/sh. See man (5) passwd. This commit performs this translation explicitly in order to make things clearer for the administrator and to avoid validation errors on the user.query API response.
Original PR: https://github.com/truenas/middleware/pull/16223
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135274
> NAS-135274 / 25.04.1 / Fix empty shell entry in DS cache (by anodos325)

- src/middlewared/middlewared/plugins/directoryservices_/util_cache.py
- src/middlewared/middlewared/plugins/idmap.py
Our directory services cache builds out UserEntry objects from passwd responses. An empty pw_shell is a valid response that the OS reinterprets as /bin/sh. See man (5) passwd. This commit performs this translation explicitly in order to make things clearer for the administrator and to avoid validation errors on the user.query API response.
Original PR: https://github.com/truenas/middleware/pull/16223
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135274
> NAS-135274 / 25.04.0 / Fix empty shell entry in DS cache (by anodos325)

- src/middlewared/middlewared/plugins/account.py
- src/middlewared/middlewared/test/integration/assets/two_factor_auth.py
- tests/api2/test_twofactor_auth.py
This commit fixes twofactor authentication for active directory accounts. There were no tests originally written for AD-related code paths when per-user 2FA was added to the product and it silently regressed when we added api_method for UserEntry.
> NAS-135268 / 25.10 / Fix two factor authentication for directory services

- src/middlewared/middlewared/plugins/account.py
- src/middlewared/middlewared/test/integration/assets/two_factor_auth.py
- tests/api2/test_twofactor_auth.py
This commit fixes twofactor authentication for active directory accounts. There were no tests originally written for AD-related code paths when per-user 2FA was added to the product and it silently regressed when we added api_method for UserEntry.
Original PR: https://github.com/truenas/middleware/pull/16224
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135268
> NAS-135268 / 25.04.1 / Fix two factor authentication for directory services (by anodos325)

- src/middlewared/middlewared/plugins/iscsi_/extents.py
- src/middlewared/middlewared/plugins/iscsi_/scst.py
- src/middlewared/middlewared/plugins/iscsi_/targets.py
- src/middlewared/middlewared/plugins/iscsi_/utils.py
- tests/api2/test_261_iscsi_cmd.py
Fix some aspects of ALUA that are broken on particular input
- Fix ALUA extents that contain a period character
- Fix ALUA target names that contain a colon character
Also add CI `test__target_extent_special_characters`
----
CI with passing iSCSI tests [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3913/).
> NAS-132373 / 25.10 / Fix ALUA breakage with particular input

- src/middlewared/middlewared/plugins/iscsi_/extents.py
- src/middlewared/middlewared/plugins/iscsi_/scst.py
- src/middlewared/middlewared/plugins/iscsi_/targets.py
- src/middlewared/middlewared/plugins/iscsi_/utils.py
- tests/api2/test_261_iscsi_cmd.py
Fix some aspects of ALUA that are broken on particular input
- Fix ALUA extents that contain a period character
- Fix ALUA target names that contain a colon character
Also add CI `test__target_extent_special_characters`
----
CI with passing iSCSI tests [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3913/).
Original PR: https://github.com/truenas/middleware/pull/16229
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132373
> NAS-132373 / 25.04.1 / Fix ALUA breakage with particular input (by bmeagherix)

- src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnfilters.conf.mako
- src/middlewared/middlewared/etc_files/syslog-ng/syslog-ng.conf.mako
- src/middlewared/middlewared/main.py
- src/middlewared/middlewared/test/integration/assets/system.py
- src/middlewared/middlewared/test/integration/utils/__init__.py
- src/middlewared/middlewared/test/integration/utils/system.py
--Backport PR--
Remote audit logging required two small tweaks to get full function:  Removed the 'final' statement from the syslog audit log stanza and, to avoid remote log filtering, changed the priority of the audit log messages from `debug` to `info`.
Other tweaks:  fixed flake8 complaint, added a comment.
The majority of the changes are in CI where functional remote logging tests are added.  The remote logging test will run on HA systems only and uses the standby node as the 'remote syslog server'.
The actual code changes are small, The majority of the changes are in the testing modules.
NOTE: Unable to get stable test runs via jenkins.   I was able to run the test successfully (repeatedly) when the runner was outside of jenkins.
Original PR: …
> NAS-134863 / 25.04.1 / Fix remote audit logging (by mgrimesix)

- src/middlewared/middlewared/alert/source/auth.py
Impose a limit on the number of admin logins report in `AdminSessionAlertClass`.
The number of logins will still be reported, but limit the details included.
> NAS-135291 / 25.10 / Restrict the size of AdminSession Alerts

- src/middlewared/middlewared/utils/limits.py
This addresses an issue seen in log files on standby controller of an HA pair. Rejecting a datastore operations from active controller will lead to the nodes getting out of sync with each other.
> NAS-135292 / 25.10 / Add failover.datastore.sql to message size whitelist

- src/middlewared/middlewared/utils/limits.py
This addresses an issue seen in log files on standby controller of an HA pair. Rejecting a datastore operations from active controller will lead to the nodes getting out of sync with each other.
Original PR: https://github.com/truenas/middleware/pull/16239
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135292
> NAS-135292 / 25.04.1 / Add failover.datastore.sql to message size whitelist (by anodos325)

- src/middlewared/middlewared/plugins/security/update.py
Recast frozenset to set to allow for json serialization.
Without this change JSON serialization throws an exception:
`truenas_api_client.exc.ClientException: Object of type frozenset is not JSON serializable`
> NAS-135294 / 25.10 / Fix handling of frozenset

- src/middlewared/middlewared/plugins/security/update.py
Recast frozenset to set to allow for json serialization.
Without this change JSON serialization throws an exception:
`truenas_api_client.exc.ClientException: Object of type frozenset is not JSON serializable`
Original PR: https://github.com/truenas/middleware/pull/16242
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135294
> NAS-135294 / 25.04.1 / Fix handling of frozenset (by mgrimesix)

- src/middlewared/middlewared/alert/source/auth.py
Impose a limit on the number of admin logins report in `AdminSessionAlertClass`.
The number of logins will still be reported, but limit the details included.
Original PR: https://github.com/truenas/middleware/pull/16237
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135291
> NAS-135291 / 25.04.1 / Restrict the size of AdminSession Alerts (by bmeagherix)

- src/middlewared/middlewared/plugins/reporting/realtime_reporting/pool.py
UI team is being sent empty zpool space usage stats in certain scenarios (i.e. when exporting a zpool). Data looks like
```
{
"pools": {
"boot-pool": {
"available": {},
"used": {},
"total": {}
},
"dozer": {
"available": {},
"used": {},
"total": {}
}
}
}
```
At their request, change it so that we only send data for pools we get info from OR if we can't get any data from any pools then report an empty dict at the top-level.
> NAS-135312 / 25.10 / dont send empty pool stats in reporting.realtime

- src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
- src/middlewared/middlewared/utils/__init__.py
This commit fixes a bug encountered by the UI team when using a regex on a nullable string field (fails with a TypeError). For convenience, we will convert the None to an empty string.
> NAS-135320 / 25.10 / Fix regex filters on nullable string fields

- src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
- src/middlewared/middlewared/utils/__init__.py
This commit fixes a bug encountered by the UI team when using a regex on a nullable string field (fails with a TypeError). For convenience, we will convert the None to an empty string.
Original PR: https://github.com/truenas/middleware/pull/16249
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135320
> NAS-135320 / 25.04.1 / Fix regex filters on nullable string fields (by anodos325)

- src/middlewared/middlewared/alert/source/fibre_channel.py
- src/middlewared/middlewared/plugins/fc/fc_host.py
- src/middlewared/middlewared/test/integration/assets/alert.py
- tests/api2/test_fibre_channel.py
React when Fibre Channel cards are either added to a system, or existing cards are replaced.
- Rewire when FC HBAs are added or replaced.  Generate a oneshot alert.
- Add CI tests for FC HBA addition or replacement
----
Fibre Channel CI tests pass for [HA](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3924/) and [single-node](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3927/).
> NAS-135221 / 25.10 / Rewire when FC HBAs are added or replaced

- src/middlewared/middlewared/alert/source/fibre_channel.py
- src/middlewared/middlewared/plugins/fc/fc_host.py
- src/middlewared/middlewared/test/integration/assets/alert.py
- tests/api2/test_fibre_channel.py
React when Fibre Channel cards are either added to a system, or existing cards are replaced.
- Rewire when FC HBAs are added or replaced.  Generate a oneshot alert.
- Add CI tests for FC HBA addition or replacement
----
Fibre Channel CI tests pass for [HA](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3924/) and [single-node](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3927/).
Original PR: https://github.com/truenas/middleware/pull/16241
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135221
> NAS-135221 / 25.04.1 / Rewire when FC HBAs are added or replaced (by bmeagherix)

- src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
- src/middlewared/middlewared/plugins/failover_/virtual_ips.py
QE found following bug:
1. be on HA system
2. only 1 interface marked critical for failover
3. physically unplug interface on standby controller
4. no alerts in UI/MW about the fact the only network interface is NO_CARRIER
Seems like this logic has _almost_ been in our checks for awhile but it was never plumbed in.
> NAS-135323 / 25.10 / fix network iface check on HA

- src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
- src/middlewared/middlewared/plugins/failover_/virtual_ips.py
QE found following bug:
1. be on HA system
2. only 1 interface marked critical for failover
3. physically unplug interface on standby controller
4. no alerts in UI/MW about the fact the only network interface is NO_CARRIER
Seems like this logic has _almost_ been in our checks for awhile but it was never plumbed in.
Original PR: https://github.com/truenas/middleware/pull/16259
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135323
> NAS-135323 / 25.04.1 / fix network iface check on HA (by yocalebo)

- src/middlewared/middlewared/plugins/network_/global_config.py
This regex is not doing any validation due to the unnecessary backslash, allowing any character to be included in the domain.
> NAS-135290 / 25.04.1 / Fix network.configuration domain validation

- src/middlewared/middlewared/pytest/unit/plugins/docker/test_docker_update_validation.py
PR #16251 added an additional API that needs to be mocked for `test_docker_update_validation`.
Also fix some `flake8`.
> NAS-135349 / 25.10 / Fix recent pytest breakage

- src/middlewared/middlewared/etc_files/local/ssh/sshd_config.mako
User provided  sshd aux params MUST COME LAST in the config. User provided "Match" blocks, for example, need to come AFTER the UsePam line. Otherwise ssh service WILL NOT START.
> NAS-135367 / 25.10 / fix SSH service with aux params

- src/middlewared/middlewared/etc_files/local/ssh/sshd_config.mako
User provided  sshd aux params MUST COME LAST in the config. User provided "Match" blocks, for example, need to come AFTER the UsePam line. Otherwise ssh service WILL NOT START.
Original PR: https://github.com/truenas/middleware/pull/16269
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135367
> NAS-135367 / 25.04.1 / fix SSH service with aux params (by yocalebo)

- src/middlewared/middlewared/plugins/security/update.py
- src/middlewared/middlewared/plugins/system_general/update.py
- tests/api2/test_zzzz_stig.py
Usage reporting should be disabled when in GPOS STIG mode.
Added CI test (config only, the functionality of the `network.configuration` `activity` field should be tested elsewhere)
Update test cleanup and setup to improve repeatability.
The CI test that covers both collection and the collection reporting: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3964/
> NAS-135117 / 25.10 / Add disable of 'usage' reporting when GPOS STIG is enabled.

- src/freenas/usr/local/bin/truenas-set-authentication-method.py
A recent migration that to set password_disabled field when the unixhash was "*" exposed a slight flaw in our logic for enabling the root account through setting authentication method to root (we didn't enable password authentication if it was disabled).
> NAS-135376 / 25.10 / Fix enabling the root account

- tests/api2/test_011_user.py
When marking a user as an smb user, if `password_disabled` is True, the validation error for SMB occurs before the immutable validation so the validation error message is different. This fixes the test to check for proper validation error message.
> NAS-135372 / 25.10 / Fix test_060_immutable_user_validation

- src/middlewared/middlewared/plugins/interface/netif_linux/utils.py
Change this so that we just have `mac` as a prefix. This hides macvtap (like previously) but also hides mac vlan based nics (start with `mac`). The macvlan interfaces for VMs are bleeding into the network UI page and it's causing confusion.
> NAS-135386 / 25.10 / hide macvlan interfaces from network API

- src/middlewared/middlewared/plugins/interface/netif_linux/utils.py
Change this so that we just have `mac` as a prefix. This hides macvtap (like previously) but also hides mac vlan based nics (start with `mac`). The macvlan interfaces for VMs are bleeding into the network UI page and it's causing confusion.
Original PR: https://github.com/truenas/middleware/pull/16279
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135386
> NAS-135386 / 25.04.1 / hide macvlan interfaces from network API (by yocalebo)

- src/middlewared/middlewared/plugins/docker/state_management.py
- src/middlewared/middlewared/plugins/docker/state_setup.py
This PR fixes a problem where we validate filesystem related stuff before starting a docker service which is good, however at that time we have not mounted docker datasets and yet we were validating that docker dataset is mounted or not and erroring out.
> NAS-135354 / 25.10 / Correct validation when attempting to start docker on boot

- src/middlewared/middlewared/plugins/docker/state_management.py
- src/middlewared/middlewared/plugins/docker/state_setup.py
This PR fixes a problem where we validate filesystem related stuff before starting a docker service which is good, however at that time we have not mounted docker datasets and yet we were validating that docker dataset is mounted or not and erroring out.
Original PR: https://github.com/truenas/middleware/pull/16278
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135354
> NAS-135354 / 25.04.1 / Correct validation when attempting to start docker on boot (by sonicaj)

- src/middlewared/middlewared/plugins/failover.py
- src/middlewared/middlewared/plugins/interface/link_address.py
- src/middlewared/middlewared/pytest/unit/plugins/test_failover.py
Physical NICs can't be just matched by name, because names can change due to OS kernel upgrades. Match them by hardware addresses instead.
> NAS-134549 / 25.10 / improve network check in HA check

- src/middlewared/middlewared/plugins/failover.py
- src/middlewared/middlewared/plugins/interface/link_address.py
- src/middlewared/middlewared/pytest/unit/plugins/test_failover.py
Physical NICs can't be just matched by name, because names can change due to OS kernel upgrades. Match them by hardware addresses instead.
Original PR: https://github.com/truenas/middleware/pull/16264
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134549
> NAS-134549 / 25.04.1 / improve network check in HA check (by themylogin)

- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
- src/middlewared/middlewared/api/v25_04_1/virt_instance.py
- src/middlewared/middlewared/api/v25_10_0/virt_instance.py
This commit adds FROZEN and ERROR as possible incus instance status since they are mentioned in incus documentation. Lxc additionally defines state strings of STARTING, STOPPING, FREEZING, and THAWED which technically possibly surface as instance state. C.f src/lxc/state.c in lxc codebase.
> NAS-135377 / 25.10 / Expand possible incus instance status results in API

- src/middlewared/middlewared/job.py
- src/middlewared/middlewared/plugins/cloud_backup/restic.py
Log excerpt will now appear like this in the UI:
```
message_type: summary
files_new: 3
files_changed: 0
files_unmodified: 0
dirs_new: 0
dirs_changed: 0
dirs_unmodified: 0
data_blobs: 0
tree_blobs: 1
data_added: 826
total_files_processed: 3
total_bytes_processed: 0
total_duration: 4.006957777
snapshot_id: 16a186de3e444d637cc37df96faab79850bde402f447a575dfbce040d9d10e6a
```
The full log will still be available at the given log path.
This change has the side-effect of being able to manually set log excerpts for other jobs in middleware.
> NAS-134491 / 25.10 / Shorten TrueCloud Backup log excerpt

- src/middlewared/middlewared/job.py
- src/middlewared/middlewared/plugins/cloud_backup/restic.py
Log excerpt will now appear like this in the UI:
```
message_type: summary
files_new: 3
files_changed: 0
files_unmodified: 0
dirs_new: 0
dirs_changed: 0
dirs_unmodified: 0
data_blobs: 0
tree_blobs: 1
data_added: 826
total_files_processed: 3
total_bytes_processed: 0
total_duration: 4.006957777
snapshot_id: 16a186de3e444d637cc37df96faab79850bde402f447a575dfbce040d9d10e6a
```
The full log will still be available at the given log path.
This change has the side-effect of being able to manually set log excerpts for other jobs in middleware.
Original PR: https://github.com/truenas/middleware/pull/16283
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134491
> NAS-134491 / 25.04.1 / Shorten TrueCloud Backup log excerpt (by creatorcary)

- src/middlewared/middlewared/plugins/truenas_connect/update.py
This PR removes ip validation from tnc configuration allowing users to specify an valid IP they want to work with TNC.
> NAS-133828 / 25.10 / Remove IP validation on TNC configuration

- src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
https://github.com/truenas/middleware/pull/16260
This typo is not present in GE.
> NAS-135425 / 25.04.1 / Fix typo in failover.disabled.get_reasons

- tests/api2/test_cloud_backup.py
http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3990/testReport/api2/test_008_cloud_backup/
https://github.com/truenas/middleware/pull/16291 cut out most of the log file from the log excerpt. Use the full log in this test instead of the excerpt.
> NAS-135430 / 25.10 / Fix cloud_backup test

- tests/api2/test_cloud_backup.py
http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/3990/testReport/api2/test_008_cloud_backup/
https://github.com/truenas/middleware/pull/16291 cut out most of the log file from the log excerpt. Use the full log in this test instead of the excerpt.
Original PR: https://github.com/truenas/middleware/pull/16297
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135430
> NAS-135430 / 25.04.1 / Fix cloud_backup test (by creatorcary)

- src/middlewared/middlewared/utils/origin.py
`socket.family` will always be `AF_INET` for internal nginx->middleware connections
> NAS-135361 / 25.10 / `get_tcp_ip_info` should determine socket family based on `X-Real-Remote-Addr`

- src/middlewared/middlewared/api/v25_10_0/pool.py
This decorates a public endpoint `pool.validate_name` which the UI uses to "validate" the zpool name. The public endpoint just passes off the string to libzfs. However, libzfs is much more lenient on what it allows to be used in zpool names. We had to add stricter validation because incus has bugs whereby it can't handle zpools with spaces in the names. We miseed, on the other hand, adding the same validation to this endpoint so it causes incongruity.
> NAS-135466 / 25.10 / fix schema validtaion in pool.validate_name

- src/middlewared/middlewared/api/v25_10_0/virt_instance.py
- src/middlewared/middlewared/plugins/virt/instance.py
RTC for incus VMs are by default set to UTC, which is fine for linux base VMs but it is problematic for Windows VMs because Windows requires RTC to be set to `localtime` in order to work correctly. To resolve this, it is required that `image.os` property is set to `Windows`, by doing this, incus will set rtc to localtime internally.
This PR introduces a `image_os` field which a user can specify at the time of creating an instance or updating it. We specify a few popular OS choices but let the user specify anything else he might want as well.
> NAS-134717 / 25.10 / Allow specifying image OS for virt VMs

- src/middlewared/middlewared/plugins/virt/instance_device.py
We were enforcing that user specify boot priority when they added a disk device which was based off an ISO volume so it was a conscious decision on the user part in terms of knowing they want to boot from the ISO or not. However with recent changes made to UI on how it handles boot priority and allowing users to boot from X disk device, this is no longer required and actually hurts usability hence this check is being removed.
> NAS-135489 / 25.10 / Do not enforce boot priority for ISO volumes

- src/middlewared/middlewared/api/v25_10_0/virt_device.py
- src/middlewared/middlewared/plugins/virt/instance_device.py
As of now, user was not allowed to set `MAC address` to VMs. This PR ensures that the user can specify `mac` when adding a device type of `nic` to the incus instance.
> NAS-135383 / 25.10 / Allow specifying custom MAC address for NIC device in virt instance

- src/middlewared/middlewared/plugins/crypto_/renew_certs.py
- src/middlewared/middlewared/plugins/failover_/event.py
This PR adds changes to make sure that certs are only renewed on the active node and standby/active both do not try to do that.
> NAS-135477 / 25.10 / Make sure certs are only renewed on active node

- src/middlewared/middlewared/plugins/account.py
- src/middlewared/middlewared/plugins/account_/constants.py
- src/middlewared/middlewared/plugins/filesystem.py
- src/middlewared/middlewared/plugins/idmap.py
- tests/unit/test_container_root.py
This commit adds a user truenas_container_root that doesn't get written to passwd and shadow files, but exists in user-related API responses. This allows users to assign permissions to the root uid in non-privileged containers and generally have UI look less confusing.
Original PR: https://github.com/truenas/middleware/pull/16319
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135375
> NAS-135375 / 25.04.1 / Add a synthetic container root user (by anodos325)

- src/middlewared/middlewared/api/v25_04_0/virt_instance.py
- src/middlewared/middlewared/api/v25_04_1/virt_instance.py
This commit adds FROZEN and ERROR as possible incus instance status since they are mentioned in incus documentation. Lxc additionally defines state strings of STARTING, STOPPING, FREEZING, and THAWED which technically possibly surface as instance state. C.f src/lxc/state.c in lxc codebase.
Original PR: https://github.com/truenas/middleware/pull/16276
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135377
> NAS-135377 / 25.04.1 / Expand possible incus instance status results in API (by anodos325)

- src/middlewared/middlewared/plugins/security/update.py
- tests/api2/test_zzzz_stig.py
The features Docker, VM support and TrueNAS Connect are not allowed under STIG mode.
Moved validation checks for those to the STIG enable command to facilitate CI testing.
Update the STIG CI test to include the STIG enable validation checks.
Also added CI tests to confirm the features cannot be enabled while in STIG mode.
Passing CI tests: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4028/
> NAS-135481 / 25.10 / Add validation checks for STIG enable.

- src/middlewared/middlewared/plugins/etc.py
- tests/unit/test_container_root.py
This commit fixes an error is passwd and shadow file generation that was introduced by adding a synthetic account for the container root user, the uid of this account is now explicitly filtered out of the user query passed as render state to the respective mako files. Test coverage is also added.
> NAS-135510 / 25.10 / Fix passwd and shadow file generation

- src/middlewared/middlewared/api/base/types/user.py
- src/middlewared/middlewared/api/v25_10_0/group.py
- src/middlewared/middlewared/pytest/unit/api/base/types/test_user.py
- tests/api2/test_account.py
Group names are validated similarly to how usernames are validated, only allowing characters in the [portable filename character set](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_282). Furthermore, they cannot start with a hyphen "-".
See https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/V1_chap03.html#tag_03_166.
http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4045/
> NAS-135270 / 25.10 / Better group name validation

- src/middlewared/middlewared/plugins/etc.py
- tests/unit/test_container_root.py
This commit fixes an error is passwd and shadow file generation that was introduced by adding a synthetic account for the container root user, the uid of this account is now explicitly filtered out of the user query passed as render state to the respective mako files. Test coverage is also added.
Original PR: https://github.com/truenas/middleware/pull/16323
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135510
> NAS-135510 / 25.04.1 / Fix passwd and shadow file generation (by anodos325)

- src/middlewared/middlewared/plugins/api_key.py
- tests/unit/test_pam_tdb.py
This commit enforces the PAM module limit on maximum number of API keys on a per-user basis, and adds a validation error.
Original PR: https://github.com/truenas/middleware/pull/16327
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135526
> NAS-135526 / 25.04.1 / Add explicit validation for API key count (by anodos325)

- src/middlewared/middlewared/plugins/pool_/dataset.py
This commit improves our validation message when an API consumer tries to create a ZFS resource with a zvol for its parent.
> NAS-135531 / 25.10 / Improve validation for ZFS resource creation

- src/middlewared/middlewared/plugins/pool_/dataset.py
This commit improves our validation message when an API consumer tries to create a ZFS resource with a zvol for its parent.
Original PR: https://github.com/truenas/middleware/pull/16329
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135531
> NAS-135531 / 25.04.1 / Improve validation for ZFS resource creation (by anodos325)

- src/middlewared/middlewared/api/v25_10_0/truecommand.py
In every case, `SecretStr` can be replaced with `Secret[str]` and function in the same way. `Secret` is handled explicitly in our custom `BaseModel` class and should *always* be used over `SecretStr`.
> NAS-135528 / 25.10 / Replace `SecretStr` in TrueCommand API (not serializing properly)

- src/middlewared/middlewared/plugins/account.py
- src/middlewared/middlewared/plugins/security/update.py
This commit fixes a check when enabling STIG that was supposed to validate that generic accounts such as "admin" or "truenas_admin" are disabled. Unfortunately, the original check included directory services uses which had the effect of preventing admins from enabling STIG while joined to AD.
> NAS-135537 / 25.10 / Fix check for enabled generic accounts

- src/middlewared/middlewared/plugins/account.py
2 issues here being addressed:
1. on line 782 we have a check for `if not group`, when that branch is true we add to a verrors object but never check for it. Since we don't check for this verrors object, on line 784 we do not protect the `group[0]` action and so we crash with an IndexError.
2. On line 650, we have the same exact logic, however, we raise a `CallError` in that if branch which protects us from this IndexError crash.
Fixes implemented:
1. protect the `group = group[0]` operation in an `else` branch to prevent `IndexError`
2. be consistent and create a `verrors` object and add a `verrors.check()` call before we move further down the logic
> NAS-135550 / 25.10 / fix IndexError in account.update

- src/middlewared/middlewared/plugins/account.py
2 issues here being addressed:
1. on line 782 we have a check for `if not group`, when that branch is true we add to a verrors object but never check for it. Since we don't check for this verrors object, on line 784 we do not protect the `group[0]` action and so we crash with an IndexError.
2. On line 650, we have the same exact logic, however, we raise a `CallError` in that if branch which protects us from this IndexError crash.
Fixes implemented:
1. protect the `group = group[0]` operation in an `else` branch to prevent `IndexError`
2. be consistent and create a `verrors` object and add a `verrors.check()` call before we move further down the logic
Original PR: https://github.com/truenas/middleware/pull/16341
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135550
> NAS-135550 / 25.04.1 / fix IndexError in account.update (by yocalebo)

- src/middlewared/middlewared/plugins/failover_/remote.py
This commit adds handling for failed POST request to send a file to the remote node in an HA pair. This protects against JSON decoder error and hopefully provides a useful error message from the remote node.
> NAS-135588 / 25.10 / Avoid JSON decode error on failed failover send

- .github/workflows/lint.yml
- src/middlewared/middlewared/api/base/validators_/passwd_complexity.py
- src/middlewared/middlewared/api/v25_10_0/acme_dns_authenticator.py
- src/middlewared/middlewared/api/v25_10_0/api_key.py
- src/middlewared/middlewared/api/v25_10_0/ipmi_lan.py
- src/middlewared/middlewared/api/v25_10_0/truecommand.py
- src/middlewared/middlewared/pytest/unit/api/base/types/test_base.py
- src/middlewared/setup.cfg
...plus a little API cleanup.
The added flake8 lint condition will fail if `pydantic.SecretStr` is imported anywhere in middlewared.
http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4091/
Security context: The TrueNAS API uses `pydantic.Secret` and `pydantic.SecretStr` to mark sensitive API fields like API keys and passwords that should be hidden in log files and the like.
> NAS-135538 / 25.10 / Remove all references to `pydantic.SecretStr`

- src/middlewared/middlewared/plugins/security/update.py
- tests/api2/test_zzzz_stig.py
The 'support' activity attempts to automatically send information to the TrueNAS support team.   This is not allowed in STIG mode.
Include a CI test:  http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4159/
> NAS-135427 / 25.10 / Add 'support' to the list of denied activities allowed in STIG mode.

- src/middlewared/middlewared/plugins/security/update.py
- tests/api2/test_zzzz_stig.py
The 'support' activity attempts to automatically send information to the TrueNAS support team.   This is not allowed in STIG mode.
Include a CI test:  http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4159/
Original PR: https://github.com/truenas/middleware/pull/16354
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135427
> NAS-135427 / 25.04.1 / Add 'support' to the list of denied activities allowed in STIG mode. (by mgrimesix)

- src/middlewared/middlewared/utils/security.py
This commit drops the password prompt age (the amount of days before account expiration at which we start to nag users) from seven days to six days. This is because our validator sets the absolute minimum value of max_password_age at seven days, and if both are at seven days then newly-created users will be automatically prompted to set passwords. That said, setting a 7 day max age for user account passwords is a questionable life choice for an administrator.
> NAS-135599 / 25.10 / Slightly drop password prompt age

- src/middlewared/middlewared/utils/security.py
This commit drops the password prompt age (the amount of days before account expiration at which we start to nag users) from seven days to six days. This is because our validator sets the absolute minimum value of max_password_age at seven days, and if both are at seven days then newly-created users will be automatically prompted to set passwords. That said, setting a 7 day max age for user account passwords is a questionable life choice for an administrator.
Original PR: https://github.com/truenas/middleware/pull/16358
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135599
> NAS-135599 / 25.04.1 / Slightly drop password prompt age (by anodos325)

- src/middlewared/middlewared/api/v25_04_1/system_security.py
- src/middlewared/middlewared/api/v25_10_0/system_security.py
Make it more clear to API consumers that None / null is an okay value for the length of password history.
> NAS-135603 / 25.10 / Expand documentation for password_history_length

- src/middlewared/middlewared/plugins/account.py
- tests/api2/test_account_idmap.py
We had validation in place to prevent changing `userns_idmap` attr for builtin groups, however the validation was missing an edge case. We checked if user tried to change the attr to something else but if the attr was set and had `null ` in it - then it would bypass the existing validation we have.
Make sure we properly handle the case where someone could unset `userns_idmap` for builtin users and also add integration tests to properly validate this.
> NAS-135475 / 25.10 / Do not allow to unset userns_idmap for builtins

- src/middlewared/middlewared/test/integration/assets/alert.py
Noticed that occasionally this would cause a CI failure.  Add some retry code to avoid.
> NAS-135605 / 25.10 / Robustize AlertMixin.clear_alert

- src/middlewared/middlewared/test/integration/assets/alert.py
Noticed that occasionally this would cause a CI failure.  Add some retry code to avoid.
Original PR: https://github.com/truenas/middleware/pull/16365
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135605
> NAS-135605 / 25.04.1 / Robustize AlertMixin.clear_alert (by bmeagherix)

- src/middlewared/middlewared/plugins/account.py
- tests/api2/test_account_idmap.py
We had validation in place to prevent changing `userns_idmap` attr for builtin groups, however the validation was missing an edge case. We checked if user tried to change the attr to something else but if the attr was set and had `null ` in it - then it would bypass the existing validation we have.
Make sure we properly handle the case where someone could unset `userns_idmap` for builtin users and also add integration tests to properly validate this.
Original PR: https://github.com/truenas/middleware/pull/16361
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135475
> NAS-135475 / 25.04.1 / Do not allow to unset userns_idmap for builtins (by Qubad786)

- src/middlewared/middlewared/plugins/failover.py
Our HA CI has exposed an egde-case failure condition. The steps for setting up our HA VMs are as follows:
1. set up SSH
2. apply license
3. disable HA
4. apply interface changes (set up virtual IP, failover alias, etc)
5. sync to peer and reboot standby controller
6. create zpool and enable HA
The scenario that this exposes is that we're not persisting the interface mac addresses thereby producing a `MISMATCH_NICS` error in `failover.disabled.reasons`. This boils down to the fact that when we run `sync_to_peer` we're overwriting the B node's mac address column because a failover event has _NOT_ occurred at this point in the setup. The fix is rather simple, in the `failover.sync_to_peer` method we'll persist the interface mac addresses BEFORE we sync the database over to it. (This is …
> NAS-135598 / 25.10 / persist MAC addresses in sync_to_peer

- src/middlewared/middlewared/plugins/failover.py
Our HA CI has exposed an egde-case failure condition. The steps for setting up our HA VMs are as follows:
1. set up SSH
2. apply license
3. disable HA
4. apply interface changes (set up virtual IP, failover alias, etc)
5. sync to peer and reboot standby controller
6. create zpool and enable HA
The scenario that this exposes is that we're not persisting the interface mac addresses thereby producing a `MISMATCH_NICS` error in `failover.disabled.reasons`. This boils down to the fact that when we run `sync_to_peer` we're overwriting the B node's mac address column because a failover event has _NOT_ occurred at this point in the setup. The fix is rather simple, in the `failover.sync_to_peer` method we'll persist the interface mac addresses BEFORE we sync the database over to it. (This is …
> NAS-135598 / 25.04.1 / persist MAC addresses in sync_to_peer (by yocalebo)

- src/middlewared/middlewared/plugins/virt/instance.py
We should immediately raise a ValidationError if in virt.instance.start if instance status is an unexpected value (for example "ERROR").
> NAS-135601 / 25.10 / Add status validation for instance start

- src/middlewared/middlewared/plugins/virt/instance.py
We should immediately raise a ValidationError if in virt.instance.start if instance status is an unexpected value (for example "ERROR").
Original PR: https://github.com/truenas/middleware/pull/16359
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135601
> NAS-135601 / 25.04.1 / Add status validation for instance start (by anodos325)

- src/middlewared/middlewared/plugins/virt/attachments.py
- src/middlewared/middlewared/pytest/unit/plugins/virt/test_attachment_delegate.py
There are 2 problems here:
1. Missing attachment delegate for incus service
2. Mixed/convoluted logic for virt instance attachment delegate which along with trying to account for (1) is also not handling zvols properly
Case (1) will be addressed in a subsequent PR, whereas for (2) we are not accounting for zvols and also trying to mix logic in terms of what should happen when delete is called.
Fix the attachment delegate to properly account for zvols and also on deletion make sure that we don't unset incus service but rather remove that zvol from a virt instance for example if that zvol is being deleted.
> NAS-135308 / 25.10 / Fix virt instance attachment delegate

- src/middlewared/middlewared/plugins/virt/attachments.py
- src/middlewared/middlewared/pytest/unit/plugins/virt/test_attachment_delegate.py
There are 2 problems here:
1. Missing attachment delegate for incus service
2. Mixed/convoluted logic for virt instance attachment delegate which along with trying to account for (1) is also not handling zvols properly
Case (1) will be addressed in a subsequent PR, whereas for (2) we are not accounting for zvols and also trying to mix logic in terms of what should happen when delete is called.
Fix the attachment delegate to properly account for zvols and also on deletion make sure that we don't unset incus service but rather remove that zvol from a virt instance for example if that zvol is being deleted.
Original PR: https://github.com/truenas/middleware/pull/16379
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135308
> NAS-135308 / 25.04.1 / Fix virt instance attachment delegate (by Qubad786)

- src/middlewared/middlewared/alembic/versions/25.04/2025-04-29_16-48_remove-cipher-column.py
- src/middlewared/middlewared/alembic/versions/25.10/2025-04-02_15-40_merge-migration.py
Add a copy of the revision in 23.10 that removed `cipher` from `system_keychaincredential.attributes`. It is possible for this field to have been added back to the database by an uploaded configuration. Due to strictly enforced API return schemas introduced in 25.04, having the extra field causes some `keychaincredential` API calls to fail.
Related PR: https://github.com/truenas/middleware/pull/16091
> NAS-135429 / 25.10 / Remove `cipher` from `system_keychaincredential` table in case it has been re-added

- src/middlewared/middlewared/utils/security.py
If password authentication is disabled and user has never had a password set, then we should not set the flag that a password change is required. The reason for this is that the account may still be used for an SSH session that is authenticated via key and we need to allow normal login to succeed (and not prompt for a password change).
> NAS-135623 / 25.10 / Relax security check for password aging data

- src/middlewared/middlewared/alembic/versions/25.04/2025-04-29_16-48_remove-cipher-column.py
git cherry-pick -x 1cb04e35f541bf04eff4c4da2162f629e9140a39
git cherry-pick -x 6604a29fb5c6a798b806bc1b48eb1773e5bffa39
git cherry-pick -x 70cdb356fcaea0fee463322f72ff0030e78a6293
Add a copy of the revision in 23.10 that removed `cipher` from `system_keychaincredential.attributes`. It is possible for this field to have been added back to the database by an uploaded configuration. Due to strictly enforced API return schemas introduced in 25.04, having the extra field causes some `keychaincredential` API calls to fail.
Related PR: https://github.com/truenas/middleware/pull/16091
Original PR: …
> NAS-135429 / 25.04.1 / Remove `cipher` from `system_keychaincredential` table in case it has been re-added (by creatorcary)

- docs/source/middleware/index.rst
- docs/source/middleware/state.rst
- src/middlewared/middlewared/alert/source/audit.py
- src/middlewared/middlewared/plugins/audit/__init__.py
- src/middlewared/middlewared/plugins/audit/audit.py
- src/middlewared/middlewared/plugins/system/__init__.py
- src/middlewared/middlewared/plugins/system/lifecycle.py
- src/middlewared/middlewared/plugins/system/utils.py
- src/middlewared/middlewared/utils/__init__.py
- tests/api2/test_audit_alerts.py
Delay certain expensive parts of middlewared auditing startup (an initial scan for file changes and removing unnecessary refreservations on old audit datasets) until after the system READY event, and only perform it on first boot after upgrade or fresh install.
> NAS-135620 / 25.10 / Simplify middleware audit startup

- src/middlewared/middlewared/plugins/audit/backend.py
We perform VACUUM after applying retention settings via cron and so we don't need to VACUUM on middleware startup. This reduces the amount of DB operations on audit tables during middleware startup.
> NAS-135634 / 25.10 / Avoid vacuum operation on audit databases

- src/middlewared/middlewared/plugins/audit/backend.py
We perform VACUUM after applying retention settings via cron and so we don't need to VACUUM on middleware startup. This reduces the amount of DB operations on audit tables during middleware startup.
Original PR: https://github.com/truenas/middleware/pull/16388
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135634
> NAS-135634 / 25.04.1 / Avoid vacuum operation on audit databases (by anodos325)

- src/middlewared/middlewared/plugins/cloud_sync.py
- src/middlewared/middlewared/rclone/remote/sftp.py
User may choose not to specify a private key for an SFTP backup in which case password authentication or authentication with an ssh-agent will be attempted instead.
https://rclone.org/sftp/#ssh-authentication
Original PR: https://github.com/truenas/middleware/pull/16389
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135582
> NAS-135582 / 25.04.1 / Allow `None` SFTP private key (by creatorcary)

- src/middlewared/middlewared/plugins/audit/audit.py
- src/middlewared/middlewared/plugins/audit/utils.py
`AuditService.setup()` produces invalid log entry in `middlewared.log`.
```
[2025/04/30 12:00:30] (ERROR) AuditService.setup():484 - Did not get clean result from truenas_verify initial setup. See /var/log/truenas_verify.TrueNAS-25.10.0-MASTER-20250430-104814.log
```
Fix 2 issues here:
1. this is not an error, bump it down to a warning
2. use the `LOG_PATH_NAME` constant defined in the `truenas_verify` package.
> NAS-135641 / 25.10 / fix invalid AuditService.setup log message

- src/middlewared/middlewared/plugins/audit/audit.py
- src/middlewared/middlewared/plugins/audit/utils.py
`AuditService.setup()` produces invalid log entry in `middlewared.log`.
```
[2025/04/30 12:00:30] (ERROR) AuditService.setup():484 - Did not get clean result from truenas_verify initial setup. See /var/log/truenas_verify.TrueNAS-25.10.0-MASTER-20250430-104814.log
```
Fix 2 issues here:
1. this is not an error, bump it down to a warning
2. use the `LOG_PATH_NAME` constant defined in the `truenas_verify` package.
Original PR: https://github.com/truenas/middleware/pull/16393
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135641
> NAS-135641 / 25.04.1 / fix invalid AuditService.setup log message (by yocalebo)

- src/middlewared/middlewared/plugins/pool_/dataset.py
- tests/api2/test_pool_dataset_create.py
A non-intuitive error message was raised when someone tried to create a dataset underneath a zpool that doesn't exist. This fixes the problem and adds a simple test.
> NAS-135557 / 25.10 / fix validation error in pool.dataset.create

- src/middlewared/middlewared/plugins/iscsi_/targets.py
Fix typo in `iscsi.target.update` schema.  Was `iscsi_target_create` but should have been `iscsi_target_update`.
Manually verified that WebUI still handles the updated value properly.
> NAS-135657 / 25.10 / Fix typo in iscsi.target.update schema

- src/middlewared/debian/middlewared.service
We have a few users unable to upgrade to 25.04.0 because the middlewared.service is being killed during boot process because our default timeout is 4mins (240 seconds). I have a fear this is a combination of pydantic and really poor performing boot drives. Either way, we are adding more and more to the monolithic middlewared service and so it's inevitable that service initialization takes longer.
> NAS-135663 / 25.10 / increase middlewared.service timeout

- src/middlewared/debian/middlewared.service
We have a few users unable to upgrade to 25.04.0 because the middlewared.service is being killed during boot process because our default timeout is 4mins (240 seconds). I have a fear this is a combination of pydantic and really poor performing boot drives. Either way, we are adding more and more to the monolithic middlewared service and so it's inevitable that service initialization takes longer.
Original PR: https://github.com/truenas/middleware/pull/16406
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135663
> NAS-135663 / 25.04.2 / increase middlewared.service timeout (by yocalebo)

- src/middlewared/middlewared/plugins/update_/pending_linux.py
UI team has switched to using this endpoint which has exposed a bug that has probably been here since it was written. For reasons unknown, systems running version can be the same as the file that has been downloaded. In this instance, this returned an "update" but the versions were the same. Regardless of that the `can_update` function has been written for this exact scenario.
> NAS-135667 / 25.10 / Fix update.get_pending

- src/middlewared/middlewared/plugins/smb.py
- src/middlewared/middlewared/plugins/smb_/constants.py
- src/middlewared/middlewared/plugins/smb_/util_smbconf.py
- tests/unit/test_smb_share.py
This commit removes kernel oplocks in favor of disabling oplocks
on a per-share basis when they have been flagged for mixed-mode
use. This avoids issues observed in the field with kernel lease
breaks possibly blocking smbd main loop and causing client timeouts
as well allowing SMB leases globally. If client requests an SMB
lease on a multiprotocol share as part of an SMB2 create request
then no lease will be granted, but the open itself will succeed.
This matches older behavior in TrueNAS core and has not resulted
in any bug reports historically.
> NAS-135040 / 25.10 / Change how oplocks are handled for multiprotocol shares

- src/middlewared/middlewared/api/v25_10_0/interface.py
These fields are not always returned.
> NAS-135700 / 25.10 / Don't require `rx_queues` or `tx_queues` in interface.create result

- src/middlewared/middlewared/api/v25_10_0/disk.py
The `disk_extend` method explicitly sets `disk['size'] = None` (which is rather strange) so we need to fix the API schema so we don't crash unnecessarily.
> NAS-135735 / 25.10 / fix API schema for disk.query

- src/middlewared/middlewared/alert/source/license_status.py
We never ended up shipping a fseries "NR" variant so this removes the obsolete logic (and comment).
> NAS-135741 / 25.10 / remove license alert check for fseries NR variant

- src/middlewared/middlewared/alert/source/license_status.py
We never ended up shipping a fseries "NR" variant so this removes the obsolete logic (and comment).
Original PR: https://github.com/truenas/middleware/pull/16438
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135741
> NAS-135741 / 25.04.1 / remove license alert check for fseries NR variant (by yocalebo)

- src/middlewared/middlewared/alert/source/license_status.py
We never ended up shipping a fseries "NR" variant so this removes the obsolete logic (and comment).
Original PR: https://github.com/truenas/middleware/pull/16438
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135741
> NAS-135741 / 25.04.2 / remove license alert check for fseries NR variant (by yocalebo)

- src/freenas/etc/sysctl.d/10-truenas.conf
Commit 3b9b1c76032a3f50053fce3c8255f178e4ba3c34 subtly broke users who depend on SLAAC related functionality. When ipv6 was enabled, it causes the net.ipv6.conf.*.forwarding sysctl to get set to 1 on _ALL_ interfaces on the host. This causes the kernel to ignore any router advertisements on those interfaces because it treats the host as a "router". To fix this problem we need to set `accept_ra=2` which will tell the kernel to accept RA's on interfaces when forwarding=1.
> NAS-135715 / 25.10 / default accept_ra sysctl to 2

- src/freenas/etc/sysctl.d/10-truenas.conf
Commit 3b9b1c76032a3f50053fce3c8255f178e4ba3c34 subtly broke users who depend on SLAAC related functionality. When ipv6 was enabled, it causes the net.ipv6.conf.*.forwarding sysctl to get set to 1 on _ALL_ interfaces on the host. This causes the kernel to ignore any router advertisements on those interfaces because it treats the host as a "router". To fix this problem we need to set `accept_ra=2` which will tell the kernel to accept RA's on interfaces when forwarding=1.
Original PR: https://github.com/truenas/middleware/pull/16442
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135715
> NAS-135715 / 25.04.2 / default accept_ra sysctl to 2 (by yocalebo)

- src/middlewared/middlewared/utils/account/faillock.py
pam_faillock(8) creates its rundir on first authentication failure and so middleware doesn't need to create the directory. It is sufficient to treat non-existence as no users being locked.
> NAS-135758 / Skip faillock dir iteration if it doesn't exist

- src/middlewared/middlewared/utils/account/faillock.py
pam_faillock(8) creates its rundir on first authentication failure and so middleware doesn't need to create the directory. It is sufficient to treat non-existence as no users being locked.
Original PR: https://github.com/truenas/middleware/pull/16446
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135758
> NAS-135758 / 25.04.2 / Skip faillock dir iteration if it doesn't exist (by anodos325)

- src/middlewared/middlewared/utils/account/faillock.py
pam_faillock(8) creates its rundir on first authentication failure and so middleware doesn't need to create the directory. It is sufficient to treat non-existence as no users being locked.
Original PR: https://github.com/truenas/middleware/pull/16446
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135758
> NAS-135758 / 25.04.1 / Skip faillock dir iteration if it doesn't exist (by anodos325)

- src/middlewared/middlewared/plugins/security/update.py
- src/middlewared/middlewared/utils/security.py
This commit adds requirement for a special character to the account password complexity ruleset for GPOS STIG per updated STIG runsheet.
> NAS-135761 / 25.10 / Update STIG password complexity ruleset

- src/middlewared/middlewared/plugins/security/update.py
- src/middlewared/middlewared/utils/security.py
This commit adds requirement for a special character to the account password complexity ruleset for GPOS STIG per updated STIG runsheet.
Original PR: https://github.com/truenas/middleware/pull/16454
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135761
> NAS-135761 / 25.04.2 / Update STIG password complexity ruleset (by anodos325)

- src/middlewared/middlewared/api/base/handler/model_provider.py
- src/middlewared/middlewared/api/base/handler/version.py
- src/middlewared/middlewared/main.py
Connecting to /websocket will attempt to use the 24.10 version of the API.
For all old versions of the API, we use factory functions to lazily load the version when it is needed. When a method model is not found in an older version (e.g. 24.10), we register it to the older version with a value of `None` since `None` is returned by this function when a `KeyError` is raised.
https://github.com/truenas/middleware/blob/accfe25027d247ab4e0cac2ba42a34eb6ca41972/src/middlewared/middlewared/main.py#L1385
The solution is to instead allow `KeyError` to propagate so that we make use of the `passthrough_nonexistent_methods` feature and use the most recent version of the method.
While here, I've also resolved a related FIXME comment and added more type hints. …
> NAS-135643 / 25.10 / Fix API calls when connected to /websocket

- src/middlewared/debian/control
Nightly builds are failing because of this comment line.
> NAS-135788 / 25.10 / remove comment from debian/control

- src/middlewared/middlewared/plugins/ldap.py
- src/middlewared/middlewared/plugins/ldap_/ldap_client.py
This commit fixes a longstanding validation bug in mutual tls authentication for the LDAP plugin. Tests will be added once CI pipeline added with this authentication type and an LDAP identity provider. This commit is not targeted for master since the underlying fix will be rolled into the overall larger rewrite project.
> NAS-135792 / 25.04.2 / Fix mutual TLS authentication for LDAP

- src/middlewared/middlewared/plugins/account.py
- src/middlewared/middlewared/plugins/account_/constants.py
- src/middlewared/middlewared/plugins/iscsi_/targets.py
- src/middlewared/middlewared/plugins/nvmet/namespace.py
- src/middlewared/middlewared/utils/reserved_ids.py
- tests/unit/test_reserved_ids.py
This commit changes the behavior of get_next_uid and get_next_gid such that we keep track of uids/gids handed out by this endpoint and prevent them from being reused in concurrent calls. These reservations of uid / gids time out after one hour.
During investigation it was discovered that additional simpler toctou issues existed related to iscsi.target and nvmet namespaces. These ones were remedied by adding locking.
> NAS-135784 / 25.10 / Avoid TOCTOU issues in account and iscsi.target

- src/middlewared/middlewared/plugins/account.py
- src/middlewared/middlewared/plugins/account_/constants.py
- src/middlewared/middlewared/plugins/iscsi_/targets.py
- src/middlewared/middlewared/utils/reserved_ids.py
- tests/unit/test_reserved_ids.py
This commit changes the behavior of get_next_uid and get_next_gid such that we keep track of uids/gids handed out by this endpoint and prevent them from being reused in concurrent calls. These reservations of uid / gids time out after one hour.
During investigation it was discovered that additional simpler toctou issues existed related to iscsi.target and nvmet namespaces. These ones were remedied by adding locking.
Original PR: https://github.com/truenas/middleware/pull/16460
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135784
> NAS-135784 / 25.04.2 / Avoid TOCTOU issues in account and iscsi.target (by anodos325)

- src/middlewared/middlewared/plugins/network.py
5 years ago in 4b8186fd4f0181a8406b19fccc55da22f126b309 a check was removed to allow `interface.delete` for physical interfaces. This was fine at the time, but it has exposed issues with how we currently do HA.
This is the following scenario that this fixes:
1. create vlan1 with parent (physical) interface of ens1
2. give vlan1 ip address information
3. HA is healthy and functional
4. delete ens1 from UI
5. network_vlan table removes entry
6. network_interface leaves a vlan1 entry in network_interface table
7. keepalived.conf gets generated with an invalid config which prevents `keepalived` service from running, which, ultimately causes failover and/or HA to go completely down
To remedy the above situation, we ensure that any interface being deleted that has a vlan on top of it will raise …
> NAS-135767 / 25.10 / fix leaving stale db entries on interface delete

- src/middlewared/middlewared/plugins/network.py
5 years ago in 4b8186fd4f0181a8406b19fccc55da22f126b309 a check was removed to allow `interface.delete` for physical interfaces. This was fine at the time, but it has exposed issues with how we currently do HA.
This is the following scenario that this fixes:
1. create vlan1 with parent (physical) interface of ens1
2. give vlan1 ip address information
3. HA is healthy and functional
4. delete ens1 from UI
5. network_vlan table removes entry
6. network_interface leaves a vlan1 entry in network_interface table
7. keepalived.conf gets generated with an invalid config which prevents `keepalived` service from running, which, ultimately causes failover and/or HA to go completely down
To remedy the above situation, we ensure that any interface being deleted that has a vlan on top of it will raise …
> NAS-135767 / 25.04.1 / fix leaving stale db entries on interface delete (by yocalebo)

- tests/unit/test_get_disks.py
This assert statement will never be true because the `disk.size_bytes` is the total disk size in bytes. The right operand of the assert is the partition size in bytes. We already have sufficient checks with the 2x assert statements before.
> NAS-135799 / 25.10 / fix unit test

- tests/protocols/iscsi_proto.py
Modern `cython` changes how `cpdef enum`s are exposed.  Update the tests so that they will work with **both** old and new cython.
Given
```
cpdef enum iscsi_session_type:
ISCSI_SESSION_DISCOVERY
ISCSI_SESSION_NORMAL
```
We used to be able to _**either**_ use `iscsi.ISCSI_SESSION_NORMAL` or `iscsi.iscsi_session_type.ISCSI_SESSION_NORMAL`.  With modern cython, only the latter works.
From https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#structs-unions-enums
> Up to Cython version 3.0.x, this used to copy all item names into the global module namespace, so that they were available both as attributes of the Python enum type (CheseState above) and as global constants. This was changed in Cython 3.1 to distinguish between anonymous cpdef enums, which only create global …
> NAS-135814 / 25.10 / Fix iscsi enum use for modern cython

- tests/protocols/iscsi_proto.py
Modern `cython` changes how `cpdef enum`s are exposed.  Update the tests so that they will work with **both** old and new cython.
Given
```
cpdef enum iscsi_session_type:
ISCSI_SESSION_DISCOVERY
ISCSI_SESSION_NORMAL
```
We used to be able to _**either**_ use `iscsi.ISCSI_SESSION_NORMAL` or `iscsi.iscsi_session_type.ISCSI_SESSION_NORMAL`.  With modern cython, only the latter works.
From https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#structs-unions-enums
> Up to Cython version 3.0.x, this used to copy all item names into the global module namespace, so that they were available both as attributes of the Python enum type (CheseState above) and as global constants. This was changed in Cython 3.1 to distinguish between anonymous cpdef enums, which only create global …
> NAS-135814 / 25.04.1 / Fix iscsi enum use for modern cython (by bmeagherix)

- tests/protocols/iscsi_proto.py
Modern `cython` changes how `cpdef enum`s are exposed.  Update the tests so that they will work with **both** old and new cython.
Given
```
cpdef enum iscsi_session_type:
ISCSI_SESSION_DISCOVERY
ISCSI_SESSION_NORMAL
```
We used to be able to _**either**_ use `iscsi.ISCSI_SESSION_NORMAL` or `iscsi.iscsi_session_type.ISCSI_SESSION_NORMAL`.  With modern cython, only the latter works.
From https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#structs-unions-enums
> Up to Cython version 3.0.x, this used to copy all item names into the global module namespace, so that they were available both as attributes of the Python enum type (CheseState above) and as global constants. This was changed in Cython 3.1 to distinguish between anonymous cpdef enums, which only create global …
> NAS-135814 / 25.04.2 / Fix iscsi enum use for modern cython (by bmeagherix)

- src/middlewared/middlewared/api/v25_10_0/nvmet_host.py
- src/middlewared/middlewared/plugins/nvmet/host.py
- tests/api2/test_nvmet_tcp.py
- Add `nvmet.host.dhchap_dhgroup_choices` and `nvmet.host.dhchap_hash_choices` APIs
- Add nvmet CI
- `test__host_dhchap_dhgroup_choices`
- `test__host_dhchap_hash_choices`
----
(Tested locally.)
> NAS-135828 / 25.10 / Add dhchap_dhgroup_choices and dhchap_hash_choices APIs

- src/middlewared/middlewared/api/v25_04_2/common.py
The query options should be properly documentated in API query methods.
Original PR: https://github.com/truenas/middleware/pull/16489
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135846
> NAS-135846 / 25.04.2 / Improve query-options documentation (by anodos325)

- tests/api2/test_virt_storage_pool.py
Recent changes have made the attachment delegate name a constant value. This has caused some integration tests, which were dependent on the previous dynamic naming behaviour, to fail.
Update and fix the affected integration tests to align with the new behaviour where the delegate name is constant.
> NAS-135850 / 25.10 / Fix virt integration tests

- tests/unit/test_virt_utils.py
Change import of 'Status' to 'VirtGlobalStatus'.
This was blocking the Goldeye unit test runs.  Do not backport.
This commit is the source: https://github.com/truenas/middleware/pull/16467
> NAS-135878 / 25.10 / Fix test_virt_utils

- tests/api2/test_zpool_capacity_alert.py
Recent changes rendered these tests incorrect so this updates them to be inline with current logic.
> NAS-135884 / 25.10 / fix zpool capacity tests

- tests/api2/test_zpool_capacity_alert.py
Recent changes rendered these tests incorrect so this updates them to be inline with current logic.
Original PR: https://github.com/truenas/middleware/pull/16501
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135884
> NAS-135884 / 25.04.2 / fix zpool capacity tests (by yocalebo)

- src/middlewared/middlewared/plugins/filesystem.py
- src/middlewared/middlewared/utils/mount.py
This commit adds changes to gracefully handle the case when we are missing a required separator in mount info line.
Basically what happened is that it seems on boot after upgrade for this user (we saw an earlier ticket as well with the same issue), somewhere a call to `catalog.config` was called. Now this call made use of `filesystem.mountinfo` which was using `getmntinfo` call.
The function `getmntinfo` raised an `IndexError` (more on this later), which was propagated above to
```
@private
async def _get_or_insert(self, datastore, options):
try:
return await self.middleware.call('datastore.config', datastore, options)
except IndexError:
async with get_or_insert_lock:
try:
return await self.middleware.call('datastore.config', datastore, options)
except IndexError:
await …
```
> NAS-135584 / 25.10 / Gracefully handle edge case when we are missing separator

- src/middlewared/middlewared/plugins/filesystem.py
- src/middlewared/middlewared/utils/mount.py
This commit adds changes to gracefully handle the case when we are missing a required separator in mount info line.
Basically what happened is that it seems on boot after upgrade for this user (we saw an earlier ticket as well with the same issue), somewhere a call to `catalog.config` was called. Now this call made use of `filesystem.mountinfo` which was using `getmntinfo` call.
The function `getmntinfo` raised an `IndexError` (more on this later), which was propagated above to
```
@private
async def _get_or_insert(self, datastore, options):
try:
return await self.middleware.call('datastore.config', datastore, options)
except IndexError:
async with get_or_insert_lock:
try:
return await self.middleware.call('datastore.config', datastore, options)
except IndexError:
await …
```
> NAS-135584 / 25.04.2 / Gracefully handle edge case when we are missing separator (by sonicaj)

- src/middlewared/middlewared/plugins/filesystem.py
- src/middlewared/middlewared/utils/mount.py
This commit adds changes to gracefully handle the case when we are missing a required separator in mount info line.
Basically what happened is that it seems on boot after upgrade for this user (we saw an earlier ticket as well with the same issue), somewhere a call to `catalog.config` was called. Now this call made use of `filesystem.mountinfo` which was using `getmntinfo` call.
The function `getmntinfo` raised an `IndexError` (more on this later), which was propagated above to
```
@private
async def _get_or_insert(self, datastore, options):
try:
return await self.middleware.call('datastore.config', datastore, options)
except IndexError:
async with get_or_insert_lock:
try:
return await self.middleware.call('datastore.config', datastore, options)
except IndexError:
await …
```
> NAS-135584 / 25.04.1 / Gracefully handle edge case when we are missing separator (by sonicaj) (by bugclerk)

- src/middlewared/middlewared/api/v25_10_0/virt_device.py
- src/middlewared/middlewared/plugins/virt/instance.py
- src/middlewared/middlewared/plugins/virt/instance_device.py
- src/middlewared/middlewared/plugins/virt/utils.py
- tests/api2/test_virt_vm.py
Currently users need to repack windows iso because it is not supported out of the box by incus as there are missing drivers.
While this gets fixed upstream, we have decided to use `raw.qemu` and specify relevant CDROM directly so it works as expected with windows. However while doing this, we see boot priority does not take effect for CDROM entry as incus first initiates qemu process with qemu cmd where this CDROM entry is specified and then using QMP, it dynamically handles devices for the virt instance which overrides boot entry. So to get that to work, we still need to specify the CDROM as a disk device in incus and everything else falls into place nicely. It has been confirmed that this works as expected with windows and that it boots nicely.
> NAS-134791 / 25.10 / Add CDROM device type

- src/middlewared/middlewared/alembic/versions/25.10/2025-05-16_15-58_nvmet_trsvcid.py
- src/middlewared/middlewared/api/v25_10_0/nvmet_port.py
- src/middlewared/middlewared/plugins/nvmet/port.py
Allow `addr_trsvcid` to be `None` for FC transport.
> NAS-135892 / 25.10 / Allow addr_trsvcid to be None for FC transport

- src/middlewared/middlewared/utils/security.py
- tests/unit/test_shadow_account_policy.py
When user passwords are disabled the user can no longer manage password change requirements or any password policy restrictions.  Under certain configurations, e.g. STIG, this can lead to the user account being disabled.   We want to avoid this condition.
The fix for this is to special case the user shadow entry to disable all expiration type settings when the user has password authentication disabled.
The shadow entry for a password disabled user will be `*:::::::`. This will prevent the user getting disabled due to password requirements.
Also added a CI unit test.
Also fixed a small error in the unit test.  Reporting info on an assert was missing some data.
This fixes the issue raised in [NAS-135863](https://ixsystems.atlassian.net/browse/NAS-135863)
> NAS-135898 / 25.10 / Add special case handling of user password disable.

- src/middlewared/middlewared/utils/security.py
This call:
`return STIGType.GPOS if config['enable_gpos_stig'] else 0`
Generates this type check error:
`"Literal[0]" is not assignable to "STIGType"`
The fix:
Add the `0` case to STIGType class.
> NAS-135910 / 25.10 / Eliminate a type check error.

- src/middlewared/middlewared/utils/security.py
- tests/unit/test_shadow_account_policy.py
When user passwords are disabled the user can no longer manage password change requirements or any password policy restrictions.  Under certain configurations, e.g. STIG, this can lead to the user account being disabled.   We want to avoid this condition.
The fix for this is to special case the user shadow entry to disable all expiration type settings when the user has password authentication disabled.
The shadow entry for a password disabled user will be `*:::::::`. This will prevent the user getting disabled due to password requirements.
Also added a CI unit test.
Also fixed a small error in the unit test.  Reporting info on an assert was missing some data.
This fixes the issue raised in [NAS-135863](https://ixsystems.atlassian.net/browse/NAS-135863)
Original PR: …
> NAS-135898 / 25.04.2 / Add special case handling of user password disable. (by mgrimesix)

- src/middlewared/middlewared/utils/security.py
- tests/unit/test_shadow_account_policy.py
When user passwords are disabled the user can no longer manage password change requirements or any password policy restrictions.  Under certain configurations, e.g. STIG, this can lead to the user account being disabled.   We want to avoid this condition.
The fix for this is to special case the user shadow entry to disable all expiration type settings when the user has password authentication disabled.
The shadow entry for a password disabled user will be `*:::::::`. This will prevent the user getting disabled due to password requirements.
Also added a CI unit test.
Also fixed a small error in the unit test.  Reporting info on an assert was missing some data.
This fixes the issue raised in [NAS-135863](https://ixsystems.atlassian.net/browse/NAS-135863)
Original PR: …
> NAS-135898 / 25.04.1 / Add special case handling of user password disable. (by mgrimesix)

- src/middlewared/middlewared/api/v25_10_0/nvmet_subsys.py
- src/middlewared/middlewared/plugins/nvmet/subsys.py
- tests/api2/test_nvmet_tcp.py
This was requested by UI team to reduce the number of API calls they need to make.
- Add optional `options.extra.verbose` to `nvmet.subsys.query`
- Add `test__verbose_subsys_query`
(Tested locally.)
> NAS-135914 / 25.10 / Add options.extra.verbose support to nvmet.subsys.query

- src/middlewared/middlewared/api/base/decorator.py
- src/middlewared/middlewared/main.py
- src/middlewared/middlewared/service/base.py
- src/middlewared/middlewared/service/decorators.py
- src/middlewared/middlewared/utils/threading.py
This does a few things:
1. adds a thread local storage object to the threads in our thread pool
2. uses the newly added `truenas_pylibzfs` module to open a persistent handle and store it in the thread-local storage for the threads in our thread pool
3. adds a `pass_thread_local_storage` keyword argument to our `api_method` decorator as well as adds a standalone decorator called `@pass_thread_local_storage`.
4. adds a sub `Config` boolean attribute called `pass_thread_local_storage`
This is the beginning steps of removing our process pool in favor of using our thread pool for libzfs operations.
This behaves similar to how we decorate other methods or configure plugins in middleware. The design works as follows:
1. if the sub `Config` object of a plugin has the boolean attribute …
> NAS-135909 / 25.10 / add thread local storage to our thread pool

- src/middlewared/middlewared/pytest/unit/test_get_or_insert.py
- src/middlewared/middlewared/service/config_service.py
This PR adds changes to fix fragile behaviour of config method where what happens is that we try to see if a row exists in the config service table by selecting first index which if it does not exist will raise `IndexError` and in that case we used to insert a row in the database.
The problem with this logic is that if any service has an extend in place which also raises `IndexError` and is not caught will result in duplicate entry being created in the config service table as the code assumed `IndexError` was being originated because it had tried to select the first row whereas that was not the case.
Now we instead call `query` directly and get the first row like `get=True` was doing already in `datastore.config` method. This is safe in terms of that if the underlying service is doing …
> NAS-135886 / 25.04.1 / Fix fragile behavior of config method (by sonicaj)

- src/middlewared/middlewared/pytest/unit/test_get_or_insert.py
- src/middlewared/middlewared/service/config_service.py
This PR adds changes to fix fragile behaviour of config method where what happens is that we try to see if a row exists in the config service table by selecting first index which if it does not exist will raise `IndexError` and in that case we used to insert a row in the database.
The problem with this logic is that if any service has an extend in place which also raises `IndexError` and is not caught will result in duplicate entry being created in the config service table as the code assumed `IndexError` was being originated because it had tried to select the first row whereas that was not the case.
Now we instead call `query` directly and get the first row like `get=True` was doing already in `datastore.config` method. This is safe in terms of that if the underlying service is doing …
> NAS-135886 / 25.04.2 / Fix fragile behavior of config method (by sonicaj)

- src/middlewared/middlewared/api/base/decorator.py
- src/middlewared/middlewared/main.py
- src/middlewared/middlewared/schema/processor.py
- src/middlewared/middlewared/service/base.py
This removes the `pass_thread_local_storage` attribute from the `Config` sub-class object. It's not very conducive to proper API design with how it operates so we'll just mirror the `pass_app` functionality.
> NAS-135950 / 25.10 / remove pass_thread_local_storage attribute for sub-Config class

- src/middlewared/middlewared/plugins/account.py
- src/middlewared/middlewared/plugins/auth.py
- src/middlewared/middlewared/utils/account/authenticator.py
- src/middlewared/middlewared/utils/auth.py
- tests/unit/test_otpw_manager.py
- tests/unit/test_shadow_account_policy.py
- tests/unit/test_utmp.py
This commit fixes a usability issue with generating temporary passwords for user accounts while in STIG compatibility mode with a minimum password age set. There are various situations in which an account administrator may need to generate a password for users so that they can authenticate and then set their password and two-factor settings. When the OTPW has been generated in this manner, set a flag that is then used to bypass the minimum password age validation.
> NAS-135946 / 25.10 / Allow password aging bypass for admin OTPW

- src/middlewared/middlewared/plugins/account.py
- src/middlewared/middlewared/plugins/auth.py
- src/middlewared/middlewared/utils/account/authenticator.py
- src/middlewared/middlewared/utils/auth.py
- tests/unit/test_otpw_manager.py
- tests/unit/test_shadow_account_policy.py
- tests/unit/test_utmp.py
This commit fixes a usability issue with generating temporary passwords for user accounts while in STIG compatibility mode with a minimum password age set. There are various situations in which an account administrator may need to generate a password for users so that they can authenticate and then set their password and two-factor settings. When the OTPW has been generated in this manner, set a flag that is then used to bypass the minimum password age validation.
Original PR: https://github.com/truenas/middleware/pull/16529
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135946
> NAS-135946 / 25.04.2 / Allow password aging bypass for admin OTPW (by anodos325)

- src/middlewared/middlewared/plugins/account.py
- src/middlewared/middlewared/plugins/auth.py
- src/middlewared/middlewared/utils/account/authenticator.py
- src/middlewared/middlewared/utils/auth.py
- tests/unit/test_otpw_manager.py
- tests/unit/test_shadow_account_policy.py
- tests/unit/test_utmp.py
This commit fixes a usability issue with generating temporary passwords for user accounts while in STIG compatibility mode with a minimum password age set. There are various situations in which an account administrator may need to generate a password for users so that they can authenticate and then set their password and two-factor settings. When the OTPW has been generated in this manner, set a flag that is then used to bypass the minimum password age validation.
Original PR: https://github.com/truenas/middleware/pull/16529
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135946
> NAS-135946 / 25.04.1 / Allow password aging bypass for admin OTPW (by anodos325)

- src/middlewared/middlewared/plugins/service_/utils.py
Correct typo, change: 'SERVICES_WRITE' to 'SERVICE_WRITE'
[api](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4528/) and [unit](http://jenkins.eng.ixsystems.net:8080/job/tests/job/unit_tests/1401/) tests look good.
> NAS-135962 / 25.10 / Fix roles typo

- src/middlewared/middlewared/plugins/service_/utils.py
Correct typo, change: 'SERVICES_WRITE' to 'SERVICE_WRITE'
[api](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4528/) and [unit](http://jenkins.eng.ixsystems.net:8080/job/tests/job/unit_tests/1401/) tests look good.
Original PR: https://github.com/truenas/middleware/pull/16531
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135962
> NAS-135962 / 25.04.2 / Fix roles typo (by mgrimesix)

- src/middlewared/middlewared/api/base/jsonschema.py
- src/middlewared/middlewared/api/base/server/doc.py
The one-line fix makes it so that we are not updating `$def` in `replace_refs`.
(See ticket for the before picture)
> NAS-135959 / 25.10 / Fix API doc generation so that we recurse into nested objects

- src/middlewared/middlewared/api/base/jsonschema.py
- src/middlewared/middlewared/api/base/server/doc.py
The one-line fix makes it so that we are not updating `$def` in `replace_refs`.
(See ticket for the before picture)
Original PR: https://github.com/truenas/middleware/pull/16530
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135959
> NAS-135959 / 25.04.2 / Fix API doc generation so that we recurse into nested objects (by creatorcary)

- src/middlewared/middlewared/api/v25_10_0/acme_dns_authenticator.py
- src/middlewared/middlewared/api/v25_10_0/reporting_exporters.py
The leading underscore in these field names prevents them from being parsed into the API docs. Use aliases instead.
https://docs.pydantic.dev/latest/concepts/models/#private-model-attributes:~:text=Attributes%20whose%20name%20has%20a%20leading%20underscore%20are%20not%20treated%20as%20fields%20by%20Pydantic%2C%20and%20are%20not%20included%20in%20the%20model%20schema.
> NAS-135971 / 25.10 / Fix `_name_` and `_required_` not appearing in API docs

- src/middlewared/middlewared/plugins/sysdataset.py
- src/middlewared/middlewared/plugins/system_dataset/hierarchy.py
This non-standard permission was there since the plugin was written. It's probably something related to FreeBSD.
Linux has this directory set to `755` which causes `truenas_verify` to alert.
> NAS-135977 / 25.10 / Fix `/var/lib/systemd/coredump` permissions

- src/middlewared/middlewared/plugins/sysdataset.py
- src/middlewared/middlewared/plugins/system_dataset/hierarchy.py
This non-standard permission was there since the plugin was written. It's probably something related to FreeBSD.
Linux has this directory set to `755` which causes `truenas_verify` to alert.
Original PR: https://github.com/truenas/middleware/pull/16540
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135977
> NAS-135977 / 25.04.2 / Fix `/var/lib/systemd/coredump` permissions (by themylogin)

- src/middlewared/middlewared/plugins/security/update.py
- tests/api2/test_zzzz_stig.py
STIG requires two factor authentication.
This PR add validation of that requirement to enforce two factor authentication for SSH access in STIG mode.
Add CI test.
CI [test](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4547/)
Original PR: https://github.com/truenas/middleware/pull/16544
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135964
> NAS-135964 / 25.04.2 / Add STIG validation check for two factor authentication with SSH. (by mgrimesix)

- src/middlewared/middlewared/api/v25_10_0/common.py
- src/middlewared/middlewared/api/v25_10_0/nvmet_host_subsys.py
- src/middlewared/middlewared/api/v25_10_0/nvmet_namespace.py
- src/middlewared/middlewared/api/v25_10_0/nvmet_port_subsys.py
- src/middlewared/middlewared/plugins/datastore/filter.py
- src/middlewared/middlewared/plugins/datastore/read.py
- src/middlewared/middlewared/plugins/iscsi_/extents.py
- src/middlewared/middlewared/plugins/nvmet/constants.py
- src/middlewared/middlewared/plugins/nvmet/host.py
- src/middlewared/middlewared/plugins/nvmet/host_subsys.py
- src/middlewared/middlewared/plugins/nvmet/kernel.py
- src/middlewared/middlewared/plugins/nvmet/namespace.py
- src/middlewared/middlewared/plugins/nvmet/port.py
- src/middlewared/middlewared/plugins/nvmet/port_subsys.py
- src/middlewared/middlewared/plugins/nvmet/subsys.py
- src/middlewared/middlewared/pytest/unit/plugins/test_datastore.py
- src/middlewared/middlewared/service/base.py
- src/middlewared/middlewared/service/config_service.py
- src/middlewared/middlewared/service/crud_service.py
Several nvmet APIs are based on entities which include foreign keys.  Query results are **not** being properly exposed in the API.  Rectify for:
- `nvmet.host_subsys.query`
- `nvmet.port_subsys.query`
- `nvmet.namespace.query`
For example, prior to this change we could have a port (from `nvmet.port.query`):
```
[
{
"id": 26,
"index": 1,
"addr_trtype": "TCP",
"addr_trsvcid": 4420,
"addr_traddr": "192.168.56.115",
"addr_adrfam": "IPV4",
"inline_data_size": null,
"max_queue_size": null,
"pi_enable": null,
"enabled": true
}
]
```
that was being returned in `nvmet.port_subsys.query` as
```
[
{
"id": 43,
"port": {
"id": 26,
"nvmet_port_index": 1,
"nvmet_port_addr_trtype": 3,
"nvmet_port_addr_trsvcid": "4420",
"nvmet_port_addr_traddr": "192.168.56.115",
"nvmet_port_addr_adrfam": 1, …
```
> NAS-135940 / 25.10 / Update nvmet APIs to properly handle results wrt foreign keys

- src/middlewared/middlewared/plugins/idmap.py
- tests/api2/test_430_smb_sharesec.py
This commit fixes error handling on trying to retrieve SID information about local accounts that have been deleted. We were checking for ValidationErrors when it should have been ValidationError. CI test is added to ensure we don't regress again in future.
> NAS-135967 / 25.10 / Fix error handling for deleted local users

- src/middlewared/middlewared/plugins/idmap.py
- tests/api2/test_430_smb_sharesec.py
This commit fixes error handling on trying to retrieve SID information about local accounts that have been deleted. We were checking for ValidationErrors when it should have been ValidationError. CI test is added to ensure we don't regress again in future.
Original PR: https://github.com/truenas/middleware/pull/16548
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135967
> NAS-135967 / 25.04.2 / Fix error handling for deleted local users (by anodos325)

- src/middlewared/middlewared/plugins/truenas_connect/finalize_registration.py
- src/middlewared/middlewared/plugins/truenas_connect/heartbeat.py
- src/middlewared/middlewared/plugins/truenas_connect/utils.py
This PR implements faster retry attempts for TNC registration finalization as requested by the TNC team. The retry schedule now uses a 5-second base interval, resulting in attempts after 5s, 10s, 20s, 40s, etc., following an exponential backoff pattern for quicker recovery from transient failures.
> NAS-135619 / 25.10 / Have exponential time back-off for finalizing TNC registration

- src/middlewared/middlewared/etc_files/fips.py
- src/middlewared/middlewared/plugins/security/info.py
- src/middlewared/middlewared/plugins/security/update.py
- src/middlewared/middlewared/scripts/configure_fips.py
This will also lead to FIPS being configured on `failover.sync_from_peer`.
Additionally, add some logging to `configure_fips` to catch additional errors.
> NAS-135978 / 25.10 / Run `configure_fips` on config upload

- src/middlewared/middlewared/etc_files/fips.py
- src/middlewared/middlewared/plugins/security/info.py
- src/middlewared/middlewared/plugins/security/update.py
- src/middlewared/middlewared/scripts/configure_fips.py
This will also lead to FIPS being configured on `failover.sync_from_peer`.
Additionally, add some logging to `configure_fips` to catch additional errors.
Original PR: https://github.com/truenas/middleware/pull/16543
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135978
> NAS-135978 / 25.04.2 / Run `configure_fips` on config upload (by themylogin)

- src/middlewared/middlewared/alert/source/smb.py
Our webui does not display the alert title which renders the original alert for this mishap ambiguous to the end-user when viewed through the webui. This commit reworks the alert text to simplify the sentence syntax and clarify the nature of the issue.
> NAS-136070 / 25.10 / Improve alert text for SMB users missing passwords

- src/middlewared/middlewared/alert/source/smb.py
Our webui does not display the alert title which renders the original alert for this mishap ambiguous to the end-user when viewed through the webui. This commit reworks the alert text to simplify the sentence syntax and clarify the nature of the issue.
Original PR: https://github.com/truenas/middleware/pull/16561
Jira URL: https://ixsystems.atlassian.net/browse/NAS-136070
> NAS-136070 / 25.04.2 / Improve alert text for SMB users missing passwords (by anodos325)

- src/middlewared/middlewared/utils/account/authenticator.py
This flag should never be set for directory services accounts so that the UI team can properly rely on it for password reset prompts.
This commit fixes incorrect behavior introduced by fix for NAS-135946. NAS-135946 added the `PASSWORD_CHANGE_REQUIRED` flag unilaterally when OTPW generated by an administrator was created. This change allowed a limited bypass of password aging rules so that users could set new passwords.
> NAS-136079 / 25.10 / Fix setting PASSWORD_CHANGE_REQUIRED account attribute

- src/freenas/etc/pam.d/common-auth-unix
- src/middlewared/middlewared/etc_files/pam.d/common-auth-unix.mako
- src/middlewared/middlewared/etc_files/pam.d/common-auth.mako
- src/middlewared/middlewared/etc_files/pam.d/middleware-api-key.mako
- src/middlewared/middlewared/etc_files/pam.d/middleware.mako
- src/middlewared/middlewared/plugins/etc.py
- src/middlewared/middlewared/utils/pam.py
- tests/unit/test_utmp.py
This comit fixes several issues with pam_faillock configuration in the common-auth pam include file.
When pam_faillock is configured in common-auth and pam_oath is configured in the SSH pam configuration file, the pam_faillock sufficient control causes authentication to short-circuit potentially bypassing oath authentication.
This commit changes common-auth-unix file so that it is dynamically generated depending on whether pam_faillock is enabled. If pam_faillock is enabled, then the the pam_deny line is replaced with the pam_faillock failure line.
This commit changes the control directive for the pam_faillock success line so that it is no longer sufficient (avoiding the short-circuit).
Original PR: https://github.com/truenas/middleware/pull/16563
Jira URL: …
> NAS-136065 / 25.04.2 / Fix pam_faillock ordering (by anodos325)

- src/middlewared/middlewared/api/base/types/filesystem.py
- src/middlewared/middlewared/api/v25_10_0/nvmet_namespace.py
Normalize nvmet `device_path` for namespaces.
(Tested locally with `test_nvmet_tcp.py` CI tests.)
> NAS-136128 / 25.10 / Normalize nvmet device_path

- docs/source/middleware/roles.rst
- src/middlewared/middlewared/plugins/audit/audit.py
- src/middlewared/middlewared/plugins/disk_/info.py
- src/middlewared/middlewared/plugins/fc/fc.py
We still have one more use of `filterable` for `CRUDService.query`. This one will have to be handled in a larger PR.
> NAS-136147 / 25.10 / Remove almost all remaining `@filterable`s

- src/middlewared/middlewared/plugins/audit/audit.py
- src/middlewared/middlewared/plugins/pool_/dataset_details.py
- src/middlewared/middlewared/plugins/zfs_/utils.py
- src/middlewared/middlewared/pytest/unit/utils/test_mountinfo.py
- src/middlewared/middlewared/utils/mount.py
This commit fixes edge cases where incorrect mount info could be returned to some callers of getmntinfo when the server has bind mounts present. The mapping based on dev_t was kept originally for backwards-compatibility, but at this point it should just be removed to prevent incorrect usage.
> NAS-136151 / 25.10 / Default to building getmntinfo keyed by mount id

- src/middlewared/middlewared/etc_files/nfs.conf.mako
The default path for NFS rpc idmapd is `/var/lib/nfs/rpc_pipefs`.  We are overriding this in `nfs.conf` with the legacy setting `/run/rpc_pipefs`.
Using the legacy path with our startup process and Linux 6.12 has exposed a deficiency in using the transitory paths in the `/run` directory where the `idmap` daemon cannot start because the legacy path is not available.
The fix:
Use the default setting for `pipefs-directory`.
Tested manually.
Original PR: https://github.com/truenas/middleware/pull/16580
Jira URL: https://ixsystems.atlassian.net/browse/NAS-136149
> NAS-136149 / 25.04.2 / Use default for NFS RPC pipefs-directory (by mgrimesix)

- src/middlewared/middlewared/plugins/pool_/dataset.py
To try and fix the unhelpful validation error as described (and fixed in) cc12ccc9303bb1465930c7bacc2143bb3259ec06, this introduced an `IndexError` crash when someone tries to create a dataset when the parent dataset doesn't exist and `create_ancestors` isn't set to True....the _EXACT_ problem that the original commit set out to fix 🤦 . The current error message that gets raised is
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/pool_/dataset.py", line 480, in do_create
parent_ds = parent_ds[0]
~~~~~~~~~^^^
IndexError: list index out of range
```
The reason for this is that we're accessing the last element of the list instead of the first. The last element of the list is the zpool. This is how `get_dataset_parents` works so resolving the issue is simply accessing the first …
> NAS-136020 / 25.10 / fix IndexError in pool.dataset.create

- tests/api2/test_pool_dataset_create.py
This adds a test case for recent PR here: https://github.com/truenas/middleware/pull/16591. Passing test [here](https://github.com/truenas/middleware/pull/16591)
> NAS-136178 / 25.10 / add API test for non-existent parent ds

- src/middlewared/middlewared/alert/source/iscsi.py
- src/middlewared/middlewared/plugins/iscsi_/auth.py
- tests/api2/test_261_iscsi_cmd.py
Perform some fixup with iSCSI Authorized Access CHAP secrets
- Add `ISCSIAuthSecretAlertSource` to warn about existing bad secrets
- Enhance iSCSI auth `secret` and `peersecret` validation
- Add `test__auth_secret`
It was found that `scstadmin`/`scst `have problems with the `#` character and _some_ issues with whitespace (e.g. all whitespace secret).  We will warn users if they currently have such secrets configured and prevent them from being added going forward.
----
[CI run](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4641/): passing (wrt iSCSI)
> NAS-136132 / 25.10 / Perform some fixup with iSCSI Authorized Access CHAP secrets

- src/middlewared/middlewared/alert/source/iscsi.py
- src/middlewared/middlewared/plugins/iscsi_/auth.py
- tests/api2/test_261_iscsi_cmd.py
Perform some fixup with iSCSI Authorized Access CHAP secrets
- Add `ISCSIAuthSecretAlertSource` to warn about existing bad secrets
- Enhance iSCSI auth `secret` and `peersecret` validation
- Add `test__auth_secret`
It was found that `scstadmin`/`scst `have problems with the `#` character and _some_ issues with whitespace (e.g. all whitespace secret).  We will warn users if they currently have such secrets configured and prevent them from being added going forward.
----
[CI run](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4641/): passing (wrt iSCSI)
Original PR: https://github.com/truenas/middleware/pull/16585
Jira URL: https://ixsystems.atlassian.net/browse/NAS-136132
> NAS-136132 / 25.04.2 / Perform some fixup with iSCSI Authorized Access CHAP secrets (by bmeagherix)

- src/middlewared/middlewared/etc_files/proftpd/proftpd.conf.mako
- src/middlewared/middlewared/plugins/directoryservices.py
- src/middlewared/middlewared/plugins/etc.py
- src/middlewared/middlewared/utils/directoryservices/constants.py
Active Directory users are not able to authenticate via the FTP protocol. 
This PR fixes that with a configuration change in the `proftpd.conf` file when a directory service is enabled.
This has been manually tested against an AD server. 
```
grimes@debianix:~/scale-repos/middleware.generic$ ftp MCGDOMAIN\\ftpuser@192.168.45.154
Connected to 192.168.45.154.
220 ProFTPD Server (tnge-hv-ftp FTP Server) [::ffff:192.168.45.154]
331 Password required for MCGDOMAIN\ftpuser
Password:
230-Welcome to TrueNAS FTP Server
230 User MCGDOMAIN\ftpuser logged in
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> quit
421 No transfer timeout (300 seconds): closing control connection
```
---------------------------------------
Testing against a FreeIPA server and CI tests will be …
> NAS-135200 / 25.10 / Add support for directory services authentication for FTP.

- src/middlewared/middlewared/utils/directoryservices/credential.py
If the configuration doesn't have an explicit realm defined, we fallback to what is set as configuration->domain. This must be forced to uppercase (because IPA realms are uppercase).
> NAS-136203 / 25.10 / Force fallback realm info for IPA to upper case

- src/middlewared/middlewared/plugins/pool_/dataset_quota.py
I made a change in our new libzfs module here https://github.com/truenas/truenas_pylibzfs/pull/74 whereby it changed the ZFSProperty's enum field names to match the upstream zfs property name. The USEDDS property was changed to USEDBYDATASET and so this fixes it which should resolve the API test failures.
> NAS-136212 / 25.10 / fix quota api tests

- tests/directory_services/conftest.py
- tests/stig/conftest.py
- tests/stig/test_01_stig.py
- tests/stig/test_02_openssl.py
We can re-enable these following the creation of our new STIG test pipeline.
Rather than being performed in tests, VM configuration will be done in `conftest.py` files for both stig and directory_services tests.
`tests/stig/conftest.py` mirrors `tests/directory_services/conftest.py`.
> NAS-136218 / 25.10 / Bring back STIG tests

- src/middlewared/middlewared/plugins/smb_/status.py
This commit makes smb.status and smb.session_count private temporarily to not block development effort for removing legacy filterable methods from the middleware schema.
> NAS-136257 / 25.10 / Remove legacy schema references in smb.status

- src/middlewared/middlewared/api/v25_10_0/docker.py
- src/middlewared/middlewared/plugins/docker/backup.py
- src/middlewared/middlewared/plugins/docker/backup_to_pool.py
- tests/api2/test_docker_backup.py
This PR adds changes to allow consumers to backup their app pool to a specific pool. This will ensure if another backup is triggered, we do not face any issues and the changes are incrementally applied (under the hood handled by replication).
> NAS-133982 / 25.10 / Allow backing up apps to a specific pool

- src/middlewared/middlewared/plugins/account.py
- tests/api2/test_account.py
Add validation to user update to prevent locking all admin user accounts.
The update to lock an admin user will be blocked if that user is the last remaining FULL_ADMIN user.
Passing CI test is [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4814/).
> NAS-136301 / 25.10 / Prevent admin user lockout

- src/middlewared/middlewared/api/v25_10_0/smb.py
This commit fixes some minor formatting / readability issues in the SMB share documentation for the share purpose by flagging the purpose names as code to avoid having underscores potentially interpreted as formatting characters.
> NAS-136378 / 25.10 / Improve formatting of share purpose in API docs

- src/middlewared/middlewared/plugins/auth.py
- tests/api2/test_auth_onetime.py
This is an enhancement requested by the UI team. If the current session is authenticated via a onetime password, adjust our available authentication mechanism choices for the *session* to exclude authentication tokens. This provides a hint to UI to not issue request to generate the token and allows code simplification.
> NAS-136328 / 25.10 / Remove TOKEN_PLAIN from auth mech choices for OTPW

- src/middlewared/middlewared/plugins/auth.py
- tests/api2/test_auth_onetime.py
This is an enhancement requested by the UI team. If the current session is authenticated via a onetime password, adjust our available authentication mechanism choices for the *session* to exclude authentication tokens. This provides a hint to UI to not issue request to generate the token and allows code simplification.
Original PR: https://github.com/truenas/middleware/pull/16636
> NAS-136328 / 25.04.2 / Remove TOKEN_PLAIN from auth mech choices for OTPW (by anodos325)

- src/middlewared/middlewared/plugins/pool_/dataset_processes.py
This addresses an issue reported by community member in the forums. os.stat("/proc/pid/fd") failed with PermissionError in case where pid was for nextcloud snap installed in Ubuntu container and readlink on fd was `/snap/nextcloud/48223/bin/run-httpd`. Suppressing the error in this situation is okay since the snap will always be installed in the root dataset of the container and so check for running containers is sufficient for our purposes of identifying in-use datasets.
> NAS-136392 / 25.10 / Do not crash in pool.dataset.processes on procfd EACCES

- src/middlewared/middlewared/plugins/nvmet/global.py
- tests/api2/test_nvmet_tcp.py
- Fix `nvmet.global.sessions` when service is not running
- Add `test__no_sessions_when_service_stopped`
- Add `test__global_sessions_loopback`
(Tested locally)
> NAS-136383 / 25.10 / Nvmet add global sessions test

- src/middlewared/middlewared/plugins/system/product.py
- src/middlewared/middlewared/plugins/truenas_connect/register.py
This PR adds changes to send available license string when drafting up registration URL of TNC. It is only done if the license is available and has not expired.
> NAS-136219 / 25.10 / Send license string to TNC on registration

- src/middlewared/middlewared/plugins/directoryservices_/activedirectory_join_mixin.py
This commit adds KRB5_FCC_NOFILE to the list of kerberos errors that we try to wait out when activating active directory. This error may occur if there's a race on keyring initialization. The second attempt will succeed and issue won't recur.
> NAS-136429 / 25.04.2 / Make KRB5_FCC_NOFILE nonfatal when trying to start AD

- src/middlewared/middlewared/alert/source/smb_recordsize.py
- src/middlewared/middlewared/plugins/smb.py
- src/middlewared/middlewared/plugins/smb_/constants.py
- src/middlewared/middlewared/plugins/smb_/util_smbconf.py
- tests/api2/test_smb_veeam_repo.py
This commit adds a new SMB share purpose of VEEAM_REPOSITORY_SHARE, which requires the ZFS recordsize to be set to 128 KiB (per guidance from Veeam) and sets the underlying SMB block size to 128 KiB so that FileFsSizeInformation the Sectors Per Allocation Unit is reported to Veeam Backup & Restore in such a way that it will use the correct offsets and lengths when it issues
FSCTL_DUPLICTE_EXTENTS_TO_FILE requests. If this is not done, then Fast Copy requests will be rejected by ZFS due to improper alignment and ZFS will fallback to doing an internal copy of the specified range.
Original PR: https://github.com/truenas/middleware/pull/16635
> NAS-135244 / 25.04.2 / Fix configuration for SMB Veeam Fast Clone (by anodos325)

- src/middlewared/middlewared/plugins/account_/builtin_administrator.py
- tests/api2/test_group_utils.py
Allows users to be deleted or password to be disabled if another user exists with `builtin_administrators` either in its auxiliary groups or as its primary group.
> NAS-136296 / 25.10 / Consider primary group when checking for password-enabled users

- src/middlewared/middlewared/plugins/directoryservices_/util_cache.py
This commit skips NSS responses for users and groups when building the directory services cache if they are from a domain that does not have an explicit idmap configuration. This discourages administrators from relying on non-deterministic mappings for accounts and avoids crashing the cache build with a KeyError.
> NAS-136338 / 25.04.3 / Skip misconfigured idmap domains in DS cache

- docs/source/accounts/implementation.rst
- src/middlewared/middlewared/api/v25_10_0/group.py
- src/middlewared/middlewared/api/v25_10_0/user.py
- src/middlewared/middlewared/plugins/account.py
- src/middlewared/middlewared/plugins/directoryservices.py
- src/middlewared/middlewared/plugins/directoryservices_/cache.py
- src/middlewared/middlewared/plugins/directoryservices_/util_cache.py
- src/middlewared/middlewared/plugins/filesystem_/acl_template.py
- src/middlewared/middlewared/plugins/idmap.py
- src/middlewared/middlewared/plugins/smb_/groupmap.py
- src/middlewared/middlewared/pytest/unit/plugins/test_user_ssh_enabled_validation.py
- tests/directory_services/test_activedirectory_user_group_cache.py
- tests/unit/test_passdb.py
This commit removes the `id_type_both` key from user entries since we are not abstracting away this implementation detail from from the public API in SMB share ACL and other areas. A side-effect of this change is that idmap domain information no longer needs to be queried when generating AD cache (or passed to related functions). This commit also adds a version identifier to directory services caches so that we automatically invalidate them on middleware startup of the underlying TrueNAS version changed (this is because the fields for users can change between versions).
> NAS-136439 / 25.10 / Remove ID type both and version directory services cache

- src/middlewared/middlewared/plugins/service.py
Added auditing of service start, stop, reload and restart.
Manual spot testing to confirm function.
```
root@fangtooth-hv-nfs[~]# midclt call service.start nfs
True
root@fangtooth-hv-nfs[~]# midclt call service.reload nfs
True
root@fangtooth-hv-nfs[~]# midclt call service.restart nfs
True
root@fangtooth-hv-nfs[~]# midclt call service.stop nfs
True
root@fangtooth-hv-nfs[~]# midclt call audit.query '{"query-filters": [["event_data.method", "in", ["service.start","service.stop","service.reload","service.restart"]]], "query-options":{"select": ["event_data","success"]}}' | jq
[
{
"event_data": {
"method": "service.stop",
"params": [
"nfs"
],
"description": "Service: stop nfs",
"authenticated": true,
"authorized": true
},
"success": true
},
{
"event_data": {
"method": "service.start", …
```
> NAS-136310 / 25.04.3 / Add auditing for service start, stop, reload and restart.

- src/middlewared/middlewared/plugins/service.py
Added auditing of service start, stop, reload and restart.
Manual spot testing to confirm function.
```
root@fangtooth-hv-nfs[~]# midclt call service.start nfs
True
root@fangtooth-hv-nfs[~]# midclt call service.reload nfs
True
root@fangtooth-hv-nfs[~]# midclt call service.restart nfs
True
root@fangtooth-hv-nfs[~]# midclt call service.stop nfs
True
root@fangtooth-hv-nfs[~]# midclt call audit.query '{"query-filters": [["event_data.method", "in", ["service.start","service.stop","service.reload","service.restart"]]], "query-options":{"select": ["event_data","success"]}}' | jq
[
{
"event_data": {
"method": "service.stop",
"params": [
"nfs"
],
"description": "Service: stop nfs",
"authenticated": true,
"authorized": true
},
"success": true
},
{
"event_data": {
"method": "service.start", …
```
> NAS-136310 / 25.04.2 / Add auditing for service start, stop, reload and restart. (by mgrimesix)

- src/middlewared/middlewared/plugins/service.py
- tests/api2/test_audit_service.py
Add auditing of the middleware `service.control` method.
This PR includes a CI test module.
CI test run is [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4916/).
> NAS-136452 / 25.10 / Add auditing of service.control.

- src/middlewared/middlewared/api/base/handler/inspect.py
- src/middlewared/middlewared/api/base/handler/model_provider.py
- src/middlewared/middlewared/api/base/handler/version.py
- src/middlewared/middlewared/api/base/server/doc.py
- src/middlewared/middlewared/api/base/server/legacy_api_method.py
- src/middlewared/middlewared/api/base/server/method.py
- src/middlewared/middlewared/apps/websocket_app.py
- src/middlewared/middlewared/main.py
- src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_nested_model.py
- src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_nested_model_list.py
- src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_or.py
- src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_union.py
- src/middlewared/middlewared/service/base.py
- src/middlewared/middlewared/service/compound_service.py
- src/middlewared/middlewared/service/decorators.py
- src/middlewared/middlewared/test/integration/utils/client.py
- tests/api2/test_legacy_api.py
- tests/conftest.py
A number of issues is being fixed here:
* ModuleModelProvider argument is module, but we pass a string. This results in the newest API version models not being loaded at all, and schema conversion not working.
* Only load API version if __init__.py exists (an empty directory of a nonexisting version might exist on the developers' machine as a result of mounting a git repo)
* Use _register_models of all the members of CompoundService (dynamically generated models were not registered)
* Test all this by just ensuring that user.query does not fail.
> NAS-136437 / 25.04.2 / Fix legacy API conversion

- src/middlewared/middlewared/etc_files/syslog-ng/syslog-ng.conf.mako
- tests/api2/test_475_syslog.py
Remote syslog supports single and mutual TLS authentication.
For single (one way) TLS: the client (TrueNAS server) needs only the ca directory configuration.
For mutual TLS: The TrueNAS server needs the CA directory that includes the syslog CA cert _and_ the syslog CA signed syslog client cert and key.
This PR:
- Remove 'revoked' check which was breaking the call.
- Refactored the remote syslog stanza to be more readable.
- Add TLS CI tests.  
Note: The CI tests are not end-to-end and validate the syslog-ng config file only.   The configuration _was_ tested manually.
Note: See [NAS-136443](https://ixsystems.atlassian.net/browse/NAS-136443).  Adding the CA cert must be done manually via the API (`midclt call certificate.create`)
CI [test …
> NAS-134598 / 25.10 / syslog single and mutual TLS

- src/middlewared/middlewared/api/base/handler/inspect.py
- src/middlewared/middlewared/api/base/handler/model_provider.py
- src/middlewared/middlewared/api/base/handler/version.py
- src/middlewared/middlewared/api/base/server/doc.py
- src/middlewared/middlewared/api/base/server/legacy_api_method.py
- src/middlewared/middlewared/api/base/server/method.py
- src/middlewared/middlewared/apps/websocket_app.py
- src/middlewared/middlewared/main.py
- src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_nested_model.py
- src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_nested_model_list.py
- src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_or.py
- src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_union.py
- src/middlewared/middlewared/service/base.py
- src/middlewared/middlewared/service/compound_service.py
- src/middlewared/middlewared/service/decorators.py
- tests/api2/test_legacy_api.py
- tests/conftest.py
git cherry-pick -x f7660aa21774721289a52a708135f5cf2d207682
git cherry-pick -x 32fe0bb58ac5b32a79f29ca7fd0420a175b69424
git cherry-pick -x da1810ef6e03181c7f3281206e2906468638714a
git cherry-pick -x 2c361259dbfb1bfe88bee4f49ddc01d9d35de635
git cherry-pick -x b4f6ac92c3f3eae2be2c6330845e05a4b2112b71
git cherry-pick -x 24ce28f85b9250e2bd6ac1ca05945c3cc4f60f74
git cherry-pick -x 5a586c0cb79563a39cf6acd972bd099f8f745f2e
git cherry-pick -x 7b77af7e65b103afd3d107534f4608a1343c1f40
A number of issues is being fixed here:
* ModuleModelProvider argument is module, but we pass a string. This …
> NAS-136437 / 25.10 / Fix legacy API conversion (by themylogin)

- src/middlewared/middlewared/plugins/device_/netlink_events.py
- tests/api2/test_ipaddress_change_events.py
This adds the ability to monitor for IP address changes using the netlink library. This isn't used anywhere yet, but subsequent PRs will make use of this functionality. I've also added tests. They are passing [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4948/testReport/api2/test_ipaddress_change_events/)
> NAS-136474 / 25.10 / use netlink to monitor for ip address changes

- src/middlewared/middlewared/plugins/docker/state_management.py
This PR adds changes where when a license is updated and apps are not supported, apps would still function unless a reboot was performed.
> NAS-136001 / 25.10 / Make sure an unlicensed system is not able to consume apps

- src/middlewared/middlewared/alembic/versions/25.10/2025-06-26_20-30_tnc_interfaces.py
- src/middlewared/middlewared/alembic/versions/25.10/2025-06-29_20-30_tnc_interfaces.py
- src/middlewared/middlewared/api/v25_10_0/interface.py
- src/middlewared/middlewared/api/v25_10_0/tn_connect.py
- src/middlewared/middlewared/plugins/network.py
- src/middlewared/middlewared/plugins/truenas_connect/hostname.py
- src/middlewared/middlewared/plugins/truenas_connect/update.py
- src/middlewared/middlewared/pytest/unit/plugins/test_interface_ip_in_use.py
- src/middlewared/middlewared/pytest/unit/plugins/test_truenas_connect.py
This PR adds changes to allow binding interfaces with truenas connect. Basically this will mean that users don't have to rely on specifying IPs which can change later on and rather we will use interfaces which are persistent and remain. 
To catch up to any ip changes on interfaces, we will be doing that in a subsequent PR.
> NAS-136426 / 25.10 / Allow specifying interfaces for TrueNAS connect

- src/middlewared/middlewared/test/integration/assets/ftp.py
- src/middlewared/middlewared/test/integration/assets/nfs.py
The previous refactor of these assets to use `service.control` instead of `service.start` | `service.stop` omitted setting `job=True` which could theoretically lead to races / bad test results.
> NAS-136525 / 25.10 / Fix service.control call in NFS and FTP test assets

- tests/runtest.py
- tests/sharing_protocols/conftest.py
The sharing protocol CI tests are being moved to subdirectories.
This PR fixes up `runtest.py` to support running the CI tests.
To run the tests:
`--test_dir sharing_protocols`
The results will be in `results/sharing_protocols_tests_result.xml
Also modified the pool create to use an existing pool.
> NAS-136554 / 25.10 / Fixup support for the sharing_protocol CI tests.

- tests/api2/test_261_iscsi_cmd.py
The test function `assert_validation_errors` was added to master in PR #16347, which was **not** backported to FT.
However, that function was then used in the tests for PR #16585 which **was** backported to FT.
Simplest & least intrusive fix is to just backport the test function, which is what this PR does.
Original PR: https://github.com/truenas/middleware/pull/16706
> NAS-136576 / 25.04.2 / Add missing assert_validation_errors (by bmeagherix)

- src/middlewared/middlewared/plugins/cloud_backup/sync.py
- tests/api2/test_cloud_backup.py
`--group-by` must be used, because otherwise snapshots are grouped by source dif, which is different every time
> NAS-136229 / 25.10 / Fix cloud backup snapshot pruning when snapshots are used

- src/middlewared/middlewared/alembic/versions/25.10/2025-07-08_23-27_tnc_use_all_interfaces.py
- src/middlewared/middlewared/api/v25_10_0/tn_connect.py
- src/middlewared/middlewared/plugins/truenas_connect/hostname.py
- src/middlewared/middlewared/plugins/truenas_connect/update.py
- src/middlewared/middlewared/pytest/unit/plugins/test_truenas_connect.py
This PR adds changes so by default TNC is configured with all the available interfaces on the system. What this means in practice is that whatever IPs we have configured on any interface, we will send them to TNC so their A records can be created appropriately unless user explicitly disables this with his/her own personal preference.
> NAS-136596 / 25.10 / Add automatic interface discovery for TrueNAS Connect

- src/middlewared/middlewared/plugins/update.py
- src/middlewared/middlewared/plugins/update_/install_linux.py
This commit fixes an issue where if scale build gives 100 or 96 percentage, we walk back from that figure when in middleware we send a subsequent event with 95 percentage. So in such cases, we max out the progress reported by scale build to 90 and then take it to completion in middleware.
Related to https://github.com/truenas/scale-build/pull/886
> NAS-136593 / 25.10 / Adjust job progress when applying update file

- src/middlewared/middlewared/plugins/virt/global.py
The `port_details` field in `port.ports_mapping` includes descriptions for all ports used by a service. Currently, the code retrieves and displays the descriptions of all ports without filtering for the specific port being used by the application.
Update the logic to filter and include only the description relevant to the specific port used by the application.
> NAS-136660 / 25.10 / Properly validate ports in virt plugin

- src/middlewared/middlewared/alembic/versions/25.10/2025-07-14_12-22_autorid-migration.py
- src/middlewared/middlewared/api/v25_10_0/directory_services.py
- src/middlewared/middlewared/plugins/directoryservices_/datastore.py
- src/middlewared/middlewared/plugins/idmap.py
- src/middlewared/middlewared/plugins/smb_/groupmap.py
- src/middlewared/middlewared/plugins/smb_/util_smbconf.py
- tests/directory_services/test_activedirectory_idmap.py
Historically our support team has pushed users to either use idmap_rid or idmap_ad (depending on domain configuration) in case with trusted domains we encourage users to separately configure idmap_rid or idmap_ad for each trusted domain. idmap_autorid is problematic when there are multiple truenas servers and multiple trusted domains because there is no guarantee that any particular server has the same idmap ranges configured as a different server.
Since we've been actively discouraging its use for many years now, it's probably better with other directory services redesign efforts in 25.10 to simply remove it as a choice.
> NAS-136630 / 25.10 / Remove idmap_autorid as a choice for idmap backends

- src/middlewared/middlewared/api/base/types/__init__.py
- src/middlewared/middlewared/api/base/types/nvmet.py
- src/middlewared/middlewared/api/v25_10_0/nvmet_global.py
- src/middlewared/middlewared/api/v25_10_0/nvmet_host.py
- src/middlewared/middlewared/api/v25_10_0/nvmet_subsys.py
- tests/api2/test_audit_nvmet.py
- tests/api2/test_nvmet_tcp.py
Add NQN type to API to perform better validation.
These changes were originally part PR #16562, but they are generally applicable.
----
Passing CI [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/5176/).
> NAS-136694 / 25.10 / Perform better NQN validation

- src/middlewared/middlewared/plugins/truenas_connect/register.py
This commit adds changes to generate a new claim token automatically for TNC if old one expired due to registration not being finalized.
> NAS-136698 / 25.10 / Generate a new claim token automatically for TNC

- src/middlewared/middlewared/plugins/truenas_connect/register.py
This commit fixes error code to raise EEXIST if claim token already exists and consumer tries to generate a new claim token.
> NAS-136703 / 25.10 / Fix error code if claim token already exists for TNC

- src/middlewared/middlewared/plugins/smb_/util_smbconf.py
- tests/unit/test_smb_share.py
This commit restores behavior in Electric Eel and Core where support for EAs over the SMB protocol was not advertised. These are different from alternate data streams and when they are enabled comprise a part of the basic file information, which incurs a significant impact on directory listing performance.
> NAS-136709 / 25.10 / Disable EA support on SMB shares

- src/middlewared/middlewared/api/v25_10_0/certificate.py
- src/middlewared/middlewared/plugins/apps/resources.py
- src/middlewared/middlewared/plugins/crypto_/certificates.py
- src/middlewared/middlewared/plugins/crypto_/query_utils.py
- src/middlewared/middlewared/plugins/directoryservices_/datastore.py
- src/middlewared/middlewared/plugins/system_advanced/syslog.py
- src/middlewared/middlewared/plugins/system_general/ui.py
This PR adds changes to make sure that we flag certs which are CAs and secondly make sure that when we present choices for different services we have, we don't show CA certs as valid in them. Lastly when we validate certs to be used with a service, we are also making sure that the cert in question is not a CA
> NAS-136683 / 25.10 / Make sure we don't present a CA cert as a valid option for different services

- src/middlewared/middlewared/plugins/docker/state_management.py
`handle_license_update` had an invalid (and unnecessary) parameter: `prev_product_type`.  Introduced in PR #16687
```
[2025/07/16 09:13:01] (ERROR) middlewared._call_hook_base():622 - Failed to run hook system.post_license_update:<function handle_license_update at 0x7fef993f9800>(*(), **{'prev_license': None}) @cee:{"TNLOG": {"exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/dist-packages/middlewared/main.py\", line 613, in _call_hook_base\n    fut = hook['method'](self, *args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: handle_license_update() missing 1 required positional argument: 'prev_product_type'", "type": "PYTHON_EXCEPTION", "time": "2025-07-16 16:13:01.626732"}}
```
> NAS-136734 / 25.10 / Fix handle license update

- src/middlewared/middlewared/etc_files/cron.d/middlewared.mako
- src/middlewared/middlewared/plugins/directoryservices.py
- src/middlewared/middlewared/plugins/directoryservices_/cache.py
- src/middlewared/middlewared/plugins/directoryservices_/datastore.py
- src/middlewared/middlewared/plugins/directoryservices_/secrets.py
- src/middlewared/middlewared/plugins/directoryservices_/util_cache.py
- src/middlewared/middlewared/plugins/kerberos.py
- src/middlewared/middlewared/plugins/sysdataset.py
- src/middlewared/middlewared/plugins/system_dataset/hierarchy.py
- src/middlewared/middlewared/utils/tdb.py
- tests/directory_services/test_activedirectory_user_group_cache.py
This commit shifts the directory services cache files to the system dataset and adds an expiration key to the caches so that middleware can be more intelligent about whether to attempt to rebuild the cache.
This happens in one of the following circumstances:
1. User initiates cache rebuild
2. User just joined a directory service
3. Cronjob issues cache refresh per crontab
The ultimate effect is that `directoryservices.setup` during a failover event to become active will no longer trigger an expensive cache rebuild and put unnecessary load on winbindd or sssd.
> NAS-136094 / 25.10 / Avoid unnecessary cache refresh on failover events

- src/middlewared/middlewared/plugins/directoryservices_/health.py
- src/middlewared/middlewared/utils/directoryservices/health.py
This commit expands the situations in which middleware sends `directoryservices.status` so that one is sent every time the health state is updated. This includes disabling directory services and transitions from DISABLED -> JOINING -> HEALTHY or HEALTHY -> LEAVING -> DISABLED.
> NAS-136737 / 25.10 / Send directoryservices.status events more often

- src/middlewared/middlewared/plugins/audit/audit.py
- tests/api2/test_audit_basic.py
The audit dataset configuration changes need to be set on both controllers of an HA system.  
Added call to push configuration to the remote node if system is HA.
Added a CI test.
New CI test was tested on HA VM.
> NAS-135932 / 25.10 / Configure audit dataset on remote node

- src/middlewared/middlewared/api/v25_10_0/directory_services.py
- tests/directory_services/test_activedirectory_basic.py
This commit fixes handling for case where the directoryservices config has been reset. In this situation configuration will be None and service_type will be None.
> NAS-136753 / 25.10 / Fix model_validator for directoryservices entry

- src/middlewared/middlewared/plugins/smb_/util_smbconf.py
- tests/unit/test_smb_share.py
This commit restores behavior in Electric Eel and Core where support for EAs over the SMB protocol was not advertised. These are different from alternate data streams and when they are enabled comprise a part of the basic file information, which incurs a significant impact on directory listing performance.
> NAS-136709 / 25.04.2 / Disable EA support on SMB shares (#16741)

- src/middlewared/middlewared/plugins/auth.py
Depending on the middleware credential type, the PAM authenticator may need to take a global utmp lock while removing the record.
Original PR: https://github.com/truenas/middleware/pull/16772
> NAS-136762 / 25.04.2 / Avoid blocking main loop on session logout (by anodos325)

- src/middlewared/middlewared/plugins/docker/fs_manage.py
This commit fixes a bug where if a user rollsback to a TN version which does not has docker apps, ix-apps dataset mountpoint would be reset and it would get mounted under it's root dataset. In this case we would like to make sure that the mountpoint correctly reflects where we want ix-apps to be mounted.
> NAS-136696 / 25.10 / Ensure ix-apps is mounted at it's proper place

- src/middlewared/middlewared/utils/account/authenticator.py
During update.run we chroot into the squashfs filesystem to perform various operations. This causes attempts to generate python-pam handles to fail. Rather than trying to massage ctypes to find the libraries within the squashfs filesystem, we can just set the PAM_REF to None. The installer shouldn't create middleware pam handles and so this is a low-risk solution to the problem.
Original PR: https://github.com/truenas/middleware/pull/16778
> NAS-136773 / 25.04.2 / Fix broken upgrades due to ctypes failure (by anodos325)

- src/middlewared/middlewared/plugins/auth.py
Seems to be a reoccurring theme whereby HA is disabled and then both controllers are power cycled, rebooted, etc. When HA is disabled...failover will not work by design. It has been this way since the beginning. However, some changes to the UI login page have introduced a situation where the user is unable to login at all without any indication as to why (even if the credentials that are provided are valid).
This changes the logic to return REDIRECT _ONLY_ when HA is healthy and the user is trying to login to the standby controller. Otherwise, the login attempt will fall through like normal.
This shifts the responsibility of whether to continue the login process and show the web page contents back to the caller (local UI in this scenario).
Original PR: …
> NAS-136775 / 25.04.2 / fallthrough auth.login_ex on unhealthy HA (by yocalebo)

- src/middlewared/middlewared/api/v25_10_0/update.py
> NAS-136766 / 25.10 / Fix crash on `update.status` call

- src/middlewared/middlewared/etc_files/local/avahi/services/ADISK.service.py
- tests/api2/test_310_service_announcement.py
This commit fixes the filter that determines whether an SMB share needs an ADISK mDNS record.
> NAS-136782 / 25.10 / Fix filter for checking time machine share

- src/middlewared/middlewared/plugins/pool_/dataset_quota.py
Fixes https://github.com/truenas/middleware/pull/16745 which incorrectly set the name to the id in the case that name resolution fails. The return schema for `pool.dataset.get_quota` specifies string or null, and null is reserved specifically for this purpose according to the API docs.
> NAS-136814 / 25.10 / Fix `pool.dataset.get_quota` failing when the quota's user no longer exists

- src/middlewared/middlewared/alembic/versions/25.10/2025-07-23_16-49_iscsi_product_id.py
- src/middlewared/middlewared/api/v25_10_0/iscsi_extent.py
- src/middlewared/middlewared/etc_files/scst.conf.mako
- src/middlewared/middlewared/plugins/iscsi_/extents.py
- tests/sharing_protocols/iscsi/test_261_iscsi_cmd.py
For SCST extents allow `product_id` to be specified on a per-extent basis.  The default (None) will result in the existing "iSCSI Disk" being returned.
Parameterize `test__inquiry` to validate that the value is seen by clients.
----
CI with passing FC and iSCSI tests [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/sharing_protocols_tests/67/).
> NAS-132570 / 25.10 / Add product_id to iSCSI API

- src/freenas/usr/local/bin/nvmf-connect.sh
R60 has 128 cores, which causes it to request 128 I/O queues per controller. The ES24N remote accepts that full request without capping to the number it can actually support. However, ES24N only provides 896 total IO queues, which are exhausted after the seventh controller is added. Because ES24N does not dynamically reduce its queue allocation based on available resources, we have to restrict each controller to 16 queues. This change prevents “No QP” errors when populating all 24 slots
- Validated the scenario described in [NAS-136819](https://ixsystems.atlassian.net/browse/NAS-136819) by @jervin777.
- [Scale Build](http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/1336/).
Original PR: https://github.com/truenas/middleware/pull/16803
> NAS-136819 / 25.04.2 / Limit NVMe RDMA I/O queues to 16 for ES24N shelves (by ixhamza)

- src/middlewared/middlewared/etc_files/sssd/sssd.conf.mako
- src/middlewared/middlewared/plugins/directoryservices_/activedirectory_health_mixin.py
- src/middlewared/middlewared/plugins/directoryservices_/activedirectory_join_mixin.py
- src/middlewared/middlewared/plugins/directoryservices_/cache.py
- src/middlewared/middlewared/plugins/directoryservices_/connection.py
- src/middlewared/middlewared/plugins/directoryservices_/datastore.py
- src/middlewared/middlewared/plugins/directoryservices_/health.py
- src/middlewared/middlewared/plugins/failover_/event.py
- src/middlewared/middlewared/plugins/smb_/groupmap.py
- src/middlewared/middlewared/plugins/system_dataset/hierarchy.py
- src/middlewared/middlewared/test/integration/assets/directory_service.py
- src/middlewared/middlewared/test/integration/utils/failover.py
- src/middlewared/middlewared/test/integration/utils/ha.py
- src/middlewared/middlewared/utils/directoryservices/common.py
- src/middlewared/middlewared/utils/directoryservices/krb5.py
- src/middlewared/middlewared/utils/gencache.py
- tests/directory_services/test_zzz_truenas_ha.py
In 25.10 the design for how directory services integrate with HA
was changed in such a way that it is now expected that the 
connection should be healthy on both the active and standby controller.
This is to provide consistent access on both storage controllers regardless
of HA state. During abusive testing multiple issues were discovered.
* Add explicit failover tests for directory services
- Add a new test asset to initiate a failover event and wait for
standby to settle.
- Fix multiple issues with existing failvoer test asset
"wait_for_standby"
* Shift the location of the directory services KDC affinity cache
In a multi-DC environment the standby controller would not
properly become healthy because it failed to communicate with
the correct KDC immediately after domain join.
* Add …
> NAS-136770 / 25.10 / Fix multiple failover issues with directory services

- src/middlewared/middlewared/plugins/jbof/crud.py
Found that on certain non-HA systems there could be a race condition that caused JBOF to not attach on boot.
> NAS-136834 / 25.10 / Avoid possible module load race condition

- src/middlewared/middlewared/plugins/truenas_connect/post_install.py
This commit fixes an issue where on post install, we tried to sync hostname ips with TNC which failed because post install workflow gets executed as soon as middleware boots which means we don't have access to networking at that moment. So for first sync, let's sync ips after a 5 minute delay which should be fine. We already sync ips on networking events, but as a good measure we can do it once post install after approximately 5 minutes.
> NAS-136804 / 25.10 / Handle post install ip syncing correctly

- src/middlewared/middlewared/plugins/vm/pci.py
- src/middlewared/middlewared/pytest/unit/plugins/test_gpu_critical.py
- src/middlewared/middlewared/pytest/unit/plugins/test_gpu_pci_structures.py
- src/middlewared/middlewared/pytest/unit/plugins/vm/test_passthrough_choices.py
- src/middlewared/middlewared/utils/gpu.py
- src/middlewared/middlewared/utils/iommu.py
- src/middlewared/middlewared/utils/pci.py
1. **GPUs incorrectly marked as critical**: PCI bridges were always considered critical devices. This caused GPUs to be marked as unavailable for passthrough when they shared an IOMMU group with a bridge, even if that bridge only connected to the GPU itself.
2. **Incomplete device lists**: The `devices` field only showed the GPU device, missing audio controllers and other devices that must be passed through together.
3. **Unclear error messages**: Critical reasons showed raw PCI addresses like "0000:00:1f.4" instead of human-readable descriptions like "SMBus (0000:00:1f.4)".
1. **Smart PCI bridge detection**: Bridges are now only marked critical if they have critical devices (Host bridge, SMBus, etc.) behind them. Bridges connecting only to GPUs are no longer considered critical.
2. …
> NAS-134926 / 25.10 / Fix GPU critical device detection logic and improve human-readable device descriptions

- tests/conftest.py
- tests/stig/test_01_stig.py
- tests/stig/test_02_openssl.py
STIG tests were failing consistently with HA in CI.  Rectify.
- Suppress calling private APIs when STIG is enabled (including in autouse fixtures)
- Be more intentional about waiting for long-running operations to complete (including 2 node reboots).
- Because of multiple reboots can no longer leverage websocket connection with unrestricted privileges 
----
Passing CI run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/stig_tests/256/).
> NAS-136579 / 25.10 / Fix STIG tests for HA

- src/middlewared/middlewared/plugins/directoryservices_/health.py
Active directory user oath configuration is keyed to the user SID value rather than being based on name, uid, or synthetic datastore IDs because all of the former are mutable. This means that if AD is broken when the users.oath file is generated then AD users will be omitted. When we transition from FAULTED to HEALTHY through directoryservices.health.recover we need to regenerate the users.oath file to properly resolve any directoryservices entries.
> NAS-136898 / 25.10 / Regenerate the users.oath file when DS becomes healthy

- src/middlewared/middlewared/restful.py
- src/middlewared/middlewared/test/integration/assets/api_key.py
- tests/api2/test_audit_rest.py
This commit uses the proper dumping function prior to sending audit messages related to REST calls.
> NAS-136910 / 25.10 / Properly dump REST API payload for audit insertion

- src/middlewared/middlewared/plugins/failover_/scheduled_reboot_alert.py
When middlware restarts after HA-related state transition from active to standby controller we generate an alert. This commit also adds a log message to the middleware log so that we have a clearer audit trail for when one of these special circumstances has occured.
> NAS-136932 / 25.10 / Add log entry to middleware log on HA reboot

- src/middlewared/middlewared/plugins/service_/services/pseudo/libvirtd.py
- src/middlewared/middlewared/plugins/vm/lifecycle.py
We are starting libvirt and it's related service in both controllers which should not be done and will cause other issues.
Original PR: https://github.com/truenas/middleware/pull/16830
> NAS-136922 / 25.04.2.1 / Fix libvirt service start in HA (by Qubad786)

- src/middlewared/middlewared/alert/source/smart.py
`passed` represents if the self-test well...passed. So the check should be the negation of it.
> NAS-136936 / 25.10 / fix smart selftest alert

- src/middlewared/middlewared/plugins/failover.py
On an internal system, an HA system was exposed to a network segmentation between the controllers. This caused both controllers to become MASTER. This caused a busy-loop of core.bulk service.restart calls to be sent back and forth to each controller endlessly. To remedy this situation I've added an extra check to ensure that `failover.disabled.reasons` needs to be empty before forwarding the remote call.
Original PR: https://github.com/truenas/middleware/pull/16836
Original PR: https://github.com/truenas/middleware/pull/16837
> NAS-136920 / 24.10.2.4 / fix busy loop on HA wrt to service.* actions (by yocalebo) (by bugclerk)

- src/middlewared/middlewared/plugins/service_/services/base.py
- src/middlewared/middlewared/plugins/service_/services/incus.py
Investigating the peculiar scenario outlined in https://github.com/truenas/middleware/pull/16836, I saw that the parent process was consuming ~19GB of resident memory. The loop was spinning running `core.bulk` api calls, more specifically `service.restart`. I created a very simple script that runs `service.restart <service>` in a `while True` loop. Monitoring the parent process in top, the resident memory would grow sporadically in chunks. A bit more investigation using `tracemalloc` and `resource` modules, I saw that there were some left-over references to objects from `pystemd` module. I found that upstream had a memory leak related to the `Unit` class but that was fixed back in 2018. I also confirmed that our version doesn't suffer from that memory leak but I was still suspicious.
I …
> NAS-136921 / 26.04 / plug a slow memory leak in service.* api

- src/middlewared/middlewared/plugins/service_/services/base.py
- src/middlewared/middlewared/plugins/service_/services/incus.py
Investigating the peculiar scenario outlined in https://github.com/truenas/middleware/pull/16836, I saw that the parent process was consuming ~19GB of resident memory. The loop was spinning running `core.bulk` api calls, more specifically `service.restart`. I created a very simple script that runs `service.restart <service>` in a `while True` loop. Monitoring the parent process in top, the resident memory would grow sporadically in chunks. A bit more investigation using `tracemalloc` and `resource` modules, I saw that there were some left-over references to objects from `pystemd` module. I found that upstream had a memory leak related to the `Unit` class but that was fixed back in 2018. I also confirmed that our version doesn't suffer from that memory leak but I was still suspicious.
I …
> NAS-136921 / 25.10-RC.1 / plug a slow memory leak in service.* api (by yocalebo)

- src/middlewared/middlewared/plugins/zfs/resource_crud.py
1. The pydantic model puts all the keys underneath the top-level `data` key. This doesn't show up because our tests go through the public API (`zfs.resource.query`) and pulling out the keys is handled via our `api_method` decorator
2. Move the try: catch: logic to the public API endpoint
> NAS-136974 / 26.04 / fix private zfs.resource.query_impl

- src/middlewared/middlewared/plugins/apps/ix_volumes.py
Now that we've branched we're able to start making changes like this. This marks the beginning of removing the calls to `zfs.dataset.query` which is still using our process pool. Using `zfs.resource.query_impl` uses our thread pool and our relatively newly minted libzfs C python library that we've been working on for a bit. The difference in speed is dramatic.
> NAS-136961 / 26.04 / remove zfs.dataset.query from apps/ix_volumes.py

- src/middlewared/middlewared/api/v26_04_0/zfs_resource_crud.py
- src/middlewared/middlewared/plugins/zfs/query_impl.py
1. the `exclude_json_schema` keyword argument does not hide this from API documentation so remove it since it has no harm in exposing it
2. add a private `raise_on_noent` keyword argument that can be passed to zfs.resource.query_impl. This will prevent an exception from being raised when some queries for a path that doesn't exist. This will be very important as we transition internal callers to this
> NAS-136979 / 26.04 / add raise_on_nonent to zfs.resource.query_impl

- src/middlewared/middlewared/api/base/model.py
- src/middlewared/middlewared/api/v26_04_0/acl.py
- src/middlewared/middlewared/api/v26_04_0/audit.py
- src/middlewared/middlewared/api/v26_04_0/iscsi_global.py
- src/middlewared/middlewared/api/v26_04_0/pool_dataset.py
- src/middlewared/middlewared/plugins/audit/audit.py
- src/middlewared/middlewared/plugins/filesystem.py
- src/middlewared/middlewared/plugins/iscsi_/global_linux.py
Some of our public endpoints fail if passed certain query options like "get" or "count" because the options are in the schema but the method doesn't support them. Some other endpoints do support the options, but the return schema doesn't reflect it. 
Apply case-by-case schema fixes to:
* `iscsi.global.sessions`
* `pool.dataset.get_quota`
* `audit.query`
* `audit.export`
* `filesystem.acltemplate.by_path`
http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/5426/
> NAS-136779 / 26.04 / Fix some query endpoints' options schemas

- src/middlewared/middlewared/api/v25_10_0/vm_device.py
- src/middlewared/setup.cfg
In older releases we allowed CDROM devices to live outside `/mnt` which is not ideal. However the problem we see right now is that if we validate this in the pydantic model itself, `vm.query` can fail which is not ideal.
We are already checking that the cdrom device is in a pool, so we don't have to do the same validation in pydantic.
> NAS-136989 / 25.10-RC.1 / Fix cdrom device path validation

- src/middlewared/middlewared/api/v25_10_0/vm_device.py
- src/middlewared/middlewared/api/v26_04_0/vm_device.py
- src/middlewared/setup.cfg
In older releases we allowed CDROM devices to live outside `/mnt` which is not ideal. However the problem we see right now is that if we validate this in the pydantic model itself, `vm.query` can fail which is not ideal.
We are already checking that the cdrom device is in a pool, so we don't have to do the same validation in pydantic.
Original PR: https://github.com/truenas/middleware/pull/16859
> NAS-136989 / 26.04 / Fix cdrom device path validation (by Qubad786)

- src/middlewared/middlewared/api/v25_10_0/vm_device.py
- src/middlewared/setup.cfg
In older releases we allowed CDROM devices to live outside `/mnt` which is not ideal. However the problem we see right now is that if we validate this in the pydantic model itself, `vm.query` can fail which is not ideal.
We are already checking that the cdrom device is in a pool, so we don't have to do the same validation in pydantic.
Original PR: https://github.com/truenas/middleware/pull/16859
> NAS-136989 / 25.10-BETA.1 / Fix cdrom device path validation (by Qubad786)

- src/middlewared/middlewared/etc_files/nsswitch.conf.mako
This commit ensures that directoryservices do not get inserted into the nsswitch.conf on standby controller if directoryservices are enabled. 25.04 and earlier expect the standby controller to not be fully configured for directory services and so we don't want NSS calls to potentially block on waiting for winbindd / sssd to bind to non-configured service. When vrrp_master gets called the nsswitch.conf is automatically reconfigured during a middleware call to directoryservices.setup.
> NAS-136994 / 25.04.2.1 / Do not configure directoryservices nsswitch on standby

- src/middlewared/middlewared/plugins/update_/status.py
We saw on a system that `update.status` returned the following output
```
{"code": "ERROR", "status": null, "error": "TypeError(\"'NoneType' object is not subscriptable\")", "update_download_progress": null}
```
Improve error reporting so we grab complete stack trace so we can at leave have more insight into what might have happened. Looking at the implementation itself, there is no obvious issue in the code semantics which could highlight this issue
> NAS-137006 / 26.04 / Properly grab update status error

- src/middlewared/middlewared/plugins/update_/status.py
We saw on a system that `update.status` returned the following output
```
{"code": "ERROR", "status": null, "error": "TypeError(\"'NoneType' object is not subscriptable\")", "update_download_progress": null}
```
Improve error reporting so we grab complete stack trace so we can at leave have more insight into what might have happened. Looking at the implementation itself, there is no obvious issue in the code semantics which could highlight this issue
Original PR: https://github.com/truenas/middleware/pull/16867
> NAS-137006 / 25.10-RC.1 / Properly grab update status error (by Qubad786)

- src/middlewared/middlewared/plugins/update_/status.py
We saw on a system that `update.status` returned the following output
```
{"code": "ERROR", "status": null, "error": "TypeError(\"'NoneType' object is not subscriptable\")", "update_download_progress": null}
```
Improve error reporting so we grab complete stack trace so we can at leave have more insight into what might have happened. Looking at the implementation itself, there is no obvious issue in the code semantics which could highlight this issue
Original PR: https://github.com/truenas/middleware/pull/16867
> NAS-137006 / 25.10-BETA.1 / Properly grab update status error (by Qubad786)

- src/middlewared/middlewared/api/base/server/ws_handler/rpc.py
- src/middlewared/middlewared/main.py
- src/middlewared/middlewared/plugins/audit/audit.py
- src/middlewared/middlewared/plugins/usage.py
- src/middlewared/middlewared/utils/origin.py
This PR adds changes so that we can have method usage stats in our usage plugin. This will give us something like the following:
```
❯ midclt call usage.gather_method_stats '{}' | jq
{
"method_stats": {
"core.set_options": 27,
"core.subscribe": 10,
"core.environ": 2,
"usage.gather_method_stats": 4,
"system.info": 1,
"usage.gather": 1
}
}
```
> NAS-136935 / 26.04 / Add method usage stats to usage plugin

- src/middlewared/middlewared/api/base/server/ws_handler/rpc.py
- src/middlewared/middlewared/main.py
- src/middlewared/middlewared/plugins/audit/audit.py
- src/middlewared/middlewared/plugins/usage.py
- src/middlewared/middlewared/utils/origin.py
This PR adds changes so that we can have method usage stats in our usage plugin. This will give us something like the following:
```
❯ midclt call usage.gather_method_stats '{}' | jq
{
"method_stats": {
"core.set_options": 27,
"core.subscribe": 10,
"core.environ": 2,
"usage.gather_method_stats": 4,
"system.info": 1,
"usage.gather": 1
}
}
```
Original PR: https://github.com/truenas/middleware/pull/16845
> NAS-136935 / 25.10-RC.1 / Add method usage stats to usage plugin (by sonicaj)

- src/middlewared/middlewared/api/base/server/ws_handler/rpc.py
- src/middlewared/middlewared/main.py
- src/middlewared/middlewared/plugins/audit/audit.py
- src/middlewared/middlewared/plugins/usage.py
- src/middlewared/middlewared/utils/origin.py
This PR adds changes so that we can have method usage stats in our usage plugin. This will give us something like the following:
```
❯ midclt call usage.gather_method_stats '{}' | jq
{
"method_stats": {
"core.set_options": 27,
"core.subscribe": 10,
"core.environ": 2,
"usage.gather_method_stats": 4,
"system.info": 1,
"usage.gather": 1
}
}
```
Original PR: https://github.com/truenas/middleware/pull/16845
> NAS-136935 / 25.10-BETA.1 / Add method usage stats to usage plugin (by sonicaj)

- src/middlewared/middlewared/api/v25_10_0/directory_services.py
- src/middlewared/middlewared/etc_files/local/openldap/ldap.conf.mako
- src/middlewared/middlewared/etc_files/sssd/sssd.conf.mako
- src/middlewared/middlewared/plugins/directoryservices_/cert_attachments.py
- src/middlewared/middlewared/plugins/directoryservices_/datastore.py
This commit fixes several bugs related to handling of MTLS certificates in the LDAP / SSSD config as well as the datastore plugin. CI tests will be added in separate PR once we have a google domain for jenkins testing.
Original PR: https://github.com/truenas/middleware/pull/16844
> NAS-136955 / 25.10-RC.1 / Fix validation and handling of MTLS cert for LDAP (by anodos325)

- src/middlewared/middlewared/api/v25_10_0/directory_services.py
- src/middlewared/middlewared/etc_files/local/openldap/ldap.conf.mako
- src/middlewared/middlewared/etc_files/sssd/sssd.conf.mako
- src/middlewared/middlewared/plugins/directoryservices_/cert_attachments.py
- src/middlewared/middlewared/plugins/directoryservices_/datastore.py
This commit fixes several bugs related to handling of MTLS certificates in the LDAP / SSSD config as well as the datastore plugin. CI tests will be added in separate PR once we have a google domain for jenkins testing.
Original PR: https://github.com/truenas/middleware/pull/16844
> NAS-136955 / 25.10-BETA.1 / Fix validation and handling of MTLS cert for LDAP (by anodos325)

- src/middlewared/middlewared/api/v26_04_0/directory_services.py
The PR to fix MTLS authentication included an API change, but it landed while we were in limbo of adding the new 26.04 APIs. This commit forward-ports the 25.10 API to 26.04 for this call.
> NAS-137015 / 26.04 / Fix API for directory services cert choices

- src/middlewared/middlewared/plugins/directoryservices_/health.py
When directory services recover from being in a FAULTED state, the dependent services such as SMB and NFS may need to be restarted in order to refresh caches / configuration and properly start serving files again.
Original PR: https://github.com/truenas/middleware/pull/16871
> NAS-137009 / 25.10-RC.1 / Restart services on becoming healthy (by anodos325)

- src/middlewared/middlewared/plugins/virt/global.py
- src/middlewared/middlewared/plugins/virt/instance.py
Now that we have VM plugin back, we do not want incus VMs to start automatically on boot as that can be problematic and if the same zvol is being used, can lead to corruption issues.
Make sure incus based VMs do not autostart on boot by filtering those out. However VMs created using early incus implementation, will still autostart (unless they have been modified at least once) because we were relying on incus to do that and as soon as incus starts it will start those automatically.
> NAS-136946 / 26.04 / Make sure incus VMs do not start automatically on boot

- src/middlewared/middlewared/plugins/account_/2fa.py
This commit removes the requirement for global 2FA to be disabled before unsetting a user's 2FA token. The reason to remove this is that otherwise there is no mechanism for a system administrator to completely remove 2FA for an existing user without toggling the global 2FA settings and downgrading system-wide security.
> NAS-137029 / 26.04 / Remove global 2fa check to unset 2FA token

- src/middlewared/middlewared/utils/nss/nss_common.py
This commit reduces the amount of dlopen during NSS calls (for example when building directory services caches) by lazy-initializing a cache containing references to the various NSS functions on a per-module basis (files, sss, winbind).
> NAS-137010 / 26.04 / Cache function pointers to nss module functions

- src/middlewared/middlewared/plugins/vm/info.py
- src/middlewared/middlewared/plugins/vm/pci.py
- src/middlewared/middlewared/plugins/vm/utils.py
We are retrieving CPU model choices from libvirt which means that when someone just navigates to VM creation wizard and UI calls cpu model choices endpoint, it ends up starting libvirt which is not ideal.
Retrieve information directly from filesystem like libvirt itself does so that we do not have to get that information from libvirt but rather the same files libvirt itself uses, thus preventing the need to start libvirt service when there is no VM created and only CPU model choices are required.
> NAS-136937 / 26.04 / Do not get CPU model choices from libvirt

- src/middlewared/middlewared/plugins/vm/info.py
- src/middlewared/middlewared/plugins/vm/pci.py
- src/middlewared/middlewared/plugins/vm/utils.py
We are retrieving CPU model choices from libvirt which means that when someone just navigates to VM creation wizard and UI calls cpu model choices endpoint, it ends up starting libvirt which is not ideal.
Retrieve information directly from filesystem like libvirt itself does so that we do not have to get that information from libvirt but rather the same files libvirt itself uses, thus preventing the need to start libvirt service when there is no VM created and only CPU model choices are required.
Original PR: https://github.com/truenas/middleware/pull/16901
> NAS-136937 / 25.10-RC.1 / Do not get CPU model choices from libvirt (by Qubad786)

- src/middlewared/middlewared/plugins/filesystem_/acl.py
This commit fixes enum reference for EVERYONE in payload in an error-related code path. In future commit I will change backend to be more aggressive about raising ValidationError if someone specifies username or groupname for special entries, since this is an invalid payload.
Original PR: https://github.com/truenas/middleware/pull/16909
> NAS-137050 / 25.10-RC.1 / Fix enum lookup for everyone@ (by anodos325)

- src/middlewared/middlewared/alembic/versions/25.10/2025-05-17_12-57_migrate-ds.py
This commit fixes an oversight in migration logic for legacy idmap domain extra options. The options need to be loaded prior to manipulation.
Original PR: https://github.com/truenas/middleware/pull/16908
> NAS-137049 / 25.10-BETA.1 / Properly handle old idmap domain options (by anodos325)

- tests/api2/test_legacy_api.py
zfs.resource.query only exists in >= 25.10
> NAS-137056 / 26.04 / fix legacy API client test

- tests/api2/test_pool_dataset_info.py
Add a CI test for `pool.filesystem_choices`
**`filesystem_choices` should:**
1. Never list the `boot-pool`, system datasets or datasets associated with apps.
2. List only filesystems if `FILESYSTEM` is requested
3. List only zvols if `VOLUME` is requested
Full run CI test passed.
`[2025-08-06 22:31:03] api2/test_pool_dataset_info.py::test_pool_filesystem_choices PASSED [ 80%]`
> NAS-137048 / 26.04 / Add CI test for pool.filesystem_choices

- src/middlewared/middlewared/plugins/usage.py
- src/middlewared/middlewared/plugins/zfs/query_impl.py
This does 3 things:
1. removes `zfs.dataset.query` in favor of `zfs.resource.query_impl`
2. removes the `snapshots_count` statistic. This was confirmed to not be used in our usage statistics.
3. adds a private `exclude_internal_paths` keyword argument that can be passed to `query_impl` _ONLY_ to allow the caller to query all zfs datasets, including the ones we hide from the public.
> NAS-137072 / 26.04 / remove zfs.dataset.query from usage.py

- src/middlewared/middlewared/plugins/sysdataset.py
Tests were failing here when trying to migrate system dataset to a root encrypted pool. This fixes it and resolve the test failures.
> NAS-137078 / 26.04 / fix another KeyEror in sysdataset.py

- src/middlewared/middlewared/alert/source/certificates.py
This commit adds changes to make sure that we only raise an alert that a cert is expiring if it is within it's renew days and still hasn't been renewed. For example if a cert is expiring on 10th, and renew days is 5, which means that system will start attempting to renew it from 5th. We will start raising an alert from 6th onwards as it shows that the system was not able to renew it successfully.
> NAS-137063 / 26.04 / Raise an alert for expiration of cert selectively

- src/middlewared/middlewared/alert/source/certificates.py
This commit adds changes to make sure that we only raise an alert that a cert is expiring if it is within it's renew days and still hasn't been renewed. For example if a cert is expiring on 10th, and renew days is 5, which means that system will start attempting to renew it from 5th. We will start raising an alert from 6th onwards as it shows that the system was not able to renew it successfully.
Original PR: https://github.com/truenas/middleware/pull/16928
> NAS-137063 / 25.10-RC.1 / Raise an alert for expiration of cert selectively (by sonicaj)

- src/middlewared/middlewared/api/v26_04_0/reporting.py
- src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
The API schema right now expects `aggregations` attribute to be always there, however that is not the case because the code does not add it if aggregations are not explicitly requested.
If aggregations are not requested, make sure the key exists so API schema is happy.
> NAS-137112 / 26.04 / Fix API schema for reporting data

- src/middlewared/middlewared/api/v25_10_0/reporting.py
- src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
git cherry-pick -x e6d1fd8c9632840b46a765bf3ab291f1758929f8
git cherry-pick -x d32cf33840207c003b25bbeef554c86a2707632a
The API schema right now expects `aggregations` attribute to be always there, however that is not the case because the code does not add it if aggregations are not explicitly requested.
If aggregations are not requested, make sure the key exists so API schema is happy.
Original PR: https://github.com/truenas/middleware/pull/16944
> NAS-137112 / 25.10-RC.1 / Fix API schema for reporting data (by Qubad786)

- src/middlewared/middlewared/api/v25_10_0/reporting.py
- src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
git cherry-pick -x e6d1fd8c9632840b46a765bf3ab291f1758929f8
git cherry-pick -x d32cf33840207c003b25bbeef554c86a2707632a
The API schema right now expects `aggregations` attribute to be always there, however that is not the case because the code does not add it if aggregations are not explicitly requested.
If aggregations are not requested, make sure the key exists so API schema is happy.
Original PR: https://github.com/truenas/middleware/pull/16944
> NAS-137112 / 25.10-BETA.1 / Fix API schema for reporting data (by Qubad786)

- src/middlewared/middlewared/plugins/sysdataset.py
309452c9c2bc4f40a3bd73a2e843088481a92382 introduced a subtle behavioral change by allowing the boot pool to be returned in this method. Change it so that the boot pool is always ignored (matching previous behavior).
> NAS-137114 / 26.04 / fix query_pools_for_system_dataset

- src/middlewared/middlewared/plugins/disk_/temperature.py
When using the endpoint `disk.temperature_agg`, we were calculating start/end time in the future with doing roughly the following:
```
start = time right now
end = time right now + days (usually 7)
```
Which meant that we asked data from netdata from right now to 7 days in the future which is not good. Netdata in this case does not error out but roughly returns the datapoints of the last 24h in such cases.
Make sure we use the correct start/end timestamps to reflect reality and ask about historical data as requested by the consumer.
Original PR: https://github.com/truenas/middleware/pull/16947
> NAS-137113 / 25.10-RC.1 / Fix start/end in temperature aggregation (by Qubad786)

- src/middlewared_docs/docs/conf.py
- src/middlewared_docs/docs/jobs.rst
- src/middlewared_docs/docs/jsonrpc.rst
- src/middlewared_docs/docs/query_methods.rst
- Comment out the intersphinx extension to speed up docs generation since we don't use it.
- Use reST section notation consistent with the Python [documentation guide](https://devguide.python.org/documentation/markup/#sections).
- Use double backticks for inline code (single backticks are for italics).
- Lex code blocks for proper rendering with syntax highlighting.
- Improve table of filter operators.
- Expand schemas for error responses and notifications.
Before:
After:
> NAS-137127 / 26.04 / Fix API docs code blocks not rendering

- src/middlewared/middlewared/plugins/pool_/dataset_query_utils.py
This commit fixes an issue where if we for example retrieve name/used/available attrs by specifying in select, the query logic breaks as it expects keys like "children" to be present. The idea is to apply the select after relevant business logic has been applied.
Original PR: https://github.com/truenas/middleware/pull/16957
> NAS-137144 / 25.10-RC.1 / Fix pool.dataset.query when using select (by sonicaj)

- src/middlewared/middlewared/pytest/unit/plugins/disk/test_dev_to_ident.py
- src/middlewared/middlewared/pytest/unit/utils/test_disk_names.py
- src/middlewared/middlewared/utils/disks.py
When truenas is virtualized using xen, disks can appear in the system as `xvdb` etc and in this case their disk identifier shows up as `''` and eventually we cannot have more then one disk in the disk table because we have a UNIQUE constraint on identifiers.
Why identifier shows up as `''` because when trying to gauge identifier, it gets available disks and if the disk in question is not found there, it skips it (it is not nice but we are going to redo this logic separately).
Make sure the regex we have which covers the disks we support actually accounts for xen disks as well.
> NAS-137126 / 26.04 / Fix proper disk syncing in Xen VMs

- src/middlewared/middlewared/pytest/unit/plugins/disk/test_dev_to_ident.py
- src/middlewared/middlewared/pytest/unit/utils/test_disk_names.py
- src/middlewared/middlewared/utils/disks.py
When truenas is virtualized using xen, disks can appear in the system as `xvdb` etc and in this case their disk identifier shows up as `''` and eventually we cannot have more then one disk in the disk table because we have a UNIQUE constraint on identifiers.
Why identifier shows up as `''` because when trying to gauge identifier, it gets available disks and if the disk in question is not found there, it skips it (it is not nice but we are going to redo this logic separately).
Make sure the regex we have which covers the disks we support actually accounts for xen disks as well.
Original PR: https://github.com/truenas/middleware/pull/16960
> NAS-137126 / 25.10-BETA.1 / Fix proper disk syncing in Xen VMs (by Qubad786)

- src/middlewared/middlewared/main.py
Internal testing has found that sending a specific set of disk events will cause all children in the process pool to crash silently and never recover. This looks like a proper upstream bug in python. The crash occurs because we're exhausting the children in the pool AND each child will execute 20 tasks before being killed and re-created. This was reproduced by a trivial 3-5 line python script. Bumping this value to 100 prevented the script from crashing process pool and fixed the issue we were seeing on internal hardware. This is the path of least resistance and a stop-gap solution as we are rapidly working towards getting rid of our process pool entirely. This will work for now.
Original PR: https://github.com/truenas/middleware/pull/16963
> NAS-137123 / 25.10-BETA.1 / bump max_tasks_per_child to 100 so process pool doesn't crash (by yocalebo)

- src/middlewared/middlewared/main.py
Internal testing has found that sending a specific set of disk events will cause all children in the process pool to crash silently and never recover. This looks like a proper upstream bug in python. The crash occurs because we're exhausting the children in the pool AND each child will execute 20 tasks before being killed and re-created. This was reproduced by a trivial 3-5 line python script. Bumping this value to 100 prevented the script from crashing process pool and fixed the issue we were seeing on internal hardware. This is the path of least resistance and a stop-gap solution as we are rapidly working towards getting rid of our process pool entirely. This will work for now.
Original PR: https://github.com/truenas/middleware/pull/16963
> NAS-137123 / 25.10-RC.1 / bump max_tasks_per_child to 100 so process pool doesn't crash (by yocalebo)

- src/middlewared/middlewared/api/v25_10_0/directory_services.py
- src/middlewared/middlewared/api/v26_04_0/directory_services.py
This commit bumps the maximum allowed directory services timeout to 60 seconds to make consistent with legacy behavior from Core.
> NAS-137105 / 26.04 / Adjust maximum timeout value for directory services

- src/freenas/usr/local/bin/nvmf-connect.sh
- src/freenas/usr/local/bin/nvmf-power-recovery.sh
During shelf power cycles, discovery events arrive before the discovery page is populated (~30s delay), causing missed connections. Implement dedicated power recovery service that detects power restoration scenarios and attempts connect-all 12 times over 60+ seconds with timer reset for hotplug events during recovery.
[Scale Build](http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/1408/)
Validated by @jervin777.
Original PR: https://github.com/truenas/middleware/pull/16938
> NAS-137082 / 25.10-RC.1 / nvme-of: add power recovery service for shelf power cycles (by ixhamza)

- src/freenas/usr/local/bin/nvmf-connect.sh
- src/freenas/usr/local/bin/nvmf-power-recovery.sh
During shelf power cycles, discovery events arrive before the discovery page is populated (~30s delay), causing missed connections. Implement dedicated power recovery service that detects power restoration scenarios and attempts connect-all 12 times over 60+ seconds with timer reset for hotplug events during recovery.
[Scale Build](http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/1408/)
Validated by @jervin777.
Original PR: https://github.com/truenas/middleware/pull/16938
> NAS-137082 / 25.04.2.2 / nvme-of: add power recovery service for shelf power cycles (by ixhamza)

- src/middlewared/middlewared/main.py
Internal testing has found that sending a specific set of disk events will cause all children in the process pool to crash silently and never recover. This looks like a proper upstream bug in python. The crash occurs because we're exhausting the children in the pool AND each child will execute 20 tasks before being killed and re-created. This was reproduced by a trivial 3-5 line python script. Bumping this value to 100 prevented the script from crashing process pool and fixed the issue we were seeing on internal hardware. This is the path of least resistance and a stop-gap solution as we are rapidly working towards getting rid of our process pool entirely. This will work for now.
Original PR: https://github.com/truenas/middleware/pull/16963
> NAS-137123 / 25.04.2.2 / bump max_tasks_per_child to 100 so process pool doesn't crash (by yocalebo)

- src/middlewared/middlewared/plugins/smb.py
This commit alters the SMB share datastore extend method to interpret a zero value for grace period as the current default for the share.
> NAS-137179 / 26.04 / Fix default value for WORM grace period

- src/middlewared/middlewared/plugins/smb.py
This commit alters the SMB share datastore extend method to interpret a zero value for grace period as the current default for the share.
Original PR: https://github.com/truenas/middleware/pull/16979
> NAS-137179 / 25.10-RC.1 / Fix default value for WORM grace period (by anodos325)

- src/middlewared/middlewared/api/v25_10_0/alertservice_attributes.py
- src/middlewared/middlewared/api/v26_04_0/alertservice_attributes.py
For both alert service types we set a URL field to the empty string by default, but the `HttpUrl` type does not allow empty strings causing `alertservice.create` to fail with a validation error.
> NAS-137061 / 26.04 / Fix `alertservice.create` for Mattermost and OpsGenie types

- src/middlewared/middlewared/api/v25_10_0/alertservice_attributes.py
git cherry-pick -x 3f5d20b6cc192abc7f7e360d3bd94bd876b4d674
git cherry-pick -x a1efe98c0a727fee148dd6ba9ed0517284326afc
For both alert service types we set a URL field to the empty string by default, but the `HttpUrl` type does not allow empty strings causing `alertservice.create` to fail with a validation error.
Original PR: https://github.com/truenas/middleware/pull/16978
> NAS-137061 / 25.10-RC.1 / Fix `alertservice.create` for Mattermost and OpsGenie types (by creatorcary)

- src/middlewared/middlewared/utils/disks.py
- src/middlewared/middlewared/utils/disks_/disk_class.py
We had fixed the regex for `VALID_WHOLE_DISK` but however there were 2 different instances of it and the other was still outdated and skipped xen based disks.
Make sure we don't have 2 different regex around and use 1 source of truth which also accounts for xen based disks.
> NAS-137180 / 26.04 / Properly fix disk syncing in xen VMs

- src/middlewared/middlewared/utils/disks.py
- src/middlewared/middlewared/utils/disks_/disk_class.py
We had fixed the regex for `VALID_WHOLE_DISK` but however there were 2 different instances of it and the other was still outdated and skipped xen based disks.
Make sure we don't have 2 different regex around and use 1 source of truth which also accounts for xen based disks.
Original PR: https://github.com/truenas/middleware/pull/16984
> NAS-137180 / 25.10-BETA.1 / Properly fix disk syncing in xen VMs (by Qubad786)

- src/middlewared/middlewared/utils/disks.py
- src/middlewared/middlewared/utils/disks_/disk_class.py
We had fixed the regex for `VALID_WHOLE_DISK` but however there were 2 different instances of it and the other was still outdated and skipped xen based disks.
Make sure we don't have 2 different regex around and use 1 source of truth which also accounts for xen based disks.
Original PR: https://github.com/truenas/middleware/pull/16984
> NAS-137180 / 25.10-RC.1 / Properly fix disk syncing in xen VMs (by Qubad786)

- src/middlewared/middlewared/api/v25_10_0/directory_services.py
This commit removes ability for users to set a directoryservices.update request without providing the configuration and credential details if a service_type has been specified. This ensures that the config details are always valid. There is already a supported method for users to clear config if that's what's needed.
Original PR: https://github.com/truenas/middleware/pull/17021
> NAS-136995 / 25.10-RC.1 / Make directoryservice validation more strict (by anodos325)

- src/middlewared/middlewared/api/v25_10_0/directory_services.py
This commit removes ability for users to set a directoryservices.update request without providing the configuration and credential details if a service_type has been specified. This ensures that the config details are always valid. There is already a supported method for users to clear config if that's what's needed.
Original PR: https://github.com/truenas/middleware/pull/17021
> NAS-136995 / 25.10-BETA.1 / Make directoryservice validation more strict (by anodos325)

- src/middlewared/middlewared/etc_files/nfs.conf.mako
- src/middlewared/middlewared/plugins/etc.py
- tests/api2/test_300_nfs.py
NFS includes a setting, 'scope'.  The purpose of this setting is to provide a unique and consistent ID that spans a filesystem shared by multiple controllers, e.g. an HA system.
For some clients, e.g. VMware, to support failover the `scope` setting must be the same between controllers.
The backports of this depend on updates to `nfs-utils`: 
- https://github.com/truenas/nfs-utils/pull/7
Added CI test which passes on local testing.
> NAS-137171 / 26.04 / Add 'scope' setting to support HA.

- src/middlewared/middlewared/alert/source/smart.py
Two of the drives we sell need to have a bit more intelligent SMART attribute processing. This adds that functionality after working with both OEMs to ensure the values we're parsing and the logic we're applying matches their expectations.
Original PR: https://github.com/truenas/middleware/pull/17033
> NAS-137022 / 25.10-RC.1 / add vendor specific SMART checks (by yocalebo)

- src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
The `NVMETargetService.become_active` had been written to optimize the case where ANA was enabled, but was broken when it was not.  Rectify.
> NAS-137255 / 26.04 / Update nvmet become_active to start the service if necessary

- src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
The `NVMETargetService.become_active` had been written to optimize the case where ANA was enabled, but was broken when it was not.  Rectify.
Original PR: https://github.com/truenas/middleware/pull/17041
Original PR: https://github.com/truenas/middleware/pull/17042
> NAS-137255 / 25.10-BETA.1 / Update nvmet become_active to start the service if necessary (by bmeagherix) (by bugclerk)

- src/middlewared/middlewared/service/core_service.py
This breaks downloading job results via midcli
> NAS-136878 / 26.04 / Disable `match_origin` for `core.download` called via UNIX socket

- src/middlewared/middlewared/plugins/iscsi_/extents.py
- src/middlewared/middlewared/plugins/nvmet/namespace.py
When a file is passed into `path_in_locked_datasets` the filename, (or a containing directory) can be an invalid name wrt dataset. Strip off any offending material.
> NAS-137259 / 26.04 / Sanitize filepath in sharing_task_determine_locked for iSCSI and nvmet

- src/middlewared/middlewared/service/core_service.py
This breaks downloading job results via midcli
Original PR: https://github.com/truenas/middleware/pull/17030
> NAS-136878 / 25.10-BETA.1 / Disable `match_origin` for `core.download` called via UNIX socket (by themylogin)

- src/middlewared/middlewared/api/v25_10_0/user.py
- src/middlewared/middlewared/api/v26_04_0/user.py
This commit switches email address validation so that the more restrictive checks only occur when creating / updating accounts. This is to resolve breakage of the users form in the UI for users who set email addresses under older versions of TrueNAS where we were not validating email addresses as carefully.
> NAS-137198 / 26.04 / Relax validation of email address in query results

- src/middlewared/middlewared/plugins/jbof/crud.py
Improve ambiguous JBOF error message (HA configured, but other node down).
Original PR: https://github.com/truenas/middleware/pull/17062
> NAS-137288 / 25.10-RC.1 / Improve JBOF error message when cannot contact HA peer node (by bmeagherix)

- tests/api2/test_account_privilege_role.py
Querying for snapshots just needs the `ZFS_RESOURCE_READ` role. Though, this will need to be revisited on how we can mimic the existing behavior of roles where someone just wants to grant a user the ability to read/write snapshots only.
> NAS-137303 / 26.04 / fix snapshot role test

- src/middlewared/middlewared/plugins/auth.py
There are some situations in which an API client may keep a websocket connection open after logout and then log back in. Due to us storing the old authenticated_credentials in the object associated with the websocket connection, this caused the audit message to be logged against the last logged-in user account rather than properly reflecting the authenticated user as "UNAUTHENTICATED" at that time. This commit clears the authentication_context (pam handle) and the autheneticated_credentials on user logout to prevent them from ever being reused.
Original PR: https://github.com/truenas/middleware/pull/17068
> NAS-137121 / 25.10-RC.1 / Clear authentication state on logout (by anodos325)

- src/middlewared/middlewared/plugins/auth.py
There are some situations in which an API client may keep a websocket connection open after logout and then log back in. Due to us storing the old authenticated_credentials in the object associated with the websocket connection, this caused the audit message to be logged against the last logged-in user account rather than properly reflecting the authenticated user as "UNAUTHENTICATED" at that time. This commit clears the authentication_context (pam handle) and the autheneticated_credentials on user logout to prevent them from ever being reused.
Original PR: https://github.com/truenas/middleware/pull/17068
> NAS-137121 / 25.10-BETA.1 / Clear authentication state on logout (by anodos325)

- src/middlewared/middlewared/api/v25_10_0/nvmet_global.py
- src/middlewared/middlewared/api/v26_04_0/nvmet_global.py
- src/middlewared/middlewared/plugins/nvmet/global.py
Remove `nvmet.global.ana_enabled` and `nvmet.global.rdma_enabled` from public 25.10 API.  These are only used internally.
Original PR: https://github.com/truenas/middleware/pull/17071
> NAS-137307 / 26.04 / Remove ana_enabled and rdma_enabled from nvmet.global public API (by bmeagherix)

- src/middlewared/middlewared/api/v25_10_0/update.py
- src/middlewared/middlewared/plugins/mail.py
- src/middlewared/middlewared/plugins/mail_/gmail.py
- src/middlewared/middlewared/plugins/network_/activity.py
- src/middlewared/middlewared/plugins/update_/status.py
- src/middlewared/middlewared/service/__init__.py
- src/middlewared/middlewared/service_exception.py
git cherry-pick -x 3ec4710a33524439bfeaf90dbc51b6e173743371
git cherry-pick -x 35afacdaa1997fa608cc9226b3eab14c292bb588
While I am here, make `NetworkActivityDisabled` a separate exception and replace `DenyNetworkActivity` in `mail` plugin, which was created for the same purpose.
Original PR: https://github.com/truenas/middleware/pull/17076
> NAS-137319 / 25.10-RC.1 / Make `update.status` return `NETWORK_ACTIVITY_DISABLED` when network activity is disabled (by themylogin)

- src/freenas/etc/logrotate.d/nginx
This uses the upstream provided nginx log rotate file with just a couple modifications (size and rotate). This more closely aligns us with what upstream debian ships.
> NAS-137325 / 26.04 / use upstream nginx logrotate.d file

- src/freenas/etc/logrotate.d/nginx
This uses the upstream provided nginx log rotate file with just a couple modifications (size and rotate). This more closely aligns us with what upstream debian ships.
Original PR: https://github.com/truenas/middleware/pull/17079
> NAS-137325 / 25.10-RC.1 / use upstream nginx logrotate.d file (by yocalebo)

- src/middlewared/middlewared/api/base/server/app.py
- src/middlewared/middlewared/api/v25_10_0/auth.py
- src/middlewared/middlewared/apps/webshell_app.py
- src/middlewared/middlewared/auth.py
- src/middlewared/middlewared/plugins/kmip/connection.py
- src/middlewared/middlewared/plugins/truenas_connect/register.py
- src/middlewared/middlewared/utils/crypto.py
- tests/api2/test_audit_audit.py
- tests/api2/test_audit_rest.py
- tests/api2/test_audit_websocket.py
- tests/api2/test_job_credentials.py
This commit switches middleware to using SSL to generate the random bytes needed for uuids that are used for session IDs or other security-adjacent areas. Middleware is also slightly adjusted so that we generate a unique per-login uuid as well to differentiate between logins on the same websocket connection.
Original PR: https://github.com/truenas/middleware/pull/17074
> NAS-137318 / 25.10-RC.1 / Use SSL RNG to generate sensitive IDs (by anodos325)

- src/middlewared/middlewared/alert/source/directory_services.py
- src/middlewared/middlewared/plugins/directoryservices_/connection.py
- src/middlewared/middlewared/utils/directoryservices/constants.py
- src/middlewared/middlewared/utils/directoryservices/dns.py
- src/middlewared/middlewared/utils/directoryservices/health.py
This commit adds logic for automatically renewing DNS entries when the administrator has configured TrueNAS to do such. This is required for some AD environments where the system administrator has configured AD to automatically scavenge records that haven't been updated for a while.
This commit also introduces a threading lock NSUPDATE_LOCK that is held whenever middleware registers / deregisters / renews DNS entries for directory services.
> NAS-121593 / 26.04 / Add logic for renewing DNS entries

- src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
Added for general best practices but also to appease the DoDIN requirements.
While I'm here, I fixed the formatting so the security header entries are indented underneath the {} blocks and line up with everything else.
> NAS-136353 / 26.04 / add more security headers to nginx.conf

- src/middlewared/middlewared/plugins/datastore/util.py
TrueCommand no longer uses this method so we can safely remove it.
> NAS-137339 / 26.04 / remove dump_json endpoint

- src/middlewared/middlewared/api/v25_10_0/alert.py
- src/middlewared/middlewared/plugins/alert.py
git cherry-pick -x 854c365336cd7c32170226fc84bbc08cb2af36e9
git cherry-pick -x 560bc22d81f0a6d97328084f893ad66a42b1e429
Original PR: https://github.com/truenas/middleware/pull/17119
> NAS-137384 / 25.10-RC.1 / Do not requires all fields to be set for alert classes (like it was before pydantic conversion) (by themylogin)

- tests/api2/test_440_snmp.py
The new `pysnmp` python library as been converted to asyncio.  This complicates using it in CI tests.
Replace the `pysnmp` calls with an `snmpwalk` call from the test runner.
Passing tests: See `test_440_snmp.py` console output [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/5809/console)
> NAS-137296 / 26.04 / Remove asyncio from SNMP CI

- src/middlewared/middlewared/plugins/service.py
- src/middlewared/middlewared/plugins/service_/utils.py
- tests/api2/test_nvmet_crud_roles.py
- tests/api2/test_nvmet_misc_roles.py
- Allow `SHARING_NVME_TARGET_WRITE` role to control `nvmet` service
- Add CI tests for `nvmet` roles
----
CI tests run/pass locally
> NAS-137418 / 26.04 / NVMe-of-service is locked for sharing admin

- src/middlewared/middlewared/plugins/service.py
- src/middlewared/middlewared/plugins/service_/utils.py
- tests/api2/test_nvmet_crud_roles.py
- tests/api2/test_nvmet_misc_roles.py
- Allow `SHARING_NVME_TARGET_WRITE` role to control `nvmet` service
- Add CI tests for `nvmet` roles
----
CI tests run/pass locally
Original PR: https://github.com/truenas/middleware/pull/17131
> NAS-137418 / 25.10-RC.1 / NVMe-of-service is locked for sharing admin (by bmeagherix)

- src/middlewared/middlewared/plugins/disk.py
- src/middlewared/middlewared/utils/disks_/disk_class.py
In previous commit 294a283408bfa4ba9a01b845bef83ab15cb81f06, the ability to create zpools when an EMPTY SD card reader was present was resolved. However, the underlying issue is still present in other parts of the stack because we also use this for gathering temperature information.
The issue is that in the `identifier` property of `DiskEntry` class goes through a process to try and determine a unique identifier for every disk on a system. This is important for obvious reasons. One of the steps for determining the unique identifier is to read the disk for partitions since we use GPT (they have GUID's). What's happening, however, is that empty SD card readers aren't reporting a serial number so we fallback to reading partitions. However, when the SD card reader is empty the `open` syscall …
> NAS-137434 / 26.04 / Fix disk temps when empty SD card readers are present

- src/middlewared/middlewared/api/v25_10_0/vm.py
- src/middlewared/middlewared/api/v26_04_0/vm.py
- src/middlewared/middlewared/plugins/vm/vms.py
- src/middlewared/middlewared/pytest/unit/plugins/test_vm.py
When secure boot is enabled for a VM, we are defaulting for `OVMF_CODE.fd` which won't work for VMs who want secure boot enabled. This causes problems and for VMs which are already installed, changing `bootloader_ovmf` can actually be problematic and result in an erroneous configuration because of how nvram files for VMs are generated.
Validation has been added to ensure that when secure boot is enabled for a VM, we do not allow configuring a `bootloader_ovmf` file which will not work with secure boot and secondly on vm update operation, we should not allow changing `bootloader_ovmf` as that can lead to the VM not booting up at all because of firmware issues.
Also when a VM is being created, we should default to a bootloader ovmf file which reflects the secure boot setting properly.
> NAS-137054 / 26.04 / Improve defaults and validation for secure boot in VMs

- src/middlewared/middlewared/plugins/vm/devices/display.py
- src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_devices_xml.py
We have seen that on higher resolutions, the default values libvirt sets for `vgamem/ram/vram` might not be sufficient and keeping that in mind, changes have been added to have reasonable defaults for these attrs so we support all the resolutions out of the box.
Original PR: https://github.com/truenas/middleware/pull/17136
> NAS-137213 / 25.10-RC.1 / Add reasonable defaults for vram/vgamem/ram attributes for display device (by Qubad786)

- src/middlewared/middlewared/plugins/vm/vm_devices.py
This logic was mistakingly removed in one of my force commits when I originally added this endpoint. This presents a better error message when neither the source nor destination fields in the API represent the disk image to be converted from (or to).
> NAS-137436 / 26.04 / improve validation in vm.device.convert

- src/middlewared/middlewared/plugins/smb_/util_smbconf.py
- tests/unit/test_smb_share.py
This commit removes the smb.conf generation step in which we add vfs_acl_xattr if POSIX ACLs are enabled. This was originally added to provide support for a somewhat richer ACL model when POSIX acltype was selected for an SMB share (non-default configuration). Unfortunately, this creates two potential sources of truth for the ACL contents and has potential to create hard-to-diagnose permissions issues on the backend.
Since we already have a rich ACL model provided by the NFSv4 acltype on ZFS, it provides a better UX to simplify the ACL implementation for POSIX ACLs by removing this module.
Original PR: https://github.com/truenas/middleware/pull/17144
> NAS-137439 / 25.04.2.4 / Simplify ACL handling in samba for POSIX ACLs (by anodos325)

- src/middlewared/middlewared/plugins/interface/lag.py
- src/middlewared/middlewared/plugins/interface/netif_linux/lagg.py
The bond (LAG) interface is not being configured correctly, which causes issues during failover. Currently, the `miimon` parameter is disabled. As a result, the bond interface cannot switch to a working interface if the active slave fails. The `miimon` parameter continuously monitors the state of inactive interfaces and triggers a switch when the primary interface goes down.
Set the `miimon` value to `100`, as recommended in the [Linux kernel bonding documentation](https://www.kernel.org/doc/html/latest/networking/bonding.html), to ensure proper bond interface handling.
It is essential to have this or `arp_interval` params set to have link monitoring in place.
> NAS-136978 / 26.04 / Fix link aggregation

- src/middlewared/middlewared/plugins/vm/vm_devices.py
Missed some validation here that was found by UI team during implementation. Need to ensure the disk image exists in a proper location. Raise a proper validation error message otherwise.
Original PR: https://github.com/truenas/middleware/pull/17145
> NAS-137440 / 25.10-RC.1 / better error message in vm.device.convert (by yocalebo)

- src/middlewared/middlewared/plugins/zfs/resource_crud.py
This commit adds changes to fix snapshot_exists as when we query underlying zfs dataset snapshots, we get the full name i.e ds@snap and we were checking the latter part earlier.
> NAS-137301 / 26.04 / Fix snapshot_exists endpoint

- src/middlewared/middlewared/plugins/directoryservices_/connection.py
When the _get_enabled_ds function was refactored for backend datastore changes an error was introduced whereby having disabled directory services could cause certain checks to fail with ValueError because we were trying to return DSType(None).
> NAS-137446 / 26.04 / Fix handling for disabled directory services

- src/middlewared/middlewared/etc_files/exports.mako
- tests/api2/test_300_nfs.py
We do not allow NFS share configuration files, or any files, in `/etc/exports.d`.  This directory is where ZFS installs it's NFS sharing configuration.  To maintain filesystem security and integrity we allow only TrueNAS managed share configuration files.
The code enforcing this is defective.  The crux being that when ZFS generates an NFS share file, `zfs.exports` it also generates a lock file, `zfs.exports.lock`.  Before we enable NFS we generate a list of files in `/etc/exports.d` and process and delete them one by one.  If one is `zfs.exports` we do additional processing to disable NFS sharing via ZFS before deleting it.  Most of the time the file listing would place `zfs.exports` before `zfs.exports.lock`.  However, sometimes `zfs.exports.lock` is processed before `zfs.exports`.  This …
> NAS-137488 / 26.04 / Fix nfs start sharenfs in exports.d

- src/middlewared/middlewared/api/v25_04_0/common.py
- src/middlewared/middlewared/api/v25_04_1/common.py
- src/middlewared/middlewared/api/v25_04_2/common.py
- src/middlewared/middlewared/api/v25_10_0/common.py
- src/middlewared/middlewared/api/v26_04_0/common.py
- src/middlewared/middlewared/plugins/datastore/read.py
- src/middlewared/middlewared/plugins/pool_/dataset_query_utils.py
- src/middlewared/middlewared/utils/filter_list.py
- src/middlewared/middlewared/utils/filter_ops.py
This is a simple change to remove the `filters` class and instead make its methods functions of the `middlewared.utils.filter_list` module. Creating multiple `filters` objects throughout middleware is unnecessary.
* Replace all `filters` objects with direct function imports
* Create new module `middlewared.utils.filter_ops` for storing filter operations
* Other minor improvements
http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/5916/
> NAS-137528 / 26.04 / Refactor filters to not be object oriented

- src/middlewared/middlewared/alembic/versions/25.10/2025-03-20_11-52_drop_smart.py
We had dropped smart related tables and in one place we were trying to drop an index of a table but for a user it errored out saying that relevant index does not exist.
This is because the user is really old and had the table created from django era where django had created a different index 
```
CREATE UNIQUE INDEX system_smarttest_smarttest_disks_smarttest_id__disk_id ON tasks_smarttest_smarttest_disks (smarttest_id, disk_id);
CREATE INDEX system_smarttest_smarttest_disks_ad111e65 ON tasks_smarttest_smarttest_disks (disk_id);
CREATE INDEX system_smarttest_smarttest_disks_ec6fbbff ON tasks_smarttest_smarttest_disks (smarttest_id);
```
Django is known to do this.
As we do not care about the table at all because we are dropping it, we can safely choose not to drop the index manually and …
> NAS-137502 / 26.04 / Fix migration index issue

- src/middlewared/middlewared/main.py
Middleware no longer starts up because of a change introduced in fab779f609470489135746e4b9f1f19dcc4cdcc3.
> NAS-137550 / 26.04 / fix middleware start-up regression

- src/middlewared/middlewared/main.py
More fallout from fab779f609470489135746e4b9f1f19dcc4cdcc3. This is clearly a typo that was forgotten about 😄
> NAS-137564 / 26.04 / fix commented out code

- src/middlewared/middlewared/plugins/iscsi_/extents.py
- src/middlewared/middlewared/plugins/nvmet/subsys.py
- src/middlewared/middlewared/plugins/pool_/dataset_encryption_operations.py
- src/middlewared/middlewared/utils/crypto.py
- src/middlewared/middlewared/utils/secrets.py
- src/middlewared/middlewared/utils/sid.py
This commit switches the middleware crypto utils from using the cpython secrets file based on os.urandom to an equivalent based on SSL RAND_bytes.
For reference see:
https://github.com/python/cpython/blob/3.13/Lib/random.py
https://github.com/python/cpython/blob/3.13/Lib/secrets.py
> NAS-137565 / 26.04 / Use openssl for generating cryptographic secrets

- tests/api2/test_006_pool_and_sysds.py
- tests/api2/test_300_nfs.py
CI test `test_004_verify_pool_property_unused_disk_functionality` in `api2/test_006_pool_and_sysds.py` has been consistently failing.
To address this we disabled ZFS `sharenfs` and `sharesmb` in a ZFS [PR](https://github.com/truenas/zfs/pull/306) 
This PR modifies `api2/test_006_pool_and_sysds.py` and tailors it to the ZFS changes.
Also removed `test_sharenfs_in_exportsd` since the ZFS change makes it impossible to create it.
[CI run](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/5921/) (before removing `test_sharenfs_in_exportsd`)
NOTE:  Successful CI runs are dependent on the ZFS PR.
> NAS-137532 / 26.04 / Update `sharenfs` test

- src/middlewared/middlewared/plugins/smb_/utils.py
- src/middlewared/middlewared/test/integration/assets/directory_service.py
- src/middlewared/middlewared/utils/crypto.py
- src/middlewared/setup.cfg
This commit bans the secrets module to force use of version that is backed by openssl RAND_bytes.
This helps us from regressing in an area where we need to be compliant.
> NAS-137570 / 26.04 / Ban python secrets module in flake8 config

- src/middlewared/middlewared/plugins/update_/status.py
Recent commit (9f3d0f1) had a typo wrt ErrnoMixin.  Rectify.
(See definition of enum [here](https://github.com/truenas/api_client/blob/1c00233b5cecd04b23c170aeee9edaa9efa2dbd4/truenas_api_client/exc.py#L22).)
Original PR: https://github.com/truenas/middleware/pull/17212
> NAS-137600 / 25.10.0 / Correct ErrnoMixin.EHAUNAVAILABLE (not HA_UNAVAILABLE) (by bmeagherix)

- src/middlewared/middlewared/plugins/filesystem.py
- src/middlewared/middlewared/utils/pwenc.py
This commit fixes an ENOMETHOD failure on HA sync to peer of pwenc secret. On receipt of a new pewnce secret via private upload endpoint we'll clear the cached open of the pwenc secret and allow clients to naturally reopen it.
> NAS-137602 / 26.04 / Fix reset of secret cache on receipt of pwenc secret

- .github/workflows/lint.yml
- src/middlewared/middlewared/api/v25_04_0/acl.py
- src/middlewared/middlewared/api/v25_04_0/auth.py
- src/middlewared/middlewared/api/v25_04_0/filesystem.py
- src/middlewared/middlewared/api/v25_04_1/acl.py
- src/middlewared/middlewared/api/v25_04_1/auth.py
- src/middlewared/middlewared/api/v25_04_1/filesystem.py
- src/middlewared/middlewared/api/v25_04_2/acl.py
- src/middlewared/middlewared/api/v25_04_2/auth.py
- src/middlewared/middlewared/api/v25_04_2/filesystem.py
- src/middlewared/middlewared/api/v25_10_0/acl.py
- src/middlewared/middlewared/api/v25_10_0/auth.py
- src/middlewared/middlewared/api/v25_10_0/directory_services.py
- src/middlewared/middlewared/api/v25_10_0/filesystem.py
- src/middlewared/middlewared/api/v25_10_0/idmap.py
- src/middlewared/middlewared/api/v26_04_0/acl.py
- src/middlewared/middlewared/api/v26_04_0/auth.py
- src/middlewared/middlewared/api/v26_04_0/directory_services.py
- src/middlewared/middlewared/api/v26_04_0/filesystem.py
- src/middlewared/middlewared/api/v26_04_0/idmap.py
Sphinx has trouble parsing our method schemas that include `Literal[None]` which is just equivalent to `None`.
> NAS-137612 / 26.04 / Replace `Literal[None]` with `None` to fix API docs

- .github/workflows/lint.yml
- src/middlewared/middlewared/api/v25_04_0/acl.py
- src/middlewared/middlewared/api/v25_04_0/auth.py
- src/middlewared/middlewared/api/v25_04_0/filesystem.py
- src/middlewared/middlewared/api/v25_04_1/acl.py
- src/middlewared/middlewared/api/v25_04_1/auth.py
- src/middlewared/middlewared/api/v25_04_1/filesystem.py
- src/middlewared/middlewared/api/v25_04_2/acl.py
- src/middlewared/middlewared/api/v25_04_2/auth.py
- src/middlewared/middlewared/api/v25_04_2/filesystem.py
- src/middlewared/middlewared/api/v25_10_0/acl.py
- src/middlewared/middlewared/api/v25_10_0/auth.py
- src/middlewared/middlewared/api/v25_10_0/directory_services.py
- src/middlewared/middlewared/api/v25_10_0/filesystem.py
- src/middlewared/middlewared/api/v25_10_0/idmap.py
git cherry-pick -x 49ddfd331fa10427a57dcf9278d091b8099eb7cc
git cherry-pick -x e838262a9c005cae3ab46b364c1aa3ccf2480da4
git cherry-pick -x 4b97328ebb85ec013f9261c083380f7aa97c943e
git cherry-pick -x c538fb070ce763b4a09b30a95b386c8d1ac4ef7a
git cherry-pick -x a41e42b9cd8899433edf952191ef8c96dcda49cd
git cherry-pick -x e34e638f8541ee63a924fafd91eb1ccc47eb5458
Sphinx has trouble parsing our method schemas that include `Literal[None]` which is just equivalent to `None`.
Original PR: https://github.com/truenas/middleware/pull/17218
> NAS-137612 / 25.10.0 / Replace `Literal[None]` with `None` to fix API docs (by creatorcary)

- src/middlewared/middlewared/api/base/decorator.py
- src/middlewared/middlewared/service/config_service.py
- src/middlewared/middlewared/service/crud_service.py
- tests/api2/test_legacy_api.py
- tests/conftest.py
git cherry-pick -x 15784fcb78ad8925ae743cfd733e9054877d6cff
git cherry-pick -x 68d6de36d582348be48e3183150017bd456f00d9
git cherry-pick -x 59c6ed534fab6ace1e910d5e042129042a515938
git cherry-pick -x ec276c456308268f843117d3c63e9e09f5e9187c
git cherry-pick -x 929b8b87092cac38cfee0acf4f5cf8247655f055
git cherry-pick -x 81fbf73db563f6cc05b93a6fa3e9bf83ddb30b81
`ConfigService` config method models must be registered like `CRUDService` query and get_instance methods so that they can be called in previous API versions.
Original PR: https://github.com/truenas/middleware/pull/17215
> NAS-137468 / 25.10.0 / Fix backwards compatibility of implicit config methods (by creatorcary)

- src/middlewared/middlewared/api/v25_10_0/ipmi_lan.py
- src/middlewared/middlewared/api/v26_04_0/ipmi_lan.py
Using `ipaddress.IPv4Address` as the field type when `strict=True` in the `BaseModel` config expects a Python object to be passed, not a string. We have custom types for this reason. This is the only use of `ipaddress` types in our API schema, so no more changes are needed.
Original PR: https://github.com/truenas/middleware/pull/17221
> NAS-137593 / 26.04 / Fix `ipmi.lan.update` (by creatorcary)

- src/middlewared/middlewared/plugins/container/container.py
For incus containers we support `-` as valid naming character too and in newer container implementation we don't. Which means that migration from older implemetnation to newer one breaks if we find a container containing a hyphen.
Allow `-` in container names as well which in turn means migration from incus to new containers works just fine. Alternatively if we don't want to support `-` in container names, we can discuss how we want to rename such incus containers.
> NAS-137684 / 26.04 / Fix containers naming regex to support backward compatibility

- src/middlewared/middlewared/plugins/datastore/connection.py
- src/middlewared/middlewared/pytest/unit/plugins/test_datastore.py
Previous commit https://github.com/truenas/middleware/pull/17236 fixed a few issues, however, I was also working on the datastore connection already closed errors in the GitHub unit tests. I believe this is the proper way of fixing the unit tests.
> NAS-137685 / 26.04 / fix datastore/connection.py::setup()

- src/middlewared/middlewared/plugins/smb_/util_smbconf.py
- tests/unit/test_smb_service.py
This commit fixes an oversight when implemnting SMB configuration portion of spotlight support in which we forgot to remove the old RPC server configuration that explicitly disabled the RPC server for MDSSVC and MDSSD.
> NAS-137667 / 26.04 / Properly set rpc server settings for spotlight

- src/middlewared/middlewared/plugins/datastore/connection.py
- src/middlewared/middlewared/pytest/unit/plugins/test_datastore.py
- src/middlewared/middlewared/pytest/unit/test_get_or_insert.py
The migration to SQLAlchemy 2.0 did not take into account how HA replication works.
`compiled.string` is a SQL query that will be passed directly to the underlying driver. In case of SQLite, it contains positional params (`?`)
`compiled.params` are named params, for SQLAlchemy internal use.
Such a combination of query with positional params, and params dictionary with named params cannot be replicated successfully on the other node.
I restored the original code, adding some adaptation for SQLAlchemy 2.0 (they now have parameter expansion for repeated params). I also restored the original unit tests since those were heavily changed when migrating.
> NAS-137675 / 26.04 / Fix `datastore.execute_write`

- src/middlewared/middlewared/plugins/account_/2fa.py
This commit forces regeneration of the users oath file on unsetting 2FA secret for a user. If we don't do this then the user will continue to receive spurious error messages that OTP_REQUIRED on login.
> NAS-137696 / 26.04 / Fix API call to unset 2FA secret

- src/middlewared/middlewared/plugins/account_/2fa.py
This commit forces regeneration of the users oath file on unsetting 2FA secret for a user. If we don't do this then the user will continue to receive spurious error messages that OTP_REQUIRED on login.
Original PR: https://github.com/truenas/middleware/pull/17242
> NAS-137696 / 25.10-RC.1 / Fix API call to unset 2FA secret (by anodos325)

- src/middlewared/middlewared/api/base/server/ws_handler/rpc.py
In the production environment, this code is never reached.
However, in integration tests environment we pickle raised exceptions to re-raise them on the test client.
`libvirt` errors are unpicklable (they are created by C code). When we tried to send a pickled `libvirt` error through the wire, unhandled `pickle.PickleError` was crashing JSON-RPC 2.0 server.
> NAS-137697 / 26.04 / Fix crash on unpicklable error

- src/middlewared/middlewared/alembic/versions/25.10/2025-09-24_21-11_tnc_prod_endpoints.py
- src/middlewared/middlewared/alembic/versions/26.04/2025-09-25_16-19_merge.py
- src/middlewared/middlewared/plugins/truenas_connect/update.py
i.e
```
root@test4WJFS5WJ55[~]# midclt call datastore.config truenas_connect | jq
{
"id": 1,
"enabled": false,
"jwt_token": null,
"registration_details": {},
"ips": [],
"interfaces": [],
"interfaces_ips": [],
"use_all_interfaces": true,
"status": "DISABLED",
"account_service_base_url": "https://account-service.tys1.truenasconnect.net/",
"leca_service_base_url": "https://dns-service.tys1.truenasconnect.net/",
"tnc_base_url": "https://web.truenasconnect.net/",
"heartbeat_url": "https://heartbeat-service.tys1.truenasconnect.net/",
"last_heartbeat_failure_datetime": null,
"certificate": null
}
root@test4WJFS5WJ55[~]#
```
Original PR: https://github.com/truenas/middleware/pull/17249
> NAS-137693 / 26.04 / Moving tn_connect urls from staging to production (by sonicaj)

- src/middlewared/middlewared/plugins/truenas_connect/acme.py
This commit adds changes to not attempt to revoke a cert if there is none configured as trying to fetch one will error out in that case.
> NAS-137728 / 26.04 / Do not try to revoke cert if there is none

- src/middlewared/middlewared/plugins/truenas_connect/acme.py
This commit adds changes to not attempt to revoke a cert if there is none configured as trying to fetch one will error out in that case.
Original PR: https://github.com/truenas/middleware/pull/17259
> NAS-137728 / 25.10.0 / Do not try to revoke cert if there is none (by sonicaj)

- tests/run_unit_tests.py
Remove `setup_middleware_tests` as the pytest dir is now included in the middlewared package.
> NAS-137740 / 26.04 / Remove setup_middleware_tests

- tests/run_unit_tests.py
Restore `setup_middleware_tests`, but make it more resilient.
> NAS-137741 / 26.04 / Fixup setup middleware tests

- src/middlewared/Makefile
This is needed so the CI pipelines that run from a "runner" will work. I'll push another PR in our CI repo to fix the unit test pipeline.
> NAS-137744 / 26.04 / fix install_test make command

- src/middlewared/middlewared/plugins/nvmet/namespace.py
- src/middlewared/middlewared/plugins/pool_/dataset.py
- tests/sharing_protocols/nvmet/test_nvmet_tcp.py
git cherry-pick -x fbf4adf1586aa115d3ebd12d29093a8b1338bea8
git cherry-pick -x ed4769d00849e3e56bd79ab45656402c99e27d31
A test started failing recently (timing issues following Trixie rebase) revealing that the `resync_lun_size_for_zvol` mechanism that we have in place for iSCSI volumes was not implemented for NVMe-oF targets.
Rectify by adding and calling private API `nvmet.namespace.resize_namespace`.
Original PR: https://github.com/truenas/middleware/pull/17266
> NAS-137742 / 25.10.0 / Fix nvmet zvol resize (by bmeagherix)

- src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
Current nginx after these changes
```
root@testD293SDM042[~]# grep -A 2 -B 2 -rin "allow_origin" /etc/nginx/nginx.conf
55-    }
56-
57:    map $http_origin $allow_origin {
58-        ~^https://web.truenasconnect.net$ $http_origin;
59-        default "";
root@testD293SDM042[~]#
```
> NAS-137754 / 26.04 / Fix CORS for TNC production

- src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
Current nginx after these changes
```
root@testD293SDM042[~]# grep -A 2 -B 2 -rin "allow_origin" /etc/nginx/nginx.conf
55-    }
56-
57:    map $http_origin $allow_origin {
58-        ~^https://web.truenasconnect.net$ $http_origin;
59-        default "";
root@testD293SDM042[~]#
```
Original PR: https://github.com/truenas/middleware/pull/17270
> NAS-137754 / 25.10-RC.1 / Fix CORS for TNC production (by sonicaj)

- src/middlewared/middlewared/plugins/iscsi_/alua.py
- src/middlewared/middlewared/plugins/iscsi_/target_to_extent.py
- src/middlewared/middlewared/plugins/iscsi_/targets.py
Perform a rescan of the internal HA target when a LUN is added to an existing target (when ALUA is already enabled).
After the Trixie rebase the test `test_alua_luns` (and more) started [failing](http://jenkins.eng.ixsystems.net:8080/job/tests/job/sharing_protocols_tests/518/) reliably.  The rebase appears to have highlighted a shortcoming/fragility in the code.
----
iSCSI tests passing CI [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/sharing_protocols_tests/521/).
> NAS-137758 / 26.04 / Fix issue when LUN is added to an ALUA target

- src/middlewared/middlewared/plugins/iscsi_/alua.py
- src/middlewared/middlewared/plugins/iscsi_/target_to_extent.py
- src/middlewared/middlewared/plugins/iscsi_/targets.py
Perform a rescan of the internal HA target when a LUN is added to an existing target (when ALUA is already enabled).
After the Trixie rebase the test `test_alua_luns` (and more) started [failing](http://jenkins.eng.ixsystems.net:8080/job/tests/job/sharing_protocols_tests/518/) reliably.  The rebase appears to have highlighted a shortcoming/fragility in the code.
----
iSCSI tests passing CI [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/sharing_protocols_tests/521/).
Original PR: https://github.com/truenas/middleware/pull/17273
> NAS-137758 / 25.10.0 / Fix issue when LUN is added to an ALUA target (by bmeagherix)

- tests/api2/test_virt_002_instance.py
- tests/api2/test_virt_instances.py
We've got a new container plugin that replaces this and these tests are failing causing us to waste time investigating these issues.
> NAS-137766 / 26.04 / disable all virt plugin API tests

- src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
The `expires` nginx directive sets the header `Cache-Control "no-cache;"` in addition to the `Expires` header. This was causing us to send two Cache-Control headers and fail these tests.
Also fix some spacing in nginx.conf.mako to make the generated conf file a little cleaner.
> NAS-137750 / 26.04 / Fix `test_ui_caching.test_index_html`

- tests/api2/test_legacy_api.py
This config endpoint doesn't exist in 25.10.0 either.
> NAS-137767 / 26.04 / fix test_legacy_api CI test

- src/freenas/usr/bin/install-dev-tools
- src/middlewared/Makefile
This changes how we reinstall the `middlewared` package to using deb only instead of fighting the myriad issues that we're experiencing by mixing pip and apt.
> NAS-137776 / 26.04 / fix reinstalling middleware on running TrueNAS

- src/middlewared/middlewared/utils/filesystem/access.py
This commit fixes access checks for group@ / GROUP_OBJ ACL entries. There was a typo that crept in while refactoring this for new API that resulted in the access for the owning group being evaluated as if it were the user. This usually didn't manifest as an error because the primary heavy ACL users are in active directory environments where the NSS backend implements ID_TYPE_BOTH (so there's an identical user and group entry). In the case of local accounts though it could result in spurious validation errors (although in the ticket this is associated with the user actually was trying to set permissions that would raise a validation error even with the fix).
> NAS-137737 / 26.04 / Fix access check for group@ / GROUP_OBJ entries

- debian/debian/postinst
- Don't start truesearch / truenas-webshare-auth by default at startup, let middleware enable them as required.
> NAS-137786 / 26.04 / Fix startup for truesearch/webshare-auth

- src/middlewared/middlewared/plugins/apps/schema_normalization.py
- src/middlewared/middlewared/pytest/unit/plugins/apps/test_normalize_gpu_options.py
When an AMD card exists, this code block is never run so the value of `kfd_device_exists` is always set to the default which is False.
jira:https://ixsystems.atlassian.net/browse/NAS-137145
> NAS-137792 / 26.04 / Fix 'kfd_device_exists' logic for non-NVIDIA gpu

- src/middlewared/middlewared/plugins/apps/schema_normalization.py
- src/middlewared/middlewared/pytest/unit/plugins/apps/test_normalize_gpu_options.py
When an AMD card exists, this code block is never run so the value of `kfd_device_exists` is always set to the default which is False.
jira:https://ixsystems.atlassian.net/browse/NAS-137145
Original PR: https://github.com/truenas/middleware/pull/17108
> NAS-137792 / 25.10.0 / Fix 'kfd_device_exists' logic for non-NVIDIA gpu (by davids3)

- src/middlewared/middlewared/etc_files/docker/daemon.json.py
So what happens here:
- `insecure-registries`: Used to have things like private **registries** 
- Insecure needs to be added here so docker "trusts" them
- Secure do not need to be added, because it works out of the box (ie ghcr.io, quay.io, etc)
- `registry-mirrors`: Used for **mirroring** ~things like ghcr, docker hub, etc~. I got informed that it applies only to docker-hub
- secure (https with valid certs)
- insecure (http or https with self signed). Those have to also be added in the `insecure-registries`, so docker "trusts" them
---
Currently we only allow users to configure mirrors in the UI.
If later we allow also to configure insecure registries, we need to adjust the code like this
```diff
- 'insecure-registries': [urlparse(registry_url).netloc for registry_url in …
```
> NAS-137731 / 26.04 / fix registry mirrors

- src/middlewared/middlewared/etc_files/docker/daemon.json.py
So what happens here:
- `insecure-registries`: Used to have things like private **registries** 
- Insecure needs to be added here so docker "trusts" them
- Secure do not need to be added, because it works out of the box (ie ghcr.io, quay.io, etc)
- `registry-mirrors`: Used for **mirroring** ~things like ghcr, docker hub, etc~. I got informed that it applies only to docker-hub
- secure (https with valid certs)
- insecure (http or https with self signed). Those have to also be added in the `insecure-registries`, so docker "trusts" them
---
Currently we only allow users to configure mirrors in the UI.
If later we allow also to configure insecure registries, we need to adjust the code like this
```diff
- 'insecure-registries': [urlparse(registry_url).netloc for registry_url in …
```
> NAS-137731 / 25.10.0 / fix registry mirrors (by stavros-k)

- src/middlewared/middlewared/plugins/update_/profile_.py
- src/middlewared/middlewared/plugins/update_/status.py
We were erroneously using train redirection to find which train's `releases.json` file will have the current release update profile.
Original PR: https://github.com/truenas/middleware/pull/17304
> NAS-137803 / 25.10.0 / Do not use trains redirect to find which train has current version profile (by themylogin)

- src/middlewared/middlewared/utils/auditd.py
- tests/stig/test_03_stig_auditing.py
In STIG mode we need to audit nginx.
This PR:
Enables auditing of nginx configuration files and logs in STIG mode.
Adds a CI end-to-end test to test a sample of nginx escalation events and a general STIG privileged event.
This PR is dependent on the same named branch from truenas/audit_rules.
Successfully ran the CI tests locally.
> NAS-137817 / 26.04 / STIG: add nginx auditing

- src/middlewared/middlewared/alert/source/usb_storage.py
Raised by the support team. We need to ignore USB CDROM devices in this alert so false positive proactive support tickets are not created in support portal. I also switched to using `os.scandir` since this is being backported to GE which uses python 3.11 and `pathlib.Path.iterdir` on that python version is not performant compared to `os.scandir`.
Original PR: https://github.com/truenas/middleware/pull/17308
> NAS-137844 / 25.10.0 / fix USB disk detection alert on HA (by yocalebo)

- tests/api2/test_smb_share_crud_roles.py
This check has been failing for months and months and the associated conversion of this private method to public has not happened so I'm disabling it to fix false positives in our API test suite.
> NAS-137867 / 26.04 / fix SMB crud roles API test

- src/middlewared/middlewared/etc_files/exports.mako
- src/middlewared/middlewared/plugins/apps/schema_action_context.py
- src/middlewared/middlewared/plugins/audit/audit.py
- src/middlewared/middlewared/plugins/boot_/environments.py
- src/middlewared/middlewared/plugins/docker/fs_manage.py
- src/middlewared/middlewared/plugins/docker/state_setup.py
- src/middlewared/middlewared/plugins/iscsi_/extents.py
- src/middlewared/middlewared/plugins/pool_/import_pool.py
- src/middlewared/middlewared/plugins/pool_/pool.py
- src/middlewared/middlewared/plugins/sysdataset.py
This moves all internal callers to using pool.dataset.update_impl. It also adds `UpdateImplArgs` class keeping same approach that we did with `CreateImplArgs` for `pool.dataset.create_impl`. Ran through the test suite and all tests pass with no obvious regressions.
> NAS-137880 / 26.04 / zfs.dataset.update -> pool.dataset.update_impl

- src/middlewared/middlewared/plugins/apps/schema_construction_utils.py
- src/middlewared/middlewared/pytest/unit/plugins/apps/test_validation_error_ctx.py
This PR resolves the runtime issue caused by missing `ctx['error']` in `ValidationError.from_exception_data` calls. Pydantic v2.9.x requires all `value_error` entries to include an error key in ctx.
> NAS-137805 / 26.04 / Fix pydantic validation error construction in apps schema validation

- src/middlewared/middlewared/etc_files/exports.mako
- src/middlewared/middlewared/plugins/usage.py
- src/middlewared/middlewared/plugins/zfs_/dataset_actions.py
This removes the completely unnecessary `zfs.dataset.path_to_dataset` endpoint. It uses our process pool unnecessarily and causes confusion for developers. While I'm here I fixed two call sites.
> NAS-137906 / 26.04 / remove zfs.dataset.path_to_dataset

- src/middlewared/middlewared/plugins/container/dataset.py
- src/middlewared/middlewared/plugins/pool_/dataset.py
- src/middlewared/middlewared/plugins/pool_/utils.py
- src/middlewared/middlewared/plugins/zfs_/dataset.py
This removes zfs.dataset.create and employs the same methodology used in pool.dataset.update_impl by having a TypedDict and a dataclass for the args for pool.dataset.create_impl. Tests pass.
> NAS-137905 / 26.04 / Remove zfs.dataset.create

- tests/runtest.py
When running tests "by hand" (i.e. outside regular CI) this will allow individual protocol tests from `sharing_protocols` to be run independently.
> NAS-137917 / 26.04 / Add additional entries to TEST_DIR_TO_RESULT

- src/middlewared/middlewared/api/v26_04_0/container.py
- tests/api2/test_container.py
We would like to not force the user to always specify `init` field. A default has been added in this case which works across all the images we offer and is the same default which is being used by incus containers as well.
> NAS-137909 / 26.04 / Have init field for a container be optional

- src/middlewared/middlewared/plugins/docker/fs_manage.py
- src/middlewared/middlewared/plugins/pool_/import_pool.py
- src/middlewared/middlewared/plugins/zfs/mount_unmount_impl.py
- src/middlewared/middlewared/plugins/zfs/resource_crud.py
- src/middlewared/middlewared/plugins/zfs_/dataset_actions.py
- src/middlewared/middlewared/plugins/zfs_/dataset_encryption.py
This removes the `zfs.dataset.umount` option and replaces with `zfs.resource.unmount`. This is a private API only called internally. This will help speed up unmount operations since the new endpoint does not use our process pool.
NOTE: the legacy endpoint actually unmounted datasets recursively by default (in `py-libzfs`) but the new endpoint does not recursively unmount by default.
> NAS-137926 / 26.04 / remove zfs.dataset.umount (replace with zfs.resource.unmount)

- src/middlewared/middlewared/plugins/vm/vms.py
- src/middlewared/middlewared/pytest/unit/plugins/test_vm.py
* `enable_secure_boot` and `bootloader_ovmf` are **create-time variables**, but their validation is currently part of the **common validation logic**, which also runs during updates.
* As a result, VMs created **before this change** are incorrectly validated during updates, leading to user-facing validation errors.
* Additionally, the transition to **Debian Trixie** has removed the `OVMF_CODE.fd` file from the available choices. This causes problems when users creates a VM without explicitly defining an OVMF value.
* Move the validation for `enable_secure_boot` and `bootloader_ovmf` to the **VM creation logic only**, preventing validation errors during updates.
* Updated the right default value for bootloader_ovmf .
Original PR: https://github.com/truenas/middleware/pull/17340
> NAS-137540 / 25.10.0 / Secureboot attrs should only be validated at create time (by Qubad786)
