truenas/middleware

src/middlewared/middlewared/plugins/reporting.py
This commit exposes stats for interfaces in reporting plugin.
=> NAS-102817 / 11.3 / Expose interface statistics

src/middlewared/middlewared/etc_files/loader.py
=> fix(middlewared/etc): allow methods to not return anything

src/middlewared/middlewared/plugins/network.py
Also stop using code from freenasUI.
=> NAS-102910 / 12 / fix(middlewared/network): make VRRP scan work

src/middlewared/middlewared/alert/source/volume_rekey.py
git cherry-pick -x 34e6f78ad67639075dca1929adf8776b3f84f0d5
=> NAS-102828 / 11.3 / Do not run VolumeRekeyAlertSource on backup node (by themylogin)

src/freenas/etc/rc.conf.local
@william-gr I've missed a lot in initial PR!
=> NAS-102894 / 11.2 / Proper NFS rc.conf for HA

src/middlewared/middlewared/etc_files/rc.conf.py
git cherry-pick -x 068d9f44ba780a4d326ea1dd571e8f14b40e436f
=> NAS-102894 / 11.3 / Do not start NFS on HA standby node (by themylogin)

src/middlewared/middlewared/plugins/vm.py
This commit fixes a bug where when we validated a device while updating a VM, we used the vm instance which was saved in the database and not the one which had just been provided. This resulted in checks being performed on stale data and giving wrong results.
=> NAS-102979 / 11.3 / Bug fix for updating VM devices via VM service

src/middlewared/middlewared/plugins/rsync.py
This commit enforces a path limit for rsync tasks of 1023 characters ( inclusive ) as anything bigger then that is rejected by freebsd.
=> NAS-102955 / 11.3 / Enforce path limit for rsync

tests/api2/iscsi.py
added global target_id extent_id  portal_id  associate_id
remove the if statement for MOUNTPOINT
=> QE NAS-102990 Adding REST status code in ISCSI API v2 testing 

src/middlewared/middlewared/plugins/smart.py
This commit updates smart method params in a usage to reflect latest changes introduced to the method.
=> Update smart method usage

src/middlewared/middlewared/plugins/iscsi.py
=> NAS-102917 / 11.3 / fix(middleward/iscsi): `iscsi.portal.listen_ip_choices` to include VIP

gui/vm/migrations/0011_normalize_devices_attributes.py, gui/vm/models.py, src/middlewared/middlewared/plugins/vm.py
This PR introduces support for specifying CPU topology for VM's
=> NAS-102285 / 12 / Add ability to specify CPU topology for VM's

src/middlewared/middlewared/plugins/pool.py
=> NAS-100995 / 11.3 / feat(middlewared/pool): make sure SED disks are unlocked prior to format

src/middlewared/middlewared/plugins/network.py
=> NAS-102962 / 11.3 / feat(middlewared/network): require configured dhcp/ip to commit changes

src/freenas-installer/etc/install.sh
When reusing an old disk, there may be leftover pool labels in strange
places. Clear out any pre-existing labels when formatting disks with new
partitions in order to prevent import/mountroot errors at boot.
Ticket: NAS-103070
=> Clear pool labels from new partitions

src/freenas-installer/etc/install.sh
When reusing an old disk, there may be leftover pool labels in strange
places. Clear out any pre-existing labels when formatting disks with new
partitions in order to prevent import/mountroot errors at boot.
Also backported parts of the previous cleanup from 12 for diff reduction as a separate commit.
Ticket: NAS-103070
=> Clear pool labels from new partitions (11.3)

src/middlewared/middlewared/alert/source/boot_pool.py, src/middlewared/middlewared/alert/source/zpool_capacity.py, src/middlewared/middlewared/etc_files/crontab, src/middlewared/middlewared/etc_files/rc.conf.py, src/middlewared/middlewared/plugins/boot.py, src/middlewared/middlewared/plugins/bootenv.py, src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/sysdataset.py, src/middlewared/middlewared/plugins/zettarepl.py
=> NAS-103081 / 12 / feat(middlewared/boot): allow different boot pool name

src/middlewared/middlewared/plugins/vm.py
This commit introduces changes to fix a bug which expected device id to be present when a device was validated in vm's data. However this is not the case always i.e when we create a VM, device id's haven't been initialized.
We used vm's data to ensure we didn't have duplicates for disk devices. Now apart from id's we have paths unique for disks, if we find a path more then once in a VM, that means it has been duplicated. We use this to validate disk devices now.
=> NAS-103028 / 11.3 / Correctly validate disks for VMs

src/middlewared/middlewared/plugins/jail.py
This commit introduces changes so we are able to retrieve defaults for a plugin.
=> NAS-103010 / 11.3 / Retrieve plugin defaults

gui/choices.py
choices.py is no longer useful. This is just to silence traceback/log until its completely removed along with database change to sqlalchemy.
=> rm(gui/choices): remove notifier calls, they are no longer relevant

src/middlewared/middlewared/plugins/network.py
=> NAS-102615 / 11.3 / fix(middlwared/network): do not raise error if HA has not been setup yet

src/middlewared/middlewared/plugins/network.py
The shell was being killed, not tcpdump.
=> fix(middlewared/network): tcpdump not being killed

src/freenas/usr/local/libexec/truenas/carp-state-change-hook.py
This fixed importing pool in HA with OpenZFS
=> fix(ha): do not use absolute path for zpool

src/middlewared/middlewared/plugins/smart.py, src/middlewared/middlewared/service.py
git cherry-pick -x 3b3b15240525f74776b472a5be63441d649a2a97
=> NAS-103021 / 11.3 / Restart smartd on interval change (by themylogin)

src/middlewared/middlewared/plugins/dyndns.py
This commit adds validation for dyndns service
=> NAS-103131 / 11.3 / Add validation for dyndns service

src/middlewared/middlewared/plugins/filesystem.py
=> NAS-103151 / 11.3 / fix(middlewared/filesystem): increase limit from 1024b to 500KB for file_receive

src/middlewared/middlewared/plugins/iscsi.py
=> NAS-103154 / 11.3 / fix(middlewared/iscsi): always have a `disk` key

nas_ports/freenas/freenas-files/Makefile, nas_ports/freenas/freenas-installer/Makefile, nas_ports/freenas/freenas-installer/pkg-plist, nas_ports/freenas/freenas-migrate93/Makefile, nas_ports/freenas/freenas-pkgtools/Makefile, nas_ports/freenas/freenas-ui/Makefile, nas_ports/freenas/pipewatcher/Makefile, src/freenas-installer/etc/install.sh
This PR aims to unify installer for FN/TN
=> NAS-103108 / 12 / Unify Installer for FN/TN

src/middlewared/middlewared/plugins/account.py
=> NAS-103157 / 11.3 / fix(middlewared/account): validate home directory on update as well

tests/api2/dyndns.py
added a test for dyndns/provider_choices API
added a dyndns test with a not supported provider expect 422
=> QE NAS-103169 Replace dyndns provider by a supported provider in dyndns API testing

src/middlewared/middlewared/plugins/account.py
=> fix(middlewared/account): only check home if not /nonexistent

src/middlewared/middlewared/plugins/jail.py
This commit introduces changes which ensure that the default plugin index is automatically adjusted to match FN/TN.
=> NAS-103143 / 11.3 / Update plugin index to automatically reflect TN

src/middlewared/middlewared/plugins/system.py
This commit improves system.general validation settings
=> NAS-103204 / 11.3 / Improve system.general validation

src/middlewared/middlewared/etc_files/zerotier.py, src/middlewared/middlewared/plugins/etc.py, src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/sysdataset.py
This PR adds changes which enable us to have a persistent zerotier service which can be configured by the user to start/stop.
=> NAS-102472 / 12 / Allow persistent Zerotier service

src/middlewared/middlewared/plugins/system.py
This commit adds ability to tell if system configured memory is ECC based or not.
=> NAS-103228 / 12 / Ability to tell if memory is ECC based

src/middlewared/middlewared/plugins/jail.py
This commit fixes a regression from recent py-libzfs changes.
=> Bug fix for creating jails via middleware

src/middlewared/middlewared/plugins/update.py
=> NAS-103319 / 11.3 / fix(middlewared/update): allow a different update server

src/middlewared/middlewared/plugins/vm.py
This commit adds changes which make sure we don't add duplicate log handlers resulting in duplicate logs
=> NAS-103164 / 11.3 / Ensure we don't add duplicate log handlers

src/middlewared/middlewared/plugins/iscsi.py
This PR fixes following issues:
1) An issue where ipv6 wildcard address won't be accepted
2) We did not allow adding an authorized member to an existing group, this fixes that.
=> Bug fixes for iscsi plugin

src/middlewared/middlewared/plugins/iscsi.py
This commit fixes a bug where we didn't update the iscsi extent data and also improves validation for iscsi extent update.
=> NAS-103009 / 11.2 / Bug fix for updating iscsi extents

docs/api/resources/storage.rst
=> NAS-103367 / 11.3 / fix(api1.0): recordsize choice is 1M not 1024K

tests/api1/group.py, tests/api1/user.py, tests/api2/group.py, tests/functions.py
improved the code for the user API v1 testing
fixed the commented test in group API v1 testing
remove GET_USER function since the use off it is depricated
=> QE NAS-103091 Adding testing for /etc/group in FreeNAS

src/middlewared/middlewared/plugins/jail.py
This commit adds support for community repository.
=> NAS-103417 / 11.3 / Add support for community repo

src/middlewared/middlewared/main.py
@william-gr replacing py files does not help, problem is somewhere in the C code
With this solution after hour of running we got
```
709 23004 python3 /home/asyncioleak2.py
3923 22048 python3 /home/asyncioleak2.py
10581 22648 python3 /home/asyncioleak2.py
15150 22280 python3 /home/asyncioleak2.py
18717 22772 python3 /home/asyncioleak2.py
```
comparing with
```
709 22604 python3 /home/asyncioleak2.py
3923 21688 python3 /home/asyncioleak2.py
10581 21596 python3 /home/asyncioleak2.py
15150 21728 python3 /home/asyncioleak2.py
18717 21720 python3 /home/asyncioleak2.py
```
right after the start which looks good to me.
Tracebacks become a little bit strange but still readable
```
File "/usr/local/lib/python3.6/site-packages/middlewared/main.py", line 165, in …
```
=> NAS-103407 / 11.2 / Fix asyncio + futures memory leak on python 3.6

src/middlewared/middlewared/plugins/rsync.py
git cherry-pick -x fec9cf73bfe749a43fe4d49969c24c40b4531e03
Use notifier.get_user_obj / notifier.get_group_obj for validation.
=> NAS-103389 / 11.3 / Allow non-local users to be set in rsync modules (by anodos325)

src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/zfs.py
This PR introduces a new API for CRUD operations on user properties for zfs datasets
=> NAS-102504 / 12 / API for CRUD operations on user props for zfs datsets

src/middlewared/middlewared/plugins/jail.py
This PR introduces changes which help us improve speed while retrieving installed plugins and their related data.
=> NAS-103410 / 11.3 / Improve retrieval speed for plugin.query

src/middlewared/middlewared/plugins/zettarepl.py
@william-gr do you think we should do the same for iocage dataset?
=> NAS-103441 / 11.3 / Exclude .system dataset from replication.list_datasets

src/middlewared/middlewared/plugins/iscsi.py
=> NAS-103486 / 11.3 / fix(middlewared/iscsi): make sure disk exists

src/middlewared/middlewared/plugins/network.py
=> NAS-103493 / 11.3 / fix(middlewared/network): configure interfaces in correct order

src/middlewared/middlewared/plugins/filesystem.py
We should only have a single 'home' permissions choice and modify the
resulting ACL when the person is joined to AD.
We should also provide job progress for permissions-related jobs
(even if the actual progress of the winacl reset is opaque).
Also make filesystem.listdir ACL-aware.
=> NAS-103519 / 11.3 / Simplify default ACL choices

src/freenas/usr/local/libexec/nas/generate_afpd_conf.py
Only add bind parameter if the specified IP address is valid.
=> NAS-103297 / 11.2 / Refuse to bind netatalk to invalid IP addresses

src/middlewared/middlewared/etc_files/afpd.py
Only add bind parameter if the specified IP address is valid.
=> NAS-103297 / 11.3 / Refuse to bind netatalk to invalid IP

src/middlewared/middlewared/plugins/pool.py
=> NAS-103518 / 11.3 / fix(middlewared/pool): properly account for multipath disks

src/middlewared/middlewared/common/smart/smartctl.py, src/middlewared/middlewared/etc_files/smartd.py, src/middlewared/middlewared/plugins/disk.py, src/middlewared/middlewared/plugins/smart.py
Areca driver does not like parallel smartctl. Also, using cam to get temperature from such drives resulted in it being always 30 C.
=> NAS-103312 / 11.3 / Areca S.M.A.R.T. fixes

src/middlewared/middlewared/plugins/filesystem.py
On paths without nfsv4 ACL support (e.g. tmpfs), acl_is_trivial_np()
raises an OSError. In this case, catch the OSError and return True
because the filesystem by definition can't have an ACL.
=> NAS-103569 / 11.3 / Handle OSError in filesystem.acl_is_trivial

src/middlewared/middlewared/plugins/network.py
=> NAS-103303 / 11.3 / fix(middlewared/network): rollback for HA and sync routes after interfaces

src/middlewared/middlewared/plugins/network.py
=> NAS-103577 / 11.3 / fix(middlewared/network): make sure interface is UP before dhclient

src/middlewared/middlewared/plugins/system.py
=> feat(middlewared/system): add `product_type`

src/middlewared/middlewared/plugins/crypto.py, src/middlewared/middlewared/plugins/rsync.py
This PR adds support `ed25519` key for crypto plugin.
=> NAS-103337 / 12 / Add ed25519 key support

src/middlewared/middlewared/plugins/vpn.py
This PR adds reasonable defaults to VPN plugin models ensuring that the records are inserted in the database conforming to db constraints.
=> NAS-103651 / 12 / Add defaults for VPN plugin models

src/middlewared/middlewared/etc_files/local/nginx/nginx.conf, src/middlewared/middlewared/main.py
Also increase read timeout for downloads.
Ticket:	NAS-103620
=> NAS-103620 / 11.3 / fix(middlewared/download): do not close pipes for running download

gui/tools/autosnap.py
git cherry-pick -x 73c2f4944339ecd739aa9b0776f5e46baf350bc1
=> NAS-103653 / 11.2 / VMware errors have unreadable str(e) (by themylogin)

src/freenas/etc/rc.conf.local
=> NAS-103678 / 11.2 / make sure to not run vmware-checkvm on truenas

src/middlewared/middlewared/alembic/versions/12.0/2019-10-30_16-17_dataset_model.py, src/middlewared/middlewared/plugins/iscsi.py, src/middlewared/middlewared/plugins/jail.py, src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/sysdataset.py, src/middlewared/middlewared/plugins/vm.py, src/middlewared/middlewared/plugins/zfs.py
This PR adds support for native ZFS encryption.
=> NAS-103477 / 12 / Add Native ZFS Encryption support

src/middlewared/middlewared/etc_files/rc.conf.py
=> NAS-103678 / 11.3 / make sure to not run vmware-checkvm on truenas (by yocalebo)

gui/tools/autosnap.py, src/middlewared/middlewared/plugins/vmware.py
git cherry-pick -x 5129315570544816d78562a83aea132ea29f1be0
git cherry-pick -x 12b511f19052c3bae9d387a54d02677c454e059f
=> NAS-103613 / 11.3 / Remove legacy vmware snapshot alerts when updating/deleting vmware (by themylogin)

src/middlewared/middlewared/alert/source/ipmi_sel.py
Colud not find anything else to ignore here https://github.com/openbmc/ipmitool/blob/master/include/ipmitool/ipmi_sel.h#L297
=> NAS-103676 / 11.3 / Ignore OS Boot IPMI SEL events

src/middlewared/middlewared/plugins/network.py, src/middlewared/middlewared/plugins/s3.py
1) Extends ip choices method to filter static ips
2) Exposes bindip choices method for s3 service
3) Validate bindip attribute for s3 service
=> NAS-103779 / 12 / Expose bindip choices for S3 service

src/middlewared/middlewared/plugins/account.py
@william-gr we already have `self.send_small_file('/root/.ssh/authorized_keys')` in `sync_to_peer`
=> NAS-100287 / 12 / Update root's authorized_keys on backup node

src/middlewared/middlewared/plugins/account.py
@william-gr another question: why does it have to be su? Does `cp -a` not preserve something? Problem is that if user has e.g. file owned by root with 600 permissions, it won't be copied.
=> NAS-103847 / 11.3 / Fix setting user home directory

src/middlewared/middlewared/plugins/network.py
=> NAS-103809 / 11.3 / fix(middlewared/network): allow interace to be DOWN, explicitly

src/middlewared/middlewared/plugins/vm.py, src/middlewared/middlewared/plugins/zfs.py
This commit adds changes which raise an exception if snapshot creation fails.
=> NAS-103884 / 11.3 / Raise exception if snapshot creation fails

gui/tools/autosnap.py
git cherry-pick -x a398ae0842734f4e0630382a69ced3ddb92c56fc
git cherry-pick -x 5674a8508bd238c4362c85a001cac359e7998545
=> NAS-103611 / 11.3 / use the correct product name in autosnap.py (by yocalebo)

src/middlewared/middlewared/plugins/replication.py
Lola suggested this and I agree with her
=> NAS-103921 / 11.3 / Make replication task consistent with cloud sync

src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/utils/__init__.py, src/middlewared/middlewared/utils/io_thread_pool_executor.py, src/middlewared/middlewared/utils/os_.py
@themylogin  this was in another branch, I am not too attached to the implementation in case you would like to do it differently, but it seems to do the trick.
=> feat(middlewared): add simple OS compat layer

src/middlewared/middlewared/etc_files/local/collectd.conf, src/middlewared/middlewared/etc_files/local/nut/upsd.conf, src/middlewared/middlewared/etc_files/local/nut/upsmon.conf, src/middlewared/middlewared/plugins/ups.py
This PR introduces the following changes:
1) Correctly set ups details for collectd plugin
2) Ensure we respect the port settings for UPS service
=> NAS-103944 / 11.3 / Bug fixes for UPS

src/middlewared/middlewared/plugins/filesystem.py
Users frequently change these permissions and remove their ability
to access data.
=> NAS-103960 / 11.3 / Return EPERM on attempts to set permissions on pool root

src/middlewared/middlewared/plugins/idmap.py
Change to pass a string as the domain rather than an id.
=> Fix idmap.common_backend_compress for sqlalchemy

src/middlewared/middlewared/job.py
(cherry picked from commit 6353e749b85af021a54b6fbf785dd964361bbad3)
=> NAS-103679 / 11.3 / Do not hide CallError.extra from job

src/middlewared/middlewared/plugins/account.py
Convert group name to gid. If this fails, default to gid=-1 for filesystem.setperm call, which will preserve existing gid value.
=> NAS-104029 / 11.3 / Fix setting permissions on .ssh directory

src/middlewared/middlewared/plugins/crypto.py
This commit fixes an issue where on boot as network isn't configured, if a user has an ip address set for his ipv4/ipv6 field, automatic certificate setup fails validation as middlewared fails to find the ip.
=> NAS-104051 / 11.3 / Update certificate directly into database

src/middlewared/middlewared/plugins/nis.py
Properly set DSState when stopping plugin
=> NAS-104100 / 11.3 / Fix regression in NIS plugin

gui/network/migrations/0011_disable_offload_capabilities.py, gui/network/models.py, src/middlewared/middlewared/plugins/jail.py, src/middlewared/middlewared/plugins/network.py, src/middlewared/middlewared/plugins/vm.py
This PR introduces changes which ensure we disable NIC capabilities for interfaces being used by jail/vm when HA is licensed.
=> NAS-103963 / 11.3 / Disable NIC capabilities when using Jail/VM(s) for TN HA

src/middlewared/middlewared/plugins/directoryservices.py
Wrapper around private API call dscache.refresh.
=> NAS-103780 / 12 / Add directoryservices.cache_refresh method

src/middlewared/middlewared/plugins/datastore/read.py
(cherry picked from commit adf4f59e7ab92197e253c5776494fd3ac425b430)
=> Add offset support

src/middlewared/middlewared/plugins/vm.py, src/middlewared/middlewared/plugins/vm_/events.py, src/middlewared/middlewared/service.py
This commit adds events for VM's which emit status for different vm's wrt running/shutdown etc
=> NAS-100780 / 12 / Add events for vms

src/middlewared/middlewared/plugins/iscsi.py
git cherry-pick -x d6b9038886bb2d88263f8b3a7610c14c376fc8ce
=> NAS-103952 / 11.2 / Ensure objects exist before deleting them in iscsi plugin (by sonicaj)

src/winacl/winacl.c
Compare value of stored value of boot pool's device ID with the device ID
in the fts_entry's stat pointer. If they're the same, exit the fts loop
and return an error.
=> NAS-104149 / 11.2 / winacl - error out if fts_entry's dev_id is same as boot pool's one

src/freenas-installer/etc/install.sh
Make sure we can use the install menu option more than once.
JIRA: NAS-104251
=> NAS-104251 / 12 / Perform cleanup when the installer loops

src/freenas-installer/etc/install.sh
Make sure we can use the install menu option more than once.
JIRA: NAS-104251
=> NAS-104251 / 11.3 / Perform cleanup when the installer loops (by freqlabs)

src/middlewared/middlewared/etc_files/local/nslcd.conf
Fix bugs that were exposed in testing LDAPs with the LDAP directory service.
=> NAS-104245 / 11.3 / Fix errors in nslcd config generation

tests/api2/snmp.py, tests/api2/system_general.py
fix contact email in snmp API test
change system/general api test 10 get sysloglevel from system/advanced
=> QE Fix snmp and system_general api test 10

src/middlewared/middlewared/plugins/cloud_sync.py
git cherry-pick -x 799a58f07a279b1e20654dc15ed1352a1a8bca1d
=> NAS-104353 / 11.2 / Fix cloud sync with snapdir=visible (by themylogin)

src/middlewared/middlewared/rclone/remote/b2.py, src/middlewared/middlewared/rclone/remote/dropbox.py
@william-gr I hope we still have time to fix the naming for B2 option. It was never working.
=> NAS-104420 / 11.3 / Add Dropbox chunk_size option and fix B2 chunk_size option

gui/storage/models.py
Jira: https://jira.ixsystems.com/browse/NAS-104552
=> NAS-104552 / 11.2 / only run jail.query if system is licensed for jails

gui/storage/forms.py
@william-gr This fixes the `_upload` endpoint from being called multiple times with the `disk.decrypt` method.
=> NAS-104587 / 11.2 / fix calling _upload multiple times on GELI import

src/middlewared/middlewared/plugins/network.py
(cherry picked from commit b04da5809a10933b8afcef9cd9d79caf3eda94a8)
=> NAS-104633 / 11.3 / Extend ip choices method to filter static ips

src/middlewared/middlewared/etc_files/local/smb4_share_load.py, src/middlewared/middlewared/etc_files/smb_configure.py, src/middlewared/middlewared/plugins/smb.py
Linux-side of enums are placeholder values. I will properly set them once I have made ix-samba package for Linux.
=> NAS-104646 / 12.0 / Add support for platform-specific SMB-related commands and paths

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py, src/middlewared/middlewared/plugins/pool.py
=> NAS-104677 / 12.0 / feat(middlewared/pool): add passphrase to the hook args (by william-gr)

src/middlewared/middlewared/plugins/pool.py
There is a race condition with ZFS events.
Ticket:	NAS-104674
=> NAS-104674 / 12.0 / fix(middlewared/pool): use a lock for syncing encrypted disk table

src/middlewared/middlewared/etc_files/nsswitch.conf, src/middlewared/middlewared/plugins/service.py
We no longer compile with nss-mdns.
=> Minor fixes related to mdns / service announcements

src/freenas/etc/ix.rc.d/ix-netif, src/middlewared/middlewared/plugins/etc.py
This PR introduces changes to ensure that we generate nginx configuration after interfaces have synced.
=> NAS-104708 / 12.0 / Generate nginx configuration after interfaces have synced

src/middlewared/middlewared/plugins/vm.py
This commit fixes an issue where VNC device creation errored out when VM was created with VNC device specified in it's payload.
=> NAS-104722 / 12.0 / Bug fix for VNC device creation with VM

src/middlewared/middlewared/plugins/snapshot.py
git cherry-pick -x 6d2b3f27fc29f49faffab7ea39516ddaa59db80b
=> NAS-104729 / 12.0 / Fix displaying periodic snapshot task state (by themylogin)

src/freenas/debian/rules, src/freenas/debian/truenas-files.lintian-overrides
We will need a post install script to compare and replace/install files in /root/, but thats good enough for now IMO to have the package building.
=> fix(truenas-files): file-or-dir-in-home lintian

src/middlewared/middlewared/plugins/pool.py
There is a race condition with ZFS events.
Ticket:	NAS-104674
=> NAS-104674 / 11.3 / fix(middlewared/pool): use a lock for syncing encrypted disk table (by william-gr)

src/middlewared/middlewared/plugins/pool.py
=> NAS-104677 / 11.3 / feat(middlewared/pool): add passphrase to the hook args

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/filesystem.py
Automatically and explicitly add smb users to the builtin_users group.
Customize default ACL based on share type (appending builtin_users entry for SMB shares).
=> Extend integration of `smb` users and groups

src/middlewared/middlewared/etc_files/local/nslcd.conf, src/middlewared/middlewared/etc_files/local/openldap/ldap.conf, src/middlewared/middlewared/etc_files/local/smb4.conf, src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/ldap.py
=> synchronize 11.3 stable and master

gui/directoryservice/forms.py
Unencrypted keytab was being inserted into table
=> NAS-104878 / 11.3 / Fix APIv1 for kerberos keytab creation

src/middlewared/middlewared/plugins/kerberos.py
Unknown enctype may break processing of ktutil output.
=> NAS-104879 / 11.3 / Exclude unknown encytypes from ktutil choices

src/middlewared/middlewared/plugins/kerberos.py
When a foreign non-samba kerberos keytab contains multiple kvnos for
same principal and enctype middleware fails to remove. In this case,
we only need to remove the non-SMB principals so switch to removing
based exclusively on principal name rather than combination of
principal and enctype (and skip principals we've already seen).
=> NAS-104884 / 11.3 / Fix failure to remove non-samba principals

src/middlewared/middlewared/plugins/kerberos.py
Unknown enctype may break processing of ktutil output.
=> NAS-104879 / 12.0 / Exclude unknown encytypes from ktutil choices (by anodos325)

src/middlewared/middlewared/plugins/zettarepl.py
git cherry-pick -x bc3f11c7120603622788233b19b0faf247535983
=> NAS-104781 / 12.0 / Better replication progress reporting (by themylogin)

src/middlewared/middlewared/plugins/zettarepl_/state.py
git cherry-pick -x 95968adf2b6bbd0d30124b0e7481bba2b8d393df
=> NAS-104859 / 12.0 / Fix crash on trying to save deleted replication task state (by themylogin)

src/middlewared/middlewared/plugins/activedirectory.py
Error introduced when we switched to not perform simple binds.
=> NAS-104916 / 11.3 / Fix references for stored exceptions

src/middlewared/middlewared/plugins/jail_freebsd.py
This PR introduces changes where we gracefully handle the case when plugin repository is misconfigured and we don't either have the INDEX or plugin's manifest file.
=> NAS-104846 / 12.0 / Gracefully handle case where plugin repository might be misconfigured

src/middlewared/middlewared/plugins/datastore/read.py
This commit fixes an issue where we selected fields before going through extending phase while retrieving objects which resulted in extend phase not working for most services as it is dependent on keys which might not be present in the data as it had already been pruned.
=> NAS-104983 / 12.0 / Bug fix for select option

src/middlewared/middlewared/rclone/remote/swift.py
OpenStack Swift support for cloud sync.
=> NAS-105016 / 12.0 / OpenStack Swift support for cloud sync

src/freenas/etc/ix.rc.d/ix-syncmultipaths
=> NAS-105063 / 12.0 / fix(rc.d): make ix-syncmultipaths executable and depend on ix-syncdisks

src/middlewared/middlewared/plugins/disk.py
=> NAS-105059 / 12.0 / fix(middlewared/disk): do not use expiring disks for multipath

src/freenas/usr/local/sbin/firmware_update.py
=> NAS-104600 / 12.0 / Rewrite HBA firmware updater to suport 9400 series.

src/middlewared/middlewared/etc_files/grub.py, src/middlewared/middlewared/plugins/etc.py, src/middlewared/middlewared/plugins/system.py
=> NAS-105102 / 12.0 / feat(middlewared/system): serial console for Scale

src/middlewared/middlewared/plugins/device_/device_info_linux.py, src/middlewared/middlewared/plugins/pool.py
This PR introduces changes where we make TN Scale logs more verbose wrt retrieving disks and creating pools.
=> Verbose logging for TN Scale

src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/admin_group.py
git cherry-pick -x 892b59cd47214c45b23df6e5ff70b8410cbda794
=> NAS-104802 / 12.0 / Provide more useful text output for winbind errors (by anodos325)

src/middlewared/middlewared/plugins/activedirectory.py
Error introduced when we switched to not perform simple binds.
=> NAS-104916 / 12.0 / Fix references for stored exceptions (by anodos325)

src/middlewared/middlewared/plugins/datastore/event.py
This commit introduces changes where we skip sending update event if the row for which the event is desired has already been removed from the database.
=> Skip sending update event if row does not exist

src/middlewared/middlewared/plugins/update.py
If we merge this, https://github.com/freenas/webui/blob/master/src/app/pages/system/update/update.component.ts#L134 can be removed
=> NAS-104852 / 12.0 / Do not allow bogus update to already selected downgrade train (by themylogin)

src/freenas/etc/ix.rc.d/ix-update
git cherry-pick -x 87bc69afcaf374265486e24ef51a7445a8aa1ccd
=> NAS-105194 / 12.0 / Fix ix-update (by themylogin)

src/middlewared/middlewared/etc_files/local/smb4.conf
=> NAS-105186 / 12.0 / Fix idmap generation for RFC2307 backend (by anodos325)

src/middlewared/middlewared/plugins/cron.py
git cherry-pick -x 4b2dbbce3426537e66a0542e6e3c596d6c16aa7e
=> NAS-105239 / 11.3 / Mark cronjob as failed if it exists with non-zero exit status (by sonicaj)

src/middlewared/middlewared/common/environ.py, src/middlewared/middlewared/event.py, src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/network.py, src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py, src/middlewared/middlewared/plugins/system.py, src/middlewared/middlewared/service.py, src/middlewared/middlewared/worker.py
git cherry-pick -x abc4d45efa704668aa7cf7215fc1422bb3dd06fc
=> NAS-105207 / 12.0 / Propagate environment update to worker processes (by themylogin)

src/autotune/files/autotune.py
Should be no significant changes.
=> NAS-102818 / 12.0 / Slightly cleanup autotuner

src/middlewared/middlewared/plugins/filesystem.py
This ACl combination is always a mistake and shouldn't be permitted.
=> NAS-105231 / 11.3 / Prevent users from setting an ACL that lacks inheritable entries

src/middlewared/middlewared/plugins/pool.py
Allow quotas and refquotas of 0 through validators
=> NAS-105238 / 11.3 / Allow quotas and refquotas of 0 through validators (by anodos325)

src/middlewared/middlewared/client/client.py
=> fix race with SO_REUSEADDR and TIME_WAIT

tests/runtest.py
This is to run API test specific to scale
=> Adding --scale option to runtest

src/middlewared/middlewared/plugins/cloud_sync.py
=> NAS-105010 / 12.0 / fix(cloud sync): Take Snapshot option can not be used for datasets th… (by themylogin)

tests/api2/pool_dataset.py
git cherry-pick -x 47505372df7da6366d79b8ed150eb61ce8ebb5a5
=> NAS-105350 / 11.3 / Fix tests (by themylogin)

src/middlewared/middlewared/plugins/zfs.py
git cherry-pick -x c1bc4bb65b7b93a0c888fc9484313953d2f88714
=> NAS-105297 / 11.3 / Do not fail pool import if some datasets failed to mount (by sonicaj)

src/middlewared/middlewared/plugins/vmware.py, src/middlewared/middlewared/plugins/zettarepl.py
git cherry-pick -x 0417c51888fd7a8ee253caa915793ed7ff43a3e1
git cherry-pick -x cc65d8c2f7414552dec2d9e522064d4422857861
=> NAS-104542 / 12.0 / Turn vmware.periodic_snapshot_task_begin/end into a job (by themylogin)

src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/admin_group.py
Regression was introduced when splitting up SMB module into parts.
=> NAS-105463 / 12.0 / Fix smb.add_admin_group

src/middlewared/middlewared/client/client.py
This will avoid the client blocking waiting on the callback
=> fix(middlewared/client): run callback in another thread

tests/api2/activedirectory.py, tests/api2/rsync.py
gived a unique name to all activedirectory job_id
=> QE-281 Added "validate_rpath": False to FN 11.3 rsync API test 04

tests/api2/activedirectory.py, tests/api2/smb.py
remove test 57 since disable activedirector job is not found
=> QE-280-2 change assert of test_065 to look for both /%D/%U and /%U

src/middlewared/middlewared/plugins/system.py
We have been seeing usages with `-t 17` in some systems where the memory was ECC but the total width did not collaborate. So after discussing with nap, we decided we should continue with determining that a memory is ECC based on `-t 16`.
=> NAS-105504 / 12.0 / Use dmidecode -t 16 for determining ECC memory

src/freenas/boot/loader.conf, src/freenas/boot/lua/local.lua, src/middlewared/middlewared/etc_files/loader.py
Also removed redundant modules path variable from loader.conf.
=> NAS-105452 / 12.0 / Load openzfs-debug when booting kernel-debug

src/middlewared/middlewared/alert/service/mail.py
small fix to unify terminology for "email"
=> NAS-104078: Unify "Email" terminology

src/middlewared/middlewared/plugins/system.py
This commit adds changes which when license is updated, ensure we create a eula pending file
=> NAS-103161 / 12 / Create eula pending file on license update

src/middlewared/middlewared/plugins/disk_/temperature.py
git cherry-pick -x cce692d37172ab0230b1fc2dcda3fc2558fb7243
=> NAS-105568 / 12.0 / Disable disktemp collectd for mpr controllers (by themylogin)

src/middlewared/middlewared/plugins/activedirectory.py
"Legacy" AD configuration requires that the AD service be started and running on both controllers. Make call to standby controller to start AD once we've confirmed that it's working on the active controller.
=> NAS-105536 / 11.3 / Start AD on standby controller once active successfully starts

src/middlewared/middlewared/plugins/datastore/write.py, src/middlewared/middlewared/plugins/disk_/sync.py, src/middlewared/middlewared/pytest/unit/plugins/test_datastore.py
This PR adds changes to ensure that we retrieve correct primary key on insertion of a record in database.
=> NAS-105595 / 12.0 / Retrieve correct primary key on insertion of record in database

src/middlewared/middlewared/plugins/jail_freebsd.py
This commit introduces changes where we ensure that if an installed plugin is using a packagesite in it's new manifest which contains ABI, we correctly expand it keeping in line with the version plugin jail is on. This ensures that the user is informed of any plugin updates correctly.
=> NAS-105609 / 12.0 / Correctly validate if installed plugins require updates

src/middlewared/middlewared/plugins/disk.py
=> Revert "NAS-105568 / 11.3 / Disable disktemp collectd for mpr controllers"

tests/api2/jail.py, tests/api2/plugin.py
Also, update Jail FreeNAS release and plugin GitHub repos
=> QE-286 Change rslsync plugin for transmission plugin for plugin API testing

src/middlewared/middlewared/etc_files/motd
=> NAS-105685 / 12.0 / Update motd to reflect TrueNAS

src/middlewared/middlewared/etc_files/ctld.py
We have an issue with the underlying sysctl module not setting the values correctly and resulting in a SIGSEGV, so we instead use subprocess here to set the sysctl values.
=> NAS-105767 / 11.3 / Fix usages of sysctl module to use subprocess instead (by sonicaj)

src/middlewared/middlewared/main.py, src/middlewared/middlewared/pytest/unit/alert/source/test_ipmi_sel.py, src/middlewared/middlewared/pytest/unit/etc_files/test_smartd.py, src/middlewared/middlewared/pytest/unit/plugins/test_disk.py, src/middlewared/middlewared/pytest/unit/test_main.py, src/middlewared/middlewared/schema.py, src/middlewared/middlewared/utils/__init__.py
git cherry-pick -x ab3fe672614c7d078076e0962389454dafd8f961
git cherry-pick -x 5525f3d0d635520a124d8e68ada4c02d24127ee8
git cherry-pick -x d0209e1798d3f4f2a00b3678eeaad7fbdd5ce7ad
git cherry-pick -x d5cd44ff6501eb8d86705997ab94e99ab981c717
git cherry-pick -x 5c11074170a673a2eb61d204e00cdd0de297a8fb
git cherry-pick -x c6d0676ad6a9241f9a8f235e0366280a132f8d38
git cherry-pick -x 3eb24782b5674e1651480a787e4e0027e3fd75e9
git cherry-pick -x c8c15fa15a96596c906ec12e73a9c60054ccad01
=> NAS-105650 / 11.3 / Properly hide secrets from middleware log for ConfigService and CRUDService (by themylogin)

src/middlewared/middlewared/plugins/zettarepl.py, src/middlewared/middlewared/plugins/zettarepl_/state.py
git cherry-pick -x 997d59b29e17d17b74901c7c5ada62d8ccac484d
=> NAS-105464 / 12.0 / Do not make scheduled replication task WAITING if it is RUNNING (by themylogin)

src/middlewared/middlewared/logger.py, src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/zettarepl.py, src/middlewared/middlewared/service.py, src/middlewared/middlewared/worker.py
git cherry-pick -x 164aa93013ff4ec7f071f2f359ac310bb8b0b8fd
=> NAS-105485 / 12.0 / Reconfigure logging in worker processes (by themylogin)

src/middlewared/middlewared/plugins/afp.py
git cherry-pick -x 69a32573764612af2ef2fba7f56023bcb5848492
=> NAS-105454 / 12.0 / afp.bindip_choices (by themylogin)

src/middlewared/middlewared/plugins/pool.py
=> NAS-105782 / None / fix(middlewared/pool): get disks only for pool being exported

src/middlewared/middlewared/alert/source/quota.py
git cherry-pick -x 2767ee4f7550c361344e3d67e1513140b95be1b5
=> NAS-105684 / 12.0 / Fix quota alert (by themylogin)

src/middlewared/middlewared/plugins/pool.py
=> NAS-105782 / 12.0 / fix(middlewared/pool): get disks only for pool being exported

src/middlewared/middlewared/plugins/pool.py
=> NAS-105782 / 11.3 / fix(middlewared/pool): get disks only for pool being exported (by william-gr)

src/middlewared/middlewared/plugins/disk_/temperature.py
git cherry-pick -x 8174dae5fcca0d3e00f76b575ba232d9b68e0039
…oesnt report the value
=> NAS-105656 / 12.0 / Disk temperature: falling back to smartctl in case the SCSI command d… (by themylogin)

src/middlewared/middlewared/plugins/activedirectory.py
Filter for when to re-join AD was a little too strict. Users may
for reasons delete our computer account in active directory. This
can cause a difficult to diagnose and fix error in starting the
AD service.
=> NAS-105853 / 12.0 / Re-join active directory if user deleted our computer object

src/middlewared/middlewared/plugins/vm.py
If we asynchronously start VM's at boot, we have seen issues with libvirt where 1 or more VM's might not start as libvirt is unable to allocate network resources properly. So this commit changes that behaviour and we start VM's sequentially on boot.
=> NAS-105843 / 12.0 / Start VM's sequentially on boot

src/middlewared/middlewared/etc_files/local/smb4.conf, src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/groupmap.py, src/middlewared/middlewared/plugins/smb_/registry.py
Add some workarounds for lack of ACL support in OS. Set acl_xattr by default
and remove a few customizations until FreeNAS samba is ported to Linux.
=> Initial linux compatibility work for SMB service

src/middlewared/middlewared/plugins/pool.py
Revert more changes related to aclmode. Add validation error related
to aclmode property on Linux.
=> Fix aclmode validation for TN Scale

src/middlewared/middlewared/plugins/network.py
git cherry-pick -x 121fece94c4993cb854a0d15fc601751abaa4e4f
git cherry-pick -x a9864061621ab4142f3082b4b60ebfa7d10995df
…as changed and stop losing DB interface order by using set
=> NAS-105764 / 11.3 / LAGG interface uses MAC of first port; Reconfigure it if first port h… (by themylogin)

src/middlewared/middlewared/etc_files/group, src/middlewared/middlewared/etc_files/master.passwd, src/middlewared/middlewared/plugins/nis.py
Ensure that NIS separator is added on new line.
=> NAS-105122 / 11.3 / NIS - regenerate master.passwd after configuration changes

src/middlewared/middlewared/plugins/alert.py
=> NAS-105792 / 12.0 / Do not alerts of unrelated levels and never sent alerts to the list o… (by themylogin)

src/middlewared/middlewared/plugins/nis.py
Ensure that NIS separator is added on new line.
=> NAS-105122 / 12.0 / NIS - regenerate master.passwd after configuration changes (by anodos325)

src/middlewared/middlewared/plugins/account.py
Convert group.do_create into wrapper around group.create_internal()
which has an optional fast_create argument that will avoid the
extra User reload and SMB group mapping. Group mappings for auto-generated
groups are generally undesirable because:
1) You end up with two identically named principals with different SIDs
which is confusing for end-users.
2) It increases the amount of churn in the group-mapping database.
=> NAS-105655 / 11.3 / Do not create SMB group mappings for auto-generated primary groups

src/middlewared/middlewared/etc_files/rc.conf.py, src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/nfs.py
git cherry-pick -x a21b3df4152e091db9bd15b5df90fc67ef6920a5
=> NAS-105956 / 12.0 / Give proper meaning for nfs.v4_krb (by themylogin)

src/middlewared/middlewared/plugins/network.py
The other changes will need to be made in TrueNAS repo.
=> NAS-105965 / 11.3 / fix rollback operation on TN HA (by yocalebo)

src/middlewared/middlewared/etc_files/rc.conf.py
Fix problem related with write tunables in rc.conf
=> NAS-105940 / 12.0 / NAS-105940: Fix problem related with write tunables in rc.conf

src/middlewared/middlewared/etc_files/rc.conf.py
Fix problem related with write tunables in rc.conf
=> NAS-105940 / 11.3 / NAS-105940: Fix problem related with write tunables in rc.conf (by bastiao)

src/middlewared/middlewared/plugins/interface/bridge.py, src/middlewared/middlewared/plugins/network.py
git cherry-pick -x 5bb9c043c52cd1b9d03e32245880d9cb4ec21648
=> NAS-105700 / 12.0 / Properly handle bridge MTU (by themylogin)

tests/api2/pool_dataset_encryption.py, tests/runtest.py
update skip_for_ha in pool_dataset_encryption
=> QE-303 puting jail and plugin to skip_tests test list of runtest.py

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py, src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/remote.py
Taken from https://github.com/iXsystems/truenas/pull/447/files
=> Properly handle HA connection errors

src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/kerberos.py
This removes dependency openldap dependency in AD plugin and
simplifies our code significatnly. It will also make future support
for LDAP channel binding simpler.
=> NAS-106023 / 12.0 / Use CLDAP for determining domain and site information

src/middlewared/middlewared/plugins/activedirectory.py
We set site-specific kerberos servers if the NAS is located in
a non-default AD site and there are more than three DCs in the
site. This caused a testing escape and corresponding regression
after some changes to other parts of the AD plugin.
- Pass AD config from set_kerberos_servers() to get_kerberos_servers()
to avoid an extra unnecessary call to get the config.
- Fix a few typos
- Ensure that servers are added as a space-separated list for
datastore insertion.
=> NAS-106010 / 11.3 / Fix activedirectory.set_kerberos_servers

tests/api2/pool_scrub.py
=> QE-305 added test to get scrub_id of the pool use for pool/scrub testing

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
[EFAULT] 'FailoverService' object has no attribute 'call_remote'
File "/usr/local/lib/middlewared_truenas/plugins/failover.py", line 1199, in upgrade_pending
assert self.call_remote('core.ping') == 'pong'
AttributeError: 'FailoverService' object has no attribute 'call_remote'
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.8/site-packages/middlewared/main.py", line 135, in call_method
result = await self.middleware._call(message['method'], serviceobj, methodobj, params, app=self,
File "/usr/local/lib/python3.8/site-packages/middlewared/main.py", line 1172, in _call
return await run_method(methodobj, *args)
File "/usr/local/lib/python3.8/site-packages/middlewared/main.py", …
=> NAS-106046 / 12.0 / use middleware.call_sync

src/middlewared/middlewared/plugins/vm.py
PCI-E passthru support in vm plugin
ok to test
=> NAS-100045 / 12.0 / NAS-100045 PCI-E passthru support (libvirt based)

src/middlewared/middlewared/plugins/activedirectory.py
Fix regression in activedirectory.leave() caused by changing kinit
method. Pass credentials to kerberos.do_kinit().
=> Pass user-provided creds in activedirectory_leave to kinit

src/middlewared/middlewared/plugins/service_/services/netbios.py
Service name for netbios name server is nmbd.
=> NAS-106064 / 12.0 / Fix regression in service announcements

src/middlewared/middlewared/plugins/gluster_linux/peer.py, src/middlewared/middlewared/plugins/gluster_linux/volume.py
=> NAS-106082 / 12.0 / fix gluster API

src/middlewared/middlewared/etc_files/syslogd.py
Same as PR: https://github.com/freenas/freenas/pull/4764 but  just for 12
=> NAS-105997 / 12.0 / configure newsyslog to manage failover related logs

src/middlewared/middlewared/alert/source/active_directory.py, src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/ldap.py, src/middlewared/middlewared/plugins/nis.py
Ensure that stale state cache gets updated if these calls succeed.
=> NAS-106148 / 12.0 / Update directory service state to "HEALTHY" as needed in .started()

src/middlewared/middlewared/plugins/update.py
`UNAVAILABLE` status doesn't really make sense if HA is non-functional.
=> NAS-106164 / 12.0 / check HA status before running update.check_available

src/freenas/etc/ix.rc.d/ix_sshd_save_keys
(cherry picked from commit 9c5f3337cf55f3c8061135bb70558be190881802)
=> Fix ix_sshd_save_keys

tests/api2/host_key.py, tests/runtest.py
added test to grabe ssh-keyscan before and after reboot
added test to reboot and wait
added test to compare ssh-keyscan output from before and after reboot
=> QE-NAS-106173 added host_key.py to test host key is persitent

tests/api2/host_key.py, tests/runtest.py
added test to grabe ssh-keyscan before and after reboot
added test to reboot and wait
added test to compare ssh-keyscan output from before and after reboot
added 'host_key' in the list to skip for HA
=> QE NAS-106173 12.0 added host_key.py to test host key is persitent

tests/api2/host_key.py
=> QE NAS-106173 12.0 adding code in host_key test 02 to wait for ping to go way

tests/api2/host_key.py
changed host_key test to loop true all line in the output in instead looking to be edentical
=> QE NAS-106173 12.0 replaced condiditon with pytest.mark.timeout in host_key test 02

src/middlewared/middlewared/plugins/network.py
Fix issue related static routes cannot be saved with empty description
=> NAS-106209 / 12.0 / NAS-106209: Fix issue related static routes cannot be saved with empty description

tests/api2/host_key.py, tests/runtest.py
changed host_key test to loop true all line in the output in instead looking to be edentical
=> QE-NAS-106173-11.3 replaced condiditon with pytest.mark.timeout in host_key test

tests/api2/alert.py
replace API search by a for loop
added pytest.mark.timeout to time out the loop after 80 second
=> QE-344 Removing seach in all test that use alret/list in alert testing

tests/api2/group.py, tests/api2/user.py
changed user test 08 to use shell variable
changed user_id to be grab from user creation
added code to grab the goup id from group API
added line to make sure we get roog group instead of wheel group for scale
=> QE-347 12/Scale Fixed group id and shell in user API testing for scale

src/middlewared/middlewared/plugins/system.py
Other tools can output similar output.
Ticket:	NAS-106251
=> NAS-106159 / 12.0 / debug: handle malformed progress reporting lines

src/middlewared/middlewared/plugins/interface/bridge.py, src/middlewared/middlewared/plugins/network.py
This commit introduces changes where if we have a network config with a chain `physical iface -> vlan -> bridge` ( all having say MTU of 9000 ), we won't be able to set a custom MTU for the ifaces if specified because interfaces are synced after bridges have been setup.
Why this is an issue is because when we add the members to the bridge we configure their MTU and if up in the chain we have lower MTU values, we can't change the MTU.
=> NAS-106306 / 12.0 / Make sure MTU is properly configured at boot for interfaces

src/middlewared/middlewared/plugins/iscsi.py
@william-gr do we want to put OS team to work instead to figure out what is the proper solution?
=> NAS-105030 / 11.3 / Fix exporting pool with iSCSI shares

src/middlewared/middlewared/etc_files/ntp.conf
12 already does this but it should be in 11.3 as well for obvious reasons.
=> NAS-106139 / 11.3 / restrict ntpd traffic to configured servers

src/middlewared/middlewared/etc_files/syslogd.py
When specifying a listening port on syslog-ng, if you do not specify the `network()` driver it will bind to all available interfaces by default.
This change does 2 things.
1. use the network() driver to prevent syslog-ng from binding to all interfaces
2. change the formatting of the entries so the config file is more readable
=> NAS-106062 / 11.3 / fix syslog-ng binding to all ints on TN HA (by yocalebo)

src/freenas/etc/ix.rc.d/ix-syncdisks, src/freenas/etc/rc.d/devd, src/middlewared/middlewared/job.py, src/middlewared/middlewared/plugins/device.py, src/middlewared/middlewared/plugins/disk.py
* Wait for devd in boot-time disk.sync_all
* Better logging in disk.sync_all
* No unnecessary updates in disk.sync_all
=> NAS-105943 / 11.3 / disk.sync_all improvements

src/middlewared/middlewared/plugins/system.py
Other tools can output similar output.
Ticket:	NAS-106251
=> NAS-106159 / 11.3 / debug: handle malformed progress reporting lines (by william-gr)

tests/api2/update.py
remove FreeNAS related code in update API test 00
=> QE-353 Change update API test 00 to avoid internal update on non internal

src/freenas/usr/local/etc/syslog-ng.conf.freenas
I will fix this when 11.3 repo code freeze gets lifted and this commit: 53a897782fde3e81e49904ecb8209238dbcbae05 is merged 1st
=> NAS-105985 / 11.3 / suppress repetitive log msgs that occur more than once in 60 secs (by yocalebo)

src/middlewared/middlewared/plugins/disk_/swap_configure.py
git cherry-pick -x 6da1940177f610325218bc1ad04720fdf350a81f
=> NAS-106454 / 12.0 / Fix savecore error logging (by themylogin)

src/middlewared/middlewared/plugins/system.py
git cherry-pick -x 51019f5b88a6b71ee72c3e9612bc22c77e534faa
=> NAS-106459 / 11.3 / Enable crash/usage for all products (by william-gr)

src/middlewared/middlewared/plugins/activedirectory.py
Due to design differences in many Linux AD domains, we should test more DCs trying to find a working NTP server. Original design was to only check against PDC emulator, this was later revised to check additional DC. After multiple reports of domains transitioning to a faulted state after failing this test due to Linux admins not running an NTP server on their AD domain controllers, we should probably become even more lax about this check. 
The key thing that we're concerned about here is that our clock hasn't drifted too far from the kerberos servers in the domains, and provide an error message to users if it is getting close to the point where kerberos is likely to break.
=> AD: cycle through more DCs as part of NTP check

src/middlewared/middlewared/plugins/nfs.py
…p to understand which exact address is causing issues
=> NAS-106461 / 12.0 / Prevent duplicate IP addresses in NFS export from causing issues. Hel… (by themylogin)

src/middlewared/middlewared/plugins/network.py
@william-gr made a fresh PR for this issue using the correct branch name 😃
=> NAS-106366 / 12.0 / loosen restrictions on network config for HA

src/middlewared/middlewared/job.py, src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/zfs.py, src/middlewared/middlewared/utils/service/__init__.py, src/middlewared/middlewared/utils/service/call.py, src/middlewared/middlewared/worker.py
* Do not run async functions in process pool
* Do not use new IO thread if we are calling synchronous method from call_sync
* Do not use new process when calling process pool method from process pool
=> NAS-106511 / 12.0 / asyncio/thread pool/process pool juggling improvements

src/middlewared/middlewared/plugins/filesystem.py
Due to ACL parsing error in POSIX1e code on FreeBSD, paths
were being incorrectly labelled as having an ACL. Fix POSIX1e
parsing on FreeBSD, but bypass this for acl_is_trivial() since
we don't currently support POSIX1e ACLs on FreeBSD through middleware.
=> NAS-106512 / 12.0 / ACLs: fix acl_is_trivial on FreeBSD platform

src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
=> Revert "NAS-106513 / 12.0 / failover service traceback"

src/middlewared/middlewared/plugins/system.py
@william-gr I've chosen to treat all non-licensed BHYVE vms as CORE. Our internal bhyve HA instances will return enterprise but I expect that since they're fully licensed and are fully operational HA "appliances". Let me know if this isn't the path you want to take.
=> NAS-106520 / 12.0 / fix product_type method on bhyve VMs

src/middlewared/middlewared/plugins/system.py
=> Revert "NAS-106520 / 12.0 / fix product_type method on bhyve VMs"

src/fenced/fenced/disks.py, src/fenced/fenced/exceptions.py, src/fenced/fenced/fence.py, src/fenced/fenced/logging.py, src/fenced/fenced/main.py
This is 100% dependent on the PR in the py-cam library here: [https://github.com/freenas/py-cam/pull/3](PR)
=> NAS-106482 / 12.1 / nvme reservation support for fenced

src/middlewared/middlewared/plugins/network.py
@yocalebo what did you intended to do with https://github.com/freenas/freenas/pull/4959/files#diff-c44b6d54b740097b6b338bb38f20ffd3L1004 ? It broke on FreeNAS where we don't have failover plugin
=> Fix bugs introduced in #4959

src/middlewared/middlewared/plugins/account.py
=> NAS-106570 / 12.1 / There is no skel dir in SCALE

src/middlewared/middlewared/etc_files/smb_configure.py
During system dataset import / SMB configuration, ensure that
the LDAP bind credentials are stored in secrets.tdb. This is only
done when LDAP is enabled and configured with samba schema
extensions.
=> NAS-106577 / 11.3 / Re-initialize secrets.tdb in LDAP environments on SMB setup

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
We no longer maintain sentinel files to indicate users / groups. ix-ldap script no longer exists. We should also refresh failover
status on switching to carp backup.
=> Remove legacy SMB-related items from failover events

src/middlewared/middlewared/client/client.py, src/middlewared/middlewared/client/utils.py
=> NAS-106589 / 12.1 / Fix midclt job with null message

src/middlewared/middlewared/client/client.py, src/middlewared/middlewared/client/utils.py
=> NAS-106589 / 12.0 / Fix midclt job with null message (by william-gr)

src/middlewared/middlewared/plugins/system.py
git cherry-pick -x bed3715e261908ba461e53c12a9cf796df3c08fd
=> NAS-106530 / 11.3 / Donot create swap partition for TN enterprise on pool creation (by sonicaj)

src/middlewared/middlewared/plugins/filesystem.py, src/winacl/winacl.c
Chroot() into directory that will have permissions change rather
than parent directory. Fix path rewriting for chroot in winacl.c.
=> NAS-106686 / 12.1 / Fix middleware chroot behavior for permissions change

src/middlewared/middlewared/plugins/filesystem.py, src/winacl/winacl.c
Chroot() into directory that will have permissions change rather
than parent directory. Fix path rewriting for chroot in winacl.c.
=> NAS-106686 / 12.0 / Fix middleware chroot behavior for permissions change (by anodos325)

src/freenas/etc/ix.rc.d/ix-sed
=> NAS-106004 / 11.3 / Fix order for ix-sed

src/freenas/etc/ix.rc.d/ix-sed
=> NAS-106004 / 12.0 / Fix order for ix-sed (by william-gr)

src/freenas/etc/ix.rc.d/ix-sed
=> NAS-106004 / 12.1 / Fix order for ix-sed (by william-gr)

tests/api2/test_004_disable_failover.py, tests/api2/test_010_enable_failover.py, tests/api2/test_790_update.py, tests/runtest.py
Adding tests to disable and enable failover for HA testing
=> QE-364 / 12.1 / Adding update option to run the update API test

src/fenced/fenced/disks.py, src/fenced/fenced/exceptions.py, src/fenced/fenced/fence.py, src/fenced/fenced/logging.py, src/fenced/fenced/main.py
This is 100% dependent on the PR in the py-cam library here: [https://github.com/freenas/py-cam/pull/3](PR)
=> NAS-106482 / 12.0 / nvme reservation support for fenced (by yocalebo)

src/middlewared/middlewared/plugins/vm/devices/nic.py
When we attach a physical NIC to a newly created linux bridge which has not been configured with an IP, and then use that bridge for VM's, we see a problem where host is unable to connect to guest and vice versa. This behaviour is slightly different then what we have in FreeBSD. References:
1) https://unix.stackexchange.com/questions/86056/why-does-linux-require-moving-ip-from-eth-interface-to-bridge-interface
2) https://unix.stackexchange.com/questions/319979/why-assign-mac-and-ip-addresses-on-bridge-interface
3) https://superuser.com/questions/1219223/linux-bridge-network-influenced-by-route-table
So in order to have a configuration where guest is able to talk to host and vice versa, we have following potential solutions:
1) Use macvlan/macvtap interfaces. They will allow VM to access …
=> NAS-106773 / 12.1 / Host guest configuration for KVM guests

src/middlewared/middlewared/plugins/crypto.py
Following latest apple guidelines, we make SAN field required:
https://support.apple.com/en-us/HT210176
=> NAS-106784 / 12.1 / Make SAN required for certificates

src/middlewared/middlewared/plugins/crypto.py
Following latest apple guidelines, we make SAN field required:
https://support.apple.com/en-us/HT210176
=> NAS-106784 / 12.0 / Make SAN required for certificates (by sonicaj)

src/middlewared/middlewared/etc_files/local/smb4.conf, src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/smb.py
Ensure that we're using correct platform-aware paths for these
directories.
=> NAS-106833 / 12.1 / Scale SMB - override build options for statedir and private dir

tests/api2/ups.py
Also Added monpwd in the list to verify
=> QE-371 / 12.0 / Adding monpwd to the ups API test 04 and 17

src/freenas/boot/loader.conf
=> NAS-106843 / 12.1 / FC ports in target mode by default

src/freenas/boot/loader.conf
=> NAS-106843 / 12.0 / FC ports in target mode by default (by william-gr)

src/middlewared/middlewared/plugins/disk.py
git cherry-pick -x e7aaef5e38713d15a56eadfc7c48338ed8db7708
=> NAS-106864 / 12.1 / NVMe SED support (by themylogin)

README.md
And test PR builder while at it
=> Remove old build status

tests/api2/cloudsync.py, tests/runtest.py
the test is runing outside of the NAS we need to ssh to read the freenas-test.txt
=> QE-372 / 11.3 / fix cloudsync API test 06

tests/api2/test_130_cloudsync.py
Also, fix cloudsync API test 06 since the test is runing outside of the NAS we need to ssh to read the freenas-test.txt
=> QE-372 / 12.1 / Scale / Fix cloudsync API test credentials and test fixture

tests/api2/cloudsync.py
the test is runing outside of the NAS we need to ssh to read the freenas-test.txt
=> QE-372 / 12.0 / fix cloudsync API test 06

src/middlewared/middlewared/plugins/smb_/registry.py
=> NAS-106948 / 12.0 / Correct typo in vfs_recycle options (by anodos325)

src/middlewared/middlewared/plugins/smb_/registry.py
=> NAS-106948 / 12.1 / Correct typo in vfs_recycle options (by anodos325)

tests/api2/test_030_activedirectory.py
When TrueNAS joins an AD domain, a kerberos keytab must be
auto-generated for the AD machine account. These two tests verify
that our current system keytab contains entries, and verifies
that these entries are regenerated if the are removed, and the
kerberos service is stopped and restarted. Expected behavior
after the kerberos start is that we have keytab entries and
a valid kerberos ticket.
Related to NAS-106963
=> NAS-106978 / 12.1 / Add regression tests for AD machine account keytab generation (by anodos325)

src/middlewared/middlewared/plugins/vpn.py
We add server/client rc files during boot phase, however at that time the rcorder has already been calculated and it is not changed resulting in openvpn server/client services not starting on boot
=> NAS-107031 / 12.1 / Start openvpn server/client services on boot if enabled

src/middlewared/middlewared/plugins/vpn.py
We add server/client rc files during boot phase, however at that time the rcorder has already been calculated and it is not changed resulting in openvpn server/client services not starting on boot
=> NAS-107031 / 12.0 / Start openvpn server/client services on boot if enabled (by sonicaj)

src/freenas-installer/etc/install.sh
This was a case that had been overlooked while cleaning up and
restructuring the installer.  We were formatting for any install that
was not an inplace upgrade.
Factor out a check for if we're doing an upgrade vs fresh install to
make things a bit more readable.  Use it to rewrite some of the logic
for deciding how to proceed during installation.  Don't format the disks
when doing an inplace fresh install to a BE.
While here, fix a bug that was encountered in testing the patch where an
uninitialized variable was reused when starting over the installer,
causing disks to appear twice in the disk list.
Ticket: https://jira.ixsystems.com/browse/NAS-106777
=> NAS-106777 / 12.1 / install.sh: Fix fresh installs to a BE

src/freenas-installer/etc/install.sh
This was a case that had been overlooked while cleaning up and
restructuring the installer.  We were formatting for any install that
was not an inplace upgrade.
Factor out a check for if we're doing an upgrade vs fresh install to
make things a bit more readable.  Use it to rewrite some of the logic
for deciding how to proceed during installation.  Don't format the disks
when doing an inplace fresh install to a BE.
While here, fix a bug that was encountered in testing the patch where an
uninitialized variable was reused when starting over the installer,
causing disks to appear twice in the disk list.
Ticket: https://jira.ixsystems.com/browse/NAS-106777
=> NAS-106777 / 12.0 / install.sh: Fix fresh installs to a BE (by freqlabs)

src/middlewared/middlewared/etc_files/crontab, src/middlewared/middlewared/plugins/cron.py, src/middlewared/middlewared/plugins/rsync.py
Also prevent rsync jobs from queueing up.
I'll backport from 12.0 to 12.1
=> NAS-106713 / 11.3 / Prevent queued and then disabled cron tasks from executing.

src/middlewared/middlewared/plugins/account.py
In case of moving location of home directory from path a to path b, if path b
does not exist, we need to explicitly set permissions as well strip any ACL
on the path in order to ensure that premissions from original path are preserved.
Preference for new mode is as follows:
1. user-supplied mode in 'user.update' call
2. existing mode on old path
3. default mode. Since this is most likely an error condition, default is 0700.
=> NAS-107074 / 11.3 / Permissions are incorrect on home directory move (by anodos325)

src/middlewared/middlewared/plugins/cloud_sync.py
git cherry-pick -x c9796c22b105c7de7f42285087efbc836cabc286
=> NAS-102808 / 11.3 / Abort cloudsync task on deletion (by themylogin)

src/middlewared/middlewared/plugins/boot_/boot_loader_linux.py
@sonicaj these changes are related to https://github.com/truenas/truenas-build/pull/35
=> GRUB NVMe support

src/middlewared/middlewared/plugins/nfs.py
git cherry-pick -x 1d4f18292fc43ede4661c59ee29d82cbc2e07007
=> NAS-107082 / 11.3 / Make v4_krb_enabled a bool (by themylogin)

src/middlewared/middlewared/plugins/zettarepl.py
git cherry-pick -x 684cbfa0788ce1ee2584de37d782cf323eb6dfa0
… creating new replication task.
This happens because SQLite IDs can duplicate deleted rows.
=> NAS-107099 / 11.3 / Do not display previous replication task status after deleting it and… (by themylogin)

tests/api2/user.py
=> NAS-107130 / 12.0 / Add test to verify builtin users are not smb users

src/freenas/boot/loader.conf
=> NAS-107010 / 12.0 / Disable L2ARC rebuild for BETA2 (by william-gr)

src/middlewared/middlewared/plugins/account.py
"smb" True -> False should result in passdb removal
"smb" False -> True without password should raise validation error
"smb" False -> True with password should result in passdb insertion
=> NAS-107135 / 12.1 / Ensure passdb insertions and removals correspond with 'smb' checkbox

tests/api2/test_011_user.py
=> NAS-107130 / 12.1 / Add test to verify builtin users are not smb users (by anodos325)

src/middlewared/middlewared/plugins/network.py
In a previous commit here: 886ca8eb4294aabe17c6b1c5cbe4b1d98f14a291 I allowed "empty" interface creation for obvious reasons.
Schema validation prevents the failover group from being null. For example, create lagg0 and give it a default MTU of 1500. Go back and edit and try to change the MTU to 9000, it will error out.
I've also fixed a few validation errors.
- show the lag name in the validation error instead of the interface name when trying to edit a child member of the lag
- Clarify the verbiage the validation errors wrt to failover
- added webUI commit here: 0b494dd7570f2f1f96092eb3ec7f8071af3f6ba4 to make failover_vhid a drop-down so middlewared
can do proper validation on it (was being sent as an empty string)
- make it so that you can't edit a child interface of a lag and add a …
=> NAS-107116 / 12.1 / allow editing empty interfaces on HA

src/middlewared/middlewared/plugins/disk.py
git cherry-pick -x e7aaef5e38713d15a56eadfc7c48338ed8db7708
=> NAS-106864 / 12.0 / NVMe SED support (by themylogin)

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py, src/middlewared/middlewared/etc_files/syslogd.py, src/middlewared/middlewared/logger.py
=> NAS-107022 / 12.0 / save failover logs in /root/syslog like 11.3 (by yocalebo)

src/middlewared/middlewared/plugins/account.py
"smb" True -> False should result in passdb removal
"smb" False -> True without password should raise validation error
"smb" False -> True with password should result in passdb insertion
=> NAS-107135 / 12.0 / Ensure passdb insertions and removals correspond with 'smb' checkbox

tests/api2/smb_registry.py
Add tests for a few additional methods of switching between "homes"
and regular shares. Verify that service.reload cifs re-synchronizes
the registry.
Related to NAS-107154
=> NAS-107156 / 12.0 / Expand testing for SMB homes shares

src/middlewared/middlewared/plugins/disk.py
@william-gr I'll backport from 12.0 to 12.1
=> NAS-107035 / 11.3 / Properly calculate swap partition size on 4k sector disks

src/middlewared/middlewared/plugins/account.py
Also ensure that next_gid is at least 1000
Related to NAS-107135
Regression tests added in NAS-107142
=> NAS-107143 / 12.1 / Ensure groupmap entries are properly added / deleted on group.update

src/middlewared/middlewared/plugins/account.py
Also ensure that next_gid is at least 1000
Related to NAS-107135
Regression tests added in NAS-107142
Original PR: https://github.com/freenas/freenas/pull/5417
=> NAS-107143 / 12.0 / Ensure groupmap entries are properly added / deleted on group.update (by anodos325)

src/middlewared/middlewared/plugins/activedirectory.py
re-initialize secrets.tdb. Rename old one to a backup file. Odds of
repeatedly joining / leaving AD are extremely low and so we don't have
to worry about a couple of these accumulating.
Clear out the backup of the domain secrets in our config file.
Flush samba's cache after successfully leaving the domain.
=> NAS-107107 / 11.3 / Clear any potential stale state after leaving AD domain

src/freenas-installer/etc/install.sh
=> NAS-106955 / 12.1 / Clarify reboot instructions in installer

src/middlewared/middlewared/plugins/smb.py
If for some reason the path is ripped out before the SMB share is deleted
this can cause failure to remove entry from share_info.tdb.
In this situation, log what happened but allow share deletion to continue.
=> NAS-107160 / 11.3 / Log sharesec delete errors

src/middlewared/middlewared/plugins/cloud_sync.py
git cherry-pick -x 1f255797ad49bcf9de5aca2d347ad2a2edb222eb
Original PR: https://github.com/freenas/freenas/pull/5415
=> NAS-106999 / 12.1 / Human-readable error for deleting used cloud credential (by themylogin) (by bugclerk)

tests/api2/ad_kerberos.py
=> NAS-107169 / 11.3 / Add basic set of tests to verify nfs spn in AD environments

tests/api2/test_032_ad_kerberos.py
Related to NAS-107166
Original PR: https://github.com/freenas/freenas/pull/5457
=> NAS-107169 / 12.1 / Add basic set of tests to verify nfs spn in AD environments (by anodos325)

tests/api2/ad_kerberos.py
Related to NAS-107166
Original PR: https://github.com/freenas/freenas/pull/5457
=> NAS-107169 / 12.0 / Add basic set of tests to verify nfs spn in AD environments (by anodos325)

tests/api2/acl.py
Verify that ALLOW and DENY ACEs do the right thing on the OS-side.
=> NAS-107215 / 11.3 / Add functional tests for ZFS ACLs

src/middlewared/middlewared/plugins/interface/lag.py
https://jira.ixsystems.com/browse/NAS-107212
Note: I have only tested this in my physical setup on SCALE. However, I am not sure how this would negatively other platforms that I cannot test.
=> NAS-107212 / 13.0 / Fix bug adding VLANs to LAGGs on SCALE

tests/api2/acl.py
This set of regression tests verifies that the individual
ACL permissions bits grant no more access than is expected from them.
=> NAS-107227 / 11.3 / Add more ACL regression tests

tests/api2/posix_mode.py
Tests for POSIX permissions endpoints including basic functional
tests to determine that OS is doing the right thing as well.
=> NAS-107254 / 12.0 / Add basic tests for filesystem permissions API

tests/api2/activedirectory.py, tests/api2/ad_idmap.py, tests/api2/ad_kerberos.py, tests/api2/auth.py, tests/api2/dyndns.py, tests/api2/ipmi.py, tests/api2/pool_dataset_encryption.py, tests/api2/snmp.py, tests/api2/user.py, tests/api2/vmware.py, tests/runtest.py
git cherry-pick -x b27cd8e705ed6d0c474e7547a848f397b59226b2
git cherry-pick -x 765bfea21d3b5e86ad324cc715be163a60edc243
git cherry-pick -x c45055792321fe2aa415a61942ba42cf57c81425
git cherry-pick -x c7b1bd1babd1cb885c5d6ffd3dbca989a1d3aa13
git cherry-pick -x 19d4d73fd261f4d97484b5161e6c9427339f3d78
git cherry-pick -x 27c6ba1159c2b90957cb2f1aa60aa7d12cf5d303
git cherry-pick -x bd4c4826eb79604372fe78761115b242beb32bae
Original PR: https://github.com/freenas/freenas/pull/5476
=> NAS-105654 / 12.0 / Add regression test for safe handling of private middleware plugin attributes (by ericbsd)

src/middlewared/middlewared/plugins/smb_/registry.py
Ensure this streams_xattr is added if streams is checked.
=> NAS-107343 / 12.1 / Fix alternate data streams support

src/middlewared/middlewared/plugins/smb_/registry.py
Ensure this streams_xattr is added if streams is checked.
Original PR: https://github.com/freenas/freenas/pull/5528
=> NAS-107343 / 12.0 / Fix alternate data streams support (by anodos325)

src/middlewared/middlewared/plugins/smb.py
Also expand validation of netbios names for legacy HA configuration.
Predictable and consistent local user authentication with legacy HA
setup requires user to configure at least one netbios alias.
Original PR: https://github.com/freenas/freenas/pull/5530
=> NAS-107213 / 12.0 / Fix validation for netbios names that are NULL (by anodos325)

tests/api2/test_007_pool_dataset_encryption.py, tests/api2/test_011_user.py, tests/api2/test_030_activedirectory.py, tests/api2/test_032_ad_kerberos.py, tests/api2/test_035_ad_idmap.py, tests/api2/test_080_auth.py, tests/api2/test_180_dyndns.py, tests/api2/test_250_ipmi.py, tests/api2/test_440_snmp.py, tests/api2/test_550_vmware.py, tests/runtest.py
git cherry-pick -x b27cd8e705ed6d0c474e7547a848f397b59226b2
git cherry-pick -x 765bfea21d3b5e86ad324cc715be163a60edc243
git cherry-pick -x c45055792321fe2aa415a61942ba42cf57c81425
git cherry-pick -x c7b1bd1babd1cb885c5d6ffd3dbca989a1d3aa13
git cherry-pick -x 19d4d73fd261f4d97484b5161e6c9427339f3d78
git cherry-pick -x 27c6ba1159c2b90957cb2f1aa60aa7d12cf5d303
git cherry-pick -x bd4c4826eb79604372fe78761115b242beb32bae
Original PR: https://github.com/freenas/freenas/pull/5476
=> NAS-105654 / 12.1 / Add regression test for safe handling of private middleware plugin attributes (by ericbsd)

src/middlewared/middlewared/plugins/crypto.py
This commit fixes an issue where SAN is added by default for CN as it's become a standard now, so DNS mapping may/may not have all the domain mappings for the prefixes, we fix that here.
=> NAS-107104 / 20.10 / Properly renew ACME certs

src/middlewared/middlewared/plugins/crypto.py
This commit fixes an issue where SAN is added by default for CN as it's become a standard now, so DNS mapping may/may not have all the domain mappings for the prefixes, we fix that here.
Original PR: https://github.com/freenas/freenas/pull/5551
=> NAS-107104 / 12.0 / Properly renew ACME certs (by sonicaj)

tests/api2/host_key.py, tests/runtest.py
added remove host_key from the skip test
=> NAS-106173 / 12.0 / adding code to wait on middleware to be online in api2/host_key.py

src/middlewared/middlewared/utils/__init__.py
- `queue.Full` exception in the producer was a no-op because the consumer didn't initiate the Queue() object with the `maxsize` keyword
- make sure we catch any other exception in the consumer and kill off the dangling process
Without these changes, there is a memory leak in a certain scenario with rsync tasks.
- if the `snapdir` zfs property is set to `visible` then rsync will try to delete/update contents in the `.zfs` directory
- this will fail, obviously, since that's a read-only area in the filesystem
- since the shared buffer could grow without bounds and because we're not catching any other exception in the consumer, there is a possibility of the buffer never getting freed
Original PR: https://github.com/freenas/freenas/pull/5565
=> NAS-107315 / 11.3 / fix rsync mem leak when snapdir = visible (by yocalebo)

tests/api2/test_260_iscsi.py, tests/api2/test_400_service.py, tests/api2/test_490_system_general.py, tests/api2/test_700_host_key.py
for test_400_service.py:
changed all_service on only source the service id
added services_list fixture
added test to source all service in services_list fixture
changed test 03 and 04 to use services_list for enable output
for test_700_host_key.py:
added test to verify ssh settings for root login before reboot
added test to verify ssh enable at boot before reboot
added test to verify if ssh is running before reboot
added test to verify ssh settings for root login after reboot
added test to verify ssh enable at boot after reboot
added test to verify if ssh is running after reboot
simplify test 18 in test_260_iscsi.py
=> NAS-107424 / 12.1 / Fix ssh releated tests for pytest dependency

src/middlewared/middlewared/plugins/account.py
Re-implement validation from legacy_ui preventing users from setting zpool mountpoints as a home directory.
Require owner read and execute on a home directory.
=> NAS-107437 / 11.3 / Expand validation for user home directories

tests/api2/test_003_network.py
added test to verify network general summary new nameservers
added test to verify network general summary default routes
added test to verify network general summary ips
=> NAS-107440 / 12.1 / 20.10 / Changing network test 03 to more automated and to not rely on config

src/middlewared/middlewared/etc_files/local/smb4.conf
(cherry picked from commit 399988e5d7c873eb51b1be078b2db85e120011e3)
=> Fix SMB share bind ip check

src/middlewared/middlewared/plugins/account.py
Permissions operations during home directory move bypass our middleware API for
permissions. Move the copy and permissions operation into a middleware job and
use API.
=> NAS-107445 / 12.0 / Remove unprotected setfacl / chmod call

src/freenas-installer/etc/install.sh
=> NAS-107493 / 20.10 / Do not try to automatically create swap on MINIs

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/map.py
=> Accept TRUENAS-MINI as well as FREENAS-MINI for enclosure

src/freenas-installer/etc/install.sh
Ticket:	NAS-107493
Original PR: https://github.com/freenas/freenas/pull/5633
=> NAS-107493 / 12.0 / Do not try to automatically create swap on MINIs (by william-gr)

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/map.py
Ticket:	NAS-107492
Original PR: https://github.com/freenas/freenas/pull/5632
=> NAS-107492 / 12.0 / Accept TRUENAS-MINI as well as FREENAS-MINI for enclosure (by william-gr)

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
=> NAS-107492 / 20.10 / Do not blacklist SGPIO for MINIs

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
Ticket:	NAS-107492
Original PR: https://github.com/freenas/freenas/pull/5651
=> NAS-107492 / 12.0 / Do not blacklist SGPIO for MINIs (by william-gr)

src/middlewared/middlewared/etc_files/rc.conf.py
Address issue where nmbd was starting on boot in 12.0.
=> NAS-107518 / 20.10 / Add service announcements to rc.conf.py

src/middlewared/middlewared/common/smart/smartctl.py
… mode are registered with the ciss driver although they really do JBOD
Original PR: https://github.com/freenas/freenas/pull/5639
=> NAS-107479 / 20.10 / Account that, for some reason, some RAID cards that are flashed to IT… (by themylogin)

src/middlewared/middlewared/etc_files/rc.conf.py
Address issue where nmbd was starting on boot in 12.0.
Original PR: https://github.com/freenas/freenas/pull/5654
=> NAS-107518 / 12.0 / Add service announcements to rc.conf.py (by anodos325)

src/middlewared/middlewared/plugins/update_/upload_location_freebsd.py
git cherry-pick -x 9e0236f197d911731b19bf2fb6f496144fe78ba5
Original PR: https://github.com/freenas/freenas/pull/5646
=> NAS-107504 / 12.0 / Fix update.destroy_upload_location (by themylogin)

src/middlewared/middlewared/plugins/pool.py
Check whether the process that is being flagged for stopping / killing
is the parent middlewared process or one of our child processes. Skip
in this case.
Original PR: https://github.com/freenas/freenas/pull/5655
=> NAS-107519 / 12.0 / Prevent middleware from killing itself (by anodos325)

src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/utils/__init__.py
Simplify our sanity check for process we're going to kill.
=> NAS-107519 / 20.10 / Prevent middleware from killing itself (by anodos325) (by bugclerk)

src/middlewared/middlewared/plugins/smb.py
When user adds invalid auxilary parameter(s) to the smb.conf, pdbedit
invocations (or any utilty that ultimately calls lpcfg_map_parameter()),
will result in additional warning messages being printed even at DEBUG 0
on stdout. This may break parsing of output from the CLI utility, and in
the case of pdbedit, will prevent updating of user password.
This commit will change two things. First is a minimal workaround for the
passdb update to splitlines() and use only last element of resulting list.
Warnings in this specific situation are prepended to the command's output
and so will be safely discarded. Additionally, validation for smb_options
(auxiliary parameters for the SMB service) will be expanded to add a
call to LoadParm.dump_a_parameter(<aux param>). This function will raise
a …
=> NAS-107501 / 11.3 / Fix pdbedit parsing when SMB service aux param invalid (by anodos325)

src/middlewared/middlewared/plugins/network.py
=> NAS-107566 / 11.3 / Handle KeyError in failover validations

src/middlewared/middlewared/plugins/pool.py
=> NAS-107588 / 20.10 / Comment inexistent sysctls for resilver priority

src/middlewared/middlewared/plugins/pool.py
Ticket:	NAS-107588
Original PR: https://github.com/freenas/freenas/pull/5673
=> NAS-107588 / 12.0 / Comment inexistent sysctls for resilver priority (by william-gr)

src/middlewared/middlewared/plugins/network.py
=> NAS-107592 / 11.3 / Make sure update is not None

src/middlewared/middlewared/plugins/filesystem.py, src/middlewared/middlewared/plugins/pwenc.py
git cherry-pick -x 3cc6f94e29a24694ac4317e955863f34f8472789
Original PR: https://github.com/freenas/freenas/pull/5681
=> NAS-107348 / 20.10 / Cache pwenc secret (by themylogin)

src/middlewared/middlewared/plugins/sysdataset.py
Destroy the cores dataset if it has > 1GiB written to it, then re-create with a 1GiB quota.
Original PR: https://github.com/freenas/freenas/pull/5688
=> NAS-107617 / 20.10 / Enforce 1GiB limit on cores dataset (by anodos325)

src/middlewared/middlewared/plugins/zettarepl.py
git cherry-pick -x 130d5c8500863fa7da483b5d9e86d4fa82843ea3
Original PR: https://github.com/freenas/freenas/pull/5722
=> NAS-107523 / 20.10 / Properly handle invalid datasets in zettarepl.list_datasets (by themylogin)

src/freenas/etc/netcli
1. use `system.is_enterprise` API
2. dont prompt for failover settings unless licensed
3. fix adding IP address on B controller if enterprise hardware but not licensed
4. default routes were broken
5. it's clearly been neglected wrt to flake8 and formatting so fix that up too
=> NAS-107720 / 20.10 / fix multiple issues with netcli on SCALE

tests/api2/activedirectory.py, tests/api2/ad_kerberos.py
git cherry-pick -x ec11a045ff1e9592ff9fe355c13c11f87df6206f
Original PR: https://github.com/freenas/freenas/pull/5734
=> NAS-107743 / 11.3 / change activedirectory api tests to  only change nameserver1 (by ericbsd)

src/middlewared/middlewared/plugins/support.py
git cherry-pick -x e0e3a8556d4ce323873fb920fa23f4cfc42af5ef
Original PR: https://github.com/freenas/freenas/pull/5752
=> NAS-107750 / 12.0 / Fix support plugin on 12 and SCALE (by themylogin)

tests/api2/test_030_activedirectory.py, tests/api2/test_032_ad_kerberos.py, tests/api2/test_035_ad_idmap.py
(cherry picked from commit ec11a045ff1e9592ff9fe355c13c11f87df6206f)
=> NAS-107743 / 12.1 / change activedirectory api tests to  only change nameserver1

src/freenas/usr/lib/systemd/system-preset/10-truenas.preset
=> NAS-107825 / 20.10 / Enable zfs-sed by default

src/middlewared/middlewared/plugins/zfs.py
On snapshot creation, we should return created snapshot details following CRUD services standard.
=> NAS-107673 / 20.10 / Correctly return snapshot data conforming to crud standard

src/middlewared/middlewared/plugins/crypto.py, src/middlewared/middlewared/plugins/vpn.py
1) Client certificate profile requires KeyAgreement to be set in KeyUsage extension. This PR updates the basic client cert profile highlighting the change.
2) Add validation checking for CN for client certs
=> NAS-107852 / 20.10 / Bug fixes for OpenVPN configuration

src/middlewared/middlewared/plugins/interface/netif_linux/interface.py, src/middlewared/middlewared/plugins/network.py
@sonicaj can you please check if we also need to handle `kube-bridge` in one of these diffs
=> NAS-107859 / 20.10 / Fix setting up bridges and MTU on Linux

tests/api1/iscsi.py, tests/api1/ldap_bsd.py, tests/api1/ldap_osx.py, tests/api2/activedirectory.py, tests/api2/afp.py, tests/api2/iscsi.py, tests/api2/ldap.py, tests/api2/nfs.py, tests/api2/smb.py, tests/functions.py
Added some changes related to iscsi and AD testing.
Note that the AD SSH BSD test will need to change that will come in future ticket.
=> NAS-104763 / 11.3 / Add LDAP regression tests

src/middlewared/middlewared/plugins/reporting/plugins_freebsd.py
This does not solve the root clause of issue (I've cloned it for UI team)
=> NAS-107886 / 20.10 / Fix CPU temperature graph

src/middlewared/middlewared/plugins/filesystem_/acl_base.py
=> Fix ACL options type

src/middlewared/middlewared/etc_files/krb5.keytab.py
Account for differences between heimdal / mit ktutil utility
in kerberos keytab generation.
=> NAS-107942 / 20.10 / Fix kerberos keytab generation on SCALE

.gitignore, tests/api2/activedirectory.py, tests/api2/afp.py, tests/api2/iscsi.py, tests/api2/ldap.py, tests/api2/nfs.py, tests/api2/smb.py, tests/functions.py
git cherry-pick -x 55a6c1894f64b36c4c505cdc375e359c6e756bef
git cherry-pick -x 3154935c2d4f83752694c8c31bf07e83da0c1bfc
git cherry-pick -x 6893cc8f5681fc6cbc8ff80afcae20d2feb5c64d
git cherry-pick -x 75bfe73beb2cc28202a7241e76cc20f8d8ea8329
git cherry-pick -x 88a98855dc5e7fca27c4a80cb57fe2536063449b
git cherry-pick -x f8c1d2663c54ef0e104d5ef215f8ee181dff5585
git cherry-pick -x c474275ba891a88408d619cdff3e3b894206ef97
git cherry-pick -x ed8eae87113804495528054cc2c8d509132ff2d0
git cherry-pick -x e1c145131f19a876e7b0c17d75daeeca00a60721
git cherry-pick -x 70f050ff3541471011c75758adbb3eb13c4035a7
git cherry-pick -x f9d76bc4a8806a378fe075150554f4d9d5b7ae98
git cherry-pick -x a06e34227883f04eb1d9886172523b68869b9770
Added some …
=> NAS-104763 / 12.0 / Add LDAP regression tests (by ericbsd)

src/middlewared/middlewared/etc_files/loader.py
=> NAS-107971 / 12.0 / prevent error msg on boot for vers 1 and 2 on m-series

src/middlewared/middlewared/plugins/pool.py
zfs.dataset.query only handles id filter specially, right now we send systemdataset filters to zfs.dataset service which results in a huge lag even if we just want to retrieve a single dataset. This improves the performance dramatically when retrieving a single dataset.
=> NAS-107995 / 20.10 / Improve pool.dataset.query performance

src/middlewared/middlewared/plugins/ups.py
There are some UPS models which run a self test at scheduled intervals where they go on battery and back during the test. We should not raise an alert in this case as this is scheduled and expected and gives a false alarm.
Original PR: https://github.com/freenas/freenas/pull/5622
=> NAS-106110 / 12.0 / Donot raise UPS alert during self test (by sonicaj)

src/middlewared/middlewared/common/smart/smartctl.py
… mode are registered with the ciss driver although they really do JBOD
Original PR: https://github.com/freenas/freenas/pull/5639
=> NAS-107479 / 12.0 / Account that, for some reason, some RAID cards that are flashed to IT… (by themylogin)

src/middlewared/middlewared/plugins/idmap.py
idmap_tdb is the only supported option for this system domain type.
=> NAS-107714 / 12.0 / Fix validation for DS_TYPE_DEFAULT_DOMAIN

src/middlewared/middlewared/plugins/reporting/plugins_freebsd.py
This does not solve the root clause of issue (I've cloned it for UI team)
Original PR: https://github.com/freenas/freenas/pull/5817
=> NAS-107886 / 12.0 / Fix CPU temperature graph (by themylogin)

src/middlewared/middlewared/plugins/vm.py, src/middlewared/middlewared/plugins/zfs.py
git cherry-pick -x 0706fff88d375c7860ce03ed210d141f2c9caac5
Original PR: https://github.com/freenas/freenas/pull/5854
=> NAS-107929 / 12.0 / Properly raise exception if cloning snapshot fails (by sonicaj)

src/middlewared/middlewared/plugins/update_/download.py, src/middlewared/middlewared/plugins/update_/utils_linux.py
git cherry-pick -x a250de4ffacf720f73c92a0975ca0879b17abbc9
Original PR: https://github.com/freenas/freenas/pull/5819
=> NAS-107749 / 12.0 / Fix SCALE response to invalid update file (by themylogin)

src/middlewared/middlewared/plugins/interface/configure.py
We're preventing link-local IPv6 addresses from being generated on SCALE because the `nd6_flags` property isn't doing anything. I've added logic to create an EUI64 link-local IPv6 address based off the mac address of the interface per rfc4291.
Without a link-local IPv6 address, IPv6 will not work in general.
=> NAS-108048 / 20.12 / add EUI64 link-local IPv6 addresses work on SCALE

src/middlewared/middlewared/plugins/smb_/passdb.py
pdbedit can fail to remove entries in the passdb.tdb file if the file
contains garbage data. This creates a situation where only recovery
scenario is the delete the passdb and re-initialize it. Presumably this
error scenario is most likely to occur during entry deletion (not insertion)
and so our error handling will be added to that aspect of passdb handling.
Store copy of garbage passdb.tdb for further analysis if this happens.
Since the NT hashes stored in the passdb.tdb file contain password-equivalent
hashes for local users, keep backup in samba's private dir.
=> NAS-108114 / 12.0 / Add error handling during passdb synchronization

src/middlewared/middlewared/plugins/usage.py
git cherry-pick -x 3cfc03d181c6455c993e7327c85a37d59d8b0379
git cherry-pick -x 32b012429539f53834a561b2eee38b2f92e4699e
Original PR: https://github.com/freenas/freenas/pull/5902
=> NAS-108059 / 11.3 / Only send usage stats for master node (by sonicaj)

src/middlewared/middlewared/plugins/smb_/passdb.py
pdbedit can fail to remove entries in the passdb.tdb file if the file
contains garbage data. This creates a situation where only recovery
scenario is the delete the passdb and re-initialize it. Presumably this
error scenario is most likely to occur during entry deletion (not insertion)
and so our error handling will be added to that aspect of passdb handling.
Store copy of garbage passdb.tdb for further analysis if this happens.
Since the NT hashes stored in the passdb.tdb file contain password-equivalent
hashes for local users, keep backup in samba's private dir.
Original PR: https://github.com/freenas/freenas/pull/5924
=> NAS-108114 / 20.12 / Add error handling during passdb synchronization (by anodos325)

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py, src/middlewared/middlewared/plugins/kmip/sync.py, src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/usage.py
git cherry-pick -x 32b012429539f53834a561b2eee38b2f92e4699e
Original PR: https://github.com/freenas/freenas/pull/5902
=> NAS-108059 / 12.0 / Only send usage stats for master node (by sonicaj)

tests/api2/network.py
added test to enable netwait
added test to verify put network configuration output
added test to get network configuration info for netwait
added test to verify get network configuration output
added test to verify that netwait is in rc.conf.freenas
added test to disable netwait
added test to verify that netwait is not in rc.conf.freenas
=> NAS-105947 / 12.0 / Added regression testing for netwait

src/middlewared/middlewared/plugins/catalogs_linux/items.py, src/middlewared/middlewared/plugins/chart_releases_linux/validation.py
This PR fixes an issue where for catalog items, we did not populate defaults based on schema and was only being done when the chart was being created.
This will help UI properly render default values or show an end user what default values look like for the item in question based on schema specified.
=> NAS-108139 / 20.12 / Correctly populate defaults to be shown in UI for catalog items

src/middlewared/middlewared/etc_files/local/nslcd.conf, src/middlewared/middlewared/etc_files/pam.d/pam.inc
Also prevent lookups for UIDs < 1000 from LDAP (with ability to override
via LDAP auxiliary parameter).
Original PR: https://github.com/freenas/freenas/pull/5808
=> NAS-107753 / 12.0 / Prevent LDAP queries for local user info (by anodos325)

src/middlewared/middlewared/plugins/smb_/registry.py
12.0 abstracted away from exposing explicit vfs module configuration
to users (instead opting to use checkboxes). In cases where we couldn't
cleanly migrate the user's VFS objects to our new feature-based config
(acls, streams, etc), we dumped the params into SMB share auxiliary
parameters. This preserves user's existing behavior (pre-12.0), but
can cause issues with time machine support if user opts to add a
time machine share at a later date (or has inconsistently-migrated
shares) since support for the SMB2 protocol extensions is determined
on the first SMB2 tree connect. This means that all shares _must_ have
vfs_fruit enabled (even ones with VFS objects in auxiliary parameters)
if users have them on any other share.
To address this potential issue, check for "vfs objects" lines when …
=> NAS-108141 / 20.12 / Fix SMB2 AAPL extension negotiation

src/freenas/usr/local/lib/middlewared_truenas/alert/source/sensors.py, src/freenas/usr/local/lib/middlewared_truenas/plugins/sensor.py
@william-gr I am not sure if this has sense to hide this alert on CORE when hardware is not FREENAS-CERTIFIED
=> NAS-108075 / 20.12 / Allow power supply alert on FREENAS-CERTIFIED

src/middlewared/middlewared/alert/source/applications_linux.py, src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py, src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py, src/middlewared/middlewared/plugins/docker_linux/client.py, src/middlewared/middlewared/plugins/docker_linux/images.py, src/middlewared/middlewared/plugins/docker_linux/update_alerts.py, src/middlewared/middlewared/plugins/docker_linux/utils.py, src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
This PR introduces changes to allow users to be notified if we have a newer version of a docker image available with the same tag name.
=> NAS-108245 / 20.12 / Add alerts for docker image updates

src/middlewared/middlewared/plugins/smb.py
Ensure that SMB shares are reconfigured properly during changes enabling / disabling vfs_fruit.
=> NAS-108264 / 12.0 / Reconfigure SMB shares on toggle of aapl_extensions

src/middlewared/middlewared/alert/service/telegram.py
I added the support for the Telegram alert service
=> Telegram alert service

src/middlewared/middlewared/plugins/pool.py
=> NAS-107620 / 20.12 / Use new sysctls for resilver/scrub priority

src/middlewared/middlewared/plugins/pool.py
Ticket:	NAS-107620
Original PR: https://github.com/freenas/freenas/pull/6008
=> NAS-107620 / 12.0 / Use new sysctls for resilver/scrub priority (by william-gr)

src/middlewared/middlewared/plugins/vm/pci_linux.py
This commit removes verbose logging for available pci devices. We do not need to log what driver each PCI device is using each time passthrough choices are retrieved.
=> NAS-108310 / 20.12 / Remove verbose logging when retrieving passthrough choices in scale

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Many bugs fixed here and also make the `failover.control` API behavior match the `failover.update` API behavior.
`failover.control` fixes
- disabling HA didn't actually disable anything (this breaks `hactl` since it uses this API)
- `options` will never be `None` and gets passed in as `{}` when that attribute isn't given to us
- if the `active` attribute wasn't provided and HA was disabled, it actually designated the standby node as the master node which is the exact opposite behavior of what `failover.update` API does.
`failover.update` fixes
- if `master` is `NOT_PROVIDED` it will never be `None` which means the `master` variable wasn't being set appropriately
Original PR: https://github.com/freenas/freenas/pull/6025
=> NAS-108313 / 12.0 / fix failover.control and failover.update (by yocalebo)

src/middlewared/middlewared/plugins/pool.py
=> NAS-107694 / 20.12 / Allow to update `autotrim` pool property

src/middlewared/middlewared/plugins/pool.py
Ticket:	NAS-107694
Original PR: https://github.com/freenas/freenas/pull/6012
=> NAS-107694 / 12.0 / Allow to update `autotrim` pool property (by william-gr)

src/middlewared/middlewared/plugins/smb_/registry.py
Add ability to convert SMB share configuration from registry back
into an equivalent SMB share configuration in return of
sharing.smb.query. This will allow direct queries of samba's running
configuration when in presence of clustered registry shares while
keeping same API. Latter part of this is yet to be implemented.
This comit just expands utility functions for the registry config.
=> NAS-108341 / 20.12 / Samba registry - expand registry utility functions

src/middlewared/middlewared/plugins/network.py
Quality of life improvements wrt to HA and the network CRUD API.
- `failover_aliases` and `failover_virtual_aliases` don't require a netmask
- ensure the validation accounts for the fact that these keys will no longer be present
=> NAS-108338 / 20.12 / fix network CRUD API for HA systems

src/middlewared/middlewared/plugins/kubernetes_linux/backup.py, src/middlewared/middlewared/plugins/kubernetes_linux/namespace.py, src/middlewared/middlewared/plugins/kubernetes_linux/restore.py, src/middlewared/middlewared/plugins/kubernetes_linux/secrets.py, src/middlewared/middlewared/plugins/kubernetes_linux/utils.py, src/middlewared/middlewared/plugins/update.py
This PR introduces changes to add backup / restore functionality for helm chart releases in case we have a breaking change and k8s infra needs to be adjusted to accommodate it.
=> NAS-108281 / 20.12 / Backup / Restore functionality for Chart Releases

src/middlewared/middlewared/main.py
The real cause of issue is resolved by https://github.com/freenas/webui/pull/4886
Original PR: https://github.com/freenas/freenas/pull/6048
=> NAS-108343 / 20.12 / Do not hide excessive args in method calls (by themylogin)

src/middlewared/middlewared/plugins/vm.py, src/middlewared/middlewared/validators.py
git cherry-pick -x 36b4805dc5eed4078befb7b8675b963a51b338b4
Original PR: https://github.com/freenas/freenas/pull/6053
=> NAS-108354 / 12.0 / Add validation to ensure valid mac address is provided for VM nic device (by sonicaj)

src/middlewared/middlewared/alembic/versions/12.1/2020-11-18_21-07_gluster_smb_crud_integration.py, src/middlewared/middlewared/async_validators.py, src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/service.py
Early stages of integrating SMB with gluster. This lays the groundwork for moving forward with the other aspects (ctbd plugin/smb registry implementation etc) of the intergration.
=> NAS-108331 / 20.12 / integrate gluster with SMB CRUD API

src/middlewared/middlewared/alert/source/freenas_bmc.py
Spoke with Tim and we decided it's best to make this message more generic in case there are other BMC issues in the future, that we may want to flag for.
=> NAS-108511 / 20.12 / Update Text Strings

src/middlewared/middlewared/plugins/sysdataset.py
We need some safeguards here as this can result in service disruption.
=> NAS-107925 / 20.12 / Prevent system dataset changes while AD is enabled

debian/debian/postinst, src/freenas/usr/local/bin/ixdiagnose
Also remove /etc/cron.d and /etc/cron.daily scripts
=> NAS-108529 / 20.12 / Do not add systemd-journald logs and other huge blobs to the debug

src/middlewared/middlewared/plugins/pool.py
=> NAS-108379 / 12.0 / Proper autotrim for inaccessible pool

src/middlewared/middlewared/alert/source/freenas_bmc.py
Spoke with Tim and we decided it's best to make this message more generic in case there are other BMC issues in the future, that we may want to flag for.
Original PR: https://github.com/freenas/freenas/pull/6095
=> NAS-108511 / 12.0 / Update Text Strings (by q5sys)

src/middlewared/middlewared/plugins/etc.py
(cherry-picked from commit f0e88688808ebfefad7428e24db2778c8754263c)
=> NAS-108521 / 12.0 / Prevent race condition when generating same config at the same time

src/middlewared/middlewared/plugins/sysdataset.py
We need some safeguards here as this can result in service disruption.
Original PR: https://github.com/freenas/freenas/pull/5814
=> NAS-107925 / 12.0 / Prevent system dataset changes while AD is enabled (by anodos325)

src/middlewared/middlewared/plugins/catalogs_linux/features.py, src/middlewared/middlewared/plugins/catalogs_linux/items.py, src/middlewared/middlewared/plugins/catalogs_linux/sync_catalogs.py, src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py, src/middlewared/middlewared/plugins/chart_releases_linux/resources.py, src/middlewared/middlewared/plugins/chart_releases_linux/schema.py, src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py, src/middlewared/middlewared/plugins/chart_releases_linux/utils.py, src/middlewared/middlewared/plugins/chart_releases_linux/validation.py, src/middlewared/middlewared/plugins/docker_linux/images.py, src/middlewared/middlewared/plugins/docker_linux/update_alerts.py, src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py, src/middlewared/middlewared/plugins/kubernetes_linux/update.py, src/middlewared/middlewared/plugins/usage.py, src/middlewared/middlewared/schema.py
1. Introduces support for specifying timezone choices
2. Allows specifying schema fields to be non-editable
3. Properly perform validation for subquestions
4. Add support for timezone reference
5. Conditionally populate default values
6. Retrieve portals for chart releases
=> NAS-108551 / 20.12 / Changes for handling catalog items schema

src/freenas/usr/local/libexec/freenas-debug/system/system.sh, src/middlewared/middlewared/job.py, src/middlewared/middlewared/plugins/vmware.py, src/middlewared/middlewared/service.py
@sonicaj is it possible that ACME / KMIP jobs might be returning something we want to hide from debug?
=> NAS-108678 / 12.0 / Fix possibility for middleware plugin to leak passwords to debug

src/middlewared/middlewared/plugins/network.py
git cherry-pick -x 544be25955d7c8d62648b037d9b7c03315d1d9b9
Ticket:	NAS-105062
Original PR: https://github.com/freenas/freenas/pull/6175
=> NAS-105062 / 12.0 / Allow empty specific attributes for NIC (by william-gr)

src/middlewared/middlewared/plugins/vm.py
git cherry-pick -x 02e21570fc8a1b62db87ce99d4ddbf60f5f3eaab
git cherry-pick -x 4a128bd0a96e18fe831fcb64423283c81f0c5c14
git cherry-pick -x 605b2bb151d702dc39b591ff43fa963c74b19bd0
git cherry-pick -x 58c7c6dd077b8cc747759d740ccaa0b85f6ce035
This PR introduces changes to ensure that before we start a VM we ensure that the VM in question has resources it requires available for starting/executing.
Original PR: https://github.com/freenas/freenas/pull/6162
=> NAS-108512 / 12.0 / Do not start a VM which has unavailable resources (by sonicaj)

src/middlewared/middlewared/plugins/vm/devices/cdrom.py, src/middlewared/middlewared/plugins/vm/devices/device.py, src/middlewared/middlewared/plugins/vm/devices/nic.py, src/middlewared/middlewared/plugins/vm/devices/pci.py, src/middlewared/middlewared/plugins/vm/devices/storage_devices.py, src/middlewared/middlewared/plugins/vm/devices/vnc.py, src/middlewared/middlewared/plugins/vm/supervisor/supervisor_base.py
This PR introduces changes to ensure that before we start a VM we ensure that the VM in question has resources it requires available for starting/executing.
=> NAS-108512 / 21.02 / Do not start a VM which has unavailable resources

src/middlewared/middlewared/plugins/pool.py
As discussed in PR review
Original PR: https://github.com/freenas/freenas/pull/6059
=> NAS-108379 / 20.12 / Proper autotrim for inaccessible pool (by themylogin)

src/middlewared/middlewared/plugins/alert.py
git cherry-pick -x 359edf4244140517c7f8535adba031c9998c05ef
Original PR: https://github.com/freenas/freenas/pull/6135
=> NAS-108555 / 21.02 / Do not show alerts with frequency=NEVER (by themylogin)

src/middlewared/middlewared/plugins/network.py
=> NAS-105062 / 21.02 / Allow empty specific attributes for NIC

src/freenas/usr/local/libexec/freenas-debug/network/network.sh
- add Speed/Duplix/Port and Auto-negotiation params for each "UP" interface on SCALE
- fix formatting of printing the default gateway
- fix verbiage of default gateway
=> NAS-108789 / 21.02 / fix various issues with network.sh plugin in freenas-debug on SCALE

tests/api2/test_260_iscsi.py
I forget to uncomment depends on my last PR
=> DOCS-1475 / uncomment depends in iscsi API test

src/middlewared/middlewared/plugins/smb_/status.py
Simplify output in case of specific (not ALL) request. Add
optimizations for specific UID or session_id.
=> NAS-108840 / 21.02 / Improve smb.status API

src/middlewared/middlewared/plugins/activedirectory.py
- flake8 fixes
- `failover.get_ips` does not return anything related to HA IPs (despite the horrible name), it returns IP addresses that the webUI (`nginx`) is bound to. So, instead, call `interface.ip_in_use` which returns known working VIP addresses on HA systems.
=> NAS-108837 / 21.02 / fix _register_virthostname in ad plugin

src/freenas/etc/netcli
git cherry-pick -x b6e73e6b455808c4a23b0906aecd2529d1c7685e
Original PR: https://github.com/freenas/freenas/pull/6204
=> NAS-108762 / 21.02 / Create VLAN network interface database record from netcli (by themylogin)

src/middlewared/middlewared/plugins/zettarepl.py
git cherry-pick -x 55a296ab084c31b2a4b51da636bb764bc71d99ed
git cherry-pick -x c3c1171d979cc68fa70ccd055055268840475f8f
Original PR: https://github.com/freenas/freenas/pull/6227
=> NAS-108796 / 12.0 / Do not receive sharenfs and sharesmb properties when replicating (by themylogin)

src/middlewared/middlewared/plugins/catalogs_linux/features.py, src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py, src/middlewared/middlewared/plugins/chart_releases_linux/resources.py, src/middlewared/middlewared/plugins/chart_releases_linux/validation.py
This PR introduces changes to retrieve used ports by Applications and also adds validation to ensure that we prohibit using a used port.
=> NAS-108691 / 21.02 / Add ability to retrieve and validate used/unused ports in Apps

src/middlewared/middlewared/plugins/activedirectory.py
Setting the NTP server may fail (ValidationError). In general case,
failure in this method should not be fatal for domain join process.
Wrap in try/except and log it.
Original PR: https://github.com/freenas/freenas/pull/6219
=> NAS-108900 / 21.02 / Add exception handling for setting NTP in AD plugin (by anodos325)

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py, src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/remote.py
Original PRs: https://github.com/freenas/freenas/pull/5916 and https://github.com/freenas/freenas/pull/6254
=> NAS-108945 / 12.0 / only run get_remote_os_version() on HA systems (by yocalebo)

src/middlewared/middlewared/plugins/kubernetes_linux/events.py
When middleware starts, we get all old k8s events which can become overwhelming for middleware to process resuling in tasks getting delayed and middleware consuming lots of cpu cycles.
=> NAS-108946 / 21.02 / Do not process old k8s events

src/middlewared/middlewared/plugins/activedirectory.py
In some edge cases it appears that middleware performing a netlogon
connection can trample winbindd's netlogon session causing winbind
operations to fail with STATUS_RPC_SEC_PKG_ERROR. This commit splits
up two things that are vital for checking overall status of our
domain join. (1) health of winbindd's netlogon connection to the
current DC it's using and (2) the ability to fail over to a working
DC if the one winbind is currently connected to becomes inaccessible.
Checks for (2) are rolled into the general periodic AD domain health
check - once per hour, and (1) is switched back to a simple "wbinfo -P" command.
=> NAS-108889 / 12.0 / Split middleware and winbind netlogon traffic between DCs

src/middlewared/middlewared/plugins/activedirectory.py
In some edge cases it appears that middleware performing a netlogon
connection can trample winbindd's netlogon session causing winbind
operations to fail with STATUS_RPC_SEC_PKG_ERROR. This commit splits
up two things that are vital for checking overall status of our
domain join. (1) health of winbindd's netlogon connection to the
current DC it's using and (2) the ability to fail over to a working
DC if the one winbind is currently connected to becomes inaccessible.
Checks for (2) are rolled into the general periodic AD domain health
check - once per hour, and (1) is switched back to a simple "wbinfo -P" command.
Original PR: https://github.com/freenas/freenas/pull/6249
=> NAS-108889 / 21.02 / Split middleware and winbind netlogon traffic between DCs (by anodos325)

tests/api2/plugin.py
Added a variable to source release version from NAS OS version and added int index_url* this way no need to update the release version.
=> DOCS-1600 / 12.0 / Changed the plugin API test sourcing of index_url*

tests/api2/test_310_plugin.py
Added a variable to source release version from NAS OS version and added int index_url* this way no need to update the release version.
(cherry picked from commit 90af4f358988e198fb04dc880413b6459e29f241)
Had to do a work around for SSH to ger the release freebsd version
Replaced 12.1-RELEASE by in freebsd_release in test 35, 31
=> Changed the plugin API test sourcing of index_url*

src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh, src/middlewared/middlewared/plugins/support.py, src/middlewared/middlewared/plugins/system.py
git cherry-pick -x 21f37ef2e9268012f9f8ec8b34c8dadc88f153f5
Original PR: https://github.com/freenas/freenas/pull/6275
=> NAS-108985 / 21.02 / Only output last 1000 lines of zpool history ioctls (by themylogin)

src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py, src/middlewared/middlewared/plugins/chart_releases_linux/ix_volumes.py, src/middlewared/middlewared/plugins/chart_releases_linux/rollback.py, src/middlewared/middlewared/plugins/kubernetes_linux/backup.py, src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py, src/middlewared/middlewared/plugins/kubernetes_linux/restore.py, src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/zfs_/zfs_events.py
1) K8s datasets are not visible in `pool.dataset.query` anymore
2) Zfs events are not raised for TN system related datasets
=> NAS-109015 / 21.02 / Specially handle TN system related datasets

src/middlewared/middlewared/plugins/pool.py
We should bring back `toggle_attachments` keeping backwards compatibility.
=> NAS-108988 / 21.02 / Bring back toggle_attachments in pool.dataset.unlock

nas_ports/freenas/freenas-files/files/pkg-install.in
(cherry picked from commit 57e04c950260b03a29ffd6431f172cf8313ba5cb)
=> revert part of 7d5f773ffa as it would never run

src/middlewared/middlewared/etc_files/docker.py, src/middlewared/middlewared/plugins/catalogs_linux/items.py, src/middlewared/middlewared/plugins/device_/device_info_linux.py, src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py
1) Ability to recognize INTEL gpus in middleware.
2) Configure INTEL gpu automatically for k8s if the system has one.
=> NAS-108532 / 21.02 / Add support for INTEL GPU in k8s

tests/api2/test_260_iscsi.py
changed the target name to have 2 random number to avoid iscsictl conflict if tests multiple test run in the same time
added testing to ensure the data stay on the zvol isqsi share
added better test dependency for the iscsi testing stack
=> DOCS-1571 / 12.1 / SCALE added API iscsi share testing with with zvol

tests/api2/iscsi.py
added testing to ensure the data stay on the zvol isqsi share
added test dependency for the iscsi testing stack for the zvol iscsi test
=> DOCS-1571 / 12.0 added API iscsi share testing with with zvol

src/middlewared/middlewared/plugins/gluster_linux/volume.py
The `ctdb.shared.volume` API was written specifically for creating the ctdb shared volume. If a request is made via the `gluster.volume` CRUD API to create a new gluster volume using the same name as the ctdb shared volume, then raise a validation error since this is a "reserved" name.
On `gluster.volume.delete`, if the ctdb shared volume is requested to be deleted, then call the `ctdb.shared.volume.delete` API since it handles other configuration items.
=> NAS-109176 / 21.02 / add ctdb shared vol validation to gluster.volume CRUD API

src/middlewared/middlewared/plugins/crypto.py
This PR fixes following issues:
1) Allow specify extensions for CSR's.
2) Fix an issue where ACME certs could not be created.
=> NAS-109237 / 21.02 / Bug fixes for crypto plugin

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
=> NAS-109298 / 12.0 / fix send_event usage for system ready

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Ticket:	NAS-109298
Original PR: https://github.com/freenas/freenas/pull/6385
=> NAS-109298 / 21.02 / fix send_event usage for system ready (by william-gr)

src/middlewared/middlewared/plugins/account.py
Run all new additions / modifications of SMB users through
a synchronize_passdb job rather than directly adding the user.
This is to avoid situations where a running passdb synchronization
job will conflict with the new user being added.
This commit also adds an optimization for the case of creating
new users with `group_create` set. In this situation, avoid reloading
the user service twice since it can be an expensive operation.
In testing these two changes roughly halved the amount of time it takes to create
a new user.
Original PR: https://github.com/freenas/freenas/pull/6301
=> NAS-109045 / 12.0 / Serialize passdb modifications (by anodos325)

src/middlewared/middlewared/plugins/disk.py, src/middlewared/middlewared/plugins/replication.py, src/middlewared/middlewared/plugins/service.py, src/middlewared/middlewared/plugins/snapshot.py, src/middlewared/middlewared/plugins/vm.py, src/middlewared/middlewared/service.py, src/middlewared/middlewared/worker.py
git cherry-pick -x cff627b62d23f791daa2f18cbbeafaa2ea20f4df
git cherry-pick -x a2f4ed0946b219ae79e977b14f5c447e98458001
Original PR: https://github.com/freenas/freenas/pull/5821
=> NAS-107793 / 12.0 / Send events for CRUD plugins (by themylogin)

src/middlewared/middlewared/plugins/reporting/events.py
git cherry-pick -x a5bc4f014e0d892facef4aca1ee4c790f2aa77c1
Original PR: https://github.com/freenas/freenas/pull/5810
=> NAS-107789 / 12.0 / reporting.realtime interface speeds (by themylogin)

src/middlewared/middlewared/plugins/sysdataset.py
…roying it if it is too big
Original PR: https://github.com/freenas/freenas/pull/6360
=> NAS-109032 / 21.02 / Account for cores dataset snapshots when evaluating its size and dest… (by themylogin)

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
This commit removes temporary wrapper used to start k8s as after 21.02 we assume that all the systems are now using same worker node password and the workaround of restarting k8s is no longer required.
=> NAS-109327 / 21.04 / Remove temporary wrapper to start kubernetes service

src/freenas/usr/local/sbin/firmware_update.py
… it has correct major version
Original PR: https://github.com/freenas/freenas/pull/6136
=> NAS-106689 / 21.04 / Ensure HBA update is to latest approved hba version and not just that… (by themylogin)

src/freenas/usr/local/lib/middlewared_truenas/plugins/sensor.py
Follow-up to 0dddcd3df6222b9a7001ae60178cbf633d1ea0a0 and 4c4e36ffb0ec10ae13e99d6ee59158ad205956e7
=> Explain power supply status on R-Series and TrueNAS Certified

src/middlewared/middlewared/plugins/interface/capabilities_freebsd.py
There are interface drivers where some capability is dependant on some other capability so if try to enable X capability which is dependant on Y, it will not be enabled unless both of them are enabled together. After discussing with mav, we should first try to enable capabilities together and if that fails we can revert to trying to enable them one by one.
=> NAS-109459 / 12.0 / Try enabling capabilities at once for interfaces

src/middlewared/middlewared/client/client.py, src/middlewared/middlewared/plugins/config.py
git cherry-pick -x bac5b395020b481de009b94659629fd948113d3e
git cherry-pick -x 449c4e1eccf0d9d71411e33375a3e0bbe05f0e62
git cherry-pick -x bf0280d8af70458826f40420fefbed525cda0036
Original PR: https://github.com/truenas/middleware/pull/6418
=> NAS-109169 / 12.0 / HA config upload / factory reset (by themylogin)

src/middlewared/middlewared/logger.py, src/middlewared/middlewared/service.py
git cherry-pick -x d3d5d19e928103ccfaea1be50025e007c185c72a
Original PR: https://github.com/truenas/middleware/pull/6438
=> NAS-109474 / 21.04 / Reconfigure zettarepl_file logger on system dataset reconfiguration (by themylogin)

src/middlewared/middlewared/plugins/activedirectory.py
During pre-join AD validation, we only need to check our clock
offset from the KDC. Later commit will add a flush of libads cache
in case of failure to find logon server during validate_domain()
call.
=> NAS-109434 / 21.04 / Avoid AD connectivity check in update() method

tests/api2/test_011_user.py
due to system not ready for the next test
=> DOCS-1792 / 12.1 a dding sleep in user api test 31, 41 and 50 to avoid failure

tests/api2/user.py
due to system not ready for the next test
=> DOCS-1792 / 12.0 adding sleep in user api test 31, 41 and 50 to avoid failure

src/middlewared/middlewared/plugins/sysdataset.py, src/middlewared/middlewared/plugins/system.py
=> Remove core files after setting up system dataset

src/middlewared/middlewared/plugins/sysdataset.py
git cherry-pick -x 325ecdb7b76867e59bc4039cdcf290a4e804143f
Ticket:	NAS-109454
Original PR: https://github.com/truenas/middleware/pull/6476
=> NAS-109454 / 21.04 / Remove core files after setting up system dataset (by william-gr)

src/middlewared/middlewared/webhooks/cluster_events.py
-make `cluster_events` webhook mount all detected gluster volumes instead of just the ctdb shared volume
Dependent on https://github.com/truenas/middleware/pull/6468
=> NAS-109497 / 21.04 / make cluster_events api mount all detected gluster volumes

src/middlewared/middlewared/plugins/gluster_linux/peer.py
Was able to get connected to a wildly broken Gluster cluster. It exposed the fact that `gluster.peer.status` could be improved. However, it also showed the fact that the 3rd party python library is omitting, in my opinion, very important information about the status of the peers in the TSP.
- no longer raise `CallError` unless the subprocess'ed cli commands fail
- no longer use the 3rd party python module for retrieving peer "status" information and parse the xml ourselves
- add `state` and `status` keys to have a more realistic idea of what the current status of the peers are
=> NAS-109617 / 21.04 / improvements to gluster.peer.status API

src/middlewared/middlewared/plugins/alert.py
git cherry-pick -x 30ac861e7cde6c9e31df816483bca444662fe08a
Original PR: https://github.com/truenas/middleware/pull/6487
=> NAS-109581 / 21.04 / Filter existing alerts by product_type (by themylogin)

src/middlewared/middlewared/plugins/account_/sync_builtin.py
=> NAS-109639 / 21.04 / Use default sudo

src/middlewared/middlewared/plugins/account_/sync_builtin.py
Ticket:	NAS-109639
Original PR: https://github.com/truenas/middleware/pull/6517
=> NAS-109639 / 12.0 / Use default sudo (by william-gr)

src/freenas/usr/local/bin/ixdiagnose
git cherry-pick -x bf4cb7095907083423631ae2937e79dae67ed70e
Original PR: https://github.com/truenas/middleware/pull/6534
=> NAS-109656 / 21.04 / Do not crash debug if /var/db/system/cores does not exist (by themylogin)

src/middlewared/middlewared/plugins/pool.py
git cherry-pick -x 7d94f9fa29d21718b71499439f196588e9bcaa8a
Original PR: https://github.com/truenas/middleware/pull/6474
=> NAS-109531 / 12.0 / Mark boot pool dataset as internal dataset (by sonicaj)

src/middlewared/middlewared/plugins/reporting/events.py
@william-gr do we want to make a custom collectd patch (our first collectd patch on SCALE) to support this in collectd?
=> NAS-109588 / 21.04 / AMD CPU temperature realtime reporting

tests/api2/test_273_kubernetes.py
Added assert to make sure that the system static ip is present in kubernetes test 01
=> DOCS-1843 / 21.04 / Changed the setup kubernetes test to use the system static ip.

tests/api2/test_305_container.py
rename test old test with private
=> DOCS-1842 / 21.04 / added public container image testing

src/middlewared/middlewared/plugins/kubernetes_linux/update.py, src/middlewared/middlewared/plugins/kubernetes_linux/utils.py
This PR introduces changes to migrate ix-applications to new pool if pool is changed and new pool does not have ix-applications dataset already existing.
=> NAS-109532 / 21.04 / Migrate ix-applications dataset to new pool if applicable

src/middlewared/middlewared/plugins/system.py
git cherry-pick -x 620ebf4a33817ce63c1b5750be9f02fed0945726
We need to retrieve build time without authentication so that UI can render the correct copyright year.
Original PR: https://github.com/truenas/middleware/pull/6553
=> NAS-109702 / 12.0 / Retrieve build time without authentication (by sonicaj)

src/middlewared/middlewared/plugins/reporting/events.py
=> NAS-108774 / 12.0 / Fix KeyError in reporting.realtime

src/middlewared/middlewared/plugins/vm.py
This commit fixes an issue where libvirt would become unresponsive if we started a VM whose grubconfig did not exist.
=> NAS-109341 / 12.0 / Do not start VM if grub config cannot be found

tests/api2/smb.py, tests/api2/smb_protocol.py, tests/protocols.py
Pylibsmb gives more fine-grained control over the SMB operations
performed on the server. Initial commit sets framework for doing these
additional tests as well as implements setting DOS modes through SMB1/2 CREATE.
=> NAS-109694 / 12.0 / Initial protocol testing for SMB using pylibsmb

src/middlewared/middlewared/service.py
We need this to handle https://jira.ixsystems.com/browse/NAS-109548
=> NAS-109741 / 12.0 / Allow better progress report for core.bulk

src/middlewared/middlewared/service.py
git cherry-pick -x 3ce6b0ace1069bdce79ad2e0789e01ec5723f45a
We need this to handle https://jira.ixsystems.com/browse/NAS-109548
Original PR: https://github.com/truenas/middleware/pull/6588
=> NAS-109741 / 21.04 / Allow better progress report for core.bulk (by themylogin)

src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
- fix `KeyError` by changing `replicate` to `replica`
- `Service` doesn't have access to `get_instance` or `config()` so just return `gluster.volume.query` using filters
- In `delete()` change `gluster.volume.umount` to `gluster.fuse.umount`
=> NAS-109810 / 21.04 / fix various issues with CtdbSharedVolumeService

tests/api2/test_510_tftp.py
This fixing the dataset unmount error on SCALE
=> DOCS-1870 / 21.04 / Added test to stop the tftp service in test_510_tftp.py

src/middlewared/middlewared/plugins/kubernetes_linux/cni.py, src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
This commit fixes an issue where we were waiting with a random value so that kube-router configured routes are added to the kube-router table. However on vms or slow machines, this random can value has potential to not work and we end up with these routes not configured which results in DNS failures inside the k8s cluster.
=> NAS-109481 / 21.04 / Add k8s routes to kube-router table

src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py
This commit adds changes to properly load and configure nvidia modules so it can be consumed by applications.
=> NAS-109192 / 21.04 / Properly load nvidia kernel modules

src/middlewared/middlewared/plugins/acme_protocol_/issue_cert.py
This commit fixes issues with the implementation allowing wildcard certificate to be created.
=> NAS-109855 / 21.04 / Add support for creating wildcard ACME certs

src/middlewared/middlewared/plugins/pool.py
This will speed up create operations with high number of sibling datasets.
=> NAS-109898 / 21.04 / PoolDatasetService.do_create: skip children lookups on parent datasets

src/middlewared/middlewared/plugins/datastore/read.py, src/middlewared/middlewared/plugins/iscsi.py, src/middlewared/middlewared/restful.py, src/middlewared/middlewared/service.py
=> NAS-109911 / 21.04 / Master api speedup

src/middlewared/middlewared/plugins/chart_releases_linux/rollback.py
This commit adds changes where if rollback fails for any reason, helm might consider the chart release to be on the previous version. That basically happens because it was able to successfully rollback some k8s resources but not all, we should account for this and in this case rollback dataset's snapshots as well because the chart release might actually be functioning as desired and we just had some resource which failed to rollback.
=> NAS-109863 / 21.04 / Improve chart release rollback logic

src/middlewared/middlewared/plugins/catalogs_linux/update.py
This commit adds changes to ensure we do not have catalog.query failing if we have a repo configured which does not exist or we are unable to clone for some reason.
=> NAS-109927 / 21.04 / Do not have catalog query fail

tests/api2/test_425_smb_protocol.py, tests/protocols.py
Pylibsmb gives more fine-grained control over the SMB operations
performed on the server. Initial commit sets framework for doing these
additional tests as well as implements setting DOS modes through SMB1/2 CREATE.
Original PR: https://github.com/truenas/middleware/pull/6543
=> NAS-109694 / 21.04 / Initial protocol testing for SMB using pylibsmb (by anodos325)

tests/api2/test_420_smb.py
This commit adds regression tests for domain sid modification across netbios name changes.
=> NAS-109805 / 21.04 / Add regression tests for domain sid modifications (by anodos325)

tests/api2/test_308_kubernetes_backup_chart_releases.py, tests/api2/test_425_smb_protocol.py
added pytestmark for dev test in api2/test_425_smb_protocol.py
=> DOCS-1959 / 20.04 / updated test_308_kubernetes_backup_chart_releases test 05, 10 and 14

src/middlewared/middlewared/webui_auth.py
=> NAS-110071 / 21.04 / Fix path for index.html

src/middlewared/middlewared/plugins/device_/udev_events_linux.py
This commit fixes an issue where in case udev errored out, we stopped polling udev. We want to keep polling udev to continue monitoring the system state. About the current issue, it was an error where system failed to poll the file descriptor.
=> NAS-110046 / 21.04 / Make sure we keep polling udev

src/middlewared/middlewared/plugins/filesystem_/acl_base.py, src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
Reverting truenas/middleware#6764 as it was merged by mistake (i.e. master is still frozen)
=> Revert "NAS-110159 / 21.04 / Connect POSIX ACL logic to nfs4xdr_winacl"

tests/api2/test_190_filesystem.py
=> relpaced nlink (1, 2, 3, 4, 5) for tuple(range(10)) in test_190_fileystem.py

src/middlewared/middlewared/plugins/usage.py
git cherry-pick -x edc33db464b9968187b9f08e7412a4738b5d78ed
git cherry-pick -x 23fe87e6c4ef5d92418e8d845b397e079cbb6120
Original PR: https://github.com/truenas/middleware/pull/5856
Jira URL: https://jira.ixsystems.com/browse/NAS-107905
=> NAS-107905 / 12.0 / Report total capacity and system version if usage collection is disabled (by sonicaj)

src/middlewared/middlewared/main.py
=> NAS-110266 / 21.04 / Workaround decode issue on shell

tests/api2/test_305_container.py, tests/api2/test_306_chart_release.py
Added a sleep of one second after test 39 in test_305_container.py to see if it will fix the random failure of test 41
=> DOCS-2030 / Changed all wait_on_job to 600 second in test_306_chart_release.py

src/middlewared/middlewared/plugins/datastore/read.py, src/middlewared/middlewared/plugins/iscsi.py, src/middlewared/middlewared/restful.py, src/middlewared/middlewared/service.py
iSCSI related api call speedup
=> NAS-109911 / 12.0 / CRUDService.query: handle force_sql_filters

src/middlewared/middlewared/plugins/alert.py
git cherry-pick -x 3969936ab39f185cd17b2988ce677a36b45c87fe
Original PR: https://github.com/truenas/middleware/pull/6754
=> Reject duplicate alert source names

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event_linux.py
- restart the services concurrently on failover event (since they're self-contained) and specify a timeout (`15` seconds by default)
- log **WAY** more information during the failover event so that I can troubleshoot this a bit easier
- general code clean up
Original PR: https://github.com/truenas/middleware/pull/6636
=> NAS-109846 / 21.06 / restart services on failover event concurrently (by yocalebo)

src/middlewared/middlewared/plugins/acme_protocol_/authenticators/cloudflare.py, src/middlewared/middlewared/plugins/acme_protocol_/authenticators/route53.py
This commit introduces changes to follow certbot settings for setting ttl value of cloudflare/route53 to 10 minutes respectively.
=> NAS-110156 / 21.06 / Update ttl of cloudflare/route53 txt records

src/middlewared/middlewared/plugins/catalogs_linux/items.py
This PR adds changes to not use cached version of refs. This fixes issues where if system state changed like certificates were added, we would still be having old/cached version, we normalize the questions again to make sure this is not the case.
=> NAS-110028 / 21.06 / Do not use cached version of refs 

src/middlewared/middlewared/plugins/gluster_linux/volume.py
I've pushed various fixes to upstream module for which 2 out of the 3 have been merged. These fixes are necessary based on the changes.
- upstream fix # 1 https://github.com/gluster/glustercli-python/pull/43
- upstream fix # 2 https://github.com/gluster/glustercli-python/pull/44
- upstream fix # 3 https://github.com/gluster/glustercli-python/pull/45
=> NAS-110283 / 21.06 / fix replacebrick and removebrick API endpoint

src/middlewared/middlewared/plugins/catalogs_linux/items.py
This commit adds changes to only raise an alert that a catalog is not healthy if the affected train is set as a preferred train by the user. Motivation for this change is that a catalog might be maintained by lots of devs and each person can be working on their own train for purposes like development, now in the UI users only interact with preferred trains, so it makes sense that we only let the user know that a catalog is not healthy if one of the affected trains is what the user has set his preferred train.
=> NAS-110525 / 21.06 / Only raise catalog not healthy alert for preferred trains

src/middlewared/middlewared/plugins/smart.py
… failures
Original PR: https://github.com/truenas/middleware/pull/6858
Jira URL: https://jira.ixsystems.com/browse/NAS-110509
=> NAS-110509 / 12.0 / Do not report successful S.M.A.R.T. test starts on SCSI/SAS drives as… (by themylogin)

src/middlewared/middlewared/plugins/network.py
This commit  fixes an issue where it's impossible to configure aliases with dhcp if we have for example 4 NICs and on a fresh install all interfaces will have DHCP running, then if for 1 interface we want to configure aliases with dhcp, we won't be able to do that as it will error out saying that DHCP can only be enabled for 1 interface.
=> NAS-110689 / 21.06 / Only consider interfaces in database for dhcp/ipv6 autoconfiguration

src/middlewared/middlewared/plugins/acme_protocol.py
This commit adds changes to ensure we properly validate that name specified for a DNS authenticator is not already in use.
=> NAS-110717 / 21.06 / Properly validate DNS authenticator names

src/freenas/usr/local/lib/middlewared_truenas/plugins/fcport.py
before my change the `initiators` key would return this on an HA system:
```
"initiators": [
"naa.21000024ff19a90a",
"naa.21000024ff19a90b",
"naa.21000024ff19a90b (TrueNAS Controller 1)",
"naa.21000024ff19a90a (TrueNAS Controller 1)"
]
```
after my change the `initiators` key returns this on HA systems:
```
"initiators": [
"naa.21000024ff19a90a (Active Controller)",
"naa.21000024ff19a90b (Active Controller)",
"naa.21000024ff19a90b (Standby Controller)",
"naa.21000024ff19a90a (Standby Controller)"
]
=> NAS-110769 / 12.0 / remove lxml from fcport and fix initators bug

src/middlewared/middlewared/plugins/catalogs_linux/items.py, src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
This PR adds changes to improve the speed for retrieving installed applications. With these changes we see around 30% improvement in the speed to installed chart releases.
=> NAS-110949 / 21.08 / Improve retrieving installed application(s) performance

tests/api2/test_011_user.py, tests/api2/test_340_pool_dataset.py, tests/api2/test_420_smb.py
test 02 of test_340_pool_dataset.py and test 002 of test_420_smb.py
I also removed "ixnas" from test 81 and 86 of test_420_smb.py
=> added acletype NFSV4 to test 30 in test_011_user.py

src/middlewared/middlewared/plugins/idmap.py
Do a bit more work to pinpoint the exact idmap range overlap.
=> NAS-110969 / 21.08 / Increase verbosity of range-related idmap verrors

src/middlewared/middlewared/plugins/idmap.py
Do a bit more work to pinpoint the exact idmap range overlap.
Original PR: https://github.com/truenas/middleware/pull/6989
Jira URL: https://jira.ixsystems.com/browse/NAS-110969
=> NAS-110969 / 12.0 / Increase verbosity of range-related idmap verrors (by anodos325)

src/middlewared/middlewared/plugins/catalogs_linux/update.py
This commit introduces changes to make catalog.create a job as we have seen if there's a huge catalog with lots of versions for each app with lots of apps in each train, it can take more then 60 seconds for the validation to complete.
=> NAS-110980 / 21.08 / Make catalog.create endpoint a job

src/middlewared/middlewared/plugins/vm/pci_linux.py
The built-in `xml.etree.ElementTree` has a `getchildren()` method but it gives a deprecation warning to use `list(elem)` instead so I've done that in this module as well.
=> NAS-110945 / 21.08 / remove lxml from vm/pci_linux plugin

src/middlewared/middlewared/plugins/smb.py
Since SMB shares will traverse mountpoints verify that new
share is not a child or parent of a share with different AFP
compatibility settings.
=> NAS-111022 / 21.08 / Add validation related to legacy AFP shares

tests/api2/test_425_smb_protocol.py
Removed the duplication of DOSmode
=> DOCS-2270 / Fixed missing inports for smb_protocol.test_151_set_xattr_via_ssh

src/middlewared/middlewared/etc_files/krb5.keytab.py, src/middlewared/middlewared/plugins/kerberos.py
This fixes some nuances of differences between MIT and heimdal
kerberos tools regarding handling of kerberos keytabs and
behavior of CLI tools.
=> NAS-111073 / 21.08 / Fix MIT kerberos keytab handling

src/middlewared/middlewared/plugins/pool.py
=> NAS-111081 / 21.08 / Fix setting default SMB ACL on dataset creation

src/middlewared/middlewared/plugins/pool.py
Before the change the recommended zvol blocksize on a 5wZ1 was 16K which proves to be highly space inefficient due to underlying ZFS math for storing the data. Further investigation showed that we were doing the same for the larger parity RAID layouts.
With this change, the new calculations are as follows:
```
2w/3w mirror = 16K
3wZ1, 4wZ2, 5wZ3 = 16K
4w/5wZ1, 5w/6wZ2, 6w/7wZ3 = 32K
6w/7w/8w/9wZ1, 7w/8w/9w/10wZ2, 8w/9w/10w/11wZ3 = 64K
10w+Z1, 11w+Z2, 12w+Z3 = 128K
```
Reviewed with performance team and @amotin
=> NAS-111046 / 21.08 / update recommended zvol blocksize depending on zpool geometry

src/middlewared/middlewared/plugins/failover_/detect_enclosure_linux.py
Internally, we're testing SCALE HA functionality by configuring BHYVE hypervisors a specific way. However, before this change, the code actually caused any SCALE VM that's installed on a BHYVE hypervisor to return `SCALE_ENTERPRISE` which is incorrect. (i.e. a TN Core user installs a SCALE VM)
Change it so that we only return `BHYVE` based on how we configure our internal BHYVE hypervisors.
=> NAS-111122 / 21.08 / fix BHYVE SCALE HA VM detection

tests/api2/test_108_catalog.py
This commit fixes api tests to update them to treat some endpoints which have been updated recently to jobs.
=> NAS-111174 / 21.08 / Fix api tests for catalog

src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
nfs4xdr_setfacl will print JSON validation errors
to stdout and return EX_DATAERR if payload is invalid.
This should be properly converted to ValidationErrors.
=> NAS-111248 / 21.08 / Convert JSON validation errors ValidationErrors

src/middlewared/middlewared/plugins/enclosure.py, src/middlewared/middlewared/plugins/enclosure_/map.py
Specifically returning single mapped enclosure for Head of system.
Previous method was not NEP compliant and did not work
=> NAS-111259 / 21.08 / Fix R20/R20A to comply to enclosure management NEP

src/middlewared/middlewared/plugins/enclosure.py, src/middlewared/middlewared/plugins/enclosure_/map.py
Including Fixes for Mini-E+ and future R20 Systems  with cobra expanders
=> NAS-111343 / 21.08 / Additional Enclosure Fixes

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py, src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/map.py
Including Fixes for Mini-E+ and future R20 Systems  with cobra expanders
Original PR: https://github.com/truenas/middleware/pull/7123
Jira URL: https://jira.ixsystems.com/browse/NAS-111343
=> NAS-111343 / 12.0 / Additional Enclosure Fixes (by darkfiberiru)

src/middlewared/middlewared/plugins/pool.py
With these changes, pool.dataset create/update operations perform constant in time. This improves speed when there are lot of sibling datasets.
=> NAS-111042 / 12.0 / pool.dataset: optimized create/update operations

src/freenas/usr/local/libexec/smart_alert.py
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900244
https://bugs.launchpad.net/ubuntu/+source/smartmontools/+bug/1878264
=> NAS-111333 / 21.08 / Filter "number of Error Log entries increased" for nvme devices until upstream bugs are fixed.

tests/api2/test_530_ups.py
This commit adds changes to update ups plugin tests to account for the email related removed fields.
=> NAS-111402 / 21.08 / Fix api tests for ups plugin

src/middlewared/middlewared/plugins/pool.py
git cherry-pick -x 3651bfec1282a193029fa7c6c223d843d0822952
Original PR: https://github.com/truenas/middleware/pull/7008
Jira URL: https://jira.ixsystems.com/browse/NAS-110987
=> NAS-110987 / 12.0 / Dataset checksum (by themylogin)

src/middlewared/middlewared/etc_files/pam.d/common-auth.mako
Add missing pam_unix directive
=> NAS-111416 / 21.08 / fix pam

src/middlewared/middlewared/plugins/auth.py, src/middlewared/middlewared/plugins/network.py
`sockstat` on linux is buggy and unmaintained. Use linux native tool (`lsof`) to accomplish the task.
=> NAS-111375 / 21.08 / remove sockstat calls on SCALE

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
Historically speaking, this is old cold that has been here since the legacy webUI. However, we're handling the situation incorrectly. This will turn the fault light on for spare hard drives when they get attached to a zpool when a data disk becomes unavailable.
We turn the `fault` light on for _all_ disks on the zpool and then subsequently `clear` them out based on what type of zfs disk they are at the end of the `zpool_sync` method. This doesn't make a lot of sense to me but in the interest of not making incredibly intrusive changes I've fixed 2 problems.
1. stop turning the `fault` light on by default (this is legacy code that makes 0 sense)
2. we were iterating over the spare devices incorrectly which means the z-series devices will no longer have the spare drives `identify` light …
=> NAS-111422 / 12.0 / fix issues in enclosure.sync_zpool

tests/api2/test_005_interface.py, tests/api2/test_009_pool.py, tests/functions.py
Remove failover_aliases and virtual_aliases netmask from test 15
Replaced expect_state with with wait_on_job in test_009_pool.py
Changed wait_on_job to 3 minutes since it was timing out with 60 seconds.
Changed to_recompile string with raw string
=> DOCS-2413 / 21.08 / Fixed interface for HA

src/middlewared/middlewared/plugins/cluster_linux/ctdb_public.py
Fix 2 main issues:
- the combination of ctdb reporting and/or the on-disk config of public addresses needs to be accounted for so that no matter what scenario the system might be in, the returned output is always the same (with the exception of the `pnn` but that's unavoidable and doesn't cause harm)
- `ctdb delip` and `ctdb addip` do not actually delete or add a public address contrary to the man pages. Instead, write the config file and then call `ctdb reloadips` which reads the config file and does what we expect it to do.
=> NAS-111535 / 21.08 / fix edge-case scenarios with ctdb public addresses

src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/service.py
git cherry-pick -x 02ca757b898ed135a06198a8ba77ff776fb68d08
git cherry-pick -x 4cee5fe353b31c0c3c543c2c0328711619e43007
git cherry-pick -x 66acf35df78109272b06076545a495afbfa31a73
Original PR: https://github.com/truenas/middleware/pull/7192
Jira URL: https://jira.ixsystems.com/browse/NAS-111459
=> NAS-111487 / 12.0 / Do not crash pool.dataset.kill_processes if a process has terminated on its own (by themylogin)

src/middlewared/middlewared/apidocs/templates/websocket/events.md, src/middlewared/middlewared/client/client.py, src/middlewared/middlewared/common/event_source/manager.py, src/middlewared/middlewared/event.py, src/middlewared/middlewared/main.py, src/middlewared/middlewared/plugins/kubernetes_linux/pods.py, src/middlewared/middlewared/plugins/reporting/processes.py, src/middlewared/middlewared/schema.py, src/middlewared/middlewared/service.py, src/middlewared/middlewared/utils/plugins.py, src/middlewared/middlewared/worker.py
1) Allow documenting return type(s) for events and event sources.
2) Allow documenting accept type(s) for event sources.
3) Raise validation error(s) if accept response is malformed for event source(s).
4) Sending error(s) to subscribed consumers of the event if the event source(s) error out for any reason.
5) Bug fixes for middleware client wrt event subscription.
6) Validate returns for events/event sources when running in debug mode.
=> NAS-110984 / 21.08 / Improvements to middleware event handling

src/middlewared/middlewared/plugins/pool.py
aclinherit should be enabled for NFSv4 ACL, but disabled for
others. First-level dataset shouldn't inherit acltype from pool.
Depending on origin of pool, acltype may be set to OFF which is
not a sensible default when all things are considered. Hence,
if it's set to 'INHERIT' and depth is 1, then default to POSIX1E.
=> NAS-109823 / 21.08 / Set correct defaults for ACL parameters on dataset creation

src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py
1) Retrieve all versions which the current app can upgrade to
2) Add more metadata to help the UI provide a clear picture of the upgrade
=> NAS-111597 / 21.08 / Retrieve more useful information for app upgrade summary

src/middlewared/middlewared/plugins/idmap.py
range_low, range_high, and backend are required.
=> NAS-111621 / 21.08 / Improve validators for idmap plugin

src/middlewared/middlewared/plugins/pool.py, src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py, tests/api2/test_425_smb_protocol.py
Several fixes for the API test and associated smb.conf parameters.
=> NAS-111689 / 21.08 / Fixes for test_425_smb_protocol

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py, src/middlewared/middlewared/plugins/disk_/sync.py
1. Dont immediately sleep in `disk.sync_all` for 1 second without checking to see if `devd` is connected. Instead see if it's connected first and then sleep appropriately.
2. Only call `enclosure.query` once so that we don't call it N times (N being the number of disks on the system)
=> NAS-111690 / 12.0 / call enclosure.query once in disk.sync_all

src/middlewared/middlewared/plugins/activedirectory.py
Support for clustering required changing to storing AD state
in all cases (even DISABLED). Also remove kerberos principal
info when leaving AD.
=> Fixes for Active Directory regression tests

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
1. No reason to call `truenas.get_chassis_hardware` for every zpool on system so call it outside for loop.
2. `disk.label_to_disk` is abysmally slow when it has to run `geom.scan()`, instead use new `label_to_dev_disk_cache` method to essentially make this portion of the method instant.
3. `_get_ses_slot_for_disk` calls `enclosure.query` but we already enumerate the enclosures at the top of this method in the `encs` variable. Use the built-in `find_device_slot` instead to prevent unnecessary `enclosure.query` calls for every disk on every zpool.
Before changes `enclosure.sync_zpool` was taking ~5mins+ on M60 with 417 disks.
After changes `enclosure.sync_zpool` is taking ~21seconds on M60 with 417 disks.
=> NAS-111693 / 12.0 / fix enclosure.sync_zpool

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
While steps have been taken to speed up `system.info`, it's still expensive. Especially on large/busy systems. Furthermore, the enclosure plugin only needs the `system-product-name` from the dmi information. `system.dmidecode_info` is cached at first boot and far less expensive than `system.info` so use it instead in the enclosure plugin.
=> NAS-111696 / 12.0 / dont call system.info in enclosure plugin

src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py, tests/api2/test_420_smb.py
Update regression tests to use correct / new internal API returns for SMB groupmap information.
Add more validation for some SMB share parameters.
Fix recycle bin and time machine edge case configurations.
=> NAS-111706 / 21.08 / Fixes for base SMB regression tests

src/middlewared/middlewared/common/smart/smartctl.py, src/middlewared/middlewared/etc_files/smartd.py, src/middlewared/middlewared/plugins/system.py
git cherry-pick -x fa7f67a89841bae4c1ede5f06b17ec8727c55f47
git cherry-pick -x e033a03099b5af3190097be1343583762be990f9
Original PR: https://github.com/truenas/middleware/pull/7263
Jira URL: https://jira.ixsystems.com/browse/NAS-111682
=> NAS-111682 / 21.08 / Improve smartd restart performance (by themylogin)

src/middlewared/middlewared/alert/source/quota.py
Dataset owner may be user from directory service. In this
case a datastore query will fail with IndexError and we'll
generate a spurious log message.
There's basically two things we need to know here:
* email address
* whether user is valid
Do passwd lookup to determine user validity, then perform
datastore query to determine whether email address is available.
Theoretically, we could perform LDAP query to try to find email address from AD or LDAP, but email address there may be incorrect / out of date (and it also adds some complexity).
=> NAS-111603 / 21.08 / Fix quota alert for dataset owner

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
`disk.sync_all` and `enclosure.sync_zpool` are expensive on very large systems (100's of disks) so move when we call them to after the necessary services have been restarted since nothing is dependent on those.
Also, we weren't waiting on `disk.sync_all` job to finish before calling `enclosure.sync_zpool`
=> NAS-111764 / 12.0 / move disk.sync_all and enclosure.sync_zpool on HA

src/middlewared/middlewared/plugins/vmware.py
This was broken by acef89b7413859a9bbe70226139756be3551b784
=> NAS-111819 / 12.0 / Fix taking vmware-aware manual snapshots

src/middlewared/middlewared/plugins/smb.py
Changes to share guest access require alteration of global SMB
server configuration. Specifically, we need to ensure that
"map to guest" is always set to "Bad User" in this case. This
parameter is generally set to "Never" because modern windows
versions will deny access to SMB share if user it received does
not match one that it requested, which has the effect of causing
unexpected denial of access to the SMB server in general as this
also applies to the server's IPC$ share.
This change fixes this behavior in SCALE, where the transition
to using the registry for storing SMB configuration details
caused a regression. The specific change is to expand the
situations where sharing.smb.create and sharing.smb.update
will re-initialize the global SMB parameters and restart the
SMB server. The …
=> NAS-111847 / 21.08 / Enforce global configuration reload on share guest access change

tests/api2/test_420_smb.py
There are behavior nuances related to when we grant IPC$ access
for share enumeration. Update test to account for these so that
we have more complete coverage of this feature.
=> NAS-111848 / 21.08 / Improve share enumeration test

src/middlewared/middlewared/plugins/smb.py
Initializing a samba3 loadparm context requires that middleware
open registry.tdb and initialize a full s3 context. This PR
switches us to use a different samba python module that is
lighter-weight and doesn't require the tdb open. As a side-effect
it's utility is more limited in scope. It can be used to
look up default values for parameters (which may change between
samba releases), and it can be used to validate SMB auxiliary
parameters. The key limitation to it is that the limited
loadparm context can't be used to read parameters that are stored
in the static configuration file (/etc/smb4.conf) and so we
need an alternate method to read non-default parameters in that
file. In this case, we simply read and convert into JSON types.
There should only be a limited number of well-known …
=> NAS-111902 / 21.10 / Remove dependency on samba3 loadparm context

src/middlewared/middlewared/etc_files/krb5.conf.mako
An invalid krb5.conf file will result in failures for all
CLI utilities (including klist).
=> NAS-111917 / 21.10 / Avoid generating invalid krb5.conf

src/middlewared/middlewared/plugins/interface/netif_linux/ethernet_settings.py
Using the `pyroute2.ethtool.Ethtool` module as well as using the `ethtool` CLI tool produced the same output so document the situation and catch the exception accordingly so we don't spam the logs unnecessarily.
=> NAS-111881 / 21.10 / catch NoSuchDevice in ethtool

src/middlewared/middlewared/alembic/versions/21.MM/2021-08-19_09-30_ca_trusted_store.py, src/middlewared/middlewared/etc_files/generate_ssl_certs.py, src/middlewared/middlewared/plugins/crypto.py
This PR adds changes to update system's trusted certificate store with CAs user has explicitly requested to be added to the system's store.
=> NAS-111529 / 21.10 / Update system's trusted certificate store with TN CAs

src/middlewared/middlewared/plugins/smb.py
netbiosname_local is value that is applied to registry running
configuraiton. Ensure that we actually apply the new config
(passing through the extend() method) rather than the updated
dict. Shift service restart to end of smb.update() method
so that vfs_fruit changes are picked up by SMB clients as they
reconnect.
=> NAS-111995 / 21.10 / Fix out of order operations in applying smb config

src/middlewared/middlewared/plugins/zfs_/zfs_events.py
…ted by replication
Original PR: https://github.com/truenas/middleware/pull/7432
Jira URL: https://jira.ixsystems.com/browse/NAS-112081
=> NAS-112081 / 21.08-BETA.1 / Ignore deletion of hidden daatset clones such as `%recv` dataset crea… (by themylogin)

src/middlewared/middlewared/schema.py
This commit introduces changes to OR Operator schema which makes sure that we dump the specified value according to the schemas available.
=> NAS-112090 / 21.10 / Add dump endpoint for or-operator schema

src/middlewared/middlewared/plugins/filesystem_/acl_base.py, src/middlewared/middlewared/plugins/filesystem_/acl_linux.py, src/middlewared/middlewared/plugins/pool.py
Leverage OROperator and other schema options to normalize accepts and returns for filesystem acl methods.
=> NAS-112089 / 21.10 / Add returns to filesystem acl

src/middlewared/middlewared/plugins/account.py
Remove SMB keys prior to attempting DB insertion.
=> NAS-112098 / 21.10 / Fix KeyError on User / Group creation

tests/api2/test_210_group.py
This commit changes a couple of minor details about how this
group of tests is written.
- SSH_CMD to run `getent group` is replaced with `get_group_obj` call
through API. In this case the API call is a wrapper around
the python `grp` module and therefore does the same thing as
an explicit call to getent group.
- Replace SSH_CMD to `midclt call smb.groupmap_list` (private API)
with calls to `group.query` with `additional_information: ["SMB"]`
specified. This has the advantage of (1) being a public API,
(2) adding test coverage for the `additional_information` in the
group plugin, and (3) optimizing the test somewhat.
=> NAS-112111 / 21.10 / Update group api tests to use 'additional_information'

tests/api2/test_011_user.py
We can optimize away some passdb_list calls through
SSH_CMD in some instances in the test_011 while also
providing test coverage for querying additional-information
through user.query.
=> NAS-112112 / 21.10 / query SMB information through user plugin in tests

src/middlewared/middlewared/client/client.py, src/middlewared/middlewared/plugins/reporting/plugins.py, src/middlewared/middlewared/plugins/reporting/rrd_utils.py, src/middlewared/middlewared/plugins/reporting/update.py
git cherry-pick -x f8b845917cc9fefbcd913a88ef4c6cd2428651a6
Original PR: https://github.com/truenas/middleware/pull/7452
Jira URL: https://jira.ixsystems.com/browse/NAS-109873
=> NAS-109873 / 12.0 / Check for RRD update time in the future (by themylogin)

src/middlewared/middlewared/plugins/failover_/event.py
Many improvements were made to system dataset configuration/migration on SCALE. However, we were calling a method that no longer existed.
1. use the new method `systemdataset.setup`
2. No reason to start/stop rrdcached, collectd or syslogd since `systemdataset.setup` does that for us.
3. Only need to stop `rrdcached` when becoming backup as that service will handle `collectd`
=> NAS-112051 / 21.10 / fix regression with sysdataset on failover (SCALE)

tests/api2/test_210_group.py
Verify the following:
- Local server SID is used as prefix for local builtin accounts.
- local builtin accounts are added as foreign members to
appropriate NT BUILTIN groups.
- NT BUILTIN group mappings exist
=> NAS-112148 / 21.10 / Add test for complex groupmap behavior

src/middlewared/middlewared/plugins/smb.py
Only attempt to remove share security and registry entry if it exists. This may result in stale references to share in share security database after removal of encrypted or disabled share, but at this point there is not an easy method to clean up the entry since it may be in a clustered or non-clustered share_info.tdb.
=> NAS-112169 / 21.10 / Check for SMB share registry entry before cleanup in delete

tests/api2/smb.py, tests/functions.py
Fixed send_file and get_file functions in functions.py
moved test 004 in test 003
=> DOCS-2032 / 12.0 / Added tests to make sure robocopy timestamp is kept

src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh
Only attempt to get acl for dataset mountpoint if dataset is
mounted and has a non-legacy mountpoint.
=> NAS-112207 / 12.0 / Fix dataset listing for cases of zvol and unmounted datasets

src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh
Only attempt to get acl for dataset mountpoint if dataset is
mounted and has a non-legacy mountpoint.
Original PR: https://github.com/truenas/middleware/pull/7485
Jira URL: https://jira.ixsystems.com/browse/NAS-112207
=> NAS-112207 / 13.0 / Fix dataset listing for cases of zvol and unmounted datasets (by anodos325)

tests/api2/test_420_smb.py, tests/functions.py
Fixed send_file and get_file functions in functions.py
=>  DOCS-2032 / 21.10 / Added tests to make sure a robocopy keep timestamp in the share

src/middlewared/middlewared/plugins/kubernetes_linux/pods.py
This commit adds changes to ignore daemonset related pods by default as we don't officially support using them. Their primary use case is making sure that you have a pod running on each node, however for our usecase we only have a single node and they have different properties from deployments/statefulsets which can be scaled up/down which is not true for daemonsets. Right now service-lb ( built in load balancer service provided by k3s ) uses daemonsets to find/manage hostports, this change also tackles that case where if laod balancer service is being used, middleware will not wait for operations related to the app be stopped/influenced by the load balancer pods because they are meant to be running and they are separate from the app itself.
=> NAS-112186 / 21.10 / Ignore pods managed by daemonsets by default

src/middlewared/middlewared/plugins/ldap.py
This helps to standardize LDAP access and provides a somewhat
more abstract mechanism for interacting with remote LDAP servers
(if needed for AD plugin or other parts of middleware).
=> NAS-111838 / 21.10 / Move LDAP client code into explicit service plugin

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py, src/middlewared/middlewared/plugins/kubernetes_linux/update.py
This PR adds changes to enforce certain properties on ix-applications dataset otherwise we get behavior which can change and result in wrong permissions and other issues inside containers like binaries not executing etc.
=> NAS-112181 / 21.10 / Enforce certain properties on ix-applications dataset

tests/cluster/config.py, tests/cluster/exceptions.py, tests/cluster/initialize_cluster.py, tests/cluster/run-cluster-tests.py, tests/cluster/utils.py
This adds a new area `middlewared/tests/cluster` that will be used for writing cluster specific API tests. This commit is the first part needed before actually writing the api tests.
1. create `run-cluster-tests.py` that will be called by an internal Jenkins CI job
2. store the various cluster related config in `config.py` so when changes are made we don't have to rewrite everything
3. write wrapper methods for making REST and/or Websocket calls in `utils.py`
4. add `--initialize-cluster` argument to `run-cluster-tests.py` that is responsible for "initializing" all the cluster nodes on each Jenkins CI job since the cluster config is wiped (by design) when the Jenkins job is run.
5. adds wrapper methods for running ssh commands on the nodes in the cluster (untested)
=> NAS-112123 / 21.10 / create cluster API test framework

src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/kerberos.py, src/middlewared/middlewared/plugins/nfs_/krb5.py, src/middlewared/middlewared/service.py
Includes internal changes to better validate methods
that use kerberos tickets or need to kinit.
=> NAS-112136 / 21.10 / Add returns decorator to kerberos methods

src/middlewared/middlewared/etc_files/ctld.py
The changes in `12.0-U5.1` to optimize systems with 100's+ of hard drives broke an edge-case where we allow configuration of iSCSI on CORE sharing raw disks. (SCALE does not allow this, thankfully).
=> NAS-112299 / 12.0 / fix ctld.conf generation when sharing raw disks

src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
Since this permissions changes to these paths would most likely
result in significant and not easily recoverable issues,
=> NAS-112314 / 21.10 / Prevent permissions changes to contents of ix-applications

src/middlewared/middlewared/plugins/network.py, tests/api2/smb.py
Set appropriate HA node NetBIOS name depending on HA configuration.
=> NAS-110762 / 12.0 / Make netbiosname tests ha-aware

src/middlewared/middlewared/plugins/interface/bridge.py, src/middlewared/middlewared/plugins/network.py
Bridge devices on SCALE do not require the unnecessary complexity for managing the bridge member's MTU's. That is all handled by the kernel.
=> NAS-112264 / 21.10 / fix bridge MTU logic on SCALE

src/middlewared/middlewared/plugins/smb_/groupmap.py
If group_mapping.tdb contains a duplicate gid entries,
then append second entry to `invalid` list to be deleted
during batch OPs. Also ensure that we always have entry
for S-1-5-32-545.
=> NAS-112362 / 21.10 / groupmap - handle case of duplicate gid entries

tests/boot.exp, tests/install.exp
Changed the install timeout to 20 min instead of 30 minutes
Changed the boot timeout to 12 min instead of 30 minutes
=> DOCS-2373 / 21.10 / Added propper timeout with exit 1 in boot.exp and install.exp

tests/boot.exp, tests/install.exp
changed the install timeout to 20 min instead of 30 minutes
changed the boot timeout to 12 min instead of 30 min
=> DOCS-2373 / 12.0 / Added propper timeout with exit 1 in boot.exp and install.exp 

src/middlewared/middlewared/plugins/network.py
SCALE HA no longer uses multicast messages for VRRP traffic. It uses unicast so there is no reason to keep a method around that isn't needed and, furthermore, isn't called anywhere.
=> NAS-112437 / 21.10 / remove scan_vrrp from network.py

src/middlewared/middlewared/plugins/activedirectory.py, src/middlewared/middlewared/plugins/smb.py, src/middlewared/middlewared/plugins/smb_/registry_global.py, src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py
Ensure `obey pam restrictions` is set when home share
is enabled.
=> NAS-112533 / 21.10 / Fix automatic home directory creation

tests/api2/test_050_alert.py
Those test are not for HA only SCALE
=> DOCS-2621 / 21.10 / Added skip if HA for core files alert tests

tests/api2/alert.py
Those are not for HA only CORE
=> DOCS-2621 / 12.0 / Added skip if HA for core files alert tests

src/middlewared/middlewared/plugins/pool.py
Subtle differences between CORE and SCALE.
=> NAS-112578 / 21.10 / fix ds creation on SCALE

tests/api2/test_050_alert.py
Added test to restor corefiles alert and to verify it is restart
Added test to remove the python core file and added test to verify that
the alert will disappear.
=> DOCS-2367 / 21.10 / Replaced kill smbd with 'python3 -c "import os; os.abort()"'

tests/api2/smb_vss.py
Flush out samba's gencache before starting test, also
chown datasets so that they're owned by our SMB user.
=> NAS-112605 / 12.0 / Ensure we have clean state for SMB VSS tests

src/middlewared/middlewared/plugins/auth.py, tests/api2/test_012_api_key.py
git cherry-pick -x 74cc57c50e5566f3290a784dc7a9b85fc01fd721
git cherry-pick -x a65cda470a6e2b7ca6495c48f90a8eb69e28bbe1
Original PR: https://github.com/truenas/middleware/pull/7622
Jira URL: https://jira.ixsystems.com/browse/NAS-112656
=> NAS-112656 / 21.08-BETA.1 / Run midclt as non-privileged user in API key tests (by themylogin)

src/middlewared/middlewared/plugins/smart.py
…_choices
Original PR: https://github.com/truenas/middleware/pull/7623
Jira URL: https://jira.ixsystems.com/browse/NAS-112357
=> NAS-112357 / 12.0 / Do not include disks that do not spport S.M.A.R.T. in smart.test.disk… (by themylogin)

src/middlewared/middlewared/plugins/disk_/wipe.py
This is 2 cherry-picks from 13 branch:
1. 141134141f89b6201f3d0726c8d62c7451dff5e0
2. 0b4b5cfc71018c0ce1b7ee735eacadddf245adf7
This dramatically improves the process for "wiping" a disk. Before my changes, we were doing the following:
1. `dd`'ing first 32MB of disk
2. `dd`'ing any partition table offsets (if they were detected)
3. `dd`'ing the last 32MB of disk
4. `gpart destroy -f` the disk (after `dd`)
5. `gpart create -s gpt`
6. `gpart destroy -f` again...
(because of our process we were opening the underlying disk(s) many times unnecessarily)
To add insult to injury, we are doing this all using `subprocess` which is expensive and inefficient. Furthermore, there is a race between when `dd` is done and the GEOM thread goes idle before we call `gpart destroy`. See …
=> NAS-112681 / 12.0 / improve the process for formatting disks (by yocalebo)

src/middlewared/middlewared/plugins/zfs_/disks_freebsd.py
This was rather ridiculous.
1. `pool.get_disks` calls `pool.get_reserved`
2. `pool.get_reserved` calls an async generator function `zfs.pool.get_disks` (this creates a child process)
3. `zfs.pool.get_disks` calls `zfs.pool.get_devices` which spawns a grandchild
Each child and grandchild has to get a copy of that xml data from the parent process which is particularly painful if there are a lot of disks.
Fix this by doing 2 major things:
1. use `with libzfs.ZFS()` directly in this method to not spin up another child process since this method is already in its own child process
2. use the `disk.label_to_dev_disk_cache` method which is a manageable dict of geom xml disk information. Generate this once in the parent and then iterate normally.
The speed difference is quite dramatic.
```
OLD: …
```
=> NAS-112699 / 12.0 / fix pool.get_disks

src/middlewared/middlewared/plugins/chart_releases_linux/validation.py
This commit adds changes to remove the chart context which is added by us to global key. Global key is special as in that it is shared with dependencies/subcharts which means that it is entirely possible that it is already being specified by chart dev to specify some global values for the chart(s) and in this case we just want to remove what global chart context we added as otherwise validation would fail because that context is not expected and not specified in the chart / app schema.
=> NAS-113175 / 22.02-RC.2 / Remove chart context added when doing validation

tests/api2/alert.py
=> DOCS-2821 / 12.0-U6.1 / Fixed alert test 09 and test 18

tests/api2/test_435_smb_registry.py
Test results: https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/API%20Tests%20-%20TrueNAS%20SCALE%20from%20branch%20(Incremental)/
=> DOCS-2828 / 22.02-RC.2 / Fixed smb_registry test 10 and 11 with set instead of list

src/middlewared/middlewared/plugins/device_/device_info_linux.py
This commit adds changes to not repeatedly log an error if we failed to retrieve rotational rate for some device.
=> NAS-113272 / 22.02-RC.2 / Do not repeatedly log same error

src/middlewared/middlewared/plugins/support.py
git cherry-pick -x b4a079d16954ff9a721f9386f89f279551be584a
Original PR: https://github.com/truenas/middleware/pull/7648
Jira URL: https://jira.ixsystems.com/browse/NAS-112709
=> NAS-112709 / 13.0 / Prevent `{"message": "Internal server error"}` leaking as `message` support-proxy category (by themylogin)

src/middlewared/middlewared/plugins/account.py, src/middlewared/middlewared/plugins/network.py
=> NAS-113288 / 22.02-RC.2 / Fix a couple of incorrect schemas

src/middlewared/middlewared/plugins/migration.py
I simply missed this with my last commit to master. 13 has the commit.
=> ha_sync = False for keyvalue.set run_migration

src/middlewared/middlewared/plugins/cluster_linux/ctdb_general.py, src/middlewared/middlewared/plugins/cluster_linux/ctdb_setup.py
* fix initialization of ctdb public ips
* check ctdb shared volume is fuse mounted
Cherry-picked from 9421e2118bf23cad735270ab24dde648f9e33624
=> NAS-113077 / 22.02-RC.1-2 / fix initialization of ctdb public ips (#7774)

src/middlewared/middlewared/plugins/ssh.py
No reason to update the database with a huge amount of `ascii` text if none of the keys have changed.
Original PR: https://github.com/truenas/middleware/pull/7843
Jira URL: https://jira.ixsystems.com/browse/NAS-113281
=> NAS-113281 / 13.0 / only run ssh.save_keys when necessary (by yocalebo)

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
This commit adds changes to make sure SED disks are unlocked on HA systems. With the changes introduced, we make sure that we always try to unlock SED disks when backup becomes master node eliminating any race conditions which might come synchronizing if master has already unlocked sed disks or not. Secondly if user changes sed disks password and initiates a failover assuming the system would unlock SED disks, it would not happen as we don't try to unlock sed disks when backup becomes master.
=> NAS-113352 / 12.0 / Make sure SED disks are unlocked on HA systems

src/middlewared/middlewared/alert/source/reporting_db.py
git cherry-pick -x 930ec678e8366de24fe72f035ca429edd6347dc5
git cherry-pick -x d4bc0e4815f75054a2ad465d550c06a163d5fa53
Original PR: https://github.com/truenas/middleware/pull/7874
Jira URL: https://jira.ixsystems.com/browse/NAS-113367
=> NAS-113367 / 22.02-RC.2 / Allow larger reporting databases (by themylogin)

src/middlewared/middlewared/plugins/failover.py
On SCALE HA, if we call the `failover.become_passive` on the active node a failover event is immediately triggered and sent to the other controller. If the node the API call was issued on reboots via the sysrq trigger, then the websocket connection between the 2 nodes is still considered "up" because the connection was severed forcefully. At the same time the underlying socket remains alive because the default TCP timeout hasn't elapsed to mark the connection as dead.
When this occurs, `failover.status` is called and it hangs for 60+ seconds which is unacceptable. Furthermore, the webUI doesn't know how to handle this and so the login is never shown. To fix all the above situations, I use `timeout` parameter so that the request will be cancelled immediately after the 5 seconds elapses.
=> NAS-112904 / 22.02-RC.2 / fix failover.status hanging for 60+ seconds
