src/middlewared/middlewared/plugins/system.py

system.is_stable

---

src/middlewared/middlewared/plugins/gluster_linux/local_events.py

Cherry-picked from 3ba110606356985842577ac71f5f20776da98995

increase timeout from 5 to 30 (#7875)

---

src/middlewared/middlewared/plugins/ldap.py

Set the LDAP directory service state to JOINING while starting the service, and trigger
FAULTED state if exception is raised during start/stop. Setting to JOINING is sufficient
to ensure that ldap entry is added to nsswitch.conf and so nss generation can be
moved back to happening before nslcd service start.

NAS-113466 / 12.0 / Manage LDAP service state during service start

---

src/middlewared/middlewared/plugins/ldap.py

Set the LDAP directory service state to JOINING while starting the service, and trigger
FAULTED state if exception is raised during start/stop. Setting to JOINING is sufficient
to ensure that ldap entry is added to nsswitch.conf and so nss generation can be
moved back to happening before nslcd service start.
Original PR: https://github.com/truenas/middleware/pull/7904
Jira URL: https://jira.ixsystems.com/browse/NAS-113466

NAS-113466 / 13.0 / Manage LDAP service state during service start (by anodos325)

---

tests/api2/nfs.py

DOCS-2903 / 12.0 U7 / Adding a timeout of 60 seconds in nfs test 12 mounting nfs

---

src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py

This commit adds changes to add another key to have humanized app version for each history version of a chart release so that we can expose this in the UI when user wants to rollback to a previous version of the chart release.

NAS-113487 / 22.02-RC.2 / Have humanized app version for history of chart releases

---

src/middlewared/middlewared/plugins/pool.py

This commit adds changes to not reset mountpoints of ix-applications dataset as that's a dataset managed by us and if we reset mountpoints, PVC's require mountpoint of legacy as otherwise the apps consuming them won't deploy because of CSI not being able to mount the PVC.

NAS-113447 / 22.02-RC.2 / Do not reset mountpoints of ix-applications dataset when importing pool

---

src/middlewared/middlewared/logger.py
src/middlewared/middlewared/plugins/catalogs_linux/items.py
src/middlewared/middlewared/plugins/catalogs_linux/sync_catalogs.py
src/middlewared/middlewared/plugins/catalogs_linux/update.py
src/middlewared/middlewared/plugins/catalogs_linux/utils.py

- Set git client's logging level to CRITICAL
- Remove necessary logging and just leave exception raises

NAS-113580 / 22.02-RC.2 / Reduce noisy logs

---

src/middlewared/middlewared/plugins/failover_/event.py

This commit adds changes to make sure SED disks are unlocked on HA systems. With the changes introduced, we make sure that we always try to unlock SED disks when backup becomes master node eliminating any race conditions which might come synchronizing if master has already unlocked sed disks or not. Secondly if user changes sed disks password and initiates a failover assuming the system would unlock SED disks, it would not happen as we don't try to unlock sed disks when backup becomes master.
Original PR: https://github.com/truenas/middleware/pull/7868
Jira URL: https://jira.ixsystems.com/browse/NAS-113352

NAS-113352 / 22.02-RC.2 / Make sure SED disks are unlocked on HA systems (by sonicaj)

---

src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py

Ensure that rpc server is properly configured for fss if
it is enabled in SCALE.

NAS-113664 / 22.02 / Add required parameters for fsrvp in SCALE

---

src/middlewared/middlewared/plugins/tftp.py

Summary
-----
1. Added API for a valid list of host addresses
2. Added validation for host to be a valid IP
This is how it looks like:
We will probably need FE guys to integrate that API so that's a dropdown with host choices instead of an input field.

NAS-113527 / 22.02 / Add host validation for TFTP service

---

src/middlewared/middlewared/pytest/unit/test_schema.py
src/middlewared/middlewared/schema.py

NAS-104989 / 22.02 / Return IP network if schema wants an IP network

---

src/middlewared/middlewared/plugins/reporting/plugins.py

Do not try to "stack" them, stacking is only supported in SCALE UI.
Here it just confuses users with incorrect numbers.

NAS-111093 / 13.0 / Make reporting graphs consistent with top

---

src/middlewared/middlewared/pytest/unit/test_schema.py
src/middlewared/middlewared/schema.py

time 1:00
Original PR: https://github.com/truenas/middleware/pull/7989
Jira URL: https://jira.ixsystems.com/browse/NAS-104989

NAS-104989 / 13.0 / Return IP network if schema wants an IP network (by themylogin)

---

src/middlewared/middlewared/plugins/system_/dmi.py
src/middlewared/middlewared/pytest/unit/plugins/system/test_dmi.py

2 cherry-picks from SCALE. 05642ede81c and f83f3561852.

NAS-113852 / 13.0 / catch up dmi parsing in 13

---

tests/api2/test_025_chart_release.py
tests/api2/test_035_ad_idmap.py
tests/functions.py

Added some sleeps in chart test give time to the system to process everything
Added timeout of 60 second in SSH_TEST to make sure SSH command doesn't hang

DOCS-2981 / Added longer sleeps to ad_idmap test 8

---

tests/api2/test_025_chart_release.py
tests/api2/test_035_ad_idmap.py
tests/functions.py

Added some sleeps in chart test give time to the system to process everything
Added timeout of 60 second in SSH_TEST to make sure SSH command doesn't hang

DOCS-2981 / 22.02-RC.2 / Added longer sleeps to ad_idmap test 8

---

src/middlewared/middlewared/plugins/mail.py

already queued messages might not be sent due to (553, b'Relaying disallowed as xxx') error.

NAS-113740 / 22.02 / send_mail_queue: Update `From` address from currently used config because if the SMTP user changes,

---

tests/api2/test_300_nfs.py
tests/functions.py

DOCS-3006 / 22.02 / Changed the SSH_TEST timeout to 2 minutes

---

src/middlewared/middlewared/plugins/filesystem_/perm_check.py
src/middlewared/middlewared/utils/osc/linux/user_context.py

This PR adds changes to use python to change user context in a process and then having a reusable implementation which can be used in other places as required to execute certain functions as some user.

NAS-113937 / 22.02 / Improve executing commands with a user context implementation

---

src/middlewared/middlewared/alembic/versions/12.0/2021-12-22_12-59_add_server_tls_uri_to_s3_config.py
src/middlewared/middlewared/etc_files/rc.conf.py
src/middlewared/middlewared/plugins/s3.py

cherry picks: https://github.com/truenas/middleware/pull/8031

NAS-114027 / 13.0 / Fix TLS certificate issue on Minio web console (cherry-picked from 12.0-stable)

---

src/middlewared/middlewared/alembic/versions/12.0/2021-12-22_12-59_add_server_tls_uri_to_s3_config.py
src/middlewared/middlewared/alembic/versions/22.02/2021-12-27_11-19_merge.py
src/middlewared/middlewared/plugins/s3.py

- Migration is cherry picked from https://github.com/truenas/middleware/pull/8031
- Relevant minio updates for SCALE minio systemd unit: https://github.com/truenas/minio/pull/3

Fix TLS certificate issue on Minio web console

---

src/middlewared/middlewared/plugins/s3_/attachments.py

git cherry-pick -x 3c45539404b11c526e74820fdbf85fa463401d21
git cherry-pick -x 1aabae315c68a42fcc04245ada7ae43f88f7f8e4
Original PR: https://github.com/truenas/middleware/pull/8060
Jira URL: https://jira.ixsystems.com/browse/NAS-114020

NAS-114020 / 13.0 / Fix MinioFSAttachmentDelegate.query (by themylogin)

---

src/middlewared/middlewared/plugins/iscsi_/global_freebsd.py

@rick-mesta this is an easy fix for an important feature that has been broken since this summer. I would consider including it in 12.0-U7.1

NAS-113409 / 12.0 / Fix `iscsi.global.sessions`

---

src/middlewared/middlewared/alembic/versions/22.02/2022-01-07_15-01_x_frame_options.py
src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
src/middlewared/middlewared/plugins/system.py

This PR adds changes to allow having x-frame-options configurable for users who would like to use our UI with third party apps like organzr.

NAS-113943 / 22.02 / Make X-frame-options configurable

---

src/middlewared/middlewared/logger.py

In middleware log, i noticed lots of noise originating from pyroute logs - this commit adds changes to raise levels to critical to only log errors which are critical.

NAS-114279 / 22.02 / Reduce pyroute logs footprint in middleware logs

---

src/middlewared/middlewared/plugins/network_/dns.py

If we don't have DNS servers configured explicitly by user, then check if DHCP has handed us one when calling `dns.sync`.

NAS-114012 / 22.02 / fix dns.sync when only DHCP is running

---

src/middlewared/middlewared/plugins/pool.py

I've no idea how these missed the original PR but they were. Fixes creating and updating zpools with hot-spares on 13.

NAS-114571 / 13.0 / fix creating/updating zpools with hot-spares on 13

---

src/middlewared/middlewared/etc_files/exports.mako

* enclose path with quotes
* default to "sys" if nfs.sec returns an empty list

NAS-114541 / 22.02 / Fix a few edge cases with exports generation

---

src/middlewared/middlewared/plugins/cloud_sync.py

git cherry-pick -x 1cd16b2b2308bf3b6299fce2555ae1a6bd07c985
Original PR: https://github.com/truenas/middleware/pull/8143
Jira URL: https://jira.ixsystems.com/browse/NAS-114176

NAS-114176 / 13.0 / Do not crash cloud sync from snapshot when a zvol is present (by themylogin)

---

src/middlewared/middlewared/plugins/geom.py

This catches up the `geom.cache` plugin with what was done in 5eb5d78b36fbd62dfceb76ca2380853d353b3eac

NAS-114714 / 13.0 / add disk driver information to geom.cache plugin

---

src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py

We currently support Nvidia and Intel GPU vendors.
For each GPU vendor, we deploy its `device-plugin` as a daemonset into `kube-system` namespace if we have found relevant vendor's GPU(s) on the hardware. The `device-plugin` daemonset is responsible for informing kubernetes about corresponding vendor's GPUs allocations that is, makes them `allocatable='1'`. These allocatable GPUs show up for selection in various catalog apps that may make use of GPUs (e.g. `plex`)
When one or more GPUs are removed, kubernetes marks them `allocatable='0'` through device-plugin. When all of the GPUs for a vendor are removed then relevant `device-plugin` daemonset is also deleted and kubernetes makes all of the GPUs `allocatable='0'`
I have seen during a TV session for a user that kubernetes somehow got …

NAS-114514 / 22.02.1 / Do not rely solely on k8s to provide the available GPUs

---

tests/api2/test_300_nfs.py

This test verifies that the exports file is appropraitely changed
as we alter the value of this global parameter.

NAS-114809 / 22.02.1 / Add test for NFS "allow nonroot"

---

src/middlewared/middlewared/plugins/zfs.py

This reverts commit 0be81b9e0a755ef49b4b3ef47a678c927079f8a9.

Bring snapshots annotation back

---

src/middlewared/middlewared/plugins/crypto.py

This commit fixes issues with the implementation allowing wildcard certificate to be created.

NAS-114761 / 13.0 / Add support for creating wildcard ACME certs in 13

---

src/middlewared/middlewared/plugins/catalogs_linux/features.py
src/middlewared/middlewared/plugins/chart_releases_linux/validation.py

- Add support for nested subquestions validations
- Add hostPath $ref validations
- Add lockedHostPath $ref validations
- Add hostPathAttachments $ref validations

NAS-114689 / 22.02.1 / Add a $ref for hostPath schema validation

---

src/middlewared/middlewared/plugins/catalogs_linux/features.py
src/middlewared/middlewared/plugins/chart_releases_linux/validation.py

- Add support for nested subquestions validations
- Add hostPath $ref validations
- Add lockedHostPath $ref validations
- Add hostPathAttachments $ref validations
Original PR: https://github.com/truenas/middleware/pull/8203
Jira URL: https://jira.ixsystems.com/browse/NAS-114689

NAS-114689 / 22.02 / Add a $ref for hostPath schema validation (by Qubad786)

---

src/middlewared/middlewared/alert/source/failover.py

None of this was written for SCALE HA so many of the checks were invalid so I've fixed all relevant issues.

NAS-114873 / 22.02.1 / fix failover.py alert on SCALE HA

---

src/middlewared/middlewared/plugins/device.py

This commit fixes an issue introduced recently which broke serial/console access.

NAS-114859 / 13.0 / Fix broken serial/console access in CORE

---

src/freenas/usr/local/lib/middlewared_truenas/alert/source/enclosure_status.py
src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py

Enclosure plugin was rewritten in 13 to scale on systems with 100's (even 1k+ hdds) but this alert was missed.

NAS-114895 / 13.0 / Fix enclosure alert 13

---

src/middlewared/middlewared/plugins/nfs_/debug.py

This is a private API for now with the idea that we can potentially
expose a limited / more basic version through public APIs
(perhaps nfs.update).

NAS-114900 / 22.02.1 / Allow getting / setting NFS-related debug levels at runtime

---

src/freenas/usr/local/lib/collectd_pyplugins/nfsstat.py

This PR also refactors the collectd plugin somewhat to
hopefully make it more readable.

NAS-114919 / 22.02.1 / Extend nfsd stats to include threadpool info

---

src/freenas/usr/local/lib/collectd_pyplugins/nfsstat.py

/proc/net/rpc/nfsd may not always exist (if nfs-server disabled). Protect against
errors when trying to read the file.

NAS-115022 / 22.12 / Fix traceback in nfsstat collectd plugin

---

src/freenas/usr/local/lib/collectd_pyplugins/nfsstat.py

/proc/net/rpc/nfsd may not always exist (if nfs-server disabled). Protect against
errors when trying to read the file.
Original PR: https://github.com/truenas/middleware/pull/8349
Jira URL: https://jira.ixsystems.com/browse/NAS-115022

NAS-115022 / 22.02 / Fix traceback in nfsstat collectd plugin (by anodos325)

---

src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py

Stale `ctdbd` daemon config is being left after the truenas cluster config is removed. This causes a problem when a new cluster is created and the private IPs in the new cluster differ from the old private IPs.
2 changes.
1. use the `clusterjob.submit` framework which actually waits on all API requests in the cluster to complete
2. add a `__remove_config` method that removes the `ctdbd` daemon config

NAS-115039 / 22.12 / remove ctdbd config on ctdb shared volume deletion

---

src/middlewared/middlewared/alert/source/proactive_support.py

git cherry-pick -x c06e835b89b132c96bbde7eab3af441579641fe7
Original PR: https://github.com/truenas/middleware/pull/8366
Jira URL: https://jira.ixsystems.com/browse/NAS-114371

NAS-114371 / 13.0 / Properly named Proactive Support alert (by themylogin)

---

src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py

Stale `ctdbd` daemon config is being left after the truenas cluster config is removed. This causes a problem when a new cluster is created and the private IPs in the new cluster differ from the old private IPs.
2 changes.
1. use the `clusterjob.submit` framework which actually waits on all API requests in the cluster to complete
2. add a `__remove_config` method that removes the `ctdbd` daemon config
Original PR: https://github.com/truenas/middleware/pull/8371
Jira URL: https://jira.ixsystems.com/browse/NAS-115039

NAS-115039 / 22.02 / remove ctdbd config on ctdb shared volume deletion (by yocalebo)

---

src/middlewared/middlewared/plugins/account.py

Original code was performing one datastore query per user, and
two datastore queries per group for each user or group in
user.query and group.query respectively.
This contains an optimization whereby we query the related
datastores only once per query request and convert relevant
data to a dictionary that allows O(1) retrieval for information
as we iterate through query results. The practical impact
on server with 500 users is that user.query speed dropped
from 7 seconds to 0.6 seconds. This has broad-ranging impacts
due to datastore and etc file design where user.query may
be called a significant number of times when adding, modifying,
or deleting users. In this case, I observed a 10x improvement
in speed.

NAS-115071 / 13.0 / Improve user.query and group.query performance (by anodos325)

---

src/middlewared/middlewared/plugins/cluster_linux/utils.py

Use the `dnsclient.forward_lookup` plugin in `cluster.utils.resolve_hostnames` which allows me to get rid of some duplicate code. Should be no functional change.

NAS-113226 / 22.12 / use dnsclient.forward_lookup in cluster.utils

---

src/middlewared/middlewared/etc_files/local/ssh/config.py
src/middlewared/middlewared/etc_files/local/ssh/sshd_config.mako
src/middlewared/middlewared/etc_files/local/users.oath.mako
src/middlewared/middlewared/plugins/etc.py

This also adds more rigid control over permissions of config and
key files. We will also begin deleting unexpected contents from
/etc/ssh if they are detected.

NAS-115119 / 22.12 / Convert SSH etc group to use common render_ctx

---

src/middlewared/middlewared/plugins/failover_/event.py
src/middlewared/middlewared/plugins/zfs.py

This PR adds changes to improve schema for the import pool internal api as it's confusing right now where options are actually properties for the pool and we are also passing import time flags in the same dict and then removing them from it.

NAS-113616 / 22.12 / Improve zfs.pool.import_pool api

---

src/middlewared/middlewared/etc_files/local/ssh/config.py

This is a more correct way of using dir_fd with the python
builtin open() and also ensures that new file created with
correct perms.

NAS-115196 / 22.12 / Use opener in ssh etc file generation

---

src/middlewared/middlewared/etc_files/local/ssh/config.py

This is a more correct way of using dir_fd with the python
builtin open() and also ensures that new file created with
correct perms.
Original PR: https://github.com/truenas/middleware/pull/8463
Jira URL: https://jira.ixsystems.com/browse/NAS-115196

NAS-115196 / 22.02.1 / Use opener in ssh etc file generation (by anodos325)

---

src/middlewared/middlewared/plugins/gluster_linux/peer.py
src/middlewared/middlewared/plugins/gluster_linux/volume.py

This PR adds changes to fix middleware not starting and properly utilize schema implementation to define return types.
```
File "/usr/bin/middlewared", line 12, in <module>
sys.exit(main())
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1810, in main
Middleware(
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1637, in run
self.loop.run_until_complete(self.__initialize())
File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
return future.result()
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1692, in __initialize
await restful_api.register_resources()
File "/usr/lib/python3/dist-packages/middlewared/restful.py", line 84, in register_resources
for methodname, method in …
```

NAS-115207 / 22.12 / Fix middleware not starting

---

src/middlewared/middlewared/plugins/gluster_linux/peer.py
src/middlewared/middlewared/plugins/gluster_linux/volume.py

This PR adds changes to fix middleware not starting and properly utilize schema implementation to define return types.
```
File "/usr/bin/middlewared", line 12, in <module>
sys.exit(main())
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1810, in main
Middleware(
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1637, in run
self.loop.run_until_complete(self.__initialize())
File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
return future.result()
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1692, in __initialize
await restful_api.register_resources()
File "/usr/lib/python3/dist-packages/middlewared/restful.py", line 84, in register_resources
for methodname, method in …
```

NAS-115207 / 22.02.1 / Fix middleware not starting (by sonicaj)

---

src/middlewared/middlewared/etc_files/krb5.keytab.py

Ensure that temporary keytab files are generated with
0o600 permissions and that directory where they are
created has 0o700 permissions. Generally clean up
this script as well.
Original PR: https://github.com/truenas/middleware/pull/8476
Jira URL: https://jira.ixsystems.com/browse/NAS-115203

NAS-115203 / 13.0 / Improve permissions handling in temporary keytab files (by anodos325)

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py

This is already being done on SCALE HA so I'm doing the equivalent on 13. This prevents failover from not working when trying to import a zpool via name and 2 or more disks have the same zpool information stamped on the labels but they're actually different zpools.
This can be reproduced easily by creating zpool named "zz" and use 3 disks. Export the zpool and recreate the zpool using 2 of those 3 disks naming it the same. Try to failover and you'll see zpool give an error to import by numeric ID instead because of duplicate zpoolnames.

NAS-115234 / 13.0 / import zpools by guid on failover event

---

src/freenas/usr/local/libexec/freenas-debug/system/system.sh
src/middlewared/middlewared/job.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/service.py

This PR adds changes to normalize jobs results to prevent leaking sensitive information like dataset keys in the debug.

NAS-115216 / 22.12 / Allow normalizing jobs results

---

src/freenas/usr/local/libexec/freenas-debug/system/system.sh
src/middlewared/middlewared/job.py
src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/service.py

This PR adds changes to normalize jobs results to prevent leaking sensitive information like dataset keys in the debug.
Original PR: https://github.com/truenas/middleware/pull/8497
Jira URL: https://jira.ixsystems.com/browse/NAS-115216

NAS-115216 / 22.02.1 / Allow normalizing jobs results (by sonicaj)

---

cluster-tests/run-cluster-tests.py

Should allow jenkins to read the xml and publish the results in "pretty" format in the webUI.

NAS-115251 / 22.12 / add junit_family=xunit2

---

cluster-tests/run-cluster-tests.py

Should allow jenkins to read the xml and publish the results in "pretty" format in the webUI.
Original PR: https://github.com/truenas/middleware/pull/8526
Jira URL: https://jira.ixsystems.com/browse/NAS-115251

NAS-115251 / 22.02.1 / add junit_family=xunit2 (by yocalebo)

---

src/middlewared/middlewared/etc_files/generate_ssl_certs.py
tests/api2/test_certs.py

Remove certificate files from the filesystem once they're removed from database.

NAS-114213 / 22.12 / Delete certificates that no longer exist

---

src/middlewared/middlewared/alembic/versions/22.02/2022-03-12_12-50_set_default_kbdmap.py
src/middlewared/middlewared/etc_files/vconsole.conf.mako
src/middlewared/middlewared/plugins/system_general/update.py

git cherry-pick -x af5e703cbc53b35ad422fdc41153fa0f142d9307
Original PR: https://github.com/truenas/middleware/pull/8532
Jira URL: https://jira.ixsystems.com/browse/NAS-115246

NAS-115246 / 22.12 / Set default kbdmap (by themylogin)

---

.github/workflows/lint.yml

…g to PEP8
Original PR: https://github.com/truenas/middleware/pull/8543
Jira URL: https://jira.ixsystems.com/browse/NAS-115273

NAS-115273 / 22.02.1 / Employ `flake8-import-order` to ensure correct import orders accordin… (by themylogin)

---

.github/workflows/lint.yml

…g to PEP8
Original PR: https://github.com/truenas/middleware/pull/8543
Jira URL: https://jira.ixsystems.com/browse/NAS-115273

NAS-115273 / 13.0 / Employ `flake8-import-order` to ensure correct import orders accordin… (by themylogin)

---

tests/api2/test_003_network.py

Many fixes, the primary one being we actually test the results on an HA system instead of only on a non-HA system.
Original PR: https://github.com/truenas/middleware/pull/8563
Jira URL: https://jira.ixsystems.com/browse/NAS-115310

NAS-115310 / 22.02.1 / simplify and fix test_003_network.py (by yocalebo)

---

tests/api2/test_011_user.py

DOCS-3393 / 22.02 / Renamed the payload in user test 31 to get right payload

---

src/middlewared/middlewared/test/integration/assets/pool.py
tests/api2/test_007_pool_dataset_encryption.py
tests/api2/test_009_pool.py

…ool-related operations
Original PR: https://github.com/truenas/middleware/pull/8608
Jira URL: https://jira.ixsystems.com/browse/NAS-115405

NAS-115405 / 22.02.1 / `from middlewared.test.integration.assets.pool import pool` to test p… (by themylogin)

---

tests/api2/test_300_nfs.py

When maproot_user and maproot_group are set to 'root', then we
also add configuration option 'no_root_squash' to the exports
line. This test ensures that this parameter is being properly
added and that it does not get added to other shares.

NAS-115448 / 22.12 / Expand maproot tests

---

src/middlewared/middlewared/etc_files/exports.mako

Ensure that root_squash is properly evaluated on a per-share basis when generating exports file.

Fix root squash parameter 22.02

---

tests/api2/test_300_nfs.py

When maproot_user and maproot_group are set to 'root', then we
also add configuration option 'no_root_squash' to the exports
line. This test ensures that this parameter is being properly
added and that it does not get added to other shares.
Original PR: https://github.com/truenas/middleware/pull/8631
Jira URL: https://jira.ixsystems.com/browse/NAS-115448

NAS-115448 / 22.02.1 / Expand maproot tests (by anodos325)

---

src/middlewared/middlewared/plugins/disk_/disk_info_base.py

What an incredibly painful way to break the build....
Jira: https://jira.ixsystems.com/browse/NAS-115458

NAS-115458 / 22.02.1 / fix the build

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py

After many hours testing, I've finally got this working. ZFS has a very subtle, non-intuitive behavior with respect to how it overwrites or appends to an existing zpool cachefile.
Original PR: https://github.com/truenas/middleware/pull/8612
Jira URL: https://jira.ixsystems.com/browse/NAS-113655

NAS-113655 / 13.0 / Properly use zpool cachefile on HA (by yocalebo)

---

src/middlewared/middlewared/apidocs/templates/index.html

This PR fixes api docs access on the port forward.

NAS-115486 / 22.12 / Fix api docs not respecting port properly when redirecting

---

src/middlewared/middlewared/apidocs/templates/index.html

This PR fixes api docs access on the port forward.
Original PR: https://github.com/truenas/middleware/pull/8646
Jira URL: https://jira.ixsystems.com/browse/NAS-115486

NAS-115486 / 22.02.1 / Fix api docs not respecting port properly when redirecting (by Qubad786)

---

src/middlewared/middlewared/plugins/filesystem.py

FILESYSTEM -> FILE for type. Shift stat / lstat calls earlier in
function so that we can short-circuit in case of filter to only
show directories or files. This is optimization for improving
webui performance for various dropdowns in case user has written
huge numbers of files to a directory.

NAS-115498 / 22.12 / Fix typo in filesystem.listdir and add optimization

---

src/middlewared/middlewared/plugins/network.py

webUI needs this info to be returned

NAS-115521 / 22.12 / return stp info in interface.query

---

src/middlewared/middlewared/plugins/usage.py

It was requested to add docker images being used by `ix-chart` application and other applications in our usage statistics.

NAS-115479 / 22.12 / Retrieve images being consumed by ix-chart

---

src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/system.py
src/middlewared/middlewared/plugins/system/debug.py
src/middlewared/middlewared/plugins/test/rest.py
src/middlewared/middlewared/restful.py
src/middlewared/middlewared/service.py
src/middlewared/middlewared/test/integration/utils/client.py
tests/api2/test_rest_api_download.py
tests/api2/test_rest_api_upload.py

git cherry-pick -x 1022cbfc2d025ce3b9f196770ac178a252b9c88a
git cherry-pick -x c046cae2e2c6f273746b69456d0f1ab875e0e549
git cherry-pick -x 14be8742e5dd236dd94435aa1e054c0dd076f5ae
* Allow specifying `?download=0` to avoid providing a pipe to the method (useful for `pool.dataset.export_keys`)
* Allow uploading files via REST resources
* Document how to work with such resources
* Add integration tests
Original PR: https://github.com/truenas/middleware/pull/8577
Jira URL: https://jira.ixsystems.com/browse/NAS-115279

NAS-115279 / 22.12 / Normalize REST resources for jobs that use pipes: (by themylogin)

---

src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh

I have ask for this too often before telling another AMD user that we can't do anything
with the fact that their CPU provides three temperatures with obscure labels, none of
which is the actual temperature of any point of their CPU.

NAS-115561 / 22.12 / Provide `sensors -j` output in debug

---

src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh

I have ask for this too often before telling another AMD user that we can't do anything
with the fact that their CPU provides three temperatures with obscure labels, none of
which is the actual temperature of any point of their CPU.
Original PR: https://github.com/truenas/middleware/pull/8679
Jira URL: https://jira.ixsystems.com/browse/NAS-115561

NAS-115561 / 22.02.1 / Provide `sensors -j` output in debug (by themylogin)

---

src/middlewared/middlewared/plugins/activedirectory.py

This fixes a couple of issues that crept in while backporting
middleware fixes to work with Samba 4.15.

NAS-115580 / 13.0 / Fix AD join failure messages

---

src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/plugins/pool_/attach_disk.py
src/middlewared/middlewared/plugins/pool_/format_disks.py

8841679f84194e95d594db3a5ffecbb2c883167d removed GELI code and this finishes up by removing the remainder of it

NAS-115587 / 22.12 / Remove geli logic on scale

---

src/middlewared/middlewared/job.py

git cherry-pick -x cf8ddef2bc1defaae00d710b999e16c63a3d0f86
git cherry-pick -x 3db4c54efad10db39a3deb8d512f7481616ccb9d
Original PR: https://github.com/truenas/middleware/pull/8690
Jira URL: https://jira.ixsystems.com/browse/NAS-115574
Original PR: https://github.com/truenas/middleware/pull/8691
Jira URL: https://jira.ixsystems.com/browse/NAS-115574

NAS-115574 / 13.0 / Fix starting jobs with lock from a thread without an event loop on python < 3.10 (by themylogin) (by bugclerk)

---

src/middlewared/middlewared/client/client.py
src/middlewared/middlewared/job.py
tests/api2/test_client_job.py
tests/api2/test_job_events.py

NAS-115719 / 22.12 / Fix job state reporting

---

src/middlewared/middlewared/client/client.py
src/middlewared/middlewared/job.py
tests/api2/test_client_job.py
tests/api2/test_job_events.py

time 3:00
Original PR: https://github.com/truenas/middleware/pull/8753
Jira URL: https://jira.ixsystems.com/browse/NAS-115719

NAS-115719 / 22.02.1 / Fix job state reporting (by themylogin)

---

src/middlewared/middlewared/plugins/zfs.py

git cherry-pick -x f6f84971d7f078c7bc2410299587384cbfb8e33b
Original PR: https://github.com/truenas/middleware/pull/8751
Jira URL: https://jira.ixsystems.com/browse/NAS-113532

NAS-113532 / 22.02.1 / Specify `search_paths` for all `zfs.find_import` calls (by themylogin)

---

src/middlewared/middlewared/plugins/iscsi.py
src/middlewared/middlewared/plugins/zfs.py
src/middlewared/middlewared/test/integration/assets/pool.py
tests/api2/test_007_pool.py
tests/api2/test_pool_replace_disk.py
tests/api2/test_snapshot_query.py

git cherry-pick -x 0fb79e18aeea0c46727f0e135de0b2a405280d01
git cherry-pick -x acda05e34ace1f6221e8b20e9838380842646636
Original PR: https://github.com/truenas/middleware/pull/8743
Jira URL: https://jira.ixsystems.com/browse/NAS-115628

NAS-115628 / 22.02.1 / `iscsi.extent.disk_choices`: only query snapshots for zvols (by themylogin)

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py

`hook_sync_geli` is unnecessary because `pool.post_create_or_update` calls `hook_setup_ha` and `hook_setup_ha`, eventually, does the exact same thing that `hook_sync_geli` does.

NAS-115826 / 13.0 / remove hook_sync_geli

---

src/middlewared/middlewared/plugins/pool.py

We need to base the maximum dataset recordsize off of `zfs_max_recordsize` module option. Furthermore, ZFS supports up to 16MB recordsize. All you have to do is `echo '16777216' > /sys/module/zfs/parameters/zfs_max_recordsize`.
This changes it so that we always determine the maximum size based off of that module option.
Original PR: https://github.com/truenas/middleware/pull/8739
Jira URL: https://jira.ixsystems.com/browse/NAS-115639
Original PR: https://github.com/truenas/middleware/pull/8749
Jira URL: https://jira.ixsystems.com/browse/NAS-115639

NAS-115639 / 13.0 / properly display zfs dataset recordsize choices (by yocalebo) (by bugclerk)

---

src/middlewared/middlewared/main.py

git cherry-pick -x ed84a7cdd55f99f8fa3e2f25b2a46acaaa1336d3
git cherry-pick -x 3ed09369b1d504577f6cf92e2df1ca2ac2618421
Original PR: https://github.com/truenas/middleware/pull/8807
Jira URL: https://jira.ixsystems.com/browse/NAS-115865

NAS-115865 / 13.0 / `middleware.block_hooks` (by themylogin)

---

src/middlewared/middlewared/plugins/network.py

…never null
Original PR: https://github.com/truenas/middleware/pull/8849
Jira URL: https://jira.ixsystems.com/browse/NAS-115541

NAS-115541 / 22.02.2 / Correctly handle network interface `description` and make sure it is … (by themylogin)

---

src/middlewared/middlewared/plugins/geom.py

Memory usage in python is typically a non-issue....until it is 😄 On a large system with ~1240 hard drives, the difference between using the standard `dict()` compared to `defaultdict()` is measurable. There is no functional change which is just icing on the cake.

NAS-115931 / 13.0 / use defaultdict in geom.cache plugin

---

src/middlewared/middlewared/plugins/mdns.py
src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/plugins/service_/services/cifs.py
src/middlewared/middlewared/plugins/smb.py

Wait until system ready before starting nmbd, wsdd, avahi.

NAS-114952 / 13.0 / Properly initialize service announcements on boot (#7429)

---

src/middlewared/middlewared/plugins/vm/vm_devices.py

This commit fixes outdated validation as it is no longer valid in scale after testing and confirming with Ryan.

NAS-115833 / 22.12 / VM Disk device validation fix

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/map.py

The MINI 3.0 XL+ is the _only_ enclosure that maps a disk from /dev/ses1 the first iteration and then maps the other drives from /dev/ses0 and then ends on /dev/ses1.
Because we're dealing with loops and dictionaries, on the first iteration of the for loop we are `pop`'ing a dictionary key and then on the next iteration `pop`'ing from another dictionary which is overwriting the variable from the first iteration of the loop. Investigating this a little closer has shown that we're iterating over the mapping code and trying to shift a bunch of variables around on the outside of the for loop and on the inside etc etc. Instead of doing that, iterate over the enclosures being passed to us and then iterate the mapping code and access the original enclosure dictionary via the mapping lots …

NAS-116001 / 13.0 / fix enclosure on MINI 3.0 XL+

---

tests/api2/test_011_user.py
tests/api2/test_032_ad_kerberos.py
tests/api2/test_045_afp.py
tests/api2/test_310_plugin.py
tests/api2/test_347_posix_mode.py
tests/api2/test_420_smb.py
tests/api2/test_425_smb_protocol.py
tests/api2/test_435_smb_registry.py

Test results for this branch: https://builds.ixsystems.com/job/Test%20development/job/TrueNAS%2013.0%20nightlies%20API%20Tests%20from%20branch/30/

DOCS-3675 / 13.0 / improved test dependencies related to pool failure.

---

cluster-tests/tests/cloudsync/test_cloudsync.py
src/middlewared/middlewared/async_validators.py
src/middlewared/middlewared/plugins/cloud_sync.py
src/middlewared/middlewared/plugins/filesystem.py
src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
src/middlewared/middlewared/plugins/smb.py
src/middlewared/middlewared/service.py
src/middlewared/middlewared/test/integration/assets/cloud_sync.py
src/middlewared/middlewared/test/integration/utils/client.py
src/middlewared/middlewared/test/integration/utils/pool.py
tests/api2/test_cloud_sync.py

git cherry-pick -x 14ba404fa605744e4457a1c0ef964850985ca919
Original PR: https://github.com/truenas/middleware/pull/8509
Jira URL: https://jira.ixsystems.com/browse/NAS-115094

NAS-115094 / 22.12 / Allow `CLUSTER:` locations to be used for cloud sync tasks (by themylogin)

---

src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py

This has never worked the way it was intended to. TC must call `ctdb.shared.volume.teardown` on all peers in the cluster and wait for completion and then call `ctdb.shared.volume.delete` on 1 of the peers to finalize it.

NAS-115980 / 22.12 / add ctdb.shared.volume.teardown method

---

src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py

This has never worked the way it was intended to. TC must call `ctdb.shared.volume.teardown` on all peers in the cluster and wait for completion and then call `ctdb.shared.volume.delete` on 1 of the peers to finalize it.
Original PR: https://github.com/truenas/middleware/pull/8864
Jira URL: https://jira.ixsystems.com/browse/NAS-115980

NAS-115980 / 22.02.2 / add ctdb.shared.volume.teardown method (by yocalebo)

---

src/middlewared/middlewared/plugins/pool.py

Fixes for bugs discovered when working on https://github.com/truenas/middleware/pull/8875. No 22.12 backport is needed.

NAS-116033 / 22.02.2 / Fix unlocking readonly datasets

---

src/middlewared/middlewared/plugins/enterprise/m_series_nvdimm_freebsd.py

Clean this file up and remove an unnecessary `subprocess` call. This PR is dependent on: https://github.com/truenas/middleware/pull/8878

NAS-116048 / 13.0 / clean up setup_m_series_nvdimm method

---

src/middlewared/middlewared/main.py
src/middlewared/middlewared/utils/io_thread_pool_executor.py

This is, essentially, a backport of https://github.com/truenas/middleware/pull/8170 where it was found the IoThreadPool wasn't working on initial middlewared startup. The issue was fixed in SCALE but never backported to 13.
This is a modified cherry-pick to keep the changes as minimal as possible for 13.
Tested on M60

NAS-116066 / 13.0 / fix IoThreadPoolExecutor

---

src/middlewared/middlewared/plugins/network.py

`interface.internal_interfaces` exists in SCALE but not on CORE and we're calling `interface.internal_interfaces` when configuring dns servers. Add a private method for this so we match SCALE functionality.

NAS-116161 / 13.0 / add interface.internal_interfaces method

---

tests/api2/test_425_smb_protocol.py
tests/protocols.py

We have had regressions here on a few occassions. Let's
add some CI tests so that it doesn't get missed again.

NAS-115976 / 22.12 / Add tests for renames over SMB protocol

---

src/middlewared/middlewared/plugins/smart.py
src/middlewared/middlewared/pytest/unit/plugins/test_smart.py

git cherry-pick -x 79a3f31401bddfdf0b415bb2a58990e0ff349e1d
git cherry-pick -x a2393a11a0d92643645a491c17f3e2fa6678d33b
Original PR: https://github.com/truenas/middleware/pull/8748
Jira URL: https://jira.ixsystems.com/browse/NAS-114960

NAS-114960 / 13.0 / Report true S.M.A.R.T. self-test progress (by themylogin)

---

src/middlewared/middlewared/plugins/network_/global.py

This fixes the scenario when the end-user is on the B node and it's the master controller and the B node's hostname is changed. Without these changes we were only changing the A and B node's hostname if the A node was the master while the B was standby.

NAS-116135 / 22.12 / fix changing hostname on standby node on HA

---

src/middlewared/middlewared/plugins/network_/global.py

This fixes the scenario when the end-user is on the B node and it's the master controller and the B node's hostname is changed. Without these changes we were only changing the A and B node's hostname if the A node was the master while the B was standby.
Original PR: https://github.com/truenas/middleware/pull/8912
Jira URL: https://jira.ixsystems.com/browse/NAS-116135

NAS-116135 / 22.02.2 / fix changing hostname on standby node on HA (by yocalebo)

---

tests/api2/test_425_smb_protocol.py
tests/protocols.py

We have had regressions here on a few occassions. Let's
add some CI tests so that it doesn't get missed again.

NAS-115976 / 13.0 / Add tests for renames over SMB protocol (by anodos325)

---

src/middlewared/middlewared/plugins/failover.py

`interface.query` returns all interfaces detected on the system not just the ones that have been configured by end-user. This fixes the check so that we only check interfaces that have been configured.
Original PR: https://github.com/truenas/middleware/pull/8973
Jira URL: https://jira.ixsystems.com/browse/NAS-116264

NAS-116264 / 22.02.2 / fix NO_VIP check on SCALE HA (by yocalebo)

---

src/middlewared/middlewared/plugins/support.py

git cherry-pick -x b0b5af98b868b3b3ab84a012dbf0c5f1fc49298a
Original PR: https://github.com/truenas/middleware/pull/7464
Jira URL: https://jira.ixsystems.com/browse/NAS-111680

NAS-111680 / 13.0 / Use OAuth access token for support-proxy requests (by themylogin)

---

src/middlewared/middlewared/job.py

This makes Task Manager filled with alert.process_alerts/alert.send_alerts garbage

NAS-116349 / 22.02.2 / Do not send events for transient jobs

---

src/middlewared/middlewared/plugins/vm/vms.py

We had deprecated allowing modifying vm devices in vm create/update methods, this PR brings the promised change and removes the functionality now.

NAS-116213 / 22.12 / Do not allow modifying devices in vm create/update

---

src/middlewared/middlewared/job.py

This makes Task Manager filled with alert.process_alerts/alert.send_alerts garbage
Original PR: https://github.com/truenas/middleware/pull/9008
Jira URL: https://jira.ixsystems.com/browse/NAS-116349

NAS-116349 / 22.12 / Do not send events for transient jobs (by themylogin)

---

src/middlewared/middlewared/plugins/enclosure_/map.py
src/middlewared/middlewared/plugins/enclosure_/r50_nvme.py

This adds r50b rear drive bay mapping. Whenever I can get ahold of a r50 device, it should be as simple as adding to the `self.R50` dict appropriately.

NAS-116303 / 22.12 / add r50b rear nvme drive bay mapping

---

src/middlewared/middlewared/plugins/activedirectory_/krb5.py

Upstream tooling for this is better now. add_update_ads updates
local keytab and also updates compuer object in AD.

NAS-116486 / 22.12 / Simplify process of adding NFS SPNs

---

src/middlewared/middlewared/plugins/zfs.py

NAS-116257 / 13.0 / Fix counting all snapshots on the system

---

src/middlewared/middlewared/plugins/smb.py

Adds clarification for TC team which of presets should be available
for cluster shares.

NAS-116545 / 22.12 / Add key to SMB share presets to indicate cluster-safety

---

src/middlewared/middlewared/plugins/activedirectory.py

Fail fast on netbios name validation if AD is enabled. The
reason for this is that these sorts of changes require remote
changes on the domain controller to work properly and can be
profoundly impactful on active production environments.
Validation was already happening through SMB plugin, but
shifting here is inexpensive and ensures that correct
schema name is included in the validation error message.
Original PR: https://github.com/truenas/middleware/pull/9115
Jira URL: https://jira.ixsystems.com/browse/NAS-115602

NAS-115602 / 22.02.2 / Prevent NetBIOS name updates while AD service is enabled (by anodos325)

---

src/middlewared/middlewared/plugins/pool.py

git cherry-pick -x 5ec467906f80d90702d1e035b54e961c952d6f49
…recordsize`
Original PR: https://github.com/truenas/middleware/pull/9116
Jira URL: https://jira.ixsystems.com/browse/NAS-116220

NAS-116220 / 22.12 / Fir crash on validation of inherited `special_small_block_size` and `… (by themylogin)

---

src/middlewared/middlewared/plugins/pool.py

git cherry-pick -x 5ec467906f80d90702d1e035b54e961c952d6f49
…recordsize`
Original PR: https://github.com/truenas/middleware/pull/9116
Jira URL: https://jira.ixsystems.com/browse/NAS-116220

NAS-116220 / 22.02.2 / Fir crash on validation of inherited `special_small_block_size` and `… (by themylogin)

---

src/middlewared/middlewared/plugins/filesystem.py
src/middlewared/middlewared/plugins/filesystem_/dosmode.py
src/middlewared/middlewared/utils/path.py
tests/api2/test_190_filesystem.py

This is primarily to help with CI for SMB server, but may
be generally useful when we in future want to have a
proper file browser.
Original PR: https://github.com/truenas/middleware/pull/9132
Jira URL: https://jira.ixsystems.com/browse/NAS-116575

NAS-116575 / 22.02.2 / Expose ZFS dosmodes in filesystem plugin (by anodos325)

---

src/middlewared/middlewared/plugins/device_/device_info.py

When SCALE is installed inside a bhyve VM, the serial for the disk is stored in `ID_SERIAL_SHORT` like it is for nvme drives. Make the necessary adjustments to get the serial appropriately.
Also I've noticed a 2nd issue, the `get_partitions` kwarg was not set in the `device.get_disks` method properly so that was a NO-OP (this is not a problem on stable) and prevents disk.sync_all from working properly.

NAS-116630 / 22.12 / fix BHYVE disk serial detection on SCALE

---

src/middlewared/middlewared/plugins/enclosure_/map.py
src/middlewared/middlewared/plugins/enclosure_/r50_nvme.py

This adds R50 rear nvme drive bay mapping to SCALE.
Also, the way we map the R50B is the equivalent, so I simplified this code quite a bit to remove a bunch of duplicate logic.

NAS-116304 / 22.02.2 / add r50 rear nvme drive mapping and simplify code

---

src/middlewared/middlewared/plugins/enclosure_/map.py
src/middlewared/middlewared/plugins/enclosure_/r50_nvme.py

This adds R50 rear nvme drive bay mapping to SCALE.
Also, the way we map the R50B is the equivalent, so I simplified this code quite a bit to remove a bunch of duplicate logic.
Original PR: https://github.com/truenas/middleware/pull/9166
Jira URL: https://jira.ixsystems.com/browse/NAS-116304

NAS-116304 / 22.12 / add r50 rear nvme drive mapping and simplify code (by yocalebo)

---

src/middlewared/middlewared/plugins/activedirectory.py

Add some custom error messages for validation errors for common
issues that may occur when we're trying to check a user's password.
Original PR: https://github.com/truenas/middleware/pull/9174
Jira URL: https://jira.ixsystems.com/browse/NAS-116651

NAS-116651 / 22.02.2 / Improve error messages for invalid AD accounts (by anodos325)

---

src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py

We have to make a call to `interface.sync` in the teardown method since ctdb service removes the IP addresses off the interface. This is a design issue and is a work-around for stable. A proper fix will come in next major release.

NAS-116646 / 22.02.2 / ctdb teardown method to resync interfaces

---

src/middlewared/middlewared/plugins/filesystem_/acl_linux.py

uid or gid of -1 means to leave existing user / group in place.
We already have retrieved the current ACL (which includes
ownership info) prior to performing the ACL execute check, and
so get the current user and group from there.
Original PR: https://github.com/truenas/middleware/pull/9182
Jira URL: https://jira.ixsystems.com/browse/NAS-116658

NAS-116658 / 22.02.2 / resolve uid -1 and gid -1 prior to perm_check (by anodos325)

---

src/middlewared/middlewared/plugins/activedirectory.py

Because of systemd linkage between winbindd and smbd, the SMB
service was staying stopped after AD service stop. Break up
the stop and start of the SMB service so that underlying processes
are toggled in correct order. Remove extraneous cache flush
(this is now done when we stop the dscache service).

NAS-116660 / 22.12 / Ensure that SMB service stays running after AD stop

---

src/middlewared/middlewared/plugins/activedirectory.py

Because of systemd linkage between winbindd and smbd, the SMB
service was staying stopped after AD service stop. Break up
the stop and start of the SMB service so that underlying processes
are toggled in correct order. Remove extraneous cache flush
(this is now done when we stop the dscache service).
Original PR: https://github.com/truenas/middleware/pull/9187
Jira URL: https://jira.ixsystems.com/browse/NAS-116660

NAS-116660 / 22.02.2 / Ensure that SMB service stays running after AD stop (by anodos325)

---

src/middlewared/middlewared/plugins/cluster_linux/ctdb_general.py

ctdb.general.healthy calls must be as fast as possible because they
are used by clustered plugins in query / config methods. Replace
much of logic here with stat(2) of ctdb_shared_volume mountpoint.
If gluster volume is unhealthy this will fail. If it's unmounted
then inode will be something other than 1.

NAS-116671 / 22.12 / optimize ctdb.general.healthy

---

src/middlewared/middlewared/plugins/cluster_linux/ctdb_general.py

ctdb.general.healthy calls must be as fast as possible because they
are used by clustered plugins in query / config methods. Replace
much of logic here with stat(2) of ctdb_shared_volume mountpoint.
If gluster volume is unhealthy this will fail. If it's unmounted
then inode will be something other than 1.
Original PR: https://github.com/truenas/middleware/pull/9193
Jira URL: https://jira.ixsystems.com/browse/NAS-116671

NAS-116671 / 22.02.2 / optimize ctdb.general.healthy (by anodos325)

---

src/middlewared/middlewared/plugins/device_/device_info.py

`Micron_5210_MTFDDAK960QDE_195027AFFE1B` (`sdi`) on `r10-105.dc1.ixsystems.net` had its serial
in `ID_SERIAL_SHORT` despite not being an NVMe device and not running on bhyve. It seems cheap
enough to just probe both properties.

NAS-116726 / 22.12 / Fix disks serial numbers

---

src/middlewared/middlewared/plugins/device_/device_info.py
src/middlewared/middlewared/plugins/disk_/disk_info.py

4k disks on r50b-2.dc1 were reporting 8x larger size.

NAS-116723 / 22.12 / Disk/partition sizes are always expressed in blocks of 512 bytes

---

src/middlewared/middlewared/plugins/smb_/groupmap.py
tests/api2/test_427_smb_acl.py

Parser was broken during refactoring and not caught during
testing.

NAS-115994 / 22.12 / Fix idmap tdb gid parsing

---

src/middlewared/middlewared/plugins/smb_/groupmap.py
tests/api2/test_427_smb_acl.py

Parser was broken during refactoring and not caught during
testing.
Original PR: https://github.com/truenas/middleware/pull/9246
Jira URL: https://jira.ixsystems.com/browse/NAS-115994

NAS-115994 / 22.02.3 / Fix idmap tdb gid parsing (by anodos325)

---

src/middlewared/middlewared/common/attachment/__init__.py
src/middlewared/middlewared/plugins/s3_/attachments.py

self.logger.debug -> self.middleware.logger.debug
Original PR: https://github.com/truenas/middleware/pull/9261
Jira URL: https://jira.ixsystems.com/browse/NAS-116834

NAS-116834 / 22.02.3 / Fix regression in s3 attachment (by anodos325)

---

src/middlewared/middlewared/plugins/filesystem.py
src/middlewared/middlewared/plugins/filesystem_/stat_x.py

Expose ability to use dirfd and at_flags in statx calls. Include
inode birth time in stat output.

NAS-116816 / 22.12 / use statx to retrieve btime for files in filesystem.stat output

---

src/middlewared/middlewared/plugins/filesystem.py
src/middlewared/middlewared/plugins/filesystem_/stat_x.py

Expose ability to use dirfd and at_flags in statx calls. Include
inode birth time in stat output.
Original PR: https://github.com/truenas/middleware/pull/9257
Jira URL: https://jira.ixsystems.com/browse/NAS-116816

NAS-116816 / 22.02.3 / use statx to retrieve btime for files in filesystem.stat output (by anodos325)

---

src/middlewared/middlewared/plugins/interface/dhclient.py

This is potentially doing 2 to 3 `with open` calls which doesn't bode well

NAS-116881 / 22.12 / stop doing file I/O on main event loop

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py

This was raising a `KeyError` because `enc.status()['elements']['Array Device Slot']` doesn't have a key of `Array Device Slot` since the data returned from that function is the raw, unformatted data. Just need to use the formatted data from `enclosure.query` which we're storing in `info` variable.

NAS-116883 / 13.0 / fix drive identify on x and m series

---

src/middlewared/middlewared/plugins/support.py

Reverts truenas/middleware#8985

Revert "NAS-111680 / 13.0 / Use OAuth access token for support-proxy requests (by themylogin)"

---

src/middlewared/middlewared/plugins/disk_/temperature.py

Investigating an unrelated issue, I found that front-end is calling this method every 2 seconds when in the `View Enclosure` page. (this is on 13 but didn't confirm on scale). What's worse, actually, is that certain webpages became non-responsive because the `disk.temperatures` tasks were stacking up and running before the previous tasks could complete. This caused a domino effect.
Either way, after discussions with William we've decided to rate limit this method to 5mins. `collectd` disk temp plugin probes every 5mins and `smartd` (by default) reads attributes every 30mins. For now, we've settled on 5 minutes to match collectd default.
I've also removed some freeBSD specific code.

NAS-116904 / 22.12 / rate limit disk.temperatures endpoint

---

src/middlewared/middlewared/plugins/disk_/temperature.py

Investigating an unrelated issue, I found that front-end is calling this method every 2 seconds when in the `View Enclosure` page. (this is on 13 but didn't confirm on scale). What's worse, actually, is that certain webpages became non-responsive because the `disk.temperatures` tasks were stacking up and running before the previous tasks could complete. This caused a domino effect.
Either way, after discussions with William we've decided to rate limit this method to 5mins. `collectd` disk temp plugin probes every 5mins and `smartd` (by default) reads attributes every 30mins. For now, we've settled on 5 minutes to match collectd default.
I've also removed some freeBSD specific code.
Original PR: https://github.com/truenas/middleware/pull/9302
Jira URL: …

NAS-116904 / 22.02.3 / rate limit disk.temperatures endpoint (by yocalebo)

---

src/middlewared/middlewared/plugins/smb.py

Samba stores SMB-related metadata as extended attributes.
This means that xattr support is required in order for an
SMB share to function as intended.

NAS-116900 / 22.12 / Verify that child mounts under SMB path are consistent

---

src/middlewared/middlewared/plugins/smb.py

Samba stores SMB-related metadata as extended attributes.
This means that xattr support is required in order for an
SMB share to function as intended.
Original PR: https://github.com/truenas/middleware/pull/9300
Jira URL: https://jira.ixsystems.com/browse/NAS-116900

NAS-116900 / 22.02.3 / Verify that child mounts under SMB path are consistent (by anodos325)

---

src/middlewared/middlewared/plugins/disk_/disk_events.py
src/middlewared/middlewared/plugins/disk_/sync.py
src/middlewared/middlewared/plugins/geom_/cache.py

Tested these changes with Jeff in QE team for, essentially, the entire day today. Each commit represents the 3 issues found respectively.

NAS-116962 / 13.0 / fix a few disk event/syncing issues found during QA

---

src/middlewared/middlewared/alert/source/m_series_nvdimm_firmware_freebsd.py

Add New qualifed Nvdimm firmware(2.1)version for 16GB 2666 NVDIMM

NAS-116986 / 13.0 / Update m_series_nvdimm_firmware_freebsd.py

---

src/middlewared/middlewared/plugins/chart_releases_linux/portals.py

This commit adds changes to allow users to specify ui portals for apps deployed via 'launch docker image' button.

NAS-115275 / 22.12 / Allow users to specify their own webui portals for apps

---

src/middlewared/middlewared/plugins/smart.py
src/middlewared/middlewared/pytest/unit/plugins/test_smart.py

…ss ...` even if progress is not reported
Original PR: https://github.com/truenas/middleware/pull/9374
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117113

NAS-117113 / 22.12 / Report S.M.A.R.T. test in progress if there is a `Self test in progre… (by themylogin)

---

tests/api2/test_427_smb_acl.py

We had regression in related to this and therefore
need explicit testing. In this case POSIX write bit
for special ACEs should be treated as a generic write
bit in the Windows SD rather than simply granting
WRITE_DATA.
Original PR: https://github.com/truenas/middleware/pull/9243
Jira URL: https://jira.ixsystems.com/browse/NAS-116767

NAS-116767 / 13.0 / Add test coverage for SMB ACL "map modify" behavior (by anodos325)

---

src/middlewared/middlewared/plugins/smb_/status.py

AUTH_LOG can block so this needs to be sync.

NAS-117209 / 22.12 / Convert smb.status to sync method

---

src/middlewared/middlewared/plugins/chart_releases_linux/scale_workload.py
src/middlewared/middlewared/plugins/kubernetes_linux/services.py

If an app has been stopped or scaled down and it's endpoint is called, we see console being spammed because valid ipvs rules exist as the service of the app still exists and just the resources have been scaled down. The spam happens because the ipvs rules forward the packets as specified but there is no workload available at the moment because it has been scaled down.
When we scale down, we remove all services related to the application which results in the ipvs rules being removed as well and hence no spam with user just getting connection refused error. On scaling the app back up, we redeploy the application which basically means helm does a 3 way merge re-creating the resources which are not there which in our case are the missing services and then scaling the workloads back up.

NAS-116664 / 22.12 / Remove services on scale down and redeploy then on scale up

---

tests/api2/test_427_smb_acl.py
tests/utils.py

Results: https://builds.ixsystems.com/job/Test%20development/job/TrueNAS%2013.0%20Internal%20API%20Tests%20from%20branch/33/

DOCS-3937 / 13.0 / adding missing tests/utils.py and fixed acltype from test_427_smb_acl.py in test 05 

---

src/middlewared/middlewared/plugins/cloud_sync.py
src/middlewared/middlewared/plugins/rsync.py
src/middlewared/middlewared/plugins/zettarepl_/state.py

… case first arg is `None`
Original PR: https://github.com/truenas/middleware/pull/9430
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117248

NAS-117248 / 22.02.3 / Fix parsing replication/rsync/cloud sync task ID from the job args in… (by themylogin)

---

src/middlewared/middlewared/plugins/update_/install.py

Use zfs.dataset plugin to retreive the zpool equivalent of AVAIL

NAS-117264 / 22.02.3 / Updater size estimates seem quite off

---

src/middlewared/middlewared/migration/0002_shell_linux.py

2 issues fixed
1. if a user shell was set to nologin on core, we did not migrate that properly on SCALE
2. we left invalid shells set when migrating from core to scale
Fix both issues by defaulting the users shell to `/usr/sbin/nologin`.

NAS-117276 / 22.12 / migrate shells from core to scale properly

---

src/middlewared/middlewared/migration/0002_shell_linux.py

2 issues fixed
1. if a user shell was set to nologin on core, we did not migrate that properly on SCALE
2. we left invalid shells set when migrating from core to scale
Fix both issues by defaulting the users shell to `/usr/sbin/nologin`.
Original PR: https://github.com/truenas/middleware/pull/9446
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117276

NAS-117276 / 22.02.3 / migrate shells from core to scale properly (by yocalebo)

---

src/middlewared/middlewared/plugins/smb.py

In the days of TrueNAS 9 we allowed a customer to set an empty
string as the path for the SMB homes share. It was limited to
only LDAP users with samba schema. This has special behavior in
samba in that it will look up the path based on user home directory
and share that path out. Since these paths can be anywhere on the
server the result is potentially undefined behavior. Our product
has become more complex since those days with dataset-level
encryption and other features. Determining whether the share path
is locked also becomes impossible for fairly obvious reasons.
Hence, the undocumented customer-specific feature is being
removed.

NAS-117293 / 22.12 / Deprecate legacy behavior to allow empty homes path

---

src/middlewared/middlewared/plugins/smb.py

In the days of TrueNAS 9 we allowed a customer to set an empty
string as the path for the SMB homes share. It was limited to
only LDAP users with samba schema. This has special behavior in
samba in that it will look up the path based on user home directory
and share that path out. Since these paths can be anywhere on the
server the result is potentially undefined behavior. Our product
has become more complex since those days with dataset-level
encryption and other features. Determining whether the share path
is locked also becomes impossible for fairly obvious reasons.
Hence, the undocumented customer-specific feature is being
removed.
Original PR: https://github.com/truenas/middleware/pull/9458
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117293

NAS-117293 / 22.02.3 / Deprecate legacy behavior to allow empty homes path (by anodos325)

---

src/middlewared/middlewared/plugins/pool_/dataset_details.py

With https://github.com/truenas/middleware/pull/9463 being merged, I can now add `apps` information to the `pool.dataset.details` endpoint.

NAS-117305 / 22.12 / fill in app information in pool.dataset.details

---

src/freenas/usr/local/sbin/disk_resize

Rewrite disk_resize to work on Linux.
Jira: https://ixsystems.atlassian.net/browse/NAS-111488

NAS-111488 / 22.12 / Linux disk resize

---

src/freenas/usr/local/sbin/disk_resize

Rewrite disk_resize to work on Linux.
Jira: https://ixsystems.atlassian.net/browse/NAS-111488
Original PR: https://github.com/truenas/middleware/pull/9460
Jira URL: https://ixsystems.atlassian.net/browse/NAS-111488

NAS-111488 / 22.02.3 / Linux disk resize (by freqlabs)

---

src/middlewared/middlewared/plugins/activedirectory_/health.py

AD domain validation shouldn't happen until middleware is fully
started.

NAS-117313 / 22.12 / Fix out of order check for system.ready in ad.started method

---

src/middlewared/middlewared/plugins/activedirectory_/health.py

AD domain validation shouldn't happen until middleware is fully
started.
Original PR: https://github.com/truenas/middleware/pull/9474
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117313

NAS-117313 / 22.02.3 / Fix out of order check for system.ready in ad.started method (by anodos325)

---

src/middlewared/middlewared/plugins/smb.py

Look ma, I'm a middleware developer now.

NAS-117328 / 22.12 / Fixes an empty line in SMB share presets

---

src/middlewared/middlewared/plugins/service_/services/kubernetes.py

Recently we have seen some users who had malformed k3s server token when their server was shutdown unexpectedly i.e power loss.
I have not been able to locate exact reason why it got malformed in such cases but this results in kubernetes not working when the server is rebooted.
The fix is quite straight forward, after investigation I found that the token is generally used to join multiple nodes and is used in encrypting bootstrap data of k3s which is used for joining nodes which does not apply to us.
If k3s had generated this token once, and the file is removed, k3s generates it again correctly which workarounds the problem of the token being malformed and the file being empty in some cases.

NAS-117074 / 22.12 / Fix kubernetes token issue

---

src/middlewared/middlewared/plugins/support.py

New JIRA does not support login/password authentication, we have to backport OAuth changes

NAS-117272 / 13.0 / Use oauth token for support-proxy

---

cluster-tests/tests/directoryservices/test_001_activedirectory.py
cluster-tests/tests/smb/test_001_sharing_smb.py
src/middlewared/middlewared/plugins/cluster_linux/ctdb_services.py
src/middlewared/middlewared/scripts/ctdb_events.py

Clearly designate when we want ctdbd to manage a clustered
service via event monitoring. Fix tests to check for
smbd socket connectivity.

NAS-117443 / 22.12 / Fix clustered SMB service management events

---

src/middlewared/middlewared/plugins/boot.py
src/middlewared/middlewared/plugins/pool.py

Tested on local vm to produce the same results as `pool.query()`

NAS-117371 / 22.12 / Make `type` field in pool topology and boot.get_state similar

---

cluster-tests/config.py
cluster-tests/tests/directoryservices/test_001_activedirectory.py

This reverts commit 17a20068ef4063f8906776167a03373bf0de6f26.

NAS-117526 / 22.02.4 / Revert "Revert "set netbios name in cluster api tests (#8762)" (#8855)"

---

src/middlewared/middlewared/plugins/cluster_linux/ctdb_public.py

Previous logic was almost correct in that we need to exclude ctdb public ip interface choices if there is an existing IP address on said interface and that IP address is a ctdb private IP.
This should make is so we properly return ctdb public IP interface choices.

NAS-117528 / 22.12 / properly show ctdb public ip interface candidates

---

src/middlewared/middlewared/plugins/cluster_linux/ctdb_public.py

Previous logic was almost correct in that we need to exclude ctdb public ip interface choices if there is an existing IP address on said interface and that IP address is a ctdb private IP.
This should make is so we properly return ctdb public IP interface choices.
Original PR: https://github.com/truenas/middleware/pull/9587
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117528

NAS-117528 / 22.02.3 / properly show ctdb public ip interface candidates (by yocalebo)

---

src/middlewared/middlewared/plugins/cluster_linux/ctdb_public.py

Previous logic was almost correct in that we need to exclude ctdb public ip interface choices if there is an existing IP address on said interface and that IP address is a ctdb private IP.
This should make is so we properly return ctdb public IP interface choices.
Original PR: https://github.com/truenas/middleware/pull/9587
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117528

NAS-117528 / 22.02.4 / properly show ctdb public ip interface candidates (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/virtual_ips.py

`keepalived` service is responsible for installing the VIPs on the interfaces. This means that by the time this method runs, there could be no vips. Skip interfaces without a `vrrp_config` attribute since it's non-fatal in this method.

NAS-117556 / 22.12 / fix IndexError in failover.vip.get_states

---

src/middlewared/middlewared/plugins/failover_/virtual_ips.py

`keepalived` service is responsible for installing the VIPs on the interfaces. This means that by the time this method runs, there could be no vips. Skip interfaces without a `vrrp_config` attribute since it's non-fatal in this method.
Original PR: https://github.com/truenas/middleware/pull/9598
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117556

NAS-117556 / 22.02.4 / fix IndexError in failover.vip.get_states (by yocalebo)

---

src/middlewared/middlewared/plugins/system_general/ui.py

`psutil.net_connections` is too expensive and doesn't scale well on a busy system.

NAS-117601 / 22.12 / optmize system.general.get_ui_urls

---

src/middlewared/middlewared/plugins/system.py

`psutil.net_connections` is too expensive and doesn't scale well on a busy system.
Original PR: https://github.com/truenas/middleware/pull/9614
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117601

NAS-117601 / 22.02.4 / optmize system.general.get_ui_urls (by yocalebo)

---

src/middlewared/middlewared/scripts/ctdb_events.py

For various reasons the middleward socket may not be available
when we are starting the ctdbd service. If this is the case, then
we should fall back to just checking that the ctdb_shared_volume
gluster volume is mounted.

NAS-117604 / 22.12 / Fix initialization event for ctdbd

---

src/middlewared/middlewared/scripts/ctdb_events.py

For various reasons the middleward socket may not be available
when we are starting the ctdbd service. If this is the case, then
we should fall back to just checking that the ctdb_shared_volume
gluster volume is mounted.
Original PR: https://github.com/truenas/middleware/pull/9616
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117604

NAS-117604 / 22.02.4 / Fix initialization event for ctdbd (by anodos325)

---

src/middlewared/middlewared/plugins/network.py

NAS-114305 / 22.12 / add cancel_rollback to interface API

---

src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/alert.py
src/middlewared/middlewared/plugins/migration.py
src/middlewared/middlewared/utils/plugins.py
src/middlewared/middlewared/worker.py

This was removed a while ago, but scaffolding was left in place. Remove the scaffolding.

NAS-117681 / 22.12 / Remove overlay_dirs

---

tests/api2/test_300_nfs.py
tests/protocols.py

This simplifies / reduces test count and also adds coverage
for basic ops over V4 protocol.

NAS-117684 / 22.12 / Separately test basic NFS ops for version 3 and version 4

---

src/middlewared/middlewared/plugins/smb_/status.py

AUTH_LOG can block so this needs to be sync.
Original PR: https://github.com/truenas/middleware/pull/9411
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117209

NAS-117209 / 13.0 / Convert smb.status to sync method (by anodos325)

---

src/middlewared/middlewared/plugins/disk_/temperature.py

Convert `NaN` float to `NoneType` to follow the paradigm that we use everywhere else.

NAS-117727 / 22.12 / convert NaN float to NoneType in temperature_agg

---

cluster-tests/tests/gluster/test_volume.py

NAS-117735 / 22.12 / Only break out of fuse mount loop early on success

---

cluster-tests/tests/gluster/test_volume.py

This fixes a cluster test.
Original PR: https://github.com/truenas/middleware/pull/9669
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117735

NAS-117735 / 22.02.4 / Only break out of fuse mount loop early on success (by anodos325)

---

tests/api2/test_300_nfs.py
tests/protocols.py

Test this by running an ad-hoc python script calling
the relevant syscalls.

NAS-117699 / 22.12 / Add test for NFS server-side-copy

---

src/middlewared/middlewared/plugins/failover.py

Trying to be too clever with the checks. Simple fact is that we need 1 interface to have `int_vip` and 1 interface with `int_critical` set. Nothing more, nothing less.
Original PR: https://github.com/truenas/middleware/pull/9691
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117829

NAS-117829 / 22.02.4 / fix failover.disabled.reasons....again (by yocalebo)

---

src/middlewared/middlewared/plugins/system_advanced/config.py

In the UI isolating GPU form is separate then the system advanced settings form but at API level the call goes to `system.advanced.update`.
For a user, he had invalid serial port specified and `system.advanced.update` was erroring out as all the fields were being validated. After discussing with @yocalebo we decided to have a separate end point to update isolated GPU PCI ids.

NAS-117409 / 22.12 / Add another method for isolating gpu pci ids

---

src/middlewared/middlewared/plugins/iscsi.py

NAS-117395 / 22.02.4 / iscsi_/extents.py blocks main event loop in many places

---

debian/debian/postinst

This matches what we're already doing in master repo.

NAS-117800 / 22.02.4 / mask off unused systemd unit files

---

src/freenas/usr/local/libexec/freenas-debug/active_directory/active_directory.sh
src/middlewared/middlewared/plugins/activedirectory_/health.py

* Make wbinfo subprocess synchronous
* Add method to use the stored machine account password to get AD
status.
* Include new machine_account_status in debug

NAS-117471 / 22.12 / Improve AD health checks

---

src/middlewared/middlewared/plugins/smb.py
src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py

We have added linux libraries to make these VFS modules work
on SCALE. We can now allow them to pass validation

NAS-117858 / 22.12 / Relax validation for FreeBSD VFS modules

---

src/middlewared/middlewared/plugins/idmap.py

Remove unnecessary winbindd restart. Wipe the winbindd cache
via python bindings rather than removing it.

NAS-117865 / 22.12 / Fix timeout during idmap updates

---

tests/api2/test_001_ssh.py

git cherry-pick -x 913f49e3eecde2dad17d032c387db91d1930f94a
Verify that our expected system dataset structure is created
and mounted with expected options during firstboot. Verify that
we don't have any unexpected services running before we start
tests.
Original PR: https://github.com/truenas/middleware/pull/9678
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117801

NAS-117801 / 22.02.4 / Add some explicit tests for firstboot (by anodos325)

---

src/middlewared/middlewared/plugins/docker_linux/images.py

We are seeing an edge case where docker image might not have a valid creation timestamp which results in conversion to date time failing ( i was not able to create such an image though for reference ).
e.g
```
truecharts/tailscale                               latest            d689f53265f0   N/A             49.9MB
```

NAS-117736 / 22.12 / Handle edge case for docker created time

---

tests/api2/test_013_test_corssl.py

backported from https://github.com/truenas/middleware/pull/9774

AUTO-220 / 22.12-BETA.1 / Fixed missing close parentheses corssl test 02

---

src/freenas/usr/local/sbin/hactl
tests/api2/test_008_hactl.py

Does a few things:
1. refactors and makes it use SCALE HA specific api
2. simplifies the code
3. fixes some verbiage that causes confusion
4. fix a few edge-case bugs
5. adds basic integration tests since this is so heavily used in support land

NAS-117887 / 22.12 / improve and refactor hactl

---

src/middlewared/middlewared/main.py
src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/test/integration/utils/client.py
tests/api2/test_auth_token.py

(cherry picked from commit d5f7512154ab7d98054f9db3289054acd56d9e31)

NAS-118091 / 22.02.4 / Forbid using download token for websocket authentication

---

src/middlewared/middlewared/plugins/failover_/remote.py

While QE was testing SCALE HA on an internal system, they managed to get it into a funky state and I noticed that the default 20 second blocking `wait` on the socket caused the system to "slow down" quite dramatically. (At least that's how it was perceived). This adds a `connect_timeout` to the remote client and changes it to `2.0` seconds by default. If the underlying socket doesn't respond within 2 seconds, then we have problems. 20 seconds is too extreme.
This makes `hactl` and `failover.status` and `failover.disabled.reasons` respond in a much more reasonable time when the heartbeat interface has an issue.
I've also added a docstring for `failover.call_remote` since the options were kind of cryptic.

NAS-118103 / 22.12 / add connect_timeout to remote client

---

src/middlewared/middlewared/plugins/failover_/fenced.py

Sigh...yet another awesome "feature" of linux to implement something like cgroups. I'm sure there are valid use-cases but there are also use-cases where it makes me want to throw my PC out of my window.
It's imperative that `fenced` _always_ run even if `systemctl restart middlewared` is called via the CLI. Before these changes, `fenced` child process receives the same signals as parent process which means the daemon would get killed and never restarted. Potentially causing "funness" on HA systems....

NAS-118110 / 22.12 / move fenced process to root cgroup

---

src/middlewared/middlewared/plugins/failover_/fenced.py

Sigh...yet another awesome "feature" of linux to implement something like cgroups. I'm sure there are valid use-cases but there are also use-cases where it makes me want to throw my PC out of my window.
It's imperative that `fenced` _always_ run even if `systemctl restart middlewared` is called via the CLI. Before these changes, `fenced` child process receives the same signals as parent process which means the daemon would get killed and never restarted. Potentially causing "funness" on HA systems....
Original PR: https://github.com/truenas/middleware/pull/9817
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118110

NAS-118110 / 22.02.4 / move fenced process to root cgroup (by yocalebo)

---

src/middlewared/middlewared/plugins/activedirectory_/cache.py
src/middlewared/middlewared/plugins/activedirectory_/health.py
src/middlewared/middlewared/plugins/idmap.py
src/middlewared/middlewared/plugins/idmap_/utils.py
src/middlewared/middlewared/plugins/smb.py
src/middlewared/middlewared/plugins/smb_/sharesec.py

Replace multiple subprocess calls with libwbclient

NAS-118094 / 22.12 / Use libwbclient bindings

---

src/middlewared/middlewared/plugins/rsync.py
src/middlewared/middlewared/utils/osc/linux/user_context.py

git cherry-pick -x 20c320055c48ed1adf32825c73deba8ac6ab3f11
Original PR: https://github.com/truenas/middleware/pull/9847
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117410

NAS-117410 / 22.02.4 / Do not store rsync command output in RAM (by themylogin)

---

src/middlewared/middlewared/plugins/failover_/event.py

Nothing is ever easy.
`EZFS_NOENT` (`NOENT`) with error code `2009` is raised when the zpool doesn't get found from the contents of the cachefile
`ENOENT` with error code `2` is raised when the cachefile doesn't exist on disk
Original PR: https://github.com/truenas/middleware/pull/9855
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118150

NAS-118150 / 22.12 / properly catch libzfs EZFS_NOENT errno on failover (by yocalebo)

---

tests/api2/test_540_vm.py

Remove unsupported device
Fixed data vmid
Fixed test 05 isinstance
Fixed test 07 isinstance and added wait_on_job
changed the initial memory to 512 and the update memory to 768

AUTO-236 / 22.02.4 / Updated VM API test to pass on KVM nested vms

---

src/middlewared/middlewared/plugins/auth.py

(cherry picked from commit ff5bc13cbecb4ddb45393561213a92b0e7d03cee)

Drop privileges when changing authentication method

---

src/middlewared/middlewared/plugins/failover.py

`failover.become_passive` calls `service.restart keepalived` which breaks the other side of the FIFO connection that `middlewared` is blocking on waiting to receive failover events. When this happens, the other node receives a MASTER event (because `keepalived` on the other node migrated the VIP to it) and an event is generated. At the same time, however, the current MASTER node misses the failover event to become BACKUP because the other side of the FIFO connection was torn down.
So the other node receives the MASTER event, tries to start `fenced` but it fails to start because it detects the SCSI PR keys are actively changing on the disks which means the other node still has the zpool. So the failover process fails by design.
The _ONLY_ safe way to "become passive" is to violently reboot …

NAS-118271 / 22.12 / fix failover.become_passive

---

src/middlewared/middlewared/plugins/failover.py

(cherry picked from commit e0858129092ef638f2c2cee72ba9452ef7c3bbfd)
Co-authored-by: caleb <yocalebo@gmail.com>
(cherry picked from commit 1e4a1aebe4d0369e4e57cdbfa18476e9b2b23e0b)

NAS-118271 / 22.02.4 / fix failover.become_passive (#9883)

---

src/middlewared/middlewared/plugins/failover_/disabled_reasons.py

NAS-118283 / 22.12 / fix failover.disabled.reasons

---

src/middlewared/middlewared/etc_files/default/rrdcached.mako
src/middlewared/middlewared/etc_files/default/syslog-ng.mako
src/middlewared/middlewared/etc_files/glusterd.conf.mako
src/middlewared/middlewared/etc_files/nscd.conf.mako
src/middlewared/middlewared/logger.py
src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/plugins/sysdataset.py

There were quite a few IO calls being made outside of threads.

NAS-116495 / 22.12 / convert most of sysdataset plugin to sync

---

src/middlewared/middlewared/plugins/network.py

Found this error while working on fixing up the unit tests. (The unit tests were accurate and were actually failing because of this)

NAS-118329 / 22.12 / fix validation error

---

src/middlewared/middlewared/pytest/unit/plugins/test_interface.py

Found these while working on the unit tests. These, as far as I can tell, haven't worked in a _long_ time.

NAS-118331 / 22.12 / fix interface unit tests

---

src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_m_series_nvme.py

I recently made changes here to add R50BM enclosure support but broke the unit test in the process. This fixes that.

NAS-118330 / 22.12 / fix m-series nvme unit test

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/directoryservices.py
src/middlewared/middlewared/plugins/smb.py

We now use only a single netbiosname for the server. This is just continuing to deprecate old behavior from legacy FreeNAS versions.
Future PR will remove DB column and remove API references (we're leaving these for now until webui team confirms they're no longer using it).

NAS-118302 / 22.12 / Remove netbiosname_b from SMB plugin

---

src/middlewared/middlewared/plugins/directoryservices.py

This method gets called on system ready event and transitions our directory services state from JOINING to FAULTED or HEALTHY if enabled, and refreshes the cache. We also restart services that are enabled and dependent on AD or LDAP being functional.

NAS-117916 / 22.12 / Add new directoryservices.setup method

---

src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
src/middlewared/middlewared/plugins/failover_/journal.py

Diagnosing an issue with `failover.disabled.reasons`, I figured out why the `JournalSyncThread` is not being run during our integration tests.
1. add `JournalSyncService` class which is a small middleware service for caching the status of the `JournalSyncThread` class
2. call `failover.journal.thread_running` in the `failover.disabled.reasons` method to properly report if the journal sync thread is running
3. make sure we always start the journal sync thread when the `middlewared` service is restarted

NAS-118373 / 22.12 / Fix a few HA issues on SCALE

---

src/middlewared/middlewared/plugins/chart_releases_linux/secrets_management.py

This commit fixes an issue where on upgrades of apps, we take snapshots of storage used by the application - however when we sync each app's secrets and remove older versions, we don't remove snapshots associated with those.

NAS-118107 / 22.12 / Remove unused snapshots of chart releases when we sync secrets

---

tests/api2/test_007_systemdataset.py
tests/api2/test_008_pool.py
tests/api2/test_377_reporting.py

I added systemdataset and reporting test similar to the Bluefin API test
I removed global use in pool API test replaced it with pool_data fixture

AUTO-71 / 13.0 / Adding systemdataset API test with reporting API test

---

tests/api2/test_420_smb.py

Our existing tests failed to catch situation where recycling process would cause an SMB service disconnection. The new tests explicitly cover basic ops (creating / deleting files, creating, removing directories) and also ops on the recycle bin over the SMB1 and SMB3 protocols. This improves test coverage while also ensuring that tests are performed under a single SMB session.

NAS-118424 / 22.12 / Improve test_420_smb - use python SMB client

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
src/middlewared/middlewared/plugins/nis.py

NIS start / stop wasn't being propagated to remote node.

NAS-117976 / 13.0 / Fix NIS for HA

---

src/middlewared/middlewared/plugins/nis.py
tests/api2/test_043_nis.py

Add some basic CI for enabling NIS, checking health, and that NIS users / groups are present.

NAS-118578 / 13.0 / Add NIS regression tests

---

src/middlewared/middlewared/etc_files/local/avahi/avahi_services.py

Avahi-daemon sets an inotfiy watch on the services directory with a callback to reload_config() (same as sending SIGHUP to proc). This means that we should avoid unnecessary FS ops in that directory. To achieve this, we compare existing service config with expected one, and only write if the contents are changing.

NAS-118594 / 22.12 / Avoid unnecessary avahi reload_config() calls

---

src/middlewared/middlewared/plugins/chart_releases_linux/scale_workload.py

When an applications is stopped (scaled down), we scale down deployments/statefulsets so that their pods don't run. However if the app contains cronjobs i.e nextcloud, they continue on executing per their schedule as they are not scaled down.
Similar to how we remove services on scaling down apps, remove cronjobs as well so that they don't execute when the app is supposed to be stopped. When the app is going to be started (scaled up), these would be created again alongside with services by courtesy of helm.

NAS-118580 / 22.12 / Remove k8s cronjobs when scaling down apps

---

src/middlewared/middlewared/rclone/remote/storjix.py

…irmed by moby in storj-ixsystems Slack channel
Original PR: https://github.com/truenas/middleware/pull/10000
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118627

NAS-118627 / 13.0 / Employ new method of testing if storj bucket is related to iX as conf… (by themylogin)

---

tests/api2/test_377_reporting.py

The other method was to flaky now I just verify that the list is not empty

AUTO-294 / Changed the test that verify the cpu reporting after system dataset changed 

---

tests/api2/test_unsupported_md_devices.py

`pytest.skip` these show up as a failure on HA tests. Instead, don't run them at all.

NAS-118751 / 22.12 / fix md integration tests on HA

---

src/middlewared/middlewared/service.py

QE found this when testing REST API endpoints.

NAS-118780 / 22.12 / fix AttributeError in service.py

---

src/middlewared/middlewared/plugins/disk_/sync.py

During boot, the standby node is trying to sync the database to the active which is not what we want. Make sure the failover status is what we want before trying to sync the entire db to the other side.

NAS-118814 / 22.12 / Fix disk.sync_all when booting

---

src/middlewared/middlewared/plugins/kubernetes_linux/restore.py

When restoring kubernetes cluster, catalog dataset is treated as throwaway and is deleted and then re-created after restore is complete to sync latest catalogs available currently. However in an edge case if any syncing jobs are active - catalog dataset deletion job fails due to active processes.
If catalogs are syncing or waiting to be synced, wait for in progress jobs to complete and abort the jobs which are in WAITING condition so that deletion operation can succeed.

NAS-118759 / 22.12 / Handle edge case for catalog sync jobs in k8s restore

---

src/middlewared/middlewared/plugins/disk_/sync.py

During boot, the standby node is trying to sync the database to the active which is not what we want. Make sure the failover status is what we want before trying to sync the entire db to the other side.
Original PR: https://github.com/truenas/middleware/pull/10046
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118814

NAS-118814 / 13.0 / Fix disk.sync_all when booting (by yocalebo)

---

src/middlewared/middlewared/plugins/disk.py

`sedutil-cli` disables this feature automatically on linux only (when `--initialSetup` is run) for some inexplicable reason. We need to disable this feature the same way on freebsd. Explicitly disable this when initial setup is run as well as on unlock.

NAS-118858 / 13.0 / disable mbr feature on sed disks

---

src/middlewared/middlewared/plugins/gluster_linux/bricks.py

Part 1 of many parts to come for expanding a gluster volume. This isn't used anywhere, yet. I will also add integration tests after all dependent methods are written.

NAS-118910 / 22.12 / add private GlusterBricksService

---

src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py

When `LoadBalancer` type services are used with apps,system was not accounting for those services when determining `used_ports` of an application.

NAS-118571 / 22.12 / Fix used ports output when load balancer services are used

---

src/middlewared/middlewared/plugins/gluster_linux/bricks.py
src/middlewared/middlewared/plugins/gluster_linux/utils.py
src/middlewared/middlewared/plugins/gluster_linux/volume.py

NAS-118990 / 22.12 / add format_bricks helper function

---

src/middlewared/middlewared/plugins/chart_releases_linux/secrets_management.py

For a user we saw that his helm secret had become malformed due to reasons unknown which resulted in us failing to list any apps as when we queried secrets and tried to parse them to get their details that failed resulting in us failing to list down any apps.
I explored helm behaviour in this case and noticed that `helm history` ignored the revision secret which was affected and showed down other valid revisions which were still available without having their secrets malformed.
Keeping in line with helm behaviour changes have been made to ignore decode exceptions in this case and just log that this happened once.

NAS-118819 / 22.12 / Handle edge case of malformed helm secrets

---

src/middlewared/middlewared/plugins/pool_/replace_disk.py

1. don't call blocking I/O in main event loop
2. remove unused imports
3. logical refactor to make it easier to read

NAS-118922 / 22.12 / fix and improve pool.replace

---

src/middlewared/middlewared/plugins/zfs_/disks.py

Noticed in a debug while investigating an unrelated problem.

NAS-119057 / 22.12 / fix KeyError in zfs_/disks.py

---

tests/install.exp

Also made sure that it is still compatible with the previous version of SCALE. 
Replaced FreeNAS with TrueNAS and removed CORE code from the install script

AUTO-311 / 22.12 / Adding changes for root less in install expect script.

---

src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py

Before redeploying apps we were not ensuring that no built-in taints are present and there was an infinite waiting cycle on pods to shift to running state before kube-router rules were configured.
Wait for built in taints to be removed and properly implement wait for other different contexts in post start lifecycle of k8s service to confirm we don't have infinite waiting cycle.

NAS-119026 / 22.12 / Properly wait for built in taints to be removed

---

src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/plugins/zfs.py

rather than shelling out to the zfs command.

NAS-117563 / 23.10 / Use libzfs to get and set quotas

---

src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/plugins/zfs.py

rather than shelling out to the zfs command.
Original PR: https://github.com/truenas/middleware/pull/10073
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117563

NAS-117563 / 22.12.1 / Use libzfs to get and set quotas (by freqlabs)

---

src/middlewared/middlewared/plugins/pool.py

Map quota_value 0 to none to remove quotas.

NAS-119226 / 23.10 / set_quota: Fix 0 to remove quota

---

src/middlewared/middlewared/plugins/pool.py

Map quota_value 0 to none to remove quotas.
Original PR: https://github.com/truenas/middleware/pull/10156
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119226

NAS-119226 / 22.12.1 / set_quota: Fix 0 to remove quota (by freqlabs)

---

src/freenas/usr/local/sbin/ix-update
src/middlewared/middlewared/alembic/versions/22.12/2022-06-12_17-50_iscsi_target_networks.py

Let's not merge this yet, I asked the user for his configuration database to ensure I fixed the correct thing.

NAS-119187 / 23.10 / Nas 119187

---

src/freenas/usr/local/sbin/ix-update
src/middlewared/middlewared/alembic/versions/22.12/2022-06-12_17-50_iscsi_target_networks.py

Let's not merge this yet, I asked the user for his configuration database to ensure I fixed the correct thing.
Original PR: https://github.com/truenas/middleware/pull/10149
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119187

NAS-119187 / 22.12.1 / Nas 119187 (by themylogin)

---

src/middlewared/middlewared/plugins/pool.py

Middleware incorrectly reports that a pool had a scrub executed when that had never materialised.

NAS-119110 / 23.10 / Properly log scrub of pool in middleware logs

---

tests/README.md
tests/api2/test_261_iscsi_cmd.py
tests/protocols/__init__.py
tests/protocols/iscsi_proto.py
tests/requirements.txt

This commit adds some basic CI tests for iSCSI targets implemented using libiscsi, cython-iscsi and PYSCSI.

NAS-119092 / 22.12.1 / Add libiscsi/pyscsi based iSCSI tests.

---

src/middlewared/middlewared/alert/base.py

No SCALE backport is needed, we have a more generic solution there

NAS-119178 / 13.0 / Use html2text in `format_alert`

---

tests/api2/test_540_vm.py

Test 04 is failing under Bhyve.

AUTO-323 / 23.10 / Moved vm test 04 under support_virtualization condition

---

tests/README.md
tests/api2/test_261_iscsi_cmd.py
tests/protocols/__init__.py
tests/protocols/iscsi_proto.py
tests/requirements.txt

Add libiscsi/pyscsi based iSCSI tests.
Add some basic CI tests for iSCSI targets implemented using libiscsi, cython-iscsi and PYSCSI.

NAS-119092 / 23.10 / Add libiscsi/pyscsi based iSCSI tests. (#10154)

---

src/middlewared/middlewared/plugins/reporting/iostat.py

Investigating scalability problems on a large internal system showed that an abnormal amount of time was spent in `psutil.disk_io_counters`. Specifically, it was busy doing `readlines()` on `/proc/diskstats`. This fixes that problem by transposing the same logic to this class but instead of reading the entire file into memory, iterate over it. Generating flamegraph afterwards has shown that this is no longer a problem.
Original PR: https://github.com/truenas/middleware/pull/10173
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119240

NAS-119240 / 22.12.1 / improve efficiency of reporting.iostat.DiskStats (by yocalebo)

---

src/middlewared/middlewared/plugins/crypto.py

If a CA has issued certificates and we try to delete the CA, users are greeted with a traceback where database does not allow deleting the certificate because of foreign key references.
Neatly determine if CA has issued any certificates and raise a validation error before trying to delete it.

NAS-118999 / 13.0 / Gracefully raise exception when deleting CA

---

src/middlewared/middlewared/etc_files/pam.d/common-account.mako
src/middlewared/middlewared/etc_files/pam.d/common-auth.mako
src/middlewared/middlewared/etc_files/pam.d/common-password.mako
src/middlewared/middlewared/etc_files/pam.d/common-session.mako
src/middlewared/middlewared/etc_files/pam.d/pam.inc.mako

We want to check pam_unix prior to anything with directory services.

NAS-119267 / 23.10 / Change ordering and arguments of pam modules

---

src/middlewared/middlewared/plugins/pool_/dataset_details.py

Requested by webUI team to allow them to more easily paginate the response.

NAS-119375 / 23.10 / flatten pool.dataset.details

---

src/middlewared/middlewared/plugins/disk_/zfs_guid.py
src/middlewared/middlewared/test/integration/utils/mock_db.py
tests/api2/test_disk_zfs_guid.py

* When retrieving disk by ZFS guid prioritize present disks over expired

NAS-119251 / 23.10 / * Do not set ZFS guid for expired disks with the same name

---

src/middlewared/middlewared/alert/source/pools.py
src/middlewared/middlewared/plugins/pool.py
tests/api2/test_pool_is_upgraded_alert_removal.py

git cherry-pick -x 8650e1b15a34e89f0cab4477267c3f08bca3ddef
Original PR: https://github.com/truenas/middleware/pull/10288
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119489

NAS-119489 / 22.12.1 / Delete `PoolUpgraded` alert on pool upgrade (by themylogin)

---

src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/plugins/pool_/dataset_details.py
src/middlewared/middlewared/plugins/pool_/unlock.py
src/middlewared/middlewared/plugins/vm/vm_devices.py

git cherry-pick -x 151a95c23750f622a8eeaa804f3f60445127a96f
git cherry-pick -x c04f46ad762e4820efabf9e1bb7d099e081f401e
Original PR: https://github.com/truenas/middleware/pull/10241
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119380

NAS-119380 / 22.12.1 / Do not treat `legacy` as mountpoint (by themylogin)

---

src/middlewared/middlewared/plugins/disk_/format.py
src/middlewared/middlewared/plugins/pool.py
src/middlewared/middlewared/plugins/pool_/format_disks.py
src/middlewared/middlewared/plugins/pool_/info.py
src/middlewared/middlewared/plugins/pool_/replace_disk.py
src/middlewared/middlewared/test/integration/assets/pool.py
tests/api2/test_pool_replace_disk.py

…rtiton of required size
Original PR: https://github.com/truenas/middleware/pull/10066
Jira URL: https://ixsystems.atlassian.net/browse/NAS-114479

NAS-114479 / 22.12.1 / Shrink swap when formatting a disk in `pool.replace` to fit a data pa… (by themylogin)

---

src/middlewared/middlewared/plugins/zettarepl.py

There were no real possible errors that might be obscured by this `pass`... yet

NAS-119623 / 23.10 / Do not silently `pass` zettarepl startup error

---

src/middlewared/middlewared/test/integration/assets/apps.py
src/middlewared/middlewared/test/integration/assets/catalog.py
src/middlewared/middlewared/test/integration/assets/kubernetes.py
src/middlewared/middlewared/test/integration/utils/__init__.py
src/middlewared/middlewared/test/integration/utils/filesystem.py
tests/api2/test_026_kubernetes_backup_chart_releases.py

A test has been added to validate that the contents of apps backup are valid including backing up the app secrets and persistent volume information so we can use that information to restore the backup safely.

NAS-119464 / 23.10 / Add integration test for validating k8s backup

---

src/freenas/boot/loader.conf

https://github.com/Aquantia/aqtion-freebsd/issues/23

NAS-119635 / 13.0 / Limit Aquantia NICs to 8 rx/tx queues

---

src/middlewared/middlewared/alert/source/nvdimm.py

Our BHYVE SCALE HA VMs don't have nvdimm devices so the failure is expected.

NAS-119621 / 23.10 / dont spam logs

---

src/middlewared/middlewared/alert/source/nvdimm.py

Our BHYVE SCALE HA VMs don't have nvdimm devices so the failure is expected.
Original PR: https://github.com/truenas/middleware/pull/10306
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119621

NAS-119621 / 22.12.1 / dont spam logs (by yocalebo)

---

src/middlewared/middlewared/alembic/versions/22.12/2022-07-27_01-00_portal_ips.py

…sent in `services_iscsitargetportalip`
Original PR: https://github.com/truenas/middleware/pull/10321
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119608

NAS-119608 / 22.12.1 / Do not crash migration when multiple bindings for the same IP are pre… (by themylogin)

---

src/middlewared/middlewared/plugins/activedirectory_/krb5.py

There's not really a good reason to expose these publicly.

NAS-119676 / 23.10 / Shift two AD kerberos method to being private

---

tests/api2/test_035_ad_idmap.py

Use common directory services assets

NAS-119673 / 23.10 / Improve state handling in AD idmap tests

---

tests/api2/test_035_ad_idmap.py

Use common directory services assets
Original PR: https://github.com/truenas/middleware/pull/10340
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119673

NAS-119673 / 22.12.1 / Improve state handling in AD idmap tests (by anodos325)

---

src/middlewared/middlewared/plugins/idmap.py
src/middlewared/middlewared/plugins/smb_/groupmap.py

Parser was broken during refactoring and not caught during
testing.
Original PR: https://github.com/truenas/middleware/pull/9246
Jira URL: https://jira.ixsystems.com/browse/NAS-115994
Original PR: https://github.com/truenas/middleware/pull/9264
Jira URL: https://jira.ixsystems.com/browse/NAS-115994

NAS-115994 / 13.0 / Fix idmap tdb gid parsing (by anodos325) (by bugclerk)

---

tests/api2/test_007_systemdataset.py

We need to override all nameservers for temporary AD join.

NAS-119706 / 23.10 / Cleanly set and cleanup nameservers in test_007

---

tests/api2/test_007_systemdataset.py

We need to override all nameservers for temporary AD join.
Original PR: https://github.com/truenas/middleware/pull/10354
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119706

NAS-119706 / 22.12.1 / Cleanly set and cleanup nameservers in test_007 (by anodos325)

---

src/middlewared/middlewared/plugins/enclosure_/map.py

NAS-119744 / 23.10 / add MINI-R platform to enclosure mgmt

---

src/middlewared/middlewared/plugins/enclosure_/map.py

Tested on internal hardware
Original PR: https://github.com/truenas/middleware/pull/10373
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119744

NAS-119744 / 22.12.1 / add MINI-R platform to enclosure mgmt (by yocalebo)

---

src/middlewared/middlewared/plugins/activedirectory_/cache.py

During the FreeNAS 9.10 release cycle it was determined that the implementation of the internal AD and LDAP user and group cache in large environments with huge user counts would render the webui entirely unusable (operations would block waiting for a db to get filled with potentially thousands of AD users and groups). As a workaround at that time a new db key was added to entirely disable this caching mechanism `disable_freenas_cache`. In FreeNAS 11.3 the cache was redesigned. By this time the middleware was multithreaded, and the cache was written in a way to take advantage of this.
`disable_freenas_cache` was kept around as a fallback mechanism for large environments so that support would have the ability to disable the caching if it proved to be problematic. In the disabled case, we …

NAS-119788 / 23.10 / Remove legacy optimization for AD cache

---

src/middlewared/middlewared/plugins/activedirectory_/cache.py

During the FreeNAS 9.10 release cycle it was determined that the implementation of the internal AD and LDAP user and group cache in large environments with huge user counts would render the webui entirely unusable (operations would block waiting for a db to get filled with potentially thousands of AD users and groups). As a workaround at that time a new db key was added to entirely disable this caching mechanism `disable_freenas_cache`. In FreeNAS 11.3 the cache was redesigned. By this time the middleware was multithreaded, and the cache was written in a way to take advantage of this.
`disable_freenas_cache` was kept around as a fallback mechanism for large environments so that support would have the ability to disable the caching if it proved to be problematic. In the disabled case, we …

NAS-119788 / 22.12.1 / Remove legacy optimization for AD cache (by anodos325)

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/map.py

Tested on internal hardware
Original PR: https://github.com/truenas/middleware/pull/10373
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119744

NAS-119744 / 13.0 / add MINI-R platform to enclosure mgmt (by yocalebo)

---

src/middlewared/middlewared/plugins/pool_/import_disk.py

NTFS disk import jobs were stuck at 0% complete.

NAS-119795 / 23.10 / Fix progress reporting for NTFS disk import

---

src/middlewared/middlewared/plugins/smb.py

SMB share paths that contain components that are
symbolic links may be unstable (as user may remove symlink breaking the share). Generally speaking,
we don't support the creation of symbolic links
through our API / webui and so this requires user
to manually do such things through the shell. This means additional validation shouldn't break users
who are using the appliance within bounds that
we set up, but should prevent some problem reports where users do things totally off the wall.
Original PR: https://github.com/truenas/middleware/pull/10404
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119815

NAS-119815 / 22.12.1 / Add additional validation related to symlinks (by anodos325)

---

src/middlewared/middlewared/main.py

Seen on a user that ran their truenas on "gamer" hardware. We constantly spammed log files with Input/Output error when we tried to flush the console messages.
Original PR: https://github.com/truenas/middleware/pull/10419
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119839

NAS-119839 / 22.12.1 / prevent console error log spam (by yocalebo)

---

src/middlewared/middlewared/plugins/disk.py

Seen in the wild.  Someone had put `-d nvme` as an extra smart option in our API. Surprisingly, we do 0 validation here. We statically generate the smartd config and don't "overwrite" the config with any of these flags so it's best to prevent them here to prevent the smartd.conf from being generated incorrectly which ultimately prevents the smartd service from starting.

NAS-119841 / 23.10 / prevent breaking smartd service with extra options

---

src/middlewared/middlewared/plugins/disk.py

Seen in the wild.  Someone had put `-d nvme` as an extra smart option in our API. Surprisingly, we do 0 validation here. We statically generate the smartd config and don't "overwrite" the config with any of these flags so it's best to prevent them here to prevent the smartd.conf from being generated incorrectly which ultimately prevents the smartd service from starting.
Original PR: https://github.com/truenas/middleware/pull/10421
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119841

NAS-119841 / 22.12.1 / prevent breaking smartd service with extra options (by yocalebo)

---

src/middlewared/middlewared/plugins/pool.py

I was recently given the opportunity to connect to a CORE system that had ~1350 disks and 91 expansion shelves....it was kind of insane. Long-story kept short, this method was calling (eventually) the `bsd.sysctl` module which was failing to allocate memory. It's a poorly written module and this has been experienced in other parts of the code base. This PR resolves that scenario.
Without these changes, on that particular system, middlewared would not start rendering the webUI inaccessible. With these changes, it allowed middlewared to start in ~10 seconds.

NAS-119849 / 13.0 / fix memory allocation error on MASSIVE systems

---

src/middlewared/middlewared/plugins/kubernetes_linux/update.py

Allow re-initializing ix-applications dataset if the existing setup has missed datasets which are required for apps to function (in the case when force flag is specified). This will destroy the current corrupt ix-applications setup and re-initialize the dataset as a fresh start for kubernetes.

NAS-119452 / 23.10 / Allow re-initializing ix-applications when force flag is specified

---

src/middlewared/middlewared/plugins/pool_/track_processes.py

git cherry-pick -x 08b9364b20a0950fee3aa42eecc1f51dd1da2e1b
git cherry-pick -x 80310fb994e94523b4c132b206547ce9d5403f38
Original PR: https://github.com/truenas/middleware/pull/10390
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119800

NAS-119800 / 22.12.1 / Handle gone processes in `pool.dataset_processes` (by themylogin)

---

src/middlewared/middlewared/plugins/vm/devices/storage_devices.py

`DISK` devices are supposed to point to zfs volumes and hence only a zfs volume should be specified in it's path attribute. Validation has been added to make sure users are not able to add random paths.

NAS-119854 / 23.10 / Validate disk device path

---

src/middlewared/middlewared/plugins/vm/devices/storage_devices.py

`DISK` devices are supposed to point to zfs volumes and hence only a zfs volume should be specified in it's path attribute. Validation has been added to make sure users are not able to add random paths.
Original PR: https://github.com/truenas/middleware/pull/10440
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119854

NAS-119854 / 22.12.1 / Validate disk device path (by Qubad786)

---

tests/api2/test_snmp_agent.py

Only in Cobia has this file been renamed to `TRUENAS-MIB.txt`

NAS-119859 / 22.12.1 / fix test_snmp_agent integration test

---

src/middlewared/middlewared/plugins/datastore/connection.py

It's not altogether clear how a user got in this situation, but the production impact of nuking the default domain idmap entry is rather profound. In the case of idmap-related tables we should remove the foreign key rather than deleting the table entry (at least if it's a builtin entry).
^^^ early stages of investigation
In commit https://github.com/truenas/middleware/commit/5265c8c49f84e3bf2bcd2bfcc30e3559019b0ca3 a migration was written to use AUTOINCREMENT to ensure id uniqueness.
In commit https://github.com/truenas/middleware/commit/85f5b97ec9a388b04ed50ff2c3c6528d0b3de994 the aforementioned migration was modified to also fix potential constraint
violation in this field.
Since there was a gap between these two commits, it is impossible that the original
migration without the …

NAS-119507 / 23.10 / Don't delete builtin idmap table entries on constraint violation

---

src/middlewared/middlewared/plugins/datastore/connection.py

In commit https://github.com/truenas/middleware/commit/5265c8c49f84e3bf2bcd2bfcc30e3559019b0ca3 a migration was written to use AUTOINCREMENT to ensure id uniqueness.
In commit https://github.com/truenas/middleware/commit/85f5b97ec9a388b04ed50ff2c3c6528d0b3de994 the aforementioned migration was modified to also fix potential constraint
violation in this field.
Since there was a gap between these two commits, it is impossible that the original
migration without the subsequent revision and therefore the user's DB still contains the original
constraint violation. This table entry is critical to the proper function of the AD
plugin and since it is user-configurable, deletion cannot be repaired without manual
intervention.
The practical impact of this is that AD users who had installed SCALE …

NAS-119507 / 22.12.1 / Don't delete builtin idmap table entries on constraint violation (by anodos325)

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/kerberos.py
tests/api2/test_036_ad_ldap.py
tests/protocols/nfs_proto.py

This PR adds a framework and some basic functional testing for using kerberos with NFSv4.

NAS-119876 / 23.10 / Add functional testing for NFS4 + KRB

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/kerberos.py
tests/api2/test_036_ad_ldap.py
tests/protocols/nfs_proto.py

This PR adds a framework and some basic functional testing for using kerberos with NFSv4.
Original PR: https://github.com/truenas/middleware/pull/10455
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119876

NAS-119876 / 22.12.1 / Add functional testing for NFS4 + KRB (by anodos325)

---

src/middlewared/middlewared/plugins/filesystem_/acl_base.py

Several SCALE users have siezed upon the idea that setting DENY entries for everyone@ is a good idea. Unfortunately, everyone@ refers to literally everyone on the system including the file owner, and we stubbornly enforce this rule (required by RFC3530 and RFC5661). I don't believe there is a legitimate case to set DENY entries for any special principas (owner@, group@, and everyone@) therefore we should raise a ValidationError in this case.

NAS-119850 / 23.10 / Prevent users from foot-shooting with DENY entries in ACL

---

src/middlewared/middlewared/plugins/filesystem_/acl_base.py

Several SCALE users have siezed upon the idea that setting DENY entries for everyone@ is a good idea. Unfortunately, everyone@ refers to literally everyone on the system including the file owner, and we stubbornly enforce this rule (required by RFC3530 and RFC5661). I don't believe there is a legitimate case to set DENY entries for any special principas (owner@, group@, and everyone@) therefore we should raise a ValidationError in this case.
Original PR: https://github.com/truenas/middleware/pull/10435
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119850

NAS-119850 / 22.12.1 / Prevent users from foot-shooting with DENY entries in ACL (by anodos325)

---

src/middlewared/middlewared/main.py

… loop
Original PR: https://github.com/truenas/middleware/pull/10509
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119770

NAS-119770 / 23.10 / Fix typo that leads to jobs being managed from outside the main event… (by themylogin)

---

src/middlewared/middlewared/plugins/service.py

We were passing query-filters directly to datastore.query without checking whether they were stored in the table.
This caused query-filters such as [['state', '=', 'RUNNING']] to fail with KeyError. This PR adds handling for these cases by performing unfiltered datastore.query in cases where filter cannot be reasonable applied at SQL-level.
This PR also adds a performance optimization to skip the service state check via an `extra` option.
This PR also slightly refactors service.query to utilize a `datastore_extend` and `datastore_extend_context` to perform service state retrieval.

NAS-119975 / 23.10 / Fix filtering service.query based on state

---

src/middlewared/middlewared/plugins/service.py

We were passing query-filters directly to datastore.query without checking whether they were stored in the table.
This caused query-filters such as [['state', '=', 'RUNNING']] to fail with KeyError. This PR adds handling for these cases by performing unfiltered datastore.query in cases where filter cannot be reasonable applied at SQL-level.
This PR also adds a performance optimization to skip the service state check via an `extra` option.
This PR also slightly refactors service.query to utilize a `datastore_extend` and `datastore_extend_context` to perform service state retrieval.
Original PR: https://github.com/truenas/middleware/pull/10518
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119975

NAS-119975 / 22.12.1 / Fix filtering service.query based on state (by anodos325)

---

src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
src/middlewared/middlewared/utils/__init__.py

Avoid unnecessary memory allocations when filtering.
Breaking this function apart improved readability
as well as improving performance in ad-hoc benchmarks by
approximately 25%.

NAS-120020 / 23.10 / Apply some minor improvements to filter_list

---

tests/api2/test_pool_is_upgraded_alert_removal.py

…time to appear/disappear
Original PR: https://github.com/truenas/middleware/pull/10567
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120065

NAS-120065 / 22.12.1 / Oneshot alerts are not created/deleted synchronously, give them some … (by themylogin)

---

tests/api2/test_pool_is_upgraded_alert_removal.py

…time to appear/disappear
Original PR: https://github.com/truenas/middleware/pull/10567
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120065

NAS-120065 / 22.12.2 / Oneshot alerts are not created/deleted synchronously, give them some … (by themylogin)

---

src/middlewared/middlewared/plugins/disk_/zfs_guid.py

Earlier versions of filter_list method contained
a bug where specifying `get` with `order_by` would short-circuit before sorting occured. So this
particular method would always return first
instance in the database. When the filter_list bug was fixed, it caused a regression in disk_by_zfs_guid because the `expiretime` key has intentionally
inconsistent types between database entries.
This PR changes from offloading the filtering to
filter_list to performing it in-method.

NAS-120063 / 23.10 / Fix sorting in disk_by_zfs_guid

---

src/middlewared/middlewared/plugins/disk_/zfs_guid.py

Earlier versions of filter_list method contained
a bug where specifying `get` with `order_by` would short-circuit before sorting occured. So this
particular method would always return first
instance in the database. When the filter_list bug was fixed, it caused a regression in disk_by_zfs_guid because the `expiretime` key has intentionally
inconsistent types between database entries.
This PR changes from offloading the filtering to
filter_list to performing it in-method.
Original PR: https://github.com/truenas/middleware/pull/10568
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120063

NAS-120063 / 22.12.1 / Fix sorting in disk_by_zfs_guid (by anodos325)

---

src/middlewared/middlewared/plugins/disk_/zfs_guid.py

Earlier versions of filter_list method contained
a bug where specifying `get` with `order_by` would short-circuit before sorting occured. So this
particular method would always return first
instance in the database. When the filter_list bug was fixed, it caused a regression in disk_by_zfs_guid because the `expiretime` key has intentionally
inconsistent types between database entries.
This PR changes from offloading the filtering to
filter_list to performing it in-method.
Original PR: https://github.com/truenas/middleware/pull/10568
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120063

NAS-120063 / 22.12.2 / Fix sorting in disk_by_zfs_guid (by anodos325)

---

tests/api2/test_pool_replace_disk.py

git cherry-pick -x 9be0c6feec10296b5ed9708e9adbf544b4b7faab
Original PR: https://github.com/truenas/middleware/pull/10574
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120028

NAS-120028 / 23.10 / Fix replacing a drive in a pool (by themylogin)

---

src/middlewared/middlewared/plugins/enclosure.py

ES60 drive bay mapping wasn't working because it enumerates the drive directories named `Drive Slot #0_***`. After investigating this method, I've found that we're not doing it the best way and each new enclosure platform that we add will cause us the same grief since the drive directory names are dynamic and can be whatever the enclosure manufacturer decides.
I've changed this so that it should, in theory, always detect drives no matter what enclosure platform we add in the future (famous last words, I know).

NAS-120036 / 23.10 / fix and improve enclosure disk slot mapping

---

src/middlewared/middlewared/plugins/enclosure.py

ES60 drive bay mapping wasn't working because it enumerates the drive directories named `Drive Slot #0_***`. After investigating this method, I've found that we're not doing it the best way and each new enclosure platform that we add will cause us the same grief since the drive directory names are dynamic and can be whatever the enclosure manufacturer decides.
I've changed this so that it should, in theory, always detect drives no matter what enclosure platform we add in the future (famous last words, I know).
Original PR: https://github.com/truenas/middleware/pull/10586
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120036

NAS-120036 / 22.12.1 / fix and improve enclosure disk slot mapping (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure.py

ES60 drive bay mapping wasn't working because it enumerates the drive directories named `Drive Slot #0_***`. After investigating this method, I've found that we're not doing it the best way and each new enclosure platform that we add will cause us the same grief since the drive directory names are dynamic and can be whatever the enclosure manufacturer decides.
I've changed this so that it should, in theory, always detect drives no matter what enclosure platform we add in the future (famous last words, I know).
Original PR: https://github.com/truenas/middleware/pull/10586
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120036

NAS-120036 / 22.12.2 / fix and improve enclosure disk slot mapping (by yocalebo)

---

src/middlewared/middlewared/alert/source/cores.py

This was a missed backport of 90063c37 to master.

NAS-120177 / 23.10 / ignore k3s.service core dumps

---

src/middlewared/middlewared/plugins/activedirectory_/dns.py
src/middlewared/middlewared/plugins/network_/dns.py
tests/api2/assets/REST/directory_services.py
tests/api2/test_030_activedirectory.py

* Fix trailing dot on ptr record string in DNS test
* Handle SERVFAIL while looking up netbiosname
* Fix formatting of messages to delete ptr records when
deleting multiple incorrect ones.
Original PR: https://github.com/truenas/middleware/pull/10631
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120193

NAS-120193 / 22.12.1 / Fix cleanup of DNS reverse zone (by anodos325)

---

src/middlewared/middlewared/plugins/vm/pci.py

PCI devices being shown in the UI are right now displaying the PCI device id which makes it difficult for users to determine what the actual device is. A description has been added to the choices output which UI can consume to show to the end user what the PCI device is about:
```
"description": "0000:22:00.0: NVMe SSD Controller SM961/PM961/SM963 by 'Samsung Electronics Co Ltd'",
```

NAS-120234 / 23.10 / Add pci passthrough device description

---

src/middlewared/middlewared/job.py
src/middlewared/middlewared/plugins/filesystem_/acl_base.py
src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
tests/api2/test_340_pool_dataset.py

This simplified API is for charts use to allow chart to specify uids / gids that need access to a given host path.
Original PR: https://github.com/truenas/middleware/pull/10633
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120190

NAS-120190 / 22.12.2 / Add simplified API for granting ids access to path (by anodos325)

---

src/middlewared/middlewared/plugins/chart_releases_linux/portals.py
src/middlewared/middlewared/plugins/chart_releases_linux/utils.py

This PR adds ability for users to define custom web portals along with https://github.com/truenas/catalog_validation/pull/33. This works in 2 layers:
1. App developer specifies that app in question can have custom web portals which results in a set of questions being presented to the user so he can add these portals.
2. User has been exposed with an option to define custom portals and if he/she desires can do that appropriately.
There are 2 cases for app developers where they might want to allow using custom portals. They are as respectively:
1. A valid case where app dev wants the user to define what aspect of app to expose ( based on other configuration he could have possible done )
2. App developer not wanting to specify portals in `questions.yaml` and using `ix_valyes.yaml` for …

NAS-119998 / 22.12.2 / Allow users to define custom portals (by sonicaj)

---

src/middlewared/middlewared/plugins/device_/device_info.py

This is added so that `device.get_disks` can return only block device names and serials which is significantly faster than enumerating all the detailed information for each disk. I will be opening a separate PR to make use of this new kwarg after this has been merged.

NAS-120315 / 23.10 / add serial_only kwarg to device.get_disks

---

src/middlewared/middlewared/plugins/device_/device_info.py

This is added so that `device.get_disks` can return only block device names and serials which is significantly faster than enumerating all the detailed information for each disk. I will be opening a separate PR to make use of this new kwarg after this has been merged.
Original PR: https://github.com/truenas/middleware/pull/10692
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120315

NAS-120315 / 22.12.2 / add serial_only kwarg to device.get_disks (by yocalebo)

---

src/middlewared/middlewared/plugins/failover.py

With the previous commit here: https://github.com/truenas/middleware/pull/10692, I've reduced the time it takes for `failover.mismatch_disks` to return by ~70.2%. (Tested it on an internal system with ~1.2k hard drives)

NAS-120324 / 23.10 / speed up failover.mismatch_disks

---

src/middlewared/middlewared/plugins/failover.py

With the previous commit here: https://github.com/truenas/middleware/pull/10692, I've reduced the time it takes for `failover.mismatch_disks` to return by ~70.2%. (Tested it on an internal system with ~1.2k hard drives)
Original PR: https://github.com/truenas/middleware/pull/10699
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120324

NAS-120324 / 22.12.2 / speed up failover.mismatch_disks (by yocalebo)

---

cluster-tests/init_gluster.py

This fixes cluster API pipeline

NAS-120345 / 23.10 / need to use IPs of cluster VMs

---

src/middlewared/middlewared/logger.py
src/middlewared/middlewared/logging/console_formatter.py

No functional change, just moving `LoggerFormatter` to its own file and renaming it to reflect reality.

NAS-120398 / 23.10 / More cleanup to logger.py

---

src/middlewared/middlewared/plugins/catalogs_linux/items.py

@sonicaj noticed an edge case when retrieving cached content from middleware for applications:
```
[2022/12/17 08:24:08] (ERROR) middlewared.job.run():438 - Job <bound method accepts.<locals>.wrap.<locals>.nf of <middlewared.plugins.catalogs_linux.items.CatalogService object at 0x7f5a44e66790>> failed
File "/usr/lib/python3/dist-packages/middlewared/job.py", line 426, in run
await self.future
File "/usr/lib/python3/dist-packages/middlewared/job.py", line 463, in __run_body
rv = await self.middleware.run_in_thread(self.method, *([self] + args))
File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1172, in run_in_thread
File …
```

Fix cache key edge case

---

src/middlewared/middlewared/plugins/bootenv.py

Invalid characters like `[` or `,` were not being caught by the regex we had in place for validating BE name and it resulted in the underlying tool `zectl` failing to create BE as zfs refused to create a dataset with the problematic characters.
BE name validation is the same as dataset name validation as a BE is just another dataset. We have a method in py-libzfs which performs the same checks as underlying libzfs and using that solves the problem of properly validating BE name.

NAS-120243 / 23.10 / Properly validate BE name

---

src/middlewared/middlewared/plugins/vm/supervisor/supervisor.py

For each VM specified in database we keep a list of VM objects throughout middleware lifecycle which is what interacts with libvirt. In each VM object we have a domain instance which is returned by the libvirt socket and consumed to perform actions for that specific VM.
If libvirt dies for whatever reason, we have logic in place which re-starts libvirt and re-initializes the libvirt connection but the domain object still points to the older libvirt socket which is no longer active.
Before consuming domain object make sure it is healthy and re-initialize otherwise as it is guaranteed at this point that libvirt is active and the socket connection is healthy.

NAS-120478 / 23.10 / Make sure domain object is active before consumption

---

src/middlewared/middlewared/plugins/truecommand/update.py

This PR adds changes to make sure that standby node marks itself as DISABLED as currently it was following the same logic as master node but it got out of sync quickly because of how status is handled. It is dependant on API actions and TC events but both of them are not valid on the standby node as the db is updated directly.

NAS-120484 / 13.0 / Mark truecommand service as disabled on standby node

---

src/middlewared/middlewared/plugins/vm/supervisor/supervisor.py

For each VM specified in database we keep a list of VM objects throughout middleware lifecycle which is what interacts with libvirt. In each VM object we have a domain instance which is returned by the libvirt socket and consumed to perform actions for that specific VM.
If libvirt dies for whatever reason, we have logic in place which re-starts libvirt and re-initializes the libvirt connection but the domain object still points to the older libvirt socket which is no longer active.
Before consuming domain object make sure it is healthy and re-initialize otherwise as it is guaranteed at this point that libvirt is active and the socket connection is healthy.
Original PR: https://github.com/truenas/middleware/pull/10737
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120478

NAS-120478 / 22.12.2 / Make sure domain object is active before consumption (by Qubad786)

---

src/middlewared/middlewared/plugins/catalogs_linux/sync_catalogs.py
src/middlewared/middlewared/plugins/kubernetes_linux/app_migrations.py
src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py

This PR adds changes to allow apps to be migrated from one train to another. The changes are limited to `OFFICIAL` catalog for now.

NAS-120522 / 23.10 / Allow apps to be migrated from one train to another

---

src/middlewared/middlewared/plugins/network.py

The docstring for this method is very descriptive on why this exists. However, when I added this I forgot to account for the fact that the first interface being created could be a "virtual" interface (i.e. vlan/lagg) which means there are entires in our `network_interfaces` table that are "empty". (i.e. they don't have ip addr/netmask info associated to them). This fixes that problem by simply catching `ValueError` (which is what is raised with `ipaddress` module) and continuing on.

NAS-120528 / 23.10 / fix setting default gateway on 1st iface creation

---

src/middlewared/middlewared/plugins/network.py

The docstring for this method is very descriptive on why this exists. However, when I added this I forgot to account for the fact that the first interface being created could be a "virtual" interface (i.e. vlan/lagg) which means there are entires in our `network_interfaces` table that are "empty". (i.e. they don't have ip addr/netmask info associated to them). This fixes that problem by simply catching `ValueError` (which is what is raised with `ipaddress` module) and continuing on.
Original PR: https://github.com/truenas/middleware/pull/10760
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120528

NAS-120528 / 22.12.2 / fix setting default gateway on 1st iface creation (by yocalebo)

---

tests/api2/test_022_catalog.py
tests/api2/test_025_chart_release.py

Many problems with these tests for which I've added a relevant docstring.

NAS-120549 / 23.10 / disable invalid api tests until they can be reviewed

---

src/middlewared/middlewared/plugins/catalogs_linux/items.py
src/middlewared/middlewared/plugins/catalogs_linux/sync_catalogs.py
src/middlewared/middlewared/plugins/catalogs_linux/update.py
src/middlewared/middlewared/plugins/catalogs_linux/utils.py
src/middlewared/middlewared/plugins/kubernetes_linux/restore.py
tests/api2/test_022_catalog.py

This PR adds changes to mark metadata file for all catalogs to be mandatory moving on in Cobia as the metadata file gives performance boost which is many times better then actually syncing the catalog itself in reality from middleware side.

NAS-120521 / 23.10 / Mark metadata file for all catalogs as mandatory

---

src/middlewared/middlewared/plugins/catalogs_linux/apps.py
src/middlewared/middlewared/plugins/catalogs_linux/items.py

This PR is for the UI team so that they have an endpoint which will provide them with all available apps from all configured catalogs.

NAS-120373 / 23.10 / Add endpoint to retrieve all available apps from all catalogs

---

src/middlewared/middlewared/plugins/disk_/availability.py

requested by webUI team for the new zpool creation redesign for Cobia. This adds another positional arg to the method to add the enclosure device and slot information for each unused disk.

NAS-120360 / 23.10 / add enclosure info to disk.get_unused

---

src/middlewared/middlewared/plugins/activedirectory_/dns.py

We should improve error message by stating exactly which SRV record is missing in the error message to better identify the nature of problem in AD domain. Since we're not submitting as a batch, reduce scope of requested SRV records to only kerberos and ldap. This is sufficient to identify horribly misconfigured DNS, and reduces number of DNS queries.

NAS-120568 / 23.10 / Improve error message for failed SRV lookup

---

src/middlewared/middlewared/plugins/activedirectory_/dns.py

We should improve error message by stating exactly which SRV record is missing in the error message to better identify the nature of problem in AD domain. Since we're not submitting as a batch, reduce scope of requested SRV records to only kerberos and ldap. This is sufficient to identify horribly misconfigured DNS, and reduces number of DNS queries.
Original PR: https://github.com/truenas/middleware/pull/10775
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120568

NAS-120568 / 22.12.2 / Improve error message for failed SRV lookup (by anodos325)

---

src/middlewared/middlewared/plugins/cloud_sync.py
tests/api2/test_130_cloudsync.py

(cherry picked from commit b545b888af0cb9ee336a74f521bf397b7d93d771)

NAS-120480 / 13.0 / Proper error when deleting used cloud sync credential

---

src/middlewared/middlewared/plugins/kerberos.py

We want to cancel the current running job.

NAS-120596 / 23.10 / Fix filter for kerberos renewal job

---

src/middlewared/middlewared/plugins/kerberos.py

We want to cancel the current running job.
Original PR: https://github.com/truenas/middleware/pull/10789
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120596

NAS-120596 / 22.12.2 / Fix filter for kerberos renewal job (by anodos325)

---

src/middlewared/middlewared/restful.py

Due to the logic in `OpenAPIResource._accepts_to_request`, if a route took exactly 1 schema, it would have the schema suffixed with `_0`, e.g. for interface.create it would be `interface_create_0`. This suffix isn't necessary, so removing it to make the interface cleaner.
NOTE: This is only changing the schema **$ref** name/path, the `_name_` and `title` params within the schema were always correct.
Before:
After:
This may seem trivial, but will help projects which use the API schemas like [truenas-go-sdk](https://github.com/dariusbakunas/truenas-go-sdk).
Here's the old/new API docs (generated on top of https://github.com/truenas/middleware/pull/10747, although this PR is independent of that one):
[before-10748.txt](https://github.com/truenas/middleware/files/10835207/before-10748.txt) …

dropped superfluous _0 suffix from some openapi schemas

---

src/middlewared/middlewared/plugins/smb_/status.py

Upstream changed output format for JSON variant of smbstatus. This PR basically returns us back to where we were in core / angelfish.
Original PR: https://github.com/truenas/middleware/pull/10803
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120632

NAS-120632 / 22.12.2 / Normalize smbstatus output (by anodos325)

---

src/middlewared/middlewared/etc_files/local/sudoers.mako

…ccount
Original PR: https://github.com/truenas/middleware/pull/10800
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120623

NAS-120623 / 22.12.2 / Only have one sudoers file entry as only the last one is taken into a… (by themylogin)

---

src/middlewared/middlewared/test/integration/assets/ftp.py

Original FTP test assets worked around the fact that we neglected to create an ftp group by creating it on the fly. Now that we have an ftp group (for FreeBSD / Core compatibility) we should use that in our tests.

NAS-120687 / 23.10 / Fix test asset for FTP group

---

src/middlewared/middlewared/test/integration/assets/ftp.py

Original FTP test assets worked around the fact that we neglected to create an ftp group by creating it on the fly. Now that we have an ftp group (for FreeBSD / Core compatibility) we should use that in our tests.
Original PR: https://github.com/truenas/middleware/pull/10829
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120687

NAS-120687 / 22.12.2 / Fix test asset for FTP group (by anodos325)

---

src/middlewared/middlewared/plugins/smb.py
tests/api2/test_430_smb_sharesec.py

During registry synchronization we may have to remove shares if they are disabled. The standard tools for removing a share from samba's registry via libsmbconf also automatically remove the share's ACL. We work around this in normal situations in our share CRUD methods, but if for some reason these methods are bypassed, then the share ACL may be inadvertently deleted when we catch a share that shouldn't exist during registry synchronization.
This PR adds detection for shares that exist on the system but are inactive and in this case toggles the share ACL before removal from registry.
CI test is added that uses datastore plugin directly to simulate the CRUD methods being bypassed.

NAS-120571 / 23.10 / Ensure that share ACL is preserved

---

src/middlewared/middlewared/plugins/smb.py
tests/api2/test_430_smb_sharesec.py

During registry synchronization we may have to remove shares if they are disabled. The standard tools for removing a share from samba's registry via libsmbconf also automatically remove the share's ACL. We work around this in normal situations in our share CRUD methods, but if for some reason these methods are bypassed, then the share ACL may be inadvertently deleted when we catch a share that shouldn't exist during registry synchronization.
This PR adds detection for shares that exist on the system but are inactive and in this case toggles the share ACL before removal from registry.
CI test is added that uses datastore plugin directly to simulate the CRUD methods being bypassed.
Original PR: https://github.com/truenas/middleware/pull/10845
Jira URL: …

NAS-120571 / 22.12.2 / Ensure that share ACL is preserved (by anodos325)

---

src/middlewared/middlewared/main.py

Noticed when I was troubleshooting an unrelated issue. I often do `systemctl restart middlewared`. This can finish before a `ws.prepare(request)` returns. When this happens, a `ConnectionRefusedError` is raised and looks pretty nasty in the logs. This PR accounts for this scenario.

NAS-121028 / 23.10 / add create_and_prepare_ws()

---

src/middlewared/middlewared/plugins/disk_/sync.py

Troubleshooting, yet another, unrelated ticket I saw this method spam log files unnecessarily. In this particular scenario, I created the 1st zpool on an HA system and, by design, the standby controller is rebooted. However, the reboot is happening before `disk.sync_all` takes place so it spams log with unnecessary, scary, errors.

prevent more unnecessary log spam in disk.sync_all

---

src/middlewared/middlewared/plugins/disk_/sync.py

Troubleshooting, yet another, unrelated ticket I saw this method spam log files unnecessarily. In this particular scenario, I created the 1st zpool on an HA system and, by design, the standby controller is rebooted. However, the reboot is happening before `disk.sync_all` takes place so it spams log with unnecessary, scary, errors.
Original PR: https://github.com/truenas/middleware/pull/10872
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121044

NAS-121044 / 22.12.2 / prevent more unnecessary log spam in disk.sync_all (by yocalebo)

---

src/middlewared/middlewared/plugins/disk_/sync.py

Troubleshooting, yet another, unrelated ticket I saw this method spam log files unnecessarily. In this particular scenario, I created the 1st zpool on an HA system and, by design, the standby controller is rebooted. However, the reboot is happening before `disk.sync_all` takes place so it spams log with unnecessary, scary, errors.
Original PR: https://github.com/truenas/middleware/pull/10872
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121044

NAS-121044 / 22.12.3 / prevent more unnecessary log spam in disk.sync_all (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/fenced.py

Troubleshooting an unrelated problem, I noticed a race condition with how we're managing sending signals and getting information from fenced process. This fixes both scenarios.

NAS-121067 / 23.10 / fix time of check, time of use race fenced plugin

---

src/middlewared/middlewared/plugins/failover_/fenced.py

Troubleshooting an unrelated problem, I noticed a race condition with how we're managing sending signals and getting information from fenced process. This fixes both scenarios.
Original PR: https://github.com/truenas/middleware/pull/10885
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121067

NAS-121067 / 22.12.2 / fix time of check, time of use race fenced plugin (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/fenced.py

Troubleshooting an unrelated problem, I noticed a race condition with how we're managing sending signals and getting information from fenced process. This fixes both scenarios.
Original PR: https://github.com/truenas/middleware/pull/10885
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121067

NAS-121067 / 22.12.3 / fix time of check, time of use race fenced plugin (by yocalebo)

---

src/freenas/usr/local/libexec/freenas-debug/system/system.sh

NAS-121073 / 23.10 / Add zectl to debug file

---

src/freenas/usr/local/libexec/freenas-debug/system/system.sh

Requested by Support
Original PR: https://github.com/truenas/middleware/pull/10891
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121073

NAS-121073 / 22.12.2 / Add zectl to debug file (by william-gr)

---

src/freenas/usr/local/libexec/freenas-debug/system/system.sh

Requested by Support
Original PR: https://github.com/truenas/middleware/pull/10891
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121073

NAS-121073 / 22.12.3 / Add zectl to debug file (by william-gr)

---

src/middlewared/middlewared/alert/source/cores.py

Based on feedback from the documentation team.

NAS-120955 / 23.10 / improve core file alert verbiage

---

src/middlewared/middlewared/alert/source/cores.py

Based on feedback from the documentation team.
Original PR: https://github.com/truenas/middleware/pull/10915
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120955

NAS-120955 / 22.12.3 / improve core file alert verbiage (by yocalebo)

---

tests/runtest.py

Add `--tests` parameter to _runtest.py_ and enable the previously ignored `-k` parameter.
This will retain existing functionality and permit selection of a subset of tests by a couple of different means when being used locally.
For example, individual tests may be (comma-separated) specified by _filename::testname_ using `--tests`:
```
./runtest.py  -v --ip <IPADDRESS> --interface <INTERFACE> --password <PASSWORD> --ha --pool <POOL> \
--tests api2/test_001_iscsi.py::test_00_set_pool_04,api2/test_001_iscsi.py::test_06_test_ssh,api2/test_261_iscsi_cmd.py::test_00_setup \
--tests api2/test_261_iscsi_cmd.py::test_16_alua_config,api2/test_261_iscsi_cmd.py::test_99_teardown
```
or `--tests` can be used to specify the files and `-k` can cherry-pick the tests to run.  (See `pytest --help` for …

NAS-121127 / 23.10 / Add --tests parameter to runtest.py

---

src/middlewared/middlewared/plugins/failover_/event.py

When both controllers boot at roughly the same time, initial VRRP config causes the controller to come up into BACKUP state. Our HA logic will process 1 failover event atomically (by design). This means, we start to process a BACKUP event but the controller that is eventually to become the MASTER controller gets ignored because the original BACKUP event hasn't finished. This logic (for ignoring failover events) was added because of run time problems we've seen in the wild. (i.e. an interface "flaps" rapidly and triggers a slew of failover events. We, obviously, don't want to failover back and forth in this scenario).

NAS-121090 / 23.10 / fix HA events on initial power on

---

src/middlewared/middlewared/plugins/failover_/event.py

When both controllers boot at roughly the same time, initial VRRP config causes the controller to come up into BACKUP state. Our HA logic will process 1 failover event atomically (by design). This means, we start to process a BACKUP event but the controller that is eventually to become the MASTER controller gets ignored because the original BACKUP event hasn't finished. This logic (for ignoring failover events) was added because of run time problems we've seen in the wild. (i.e. an interface "flaps" rapidly and triggers a slew of failover events. We, obviously, don't want to failover back and forth in this scenario).
Original PR: https://github.com/truenas/middleware/pull/10902
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121090

NAS-121090 / 22.12.3 / fix HA events on initial power on (by yocalebo)

---

src/middlewared/middlewared/plugins/failover_/event.py

When both controllers boot at roughly the same time, initial VRRP config causes the controller to come up into BACKUP state. Our HA logic will process 1 failover event atomically (by design). This means, we start to process a BACKUP event but the controller that is eventually to become the MASTER controller gets ignored because the original BACKUP event hasn't finished. This logic (for ignoring failover events) was added because of run time problems we've seen in the wild. (i.e. an interface "flaps" rapidly and triggers a slew of failover events. We, obviously, don't want to failover back and forth in this scenario).
Original PR: https://github.com/truenas/middleware/pull/10902
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121090

NAS-121090 / 22.12.2 / fix HA events on initial power on (by yocalebo)

---

src/freenas/usr/local/lib/middlewared_truenas/plugins/truenas.py

This fixes the primary problem where this method didn't account for legacy minis that were tagged in SMBIOS with `FREENAS-MINI`. While I'm here, clean it up to match what we do in scale.

NAS-120976 / 13.0 / fix truenas.get_chassis_hardware

---

src/middlewared/middlewared/plugins/kubernetes_linux/restore.py
src/middlewared/middlewared/plugins/kubernetes_linux/yaml.py

Co-authoried-by: Jay Looney <jay.m.looney@gmail.com>
Original PR: https://github.com/truenas/middleware/pull/10904
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120458

NAS-120458 / 22.12.3 / Fix older kubernetes backups not restoring (by sonicaj)

---

src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py

Spoke with hardware platform team about this because, apparently, we were missing nvdimm types as well as incorrectly identifying others.

NAS-121148 / 23.10 / fix mseries.nvdimm.info

---

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py

Dependent on changes in PR: https://github.com/truenas/middleware/pull/10956

NAS-121147 / 23.10 / fix nvdimm alerts

---

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py

Dependent on changes in PR: https://github.com/truenas/middleware/pull/10956
Original PR: https://github.com/truenas/middleware/pull/10958
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121147

NAS-121147 / 22.12.2 / fix nvdimm alerts (by yocalebo)

---

src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py

Dependent on changes in PR: https://github.com/truenas/middleware/pull/10956
Original PR: https://github.com/truenas/middleware/pull/10958
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121147

NAS-121147 / 22.12.3 / fix nvdimm alerts (by yocalebo)

---

tests/api2/test_025_chart_release.py
tests/api2/test_026_kubernetes_backup_chart_releases.py

and in  kubernetes backup chart release api test

TE-370 / 22.12.2 / Changed ipfs train to community in chart release api test

---

tests/api2/test_025_chart_release.py
tests/api2/test_026_kubernetes_backup_chart_releases.py

and kubernetes backup chart release api test

TE-370 / 22.12.3 / Changed ipfs train to community in chart release api test

---

tests/api2/test_025_chart_release.py

Keeping this for future reference when App API test will be rework.

TE-373 / 22.12.2 / Comment out chart_release test_21 and related tests

---

tests/api2/test_025_chart_release.py

Keeping this for future reference when App API test will be rework.
(cherry picked from commit 49bffffc59e7bafb06cb64d5a4fa511b09cfebab)

TE-373 / 22.12.3 / Comment out chart_release test_21 and related tests

---

src/middlewared/middlewared/plugins/service_/on_config_upload.py

(cherry picked from commit bccbc2aedf46e0829456e50ef491a5805717948d)

NAS-121216 / 22.12.2 / properly enable/disable systemd units (#10985)

---

src/middlewared/middlewared/plugins/keychain.py
tests/api2/test_keychain_ssh.py

…_setup`
Original PR: https://github.com/truenas/middleware/pull/11016
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121203

NAS-121203 / 22.12.2 / Better error message for `keychaincredential.remote_ssh_semiautomatic… (by themylogin)

---

src/middlewared/middlewared/plugins/keychain.py
tests/api2/test_keychain_ssh.py

…_setup`
Original PR: https://github.com/truenas/middleware/pull/11016
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121203

NAS-121203 / 22.12.3 / Better error message for `keychaincredential.remote_ssh_semiautomatic… (by themylogin)

---

src/middlewared/middlewared/plugins/nfs.py
src/middlewared/middlewared/pytest/unit/plugins/test_nfs.py
tests/api2/test_300_nfs.py

Updated validation checks:
* Allow sharing unrelated directories
* Prevent sharing related directories to 'same' hosts

NAS-120957 / 23.10 / Update NFS /etc/exports validations

---

src/middlewared/middlewared/plugins/catalogs_linux/apps.py
src/middlewared/middlewared/plugins/catalogs_linux/items.py

It was requested that we provide an endpoint to retrieve latest updated apps. Meanwhile i have normalised `last_update` attribute to be a datetime object and not a date string keeping consistency with how we handle dates in middleware in other places.

NAS-120625 / 23.10 / Endpoint to get updated apps

---

src/middlewared/middlewared/plugins/account_/sync_builtin.py
src/middlewared/middlewared/plugins/auth.py
tests/api2/test_twofactor_auth.py

```
api2/test_twofactor_auth.py ......                                                                                      [100%]
------------------------------- generated xml file: /root/tests/results/api_v2_tests_result.xml -------------------------------
===================================================== 6 passed in 14.66s ======================================================
Warning: Permanently added '192.168.0.146' (ECDSA) to the list of known hosts.
```

NAS-121332 / 23.10 / Fix 2FA tests

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/idmap.py

This simplifies logic significantly related to trusted domains. If user enables this option, don't try to auto-detect working settings. Instead we'll raise a verbose validation error message if user hasn't properly configured their idmap settings.

NAS-121388 / 23.10 / Remove trusted domain auto-detection

---

src/middlewared/middlewared/plugins/activedirectory.py
src/middlewared/middlewared/plugins/idmap.py

This simplifies logic significantly related to trusted domains. If user enables this option, don't try to auto-detect working settings. Instead we'll raise a verbose validation error message if user hasn't properly configured their idmap settings.
Original PR: https://github.com/truenas/middleware/pull/11076
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121388

NAS-121388 / 22.12.3 / Remove trusted domain auto-detection (by anodos325)

---

src/middlewared/middlewared/scripts/ctdb_events.py

FS operations on cluster metadata files via the glusterfs fuse mount will fail with ENOTCONN if the mountpoint is unhealthy. Catch this and convert into event to pass to middleware for alerting in TC.

NAS-121271 / 23.10 / Improve ENOTCONN handling for cluster events

---

src/middlewared/middlewared/scripts/ctdb_events.py

FS operations on cluster metadata files via the glusterfs fuse mount will fail with ENOTCONN if the mountpoint is unhealthy. Catch this and convert into event to pass to middleware for alerting in TC.
Original PR: https://github.com/truenas/middleware/pull/11031
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121271

NAS-121271 / 22.12.3 / Improve ENOTCONN handling for cluster events (by anodos325)

---

src/middlewared/middlewared/plugins/idmap.py

libwbclient supports bulk conversion of SIDs to uids and gids. When I wrote python bindings for this I added this support but didn't expose API through middleware. This commit exposes via private interface as significant optimization for times we need bulk results.

NAS-121412 / 23.10 / Add bulk sid conversion endpoint

---

src/middlewared/middlewared/plugins/idmap.py

libwbclient supports bulk conversion of SIDs to uids and gids. When I wrote python bindings for this I added this support but didn't expose API through middleware. This commit exposes via private interface as significant optimization for times we need bulk results.
Original PR: https://github.com/truenas/middleware/pull/11086
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121412

NAS-121412 / 22.12.3 / Add bulk sid conversion endpoint (by anodos325)

---

tests/protocols/iSNSP/client.py
tests/protocols/iSNSP/packet.py

Does a better job of handling partial socket `send`/`recv`.
Furthermore, will properly detect a closed socket.

NAS-121425 / 23.10 / Robustize sending and receiving iSNS packets

---

cluster-tests/tests/filesystem/test_002_glusterfs_filesystem_plugin.py
src/middlewared/middlewared/plugins/gluster_linux/filesystem.py

This method uses a temporary glusterfs filesystem handle to recursively remove all items in specified path.

NAS-121526 / 23.10 / Add rmtree method for glusterfs plugin

---

cluster-tests/tests/filesystem/test_002_glusterfs_filesystem_plugin.py
src/middlewared/middlewared/plugins/gluster_linux/filesystem.py

This method uses a temporary glusterfs filesystem handle to recursively remove all items in specified path.
Original PR: https://github.com/truenas/middleware/pull/11117
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121526

NAS-121526 / 22.12.3 / Add rmtree method for glusterfs plugin (by anodos325)

---

src/middlewared/middlewared/plugins/system/product.py

Clean this up while I'm here. I'm investigating an unrelated issue but had to look here.

NAS-121574 / 23.10 / Improve license endpoints

---

src/middlewared/middlewared/plugins/system/product.py

Clean this up while I'm here. I'm investigating an unrelated issue but had to look here.
Original PR: https://github.com/truenas/middleware/pull/11134
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121574

NAS-121574 / 22.12.3 / Improve license endpoints (by yocalebo)

---

src/freenas/usr/lib/modprobe.d/truenas.conf

Ticket: [NAS-121406](https://ixsystems.atlassian.net/browse/NAS-121406).
[NAS-121406]: https://ixsystems.atlassian.net/browse/NAS-121406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Original PR: https://github.com/truenas/middleware/pull/11145
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121406

NAS-121406 / 22.12.3 / Update zfs indirect block size to 15 (by ixhamza)

---

src/middlewared/middlewared/plugins/zfs_/pool.py
src/middlewared/middlewared/plugins/zfs_/pool_actions.py
src/middlewared/middlewared/plugins/zfs_/zfs_events.py

See https://github.com/truenas/py-libzfs/pull/232 for details

NAS-121658 / 23.10 / fix py3.11 compatibility by calling new method

---

src/middlewared/middlewared/plugins/disk_/sync.py
src/middlewared/middlewared/plugins/disk_/zfs_guid.py
src/middlewared/middlewared/plugins/failover_/event.py

… to disk names and disk names to ZFS guids simultaneously
Original PR: https://github.com/truenas/middleware/pull/11200
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121480

NAS-121480 / 22.12.3 / Fix race condition when trying to change mappings of disk identifiers… (by themylogin)

---

src/middlewared/middlewared/plugins/activedirectory.py

This PR fixes some bugs brought into refactored backport from SCALE.

NAS-121538 / 13.0 / Fix active directory join on fresh install

---

src/middlewared/middlewared/plugins/catalogs_linux/apps.py

UI requested that an endpoint be provided which provides apps similar to the one in question.
Here we take list of categories and tags and do a match to locate similar apps.

NAS-121562 / 23.10 / Add endpoint to retrieve similar apps

---

src/middlewared/middlewared/plugins/activedirectory.py

Fixes for SEE-related ticket where support engineer was deliberately breaking AD by deleting kerberos settings while we were joined to AD caused a regression in activedirectory plugin.

NAS-121804 / 13.0 / Fix activedirectory.leave endpoint

---

src/middlewared/middlewared/plugins/usage.py

This plugin has clearly been neglected. It's using an absurd amount of memory (depending on size of system) as well as doing a whole bunch of duplicated api calls.
This removes the very obvious problem of querying all zfs properties recursively for every zfs dataset on the system (3 separate times) and instead only queries the properties that we're after and only does it once. Finally, this passes the `snapshots_count` extra arg to zfs.dataset.query so we can remove a `zfs.snapshot.query` call which can be extremely brutal.
Fixes implemented:
- only query zfs properties we're after
- use snapshots_count to populate the total snapshots in same for loop removing a zfs.snapshot.query call
- remove a 2 more zfs.dataset.query calls
This plugin is still miserable in certain areas but this is a …

NAS-121811 / 22.12.3 / stop getting all zfs props recursively (by yocalebo)

---

src/middlewared/middlewared/plugins/usage.py

Remove osc module from this plugin since it's not needed.

NAS-121812 / 23.10 / remove osc module from usage.py plugin

---

src/middlewared/middlewared/plugins/usage.py

- inner functions incur a non-trivial amount of overhead and there is almost 0 reason to use them
- simplify this for loop dramatically so we only iterate network interfaces once (instead of 4 times)

NAS-121813 / 23.10 / simplify and speed up gather_network() in usage.py

---

src/middlewared/middlewared/plugins/usage.py

- inner functions incur a non-trivial amount of overhead and there is almost 0 reason to use them
- simplify this for loop dramatically so we only iterate network interfaces once (instead of 4 times)
Original PR: https://github.com/truenas/middleware/pull/11229
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121813

NAS-121813 / 22.12.3 / simplify and speed up gather_network() in usage.py (by yocalebo)

---

src/middlewared/middlewared/plugins/usage.py

Instead of doing a raw capacity key for each pool, this adds another top-level key "total_raw_capacity" which matches the other top-level key "total_capacity" that we do for zfs list output.

NAS-121817 / 23.10 / add top-level key "total_raw_capacity" to usage.py

---

src/middlewared/middlewared/plugins/usage.py

Instead of doing a raw capacity key for each pool, this adds another top-level key "total_raw_capacity" which matches the other top-level key "total_capacity" that we do for zfs list output.
Original PR: https://github.com/truenas/middleware/pull/11234
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121817

NAS-121817 / 22.12.3 / add top-level key "total_raw_capacity" to usage.py (by yocalebo)

---

src/middlewared/middlewared/plugins/usage.py

- remove unnecessary inner function in `gather_services()`
- simplify `gather_vms()`
- remove unnecessary newlines
There should be no difference in functionality.

NAS-121821 / 23.10 / further improvements to usage.py

---

src/middlewared/middlewared/plugins/usage.py

- remove unnecessary inner function in `gather_services()`
- simplify `gather_vms()`
- remove unnecessary newlines
There should be no difference in functionality.
Original PR: https://github.com/truenas/middleware/pull/11236
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121821

NAS-121821 / 22.12.3 / further improvements to usage.py (by yocalebo)

---

src/middlewared/middlewared/plugins/usage.py

Inside gather_filesystem_usage() we were iterating over the root datasets and zvols and calculating the size (again?). Instead do it when we're querying the datasets and create an appropriate key in the context variable that gets passed around to the various methods.
Original PR: https://github.com/truenas/middleware/pull/11239
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121823

NAS-121823 / 22.12.3 / optimize gather_filesystem_usage() in usage.py (by yocalebo)

---

tests/protocols/nfs_proto.py

This module had many linting problems.
Most of the issues were related to using '==' instead of 'is'. Some extra or missing spaces.
Also improved the robustness of the mkdir calls and added return checking.

NAS-121837 / 23.10 / Cleanup Flake8 errors in tests/protocols/nfs_proto.py

---

src/middlewared/middlewared/plugins/ipmi_/sel.py

These are called in an alert, but this will produce log spam if there is no ipmi kernel module loaded. Prevent that from happening by checking if we have an ipmi device available.

NAS-121846 / 23.10 / fix ipmi-sel log spam

---

src/middlewared/middlewared/plugins/ipmi_/sel.py

These are called in an alert, but this will produce log spam if there is no ipmi kernel module loaded. Prevent that from happening by checking if we have an ipmi device available.
Original PR: https://github.com/truenas/middleware/pull/11249
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121846

NAS-121846 / 22.12.3 / fix ipmi-sel log spam (by yocalebo)

---

src/freenas/usr/local/lib/middlewared_truenas/alert/source/enclosure_status.py

Enclosure elements can "flap" (i.e. report a bad status but then be cleared almost immediately). The alert that is flapping is a particular problem in and of itself. However, this fixes the scenario so that we wait a bit before we raise an alert to the end-user.

NAS-121881 / 13.0 / Fix flapping enclosure alerts

---

src/middlewared/middlewared/plugins/catalogs_linux/apps.py
src/middlewared/middlewared/plugins/catalogs_linux/item_version.py
src/middlewared/middlewared/plugins/catalogs_linux/items.py

Add `sources` field to cached catalog items file so it can be consumed by UI team in new apps UI.

NAS-121855 / 23.10 / Update returns schema example for catalog items

---

src/middlewared/middlewared/plugins/account.py

Missing "await" for this coroutine so it's never being scheduled to be executed as a task.

NAS-121924 / 23.10 / fix un-awaited coroutine in account.py

---

src/middlewared/middlewared/plugins/nfs_/debug.py
tests/api2/test_300_nfs.py

The goal was to enhance the existing tests and to fix any issues that were exposed.
* Fixed nfs_/debug.py as it was not functioning as expected
* Enhanced behavior testing in test_300_nfs.py
- Added client testing where possible
- Added independent verification of setting changes where possible

Improve nfs CI and other nfs fixes

---

tests/protocols/nfs_proto.py

Output from nfs4getfacl changed with bookworm update.

NAS-121956 / 23.10 / Fix NFS proto test

---

src/middlewared/middlewared/plugins/catalogs_linux/apps.py

This commit fixes an issue where we were displaying all apps and not taking into account preferred trains apps only.

NAS-121842 / 23.10 / Only show those apps which are in preferred trains

---

src/freenas/usr/bin/install-dev-tools

See https://github.com/truenas/scale-build/pull/418 for details.

NAS-121741 / 23.10 / add execute bit back to dpkg in dev tools script

---

src/freenas/usr/bin/install-dev-tools

See https://github.com/truenas/scale-build/pull/418 for details.
Original PR: https://github.com/truenas/middleware/pull/11307
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121741

NAS-121741 / 22.12.3 / add execute bit back to dpkg in dev tools script (by yocalebo)

---

src/middlewared/middlewared/plugins/pool_/dataset_details.py

This PR addresses an issue where a user reported encrypted properties were not being correctly reported in the UI which on investigation i found that we were first building a mapping of all datasets and then performing an additional loop to normalize the dataset which was redundant and we were making some mistake with the references of the objects being maintained which resulted in the dataset not properly reflecting it's normalized properties.
I have not investigated the actual reference issue but just not maintaining that mapping and normalizing in one iteration fixes the issue reasonably.
Left one outlines the one without fix and the right one with the fix.
Original PR: https://github.com/truenas/middleware/pull/11210
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120096

NAS-120096 / 22.12.3 / Fix normalization of datasets  (by sonicaj)

---

src/middlewared/middlewared/plugins/catalogs_linux/apps.py
src/middlewared/middlewared/plugins/catalogs_linux/item_version.py
src/middlewared/middlewared/plugins/catalogs_linux/items.py

`screenshots` field has been added to available apps as requested by the UI team so it can be consumed in the new Apps UI redesign.

NAS-121709 / 23.10 / Update returns schema example for catalog items

---

tests/api2/test_261_iscsi_cmd.py
tests/protocols/__init__.py
tests/protocols/iscsi_proto.py

Now that SCST has been updated to check initiator name upon LOGIN, add a unit test.

NAS-121743 / 23.10 / NAS-121743

---

src/middlewared/middlewared/plugins/enclosure_/nvme.py
src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/failover_/detect_enclosure.py
src/middlewared/middlewared/plugins/failover_/internal_interface.py
src/middlewared/middlewared/plugins/truenas.py

This adds logic to properly detect the F1 HA product type. NOTE: this does not add the drive bay identification logic (that will come in another PR)

NAS-121259 / 23.10 / add F1 product detection

---

src/middlewared/middlewared/plugins/ipmi_/mc.py

Add an `ipmi.mc` plugin. This isn't used (yet).

NAS-122023 / 23.10 / add ipmi.mc plugin

---

src/middlewared/middlewared/plugins/ipmi_/mc.py

Add an `ipmi.mc` plugin. This isn't used (yet).
Original PR: https://github.com/truenas/middleware/pull/11334
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122023

NAS-122023 / 22.12.3 / add ipmi.mc plugin (by yocalebo)

---

src/middlewared/middlewared/plugins/account.py

We need to wait for the chown job to finish

NAS-122025 / 23.10 / Fix API test failure for user creation

---

src/middlewared/middlewared/plugins/failover_/internal_interface.py
src/middlewared/middlewared/plugins/network.py

The F1 HA platform is an AMD system. This means it's using a different driver for the ntb heartbeat interface (AMD vs Intel). The AMD ntb driver operates subtly different than the Intel driver. If the A controller is rebooted, the B controllers ntb0 interface is hot-plugged (i.e. removed). When the A controller comes back online, the ntb0 interface is hot-plugged (i.e. added). For this platform we need to re-add the ip address on hot-plug add event.

NAS-122005 / 23.10 / properly handle ntb0 iface on F1 HA platform

---

src/middlewared/middlewared/plugins/pool.py

git cherry-pick -x 818bf1f27202211b5e015e5b86009d272d9ca380
git cherry-pick -x 2253c495618f67dd049f86cfbfe04a386700ec62
…rub datetime
Original PR: https://github.com/truenas/middleware/pull/11329
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121816

NAS-121816 / 22.12.3 / Also account for pylibzfs-initialed scrubs when checking last pool sc… (by themylogin)

---

src/middlewared/middlewared/plugins/pool_/dataset_encryption_lock.py

(might be erroneously set previously)

NAS-121907 / 23.10 / Remove immutable flag after mounting unlocked dataset too

---

src/middlewared/middlewared/plugins/ipmi_/lan.py

The original code works well on systems with BMC devices that have multiple lan channels. However, this would return empty on BMC devices with 1 lan channel. This uses the `bmc-info --get-channel-info` command which gives us an easier (and faster) way to get the available lan channels. This fixes it so that `ipmi.lan.query` returns properly on single lan channel BMC devices.

NAS-122064 / 23.10 / use bmc-info --get-channel-info to fix ipmi.lan.query

---

tests/api2/test_420_smb.py

This has now been fixed in smbtorture suite.

NAS-121353 / 23.10 / Re-enable local.replace torture test

---

tests/api2/test_261_iscsi_cmd.py

This _allows_ the iSCSI tests to support raw sense data offered by `cython-iscsi` & `python-scsi`, but does **not** require it.
(This PR is for stable/bluefin only as the mechanism already exists in Cobia/master as part of a larger change.)

NAS-122106 / 22.12.3 / Allow iSCSI tests to support raw sense data

---

src/middlewared/middlewared/plugins/account.py

This avoids having log spam when we know AD or LDAP is unhealthy and avoids failures further down the line when API user tries to actually use the returned information for something.

NAS-122110 / 23.10 / skip cache lookup if directory services unhealthy

---

src/middlewared/middlewared/alert/source/deprecated_service.py

This improves the verbiage for the deprecated service alert in Bluefin. With guidance from technical documentation team.

NAS-122140 / 22.12.3 / improve verbiage for deprecated service alert

---

src/freenas/usr/local/bin/truenas-initrd.py

We were using product/vendor id to isolate GPUs which caused a problem when identical GPUs were present in the system. What happened in that case is that the product/vendor id is same for identical GPUs and it results in all the identical GPUs being isolated.
Wrote a short script which explicitly consume the pci slots address and add a driver override for `vfio-pci` so that it is the only one consumed. Following is an output showing one of the identical GPUs being properly isolated from the host(you can check from the `Kernel driver in use` attribute):
```
03:00.0 VGA compatible controller [0300]: ASPEED Technology, Inc. ASPEED Graphics Family [1a03:2000] (rev 41)
DeviceName: ASPEED Video AST2500
Subsystem: Super Micro Computer Inc ASPEED Graphics Family [15d9:095d]
Kernel driver in use: …
```

NAS-117915 / 23.10 / Solve identical gpu passthrough problem

---

src/middlewared/middlewared/plugins/gluster_linux/local_events.py
src/middlewared/middlewared/webhooks/cluster_events.py

Updating to bookworm caused library version bump to a version where API had been changed.

NAS-122156 / 23.10 / fix python-jwt usage

---

src/middlewared/middlewared/scripts/wait_to_hang_and_dump_core.py

No git commit message and ticket was empty. Write the intentions of what this script is expected to do in the actual script so it's easily obtained for future developers.

NAS-122228 / 23.10 / add docstring to wait_to_hang_and_dump_core script

---

tests/api2/test_050_alert.py

- the core dump alert is targeted at the "critical" sharing services (PR here: https://github.com/truenas/middleware/pull/11258)
- these alerts are named incorrectly because they were testing python core dumps and not smbd
Remove these and we can revisit adding them back at a later time (maybe targeting smbd since it's a user-space process (like we were originally doing)).

NAS-122218 / 23.10 / remove unnecessary core dump alert api tests

---

src/middlewared/middlewared/scripts/wait_to_hang_and_dump_core.py

No git commit message and ticket was empty. Write the intentions of what this script is expected to do in the actual script so it's easily obtained for future developers.
Original PR: https://github.com/truenas/middleware/pull/11415
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122228

NAS-122228 / 22.12.4 / add docstring to wait_to_hang_and_dump_core script (by yocalebo)

---

tests/api2/test_050_alert.py

- the core dump alert is targeted at the "critical" sharing services (PR here: https://github.com/truenas/middleware/pull/11258)
- these alerts are named incorrectly because they were testing python core dumps and not smbd
Remove these and we can revisit adding them back at a later time (maybe targeting smbd since it's a user-space process (like we were originally doing)).
Original PR: https://github.com/truenas/middleware/pull/11414
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122218

NAS-122218 / 22.12.3 / remove unnecessary core dump alert api tests (by yocalebo)

---

tests/api2/test_050_alert.py

- the core dump alert is targeted at the "critical" sharing services (PR here: https://github.com/truenas/middleware/pull/11258)
- these alerts are named incorrectly because they were testing python core dumps and not smbd
Remove these and we can revisit adding them back at a later time (maybe targeting smbd since it's a user-space process (like we were originally doing)).
Original PR: https://github.com/truenas/middleware/pull/11414
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122218

NAS-122218 / 22.12.4 / remove unnecessary core dump alert api tests (by yocalebo)

---

tests/api2/test_022_catalog.py
tests/api2/test_025_chart_release.py

TRUECHARTS is wrong since it is not TrueChart.

TE-629 / 22.12.3 / Fixed TRUENAS catalog and replace TRUECHARTS by CUSTOMCHART

---

tests/api2/test_022_catalog.py

TRUECHARTS is wrong since it is not TrueChart.
(cherry picked from commit 2b08676ea9379fcdc511c63d5eb8730d17888ec2)

TE-629 / 22.12.4 / Fixed TRUENAS catalog and replace TRUECHARTS by CUSTOMCHART

---

src/middlewared/middlewared/plugins/ldap.py
src/middlewared/middlewared/plugins/ldap_/ldap_client.py

This somewhat cleans up the middleware LDAP client and also refactors to place LDAP client operations under a single LDAP client lock.

NAS-122260 / 23.10 / shift python ldap usage to separate file

---

tests/api2/test_560_webdav.py

(cherry picked from commit a0365976ba8c47f6b0b1654b7f4396c4b63709b6)

TE-654 / 22.12.3 / Changed the webdav test to verify webdav is deprecated.

---

src/middlewared/middlewared/plugins/activedirectory.py

For quite some time already we don't need the AD bindpw stored in our sqlite database. Pop it out of config dict before insertion in activedirectory.update (after we've performed kinit to get kerberos ticket as admin).

NAS-122344 / 23.10 / Rely exclusively on kerberos tickets for AD ops

---

src/middlewared/middlewared/plugins/idmap.py
src/middlewared/middlewared/plugins/smb.py
tests/api2/test_420_smb.py
tests/api2/test_430_smb_sharesec.py

These endpoints wrap around smb.sharesec and provide a more
consistent and simpler wrapper around the SMB share ACL.

NAS-122339 / 23.10 / Improve sharesec endpoint

---

tests/api2/test_200_ftp.py
tests/protocols/__init__.py
tests/protocols/ftp_proto.py

* Change defaultroot 'default' setting from False to True to match actual
* Add 'clear' of anonpath when onlyanonymous is disabled

NAS-120654 / 23.10 / Add CI tests for FTP

---

src/middlewared/middlewared/plugins/disk_/temperature.py
src/middlewared/middlewared/pytest/unit/plugins/disk/test_temperature.py

…I disks
Original PR: https://github.com/truenas/middleware/pull/11513
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122313

NAS-122313 / 22.12.4 / Fix `disk.read_sata_or_sas_disk_temps` only working properly with SCS… (by themylogin)

---

tests/api2/test_200_ftp.py

Trap both EOFError and connection error.

NAS-122492 / 23.10 / Nas 122492

---

src/middlewared/middlewared/plugins/enclosure_/nvme.py
src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/failover_/detect_enclosure.py
src/middlewared/middlewared/plugins/failover_/internal_interface.py
src/middlewared/middlewared/plugins/ipmi_/lan.py
src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/plugins/truenas.py

Current model name was decided against so it was changed. This fixes the f-series platform models.

NAS-122454 / 23.10 / fix f-series model

---

src/middlewared/middlewared/scripts/configure_fips.py

This prevents upgrades and fresh installations.

NAS-122587 / 23.10 / fix IndexError crash in configure_fips.py

---

src/middlewared/middlewared/plugins/failover_/datastore.py

#
#
#
We had a safeguard in place that prevented this scenario but it was lost in commit: e2afcdec6ee89e7849168db89ee3ff9f5ac6bcaf (which also fixed an insidious HA db replication issue). Also note that I had to do this in `failover.datastore.receive` since the current versions of bluefin have this method and would prevent this situation without having to deal with the ENOMETHOD dance.

NAS-122693 / 23.10 / fix replication database when alembic revisions dont match

---

src/middlewared/middlewared/plugins/ipmi_/lan.py

Without the `--verbose` flag, the vlan information is not displayed. This adds that flag and also ensures that we return booleans and/or integers based on the values that are returned from the command.
(i.e. if value is "no", we'll return False or if the value is '2', will return 2 etc)
This is needed for webUI team.

NAS-122752 / 23.10 / ensure vlan info is returned in ipmi.lan.query

---

src/middlewared/middlewared/plugins/vm/supervisor/supervisor.py

Change the VM manager to perserve the UEFI variables when updating the VM data in libvirt.  This adds a new argument to undefine_domain for when update_domain is updating the domain's xml to perserve the NVRAM contents.  Also change update_domain to move the NVRAM file when the domain is renamed, to preserve its contents.
This also changes undefine_domain to use libvirt's functionality to remove the NVRAM storage.

NAS-121605 Don't delete UEFI vars when updating VM data

---

src/middlewared/middlewared/plugins/vm/pci.py

This is way too complicated for what it does. We can gather this information using pyudev (python bindings to udev database) instead of subprocessing in the main event loop. Furthermore, caching this information doesn't really make sense because, in theory, certain pci devices are hot-pluggable. This is fast enough by itself that we don't need to cache the information.
The returned data is the exact same so there is no change in functionality or behavior.
Original PR: https://github.com/truenas/middleware/pull/11624
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122817

NAS-122817 / 22.12.4 / simplify and improve vm.device.get_pci_devices (by yocalebo)

---

src/middlewared/middlewared/restful.py

If a consumer of our REST API sends us json formatted data that is incorrect we crash here:
```
File "/usr/lib/python3/dist-packages/middlewared/restful.py", line 524, in on_method
return await do(method, req, resp, authenticated_credentials, *args, **kwargs)
File "/usr/lib/python3/dist-packages/middlewared/restful.py", line 669, in do
request_body = await req.json()
File "/usr/lib/python3/dist-packages/aiohttp/web_request.py", line 614, in json
return loads(body)
File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, …
```

NAS-122869 / 23.10 / Better REST error message

---

src/middlewared/middlewared/plugins/activedirectory_/dns.py

Don't raise exception on addresses that don't pass criteria.

NAS-122933 / 23.10 / Support dual-homed servers

---

src/middlewared/middlewared/plugins/vm/pci.py

With recent improvements to PCI devices we had changed the return type of `vm.device.passthrough_device` which resulted in an error when creating a PCI device.
Make sure we maintain backwards compatibility with the API.

NAS-123040 / 23.10 / Fix creating PCI device

---

src/middlewared/middlewared/plugins/vm/pci.py

With recent improvements to PCI devices we had changed the return type of `vm.device.passthrough_device` which resulted in an error when creating a PCI device.
Make sure we maintain backwards compatibility with the API.
Original PR: https://github.com/truenas/middleware/pull/11679
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123040

NAS-123040 / 22.12.4 / Fix creating PCI device (by Qubad786)

---

src/middlewared/middlewared/plugins/account.py
src/middlewared/middlewared/plugins/failover_/datastore.py
tests/api2/test_user_admin.py

git cherry-pick -x 54737d9d3c625c59a3ab4597a2d9f7142ceb81d9
git cherry-pick -x edda10d715859e745f51ccedfbabb54894625f86
Original PR: https://github.com/truenas/middleware/pull/11682
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122863

NAS-122863 / 22.12.4 / Generate passwd and shadow files after setting up the local administrator (by themylogin)

---

src/middlewared/middlewared/plugins/gluster_linux/local_events.py
src/middlewared/middlewared/webhooks/cluster_events.py

There may be need in future to pass sensitive info through this interface, and it's easier to make payloads private now than in future after Cobia is released.

NAS-123062 / 23.10 /  Encrypt gluster localevents payloads 

---

src/middlewared/middlewared/plugins/failover_/nftables.py

2 problems noticed.
- the firewall rule that blocks traffic from VIP (gets set on the standby controller) wasn't being removed on a MASTER failover event
- calling `failover.firewall.drop_all` would produce duplicate entries in the `INPUT` chain
To resolve both scenarios, I flush all rules in the `INPUT` chain. This fixes the above scenarios and, more importantly, allows apps to function properly with the VIP when hostNetworking is enabled.

NAS-123022 / 23.10 / flush "INPUT" chain in failover.firewall methods

---

src/middlewared/middlewared/plugins/failover_/nftables.py

2 problems noticed.
- the firewall rule that blocks traffic from VIP (gets set on the standby controller) wasn't being removed on a MASTER failover event
- calling `failover.firewall.drop_all` would produce duplicate entries in the `INPUT` chain
To resolve both scenarios, I flush all rules in the `INPUT` chain. This fixes the above scenarios and, more importantly, allows apps to function properly with the VIP when hostNetworking is enabled.
Original PR: https://github.com/truenas/middleware/pull/11690
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123022

NAS-123022 / 22.12.4 / flush "INPUT" chain in failover.firewall methods (by yocalebo)

---

src/middlewared/middlewared/plugins/failover.py

A few problems:
- we're restarting Kubernetes and kuberouter services on the standby which shouldn't ever be done
- we're looking for 'webshell' service which no longer exists
Original PR: https://github.com/truenas/middleware/pull/11692
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123068

NAS-123068 / 22.12.4 / improve and fix service_remote and call_remote (by yocalebo)

---

.github/workflows/lint.yml

It will say if
```
+src/middlewared/middlewared/role.py:71:1: A001 variable "id" is shadowing a python builtin
```

NAS-123088 / 23.10 / Use  flake8-builtins

---

src/middlewared/middlewared/plugins/zettarepl.py

… main loop
Original PR: https://github.com/truenas/middleware/pull/11703
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123109

NAS-123109 / 22.12.4 / Fix `zettarepl.target_unmatched_snapshots` running `list_datasets` in… (by themylogin)

---

src/middlewared/middlewared/plugins/ups.py

This commit adds changes to not spam middleware logs again and again if the error has already been logged once.

NAS-123089 / 23.10 / Do not spam upsd errors

---

src/middlewared/middlewared/plugins/crypto_/certificate_authorities.py
src/middlewared/middlewared/plugins/crypto_/certificates.py
src/middlewared/middlewared/plugins/crypto_/key_utils.py

This PR adds changes to reflect the newer EC curve default which we are using.

NAS-123083 / 23.10 / Update default EC Curve references

---

src/middlewared/middlewared/plugins/ipmi_/lan.py

On the f-series (F60 at least), when adding the `--verbose` flag to the underlying ipmi command, return code is always 1 even though the correct output is given. Since this endpoint is actually called in the network settings page, we need to ensure we don't crash here because the webUI makes a call here when the user browses to that webpage. This means, if ipmi crashes, they can't alter any network settings.
Check to see if stderr is actually given and log an error with that information or check to ensure that there is stdout before trying to parse anything. I'm backporting this to the stable/bluefin branch because, in theory, this doesn't actually relate to the f-series platform but could affect any system.

NAS-123211 / 23.10 / fix ipmi.lan.query crash on f-series

---

src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
src/middlewared/middlewared/plugins/reporting/realtime_reporting/ifstat.py

Following problems were observed:
1. Some graphs missing vertical labels
2. Missing identifier in titles
3. UI not able to accommodate more then 3000 data points in the UI graphs
4. Network realtime reporting had different units
The problems observed were addressed and other points which had been raised were hashed out with UI team.

NAS-123210 / 23.10 / Fixes to reporting API

---

src/middlewared/middlewared/plugins/system/product.py

End url looks like `https://www.truenas.com/docs/scale/scale23.10/#23100` (for example)

NAS-123240 / 23.10 / add final url for release notes

---

cluster-tests/init_gluster.py
src/middlewared/middlewared/plugins/cluster_linux/ctdb_event.py
src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py
src/middlewared/middlewared/plugins/cluster_linux/management.py

Aggregate all relevant cluster info into single endpoint.

NAS-123239 / 23.10 / Add cluster.management.summary endpoint for TC

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

CTDBD keeps in in-memory version of the nodes file. It's possible that administrators may rashly decide to manually edit this file without going through our standard APIs. In this case the CTDB client will notice a mismatch and raise RuntimeError. We should try to gracefully-ish recover from this by forcing a reload of the nodes file and trying to get our node status again.

NAS-123277 / 23.10 / Add error handling for CTDB nodes file mismatch

---

src/middlewared/middlewared/plugins/disk_/temperature.py

This method is still trying to subprocess out to `rrdtool` but we have since removed that tool with the reporting rewrite. Use the new endpoints to query the same information.
- `disk.read_temps` is no longer needed since it was called by collectd but that program was removed
- fix imports and remove unused modules
- fix `disk.temperature_agg`

NAS-123330 / 24.04 / fix crash in disk.temperature_agg

---

src/middlewared/middlewared/plugins/disk_/temperature.py

This method is still trying to subprocess out to `rrdtool` but we have since removed that tool with the reporting rewrite. Use the new endpoints to query the same information.
- `disk.read_temps` is no longer needed since it was called by collectd but that program was removed
- fix imports and remove unused modules
- fix `disk.temperature_agg`
Original PR: https://github.com/truenas/middleware/pull/11760
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123330

NAS-123330 / 23.10 / fix crash in disk.temperature_agg (by yocalebo)

---

src/middlewared/middlewared/plugins/system/product.py

Now that we've branched for Cobia, the release notes webpage will be published soon and these are the URLs that will be used.

NAS-123338 / 24.04 / change the release notes URL

---

src/middlewared/middlewared/plugins/system/product.py

Now that we've branched for Cobia, the release notes webpage will be published soon and these are the URLs that will be used.
Original PR: https://github.com/truenas/middleware/pull/11767
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123338

NAS-123338 / 23.10 / change the release notes URL (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure.py

This adds ES102S enclosure support to our product. I had to change some logic because this enclosure seems to enumerate disk slot directories starting at 1 instead of 0. Every other enclosure (including head-units) that we sell enumerate starting at 0 so this exposed the fact that our logic was flawed and we would be off by 1 when mapping the disks to their respective enclosure slots. I also noticed some pretty severe inefficiencies while I was here. We are parsing stdout for the enclosure and for each line in the output, we were iterating every enclosure disk slot directory in procfs and opening/closing files.
Fixes and improvements I've made here:
- do not iterate every enclosure slot dir for every line of stdout for the enclosure (we just skip the disk slot element types now)
- add a …

NAS-122711 / 24.04 / add ES102S enclosure support

---

src/middlewared/middlewared/plugins/enclosure.py

This adds ES102S enclosure support to our product. I had to change some logic because this enclosure seems to enumerate disk slot directories starting at 1 instead of 0. Every other enclosure (including head-units) that we sell enumerate starting at 0 so this exposed the fact that our logic was flawed and we would be off by 1 when mapping the disks to their respective enclosure slots. I also noticed some pretty severe inefficiencies while I was here. We are parsing stdout for the enclosure and for each line in the output, we were iterating every enclosure disk slot directory in procfs and opening/closing files.
Fixes and improvements I've made here:
- do not iterate every enclosure slot dir for every line of stdout for the enclosure (we just skip the disk slot element types now)
- add a …

NAS-122711 / 23.10 / add ES102S enclosure support (by yocalebo)

---

src/middlewared/middlewared/plugins/account_/2fa.py

This PR adds changes to allow user to unset his 2fa secret if 2fa is disabled globally.

NAS-123440 / 24.04 / Allow user to unset his 2fa secret

---

src/middlewared/middlewared/plugins/account_/2fa.py

This PR adds changes to allow user to unset his 2fa secret if 2fa is disabled globally.
Original PR: https://github.com/truenas/middleware/pull/11807
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123440

NAS-123440 / 23.10 / Allow user to unset his 2fa secret (by sonicaj)

---

cluster-tests/requirements.txt
cluster-tests/run-cluster-tests.py

Adding requirements file and supporting passing pytest path to the test runner script will help us simplify the jenkins configuration for our clustering test runner.

NAS-123354 / 22.12.4 / Update cluster-tests for unified releng pipeline

---

src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_stats_func.py

We have util functions which determine reporting realtime statistics and unit tests have been added to test the reporting in question to make sure it is accurate.

NAS-123074 / 24.04 / Add unit tests for realtime statistics

---

src/middlewared/middlewared/alert/source/enclosure_status.py

Fix regression introduced in 0e7e710f1367d26b4d178acec1b264bd844db6b5

NAS-123496 / 24.04 / fix regression in enclosure alert

---

src/middlewared/middlewared/alert/source/enclosure_status.py

Fix regression introduced in 0e7e710f1367d26b4d178acec1b264bd844db6b5
Original PR: https://github.com/truenas/middleware/pull/11824
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123496

NAS-123496 / 23.10 / fix regression in enclosure alert (by yocalebo)

---

src/middlewared/middlewared/plugins/reporting/netdata/client.py

On a m60 system with 1200 disks we saw asyncio logging warnings with the request saying that the task is blocked.
The problem was occurring when we tried to load all of the content at once it blocked the event loop and breaking that in chunks solved the problem with the warning being no longer visible.

NAS-123443 / 24.04 / Handle netdata response in chunks

---

src/middlewared/middlewared/plugins/reporting/netdata/client.py

On a m60 system with 1200 disks we saw asyncio logging warnings with the request saying that the task is blocked.
The problem was occurring when we tried to load all of the content at once it blocked the event loop and breaking that in chunks solved the problem with the warning being no longer visible.
Original PR: https://github.com/truenas/middleware/pull/11809
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123443

NAS-123443 / 23.10 / Handle netdata response in chunks (by Qubad786)

---

src/middlewared/middlewared/plugins/tunables.py

git cherry-pick -x 7660742fa1f44ea287a7470dc309533ef08b95f2
git cherry-pick -x ac4431fd4224fee6f2a24cde48ad6986fd292c3b
Original PR: https://github.com/truenas/middleware/pull/11810
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123216

NAS-123216 / 22.12.4 / Do not crash on sysfs write failure (by themylogin)

---

src/middlewared/middlewared/plugins/interface/netif_linux/routing.py

This commit adds changes to safely retrieve interfaces from iproute as we have seen on some hardware (likely bad hardware) it is possible this fails sometimes so we should be safe about it when trying to retrieve the links/ifaces from iproute.

NAS-123231 / 24.04 / Safely retrieve interfaces from iproute

---

src/middlewared/middlewared/plugins/interface/netif_linux/routing.py

This commit adds changes to safely retrieve interfaces from iproute as we have seen on some hardware (likely bad hardware) it is possible this fails sometimes so we should be safe about it when trying to retrieve the links/ifaces from iproute.
Original PR: https://github.com/truenas/middleware/pull/11831
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123231

NAS-123231 / 23.10 / Safely retrieve interfaces from iproute (by sonicaj)

---

src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/failover_/remote.py

git cherry-pick -x 4ffedb4964adb2a4c45d0fcb41ce4b8fd017e437
git cherry-pick -x e0485003834b9130954f70f263d2af0ff193b6d2
Original PR: https://github.com/truenas/middleware/pull/11836
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123540

NAS-123540 / 22.12.4 / Fix failover upgrade error (by themylogin)

---

src/middlewared/middlewared/alert/source/pools.py
src/middlewared/middlewared/plugins/zfs_/zfs_events.py
tests/api2/test_pool_is_upgraded.py

* Properly handle one-shot pool alerts for boot pool

NAS-123575 / 24.04 / Don't issue "New Feature Flags Are Available for Pool" alert for the boot-pool

---

src/middlewared/middlewared/alert/source/pools.py
src/middlewared/middlewared/plugins/zfs_/zfs_events.py
tests/api2/test_pool_is_upgraded.py

* Properly handle one-shot pool alerts for boot pool
Original PR: https://github.com/truenas/middleware/pull/11876
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123575

NAS-123575 / 22.12.4 / Don't issue "New Feature Flags Are Available for Pool" alert for the boot-pool (by themylogin)

---

src/middlewared/middlewared/alert/source/pools.py
src/middlewared/middlewared/plugins/zfs_/zfs_events.py
tests/api2/test_pool_is_upgraded.py

* Properly handle one-shot pool alerts for boot pool
Original PR: https://github.com/truenas/middleware/pull/11876
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123575

NAS-123575 / 23.10 / Don't issue "New Feature Flags Are Available for Pool" alert for the boot-pool (by themylogin)

---

tests/api2/test_200_ftp.py

The output of the ftpwho command changed which resulted in test failures. Changed to a json formatted output and modified the processing accordingly.

NAS-123605 / 24.04 / Update ftp IP connection test

---

tests/api2/test_200_ftp.py

The output of the ftpwho command changed which resulted in test failures. Changed to a json formatted output and modified the processing accordingly.
Original PR: https://github.com/truenas/middleware/pull/11894
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123605

NAS-123605 / 23.10 / Update ftp IP connection test (by mgrimesix)

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

If clustering is enabled and brick hosted on a pool, prevent it from being exported.

NAS-123491 / 24.04 / Prevent pool export if hosting gluster volume

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

If clustering is enabled and brick hosted on a pool, prevent it from being exported.
Original PR: https://github.com/truenas/middleware/pull/11812
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123491

NAS-123491 / 23.10 / Prevent pool export if hosting gluster volume (by anodos325)

---

src/middlewared/middlewared/plugins/interface/netif_linux/address/mixin.py

Move the ipv4/v6 address into a single for loop removing an unnecessary 2nd call to `ipr.dump`.

NAS-123674 / 24.04 / optimize addresses property in AddressMixin

---

src/middlewared/middlewared/plugins/enclosure.py
src/middlewared/middlewared/plugins/enclosure_/fseries_drive_identify.py

This was missed when I initially added the new F series product. This is very similar to what we do with the r30.

NAS-123612 / 24.04 / add fseries drive identification logic

---

src/middlewared/middlewared/plugins/enclosure.py
src/middlewared/middlewared/plugins/enclosure_/fseries_drive_identify.py

This was missed when I initially added the new F series product. This is very similar to what we do with the r30.
Original PR: https://github.com/truenas/middleware/pull/11936
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123612

NAS-123612 / 23.10 / add fseries drive identification logic (by yocalebo)

---

src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/restful.py
tests/api2/test_auth_token.py

…erminated
Original PR: https://github.com/truenas/middleware/pull/11905
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123515

NAS-123515 / 22.12.4 / Destroy all tokens created or used in a session when it is forcibly t… (by themylogin)

---

src/middlewared/middlewared/plugins/auth.py
src/middlewared/middlewared/restful.py
tests/api2/test_auth_token.py

…erminated
Original PR: https://github.com/truenas/middleware/pull/11905
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123515

NAS-123515 / 23.10 / Destroy all tokens created or used in a session when it is forcibly t… (by themylogin)

---

cluster-tests/tests/gluster/test_volume.py

Verify we prevent pool export while we're clustered.

NAS-123571 / 24.04 / Add test for pool export behavior when clustered

---

cluster-tests/tests/gluster/test_volume.py

Verify we prevent pool export while we're clustered.
Original PR: https://github.com/truenas/middleware/pull/11956
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123571

NAS-123571 / 23.10 / Add test for pool export behavior when clustered (by anodos325)

---

src/middlewared/middlewared/plugins/account.py

This is calling a bunch of blocking I/O in the main event loop. It's just easier to convert the entire method to synchronous.

NAS-123751 / 24.04 / fix update_sshpubkey

---

src/middlewared/middlewared/plugins/account.py

This is calling a bunch of blocking I/O in the main event loop. It's just easier to convert the entire method to synchronous.
Original PR: https://github.com/truenas/middleware/pull/11966
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123751

NAS-123751 / 23.10 / fix update_sshpubkey (by yocalebo)

---

src/middlewared/middlewared/plugins/interface/netif_linux/address/mixin.py

This same fix was already applied in our routing plugin but also needs to be applied here. This is considered an edge-case crash because we've only seen it twice in the wild. Checking upstream source implies that we should retry on this error since it's not considered fatal.

NAS-123763 / 24.04 / fix edge-case crash in AddressMixin

---

tests/api2/test_rsync_ssh_authentication.py

(cherry picked from commit d5290beefe9fe7d7243ff38098936530721ea565)

NAS-123716 / 22.12.4 / Fix rsync tests

---

src/middlewared/middlewared/plugins/vm/devices/display.py
src/middlewared/middlewared/plugins/vm/vm_display_info.py

This PR adds changes to not ask for a password and neither add it to get parameters of the request uri of a display device's web uri.

NAS-123722 / 24.04 / Do not ask for password when giving web uri for a display device

---

src/middlewared/middlewared/plugins/nfs.py
src/middlewared/middlewared/validators.py

* NotMatch validator can avoid complicated regex when writing exclude patterns
* Added explanation of NFS share hostname validation to provide the user with a human readable message.

NAS-123830 / 24.04 / Add NotMatch validator and NFS share validation explanation

---

src/middlewared/middlewared/plugins/kubernetes_linux/backup.py
tests/api2/test_026_kubernetes_backup_chart_releases.py

There is an issue related to snapshot duplication validation where incorrect keys are being used for validation. This is resulting in inaccurate validation of snapshot duplication.
In order to address this bug and ensure accurate validation, necessary changes have been made. Additionally, an integration test has been added to thoroughly test this issue and verify the solution.

NAS-123823 / 24.04 / Fix kubernetes backup name validation

---

src/middlewared/middlewared/plugins/kubernetes_linux/backup.py
tests/api2/test_026_kubernetes_backup_chart_releases.py

There is an issue related to snapshot duplication validation where incorrect keys are being used for validation. This is resulting in inaccurate validation of snapshot duplication.
In order to address this bug and ensure accurate validation, necessary changes have been made. Additionally, an integration test has been added to thoroughly test this issue and verify the solution.
Original PR: https://github.com/truenas/middleware/pull/12002
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123823

NAS-123823 / 23.10 / Fix kubernetes backup name validation (by Qubad786)

---

src/middlewared/middlewared/plugins/reporting/events.py

We saw a rogue case where a timeout error happened for a user when trying retrieve netdata metrics which resulted in realtime event source erroring out.
This error could not be reproduced but it was agreed with Caleb that we can have at least a retry logic in place to account for such weird cases in realtime reporting event source.

NAS-123614 / 24.04 / Have a retry mechanism in realtime event source

---

src/middlewared/middlewared/plugins/reporting/events.py

We saw a rogue case where a timeout error happened for a user when trying retrieve netdata metrics which resulted in realtime event source erroring out.
This error could not be reproduced but it was agreed with Caleb that we can have at least a retry logic in place to account for such weird cases in realtime reporting event source.
Original PR: https://github.com/truenas/middleware/pull/12000
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123614

NAS-123614 / 23.10 / Have a retry mechanism in realtime event source (by Qubad786)

---

src/middlewared/middlewared/plugins/rsync.py
tests/api2/test_rsync_ssh_authentication.py

with SSH key in user home directory.
Add `ssh_keyscan` option to automatically run `ssh_keyscan` when setting up a rsync task with SSH key in user home directory.
Original PR: https://github.com/truenas/middleware/pull/12006
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123733

NAS-123733 / 23.10-RC.1 / Check for host keys in user home directory when setting up a rsync task (by themylogin)

---

src/middlewared/middlewared/plugins/rsync.py
tests/api2/test_rsync_ssh_authentication.py

with SSH key in user home directory.
Add `ssh_keyscan` option to automatically run `ssh_keyscan` when setting up a rsync task with SSH key in user home directory.
Original PR: https://github.com/truenas/middleware/pull/12006
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123733

NAS-123733 / 23.10 / Check for host keys in user home directory when setting up a rsync task (by themylogin)

---

src/middlewared/middlewared/plugins/usage.py

Quiet option for NFS exports was removed.

NAS-123968 / 24.04 / Fix usage plugin

---

src/middlewared/middlewared/alert/source/license_status.py

On our M60 with 12x ES102 JBODs (with ~1.2k+ hard drives), I was noticing that `failover.get_ips` was taking > 46 seconds to return.
I gathered flame graphs of the running middleware process and noticed that `alert/license_status.py` line 81 (`enclosure.query`) was the spot where it was blocked. This doesn't surprise me because that's the old enclosure code that wasn't written in a way to be efficient. It's the exact opposite of efficient.
I changed to using `enclosure2.query` which is the new enclosure code that was written exclusively with speed/efficiency in mind and `failover.get_ips` now takes ~0.4 seconds to return.
The only logical conclusion that I can come up with is that our alert was calling such an inefficient method every 60 seconds that it was slowing down the entire main …

NAS-123981 / 23.10 / dramatically improve alert/license_status.py (by yocalebo)

---

src/middlewared/middlewared/plugins/cloud/crud.py
src/middlewared/middlewared/plugins/cloud_backup/crud.py
src/middlewared/middlewared/plugins/cloud_backup/sync.py
tests/api2/test_cloud_backup.py

This PR provides the ability to specify a zvol as a source for Restic cloud backup.
Data consistency is ensured by taking a temporary snapshot of said zvol before the operation and using its clone as Restic data source.

NAS-123082 / 24.04 / Cloud backup of zvols

---

src/freenas/usr/local/libexec/freenas-debug/system/system.sh
src/middlewared/middlewared/main.py
src/middlewared/middlewared/service.py

git cherry-pick -x 2982c2cfa39921917b646b8e254a050765526e38
git cherry-pick -x cad8a91fbfb438d442b335c090c8083804ca94b2
Original PR: https://github.com/truenas/middleware/pull/12096
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124070

NAS-124070 / 22.12.4 / Remove websocket message logging as it leaks private data (by themylogin)

---

tests/api2/test_420_smb.py

This is an initial step to improving the SMB API tests. Many of the removed items have been superseded by more explicit / better testing.

NAS-124096 / 24.04 / Remove legacy / problematic SMB tests

---

tests/api2/test_draid_record_and_block_size.py

On HA VMs we don't want draid tests to run because we don't have enough disks and also we don't want to use `call` at module level because in HA vms at the time these are loaded the IP is not set so `call` is destined to fail.
Skip the module if the tests are running on HA and use a fixture instead which determines if sufficient disks are available or not instead of making that call on module level.

NAS-124115 / 24.04 / Fix draid integration test on HA vms

---

tests/api2/test_draid_record_and_block_size.py

On HA VMs we don't want draid tests to run because we don't have enough disks and also we don't want to use `call` at module level because in HA vms at the time these are loaded the IP is not set so `call` is destined to fail.
Skip the module if the tests are running on HA and use a fixture instead which determines if sufficient disks are available or not instead of making that call on module level.
Original PR: https://github.com/truenas/middleware/pull/12106
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124115

NAS-124115 / 23.10 / Fix draid integration test on HA vms (by Qubad786)

---

src/middlewared/middlewared/plugins/failover_/detect_enclosure.py

Seen in a users debug (for an unrelated issue) that was running TrueNAS on non-iX enterprise hardware. This just ensures that we only run this function on iX sold appliances.

NAS-124316 / 24.04 / dont run enclosure.detect on non-iX hardware

---

src/middlewared/middlewared/plugins/failover_/detect_enclosure.py

Seen in a users debug (for an unrelated issue) that was running TrueNAS on non-iX enterprise hardware. This just ensures that we only run this function on iX sold appliances.
Original PR: https://github.com/truenas/middleware/pull/12175
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124316

NAS-124316 / 23.10 / dont run enclosure.detect on non-iX hardware (by yocalebo)

---

tests/api2/test_470_system.py

NAS-124328 / 24.04 / Fix missing ip following removal of dev_test

---

src/middlewared/middlewared/plugins/smb_/passdb.py

Initial testing was performed with an upper-case netbios name, which didn't cause issues because the passdb backend forces the domain to uppercase. Unfortunately, this led to false-positives when the netbios name was stored as lowercase in the TrueNAS configuration. This commit switches to using the case-insentive operator for filtering and makes the error message more verbose.

NAS-124334 / 24.04 / Make passdb reinit check use case-insensitive filter

---

src/middlewared/middlewared/plugins/smb_/passdb.py

Initial testing was performed with an upper-case netbios name, which didn't cause issues because the passdb backend forces the domain to uppercase. Unfortunately, this led to false-positives when the netbios name was stored as lowercase in the TrueNAS configuration. This commit switches to using the case-insentive operator for filtering and makes the error message more verbose.
Original PR: https://github.com/truenas/middleware/pull/12193
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124334

NAS-124334 / 23.10 / Make passdb reinit check use case-insensitive filter (by anodos325)

---

tests/api2/test_470_system.py

Also some flake8
Original PR: https://github.com/truenas/middleware/pull/12188
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124328

NAS-124328 / 23.10 / Fix missing ip following removal of dev_test (by bmeagherix)

---

tests/api2/test_261_iscsi_cmd.py

This was inspired by some recent discussion on the SCST mailing list.

NAS-124352 / 24.04 / Add iSCSI initiator group test

---

tests/api2/test_261_iscsi_cmd.py

This was inspired by some recent discussion on the SCST mailing list.
Original PR: https://github.com/truenas/middleware/pull/12203
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124352

NAS-124352 / 23.10 / Add iSCSI initiator group test (by bmeagherix)

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

Users are seeing ix-zfs.service take many 10's of minutes to complete while sometimes not even completing after letting it sit for many hours. This is probably an esoteric zfs/hardware problem for the extreme cases but we're really hurting ourselves by doing a bunch of unnecessary zpool calls. This limits the amount of zpool/zfs I/O that is performed in the `pool.import_on_boot` method since it's called in the `ix-zfs.service` systemd unit file which blocks boot-up from completing. Please note that most of the lines changed here are actually me documenting this madness since there were none and a small part of my soul was stolen from me when investigating this area of our code. P.S. I've added logging to _EVERYTHING_. Troubleshooting this is a nightmare and using `job.set_progress` is …

NAS-123504 / 24.04 / fix ix-zfs.service

---

src/middlewared/middlewared/plugins/pool_/import_pool.py

Users are seeing ix-zfs.service take many 10's of minutes to complete while sometimes not even completing after letting it sit for many hours. This is probably an esoteric zfs/hardware problem for the extreme cases but we're really hurting ourselves by doing a bunch of unnecessary zpool calls. This limits the amount of zpool/zfs I/O that is performed in the `pool.import_on_boot` method since it's called in the `ix-zfs.service` systemd unit file which blocks boot-up from completing. Please note that most of the lines changed here are actually me documenting this madness since there were none and a small part of my soul was stolen from me when investigating this area of our code. P.S. I've added logging to _EVERYTHING_. Troubleshooting this is a nightmare and using `job.set_progress` is …

NAS-123504 / 23.10 / fix ix-zfs.service (by yocalebo)

---

src/middlewared/middlewared/etc_files/scst.conf.mako
tests/api2/test_261_iscsi_cmd.py

When specified as a portal address, do not write Virtual IP address to `/etc/scst.conf` when ALUA is enabled on a HA system. 
Instead each node will use the corresponding node specific IP.
Also, add test `test_28_portal_access` to ensure correct operation on both regular and HA/ALUA systems.
Finally, correct an incorrect indentation in `test_27_initiator_group` (added yesterday).

NAS-124391 / 24.04 / Virtual IP portal address for iSCSI ALUA target not applied correctly

---

tests/api2/test_420_smb.py

This PR simplifies many test cases in the test_420_smb file, removes various sleep() calls, and replaces calls to midclt via SSH with websocket client calls.

NAS-124388 / 24.04 / Refactor and simplify test_420_smb

---

src/middlewared/middlewared/etc_files/scst.conf.mako
tests/api2/test_261_iscsi_cmd.py

When specified as a portal address, do not write Virtual IP address to `/etc/scst.conf` when ALUA is enabled on a HA system. 
Instead each node will use the corresponding node specific IP.
Also, add test `test_28_portal_access` to ensure correct operation on both regular and HA/ALUA systems.
Finally, correct an incorrect indentation in `test_27_initiator_group` (added yesterday).
Original PR: https://github.com/truenas/middleware/pull/12218
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124391

NAS-124391 / 23.10 / Virtual IP portal address for iSCSI ALUA target not applied correctly (by bmeagherix)

---

src/middlewared/middlewared/apidocs/templates/websocket/query.md
src/middlewared/middlewared/plugins/datastore/read.py
src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
src/middlewared/middlewared/utils/__init__.py

This adds minor API improvement to filter_list to allow selected items from nested dicts. During testing it was also determined that eliminating the lambda functions from op maps yielded consistent minor performance improvement.

NAS-124418 / 24.04 / Add ability to select items from nested dict

---

src/middlewared/middlewared/rclone/remote/azureblob.py
src/middlewared/middlewared/validators.py

…ally cryptic)
Original PR: https://github.com/truenas/middleware/pull/12227
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124409

NAS-124409 / 23.10 / Validation for Azureblob account name (rclone error message can be re… (by themylogin)

---

src/middlewared/middlewared/plugins/vm/clone.py

When cloning a VM which has a display device where no password is configured (which was allowed in earlier versions of SCALE) - cloning the VM fails with a traceback as we are not able to clone the display device in question.
Properly validate the VM before cloning ensuring that it's display devices have a password configured and raise a validation error before trying to clone the VM.

NAS-124297 / 24.04 / Add empty password validation when cloning a VM

---

tests/api2/test_435_smb_registry.py

Simplify test cases, speed up tests, and convert REST to WS calls.
Original PR: https://github.com/truenas/middleware/pull/12247
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124468

NAS-124468 / 23.10.0 / Simplify SMB registry tests (by anodos325)

---

tests/api2/test_420_smb.py

Create temporary user with randomized password for during of test
module, and ensure that SMB server state is returned to defaults
post-test.

NAS-124491 / 24.04 / Remove shareuser from SMB CI test

---

src/middlewared/middlewared/plugins/tdb/wrapper.py

Python tracebacks in middlewared log in recent nightlies indicates there's an edge case where close() method on a tdb handle is failing with EBADF. This occurs because once a handle is closed we set the value of its associated O_PATH fd to -1. This commit changes the logic for closing a TDB handle in the following manner:
* If O_PATH fd is -1 and the tdb handle is None then we know handle is closed and just return early in the close method.
* self.hdl (the actual TDB handle) is now set to None after it is closed so that we free up resources earlier, and protect against reuse of an already-closed handle.

NAS-124494 / 24.04 / Add more robust checks before closing tdb handle

---

src/middlewared/middlewared/plugins/tdb/wrapper.py

Python tracebacks in middlewared log in recent nightlies indicates there's an edge case where close() method on a tdb handle is failing with EBADF. This occurs because once a handle is closed we set the value of its associated O_PATH fd to -1. This commit changes the logic for closing a TDB handle in the following manner:
* If O_PATH fd is -1 and the tdb handle is None then we know handle is closed and just return early in the close method.
* self.hdl (the actual TDB handle) is now set to None after it is closed so that we free up resources earlier, and protect against reuse of an already-closed handle.
Original PR: https://github.com/truenas/middleware/pull/12263
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124494

NAS-124494 / 23.10.0 / Add more robust checks before closing tdb handle (by anodos325)

---

src/middlewared/middlewared/plugins/enclosure_/map2.py
src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py

Slowing working on this rewrite and noticed on an internal R50B, this wasn't mapping appropriately. This fixes both problems.

NAS-124499 / 24.04 / fix enclosure2 mapping code

---

src/middlewared/middlewared/plugins/enclosure.py
src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/identification.py
src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_identification.py
src/middlewared/middlewared/utils/license.py

NAS-124567 / 24.04 / rename ES102S to ES102G2

---

src/middlewared/middlewared/plugins/enclosure.py
src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/identification.py
src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_identification.py
src/middlewared/middlewared/utils/license.py

Original PR: https://github.com/truenas/middleware/pull/12289
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124567

NAS-124567 / 23.10.0 / rename ES102S to ES102G2 (by yocalebo)

---

src/middlewared/middlewared/plugins/enclosure.py
src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
src/middlewared/middlewared/plugins/enclosure_/identification.py
src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_identification.py
src/middlewared/middlewared/utils/license.py

Original PR: https://github.com/truenas/middleware/pull/12289
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124567

NAS-124567 / 23.10.1 / rename ES102S to ES102G2 (by yocalebo)

---

src/middlewared/middlewared/plugins/smb.py

Homes share may be removed by either updating the share so that home=False or deleting the share. After these changes have been committed, we need to rebuild our global SMB config to remove the "obey pam restrictions" parameter.
Original PR: https://github.com/truenas/middleware/pull/12290
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124575

NAS-124575 / 23.10.1 / Cleanup global settings after removing homes share (by anodos325)

---

src/middlewared/middlewared/apidocs/templates/websocket/query.md
src/middlewared/middlewared/plugins/datastore/read.py
src/middlewared/middlewared/pytest/unit/test_schema.py
src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
src/middlewared/middlewared/schema/dict_schema.py
src/middlewared/middlewared/service/crud_service.py
src/middlewared/middlewared/utils/__init__.py
src/middlewared/middlewared/validators.py

This helps provide users more useful ways to slice-and-dice large amounts of data provided via APIs for reporting purposes. The commit also extends our CI and validation to cover query-options.

NAS-124616 / 24.04 / Add ability to perform SELECT AS through query-options

---

src/middlewared/middlewared/plugins/smb.py

Raise ValidationError if a different exists that has `home` set to True.

NAS-124364 / 24.04 / Fix check for existing home directory

---

src/middlewared/middlewared/apidocs/templates/websocket/query.md

Add some example SQL SELECT statements and how to translate that into our query-options and query-filters.

NAS-124622 / 24.04 / Expand query-filters and query-options docs

---

src/middlewared/middlewared/plugins/cluster_linux/management.py

Force RFC-1918 addresses for inter-node traffic on TrueNAS clusters.

NAS-124672 / 24.04 / Add validator for CTDB private IP addresses

---

src/middlewared/middlewared/plugins/failover.py

This commit fixes an issue where we tried to unlock all the passphrase encrypted datasets on failover each time we imported a pool but that was bound to fail as pools which had not imported at that time would not be found and would obviously result in erroneous logging. So changes have been made to only unlock datasets of pool which has been imported at the time.

NAS-124596 / 24.04 / Only unlock datasets which are requested on failover

---

src/middlewared/middlewared/plugins/failover.py

This commit fixes an issue where we tried to unlock all the passphrase encrypted datasets on failover each time we imported a pool but that was bound to fail as pools which had not imported at that time would not be found and would obviously result in erroneous logging. So changes have been made to only unlock datasets of pool which has been imported at the time.
Original PR: https://github.com/truenas/middleware/pull/12339
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124596

NAS-124596 / 23.10.0 / Only unlock datasets which are requested on failover (by sonicaj)

---

src/middlewared/middlewared/etc_files/scst.conf.mako
src/middlewared/middlewared/migration/0003_iscsi_vendor.py
src/middlewared/middlewared/plugins/audit/audit.py
src/middlewared/middlewared/plugins/cloud_sync.py
src/middlewared/middlewared/plugins/cloud_sync_/crud.py
src/middlewared/middlewared/plugins/etc.py
src/middlewared/middlewared/plugins/iscsi_/extents.py
src/middlewared/middlewared/plugins/iscsi_/global_linux.py
src/middlewared/middlewared/plugins/network_/global_config.py
src/middlewared/middlewared/plugins/nfs.py
src/middlewared/middlewared/plugins/pool_/dataset_encryption_info.py
src/middlewared/middlewared/plugins/pool_/dataset_encryption_lock.py
src/middlewared/middlewared/plugins/smb.py
src/middlewared/middlewared/plugins/smb_/registry_global.py
src/middlewared/middlewared/plugins/smb_/sharesec.py
src/middlewared/middlewared/plugins/usage.py
src/middlewared/middlewared/plugins/vmware.py
src/middlewared/middlewared/plugins/zfs_/dataset_encryption.py
src/middlewared/middlewared/service/sharing_service.py
tests/api2/test_sharing_service_encrypted_dataset_info.py

This PR adds various changes to optimize retrieval of shares/tasks after a discussion with @anodos325.
(TODO: Fill this in)

NAS-124598 / 24.04 / Optimize retrieving shares/tasks information

---

src/middlewared/middlewared/etc_files/scst.conf.mako
src/middlewared/middlewared/migration/0003_iscsi_vendor.py
src/middlewared/middlewared/plugins/cloud_sync.py
src/middlewared/middlewared/plugins/cloud_sync_/crud.py
src/middlewared/middlewared/plugins/etc.py
src/middlewared/middlewared/plugins/iscsi_/extents.py
src/middlewared/middlewared/plugins/iscsi_/global_linux.py
src/middlewared/middlewared/plugins/network_/global_config.py
src/middlewared/middlewared/plugins/nfs.py
src/middlewared/middlewared/plugins/pool_/dataset_encryption_info.py
src/middlewared/middlewared/plugins/pool_/dataset_encryption_lock.py
src/middlewared/middlewared/plugins/smb.py
src/middlewared/middlewared/plugins/smb_/registry_global.py
src/middlewared/middlewared/plugins/smb_/sharesec.py
src/middlewared/middlewared/plugins/usage.py
src/middlewared/middlewared/plugins/vmware.py
src/middlewared/middlewared/plugins/zfs_/dataset_encryption.py
src/middlewared/middlewared/service/sharing_service.py
tests/api2/test_sharing_service_encrypted_dataset_info.py

This PR adds various changes to optimize retrieval of shares/tasks after a discussion with @anodos325.
(TODO: Fill this in)
Original PR: https://github.com/truenas/middleware/pull/12316
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124598

NAS-124598 / 23.10.1 / Optimize retrieving shares/tasks information (by sonicaj)

---

src/middlewared/middlewared/plugins/reporting/update.py

This PR updates older endpoints we had to use the newer netdata endpoints (this change is already present in dragonfish) - so if any entity is still trying to consume these older endpoints, they will actually be able to get relevant data requested instead of erroring out because collectd/rrdcached no longer exist.
Also i was not able to locate usages in middleware for `reporting.get_data` in middleware in cobia, so that part is still a mystery as to who was consuming this endpoint.

NAS-124696 / 23.10.1 / Use newer reporting api endpoints

---

src/middlewared/middlewared/plugins/failover.py
src/middlewared/middlewared/plugins/failover_/detect_enclosure.py
src/middlewared/middlewared/plugins/failover_/internal_interface.py
src/middlewared/middlewared/plugins/network.py
src/middlewared/middlewared/plugins/truenas.py

Add h-series platform detection. Many more changes are going to be required for this platform, but this at least gets us to a point where we can install SCALE and have it be somewhat functional.

NAS-123853 / 24.04 / add h-series platform detection

---

src/middlewared/middlewared/plugins/kubernetes_linux/update.py

This commit adds changes to account for containerd socket not being ready when validating if k8s setup is complete and it can be consumed internally

NAS-124840 / 24.04 / Account for containerd not being ready

---

src/middlewared/middlewared/plugins/kubernetes_linux/update.py

This commit adds changes to account for containerd socket not being ready when validating if k8s setup is complete and it can be consumed internally
Original PR: https://github.com/truenas/middleware/pull/12399
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124840

NAS-124840 / 23.10.1 / Account for containerd not being ready (by sonicaj)

---

tests/api2/test_006_pool_and_sysds.py

This started to fail the moment this was merged upstream to openzfs: https://github.com/truenas/zfs/commit/22da5ae59fbf8902f4897c2d417f5673591cc8e7. There is a subtle but profound behavioral change with that commit. We test to make sure that we can't set `sharenfs` on the root dataset up above which is enough to test these properties. Remove the logic that fails.

NAS-124889 / 24.04 / fix failing api test

---

tests/api2/test_006_pool_and_sysds.py

This started to fail the moment this was merged upstream to openzfs: https://github.com/truenas/zfs/commit/22da5ae59fbf8902f4897c2d417f5673591cc8e7. There is a subtle but profound behavioral change with that commit. We test to make sure that we can't set `sharenfs` on the root dataset up above which is enough to test these properties. Remove the logic that fails.
Original PR: https://github.com/truenas/middleware/pull/12409
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124889

NAS-124889 / 23.10.1 / fix failing api test (by yocalebo)

---

src/middlewared/middlewared/plugins/idmap.py

The idmap plugin implicitly assumes that winbindd is running. This commit adds a wrapper around places where we're using libwbclient to perform operations and if it appears that winbindd is actually stopped, try to start it up non-silently.

NAS-124877 / 24.04 / Attempt to start winbindd if it's not running

---

src/middlewared/middlewared/plugins/kubernetes_linux/update.py

This commit adds changes to account for containerd socket not being ready when validating if k8s setup is complete and it can be consumed internally
Original PR: https://github.com/truenas/middleware/pull/12399
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124840
Original PR: https://github.com/truenas/middleware/pull/12401
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124840

NAS-124840 / 23.10.0.1 / Account for containerd not being ready (by sonicaj) (by bugclerk)

---

src/fenced/fenced/disks.py

This does exactly what is described here: https://github.com/truenas/py-nvme/pull/16 but makes the necessary changes for CORE.

NAS-124781 / 13.0 / fix inconsistent nvme reservation handling

---

src/fenced/fenced/disks.py

This does exactly what is described here: https://github.com/truenas/py-nvme/pull/16 but makes the necessary changes for CORE.
Original PR: https://github.com/truenas/middleware/pull/12420
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124781

NAS-124781 / 13.1 / fix inconsistent nvme reservation handling (by yocalebo)

---

src/middlewared/middlewared/plugins/disk_/disk_info.py
src/middlewared/middlewared/pytest/unit/plugins/disk/test_label_to_dev.py

… label is a partition
Original PR: https://github.com/truenas/middleware/pull/12424
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124782

NAS-124782 / 23.10.1 / Make `disk.label_to_dev` and `disk.label_to_disk` work for cases when… (by themylogin)

---

src/middlewared/middlewared/plugins/smb_/sharesec.py
tests/api2/test_430_smb_sharesec.py

SMB share ACLs may be modified by by SMB clients or locally outside of our APIs by intrepid administrators. Currently we periodically check whether the file has changed behind our back and update stored copies of the SMB share ACL (in our config file). The share ACL stored in DB is base64 encoded security descriptor blob from share_info.tdb.
This edge case did not have adequate test coverage and regressed after an API redesign for the cobia release.

NAS-125005 / 24.04 / Fix periodic sync of SMB share ACL with datastore

---

src/middlewared/middlewared/plugins/smb_/sharesec.py
tests/api2/test_430_smb_sharesec.py

SMB share ACLs may be modified by by SMB clients or locally outside of our APIs by intrepid administrators. Currently we periodically check whether the file has changed behind our back and update stored copies of the SMB share ACL (in our config file). The share ACL stored in DB is base64 encoded security descriptor blob from share_info.tdb.
This edge case did not have adequate test coverage and regressed after an API redesign for the cobia release.
Original PR: https://github.com/truenas/middleware/pull/12435
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125005

NAS-125005 / 23.10.1 / Fix periodic sync of SMB share ACL with datastore (by anodos325)
